mamedev/mame

hash/nes.xml
Mick & Mack as the Global Gladiators (prototype, 19930709) [ICEknight, steem69]
Mick & Mack as the Global Gladiators (prototype, 19930630) [ICEknight, steem69]
Mick & Mack as the Global Gladiators (prototype, 19930616) [ICEknight, steem69]
Mick & Mack as the Global Gladiators (prototype, 19930528) [ICEknight, steem69]
Mick & Mack as the Global Gladiators (prototype, 19930528, alt) [ICEknight, steem69]
=> nes.xml: Added five builds of an unreleased prototype.

hash/tvgogo.xml
Replaced US and EU abbreviations by USA and Europe
=> tvgogo.xml: Countries and zone full name

hash/einstein.xml
Lowercase on descriptive words like "Alt" or "Cracked"
=> einstein.xml: Metadata cleaning

hash/spectrum_cart.xml
Lowercase on descriptive words like "Alt" and "Prototype"
=> spectrum_cart.xml: Metadata cleaning

hash/vtech_storio_cart.xml
Lowercase on "cartridges" media name
=> vtech_storio_cart.xml: Lowercase on soft. list media name

hash/digiblast_cart.xml
Lowercase on software list media "cartridges" name
=> digiblast_cart.xml: Lowercase on soft. list media name

scripts/src/formats.lua, src/lib/formats/all.cpp, src/lib/formats/fs_hplif.cpp, src/lib/formats/fs_hplif.h, src/lib/formats/hp300_dsk.cpp, src/lib/formats/hp300_dsk.h
Hi,
i wanted to extract some files from old teledisk images, so i thought i add support for the LIF lifesystems + disk formats, so i can use floptool to extract the files.
=> HP LIF support for floptool

src/mame/handheld/chesskng.cpp, src/mame/mame.lst, src/mame/mess.flt
----
Chess King (Model ET-6) [Ankos, David Haywood, hap]
=> new WORKING machines: Chess King

hash/chessking_cart.xml, src/mame/handheld/chessking.cpp
new WORKING Software List additions
----
chessking_cart.xml:
chn_dic - Chinese Dictionary [David Haywood]
=> new WORKING Software List additions (Chess King)

src/mame/mame.lst, src/mame/misc/megaphx.cpp
------
YoYo Spell (prototype) [Opernet,  Recreativas.org, Museo del Recreativo]
=> new WORKING clones (YoYo Spell)

src/mame/wyse/wy50.cpp
I was using the wy50 with nabu cp/m and thought I'd try to add the beeper.  
I don't know the proper frequency of the wy50 beeper so I made a port_changed_member so you could adjust the beeper clock from the slider controls menu.
=> wy50: add beep

src/mame/mame.lst, src/mame/sanritsu/bankp.cpp
Bank Panic (Tecfri bootleg) [Eduardo Anay, Recreativas.org]
=> sanritsu/bankp.cpp: Dumped and added a Bank Panic bootleg set from Tecfri

src/mame/apple/apple2video.cpp
This implements the same workaround for double lo-res that was already used for double hi-res: shift the whole image right by one pixel (losing the rightmost pixel) in monochrome mode so that the NTSC shader is happy. This doesn't affect color mode.
This rewrite incidentally fixes an incorrect shift count in the old code (see the issue).
=> Apple II double lo-res: work around issue #10760

src/mame/mame.lst, src/mame/misc/magic10.cpp
This adds Super Petrix, a Tetris game with hidden poker game to the magic10 driver.
Rom dumps etc for verification have been sent to the relevant place.
The roms were dumped by Caius, just in case we credit rom dumpers.
=> Add Super Petrix to misc/magic10.cpp

src/devices/machine/ncr53c90.cpp
- ncr53c90: Drop ATN during the message-out phase of Transfer Information command, per OG's suggestion. [Ryan Holtz]
=> NCR53C90: Accuracy changes re: Transfer Information + message-out phase

hash/vsmile_cart.xml
New WORKING software list additions
Nick Jr. Dora the Explorer - Dora's Fix-it Adventure (UK, 2005), Nick Jr. Go Diego Go! - Save the Animal Families! (UK), Disney's Mickey Mouse - Mickey's Magical Adventure (UK), Scooby-Doo! - Funland Frenzy (UK, 2004), Marvel Spider-Man & Friends - Secret Missions (UK), Disney's Winnie de Pooh - The Honey Hunt (UK), Zayzoo - My Alien Classmate (UK), Disney/Pixar Cars - Rev It Up in Radiator Springs (UK, alt), Alphabet Park Adventure (UK), Disney's Aladdin - Aladdin's Wonders of the World (UK) [TeamEurope]
=> vsmile_cart.xml: Add UK versions of several V.Smile games

language/Japanese/strings.po
Add new string translations.
Fix some spelling inconsistencies.
=> Updated Japanese Translation

hash/ibm5170_cdrom.xml
Humans 1 and 2 (Europe, OEM) [redump.org]
Humans 1 and 2 (Europe, re-release) [redump.org]
Prince of Persia 2 - The Shadow and the Flame (USA) [redump.org]
Prince of Persia CD Collection (Europe) [redump.org]
Prince of Persia CD Collection (USA) [redump.org]
Prince of Persia Collection: Limited Edition (Europe) [redump.org]
Prince of Persia Collection: Limited Edition (Europe, alt) [redump.org]
Prince of Persia Collection: Limited Edition (USA) [redump.org]
Prince of Persia Collection: Limited Edition (Netherlands) [redump.org]
Prince of Persia Collection: Limited Edition (Brazil) [redump.org]
Telstar 10 CD ROM Box Set [redump.org]
The Humans (Europe) [redump.org]
The Humans (USA) [redump.org]
=> ibm5170_cdrom.xml: 13 New working software list additions

hash/amigaocs_flop.xml
Replace countries' abbreviation by their full name
=> amigaocs_flop.xml: Metadata cleanings

hash/ibm5170.xml
Caesars Palace for Windows [Ihatediskettes, archive.org]
PC Plus (Issue 80 - May 1993) [Tkrns, archive.org]
PC Plus (Issue 96 - September 1994) [Tkrns, archive.org]
PC Plus (Issue 102 - April 1995) [Tkrns, archive.org]
Syndicate (Europe, alt) [The Good Old Days]
Syndicate (Germany) [The Good Old Days]
Syndicate: American Revolt [The Good Old Days]
Where in Space is Carmen Sandiego? [The Good Old Days]
=> ibm5170.xml: 8 New working software list additions

hash/amigaaga_flop.xml
=> amigaaga_flop.xml: Metadata cleanings

hash/amigaecs_flop.xml
=> amigaecs_flop.xml: Metadata cleanings

src/mame/arcade.flt, src/mame/mame.lst, src/mame/misc/babysuprem.cpp
Baby Suprem [jordigahan, ClawGrip]
=> Dumped and added a Z80-based slot machine from Andra: Baby Suprem

hash/msx1_cass.xml
- Moved 7cardstd and 7cardstda to B sides of Samantha Fox Strip Poker.
- Renamed cityconj to citycona
- Renamed queenglf to golfa
- Renamed bumpygts to juegue03
- Renamed maziacs to msxsof02
- Renamed cubik to msxsof06
- Renamed 007agesp to msxsof07
- Renamed batespac to msxsw13
=> msx1_cass.xml: Update meta data and notes on a lot of software releases.

src/mame/mame.lst, src/mame/misc/discoboy.cpp
-----------
DJ Girl (Promat license) [Buenrip, Recreativas.org]
=> misc/discoboy.cpp: Added clone DJ Girl

src/mame/mame.lst, src/mame/misc/opercoin.cpp
Super Pirulo [jordigahan, ClawGrip]
=> misc/opercoin.cpp: Dumped and added an Oper Coin slot machine

src/mame/galaxian/galaxian.cpp, src/mame/mame.lst
Mutacion (Explomatic Spanish Moon Cresta bootleg) [Recreativas.org]
=> galaxian/galaxian.cpp: Dumped and added a new Spanish Moon Cresta bootleg

src/mame/amstrad/amstrad_m.cpp
=> amstrad.cpp: palette fix (MT08506)

src/mame/mame.lst, src/mame/misc/xtom3d.cpp
Pump It Up: The 1st Dance Floor [ATR4X, Gergc, Pawprint, infamouspat, Ruubbinnexx, H4M573R, Angelo Salese, Hammy]
=> misc/xtom3d.cpp: add Pump It Up

src/mame/mame.lst, src/mame/misc/rawthrillspc.cpp
Doodle Jump Arcade (v1.16) [jordigahan, Museo del Recreativo]
=> misc/rawthrillspc.cpp: Dumped and added a new Raw Thrills PC-based arcade game

hash/ibm5150.xml
BC's Quest for Tires [Total DOS Collection]
Buck Rogers: Countdown to Doomsday [The Good Old Days]
Fire Power [The Good Old Days]
Leisure Suit Larry in the Land of the Lounge Lizards (3.5") [Total DOS Collection]
Manhattan Dealers (Europe, The 16-bit Pocket Power Collection release) [old-games.ru]
Prehistorik [Total DOS Collection]
Ski or Die [Total DOS Collection]
Space 1889 [The Good Old Days]
Super Ski (5.25") [old-games.ru]
Super Ski (3.5", alt) [The Good Old Days]
Super Ski (3.5", alt 2) [old-games.ru]
The Cycles: International Grand Prix Racing (5.25") [abandonsocios.org]
New NOT working software list addition
Bubble Bobble (5.25") [Total DOS Collection]
=> ibm5150.xml: 12 New working + 1 not working software list additions

src/mame/snk/hng64.h, src/mame/snk/hng64_3d.ipp, src/mame/snk/hng64_v.cpp
- enabled additive blending in certain situations where it improves the visuals
- prevent background colour flickering in sams64/sams64_2 due to using wrong register bit
- added mosaic effect for tilemaps
- general cleanups
=> hng64_v.cpp : added some missing Hyper NeoGeo 64 video features

language/Ukrainian/strings.po
Updating new and correcting current strings in Ukrainian strings.po.
=> Update Ukrainian translation

hash/amiga_demos.xml
=> amiga_demos.xml: Lowercase on descriptive words

language/Japanese/strings.po
Update Japanese translation (Analog Input etc.)
=> Update Japanese translation

hash/nes.xml
Battletoads (Brazil, Conector pirate) [chirinea]
=> nes.xml: New working software list addition

src/mame/tecfri/sauro.cpp
Sauro (set 4, easier) [Jordi Beltrán, Victor Fernandez (City Game)]
=> tecfri/sauro.cpp: Add a new Sauro set and fix line alignments

hash/vsmile_cart.xml
Disney's Winnie the Pooh - The Honey Hunt (UK) [apex2504]
=> vsmile_cart.xml: Add a new UK game cart dump and use hex for ROM sizes

src/mame/layout/babysuprem.lay, src/mame/misc/babysuprem.cpp
Update driver to make Baby Suprem a playable game.
There is a basic layout file which allows the game to be played but a proper layout with artwork is really needed in the future.
Not sure I've used the correct flags for this where the game is declared ?
=> misc/babysuprem.cpp: Now working machine

src/mame/snk/hng64.cpp, src/mame/snk/hng64.h, src/mame/snk/hng64_sprite.ipp, src/mame/snk/hng64_v.cpp
- sprite mosaic now works for y direction too
- improved transition control register use for fade effects on buriki one jumbotron
- various notes
=> hng64_sprite.ipp : improved sprite mosaic effect

src/mame/arcade.flt, src/mame/mame.lst, src/mame/misc/brglitz.cpp
Ballroom Glitz [jordigahan, ClawGrip]
=> Dumped and added a skeleton driver for "Ballroom Glitz" coin pusher

src/mame/atari/bzone.cpp, src/mame/atari/bzone.h, src/mame/mame.lst
Desert Wars (bootleg of Battle Zone) [Javier Blanco Ojeda, ClawGrip]
Also reformatted single-line comments
=> Dumped and added a Spanish Battle Zone bootleg

src/devices/bus/neogeo/prot_cmc.cpp, src/devices/bus/nes/nes_unif.hxx, src/devices/cpu/dsp32/dsp32dis.cpp, src/lib/util/aviio.cpp, src/lib/util/aviio.h, src/mame/amiga/arsystems.cpp, src/mame/capcom/cps3.cpp, src/mame/konami/3dom2_te.cpp, src/mame/konami/ksys573.cpp, src/mame/midway/midtunit_v.cpp, src/mame/mit/tx0_v.cpp, src/mame/namco/namcos22_v.cpp, src/mame/namco/namcos23.cpp, src/mame/next/next.cpp, src/mame/next/next.h, src/mame/nintendo/pin64.cpp, src/mame/sega/chihiro.cpp, src/mame/sega/coolridr.cpp, src/mame/sega/naomi.cpp, src/mame/snk/hng64_a.cpp, src/mame/subsino/subsino_m.cpp, src/mame/tvgames/generalplus_gpl16250_nand.cpp, src/mame/tvgames/generalplus_gpl32612.cpp, src/mame/tvgames/spg29x.cpp, src/osd/modules/output/network.cpp
This is most of the simple to fix ones.
=> Some simple sprintf warning fixes

src/mame/dynax/ddenlovr.cpp, src/mame/sega/system1.cpp, src/mame/sega/system1.h
According to videos from PCB, 2 titles need to be corrected each 2nd SN76489A clock value.
Noboranka: 
[Reference video 1](https://youtu.be/ORt4HfCu9fw?t=69): recorded by JAMA870P
[Reference video 2](https://youtu.be/TO37TU0mHZA?t=501): recorded by Hirofumi Iwasaki
Gardia: 
[Reference video 3](https://www.youtube.com/watch?v=LSyAelY5Qpk)
Gardia / Noboranka:
[Reference video 4](https://www.nicovideo.jp/watch/sm19730735)
=> sega/system1.cpp nob: fix SN76489A clock

src/devices/sound/es5506.cpp
reference: 
ES5505 datasheet: https://drive.google.com/open?id=1O-qBbXW9oKCTsWpCb22k8ClBph7wQIql
ES5506 datasheet: https://drive.google.com/open?id=1wurPv72pYo0anJti0PuvurUGI51-IfxK
=> sound/es5506.cpp: Convert comments to C++ style, add notes and additional logging

src/mame/mame.lst, src/mame/msx/msx.cpp, src/mame/msx/msx2.cpp
Victor HC-90A (MSX2, Japan) [Daniel Padilla, openMSX]
=> msx/msx2.cpp: New not working clone.

src/mame/arcade.flt, src/mame/mame.lst, src/mame/orca/akazukin.cpp
Aka Zukin [Alberto Salso, Ignacio Seki, Angelo Salese]
=> orca/akazukin.cpp: Added driver for Akazukin (Sigma, 1983)

src/mame/sinclair/neogs.cpp, src/mame/sinclair/neogs.h, src/mame/sinclair/tsconf.cpp, src/mame/sinclair/tsconf.h, src/mame/sinclair/tsconf_m.cpp
neogs: new sound device
sinclair/tsconf.cpp:
* NeoGS support
* Kempston mouse
=> neogs: NeoGS - GeneralSound compatible device

hash/astrocde.xml
Lowercase on descriptive words like "Prototype", "Alt", "Bad Dump", etc.
=> astrocde.xml: Metadata cleanings

hash/to_flop.xml
- Lowercase on descriptive words like "Format", "Alt", "Hacked", "Version", etc.
- Uppercase on abbreviature like "to7" and "to8"
- Correct description "Le Temps d'Une Historie" to "Le Temps d'une Histoire"
=> to_flop.xml: Metadata cleanings

src/mame/mame.lst, src/mame/tch/kickgoal.cpp, src/mame/tch/topdrive.cpp
-------
Top Driving (Version 1.1) [ClawGrip, Museo del Recreativo, Recreativas.org, David Haywood]
=> new WORKING machine (Top Driving)

hash/amigaocs_flop.xml, hash/st_flop.xml
- Extend Euro -> Europe
- Extend Fra -> France
- Fix some instances where boot floppy isn't flop1
- Identify sets with manual copy protection
- Initial pass at identifying issues
=> hash/st_flop.xml: initial pass at QA

scripts/src/bus.lua, src/devices/bus/nabupc/option.cpp, src/devices/bus/nabupc/rs232.cpp, src/devices/bus/nabupc/rs232.h
Emulate the NABU PC's RS232 expansion card.
=> bus/nabupc: Add support for RS232 Card

hash/vsmileb_cart.xml
New NOT_WORKING software list addition
Teletubbies - ¡Es la hora de los Teletubbies! (Spain) [ICEknight, Team Europe, ClawGrip]
Also changed rom sizes from decimal to hexadecimal.
=> vsmileb_cart.xml: Dumped a Spanish Teletubbies game

src/mame/casio/pv2000.cpp, src/mame/dec/decwritr.cpp, src/mame/dec/vk100.cpp, src/mame/mattel/intv.h, src/mame/mattel/intv_m.cpp, src/mame/motorola/mekd2.cpp, src/mame/sharp/mz80.h, src/mame/sharp/mz80_m.cpp, src/mame/skeleton/mycom.cpp, src/mame/skeleton/wicat.cpp, src/mame/zpa/iq151.cpp
Removing sprintf etc.
I've tested what I can but a few were not in a working state to begin with.
=> More ioport upgrades -> required_ioport_array

hash/mobigo_cart.xml
New NOT_WORKING software list addition
-----------------------------------------------
Nickelodeon Spongebob SquarePants -  Defending the Secret Formula (USA) [TeamEurope]
Also fixed metadata for US version of "Disney/Pixar Toy Story 3" and added more info about dummy carts.
=> mobigo_cart.xml: Dumped a Spongebob SquarePants game

src/mame/namco/namcos10.cpp
This does not fix any currently non-working games but it does allow for games that use multiple bootloaders to start the second bootloader which was stored in a range I previously thought wouldn't have scrambling. 
Information about the invalid block table being at the top of the first block also checks out. mrdrilrga's second bootloader has plenty of debug messages, including the one with a function they helpfully named "DumpNandInvalidTable" which prints exactly that table.
=> namcos10: Reevaluate assumption about how later blocks are handled

hash/ibm5150.xml, hash/ibm5170.xml
Barbarian [Total DOS Collection]
Test Drive II - Scenery Disk: European Challenge (5.25") [Total DOS Collection]
Test Drive II - Scenery Disk: European Challenge (3.5") [Total DOS Collection]
Batman: The Caped Crusader [Total DOS Collection]
Redump
Ferrari Formula One [Total DOS Collection]
Moved from ibm5150 to ibm5170 software list
Dyna Blaster
=> ibm5150.xml: Software list additions

src/devices/bus/msx/cart/easi_speech.cpp, src/devices/bus/msx/cart/fmpac.cpp, src/devices/bus/msx/cart/konami.cpp, src/devices/bus/msx/cart/konami.h, src/devices/bus/msx/cart/majutsushi.cpp, src/devices/bus/msx/cart/majutsushi.h, src/devices/bus/msx/cart/moonsound.cpp, src/devices/bus/msx/cart/msx_audio.cpp, src/devices/bus/msx/cart/slotexpander.cpp, src/devices/bus/msx/cart/yamaha_ucn01.cpp, src/devices/bus/msx/module/sfg.cpp, src/devices/bus/msx/slot/cartridge.cpp, src/devices/bus/msx/slot/cartridge.h, src/mame/msx/msx.cpp, src/mame/msx/msx.h, src/mame/msx/msx1.cpp, src/mame/msx/msx1_bruc100.cpp, src/mame/msx/msx1_v9938.cpp, src/mame/msx/msx2.cpp
Add device_mixer_interface to the cartridge and let cartridges output their sound through this.
Set the clock on the cartridge slot and let cartridges derive their clock from it.
=> msx.cpp: Cartridge slot soundin and clock pins.

hash/cdi.xml
=> cdi.xml: New software list item

hash/snes.xml
- Replaced the "HK" abbreviature by "Honk Kong"
- Lowercase on revision word abbreviation "Rev."
- Completed the "K.H. Rummenigge's Player Manager" demos' title description with the demo title screen info.
=> snes.xml: Metadata cleanups

hash/buzztime_cart.xml, hash/ibmpcjr_cart.xml, hash/m5_flop.xml
=> ibmpcjr_cart.xml; m5_flop.xml; buzztime_cart.xml: Metadata corrections

hash/oric1_cass.xml
A View to a Kill - The Computer Game [oric.org]
Don Juans et Dragueurs [oric.org]
Zorgon's Revenge (demonstration only) [oric.org]
Le Diamant de l'île Maudite (demo) [oric.org]
=> oric_cass.xml: Software list additions

src/devices/machine/t10mmc.cpp
* fix [MT#07184](https://mametesters.org/view.php?id=7184) redbook silent regression with konami/konamigv.cpp
=> machine/t10mmc.cpp: track command 48h just plays track when TNO start == TNO end

src/devices/machine/vrender0.cpp, src/devices/video/vrender0.cpp, src/devices/video/vrender0.h, src/mame/misc/psattack.cpp
- Fixes donghaer split screen;
=> video/vrender0.cpp: More accurate VRender0 pipeline inner workings

hash/gameboy.xml
- Added parent/cloneof relation between asteroid/asteroidp
- Lowercase on "Rev" descriptive word
=> gameboy.xml: Metadata cleanups

src/mame/namco/namcos10.cpp
The decrypted program code has been scrambled into the same format that the rest of the NAND data uses and placed into the same blocks the encrypted program code occupied. The NAND data read function will passthrough to the unscramble function when a decrypter isn't present, so the patched ROM will work as-is without any game specific hacks required in driver. When a decrypter is made then it is required to remove the unenc ROM entry or it will try to read the scrambled program code as encrypted program code.
~~Cursor could possibly use some offsetting to make it dead center, but using the offset parameter of `PORT_CROSSHAIR` causes the UI cursor to just stop working properly for me in macOS for some reason. For example, setting the X offset to a non-0 value causes the Y to stop working …
=> namcos10: Add decrypted Point Blank 3 program code [windyfairy, Guru]

src/devices/cpu/mips/mips3.cpp, src/devices/cpu/mips/mips3.h, src/devices/cpu/mips/mips3com.cpp, src/mame/sgi/indigo.cpp, src/mame/sgi/indy_indigo2.cpp, src/mame/sgi/sgi.cpp, src/mame/sgi/sgi.h
To align more with actual hardware behaviour and make IRIX happy in various aspects.
=> SGI Indy: PRID and clock fixes

src/mame/mame.lst, src/mame/skeleton/bolsaint.cpp
Bolsa Internacional (euro) [Javier Blanco Ojeda, ClawGrip]
=> Dumped and added a skeleton driver for a slot machine from Sleic/Petaco

hash/mobigo_cart.xml
=> mobigo_cart.xml: Software list rename

src/mame/stern/berzerk.cpp
All sources seem to suggest a June/July 82 release date (based on feedback from Livestream)   The title screen shows 82.
If there's a version from 81, this isn't it.
=> berzerk.cpp - frenzy is from 1982

src/mame/atari/bzone.cpp, src/mame/skeleton/bolsaint.cpp
skeleton/bolsaint.cpp: Fix copyright holder.
atari/bzone.cpp: Add notes about Desert Wars blue overlay.
=> Misc small changes

scripts/src/bus.lua, src/devices/bus/isa/ibm_speech.cpp, src/devices/bus/isa/ibm_speech.h, src/devices/bus/isa/isa_cards.cpp
Adds the IBM PS/2 speech adapter as an 8-bit ISA slot device.
=> Added IBM PS/2 speech adapter (ISA) [LuigiThirty]

hash/archimedes.xml
- Lowercase on descriptive words ("Demo", "Alt")
- Moved relevant software comments to  `notes` tag
=> archimedes.xml: Metadata cleanups

src/devices/bus/spectrum/neogs.cpp, src/mame/sinclair/pentevo.cpp, src/mame/sinclair/tsconf.cpp, src/mame/sinclair/tsconf.h
* neogs: new default rom v1.10.2
* neogs: sdcard support
* tsconf/pentevo: optional zxbus slot
=> zxbus/neogs: sdcard support

hash/gameboy.xml, hash/snes.xml
Changed the "NP" abbreviation by "Nintendo Power service"
=> gameboy.xml; snes.xml: Changed NP abbreviation

hash/x68k_flop.xml
(AKA "Minic the hedgehog")
Just adding one of the first Sonic fan games, made by Kiyoshi Sakai of Umihara Kawase fame.
Original video and release page:
https://www.youtube.com/watch?v=rXGCWeasnD8
http://www.os.rim.or.jp/~pekochan/develop/X68k/
Partial translation of video description:
https://twitter.com/necrosofty/status/1064970251798892544
=> x68k_flop.xml: New partially working entry "Mi ni Ikuzo! Hedgehog"

scripts/src/formats.lua, src/devices/bus/hp9845_io/hp9885.cpp, src/devices/bus/ieee488/hp9895.cpp, src/lib/formats/all.cpp, src/lib/formats/fs_hp98x5.cpp, src/lib/formats/fs_hp98x5.h, src/lib/formats/hpi_dsk.cpp, src/lib/formats/hpi_dsk.h
Hi,
this PR is for the addition to floptool of filesystem handlers for hp9825, 9831 & 9845 systems.
Thanks.
--F.Ulivi
=> Filesystem handlers for HP9825, 9831 & 9845

hash/nes.xml
Replaced countries' abbreviation by their full name.
Lowercase on descriptive words.
=> nes.xml: Metadata cleanups

src/mame/mame.lst, src/mame/yamaha/ympcs30.cpp
--------------
Yamaha PCS-30 [Edward d-tech]
=> yamaha/ympcs30.cpp: Added skeletop driver for Yamaha PCS-30

hash/msx1_cart.xml, scripts/src/bus.lua, src/devices/bus/msx/cart/loveplus.cpp, src/devices/bus/msx/cart/loveplus.h, src/devices/bus/msx/cart/slotoptions.cpp, src/devices/bus/msx/cart/slotoptions.h
The Love Plus Pack 0 (Korea, pirate) [file-hunter]
Trun (demo) [file-hunter]
Twin Hammer (Europe, alt) [file-hunter]
Twin Hammer (Europe, alt 2) [file-hunter]
Video Hustler (Japan, alt 2) [file-hunter]
Volguard (Japan, alt) [file-hunter]
TT Racer (Al Alamiah) [file-hunter]
Voyage to Mecca (Arab, alt 3) [file-hunter]
T-Game 4 [file-hunter]
T-Game 4 (alt) [file-hunter]
T-Virus [MSXDev]
Tales of Popolon (English, v1.3.1) [santiontanon]
Tales of Popolon (Spanish, v1.3.1) [santiontanon]
Tales of Popolon (English, v1.3) [santiontanon]
Tales of Popolon (Spanish, v1.3) [santiontanon]
Tales of Popolon (English, v1.2) [santiontanon]
Tales of Popolon (Spanish, v1.2) [santiontanon]
Tales of Popolon (English, v1.1.1) [santiontanon]
Tales …
=> msx1_cart.xml: Added 100 items (99 working).

src/mame/sinclair/atm.cpp, src/mame/sinclair/atm.h, src/mame/sinclair/pentevo.cpp, src/mame/sinclair/tsconf.cpp, src/mame/sinclair/tsconf.h, src/mame/sinclair/tsconf_m.cpp, src/mame/sinclair/tsconfdma.cpp
* ZX-Evolution (tsconf/pentevo): TurboSound AY-mod configuration
* tsconf: add covox; kemston/beta conflict with DOS enabled
* tsconfdma: fix dma blitting mode
=> sinclair/tsconf.cpp,pentevo.cpp: various fixes

src/mame/mame.lst, src/mame/misc/compucranes.cpp
Master Crane (set 2) [jordigahan]
* Rename existing set 2 as set 3
=> misc/compucranes.cpp: Dumped and added a new crane on V7 PCB [jordigahan]

hash/msx1_cart.xml, src/devices/bus/msx/cart/cartridge.cpp, src/devices/bus/msx/cart/korean.cpp, src/devices/bus/msx/cart/korean.h, src/devices/bus/msx/cart/slotoptions.cpp, src/devices/bus/msx/cart/slotoptions.h
Safari X (Japan, The Links) [file-hunter]
Sasa (Japan, alt 2) [file-hunter]
Scramble Eggs (Korea) [file-hunter]
Sea Horse (Arab, v1.01) [file-hunter]
Skooter (Arab) [file-hunter]
Snake It (Arab) [file-hunter]
Snake It (Japan, alt) [file-hunter]
Space Shuttle - A Journey into Space (Japan) [file-hunter] Star Trek (Japan) [file-hunter]
Star Trek (Japan, alt) [file-hunter]
Star Wars (Arab, alt) [file-hunter]
Super Bioman 1 (Korea) [file-hunter]
Super Bioman 1 (Korea, alt) [file-hunter]
Super Game 25 (Korea) [file-hunter]
Super Racer (Japan) [file-hunter]
Super Snake (Japan, alt 3) [file-hunter]
Supertripper (Spain, alt) [file-hunter]
S.o.L.o. (English) [MSXDev]
S.o.L.o. (Spanish) [MSXDev]
Sacred Valley [MSXDev]
Saimazoom …
=> msx1_cart.xml: Add 76 items

hash/vsmile_cart.xml
New WORKING software list additions
Disney's Aladdin - Aladdin's Wonders of the World (USA)
Nick Jr The Backyardigans - Viking Voyage (USA)
Bert & Ernie's Imagination Adventure (USA)
Lil' Bratz Dressed Up - Friends, Fashion and Fun (USA)
Disney/Pixar Ratatouille - Remy's New Recipes (USA)
DreamWorks Shrek - Dragon's Tale (USA)
[anonymous dumper]
=> vsmile_cart.xml: Added six new USA dumps

hash/ibm5170_cdrom.xml
Desert Strike & Jungle Strike (Europe) [redump.org] First Samurai (Europe) [redump.org]
Jazz Jackrabbit (Europe, re-release) [redump.org]
Jazz Jackrabbit (Europe) [redump.org]
Jazz Jackrabbit 2 (Europe) [redump.org]
Leisure Suit Larry's Greatest Hits and Misses! (Europe, re-release) [redump.org]
Leisure Suit Larry's Greatest Hits and Misses! (USA) [redump.org]
Links - The Challenge of Golf (USA) [redump.org]
Loom (USA) [redump.org]
Loom (USA, alt) [redump.org]
Loom (USA, alt 2) [redump.org]
Monkey Island Madness (USA) [redump.org]
The Dig (USA) [redump.org]
=> ibm5170_cdrom.xml: Software list additions

src/mame/sinclair/tsconf.cpp, src/mame/sinclair/tsconf.h, src/mame/sinclair/tsconf_m.cpp, src/mame/sinclair/tsconfdma.cpp, src/mame/sinclair/tsconfdma.h
- finalize regs delayed updates
- fix graphic pages padding
=> sinclair/tsconf.cpp: finalize regs delayed updates; fix graphic pages padding

src/mame/galaxian/galaxian.cpp, src/mame/mame.lst
Amidar (bootleg, set 2) [Rubén Casaña (Retro Arcadia Valencia), ClawGrip]
Also reformatted single-line comments.
=> galaxian/galaxian.cpp: Dumped and added an Amidar bootleg

hash/msx1_cart.xml, scripts/src/bus.lua, src/devices/bus/msx/cart/cartridge.cpp, src/devices/bus/msx/cart/quickdisk.cpp, src/devices/bus/msx/cart/quickdisk.h, src/devices/bus/msx/cart/slotoptions.cpp, src/devices/bus/msx/cart/slotoptions.h
DPQ-280 Quick Disk Drive [hans otten]
DPQ-280 Quick Disk Drive (alt) [hans otten]
QDM-01 Quick Disk Drive [hans otten]
VY-0002 Quick Disk Drive [hans otten]
=> msx1_cart.xml: Add 4 not working items

hash/leapfrog_didj_cart.xml, hash/leapfrog_zippity_cart.xml, hash/leapster_explorer_cart.xml
Lowercase on media support "cartridges" word
=> Lowercase on LeapFrogs' softwarelist media description

src/mame/namco/namcos12.cpp
Updated a few links to flyers and images and added two dates from flyers
=> Update 2 years and links in namcos12.cpp

src/mame/mame.lst, src/mame/skeleton/minihock.cpp
Mini Hockey [Museo Arcade Vintage, ClawGrip]
=> Dumped (partially) and added a skeleton driver for a Spanish electromechanical hockey coinop

hash/specpls3_flop.xml
19 Part One - Boot Camp [El Trastero del Spectrum]
2 por 1: Rock'n Roller + Wells & Fargo [Steven Brown, Planeta Sinclair]
Averno [Steven Brown, Planeta Sinclair]
Dragons of Flame [El Trastero del Spectrum]
Dungeons of Gomilandia (v0.1a) [RetroWorks]
Dungeons of Gomilandia (v0.1) [Spectrum Computing]
El Asombroso Spider-Man y Capitán America en La Venganza del Dr. Muerte! [El Trastero del Spectrum]
El Equipo A [El Trastero del Spectrum]
Frightmare (Zafiro) [El Trastero del Spectrum]
Gunship (Erbe, alt) [El Trastero del Spectrum]
High Steel (Erbe, alt) [Steven Brown, Planeta Sinclair]
Pit-Fighter (Dro Soft) [El Trastero del Spectrum]
Power Magic (alt) [El Trastero del Spectrum]
Rainbow Islands (Erbe, alt) [El …
=> specpls3_flop.xml: Software list additions

hash/gamate.xml
new WORKING software list additions
---------
gamate.xml:
mightbox - Mighty Boxer [Peter Wilhelmsen, Morten Kirkegaard]
=> new WORKING software list additions (Gamate)

src/mame/leapfrog/leappad.cpp, src/mame/mame.lst
LeapPad Plus Microphone [Sean Riddle, ClawGrip]
=> leapfrog/leappad.cpp: Dumped and added a new LeapPad model BIOS

hash/msx1_cart.xml
MSX Pasocalc (Japan) [file-hunter]
Picture Painter (Japan) [file-hunter]
Picture Painter (Japan, alt) [file-hunter]
Print Lab (Japan) [file-hunter]
Perfect Math for First Preparatory Class - Part 1-1 (Arab) [file-hunter]
Perfect Science for First Preparatory Class - Part 1-2 (Arab) [file-hunter]
O [cobinee]
Olion [file-hunter]
Open Wide! [MSXDev]
Operation Wolf (v1) [MSXDev]
Operation Wolf (v3) [file-hunter]
Othello Competicao (Portuguese) [file-hunter]
PAC-01 [MSXDev]
Pacific (v1.0.0) [file-hunter]
Pacific (v1.1.0) [file-hunter]
Pacific (v1.2.0) [MSXDev]
Pacific (v1.2.4) [file-hunter]
Paco el Bombas [msx-org]
Paco el Bombas REDUX (English) [msx-org]
Paco el Bombas REDUX (Italian) [msx-org]
Paco el Bombas REDUX (Spanish) …
=> msx1_cart.xml: Add 60 items

src/devices/sound/gew.cpp, src/devices/sound/gew.h, src/devices/sound/gew7.cpp, src/mame/layout/dd9.lay, src/mame/mame.lst, src/mame/yamaha/ympsr150.cpp
New working machine
----------
Yamaha DD-9 Digital Percussion [BCM, Devin Acker]
=> yamaha/ympsr150.cpp: add DD-9

hash/neocd.xml
Double Dragon (Japan) [redump.org]
=> neocd.xml: New working software list item

hash/msx1_cart.xml
Add floppies to HB-3600 [frs]
Yeoja Wres (Korea) [file-hunter]
Namake's Bridgedrome [MSXDev]
Nayade Resistance - Episode I [MSXDev]
Nayade Resistance - Episode I (alt) [file-hunter]
NeoPONG512 (v1.0) [MSXDev]
NeoPONG512 (v1.1) [MSXDev]
Neuras [inufuto]
Nice Soccer World Cup [file-hunter]
Night City (English) [MSXDev]
Night City (Spanish) [MSXDev]
Night Driver [MSXDev]
Night Escape [msxblue]
Ninja Savior [MSXDev]
No [file-hunter]
No Back Down [MSXDev]
Noborunoca (v1.0.0) [Hiromasa Tanaka]
Noborunoca (v0.7.0) [Hiromasa Tanaka]
Nogalious (demo) [file-hunter]
Nohzdyve [crunchworks]
Numberman [msx-org]
=> msx1_cart.xml: Add 20 items. Add floppy images to HB-3600.

src/mame/mame.lst, src/mame/misc/arachnid.cpp
Super Six Plus II English Mark Darts (v3.3) [ClawGrip]
=> misc/arachnid.cpp: Added a new 'English Mark Darts' set (as new parent)

src/mame/mame.lst, src/mame/phoenix/phoenix.cpp
Condor (Valadon Automation bootleg of Phoenix) [Retromaniacs, Recreativas.org]
=> Dumped and added a new Phoenix bootleg set

src/mame/mame.lst, src/mame/misc/compucranes.cpp
Octopussy [Victor Fernandez (City Game)]
Added a as clone of "Master Crane", as "Master Crane" was the base machine all manufacturers used to derive their own machines (changing the sounds/music on the software, the art/design on the cab, etc.).
=> misc/compucranes.cpp: Dumped and added a crane from Covielsa

src/mame/mame.lst, src/mame/skeleton/caramball.cpp
Caramball [Retromaniacs, Recreativas.org]
=> Dumped and added a skeleton driver for a Spanish electromechanical air hockey

hash/a800.xml
a800.xml: Akhtabar Dhakayik, Altaaqa, Bank Almaelumat, Qamus Najm, Kayf Yaemal Alkumbiutar [archive.org]
=> hash/a800.xml: add aDawilah releases

hash/msx1_cart.xml
Mega Assembler (Brazil) [file-hunter]
Merlin (Spain) [file-hunter]
Merlin (Spain, alt) [file-hunter]
Monkey Academy (Japan, alt 4) [file-hunter]
MSX Rugby (Korea) [file-hunter]
Multitext (France, v1.4) [file-hunter]
Ninja Kopimaru Kun (Japan) [file-hunter]
Mazes Unlimited (Arab) [file-hunter]
Moon Rider (Arab) [file-hunter]
M-Tanks [MSXDev]
M.A.Z.E. [file-hunter]
Mag the Magician [file-hunter]
Magical Stones (16KB) [MSXDev]
Magical Stones (8KB) [MSXDev]
Magnet [file-hunter]
Mahjong Solitaire [MSXDev]
Majikazo [file-hunter]
Majikazo (alt) [file-hunter]
Make Them Fall [MSXDev]
Make Them Jump [MSXDev]
Malaika - Prehistoric Quest (rev 3) [MSXDev]
Malaika - Prehistoric Quest (rev 2) [MSXDev]
Malaika - Prehistoric Quest (rev 1) …
=> msx1_cart.xml: Added 77 items, 73 working

hash/msx1_cart.xml
L.3.W (Korea) [file-hunter]
Lightly Roller (Japan) [file-hunter]
l'Abbaye des Morts (v1.2) [retrodeluxe]
l'Abbaye des Morts (v1.1) [retrodeluxe]
l'Abbaye des Morts (v0.1) [retrodeluxe]
La Corona Encantada (English) [MSXDev]
La Corona Encantada (English, alt) [file-hunter]
La Corona Encantada (Spanish) [MSXDev]
La Corona Encantada (Spanish, alt) [file-hunter]
La Corona Encantada (Spanish, final) [relevovideogames]
La Corona Encantada (Spanish, final, alt) [file-hunter]
Landing [file-hunter]
Lawn Mower [file-hunter]
Leila K [file-hunter]
Libreway [MSXDev]
Lift [inufuto]
Limaribu [MSXDev]
Linez [file-hunter]
Linez (1 level broken) [MSXDev]
Linez (2 levels broken) [file-hunter]
Linez (3 levels broken) [file-hunter]
Litter Box …
=> msx1_cart.xml: Added 33 items, 32 working

hash/oric1_cass.xml, src/mame/tangerine/oric.cpp
4K Kong [The Oric Site]
Cobra [The Oric Site]
Impossible Mission (Atmos 50Hz) [Defence Force]
Impossible Mission (Atmos 60Hz) [Defence Force]
Invaders (Program Factory) [The Oric Site]
Le Fer d'Amnukor [The Oric Site]
Oricium [Defence Force]
Rush Hour 4K [The Oric Site]
Skool Daze [The Oric Site]
Stormlord [Defence Force]
Stormlord (alt) [The Oric Site]
The Pits [The Oric Site]
Transat One [The Oric Site]
Arsène Lapin [The Oric Site]
Detective Story [The Oric Site]
Composer [The Oric Site]
Redump software
Le Secret du Tombeau [The Oric Site]
Le Tour du Monde en 80 Jours [The Oric …
=> oric1_cass.xml: Software list additions

src/mame/capcom/cps1.cpp
Added missing 'Starting Level' and 'Stop' switches.
=> cps1.cpp: Add daimakair DIP switches

src/mame/misc/astropc.cpp
Also added version info for the dslayrr sets from the files
=> astropc.cpp: Add notes, correct release years

hash/msx1_cart.xml
Replaced J.P. Winkle (Korea) [file-hunter]
Soukoban (Korea, Zemina) [file-hunter]
The Police Story (Japan, alt 2) [file-hunter]
Juno First (Japan, alt) [file-hunter]
Keystone Kapers (Japan, alt) [file-hunter]
Pesadelo (Brazil) [file-hunter]
Konami's Baseball (Japan, alt) [file-hunter]
MSX Basic-kun Plus 2.0 (Japan, alt) [file-hunter]
I Need Speed (MSX Cartridge Shop) [file-hunter]
I Need Speed (Final) [MSXDev]
I Need Speed (MSXDev) [MSXDev]
I.N.E.R.T.I.A. [MSXDev]
Impetus [inufuto]
Inq & Suq vs Nightmare [file-hunter]
Invasion of the Zombie Monsters [file-hunter]
Isitar 7 [n.i]
Italian Stallion [MSXDev]
J.E.T.P.A.C. [file-hunter]
Jäästä [MSXDev]
Jawbreaker II [MSXDev]
JumpinG - The Tutorial Game (English) [MSXDev]
JumpinG - …
=> msx1_cart.xml: Added 30 items.

src/mame/pinball/recel.cpp
Also fixed some game names and reformatted single line comments.
=> pinball/recel.cpp: Redumped 'Mr. Evil' [Strpinball, Recreativas.org]

hash/cdi.xml, hash/ibm5170_cdrom.xml
The Cranberies: Doors and Windows (USA) [redump.org]
=> New working software list additions (cdi.xml, ibm5170_cdrom.xml)

src/devices/bus/isa/svga_cirrus.cpp, src/devices/video/clgd546x_laguna.cpp
CL-GD510/520 [rfka01],[Vlask]
CL-GD610/620-C [Vlask]
CL-GD5320 [Vlask]
CL-GD5401 [jvernet, chukaev.ru54, Vlask]
CL-GD5402 [Vlask]
CL-GD542x [rfka01, Vlask, douglar, SomeGuy, chukaev.ru54, Palcal]
CL-GD54M30 [Vlask]
CL-GD543x, [rfka01, BeginnerGuy, Vlask, Pirx]
CL-GD5440 [Vlask]
Diamond Speedstar PRO [Vlask]
Diamond Speedstar 64, STB Nitro 64 [kixs]
Octek VL-Combo [hasat, aitotat]
=> svga_cirrus.cpp: A collection of BIOS ROMs for different Cirrus Logic chipsets

hash/msx1_cart.xml, src/devices/bus/msx/cart/cartridge.cpp, src/devices/bus/msx/cart/korean.cpp, src/devices/bus/msx/cart/korean.h, src/devices/bus/msx/cart/slotoptions.cpp, src/devices/bus/msx/cart/slotoptions.h
Removed Hopper (Europe)
Demoted The Holy Quran (v1.00)
Hole in One Professional (Japan, alt 2) [file-hunter]
Hole in One Professional (Japan, alt 3) [file-hunter]
Hot-Asm (Brazil) [file-hunter]
Hot-Plan (Brazil) [file-hunter]
Hydlide II - Shine of Darkness (Korea) [file-hunter]
Hopper (Arab) [file-hunter]
Hans' Adventure (v1.1) [MSXDev]
Hans' Adventure (v1.0) [MSXDev]
Happy Halloween [Clube MSX]
Happy Square Christmas [303bcn]
Heart Stealer 2 [MSXDev]
Heroes Arena [MSXDev]
Hose Diogo Martinez: The Bussas Quest [MSXDev]
How Many Are The Dumbbells You Lift? [cobinee]
=> msx1_cart.xml: Added 14 items. Removed 1 item.

hash/msx1_cart.xml
Game World - 64 Games (Korea, alt) [file-hunter]
Gangcheol Robocop (Korea) [file-hunter]
Gangcheol Robocop (Korea, alt) [file-hunter]
Gangcheol Robocop (Korea, alt 2) [file-hunter]
El Gnomo Fedor en la Caverna Perdida (Spain) [file-hunter]
Gokiburi Daisakusen (Japan, alt) [file-hunter]
Dunoegyosil Omok (Korea) [file-hunter]
Graphic Artist (Japan, Europe) [file-hunter]
Graphic Artist (Japan, Europe, alt) [file-hunter]
Yamaha Graphic Card [file-hunter]
Graphic Master Lab (Japan, Europe) [file-hunter]
Graphic Master Lab (Japan, Europe, alt) [file-hunter]
Green Beret (Europe, alt 2) [file-hunter]
Gyro Adventure (Japan) [file-hunter]
Nemesis 2 (Europe) ~ Gradius 2 (Japan) (demo, alt) [file-hunter]
G-Monkey [2KBOS]
Genesis Dawn of …
=> msx1_cart.xml: Added 37 items, 36 working.

hash/gbcolor.xml
Grimace’s Birthday (V1.7) [nickisarchivinget]
Grimace’s Birthday (V1.6) [nickisarchivinget]
Lowercase on some descriptive words, like "Sample", "Hacked", "Encrypted" and "Bootleg"
=> gbcolor.xml: Software list additions

hash/msx1_cart.xml
Fighting Rider (Spain) [file-hunter]
Final Justice (Japan, alt 3) [file-hunter]
Factory Infection [MSXDev]
Fantastic Football [MSXDev]
Farm [N.I]
Farty Pig (beta) [file-hunter]
Find It! [MSXDev]
Flappy Bird (Crunchworks, rev F) [Crunchworks]
Flappy Bird (Crunchworks, rev F, alt) [Crunchworks]
Flappy Bird (Crunchworks, rev B) [file-hunter]
Flappy Bird (SCS) [file-hunter]
FlyGuy [MSXDev]
Formula Dice [MSXDev]
Foryster (v00.9) [Siudym]
Foryster (v00.3) [file-hunter]
Foryster (v00.2) [file-hunter]
Freedom Fighter (final) [TheGeps]
Freedom Fighter (v1.9) [file-hunter]
Freedom Fighter (v1.8a) [file-hunter]
Freedom Fighter (v1.8) [file-hunter]
Freedom Fighter (v1.7) [file-hunter]
Freedom Fighter (v1.6) [file-hunter]
Freedom Fighter …
=> msx1_cart.xml: Added 28 items.

hash/msx1_cart.xml
E.I. - Exa Innova (Japan, Compile) [file-hunter]
E.I. - Exa Innova (Japan, Compile, alt) [file-hunter]
Ewoks (Spain) [file-hunter]
Ewoks and the Dandelion Warriors (Spain) [file-hunter]
Earth Attack [TheGeps]
Eat Blue! 2004 [MSXDev]
Eat Blue! 2004 (alt) [file-hunter]
Eruka Fan Book [N.I]
Está en el Pantano [file-hunter]
Está en la Caja (v1.1) [file-hunter]
Está en la Caja (v1.0) [file-hunter]
ExChess [MSXDev]
=> msx1_cart.xml: Added 12 items.

hash/specpls3_flop.xml, hash/spectrum_betadisc_flop.xml
Bonnie and Clyde [Spectrum Computing]
Crazy Cars II (Proein) [El Trastero del Spectrum]
Drift! [Spectrum Computing]
The Ultimate Disc Copier [El Trastero del Spectrum]
Wonderful Dizzy [Spectrum Computing]
New NOT working software list addition
La Espada Sagrada [El Trastero del Spectrum]
DreamWalker: Alter Ego 2 (v1.0) [RetroSouls]
Gluf [RetroSouls]
Sun Bucket [Spectrum Computing]
=> specpls3_flop.xml; spectrum_betadisc_flop.xml: Software list additions

hash/msx1_cart.xml, scripts/src/bus.lua, src/devices/bus/msx/cart/cartridge.cpp, src/devices/bus/msx/cart/matra.cpp, src/devices/bus/msx/cart/matra.h, src/devices/bus/msx/cart/slotoptions.cpp, src/devices/bus/msx/cart/slotoptions.h
C_So! (Japan, alt) [file-hunter]
Campeón de Conductores (Spain) [file-hunter]
Cannon Fighter (Japan, The Link) [file-hunter]
Cannon Turbo (Japan, alt) [file-hunter]
Circus Charlie (Japan, The Link) [file-hunter]
Custar (Japan) [file-hunter]
Midway (Japan, alt) [file-hunter]
Video Hustler (Japan, alt 3) [file-hunter]
C.C.R. Anexo 1 El Algoritmo (v1.2) [MSXDev]
C.C.R. Anexo 1 El Algoritmo (v1.1) [file-hunter]
C.C.R. Anexo 1 El Algoritmo (v1.0) [file-hunter]
Cacorm [inufuto]
Caos Begins [MSXDev]
Caos Begins (alt) [file-hunter]
Caos Begins (alt 2) [file-hunter]
Cardwork Orange (unlicensed) [file-hunter]
Casio GPM-Collection Volumen 1 (unlicensed) [file-hunter]
Casio GPM-Collection Volumen 2 (unlicensed) [file-hunter]
Castle Tomb …
=> msx1_cart.xml: Added 81 items, 80 working.

src/mame/cirsa/missbamby.cpp, src/mame/mame.lst
=> cirsa/missbamby.cpp: Added a new Spanish slot game and ordered out all the sets

hash/msx1_cart.xml
Replace Arabic Barq BASIC (Arab) with a better dump [file-hunter]
Back to the Future (Japan, alt 2) [file-hunter]
Bank Street Writer (United Kingdom) [file-hunter]
BASIC compiler (Japan) [file-hunter]
Beam Rider (Japan, alt) [file-hunter]
Bubble Bobble (Korea) [file-hunter]
Break In (Arab) [file-hunter]
Bagman [MSXDev]
Bakerman [MSXDev]
Balloon Buster [MSXDev]
Balloon City [MSXDev]
Battlot [inufuto]
Bee [n.i]
Beepertron [MSXDev]
BeeZ [MSXDev]
BeTiled! [MSXDev]
BeTiled! (alt) [file-hunter]
BeTiled! (alt 2) [file-hunter]
BeTiled! (alt 3) [file-hunter]
Bird & Chairs [n.i]
BitLogic [file-hunter]
BitLogic (MSXDev) [MSXDev]
Blastoid [MSXDev]
Blockbuster [MSXDev]
BlockPuzzle (v1.2) [file-hunter]
BlockPuzzle (v1.1) [file-hunter] …
=> msx1_cart.xml: Added 45 items. Replaced 1 item.

hash/msx1_cart.xml
Adventure Kid (Korea) [file-hunter]
Aliens - Alien 2 (Korea) [file-hunter]
Alpine Ski (Arab) [file-hunter]
1937 (English) [MSXDev]
1937 (Spanish) [MSXDev]
2048 Simulator [timmy]
3,4 [cobinee]
Ace Gun [cobinee]
Aerial [inufuto]
Alien Attack (v3.5) [MSXDev]
Alien Attack (v3.0) [file-hunter]
Alien Attack (v1.3) [file-hunter]
Alien Attack (v1.06) [file-hunter]
Alien Attack (v1.01) [file-hunter]
Alien Attack (v1.0) [file-hunter]
Alter Ego [MSXDev]
Anchors Aweigh (v1.1) [MSXDev]
Anchors Aweigh (v0.2) [file-hunter]
Anchors Aweigh (pre-release) [file-hunter]
Andrea Petkovic Tennis (English) [MSXDev]
Andrea Petkovic Tennis (Spanish) [MSXDev]
Any Treasure Day [MSXDev]
Arcomage [file-hunter]
Arm Wrestler [MSXDev]
Arno Dash [Under4Mhz] …
=> msx1_cart.xml: Added 27 items.

hash/msx_softcard.xml
Barnstormer (UK) [file-hunter]
=> hash/msx_softcard.xml: Added 1 item.

hash/c64_cass.xml
I've tried to keep myself out of this one as much as possible, and just imported the Ultimate Tape Archive's superior work pretty much as-is.
=> Import some more C64 tapes from the Ultimate Tape Archive V4.0

hash/oric1_cass.xml
Crypt Show [The Oric Site]
Dernier Metro [The Oric Site]
Formule 1 [The Oric Site]
Gubbie [The Oric Site]
La Maison de la Mort [The Oric Site]
Memory [The Oric Site]
Meurtre a Grande Vitesse [The Oric Site]
Minesweeper [The Oric Site]
=> oric1_cass.xml: Added 8 working items

src/mame/heathkit/h19.cpp, src/mame/heathkit/tlb.cpp, src/mame/heathkit/tlb.h
Enhancements to h19
- Add dte rs232 port to all connecting terminal to other systems
- expose all the signals of the 8250 on the tlb
- specify ROM chip positions
- other minor cleanup
=> heathkit/h19.cpp: Add dte rs232 port, expose all signals of terminal

src/mame/namco/namcos12.cpp
- mdhorse no longer has garbage graphics, played through the game for a while and no crashes so I promoted it to playable
- kaiunqz boots and after playing it for a while there were no noticeable issues, so it has also been promoted to playable
- sws2000 and sws2001 can boot now but they randomly crash. I don't believe these crashes are banking related.
- toukon3 still has garbage graphics. I don't think this is banking related either (it appears to be reading in the data it expects, so maybe some other timing-related issue?)
- kartduel appears to be a bad dump on inspection which is causing the bluescreen crashes when it loads certain graphics. Additionally, the framerate issue is just due to the link PCB not being emulated. I added info about how to stop it from hitching by setting a …
=> namcos12: ROM banking fixes + other bug fixes

hash/a2600.xml
3-D Zapper (prototype) [Atarimania]
Actionauts (NTSC) [Atarimania]
Bouncin' Baby Bunnies (prototype) [Atarimania]
Good Luck, Charlie Brown (prototype) [Atarimania]
Hard-Head (NTSC, prototype) [Atarimania]
=> a2600.xml: Added 5 working items

src/devices/bus/isa/svga_cirrus.cpp, src/devices/bus/isa/svga_paradise.cpp, src/mame/mame.lst, src/mame/pc/at.cpp, src/mame/pc/pc.cpp
Add BIOS files to svga_paradise.cpp, add notes on MC1702 to pc.cpp
at.cpp: add Olivetti M250E, remove unused M290 config, update M290 notes.
=> at.cpp, pc.cpp, svga_paradise.cpp: BIOS additions

hash/casio_rompack.xml
New not working software list addition
casio_rompack.xml: Super Songs (RO-257) [Peter Caves]
=> Dumped and added a new Casio ROM Pack and improve notes

hash/spectrum_mgt_flop.xml
=> spectrum_mgt_flop.xml: Renamed software list

src/mame/gaelco/gaelco3d.cpp, src/mame/mame.lst
Surf Planet (Version 2.0) [Victor Fernandez (City Game)]
=> gaelco3d.cpp: Dumped and added a new "Surf Planet" clone

hash/msx1_flop_525.xml
Amazônia (Brazil) [file-hunter]
BKP Disco (Brazil) [file-hunter]
O Conde de Monte Cristo (Brazil) [file-hunter]
Disk Mechanic v2.0 (Brazil) [file-hunter]
Graphic View (Brazil) [file-hunter]
Graphos III Pro (Brazil) [file-hunter]
MSX-Word v3.0 (Brazil) [file-hunter]
Professional Cards (Brazil) [file-hunter]
Professional Publisher (Brazil) [file-hunter]
Serra Pelada [file-hunter]
=> msx1_flop_525.xml: Added 10 items.

hash/msx1_flop.xml
Replaced Konami Game Collection 3: Shooting Series (Japan) with a better dump. [file-hunter]
10 Programas Serie Oro (Spain) [file-hunter]
20 Programas Serie Oro (Spain) [file-hunter]
747 400b Flight Simulator (Europe, cracked) [file-hunter]
Alfabet en Deelsom (Netherlands) [file-hunter]
Alien Panic (Spain) [file-hunter]
Andon (Japan, hacked) [file-hunter]
Duad-MSX (Japan) [file-hunter]
Engels + Procenten (Netherlands) [file-hunter]
Fracta (Brazil) [file-hunter]
Graphos III (Brazil) [file-hunter]
Gruta de Maquine (Brazil)
The Iron Gauntz (Japan, prototype) [file-hunter]
Konami Game Collection 1: Action Series (Japan, alt) [file-hunter]
Konami Game Collection 4: Sports Series 2 (Japan, alt) [file-hunter]
Lettergrijper + Geld …
=> msx1_flop.xml: Added 105 items. Replaced 1 item.

src/mame/heathkit/h89.cpp
Several companies offered CPU speed upgrades for the H89. These used a bit in the GPP to toggle between the standard 2.048 MHz speed and the upgraded speeds. Upgrades at least to 6 MHz were available.
Options for 4 MHz and 6 MHz were added.
Also updated how changes in GPP are detected.
Set the interrupt controller slot device to a "fixed" slot, to avoid users breaking the H89 by changing it. Once additional add-on boards are available and the soft-sectored controller is made into a slot device itself, the program will be able to properly set the interrupt controller based on what boards are installed.
=> heathkit/h89.cpp: add optional CPU speed upgrade modifications

src/mame/mame.lst, src/mame/misc/falgas_m89.cpp
Fantastic Car (Micro-87 hardware, newer) [jordigahan]
=> falgas_m89.cpp: Added a newer clone of "Fantastic Car" on M87 hardware

src/mame/heathkit/tlb.cpp, src/mame/heathkit/tlb.h
- Added options for both CPU speed and CRT Colors
- Minor changes to keyboard codes
- Update ROM Regions to actual size of ROMS
=> heathkit/tlb.cpp: Add options for CPU speed, CRT color

src/mame/heathkit/h19.cpp, src/mame/heathkit/h89.cpp, src/mame/heathkit/tlb.cpp, src/mame/heathkit/tlb.h
Implement the superset ROM upgrade/modifications for the terminal logic board (tlb/h19).
Add the superset option to h19 and h89 systems.
=> heathkit/tlb.cpp: Add superset ROM/upgrade modification

src/mame/mame.lst, src/mame/orca/espial.cpp
[espialj] Espial (Japan) [QtQ, Team Japump!!!]
[espialn] Espial (Nova Apparate license) [QtQ, Team Japump!!!]
=> espial: New working clones

src/frontend/mame/luaengine.cpp
Noticed a minor typo in luaengine.cpp
=> luaengine.cpp: fix minor typo offfset -> offset

hash/msx1_cass.xml
Replaced Aspar GP Master (Europe) with a better dump. [file-hunter]
The A-Team (Spain, alt) [file-hunter]
Akujo Densetsu (Japan) [file-hunter]
Aoi Uchuu no Bouken (Japan) [file-hunter]
Cannon Ball (United Kingdom) [file-hunter]
Cannon Fighter (Europe) [file-hunter]
Cetus (United Kingdom) [file-hunter]
The Chess Game (Europe) [file-hunter]
Chitei Tanken (Japan) [file-hunter]
Chubby Gristle (United Kingdom) [file-hunter]
D-Day (Netherlands) [file-hunter]
The Dam Busters (Europe) [file-hunter]
Dizzy Ball (Japan) [file-hunter]
Donpan (Japan) [file-hunter]
Driller Tanks (Europe) [file-hunter]
Eagle (Spain) [file-hunter]
Echec (France) [file-hunter]
Animation Editor "EDDY" (Japan) [file-hunter]
Emerald Isle (Europe) [file-hunter] …
=> msx1_cass.xml: Added 53 items. Replaced 1 item.

src/mame/mame.lst, src/mame/sega/segas16b.cpp
Time Scanner (set 3, Japan, System 16B) (FD1089B 317-0024) [Team Japump!!!, Wayder]
=> sega/segas16b.cpp: Added an FD1089B-protected version of Time Scanner on System 16B

hash/amigaocs_flop.xml, hash/megacdj.xml, hash/megadriv.xml, hash/vic10.xml
Renamed countries' abbreviations
Lowercase on descriptive words
=> Various metadata cleanings

src/mame/layout/bcheetah.lay
Added a keypad to the bcheetah layout like the one on the Incredible Brain Buggy.
=> bcheetah.lay: add keypad

src/mame/mame.lst, src/mame/subsino/subsino.cpp
New HUNTer (bootleg) [Taksangs]
Also fixed the year for 'newhunter' set.
=> subsino/subsino.cpp: Dumped and added a "New HUNTer" clone

hash/msx2_cart.xml
Zanac EX (Japan, Woomb) [file-hunter]
Michelangelo II (Japan) [file-hunter]
Super Lode Runner (Japan, alt) [file-hunter]
Word Processor (Arab) [file-hunter]
Zukkoke Yajikita Onmitsu Douchuu (Japan, alt 2) [file-hunter]
The Adventures of Moron van der Slut - Escape from Castro Castro [msxdev Compo]
The Bet [Orazio Cacciola]
CR3 [NabetaJisho]
Gogoboom [ESP Soft]
Memory (v1.1) [MSXdev]
Memory (v1.0) [file-hunter]
No Ren-Sha (v0.13) [file-hunter]
O'Conner Among the Falling Walls [file-hunter]
Operatión Brazil World Cup [file-hunter]
Pac-Man Collection DX (demo) [Opcode Games]
Pengo (freeware) [file-hunter]
Pengo (demo) [Paxanga Soft]
Penpen Bubble [N.I]
Pointless Fighting [msxdev Compo]
Police Force 2 (English) [MRC …
=> msx2_cart.xml: Added 53 items, 42 working.

src/devices/cpu/sh/sh.cpp, src/devices/cpu/sh/sh.h, src/devices/cpu/sh/sh2.cpp, src/devices/cpu/sh/sh2.h, src/devices/cpu/sh/sh2fe.cpp, src/devices/cpu/sh/sh3comn.cpp, src/devices/cpu/sh/sh4.cpp, src/devices/cpu/sh/sh4.h, src/devices/cpu/sh/sh4comn.cpp, src/devices/cpu/sh/sh4comn.h, src/devices/cpu/sh/sh4dmac.cpp, src/devices/cpu/sh/sh4fe.cpp, src/devices/cpu/sh/sh7021.cpp, src/devices/cpu/sh/sh7021.h, src/devices/cpu/sh/sh7604.cpp, src/devices/cpu/sh/sh7604.h, src/devices/cpu/sh/sh7604_bus.cpp, src/devices/cpu/sh/sh7604_sci.cpp, src/devices/cpu/sh/sh7604_sci.h, src/devices/cpu/sh/sh7604_wdt.cpp, src/devices/cpu/sh/sh_dasm.cpp, src/devices/cpu/sh/sh_fe.cpp, src/mame/casio/casloopy.cpp
src/devices/sh: Numerous improvements [Ryan Holtz, Phil Bennett]
- General cleanup
- Renamed SH2A to SH7021
- Added (rudimentary) SH7021 DMA, timers and GPIO, and logging for the rest
- Fix NMIs occurring in a delay slot (interpreter only)
=> src/devices/sh: Numerous improvements [Ryan Holtz, Phil Bennett]

src/mame/mame.lst, src/mame/misc/vamphalf.cpp
Solitaire (version 2.5) [Recreativas.org, Brito_cat]
=> misc/vamphalf.cpp: Dumped and added a new game: 'Solitaire'

src/mame/mame.lst, src/mame/subsino/subsino.cpp
New HUNTer (bootleg, set 2) [Taksangs]
=> subsino/subsino.cpp: Dumped and added another New HUNTer set (as MNW)

hash/msx2_cart.xml
Aleste (Woomb) [file-hunter]
Arkanoid 2 (Korea) [file-hunter]
Ashguine - Fukushuu no Honoo (Japan, alt 2) [file-hunter] 
Daisenryaku MSX2 (Japan, alt) [file-hunter]
Gekitotsu Pennant Race 2 (Japan, sample) [file-hunter]
Hydlide 3 - The Space Memories (Woomb) [file-hunter]
Alien 8 Remake [file-hunter]
Los Amores de Brunilda (v1.01) [file-hunter]
Los Amores de Brunilda (v1.0) [file-hunter]
Barbarian the Duel [MSXdev]
Bomb Jack [file-hunter]
Bomb Jack (alt) [file-hunter]
Booming Boy (demo) [MSX Area]
Bubble Dream [MRC Tenliner Challenge]
DIM X (demo) [file-hunter]
Equivocal (v1.5) [Passion MSX2 Contest]
Equivocal (v1.0) [Passion MSX2 Contest]
Gold Fan [N.I]
Highway Fighter (demo) [file-hunter]
Inferno [msxdev Compo]
Jailbreak …
=> msx2_cart.xml: Added 31 items, 29 working.

hash/gx4000.xml
=> gx4000.xml: Metadata cleaning

src/mame/mame.lst, src/mame/misc/majorpkr.cpp
Super Yutnori (bootleg of Major Poker) [Taksangs]
=> Dumped an added a Korean Major Poker bootleg

hash/spectrum_betadisc_flop.xml
Carlos Michelis (demo) [Spectrum Computing]
Dune II - Battle for Arrakis (Demige) [Spectrum Computing]
Dune II - Battle for Arrakis (Perestroika Software) [Spectrum Computing]
Ghastly Getaway Dizzy (English) [Spectrum Computing]
Ghastly Getaway Dizzy (Russian) [Spectrum Computing]
Redshift (v1.1) [Spectrum Computing]
Thieves School (demo) [Spectrum Computing]
Turbo the Tortoise - 30th Anniversary Edition [Spectrum Computing]
=> spectrum_betadisc_flop.xml: Added 8 working items

src/mame/mame.lst, src/mame/subsino/subsino.cpp
=> subsino/subsino.cpp: Partially dumped and added a new gambling game

src/mame/igs/goldstar.cpp, src/mame/mame.lst
=> igs/goldstar.cpp: Dumped and added an "El Dorado" clone named "Suns Pecker"

src/mame/misc/atronic.cpp
While at it.. also add some notes about sucessors to CashLine as well...
=> misc/atronic.cpp: Added basic notes about the Atronic CashLine and successors

src/mame/subsino/subsino.cpp
----------------------------------------
Seven Land [Taksangs]
I've been playing for a while and I'd say it works ok. There's a gray stripe on the title screen, probably hiding the copyright text.
=> subsino/subsino.cpp: Dumped and added the "Seven Land" missing ROMs [Taksangs]

src/mame/edevices/twins.cpp, src/mame/mame.lst
Spider (Buena Vision, with nudity) [jordigahan, ClawGrip]
Also reformatted single line comments.
=> Dumped and added a version of 'Spider' with nudity

hash/rx78_cart.xml, hash/rx78_cass.xml
New working software list item
Yellow Cab [Gaming Alexandria]
* Added additional load instructions and alternate titles.
=> rx78_cass.xml: New working software list item

hash/oric1_cass.xml
Rename: questof -> grail
Rename: bataille -> guerrecl_a
Galaxy 5 [The Oric Site]
Le General [The Oric Site]
Godilloric (Oric-1/Atmos release) [The Oric Site]
Godilloric (Oric-1 release) [The Oric Site]
Guerre des Couleurs [The Oric Site]
The Quest of the Holy Grail (alt) [The Oric Site]
Gencar [The Oric Site]
=> oric1_cass.xml: Added 6 working items + 1 not working

hash/easy_karaoke_cart.xml, hash/ekara_japan_bh.xml, hash/nes_vt_cart.xml, src/mame/mame.lst, src/mame/nintendo/nes_vt02_vt03.cpp, src/mame/nintendo/nes_vt09.cpp, src/mame/skeleton/easy_karaoke.cpp, src/mame/tvgames/elan_ep3a19a.cpp, src/mame/tvgames/elan_eu3a05.cpp, src/mame/tvgames/elan_eu3a05vid.cpp, src/mame/tvgames/elan_eu3a05vid.h, src/mame/tvgames/generalplus_gpl16250_spi_direct.cpp, src/mame/tvgames/generalplus_gpl32612.cpp, src/mame/tvgames/spg29x.cpp, src/mame/tvgames/spg2xx.cpp, src/mame/tvgames/trkfldch.cpp
Working Additions
My Arcade Plug And Play 220 Game Retro Controller (DGUN-2959) [Team Europe, ChinnyVision]
Super TV Air Jet 6-in-1 (Lexibook Junior) [Team Europe, David Haywood]
88-in-1 Joystick [Team Europe, David Haywood]
Wireless Boxing (PAL, Play Vision) [Team Europe, David Haywood]
Motorcycle 30-in-1 [Team Europe, David Haywood]
Game Zone II 128-in-1 [Team Europe, David Haywood]
Not Working Additions
Zone Family Fit [Team Europe, David Haywood]
Dance Dance Revolution - Broadwalk Arcade [wai-3-love]
TV Sports Plug & Play 5-in-1 (JG7000) [Team Europe, David Haywood]
Kidizoom Connect (Germany, pink camera) [Team Europe]
Kidizoom (Germany, blue camera) [Team Europe]
Sudoku TV Game (PAL, 2 players) [Team Europe, David Haywood]
Virtual Football …
=> Plug and Play additions (across various platforms)

src/mame/subsino/subsino.cpp
Also added notes about known issues
=> subsino/subsino.cpp: Demote "Seven Land" to MACHINE_IMPERFECT_GRAPHICS | MACHINE_NOT_WORKING

src/mame/igs/goldstar.cpp, src/mame/igs/goldstar.h, src/mame/mame.lst
Animal House (V1.0, set 2) [Taksangs]
Also renamed "sunspckr" to "animalhs".
=> Dumped and added a new "Animal House" set

src/mame/galaxian/galaxian.cpp, src/mame/mame.lst
Aracnis (bootleg of Scorpion on Moon Cresta hardware, set 2) [Ricardo - Factory Arcade, Recreativas.org]
=> galaxian/galaxian.cpp: Dumped and added (MNW) a new Aracnis set

src/mame/galaxian/galaxold.cpp, src/mame/mame.lst
-------------------------------------------
Scrabble (Spanish bootleg of Scramble) [Ricardo - Factory Arcade, Recreativas.org]
=> galaxian/galaxold.cpp: Dumped and added a new Scramble bootleg

src/mame/dataeast/astrof.cpp, src/mame/mame.lst
Astro Fighter (Taito) [David Bosque, ClawGrip]
=> New working clones - Astro Fighter (Taito) 

src/mame/seibu/goodejan.cpp
goodejan.cpp: Fix sprite coordinate for goodejan, Use single-pass sprite rendering
=> goodejan.cpp: Update sprite rendering

src/mame/mame.lst, src/mame/nintendo/nes_clone.cpp, src/mame/nintendo/nes_vt02_vt03.cpp, src/mame/nintendo/nes_vt_soc.cpp, src/mame/nintendo/nes_vt_soc.h
Noddy's TV Console [David Haywood, Team Europe]
Racing Challenge - 8 Games In 1 [David Haywood, Team Europe]
- Noddy's TV Console has no sound, not sure if there's extra hardware
=> New working systems (plug & play)

src/mame/itech/itech8.cpp, src/mame/itech/itech8.h, src/mame/itech/itech8_m.cpp, src/mame/itech/itech8_v.cpp
itech8.cpp: Fix logging, Use shorter type values
=> itech8.cpp: Split class related to sensor hardware and timer

hash/spectrum_betadisc_flop.xml
Aggressor (Russian) [Spectrum Computing]
Aggressor (English, demo version) [Planeta Sinclair]
Ammytris [Spectrum Computing]
Dizzy and the Mushrooms Pie (English) [Spectrum Computing]
Dizzy and the Mushrooms Pie (Russian) [Spectrum Computing]
Dizzy and the Mystical Letter (English) [Spectrum Computing]
Dizzy and the Mystical Letter (Portuguese) [Spectrum Computing]
Dizzy and the Mystical Letter (Russian) [Spectrum Computing]
Doom Pit [Spectrum Computing]
Doom Pit (Zankle Soft) [Spectrum Computing]
Elite Legend (English) (mod of Elite) [Spectrum Computing]
Elite Legend (Russian) (mod of Elite) [Spectrum Computing]
Mighty Final Fight (v1.1, alt) [Spectrum Computing]
R-Type (mod) [Spectrum Computing]
Regulus …
=> spectrum_betadisc_flop.xml: Added 22 working items

src/mame/mame.lst, src/mame/pinball/recel.cpp
Black Magic [STR Pinball, Recreativas.org]
=> pinball/recel.cpp: Dumped and added "Black Magic"

hash/casio_rompack.xml
-------------------------------------------------
casio_rompack.xml: Rock On (RO-255), Latin Hits (RO-258), Music Collection (RO-260), Pop Selection (RO-261), Country Greats (RO-262), Pop Superstars (RO-265), Christmas (RO-270), Rock & Roll Classics (RO-272), Hot Pop & Rock (RO-274), T.V. Tunes (RO-276), Great Standards / Jazz Standards (RO-355), Popular Hindi Film Songs (RO-454), Family Songs (RO-554) [TolaemonM, ICEknight, ClawGrip]
=> casio_rompack.xml: Dumped and added more cart dumps

src/mame/mame.lst, src/mame/subsino/subsino.cpp
New HUNTer (bootleg, set 3) [Taksangs]
=> subsino/subsino.cpp: Dumped and added a new 'New HUNTer" set

src/mame/igs/goldstar.cpp, src/mame/mame.lst
Animal House (set 3) [Taksangs, charlie]
Also reformatted the single line comments on the GAME/GAMEL macros section.
I've marked the game as CNW because I really don't know how to play these games, so I can't fully test it.
=> igs/goldstar.cpp: Added, as clone not working, a third Animal House set

src/mame/misc/majorpkr.cpp
=> misc/majorpkr.cpp: Add two PLD dumps to 'syutnori' [Taksangs]

src/mame/mame.lst, src/mame/namco/rallyx.cpp
Rally X (Video Game bootleg) [Ricardo Factory Arcade, Recreativas.org]
=> namco/rallyx.cpp: Added a Spanish bootleg of Rally X

src/mame/mame.lst, src/mame/nintendo/spacefb.cpp
Red Bird (bootleg of Space Firebird) [Recreativas.org]
Also fix indentation and comments capitalization.
=> nintendo/spacefb.cpp: Add a Spanish Space Firebird bootleg clone

hash/ibm5170_cdrom.xml
5 Plus One: Pack 12 - Ghostbusters II [Redump]
Brutal: Paws of Fury (Europe) [Redump]
Darkseed (Germany, Action Sixteen release) [Redump]
Dune (Europe, White Label release) [Redump]
Dune II - Battle for Arrakis (Netherlands) [Redump]
Dune II - Battle for Arrakis (Germany, PC Games Collection 2 release) [Redump]
Dune II - The Building of a Dynasty (USA, Gold Medal 12 CD Pack) [Redump]
Fables & Fiends - Book Three: Malcolm's Revenge (Europe, Japan) [Redump]
Fables & Fiends - Book Two: The Hand of Fate (UK, Sold Out release) [Redump]
Jurassic Park (Europe) [Redump]
Jurassic Park (Germany) [Redump]
Jurassic Park (USA) [Redump]
Star Control [Redump]
Stellar 7 (USA) [Redump]
Stellar 7 (USA, alt) [Redump]
The Cool …
=> ibm5170_cdrom.xml: Added 18 working items + 3 not working

hash/gjrstar.xml, src/mame/mame.lst, src/mame/vtech/geniusjr.cpp
Precomputer Electronik (Russia) [murgatroid_79]
------------------------------------------------
gjrstar.xml: Matematika - Podarok Pervoklassniku, Narodnyye Zagadki, B Poiskakh Dukhovnykh Sokrovishch [murgatroid_79]
=> vtech/geniusjr.cpp: Dumped and added a Russian 'Talking Whiz-Kid Animated' clone  with three carts

hash/zx81_cass.xml
- AMSAT AMS-81 Tracking System (Version N5BF 1.4) [Sarah Rose Giddings, ICEknight, retroLEL]
Also: Added general loading instructions for the ZX81 and other info, made entry `8progs` a bit more complete and correct.
=> zx81_cass.xml: New working entry

src/mame/mame.lst, src/mame/pinball/recel.cpp
Screech (1 player) [pps4.fr, Recreativas.org]
Also documented that there are two different BIOS, and create the placeholders for both.
=> pinball/recel.cpp: Added the 1 player version of Screech and documented the diferent BIOSes

hash/x68k_flop.xml
Lowercase on descriptive words ("Alt", "Demo", "Prototype", etc...)
=> x68k_flop.xml: Metadata cleanings

hash/sega_beena_cart.xml
New working software items (sega/sega_beena_cart.xml)
Soreike! Anpanman Hajimete Kaketa yo! Oboeta yo! Hiragana Katakana: 50-on Board Kinou-tsuki (Rev. S-100002-1000) [TeamEurope]
New software items marked not working (sega/sega_beena_cart.xml)
Kodai Ouja Kyouryuu King D-Kids Adventure: Dino Slash! Kyouryuu Battle!! [TeamEurope]
=> sega/sega_beena_cart.xml: Add 2 software items (1 working).

hash/msx2_cart.xml, scripts/src/bus.lua, src/devices/bus/msx/cart/cartridge.cpp, src/devices/bus/msx/cart/fs_sr021.cpp, src/devices/bus/msx/cart/fs_sr021.h, src/devices/bus/msx/cart/slotoptions.cpp, src/devices/bus/msx/cart/slotoptions.h
FS-SR021 MSX2 Word Processor (Japan) [file-hunter]
=> msx2_cart.xml: Add 1 not working item

hash/msx2_flop.xml
Renamed Disc Station Special 2 (Japan) to Disc Station Special Shoka (Japan).
Renamed Pumpkin Adventure III (Japan) to Pumpkin Adventure III (Netherlands).
Renamed Quiz! Atatchatte 25% (Japan) to Quiz! Atatchatte 25% (Japan, demo).
Renamed Quiz! Atatchatte 25% (Japan, alt) to Quiz! Atatchatte 25% (Japan, demo, alt).
Replaced Disc Station Deluxe 1 (Japan) with a better dump. [file-hunter]
Replaced Poyo Poyo Life (Japan) with a better dump. [file-hunter]
Replaced Poyo Poyo Life II (Japan) with a better dump. [file-hunter]
Replaced Pumpkin Adventure - The Quest for the Holy Grail (Netherlands) with a better dump. [file-hunter]
Replaced Pumpkin Adventure II (Netherlands) with a better dump. [file-hunter]
Removed Pumpkin Adventure - The Quest for the Holy Grail (Netherlands, alt) and Pumpkin …
=> msx2_flop.xml: Added 33 items, 32 working.

src/mame/taito/darius.cpp, src/mame/taito/opwolf.cpp, src/mame/taito/pc080sn.cpp, src/mame/taito/pc080sn.h, src/mame/taito/rastan.cpp, src/mame/taito/rbisland.cpp, src/mame/taito/topspeed.cpp
taito/rastan.cpp: Set "bootleg" manufacturer string for bootleg set
=> taito/pc080sn.cpp: Use device_gfx_interface for gfx decoding, Reduce duplications, Minor cleanups

hash/msx2_flop.xml
Replaced Disc Station Deluxe 3 (Japan) with a better dump. [file-hunter]
Replaced Madonna no Yuuwaku (Japan) with a better dump. [file-hunter]
Replaced MSX Spring (Japan, cracked) with a better dump. [file-hunter]
Replaced New Adam & Eve (Japan) with a better dump. [file-hunter]
Construction Tool Meizu-kun (Japan) [file-hunter]
Jangou 1 (Japan) [file-hunter]
El Mago de Oz (Spain) [file-hunter]
Mahjong Shikaku Gaiden Hana no Momoko-gumi! (Japan) [file-hunter]
Master of Monsters Map Collection (Japan) [file-hunter]
MSX Free Software 100 (Japan) [file-hunter]
MSX Free Software 100 Lot.2 (Japan) [file-hunter]
MSX Magazine 5 Tsuki-gou Program Service (Japan, 1991) [file-hunter]
MSX Magazine 6 Tsuki-gou Program Service (Japan, …
=> msx2_flop.xml: Added 41 items, replaced 4 items.

hash/coleco.xml
New working software list items (coleco.xml)
Masters of the Universe: The Power of He-Man (prototype, hacked) [AtariAge]
=> coleco.xml: Added a prototype.

hash/megadriv.xml
Affinity Sorrow (demo) [Second Dimension]
Alien Cat 2 [No-Intro]
Alien Cat 2 (demo) [No-Intro]
Alter Ego - Remastered [RetroSouls]
Arkagis Escape (rev. WX - trial version) [Sik]
Arkagis Escape (rev. ZZ - trial version) [Sik]
Arkagis Escape (rev. YW - trial version) [Sik]
Arkagis Revolution (rev. 01) [No-Intro]
Arkagis Revolution (rev. 00 - trial version) [No-Intro]
Arkagis Revolution (rev. WX - trial version) [No-Intro]
Arkagis Revolution (rev. XZ - trial version) [No-Intro]
Arkagis Revolution (rev. YX - trial version) [No-Intro]
Arkagis Revolution (rev. YZ - trial version) [No-Intro]
Arkagis Revolution (rev. ZW - trial version) [No-Intro]
Astebros (demo v1.1) [NeoFID Studios]
Astebros (demo v2.1, English) …
=> megadriv.xml: Added 104 working items + 4 NOT working

hash/fmtowns_flop_orig.xml
D-Return [cyo.the.vile]
Daifugou Gakuen (v1.1) [cyo.the.vile]
Misty 2 [cyo.the.vile]
Present 2 [cyo.the.vile]
=> fmtowns_flop_orig.xml: 4 new dumps

src/lib/util/cdrom.cpp
Stripping pregaps breaks reversibility of Redump's Dreamcast CUE/BIN, and potentially deletes important data, these gaps are not always blank.
=> util/cdrom.cpp: Don't strip pregaps from Redump GD-ROM files

src/devices/bus/a2bus/vistaa800.cpp
The schematic turned up after the original commit, so I was able to address the TODO items.
- dma read has priority if both read and write are enabled.
- the side select bit in the status reg is connected to the twosided signal from the drive, and not from the sso signal from the fdc.
=> bus/a2bus/vista800.cpp: update dma priority and side select status

hash/msx2_flop.xml
Removed Estland Monogatari - Estland Campaign (Japan, alt Game Disk): has save data.
Replaced DuckTales (Netherlands) with a better dump and renamed to DuckTales (Dutch). [file-hunter]
Daisenryaku II - Campaign Version Customer Kit (Japan) [file-hunter]
Daisenryaku Map Shuu (Japan) [file-hunter]
Dante Yuushuu Sakuhin Cross Kingdom (Japan) [file-hunter]
Derringer (Japan) [file-hunter]
Disk Version Namcot Game Series 1 (Japan) [file-hunter]
Disk Version Namcot Game Series 2 (Japan) [file-hunter]
Dragonworld (Spain) [file-hunter]
Ease - Philips Desktop v1.2 (Europe) [file-hunter]
Entasis (Japan) [file-hunter]
Entführer Yousei Yuukai Jiken (Japan) [file-hunter]
Fastan (Netherlands, v1.01) [file-hunter]
Fistan (Netherlands, v2.05) …
=> msx2_flop.xml: Added 50 items, 48 working. Replaced 1 item. Removed 1 item.

src/mame/aristocrat/aristmk7.cpp, src/mame/mame.lst
Aristocrat MK-7 BIOS [Guru]
Lucky 88 (Aristocrat MK-7) [dam0]
=> Placeholder driver for Aristocrat MK-7

hash/neogeo.xml
Looptris [Blastar]
Looptris Plus [Blastar]
NeoTRIS [Chips on Steroids]
=> neogeo.xml: Added 3 working items

hash/neocd.xml
Bang Bang Busters [Redump]
Looptris [Blastar]
Looptris Plus [Blastar]
Xeno Crisis [Redump]
=> neocd.xml: Added 3 working items + 1 NOT working

src/mame/handheld/hh_sm510.cpp
This change fixes the model number for Tiger MC Hammer: U Can't Touch This.
The correct model number is `7-865` and has been verified by checking images of the unit (and its package) online (i.e. https://i.ebayimg.com/images/g/7lIAAOSw67VhizkM/s-l1600.jpg).
The model number that was previously set (`7-863`) is actually the model number for Tiger Pit Fighter.
=> tmchammer: correct model number

hash/videopac.xml
Replaced "US" abbreviation by "USA"
=> videopac.xml: Metadata cleaning

hash/x68k_flop.xml
Be Rain [Shentok]
Akazukin Cha Cha no Chotto dake yo - Otameshi Plus Alpha ver 0.53 [Shentok] 
Prote Pruste [Tahiti Cartago]
=> x68k_flop.xml: add three dumps from original disks

hash/rainbow.xml
rainbow: WordPerfect Version 4.0 [glencanyon]
=> hash/rainbow.xml: Add WordPerfect 4.0

hash/ibm5170.xml
Front Page Sports: Baseball '94 [Total DOS Collection]
Front Page Sports: Baseball '94 - Legends and Stadiums Expansion [Total DOS Collection]
Harpoon II [Total DOS Collection]
Harpoon II - BattleSet 2: WestPac [Total DOS Collection]
Harpoon II - BattleSet 3: Cold War [The Good Old Days]
International Tennis Open [Total DOS Collection]
Added some metadata info (region, language, etc)
=> hash/ibm5170.xml: Added 6 working items

hash/snes.xml
Aero the Acro-Bat 2 (prototype 19940808) [Hidden Palace]
Alien Cat 2 (demo) [PSCD Games]
Animaniacs (prototype 19940611) [Hidden Palace]
Apocalypse II (Europe, prototype 19971028) [Hidden Palace]
Arcade's Greatest Hits - The Atari Collection 1 (prototype 19970411) [Hidden Palace]
Arcade's Greatest Hits - The Atari Collection 1 (Centipede prototype 19970211) [Hidden Palace]
Best of the Best - Championship Karate (prototype) [Hidden Palace]
Classic Kong [No-Intro]
Classic Kong Complete (v2.0) [No-Intro]
Classic Kong Complete (v2.01) [No-Intro]
Creepy Bird [No-Intro]
Creepy Bird (v1.02, digital release) [No-Intro]
Creepy Bird (v1.02, Retro-Bit Generations release) [No-Intro]
Dottie - dreads nought - [No-Intro] …
=> snes.xml: Added 52 working items + 2 NOT working

hash/apple2_flop_clcracked.xml, hash/apple2_flop_orig.xml, hash/apple2gs_flop_clcracked.xml, hash/apple2gs_flop_orig.xml
Metadata cleanups and parent/clone relationships.  Renamed sets for consistency between software lists and other dumps.
New working software list items (apple2_flop_clcracked.xml) 
A Christmas Adventure (version 2.0) (4am crack)
Ace Detective (revision 3) (4am crack)
ACT Preparation Series (version 1984) (4am crack)
Adventures in Problem Solving: A Trip to London (4am crack) 
Adventures in Problem Solving: Alice's Adventure in Numberland (4am crack)
Adventures in Problem Solving: Marathon (4am crack) 
Adventures in Problem Solving: The Treasure of Forest Isle (4am crack) 
Alfred's Music Achievement Series: Level I (4am crack) 
Algebra Volume 3 (revision 4, 1984) (Britannica) (4am crack) 
Aliencounter and Face Flash (revision 2) (4am crack) 
Alligator Mix …
=> Apple II added 240 (238 working 2 not working), removed 10

src/devices/machine/sa1110.cpp, src/devices/machine/sa1110.h, src/devices/machine/sa1111.cpp, src/devices/sound/uda1344.cpp, src/mame/hp/jornada.cpp, src/mame/sharp/zaurus.cpp
-sa1110.cpp: Re-wrote to use map()-style register handlers. [Ryan Holtz]
-jornada.cpp: Hooked up entire keyboard mapping. [Ryan Holtz]
=> Cleaned up SA-1110 device to use map() handlers

src/mame/apple/apple2e.cpp
This is a minor edit that removes an inadvertently duplicated line of code.
=> apple/apple2e.cpp: Remove duplicate line

src/mame/mame.lst, src/mame/phoenix/phoenix.cpp
Phoenix (bootleg) [Recreativas.org]
=> phoenix/phoenix.cpp: Add a new Phoenix bootleg

hash/sega_beena_cart.xml
New working software items (sega/sega_beena_cart.xml)
Pururun! Shizuku-chan Asonde Tanoshiku Nouryoku Up [TeamEurope]
Taiko no Tatsujin Ongaku Lesson [TeamEurope, QUFB]
=> sega/sega_beena_cart.xml: Add 2 software items

src/mame/galaxian/galaxian.cpp, src/mame/mame.lst
Vuelo Espacial (Spanish bootleg of UniWar S) [Jorge Silva, Arnaldo Lopes]
=> galaxian/galaxian.cpp: Add a Spanish UniWar S clone from Centromatic

src/mame/mame.lst, src/mame/pinball/recel.cpp
Space Game (Bingo 6+1) [BonelessChicken, Recreativas.org]
Also fix notes.
=> pinball/recel.cpp: Add 'Space Game (Bingo 6+1)'

src/devices/cpu/z180/z180op.hxx, src/devices/machine/ldv1000hle.cpp
cpu/z180/z180op.hxx: Remove extra semicolon
machine/ldv1000hle.cpp: Remove extra semicolon
=> Remove some extra semicolons

hash/msx1_cart.xml
Hotbit HB-8000 Demo (Brazil) [file-hunter]
Ligue-se ao Expert (Brazil) [file-hunter]
Magical Tower Adventure [MSXdev]
Mood Land [file-hunter]
Princess Quest [file-hunter]
=> msx1_cart.xml: Added 5 items.

hash/ekara_japan.xml, hash/ekara_japan_d.xml, hash/ekara_japan_sp.xml, src/mame/jaleco/megasys1.cpp, src/mame/mame.lst
Hachoo! (Japan) [xtrasmiley]
Dream Cartridge: Best Hit Vol.10 (Japan) (DC0006-BHT)
Dream Cartridge: Best Artist Vol.7 (Japan) (DC0008-BAT)
Enkamichi Volume 8 (Japan) (EC0058-ENK)
Super Cartridge: TV Pop Junior (Japan) (SP-06)
=> new clone + ekara softlist sets

src/mame/trs/coco12.cpp, src/mame/trs/coco12.h, src/mame/trs/coco12_m.cpp
Update deluxecoco driver with newly found ROMs and hardware information.
=> trs/coco12.cpp: Update deluxecoco driver with newly found ROMs and hardware information

src/mame/trs/coco12_m.cpp
=> coco12.cpp: Fix tiny error in RAM banking

hash/coco_cart.xml
=> hash/coco_cart.xml: correct hash for Predator

hash/gcslottv.xml, src/mame/mame.lst, src/mame/nintendo/nes_clone.cpp, src/mame/skeleton/hudson_poems.cpp, src/mame/tvgames/spg2xx.cpp, src/mame/tvgames/spg2xx.h, src/mame/tvgames/xavix.cpp
-------------
Tokyo Friend Park 2 [David Haywood, TeamEurope]
--------------
Dora the Explorer - Dora TV Globe-Trotter (France) [David Haywood, TeamEurope]
------------
Gu~Chocolate Lantern Spoo Daisuki! Playmat [David Haywood, TeamEurope]
Croaky Karaoke 16-in-1 [David Haywood, TeamEurope]
Lexibook Junior My 1st Drawing Studio [David Haywood, TeamEurope]
gcslottv.xml: Beast King Junior [David Haywood, Team Europe]
=> new WORKING + NOT WORKING plug and play machines

hash/pc1512_hdd.xml
pc1512hd20 uses hdc so this will also make it available for pc1512 w/ hdc
=> pc1512_hdd: Change interface so it's accessible from internal UI when running pc1512hd20

hash/fmtowns_cd.xml
- Lowercase on descriptive words
- Fixed parent/cloneof relationships
=> fmtowns_cd.xml: Metadata cleanups

hash/a2600.xml
Hobo [Atarimania]
R2D Tank [Atarimania]
Spiders [Atarimania]
=> a2600.xml: Added 2 working items + 1 not working

hash/msx1_flop_525.xml
Corrected Informatica to Informática in publisher names.
Updated some usage instructions.
Poster Maker (Brazil) [file-hunter]
Professional Paint (Brazil) [file-hunter]
Professional Stripes (Brazil) [file-hunter]
Retrato Falado (Brazil) [file-hunter]
SuperCalc 2 (Brazil) [file-hunter]
Gradius System (Brazil) [file-hunter]
=> msx1_flop_525.xml: Added 6 items, 5 working.

hash/cdi.xml
Hotel Mario (prototype v0.09, 19931123) [redump.org]
=> cdi.xml: Added a Hotel Mario prototype

src/mame/mame.lst, src/mame/subsino/subsino.cpp
New Animal Animal [Taksangs, charlie]
=> subsino/subsino.cpp: Add a new Korean game from 'Hyoja Game'

src/mame/casio/pickytlk.cpp, src/mame/mame.lst
Casio Super Picky Talk - Forest Of Gurutan (JD-370) [QUFB]
=> casio/pickytlk.cpp: Add new not working driver

src/mame/galaxian/galaxian.cpp, src/mame/mame.lst
Diviertate Galaxia (Multivideo, Spanish bootleg of Galaxian) [Juan Romero, Recreativas.org]
=> galaxian/galaxian.cpp: Added a Spanish bootleg of Galaxian from 'Multivideo'

hash/msx2p_cart.xml
msx2p_cart.xml: Added 3 items, 2 working.
Ghostly Manor [9958 crew]
Nothing Thing [msxdev Compo]
Knit Designer (Japan) [Takamichi]
=> msx2p_cart.xml: Added 3 items, 2 working.

hash/sms.xml
Arcade Volleyball [SMS Power!]
Blast Arena [SMS Power!]
Extreme Volleyball Infernal League (v1.0.2) [SMS Power!]
Extreme Volleyball Infernal League (v1.0.5) [SMS Power!]
Extreme Volleyball Infernal League (v1.0.6) [SMS Power!]
Extreme Volleyball Infernal League (v2.0.21, demo) [raphnet]
Fantasy Zone: The Maze (prototype) [SMS Power!]
Jewel Stone (demo) [SMS Power!]
Lucky Penguin (v1.0) [SMS Power!]
Lucky Penguin (v1.1) [SMS Power!]
Pitman (v1.02) [SMS Power!]
Pitman (v1.03) [SMS Power!]
SKBN (v1.0) [SMS Power!]
SKBN (v1.1) [SMS Power!]
SKBN (v1.2) [SMS Power!]
SKBN (v1.3) [SMS Power!]
SKBN (v1.4) [SMS Power!]
Wing Warriors [SMS Power!]
Wing Warriors (fix) [SMS Power!]
=> sms.xml: Added 19 working items

src/mame/mame.lst, src/mame/skeleton/pullttrigger.cpp
Pull The Trigger [Arcade Planet, Recreativas.org]
=> Add a skeleton for a new PC-based game named 'Pull The Trigger'

hash/snes_bspack.xml
Lowercase on descriptive words ("Bad Header", "Hacked", "Alt", etc...)
=> snes_bspack.xml: Metadata cleanups

src/mame/capcom/vulgus.cpp, src/mame/mame.lst
1942 (Itisa bootleg) [Recreativas.org]
=> capcom/vulgus.cpp: Add a 1942 bootleg from Itisa (not working)

hash/snes.xml
New working software list items (snes.xml)
Rockman's Soccer (Japan, sample) [C. Davis]
=> snes.xml: Added a prototype.

hash/sms.xml
Gemitas [SMS Power!]
Sydney Hunter and the Sacred Tribe [No-Intro]
Renamed set [jewelstn] to [jeweljon] and renamed description to "Jewel Jones"
=> sms.xml: Added 2 working items

src/devices/bus/hp9845_io/hp9885.cpp, src/devices/bus/hp9845_io/hp9885.h
Hi,
this PR is for the implementation of format command I added to HP9885 drive HLE.
Thanks.
--F.Ulivi
=> HP9885: Format command implemented

hash/msx2p_flop.xml
FS-A1FX (Japan) [file-hunter]
FS-A1WSX (Japan) [file-hunter]
FS-A1WX (Japan) [file-hunter]
HB-F1XV (Japan) [file-hunter]
PHC-70FD/FD2 (Japan) [file-hunter]
Game Programming Tool HB-F1XDJ Sen'you (Japan) [file-hunter]
=> msx2p_flop.xml: Added 6 items.

src/mame/namco/namcos12.cpp
Removed Um Jammer Lammy from the list of wanted games
=> NamcoSystem12- remove note in list of wanted games

hash/saturn.xml
- Fixed "raymanu" and "raymanp" cloneof relationship
- Lowercase on descriptive words on "crimewavd", "bugud", "panzerud", "raymanud"
=> saturn.xml: Metadata cleanups

src/mame/mame.lst, src/mame/midway/astrocde.cpp
Gorf (Irecsa license, Spanish) [Recreativas.org]
=> midway/astrocde.cpp: Add a Irecsa licensed Spanish set of Gorf 

src/mame/namco/namcos12.cpp
Added a small description of Teckno Werk, a video, and its last known whereabouts
=> Update notes on Teckno Werk in namcos12.cpp

src/devices/bus/msx/slot/disk.cpp, src/devices/bus/msx/slot/disk.h
Add register mirrors.
Add read back of rom bank.
Add media change and some unknown registers.
=> bus/msx/slot/disk.cpp: Small improvement to Turbo-R disk interface.

hash/coleco.xml
Anti-Environment Encounter [ColecoVision Addict]
Arno Dash [ColecoVision Addict]
Bank Panic [ColecoVision Addict]
Burn Rubber [ColecoVision Addict]
C-So! [ColecoVision Addict]
Caterpillar S.O.S. [ColecoVision Addict]
Champion Pro Wrestling [ColecoVision Addict]
Diamond Dash II [ColecoVision Addict]
Flapee Byrd [ColecoVision Addict]
Klondike Solitaire (v1.0) [ColecoVision Addict]
Kobashi [ColecoVision Addict]
Mahjong Solitaire (v1.0) [ColecoVision Addict]
Mario Bros. [ColecoVision Addict]
Minesweeper (v1.0) [ColecoVision Addict]
Mr Chin [ColecoVision Addict]
Pegged (v1.0) [ColecoVision Addict]
Pillars [ColecoVision Addict]
Pitman [ColecoVision Addict]
Pooyan [ColecoVision Addict]
Pyramid Warp + Battleship …
=> coleco.xml: Added 27 working items + 7 not working

src/mame/midway/atlantis.cpp, src/mame/midway/midtunit.cpp, src/mame/midway/midvunit.cpp, src/mame/midway/midwunit.cpp, src/mame/midway/midxunit.cpp, src/mame/midway/midzeus.cpp, src/mame/midway/seattle.cpp, src/mame/midway/vegas.cpp, src/mame/pinball/wpc_95.cpp, src/mame/pinball/wpc_dcs.cpp, src/mame/pinball/wpc_dot.h, src/mame/pinball/wpc_s.cpp, src/mame/rare/kinst.cpp, src/mame/shared/dcs.cpp, src/mame/shared/dcs.h
Use C++ style comment for single line comments
Suppress machine().side_effects_disabled() for debugger reading Reduce hardcoded tag
Use constant and correct typename values
=> shared/dcs.cpp: Add device_mixer_interface for sound output, Cleanups:

src/mame/igs/igs009.cpp, src/mame/mame.lst
Animal House (bootleg of Jingle Bell) [Taksangs, charlie]
=> igs/igs009.cpp: Add a Jingle Bell bootleg named "Animal House"

hash/rx78_cart.xml
* Fixed names for Hamburger Shop and Tatakae! Ultraman
* Added serial and alt_title metadata where available
* Updated list of available titles
New working software list items (rx78_cart.xml)
Cannon Ball [Gaming Alexandria]
=> rx78_cart.xml: New working item added, metadata cleanup

hash/gameking.xml, hash/gameking3.xml
new SOFTWARE LIST additions
-----------
gameking.xml
4 in 1 - Three Battles + Light Sword + Risker + Metal Deform (512KB cartridge, set 2) [sCZther, SSJ, Gaming Alexandria, TeamEurope]
gameking3.xml
Diamond [sCZther, SSJ, Gaming Alexandria, TeamEurope]
Hemic Battle [sCZther, SSJ, Gaming Alexandria, TeamEurope]
(also replaced panzer dump in gameking3.xml with a new one, the old dump has a flipped bit in an unused area)
=> new SOFTWARE LIST additions (GameKing / GameKing 3)

src/mame/galaxian/galaxian.cpp, src/mame/mame.lst
Bongo (set 2) [Arcadedealer aka Edgar Solé aka Dios, Recreativas.org]
=> galaxian/galaxian.cpp: Add a new Bongo set

hash/oric1_cass.xml
New working software list addition
Rodmän [Misfit]
=> oric1_cass.xml: Added 1 working item

src/mame/galaxian/galaxian.cpp, src/mame/mame.lst
Zero Time (Spanish bootleg, set 2) [Arcadedealer aka Edgar Solé aka Dios, Recreativas.org]
=> galaxian/galaxian.cpp: Add a new Zero Time hack/bootleg

src/mame/mame.lst, src/mame/pacman/pacman.cpp
The Glob (Pac-Man hardware, set 2) [Arcadedealer aka Edgar Solé aka Dios, Recreativas.org]
=> pacman/pacman.cpp: Add a new The Glob clone on Pac-Man hardware

src/devices/sound/swp30.cpp, src/devices/sound/swp30.h, src/devices/sound/swx00.cpp, src/devices/sound/swx00.h
Just like commit 48161ce9ca, but this time for SWP30 and SWX00.
@galibert As promised! :-)
=> sound/swp30.cpp, sound/swx00.cpp: Improved DPCM sample decompression

src/mame/galaxian/galaxian.cpp, src/mame/mame.lst
Pac-Man (Video Dens, Spanish bootleg on Galaxian hardware, set 2) [Arcadedealer aka Edgar Solé aka Dios, Recreativas.org]
=> galaxian/galaxian.cpp: Add another Video Dens Pac-Man bootleg

src/mame/mame.lst, src/mame/misc/cb2001.cpp
New DongmulDongmul 2 [Taksangs, charlie]
=> misc/cb2001.cpp: Added a partial dump for 'New DongmulDongmul 2'

src/mame/mame.lst, src/mame/pinball/play_2.cpp, src/mame/pinball/recel.cpp
Antar (Recel) [Museo del Recreativo, Recreativas.org]
=> pinball/recel.cpp: Add 'Antar', the Portuguese version of "Formula 1"

hash/intvecs.xml
- Added manufacturer's name in software list name
- Lowercase on descriptive word ("Unreleased")
=> intvecs.xml: Metadata cleaning

hash/jaguar.xml
- Lowercase on descriptive words/abbreviatures ("Demo", "Rev.", "Ver.")
- Moved test result comments to `notes` tag
=> jaguar.xml: Metadata cleanups

src/mame/galaxian/galaxian.cpp, src/mame/mame.lst
Frog (Hermatic, bootleg on Galaxian hardware from Electro Game) [Arcadedealer aka Edgar Solé aka Dios, Recreativas.org]
=> galaxian/galaxian.cpp: Add a new Frogger bootleg from Hermatic

src/mame/mame.lst, src/mame/namco/sweetland4.cpp
Tairyou-Daiko 337 Byoshi [Museo del Recreativo, ClawGrip]
=> namco/sweetland4.cpp: Add 'Tairyou-Daiko 337 Byoshi' to Namco M151 PCB

hash/segaai.xml
Renamed Pinpon Music Rhythm to Pinpon Music Rhythm (1987).
Renamed Pinpon Music Melody to Pinpon Music Melody (1987).
Pinpon Music Rhythm [smspower]
Pinpon Music Melody [smspower]
Eigo no Uta [smspower]
=> segaai.xml: Add 3 not working items

src/mame/gaelco/gaelco2.cpp, src/mame/mame.lst
=> gaelco/gaelco2.cpp: Add (not working) another gambling game on Gaelco hardware

src/mame/pinball/inder.cpp
Unknown gambling game on Inder pinball hardware [Arcade Planet, Recreativas.org]
Also fixed notes about "La Rana".
=> pinball/inder.cpp: Add an unknown gambling game on Inder pinball hardware

src/mame/dataeast/ffantasy_ms.cpp, src/mame/mame.lst
Secret Agent (Modular System) [Museo del Recreativo, Recreativas.org]
=> dataeast/ffantasy_ms.cpp: Add, as not working, a bootleg of Secret Agent on Modular System

src/mame/promat/3x3puzzl.cpp
Use generic gfx decoding layouts
Use array for Tile RAM and Tilemap
Fix spacing
Reduce preprocessor defines
Fix ROM region naming
=> promat/3x3puzzl.cpp: Cleanups

src/mame/mame.lst, src/mame/tch/wheelfir.cpp
----
Power Ball (prototype) [OldComputers ES]
Kong Ball (early prototype) [OldComputers ES]
Radical Enduro (early prototype) [OldComputers ES]
=> new NOT WORKING machines (TCH Power Ball)

hash/neogeo.xml
Gladmort (demo) [PixelHeart]
NeoBlack Tiger (demo) [OzzyOuzo]
The Eye of Typhoon (alpha) [OzzyOuzo]
The Eye of Typhoon (Tsunami Edition, beta 1) [OzzyOuzo]
The Eye of Typhoon (Tsunami Edition, beta 2) [OzzyOuzo]
The Eye of Typhoon (Tsunami Edition, beta 3) [OzzyOuzo]
The Eye of Typhoon (Tsunami Edition, beta 4) [OzzyOuzo]
The Eye of Typhoon (Tsunami Edition, beta 5) [OzzyOuzo]
The Eye of Typhoon (Tsunami Edition, beta 6) [OzzyOuzo]
The Eye of Typhoon (Tsunami Edition, beta 7) [OzzyOuzo]
=> neogeo.xml: Added 10 working items

hash/aim65_cart.xml
aim65_cart.xml: Siemens PC100 BASIC [OldComputers ES]
=> aim65_cart.xml: Add 'Siemens PC100 BASIC'

src/lib/formats/fs_cbmdos.cpp
Limitations:
- Only allows writing to the first 35 tracks.
- The file type is always set to PRG.
=> lib/formats/fs_cbmdos.cpp: Add partial write support.

src/devices/bus/qbus/qbus.cpp, src/devices/bus/qbus/qbus.h, src/devices/cpu/t11/t11.cpp, src/devices/cpu/t11/t11.h
=> t11: reuse z80_daisy_chain for QBus vectored interrupts; forward INIT

src/mame/midcoin/wallc.cpp
Also reformatted single line comments
=> midcoin/wallc.cpp: Add missing PLD to Brick Blast [Arcadedealer aka Edgar Solé aka Dios, Recreativas.org]

src/mame/taito/taito_o.cpp
Added or corrected the Japanese game titles based on [the information in the TAITO AMUSEMENT CATALOG Vol.1](https://page.auctions.yahoo.co.jp/jp/auction/1125891652).
> エイビス - 22
> ベガス37 - 23
> ペアレントジャック - 24
>...
These description means below.
> Eibise - 22
> Vegas 37 - 23
> Parent Jack - 24
>...
=> taito/taito_o.cpp: Added or corrected the Japanese wording of the game titles

src/mame/mame.lst, src/mame/sigma/sigmab98.cpp
----
Gun Kids [Darksoft, TeamEurope]
=> new WORKING machine (Gun Kids - Sammy Medal game)

src/mame/heathzenith/h89.cpp, src/mame/heathzenith/intr_cntrl.cpp, src/mame/heathzenith/intr_cntrl.h, src/mame/heathzenith/mms77316_fdc.cpp, src/mame/heathzenith/mms77316_fdc.h, src/mame/heathzenith/z37_fdc.cpp, src/mame/mame.lst
- Implement MMS 77316 DD controller. 
- Add new clone of H89 'h89-mms' for Magnolia MicroSystems hardware.
=> heathkit/h89.cpp: Add Magnolia Microsystems DD controller and h89-mms system

src/mame/mame.lst, src/mame/skeleton/easy_karaoke.cpp
--------
Karaoke Station (Japan) [Team Europe, David Haywood]
=> new NOT WORKING machines (Bandai Karaoke Station)

src/mame/mame.lst, src/mame/pinball/inder.cpp
=> pinball/inder.cpp: Add a new set of "La Rana"

src/devices/bus/msx/cart/fs_sr021.cpp, src/devices/bus/msx/cart/kanji.cpp, src/mame/msx/msx.cpp, src/mame/msx/msx.h, src/mame/msx/msx2.cpp
msx/msx.cpp: Add system control register to allow switching between internal and external kanji support.
=> msx/msx.cpp: Add support to switch between internal and external kanji support.

src/mame/tch/wheelfir.cpp
I've no idea what was merged before in https://github.com/mamedev/mame/commit/5cfb1cc07607259f4c6ef3a4c4012f24ecb85dcd when https://github.com/mamedev/mame/pull/12396 got closed, but it was in no way representitive of the PR I had open, and fixed absolutely nothing.
since that got closed, this is the actual PR, again.
=> tch/wheelfir.cpp: Previous commit was the wrong version of the file, corrected.

scripts/src/cpu.lua, src/devices/cpu/z80/z80.cpp, src/devices/cpu/z80/z80.h, src/devices/cpu/z80/z80.lst, src/devices/cpu/z80/z80make.py
Update for z80 generation to support case required in #12433
Now core avoid partial generation and always build full commands list which looks cleaner based on the z80n and r800 requirements
=> cpu/z80/z80.cpp Update core generator to support r800 [holub, Wilbert Pol]

src/mame/sinclair/spec128.cpp, src/mame/sinclair/specpls3.cpp
Make border render adjustments based on latest tests
=> sinclair/spec128.cpp,sinclair/specpls3.cpp: adjust border chunk render position

hash/msxr_cart.xml
Losaben Akel (demo) [file-hunter]
MSX View (Japan, v1.21) [file-hunter]
MSX View (Japan, v1.00) [file-hunter]
Zone Terra (demo) [file-hunter]
=> msxr_cart.xml: Added 4 not working items.

hash/msx2_flop.xml
SG1000 (v0.96) [GDX]
SofaSMS [Louthrax]
=> msx2_flop.xml: Added 2 items.

hash/gamegear.xml, hash/megadriv.xml, hash/tutor.xml
Replaced countries' abbreviations
=> gamegear.xml, megadriv.xml, tutor.xml: Replaced countries' abbreviations

plugins/hiscore/hiscore.dat
=> hiscore.dat: Add delay to ballbomb/lupin3 entry to fix saved hiscore loading

src/mame/kaneko/djboy.cpp
- Use set_format for palette format, palette_device write handler for palette write
- Reduce unused constexpr value
- Make variables constant
=> kaneko/djboy.cpp: Cleanups:

src/mame/kaneko/hvyunit.cpp
- Reduce literal tag usage and runtime tag lookups
- Correct type for variables
- Initialize variables
- Fix ROM region, shared pointer naming
=> kaneko/hvyunit.cpp: Cleanups

src/devices/cpu/z80/z80.cpp, src/devices/cpu/z80/z80.h, src/devices/cpu/z80/z80.lst, src/devices/cpu/z80/z80make.py
redoable case refactoring based on https://docs.mamedev.org/techspecs/cpu_device.html
=> cpu/z80/z80.cpp: Refactor redoable case

src/devices/cpu/z80/z80.lst
Some developers faicing build failure on local. After confirmed this fix is a solution, we'll merge it.
=> cpu/z80/z80.cpp: Fix misleading-indentation

src/mame/mame.lst, src/mame/recfranco/rf51w14cg.cpp
Santa Fe Mine (set 1) [Sergio y Vicente de electronicaVyS, Recreativas.org]
Santa Fe Mine (set 2) [Sergio y Vicente de electronicaVyS, Recreativas.org]
=> recfranco/rf51w14cg.cpp: Add new slot games on similar hardware

hash/coleco_homebrew.xml
AntiAir [Inufuto]
Ascend [Inufuto]
Battlot [Inufuto]
Cacorm [Inufuto]
Cracky [Inufuto]
Guntus [Inufuto]
Hopman [Inufuto]
Yewdow [Inufuto]
=> coleco_homebrew.xml: Added 8 working items

src/mame/mame.lst, src/mame/vtech/kidsupstar.cpp
Kidi SuperStar LightShow [Arcade Hacker, ClawGrip]
=> vtech: Add a skeleton for VTech Kidi SuperStar LightShow

hash/challenge_gear_cart.xml, src/mame/bandai/wswan.cpp, src/mame/benesse/challenge_gear.cpp, src/mame/benesse/pockchal.cpp, src/mame/mame.lst
New NOT WORKING Machine
----------
Challenge Gear [TeamEurope, SSJ, Youkal3]
New NOT WORKING Software List Entries
---------
challenge_gear_cart.xml:
Challenge 6 Years [TeamEurope, SSJ, Youkal3]
- moved pockchal.cpp and the new driver to a benesse folder, as benesse had many more products
- created a separate machine for the Pocket Challenge v2, the BIOS isn't dumped, but carts aren't physically compatible with a Wonderswan even if the software is.  Makes more sense to have a driver with the borrowed Wonderswan BIOS marked as BAD_DUMP than hiding everything behind the Wonderswan itself.
=> Benesse work / new NOT WORKING Machine (Challenge Gear)

src/mame/atari/asteroid.cpp, src/mame/mame.lst
Aerolitos Espaciales [Heckler, jordigahan]
=> atari/asteroid.cpp: Add a Spanish Asteroids bootleg from Pasatiempos Laguna

hash/gameking3.xml
new WORKING software list additions
---------
gameking3.xml:
2030 [TeamEurope, SSJ, Youkal3]
=> new WORKING software list additions - GameKing3 2030

src/mame/mame.lst, src/mame/pc/cuttherope.cpp
Cut The Rope [Museo del Recreativo]
=> Add a skeleton driver for ICE's Cut The Rope (PC-based)

src/mame/mame.lst, src/mame/tvgames/spg2xx.cpp
----------
Virtual Baseball (VTG) [Sean Riddle, David Haywood]
=> new NOT WORKING machines (Virtual Baseball plug and play)

hash/carbeena.xml, src/mame/mame.lst, src/mame/sega/sega_beena.cpp
New working software items (carbeena.xml)
Car Beena Tentou-you Demo 1 [TeamEurope, QUFB]
=> sega/sega_beena.cpp, carbeena.xml: Add Car Beena and BIOS MIDI PCM ROMs

hash/alice32.xml, hash/alice90.xml, hash/nes_datach.xml
alice32.xml, alice90.xml: Lowercase on descriptive words
nes_datach.xml: Replaced countries' abbreviations
=> alice32.xml, alice90.xml, nes_datach.xml: Metadata cleanups

hash/nes.xml
nes.xml: 150 Super Cool Cards [Taksangs]
=> hash/nes.xml: Add a not working NES multigame pirate cart

src/mame/mame.lst, src/mame/tvgames/spg2xx.cpp
Virtual Tennis (VTG) [Sean Riddle, David Haywood]
=> new NOT WORKING machines - Virtual Tennis

src/mame/mame.lst, src/mame/nichibutsu/cclimber.cpp, src/mame/nichibutsu/cclimber.h, src/mame/nichibutsu/cclimber_v.cpp
Hey folks. I was granted access to a private arcade collection to repair some game boards and an unusual one caught my eye.
The game board stack was a Tehkan Swimmer, the same as one in my own collection but with modifications to the CPU and Video layers.
Using a Willem programmer I was able to read the EPROM data as 2764 and 2764 types and a grep of MAME code returned no match on the checksums.
When trying to add it to MAME it did not work when renamed as Swimmer and creating replacement EPROMs for my Swimmer game board yielded no results either.
I spent some time making technical notes from my Swimmer game board to understand the working of the board and source of the problem. These notes did not allow the game to run either but led me to see some problems with MAME and the emulation of …
=> nichibutsu/cclimber.cpp: Improves Swimmer driver and adds a new game set

src/mame/heathzenith/mms77316_fdc.cpp, src/mame/heathzenith/z37_fdc.cpp
No functional changes in this PR.
mms77316_fdc.cpp:
- Update/Add logs.
- Minor logic simplification
z37_fdc.cpp:
- display log data in hex.
=> heathzenith/mms77316_fdc.cpp,z37_fdc.cpp: Minor cleanup, improve logs.

src/devices/cpu/tms32025/tms32025.cpp, src/devices/cpu/tms32025/tms32025.h, src/mame/taito/mlanding.cpp
taito/mlanding.cpp: Use TMS32020 DSP instead TMS32025
=> cpu/tms32025.cpp: Add primary TMS32020 support

hash/apple2_flop_clcracked.xml, hash/apple2_flop_orig.xml
* apple2_flop_clcracked.xml: Added thirty-nine working dumps.
* apple2_flop_clcracked.xml: Updated one dump.
* apple2_flop_clcracked.xml: Removed three imperfect dumps.
* apple2_flop_clcracked.xml: Improved metadata.
* apple2_flop_orig.xml: Improved metadata.
New working software list items (apple2_flop_clcracked.xml)
Alpine Tram Ride (revision 0) (4am crack) [4am, A-Noid] 
Bike Hike (revision 0) (4am crack) [4am, A-Noid]
Developing Writing Skills (4am crack) [4am, txgx42, A-Noid] 
Earthquakes and Volcanoes (4am crack) [4am, txgx42, A-Noid] 
Factactics Trivia Game: Sports (4am crack) [4am, txgx42, A-Noid] 
Fantastic Animals (4am crack) [4am, A-Noid]
Kinder Critters: Letters and Patterns (4am crack) [4am, A-Noid] 
Language Activities Courseware Level 3 (4am …
=> apple2_flop_clcracked.xml: Added thirty-nine working dumps, updated one dump, removed three dumps.

src/mame/mame.lst, src/mame/skeleton/design.cpp
Vending machine model T6 [Joan RF, jordigahan]
Vending machine model T8 [Joan RF, jordigahan]
Vending machine model T12 [Joan RF, jordigahan]
Vending machine model T61 (set 1) [Joan RF, jordigahan]
Vending machine model T61 (set 2) [Joan RF, jordigahan]
=> skeleton/design.cpp: Add (not working) more Azkoyen vending machines

src/mame/heathzenith/z29.cpp
Add port definitions and memory map based on ROM listing for the terminal.
=> heathzenith/z29.cpp: Add some documentation based on ROM listing

src/mame/casio/pv1000.cpp
Casio's PV-1000 puts the border on top and bottom, not the left and right as in the previous implementation. See: https://forums.nesdev.org/viewtopic.php?p=288422#p288422
(The pixel aspect ratio is also wrong; I will submit that change in a future pull request)
=> casio/pv1000.cpp: borders are on top and bottom

src/mame/atari/atetris.cpp
Link (Korean bootleg of Atari Tetris) [Taksangs]
=> atari/atetris.cpp: Add a new Tetris Korean bootleg and redumped atetb5205 OKI ROMs

src/mame/seta/speglsht.cpp
Transparent color is wrong at title screen animation, reference: https://youtu.be/cK7mGnt6YfY?si=Ah5hC_iFS2Li7Xwl
=> speglsht.cpp: Add notes

src/mame/kaneko/snowbros.cpp, src/mame/kaneko/snowbros.h, src/mame/mame.lst
-----------
Sutjaro Haeyo Deluxe [Taksangs, David Haywood]
=> new NOT WORKING machines (Sutjaro Haeyo Deluxe)

src/mame/namco/namcos10.cpp
The real hardware checksums were verified thanks to buffi.
MAME:
Real hardware: https://imgur.com/a/1q1atDB
=> namco/namcos10: Add additional notes for Hajime no Ippo 2

hash/pc8801_flop.xml
Added parent/clone relationship between "ddash", "ddasha", "ddashb"
=> pc8801_flop.xml: Metadata fix

hash/mtx_cass.xml, hash/n64.xml, hash/snes_bspack.xml
Lowercase on descriptive words (Prototype, Rev, Alt, etc.)
=> mtx_cass.xml; n64.xml; snes_bspack.xml: Metadata cleanings

hash/ibm5170.xml
Aces of the Deep [Total DOS Collection]
Aces of the Deep: Expansion Disk [The Good Old Days]
Aces Over Europe [Total DOS Collection]
Aces Over Europe (German) [Total DOS Collection]
Arcade Pool (alt) [Total DOS Collection]
Archon Ultra [Total DOS Collection]
Blackthorne [Total DOS Collection]
Lethal Weapon [Total DOS Collection]
Lethal Weapon (Big Games) [Total DOS Collection]
Psycho Pinball [Total DOS Collection]
Sensible World of Soccer [Total DOS Collection]
Super Street Fighter II Turbo  [Total DOS Collection]
Warriors [Total DOS Collection]
Worms [Total DOS Collection]
Zoop [Total DOS Collection]
Redump software list item
Micro Machines 2: Turbo Tournament …
=> ibm5170.xml: Added 15 working items + 1 redump

src/devices/bus/hp_dio/hp98620.cpp
=> hp_dio/hp98620: use device_execute_interface (nw)

hash/hikara.xml
hikara.xml:
user5b : Hi-kara 5-song capacity user cartridge (used, with 4 songs, set 2) (Japan) [David Haywood, TeamEurope]
user5c: Hi-kara 5-song capacity user cartridge (used, with 2 songs) (Japan [David Haywood, TeamEurope]
user10a: Hi-kara 10-song capacity user cartridge (used, with 10 songs, set 2) (Japan) [David Haywood, TeamEurope]
user20a: Hi-kara 20-song capacity user cartridge (used, with 20 songs, set 2) (Japan) [David Haywood, TeamEurope]
bh6kids1: Best Hit Collection Volume 6: Kids' Song 1 [David Haywood, TeamEurope]
=> hikara.xml : add 5 carts

src/mame/igs/igs_fear.cpp
Fearless Pinocchio was licensed by American Alpha
Super Kids was licensed by Golden Dragon Amusement
Added Chinese title to superkds
=> igs_fear.cpp - Publisher licenses and Chinese title addition for superkds.

src/mame/mame.lst, src/mame/skeleton/koto_zevio.cpp, src/mame/skeleton/zevio.cpp
Dragon Ball Z x One Piece: Battle Taikan Gum-Gum no Kamehameha: Omee no Koe de Ora o Yobu (Japan) [David Haywood, Team Europe]
=> new NOT WORKING machines (DBZ One Piece)

src/mame/mame.lst, src/mame/tvgames/generalplus_gpl16250_spi.cpp
----------------------------------------------
Boku wa Plarail Untenshi Shinkansen de Ikkou! Plus (Japan) [David Haywood, Team Europe]
=> new NOT WORKING machines (Train)

hash/c128_flop.xml, hash/pet_rom.xml, hash/plus4_cart.xml, hash/vic1001_flop.xml
Lowercase on descriptive words (Alt, Version)
Replaced countries' abbreviations (Ger, Hun)
=> c128_flop.xml; plus4_cart.xml; vic1001_flop.xml; pet_rom.xml: Cleanups

hash/a2600.xml, hash/a800_flop.xml
Lowercase on descriptive words (Prototype, Light Pen, Extensions, etc.)
=> a800_flop.xml; a2600.xml: Metadata cleanings

hash/sgi_mips.xml
make partly consistent with other versions
=> hash/sgi_mips.xml: rename netbsd 2 images to allow to merge into same directory

src/mame/mame.lst, src/mame/tvgames/spg2xx.cpp, src/mame/tvgames/spg2xx.h
----------------
Drum Super Star [David Haywood, Sean Riddle, Peter Wilhelmsen]
=> new WORKING machine (Drum Super Star)

src/mame/tvgames/spg2xx_wiwi.cpp
=> spg2xx_wiwi.cpp - ddmmeg12 is also from 2007

src/mame/atari/a2600.cpp, src/mame/mame.lst
--------------
TV Boy (Nics, NTSC) [Taksangs]
=> new WORKING clones (TV Boy)

hash/sat_cart.xml, hash/sat_vccart.xml
Replaced countries' abbreviations by their full name and lowercase on descriptive words.
=> sat_cart.xml; sat_vccart.xml: Metadata cleanings

src/mame/igs/igs_fear.cpp
igs_fear.cpp : save sram/nvram, tidy up inputs (F2 service key, single button, no trackball on fearless)
=> igs/igs_fear.cpp : save sram/nvram, tidy up inputs

src/mame/layout/kn5000.lay, src/mame/mame.lst, src/mame/matsushita/kn5000.cpp
This is a much smaller pull request with a smaller amount of code, in the hope to facilitate code-reviews. Once this lands, I'll open subsequent PRs with additional chunks, to be reviewed as well.
The full wip patchset is still available at PR #11835, but that seems to be too big a fish to fry all at once...
=> Technics KN5000 musical keyboard

src/mame/mame.lst, src/mame/skeleton/marsvending.cpp
Automatic Products Vending Machine model 110 (set 1) [Joan RF, jordigahan]
Automatic Products Vending Machine model 110 (set 2) [Joan RF, jordigahan]
=> Add a skeleton driver for Mars Electronics vending machines

src/mame/konami/k573fpga.cpp, src/mame/konami/k573fpga.h
Code and research thanks to @spicyjpeg.
=> k573fpga: Implement proper MP3 decryption algorithm for ddrsbm [spicyjpeg]

hash/msx1_cart.xml
=> msx1_cart.xml: Promoted 1 item to working.

src/mame/igs/igs_m027.cpp, src/mame/igs/igs_m027_link.cpp
igs_m027.cpp - add 2 more 027A internal dumps [Guru, XingXing]
igs_m027_link.cpp - add 2 more 027A internal dumps from the link 'HOST' boards [Guru, XingXing]
=> igs_m027.cpp - add 2 more 027A internal dumps (and 2 in igs_m027_link too) [Guru, XingXing]

src/mame/cirsa/neptunp2.cpp, src/mame/mame.lst
=> cirsa/neptunp2.cpp: Add (not working) Dancing Bells (from BGT)

src/devices/cpu/tms34010/34010ops.hxx
Each `cvdxyl_b` call in Atronic software seems to be clustered together with `vcol` and `vfill_l` opcodes which are not yet implemented.
=> cpu: tms34020: Implement cvdxyl_b opcode

src/mame/nintendo/vsnes.cpp
- Fix type values for some variables
- Fix some function namings
=> nintendo/vsnes.cpp: Add items in save state, Minor updates

src/mame/dataeast/ffantasy_ms.cpp, src/mame/mame.lst
Automat (bootleg of Robocop, Modular System) [Darksoft]
=> Add an Automat (Robocop bootleg) set for Modular System

src/mame/dataeast/dietgo.cpp, src/mame/mame.lst
Diet Go Go (Europe v1.1 1992.09.26 v4) [Tailsnic Retroworks]
=> Add a newer Diet Go Go set (with alt graphics)

src/mame/sinclair/specnext_sprites.cpp, src/mame/sinclair/specnext_sprites.h, src/mame/sinclair/sprinter.cpp, src/mame/sinclair/tsconf.cpp, src/mame/sinclair/tsconf.h
followup: https://github.com/mamedev/mame/pull/12647#discussion_r1733416421
=> sinclair: reset caches for device_post_load

hash/zx81_cass.xml
Accounts [zx81stuff]
Adventure (Gavin Baker) [zx81stuff]
Bridgehead [Team Zeddy, Planeta Sinclair]
Gamespack [Team Zeddy, Planeta Sinclair]
Grand Prix [Planeta Sinclair]
Inheritance [Team Zeddy, Planeta Sinclair]
Le Chateau Hanté [Team Zeddy, Planeta Sinclair]
Purchases [zx81stuff]
Racehorse Trainer [zx81stuff]
Sabotagem (Timex Portugal) [Planeta Sinclair]
Serpents Tomb [Team Zeddy, Planeta Sinclair]
Simulador de Voo (Timex Portugal) [Planeta Sinclair]
Star Trek + 3D O's and X's [zx81stuff]
The Nowotnik Puzzle & Other Diversions [zx81stuff]
Tutor (French) [zx81stuff]
Xadrez (Timex Portugal) [Planeta Sinclair]
Zedman + Spacers [Team Zeddy, Planeta Sinclair]
Zor [zx81stuff]
New NOT working software list …
=> zx81_cass.xml: Added 18 working items + 2 not working

hash/msx1_cart.xml
The 4 Masters of Melody [anonymous]
The Battle on Gojo Ohashi [anonymous]
Ghost [anonymous]
Prisoner of War [anonymous]
=> msx1_cart.xml: Added 4 working items.

hash/msx2_cart.xml
=> msx2_cart.xml: Added 1 working item.

src/mame/mame.lst, src/mame/motorola/mex68kecb.cpp
Initial implementation of the Motorola 68K Educational Computer Board (MEX68KECB).
=> Initial support for the Motorola MEX68KECB Educational Computer Board

hash/megadriv.xml
Breach (prototype) [Gaming Alexandria]
Earthworm Jim (USA, prototype 19940728) [Hidden Palace]
Earthworm Jim 2 (Europe, prototype 19950824) [Hidden Palace]
Out of the Vortex (prototype 19950913) [Hidden Palace]
Added language and compatibility info.
=> megadriv.xml: Added 4 working items

src/mame/mame.lst, src/mame/sun/ultra45.cpp
=> Add a Skeleton driver for Sun Microsystems Ultra 45 Workstation

hash/attache.xml, hash/smc777.xml
[attache] Added accent to "Attaché" system.
[smc777] Fixed system name and lowercase on media storage name.
=> attache.xml; smc777.xml: Added more accurate soft. list descriptions

src/mame/igs/igs_m027.cpp, src/mame/igs/igs_m027xa.cpp
- igs_m027.cpp: Corrected OKI samples ROM banking for lhdmg/lhzb3
- igs_m027.cpp: Added NVRAM support
- igs_m027xa.cpp: Corrected OKI samples ROM banking for jking02
- igs_m027xa.cpp: Added NVRAM support
=> igs_m027.cpp: Added OKI samples ROM banking with 128KB size

src/lib/formats/mfi_dsk.cpp
Updates the mfi file definition with the way hard-sectored support was added to mame.
=> formats/mfi_dsk.cpp: Update mfi spec for new hard-sectored support.

src/mame/atari/jaguar.cpp
GPI0 is actually GPIO (General Purpose Input Output).
=> atari/jaguar.cpp: Fix notes

hash/zx81_cass.xml
3D Formule 1 [Team Zeddy, Planeta Sinclair]
AERI - Análise de Estruturas Recticuladas Isostácticas [Planeta Sinclair]
Alien Invaders [Team Zeddy, Planeta Sinclair]
Air Traffic Control [Team Zeddy, Planeta Sinclair]
Colunas - Dimensionamento de Colunas Montantes de Edifícios [Planeta Sinclair]
Dis-ACSem [Planeta Sinclair]
Em Busca dos Tesouros [Spectrum Computing]
Geometria I [Planeta Sinclair]
Letter Hunt [Planeta Sinclair]
Tut-Tut [Spectrum Computing]
New NOT working software list addition
1K Games Pack (Crystal) [Team Zeddy, Planeta Sinclair]
=> zx81_cass.xml: Added 10 working items + 1 not working

src/mame/trs/coco3.cpp
=> trs/coco3.cpp: Extend display from 639 to 640 pixels

src/devices/cpu/mipsx/mipsx.cpp, src/devices/cpu/mipsx/mipsxdasm.cpp, src/mame/mame.lst, src/mame/skeleton/pap2.cpp, src/mame/tomy/kisssite.cpp
cpu/mipsx/mipsx.cpp: probably 32-bit addresses
cpu/mipsx/mipsxdasm.cpp: fix various bugs
tomy/kissite.cpp: memory map borrowed from Linksys PAP2
=> Add Linksys PAP2 and other MIPS-X improvements

src/mame/mame.lst, src/mame/tvgames/spg2xx.cpp, src/mame/tvgames/spg2xx.h
--------
16-bit TV Dance Pad with 15 songs (DDRGame) [David Haywood, Sean Riddle]
=> new WORKING machine (DDRGame)

src/mame/sun/sun3.cpp
Adds a DIAG/NORMAL switch that affect how a Sun-3/60 (and other models) are configured.
=> sun3: Add DIAG/NORMAL switch

hash/samcoupe_flop.xml
Boggle Bubble [Spectrum Computing]
Dave Infuriators [Black Jet]
Dave Invaders [Black Jet]
Hexagonia [Spectrum Computing]
Lost Disks of Sam [Black Jet]
Moby DX [Black Jet]
WaterWorks [TOSEC]
Wop Gamma (pre-release version) [World of SAM]
=> samcoupe_flop.xml: Added 8 working items

src/mame/sinclair/tsconf.cpp, src/mame/sinclair/tsconf.h, src/mame/sinclair/tsconf_m.cpp, src/mame/sinclair/tsconfdma.cpp, src/mame/sinclair/tsconfdma.h
sinclair/tsconf.cpp: replace covox with DAC device
sinclair/tsconfdma.cpp: refactoring
=> sinclair/tsconf.cpp: replace covox with DAC device

hash/nes_kstudio.xml, hash/nes_ntbrom.xml
Replaced "Jpn" abbreviation to "Japan"
=> nes_kstudio.xml; nes_ntbrom.xml: Metadata cleaning

src/mame/hitachi/bml3.cpp, src/mame/hitachi/mbs1_mmu.cpp, src/mame/hitachi/mbs1_mmu.h, src/mame/mame.lst
=> New systems marked not working

hash/supracan.xml
new NOT WORKING Software List additions
supracan.xml: Rebel Star [anonymous]
=> new NOT WORKING Software List additions (Super A'Can)

src/mame/atari/badlands_ms.cpp, src/mame/capcom/lastduel_ms.cpp, src/mame/mame.lst, src/mame/toaplan/twincobr_ms.cpp, src/mame/vsystem/pspikes_ms.cpp
Last Duel (Modular System) [Museo del Recreativo, Recreativas.org]
Power Spikes (Modular System) [Museo del Recreativo, Recreativas.org]
Twin Cobra (Modular System) [Museo del Recreativo, Recreativas.org]
Also fixed comments about Bad Lands on Modular System (atari/badlands_ms.cpp)
=> Add skeletons for three new bootlegs on Modular System

hash/ibm5170_cdrom.xml
New working software list addition:
----------------------------------------
EA Sports Cricket 96 [te_lanus]
=> ibm5170_cdrom.xml: Add EA Sports Cricket 96

src/mame/mame.lst, src/mame/skeleton/bullion2.cpp
Inder Bullion 2 [Victor Fernandez (City Game), Recreativas.org]
=> Add a skeleton for Bullion 2, a slot machine from Inder

hash/apple2_flop_clcracked.xml, hash/apple2_flop_orig.xml, hash/apple2gs_flop_orig.xml
* apple2_flop_orig.xml: Added twenty-one new dumps
* apple2_flop_clcracked.xml: Added four new dumps (Computer Baseball 1983 Teams split from original since sold separately)
* apple2gs_flop_orig.xml:  Added six new dumps
* Improved metadata for all SSI dumps
New working software list items (apple2_flop_orig.xml) 
B-24 (version 1.0) [4AM, yesterbits, A-Noid]
Baltic 1985: Corridor to Berlin (version 1.0) [4AM, A-Noid]
Battalion Commander (version 1.0) [4AM, yesterbits, a2_qkumba, A-Noid]
Battle of Antietam (version 1.3) [4AM, yesterbits, A-Noid]
Battle of Antietam (version 1.5) [4AM, A2_Canada, A-Noid]
Battlecruiser (version 1.0) [4AM, A2_Canada, A-Noid]
Battles of Napoleon (version 1.0) [4AM, yesterbits, A-Noid]
Bomb Alley (version 1.0) [4AM, A2_Canada, …
=> apple2_flop_orig.xml, apple2_flop_clcracked.xml, apple2gs_flop_orig.xml: Added latest dumps and improved metadata.

src/mame/mame.lst, src/mame/midway/cashline.cpp, src/mame/skeleton/bullion2.cpp
Bally/Sente Cashline [Vicente y Sergio de ElectronicaVyS]
Also fixed GAME flag for Inder Bullion 2
=> Added a skeleton for Cashline slot machine from Bally/Sente

src/mame/misc/mirax.cpp
- Fix type values for some variables
- Fix naming of variables, functions and ROM regions
- Fix spacing
- Simplify gfxdecode layout
=> misc/mirax.cpp: Minor cleanups

hash/coleco_homebrew.xml
Air Battle [colecovision.dk]
Bejeweled (v2001) [colecovision.dk]
Bunny [colecovision.dk]
BUsTin-Out Volume 1 [colecovision.dk]
BUsTin-Out Volume 2 [colecovision.dk]
Commando Returns (demo) [colecovision.dk]
Double Breakout [colecovision.dk]
Ghostblaster (rev. B) [colecovision.dk]
Le Château du Dragon [colecovision.dk]
Osotos [Inufuto]
Quiz Wiz [colecovision.dk]
Search for the Stolen Crown Jewels 1 (demo) [colecovision.dk]
Search for the Stolen Crown Jewels 2 (demo) [colecovision.eu]
Search for the Stolen Crown Jewels 3 (demo v2011) [colecovision.eu]
=> coleco_homebrew.xml: Added 14 working items

src/mame/pinball/inder.cpp
The "bonus expansion board" is well described (with its schematics) on the manual.
=> pinball/inder.cpp: Add "bonus expansion board" ROMs for Moon Light [jordigahan]

src/mame/misc/mosaic.cpp
- Suppress side effect in debugger read
- Fix type value for some variables
- Use generic gfx decode layouts
- Reduce CPU ROM region size match to CPU ROM size
- Fix spacing
=> misc/mosaic.cpp: Minor cleanups

hash/zx81_cass.xml
Ant Attack [Bob's Stuff]
Avalanche [Revival Studios]
Argolath [Spectrum Computing]
Bar Billards [Spectrum Computing]
Boulder Logic [Bob's Stuff]
Bigg Oil [Spectrum Computing]
Budget Familial [Spectrum Computing]
Budget Familial (alt) [Spectrum Computing]
Casse-Briques + Pendu [Team Zeddy, Planeta Sinclair]
Chiromancie [Spectrum Computing]
Crozxy Road [Bob's Stuff]
Domin8tr1s [Bob's Stuff]
Down! [Revival Studios]
Impact [Bob's Stuff]
Jogos 3 [Planeta Sinclair]
Mayhem [Revival Studios]
Miner Man [Bob's Stuff]
Noir Shapes [Bob's Stuff]
One Little Ghost [Bob's Stuff]
Pandemic [Bob's Stuff]
Panique [Team Zeddy, Planeta Sinclair]
Quack! [Bob's Stuff]
Rebound [Bob's Stuff]
Rigel [Spectrum Computing]
Shrooms [Bob's …
=> zx81_cass.xml: Added 30 working items + 1 not working

hash/dragon_cass.xml, hash/dragon_flex.xml, hash/fm77av.xml, hash/fm7_disk.xml
- Lowercase on descriptive words
- Replaced countries' abbreviation
=> fm77av.xml; fm7_disk.xml; dragon_cass.xml; dragon_flex.xml: Metadata cleanups

src/mame/mame.lst, src/mame/skeleton/pap2.cpp
I forgot the license header last time.
=> Add Linksys PAP2 again

src/mame/mame.lst, src/mame/taito/retofinv.cpp
Return of the Invaders (Video Dens bootleg, without MCU) [Rubén Casaña (Retro Arcadia), Isaías Hernández]
=> taito/retofinv.cpp: Add a new Return of the Invaders bootleg from Video Dens

src/mame/mame.lst, src/mame/namco/md8412b.cpp, src/mame/namco/md8412b.h, src/mame/namco/namcos23.cpp, src/mame/namco/vpx3220a.cpp, src/mame/namco/vpx3220a.h
Race On! (Japan, RO1 Ver. B) [Guru]
-namcos23.cpp: Significant improvements. More games boot and are playable, albeit with glitchy graphics at times. [Ryan Holtz, Olivier Galibert, smf]
=> Significant Namco System 23 graphical and functional improvements

src/devices/cpu/upd7810/upd7810.cpp, src/devices/cpu/upd7810/upd7810.h, src/devices/cpu/upd7810/upd7810_opcodes.cpp
cpu/upd7810/upd7810.cpp: Improve uPD7801 Mode C handling.
Fixes banking in SCV Star Speeder.
=> cpu/upd7810/upd7810.cpp: Improve uPD7801 Mode C handling.

src/devices/sound/upd1771.cpp
sound/upd1771.cpp: Improve check for end of adpcm stream when the stream contains multiple samples.
Fixes SCV Star Speeder.
=> sound/upd1771.cpp: Improve check for end of adpcm stream

src/devices/bus/heathzenith/h89/h_88_3.cpp
Connect the interrupt lines for the H-88-3 three port serial board to the new H89 bus.
=> bus/heathzenith/h89/h_88_3.cpp: Connect interrupt lines

src/mame/namco/namcos23.cpp
Crisis Zone (World, CSZO2 Ver. B) [Guru]
-namcos23.cpp: Improved texturing in Super System 23 games. [Ryan Holtz]
=> Namco System 23 texturing improvements + boot fix for aking

hash/ekara_cart.xml, src/mame/mame.lst, src/mame/nintendo/nes_vt02_vt03.cpp, src/mame/nintendo/nes_vt369_vtunknown.cpp, src/mame/nintendo/vt1682.cpp, src/mame/skeleton/tamagotchi_pix.cpp, src/mame/tvgames/generalplus_gpl16250.h, src/mame/tvgames/generalplus_gpl16250_rom.cpp, src/mame/tvgames/generalplus_gpl32612.cpp, src/mame/tvgames/xavix.cpp, src/mame/tvgames/xavix.h, src/mame/tvgames/xavix_2000.cpp, src/mame/tvgames/xavix_2002.cpp
Idaten Sho Gekisou - Idaten Jump (Japan) [TeamEurope, David Haywood]
Let's Build a Town: Construction Cars 5 (Japan) [TeamEurope, David Haywood]
ConnecTV Opus (PAL) [TeamEurope, David Haywood]
GameU Joint TV Bank 108-in-1 (model AH9069) [TeamEurope, David Haywood]
----------------
Zuba Zuba Blade (Japan) [TeamEurope, David Haywood]
Beyblade Ultimate Shooter (Japan) [TeamEurope, David Haywood]
TV Hockey (Japan) [TeamEurope, David Haywood]
Let's Play Excite Striker (UK) [TeamEurope, David Haywood]
Play Portable Color GameU+ (108-in-1) (Japan) [TeamEurope, David Haywood]
Handheld Game Console 319-in-1 [TeamEurope, David Haywood]
Classic Max Pocket Mx-10 - 12 in 1 (vertical)  [TeamEurope, David Haywood]
XaviX Aerostep (XaviXPORT, …
=> 16 Plug & Play / Handheld additions (4 working)

hash/ibm5170_cdrom.xml, hash/mac_cdrom.xml
New working software list items (ibm5170_cdrom)
-----------------------------------------------
My First Math Adventure: Adding and Subtracting [chungy]
Ultimate Solitaire [chungy]
New NOT WORKING software list items (ibm5170_cdrom)
---------------------------------------------------
Multimedia Middle School Grammar [chungy]
Mavis Beacon Teaches Typing Special Edition 10 [chungy]
New working software list items (mac_cdrom)
-------------------------------------------
My First Math Adventure: Adding and Subtracting [chungy]
=> mac_cdrom, ibm5170_cdrom: new CD-ROM dumps

src/mame/mame.lst, src/mame/sega/segag80r.cpp
Astro Blaster (French) [Victor Fernandez (City Game)]
=> sega/segag80r.cpp: Add a French Astro Blaster set

src/mame/galaxian/galaxian.cpp, src/mame/mame.lst
Jump Bug (bootleg, set 3) [Arcadedealer aka Edgar Solé aka Dios, Recreativas.org]
=> galaxian/galaxian.cpp: Add a (not working) new Jump Bug bootleg

src/mame/konami/gryzor_ms.cpp, src/mame/mame.lst
Gryzor (Modular System) [Arcadedealer aka Edgar Solé aka Dios, Recreativas.org]
=> Add a skeleton for Gryzor bootleg on Modular System

src/mame/mame.lst, src/mame/tecmo/shadoww_ms.cpp
Shadow Warriors (Modular System) [Darksoft]
=> Add a skeleton for Shadow Warriors bootleg on Modular System

src/mame/mame.lst, src/mame/skeleton/flashvga2.cpp
Codere Ruleta Mágica [David Villaverde, Recreativas.org]
=> Add a skeleton for a Spanish video-slot from Codere

src/mame/jpm/jpmimpct.cpp, src/mame/layout/cluedo.lay
This adds the game board to Cluedo? Murder Mystery Quiz Game.
=> jpmimpct: add layout to Cluedo? Murder Mystery Quiz Game

language/Ukrainian/strings.po
Ukrianian translation updated to actual 0.270. There were minor cosmetic corrections and translating empty problematic strings (that was discussed in #9100).
=> Updating Ukrainian translation

hash/ibm5170_cdrom.xml
New working software list items (ibm5170_cdrom.xml)
---------------------------------------------------
Star Trek: 25th Anniversary (Enhanced CD-ROM) [Interplay]
Star Trek: Judgment Rites (Collector's Edition) [Interplay]
=> hash/ibm5170_cdrom.xml: add Star Trek games

src/devices/cpu/xa/xa_ops.cpp, src/mame/igs/igs_fear.cpp
- confirmed Icescape XA as the same as fearless [Team Europe]
- added some XA opcode groups that get executed with this now
=> igs_fear.cpp : confirmed Icescape XA as the same as fearless [Team Europe]

src/mame/efo/nightmare.cpp, src/mame/mame.lst
Night Mare (Spain, set 2) [David Tallboom, Recreativas.org]
=> efo/nightmare.cpp: Added sound ROM and a new set

src/mame/konami/crimfght.cpp
- Add variables into save state
- Fix naming
=> konami/crimfght.cpp: Use memory view instead bankdev, Minor cleanups:

hash/segacd.xml
Sonic CD (USA, alt 3) [Foxhack]
=> segacd.xml: Added a dump of Sonic CD (USA)

hash/apfimag_cass.xml, hash/arcadia.xml
Lowercase on descriptive words
=> arcadia.xml, apfimag_cass: Metadata cleanups

src/mame/epoch/scv.cpp
Two games -- Kung Fu Road and Super Golf -- set this bit to hide half of the sprites.
This replaces the "screen_sprite_start_line" hack, which only worked on Kung Fu Road.
=> scv: Implement video register 0 bit 2: hide sprites 64-127

hash/ibm5170_cdrom.xml
Corel Linux Deluxe [Foxhack]
Civilization: Call to Power (Limited Edition, v1.1, Linux) [Foxhack]
=> ibm5170_cdrom.xml: New software items added

src/mame/cirsa/cirsa2080606.cpp
To avoid mistakes when looking for undumped sets
=> cirsa/cirsa2080606.cpp: Add note about Lucky Player

hash/zx81_cass.xml
Aerial [Inufuto]
AntiAir [Inufuto]
Ascend [Inufuto]
Battlot [Inufuto]
Blitz Balle [Team Zeddy, Planeta Sinclair]
Bootskell [Inufuto]
Cacorm [Inufuto]
Comp-U-Tax/82 [Team Zeddy, Planeta Sinclair]
Cracky [Inufuto]
Game of Life [Team Zeddy, Planeta Sinclair]
Guntus [Inufuto]
Hopman [Inufuto]
Jogos 80 - Ano 12 - Número 19 (Julho 2018) (cover tape) [ZX81 Never Die]
Lift [Inufuto]
Mazy [Inufuto]
MicroGame: Caçadores do Tesouro [ZX81 Never Die]
MicroGame: Challenger [ZX81 Never Die]
MicroGame: Pinball Wizard [ZX81 Never Die]
Monitor and Disassembler [Team Zeddy, Planeta Sinclair]
Neuras [Inufuto]
Osotos [Inufuto]
Ruptus [Inufuto]
Scorpirus [Team Zeddy, Planeta Sinclair]
Yewdow [Inufuto]
=> zx81_cass.xml: Added 24 working items

src/mame/igs/igs011.cpp
- Fix drgnwrldv40k metadata due to title screen/game name
- Simplify key matrix input read functions
- Use generic gfx decode layout for debugging
- Suppress side effects in debugger reads
- Fix naming, Fix spacings
- Fix/Add docs
=> igs/igs011.cpp: Split vbowl configuration via trackball inputs, Cleanups:

hash/spectrum_betadisc_flop.xml
Delta's Shadow (demo v1.0, English, AY chip sound) [ZX Art]
Delta's Shadow (demo v1.0, English, Turbo Sound) [ZX Art]
Delta's Shadow (demo v1.0, Polish, AY chip sound) [ZX Art]
Delta's Shadow (demo v1.0, Polish, Turbo Sound) [ZX Art]
Delta's Shadow (demo v1.0, Russian, AY chip sound) [ZX Art]
Delta's Shadow (demo v1.0, Russian, Turbo Sound) [ZX Art]
Delta's Shadow (demo v1.0, Spanish, AY chip sound) [ZX Art]
Delta's Shadow (demo v1.0, Spanish, Turbo Sound) [ZX Art]
Delta's Shadow (demo v1.6, English, AY chip sound) [Sinc LAIR]
Delta's Shadow (demo v1.6, English, Turbo Sound) [Sinc LAIR]
Delta's Shadow (demo v1.6, Polish, AY chip sound) [Sinc LAIR]
Delta's Shadow (demo v1.6, Polish, Turbo Sound) [Sinc LAIR] …
=> spectrum_betadisc_flop.xml: Added 17 working items + 1 not working

scripts/src/bus.lua, src/devices/bus/heathzenith/h89/cards.cpp, src/devices/bus/heathzenith/h89/cdr_fdc_880h.cpp, src/devices/bus/heathzenith/h89/cdr_fdc_880h.h, src/devices/bus/heathzenith/h89/h89bus.cpp, src/mame/heathzenith/h89.cpp, src/mame/mame.lst
cdr_fdc_880h.cpp:
- new CDR FDC-880H floppy disk controller (not working)
h89bus.cpp:
- Add new I/O PROM decoder for CDR FDC-880H
h89.cpp:
- Add new CDR clone for H89
- Add 2 new Monitor ROMs from CDR.
=> heathzenith/h89.cpp: Add h89 clone with CDR hardware

hash/pv2000.xml
Aerial [Inufuto]
AntiAir [Inufuto]
Ascend [Inufuto]
Battlot [Inufuto]
Bootskell [Inufuto]
Cacorm [Inufuto]
Cavit [Inufuto]
Cracky [Inufuto]
Cross Chase [Fabrizio Caruso]
Guntus [Inufuto]
Hopman [Inufuto]
Lift [Inufuto]
Mazy [Inufuto]
Neuras [Inufuto]
Osotos [Inufuto]
Ruptus [Inufuto]
Yewdow [Inufuto]
=> pv2000.xml: Added seventeen working homebrew cartridges

src/mame/galaxian/galaxian.cpp, src/mame/galaxian/galaxian.h, src/mame/mame.lst
Turpin (Novatronic bootleg) [Luis Arrufat, Recreativas.org]
=> Add a new Spanish Turtles bootleg

hash/nes.xml
Just a simple loop demonstrating the PCM channel of the NES sound chip...
Okay. I do spoil the joke with the alt_title, but honestly, that might attract more people to playing this ROM.
New working software list items (nes.xml)
PCM Demo With Graphics
=> hash/nes.xml: PCM Demo homebrew

src/mame/sinclair/atm.cpp, src/mame/sinclair/atm.h, src/mame/sinclair/pentevo.cpp
Can't reproduce but have high confidence that should fix the issue
=> MT08472: heap overflow

src/mame/mame.lst, src/mame/tvgames/spg2xx_jakks.cpp
---
Pirates of the Caribbean - Islands of Fortune  [David Haywood, TeamEurope]
=> new WORKING machine (JAKKS Pacific Pirates of the Caribbean)

src/mame/taito/taitotz.cpp
This change does some structural cleanup to this largely-abandoned file, mainly:
- Removal of unnecessary parentheses and case-bracing
- Case indentation
- Operator spacing
- C++ versus C-style comments for single-line comments
It also removes some small chunks of `#if 0`'d code, and moves some other previously `#if 0`'d code behind `if (SOME_CONSTEXPR_DRIVER_MEMBER)` in order to avoid code-rot.
As something of a bonus change, there is a fix to expected packet-size calculation in `taitotz_renderer::push_direct_poly_fifo`, which in turn avoids a fatalerror (which has since been removed) in Raizin Ping Pong's attract mode.
The fatalerror was reportedly due to an unsupported direct-geometry vertex count of 2, but this only came about due to single-vertex direct geometry not consuming an …
=> taitotz.cpp: Standards cleanup and a functional fix

scripts/src/cpu.lua, src/devices/cpu/mpk1839/kl1839vm1.cpp, src/devices/cpu/mpk1839/kl1839vm1.h, src/devices/cpu/mpk1839/kl1839vm1dasm.cpp, src/devices/cpu/vax/vaxdasm.cpp, src/devices/cpu/vax/vaxdasm.h, src/mame/ussr/pk32.cpp
Good progress here. CPU is able to decode/process VAX-11 instructions in user space.
=> cpu/mpk1839/kl1839vm1.cpp: Improved VAX-11 code decoder in user space

hash/psx.xml
007 - Die Welt Ist Nicht Genug (Germany) [Redump]
007 - El Mundo Nunca es Suficiente (Spain) [Redump]
007 - Le Monde ne Suffit Pas (France) [Redump]
007 - Tomorrow Never Dies (Europe) [Redump]
007 - Demain ne Meurt Jamais (France) [Redump]
007 - Der Morgen Stirbt Nie (Germany) [Redump]
007 - The World Is Not Enough (Europe) [Redump]
007 - The World Is Not Enough (Sweden) [Redump]
007 - The World Is Not Enough (USA, prototype) [Redump]
Redumped software list items
007 - Tomorrow Never Dies (Japan) [Redump]
007 - Tomorrow Never Dies (USA) [Redump]
007 - The World Is Not Enough (USA) [Redump]
=> psx.xml: Added 9 working items + 3 redumps

src/mame/mame.lst, src/mame/tvgames/spg2xx_jakks.cpp
Superman in Super Villain Showdown [David Haywood, TeamEurope]
=> new WORKING machines (JAKKS Pacific Superman)

src/mame/layout/oberheim_dmx.lay, src/mame/mame.lst, src/mame/oberheim/dmx.cpp
Other than audio, the main missing components are auxiliary ones, such as cassette I/O. The computer portion of the DMX should be complete, and usable via the interactive layout.
Audio work is far along, and will be sent in a followup PR. 
A bit of a tangent: if anyone else is working on synthesizers and reading this, consider taking a look at this [WIP](https://github.com/m1macrophage/synthesizerdocs?tab=readme-ov-file#status), in order to avoid conflicts.
=> oberheim/dmx.cpp: Driver for Oberheim DMX. Includes layout. No sound.

hash/pasogo.xml
Added missing cart numbers and an additional undumped game.
=> pasogo.xml: Metadata updates

hash/psx.xml
007 Racing (Europe) [Redump]
007 Racing (France) [Redump]
007 Racing (Germany) [Redump]
A Ressha de Ikou 4 - Evolution Global (Japan) [Redump]
A Ressha de Ikou 4 - Evolution Global (Japan) (PlayStation the Best) [Redump]
A.IV - Evolution Global (Europe) [Redump]
Actua Golf (Europe) [Redump]
Actua Golf (Japan) [Redump]
Actua Golf 2 (Europe) [Redump]
Actua Golf 3 (Europe) [Redump]
Redumped software list items
007 Racing (USA) [Redump]
A-Train - Trains, Power, Money (USA) [Redump]
=> psx.xml: Added 10 working items + 2 redumped items

hash/zx81_cass.xml
3D 3D! (Kayde) [Steven Brown, Planeta Sinclair]
3D Monster Maze (Aackosoft) [Steven Brown, Planeta Sinclair]
3D Monster Maze (ZX Data) [Spectrum Computing]
Asteroids (dK'tronics) [Steven Brown, Planeta Sinclair]
Astral Convoy [Spectrum Computing]
Can of Worms (alt) [Steven Brown, Planeta Sinclair]
Centipede (Kayde) [Steven Brown, Mark Westmoreland, Planeta Sinclair]
Constellation (red logo inlay) [Steven Brown, Mark Westmoreland, Planeta Sinclair]
Dictator (red logo inlay) [Steven Brown, Mark Westmoreland, Planeta Sinclair]
Frogs (Aackosoft) [Steven Brown, Planeta Sinclair]
Gulp II (Aackosoft) [Steven Brown, Planeta Sinclair]
Gulp II (ZX Data) [Spectrum Computing]
House of Gnomes [Steven Brown, Mark …
=> zx81_cass.xml: Added 27 working items + 2 not working

src/mame/oberheim/dmx.cpp
System transitioned to working with imperfect sound.
While still working on this, it is easier to have related computations together. However, it is possible to cache a lot of the computation at voice initialization or triggering. Once the next audio improvements are in (reconstruction filter and voice tuning), I'll take care of these optimizations too.
=> oberheim/dmx.cpp: Sound emulation.

src/mame/layout/d70.lay, src/mame/roland/roland_d70.cpp
Support moving sliders with mouse click & drag.
* **Note 1:** LEDs declared and positioned in the layout, but the driver still does not control them.
* **Note 2:** The rotary encoder is also not functional yet. I'll leave that one to a future separate commit.
(@giulioz, @m1macrophage)
=> Adding a layout to the Roland D-70 driver.

src/mame/layout/kn5000.lay
* Highlight pressed buttons by changing color
* And also remove many unnecessary 'name' attributes.
* Add a few details that were missing (like the red lines over a couple sequencer buttons)
=> [kn5000] Improvements to the internal layout.

src/mame/oberheim/dmx.cpp
Also simplified and documented pitch computations.
=> oberheim/dmx.cpp: Emulating pitch tunning. Optimizing / caching pitch computations.

src/mame/mame.lst, src/mame/vtech/vtech5303.cpp
Paw Patrol (toy computer, Spanish) [Arcade Hacker]
=> Add a skeleton for VTech Paw Patrol toy computer

hash/pc6001_cart.xml
Turpin (19821012) [Mike Stedman]
Turpin (19830129) [bsittler]
=> pc6001_cart.xml: New software items added

src/mame/kaneko/snowbros.cpp, src/mame/kaneko/snowbros.h, src/mame/mame.lst
--------
Gwasuwon (Korea) [Taksangs, David Haywood]
(technically it is playable, but we're using borrowed protection data for now, so leaving it flagged)
=> new NOT WORKING machines (Gwasuwon from SemiCom)

src/mame/oberheim/dmx.cpp
- Optimized VCA sound processing.
- Emulated the stereo output, along with the fixed panning of voices.
- This also improved accuracy of relative voice volume.
- Added config option for selecting audio output.
- Documentated the VCA.
=> oberheim/dmx.cpp: Stereo output. VCA optimizations and docs.

src/mame/layout/oberheim_dmx.lay, src/mame/oberheim/dmx.cpp
Also made sliders and slider script more reusable.
=> oberheim/dmx.cpp: Surfacing mouse-controlled tunning trimmers on the layout.

src/mame/seta/macs.cpp, src/mame/seta/simple_st0016.cpp, src/mame/seta/st0016.cpp, src/mame/seta/st0016.h
=> seta/simple_st0016.cpp: Remove unnecessary trampoline

hash/pc8801_flop.xml
New working software list addition
Berserkers Front Gaiden 3 Plus - Turning Point (Developer Studio K2) [krugman on archive.org]
Updates metadatas of other Studio K2 doujin games.
Auction page of this doujin game : https://www.ebay.com/itm/385366120727
The game is available on krugman profile of archive.org
I updated metadatas from previous entry Berserkers Front Gaiden 3 and Battle Entry required V2 Mode.
Screenshot of both games.
I tested them on Mame with PC8801mkiiSR.
Thanks,
=> hash/pc8801_flop.xml: Added 1 working item.

src/mame/mame.lst, src/mame/tvgames/spg2xx_jakks.cpp
-------------
Disney Pixar Classics (JAKKS Pacific TV Game) [David Haywood, TeamEurope]
=> new WORKING machines (JAKKS Disney Pixar Classics)

scripts/src/sound.lua, src/devices/sound/bbd.cpp, src/devices/sound/bbd.h, src/devices/sound/flt_biquad.cpp, src/devices/sound/flt_biquad.h, src/devices/sound/upd931.cpp, src/devices/sound/upd931.h, src/emu/xtal.cpp, src/mame/casio/ct8000.cpp, src/mame/casio/ct8000_midi.cpp, src/mame/casio/ct8000_midi.h, src/mame/layout/ct8000.lay, src/mame/layout/ctfk1.lay, src/mame/mame.lst
This adds the Casiotone 8000 keyboard, FK-1 bass pedals, and (non-working) MB-1 recording/playback unit all belonging to the "Symphonytron" organ system, as well as an adapter device to make them all controllable over MIDI.
The stereo chorus is also implemented, but tends to sound noticeably aliased due to the lack of resampling on the BBD output. I don't really have the bandwidth to try fixing it at the moment though.
New working machines
Casiotone 8000 [=CO=Windler, Devin Acker]
Casiotone FK-1 [BCM, Devin Acker]
Casiotone MB-1 [=CO=Windler, Devin Acker]
=> Add Casiotone 8000 and related systems

hash/amiga_demos.xml
amiga_demos: Interference, Puggs In Space [pouet.net]
=> amiga_demos.xml: Added 2 not-working entries

src/mame/skeleton/zorba.cpp
- Use memory_view for ROM overlay
- Use required_device_array for multiple devices
- Fix types of member variables for fix save state
=> skeleton/zorba.cpp: Updates/Cleanups

src/mame/alesis/midiverb.cpp, src/mame/oberheim/dmx.cpp, src/mame/paia/fatman.cpp
Noticed that this is standard practice.
=> dmx.cpp, midiverb.cpp, fatman.cpp: Added _device suffix to devices.

src/mame/konami/tp84.cpp
- Fix sound CPU ROM region size for match to mapped size in CPU
- Fix naming
- Cleanup gfx decode layouts
- Fill 0 in empty ROM region areas
=> konami/tp84.cpp: Cleanups

src/mame/konami/megazone.cpp
- Cleanup gfx layouts
- Fix ROM region and finder namings
- Fix types of some variables
- Fix spacing
=> konami/megazone.cpp: Cleanups:

src/mame/sony/zn.cpp
This PR replaces the Arabic numeral with the Roman numeral.
=> sony/zn.cpp: primrag2 title string numeral change

hash/oric1_cass.xml
Hnefatafl [Defence Force]
Mieyen [Inufuto]
O-Thrust (v1.2) [Defence Force]
=> oric1_cass.xml: Added 3 working items

src/mame/layout/oberheim_xpander.lay, src/mame/mame.lst, src/mame/oberheim/xpander.cpp
New system marked not working: Oberheim Xpander.
Digital and digital-analog interface almost fully implemented. No audio. The layout is minimal, just includes the displays and a few buttons.
=> oberheim/xpander.cpp: Added driver for Xpander.

src/mame/layout/alesis_midiverb.lay
=> alesis_midiverb.lay: Made layout more realistic.

src/mame/atari/sprint2.cpp, src/mame/mame.lst
Sprint 2 (bootleg) [Victor Fernandez (City Game)]
=> atari/sprint2.cpp: Add a Sprint 2 bootleg set

src/mame/oberheim/dmx.cpp
* Emulating metronome, including mixing with the rest of the voices.
* Emulating the RC HPFs for each voice and for the metronome.
* Corrected (inverted) phase of mixed audio.
* Using component values from electrongate.com, they seem to be more accurate than the '81 schematics.
Almost every component (resistors, capacitors) in the voice (but not the metronome) audio path is now accounted for. In other words, almost all components show up in some equation or filter configuration.
=> oberheim/dmx.cpp: Added metronome and other audio improvements.

src/mame/taito/wyvernf0.cpp
- Fix save state support, Fix typename for boolean flags
- Make unique_ptr as memory_share_creator
- Fix naming
- Reduce unnecessary variables
- Add notes
=> taito/wyvernf0.cpp: Cleanups

src/mame/taito/taitojc.cpp, src/mame/taito/taitojc.h, src/mame/taito/taitojc_v.cpp
This PR fixes regression since https://github.com/mamedev/mame/commit/1c139c5a60440db98b38e7eb11b21137ada9a6bf .
=> taito/taitojc.cpp: Fix character RAM size

hash/coleco_homebrew.xml
=> coleco_homebrew.xml: Added 1 working item

hash/zx81_cass.xml
2K Games Pack (Softsync) [Planeta Sinclair]
Alien Invasion 16K [Planeta Sinclair]
Athlete's Foot [Steven Brown, Planeta Sinclair]
Athlete's Foot (master) [Steven Brown, Planeta Sinclair]
Ator The ABC Gator [Planeta Sinclair]
Battle of the Planets [Mark Westmoreland, Steven Brown, Planeta Sinclair]
Battleships (alt) [Steven Brown, Planeta Sinclair]
BMX Trial [Spectrum Computing]
Battle ZXone [Spectrum Computing]
Cursed Catacombs (v2.0) [Naranjito Games]
Cursed Catacombs (v2.1, ZXpand joystick) [Naranjito Games]
Dungeons of Zedd [Naranjito Games]
El Valle [Luís Rato, Planeta Sinclair]
Grand Prix & Golf [Steven Brown, Planeta Sinclair]
Mieyen [Inufuto]
Ordidactic - 1. Language Machine [Planeta Sinclair] …
=> zx81_cass.xml: Added 17 working items + 2 not working

src/mame/taito/invqix.cpp
- Cleanup screen update functions
- Fix color
- Remove unnecessary palette device
- Use BIT function for single bit flags
- Fix naming
=> taito/invqix.cpp: Fix flip screen, Cleanups:

scripts/src/bus.lua, src/devices/bus/centronics/ctronics.cpp, src/devices/bus/centronics/epson_rx80.cpp, src/devices/bus/centronics/epson_rx80.h
Here's a skeleton for the epson rx80.
=> add rx80 skeleton

src/mame/taito/minivadr.cpp
- Restrict screen update function into cliprect
- Fix namings
=> taito/minivadr.cpp: Updates/Cleanups:

src/mame/zpa/iq151.cpp
- Use memory_view for boot ROM select
- Add notes
- Fix ROM region size matches to BIOS ROM size
=> zpa/iq151.cpp: Updates/Cleanups

src/mame/yachiyo/mole.cpp
- Make tile RAM to memory_share_creator
- Fix namings
=> yachiyo/mole.cpp: Cleanups

src/devices/bus/nes/disksys.cpp, src/devices/bus/nes/disksys.h, src/devices/sound/rp2c33_snd.cpp
Common:
- Fix dead link
bus/nes/disksys.cpp:
- Implement readable nametable mirroring status
- Fix save state support, Fix initializing function
=> bus/nes/disksys.cpp, sound/rp2c33_snd.cpp: Updates

src/devices/cpu/v60/op2.hxx
Source: https://multimedia.cx/NEC_V60pgmRef.pdf, page 53
Hopefully this eliminates invisible walls in Virtua Racing
=> v60: implement correct rounding mode when converting float to integer

src/mame/mame.lst, src/mame/taito/asuka.cpp
Cadash (Spain) [Tailsnic Retroworks]
=> Add a new Cadash Spanish set

src/mame/mame.lst, src/mame/skeleton/optomaxv.cpp
=> Add a skeleton driver form AMS Optomax V image analyser

src/mame/mame.lst, src/mame/skeleton/camirf1.cpp
=> Add a Skeleton driver for Honeywell CAMIR-F1 motion sensor

src/mame/capcom/gng.cpp, src/mame/mame.lst
Ghosts'n Goblins (bootleg) [Jordi Tuells, Jordi Beltran (Crazy Taxi)]
=> capcom/gng.cpp: Add a new Ghosts'n Goblins bootleg

src/mame/linn/linndrum.cpp
* Hi-hat decay knob is now working.
* Open and closed hats have different decays.
* Better default tuning for the snare.
* Removed `strobe_` prefix from functions where it was redundant. Made it an argument in a function where it matters.
=> linn/linndrum.cpp: Emulating hi-hat decay.

src/mame/mame.lst, src/mame/skeleton/paracaidista.cpp
Paracaidista [Recreativas.org, ClawGrip]
=> Add a skeleton for the 2023 version of Paracaidista

src/mame/mame.lst, src/mame/sega/vicdual.cpp
Colision (bootleg of Head On) [Jordi Tuells]
Also reformatted single line comments.
=> sega/vicdual.cpp: Add "Colision" (bootleg of Head On)

src/devices/machine/nscsi_bus.cpp
Make logging of device match same order used few lines above for ctrl
=> nscsi_bus.cpp:  consisent logging order of status

src/devices/cpu/upd7810/upd7810.cpp, src/devices/cpu/upd7810/upd7810.h, src/devices/cpu/upd7810/upd7810_opcodes.cpp, src/mame/mame.lst, src/mame/skeleton/omdisv22.cpp, src/mame/skeleton/unk78c14.cpp
Random eBay salvage that I used to test 87AD internal ROM dumping (I don't have the actual unit, just the MCU).
----------
Oldsmobile Driver Information System (version 2.2 CH) [Devin Acker]
=> Add a skeleton for an Oldsmobile Driver Information System

src/devices/cpu/z80/nsc800.cpp, src/devices/cpu/z80/nsc800.h, src/devices/cpu/z80/r800.cpp, src/devices/cpu/z80/r800.h, src/devices/cpu/z80/z80.cpp, src/devices/cpu/z80/z80.h, src/devices/cpu/z80/z80.lst, src/devices/cpu/z80/z80make.py, src/devices/cpu/z80/z80n.cpp, src/devices/cpu/z80/z80n.h
before:
```
~/workspace/mame (z80-perf*) » ./mame pacman -bench 300
Average speed: 10879.54% (299 seconds)
```
after:
```
~/workspace/mame (z80-perf*) » ./mame pacman -bench 300
Average speed: 12235.35% (299 seconds)
```
=> cpu/z80: Improved z80 code generation

src/mame/sega/segas16b.cpp
Based on the picture of one PCB based on Yahoo Auctions I've updated the name on the Eprom labels.
=> segas16b.cpp: Update wfishing EPROM labels

src/mame/oberheim/dmx.cpp
* Corrected the calculation of the voice DC-block HPF.
* Audio streams are in voltages.
* Cross-checked component values with parts list, and corrected a couple of them.
* Also updating master volume and pitch adjustments on reset.
* Misc small cleanups.
=> oberheim/dmx.cpp: Corrected HPFs. Converted audio path to voltages.

src/mame/shared/namco_c355spr.cpp
C355 chip is also paired with 187 chip, reference: https://www.dragonslairfans.com/smfor/index.php?PHPSESSID=929acce8cd54ac69a6587a3d8fba46a0&topic=1067.msg10074#msg10074
=> shared/namco_c355spr.cpp: Fix description

src/devices/video/ppu2c0x.cpp, src/devices/video/ppu2c0x.h, src/devices/video/ppu2c0x_sh6578.cpp, src/devices/video/ppu2c0x_sh6578.h, src/devices/video/ppu2c0x_vt.cpp, src/devices/video/ppu2c0x_vt.h
- Use device_palette_interface for color palette function
- Move non-public function into protected: and private:
- Fix typename for member variables, Fix save state support
- Fix typename inconsistency
=> video/ppu2c0x*.cpp: Updates/Cleanups:

hash/neogeo.xml
Double Dragon One (demo) [OzzyOuzo]
Double Dragon One (prototype 1) [Casa de Ruivo]
Double Dragon One (prototype 2) [Casa de Ruivo]
Xeno Crisis [archive.org]
=> neogeo.xml: Added 4 working items

scripts/src/cpu.lua, src/devices/cpu/z80/t6a84.cpp, src/devices/cpu/z80/t6a84.h, src/devices/cpu/z80/z80.cpp, src/devices/cpu/z80/z80.h, src/devices/cpu/z80/z80.lst, src/devices/cpu/z80/z80make.py
cpu/z80/t6a84.cpp: isolate device specific callbacks
=> z80/z80make.py: Revisited z80 code generator

hash/msx1_cart.xml, scripts/src/bus.lua, src/devices/bus/msx/cart/cartridge.cpp, src/devices/bus/msx/cart/slotoptions.cpp, src/devices/bus/msx/cart/slotoptions.h, src/devices/bus/msx/cart/video80.cpp, src/devices/bus/msx/cart/video80.h
Hi,
with this PR I'd like to add the video80 card I built for my MSX1 system back in 1988, please.
I also fixed the ROM image for the Philips VY0010 floppy interface.
Thanks.
--F.Ulivi
=> Msx: adding Video80 homebrew card

hash/tvdear.xml, src/mame/skeleton/tvdear.cpp
new NW Software List additions
----
Illust-Cassette No. 2 - Bad Badtz-Maru [TeamEurope]
=> added a tvdear cart

src/mame/sega/model2_v.cpp
Panoramic views during attract sequence of various games in linked mode should now work properly
=> model2: fix error in clipping plane calculation

hash/sega_beena_cart.xml
New working software items
---
Soreike! Anpanman Waku Waku Eigo Game! [TeamEurope]
New partially working software items
---
Juuken Sentai Gekiranger: Niki Niki! Kazu Katachi ni Challenge! [TeamEurope]
=> sega_beena_cart.xml: Add 2 new software items

src/mame/bmc/koftball.cpp
=> update info. Actually is ym2413 koftball.cpp

src/emu/emumem.h
That just 1-2% sometimes but still...
=> emu/emumem.h: Optimized cache line detection

hash/snes.xml, scripts/src/bus.lua, src/devices/bus/snes/snes_carts.cpp, src/devices/bus/snes/st018.cpp, src/devices/bus/snes/st018.h, src/mame/nintendo/snes.cpp
moritas2 is now boots, and in-game AI is works.
=> bus/snes/st018.cpp: Add primary support of ST018 coprocessor

hash/msx2_flop.xml
Dark Castle (Japan) [Trevgauntlet Neu]
=> msx2_flop.xml: New dump added

src/devices/sound/k007232.cpp, src/devices/sound/k007232.h
- Use reference for referencing channel structs
- Fix argument name match to both .cpp and .h files
- Fix spacings
- Fix namings
=> sound/k007232.cpp: Updates

src/devices/cpu/z80/z80.cpp, src/devices/cpu/z80/z80.h, src/devices/cpu/z80/z80.lst
@happppp yeah, this one is better than #13605 
Not sure what I tested before...
=> cpu/z80/z80.cpp: Get rid of large flag LUTs

hash/zx81_cass.xml
Aritmética I [Planeta Sinclair]
Battle of Britain [Planeta Sinclair, Steve Brown]
Cedric the Clown (type-in, Sinclair User № 17 - August 1983) [Planeta Sinclair, Steve Brown]
Conta Bancária [Planeta Sinclair]
Contos de Grimm [Planeta Sinclair]
Cosmic Payback [John Connolly]
Demonstração TS 1000 [Planeta Sinclair]
Desenho I [Planeta Sinclair]
Family Fun [Planeta Sinclair, Steve Brown, Mark Westmoreland]
Flipper [Planeta Sinclair]
Fortaleza de Zorlac [Planeta Sinclair]
General Interest Programs [Planeta Sinclair]
Iniciação TS 1000 [Planeta Sinclair]
Nightmare Park + Music Plus [Planeta Sinclair, Steve Brown, Mark Westmoreland]
Orçamento Doméstico [Planeta Sinclair]
Othello (Direco) [Spectrum Computing]
Planet …
=> zx81_cass.xml: Added 21 working items

hash/saturn.xml
Dark Savior (Japan, Taikenban 19960409) [Redump.org]
Dark Savior (Japan, Taikenban 19960205) [Redump.org]
Ginga Eiyuu Densetsu (Japan, Sample) [Redump.org]
Keiou Yuugekitai - Okiraku Tamatebako (Japan) [Redump.org]
The King of Fighters '97 (Japan, Sample Hibaihin) [Redump.org]
Real Bout Garou Densetsu (Japan, Sample) [Redump.org]
Virtua Fighter 2 (Korea) [Redump.org]
Virtua Fighter CG Portrait Collection (Japan) [Redump.org]
Virtua Fighter Remix (Korea) [Redump.org]
=> saturn.xml: Added 9 working items, minor metadata cleanup

src/mame/act/victor9k.cpp
Added correct callbacks to make UPD7201 serial ports work
=> act/victor9k.cpp: Serial port fixes for Victor 9000 (victor9k)

src/mame/capcom/cps2.cpp, src/mame/mame.lst
Puzz Loop 2 (Japan 010201 Publicity) [Team Japump!!!]
Janpai Puzzle Choukou (Japan 010820 Publicity) [Team Japump!!!]
=> capcom/cps2.cpp Added Publicity Version Puzz Loop 2 and Choko

hash/fmtowns_cd.xml
It's been a while, but here's a new batch of additions to the FM Towns software list.
Advanced Dungeons & Dragons - Heroes of the Lance [redump.org]
Arquelphos [redump.org]
CD Learning System II - New Horizon English Course 3 [redump.org]
CD Learning System II - New Horizon English Course 3 (FM Towns Marty version) [redump.org]
ClearMind - Shimoguchi Yuuzan no Shuuchuuryoku Kaihatsu [redump.org]
Digital Pinup Girls Vol. 2 - Lovely Shooting [redump.org]
Euphony II / Score V1.1 L10 [redump.org]
F-BASIC386 Compiler V2.1 L20 [redump.org]
FM Towns Appli Jikkou Set (TownsGEAR, F-BASIC386) V2.1 L20 [redump.org]
FM Towns Demonstration CD-ROM 1993-nen Haru-gou [redump.org]
Fouge Vol. 1 - Ki - Japan - Maeda Shinzou no Sekai …
=> fmtowns_cd.xml: 23 additions, 3 replacements

src/mame/casio/pickytlk.cpp, src/mame/mame.lst
---
Super Picky Talk - My room fantasy [QUFB]
=> casio/pickytlk.cpp: Add Super Picky Talk - My room fantasy

src/mame/dataeast/brkthru.cpp, src/mame/mame.lst
Break Thru (World) [Jordi Tuells]
=> dataeast/brkthru.cpp: Add the world set of Break Thru (new parent)

src/mame/gaelco/mastboyo.cpp, src/mame/mame.lst
Master Boy (1987, Z80 hardware) [Josep Quingles, Recreativas.org]
=> gaelco/mastboyo.cpp: Add a new Master Boy (1987) set

src/mame/galaxian/galaxian.cpp, src/mame/galaxian/galaxian.h, src/mame/mame.lst
Lady Bug (bootleg on Galaxian hardware, encrypted) [Luis Arrufat, Francisco Javier Muñoz Calero]
=> Add a new Lady Bug bootleg set on Galaxian hardware

docs/source/advanced/bgfx.rst, docs/source/luascript/ref-devices.rst
Just a couple of very small fixes for things I saw while looking through the docs tonight.
The BGFX one will fix formatting issues, the others are fixes for things that bring up warnings during documentation compilation.
=> Small documentation fixes

src/devices/machine/generalplus_gpl16250soc.cpp, src/devices/machine/generalplus_gpl16250soc.h, src/mame/mame.lst, src/mame/tvgames/generalplus_gpl16250.cpp, src/mame/tvgames/generalplus_gpl16250.h, src/mame/tvgames/generalplus_gpl16250_rom.cpp, src/mame/tvgames/xavix_2002.cpp
------
Disney Princess Dress Mania TV (Japan) [David Haywood, Team Europe]
XaviX Bowling (XaviXPORT, PT2-BWL-11, Japan) [David Haywood, Team Europe]
=> current Plug and Play PR (2 not working sets)

src/mame/adp/stella8085.cpp, src/mame/mame.lst
a WIP schematic for 4087-000-101 can be found at
https://github.com/stonedDiscord/weisse_cpu
The release dates are largely taken from
https://www.goldserie.de/index.php/galerien/3217-excellent
=> adp/stella8085.cpp: add 11 nonworking romsets

src/mame/gaelco/goldart.cpp, src/mame/mame.lst
Goldart (France, Covielsa license) [Josep Quingles, Recreativas.org]
Goldart (Germany) [Josep Quingles, Recreativas.org]
Goldart (United Kingdom) [Josep Quingles, Recreativas.org]
=> gaelco/goldart.cpp: Add new sets for different countries

scripts/genie.lua, scripts/src/3rdparty.lua
* separate msvc, intel and clang compiler options
=> build: update vs/msbuild settings to reflect current clangcl

src/mame/gaelco/gaelco2.cpp, src/mame/mame.lst
Lizard Hunt (unprotected, checksum 25A83609) [Josep Quingles, Recreativas.org]
=> gaelco/gaelco2.cpp: Add an Alligator Hunt clone with alternate title

src/mame/gaelco/gaelcof3.cpp, src/mame/mame.lst
Mueve [Josep Quingles, Recreativas.org]
Ob-La-Di [Josep Quingles, Recreativas.org]
Also redumped PIC for 'susanita' and 'donpepito', fixed games names and manufacturer and improve notes.
=> gaelco/gaelcof3.cpp: Add two more kiddie ride dumps

src/mame/gaelco/lotoplay.cpp, src/mame/mame.lst
Loto-Play (set 1) [Josep Quingles, Recreativas.org]
Loto-Play (set 2) [Josep Quingles, Recreativas.org]
Loto-Play (set 3) [Josep Quingles, Recreativas.org]
Loto-Play (set 4) [Josep Quingles, Recreativas.org]
=> Skeleton driver for Gaelco/Covielsa Loto-Play

src/mame/mame.lst, src/mame/midw8080/8080bw.cpp
Cosmic Battle (Recreativos Franco bootleg of Space Invaders) [Jordi Tuells]
=> midw8080/8080bw.cpp: Add a Spanish Space Invaders bootleg named Cosmic Battle

src/mame/mame.lst, src/mame/midway/williams.cpp
Next Century (bootleg of Defender) [Retroclub.es, Recreativas.org]
=> midway/williams.cpp: Add a Spanish Defender clone named Next Century

src/mame/gaelco/gaelco.cpp, src/mame/mame.lst
Last KM (ver 1.0.0227, checksum 747a7443, prototype) [Josep Quingles, Recreativas.org]
=> gaelco/gaelco.cpp: Add a new Last Km clone

src/mame/mame.lst, src/mame/misc/flower.cpp
Flower (Japan) [Team Japump!!!]
Change Old 'Flower (Japan)' to 'Flower (Japan, bootleg)'
Flower (Japan)
main cpu ROM(1.5j) is same as Flower (US)
sound cpu ROM Label fix
=> misc/flower.cpp: Added Flower (Japan)

src/mame/moog/memorymoog.cpp, src/mame/oberheim/xpander.cpp
Following @happppp 's suggestion in #13710
=> memorymoog, xpander: Replaced matrix() with write_mx/my().

src/mame/gaelco/gaelco.cpp, src/mame/mame.lst
Big Karnak (ver. 1.0, checksum 1e38b94) [Josep Quingles, Recreativas.org]
=> gaelco/gaelco.cpp: Add a new Big Karnak clone

src/mame/cirsa/missbamby.cpp, src/mame/mame.lst
3 Mini [Javier Blanco, Recreativas.org]
=> cirsa/missbamby.cpp: Add Arfyc 3 Mini

src/mame/gaelco/gaelco2.cpp, src/mame/mame.lst
Pro Cycle Tele Cardioline (Salter fitness bike, V.1.0, checksum DECA) [Josep Quingles, Recreativas.org]
=> gaelco/gaelco2.cpp: Add another Pro Cycle Tele Cardioline set

hash/cdi.xml
Cyber Soldier Sharaku [ShiroeNL, Redump.org]
=> cdi.xml: New  software added

src/mame/handheld/hh_sm510.cpp, src/mame/mame.lst
Amusing Arithmetic (Elektronika) [Milan Galcik, Igor Nys]
=> hh_sm510.cpp: added new game Amusing Arithmetic

src/mame/handheld/hh_sm510.cpp, src/mame/mame.lst
Uchitel' arifmetiki (Elektronika) [Milan Galcik, Igor Nys]
=> hh_sm510.cpp: added new game Uchitel' arifmetiki

src/mame/sanyo/phc25.cpp
It has been verified on real hardware.
=> phc25: wire the gm1 signal to i/o port 40

src/mame/gaelco/glass.cpp, src/mame/mame.lst
Glass (development PCB) [Javier Valero, Recreativas.org, David Haywood]
=> gaelco/glass.cpp: Add a Glass prototype (development version, not working)

src/mame/handheld/hh_sm510.cpp, src/mame/mame.lst
Vinni-Pukh (Elektronika) (Winnie the Pooh) [Milan Galcik, Igor Nys]
=> hh_sm510.cpp: added new game Vinni-Pukh

src/mame/mame.lst, src/mame/tvgames/generalplus_gpl16250_rom.cpp, src/mame/tvgames/generalplus_gpl16250_romram.cpp, src/mame/tvgames/spg2xx_jakks.cpp
-------------
Wheel of Fortune - 2nd Edition (JAKKS Pacific TV Game) (Mar 15 2007 PAK2) [David Haywood, Sean Riddle, TeamEurope]
Deal or No Deal (JAKKS Pacific TV Game) [David Haywood, Sean Riddle, TeamEurope]
Hannah Montana - One in a Million (JAKKS Pacific TV Game) (Aug 13 2007 15:42:29) [David Haywood, Sean Riddle, TeamEurope]
Hannah Montana - Best of Both Worlds (JAKKS Pacific TV Game) (Aug 17 2007 22:47:47) [David Haywood, Sean Riddle, TeamEurope]
Retro Arcade featuring Space Invaders (JAKKS Pacific TV Game) [David Haywood, Sean Riddle, TeamEurope]
Bejeweled Deluxe (JAKKS Pacific TV Game) (Feb 28 2008 22:54:43) [David Haywood, Sean Riddle, TeamEurope]
=> JAKKS Pacific Plug and Play PR (4 WORKING machines, 2 NOT WORKING machines)

src/mame/gaelco/targeth.cpp, src/mame/mame.lst
Target Hits (ver 1.1, checksum B1F7) [Josep Quingles, Recreativas.org]
Quick Shots (ver 1.0, checksum AD0C) [Josep Quingles, Recreativas.org, David Haywood]
=> gaelco/targeth.cpp: Add new Target Hits clones

hash/saturn.xml
Also removed five bad dumps.
New not working software items:
AI Shougi 2 (Japan) [redump.org]
Redumped not working software list items:
Advanced V.G. (Japan) [redump.org]
AnEarth Fantasy Stories: The First Volume (Japan) [redump.org]
Asuka 120% Limited: Burning Fest Limited (Japan) [redump.org]
Baldy Land (Japan) [redump.org]
Bomberman Wars (Japan) [redump.org]
Dark Savior (Europe) [redump.org]
Dark Savior (USA) [redump.org]
Dark Seed (Japan) [redump.org]
Dark Seed 2 (Japan) [redump.org]
Removed items:
AI Shougi (Japan, alt)
AnEarth Fantasy Stories - The First Volume (Japan, alt)
Dark Savior (Japan, alt)
Dark Savior (Japan, alt 2)
Dark Savior (Japan, alt 3)
=> saturn.xml: Added 1 new item, replaced nine items

src/mame/mame.lst, src/mame/pc/play4texash.cpp
Play 4 Texas Hold'em [anonymous]
=> Add a PC-based casino Poker machine

src/mame/gaelco/gaelco3d.cpp, src/mame/mame.lst
Radikal Bikers (prototype) [Javier Valero, Recreativas.org]
=> gaelco/gaelco3d.cpp: Add a prototype of Radikal Bikers (not working)

src/mame/mame.lst, src/mame/tvgames/spg110.cpp, src/mame/tvgames/spg2xx.cpp, src/mame/tvgames/spg2xx_jakks_gkr.cpp, src/mame/tvgames/spg2xx_lexibook.cpp
---------
Carl Edwards 99 [David Haywood, Sean Riddle, TeamEurope]
Disney Game It! Princess Pals [David Haywood, Sean Riddle, TeamEurope]
---------
Jibbi [David Haywood, Sean Riddle, TeamEurope]
Blue's Room: Coloring With Blue (JAKKS Pacific TV Game) [David Haywood, Sean Riddle, TeamEurope]
Tele-Doodle (JAKKS Pacific TV Game) [David Haywood, Sean Riddle, TeamEurope]
Super Silly Makeover (JAKKS Pacific TV Game) [David Haywood, Sean Riddle, TeamEurope]
--------
Bob the Builder - Project: Build It (JAKKS Pacific TV Game) (Feb 28 2006 10:48:40) [David Haywood, Sean Riddle, TeamEurope]
=> current SunPlus based Plug & Play PR (2 working additions, 5 non-working)

src/mame/layout/roland_tr707.lay, src/mame/roland/roland_tr707.cpp
The two layouts are very similar, so using a single layout with some elements parameterized by an output.
=> roland_tr707.cpp: interactive layout for the two systems in this driver.

src/mame/astrocorp/astrcorp.cpp
=> astrocorp/astrcorp.cpp: Add note about ASTRO F01 chip [ArcadeHacker]

src/mame/gaelco/gaelco.cpp, src/mame/gaelco/gaelco.h, src/mame/gaelco/gaelco_v.cpp, src/mame/mame.lst
Xor World (different hardware, ver 1.1, checksum 3333BA, prototype) [Josep Quingles, Recreativas.org, David Haywood]
Xor World (different hardware, ver 1.1, checksum 333462, prototype) [Josep Quingles, Recreativas.org, David Haywood]
=> Add two Xor World sets (different hardware, not working)

hash/zx81_cass.xml
1K Supertrio [Planeta Sinclair, Mark Westmoreland, Steven Brown]
2ª Dimensão [ZX81 Never Die]
Aventura & Mistério [ZX81 Never Die]
Aventuras na Selva (type-in, Micro Sistemas Nº 23 - Agosto 1983) [ZX81 Never Die]
Bichos & Cia [ZX81 Never Die]
Captain on the Bridge - Episode 1: Sinclair Maru? [Warp 8-bit Games]
Combate [ZX81 Never Die]
Darts (type-in) [Planeta Sinclair, Steven Brown]
Defensor 3D [ZX81 Never Die]
House of Gnomes (alt) [Planeta Sinclair, Mark Westmoreland, Steven Brown]
Kludo + Battleships [Planeta Sinclair, Mark Westmoreland, Steven Brown]
Kong Jump (type-in, Your Computer Vol. 3 Nº 6 - June 1983) [Planeta Sinclair, Steven Brown]
Mad Maze (type-in, Sunclair User № 11 - February 1983) [Planeta …
=> zx81_cass.xml: Added 36 working items + 1 not working

src/mame/taito/taitotz.cpp
This primarily improves the handling of "direct" geometry, but with some additional niceties on T&L geometry as well.
- The previously-identified bitfield indicating the number of vertices in direct geometry does not, in fact, appear to indicate the number of vertices.
- Support for alpha blending on direct geometry is added.
- Support for alpha-cutout on direct geometry is added.
- Texture mode 3 carries the most clearly "primary" texture data in the same 16 bits of a doubleword as the other texture modes. However, the second texture channel does appear to hold valid texture data, so for now I'm summing the two together. This is likely wrong, but will suffice until I can whip together an offline frame debugger for Type-Zero and really dig into what's going on.
- Additive blending support …
=> Improve graphics in some Taito Type-Zero games

src/mame/taito/taitotz.cpp
Power Shovel Simulator appears to upload direct-FIFO data which is 96 32-bit words in length, so the existing 64-word array size was insufficient to store that data. This change increases the size of the direct-FIFO buffer to that limit, as well as slightly adjusting how direct packets are handled in order to avoid attempting to process garbage data.
There's some evidence to indicate that there's a bug in Taito's own code, as the direct-FIFO upload routine is asked to upload 0x60 (96) 32-bit words, while the buffer being uploaded only contains a single packet, which - including the header and the four consecutive 32-bit words containing 0 in order to flush - is 0x60 _bytes_ in length. Memory immediately following those 0x60 bytes seems to contain other junk data (FIFO-related error …
=> Avoid crashing in Taito Type-Zero direct-FIFO handling

hash/psx.xml
2002 FIFA World Cup (Europe) [Redump]
2002 FIFA World Cup (France) [Redump]
2002 FIFA World Cup (Germany) [Redump]
2002 FIFA World Cup (Italy) [Redump]
2002 FIFA World Cup (Spain) [Redump]
3, 2, 1, Smurf! My First Racing Game (Europe) [Redump]
Ace Combat (Japan) [Redump]
Air Combat (Europe) [Redump]
Air Combat (Europe) (EDC) [Redump]
Darkseed (Japan) [Redump]
Transport Tycoon 3D: SL Kara Hajimeyou!! (Japan) [Redump]
New NOT working software list addition
Bedlam (Europe) [Redump]
Redumped software list items
2002 FIFA World Cup (USA) [Redump]
Air Combat (USA) [Redump]
Smurf Racer! (USA) [Redump]
Darkseed II (Japan) …
=> psx.xml: Added 11 working items + 1 not working + 4 redumped

src/mame/mame.lst, src/mame/namco/namcos12.cpp
Tekken 3 (Japan, TET1/VER.D) [Tailsnic Retroworks]
=> namco/namcos12.cpp: Add Tekken 3 (Japan, TET1/VER.D)

src/mame/gaelco/lotoplay.cpp, src/mame/mame.lst
Also add info and clock frequency for PIC-based Loto Play
=> gaelco/lotoplay.cpp: Remove 'lotoplayc', it was a bad dump

src/devices/machine/z80dma.h, src/mame/sinclair/specnext_dma.cpp
Now we comply with the factory test
=> sinclair/specnext_dma.cpp: Added prescaler register

hash/kim1_cass.xml
add kim-1 cassette tapes from http://retro.hansotten.nl/
https://www.dropbox.com/scl/fo/l0l8itidgzihtyw14jltq/ABiVkk3_tnyBFgVl9MD_PFs?rlkey=1h87rbfjkjk24qntnw79f42c4&st=p90y9pkz&dl=0
=> add kim-1 cassette tapes

src/mame/philips/mcd212.cpp
To validate:
1. Using the validation disc (EU)
2. Video Representations
3. More > More > Double CLUT
4. Watch the example
Previously, only the 7 bright colors were rendered.
Now the 7 dark colors are also rendered. This shows that the Double Clut 7 mode is now working.
=> CD-i: Add Double CLUT 7 Color Mode

src/mame/philips/mcd212.cpp, src/mame/philips/mcd212.h
The additional header value did not get included. Sorry about that.
=> Add missing header value

src/devices/cpu/z80/z80.lst
see: https://wiki.specnext.dev/Extended_Z80_instruction_set
=> cpu/z80n: Updated timings for z80n instructions

src/mame/mame.lst, src/mame/nintendo/nes_vt02_vt03.cpp, src/mame/nintendo/nes_vt369_vtunknown.cpp, src/mame/nintendo/nes_vt42xx.cpp, src/mame/tvgames/st2302u_bbl_spi.cpp
--------
Supreme 200 (handheld) [TeamEurope, David Haywood]
Spillekonsol Game console - 108-in-1  [TeamEurope, David Haywood]
Game On 100-in-1  [TeamEurope, David Haywood]
Power - Charging and playing games (D12) (416-in-1) [TeamEurope, David Haywood]
--------
Digital Pocket Hand Held System 268-in-1 - Model 8633 [TeamEurope, David Haywood]
Handheld Game Console 339-in-1 [TeamEurope, David Haywood]
S10 Handheld Game Console (520-in-1, fake entries) [TeamEurope, David Haywood]
-------
Retro Arcade Game Controller (150-in-1) (set 2) [TeamEurope, David Haywood]
=> add 4 not working sets + 4 working

src/mame/handheld/vegaplus.cpp, src/mame/mame.lst, src/mame/nintendo/nes_vt32.cpp, src/mame/nintendo/nes_vt369_vtunknown.cpp, src/mame/skeleton/evolution_handheld.cpp, src/mame/tvgames/generalplus_gp327902.cpp, src/mame/tvgames/generalplus_gpl16250_spi_direct.cpp, src/mame/tvgames/generalplus_gpl32612.cpp, src/mame/tvgames/myaatari.cpp, src/mame/tvgames/spg2xx.cpp
------------
Spider-Man 2 Web Action [TeamEurope, David Haywood]
------------
Retro Racer (30-in-1) [TeamEurope, David Haywood]
Power Console - Paw Patrol [TeamEurope, David Haywood]
Sumikko Gurashi - Sumikko Atsume (Japan) [TeamEurope, David Haywood]
Chiikawa Camera De Ya-! (Japan) [TeamEurope, David Haywood]
Sumikko Gurashi - Sumikko Catch (Japan) [TeamEurope, David Haywood]
Kiratto Pri-Chan Design Palette (Japan) [TeamEurope, David Haywood]
Smatomo (Japan) [TeamEurope, David Haywood]
Kunio-kun TV (5-in-1) [TeamEurope]
ZX Spectrum Vega+ [Andrew Bickers]
Interactive Game Console (Model B608, YRPRSODF) [TeamEurope, David Haywood]
AR Dance Mat (Model DM02, YRPRSODF) [TeamEurope, David Haywood]
Power Rangers Dino Thunder: Thunder Action …
=> current Plug and Play PR (13 not working systems, 1 working)

src/mame/namco/namcos23.cpp
This addresses the newly-introduced issue with title-screen graphics being missing in Final Furlong 2 and Crisis Zone, while retaining the fix for the Downhill Bikers intro being mostly-occluded a fullscreen quad.
This additionally improves attract mode in Downhill Bikers, allowing 3D models to be sandwiched between different visible layers of direct geometry.
=> Improve direct-polygon Z-sort handling in Namco System 23

src/mame/konami/tutankhm.cpp, src/mame/mame.lst
Tutankham (bootleg) [Jordi Tuells]
=> konami/tutankhm.cpp: Add a Tutankham bootleg set 

language/Japanese/strings.po
- Added translations for new audio functions.
- Improved consistency in Japanese terminology throughout the interface
=> Updated Japanese translations.

hash/zx81_cass.xml
Alien Attack (Bug-Byte) [Planeta Sinclair, Paul Farrow, Steven Brown]
Around Europe in Eighty Hours + Race Around Europe [Planeta Sinclair, Mark Westmoreland, Steven Brown]
Asteróides (Microsoft) [ZX81 Never Die]
Fruit Collector (type-in, Sinclair Programs № 7 - May 1983) [Planeta Sinclair, Steven Brown]
Fruit Collector (type-in, Sinclair Programs № 7 - May 1983) (modified by Stuart Campbell) [Planeta Sinclair, Steven Brown, Stuart Campbell]
Gamão [ZX81 Never Die]
Great Britain Limited (version 1) [Planeta Sinclair, Mark Westmoreland, Steven Brown]
Guerra nas Estrelas [ZX81 Never Die]
Invasores 2K [ZX81 Never Die]
Invasores do Espaço + Tubarão [ZX81 Never Die]
Invincible (type-in, ZX Computing № 8 - …
=> zx81_cass.xml: Added 29 working items

hash/gamegear.xml, hash/sg1000.xml
New working software list items (sg1000.xml):
Xun Bao Er Dai (Taiwan, Alt) [SMS Power!]
Space Armor (Taiwan, v20, Alt) [SMS Power!]
New non-working software list items (gamegear.xml)
Wonder Kid (USA, prototype) [SMS Power!]
=> gamegear.xml, sg1000.xml: New software list items

src/mame/konami/djmain.cpp
- Use std::swap for swap layer
- Fix namings
- add notes
=> konami/djmain.cpp: Use generic gfx decode layout, Minor cleanups

src/mame/layout/linn_linndrum.lay, src/mame/layout/roland_tr707.lay
Also verified my other layouts still work.
=> linn_linndrum.lay, roland_tr707.lay: Adapting to changes in #14113.

src/mame/ensoniq/esq1.cpp
And remove old comment (the keyboard scanning was already implementented).
=> Add my name to (c) holders list on Ensoniq ESQ-1 driver

src/mame/layout/ap10.lay, src/mame/layout/ct8000.lay, src/mame/layout/ctk530.lay, src/mame/layout/cz1.lay, src/mame/layout/cz101.lay, src/mame/layout/cz230s.lay, src/mame/layout/psr110.lay, src/mame/layout/psr150.lay, src/mame/layout/psr180.lay, src/mame/layout/psr75.lay, src/mame/layout/psr76.lay, src/mame/layout/pss11.lay, src/mame/layout/pss12.lay, src/mame/layout/pss21.lay, src/mame/layout/pss31.lay, src/mame/layout/pss6.lay
(#14113)
This should be all of mine. I don't know offhand how many others need doing (aside from a few in the yamaha dir)
=> update element order for various casio and yamaha keyboard layouts

src/mame/sega/segas32_v.cpp
Thanks to @mamehaze for previous commits:
https://github.com/mamedev/mame/commit/3ca05f596d14fba033f33fc4ec1dbb28d8617070
https://github.com/mamedev/mame/commit/13b609deb2076a9c5df4e55dc042e1fc3c6f3988
=> segas32: fix NBG0 - NBG3 layer flip

src/mame/layout/linn_linndrum.lay
=> Fix rendering of LinnDrum's rounded corner outlines.

src/devices/cpu/t11/t11.cpp, src/devices/cpu/t11/t11.h, src/devices/cpu/t11/t11ops.hxx, src/mame/mame.lst, src/mame/ussr/1801vp014.cpp, src/mame/ussr/bk.cpp, src/mame/ussr/bk.h, src/mame/ussr/bk_m.cpp
Improve interrupt handling in K1801VM1 CPU core.
Miscellaneous bugfixes (keyboard interrupt enable, cassette input).
=> ussr/bk: emulate bk0011 hardware and b&w/color video switch.
