mamedev/mame

src/devices/cpu/powerpc/ppcdrc.cpp, src/devices/cpu/powerpc/ppcfe.cpp, src/mame/konami/stingnet.cpp
Findings around this can be found here: https://github.com/mamedev/mame/commit/62f77513f1a4297dd15971f8909e0922918a53cc#r125639616
For 4xx series and 601 this change will skip over the register update which is what the CPU manuals says should happen. For any other flavor it will raise an illegal instruction exception since the behavior isn't defined but it does state it's an invalid form.
Only known game so far to rely on this functionality is `tropchnc` which explodes early on in boot process without this fix.
=> ppc: Don't overwrite RA in lmw instruction

src/mame/konami/twin16.cpp
We have dumped and measured PROM E16 used for priority encoding from a GX870 PWB351311A board. I have added the information to the driver.
=> konami/twin16.cpp: Dumped priority PROM for The Final Round/Hard Puncher

src/mame/apple/apple3_m.cpp
This updated is based on the schematic and logic analyser traces to confirm behavior on real hardware. The CPU speed is down changing to 1MHz when reading the video memory, and then back to 2MHz during the blanking periods. The video screen can also be turned off, resulting in 2MHz speed running full time.
The other thing impacting the CPU speed is slowdowns for dram refresh cycles. There is a logic rom that takes input from the video counters to generate the refresh signal, it's not a simple asymmetric clock signal. I have used an average frequency measured from a logic analyser trace for now for the resultant higher clock speed.
With these changes in, the game Atomic Defence speech is very close in sound now to the real hardware. Previously it was running much faster in MAME. And the …
=> apple/apple3_m.cpp: Added cpu clock changing for video raster scanning

scripts/src/3rdparty.lua, src/osd/modules/diagnostics/diagnostics_win32.cpp
I recently tried building MAME for Windows/arm64 with clang and mingw and it almost just worked, given the right build options. These are fixes for the couple of build issues I encountered.
These changes were tested by compiling natively with msys2/clangarm64 and also by cross-compiling with [llvm-mingw](https://github.com/mstorsjo/llvm-mingw). I booted a handful of machines without issue.
The crash diagnostic code is tested and working as well. Example:
```
-----------------------------------------------------
Exception at EIP=00007FF66C3144A8 (+0x6c3144a8): ACCESS VIOLATION
While attempting to write memory at 0000000000000000
-----------------------------------------------------
X0=000001B05EAC9E10  X1=CDCDCDCDCDCDCDCD  X2=0000000000000018  X3=0000000000000040
X4=0000000000000003 …
```
=> Fix mingw/arm64 build issues

hash/mac_cdrom.xml, hash/mac_flop.xml, hash/mac_flop_clcracked.xml, hash/mac_flop_orig.xml, hash/mac_hdd.xml, hash/mac_hdflop.xml
Added the manufacturer's name.
Lowercase on the storage medias' name.
Renamed "Mac" abbreviation to "Macintosh".
=> Renamed various Apple Macintosh software lists' description

src/mame/namco/namcos12.cpp
Previously this game would crash to a blue screen if you selected "race" mode, just before you entered the car selection screen. The crashing no longer happens after a new redump from Phil. The game still needs the network PCB emulated to fix the frame rate hitching issue that happens when it tries to communicate with the network PCB, so it still can't be promoted to working.
=> namco/namcos12: redump of bad ROM for Kart Duel [Phil Bennett]

hash/msx1_cass.xml
Replaced Booty (Europe) with a better dump. [file-hunter] 
Replaced North Sea Helicopter with a better dump. [file-hunter]
Removed Silicon Dreams (Europe, alt 2) and Silicon Dreams (Europe, alt 3).
Renamed Soviet (Europe?) to Soviet (Spain).
Inleiding tot de SpectraVideo SV 728 (Netherlands) [file-hunter] 
TEACH YOURSELF BASIC (United Kingdom) [file-hunter] 
The Archers (Europe) [file-hunter]
Bang! Bang! (Japan) [file-hunter]
The Growing Pains of Adrian Mole (United Kingdom) [file-hunter] 
The Munsters (Europe) [file-hunter]
River Chase (Japan) [file-hunter]
Scapeghost (Europe) [file-hunter]
Sea Hunter (Europe) [file-hunter]
The Secret Diary of Adrian Mole Aged 13¾ (Europe) [file-hunter] 
Silicon Dreams I - Snowball (United …
=> msx1_cass.xml: Added 70 items, 68 working. Replaced 2 items. Removed 2 items. Renamed 1 item.

src/mame/heathkit/tlb.cpp
Fixes scan out of video when GP-19 is in graphics mode.
=> heathkit/tlb.cpp: Fix GP-19 graphics mode display

src/mame/capcom/cps2.cpp
Adds support for the debugging DIP switches which are referenced in many CPS2 games and which apparently existed on dev boards thanks to images that have surfaced. Implemented as a machine configuration.
A write-up detailing the switches is posted here:
https://sudden-desu.net/entry/cps2-debug-switches-and-the-games-that-love-them
Note that in the article, I mentioned deciding against submitting a PR as it should technically be a whole new driver as it is different hardware, but given a conversation with @MooglyGuy on twitter, I've decided to go ahead and let the devs decide if it should be accepted.
https://twitter.com/TheMogMiner/status/1588881175309086730
=> capcom/cps2.cpp: Support for CPS2 debug DIP switches

src/osd/sdl/osdsdl.cpp
SDL_GetDesktopDisplayMode returns 0 on success.  The current logic seems to assume that it returns true on success.  Updated the logic so that the lines printing the desktop mode and current display mode info can be reached.
=> osd/sdl: Fixed interpretation of result of SDL_GetDesktopDisplayMode

src/mame/heathkit/tlb.cpp
Fix the following coverity error:
```
*** CID 465494:  Uninitialized members  (UNINIT_CTOR)
/src/mame/heathkit/tlb.cpp: 1073 in heath_superset_tlb_device::heath_superset_tlb_device(const machine_config &, const char *, device_t *, unsigned int)()
1067      *
1068      * Developed by TMSI
1069      */
1070     heath_superset_tlb_device::heath_superset_tlb_device(const machine_config &mconfig, const char *tag, device_t *owner, uint32_t clock) :
1071            heath_tlb_device(mconfig, HEATH_SUPERSET, tag, owner, clock)
1072     {
CID 465494:  Uninitialized members  (UNINIT_CTOR)
>>>     Non-static class member "m_selected_char_set" is not initialized in this constructor nor in any functions that it calls.
1073     }
```
=> heathkit/tlb.cpp: fix coverity error

src/osd/sdl/window.cpp
Meant to address the issue reported here:
https://github.com/mamedev/mame/issues/7532#issuecomment-1713880191 And possibly here:
https://github.com/mamedev/mame/issues/7922#issuecomment-1713887214
=> removes SDL_WINDOW_BORDERLESS flag

hash/msx1_cass.xml
Chōjin Rokku Majo No Millenium (Japan) [file-hunter]
Lancelot (United Kingdom) [file-hunter]
Let's Computer (Japan) [file-hunter]
Lord Watson (Spain) [file-hunter]
Mandragore (United Kingdom) [file-hunter]
Marude Son Goku (Japan) [file-hunter]
Minder (United Kingdom) [file-hunter]
Mister Jaws (Netherlands) [file-hunter]
MST-CALC (Europe) [file-hunter]
Ninja (Netherlands, Aackosoft) [file-hunter]
Ninja (Netherlands, Eaglesoft) [file-hunter]
Octopuss (France) [file-hunter]
Offering (Japan) [file-hunter]
Oh No! (Brazil) [file-hunter]
Phantomas 2 (Spain, alt) [file-hunter]
Photographic Memory (Netherlands) [file-hunter]
Pirates (Spain) [file-hunter]
Portopia Renzoku Satsujin Jiken (Japan) [file-hunter] 
Punchy & Judy (United …
=> msx1_cass.xml: Added 29 items.

src/devices/machine/t10mmc.cpp
Split off from previous PR (https://github.com/mamedev/mame/pull/11558#pullrequestreview-1636339911) because this regression needs to be fixed regardless of that PR.
The code reads CD_TRACK_MODE1 using CD_TRACK_MODE1_RAW because the CD-ROM code can generate a usable 16-byte header for non-raw tracks without the header. I forgot that when implementing the buffer_offset stuff so it's returning 16 bytes of header when user data is requested.  This PR fixes `taiko6` not loading currently.
=> t10mmc: Fix reading user data from mode 1 tracks using T10MMC_CMD_READ_CD

hash/msx1_flop.xml
Removed:
Bank Street Writer (Japan, disk conversion)
Cannon Fighter (Japan, disk conversion)
Chubby Gristle (United Kingdom, disk conversion)
Dip Dip (Spain, disk conversion)
Dizzy Ball (Japan, disk conversion)
DonPan (Japan, disk conversion)
Driller Tanks (Japan, disk conversion)
Driller Tanks (Japan, disk conversion, alt)
Eagle (Spain, disk conversion)
Emerald Isle (United Kingdom, disk conversion)
Eric and the Floaters (Europe, disk conversion)
Football Manager (Europe, disk conversion)
Graphic Artist (Japan, disk conversion)
Jump Jet (Brazil, disk conversion)
Keystone Kapers (United Kingdom, disk conversion)
Minder (United Kingdom, disk conversion)
The Munsters (United Kingdom, disk conversion)
The Munsters (United Kingdom, disk conversion, alt) 
Punch & Judy (United Kingdom, disk …
=> msx1_flop.xml: Removed 26 disk conversions.

docs/source/debugger/execution.rst
As reported [here](https://github.com/mamedev/www.mamedev.org/issues/28), there is a extra tick mark in the `gtime` example in `execution.rst`. This simply removes the extra tick mark.
=> Removed extra tick after gtime example in documentation

docs/source/advanced/ctrlr_config.rst, docs/source/advanced/hlsl.rst, docs/source/commandline/commandline-all.rst, docs/source/commandline/sdlconfig.rst, docs/source/debugger/execution.rst, docs/source/debugger/index.rst, docs/source/debugger/registerpoints.rst, docs/source/index.rst, docs/source/initialsetup/configuringmame.rst, docs/source/luascript/ref-input.rst, docs/source/luascript/ref-mem.rst, docs/source/luascript/ref-render.rst, docs/source/plugins/autofire.rst, docs/source/plugins/discord.rst, docs/source/plugins/index.rst, docs/source/plugins/inputmacro.rst, docs/source/usingmame/assetsearch.rst, docs/source/usingmame/mamemenus.rst, docs/source/usingmame/usingmame.rst, docs/source/whatis.rst
Fixes of various typos, misspellings, and other minor errors in the website Documentation.
=> Various Documentation fixes

src/devices/cpu/ks0164/ks0164.cpp, src/devices/cpu/ks0164/ks0164d.cpp, src/devices/sound/ks0164.cpp, src/devices/sound/ks0164.h, src/mame/misc/dgpix.cpp
- Removed the fake intelfsh emulation code and turned it all into real intelfsh devices. Each of the ROM board types have up to 8 flash ROMs but usually only 2 are populated, except for kdynastg which had 4. This involved some endianness changes so the patches were also fixed.
- Implemented BMkey ROM PCB and refactored out the old Type A ROM PCB code into separate devices because they have slightly different memory mappings and usages
- Implemented/documented a new rotate opcode in the KS0164 CPU which was in a codepath used by btplay2k
- Fixed issue where shifts would not disassemble due to bit 3 being set (the actual CPU emulation code does not use bit 3 for those opcodes)
- Swapped bges/bles opcodes which was causing some code to be executed improperly (fixes sound effects in a lot of …
=> dgpix: Use intelfsh + improvements to sound emulation

docs/source/commandline/sdlconfig.rst
While updating my toolset and getting things working again, I noticed there were four warnings in the documentation compilation process. Three of them are sections of the Lua scripting that haven't been written yet. This warning about ``sdlconfig.rst:2: WARNING: Title underline too short.`` could be fixed in one byte so I might as well just get it while I'm here.
=> Fix documentation compilation warning

3rdparty/bgfx/src/glimports.h
Current MAME git master code breaks if trying to compile on Linux / GLES 2.0 with bgfx and Wayland enabled because of bgfx r recent commit which has not been cherry-picked.
So this PR is loosely based on the following upstream bgfx commit : https://github.com/bkaradzic/bgfx/commit/66d50eb721334d6538a7eccdfdabb997667af1db
=> BGFX : Fixed duplicate import of functions on Linux using gles20

src/mame/apple/apple2video.cpp
Fix DHGR rendering when in Color/Composite mode (rgbmode == -1, in this function), so it doesn't fall through to the Video-7 RBG rendering, where only rgbmode == 1 or rgbmode == 3 is expected.  DHGR graphics look much better when the color artifact emulation is applied, which the Video-7 rendering does not do.
This returns the rendering back to what it was like in the MAME 252.  The bIsRGBMonitor was removed, as it seems to just be a patch to try and fix the issue introduced in 253, where the monochrome flag was added.  The addition of bIsRGBMonitor just made it so that when rgbmode was -1 in the function, it acted like rgbmode == 3, but that is not ideal.
This was tested using a Total Replay image, and playing DHGR games, such as Airheart and Heavy Barrel.
=> apple/apple2video.cpp: Fix Apple II DHGR rendering in Color/Composite mode

hash/fmtowns_cd.xml
- Removed the floppy disk from the Deep set as it was a "fake" disk that didn't come with the game originally.
- Fixed and cleaned up some dump source comments.
Auto Demo '93 Fuyu [redump.org]
CONFIG-ROM [beanstalk]
Drive Simulator - Home Navi V1.0 L01 [redump.org, cyo.the.vile]
Heike Monogatari (Gekan) [redump.org]
Hyper Planet Shiki Vol. 3 [redump.org]
Many Colors II [redump.org]
Naomi Komaki for Janis [redump.org]
NHK Special - Ginga Uchuu Odyssey Vol. 2 - Choushinsei Bakuhatsu (FM Towns Marty version) [redump.org]
Wing Commander (alt) [redump.org]
Woman's Memory [redump.org]
Z's Staff Pro Towns [redump.org]
Fujitsu Habitat V2.1 L13A …
=> fmtowns_cd.xml: added 13 new dumps, replaced 4

src/mame/heathkit/tlb.cpp
Add back in the TODO list, 2 issues with the GP-19 emulation that was inadvertently removed with https://github.com/mamedev/mame/pull/11534 since it looks like a fix proposed in https://github.com/mamedev/mame/pull/11504 is not going to be accepted.
=> heathkit/tlb.cpp - add back in gp19 fix TODOs

src/mame/casio/ra3.cpp
Just to make sure the user doesn't get blasted with noise if they try to play an empty patch.
=> casio_ra3_device: fill newly created image with zero instead of 0xff

src/devices/imagedev/midiin.cpp, src/devices/imagedev/midiin.h
This was tested on the cz101 driver using the patches from https://github.com/alphacharlie/CZ-Presets/tree/master/CZ-230S
The 100ms delay between messages is probably overkill for most devices, but it should be safe enough.
=> midiin_device: support loading sysex dumps

hash/apple2_flop_clcracked.xml, hash/apple2_flop_orig.xml, hash/mac_flop_clcracked.xml
Some metadata cleanup and consistency checking for Apple II softlists.
Software redumped (apple2_flop_orig.xml)
Wizardry III: Legacy of Llylgamyn (Version 4, 20-Aug-1983 update) [4AM, a2_qkumba]
Software redumped (apple2_flop_clcracked.xml)
Marty's Family Reader (4am crack) [4AM, LoGo]
Marty's Reading Workout (4am crack) [4AM, LoGo]
Greeting Card Maker (4am crack) [4am]
Peanuts Maze Marathon (4am crack) [4am]
The School Tool (4am crack) [4am]
New working software list items (apple2_flop_clcracked.xml) 
A First Program About Insects (4am crack) [4am]
Algebra Word Problems (4am crack) [4am]
Alphabet Zoo (4am crack) [4AM]
Arithmekicks (4am crack) [4am]
Arithmetickle (4am crack) [4am]
Destiny (4am …
=> New working software list items

scripts/genie.lua
Make generation of `has_*.h` files deterministic
Without this patch, order of entries in `generated/has_{buses,cpus,formats,machines,sounds,videos}.h` varied across builds.
This patch was done while working on [reproducible builds for openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds).
=> Make generation of has_foo.h files deterministic

src/lib/netlist/tools/nl_convert.cpp
I tried to convert a KiCad netlist and when a component value was missing or not a number nltool would only report `Exception caught: Error converting string to number:` but not what component or line was meant.
This PR counts the lines, prints the line number to stderr and passes on the exception.
=> nltool: report line number when an exception occurs

src/mame/igs/goldstar.cpp, src/mame/mame.lst
=> igs/goldstar.cpp: Dumped and added Dyna's El Dorado V5.1DR

scripts/src/cpu.lua, scripts/src/sound.lua, src/devices/cpu/arm7/ap2010cpu.cpp, src/devices/cpu/arm7/ap2010cpu.h, src/devices/sound/ap2010pcm.cpp, src/devices/sound/ap2010pcm.h, src/emu/ioport.h, src/mame/layout/beena.lay, src/mame/mame.lst, src/mame/sega/sega_beena.cpp
The driver can now play games, supporting all needed inputs except those requiring game specific peripherals.
Graphics are mostly done, there are still some issues which require a more accurate emulation of the pixel clock, which will be addressed after I disassemble some more games that make use of it. Currently it's used to support palette changes per scanline.
A new device is introduced for the Storyware (a booklet containing pages with artwork that can be interacted with a pen). An attempt was made to make it generic enough to eventually be reused for the Sega Pico / Yamaha Copera.
There are two main aspects about the Storyware device which I'm not entirely confident about:
1. To allow a player to specify page images, an environment variable needs to be set with the absolute path of …
=> sega_beena: Playable WIP

3rdparty/asio/include/asio/detail/impl/socket_ops.ipp
This fixes an incorrect variable reference in ASIO 1.20.0, replacing `result` with `value`. It was fixed in ASIO 1.22.1: https://github.com/chriskohlhoff/asio/commit/f79d3dc5c85675b01196d301595155ede085483d
I discovered this when porting MAME 0.259 to HaikuOS. (BTW, porting was successful, and the recipe is now in HaikuPorts.)
=> asio: Fix variable reference in sockatmark()

src/lib/formats/imd_dsk.cpp
Otherwise imgtool gets unhappy with IMD images:
Starting program: ./imgtool identify ./altos586/SDX-586.IMD
...
Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x000000000025d426 in bml3_diskimage_open (image=..., dummy=...)
at .../src/tools/imgtool/modules/bml3.cpp:520
#2  0x000000000024807d in imgtool_floppy_open_internal (stream=..., image=...)
at .../src/tools/imgtool/iflopimg.cpp:83
#3  imgtool_floppy_open (image=..., stream=...)
at .../src/tools/imgtool/iflopimg.cpp:101
#4  0x000000000024bbdf in imgtool::image::internal_open
(module=module@entry=0x302320, filename="./altos586/SDX-586.IMD",
read_or_write=read_or_write@entry=0, createopts=createopts@entry=0x0,
outimg=std::unique_ptr<imgtool::image> = {...}) …
=> formats/imd_dsk: implement get_sectors_per_track()

src/tools/imgtool/main.cpp
An invalid option to imgtool would cause it to crash:
$ ./imgtool create mess_hd hdd.img --moo=666
Segmentation fault (core dumped)
With a fix:
$ ./imgtool create mess_hd hdd.img --moo=666
--moo: Unrecognized option
Very lovely!
=> imgtool: check for unrecognized options

src/mame/heathkit/h89.cpp
Add support for Kres's KMR-100 ROM on the CPU board. This ROM is based on Ultimeth's ROM, and has some Kres specific functionality added.
=> heathkit/h89.cpp: Add support for Kres KMR-100 ROM

src/devices/machine/ins8250.cpp, src/mame/heathkit/tlb.cpp
Compared behavior between a real H19 and the emulated H19, while holding down the break key. Both behaved identically, other keys pressed while the break key was pressed queued up and processed after the break key was released.
=> ins8250.cpp: Implement Break functionality

src/devices/machine/ins8250.cpp
The original 8250 class chips did not have a scratchpad register at offset 7. This was added in the 16450. 
8250 datasheets specify this, and can be found in some old manuals like the Heath H89 or H19 manual. 
Here is the chart in an H89 manual.
It is also documented on this wiki, that the lack of the scratchpad was a way to determine it was an 8250 chip: https://en.wikibooks.org/wiki/Serial_Programming/8250_UART_Programming
=> ins8250.cpp: Remove scratchpad register access to 8250 class chips

src/mame/mame.lst, src/mame/universal/cosmic.cpp
Space Panic (set 4) [David Bosque, ClawGrip]
Also reformatted single line comments.
=> universal/cosmic.cpp: Dumped and added a new Space Panic set

hash/samcoupe_flop.xml, src/devices/bus/samcoupe/drive/atom.cpp, src/devices/bus/samcoupe/drive/drive.cpp, src/devices/bus/samcoupe/drive/floppy.cpp, src/devices/bus/samcoupe/expansion/expansion.cpp, src/devices/bus/samcoupe/mouse/mouse.cpp, src/devices/bus/samcoupe/mouse/mouseport.cpp, src/mame/samcoupe/samcoupe.cpp
Rename "Sam Coupe" to "Sam Coupé"
Rick Dangerous [Spectrum Computing]
Street Fighter 1 [Spectrum Computing]
=> samcoupe_flop.xml: Added 2 working items

src/mame/dataeast/karnov.cpp
The PCB can permanently disabled blanking interrupts, and it does so during power up. Writes to certain memory addresses will enable/disable the interrupt. Any write in the range will clear the current interrupt request. The logic in the schematic is not obvious, and it actually spawns to one more page at the end, but its functionality is modelled with this PR.
=> karnov: interrupt enable feature added as per schematics

src/devices/bus/sms_ctrl/diypaddle.cpp, src/devices/cpu/avr8/avr8.cpp, src/devices/cpu/avr8/avr8.h, src/devices/cpu/avr8/avr8ops.hxx, src/mame/elektor/avrmax.cpp, src/mame/handheld/pensebem.cpp, src/mame/homebrew/lft_chiptune.cpp, src/mame/homebrew/lft_craft.cpp, src/mame/homebrew/lft_phasor.cpp, src/mame/homebrew/sbc6510.cpp, src/mame/homebrew/uzebox.cpp, src/mame/makerbot/replicator.cpp, src/mame/ultimachine/rambo.cpp
AVR8:
- Optimized general-timer and SPI-timer handling.
- Templatized timer accessor functions in order to flatten branches and reduce runtime load.
- Approximately 1.5x speedup; `uzebox frogger` which ran at 82-83% unthrottled now runs at 146-147% unthrottled. Other AVR-based drivers show a similar speedup.
=> Optimizations for Atmel AVR-8 core

src/mame/funtech/supracan.cpp
supracan: Hooked up internal 68k boot ROM, externalized key. [Ryan Holtz, wxhsplash]
=> supracan: Hooked up internal 68k boot ROM, externalized key

hash/copera.xml, src/mame/sega/segapico.cpp
Minimal logic added to allow games to boot and load pages.
For page and pen input improvements, see #11592
New software items marked not working
-------------------------------------
Alice in Oshare-Land [Darksoft, rtw, Gaming Alexandria, QUFB, TeamEurope]
=> sega/segapico.cpp: Initial external interrupt support for Copera

hash/msx2_flop.xml
Replaced with a better dump: VS Rotation (Japan) [file-hunter]
Removed Ultima IV - Quest of the Avatar (Japan, alt disk 2) (disk 2 is from an English translation) 
Removed Vectron (Netherlands) and Vectron (Netherlands, alt) (extracted from a compilation) 
Removed Zoo (Netherlands, alt) and Zoo (Netherlands, alt 2) (hacked versions)
Konami Game Collection Bangai-hen (Japan, alt) [file-hunter] 
The Legend of Shonan (Japan) [file-hunter]
Sailor-fuku Senshi Felis (Japan) [file-hunter]
Tempo Typen (Netherlands) [file-hunter]
Tenkyuhai Special - Tougen no Utage (Japan) [file-hunter] 
Tenkyuhai Special - Tougen no Utage II (Japan) [file-hunter] 
Thanatos (Japan) [file-hunter]
Tokimeki Sports Gal (Japan) [file-hunter]
Tominaga …
=> msx2_flop.xml: Added 54 items, 49 working. Replaced 1 item. Removed 5 items.

hash/ibm5150.xml
3-D Helicopter Simulator [Total DOS Collection]
BattleZone [Total DOS Collection]
Boppie's Great Word Chase [Total DOS Collection]
Brimstone [Total DOS Collection]
Dig Dug (Atarisoft) [Total DOS Collection]
Dig Dug (Datasoft) [Total DOS Collection]
Changes [Total DOS Collection]
Championship Lode Runner [Total DOS Collection]
Cutthroats [Total DOS Collection]
Defender [Total DOS Collection]
Gremlins [Total DOS Collection]
Crime and Punishment [Total DOS Collection]
Crossfire [Total DOS Collection]
Ghostbusters [Total DOS Collection]
Julius Erving and Larry Bird Go One-on-One [Total DOS Collection]
Metadata changes …
=> ibm5150.xml: Added 11 working items + 4 not working

src/devices/cpu/tms32025/tms32025.cpp
The tms32025.cpp neg instruction, as coded, accidentally modifies ST0 instead of ST1.
The instruction should be modifying the C bit (in ST1) but the code calls SET0(C_FLAG) when it should call SET1(C_FLAG).
C_FLAG refers to a bit in ST1, not in ST0. 
Calling CLR0(C_FLAG) or SET0(C_FLAG) modifies ST0's INTM bit instead of ST1's C bit.
Reviewing the rest of the tms32025.cpp code, CLR1(C_FLAG) and SET1(C_FLAG) are used everywhere else.
=> tms32025 neg instruction accidentally modifies ST0 instead of ST1

src/mame/heathkit/h19.cpp, src/mame/heathkit/h89.cpp, src/mame/heathkit/tlb.cpp, src/mame/heathkit/tlb.h
Adds the Cleveland Codonics Imaginator I-100 option to the TLB(Terminal Logic Board) for the Heathkit H19 and H89 systems.
=> heathkit/tlb.cpp: Add Imaginator I-100 for Heath H19/H89

src/mame/taito/taito_f3.h, src/mame/taito/taito_f3_v.cpp
I've looked at the taito F3 video code [before](https://github.com/mamedev/mame/issues/10033), although at the time I didn't get very far. I recently decided to look at it again. The code is a bit hard to follow, so as part of getting to understand it a bit better, I've done some cleanup / updates to the code.
There are 3 commits:
[taito_f3_v.cpp, taito_f3.h: turn code defines into functions](https://github.com/mamedev/mame/commit/87bff61c975cb3179d1b3cf8f920f02b023cda50)
`Switch + define` were being used as unrolled `for` loops, these have been turned into normal `for` loops. Some defines were turned into functions/lambdas. There are still 2 code defines (`UPDATE_PIXMAP_SP`, `UPDATE_PIXMAP_LP`) left. I didn't come up with a good replacement solution, so no point in replacing them at this …
=> Taito F3 cleanup

src/devices/sound/upd933.cpp, src/devices/sound/upd933.h
From my still-in-progress CZ-1 driver, this mostly just changes interrupt generation to ensure accurate timing. Also better handling of interrupt priority (probably) and a couple of other miscellaneous things for the aforementioned driver.
=> upd933: rework irq to use a timer

src/mame/heathkit/tlb.cpp
imaginator's `device_reset()` was missing a call to the base class device_reset.
=> heathkit/tlb.cpp: Fix reset handling for slot device imaginator

src/mame/konami/thunderx.cpp
- removed unneeded loop counters
- removed unneeded multiplication/division operations
- matched variable names in both functions
Played the game for 20 minutes with no issues. Collision detection works the same.
=> thunderx: simplified code of 052591 PMC emulation for clarity

src/mame/heathkit/tlb.cpp
Fixes the on-screen menu (ctrl-ESC brings it up) for the superset ROM/ tlbc slot option for the H19/H89.
=> heathkit/tlb.cpp: Fix on-screen menus for superset tlbc slot option

hash/sega_beena_cart.xml
* Beena Town e Youkoso (Rev. S-100001-1002) [TeamEurope]
* Chiiku Drill Oshare Majo Love and Berry: Moji Kazu Chie Asobi [TeamEurope]
* Chiiku Drill Pocket Monsters Diamond &amp; Pearl: Moji Kazu Chie Asobi [TeamEurope]
* Doraemon Chinou Daikaihatsu! Waku Waku Game Land [TeamEurope]
* Doraemon Tanoshii En Seikatsu Youchien Hoikuen [TeamEurope]
* Doraemon Tanoshiku O-Keiko Hiragana Katakana [TeamEurope]
* Futari wa Pretty Cure Max Heart [TeamEurope]
* Game ga Ippai Kikansha Thomas [TeamEurope]
* Geneki Toudai-sei ga Tsukutta! 'Dekiru Ko ni Naru Seikatsu Shuukan Dragon Sakura Youji-hen' [TeamEurope]
* GoGo Sentai Boukenger Kazu to Katachi o Oboeyou! [TeamEurope]
* Kouchuu Ouja Mushiking: Nebu-Hakase to Kazu Katachi ni Challenge! [TeamEurope]
* Meitantei Conan: Kanzen Suiri! Kazu to Zukei no …
=> sega/sega_beena.cpp: Add 33 software list items

src/devices/cpu/powerpc/ppcdrc.cpp, src/devices/cpu/powerpc/ppcfe.cpp
Tested with tropchnc to make sure the original broken case is still working, as well as the landhigh and dendego3 games mentioned in the MAME testers report. landhigh gets to the title screen again and dendego3 boots to a question mark screen which is as far as it seems to go even without the invalid form checks I added in https://github.com/mamedev/mame/pull/11512.
After looking into it some more this week I saw in the 403 manuals it specifically states "The PPC403GCX executes all invalid instruction forms without causing an illegal instruction exception" (and similar for the other 403 variants). Couldn't find a direct mention of how to handle it in 60x manuals besides it just being undefined behavior, but it doesn't look like it should throw an illegal instruction exception there either …
=> cpu/powerpc: Remove illegal instruction exception for lmw invalid form case (MT08791)

src/mame/heathkit/tlb.cpp, src/mame/heathkit/tlb.h
Change from memory_view to memory bank for the Imaginator I-100 ROM.
=> heathkit/tlb.cpp: Use memory bank for imaginator I-100 ROM

src/mame/taito/cchance.cpp
According to taito's past official web page ["Arcade Game History"](https://web.archive.org/web/19970624172849/http://www.taito.co.jp/AHIS80B.HTM), release year is 1987.
Cherry Chance (チェリーチャンス) can be found in the 1987 entry.
=> taito/cchance.cpp: Verify manufacturer and year of release

src/devices/machine/t10mmc.cpp, src/mame/konami/ksys573.cpp
ROM dump thanks to tweak! and Caldenza. Track 23 of 845jab02 had 2 places where the audio dropped so Taro made a dump of his own CD to replace the old dump.
Additionally, CDDA audio volume should work properly again now. DDR will read in the CD audio control page, modify what it needs, then send it back on boot. In a refactor back in Sept the code was rewritten to use ptr instead of fixed offsets in the data buffer so all pages could be sent back when requested, but it unintentionally changed the layout of the page data so the volumes in older DDR games sounded really unbalanced when it tried to set the output gain for the CDDA channels to non-sense values.
=> konami/ksys573: Add Dance Dance Revolution (GC845 VER. JAB)

src/mame/taito/taito_f3_v.cpp
clean up after hack from #10920
mame combines palette base and pen color with addition, but the high planes in gfx overlap with lowest palette line bits in the color address (i.e. bitwise OR). account for this discrepancy in `get_tile_info`
=> taito/taito_f3_v.cpp: eliminate game-specific palette hack [ywy, 12]

src/mame/kaneko/airbustr.cpp, src/mame/kaneko/djboy.cpp, src/mame/kaneko/galpanic.cpp, src/mame/kaneko/hvyunit.cpp, src/mame/kaneko/kan_pand.cpp, src/mame/kaneko/kan_pand.h, src/mame/kaneko/sandscrp.cpp, src/mame/kaneko/snowbros.cpp, src/mame/kaneko/snowbros.h
kaneko/airbustr.cpp: Fix out of range issue
=> kaneko/kan_pand.cpp: Use device_gfx_interface for gfx decoding behavior, use correct type for variables

src/mame/atari/shuuz.cpp
Shuuz has been missing its sprite-shadow effect.
MO color 1 causes a PF palette shift + 0x200, if the mo has priority over the pf.
These shadows are visible at the feet of the round-card woman and the standing on-screen players.
Reference: https://farm5.staticflickr.com/4767/38913008994_3e2d2f6449_b.jpg
=> atari/shuuz.cpp: add missing sprite-to-playfield shadow effect 

src/emu/rendlay.cpp
This makes text on non-black backgrounds look better without the need to give text elements an explicit background color.
Before and after, using pss6 as an example:
=> emu/rendlay.cpp: keep the alpha channel intact when rendering text components

src/mame/konami/battlnts.cpp, src/mame/konami/bladestl.cpp, src/mame/konami/k007342.cpp, src/mame/konami/k007342.h, src/mame/konami/k007420.cpp, src/mame/konami/k007420.h, src/mame/konami/rockrage.cpp
Use device_gfx_interface for gfx decoding, Use correct type values, Reduce macros, Minor cleanups
konami/battlnts.cpp, konami.bladestl.cpp, konami/rockrage.cpp: Cleanup gfxdecodes
=> konami/k007342.cpp, konami/k007420.cpp: Update and minor cleanups

src/devices/video/mc6845.cpp
Changes in https://github.com/mamedev/mame/pull/11756 caused the ma7551t to hard lock up. With the updated code, the system seems to be overloaded with `handle_line_timer()` calls and initialization does not complete, even though the bool `m_has_valid_parameters` is false. This change, does not enable the line timer until `m_has_valid_parameters` becomes true, this allows the system to properly initialize. And for systems that has valid parameters, the enabling is done in `recompute_parameters()`.
=> video/mc6845.cpp: Fix hang in ma7551t related to mc6845

src/mame/dataeast/actfancr.cpp, src/mame/dataeast/dec0.cpp, src/mame/dataeast/dec0_v.cpp, src/mame/dataeast/dec8.cpp, src/mame/dataeast/dec8_v.cpp, src/mame/dataeast/deckarn.cpp, src/mame/dataeast/deckarn.h, src/mame/dataeast/decmxc06.cpp, src/mame/dataeast/decmxc06.h, src/mame/dataeast/karnov.cpp, src/mame/dataeast/madmotor.cpp, src/mame/dataeast/stadhero.cpp, src/mame/dataeast/thedeep.cpp, src/mame/dataeast/vaportra.cpp
dataeast/dec0.cpp, dataeast/dec8.cpp, dataeast/karnov.cpp, dataeast/madmotor.cpp: Rename GFX ROM regions for consistency
=> deckarn.cpp, decmxc06.cpp: Use device_gfx_interface for gfx decoding

scripts/src/bus.lua, src/devices/bus/waveblaster/waveblaster.cpp, src/devices/bus/waveblaster/wg130.cpp, src/devices/bus/waveblaster/wg130.h
Same ROM and everything else as the existing gz70sp driver, minus the test and demo inputs.
=> add Casio WG-130 waveblaster device

src/devices/cpu/pps4/pps4.cpp
The code was documenting:
iLB -  Load B indirect (0xc*)
iTM - Transfer and mark indirect (0xc0 en el driver)
Clearly one of them is wrong. It's iTM, but it was wrong only on the comment, the implementation is good.
=> cpu/pps4/pps4.cpp: Fix typo on opcode comment [Arcade Hacker]

src/mame/trs/agvision.cpp, src/mame/trs/mc10.cpp
Remove set_raw from mc10 and agvision driver. No longer needed after VDG update.
=> trs/mc10.cpp, agvision.cpp:  remove set_raw

src/devices/video/upd7220.cpp
The SYNC command according to the upd7220 datasheet has a DE (Display Enable) on bit one of the command byte. This should be processed when receiving the command. 
This fixes LOGO professor on the Epson QX-10. That program during boot uses BCTRL to disable the display and then slightly later issues a SYNC command to re-enable the display. Without this fix the disable is never turned back on.
=> upd7220: Sync command should enable/disable the DE bit

src/mame/heathkit/tlb.cpp, src/mame/heathkit/tlb.h
When DE is not set, use the bitmap's `rowpixels()` instead of `count_x * 8` to clear the row. This allows the removal of the cliprect clearing occurring in the MC6845_BEGIN_UPDATE callback, which was need to properly handle the screen saver feature of the superset.
=> heathkit/tlb.cpp: Avoid clearing cliprect in MC6845_BEGIN_UPDATE for superset ROM. 

hash/tvochken.xml
Added software list with barcode card artwork.
=> tvochken.xml: Add TV Ocha-Ken barcode card parts

src/mame/mame.lst, src/mame/tvgames/gpm4530a_lexibook_jg7420.cpp
new machines marked as NOT WORKING
Lexibook JG7420 200-in-1 [David Haywood]
=> new machines marked as NOT WORKING ( Lexibook JG7420 200-in-1 )

src/mame/seta/seta.cpp
PCB has no stereo speaker connector, FM clock reference video is https://www.youtube.com/watch?v=Gq0vScbBmyI (real PCB footage)
=> seta/seta.cpp: Fix FM clock and sound routing for utoukond

src/mame/heathkit/tlb.cpp
Reversing the bits during device_start() avoids having to do it for every scan line when using the imaginator slot device, since the font bits are reverse from the pixel layout and one would be need be reversed. 
Reversing is also needed for the SigmaSoft IGC in this open PR - https://github.com/mamedev/mame/pull/11801 Depending on which PR is merged first, I will update the other PR to properly handle this.
=> heathkit/tlb.cpp: Reverse bits in font roms to avoid doing it on scanout

src/mame/konami/viper.cpp, src/mame/mame.lst
The NVRAM from code1da is a valid NVRAM for GK992 UAD so I moved it to code1d's ROM entry. The expected DS2430 serial for the UAD NVRAM was extracted from the NVRAM data (bytes 0x2a-0x30, reversed) and the serial checksum generated to make a new ds2430_code1d2.u3 that works with the paired NVRAM so no more RTC self-check errors.
code1da was removed because it's just another copy of 922d02. If you extract the two CHDs and mount them as FAT16 then you can find the main ROM file on the filesystem. If you do a checksum comparison of those two files you can see they're identical. The differences in the CHDs seem to come from metadata or other filesystem-related things.
```
76a9bf5c6910c676a44a02649639d730ba19be3a */Volumes/NO NAME/GK922D02.BIN
76a9bf5c6910c676a44a02649639d730ba19be3a …
```
=> konami/viper: Fix code1d NVRAM/DS2430, remove duplicate code1da

src/mame/taito/taitopjc.cpp
Attempt at addressing #11718 (does not fix MT8069 from testing).
Demoted optiger to MNW and MIT due to egregious timing problems that render the game border-line playable.
=> Change optiger input back to AD_STICK

src/mame/efo/cidelsa.cpp, src/mame/mame.lst
New working machine
Altair II [Basilio García, Recreativas.org]
Also renamed the difficulty levels on all driver's games from "Conservative" / "Liberal" to standard names. Cidelsa uses standard names, Spanish (fácil / difícil) or English (easy / difficult), on their documents, I have not found a single reference of "Conservative"/ "Liberal".
=> cidelsa.cpp: Add Cidelsa's "Altair II"

src/mame/rm/rmnimbus.cpp, src/mame/rm/rmnimbus.h, src/mame/rm/rmnimbus_m.cpp
This pull request fixes RM Nimbus joystick emulation by using the correct port address for directional data and setting the correct bits when that address is read.  Currently the mouse data port (0xa4) is used for all joystick data, but only the buttons are actually read from this port.  The joystick port (0xa0) is used for the directional data as described in chapter 2 of of the service manual (https://www.thenimbus.co.uk/upgrades-and-maintenance/service-manual).
This can be demonstrated/tested by running the following RM Basic program which does not work without my change:
```
10 SET MODE 40
20 SET JOYSTICK
30 REPEAT
40   ASK JOYSTICK X%, Y%, Button%
50   POINTS X%, Y%
60 UNTIL Button% = 1
```
I have also removed the "Input Port 0 Device" config port as this is no longer necessary and …
=> Nimbus joystick fix

src/mame/taito/gladiatr.cpp, src/mame/taito/gladiatr.h, src/mame/taito/gladiatr_v.cpp
Remove VIDEO_START_MEMBER and MACHINE_RESET_MEMBER, use video_start() and machine_reset() overrides instead. Reduce runtime tag lookups
Rename gfx regions for consistent.
=> taito/gladiatr.cpp: Use set_format for palette format, Minor cleanups

src/mame/igs/goldstar.cpp
Redumped all the ROMs with a different programmer, and found out that U24 is bitrotten (replaced the current dump with the best one we got, marking it as BAD_DUMP).
Also recorded a video from the real PCB: https://youtu.be/qiSw044Twdc
=> igs/goldstar.cpp: Added missing PROM and PLDs for 'hamhouse' [Taksangs]

src/mame/heathkit/h89.cpp
These changes implement the single-step hardware functionality in the H89. This is based the manual, and an h89 diagnostic program. It is now passing the tests:
=> heathkit/h89.cpp: Implement single-step hardware

src/mame/mame.lst, src/mame/misc/playcenter.cpp
Playcenter Evolution III (v14.0, 'Epox' hardware) [Cuclis, Oskarito, Ángel]
=> misc/playcenter.cpp: Add, as not working, a new Playcenter machine

src/mame/neogeo/neogeo_v.cpp
On real hardware, a byte written in palette RAM is repeated in the whole word (CPU UDS/LDS signals seems to be ignored for palette access). This is used by some software to detect emulation.
=> neogeo/neogeo_v.cpp: Make palette byte access behave the same as on real hardware

src/devices/cpu/mb88xx/mb88xx.cpp, src/devices/cpu/mb88xx/mb88xx.h
This deals with the interrupt handler a little better, and fixes Arabian bugs caused by mb88xx bugs.
I tested it with the other games that use that chip, and didn't see any regressions. Most importantly, none in bosco sound. The 54xx in bosco seem especially sensitive to interrupt races, causing the pitch of shots to be wrong.
Should fix https://mametesters.org/view.php?id=8436 & https://mametesters.org/view.php?id=3916
=> Improve interrupt handing in mb88xx

src/mame/rm/rmnimbus.cpp, src/mame/rm/rmnimbus.h, src/mame/rm/rmnimbus_m.cpp
This PR adds support for a second joystick on the RM Nimbus.  I decided to do this after discovering the RM Basic demo program that covers joystick support.  It's basically a two player paint program with two brushes (each controlled by a different joystick).  To run the demo start RM Basic and type
```
load "mousedem"
run
```
(then wait until it asks about having a joystick before pressing a key to begin).
Interestingly this demo makes it obvious that each joystick should actually only have one button!  This fits with the description of using an Atari style joystick, given in the service manual, as those joysticks only had one button.  Hence the button data returned via the mouse data port actually relates to the button status of both joysticks.
Questions and comments welcome.
=> add support for 2nd RM Nimbus joystick

hash/nes.xml
Fixed the board type name of `sspinbal`, which is "NES-SNEPROM-01" as seen in the picture:
Also renamed the dump to "0.prg", following the notes in the softlist:
> When no label was present on the cart pcb, we have arbitrarily chosen the names
>    0.prg and 0.chr (alternatively, 1.prg and 1.chr for later revisions of a game).
=> nes.xml: Fixed board name

src/mame/igs/pgm.cpp, src/mame/mame.lst
I saw the comment that u9/u10 in martmasttw are possibly a bad dump, so I dumped them from my own cartridge. They came back as identical to martmast102c, so looks like it was a bad dump previously. The ARM ROM looks like it's the only unique ROM in this set. That dump is still bad; I'm not sure how to dump it, though if someone has the custom ROM/ROMs that are used to do that I'm happy to give it a go.
=> igs/pgm.cpp: redump martmasttw

scripts/src/bus.lua, src/devices/bus/a2bus/cards.cpp, src/devices/bus/a2bus/vistaa800.cpp, src/devices/bus/a2bus/vistaa800.h
Added support for the Vista A800 8" disk controller card. 
I picked up a non working one of these cards, so wanted to understand it better. I was able to use the Vista A800 disks and rom available on the Apple2 documentation project and then format and boot DOS 3.3 and CPM ok from the 8 inch disks.
=> bus/a2bus: Added Vista A800 8inch Disk Controller Card

hash/msx2_flop.xml
Removed Last Armageddon (Japan, alt) and Last Armageddon (Japan, alt 2): contain save data.
Replaced Lemmingso (UK?) with a better dump. [file-hunter]
Replaced Lilo - La Conquista de la Fama (Spain) with a better dump. [file-hunter]
L'Affaire (Japan) [file-hunter]
Kan Satoru Hyakka (Japan) [file-hunter]
Konai Shasei Vol. 1 (Japan) [file-hunter]
Konai Shasei Vol. 2 (Japan) [file-hunter]
Konai Shasei Vol. 3 (Japan) [file-hunter]
Last Armageddon Alien Zukan (Japan) [file-hunter]
Lightning Bacchus - The Knight of Iron (Japan) [file-hunter]
Shiro to Kuro no Densetsu Soushuu-hen (Japan) [file-hunter]
Juki, the Ranger. (Japan) [file-hunter]
Konami Quiz 2 Promo (Dutch) [file-hunter]
Konapuzz Promo [file-hunter]
Kung Fu [file-hunter] …
=> msx2_flop.xml: Added 22 items, 21 working. Removed 1, replaced 2 items.

hash/msx2_flop.xml
Replaced Hamaraja Night (Japan) with a better dump. [file-hunter]
Giddy Runner (Japan) [file-hunter]
Ginga Eiyuu Densetsu Powerup & Scenario Shu (Japan) [file-hunter]
Girls Paradise Rakuen no Tenshitachi (Japan) [file-hunter]
Gize! XIX (Japan) [file-hunter]
Gram Cats 2 (Japan) [file-hunter]
Guide CG Disk (Japan) [file-hunter]
Hadou no Hyouteki - Legend of The Melvel (Japan, Kanji ROM-free version) [file-hunter]
Hadou no Hyouteki - Legend of The Melvel (Japan) [file-hunter]
HAL Game Collection Vol. 1 (Japan) [file-hunter]
HAL Game Collection Vol. 2 (Japan) [file-hunter]
Haphazard (Japan) [file-hunter]
Haphazard 1 & 2 (Japan) [file-hunter]
Hard Graphics Soushuuhen (Japan) [file-hunter]
Hot Milk (Japan) [file-hunter]
Igusta …
=> msx2_flop.xml: Add 36 items, 34 working. Replaced 1 item.

makefile, scripts/genie.lua, scripts/src/emu.lua
Made this by popular demand of building tools and not MAME executable. 
By using `make TOOLS=1 EMULATOR=0` it is now possible to build tools only.
=> Make building emulator optional

src/mame/snk/hng64.cpp
Samurai Shodown 64 has the Koreanized Chinese title, Pae Wang Jeon Seol 64.
=> hng64.cpp: sams64 Korean title inclusion

src/tools/unidasm.cpp
For symmetry with `-skip`, it is convenient to specify `-count` using the same number base, e.g. `-skip 0x1000 -count 0x200`. Unprefixed count values are still interpreted as decimal, as before.
=> unidasm: Allow -count to be specified in hexadecimal or octal.

src/mame/heathkit/h89.cpp, src/mame/heathkit/h_88_cass.cpp, src/mame/heathkit/h_88_cass.h, src/mame/mame.lst
Adds the H-88-5 cassette interface board and the H88 clone of the H89. 
Adding the H88 clone (which Heath Company sold with only the cassette interface board) is simpler and more historically accurate. 
MTR-88 BIOS was also change to only be valid with the H88 and the only bios supported by the H88.
=> heathkit/h89.cpp: Add H-88-5 Cassette interface and the H88 clone of H89

scripts/src/machine.lua, scripts/src/sound.lua, src/devices/machine/laserdsc.cpp, src/devices/machine/laserdsc.h, src/devices/machine/ldstub.cpp, src/devices/machine/ldstub.h, src/devices/machine/ldv1000.cpp, src/devices/machine/ldv1000.h, src/devices/machine/ldv1000hle.cpp, src/devices/machine/ldv1000hle.h, src/devices/machine/ldv4200hle.h, src/devices/sound/ssi263hle.cpp, src/devices/sound/ssi263hle.h, src/mame/cinematronics/dlair.cpp, src/mame/konami/konblands.cpp, src/mame/layout/thayers.lay, src/mame/misc/esh.cpp, src/mame/misc/istellar.cpp, src/mame/misc/thayers.cpp, src/mame/sega/gpworld.cpp, src/mame/sega/segald.cpp, src/mame/sega/timetrv.cpp, src/mame/taito/lgp.cpp, src/mame/universal/superdq.cpp
Systems promoted to working
Thayer's Quest (set 1) [Ryan Holtz, Matt Ownby, ld-decode Team]
Thayer's Quest (set 2) [Ryan Holtz, Matt Ownby, ld-decode Team]
-thayers: Added CHD and promoted to working. [Ryan Holtz]
* Fixed periodic IRQ hookup.
* Fixed COP421 clock divisor.
* Switched to LD-V1000 by default and removed LD-PR7820 support for now.
* Switched to using logmacro and shorthand data types.
* Adjusted IRQ triggering and acknowledgement according to schematics.
* Extracted SSI-263 skeleton into its own device using the Votrax SC-01 as a stand-in.
-ldv1000hle: Added an HLE version of the Pioneer LD-V1000 laserdisc player. [Ryan Holtz]
-laserdsc: Added a general-purpose parallel laserdisc interface, to …
=> Added LD-V1000 HLE device, placeholder SSI-263A HLE device, and promoted Thayer's Quest

src/lib/formats/jvc_dsk.cpp, src/lib/formats/os9_dsk.cpp
The CoCo driver includes a 3.5 inch disk drive option, but the specific formats were missing from the os9 format list.
The scoring was adjust so the OS-9 format would prevail in a fight against JVC.
=> jvc_dsk, os9_dsk.cpp: Add 3.5 inch disk formats, adjust scoring

hash/msx2_flop.xml
Replaced Crimson II (Japan, alt) with a better dump. [file-hunter]
1789 La Révolution (France) [file-hunter]
3 Tsu no Negai (Japan) [file-hunter]
Aapaa MyaaDock (Japan) [file-hunter]
Aleste 2 (Japan, Woomb) [file-hunter]
Arrows (Japan) [file-hunter]
The Avenger of Death (Netherlands) [file-hunter]
Bad Max (France) [file-hunter]
Ball Out Special (Japan) [file-hunter]
Beast (Japan) [file-hunter]
Beast 2 (Japan) [file-hunter]
Changan Super (Japan) [file-hunter]
Continental (Japan) [file-hunter]
Cosmic Psycho (Japan) [file-hunter]
Crafton & Xunk (France) [file-hunter]
Gogo 11-ji 48-bu Version 4 (Japan) [file-hunter]
Hatchake Ayayo-san (Japan) [file-hunter]
Hatchake Ayayo-san II: Ikenai Holiday (Japan) [file-hunter]
Kurutta …
=> msx2_flop.xml: Added 44 items. Replaced 1 item.

src/mame/capcom/higemaru.cpp
Before
After
Notice the four small red dots.
=> higemaru: Add tile x/y flip, fixes hi-score screen

hash/super_tv_pc_cart.xml, src/mame/mame.lst, src/mame/tvgames/xavix_2002.cpp, src/mame/tvgames/xavix_2002.h
new machines marked as NOT WORKING
Super TV PC (Epoch) [Team Europe, QUFB]
-------------
super_tv_pc_cart.xml:
-------
Tottoko Hamtaro Ham Ham Ongaku Paradichu! [Team Europe, QUFB]
Doraemon Chō Nōryoku Game Collection [Team Europe, QUFB]
Meitantei Conan: Suiri Adventure [Team Europe, QUFB]
ECC Junior: Ason de Eigo dekichatta! [Team Europe, QUFB]
Pet Mobile Link [Team Europe, QUFB]
previous Super TV PC was identified as the Hello Kitty version and is now marked as such.
=> new machines marked as NOT WORKING - Super TV PC

src/devices/bus/thomson/cd90_015.cpp, src/devices/imagedev/floppy.cpp, src/devices/imagedev/floppy.h
Updated all member variables to be prefixed with `m_`, the existing code had a few with the prefix but most without. This made it more difficult to follow the code.
=> floppy.cpp: Update class variables to the current encouraged naming convention.

src/mame/misc/sttechno.cpp
Implemented xflip and yflip flags that I had previously noted but didn't know where to test in-game. The big mouse no longer moonwalks on the first stage.
Small cleanup: I noticed I had swapped `tile_x` and `tile_y` when renaming them from old temp variable names during cleanup so I fixed that too.
=> misc/sttechno: Implement xflip and yflip flags

hash/msx2p_flop.xml
Removed MSX2 items:
- Twinkle Star - Hoshi no Mahou Tsukai (Japan)
- Twinkle Star - Hoshi no Mahou Tsukai (Japan, alt)
- Pana Amusement Collection Disc (Japan)
- Pana Amusement Collection Disc (Japan, alt)
- Pana Amusement Collection Disc (Japan, alt 2)
Removed Laydock 2 - Last Attack (Japan, alt): contains save data.
Removed Sea Sardine Side-2 (Japan) and Sea Sardine Side-2 (Japan, alt): extracted from MSX Disk Communication 91-02.
Removed Yoshida Kensetsu (Japan, alt): contains save data.
Merged F-1 Spirit 3D Special (Japan, alt) and F-1 Spirit 3D Special (Japan, alt 2).
Moved demo disk from F-1 Spirit 3D Special (Japan) to F-1 Spirit 3D Special (Japan, demo).
Renamed Beppin (Japan) to Beppin Disk (Japan).
The Komainu Quest …
=> msx2p_flop.xml: Added 7 items, 5 working. Removed 8 items.

hash/msx2_flop.xml
Moved from msx2p_flop software list:
- Twinkle Star - Hoshi no Mahou Tsukai (Japan)
- Twinkle Star - Hoshi no Mahou Tsukai (Japan, alt)
- Pana Amusement Collection Disc (Japan)
Sound Machine voor MSX2 Computers (Netherlands?) [file-hunter]
VideoBench (Netherlands) [file-hunter]
=> msx2_flop.xml: Added 2 items. Moved 3 items.

src/mame/atari/atarig42.cpp
Add the ADSP-2105 program from the hard to find com-link board only used in kit versions of Road Riot.
=> roadriot, roadriota: Dump comm board program

src/devices/bus/rc2014/micro.cpp, src/devices/bus/rc2014/ram.cpp, src/devices/bus/rc2014/rc2014.cpp, src/devices/bus/rc2014/rc2014.h, src/devices/bus/rc2014/serial.cpp, src/devices/bus/rc2014/z180cpu.cpp, src/devices/bus/rc2014/z80cpu.cpp
All RC2014 related drivers were broken after https://github.com/mamedev/mame/pull/11333  so this is attempt to fix it.
By architecture this is most similar to S100 but did not see any callback logic like this in implementation there.
Please suggest if there are better ways to do it.
=> rc2014: fix callback initialization

src/devices/machine/ldv1000.h, src/devices/machine/ldv1000hle.cpp, src/mame/cinematronics/dlair.cpp, src/mame/sega/timetrv.cpp
-dlair.cpp: Added zero-dropout LD-CHD for Dragon's Lair rev. F2/F/E/D [Ryan Holtz, Matt Ownby, ld-decode Team]
-ldv1000hle.cpp: Only adjust video and audio enables on field 0, improves seeking visuals. [Ryan Holtz]
Systems promoted to working
Dragon's Lair (US Rev. F2) [Ryan Holtz, Matt Ownby, ld-decode Team]
Dragon's Lair (US Rev. F) [Ryan Holtz, Matt Ownby, ld-decode Team]
Dragon's Lair (US Rev. E) [Ryan Holtz, Matt Ownby, ld-decode Team]
Dragon's Lair (US Rev. D, Pioneer LD-V1000) [Ryan Holtz, Matt Ownby, ld-decode Team]
Time Traveler (Japan) [Ryan Holtz, Matt Ownby, ld-decode Team]
=> Promote Dragon's Lair and Time Traveler (Japan) to working

src/mame/netronics/exp85.cpp
The Netronics Explorer-85 has dedicated circuitry for mirroring the monitor ROM to  low memory (0x0000 -- 0x0800) after a system start/reset and during an interrupt. This logic was reproduced as accurately as possible, since the emulation of the intel 8085 does not have the pin outs needed for implementing the exact logic used in the original circuitry (IO/M, S0, S1 and ALE).
With the mirror switching working, it is possible to execute the MS BASIC ROM (it uses the low memory 8KB of RAM).
Another non-working feature was the step by step execution capability of the monitor program. This tracer uses a timer to interrupt the executing program once per instruction. In a real system the 8155 timer chip has a delay of around ~70ns (measured). This is enough for the next instruction cycle to …
=> netronics/exp85.cpp: implemented rom mirroring, fixed interrupt handling timing

src/mame/bfm/bfm_gu96x8m_k657c2.cpp, src/mame/bfm/bfm_gu96x8m_k657c2.h, src/mame/bfm/bfm_sc4.cpp, src/mame/bfm/bfm_sc4.h, src/mame/bfm/bfm_sc5.cpp, src/mame/layout/bfm_sc5_gu96x8.lay
This implements the Bell Fruit GU96X8M-K629C3 96 * 8 VFD with led backlight.
ATM I've simply replaced the use of the BDA display which had 16 5*7 dot matrix digits with this new display driver.
If the Scorpion 5 driver is ever progressed the correct display will have to be loaded for each game.
=> mame/bfm: Implement Bell Fruit 96x8 dot matrix display for Scorpion 5.

src/mame/handheld/hh_ht11xx.cpp, src/mame/mame.lst
---------
Block Game & Echo Key [azya52, David Haywood]
=> handheld/hh_ht11xx.cpp: Add support for Brick Game

scripts/src/machine.lua, src/devices/machine/s2350.cpp, src/devices/machine/s2350.h
Adds the AMI's USRT S2350 USRT needed for the Heath hard-sectored disk controller. 
This is prep work for supporting the H-88-1 hard-sectored controller for the Heath H89.
=> machine/s2350.cpp: Add new AMI S2350 USRT, prep for Heath hard-sectored support

src/mame/mame.lst, src/mame/taito/taito_f2.cpp
Euro Champ '92 (Japan) [Tailsnic Retroworks]
=> taito/taito_f2.cpp: Add the Euro Champ '92 Japanese set

hash/pcecd.xml
Added `language` info and rename "Game Express" to "Games Express"
FX Unit Yuki: The Henshin Engine (re-release) [Redump]
Henshin Engine (demo) [Sarumaru Company]
Hypernova Blast (USA) [Redump]
Insanity [Redump]
Jessie Jaeger in Cleopatra's Curse [Redump]
Jessie Jaeger in Cleopatra's Curse (demo) [Bold Game Studio]
Meteor Blaster DX (USA, re-release) [Redump]
Mysterious Song (re-release) [Redump]
Mysterious Song [Redump]
Pyramid Plunder [Redump]
Revival Chase [Redump]
Space Ava 201: Quantum Field Theory [Nicole Express]
Ultimate Rally Club [Orion]
Redump software list items
Hi-Leg Fantasy (Japan) [Redump]
Implode (USA) [Redump]
Meteor Blaster DX (USA) [Redump]
=> pcecd.xml: Added 13 working items + 3 redumps

scripts/src/video.lua, src/devices/cpu/upd7810/upd7810.cpp, src/devices/cpu/upd7810/upd7810.h, src/devices/cpu/upd7810/upd7810_opcodes.cpp, src/devices/sound/upd934g.cpp, src/devices/sound/upd934g.h, src/devices/video/mn1252.cpp, src/devices/video/mn1252.h, src/mame/casio/cz230s.cpp, src/mame/casio/ra3.cpp, src/mame/casio/ra3.h, src/mame/layout/cz230s.lay, src/mame/layout/sz1.lay, src/mame/mame.lst
----------
Casio CZ-230S [BCM, =CO=Windler, Devin Acker]
Casio SZ-1 [BCM, Devin Acker]
This commit also:
- adds the Panasonic MN1252 LCD controller
- implements the bit in the uPD7810 MM register to enable/disable internal RAM (needed for cz230s which maps ROM in that area instead)
- fixes the channel assignment bits in the uPD934
=> New working machines (Casio CZ-230S and SZ-1)

src/mame/rm/rmnimbus.cpp
As discussed in comments to my previous pull request (https://github.com/mamedev/mame/pull/11890) this PR changes the default mouse emulation mode to HLE.  I think this is a more useful default as it gives the best user experience now (especially for casual users that might not discover the config setting).
=> rm/rmnimbus.cpp: Change default mouse emulation mode to HLE

src/emu/memarray.cpp
Fixes the little-endian functions read8_from_64le and write8_to_64le using the big-endian BYTE8_XOR_BE macro instead of the little-endian BYTE8_XOR_LE macro.
=> memarray.cpp: Fix use of mismatched endianness macros

src/devices/cpu/t11/t11.cpp, src/devices/cpu/t11/t11.h, src/devices/cpu/t11/t11ops.hxx, src/mame/dec/pdp11.cpp, src/mame/ussr/dvk_kcgd.cpp
Opcode fetch ignores least significant bit of PC; some tests check this. MTPS and MFPS are byte-wide instructions.
Define instruction set variants and reject instructions that are invalid for current CPU type.
=> cpu/t11: minor enhancements:

src/mame/rm/rm380z.h, src/mame/rm/rm380z_m.cpp, src/mame/rm/rm380z_v.cpp
As noted in https://mametesters.org/view.php?id=6484 the first character of the "Disc not ready" error message went missing when trying to boot from the monitor without a disc.  The message was written correctly, but then corrupted because it was not possible for the firmware to read character data back from the screen.  rm380z_state::videoram_read() always returned the last byte written to a (row,col) which was usually the attributes of a character rather than the character itself :-)  This lead to some sort of bug in the firmware where it would overwrite the "D" character with zero.
I've updated rm380z_state::videoram_read()  so that it returns the requested data (either a character or it's attributes) and the error message now displays correctly.  While doing this I've also tidied up …
=> rm/rm380z.cpp: Fix vram access to allow reading of character data from screen

src/mame/handheld/hh_sm510.cpp, src/mame/mame.lst
This PR adds Double Dragon II: The Revenge by Tiger. The MCU was dumped by Sean Riddle and I have digitized the display and prepared the MAME driver.
Marking this PR as a draft since the joystick left action doesn't seem to have any effect and I haven't figured out if the configuration is incorrect or if the left joystick simply doesn't have any effect in the game.
=> handheld/hh_sm510.cpp: Add Tiger Double Dragon II: The Revenge

src/mame/apple/apple2e.cpp
It appears that during a reset, the expected and executed language card state changes do not also update the system memory map. This can cause a reset vector to fail when the language card RAM has been banked over ROM. The following software hangs when reset is asserted:
Merlin running from [32 Meg Hard Drive Image](https://wiki.reactivemicro.com/32_Meg_Hard_Drive_Image)
BBC Basic running from [Applecorn](https://github.com/bobbimanners/Applecorn/releases/tag/v0.52-beta)
A reset hang can be demonstrated from a clean boot by entering the following code into the monitor. It banks in the LC over ROM and waits for the user to press reset. If the LC bank is uninitialized and reset is pressed, it will hang in a cascade of `BRK` instructions.
```
*300: 2C 80 C0 4C 03 03 N 300G
```
The Apple //c …
=> apple/apple2e.cpp: update LC memory map when LC state changes

src/mame/konami/hexion.cpp, src/mame/konami/spy.cpp, src/mame/konami/thunderx.cpp
Small changes based on silicon reverse-engineering.
spy: Confirmed projection function constants, more accurate collision check without the need for special case handling
thunderx: Simplified collision check, fixed object flags updates
hexion: Added special 16-byte VRAM clearing command
Not sure if mentionning an URL to the documentation in comments is the right thing to do.
=> Modified k052591 PMC emulation to reflect how the real programs work

src/lib/netlist/plib/pexception.cpp, src/osd/modules/sound/pulse_sound.cpp
- `__GLIBC__` is the correct macro to check for `feenableexcept`
- `POLLIN` is the correct macro for poll, `POLL_IN` is defined in `signal.h`
it still won't compile because bx [deliberately removed support](https://github.com/bkaradzic/bx/commit/d7ecac17060ab8cf765b21e55a762aa4855dfdb1), but at least removes the need to patch mame
=> Fix compilation against musl

src/lib/util/cdrom.cpp
=> Remove duplicate CD modes

src/devices/cpu/m6809/hd6309.lst
Add case statements to enable indirect register W references. Problem discovered by Glenn Hewlett. Patch by Ciaran Anscomb.
When an illegal index addressing mode is executed, pop next CPU state off stack to ensure vector is correctly jumped to. Problem discovered by Glenn Hewlett.
=> hd6309.cpp: Fix index addressing modes

src/devices/cpu/patinhofeio/patinho_feio.cpp
Fixes the string concatenation "withthe" without a space between the words.
=> cpu/patinhofeio/patinho_feio.cpp: Fix missing space in printf string

src/devices/sound/discrete.cpp
The synchronisation barriers used in the discrete sound device aren’t really thought out properly.  There are two variable where concurrent accesses matter:
* `output_buffer::ptr`, used to determine the number of samples available to the consumer.
* `discrete_task::m_threadid`, used to ensure only a single thread runs a given task at any given time.
Using the `volatile` qualifier for `output_buffer::ptr` doesn’t really help, as it doesn’t enforce ordering between writes to the buffer and writes to the pointer itself.  The pointer itself needs to be updated with release semantics, while it needs to be read with acquire semantics when determining how many samples are available to the consumer.
`discrete_task::m_threadid` needs to be updated with acquire semantics when locking and release …
=> sound/discrete.cpp: Use appropriate memory barriers for task synchronisation

hash/pixter_cart.xml, src/mame/mame.lst, src/mame/mattel/pixtermu.cpp
New software list items marked not working (pixter_cart.xml)
-------------
Alphabet Forest [QUFB]
Clifford - The Big Red Dog [QUFB]
Cyberchase [QUFB]
Mazes, Puzzles & Games [QUFB]
SpongeBob SquarePants - Math Adventure [QUFB]
=> mattel/pixtermu.cpp: Add new not working system & software list

src/lib/util/chd.cpp
This should fix #12023. The maximum output size of the buffer is now calculated based on what will be placed in it.
=> Fix tiny CHD creation (Fixes #12023)

src/mame/rm/rm380z.cpp, src/mame/rm/rm380z.h, src/mame/rm/rm380z_m.cpp, src/mame/rm/rm380z_v.cpp
I've managed to obtain a dump of the real character ROM for COS 4.0 courtesy of the Research Machines user group, and this PR pulls this in and updates the display code to use it.
What is the correct process for updating a rom set?  This my working version that includes the new character rom:
[rm380z.zip](https://github.com/mamedev/mame/files/14268302/rm380z.zip)
The real characters are actually larger than the fake set we used before (8x10 rather then 5x9) and even include 2 extra rows to be used when the underline attribute is set.  This all makes the display handling much easier and improves the display greatly.
So with these characters 80 column mode has a display resolution of 640x240 and 40 column mode uses 320x240.
For COS 3.4 I've set the display resolution to 240x240 which I …
=> rm/rm380z.cpp: Use real character ROM for COS 4.0, correct screen resolution and add support for user defined characters

src/mame/mame.lst, src/mame/misc/vocalizer.cpp
----------
Breakaway Music Systems Vocalizer 1000 [Loscha, Devin Acker]
Uses a rebadged (or cloned?) ES5503 made by NCR. Currently "not working" due to lack of mic input + several patches that use the sync/AM mode not sounding right. Unfortunately I don't have any hardware recordings at the moment. Otherwise mostly works, though.
=> New NOT_WORKING machine (Vocalizer 1000)

src/lib/netlist/build/makefile
Removes the duplicate $(OBJ)/devices directory from the list of object directories.
=> netlist/build/makefile: Remove duplicate $(OBJ)/devices directory

hash/compclr2_flop.xml, hash/digilog320.xml, hash/intv.xml, hash/rainbow.xml
rainbow.xml: Lowercase on storage media description (DEC Rainbow 100 disk images).
digilog320.xml: Lowercase on storage media description (Digilog 320 disks).
intv.xml: Added manufacturer's name (Mattel Intellivision cartridges)
compclr2_flop.xml: Lowercase on storage media description (Compucolor II disk images) and lowercase on descriptive text on software's name
=> rainbow.xml; intv.xml; digilog320.xml; compclr2_flop.xml: Normalize software list description

hash/h88_cass.xml, src/lib/formats/h8_cas.cpp, src/lib/formats/kc_cas.cpp, src/mame/heathkit/h89.cpp, src/mame/heathkit/h_88_cass.cpp
Added official Heath software programs for the H88 cassette interface. These programs were originally written for the H8 and it's cassette interface, but needed updating to support the H89's 8250 UART for the console, instead of the original 8251 used in the H8.
=> heathkit/h89.cpp: Add software list for H88 cassette software

src/mame/konami/ksys573.cpp, src/mame/mame.lst
The main difference with the JA variant is that it lacks the "original program" game mode.
=> ksys573: Add Martial Beat JAB variant

src/mame/irem/travrusa.cpp, src/mame/mame.lst
Add support for Traverse USA and clones different PROMs setup with two 256x4 character palette PROMs instead of only 256x8 one (same contents on both setups).
Confirmed to exist on Traverse USA, MotoTour and MotoRace USA.
=> irem/travrusa.cpp: Add support for Traverse USA and clones different PROMs setup [Victor Fernandez (City Game), Recreativas.org]

src/lib/util/bitstream.h
Additional testing from someone else before merging would be appreciated.
In this case, the parent chunk types were using 26 bits per offset values which behaved unexpectedly resulting in some bits being dropped when reading and writing the data. I think the issue only happens when dealing with values larger than 24 bits due to the way buffering was implemented. So I've changed both `bitstream_in` and `bitstream_out` to more greedily fill its buffers, including partial reads for `bitstream_in`.
Old (can see an additional CRC error message I added to help debug, should be reproducible):
```
> ./chdman copy -i gdj_aaa_2007071100.chd -op gdj_aaa_2007100800.chd -o newchild2.chd 
chdman - MAME Compressed Hunks of Data (CHD) manager 0.262 (mame0252-3687-gb0c8802da65-dirty)
Output CHD: …
```
=> util/bitstream: Fix cases where bits would be dropped when reading and writing

src/devices/machine/z80scc.cpp, src/devices/machine/z80scc.h
Fixes serial emulation at 115200bps.
This leaves some things unimplemented (like TRxC and DPLL clock sources), but makes programs communicating at 115.200bps function properly.
For context, toggling this chip to 115200bps or 230400bps is done by
1) setting the clock multiplier to 16 (230400bps) or 32 (115200bps), WR4 bits 6 or 7
2) setting the clock source for TX and RX to /RTxC instead of BRG, WR11
3) stopping the baud rate generator, WR14 bit 0
I hope this is a good first PR.
Thanks!
=> machine/z80scc.cpp: Added support for RTxC transmit/receive clock source

hash/adam_flop.xml, hash/mindset_flop.xml, hash/next_hdd.xml
mindset_flop.xml: Lower case on storage media's description (Mindset Corporation Mindset floppy discs).
adam_flop.xml: Keep upper case only on the first letter of the system's name (Coleco Adam diskettes).
next_hdd.xml: Put the manufacturer's name on first place (NeXT hard disk images).
=> mindset_flop.xml; adam_flop.xml; next_hdd.xml: Normalize software list description

hash/ekara_japan.xml, hash/ekara_japan_ac.xml, hash/ekara_japan_en.xml, hash/ekara_japan_kd.xml, hash/ekara_japan_m.xml, hash/ekara_japan_packin.xml, hash/ekara_japan_s.xml, src/mame/mame.lst, src/mame/skeleton/hudson_poems.cpp, src/mame/tvgames/xavix.cpp
-----------
Kids' Song Best 40 (Japan) (EC0084-KSB) [Team Europe, David Haywood]
Morning Musume Special (Japan) (BX01-MOR) [Team Europe, David Haywood]
Enka-shū Dai Volume 1 (Japan) (EN-1) [Team Europe, David Haywood]
Enka-shū Dai Volume 2 (Japan) (EN-2) [Team Europe, David Haywood]
Kids' Song 20 (Japan) (KD-1) [Team Europe, David Haywood]
J-Pop Mix Mini Volume 1 (Japan) (MC0009-JPM) [Team Europe, David Haywood]
Artist Mini Volume 9 (Yamaguchi Momoe) (Japan) (MC0016-ATM) [Team Europe, David Haywood]
PostPet (Japan) (SC0011-PST) [Team Europe, David Haywood]
Saiten Cartridge: Nesshō vol. 5 (Japan) (SC0016-SAI) [Team Europe, David Haywood]
these titles aren't optimal, ideally this will be merged and the titles corrected by somebody who knows the language, along with …
=> ekara: add 9 cartridges [David Haywood, Team Europe]

scripts/src/osd/modules.lua, src/devices/bus/isa/3c503.cpp, src/devices/bus/isa/ne1000.cpp, src/devices/bus/isa/ne2000.cpp, src/devices/bus/nubus/nubus_asntmc3b.cpp, src/devices/bus/x68k/x68k_neptunex.cpp, src/devices/machine/edlc.cpp, src/devices/machine/i82586.cpp, src/emu/dinetwork.cpp, src/emu/dinetwork.h, src/emu/network.cpp, src/mame/apple/macquadra700.cpp, src/mame/apple/macquadra800.cpp, src/osd/interface/nethandler.cpp, src/osd/interface/nethandler.h, src/osd/modules/netdev/pcap.cpp, src/osd/modules/netdev/taptun.cpp, src/osd/osdnet.cpp, src/osd/osdnet.h
This is required for #12054 to avoid fatal errors with network devices.  This doesn’t completely clean up the interface to OSD network modules (it’s still using free functions and static variables in a really nasty way), but it does clean up a very nasty cross dependency.
There are still issues with the receive polling timer:
* The interval is set based on the MTU, assuming the rate packets arrive is no more than the theoretical maximum rate that maximal length packets can be serialised.  However, smaller packets can arrive much faster, particularly when using jumbo frames (9000 octet MTU).
* That aside, the code was always based on the incorrect assumption that an `emu_timer` will synchronise with real time.  It doesn’t, so for a system that’s fairly lightweight to emulate (e.g. an …
=> osd/osdnet.cpp: Removed dependency from OSD network device to libemu

src/emu/machine.cpp, src/emu/save.cpp, src/emu/save.h
The only thing that causes non-fatal illegal save state registrations right now is registering an item for save states after start in a system not marked as supporting save states.
It’s high time anything doing that gets fixed.  Not supporting save states means save state support is incomplete, not that the driver has a license to do illegal things.
Opening this as a pull request to give fair warning, and so it can be merged after freeze.
=> emu/save.cpp: Make illegal save state registrations always fatal

src/lib/util/bitstream.h
Found that in addition to forgetting to clear `m_dbitoffs` when flushing resulting in data being shifted incorrectly after a flush when `m_dbitoffs` was non-0, the variable `m_doffset` would go out of sync after flushing when `m_dbitoffs` was used so that needed to be adjusted as well.
I've tested with `chdman info` to check that the 175 CHDs I have on hand can still decompress the map data still, recreated the delta CHD (`chdman copy -i ~/chd_test/gdj_aaa_2007071100.chd -op ~/chd_test/gdj_aaa_2007100800.chd -o ~/chd_test/newchild5.chd`) and verified that all of the hashes validated, and then did various tests using the `dlair` laserdisc CHD including extracting using `chdman extractld`, recreating using `chdman createld`, and verifying that the SHA1 and Data SHA1 were the same in the …
=> util/bitstream: Adjust m_doffset based on m_dbitoffs when flushing

src/mame/trs/gime.cpp
A zero in `memory` was being used as a flag for a dummy memory bank. Adding the `offset` before checking the condition could cause unallocated memory to be referenced.
=> trs/gime.cpp: Fix crash in rare circumstance

scripts/build/verinfo.py
so \ chars aren't treated as part of an escape sequence. (It does the right thing but it generates a warning)
```
python3 ./scripts/build/verinfo.py 
./scripts/build/verinfo.py:26: SyntaxWarning: invalid escape sequence '\s'
pattern = re.compile('\s+BARE_BUILD_VERSION\s+"(([^."]+)\.([^."]+))"')
usage: verinfo.py [-h] [--target <target>] [--subtarget <subtarget>] [--executable <executable>] [--format <format>] [--resources <resfile>] [-o <outfile>]
<srcfile>
```
=> scripts/build/verinfo.py: use a python raw string for the regular expression

scripts/src/bus.lua, src/devices/bus/mc10/mc10_cart.cpp, src/devices/bus/mc10/multiports_ext.cpp, src/devices/bus/mc10/multiports_ext.h
This addition to the Alice line (4k, 32 and 90) adds RAM and Cartridge support in a different way as the already supported Darren Atkinson's MCX-128 cartridge.
=> trs/mc10.cpp: Add "Multiport" cartridge and RAM expansion for the Matra & Hachette Alice

hash/scv.xml
BASIC Nyuumon contains on-cart battery-backed RAM (the cartridge includes a battery compartment for it, and http://takeda-toshiya.my.coocan.jp/scv/scv.pdf even uses it as an example of on-cart RAM), though scv.xml does not specify this, causing the title to freeze after selecting an option on its title screen.
=> hash/scv.xml Fix BASIC Nyuumon entry to work properly

src/mame/heathkit/h17_fdc.cpp, src/mame/heathkit/h17_fdc.h
Initial code for the Heath H-88-1 Hard-sectored controller for the H-89 family of systems. This supported up to 3 floppy drives. 
This initial code implements the I/O ports of the controller, includes the AMI S2350 USRT, the transmitter clock for the USRT. 
Things still needed
- MAME's core code must support hard-sectored disk images.
- Receiver clock for the USRT, based on read clock bits from the disk.
- Add support for a Heath hard-sectored disk image format.
- Add controller to the H89 systems.
=> heath/h17_fdc.cpp: Skeleton impl for the H-88-1 Hard-Sectored Controller

src/devices/cpu/hcd62121/hcd62121.cpp, src/devices/cpu/hcd62121/hcd62121.h
These changes bring emulation closer to the intended speed, allowing screens in CFX9850 models to be interacted without the system turning off immediately (instead of the intended 6 minutes of idle time).
George Stagg identified some missing instructions and how timers were set. In particular, that instruction 0xB3 sets the timeout for the next sleep operation at instruction 0xFE.
Concrete values for timeouts are based on test ROMs I wrote to iterate over almost all possible parameters, using a logic analyzer to get approximate durations for each timeout. If anyone is interested in checking out these timings, you can open [these traces](https://github.com/qufb/data/tree/main/cfx9850gb/dsl) in DSView, using the sigrok decoder found on the same repo.
=> cpu/hcd62121: Implement missing mov instructions and timer wait

src/mame/namco/namcos2.cpp
This memory chip is also present in the Cosmo Gang PCB. I read it and the content matches what is used in other games.
=> Added zoom table dump for cosmogng

src/mame/galaxian/galaxian.cpp, src/mame/mame.lst
Bagman (bootleg on Moon Cresta hardware, set 3) [David Bosque, Recreativas.org]
=> galaxian/galaxian.cpp: Add a new Bagman bootleg on Moon Cresta hardware

src/mame/jaleco/megasys1.cpp, src/mame/jaleco/megasys1.h
Added MCU dump for cybattlr. [kuze]
Also added and hooked it up for chimerab set which uses the same MCU, but marked as BAD_DUMP, as it only was dumped by kuze from a Cybattler PCB
=> megasys1.cpp: added MCU dump for cybattlr and hook it up [kuze]

src/mame/mame.lst, src/mame/taito/2mindril.cpp
Two Minute Drill (Ver 2.2A 1993/10/18) [Sergio Galiano, Recreativos Piscis]
Picture of the actual pcb:
[https://i.imgur.com/wnwBEx2.jpg](https://i.imgur.com/wnwBEx2.jpg)
As you can see in the picture, program roms (d58-16 and d58-17) has an asterisk next to their reference, but I omitted it on the filenames due to incompatibility.
=> taito/2mindril.cpp: Added Two Minute Drill Ver 2.2A

src/mame/nmk/nmk16.cpp, src/mame/nmk/nmk16.h, src/mame/nmk/nmk214.cpp, src/mame/nmk/nmk214.h
Added implementation for NMK214 as a new device. It's used for descrambling GFX data on some games in the nmk16 driver.
The implementation was made based on the reverse engineering work of the chip at silicon level: 
[https://github.com/sergiopolog/GateArray-RE/tree/master/NMK/nmk-214](https://github.com/sergiopolog/GateArray-RE/tree/master/NMK/nmk-214)
Results of the descrambling GFX process for both sprites and background tiles using this implementation match exactly with the ones from previous implementation made by @mamehaze (and Antiriad) back then.
In this case, all the internal configurations that could be selected to perform it are included, even if they are never used for any game, just for documentation purposes.
Real hardware performs the descrambling process on the fly for …
=> New NMK214 device: added implementation for NMK214 descrambling GFX device and hook it up to nmk16 driver

hash/msx1_cass.xml
Renamed Aackobase II (Europe) and Aackobase II (Europe, alt) to Aackobase II (Netherlands) and Aackobase II (Netherlands, alt).
Add disk version to Aackobase II (Netherlands) and Aackobase II (Netherlands, alt) [file-hunter]
The Games Collection (Europe) [anonymous]
Games Tutor (I) (Spain) [file-hunter]
Hard-Copy (Spain) [file-hunter]
T-GRAPH (Europe) [file-hunter]
=> msx1_cass.xml: Added 4 items, 3 working. Updated 2 items.

src/mame/apple/apple2e.cpp
Some IOU softswitches are not being reset when the system is reset. This can leave the display and annunciators in an incorrect state after a reset.
From a fresh start, enter the following into the monitor to enable 80-column video and then press RESET. Note the 80-column video remains enabled which is not correct.
```
*C00D:1
```
From a fresh start, enter the following into the monitor to draw MouseText characters to the screen and then press RESET. Note the MouseText characters remain enabled which is not correct.
```
*C00F:1 N 428:40 41 42 43 44 45
```
This patch corrects these issues by adding reset handling for the missing IOU softswitches:
- 80COL
- ALTCHR
- AN0
- AN1
- AN2
- AN3
In addition, reset code related to MMU, IOU, and LC softswitches has been reorganized into logical …
=> apple/apple2e.cpp: Correctly reset IOU softswitches on system reset

src/mame/bfm/bfm_bd1.h, src/mame/bfm/bfm_bda.h
Ran into this while debugging; the fix appears to be valid under C++17.
=> const -> constexpr, fixes undefined references when building with -O0 on macOS

src/mame/mame.lst, src/mame/misc/vampire.cpp
-----------
Vampire (prototype?) [Tomasz Slanina, Heiko Klusmann]
=> new WORKING machines (Vampire)

src/mame/apple/apple2gs.cpp
reported in MAMETesters 8736
reproduction:
```
10 def fnp(x)=peek(49248+x)>127
20 ? fnp(0)fnp(1)fnp(2)fnp(3)
30 goto 20
```
=> apple/apple2gs.cpp: fix joystick buttons to return in bit 7

src/mame/rm/rm380z.cpp, src/mame/rm/rm380z.h, src/mame/rm/rm380z_m.cpp
Double sided disks would not load before because the floppy drives were wrongly configured as single sided.  The wrong control port bit was also being used to select the side.  After fixing this I can load more software and access the second side of double sided disks (logical drives C: and D:).
I've also added support for 8 inch disks used by the /F firmware variants such as "COS 3.4D/F".  The "/F" refers to FDS (Full Disc System - 8") as opposed to MDS (Mini Disc System - 5.25"), which is designated by "/M".
FDS and MDS actually use different ports, so I've also updated the IO port map to include both sets.  The firmware guide shows both as being reserved for FDC use.  NB the control port address is not fully decoded and can actually be written to using 4 addresses which is why I've …
=> rm/rm380z.cpp: Correct floppy disk handling so double sided disks work and also add support for 8 inch disks

src/mame/rm/rm380z.cpp, src/mame/rm/rm380z.h, src/mame/rm/rm380z_m.cpp
This PR adds sound for COS 4.0 only as the beep control character, and escape codes to change the beep duration and frequency are not supported by COS 3.4.  The firmware guide lists these as only being implemented in COS 4.0 and later releases.
With this change <Ctrl+G> beeps, and more excitingly music is played in the "Go West" game!  It plays a recognisable rendition of "Coming 'Round the Mountain" and another tune when you reach San Francisco.  I have not found any other software with sound yet.
=> rm/rm380z.cpp: Add sound for COS 4.0

hash/jaminator.xml, scripts/src/sound.lua, src/devices/sound/cf61909.cpp, src/devices/sound/cf61909.h, src/mame/mame.lst, src/mame/misc/jaminator.cpp
Toy guitar thing from 1990, co-developed by Steve Capps of classic Mac and Newton fame, plus the original run of six song carts (along with an attempt at cataloguing the later series of carts from when the system was rereleased in 1993).
New working machine
----------
Noise Toys Inc. Jaminator [Devin Acker]
----------
jaminator.xml: Classic Rock I (USA), Classic Rock II (USA), Hard Rock I (USA), Hard Rock II (USA), Lead Rock Guitarists (USA), Modern Rock (USA) [Devin Acker]
=> New working machine (Jaminator)

hash/dc.xml, hash/n64.xml, hash/saturn.xml, hash/snes.xml, src/mame/konami/ksys573.cpp, src/mame/skeleton/hudson_poems.cpp
Looking to solicit opinions on this.
The 実況パワフルプロ野球 franchise is usually called “Jikkyou Powerful Pro Yakyuu” in English.  However, in Japanese media, it seems to be more frequently rendered in literal romaji as “JIKKYOU PAWAFURU PURO YAKŪ”.  You can see this in the attract sequences for the games on Konami System 573, for example (e.g. `powyakex`).
“Powerful” and “Pro” are definitely loanwords from English.  The MAME convention has always been to use standard English spellings for loanwords.  Also, if we switch to literal romaji, we’ll be the odd ones out as all the other software catalogues will still be using “Jikkyou Powerful Pro Yakyuu”.
So in this case, should “JIKKYOU PAWAFURU PURO YAKŪ” be treated as an official Latin script title and used for system and software descriptions?  Or …
=> Use literal romaji for Jikkyou Powerful Pro Yakyuu game titles

src/mame/nmk/nmk16.cpp, src/mame/nmk/nmk16.h
The new gfx decryption method and mcu dump are added to every game (and clones) which use it on the driver:
- `macross`
- `gunnail`
- `bjtwin`
- `nouryoku`
Internal ROM on NMK215 is the same for all games, so the dump already included for `saboten` is now added for the rest of the games.
Old method is still in use for bootleg clones in which the actual decryption process used is still not in-depth documented.
- Also updated CPU clock for `mustang` (and clones) to proper value and added notes about bootlegs [hammy]
=> nmk16.cpp: The new MCU based GFX decryption method is added for rest of games

src/devices/cpu/hcd62121/hcd62121.cpp, src/devices/cpu/hcd62121/hcd62121.h, src/devices/cpu/hcd62121/hcd62121d.cpp, src/devices/cpu/hcd62121/hcd62121d.h, src/mame/casio/cfx9850.cpp
- Fix CFX9850GB `display_ram` mapping, this one doesn't write to segment 0x60;
- Debugger edits to register values were all being incorrectly applied to the first register, now they should go to the corresponding set of 4 registers;
- Implement TIME register;
- Add more instructions tested on hardware;
- Fix swap flags, they are always cleared regardless of values;
- Fix timer so that it expires on KO enabled key input;
- Add an infinite timer variant, which seems to only be used along with the low power variant of `timer_wait`;
- Prefer more accurate palette taken from an [online Casio manual](https://support.casio.com/storage/en/manual/pdf/EN/004/fx_plus_ch_intro_EN.pdf), although it isn't clear what contrast levels they used for those screenshots;
=> casio/cfx9850.cpp: Various fixes

src/mame/cirsa/neptunp2.cpp, src/mame/mame.lst
Charleston (V2.1, Catalonia) [Arcade Planet, Recreativas.org]
=> cirsa/neptunp2.cpp: Added a new mechanical slot machine from 'Europea' 

src/mame/igs/pgm2.cpp, src/mame/mame.lst
Bu Bu Car (English) [Victor Fernandez (City Game), Recreativas.org]
We haven't desoldered and dumped the surface mounted flash ROMs because we'd better wait for the program ROM to be decrypted (by anyone able of doing it) so we can then run a trojan and extract the CPU internal ROM.
=> igs/pgm2.cpp: Add the program ROM of "Bu Bu Car"

src/mame/cirsa/neptunp2.cpp, src/mame/mame.lst
Gladiadores (V1.0, CAA) [Arcade Planet, Recreativas.org]
Corsarios (Cirsa slot machine, V5.10D, Catalonia) [Arcade Planet, Recreativas.org]
=>  cirsa/neptunp2.cpp: Added two electromechanical slot machines from Cirsa.

src/mame/mame.lst, src/mame/misc/diamondking.cpp
Caribe [Arcade Planet, Recreativas.org]
=> misc/diamondking.cpp: Added "Caribe" slot machine from Segasa Sonic

src/mame/mame.lst, src/mame/mr/dribling.cpp
Dribbling (Automave bootleg, Spain) [David Bosque, Recreativas.org]
Also renamed 'driblingbr' to 'driblingvm' and change game description.
=> mr/dribling.cpp: Add a Dribbling bootleg from Automave (partial dump)

src/devices/video/mc6845.cpp, src/devices/video/mc6845.h, src/mame/commodore/cbm2.cpp, src/mame/heathkit/tlb.cpp
Verified with the build artifacts on this PR that the DE check prevents the crash in Windows (tested with a load prior to the original revert and saw the crash to verify my setup).
=> video/mc6845.cpp: Restore support for zero active width/height configuration

src/devices/video/mc6845.cpp, src/devices/video/mc6845.h, src/mame/commodore/cbm2.cpp, src/mame/heathkit/tlb.cpp
Reverts mamedev/mame#12007
This is a case of attempting to fix the symptom rather than the issue, and it breaks all systems that use 6845-family CRTCs with "show borders" set.
=> Revert "video/mc6845.cpp: Restore support for zero active width/height configuration"

src/mame/rm/rm380z.cpp, src/mame/rm/rm380z.h, src/mame/rm/rm380z_m.cpp, src/mame/rm/rm380z_v.cpp
The RM 8" disk format is actually the IBM-3740 standard which means that generic CP/M disks in this format are compatible.  By testing these I've discovered that the FD-1771 square wave clock frequency needs to be changed for 8" disks.  This PR does that and allows such disks to load.  For example, I've just played the Infocom text adventure Zork from an 8" disk image :-)
I have also removed the slot device "fixed" restriction to allow switching between MDS and FDS drives.  It is actually possible to use FDS drives with MDS firmware if you patch the CP/M disk parameter tables, i.e boot from MDS disk in drive A:, then patch the disk parameter tables for drive B: before using with FDS disks!  I have written an assembler program to do just that.  The extra disk space allows larger CP/M …
=> rm/rm380z.cpp: Fix 8" disk clock frequency and minor VDU-80 display improvements

src/devices/cpu/t11/t11.cpp, src/devices/cpu/t11/t11.h, src/devices/cpu/t11/t11ops.hxx
=> cpu/t11: Improve trace trap processing; add basic interrupt processing to the K1801VM1.

src/mame/namco/namcops2.cpp
Battle Gear 3 has an US version released by Betson in 2004, using American-style budget/wooden cabinets. Contrary to disclaimers printed throughout the [bilingual flyer](https://flyers.arcade-museum.com/videogames/show/4222), it does have Honda cars (contrast to sidebs2u and batlgear, the US versions for Side by Side 2 and Battle Gear 1) and even shown prominently in the cabinet marquee. Since the export BG3 has a notice against exporting that version to the U.S. on startup, it seems to have its own unique region dongle - apparently to show a Japanese model disclaimer, as well to use Betson's North American NESYS (online service, closed after 2005) server.
Links:
- [Betson's BG3 NESYS server site](https://web.archive.org/web/20050214104932/http://bg3.betson.com:80/); Honda cars are …
=> Battle Gear 3 has an US version + export ver. dongle info + MotoGP should be 1 word

src/mame/atari/harddriv.cpp
Fixed wrongly mapped brake pedal input from 8ADC:6 to 8ADC:2 and swapped the Voice Mic function which is unused from 8ADC:2 to 8ADC:6 to avoid any conflict/loss of functionality. Steering input still needs to be fixed (if you turn to the far left of right the centre point of the steering wheel will shift and constantly pull the wheel in the opposite direction) Hard Drivin's Airborne has the same problem. Will try to fix that if I can and update the code here on GitHub.
=> strtdriv: fixed incorrect brake pedal port mapping in harddriv.cpp

scripts/src/osd/sdl_cfg.lua
Some distros (e.g. openSUSE) put the headers in /usr/include/wayland
This should fix the error reported over at bannister.org forums [1]. Unfortunately, I have no way of testing this.
[1] https://forums.bannister.org/ubbthreads.php?ubb=showflat&Number=123347
=> Use pkgconfig to determine wayland include dir

docs/source/tools/chdman.rst, src/tools/chdman.cpp
The output split bins code took inspiration from from @landfillbaby's PR (https://github.com/mamedev/mame/pull/11727). I included some of their changes and did some additional refactoring, and also implemented the start of a formatting system for output filenames after some general design feedback from cuavas.
An example of the formatting system:
`chdman extractcd -i test.chd -o test.cue -ob "test %03t.bin"`
will result in the output bin filenames in the format of "test 001.bin", "test 002.bin", "test 003.bin", etc. 
And `%t` will give the track number without any additional formatting.
The output split bins is a prerequisite for implementing exporting of Dreamcast cues so the two changes have been included together. The commits are fully independent changes so I recommend looking at the …
=> chdman: Add support for exporting Dreamcast cues and outputting one bin per track

src/emu/debug/express.cpp
One iterator was being compared with another from the wrong container. I observed this by chance when I hit an assert in a debug MSVC build with checked iterators enabled. This bug could cause dereferencing of a past-the-end iterator in expressions ending with an operator.
=> debug/express.cpp: Fix bad iterator comparison in postfix conversion.

hash/msx1_flop.xml
Replace TT Racer (Netherlands) with a better dump. [file-hunter]
Replace Zanac (Netherlands) with a better dump. [file-hunter]
Aackotext II (Netherlands, v2.2) [file-hunter]
Brasil Geográfico (Brazil) [file-hunter]
dBASE II (Netherlands) [file-hunter]
MS Text (Netherlands) [file-hunter]
Score Editor (Japan) [file-hunter]
MSX-AIDS (Japan, v1.1) [file-hunter]
Nihongo Waupuro Kan-juku Tomato (Japan) [file-hunter]
JUBILEUM Diskette (Netherlands) [file-hunter]
Serial Interface (Netherlands) [file-hunter]
MSX Data Communications (Netherlands) [file-hunter]
Yamaha Portatone PSR-6300 Demonstration [file-hunter]
=> msx1_flop.xml: Added 11 items, 8 working.

hash/msxr_flop.xml
Demoted all items.
Use full country names and lowercase alt/demo/etc modifiers.
Removed MSX View (Jpn, Bad Dump?)
Rename Moon Light Saga (Jpn) to Moon Light Saga (Japan, alt).
Replace Space Panic! (Japan) with a better dump. [file-hunter]
FS-A1GT (Japan) [file-hunter]
FS-A1ST (Japan) [file-hunter]
The Best of Hamaraja Night (Japan) [file-hunter]
Dewoman Zenpen (Japan) [file-hunter]
Dewoman Chuuhen (Japan) [file-hunter]
Fantasy Attraction (Japan) [file-hunter]
innocent wish ~destiny2~ (Japan) [file-hunter]
Mahouno Kunino Hoippuru (Japan) [file-hunter]
Mechanical Brain (Japan) [file-hunter]
Me-yuu Isago - Mejuusa (Japan) [file-hunter]
MSX ViewCALC (Japan) [file-hunter]
R2 Chaser's (Japan) [file-hunter]
South …
=> msxr_flop.xml: Added 28 not working items. Removed 1 item.

src/devices/machine/icd2061a.cpp
Just to be sure I checked and all other usages of `m_reg_clocks` are using constants instead of variables. `truckk` and `ujlnow` are both still booting so code-wise it's working as expected (they rely on the feature clock working properly to even boot).
cc: @happppp
=> machine/icd2061a: Fix out of bounds array access

src/mame/namco/namcops2.cpp
Updated the dump status of THE IDOLM@STER & Minna de Kitaeru Zenno Training.
Also added some info about the [V300 FCB PCB](https://twitter.com/lsylsy2/status/1071616172263534592) found on the actual THE IDOLM@STER cabinets.
=> namco/namcops2.cpp: correct notes with regards of THE IDOLM@STER & V300 I/O boards

hash/msx2_flop.xml
Replaced with better dumps: [file-hunter]
Veldslag (Netherlands)
Zeeslag (Netherlands)
Zoo (Europe)
Mitsubishi ML-G30 [file-hunter]
Atlas / Encyclopedie (Belgium) [file-hunter]
Belasting Diskette 1989 (Netherlands) [file-hunter]
Brainstorm (Netherlands) [file-hunter]
Cheat Master (Netherlands) [file-hunter]
Compass - Finally Free Edition (v1.2.09) [turbor]
Copy Aid Tenka Muteki (Japan, v2.32+) [file-hunter]
Copy Aid Tenka Muteki (Japan, v2.32) [file-hunter]
Copy Aid Tenka Muteki (Japan, v2.30) [file-hunter]
Copy Aid Tenka Muteki (Japan, v2.20) [file-hunter]
Copy Aid Tenka Muteki (Japan, v2.12) [file-hunter]
DemoKit Deluxe (Netherlands) [file-hunter]
Disk Album 42 - MSX-C Nyuumon Jougekan (Japan) [file-hunter]
DupeDisk …
=> msx2_flop.xml: Added 77 items, 64 working.

hash/megadriv.xml
- Added list of known missing Sega Game Toshokan games.
- Added the specific titles of the collections where some of these dumps come from.
- Corrected Kandume -> Kanzume.
- Added proper years for all of their entries according to Sega's website.
- Added full "serialized" title to existing Riddle Wired entry.
=> megadriv.xml: Added and corrected info on the Sega Game Toshokan games

src/devices/cpu/i86/i186.cpp
For the driver I'm currently writing there were two issues with the i186 emulation:
- drq_callback from timer 2 did not start dma transfer causing a blank screen
- when timer 0 or 1 use timer 2 as pre-scaler they were also incremented by their timer device, causing way too fast sequenced rhythms.
It would be good if someone familiar with the implementation would review this as I just did the changes to make it work for me - especially the pre-scaler commit.
https://github.com/orgs/mamedev/discussions/99
My WIP driver for testing can be found here  https://github.com/hjanetzek/mame/pull/2
=> i186: fix dma on timer2 and timer2 as prescaler

scripts/src/3rdparty.lua
=> Add C compiler flags for Wayland EGL backend to bgfx build options

src/lib/util/cdrom.cpp, src/tools/chdman.cpp
trackinfo.splitframes was not initialized.
=> Fixes chdman extract cd (Broken since splitbin option)

docs/source/tools/othertools.rst
Header claims "Developer-focused" tools, repeating "Most users will not need to work with this." is an unnecessary hyperbole considering all these tools expect specific domain knowledge already.
=> docs: remove unnecessary repetition in othertools.rst

src/mame/seta/seta2.cpp
As seen on title screen, this bootleg is from 1998 :
=> seta/seta2.cpp: Fixed year for Guardians / Denjin Makai II (bootleg)

src/mame/itech/itech32.cpp, src/mame/itech/itech32.h, src/mame/itech/itech32_v.cpp
Recuce runtime tag macros
Fix metadatas (ex: shufshot and clones are hasn't strata related stuff (logo, etc)) Use machine().side_effects_disabled() for debug stuffs Use correct, constant typename values
Fix naming for ROM regions
Use logmacro for logging features
Reduce defines
Use array for reduce duplicates
Move drivedge specific stuffs into drivedge_state
=> itech/itech32.cpp: Various cleanups and updates:

hash/apple2gs_flop_clcracked.xml
GBA Championship Basketball: Two-on-Two (cleanly cracked) [Brian Troha]
Reader Rabbit (Version 2.0) (cleanly cracked) [Brian Troha]
ShowOff (Version 1.0) (cleanly cracked) [Brian Troha]
Sid Meier's Pirates! (cleanly cracked) [Brian Troha]
USA GeoGraph (Version 1.0) (cleanly cracked) [Brian Troha]
World GeoGraph (Version 1.3) (cleanly cracked) [Brian Troha]
=> apple2gs_flop_clcracked.xml: added 6 dumps, used info tags for a lot of dumps [Brian Troha]

src/mame/itech/itech8.cpp, src/mame/itech/itech8.h, src/mame/itech/itech8_m.cpp, src/mame/itech/itech8_v.cpp
Reduce unnecessary lines
Reduce preprocessing defines
Use correct typename values
Use C++ style comment for single line comments
Use palette_device for grmatch color behaviour
Remove unpopulated device
Fix filename comments
Use input_merger for FIRQ with VIA
Use machine().side_effect_disabled() for avoid debugger issue
Replace pointers to references
Fix spacing in metadatas
=> itech/itech8.cpp: Various cleanups

src/devices/bus/msx/slot/music.cpp, src/devices/bus/msx/slot/music.h, src/mame/mame.lst, src/mame/msx/msx.cpp, src/mame/msx/msx.h, src/mame/msx/msx2.cpp, src/mame/msx/msx2p.cpp
- Move MSX2+ machines to msx/msx2p.cpp.
- Add support for Kanji level 2 I/O ports.
- Add support for MSX2+ boot flags register.
- Hook up msx2p_cart and msxr_cart software lists.
=> msx/msx.cpp: Small MSX2+ related updates

src/mame/konami/konamigv.cpp
HLE implementation of the printer Sony UP-1200 analog video printer used by Tokimeki Memorial Oshiete Your Heart. The printer receives an S-Video signal from the subboard PCB and separately a communication line to control the machine. `tmosh` and `tmoshs` only take and print one picture, but `tmoshsp` takes 16 different pictures and uses the 16 image layout setting of the printer.
The printer output is shown as a second screen as can be seen in the example pictures below.
tmosh (1 large image):
tmoshs (Konami logo position changes, text and icon in the very center of the picture):
tmoshsp (Konami logo and Tokimeki Memorial logo are always in the same spot):
Here's a picture of multiple prints from both the `tmosh` version and the `tmoshsp` version for layout reference.
This PR also …
=> konami/konamigv: Add printer support for Tokimeki Memorial Oshiete Your Heart

src/mame/midway/williams.cpp, src/mame/midway/williams.h, src/mame/midway/williams_m.cpp, src/mame/midway/williams_v.cpp, src/mame/midway/wmg.cpp
Use memory_view for ROM/Palette overlay
Reduce unnecessary devices, variables
Reduce ROM region size, rearrange ROM offsets
Fix naming for tile ROM region
Reduce runtime tag lookups
suppress machine().side_effects_disabled() for debugger reading PIA constantize variables
=> midway/williams.cpp, wmg.cpp: Various cleanups

src/mame/konami/konamigv.cpp
Clean up input keybinds for these games.
Control panel: https://twitter.com/BEEP_SHOP/status/1759432324473835546
I/O test
=> konami/konamigv: Remove unused inputs from Tokimeki Memorial Oshiete Your Heart games

src/mame/midway/midyunit.cpp, src/mame/midway/midyunit.h, src/mame/midway/midyunit_m.cpp, src/mame/midway/midyunit_v.cpp
Split class per devices to reduce optional finders
Fix naming of ROM region, paletteram finder
Fix filename, Reduce defines
Use logmacro for logging protection related stuffs
Constantize variables, Use correct typename values
suppress side_effects_disabled() for debugger reading protection result
use soundlatch->data_pending_callback() for mkyawdim2 sound irq
Move driver init to machine_config for mkyawdim2 sound related stuffs
=> midway/midyunit.cpp: Various cleanups

src/mame/trs/coco.cpp
Changed offset to align MAME's light gun cursor with what the games expect. I believe this fell out of adjustment with the recent MC6847 changes.
=> trs/coco.cpp: Fix light gun offset

src/osd/strconv.cpp
- Defer to MAME's built-in UTF-8 decoding because MultiByteToWideChar needs the length of the code unit and once that's been determined it's convenient do the rest of the conversion and sidestep the complication of UTF-16 (surrogate pairs).
- Remove the FIXME about other variable length encodings such as GB18030. With the sole exception of UTF-8, only single- and double-character encodings are supported as the active ANSI code page. Other code pages are only usable in conversion functions and not relevant here. Source: [[MS-UCODEREF]: Supported Codepage in Windows | Microsoft Learn](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-ucoderef/28fefe92-d66c-4b03-90a9-97b473223d43).
- Remove the FIXME about surrogate pairs because these only arise in the context of Unicode …
=> osd/strconv.cpp: Support UTF-8 Windows ANSI code page.

src/mame/midway/atlantis.cpp, src/mame/midway/midvunit.cpp, src/mame/midway/midwayic.cpp, src/mame/midway/midwayic.h, src/mame/midway/midzeus.cpp, src/mame/midway/seattle.cpp, src/mame/midway/vegas.cpp
Suppress side effects for debugger reads
Use C++ style line comments for single line comments
Reduced use of literal tag
=> midway/midwayic.cpp: Reduce hardcoded tags, Cleanups:

hash/apple2_flop_clcracked.xml, hash/apple2_flop_orig.xml, hash/apple2gs_flop_clcracked.xml, hash/apple2gs_flop_orig.xml
Meta data cleanups for MECC eduware titles (1/3 done).
New working software list items (apple2_flop_clcracked.xml)
Mastering Math Series 4: Space Subtraction (A-145 version 1.0) (4am crack) [4am]
Mastering Math Series 5: Subtraction Puzzles (A-146 version 1.0) (4am crack) [4am]
Mastering Math Series 6: Multiplication Puzzles (A-147 version 1.0) (4am crack) [4am]
Mastering Math Series 7: Quotient Quest (A-148 version 1.0) (4am crack) [4am]
Mastering Math Series: Diagnostic System (A-149 version 1.1) (4am crack) [4am]
Mastering Math Series: Management System (A-150 version 1.0) (4am crack) [4am]
Mastering Math Series: Management System (A-150 version 1.1) (4am crack) [4am]
Mastering Math Series: Worksheet Generator (A-151 version 1.0) (4am crack) [4am] …
=> apple2_flop_clcracked: Added 9 dumps, 1 redump, 1 removed.  Meta data cleanups for MECC.

src/devices/machine/spi_sdcard.cpp
somehow related to MT08855 - but it's unclear how "wrong" spi commands can kill entire emu memory.
=> machine/spi_sdcard.cpp: fix write data leaking into cmd buffer

src/mame/misc/skimaxx.cpp
Reduce runtime tag lookups
Suppress side effect for debugger reads
=> misc/skimaxx.cpp: Cleanups

hash/apple2_flop_clcracked.xml, hash/apple2_flop_orig.xml
Improved meta data for Essential Data Duplicator and Nibbles Away.
New working software list items (apple2_flop_orig.xml) 
Anchorman [4am, ianoid, A-Noid]
Back It Up III (version 3.4) [4am, ianoid, A-Noid] 
Candy Land [4am, A-Noid]
Chuck Yeager's Advanced Flight Trainer [4am, A-Noid] 
Copy II Plus (version 3.3) [4am, txgx42, A-Noid]
Essential Data Duplicator 4 Plus (version 4.1) [4am, txgx42, A-Noid] 
Nibbles Away (version B2) [4am, txgx42, A-Noid]
Nibbles Away ][ (version A1) [4am, A2_Canada, A-Noid] 
Questmaster I: The Prism of Heheutotol [4am, ianoid, A-Noid] 
Wizimore: Catacombs of Vlad [4am, A2_Canada, A-Noid] 
Wizimore: Nihonbashi [4am, A2_Canada, A-Noid]
Wizimore: O'Connor's Mine [4am, A2_Canada, A-Noid] 
Wizimore: The Emperor's Seal [4am, A2_Canada, …
=> apple2_flop_orig.xml: Added 14 dumps. apple2_flop_cllcracked.xml: Added 1 dump.

src/mame/nmk/nmk16.cpp
According to the former developer's [submission to X](https://twitter.com/shulgee/status/1779508684022026585), "Jewels" was followed by "Slot Gal," which was based on it. 
> "Jewels" was followed by "Slot Gal," which was based on it. The panel patterns that had been jewels in "Jewels" were changed to a slot machine, and pictures of gals were added as a sexy element. I have heard that this change has increased location test income from 300 yen to 500 yen (a whopping 66% increase).
"Many Block" uses tiles with a slot machine pattern and has a title image of "SLOT GAL" inside (though the gal does not appear). Therefore, "Many Block" should be called a "Slot Gal" hack rather than a "Jewels" hack.
=> nmk/nmk16.cpp: Correct origin of "Many Block"

src/mame/midway/midtunit.cpp, src/mame/midway/midtunit.h, src/mame/midway/midtunit_m.cpp, src/mame/midway/midtunit_v.cpp, src/mame/midway/midtunit_v.h, src/mame/midway/midwunit.cpp, src/mame/midway/midwunit.h, src/mame/midway/midwunit_m.cpp, src/mame/midway/midxunit.cpp, src/mame/midway/midxunit.h, src/mame/midway/midxunit_m.cpp
midtunit_v.cpp:
Use devcb_write_line for DMA IRQ handling
Reduce hardcoded tags
Reduce unnecessary DUMMY_TAG
Initialize variables in constructor
Use logmacro.h for logging
Fix function name
midtunit.cpp:
Split class related to sound system
Reduce defines
Reduce literal tag usage
Use logmacro.h for logging
Fix function name
Suppress side effects for debugger read
Reduce unnecessary functions
Reduce unnecessary finders
midwunit.cpp:
Reduce defines
Reduce literal tag usages
Suppress side effects for debugger read
Fix function naming
Reduce unnecessary finders
midxunit.cpp:
Reduce defines
Reduce literal tag usages
Suppress side effects for debugger read
Fix function naming
=> midway/midtunit.cpp, midtunit_v.cpp, midwunit.cpp, midxunit.cpp: Cleanups

src/devices/bus/msx/cart/ascii.cpp, src/devices/bus/msx/cart/dooly.cpp, src/devices/bus/msx/cart/fs_sr021.cpp, src/devices/bus/msx/cart/halnote.cpp, src/devices/bus/msx/cart/holy_quran.cpp, src/devices/bus/msx/cart/konami.cpp, src/devices/bus/msx/cart/msx_audio.cpp, src/devices/bus/msx/cart/msxdos2.cpp, src/devices/bus/msx/cart/scsi.cpp, src/devices/bus/msx/cart/slotexpander.cpp
bus/msx/cart/dooly.cpp: Use banks instead of views.
=> bus/msx/cart/*: Use arrays of memory views.

src/mame/casio/rz1.cpp
The RZ-1 has ten individual line outs for individual samples in addition to the regular mix output. This lets the individual sounds be more easily mixed and panned through the frontend.
=> casio/rz1.cpp: implement individual line outputs

src/mame/midway/midyunit.cpp, src/mame/midway/midyunit.h, src/mame/midway/midyunit_m.cpp, src/mame/midway/midyunit_v.cpp
Reduce unnecessary MACHINE_RESET_MEMBER and VIDEO_START_MEMBER Split machine config to reduce duplicates
Split driver state class to reduce optional finders Add missing items in save state
=> midway/midyunit.cpp: Further cleanups

src/mame/misc/coolpool.cpp, src/mame/misc/coolpool.h
Split driver state to reduce optional finders
Use palette_device for amerdart palette
Suppress side effects for debugger read
Use logmacro.h for logging functions
Use std::swap for swap function
=> misc/coolpool.cpp: Cleanups

src/mame/mame.lst, src/mame/skeleton/pcksurfer.cpp
Pocket Surfer (prototype) [Chan Chu Yo]
=> Add a skeleton for Datawind's Pocket Surfer (pocket internet terminal)

src/devices/sound/swp00.cpp, src/devices/sound/swp00.h
Through reverse engineering the ROMs of the MU50 and related sound modules I think I've figured out that the magic number that the MU50 stores along with the sample format isn't the fractional part of the loop point, but instead holds an offset and scale for DPCM decompression (which I guess makes it ADPCM).
I guess some of the related sound devices (like maybe the SWP30?) cloud also use this patch.
=> sound/swp00.cpp: Improved DPCM sample decompression

src/mame/midway/midvunit.cpp, src/mame/midway/midvunit.h, src/mame/midway/midvunit_v.cpp
Suppress side effects for debugger reads
Add missing item to save state
Use logmacro.h for logging function
Fix region naming and variable naming
Fix video clock related to PCB docs (33.3333MHz)
=> midway/midvunit.cpp: Split driver state class to reduce optional finders, cleanups:

src/mame/mame.lst, src/mame/namco/quickncrash.cpp
Quick & Crash (set 2) [Museo del Recreativo, ClawGrip]
=> namco/quickncrash.cpp: Add a new 'Quick & Crash' set

src/mame/mame.lst, src/mame/skeleton/tvcobrasd.cpp
Cobra Sport Dart / Tour Sport Dart (AY-8910 sound) [Vicente y Sergio de ElectronicaVyS, Tascabarrio]
=> skeleton/tvcobrasd.cpp: Add a new Cobra Sport Dart set with AY-8910 sound

hash/ampro.xml, hash/apc.xml, hash/tiki100.xml, hash/vixen.xml, hash/wicat.xml
- ampro.xml: Lowercase on storage media's name
- apc.xml: Lowercase on storage media's name
- tiki100.xml: Lowercase on storage media's name and replaced country abbreviation by the fullname
- vixen.xml: Lowercase on storage media's name
- wicat.xml: Added storage media's name in software list name
=> ampro.xml; apc.xml; tiki100.xml; vixen.xml; wicat.xml: Metadata cleanups

hash/megadriv.xml
Bad Dump replaced with verified one:
- Férias Frustradas do Pica-Pau (Brazil) (fixes GitHub Issue https://github.com/mamedev/mame/issues/11950) [MARCSLASH, arthurthekidboy]
Clones added:
- Sonic The Hedgehog (World, JP2, ripped from Sonic Mega Collection) [Sonic Cult, SonicBlur, Just Me, Haku Ronin]
- Sonic The Hedgehog 2 (prototype 199209xx, pirate) [drx, Hidden Palace]
=> megadriv.xml: Added 2 working items, replaced bad dump

src/mame/konami/konamigq.cpp
Fixes https://mametesters.org/view.php?id=8856.
=> konami/konamigq: Remove :image tag from HDD image (MT#08856)

hash/mz700_cass.xml
- Flagged non supported items, based on the MT08811 report
- Replaced countries' abbreviations by their full names.
- Lowercase on descriptive words
- Added loading instructions for the Sharp MZ-700 system
=> mz700_cass.xml: Metadata updates

src/mame/heathkit/h19.cpp, src/mame/heathkit/h89.cpp, src/mame/heathkit/h_88_cass.cpp, src/mame/heathkit/h_88_cass.h, src/mame/heathkit/intr_cntrl.cpp, src/mame/heathkit/intr_cntrl.h, src/mame/heathkit/sigmasoft_parallel_port.cpp, src/mame/heathkit/sigmasoft_parallel_port.h, src/mame/heathkit/z37_fdc.cpp, src/mame/heathkit/z37_fdc.h
Functional change:
- Adds writing to standard RAM when H89 has a full 64k and lower 8k is in ROM/special RAM mode.
Changes include:
- Changed to use u8/u16/u32.
- Add consistent horizontal spacing for readability.
- Update some comments.
=> heathkit/h89.cpp: General file cleanup

src/devices/cpu/h8/gt913.cpp, src/devices/cpu/h8/gt913.h, src/mame/casio/ctk551.cpp
At some point the H8/300 parent class changed all its ports to 8-bit, but the GT913 still has a 16-bit port (technically just a special write strobe meant to latch the data bus) that the ctk530 LED matrix uses.
=> gt913: fix 16-bit output port (used by ctk530 display)

src/mame/seta/ssv.cpp, src/mame/seta/ssv.h, src/mame/seta/ssv_v.cpp
- Split driver state class for with DSP
- Reduce duplicate
- Fix spacing
- Fix typename values
- Fix document
- Reduce usage of literal tags
- Reduce runtime tag lookup
- Use generic gfx decode layout for gdfs tilemap
- Fix naming for ROM region and tags
=> seta/ssv.cpp: Cleanups

src/mame/mame.lst, src/mame/subsino/subsino.cpp
Lucky Seven [Taksangs, charlie]
=> subsino/subsino.cpp: Add a new bootleg of 'Treasure Bonus' named 'Lucky Seven'

src/mame/atari/atetris.cpp, src/mame/mame.lst
Tetris (bootleg set 7, with OKI M5205) [Taksangs]
=> atari/atetris.cpp: Add a new Atari Tetris bootleg (with an extra OKI for sound)

src/mame/galaxian/galaxian.cpp, src/mame/galaxian/galaxian.h
Compared to the parent set, `bongoa` ignores the AY input ports and reads dip switches from a memory-mapped port.
This set also hacks out the code which initializes the AY port direction bits (compare code at $2288 in both sets), which means the 'noise enable' bits are never initialized either, leaving the noise generator enabled on all three channels. Is that actually what's supposed to happen or should the noise output be disabled by default instead?
=> galaxian/galaxian.cpp: 'bongoa' dip switches are memory mapped

hash/cubieboard4.xml, src/mame/mame.lst, src/mame/skeleton/cubieboard4.cpp
New not working machines
Monkey Jump [Museo del Recreativo, Recreativas.org]
cubieboard4.xml:
Android 4.1.20161119 for Cubieboard4 (v4.4, internal eMMC) [ClawGrip]
Android 4.3.20170717 for Cubieboard4 (v4.4, internal eMMC) [ClawGrip]
Debian server for Cubieboard4 (v1.0, internal eMMC) [ClawGrip]
Debian server for Cubieboard4 (v1.0, MicroSD card) [ClawGrip]
Linaro desktop for Cubieboard4 (v1.1, HDMI, internal eMMC) [ClawGrip]
Linaro desktop for Cubieboard4 (v1.0, HDMI, MicroSD card) [ClawGrip]
Linaro server for Cubieboard4 (v2.0, HDMI, MicroSD card) [ClawGrip]
Linaro server for Cubieboard4 (v2.0, VGA, MicroSD card) [ClawGrip]
=> Add a skeleton driver for Cubieboard4 (CC A-80) single board computer

hash/megadriv.xml
Fixed some descriptions and added some notes.
=> megadriv.xml: Fixed descriptions, added notes

src/mame/seta/downtown.cpp
- Use logmacro for logging functions
- Split driver class related to Tilemap chip, X1-010 soundchip
- Fix naming for ROM region and shared RAM tags
- Fix PCMMUTE bit for calibr50
=> seta/downtown.cpp: Cleanups

src/mame/misc/micro3d.cpp, src/mame/misc/micro3d.h, src/mame/misc/micro3d_a.cpp, src/mame/misc/micro3d_a.h, src/mame/misc/micro3d_m.cpp, src/mame/misc/micro3d_v.cpp
Use reference instead pointers
Add missing items into save state
Reduce unnecessary lines
Fix variable and function namings
Suppress side effects for debugger reads
Use array for noise generator
Reduce preprocessor defines
=> misc/micro3d.cpp: Cleanups:

src/mame/promat/1945kiii.cpp
Use C++ style comment for single line comments
Reduce preprocessor defines
=> promat/1945kiii.cpp: Use generic gfx decode layout, Cleanups:

src/mame/midway/midzeus.cpp, src/mame/midway/midzeus.h, src/mame/midway/midzeus_v.cpp
Use logerror.h for logging function
Reduce unnecessary lines, Constantize variables
Reduce preprocessor defines
Fix naming for ROM region and tags
Reduce runtime tag lookups
Move driver init code into machine_start and address map
=> midway/midzeus.cpp: Split driver state class per IO config, Cleanups:

src/mame/galaxian/galaxian.cpp, src/mame/galaxian/galaxian.h, src/mame/mame.lst
Jump Bug (bootleg, set 2) [Arcadedealer aka Edgar Solé aka Dios, Recreativas.org]
=> Add a new Jump Bug bootleg on Galaxian hardware

src/mame/seta/seta2.cpp, src/mame/seta/seta2.h, src/mame/seta/seta2_v.cpp
- Use logmacro for logging functions
- Move mj4simai specific stuffs into mj4simai_state class
- Fix spacing
- Use correct typename values
- USe C++ style comments for single line comments
- Fix initialization
=> seta/seta2.cpp: Cleanups

src/mame/galaxian/galaxian.cpp, src/mame/galaxian/galaxian.h, src/mame/galaxian/galaxian_a.cpp, src/mame/galaxian/galaxian_a.h, src/mame/mame.lst
This is a followup to https://github.com/mamedev/mame/pull/12314, using [this video](https://www.youtube.com/watch?v=ANLFKoMLPRI) as a reference. (I haven't attempted to figure out which color PROM the board in that video is using, though)
I was inclined to mark this set as a bootleg since the ROM differences are very clearly hacks on top of the parent set, but I'll wait for a second opinion on that.
=> galaxian/galaxian.cpp: hook up Galaxian discrete sound for 'bongoa', rename set to indicate the different hardware

src/mame/taito/taito_f3.h, src/mame/taito/taito_f3_v.cpp
addresses my own concerns with #11811 speed regression against previous implementation.
* switch AoS z buffers and per-pix blend info to SoA
* allow vectorization of line blending operation
* regains empty line optimization by tracking tilemap row usage
* consolidate sprite framebuffers (we still pull from it multiple times for each sprite priority group)
* other minor wins from safe logic reorderings
=> taito/taito_f3_v.cpp: regain performance after major rewrite

src/mame/casio/fp1100.cpp, src/mame/mame.lst
=> casio/fp1100.cpp: Add FP1000

src/mame/upl/xxmissio.cpp
=> upl/xxmissio.cpp: Move tilemap mark_tile_dirty into RAM write function, Minor cleanups:

src/mame/upl/ninjakd2.cpp, src/mame/upl/ninjakd2.h, src/mame/upl/ninjakd2_v.cpp
- Fix robokid, omegaf palette format
- Fix function namings
- Fix spacings
- Suppress side effect for debugger read
- Use correct typename values
- Fix ROM region namings
=> ninjakd2.cpp: Updates and cleanups:

src/mame/konami/konamigq.cpp, src/mame/konami/konamigv.cpp, src/mame/konami/twinkle.cpp
The 10usec delay per bytes is too slow and causing issues with games, so this should bring load speeds back closer to what it was with the old code. Should also fix https://mametesters.org/view.php?id=8860.
Previous related commits:
https://github.com/mamedev/mame/commit/a6a81a692955a8abfd41db832ec33cd64fe9323e
https://github.com/mamedev/mame/commit/cb8b90cd389ca928ffade1d8384893fdde87d4d1
=> konami/konamigv, konami/konamigq, konami/twinkle: Adjust DMA timings

src/mame/mame.lst, src/mame/rm/rm380z.cpp, src/mame/rm/rm380z.h
This PR adds support for COS 4.0/F, new romset attached below:
[rm380zf.zip](https://github.com/mamedev/mame/files/14812260/rm380zf.zip)
It's basically the same as COS 4.0/M, but with some differences in the FDC code (no motor control and different timing).  The 8" disk support is useful as it allows larger CP/M programs to run using the VDU-80 display.
I have also verified that the 4.0/M roms we had are good, and made the machine descriptions clearer by adding "/M" and "/F" postfixes.
=> rm/rm380z.cpp: Add COS 4.0/F firmware

src/mame/vsystem/fromanc2.cpp, src/mame/vsystem/fromanc2.h, src/mame/vsystem/fromanc2_v.cpp
- Split driver state class for reduce optional finders
- Correct type for variables
- Reduce literal tag usage and runtime tag lookups
- Use generic gfx decode layout
- Fix spacing
=> vsystem/fromanc2.cpp: Cleanups

src/mame/namco/namcops2.cpp
This game was actually released in 2006. 2005 is when the PS2 version came out.
=> Fix Soulcalibur III release date

src/devices/cpu/f2mc16/f2mc16.cpp, src/devices/cpu/f2mc16/f2mc16.h
Added instructions required to emulate Tomy Prin-C. Also added some fatal errors in order to not silently ignore missing instructions.
The following bugs were fixed:
* `ADD A, #imm8`/`SUB A, #imm8`: bits 8 to 15 of A must be zero-extended;
* `ADDL A, @RWx + disp8`/`SUBL A, @RWx + disp8`/`CMPL A, @RWx + disp8`/`ANDL A, @RWx + disp8`: 8-bit displacement fetched as 4 instead of 1 byte;
* `ADDSP #imm8`: 8-bit immediate must be sign-extended;
* `BLE`/`BGT`/`BHI`: Operator `or` must have precedence over checked condition value;
* `EXT`: Z flag was set on PC instead of PS;
* `MOVW @RWx + disp8, #imm16`: 8-bit displacement fetched as 2 instead of 1 byte;
* `MOV A, @RWx + RW7`/`MOV @RWx + RW7, A`: PC incremented by 3 instead of 2 bytes;
* `MOV @RWx + RW7, #imm8`: Operand fetched with 3-bit instead …
=> cpu/f2mc16: Add and fix several instructions

hash/princ.xml, src/devices/cpu/f2mc16/mb9061x.cpp, src/devices/cpu/f2mc16/mb9061x.h, src/mame/mame.lst, src/mame/tomy/tomy_princ.cpp
To simplify the changeset, I've split instruction set changes in another PR, which should be merged first: https://github.com/mamedev/mame/pull/12427
* cpu/f2mc16/mb9061x.cpp: Added most ports/registers accessed by Prin-C;
* hash/princ.xml: Marked software items as supported, and adjusted some dates to match ICs;
* tomy/tomy_princ.cpp: Implemented graphics, keyboard and pen inputs; 
* tomy/tomy_princ.cpp: Adjusted machine names to match official names given in manuals;
* tomy/tomy_princ.cpp: Added new ROM revision 3 for Prin-C non touch-pad model;
=> tomy/tomy_princ.cpp: Promoted princ and princnt to working

src/devices/machine/wd_fdc.cpp
When testing formatting disks with the new MMS controller in https://github.com/mamedev/mame/pull/12413, the formatting would fail after writing the first track. The code was checking the status byte, and expecting S1 Data Request to be 0. By adding this drop_drq() at the end of the command, it allowed the formatting to complete successfully.
=> machine/wd_fdc.cpp: lower drq at the end of track write

src/emu/emucore.h
This compiler requires exception classes to be copyable, because it copies the exception object as part of `std::current_exception()`. This means that code like the following has to work:
emu_fatalerror e1(...);
emu_fatalerror e2(e1);
However, it doesn't, because in this case the perfect-forwarding constructor is a better match than the copy constructor. So the compiler tries to instantiate the perfect-forwarding constructor with `Format`=`emu_fatalerror &`, which fails, since that's not a valid format string type.
To fix this, disable the perfect-forwarding constructor when `Format` is a subclass of `emu_fatalerror`.
Fixes #11316
=> emucore.h: fix build error on VC++

src/mame/seibu/darkmist.cpp, src/mame/seibu/metlfrzr.cpp, src/mame/seibu/mustache.cpp, src/mame/seibu/panicr.cpp, src/mame/seibu/t5182.cpp, src/mame/seibu/t5182.h
- Use DERIVED_CLOCK for Z80 clock input
- Fix spacing
- Correct typename for variables
seibu/darkmist.cpp: Cleanups
- Reduce literal tag usage and runtime tag lookups
- Fix spacings
seibu/metlfrzr.cpp: Cleanups
- Reduce literal tag usage and runtime tag lookups
- Fix spacing
- Fix ROM region namings
- Fix filename in comment
seibu/mustache.cpp: Cleanups
- Fix spacing
- Fix main CPU ROM region size
seibu/panicr.cpp: Cleanups
- Fix typo in comment
- Reduce literal tag usages and runtime tag lookups
- Use mark_tile_dirty for text tilemap layer mark dirty method
- Fix screen draw routine with cliprect
- Constantize …
=> seibu/t5182.cpp: Remove hardcoded tags, Cleanups:

src/devices/imagedev/floppy.cpp, src/devices/imagedev/floppy.h
`floppy_image_device::find_index` uses binary search to find the index for which `buf[spos] <= position < buf[spos + 1]`. However, the algorithm behaves incorrectly when `position < buf[0]`. In this case, the algorithm returns 0, as if `position` was between `buf[0]` and `buf[1]`.
The effect of this is that if `get_next_transition` is called with a timestamp that is between the start of the revolution and the first transition, then instead of returning the timestamp of that transition, it returns the timestamp of the second transition instead. Essentially, the first 1-bit on the track gets flipped to a 0.
I have encountered this in Apple II emulation, where this bug manifests as sporadic I/O errors.
Fix it by doing two things:
1. Replace `find_index` with a call to `upper_bound` from the …
=> imagedev/floppy: fix a bug with reading the first 1-bit on a track

src/emu/drivenum.cpp
If `it` points to the last element of `penalty`, the `resize` call invalidates it, and the subsequent call to `emplace` is undefined. This causes a crash in MSVC debug mode.
Fix it by resizing _after_ emplacing.
=> drivenum.cpp: fix undefined behavior in find_approximate_matches

src/emu/xtal.cpp, src/mame/mame.lst, src/mame/sega/segac2.cpp
Addition of Print Club Vol. 3 to the Sega C2 driver.
* Print Club Vol. 3 ROM entry added
* Crystal value modified; derivative `pclub` hardware used for all Print Club boards
* Print Club hardware documented in top comments, specifically daughterboards and separate analog board
* Notes about Puyo Puyo 2's link capabilities added in upper comment area
NOTE: The protection has not yet been dumped or reversed. I do not know where to begin with this, or if I should be trying to dump the Altera device directly, or what. I am requesting guidance on this matter. For now, I have a stand-in protection function, just copied from the previous volume.
=> sega/segac2.cpp: Print Club Vol. 3

src/devices/cpu/hcd62121/hcd62121.cpp, src/devices/cpu/hcd62121/hcd62121.h, src/mame/casio/pickytlk.cpp, src/mame/layout/pickytlk.lay
Most screens can now be interacted as expected. Some additional changes include:
* Add a new flag register bit, which is used for detecting when the pen is pressed and then hold down;
* Remove the last column from the LCD display, which now matches the visible area in hardware;
=> casio/pickytlk.cpp: Add tablet support

plugins/hiscore/hiscore.dat
Support for saving hi scores (game A and B) for Game & Watch Donkey Kong Jr. using hiscore plugin.
Tested in Batocera Linux v39 (MAME v0.261)
EDIT: this is my first contribution - I read the documentation and could get more input as to the best way to add other Game & Watch driver updates to hiscore.dat as I complete & validate them.  Should I just keep adding commits to this branch until it is merged (what I’m planning to do as I don’t expect this pull request to be processed immediately) or create separate pull requests?
=> hiscore: gnw_dkjr: Donkey Kong Jr (New Wide Screen)

src/devices/imagedev/floppy.cpp
Currently, when `floppy_sound_device::step` selects a new seek sample, the value of `m_seek_samplepos` remains the same as it was the last time a seek sample was played. This might be an invalid position for the new sample, since the seek samples have different lengths. When this is the case, the next call to `floppy_sound_device::sound_stream_update` makes an out-of-bounds memory access as it reads the sample data.
Fix this by resetting `m_seek_samplepos` to 0 when a new seek sample is selected.
This also makes the seek sounds more consistent, since previously they would start from a semi-random position each time.
=> imagedev/floppy.cpp: fix out-of-bounds access to the seek sample

hash/msx2p_flop.xml
Renamed “Tetris II Special Edition” to “Tetris II Special Edition (re-release)”.
=> msx2p_flop.xml: Renamed 1 item.

src/emu/emupal.cpp, src/emu/emupal.h, src/mame/gaelco/mastboy.cpp
- Use set_format for palette format
- Use tilemap_t for tilemap
- Use correct type for variables
- Reduce unused variables
emu/emupal.cpp: Add GRBx_444 palette format
=> gaelco/mastboy.cpp: Cleanups

src/mame/gaelco/gaelco2.cpp, src/mame/gaelco/gaelco2.h, src/mame/gaelco/gaelco2_m.cpp, src/mame/gaelco/gaelco2_v.cpp
- Fix metadata for snowboar* matches as copyright screen and 'OMK presents' screen
- Fix metadata for bang* matches as copyright screen
- Split snowboar state class for reduce optional finder
- Correct variable types
- Fix spacing
- Fix ROM region naming
- Reduce duplication
- Reduce unnecessary line
- Fix filename in comment
- Fix typo
=> gaelco/gaelco2.cpp: Fix metadata, Cleanups

src/mame/tecmo/gaiden.cpp, src/mame/tecmo/gaiden.h, src/mame/tecmo/gaiden_v.cpp
- Split driver class for wildfang and raiga via protection methods
- Split driver class for mastninj via MSM5205 controls
- Fix raiga post-load behavior
- Reduce duplications
- Fix function namings
- Fix, Correct type for variables
- Reduce unused functions
- Fix code style consistency
=> tecmo/gaiden.cpp: Updates & Cleanups

src/mame/igs/igs_fear.cpp
working on the disassembler highlighted some opcodes that didn't decode correctly in the 80c51XA dump in superkds, turns out it was just bad, one of the pins was floating so XingXing redumped it.
=> igs/igs_fear.cpp: replace XA dump in superkds, old one was bad [XingXing]

hash/sony_news.xml, hash/sony_news_risc.xml, src/mame/sony/news_38xx.cpp, src/mame/sony/news_68k.cpp, src/mame/sony/news_r3k.cpp, src/mame/sony/news_r4k.cpp
Because both the r3k and r4k have some level of binary compatibility, I added these into the same software list even though the current entries only work for OS installs on one or the other, so I can change this if having separate ones would be preferred.
=> sony/news_r3k.cpp, sony/news_r4k.cpp, sony/news_68k.cpp, sony/news_38xx.cpp: Add software list for Sony NEWS systems

src/devices/machine/am9513.cpp
Logging wants to show previous channel number but because channels when printed start at 1,  cliche is to always print 'c+1' meaning previous channel number is (c-1)+1  aka c  not c-1.
=> machine/am9513.cpp: fixed wrong log message for cascading TCs

src/mame/konami/ksys573.cpp
`m_pccard_cd` is in an uninitialized state after the recent PC card changes which is causing some Sys573 games to behave incorrectly (most notably ddrjb freezing on boot), so this PR initializes them to 1. Also fixed a small indentation issue I noticed.
=> konami/ksys573: Initialize m_pccard_cd

src/mame/recfranco/rf51w14cg.cpp
It was protected, the dump is useless
=> recfranco/rf51w14cg.cpp: Mark the Santa Fe Mine reels PIC as NO_DUMP

src/mame/unico/goori.cpp
- Fix ROM region naming
- Correct type for variables
- Make variables constant
- Fix spacing
=> unico/goori.cpp: Use generic gfx decode layout, Cleanups

src/mame/heathzenith/h89.cpp, src/mame/heathzenith/mms77316_fdc.cpp, src/mame/heathzenith/mms77316_fdc.h
The 77316 FDC requires wait states to work with 8" DD disks, since the 2 MHz Z80 could not handle the data rate of 8" DD disks. The hardware on the card will hold the CPU in wait states until the DRQ state is raised.
Reading and writing is now working correctly with the latest comit.
=> heathzenith/h89.cpp: Add wait states for mms 77316 fdc

src/devices/cpu/m68000/m68kfpu.cpp
commit 6957c469983 changed the write part, but missed to convert the read part. This fixes booting HP-UX 9 boot on hp9k_3xx.
Fixes: 6957c469983 ("cpu/m68000: Updated 680x0 FPU to Softfloat 3 from 2.")
=> cpu/m68000: Fix fmovem reads for mode=2

src/lib/formats/fs_hplif.cpp, src/lib/formats/hp300_dsk.cpp
With this change, all the SSDD disks from hpmuseum can be read, and the size of the disk matches. While at it, also fix a typo.
=> floptool: fix HP 9121 format #4

src/mame/atari/cops.cpp
Hopefully this is clearer, I do have a default NVRAM, but I don't know if that's worth including
=> cops.cpp: Make the first boot instruction clearer (nw)

src/mame/casio/pv1000.cpp
Research I did a year ago established that Casio's PV-1000 border colors red and blue bits are reversed. 
See https://forums.nesdev.org/viewtopic.php?p=288421#p288421
People on the discord agreed that swapping the palette definition and tiles interpretation structure was cleaner than explicitly bit-reversing the value received during the I/O port writes
=> Casio PV-1000: Border colors are wrong (blue and red are swapped)

scripts/src/sound.lua, src/devices/machine/spg2xx_audio.cpp, src/devices/machine/spg2xx_audio.h, src/devices/sound/imaadpcm.cpp, src/devices/sound/imaadpcm.h
Based on some investigations I made of V.Smile sound samples and the waveforms generated by different algorithms, it seems very likely to me that the ADPCM algorithm used in SPG2xx is actually IMA rather than OKI.
This PR adds a new class for IMA ADPCM adapted from the existing OKI ADPCM class and updates the SPG2xx machine to use this instead.
=> spg2xx: Switch ADPCM algorithm to IMA ADPCM

src/mame/heathzenith/h89.cpp
Fixes shadow writes when in ROM mode. 
- This now properly writes to the floppy RAM which fixes a boot issue with HDOS 2.0.
=> heathzenith/h89.cpp: Fix shadow memory writes

hash/aim65_cart.xml, src/mame/rockwell/aim65.cpp
Add Comelta's DRAC-1 as a new AIM 65 BIOS, and it's BASIC, an alternate version of the AIM 65 BASIC v1.1, as a new software list item.
aim65_cart.xml:
AIM 65 BASIC v1.1 (alt) [OldComputers ES]
=> Add Comelta's DRAC-1 (AIM 65 based) and it's BASIC [OldComputers ES]

src/mame/heathzenith/z37_fdc.cpp
Fixes disk formatting under HDOS 2.0. 
This change is not needed for HDOS 3.0 or CP/M 2.2.04 disk formatting.
Verified with the schematics, the ready line is tied to +5V.
=> heathzenith/z37_fdc.cpp: Fix HDOS 2.0 INIT (disk formatting)

src/devices/machine/ncr5385.cpp
- Tek4404 issues cmd=0xff which expects an IRQ even though its an INT_INVALID_CMD
- minor readability; replaced magic hex value with symbolic names
=> machine/ncr5385.cpp: raise IRQ for INT_INVALID_CMD

src/mame/trs/gime.cpp
Video 512k bank is external to the GIME. It can be changed at anytime.
=> trs/gime.cpp: video 512k bank is not tied to the frame start

src/mame/mame.lst, src/mame/tvgames/xavix.cpp
--------------
Excite Ping Pong 2 (Japan) [Team Europe, Peter Wilhelmsen, David Haywood]
Croket! Itada Kinka! Banker Battle!! (Japan) [Team Europe, Peter Wilhelmsen, David Haywood]
Shooting King (Japan) [Team Europe, Peter Wilhelmsen, David Haywood]
Gun Gun Revolution (Japan) [Team Europe, Peter Wilhelmsen, David Haywood]
these all run, but lack inputs.  Excite Ping Pong 2 has some graphical corruption which looks like it might be bitrot, so is marked as bad (reads were consistent)
=> added 4 XaviX based games, not working

scripts/src/sound.lua, src/devices/sound/roland_gp.cpp, src/devices/sound/roland_gp.h, src/devices/sound/roland_lp.cpp, src/devices/sound/roland_lp.h, src/devices/video/t6963c.cpp, src/devices/video/t6963c.h, src/mame/roland/roland_cm32p.cpp, src/mame/roland/roland_d50.cpp, src/mame/roland/roland_d70.cpp, src/mame/roland/roland_jv80.cpp, src/mame/roland/roland_r8.cpp, src/mame/roland/roland_u20.cpp
- Renames `rolandpcm` into `roland_lp` to make it distinct from other PCM chips
- Adds a skeleton for the GP (TC6116) chip
- Fixes the T6963C LCD controller by adding ram read support and correct text/graphics enable register handling. This makes the Roland D-70 behave correctly with message popups
- Fixes the allocation of waveroms in the Roland D-70
- Adds the first ever dump of the internal mask ROM of the Roland D-50 CPU
- Fixes the memory map of the JV80 and wires up the PCM chip skeleton
- Adds a skeleton and ROM dumps for the RD-500
=> Fixes/ROMs for Roland stuff

src/mame/igs/igs_fear.cpp, src/mame/igs/pgmcrypt.cpp
igs_fear.cpp - add IGS027A dump to fearless
pgmcrypt.cpp - properly fix fearless decryption
=> igs/igs_fear.cpp - add IGS027A dump to fearless [tormod, Peter Wilhelmsen, XingXing]

scripts/src/cpu.lua, src/devices/cpu/z80/r800.cpp, src/devices/cpu/z80/r800.h, src/devices/cpu/z80/z80.cpp, src/devices/cpu/z80/z80.h, src/devices/cpu/z80/z80.lst
- Removed undocumented Z80 instructions that are not supported by the R800
- Updated basic instruction timing
- Implement MULUB and MULUW 
Other R800 features are still not implemented
=> cpu/z80/r800.cpp: Updated instruction execution.

src/mame/igs/igs_fear.cpp
- added timer and interrupt
- added rtc
- add input and dipswitch
- add fipx in sprite drawing
- correct game version of superkids
=> igs/igs_fear.cpp: made game playable without sound [XingXing]

src/mame/nintendo/snes_m.cpp, src/mame/nintendo/snesb.cpp
This adds/verifies the DIP definition for all the SNES bootlegs that had a TODO for them. Defaults are based on the original SNES games, when possible, aside from Wild Guns (the original gives extends at 100k, which isn't an option with this bootleg, so the default is 400k to match current MAME behavior).
Also, Wild Guns now inits the continue counter on boot/reset, which is apparently supposed to be done by whatever's on the other side of the shared RAM. The only times it's initialized by the game itself are when the current counter hits zero or when a second player joins mid-game. I promoted it to working since I didn't encounter any other issues during a full playthrough.
=> nintendo/snesb.cpp: fill in missing DIP switches for several games, add continue counter init for Wild Guns

src/mame/mame.lst, src/mame/skeleton/webtouchone.cpp
Alcatel Web Touch One (model 2840, Terra, Spanish) [Arcade Hacker, ClawGrip]
=> Add a skeleton driver for Alcatel Web Touch One web phone

src/devices/bus/mc10/mc10_cart.cpp, src/devices/bus/mc10/mc10_cart.h, src/devices/bus/mc10/mcx128.cpp, src/devices/bus/mc10/mcx128.h, src/devices/bus/mc10/multiports_ext.cpp, src/devices/bus/mc10/multiports_ext.h, src/devices/bus/mc10/pak.cpp, src/devices/bus/mc10/pak.h
Resolving the comments on #12080
- Clean some mentioned code aspects
- Specify the ROM minimum size and block size
- Sort includes
- Clean the global namespace
- Add license lines
Report the comments on other previously written MC10 cart devices.
=> trs/mc10.cpp: add minimum rom size and block size for cartridge rom, clean global namespace

src/mame/taito/buggychl.cpp
Add other known undumped versions:
- Another ranking song version - ported to PS2 "Taito Memories".
https://youtu.be/JXIvaM5508c?si=wCojMales2Kg9L7u&t=270 (Ranking 1st song)
https://youtu.be/Btnl9FYTiL8?si=rrGTblIfOlIQo6NJ&t=308 (Ranking 2nd song)
- 2 player joystick version - after inserting a coin, 
instead of "START YOUR ENGINE", it displays "PUSH ONLY 1-PLAYER BUTTON".
https://youtu.be/iE9-q4IruS4?si=eYL5_iXDZDyH9TS_&t=31
(The title of this video states that this is the joystick version)
- Japanese version - after inserting a coin, instead of "START YOUR ENGINE", 
it displays "セレクトボタンをおしてね！！(Press select button!!)" 
and "クレジット(Credit)" instead of "CREDIT".
https://youtu.be/gmC8Al1oCpo?si=JTO6eJ5Q_6-bj_NQ&t=6
=> taito/buggychl.cpp: add description of undumped versions.

src/devices/machine/spg2xx_audio.cpp, src/devices/machine/spg2xx_audio.h
Summary of new behavior:
* Automatic stops sets channel stop flag while keeping channel enable flag unchanged (unlike current emulation where it's cleared). 
* Channel is only active (channel status flag true) when enable flag is true and stop flag is false.
This was verified in real hardware by running audio test roms on V.Smile. From what testing I have done so far, the changes don't really affect the games much if at all, but it should be technically more accurate.
=> spg2xx: Fix behavior of audio channel enable/stop flags

hash/msx2_flop.xml, scripts/src/bus.lua, src/devices/bus/msx/cart/cartridge.cpp, src/devices/bus/msx/cart/ide.cpp, src/devices/bus/msx/cart/ide.h, src/devices/bus/msx/cart/slotoptions.cpp, src/devices/bus/msx/cart/slotoptions.h, src/devices/machine/atahle.cpp, src/devices/machine/atahle.h
bus/msx/cart/ide.cpp: Add support for Sunrise ATA-IDE [msxpro, Wilbert Pol]
machine/atahle.cpp:
- Clear DMA modes when switching to PIO mode.
- Do not log when reading from the debugger.
msx2_flop.xml: Added 2 items.
Sunrise IDE firmware (v2.50) [anonymous]
Sunrise IDE firmware (v2.40) [anonymous]
=> bus/msx/cart/ide.cpp: Add support for Sunrise ATA-IDE [msxpro, Wilbert Pol]

src/devices/machine/spg2xx_audio.cpp, src/devices/machine/spg2xx_audio.h
Also discovered from testing in real hardware (V.Smile). Probably not likely to noticeably affect games, but should still be technically more accurate.
=> spg2xx: Auto-increment wave address register when channel is playing

scripts/src/bus.lua, src/devices/bus/ieee488/hp9133.cpp, src/devices/bus/ieee488/hp9133.h, src/devices/bus/ieee488/ieee488.cpp, src/devices/cpu/m6809/base6x09.lst, src/devices/cpu/m6809/m6809.cpp, src/devices/cpu/m6809/m6809.h, src/devices/machine/wd2010.cpp, src/devices/machine/wd2010.h, src/mame/hp/hp98x6.cpp
This adds the HP9133 disk drive, which was common with HP9000 200 and 300 systems. It also adds a sync acknowledge callback to the 6809, and multi sector read/write to wd2010.
=> Add HP9133 disk drive

src/devices/machine/at28c64b.cpp
actual rom size may be less than AT28C64B_DATA_BYTES. a2bus/booti,  as a motivating example, has a ROM size of 0x2000.
MT 08524
=> machine/at28c64b.cpp: Fix read overflow initializing nvram

src/mame/konami/viper.cpp, src/mame/mame.lst
Most changes from #12546 along with additional changes.
- Updated TODO to remove problems "fixed" by the skeleton LAN controller device.
- Removed outdated "Game status" list.
- Added lightgun inputs to wcombatu.
- Marked thrild2c's CF dump as bad.
- Removed all clones with alt CF dumps of the same version: p911ea, thrild2ab, thrild2ac, tsurugie, wcombatb
=> konami/viper.cpp: hookup wcombat inputs, update QA

src/devices/machine/upd765.cpp, src/devices/machine/upd765.h
The upd765 does not clear the drive busy bits until you issue a sense interrupt status command. Without this fix CP/M Plus on the QX-10 gives disk I/O errors because it expects the busy bit to stay set until it has a chance to issue the SIS command.
I have verified this is the correct behavior on a real QX-10, which uses a NEC D765AC as its floppy controller. Regarding the cpc6128, this fix does not seem to cause an issues with accessing a disk, I can run cat from basic and get a directory as well load files from the disk. Same thing with the specpl3e, loading programs from disk appears to work fine.
=> upd765: Drive busy bits should not be cleared until a SIS is executed

src/mame/casio/pv1000.cpp
* ioFF has a toggle that just draws border color instead of tiles, so that the CPU runs faster.
* The pixel clock is slow, so the pixel aspect is noticeably wide - about 4:3
* ioFF supports drawing tile data from all eight 8KiB windows out of the 64KiB address space; add support for the easy bottom four
=> casio/pv1000.cpp: Three tiny changes

hash/megaduck.xml
new NOT WORKING Software List entry
----------
megaduck.xml: Bilder Lexikon [PeT, TeamEurope, SSJ, Youkal3]
"The Bilder Lexikon contains 512kbyte via 32kbyte Bankswitching at $0, but the switching address is $1 like for the 16kbyte bankswitching."
=> new NOT WORKING Software List entry

src/devices/bus/rs232/rs232.cpp, src/mame/dec/rainbow.cpp, src/mame/falco/falco500.cpp
This adds the support for using the Mouse Systems serial mouse in the QX-10 emulation. Valdocs supported this mouse when using programs like valpaint and valdraw.
=> rs232: Add Mouse Systems serial mouse to default rs232 list.

hash/msx2_flop.xml
Renamed “NV Magazine Special 26 (Japan)” to “NV Magazine 1996-7 (Japan)”.
Renamed “NV Magazine 1996-08 (Japan)” to “NV Magazine 1996-8 (Japan)”.
Renamed “NV Magazine 1996-09 (Japan)” to “NV Magazine 1996-9 (Japan)”.
Renamed “NV Magazine 1997-01 (Japan)” to “NV Magazine 1997-1 (Japan)”.
Renamed “NV Magazine 1997-09 (Japan)” to “NV Magazine 1997-9 (Japan)”.
Renamed “NV Magazine 2002-06 (Japan)” to “NV Magazine 2002-6 (Japan)”.
Renamed “NV Magazine 2002-07 (Japan, incomplete dump)” to “NV Magazine 2002-7 (Japan)”.
Renamed “NV Magazine 2002-08 (Japan)” to “NV Magazine 2002-8 (Japan)”.
Removed “R・SYSTEM 3.2 (Japan)”, it was part of NV Magazine 1996-12.
NV Hokkaido Vol. 1 (Japan) [file-hunter]
NV Magazine 1 (Japan) [file-hunter]
NV …
=> msx2_flop.xml: Added 56 items, 52 working. Removed 1 item.

scripts/src/cpu.lua, src/devices/cpu/xa/xa.cpp, src/devices/cpu/xa/xa.h, src/devices/cpu/xa/xa_ops.cpp, src/devices/cpu/xa/xadasm.cpp, src/devices/cpu/xa/xadasm.h, src/devices/sound/ics2115.cpp, src/mame/igs/igs_fear.cpp, src/mame/igs/igs_m027.cpp
(squashed version of the PR, as requested)
this adds basic execution to XA core.  It emulates enough of the XA to give fearless and superkds working sound.
some considerations
- only the exact forms of the opcodes used so far have been implemented
- no optimizations have been done, use of const, inline use, templates etc. are planned for a future update; code is still primed for debugging and development
- overall structure, code style are not 100% final (see above) and will be adjusted as the CPU is better understood
- peripherals, interrupts etc. are not yet fully implemented, nor is anything outside of the page zero mode used here due to lack of test cases
Machines Promoted to WORKING
Super Kids (S019CN) [David Haywood, XingXing]
Fearless Pinocchio …
=> cpu/xa: CPU core work for fearless/superkds - adds sound, promotes to working

hash/easy_karaoke_cart.xml, src/mame/mame.lst, src/mame/skeleton/easy_karaoke.cpp
Disney Classic Handheld Karaoke Player (DKS7000-C) [Sean Riddle, David Haywood]
-------------------------------------
easy_karaoke_cart.xml
dkp2: Disney Princess 10-Song Karaoke Cartridge II (DK-P2)  [Sean Riddle, David Haywood]
dkp3: Disney Princess 10-Song Karaoke Cartridge III (DK-P3)  [Sean Riddle, David Haywood]
(also removed the parent/clone relationships from most of these, as they're distinct products in reality)
=> new NOT WORKING machines (Disney Classic Handheld Karaoke Player)

src/mame/heathzenith/h8.cpp, src/mame/layout/h8.lay
Add front panel keypad and support for serial console to Heathkit H8.
=> Heath/Zenith H8: Add Front Panel Keypad and Support for Serial Console

src/mame/nmk/macrossp.cpp
- Use generic gfx decode layout
- Use array for background tilemaps and related stuffs
- Fix code style consistency
- Use cliprect for background drawing
- Fix ROM region and function namings
- Fix spacing
- Use correct typename for member variables
- Demote quizmoon MACHINE_IMPERFECT_GRAPHICS and MACHINE_IMPERFECT_SOUND via incorrect blending method and sound in title scene
=> nmk/macrossp.cpp: Cleanups:

hash/altos586.xml, src/devices/cpu/i86/i186.h, src/devices/cpu/i86/i86.cpp, src/devices/cpu/i86/i86.h, src/mame/altos/altos586.cpp, src/mame/altos/altos586_hdc.cpp, src/mame/altos/altos586_hdc.h, src/mame/mame.lst
Hi. This adds incomplete emulation of Altos 586 -- the main board and a hard drive board. It is good enough to boot and pass tests on the diagnostic floppy, but not much else (no XENIX, CCP/M, OASIS). More details in the commit messages of the individual commits and code comments.
I eventually intend to extend the emulation to boot all the supported software, but as I'm pretty new to MAME, I thought it's a good idea to post this for review early, before I go too far doing something stupid. 
This is my first time programming C++ so please go easy on me :)
=> Add Altos 586 emulation

hash/leapfrog_leappad_cart.xml
new NOT WORKING Software List entries
leapfrog_leappad_cart.xml  [David Haywood, Team Europe]
ecchello1: ECC Junior no hajimete eikaiwa! 1 Eigo de tanoshiku Say Hello! (Japan)
funtogeth: Minna de tanoshiku! CoCoPad (Otameshi soft) (Japan)
bennyeng2: Benny and Friends English Book Vol. 2 -Majo to taiketsu! Daibouken- (Japan)
thomasj: Kikansha Thomas to nakamatachi - Kikansha Thomas Yakunitatsu kikansha (Japan)
multy2j: Shinkenzemi Challenge 2 nensei Korasho to issho ni kuku o oboeyou! (Japan)
anpapinj: Anpanman no CoCoPad de aiueo kyoushitsu Pinocchio (Japan)
idainaru: Idainaru Sakkyokukatachi (Japan)
anpanmnj: Yuuki Rinrin Anpunch! (Japan)
helkitj: Hello Kitty no gakkou no ichinichi (Japan)
disprinj: Disney Princess (Japan)
poohj: Kuma no Pooh-san Hachimitsu no …
=> new NOT WORKING Software List entries (CocoPad)

hash/dai_cass.xml, hash/pcw.xml, hash/xegs.xml
- Replaced countries' abbreviations by their full name.
- Lowercase on descriptive words.
- Added language info.
=> dai_cass.xml; pcw.xml; xegs.xml: Metadata cleanings

src/mame/metro/metro.cpp, src/mame/metro/metro.h, src/mame/metro/metro_v.cpp
- Move save_items and some init stuffs in machine_start()
- Use correct typename values
- Fix variables and function namings
- Reduce literal tag usage and runtime tag lookups
=> metro/metro.cpp: Split driver state class via hardware config, Cleanups:

src/mame/konami/xmen.cpp
Connects service ports, following our [schematic extraction for a GX065 board](https://github.com/jotego/jtbin/blob/master/sch/xmen.pdf) (xmen 2p)
Note that I am reviewing the schematics and the PDF may change in the coming weeks with corrections.
=> konami/xmen.cpp: Add service switch inputs

src/mame/neogeo/midas.cpp, src/mame/neogeo/neogeo_spr.h
neogeo/midas.cpp: Fix zoom table RAM size (The maximum allowed access is 64K bytes)
=> neogeo/neogeo_spr.cpp: Fix display timing related parameters

src/mame/casio/pv1000.cpp
This slows down games to realistic speeds.
Please let me know if there's a better way to do any of this.
=> casio/pv1000.cpp: Toggle BUSREQ like hardware does

src/osd/modules/debugger/debuggdbstub.cpp, src/osd/modules/lib/osdobj_common.cpp, src/osd/modules/lib/osdobj_common.h
This allows setting the host to 0.0.0.0 to accept connections from outside of localhost.
=> gdbstub: add -debugger_host option

src/mame/konami/k052109.cpp, src/mame/konami/k052109.h
- adds missing information about internal registers
- correctly implements color bit selection (one kludge removed)
Tested on xmen and gradius3 (set the selection bit high) and several of the other games (tmnt,tmnt2,aliens,mia,scontra,thunderx,ssriders) which do not set it.
=> konami/k052109.cpp: Remove the color kludge for xmen/gradius3

src/mame/misc/changyu.cpp
except the psg since its mapped at 0x0502 0x0503 data address write in the mcu.
=> misc/changyu.cpp: Add VBL NMI and hook up the opll for changyu2

src/mame/atari/cops.cpp
we tend to provide default nvrams for games which require non-obvious bootup/init procedures, so do that here.
=> cops.cpp: revlatns - provide a default nvram

hash/hp98x6_rom.xml, src/mame/hp/hp98x6.cpp, src/mame/hp/hp98x6_optrom.cpp, src/mame/hp/hp98x6_optrom.h
Hi,
this commit adds the support for optional ROMs to HP98x6 family of systems.
I'll e-mail the relevant ROM images shortly.
Thanks.
--F.Ulivi
=> HP98X6: added support for option ROMs

src/mame/igs/igs017.cpp, src/mame/igs/igs017_igs031.cpp, src/mame/igs/igs017_igs031.h, src/mame/igs/igs_m027.cpp, src/mame/igs/igs_m027xa.cpp, src/mame/mame.lst
jking02,  crzybugs - add IGS027A internal ROM dumps [Peter Wilhelmsen]
I've also moved the sprite/tile gfx decryptions out of igs017.cpp driver file, and into the video device, as I think it must be a configurable behavior of the 031 (many IGS encryptions are configurable, and it needs to be shared between drivers too)
The machines with an XA have also been split out to a different driver for now
=> jking02,  crzybugs - add IGS027A internal ROM dumps [Peter Wilhelmsen]

src/mame/casio/pv1000.cpp
Hardware documentation is at https://obscure.nesdev.org/wiki/Casio_PV-1000/ASIC_registers#Interrupt_enable_($FC)_%3E_write
=> casio/pv1000.cpp: implement IRQs (and acknowledgement) like hardware does

src/devices/cpu/t11/t11.cpp, src/devices/cpu/t11/t11dasm.cpp, src/devices/cpu/t11/t11ops.hxx, src/devices/machine/pdp11.h, src/mame/ussr/bk.cpp, src/mame/ussr/bk_m.cpp
Allows bus error handlers on BK to deal with interrupt from STOP key (which causes a HALT-mode IRQ and triggers access to unmapped region at 177674).
=> cpu/t11, ussr/bk: Improve interrupt handling on 1801VM1, misc fixes.

src/devices/bus/pci/pdc20262.cpp, src/devices/machine/sis7018_audio.cpp, src/devices/machine/sis950_lpc.cpp, src/mame/konami/viper.cpp, src/mame/nec/pce_cd.cpp, src/mame/pc/sis630.cpp
Replacing the typo word complaint with compliant to help make a little more sense for certain pieces.
=> Replace a few complaint with compliant (Part 1)

src/mame/igs/igs_m027.cpp
this is how all the booting sets in the driver look now (tilemap visible in at least 1 screen in each)
=> igs_m027.cpp - fix some tile ROM loading

src/mame/misc/changyu.cpp
At least PSG on MCU has hooked up.
except the machine tried to write to send commad the soundcpu mcu at 0x2038.  at 0c data space memory of mcu if write 21. will sound alarm.
=> misc/changyu2.cpp: Add PSG to sound CPU memory map

src/mame/motorola/mex68kecb.cpp
Add an Abort button that triggers an NMI, just like the hardware.
Also fix the boot vector handler's comment to refer to the correct ROM location and the correct number of bytes that are mapped from the ROM.
=> mex68kecb: Add Abort button, minor cleanup

src/mame/igs/igs_m027.cpp
this is fairly crude, but it allows us to see that the decrypt functions are correct for program (was correct) and sprites (was not correct)
=> Update igs_m027.cpp - bypass chessc2 startup check so decryption can be verified

src/mame/mame.lst, src/mame/trainer/ms68k.cpp
The Marion Systems MS68K was a single-board 68000 system designed by Tom Oberheim in 1985 with a DUART providing two serial ports and (in combination with a latch) a parallel printer port, WD1772 floppy controller, optional NCR53C80 SCSI controller, and up to 512KB of RAM and 128KB of ROM onboard. Also included is an expansion connector providing access to most of the 68000 bus as well as memory refresh signals and a single dedicated interrupt line.
The stock ROM is a monitor that also contains a port of Tiny BASIC 1.2 at 0xF04900 with a loader at 0xF04800. Thus while there is no direct monitor command to start it, a simple GF04800 will start Tiny BASIC (and as usual BYE will exit back to the monitor).
The monitor’s included floppy boot functionality will load the first sector of the disk …
=> MS68K: Marion Systems MS68K

src/mame/nmk/ddealer.cpp
Same work done on this PR for **nmk/nmk16.cpp** driver:
https://github.com/mamedev/mame/pull/12562
is now applied in **nmk/ddealer.cpp**
Double Dealer uses the same "hires" screen resolution than several games in the nmk16 driver, and the same interrupt system based on PROM contents, so the same config is applied to it.
Pixel Clock was confirmed on real hw, too.
=> nmk/ddealer.cpp: upgraded interrupts trigger system based on PROM contents

src/mame/apple/apple2e.cpp
- Initializes Apple //c mouse related variables
- Sets Y0 interrupt flag on //c mouse Y-axis movement even if X-axis movement is still being processed (allowing both the X0 and Y0 interrupt flags to be set at the same time)
- Increases //c mouse port sensitivity (found in apple2e.cpp) from 20 to 40 to match that of the //e mouse (found in a2bus/mouse.cpp)
=> apple2e: Apple //c mouse fixes

src/devices/bus/s100/vectordualmode.cpp, src/devices/imagedev/floppy.cpp, src/devices/imagedev/floppy.h, src/lib/formats/flopimg.cpp, src/lib/formats/flopimg.h
Here is an alternate approach for handling hard-sectored floppy drives. Instead of requiring duplicating the existing drives and updating the variants, the sectoring is set during device configuration. This allows the drive to select the proper variants based on the sectoring type.
=> floppy.cpp: Use standard drives for hard-sectored systems

hash/nes.xml
New working software list items (nes.xml)
D-Pad Hero (version 1.0)
D-Pad Hero (version 1.1)
D-Pad Hero II
The latest version of the games are available at https://dpadhero.com/Download.html
D-Pad Hero 1 1.0 can be found on the wayback machine at https://web.archive.org/web/20100110052408/https://dpadhero.com/Download.html
=> hash/nes.xml: add three working NES homebrew games

hash/nes.xml
New NOT WORKING software list additions
8-bit Xmas 2023
ROM can be downloaded from https://www.retrousb.com/product/8-bit-xmas-2023/33?cp=true&sa=false&sbp=false&q=false&category_id=W4OKTBSUZRS2F3DC6WNNJ476
Game doesn't function in MAME presently; maybe a new mapper is required? Very similar graphical bugs as xmas16, perhaps they are related.
=> hash/nes.xml: Add 8-bit Xmas 2023, NOT WORKING

hash/coleco.xml, hash/coleco_homebrew.xml
[coleco] Replaced "Euro" abbreviation to "Europe"
[coleco_homebrew] Uppercase to "64K" description
=> coleco.xml; coleco_homebrew.xml: Metadata cleanups

src/devices/cpu/tlcs900/tmp95c061.cpp, src/devices/cpu/tlcs900/tmp95c061.h, src/devices/cpu/tlcs900/tmp95c063.cpp, src/devices/cpu/tlcs900/tmp95c063.h
Based on feedback from @cuavas at https://github.com/mamedev/mame/pull/12684#discussion_r1730040576, this PR uses templates to "avoid copy/pasta".
=> use templates for TLCS900 I/O ports

src/mame/sun/sun3.cpp, src/mame/sun/sun3x.cpp, src/mame/sun/sun4.cpp
Add default NSCSI tape support to sun3, sun3x, and sun4.
=> sun3, sun3x, sun4: Add NSCSI tape to default devices.

src/mame/namco/namcos12.cpp
-Added links to a flyer for Aerosmith's Quest For Fame and changed the date from 2001 to 1999 in order to match the year on the flyer and other sources that reference this as the release year
-Added a link to videogame footage of Submarines and a specific reference of the tradeshow where the cabinet was demonstrated
Reference of the trade show:
https://web.archive.org/web/20200927151212/https://ascii.jp/elem/000/000/314/314701/
=> Update notes on undumped namcos12 games

scripts/src/cpu.lua, src/devices/cpu/mpk1839/kl1839vm1.cpp, src/devices/cpu/mpk1839/kl1839vm1.h, src/devices/cpu/mpk1839/kl1839vm1dasm.cpp, src/devices/cpu/mpk1839/kl1839vm1dasm.h, src/mame/mame.lst, src/mame/ussr/pk32.cpp, src/tools/unidasm.cpp
*Elektronika PK32* is based on MPL1839 and wasn't produced to mass market.
at the current state PK32 runs in terminal mode with all internal tests pass.
\+ mpl1839/kl1839vm1.cpp: MPL's *L1839VM1* cpu device:
1839 cpu is able to execute code in user space fully compatible with VAX11
Some info available here (rus):
http://turbinium.com/forum/index.php?topic=16.0
=> ussr/pk32.cpp: Elektronika PK-32 - not working

src/mame/skeleton/gm1000.cpp
Add dump of Eniac Sound Saurus BH-1000
https://piano.tyonmage.com/eniac/bh-1000.html
There's a previous dump of the Suzuki GM-1000 which seems to be pretty much the same device. That one lacks the mask rom dumps.
Pics: https://photos.app.goo.gl/G12YJPEWpDKQPYr69
Roms have been sent to DU. Let me know if you need them.
Credit: buffi
=> gm1000.cpp: Add dump of Eniac Sound Saurus BH-1000

hash/ibm5170_cdrom.xml, hash/mac_cdrom.xml
This is basically a dump of all the physical Doom games I have.  It's a bit more complete than before. :-)
New working software list titles (ibm5170_cdrom.xml)
----------------------------------------------------
Chex Quest [Digital Café]
Demon Gate: 666 New Levels for Doom & Doom II [Laser Magic] Depths of Doom Trilogy [id Software]
Doom II [id Software]
Doom II French [id Software]
Doom Shareware [id Software]
Doom: Collector's Edition [id Software]
Final Doom [id Software]
Hell to Pay [Wraith Corporation]
Heretic: Shadow of the Serpent Riders [Raven Software]
Hexen: Beyond Heretic [Raven Software]
Hexen: Deathkings of the Dark Citadel [Raven Software]
Master Levels for Doom II [id Software]
Strife: Quest for the Sigil [Rogue Entertainment]
The Ultimate Doom [id Software]
New working …
=> hash/{ibm5170,mac}_cdrom: Doom and related games

hash/apple2_cass.xml, hash/apple2_flop_clcracked.xml, hash/apple2_flop_orig.xml
apple2_flop_orig: Added forty four working items and updated one item.
apple2_flop_orig: Redumped one item.
apple2_flop_orig: Improved metadata.
apple2_flop_clcracked: Redumped one item.
apple2_flop_clcracked: Removed two imperfect cracks.
apple2_flop_clcracked: Improved metadata.
apple2_cass: Added one not working item.
New working software list items (apple2_flop_orig.xml) 
A Week That Changed The World [4am, yesterbits, A-Noid] 
Adventure in Time [4am, txgx42, A-Noid]
Animate [4am, A-Noid]
Bag of Tricks 2 (version 2.0) [4am, A-Noid]
David-DOS [4am, A-Noid]
Early Heroes of the Bible [4am, yesterbits, A-Noid] 
Federation [4am, A-Noid]
Israel's Golden Years [4am, yesterbits, A-Noid]
Measuring Economic Activity [4am, LoGo, A-Noid]
Moses Leads His People …
=> apple2_flop_orig, apple2_cass: Added latest dumps and improved metadata.

src/mame/capcom/lwings.cpp
Adds control of the sound CPU reset line by the main CPU, following original Trojan schematics.
=> trojan/avengers: sound CPU reset control by main CPU

hash/thinkpad8xx.xml
=> thinkpad8xx.xml: Fix AIX 2nd CD name

hash/neogeo.xml
New working software list addition
GladMort (demo 2) [PixelHeart]
=> neogeo.xml: Added 1 working item

hash/ibm5170_cdrom.xml
=> hash/ibm5170_cdrom: Add Zork Nemesis

src/mame/misc/mcatadv.cpp
Checked exact Z80 CPU type and included U3106-F which is also in Nostradamus
=> misc/mcatadv.cpp: Clarified comment about sound chips

src/mame/mame.lst, src/mame/skeleton/tvdear.cpp
new NOT WORKING systems
TV Dear [David Haywood, Team Europe]
=> new NOT WORKING systems (TV Dear)

src/mame/ibm/thinkpad600.cpp, src/mame/mame.lst
IBM ThinkPad 600 [ArcadeHacker]
IBM ThinkPad 600E [ArcadeHacker]
=> Add a skeleton for IBM ThinkPad 600 series

src/mame/ibm/thinkpad600.cpp
=> ibm/thinkpad600.cpp: The 2nd SEEPROM was on the 600E, not on the 600

hash/ibm5170_cdrom.xml
Same methodolgy as Zork; discs 1 and 3 are MODE2 data tracks and use raw 2352B sectors, disc 2 is MODE1 and fine as a 2048B sector disc.
=> hash/ibm5170_cdrom.xml: add Duke Nukem Kill-A-Ton Collection

src/devices/sound/k054539.cpp, src/devices/sound/k054539.h
The external RAM has indeed 32kB, as comments in the MAME source file say. However, the k054539 class is dealing with it as 16kB. The connection to the chip has the upper address bit connected to the K054539 address bit 16, not the expected 14. Checkout the schematics extracted by my team:
If you inspect Konami's X-Men test sequence, you will see that it keeps advancing the internal test address register until bit 16 toggles, then it writes test content again. After that, it keeps advancing it until it wraps around and it checks at the two 16kB halves: the one at A16=0 and then A16=1. It stops the test after checking the first 16kB at A16=1 without writting the pointer again (as it is not needed)
This is a simulation of my verilog implementation of X-Men, but you can check the behavior in …
=> k054539: correctly handles reverb RAM as 32kB during test and initialization

docs/source/initialsetup/compilingmame.rst
* Corrects a typo where "_DirectX SDK_" was misspelled as "_Direct SDL_" (understandably :smiley:).
* Updates information about DirectX SDK availability.
Fixes  #12849
=> Improve DirectX SDK information in Docs

hash/famicom_flop.xml, hash/nes.xml, hash/snes.xml
Homebrew game inspired by an iPhone game "Desert Golfing". There's a [YouTube video](https://www.youtube.com/watch?v=9UP7HImbAlA) about its development. It's pretty fun!
Old versions are not available for download anymore from [the official page](https://rainwarrior.itch.io/nesert-golfing), which only offers the latest 1.5. A workaround I found that I feel is acceptable, is that according to the [README in the source](https://github.com/bbbradsmith/NESertGolfing/), [cc65 commit 80a43d732](https://github.com/cc65/cc65/commit/80a43d732dc9551ad84343ea9644d8fab7ec0bd9) was used as the toolchain. By building this exact version, I was able to create byte-for-byte perfect replicas of the 1.5 ROMs; since this toolchain version is older than NESert Golfing, the developer likely never updated it …
=> hash/{famicom_flop,nes,snes}.xml: add (s)NESert Golfing

src/mame/atari/asteroid.cpp
This seems to have been omitted for some reason.
=> asteroid: Set the watchdog frequency.

hash/thinkpad8xx.xml
thinkpad8xx.xml: IBM AIX 4 [ClawGrip]
Also added some metadata to AIX 4.1.5
=> hash/thinkpad8xx.xml: Add AIX 4 (not working)

src/devices/machine/timekpr.cpp, src/mame/misc/multfish.cpp, src/mame/misc/multfish.h, src/mame/misc/multfish_boot.cpp
- Fix naming
- Make video RAM to unique_ptr
- Fix type values for variables
- Fix spacings
- Reduce static functions
machine/timekpr.cpp: Suppress side effect in debugger read
=> misc/multfish*.cpp: Minor cleanups

src/mame/mame.lst, src/mame/skeleton/dash4.cpp
DASH4 Debug Adapter [Arcade Hacker]
=> Add a skeleton for DASH4 Debug Adapter for SH CPUs

src/devices/bus/a2bus/suprterminal.cpp
Poking CFFF and then C300 is supposed to map the C800 range to the Sup'R'Terminal extension ROM.
But if you do that right after bootup, then the CFFF poke will not run `a2bus_suprterminal_device::write_c800`, because the C800 range is not yet assigned to the Sup'R'Terminal. (IOW, `apple2_state:m_cnxx_slot` is still -1.) Because of that, `m_bC800IsRAM` will remain uninitialized.
The C300 poke will then assign the C800 range to the Sup'R'Terminal, but since `m_bC800IsRAM` is uninitialized, it will be unpredictable whether accesses to that range go to the extension ROM or RAM.
Fix this by initializing `m_bC800IsRAM` in `a2bus_suprterminal_device::device_start`.
=> suprterminal: fix unpredictable memory map due to uninitialized value

scripts/src/osd/modules.lua
This is closer to how Qt6's moc.prf finds moc, i.e.
```
qtPrepareLibExecTool(QMAKE_MOC, moc)
...
defineTest(qtPrepareLibExecTool) {
isEmpty(instloc): instloc = "$$[QT_HOST_LIBEXECS]"
qtPrepareTool($$1, $$2, $$3, $$4, $$instloc)
}
```
---
Specifically adding for Homebrew - https://github.com/Homebrew/homebrew-core/pull/193751
However, I think this will help other repositories/distros that don't use `QT_HOME / libexec / moc`. For example, Arch Linux uses `QT_HOME / moc` and thus needs to modify the script[^1].
Similar handling in Meson[^2] though they also fall back on `QT_INSTALL_LIBEXECS`. Not sure if that is actually needed so left out for now.
[^1]: https://gitlab.archlinux.org/archlinux/packaging/packages/mame/-/blob/main/PKGBUILD?ref_type=heads#L58-59
[^2]: …
=> Allow querying for alternate Qt6 libexec directory

hash/hikara.xml, hash/super_tv_pc_cart.xml, src/devices/machine/generalplus_gpl16250soc.h, src/devices/machine/generalplus_gpl16250soc_video.cpp, src/devices/machine/generalplus_gpl16250soc_video.h, src/mame/mame.lst, src/mame/nintendo/nes_vt369_vtunknown.cpp, src/mame/sega/mdconsole.cpp, src/mame/sega/megadriv_rad.cpp, src/mame/skeleton/epoch_tv_globe.cpp, src/mame/tvgames/generalplus_gpl16250.h, src/mame/tvgames/generalplus_gpl16250_rom.cpp, src/mame/tvgames/generalplus_gpl32612.cpp, src/mame/tvgames/spg2xx.cpp, src/mame/tvgames/spg2xx_wiwi.cpp, src/mame/tvgames/st2302u_bbl_rom.cpp, src/mame/tvgames/st2302u_bbl_spi.cpp, src/mame/tvgames/xavix.cpp, src/mame/tvgames/xavix.h, src/mame/tvgames/xavix_2000.cpp, src/mame/tvgames/xavix_2000.h, src/mame/tvgames/xavix_2002.cpp, src/mame/tvgames/xavix_m.cpp, src/mame/tvgames/xavix_v.cpp
This is a squashed version of https://github.com/mamedev/mame/pull/12812
All-Star Thanksgiving Super Luxurious! Definitive Quiz Edition ~ Akasaka 5-Chome Experience Studio [David Haywood, TeamEurope, Peter Wilhelmsen]
Mini-Moni Stage! Dance Dapyon! (Japan) [David Haywood, TeamEurope, Peter Wilhelmsen]
Mini-Moni Stage! Dance Dapyon! Plus (Japan) [David Haywood, TeamEurope]
Gin-gin Boarders (Japan) [David Haywood, TeamEurope, Peter Wilhelmsen]
Mega Drive Play TV 2 (Japan) [David Haywood, TeamEurope]
Mega Drive Play TV 3 (Japan) [David Haywood, TeamEurope]
265-in-1 Handheld Game (SPG2xx based) [David Haywood, TeamEurope]
new Software List additions
hikara.xml
Hi-kara PIZZA-LA [David Haywood, TeamEurope] …
=> 7 new WORKING plug and Play Units, 17 NOT WORKING Plug and Play Units, 3 Software List additions, 8 promotions

src/devices/bus/a2bus/suprterminal.cpp
Accessing the C0B2, C0B4 and C0B6 locations is supposed to work whether you read or write to them, according to the Sup'R'Terminal manual.
=> bus/a2bus/suprterminal.cpp: allow mapping control via C0Bx reads

src/devices/cpu/m68000/m68k_in.lst, src/devices/cpu/m68000/m68kcpu.cpp, src/devices/cpu/m68000/m68kmmu.h, src/devices/cpu/m68000/m68kmusashi.h, src/devices/cpu/m68000/m68kops.cpp
renaming m_instruction_restart to m_can_instruction_restart to clearly distinguish from m_restart_instruction which indicates we are restarting an instruction.
=> m68000: member var m_instruction_restart and m_restart_instruction ambiguous

.github/workflows/bgfxshaders.yml, .github/workflows/ci-linux.yml, .github/workflows/ci-macos.yml, .github/workflows/ci-windows.yml, .github/workflows/docs.yml, .github/workflows/hash.yml, .github/workflows/language.yml
The default branch of checkout and upload-artifact was renamed to `main` years ago:
* https://github.com/actions/checkout/tree/master
* https://github.com/actions/upload-artifact/tree/master
upload-artifacts >v1 doesn't error by default if artifacts aren't found: https://github.com/actions/upload-artifact/?tab=readme-ov-file#customization-if-no-files-are-found
checkout >v1 doesn't fetch the entire commit history by default: https://github.com/actions/checkout?tab=readme-ov-file#checkout-v4
=> Upgrade checkout and upload-artifacts actions

scripts/src/bus.lua, src/devices/bus/qbus/bk_kmd.cpp, src/devices/bus/qbus/bk_kmd.h, src/devices/bus/qbus/qbus.cpp, src/devices/bus/qbus/qbus.h, src/devices/cpu/t11/t11ops.hxx, src/devices/machine/1801vp128.h, src/mame/ussr/bk.cpp, src/mame/ussr/bk.h, src/mame/ussr/bk_m.cpp
cpu/t11: VM1 does not use RMW bus transaction for MOV and MOVB insns (fixes writing to floppy)
=> ussr/bk: attach floppy

src/mame/cirsa/cirsa2080606.cpp, src/mame/cirsa/neptunp2.cpp, src/mame/mame.lst
La Máquina del Tiempo [jordigahan, Recreativas.org]
=> Add a Skeleton driver for Cirsa "2080606" slot machines hardware

hash/ibm5170_cdrom.xml, hash/mac_cdrom.xml
The "quake" entry was a bad dump, it lacked the game's audio tracks even though official shareware releases include them. The main "quake" entry has been replaced with the 1.06 full version, and correct shareware dumps are added in addition.
id Anthology had previously marked discs 3 and 4 as "nodump"; disc 3 of the id Anthology is identical to the standalone Quake 1.06 release (here as "quake"), and disc 4 is Macintosh software, so it is moved to mac_cdrom.xml with the proper hash.
I could, perhaps, include id Anthology disc 3, but since it's identical to "quake", I don't think that duplication is appropriate. It might be worthwhile putting note for the frontend pointing to where it is. I don't know the proper procedure for a disc that's duplicated in two releases.
=> Add correct and complete Quake dumps, and id Anthology 4

src/mame/apple/apple2e.cpp
The $c020 and $c028 softswitches as implemented do not follow what Apple implemented on the IIe, IIc and IIc Plus.  The entire $c02x region should respond, not just $c020 and $c028.  This PR fixes the implementation to match what the hardware does and also to match Apple's documentation (Apple IIc Technical Reference Manual 2nd Ed).
This PR was tested against the behavior of actual Apple IIc Plus hardware.  This PR will break unpatched versions of the game Choplifter, as these are also broken on real Apple IIc Plus hardware running ROM5.  The reason for this is that Choplifter sends its audio out to the cassette out (via $c020) at the same time it sends it to the speaker.  On the IIc and IIc Plus, this toggles the ROM bank being used.  When Choplifter then uses the ROM routine to read the …
=> apple/apple2e.cpp: Fix behavior of $c02x softswitches to match behavior of hardware

src/mame/misc/mjsenpu.cpp
- Use palette_device handlers for palette
- Use std::unique_ptr for VRAM variables
- Make screen update function into cliprect-stricted
- Correct VRAM data type
- Use logerror for logging features
- Improve function and ROM region namings
- Add notes for in-game text and voices
- Fix key matrix function, Improve namings for IO related variables
=> mjsenpu.cpp: Minor cleanups

src/devices/cpu/powerpc/ppccom.cpp
a) all constants were one digit too short
b) the payload was always expected to be 0 (which is just a special case qnan (Real Indefinite) though)
=> PPC: Fix qnan check

src/mame/matsushita/kn5000.cpp
With this we now get a good-looking "CPU data transmission" error screen during boot:
=> matsushita/kn5000.cpp: add 2 newly dumped data ROMs

src/devices/bus/heathzenith/h89/h89bus.cpp, src/devices/bus/heathzenith/h89/h_88_3.cpp, src/devices/bus/heathzenith/h89/h_88_5.cpp, src/devices/bus/heathzenith/h89/sigmasoft_sound.cpp, src/devices/bus/heathzenith/h89/we_pullup.cpp, src/mame/heathzenith/h89.cpp
Connect the write-enable pull-up used for floppy RAM in the new h89bus architecture.
- add handler in h89.cpp
- rename flag from m_floppy_ram_wp to m_floppy_ram_we to reflect slot signal name
- complete file comments for bus/heathzenith/h89/we_pullup.cpp
Some minor cleanup of the new h89bus code
- fix write select signal mask for p506
- disable debug logging
- update some comments
=> heathzenith/h89.cpp: Connect write-enable pullup on new h89bus

src/devices/bus/epson_qx/multifont.cpp
Some time earlier this year the font data for the QX-10 multifont card was dumped and can currently be found on archive.org.
This updates the font roms from NO_DUMP to include the checksums for these dumps. I have tried the roms with the emulator multifont card option and everything appears to work correctly without issue.
=> qx10: add checksums for multifont rom dumps

src/devices/video/upd7220.cpp
- fix `pc9801:mightyhd` text screen display
=> video/upd7220.cpp: command reset shouldn't touch RA parameters

src/lib/formats/ap2_dsk.cpp
In this case, `levels` is empty, and `generate_track_from_levels` immediately crashes with a division by zero. To fix this, just leave the track empty instead.
=> ap2_dsk.cpp: don't crash when loading a NIB file with an all-zero track

src/mame/tecmo/tehkanwc.cpp
Small edit to:
- confirm that the vblank time is correct (comment removed)
- correct the refresh rate (derived from my extracted schematics)
- make the palette a _ram()_ so it matches the PCB (again, see schematics). It also makes it possible to dump it on MAME debugger (which is convenient for my workflow, please allow it) 
video timing:
[schematics](https://github.com/user-attachments/files/17611390/tehkanwch.pdf)  (missing a few signals, work in progress)
=> tehkanwc: correct refresh rate

src/devices/video/upd7220.cpp
When the upd7220 is calculating the next EAD for read or write operation it should look at the GD bit set with the FIGS command and when it is set during mixed mode half the pitch value. This was already being done for the graphics figure drawing functions, but the rdat,wdat and dma read/write functions were using the unmodified pitch. 
This causes a noticeable problem in valdocs on the QX-10 as it uses wdat to draw its block cursor, but the pitch value is set to 80 characters per line, but when drawing graphics needs to be halved to reach the correct next effective address. In valdocs this would show up as the cursor being twice as tall with a gap between every other line.
Writing some test code on my QX-10 that sets mixed mode with a pitch of 80 and then draws a block cursor with and …
=> upd7220: Fix pitch calculation in rdat/wdat routines

src/mame/epson/qx10.cpp
I noticed when testing #12943 that the zoom diag tests were broken on the QX10, bisecting showed that it was these two commits that broke things.
Revert "epson/qx10.cpp: rectify previous commit"
This reverts commit 35f1ec96be9e097247f13680acb4f62d6e63e538.
Revert "epson/qx10.cpp: use copyrozbitmap for (external to 7220) zoom handling"
This reverts commit a266a60699b4fe34fe14a8d11f2415ee4b48ef46.
=> epson/qx10.cpp: Revert commits that broke zoom handling on the QX10

src/mame/pacman/pacman.cpp
Still missing one PROM, that was bad on the dumped PCB
=> pacman/pacman.cpp Dumped PROMs for "Pengo (Marti Colls bootleg on Pac-Man hardware, set 1)" [Arcadedealer aka Edgar Solé aka Dios, Recreativas.org]

src/mame/mame.lst, src/mame/misc/compucranes.cpp
OM Vending Toy Shop
* No credits for the new set (anonymous).
* Fix ROM sizes for 'mastcrane' and 'mastcrane'.
* Fix year for 'octopussy'.
* Fix hardware notes: All SEPROMs are 24C16, CPU types, etc.
* Fix xtal value (it's 12 MHz, not 6).
=> misc/compucranes.cpp: Fix ROM sizes, year, comments, etc. and add a new game

src/devices/cpu/mips/mips3.cpp, src/devices/cpu/mips/mips3dsm.cpp
This adds support for MAD/MADU in the interpreter, as well as fixing the implementation and disassembly of the MUL instruction. All are specific to the IDT R4650.
=> MIPS3 fixes for IDT-specific instructions

hash/gba.xml, hash/nes.xml
These titles were retrieved out of the Way Back Machine; some versions were not archived by it, it is unknown if they will surface again.
New working software list items (gba.xml)
LOCKJAW: The Reference
LOCKJAW: The Overdose
Tetanus on Drugs (Milestone 3)
Tetanus on Drugs (Preview Release 1)
New working software list items (nes.xml)
LJ65 (0.41, NTSC)
LJ65 (0.41, PAL)
Tetrimino (0.30, NTSC)
Tetrimino (0.30, PAL)
Tetrimino (0.27, NTSC)
Tetrimino (0.27, PAL)
Tetrimino (0.2)
Tetrimino (0.1)
=> hash/gba.xml, hash/nes.xml: add Pin Eight's Lockjaw games

hash/nes.xml
I had misspelled the game's (old) name and copy+pasted the misspelling all the way through. Oops :)
=> hash/nes: fix name of Tetramino (LJ65 prototypes)

hash/oric1_cass.xml
Removed `region` info tag since there isn't any notice or restriction to a particular region.
Aerial [Inufuto]
AntiAir [Inufuto]
Ascend [Inufuto]
Battlot [Inufuto]
Bootskell [Inufuto]
Cacorm [Inufuto]
Cavit [Inufuto]
Cracky [Inufuto]
El Prisionero [Commodore Plus]
Guntus [Inufuto]
Hopman [Inufuto]
I Sentieri di Galdeon (Italian) [Defence Force]
Impetus [Inufuto]
Killer Caverns [The Oric Site]
Les Chemins de Galdeon (French) [Defence Force]
Lift [Inufuto]
Los Camiños de Galdeon (Spanish) [Defence Force]
Mazy [Inufuto]
Neuras [Inufuto]
Osotos [Inufuto]
Pulsoids [Defence Force]
Rodmän (demo) [The Future Was 8 Bit]
Ruptus [Inufuto]
The Paths of Galdeon (English) [Defence Force]
Torreoscura [Commodore Plus]
Yewdow …
=> oric1_cass.xml: Added 26 working items

src/devices/bus/a2bus/a2diskiing.cpp, src/lib/formats/all.cpp, src/lib/formats/ap2_dsk.cpp, src/lib/formats/ap2_dsk.h
This is the equivalent of DSK used for 13-sector disks.
While `diskiing` cannot directly boot from 13-sector disks, you can still access such disks with it (for example, using the BOOT13 and MUFFIN programs from the DOS master disk), so list the format as supported by both `diskiing13` and `diskiing`.
=> ap2_dsk.cpp: add read-only support for the D13 format

src/mame/layout/cluedo.lay
Corrects the license of the cluedo.lay file from BSD-3 to CC0-1.0 (from https://github.com/mamedev/mame/pull/12879)
=> Correct cluedo.lay license from BSD-3 to CC0-1.0

src/mame/sega/segas32.cpp
The game requires the same mono style banking which is used by Stadium Cross, with thanks to mahoneyt944 who spotted the issues
=> Fix missing and or incorrect sounds with a player 2 game in Title Fight

src/mame/tvgames/trkfldch.cpp
the workings of the audio hardware for this SoC type are a bit of a mystery
I've at least isolated the 'play sample from ROM' call in abl4play which could be a vital starting point, so is worth making a note of in the driver for future reference
=> Update trkfldch.cpp - add notes about where sample playback request is in abl4play

src/mame/heathzenith/h89.cpp
Add 2 new BIOS options for H89 from SigmaSoft and Systems. Two versions of SigmaROM.
=> heathzenith/h89.cpp: Add SigmaROM BIOS

src/mame/irem/m72.cpp, src/mame/irem/m72.h, src/mame/irem/m72_v.cpp
- Fix typename values for boolean flags
- Fix naming
- Fix spacings
- Add notes
=> irem/m72.cpp: Split driver state for reduce optional finders, Updates:

scripts/src/cpu.lua, src/devices/cpu/z80/t6a84.cpp, src/devices/cpu/z80/t6a84.h, src/devices/cpu/z80/z80.cpp, src/devices/cpu/z80/z80.h, src/devices/cpu/z80/z80.lst, src/mame/layout/ferie.lay, src/mame/mame.lst, src/mame/sega/sega_ferie.cpp
Basic functionality is implemented. I haven't tried most features of this system, which is why it's marked MACHINE_NOT_WORKING.
Some changes done in Z80 base class were required to support T6A84's multiple address spaces / memory pages:
* Stack reads and writes are handled by dedicated virtual functions. In this case, they are overridden to use a distinct address space;
* For interrupts, I considered using daisy-chain, but this would require even more changes to the base class. Additionally to fetching interrupt vectors, we need to execute interrupt routines in a distinct page. This seems easier to support by adding a new "return from interrupt" callback to handle switching mapped pages;
=> sega/sega_ferie.cpp: Add new not working system

src/mame/jaleco/bnstars.cpp, src/mame/jaleco/ms32.cpp, src/mame/jaleco/ms32.h, src/mame/jaleco/ms32_v.cpp
- Use generic gfx decode layout
- Fix spacing
- Reduce runtime tag usage, literal tag usages
- Fix naming
=> jaleco/ms32.cpp, jaleco/bnstars.cpp: Minor cleanups:

src/mame/kaneko/kaneko_spr.cpp, src/mame/kaneko/kaneko_spr.h, src/mame/kaneko/kaneko_tmap.cpp, src/mame/kaneko/kaneko_tmap.h
kaneko/kaneko_spr.cpp: Fix typename for boolean flags
=> kaneko/kaneko_spr.cpp, kaneko/kaneko_tmap.cpp: Use generic gfx layout, Reduce unnecessary finder

src/devices/cpu/lh5801/5801dasm.cpp
The calculations for RelP and RelM include adding the pc which is incorrect I think.  Removing the "pc+" seems to fix the calculation.
=> cpu/lh5801: Don't add PC value twice when disassembling relative addressing modes

src/mame/fuuki/fuukifg2.cpp, src/mame/fuuki/fuukifg3.cpp, src/mame/fuuki/fuukispr.cpp, src/mame/fuuki/fuukispr.h, src/mame/fuuki/fuukitmap.cpp, src/mame/fuuki/fuukitmap.h
fuuki/fuukispr.cpp: Use generic gfx decode layout, Improve naming (it just emulates sprite hardware)
fuuki/fuukifg2.cpp: Fix comments
fuuki/fuukifg3.cpp: Reduce duplicates
=> fuuki/*.cpp: Split tilemap features from fuuki hardware to device

src/mame/philips/cdicdic.cpp
Fixes:
https://mametesters.org/view.php?id=8833
I also thought it would fix this one but my assumption was wrong:
https://mametesters.org/view.php?id=8955
Further tests might be needed but I'm not a big fan of Hotel Mario and therefore unable to complete this game as it is quite repetitive.
=> cdicdic: Fix restarting audio_map after stopping it

src/mame/toaplan/mjsister.cpp
- Reduce literal tag usages, Runtime tag lookups
- Fix typename value for boolean flags
- Fix initializations, save states
- Fix namings
=> toaplan/mjsister.cpp: Minor cleanups

src/mame/jaleco/tetrisp2.cpp, src/mame/jaleco/tetrisp2.h, src/mame/jaleco/tetrisp2_v.cpp
- Split state via configurations
- Use machine_start(), video_start() overrides for video initialization
- Reduce runtime tag lookups, literal tag usages
- Fix typename value consistency
- Use generic gfx decode layout
- Fix naming
=> tetrisp2.cpp: Use memory_bank finder for sound bankswitching, Cleanups:

src/mame/mame.lst, src/mame/roland/roland_mt32.cpp
This is basically a MT-32 with a bunch of extra stuff, including a sequencer and a Quick Disk drive.
The main firmware likely will work on regular MT-32 too since it's labeled similar to those dumps, but a different ver.
There's an additional rom on the PR Board
Dump has been sent to DU
Pics: https://photos.app.goo.gl/FBDHrSYicfop3qVs5
Credit: "buffi"
=> Add a skeleton for Roland MT-100

src/devices/cpu/hcd62121/hcd62121.cpp, src/devices/cpu/hcd62121/hcd62121.h, src/devices/cpu/hcd62121/hcd62121d.cpp, src/mame/casio/pickytlk.cpp, src/mame/mame.lst
* Implement timer state register updates;
* Implement monocolor model tablet inputs;
* Fix invalid copy extension on instruction 0xC5 `movw (lar),i8`;
New systems added as NOT WORKING
Picky Talk - Super Denshi Techou [QUFB]
Disney Characters - Tegaki Electronic Note [QUFB]
Color Picky Talk - Super Denshi Techou [QUFB]
Super Picky Talk - Access Pet [QUFB]
Plet's (MK-300) [QUFB]
Plet's (MK-350) [QUFB]
=> cpu/hcd62121,casio/pickytlk.cpp: Add support for more Picky Talk models

src/frontend/mame/ui/selmenu.cpp
The scale ratio can be greater than 1, especially on a big 4K screen.  Instead of getting a tiny icon, scale it up
=> scale icons up and down

src/devices/bus/a2gameio/joyport.cpp
This changes the description of "Sirius JoyPort" to read "Sirius JoyPort with Atari joysticks" instead.
The Sirius JoyPort supports different types of peripherals to be connected to it.
=> a2gameio: Updated Sirius JoyPort description to mention Atari joysticks being connected to it

src/mame/trs/gime.cpp, src/mame/trs/gime.h
The legacy GIME mode lines per row calculation is very different from the MC6847. Also fix a small border color issue when compared with real hardware.
=> trs/gime.cpp: fix some legacy video modes

src/mame/toaplan/dt7.cpp, src/mame/toaplan/toaplan_v25_tables.h
=> dt7.cpp - improve text layer handling (adds rowselect, fixes course select screen) [David Haywood]

src/lib/formats/ap2_dsk.cpp, src/lib/formats/ap2_dsk.h
* convert `#define` to `constexpr`;
* remove unused constants;
* replace magic numbers with constants where appropriate.
=> ap2_dsk.cpp/h: clean up constants

src/lib/formats/ap2_dsk.cpp
I accidentally broke this in 47d8c69b, where I forgot to account for the "oddball" images from the software list. AFAICS, bardstl3 is the only software to be broken, because its images are _shorter_ than they're supposed to be.
In addition, disk 3 of this image has a different size that's not listed in `identify()`, so it couldn't even be loaded before that commit. Fix that too.
=> ap2_dsk.cpp: fix loading bardstl3

src/mame/gaelco/gaelco3d.cpp, src/mame/gaelco/gaelco3d.h
This PR adds the Start Lamp output for Radikal Bikers, now it can be used on external devices to simulate the original European Gaelco cabinet version.
=> radikalb: add output start lamp to Gaelco Radikal Bikers

hash/ibm5170.xml, hash/ibm5170_cdrom.xml, hash/ibm5170_hdd.xml
MAME had a completely broken warez version of Windows NT 3.1, that was replaced with a known-good unmodified copy. Language variants of Windows NT 3.1 were also added (I don't have the non-English copies of future versions, can't do those at this time). Advanced Server is added to the list.
Windows NT 3.5 was added new.
Windows NT 3.51's CD-ROM image was not the original copy, and likewise updated to a known-good unmodified copy. Server was added to the list.
Windows NT 4.0 was added new, all known-good copies and editions of such.
=> Windows NT 3.x/4.0/2000 pristine images

src/devices/cpu/e132xs/e132xsdrc_ops.hxx
MAME Testers bugs fixed
- 08942: [Gameplay] (misc/vamphalf.cpp) coolmini: Minigames don't work properly/softlock
-e132xs: Sign-extend the divisor in DIVS instructions. [Ryan Holtz]
=> Fixed MT#08942 (some broken minigames in coolmini)

hash/a2600.xml, hash/megadriv.xml
I had 1.0 on my hard disk, never knew it was updated until now.  Found the final release easily, there's a "1.12" referenced in a YouTube video between 1.0 and final, but I was unable to find a copy.
Archive.org has the Russian translation hacks, too.
New working software list items (megadriv.xml)
----------------------------------------------
Fix-it Felix Jr.
Fix-it Felix Jr. (v1.0) [chungy]
Wreck It Ralph (Russian translation bootleg) [unknown]
Wreck It Ralph (Russian translation bootleg, alt) [unknown]
=> hash/megadriv.xml: add Fix-It Felix Jr.

src/devices/cpu/upd177x/upd177xd.cpp, src/devices/cpu/upd177x/upd177xd.h
- Fix disassembly of MVI in the 0x4000 range.
- Rename mdi/mdo to md1/md0.
- Add STEP_OVER/STEP_OUT to call and ret instructions.
=> cpu/upd177x/upd177xd.cpp: Some small fixes

hash/ibm5170.xml, hash/ibm5170_cdrom.xml
Cleaning up the NT 3.1 entries, the existing floppy set is actually build 528, so simply rename that.  Place the original (build 511) floppy set as winnt31o_35.
The floppy disk connected to the cdrom set winnt31o2 actually belongs to winnt31o (build 528 instead of 511), and the build 511 3.5" install floppy is now marked as “nodump.”  Users can still start the installation from DOS and use the CD-ROM version, but a direct boot from floppy is only an option for 5.25" drives until a dump is made.
The old floppy disk connected to cdrom winnt31/winnt31o has been replaced by what was in winnt31o2.  The only difference is that this disk has unused sectors filled out with f6 bytes, the same as what happens from Microsoft's format utilities of the day.
=> hash/ibm5170{,_cdrom}: Original Windows NT 3.1 floppy distribution

hash/a2600.xml
Honestly, not sure how that happened. I usually use rhash to generate the rom lines. :)
=> hash/a2600: fix file name of Fix It Felix Sr NTSC

hash/leapfrog_leappad_cart.xml
Oyako Eigo Step 1 gatsu gou - Doubutsuen ni Ikou! (Japan) [David Haywood, TeamEurope, Fujix]
Oyako Eigo Jump 5 gatsu gou - Okashi no Kuni no Daibouken (Japan) [David Haywood, TeamEurope, Fujix]
Oyako Eigo Jump 9 gatsu gou - Monjaa Gou de Tankenja! (Japan) [David Haywood, TeamEurope, Fujix]
Oyako Eigo Jump 1 gatsu gou - Shougakkou Taiken Report (Japan) [David Haywood, TeamEurope, Fujix]
Korasho Land 1 Gakkou e Ikou! (Japan) [David Haywood, TeamEurope, Fujix]
Korasho Land 4 Machino Naka wo Tanken! (Japan) [David Haywood, TeamEurope, Fujix]
Korasho Land 2 Tanoshii Ichinichi (Japan) [David Haywood, TeamEurope, Fujix]
Korasho Land 3 Tanjoubi Omedetou (Japan) [David Haywood, TeamEurope, Fujix]
Korasho Land 5 …
=> leapfrog_leappad_cart.xml: added 16 sets [David Haywood, TeamEurope, Fujix]

src/mame/apple/apple2e.cpp, src/mame/mame.lst
This adds German and Swedish Apple IIe/IIc variants.
The enhanced IIe Swedish character ROM has not been found. It is based off of the unenhanced IIe Swedish character ROM and is marked as bad.
- Apple //e (Germany)
- Apple //e (enhanced, Germany)
- Apple //e (Platinum, Germany)
- Apple //c (Germany)
- Apple //c (UniDisk 3.5, Germany)
- Apple //c (Original Memory Expansion, Germany)
- Apple //c (rev 4, Germany)
- Apple //e (Sweden)
- Apple //e (enhanced, Sweden)
- Apple //e (Platinum, Sweden)
- Apple //c (Sweden)
- Apple //c (UniDisk 3.5, Sweden)
- Apple //c (Original Memory Expansion, Sweden)
- Apple //c (rev 4, Sweden)
=> apple2e: Add German and Swedish Apple IIe/IIc variants

src/mame/namco/mappy.cpp, src/mame/namco/mappy.h, src/mame/namco/mappy_v.cpp
- Fix 15XX sound clock related to XTAL on PCB
- Simplify gfx layout
- Fix naming
- Fix typo
- Fix filename
=> namco/mappy.cpp: Split phozon state for reduce optional finders, Cleanups:

src/devices/machine/ncr5385.cpp
- need to clear bits before we regenerate them
=> ncr5385 aux_status generation

3rdparty/lsqlite3/lsqlite3.c, src/mame/moog/source.cpp, src/mame/nec/pc88va.cpp
Two are for implicit casts (which the visual studio build elevates to Errors) and one is for an unused variable.
Since these break compilation from a fresh build in default conditions, and the project is set to elevate warnings to errors, these likely should be fixed.
=> Fix 2 Visual Studio Warnings

hash/ibm5170_cdrom.xml
All but two of the Sonic CD entries on redump.org are represented here.  The two left out are part of compilations and do not belong as standalone releases.
This game doesn’t really run well on ct486, but should be fine on pcipc.
New working software list items (ibm5170_cdrom.xml)
---------------------------------------------------
Sonic CD (USA) [redump.org]
Sonic CD (USA, 1997 release) [redump.org]
Sonic CD (USA, 1996 release) [redump.org]
Sonic CD (USA, Pentium Processor Edition) [redump.org] Sonic CD (USA, Pentium Processor Edition alt) [redump.org] Sonic CD (USA, Packard Bell) [redump.org]
Sonic CD (Europe) [redump.org]
Sonic CD (China) [redump.org]
=> hash/ibm5170_cdrom: Add Sonic CD

scripts/src/bus.lua, src/devices/bus/heathzenith/h89/cards.cpp, src/devices/bus/heathzenith/h89/z_89_11.cpp, src/devices/bus/heathzenith/h89/z_89_11.h
When this new card is selected, the CP/M configur.com program properly detects it.
=> bus/heathzenith/h89: Add Z-89-11 Multi-Mode Interface Card option

src/devices/cpu/drcbec.cpp, src/devices/cpu/drcbex64.cpp, src/devices/cpu/drcbex86.cpp, src/devices/cpu/drcumlsh.h, src/devices/cpu/uml.cpp, src/devices/cpu/uml.h
- Fixed an issue with x64 LOAD not clearing the rest of the register in rare cases
- Fixed x86 LOADS not sign extending properly for 64-bit loads
- Fixed x86 data widths for FLOAD/FSTORE to support doubles
- Bandaid fix for clearing x86 upper half of register when writing to a 32-bit ireg. This won't cover all cases but should cover a lot of the common usages (I0-I3)
=> DRC backend fixes pt 2

src/mame/atari/atarig1.cpp, src/mame/atari/atarig1.h, src/mame/atari/atarig1_v.cpp, src/mame/atari/atarig42.cpp, src/mame/atari/atarig42.h, src/mame/atari/atarig42_v.cpp, src/mame/atari/atarigt.cpp, src/mame/atari/atarigt.h, src/mame/atari/atarigt_v.cpp, src/mame/atari/atarigx2.cpp, src/mame/atari/atarigx2.h, src/mame/atari/atarigx2_v.cpp, src/mame/atari/atarirle.cpp, src/mame/atari/atarirle.h
- Fix save states
- Fix naming
- Fix spacing
atari/atarigx2.cpp:
=> atari/atarig1.cpp, atarig42.cpp, atarigt.cpp, atarigx2.cpp, atarirle.cpp: Cleanups:

src/osd/interface/inputcode.h
This seems to capture the spirit of what the asserts were doing without tripping the enum range warnings.
=> osd/interface/inputcode.h: Fix warnings in debug build

src/mame/konami/nemesis.cpp, src/mame/konami/nemesis.h, src/mame/konami/nemesis_v.cpp
- Reorder variables and object finders in header file
- Reduce runtime tag lookups, literal tag usages
- Fix namings
- Fix spacings
- Fix save states
- Add notes
=> konami/nemesis.cpp: Split driver classes for reduce optional finders, Cleanups:

scripts/src/3rdparty.lua
The builder was failing in compiling the Lzma source code due to the global compiler flag `-Werror -Wstrict-prototype` triggering errors when compiling code specific to arm64 architecture.
This PR sets the  `-Wno-error=strict-prototypes` flag when building the Lzma library
=> 3rdparty.lua: Fix compilation of Lzma for arm64 architecture

src/mame/namco/baraduke.cpp, src/mame/namco/namco_cus4xtmap.cpp, src/mame/namco/namco_cus4xtmap.h, src/mame/namco/namcos86.cpp, src/mame/namco/namcos86.h, src/mame/namco/namcos86_v.cpp
namco/baraduke.cpp:
- Use video/resnet.h for palette initialization
- Simplify gfx decode layout
- Fix address map order
namco/namcos86.cpp:
- Use video/resnet.h for palette initialization
- Use set_pen_indirect and set_indirect_color for indirect color palette beheviour
- Simplify gfx decode layout
- Reduce unnecessary pointer
- Fix type value for some variables
- Fix address map order
- Fix spacing
- Fix naming
=> namco/namco_cus4xtmap.cpp: Device-fied CUS42 + CUS43 tilemap hardware, Cleanups:

src/mame/neogeo/midas.cpp, src/mame/neogeo/neogeo.cpp, src/mame/neogeo/neogeo.h, src/mame/neogeo/neogeo_spr.cpp, src/mame/neogeo/neogeo_spr.h, src/mame/neogeo/neogeo_v.cpp, src/mame/neogeo/neogeocd.cpp, src/mame/neogeo/neopcb.cpp
- neogeo/midas.cpp:
- Split hammer to derivated class
- Fix namings
- neogeo/neogeo_spr.cpp:
- Use enum for fix layer bankswitch type
- Reduce preprocessor macros
- Move various functions and variables into protected: section
- Fix filename comment
- Fix naming
- neogeo/neogeo.cpp:
- neogeo/neogeocd.cpp:
- Fix code style consistency, Use lowercase hexadecimal digits and variable names
- Move various variables and functions into private: section
- Reduce preprocessor macros
- Fix save states
- neogeo/neopcb.cpp:
- Reduce literal …
=> Various neogeo related driver cleanups:

src/devices/bus/heathzenith/h19/tlb.cpp, src/devices/bus/heathzenith/h19/tlb.h, src/mame/heathzenith/h89.cpp
tlb.cpp: 
- Add machine configuration option to install/remove the optional page 2 memory for the UltraROM.
h89.cpp:
- Use class variable instead of tag for memory_view region routine.
=> heathzenith/h19/tlb.cpp: Make the page 2 memory option configurable for UltraROM

src/mame/nmk/quizdna.cpp
- Use memory_view for ROM/RAM bankswitching
- use set_format for palette format
- Fix typename for boolean flag
- Use generic gfx layout for gfx decode
=> nmk/quizdna.cpp: Cleanups:

src/devices/imagedev/flopdrv.cpp, src/devices/imagedev/flopdrv.h
Seems like the list of machines still using legacy floppy drives has shrinked rapidly..
=> imagedev/flopdrv.cpp: Remove code supporting functionality that's no longer used

src/mame/moog/memorymoog.cpp, src/mame/moog/source.cpp
Just a minor style change. Makes my Moog drivers stylistically consistent with a large number of existing drivers. Will follow this pattern in future drivers too.
=> mame/moog/*.cpp: Using the more prevalent style for * and & placement.

src/mame/koei/pasogo.cpp
Reading the datasheet at https://bitsavers.org/components/amphus_vadem/VG230/VG230_General_Description.pdf and register 79H is the RTC mode, not RTC status (which is on 7AH), and writing to 78H shouldn't affect the RTC's stored days
=> pasogo.cpp: Fix copy/paste errors

src/mame/apple/macadb.cpp
This PR adds support for the second button of an ADB mouse
Testing:
Apple IIGS emulation with MAME 0.273 has the following behavior with regards to the second mouse button:
- The "Shift-Command-Clear" combination enables the ADB mouse keypad.  With a ROM 01, this sequence seems to only work if System Software is running.  With a ROM 03, it also works if ProDOS is running (probably any OS).
- The "Clear" disables the ADB mouse keypad.
- The keypad 5 key emulates the first mouse button.  This works with both apple2gs (ROM 03) and apple2gsr1 (ROM 01)
- The keypad - key emulates the second mouse button.  This only works with the apple2gs (ROM 03)
- There is no means to generate the second mouse button press using the MAME emulated mouse.
Application support (note, with MAME 0.273, the tests …
=> macadb: add support for second button of an ADB mouse

src/mame/roland/roland_d70.cpp
* Chose more accurate colors for the LCD. 
* Declared more versions of the program ROMs.
* Split the ROMs to match actual chips and renamed them to indicate their corresponding IC references (IC4 for the even ROMs and IC9 for the odd ones).
Before:
After:
(@giulioz)
=> Improvements to Roland D-70

src/mame/gaelco/gaelco3d.cpp, src/mame/gaelco/gaelco3d.h, src/mame/gaelco/gaelco3d_v.cpp
- Use logmacro.h for logging
- Fix namings
- Fix spacing
- Fix typo
- Remove unused variable
=> gaelco/gaelco3d.cpp: Cleanups

src/mame/gaelco/gaelco.cpp, src/mame/gaelco/gaelco.h, src/mame/gaelco/gaelco_v.cpp
- Split driver class for reduce optional finders
- Fix namings
=> gaelco/gaelco.cpp: Cleanups

src/mame/philips/minitel_2_rpic.cpp
I've tested the command line given at the top of the `minitel_2_rpic.cpp` file (`-modem null_modem -bitb socket.127.0.0.1:20000`) and it didn't work (transferred data was corrupted), because the correct serial parameters are set for `terminal`. This commit makes them apply to `null_modem` instead, so that the documented command line actually works.
While at it, I've also changed the parameters for the second serial port (`periinfo`) to match the Minitel's defaults and verified that it actually works, despite the comment at the top of the file stating the opposite.
These are all the test command lines I've successfully validated, to test that the two Minitel serial ports (`modem` and `periinfo`) work, both in isolation and together. I've used [minipavi.fr](http://minipavi.fr) as the test …
=> minitel2: fix modem and periinfo default configurations

src/mame/philips/minitel_2_rpic.cpp
Previously, some distinct levels were mapped to the same color, which made them indistinguishable.
The progression of the gray levels is documented both in the Videotex documentation (STUM1B) and in the TS9347 datasheet, by mapping colors to grayscale-equivalent levels.
From STUM1B (page 32):
From the TS9347 datasheet (pages 10 and 19):
Visually tuned with a test pattern ([colors.vdt.zip](https://github.com/user-attachments/files/18339197/colors.vdt.zip)) using a real Minitel as a reference:
Note: The number after # is the index in MAME's minitel2 palette
EDIT: For comparison, with the old palette the above test pattern would have been rendered as:
Important: if you test the new palette, in order to actually see the background colors generated by the test pattern, you currently have to …
=> minitel2: tune palette to differentiate all colors

src/devices/sound/dac76.h
AM6070 is the DAC being used in the DMX.
**Questions**
1) Is documentation of the component compatibility enough? Or is the preference to add a `class am6070_device` and `DECLARE_DEVICE_TYPE(AM6070, am6070_device)` ?
2) @startaq, just out of curiosity, is the `* 8` below done to improve or avoid aliasing? Or is there some other reason?
https://github.com/mamedev/mame/blob/82466846f81f93244ee2188c06bae8f45a2e6dd0/src/devices/sound/dac76.cpp#L51-L54
=> sound/dac76.h: Documenting equivalence to AM6070. Fixing pin locations.

src/mame/sega/segas32_v.cpp
It seems that zooming requires more resolution but uses 9 bit otherwise.
This should fix the missing background for harddunk in attract mode, while also working with radr map selection, alien3 map between stages and so on. Has not been verified to real hardware but it seems to test correctly with all games. Let me know if there's a specific transition / case you would like tested.
=> Segas32 - Resolution change when zooming

scripts/src/bus.lua, src/devices/bus/hp_dio/hp98628_9.cpp, src/devices/bus/hp_dio/hp98628_9.h, src/devices/bus/hp_dio/hp_dio.cpp, src/devices/bus/hp_dio/hp_dio.h, src/devices/machine/z80sio.cpp, src/devices/machine/z80sio.h, src/mame/hp/hp98x6.cpp
Hi,
this PR adds the support for HP98628 & HP98629 expansion cards on HP98x6 systems.
A few notes:
* In theory, all existing 16-bit DIO cards should work on 98x6 machines. I had no time
to test them, though. That's the reason why for the time being I'm keeping the two
cards I developed on a separate set of optional cards (the one in dio16_hp98x6_cards
function). Once the other 16-bit cards are tested on hp98x6, the two lists will
be merged.
* I realized that the 98603a and 98603b cards that @svenschnelle developed have the same
function of two optional ROMs I put in the ROM software list. I don't know what should
be the preferred way to add optional ROMs, either as a plug-in card or as a ROM in
a sw list.
* 98629 card was used to interface to a kind of LAN that HP called SRM (Shared …
=> HP98x6: added HP98628 & HP98629 expansion cards

src/mame/barcrest/mpu3.cpp
100hz signal to the pia was previously done with m_pia3->cb1_w(~m_signal_50hz);
As m_signal_50hz was an int with a value of 0 or 1 this meant cb1_w() was always being called with a non-zero value.
In addition to the above, it's supposed to be a 100hz signal, not 50hz.
This fixes software which boots and then locks with TURN-ON-DELAY 30 on the display.
Also, fixes software which use the WAI instruction and then lock.
=> barcrest\mpu3.cpp: Correct 100hz signal to pia6821 ic3

src/mame/oberheim/dmx.cpp
- Refactored the gain and decay logic into its own VCA device, to make it easy to add the anti-aliasing filters.
- Added the anti-aliasing / reconstruction filters.
- Optimization: Gain and decay-RC-constant variations computed at initialization.
- Bugfix: voices with pitch control have 1 instead of 3 decay variations. Fixes decay speed in some TOM variations.
=> oberheim/dmx.cpp: AA filters, VCA as a device, optimizations, bug fix.

src/devices/cpu/drcbearm64.cpp, src/devices/cpu/drcbec.cpp, src/devices/cpu/drcbex64.cpp, src/devices/cpu/drcbex86.cpp
Discussed this with cuavas already.
The original intention (based on the initial commits of the DRC by Aaron) was for the shift/rotate functions to calculate flags even if the shift was 0, but 13-ish years ago it got refactored in a way that made some of the opcodes calculate the flags and some of them not calculate the flags if the shift was 0.
=> DRC: Calculate flags for shifts/rotates with a shift of 0

src/mame/misc/changyu.cpp
at the driver note
marked 9101
1991 january?
in the maganize 317 of Sep. 91 Replay
fun nine look similar to 999.
96c 97c 98c are just voice rom cvsd.
=> misc/changyu.cpp: change year 19?? to 1991 for changyu2, pinpoint voice roms

src/mame/alesis/midiverb.cpp, src/mame/layout/alesis_midiverb.lay, src/mame/mame.lst
Driver for MIDIverb, including interactive layout. No audio emulation yet. The UI portion of the device is fully emulated, though there isn't much to it.
=> alesis/midiverb.cpp: Adding non-working driver for midiverb.

src/devices/bus/heathzenith/h89/h89bus.cpp, src/mame/heathzenith/h89.cpp
For the existing `h89bus_device::io_dispatch_r()` routine, a check of the offset was occurring that made the check in `h89_mms_state::port_f2_mms_r` redundant. Between the two checks, having it in h89bus_device simplified the logic. 
@rb6502  let me know if you agree with this approach, or if you think the check should removed from `h89bus_device::io_dispatch_r()`.
=> heathzenith/h89.cpp: Update gpp handling for MMS FDC

src/devices/video/ef9345.cpp
With this change, the minitel2 can correctly display its status row at the top of the screen.
Screenshots before:
Screenshots after:
Corresponding picture from a real Minitel 2: http://hxc2001.free.fr/minitel/minitel2.jpg (from @jfdelnero's website).
The ef9345.cpp file provides support for both the EF9345 and the TS9347 video chips. Compared to the EF9345, the TS9347 has a slightly different logic for the "service row" (i.e. a text line that is conceptually separate from the main contents of the screen). In particular:
- the EF9345 lets one select the memory location for fetching data for the service row, but not where to display it (it's always displayed at the top of the screen)
- the TS9347 lets one select where to display (either at the top or at the bottom), but not where to fetch …
=> ef9345: implement service row for the TS9347 variant

hash/juku.xml
Add JUKU E5104 system disks currently available:
* Three Baltiyets system disks from 1988 with EKDOS 2.29 (maybe partly updated later)
- JUKU-1 / ДГШ5.106.105
- DIAGNOSTICS 1.0, UTY 0.2/0.1, NETOS 2.0/0.1, SED 6.0/2.1, B80 5.21, BASCOM, L80 3.44, SID, RDEM 1.1, CM6329, FX800, COMPU
- JUKU-2 / ДГШ5.106.105-01
- LINKMT 5.5, UTY 0.2/0.1
- JUKU-3 / ДГШ5.106.105-02
- DBASE 2.4, MULTIPLAN 1.05, GTR 2.5B, SNAKE 1.3, UTY 0.2/0.1
* EKTA additional utilities disk 4 from December 1989 with EKDOS 2.30
- Updated Epson/Compu printer drivers
- A set of various "exciting utilities"
=> hash/juku: Add E5104 system disks & additional utils disk

src/mame/edevices/edevices.cpp, src/mame/edevices/edevices.h, src/mame/edevices/mwarr.cpp, src/mame/edevices/stlforce.cpp
- Fix some typename value
edevices/mwarr.cpp: Cleanups
- Fix naming
- Fix spacing
- Use generic gfx decode layouts, Cleanup gfx layouts
- Remove unneeded trampoline
edevices/stlforce.cpp: Cleanups
- Use generic gfx decode layouts, Cleanup gfx layouts
- Remove unused function
- Fix spacing
=> edevices/edevices.cpp: Use device_gfx_interface for gfx interface, Cleanups:

src/mame/philips/mcd212.cpp, src/mame/philips/mcd212.h
This change fixes the following issues with the DYUV format:
1. The DYUV format incorrectly was too dark by 16/256. This fix corrects a previously incorrect attempt to fix that issue.
2. The DYUV format does not allow Mosaic features.
To Validate this change:
1. Use the Validation CD (Europe).
2. Click "Philips Tests"
3. Click "Video Representations"
4. Click "DYUV Decoder"
Result:
The DYUV format is slightly brighter. Mosaic effects will work more correctly. Unfortunately I don't know of a good example of how to see the mosaic behavior difference, however the spec makes it clear this configuration is not allowed.
Uncertain Issues:
The previous midpoint interpolation of 129+129 would be 1. The spec agrees with that formula. As the expected behavior is not yet well understood, a modified …
=> CD-i: Fix DYUV Format

hash/ibm5170_cdrom.xml
Found clean floppy disk images from MSDN sets, so build 528 of NT 3.1 now has a 5.25" floppy disk for CD-ROM based installs.  Most translated versions have their floppy disks for CD-ROM based installs added, too.
MSDN often contained whatever the latest service pack was at the time a set was made, those discs are here now too.  Microsoft was cost-conscious of printing many CDs, so these are often combined with other software.  A sole independent Windows NT 3.51 SP4 disc has been found and included here.  Were other 3.x service pack CD-ROMs made? Most likely SP5 was, but I have not located one.
Were 3.x service packs released on independent
CD-ROMs from the MSDN sets?  If so, they should replace the entries here.
The resource kit CD-ROMs for 3.1, 3.5, 3.51, and 4.0 are all included here. …
=> ibm5170_cdrom: NT 3.x floppies, SDKs, resource kits, service packs

src/mame/philips/mcd212.cpp, src/mame/philips/mcd212.h
This change:
1. Fixes RLE encoding which was short by 50%
2. Color Key now supports bit masking
3. Simplifies code, reducing by >100 lines.
4. Renames Channel to Path to match the Green Book spec.
5. Adds TODO for QHY DYUV images. This image type can't be tested without 625 scanline resolution which is currently blocked. So this will remain a known gap until several other features are added.
**Examples games you can use to test this fix:**
All the Fun at the Funfair
Validation Disc (screenshots below).
Notice that the flag's triangle is now 2x as wide.
Notice that the pointed to line now has uniform size for Red Green and Blue.
In the default case, simply take notice of the RL3 encoded lines are now uniformly sized boxes.
With this fix, the transparency mask bits are coded to allow to …
=> CD-i: Fix RLE and Transparency Color Key Bitmask

src/mame/mame.lst, src/mame/tvgames/monkey_king_3b.cpp
This was dumped from the fourth edition of the handheld from 2019. I don't know which, if any, of the other versions have also been dumped.
AtGames Atari Flashback Portable (version 4) [Devin Acker]
=> Add NOT_WORKING Atari Flashback Portable (fourth edition) dump

src/lib/util/corestr.cpp, src/osd/modules/sound/sdl_sound.cpp
Fedora 42 plans to ship gcc-15 and to replace native SDL2 with sdl2-compat. These changes have exposed minor header issues which this PR addresses.
=> Fedora 42 build fixes

src/mame/alesis/midiverb.cpp
- Routed the entire audio path.
- DSP is mostly a passthrough. Just does quantization (ADC) right now.
- Using 'samples' mechanism for audio input.
- Other style and code organization fixes.
It is now possible to "process" audio through the midiverb (see instructions near the top of the driver). There won't be any reverb, but there should still be some difference between wet and dry.
=> alesis/midiverb.cpp: Routed entire audio path. DSP just a passthrough.

hash/pc8801_flop.xml
- Required V2 Mode set so change PC8801 to PC8801mk2SR
- Parent set the scenario disk is user disk so make user is not possible (add a note)
If I set the scenario disk on XM8, the message indicate the disk is not the correct one.
If I set Mode n88v1h
The user disk of this set seems a blank disk.
Thanks,
=> hash/pc8801_flop.xml: babylon updates

src/mame/mame.lst, src/mame/tvgames/generalplus_gpl16250_rom.cpp
Power Rangers to the Rescue (JAKKS Pacific TV Game) (Aug 8 2008 16:46:59) [David Haywood, TeamEurope]
=> added Power Rangers to the Rescue (JAKKS Pacific TV Game) (as not working)

src/mame/philips/mcd212.cpp, src/mame/philips/mcd212.h
1. This fix adds RGB decoding and RGB Transparency bit. It disables transparency color keying for RGB.
2. It fixes an incorrect enum that was foreshadowed in previous revisions.
As with previous pulls, you can validate this using the Validation Disc (Europe) for the CD-i.
Due to the enum for CLUT8 and RGB being the same, this previously decoded as a CLUT8 image. When ICM flag 1 is used on path 1, it is instead decoded as RGB.
The house is now the right color
RGB is now decoded correctly. Additionally, RGB does not match color key. Even when matching "red" colors, notice that the line of RGB still shows red. This is correct behavior, as RGB is not allowed to match color keys.
The implementation of RGB color keying is to always be false. However the spec says that "RGB cannot use color key …
=> CD-i: Add RGB Decoding

src/mame/galaxian/galaxian.cpp, src/mame/mame.lst
=> Add a new War of the Bugs clone from Radar Ltd.

src/mame/seta/downtown.cpp
VBlank controls music tempo, reference: https://www.youtube.com/watch?v=RKPM7x73lDk
This commit also adjusts arbalest music tempo close to real hardware, because this game uses similar hardware as metafox. (and same screen size, refresh rate?)
=> seta/downtown.cpp: Fix metafox music tempo close to real hardware, Fix naming, Add notes

src/lib/formats/cassimg.cpp, src/lib/formats/tzx_cas.cpp
We have to revert this part as it potentially can cause regression in other images formats but tap.
I'll be looking for potential fix of the existing problem but given impact it must be considered more carefully.
=> formats/cassimg.cpp: prevent regression in cass images

hash/apple2gs_flop_clcracked.xml
New working software list items (apple2gs_flop_clcracked.xml) 
Draw Plus (version 1.0) [Brian Troha]
MultiScribe IIgs (version 3.01c) [Brian Troha]
The New Talking Stickybear Alphabet [Brian Troha]
The New Talking Stickybear Opposites [Brian Troha] The New Talking Stickybear Shapes [Brian Troha]
TopDraw (version 1.01A (8/4/87)) [Brian Troha]
- redumped Skate or Die IIgs (version 1.0) [Brian Troha]
=> apple2gs_flop_clcracked.xml: added 6 dumps, 1 redump [Brian Troha]

src/mame/toaplan/toaplan1.cpp, src/mame/toaplan/toaplan1.h, src/mame/toaplan/toaplan1_m.cpp, src/mame/toaplan/toaplan1_v.cpp
- Fix typename for boolean flags and member variables
- Fix save states
- Fix spacing
- Fix naming
=> toaplan/toaplan1.cpp: Fix metadata via region/settings, Cleanups:

hash/pc8801_flop.xml
- sf3dopv is the same game as sf3dthxg. So I make it a alternative. Add sf3dopv to undumped list. Fix the name to reflect the box name.
I put S.F.3.D Original Operation V on the undumped list.
TOSEC listed S.F.3.D Original Operation V but it is S.F.3.D Point X Senryou Sakusen - Operation Thanksgiving. (check with TOSEC (2024-05-17))
Both games existed as mentioned of this website
https://www.zimmerit.moe/kow-yokoyama-sf3d-original/
Box art of S.F.3.D Point X Senryou Sakusen - Operation Thanksgiving
https://gamesdb.launchbox-app.com/games/images/147053-sf3d-original-operation-thanksgiving
Box art of S.F.3.D Original Operation V
https://www.ebay.com/itm/375902905939
Name for S.F.3.D Point X Senryou Sakusen - Operation Thanksgiving
https://www.8-bits.info/gamelist/PC88/info/info_QI7pTNS9F8yuP …
=> hash/pc8801_flop.xml: update QA

hash/pc8801_cass.xml
New software list items marked not working (pc8801_cass.xml) 
-------------------------------------------------------------------------------------------
Computer the Golf (1983)(Nihon Falcom) [shawnji on archive.org]
It is available on shawnji profile on archive.org.
Information of the game:
https://www.giantbomb.com/computer-the-golf/3030-70864/releases/
Thanks,
=> hash/pc8801_cass.xml: Added 1 not-working item

src/devices/machine/mc68328.cpp, src/devices/machine/mc68328.h
In the course of fleshing out the AlphaSmart 3000 emulation, I've made these two changes to more accurately emulate the underlying hardware. They are separate commits to help in case of future regression testing.
- The Port A change should have no impact on existing emulation, as none of the machines (cowtipping, iqunlim, clie_db, palm) use port A.
- The timer change should be functionally equivalent, though the timer tick callback will be called more often. It might affect emulation speed on very low power host systems.
=> Fixes for MC68EZ328

src/mame/toaplan/twincobr.cpp, src/mame/toaplan/twincobr.h, src/mame/toaplan/twincobr_m.cpp, src/mame/toaplan/twincobr_v.cpp, src/mame/toaplan/wardner.cpp
- Fix typename for boolean flags and member variables
- Use machine_start() for save states
- Fix palette entries for wardner
- Fix filename
- Fix spacings
- Fix namings
=> toaplan/twincobr.cpp, toaplan/wardner.cpp: Cleanups

src/devices/machine/z80dma.cpp, src/mame/kontron/kdt6.cpp
- Use memory_view for boot ROM enable function
machine/z80dma.cpp: Suppress side effects for debugger reads, Reduce unnecessary line
=> kontron/kdt6.cpp: Cleanups:

src/devices/cpu/drcbearm64.cpp, src/devices/cpu/drcbearm64.h
This should implement some of the optimisations previously discussed for AArch64 code generation:
* `bl` displacement is in words
* The `emit_*_mem` functions know the operand size, so they can pass the corresponding shift to `emit_ldr_str_base_mem` rather than trying to calculate it after the fact
* An immediate load/store offset can be either a 9-bit signed byte offset or an unsigned 12-bit element offset
* An unsigned 12-bit element offset can always reach an entire page, so the page-relative access can always be done in two instructions
And one bug fix:
* AArch64 doesn’t allow a variable left shift for a register offset, it only allows zero or the element size, so there’s no point testing intermediate shift values.
@987123879113 and/or @rb6502 can you check this out and test it?
=> cpu/drcbearm64.cpp: Optimise load/store and call generation

hash/x68k_flop.xml
New working software list additions (x68k_flop.xml) 
Last Force - The Virtual Battle in 1930's (1993)(Hong Kong Project) [Shentok on archive.org] 
It is available on Shentok profile on archive.org.
Xadlak Plus (1996)(Sprite) [danielham on archive.org]
It is available on danielham profile on archive.org.
I tested them on Mame with the driver X68000.
Thanks.
=> hash/x68k_flop.xml: Added 2 working items.

src/mame/layout/paia_fatman.lay, src/mame/mame.lst, src/mame/paia/fatman.cpp
New system marked not working: fatman.
The digital portion of the synth is fully emulated. The digital-analog interface is almost fully emulated: voltage calculations, envelope generators and their controls. The only thing missing is emulation of the "punch" switch.
The rest of the analog circuitry is not emulated. There is no audio.
A layout is included, but not too interactive right now.
=> paia/fatman.cpp: Adding driver for FatMan.

src/mame/layout/oberheim_dmx.lay
- Click and adjustment state is now tracked for each pointer ID individually, rather than globally.
- If a user selects the slider knob, the adjustment will be proportional to the knob movement. This allows for finer adjustments. If the user clicks elsewhere on the slider, the adjustment is based on the absolute position of the click.
This is a followup to the discussion in #13177.  Tested on a single-mouse setup.
This should also work with multiple pointer devices, and touchscreens (assuming the latter generate "button press" events). But I was not able to verify. I tried testing with multiple mouse cursors (using `xinput` and multiple mice), but it seems like SDL2 does not support that. I also tried emulating a touchscreen with `evdev`, but this didn't work either. If someone has  a way …
=> oberheim_dmx.lay: Proper tracking of pointer IDs. Easier fine adjustments.

src/mame/intel/intellec8.cpp, src/mame/mame.lst
Intellec 8 MCS MOD80 (set 1, 884A) [ArcadeHacker]
Intellec 8 MCS MOD80 (set 2, 880) [ArcadeHacker]
=> intel/intellec8.cpp: Add two Intellec 8 MOD80 sets

scripts/genie.lua, src/devices/cpu/drcbex64.cpp, src/devices/cpu/drcbex64.h, src/emu/emumem.h, src/emu/emumem_aspace.cpp
At the urging of @galibert, this makes the x86-64 recompiler back-end dispatch memory accesses to specific handlers directly, avoiding one level of out-of-line function calls.  From my testing on an Intel 8th generation i7, the performance improvement is measurable, but less than 5% at best.
I’d like people to test this with other x86-64 CPUs (e.g. AMD or different generations of Intel CPUs) to see what kind of difference it makes (if any).
If it does seem to produce a useful improvement, I can follow up by adding code to directly dispatch reads smaller than native width, and add scaffolding for carrying over the same optimisations to AArch64.  If it doesn’t seem to be a worthwhile improvement, I’ll just move across the removal of the static address space accessors and ditch the …
=> cpu/drcbex64.cpp: Directly dispatch memory accesses to specific handlers

docs/source/initialsetup/compilingmame.rst, scripts/genie.lua, src/osd/modules/font/font_sdl.cpp, src/osd/modules/render/bgfx/shadermanager.cpp, src/osd/modules/render/drawbgfx.cpp
This PR adds support for the bgfx video backend when building for emscripten.
In order to get bgfx build and run with mame, the following changes has been done:
* `src/osd/modules/render/bgfx/shadermanager.cpp`: Change `make_path_string(...)` to always return the path to the `essl` shaders. This wasn't working properly since the call to the function is done before bgfx has been initialised and therefore returned the renderer type `Noop` instead (see https://bkaradzic.github.io/bgfx/bgfx.html#_CPPv4N4bgfx15getRendererTypeEv).
* `src/osd/modules/render/drawbgfx.cpp`: Change `set_platform_data(...)` to return platform data with a window handle that includes a HTML target selector for the canvas element to use (currently set to `#canvas`).
* `scripts/genie.lua`: Update emscripten compiler …
=> emscripten: fixes to get bgfx working

src/mame/konami/spy.cpp
- Use memory_view for RAM overlay
- Reduce sound CPU ROM region size for match to mapped size in sound CPU
- Fix save state supports
- Fix naming
- Use std::fill_n for initialize PMC RAM
- Add notes for unknown writes
=> konami/spy.cpp: Updates, Cleanups

src/mame/konami/k051733.cpp
- use logmacro.h for logging
- Remove unnecessary include
- Fix spacing
=> konami/k051733.cpp: Cleanups

src/mame/konami/k001005.cpp, src/mame/konami/k001006.cpp, src/mame/konami/k001006.h
Common:
- Use BIT function for single bit flags
konami/k001005.cpp:
- Fix spacing
konami/k001006.cpp:
- Use device_palette_interface for palette
- Add error if texture ROM size is not multiple of 0x40000 bytes or texture ROM size is less than 0x40000 bytes
- Match m_texrom data size to texture ROM size
=> konami/k001005.cpp, konami/k001006.cpp: Cleanups

hash/megacd.xml
I think this may have been missed during the megacd re-org
=> In megacd software list, make eternalcu a clone of eternalc

src/mame/namco/namcos12.cpp
marked it as ASIA/US? instead but it's most likely a US set, due to Parental Advisory warning.
The Japanese language in-game is hardcoded to disabled (windyfairy did some research on it before)
A real Japanese set would likely be hardcoded to Japanese in-game, or have the option to choose enabled.  That would most likely have the code TKK1, rather than TKK2 (although we can't be sure as the number is just release order, not region)
=> Update namcos12.cpp - truckk can't be a Japanese set

src/devices/cpu/m68000/scc68070.cpp, src/devices/cpu/m68000/scc68070.h
Fixes `cdi:zombie` and clones crashing after the intro, and possibly other stuff.
Not sure if `cpu/m68000/scc68070.cpp` is the ideal place to put this, or if somewhere else would work better for if/when the MMU gets implemented.
=> scc68070: limit external memory addresses to 24 bits

src/mame/ibm/ibm3153.cpp, src/mame/ibm/ibm3477.cpp, src/mame/mame.lst
IBM InfoWindow 3477 [OldComputers ES]
=> Add a skeleton driver for IBM InfoWindow 3477

src/mame/oberheim/dmx.cpp
Followup to the discussion in #13367.
=> oberheim/dmx.cpp: Removed imperfect_sound, reported tape as unemulated.

src/mame/mame.lst, src/mame/vtech/magibook.cpp
MagiBook (Spanish) [ArcadeHacker]
=> Add a skeleton driver for VTech MagiBook / LeapFrog LeapStart

src/mame/taito/taito_b.cpp, src/mame/taito/taito_b.h, src/mame/taito/taito_b_v.cpp, src/mame/taito/tc0180vcu.cpp, src/mame/taito/tc0180vcu.h
Common:
- de-std::unique_ptred bitmap variables
taito/taito_b.cpp:
- Split driver state class via hardware/input configurations
- Fix silentd soundchip type; It's PCB (ET910000B) has YM2610B, reference: various PCB pics
- Fix rambo3p crash when try to reading trackball input
- Move audio CPU bank configuration into machine_start
- Fix palette format for games using 15 bit color palette
- Fix namings
- Add notes
taito/tc0180vcu.cpp:
- Fix typename for boolean flags
- Fix spacings
=> taito/taito_b.cpp, taito/tc0180vcu.cpp: Updates / Cleanups:

src/mame/taito/taito_f2.cpp, src/mame/taito/taito_f2.h, src/mame/taito/taito_f2_v.cpp, src/mame/taito/tc0280grd.cpp, src/mame/taito/tc0280grd.h
Common:
- Fix typenames for fix save state
- Fix naming
taito/taito_f2.cpp:
- Fix metadata via region and bootlegged game (both mjnquest set have been confirmed to be Japanese version)
- Split driver state class via hardware configuration
- Fix input matrix read behaviour
- Fix docs
- Fix spacings
- Fix driveout sound routing because no sound chip with stereo support
taito/tc0280grd.cpp:
- Split TC0430GRW into separated device
- Add variables into save state
=> taito/taito_f2.cpp, taito/tc0280grd.cpp: Updates/Cleanups:

src/mame/taito/taitojc.cpp, src/mame/taito/taitojc.h, src/mame/taito/taitojc_v.cpp, src/mame/taito/taitopjc.cpp, src/mame/taito/tc0780fpa.cpp, src/mame/taito/tc0780fpa.h
Common:
- Make some arrays to memory_share and shared_ptr
- Fix naming
- Fix typename for fix save state
- Fix spacing
- Use set_format for palette
- Reduce unnecessary variables
taito/taitojc.cpp:
- Split dendego* driver state class via controller config
- Make some arrays to shared_ptr
taito/taitopjc.cpp:
- Fix gfx amount for fix OOB gfx access in tilemap
- Use logmacro for logging
- Add items in save state
- Add notes
taito/tc0780fpa.cpp:
- Use plain type for bitmaps
=> taito/taitojc.cpp, taito/taitopjc.cpp, taito/tc0780fpa.cpp: Cleanups/Updates:

src/mame/handheld/hh_sm510.cpp
The white background of the SVG for kchqflag has been increased to avoid a black border from being shown.
=> kchqflag: Increase white svg background to avoid black border

scripts/src/cpu.lua, src/devices/cpu/tlcs900/tlcs900.cpp, src/devices/cpu/tlcs900/tlcs900.h, src/devices/cpu/tlcs900/tmp94c241.cpp, src/devices/cpu/tlcs900/tmp94c241.h, src/devices/cpu/tlcs900/tmp95c061.cpp, src/devices/cpu/tlcs900/tmp95c061.h, src/devices/cpu/tlcs900/tmp95c063.cpp, src/devices/cpu/tlcs900/tmp95c063.h, src/mame/matsushita/kn5000.cpp
=> new tlcs900 variant: TMP94C241

src/mame/taito/slapshot.cpp, src/mame/taito/slapshot_v.cpp, src/mame/taito/taito_f2_v.cpp
Common:
- Fix typename for boolean flags
- Use util::sext for sign extended variables
- Use BIT for single bit variables
taito/slapshot.cpp:
- Fix notes
- Fix spacings
=> taito/slapshot.cpp, taito/taito_f2.cpp: Cleanups

src/devices/video/k053936.cpp
The quest to improve blending on Konami systems continue.
A rather simple change once again: blending appears to be performed backwards in k053936.cpp's `K053936GP_copyroz32clip()`. I tried a few games that use this chip, but I only observed transparency in two games: `mmaulers` (planet fade-in in the intro) and `gaiapols` (water, glass floor). The visual changes are pretty minor from what I've seen, but it's a step forward nonetheless.
I also combined solid / alpha drawing paths to reduce duplicate code.
Another thing I tried was to convert the do loops to more conventional for loops, along with the usual nailing everything down with const and more appropriate types. This lost some performance, so decided to only commit the bare minimum for now.
=> k053936.cpp: invert blending, reduce code duplication

src/mame/mame.lst, src/mame/vtech/geniuscolor.cpp
New systems marked not working 
VTech Genio Color Pocket (Spanish) [jordigahan, ClawGrip]
=> Add a skeleton driver for VTech Genius Color Pocket console

src/mame/sigma/sigmab31.cpp
same sound cpu memory maps of b52. 
only the sound cpu are hooked up except the main cpu.
=> hooking the sound cpu for captain lucky sigmab31.cpp

src/mame/taito/qix.cpp, src/mame/taito/qix.h, src/mame/taito/qix_a.cpp, src/mame/taito/qix_m.cpp, src/mame/taito/qix_v.cpp
- Use palette_device for palette feature
- Separate driver state class for kram3 due to encryption
- Use logmacro.h for MCU logging
- Fix spacings
- Fix namings
- Add notes
=> taito/qix.cpp: Cleanups/Updates

hash/apple2_flop_clcracked.xml, hash/apple2_flop_orig.xml
Updated metadata for Locksmith
Removed (apple2_flop_clcracked.xml)
Locksmith (version 5.0 Revision C) (imperfect clean crack)
Locksmith (version 5.0 Revision F) (imperfect clean crack)
=> apple2_flop_clcracked: Removed 2 dumps and updated metadata for Locksmith

src/mame/zvt/pp01.cpp, src/mame/zvt/pp01.h, src/mame/zvt/pp01_m.cpp, src/mame/zvt/pp01_v.cpp
- Restrict screen update function to cliprect
- Add device_post_load for memory bankswitching
- Fix logging
- Fix typename for boolean flags
- Fix spacings
- Fix namings
=> zvt/pp01.cpp: Updates/Cleanups

src/mame/wing/pinkiri8.cpp
- Move video function into janshi_vdp_device
- Use device_gfx_interface for janshi_vdp_device gfx decoding feature
- Demote pinkiri8 to MACHINE_NO_SOUND because sound ROM not dumped (or not exists in real hardware?)
- Use set_format for palette format, Fix palette entry matches to palette RAM size(*2 for 16(15 actually) bit color)
- Add items into save state
- Fix input matrix reading behavior
- Reduce literal tag usages and runtime tag lookups
- Convert background tilemap to tilemap_t
- Fix namings
- Fix spacings
=> wing/pinkiri8.cpp: Updates/Cleanups:

src/mame/layout/linn_linndrum.lay, src/mame/layout/oberheim_dmx.lay, src/mame/layout/roland_d70.lay
* Explicit configuration: Using add_* functions, instead of scanning through the layout for sliders.
* Separated the copy-pasteable portion of the script.
* A no-op for the DMX and LinnDrum layouts.
* Fixes multitouch and slider "drift", and adds support for relative adjustments to the D70 sliders (they were using an older version of the script).
=> Multiple synth layouts: updated to the latest slider script.

src/mame/philips/mcd212.cpp, src/mame/philips/mcd212.h
This intentionally has no visible effects. The purpose is to make the code easier to understand and maintain.
1. The non-canonical name "Regions" was changed to the official name "Mattes". Corresponding abbreviation "R" is changed to "M".
2. Deprecated function get_plane_width is deleted.
3. mix_lines is refactored.
4. Minor changes.
=> philips/mcd212.cpp: Rename matte flag constants and refactor matte handling code

src/mame/layout/linn_linndrum.lay, src/mame/linn/linndrum.cpp
Extended the LinnDrum's layout script to support knobs with a `simplecounter` in them.
Click on a knob and scroll up/down to change its value.
=> linn/linndrum.cpp: Made knobs controllable by pointing device.

hash/megacd.xml
- Added parent/clone relationship between "Blackhole Assault (Europe)" / "Black Hole Assault (Japan)"
- Lowercase on descriptive words "Night Trap (USA, re-release)"
- Replaced country abbreviation "Cadillacs and Dinosaurs - The Second Cataclysm (Brazil)"
=> megacd.xml: Metadata cleanups

src/mame/snk/munchmo.cpp
- Cleanup gfx decode layouts, Use GFXDECODE_SCALE for internally scaled gfxs
- Split tile index LUT ROM and tile GFX ROM region for cleanup gfx decode layout and Fix ROM region naming confusion
- Fix save state support
- Fix typename for boolean flag
- Fix naming
=> snk/munchmo.cpp: Updates/Cleanups

src/mame/igs/igs_68k_023vid.cpp
the hardware isn't mapped identically between these, xypmd  is a 'SUPER' version and may be less protected, it does more than xypmda and accesses fewer addresses, however it could just be I/O differences.
xypmda also fails to show the 'SUPER DERBY' logo at the start of a race properly (even if it's a simple thing on the tx tilemap) and has issues moving the camera, which suggest that one might actually be using the 025 protection while the parent either doesn't, or uses it for something else entirely.
=> make xypmd / xypmda show something

scripts/src/bus.lua, src/devices/bus/centronics/ctronics.cpp, src/devices/bus/centronics/epson_fx80.cpp, src/devices/bus/centronics/epson_fx80.h
Skeleton for Epson FX-80 and Epson JX-80
=> src/devices/bus/centronics/epson_fx80.cpp : add skeleton for epson fx-80

src/mame/sega/model3.cpp
Picture of actual Model 3 Step 2 video board for reference:
=> Removing erroneously duplicated lines in figure of Model 3 Step 2 video board

src/mame/mame.lst, src/mame/skeleton/css11501sk9.cpp
=> Add a skeleton driver for Cisco CSS11501S-K9 Content Services Switch

src/devices/cpu/drcbearm64.cpp
This is more of the stuff recommended by @galibert – I need help testing this on a 64-bit ARMv8 system.
The basic premise is that:
* The address line count, global address mask and dispatch table pointers for an address space don’t change after setup.  This means you can treat them as immediate constants/PC-relative addresses and avoid accessing the address space object altogether.
* In practice, the global address mask is always a contiguous sequence of set bits.  This means the address can be masked with an AND immediate instruction.  The dispatch table index can also be extracted with a UBFX instruction before the mask is applied for slightly better pipeline utilisation.
I’ve used some functions to reduce repetition, and I’ve commented to code to explain what it’s doing (not just the …
=> cpu/drcbearm64.cpp: Emit optimised memory access code

src/mame/misc/mcatadv.cpp
- Fix typename consistency, Make some variables constant
- Use util::sext for sign extend function
- Remove unnecessary config.replace()
- Fix spacing
- Fix filename
=> misc/mcatadv.cpp: Cleanups:

src/devices/sound/gt155.cpp, src/devices/sound/gt155.h
Fixes the issue mentioned here: https://github.com/mamedev/mame/pull/12957#issuecomment-2695904360
=> gt155: avoid possible overflow in filter output

src/mame/nmk/nmk16.cpp, src/mame/seibu/airraid.cpp, src/mame/seibu/bloodbro.cpp, src/mame/seibu/cabal.cpp, src/mame/seibu/dcon.cpp, src/mame/seibu/deadang.cpp, src/mame/seibu/dynduke.cpp, src/mame/seibu/goodejan.cpp, src/mame/seibu/legionna.cpp, src/mame/seibu/r2dx_v33.cpp, src/mame/seibu/raiden.cpp, src/mame/seibu/raiden2.cpp, src/mame/seibu/sengokmj.cpp, src/mame/seibu/toki.cpp, src/mame/shared/seibusound.cpp, src/mame/shared/seibusound.h, src/mame/sunelectronics/shanghai.cpp
- Fix typename for boolean flags
- Fix spacing
- Fix naming of Z80 banked area
=> shared/seibusound.cpp: Make coin IO port optional (for removal nmk16.cpp bootlegs unused IO region), Cleanups:

src/devices/cpu/drcbearm64.cpp
If you use `-drc_log_native` on x86-64, you get output like this, with disassembled UML following the binary representation (before resolving forward labels):
```
call 0x18E76A10C42                      ; E836F2FFFF
read32mask:                                 ;                         | handle  read32mask
short jmp L1                            ; EB..
lea rsp, [rsp-0x28]                     ; 488D6424D8
L1:
and ebx, 0x7FFFFFFF                     ; 81E3FFFFFF7F            | and     i0,i0,$7FFFFFFF
cmp ebx, 0xFF01FFFF                     ; 81FBFFFF01FF            | cmp     i0,$FF01FFFF,ZC
ja PC$1                                 ; 0F87........            | jmp     $       1,a
cmp ebx, 0xFF000000                     ; 81FB000000FF            | cmp     i0,$FF000000,C
jb PC$1 …
```
=> cpu/drcbearm64.cpp: Add disassembled UML comments to logged assembly

hash/ibm5170.xml, hash/ibm5170_cdrom.xml
CD-ROM dumped from my own disc.
Floppy images are sort-of unofficial, given that no such floppy disks are shipped in the software’s box.  Even still, the disc has \%LANG%\DOSMAKE\MAKEDISK.BAT files that can be used to create bootable floppy disks.  The utility of the floppy disks for booting systems (especially ct486) without El Torito support is rather high, so I am including them here.
New working software list items (ibm5170.xml)
---------------------------------------------
Norton PartitionMagic 8.05 (English) [chungy]
Norton PartitionMagic 8.05 (French) [chungy]
Norton PartitionMagic 8.05 (German) [chungy]
Norton PartitionMagic 8.05 (Italian) [chungy]
Norton PartitionMagic 8.05 (Spanish) [chungy]
New working software list items (ibm5170_cdrom.xml) …
=> hash/ibm5170{,_cdrom}: PartitionMagic 8.05

src/mame/linn/linndrum.cpp
Added:
* All voice cores and auxiliary sound modules emulated.
* Some analog post-processing emulated: snare/stick volume variations and LPF, mux drum volume variations.
* linndrum promoted to working.
Missing functionality (more info at the top of the driver):
* Volume and pan sliders not hooked up yet.
* Tuning knobs not hooked up yet.
* Some analog post-processing missing.
* Missing checksums for 3 samples (bass, cabasa, claps). If someone has access to the missing checksums, feel free to add them afterwards.
=> linn/linndrum.cpp: First pass at audio emulation.

src/devices/cpu/drcbearm64.cpp
This attempts to fix potential crashes if a recompiler front-end uses immediate operands with `ADDC`/`SUBB` as described in GitHub #13475, as well as optimising more cases where register loads can be avoided.
I’d appreciate review and/or testing.
=> cpu/drcbearm64.cpp: Fix issues with and optimise ADD[C]/SUB[B] code generation

src/devices/cpu/drcbearm64.cpp, src/devices/cpu/drcbearm64.h
If you look at the current code generated by the AArch64 recompiler back-end, you see stuff like this (example is the “fastram” checks for a 32-bit read in `fiveside`):
```
ands w19, w19, 0x7FFFFFFF               ; 737A0072
nop                                     ; 1F2003D5
mov w9, w19                             ; E903132A
mov w10, 0xFF01FFFF                     ; CA1FA012
cmp w9, w10                             ; 3F010A6B
cset x12, 5                             ; EC279F9A
bfi x28, x12, 0, 1                      ; 9C0140B3
mrs x12, 0xDA10                         ; 0C423BD5
bfi x12, x28, 0x1D, 1                   ; 8C0363B3
eor x12, x12, 0x20000000                ; 8C0163D2
msr 0xDA10, x12                         ; 0C421BD5
b.hi PC$1                               ; 08000054
mov w9, w19 …
```
=> cpu/drcbearm64.cpp: Optimised conditional operations using carry flag

src/mame/layout/linn_linndrum.lay, src/mame/linn/linndrum.cpp
* Mix and pan sliders work.
* Master volume knob works.
* Tuning knobs and trimmer work.
* Adjusted knob sensitivity on the layout.
* Corrected relative levels of voices.
* Added output LPF and DC-blocking HPFs.
* Mild refactoring: moved voice setup in strobe_* functions.
The non-trivial equations in `update_*()` and `strobe_*()` functions were validated with simulations.
=> linn/linndrum.cpp: Mixing, panning and tuning.

src/devices/cpu/sc61860/scdasm.cpp, src/devices/cpu/sc61860/scops.hxx, src/devices/cpu/sc61860/sctable.hxx
Working on the Sharp PC-series emulaton, I noticed a bug in the SC61860 cpu, which was missing an opcode implementation.
It is a pointlike fix, and it has been tested by me locally for correctness.
See also https://www.youtube.com/watch?v=qsQMiYbir20, for an example of my activity on this device.
=> fixing cpu for missing opcode

src/devices/cpu/z80/z80dasm.cpp
STEP_COND on repeatable instructions doesn't allow to skip execution with F10
STEP_OVER is more reasonable for this instructions as allowed to take advantage from F10/F11
Per my understanding that should close match expectation:
`static constexpr u32 STEP_OVER       = 0x20000000;   // this instruction should be stepped over by setting a breakpoint afterwards`
=> z80/z80dasm.cpp: Switched *R (LDIR, OTIR, etc) debugger flag to STEP_OVER

src/devices/cpu/i960/i960.cpp
Commit 4cce14e changed the behavior of the shli instruction to preserve the sign bit, but I don't know of any other CPUs that do this nor is there any evidence in the [programmers reference manual](http://bitsavers.informatik.uni-stuttgart.de/components/intel/i960/80960KB_Programmers_Reference_Manual_Mar88.pdf) to suggest the i960 actually does this.
The i960 manual says that shifting left is supposed to be equivalent to multiplying by a power of 2, but if you multiply the signed integer 2,000,000,000 by 2 it overflows to negative, so the sign bit is not being preserved in this case.
If there is actual evidence that the i960 preserves the sign bit when shifting integers left I would be interested to see it, but until then I can only assume that commit 4cce14e is a regression; the opponent …
=> i960: don't preserve sign bit when shifting integer left

src/mame/sinclair/spectrum.cpp, src/mame/sinclair/spectrum.h, src/mame/sinclair/sprinter.cpp
```
~/workspace/mame (spectrum-perf*) » ./mame spectrum -bench 300
Average speed: 2199.09% (299 seconds)
-----------------------------------------------------------------------------------------------
~/workspace/mame (spectrum-perf*) » ./mame spectrum -bench 300
Average speed: 3265.35% (299 seconds)
```
=> sinclair/spectrum.cpp: Improved performance by 50% avoiding memregion lookup in a critical path

src/mame/dataeast/rohga.cpp, src/mame/mame.lst
Wizard Fire (Over Sea v1.0) [Tailsnic Retroworks]
Also reformatted comments and used hex (instead of decimal) for PROMs regions sizes
=> dataeast/rohga.cpp: Add Wizard Fire (Over Sea v1.0)

src/mame/mame.lst, src/mame/skeleton/powerpack.cpp
Powerpack In-Circuit Emulator PP-SW+ PIII [ArcadeHacker]
=> Add a skeleton for Microtek Powerpack In-Circuit Emulator PP-SW+ PIII

src/mame/mame.lst, src/mame/misc/compucranes.cpp
Cranesaurus Single [Zooo Arcade, Recreativas.org]
Also fix CPU type on Toy Shop
=> misc/compucranes.cpp: Add a new crane coinop on GANCHONEW hardware

src/devices/sound/scsp.cpp, src/devices/sound/scsp.h
The previous code would immediately clear the SCIPD register (m_udata.data[0x20/2]) when firing a MIDI interrupt, which would cause issues if a timer interrupt fired before reading from the MIDI input FIFO buffer; the SCIPD register would be set up to fire another MIDI interrupt and the SCSP would end up reading garbage from the "empty" input FIFO. The new code clears the SCIPD register only when clearing the interrupt, preventing it from firing again if the input FIFO is empty.
Also the MIDI output FIFO buffer is separate from the MIDI input FIFO buffer; the former is currently not hooked up to either the Model 2 or Model 3 drivers.
=> scsp: improve handling of MIDI interrupts

hash/x68k_flop.xml
A new update for the X68000 software list. I finally figured out how to properly convert those Konami disks with the "track full of overlapped sectors" protection (turns out the track had to be aligned correctly with the index signal), so the Namachuukei 68 dump that rockleevk did a long time ago now works and can be added to the list.
I also included the new disks that krugman has been dumping lately, all of them are working as far as I have tested.
As usual, I have compared everything with the existing images. Protected disks that already had a cracked version have been added preserving the existing ones, and disks where the decoded data matches the existing image have been replaced, since the MFM format represents the disk more accurately at a lower level.
New working software list …
=> x68k_flop.xml: added/replaced 17 dumps from original disks

src/mame/philips/mcd212.cpp
The DYUV decoder requires an interpolation between steps. The previous implementation was based on the manual. This interpolation is based on visual comparison to the hardware.
Notice that the pink lines at the top now match up correctly, instead of being off by ~2 pixels.
Fixes: https://github.com/mamedev/mame/issues/13438
=> CD-i: Fix DYUV off-by-1

hash/tvgogo.xml, src/mame/mame.lst, src/mame/nintendo/nes_sh6578.cpp, src/mame/nintendo/nes_vt09.cpp, src/mame/nintendo/nes_vt32.cpp, src/mame/nintendo/nes_vt32_soc.cpp, src/mame/nintendo/nes_vt32_soc.h, src/mame/nintendo/nes_vt369_vtunknown.cpp, src/mame/sega/megadriv_rad.cpp, src/mame/tvgames/spg2xx_lexibook.cpp, src/mame/tvgames/xavix.cpp, src/mame/tvgames/xavix_2002.cpp
this is a squashed version of https://github.com/mamedev/mame/pull/13401 without the XaviX sound changes, as more has been discovered since then, which invalidates quite a lot that
- added controls to maxheart (game is playable, but shuts down into power saving after 15 minutes as if no buttons had been pressed) [David Haywood]
- started researching the banking scheme used by atgame40, while several games are now bootable the others appear to use video modes specific to this Genesis clone SoC so fail to display proper gameplay [David Haywood]
------------
Millennium Arcade 3D 15-in-1 [TeamEurope, David Haywood]
------------
TV Games Baseball (SH6578 hardware) [Ankos, Kryzsiobal]
Chāo Jí Zhī Shi Dà Fù Wēng (vol. 1) [Ankos, Kryzsiobal]
Chāo Jí …
=> current Plug+Play work for 0.276 (1 working, 8 non-working, 2 softlist, minor research)

src/devices/sound/s_dsp.cpp, src/devices/sound/s_dsp.h, src/mame/nintendo/nss.cpp, src/mame/nintendo/sfcbox.cpp, src/mame/nintendo/snes.cpp, src/mame/nintendo/snesb.cpp, src/mame/nintendo/snesb51.cpp
- Fix pitch modulation emulation
- Fix input clock
- Fix save state support
- Fix indent inconsistency
- Use std::clamp for clamping functions
- Use reference for voice state
- Use lowercase hexadecimal values
- Use logmacro.h for logging
reference: https://snes.nesdev.org/wiki/SNESdev_Wiki
=> sound/s_dsp.cpp: Updates/Cleanups

scripts/src/sound.lua, src/devices/bus/nes/mmc5.cpp, src/devices/bus/nes/mmc5.h, src/devices/bus/nes/nes_slot.h, src/devices/sound/mmc5.cpp, src/devices/sound/mmc5.h, src/devices/sound/nes_defs.h
- Heavily based from devices/sound/nes_apu.cpp, Adjusted to differences compares to NES APU and MMC5.
bus/nes/mmc5,cpp: Fix save state support, Implement MMC5 sound, Make some variables constant
bus/nes/nes_slot.h: Fix save state support
sound/nes_defs.h: Fix save state support
reference: https://www.nesdev.org/wiki/MMC5_audio
=> devices/sound/mmc5.cpp: Implement MMC5 sound emulation

src/mame/namco/namcops2.cpp
[As pointed out here](https://twitter.com/mokonaXVI/status/1900725071817437407) [through this auction listing.](https://www.ebay.com/itm/176916947204?_skw=battle+gear&itmmeta=01JPBNH27KRKX070HV7FBPVV1G&hash=item2931126104:g:gSYAAOSwN7Bn0cAu&itmprp=enc%3AAQAKAAAA0FkggFvd1GGDu0w3yXCmi1eMCW8qh8Fjk0L%2BPMGruHGD0en6CV0gCfcQrx5Bbcqw02ilz5%2FuiuX35%2BxQvIenFZL5g5EH8SgloiebZ3Remt0emqSteGDsV9kXcfZjgsz55t5GP6bCzY9lMGRDesklNo%2Bcoj915edv35VKdBkAFE0riQ9PnMbJ9X4YXtfwWl2c7ebBA05MUN8MZeibpIsTrVZfVtoGBYYzpgLFJne45vfK03X3AxjvqdUFH7tOQcjc2b24dE3ATm1YHrrdqfxQdb4%3D%7Ctkp%3ABk9SR4CkxPWyZQ)
>DONGLE NM00015  B3900077A  
>HDD 40.0GB WD WD400EB
>(BG3 TUNED)-(HK) M9006543A VER.2.00C
Other references of the alternate server intended to be used with this revision (vs. the "O" export/English version, which has media …
=> Battle Gear 3 Tuned has a Hong Kong (server?) version

src/devices/cpu/m68000/m68010.cpp, src/devices/cpu/m68000/m68010.h, src/devices/cpu/m68000/m68kcpu.h
This is required for tek4404 to work.
Added ctor taking internal_map for handling tek4404 custom MMU
=> m68kcpu:  for 68010 only, do not throw away buserr on prefetch

src/mame/sega/model1.cpp, src/mame/sega/model2.cpp
The Manx TT course select rotation bug was caused by the i960 running too far ahead of the copro TGP and overwriting 0x918000 before the TGP got a chance to read it; adding a wait state when writing to the input FIFO prevents this.
Also increase frequency of TGP to 16.666 MHz (50 MHz / 3) on Model 2 and decrease to 13.333 MHz (40 MHz / 3) on Model 1; the [MB86232 datasheet](https://bitsavers.trailing-edge.com/components/fujitsu/_dataSheets/MB86232_DSP_Sep89.pdf) specifies that a machine cycle equates to three master clock cycles so presumably the same applies to the MB86233 and MB86234. 13.333 MHz for the MB86233 would match the 75ns cycle time listed for the MB86232, and it is likely that the [MB86234 process shrink](https://caps0ff.blogspot.com/2017/11/tgp-status-update.html) allows it …
=> model2: wait state when writing to copro TGP input FIFO; also adjust TGP frequencies on Model 1/2

src/mame/konami/k053246_k053247_k055673.cpp, src/mame/konami/k053246_k053247_k055673.h, src/mame/konami/k054156_k054157_k056832.cpp, src/mame/konami/k054156_k054157_k056832.h, src/mame/konami/k054338.cpp, src/mame/konami/konamigx.cpp, src/mame/konami/konamigx.h, src/mame/konami/konamigx_v.cpp, src/mame/konami/moo.cpp, src/mame/konami/mystwarr.cpp, src/mame/konami/mystwarr.h, src/mame/konami/mystwarr_v.cpp, src/mame/konami/xexex.cpp
I feel like I'm starting to amass a lot of changes so I'm opening a PR now. That, and the current changes are starting to reach a stable state! ...I hope!
The TL;DR version, games I know to be affected in parentheses:
**Additive sprite blending** (mmaulers)
**Improved tile blending** (mystwarr, viostorm, metamrph, sexyparo)
---
10 months ago, master Galibert sent down His [holy](https://github.com/orgs/mamedev/discussions/109#discussioncomment-9355919) [scriptures](https://github.com/orgs/mamedev/discussions/109#discussioncomment-9429978) to a certain inquisitive peasant. Since then I've spent some time on and off trying to interpret His writings, and well, I can confidently say that *some* of it has definitely sunk in!
---
File by file commentary:
**k053246_k053247_k055673.cpp, …
=> Konami (GX) blending - additive sprite blending, improved tile blending

scripts/src/sound.lua, src/devices/sound/va_eg.cpp, src/devices/sound/va_eg.h, src/devices/sound/va_vca.cpp, src/devices/sound/va_vca.h, src/mame/linn/linndrum.cpp, src/mame/oberheim/dmx.cpp, src/mame/paia/fatman.cpp
* Implemented VA_RC_EG (in `sound/va_eg`). Emulates an RC-circuit-based envelope generator. Values are published to a sound stream and can also be accessed directly.
* Implemented VA_VCA (in `sound/va_vca`). Emulates a voltage-controlled amplifier. 
* Replaced the custom EG and VCA implementations in `paia/fatman`, `linn/linndrum` and `oberheim/dmx` with the ones above.
This also required moving initialization and triggering code from the custom VCA devices in the `linndrum` and `dmx` into the core audio device in each driver.
Followed the naming and EG structure suggestions in  #13531. Open to additional suggestions of course.
=> Implemented VA EG (Envelope Generator) and VCA (Voltage Controlled Amplifier) sound devices.

src/devices/sound/c6280.cpp, src/devices/video/huc6202.cpp, src/devices/video/huc6202.h, src/devices/video/huc6260.cpp, src/devices/video/huc6260.h, src/devices/video/huc6270.cpp, src/devices/video/huc6270.h
Common:
- Fix typename for fix save state support
- Use lowercase hexadecimal values
- Fix spacings
sound/c6280.cpp:
- Minor volume/LFO accuracy fixes
- Use reference instead pointer
video/huc6202.cpp:
- Fix typename inconsistency
video/huc6260.cpp:
- Fix save state
video/huc6270.cpp:
reference: https://github.com/tildearrow/furnace/issues/88#issuecomment-1052483501
=> Various PC Engine related fixes/Cleanups/Updates:

src/devices/video/mb_vcu.cpp, src/devices/video/mb_vcu.h, src/mame/stern/mazerbla.cpp
Common:
- Remove unnecessary includes
- Fix spacings
devices/video/mb_vcu.cpp:
- Use device_palette_interface for palette functions
- Use required_address_space for host memory accessing
- Use logmacro for logging
- Add helper for VRAM addressing
- Cleanup 2bpp gfx drawing, Screen update function
- Fix initialization
- Fix namings
stern/mazerbla.cpp:
- Remove unnecessary palette device and inits
- Reduce unnecessary trampolines
- Fix filename/directory in comments
=> stern/mazerbla.cpp, devices/video/mb_vcu.cpp: Updates/Cleanups:

src/devices/sound/va_eg.cpp, src/devices/sound/va_eg.h
* Actually take a voltage snapshot when R or C change. This was being attempted, but didn't work because set_target_v would exit early if the target was not changing. No existing systems were affected, since setting R was always followed by setting a new target.
* Consider the EG done based on elapsed time, instead of proximity to target value. Some low volume DMX sounds (the quiet Bass and Hat variations), were affected by this.
=> sound/va_eg.cpp: Fixed subtle bugs.

src/devices/sound/dac76.cpp, src/devices/sound/dac76.h, src/mame/linn/linndrum.cpp, src/mame/oberheim/dmx.cpp
* Added support for reference current (multiplying capability).
* Added support for voltage output.
* Added support for streaming reference current.
* Used those capabilities in `oberheim/dmx.cpp` and `linn/linndrum.cpp`.
I went with this approach because it better matches the real device. The DAC76 is a multiplying DAC. But I can think of some alternative implementations. @galibert or others, let me know if one of those is preferable:
1. Add a `configure_dac76_voltage_output()` in `sound/va_vca`, and have drivers that need multiplying capability always follow the `dac76_device` with a `va_vca_device`. This is similar to the implementation before this PR, but the dac76-specific logic will move from individual drivers to `va_vca`.
1. Add an `mdac76_device` subclass in `sound/dac76`, so as …
=> sound/dac76.cpp: Emulating multiplying capability and using it in dmx and linndrum.

src/mame/sega/model2.cpp, src/mame/sega/model2.h, src/mame/sega/model2_v.cpp
Polygons in later windows are always drawn after polygons from earlier windows, regardless of z value. This appears to fix z-sorting in all games that I have tested. At the moment I'm leaving the "bucket sort" implementation intact but I wonder if there's a better way to do it. I would guess that the real hardware is performing an insertion sort since it can z-sort the polygons as they are being received from the geometry DSPs.
Four planes representing the visible frustum are now used for polygon clipping, rather than a single plane for z-clipping. It is no longer necessary to add 1.0 to z during projection to prevent texture corruption, and so objects very close to the camera (such as the course map in Daytona, which has a z value of 0.00009) are now visible at the correct size and …
=> model2: improve z-sort and clipping

hash/megadriv.xml
Beyond Zero Tolerance (prototype 19950714) [Hidden Palace]
Eyra - The Crow Maiden (digital release) [no-intro]
Zero Tolerance (Europe, USA) (rev. C) [no-intro]
Zero Tolerance (from "QUByte Classics: Zero Tolerance Collection by PIKO" on Switch eShop) [no-intro]
Zero Tolerance (Germany) [no-intro]
Zero Tolerance Underground (from "QUByte Classics: Zero Tolerance Collection by PIKO" on Switch eShop) [no-intro]
Zero Wing (Retro-Bit) [no-intro]
Zombies Ate My Neighbors (Limited Run Games) [no-intro]
=> megadriv.xml: Added 8 working items

src/devices/machine/6522via.cpp, src/devices/machine/m68sfdc.cpp, src/devices/machine/mc6852.cpp, src/devices/machine/mc6852.h, src/mame/act/victor9k.cpp
Audio on the Victor 9000 was not working, mainly due to missing functionality on the transmit path of the mc6852 SSDA.
Summary of changes:
- mc6852: Add code to initiate serial output of transmit data.
- mc6852: Implement transfer complete callback, which keeps sending data from FIFO, and sends sync or mark codes upon FIFO underrun.
- mc6852: fix a couple of small coding errors.
- mc6852/m68sfdc: Add a function to allow an existing (unorthodox?) transmit mechanism to continue working, to avoid breaking m68sfdc
- 6522via: software running on the victor9k seems to rely on a hardware behavior that wasn't implemented in the emulator: setting the counter latch value to 0 produces a high-frequency output on PB7 in continuous mode, but software expects this not to output a clock signal on PB7 …
=> Get audio working on Victor 9000 (victor9k)

hash/ibm5150.xml, hash/ibm5170.xml, hash/ibm5170_cdrom.xml, hash/ibm5170_hdd.xml
This one is installed with the CD-ROM version of the operating system, and the “Full” installation option selected.  It is much more representative of what FreeDOS is supposed to be than using the floppy disk set as in the previous image.
I've also made a repository to preserve and document the INP files used to create the FreeDOS disk images: https://github.com/chungy/mame-reprod-chd/tree/master/freedos13
=> hash/ibm51*.xml: New FreeDOS 1.3 hard disk image, FreeDOS 1.4 images

src/devices/machine/rescap.h, src/mame/linn/linndrum.cpp, src/mame/oberheim/dmx.cpp
Used it in oberheim/dmx.cpp and linn/linndrum.cpp.
=> machine/rescap.h: Implemented audio potentiometer law.

src/mame/mame.lst, src/mame/phoenix/phoenix.cpp
Fenix (Explomatic, Spanish bootleg of Phoenix) [Jordi Tuells]
=> phonenix/phoenix.cpp: Add a new Spanish bootleg of Phoenix

src/devices/cpu/avr8/avr8.cpp, src/mame/handheld/pensebem.cpp, src/mame/makerbot/replicator.cpp, src/mame/skeleton/venteta.cpp, src/mame/ultimachine/rambo.cpp
- Fix address mask (word(2 byte) unit)
- Fix boot size
- Fix PC shifting in state_string_export
- verified from their datasheets
handheld/pensebem.cpp: Fix internal ROM region size
makerbot/replicator.cpp: Use lowercase hexadecimal values
skeleton/venteta.cpp: Fix CPU type for fix PC size (16 bits - also word unit) and internal RAM size (4000 bytes)
ultimachine/rambo.cpp: Fix internal ROM region size, Use lowercase hexadecimal values
=> cpu/avr8/avr8.cpp: Updates:

src/devices/machine/msm6200.cpp, src/devices/machine/msm6200.h, src/devices/sound/upd934g.cpp, src/devices/sound/upd934g.h, src/emu/xtal.cpp, src/mame/casio/cps2000.cpp, src/mame/casio/cz1.cpp, src/mame/mame.lst
Also some fixes to the uPD934 and MSM6200.
----------
Casio CPS-2000 [BCM, Devin Acker]
=> Add skeleton for Casio CPS-2000

src/devices/sound/flt_biquad.cpp, src/devices/sound/flt_biquad.h, src/mame/layout/linn_linndrum.lay, src/mame/linn/linndrum.cpp
Primary changes:
* Hihat decay knob will have an effect even if changed during playback.
* Modeling the "click" filter. Validated with a [simulation](https://falstad.com/circuit/circuitjs.html?ctz=CQAgjCAMB0l3BWEAmAbAZlqgHKsBOSZffMdVEBSSy6hAUwFowwAoAdxABY4Ufuu2PtUisAxgKHJ+CMMmHdwTITFQJUcAkQDs6rsm3oosSBBhtOs+dLr5r-UZbsKEzg-NETX17fO8h0ZGoubmhtZRBGGFMiQnUwSG1IfDxIBCNo0yhWAHNKZ0DbeXRyKGyne2pUXwVHEGrK+pr3bIAnJp95BoDS6mkwVFyOnopu9AQPcuGbEF8+h1YwJO5eceKJgI2IIJR4aggLYfVqOcoNbLzutVGa7pFWdu7-K-UyuUhBzifzp+c6-2OR3OojyzxkzmuZU8+T8zjBwVC4UYQiiJgm6mO2kMXHQSS4SEyZg4MLORRJ0K4glJlDk1JCYAiqlQeGZ2kpS30pgohOMhx4dHOlKEgNE7Ss1IBwJ6umJ-M28jlMzqcrWKwF9wAHrN9HwkAkqdIhPSQgAJAAKADEADoAZwAFOwABb0AB2toAbgB7AA2AFcALb0W0270ASwAJvRWrbQzbbQBDAAutoSkAApABKaC2gAy9AAZsmbTaxJ6AA70aCsLWGfBnCgJUrqOvGkAAIUttodzrdNq9fsDwbDkejNoAP …
=> linn/linndrum.cpp: Modeled click filter, improved hihat decay emulation, and did cleanups.

hash/sgx.xml
Replaced "cartridges" to "HuCards" on the software list description.
=> sgx.xml: Changed media description

src/mame/seta/ssv.cpp, src/mame/skeleton/tsispch.cpp
This PR fixes address range for DSP accessing after https://github.com/mamedev/mame/pull/13530 .
=> seta/ssv.cpp, skeleton/tsispch.cpp: Fix address range after https://github.com/mamedev/mame/pull/13530

src/devices/video/ef9345.cpp
Before this commit, characters with the double-height attribute (H) were scaled by equally repeating all their scanlines twice.
In the real chip, the first scanline is repeated three times and the last one only once.
---
Image comparisons (source code [here](https://github.com/fabio-d/minitel-ef9345-testsuite/blob/512d2378df58b25683431e9b077d3fa9b13f88c8/tests/test_size.py#L103)):
* real output from both EF9345 and TS9347 chips (captured via a [custom board](https://github.com/fabio-d/minitel-ef9345-testsuite/tree/main/hw_devboard)):
* current MAME output:
The four boxes show the four different scaling modes supported by the chip:
1. Regular size (i.e. no scaling)
1. Double width
1. Double height
1. Double width and height
As you can see, in the last two boxes (those involving double …
=> ef9345: apply same double-height scaling as the real chip

src/devices/cpu/nec/v5x.cpp, src/devices/cpu/nec/v5x.h, src/devices/machine/i8251.cpp, src/devices/machine/i8251.h, src/devices/video/hd44352.cpp, src/mame/casio/fz1.cpp, src/mame/mame.lst
and also
- implement internal serial interrupt for V50 (and made serial signals other than Tx/Rx exclusive to the V33, since other chips don't have those pins)
- support alternate screen dimensions for HD44352
----------
Casio FZ-1 Digital Sampling Synthesizer [Rainer Buchty, Devin Acker]
----------
Casio FZ-10M Digital Sampling Synthesizer Module [Tom Virostek, Devin Acker]
Casio FZ-20M Digital Sampling Synthesizer Module [BCM, Devin Acker]
=> add preliminary driver for Casio FZ series samplers

src/mame/gaelco/gaelco2.cpp, src/mame/mame.lst
Touch and Go (North America, 14/Nov/1995, checksum 05737572) [Josep Quingles, Recreativas.org]
Touch and Go (non North America, 16/Nov/1995, checksum 056533F0) [Josep Quingles, Recreativas.org]
Touch and Go (non North America, 15/Nov/1995, checksum 056C2336) [Josep Quingles, Recreativas.org]
Touch and Go (non North America, 15/Nov/1995, checksum 056C138F) [Josep Quingles, Recreativas.org]
=> gaelco/gaelco2.cpp: Sorted out Touch and Go sets and add missing ones

src/mame/sega/model2_v.cpp
MAME no longer hangs when exiting Sonic the Fighters service menu
=> sega/model2: prevent infinite loop in geo_parse()

src/devices/cpu/i960/i960.cpp
128 bytes of padding was resulting in stack overflow during the Virtual-On ranking screen, crashing MAME. Reducing the padding to 64 bytes prevents the stack overflow while still ensuring that saved local registers are not overwritten by the processor state.
It should be noted that the actual i960 behavior is to save the processor state before performing the call operation ([source](http://bitsavers.informatik.uni-stuttgart.de/components/intel/i960/80960KB_Programmers_Reference_Manual_Mar88.pdf), 8-5), though this is unlikely to result in any difference in operation.
=> cpu/i960: Reduce padding area size when servicing interrupt

src/mame/gaelco/mastboy.cpp, src/mame/mame.lst
Master Boy (Spain, set 3, checksum 6070) [Josep Quingles, Recreativas.org]
Master Boy (Spain, set 4, checksum CC6D) [Josep Quingles, Recreativas.org]
Master Boy (Italy, set 3, checksum 6918) [Josep Quingles, Recreativas.org]
Master Boy (Italy, set 4, checksum 680C) [Josep Quingles, Recreativas.org]
Master Boy (Italy, test version) [Josep Quingles, Recreativas.org]
Master Boy Olympic (Italy, set 1, checksum 77A8) [Josep Quingles, Recreativas.org]
Master Boy Olympic (Spain, set 1, checksum 7309) [Josep Quingles, Recreativas.org]
Master Boy Olympic (Spain, set 2, checksum 741B) [Josep Quingles, Recreativas.org]
Master Boy Version II (Italy, set 1, checksum 618F) [Josep Quingles, Recreativas.org]
Master Boy Version II (Spain, set 1, checksum 5A0B) [Josep …
=> gaelco/mastboy.cpp: Sorted out Master Boy sets and added missing ones

src/mame/dataeast/brkthru.cpp, src/mame/mame.lst
Has the same ROMs as the original World version
=> dataeast/brkthru.cpp: Remove brkthrubl

src/osd/modules/debugger/win/consolewininfo.cpp, src/osd/modules/debugger/win/debugwininfo.cpp, src/osd/modules/debugger/win/debugwininfo.h, src/osd/modules/debugger/win/disasmbasewininfo.cpp, src/osd/modules/debugger/win/disasmwininfo.cpp, src/osd/modules/debugger/win/editwininfo.cpp, src/osd/modules/debugger/win/editwininfo.h, src/osd/modules/debugger/win/memorywininfo.cpp
For the wininfos that participate as individual panes in the main console window, their viewinfos are referenced via the m_views[] array with hard-coded indices of 0, 1, and 2.
- Define & use enums for those indices (VIEW_IDX_DISASM, VIEW_IDX_STATE, VIEW_IDX_CONSOLE)
- Change MAX_VIEWS from a hard-coded constant of 4 to the last enum in that list, which changes it to 3.  (I don't think it should have been 4 in the first place.)
- wininfos that NEVER appear as panes in the main console window (e.g., logwin_info, pointswin_info, etc.) continue to use m_views[0]
This cleanup was originally written as part of my large source-level debugging PR (#13444), so merging this will shrink that somewhat.
=> [win] debugger cleanup: use enums for m_views indices

src/mame/mame.lst, src/mame/pinball/gts3a.cpp
Cue Ball Wizard (Spanish) [Victor Fernandez (City Game), Jordi Beltran (Crazy Taxi)]
=> pinball/gts3a.cpp: Add a Vifico licensed version of Cue Ball Wizard

src/osd/modules/debugger/osx/debugview.mm
The Cocoa debugger has an annoying bug where the first time the console "overflows" the bottom, the view will not scroll.
This patch includes a workaround to skip frame size notifications in the middle of the text update, and this seems to fix the issue.
https://github.com/user-attachments/assets/13edad06-76cc-4f65-bcbb-98f936225fb9 
https://github.com/user-attachments/assets/b3a9a118-748b-4984-a2da-5d82f40237db
=> cocoa debugger: debug view scroll workarounds

src/mame/gaelco/gaelco2.cpp, src/mame/mame.lst
Bang! (version 2, checksum 140E) [Josep Quingles, Recreativas.org]
Bang! (version 2, checksum D35D) [Josep Quingles, Recreativas.org]
Gun Gabacho (Japan, version 2, checksum 1C8C) [Josep Quingles, Recreativas.org]
Gun Gabacho (Japan, version 2, checksum B75B) [Josep Quingles, Recreativas.org]
Old 'bang' set has been renamed to 'bangb', as it's the older version, and the new V2 set with checksum 140E becomes the new parent.
=> gaelco/gaelco2.cpp: Add four new Gaelco Bang sets

src/mame/gaelco/gaelco3d.cpp, src/mame/mame.lst
Football Power (version 4.6) [Josep Quingles, Recreativas.org]
Football Power (version 1.4) [Josep Quingles, Recreativas.org]
The old parent set, 'footbpow', has been renamed to 'footbpow12', and the new v4.6 becomes the new parent
=> gaelco/gaelco3d.cpp: Add two more Football Power sets

src/devices/cpu/mb86235/mb86235.cpp, src/devices/cpu/mb86235/mb86235.h, src/devices/cpu/mb86235/mb86235d.cpp, src/devices/cpu/mb86235/mb86235defs.h, src/devices/cpu/mb86235/mb86235drc.cpp, src/devices/cpu/mb86235/mb86235fe.cpp, src/devices/cpu/mb86235/mb86235ops.cpp, src/mame/sega/model2.cpp
Most Sega Model 2C-CRX games are now working with 3D graphics. Top Skater still doesn't display properly because it uses a secondary transformation matrix which is not implemented in the HLE geometry engine; proper emulation of the geometry DSP is required.
Resubmitting because the previous pull request failed validation due to unrelated commits that have since been fixed. Hopefully it should pass this time
=> cpu/mb86235: Improve TGPx4 interpreter

src/mame/skeleton/whtm68k.cpp
since required rom banking at 8000-FFFF so demoted to imperfectly sound
Bank 1 music 1-4
at 8000-FFFF
Bank 2 music 1-3
at 10000-17FFF
Bank 3 music 1-3
at 18000-1FFFF
at dip switch 2 seem to be input?
sw2 3 left
sw2 4 right
sw2 5 bet
sw2 6 start
sw2 8 pay out
=> demote to imperfectly sound whtm68k.cpp

src/emu/debug/debugcmd.cpp, src/emu/debug/debugcpu.cpp, src/emu/debug/express.cpp, src/emu/debug/express.h, src/frontend/mame/cheat.cpp, src/frontend/mame/luaengine_debug.cpp
This addresses issue #6655 (symlist command usability), plus adds a bit of plumbing for future extensibility.
The distinction between global and CPU symbols is unclear to most who don't read the source, so this makes `symlist` more natural:
- `symlist` with no arguments displays all global *and* :maincpu symbols, with clear header text for each list.  At the bottom, prints helper text to make user aware of the cpu form
- `symlist <cpu>` works as it has before, only displays symbols for specified CPU
This pr includes some changes in anticipation of features that add new kinds of symbol tables.  Example: the source-level debugging pr (#13444) adds symbol tables for local and global variables that appear in the debugged source code.  The following were originally part of the source-level …
=> debugger: symlist usability + symbol table extensibility

src/mame/tandberg/tdv2100_disp_logic.cpp
I had a closer look at the schematics and a few of the jumper-settings in the manual, and realized a few things:
1. A handful of jumpers had their polarity wrong, leading to wrong default settings
2. The latching of the attribute happens on the rising edge of the character-clock, i.e. active with the character immediately following the change
=> Fix tdv2100 display edge-cases

src/mame/gaelco/gaelco.cpp, src/mame/mame.lst
Thunder Hoop (ver. 1, checksum 02a09fcd) [Josep Quingles, Recreativas.org]
Thunder Hoop (ver. X, checksum 00000020, without title) [Josep Quingles, Recreativas.org]
Thunder Hoop (North America, ver. C4, checksum 02A0A008) [Josep Quingles, Recreativas.org]
Thunder Hoop (non North America, ver. X, checksum 00000020, set 1) [Josep Quingles, Recreativas.org]
Thunder Hoop (non North America, ver. X, checksum 00000020, set 2) [Josep Quingles, Recreativas.org]
=> gaelco/gaelco.cpp: Add new Thunder Hoop sets

src/mame/mame.lst, src/mame/pinball/gts3a.cpp
Super Mario Brothers (pinball, Spanish) [Victor Fernandez (City Game)]
Sadly, it's missing the Display ROM (it was damaged).
=> pinball/gts3a.cpp: Add the Vifico-licensed version of Super Mario Bros pinball

src/lib/formats/phc25_cas.cpp, src/mame/sanyo/phc25.cpp
When trying to load the WAV file produced by castool on a real phc-25, we noticed that the program is not detected and the loading fails.
We compared with a working WAV file and noticed that the baud polarity is inverted. If we invert the polarity in the WAV file produced by castool, then it loads correctly on real hardware.
This PR proposes to invert the cassette polarity both in the machine and in the format ; this is a noop for people loading a .phc file in MAME, but should fix using castool for the real target.
=> phc25: Invert cassette polarity.

src/devices/video/ppu2c0x.h, src/devices/video/ppu2c0x_vt.cpp, src/devices/video/ppu2c0x_vt.h, src/mame/nintendo/nes_vt32_soc.cpp, src/mame/nintendo/nes_vt32_soc.h, src/mame/nintendo/nes_vt369_vtunknown.cpp, src/mame/nintendo/nes_vt369_vtunknown_soc.cpp, src/mame/nintendo/nes_vt369_vtunknown_soc.h, src/mame/nintendo/nes_vt_soc.cpp, src/mame/nintendo/nes_vt_soc.h
- added basic support for 'high resolution' mode on VT369 (currently renders at standard resolution, but the tiles used are now correct)
- added another new sprite mode, used in high res mode
- menus are now visible in rtvgc300, rtvgc300fz, background is visible on image match in lxcmcysp is visible
- moved some VT32 specific code to the VT32 device as it was preventing aero engine in the rtvgc300 sets from working
- split VT32 PPU into its own derived device
- added preliminary support for a new VT32 (or maybe a newer variant of it) specific(?) video mode used by lxpcsp and maybe a few others
- added VT32 specific support for a bitswap on PPU character data pulls used by some titles (some of the bonus games in myaasa etc.)
- improved a few notes
=> vt369 - allow rtvgc300/rtvgc300fz to display menus / select games, vt32 - preliminary support for new video mode used by lxpcsp 

src/mame/mame.lst, src/mame/olivetti/celint2k.cpp
Olivetti Celint 2000 (Superfono Santander edition) [ArcadeHacker]
=> Skeleton driver for Olivetti Celint 2000

src/mame/gaelco/glass.cpp, src/mame/mame.lst
Glass (Ver 1.1, Break Edition, checksum 49D5E66B, Version 1994, set 1) [Josep Quingles, Recreativas.org, David Haywood]
Super Splash (Ver 1.1, Break Edition, checksum 59D5E66B, Version 1994) [Josep Quingles, Recreativas.org, David Haywood]
Glass (Ver 1.1, Break Edition, checksum D7AF5496, Version 1994, US) [Josep Quingles, Recreativas.org, David Haywood]
Glass (Ver 1.1, Break Edition, checksum 3D8A724F, Version 1994, unprotected, Korea) [Josep Quingles, Recreativas.org, David Haywood]
Glass (Ver 1.0, Break Edition, checksum EBCB0BFE, 22 Nov 1993) [Josep Quingles, Recreativas.org, David Haywood]
Glass (Ver 1.0, Break Edition, checksum 6241CD67, 16 Nov 1993) [Josep Quingles, Recreativas.org, David Haywood]
Glass …
=> gaelco/glass.cpp: Add new sets (new parent too)

src/mame/trs/coco3.cpp
This fixes a hang on start that many people experienced.
=> trs/coco3.cpp: Change order of GIME initialization.

src/devices/machine/mm58174.cpp, src/devices/machine/mm58174.h
Fix/Update MM58174 implementation based on data sheet and current style conventions
- Add conditional logging, instead of using 'logerror' for regular port reads/writes
- Properly handle leap year status register writes and base RTC year updates
- Use upper-case for existing constants
- Use constants for register addresses
- Don't call fatalerror() for port writes to interrupt control register with unexpected values
- Fix saving of class variables by changing to fixed size ints.
- Mask off unused data pins when writing to registers (data sheet - "Any unused data pins will be ignored during a write operation (e.g., days of week uses only DB2 through DB0)."
=> machine/mm58174.cpp: Improve chip emulation based on data sheet

src/mame/mame.lst, src/mame/tvgames/generalplus_gpl16250_rom.cpp, src/mame/tvgames/spg110.cpp, src/mame/tvgames/spg2xx_jakks.cpp, src/mame/tvgames/spg2xx_jakks_gkr.cpp
redumped "Wall-E (JAKKS Pacific TV Game) (Dec 18 2007 11:34:25)" [TeamEurope]
------------
1 Vs 100 (JAKKS Pacific TV Game) [David Haywood, Sean Riddle, TeamEurope]
Avatar: The Last Airbender - Book One Challenges (JAKKS Pacific TV Game) (06 Jun 2006 A) [David Haywood, Sean Riddle, TeamEurope]
X-Men - Mutant Reign (JAKKS Pacific TV Game) [David Haywood, Sean Riddle, TeamEurope]
Jeopardy (JAKKS Pacific TV Game) [David Haywood, Sean Riddle, TeamEurope]
Are You Smarter than a 5th Grader? (JAKKS Pacific TV Game) [David Haywood, Sean Riddle, TeamEurope]
------------
Thomas & Friends - Right on Time (JAKKS Pacific TV Game) (Jun 28 2006 18:24:37) [David Haywood, Sean Riddle, TeamEurope]
The Price Is Right (JAKKS Pacific TV Game) (Mar 24 2009 …
=> current JAKKS Pacific PR - 1 redump, 8 new sets

src/mame/gaelco/splash.cpp, src/mame/mame.lst
New Splash (ver. 1.4, checksum A26032A3, Korea, set 1) [Josep Quingles, Recreativas.org]
New Splash (ver. 1.4, checksum A26032A3, Korea, set 2) [Josep Quingles, Recreativas.org]
Splash! (ver. 1.1, checksum 4697D2BF, non North America) [Josep Quingles, Recreativas.org]
=> gaelco/splash.cpp: Add more Splash clones 

src/mame/gaelco/glass.cpp, src/mame/mame.lst
Super Splash (Ver 1.0, checksum 2104394E, 27 Oct 1993) [Josep Quingles, Recreativas.org, David Haywood]
=> gaelco/glass.cpp: Add a new Super Splash set (not working) 

src/mame/sega/segahang.cpp
I think it's copy-paste error or confused with 2xYM2203/YM2151 sound set?
=> sega/segahang.cpp: Fix PCM sample loading for endurobl

src/mame/sinclair/specnext.cpp
Not all layer blendings are implemented (noted in comments) but this message scares users. I would prefer receive bugreports about incompatible software because currently there are no known soft which can be used for such modes testing.
=> sinclair/specnext.cpp: Removed IMPERFECT_GRAPHICS flag

src/devices/cpu/m6800/m6801.cpp
Noticed this because the tr707 uses the ICR to compute the displayed tempo. The issue can be reproduced in #13798: the tempo display is erratic. Applying this PR fixes it.
Sending as a separate PR because the modified code is used more broadly.
I verified that `icrh_r` and `icrl_r` are mapped to the correct addresses for the high and low bytes of the ICR respectively. But they were returning the low and high bytes instead.
=> cpu/m6800/m6801.cpp: Corrected the ICR read handlers.

src/mame/sega/model1_m.cpp, src/mame/sega/model2.cpp
Calculating `index ^= 0x3fff` when `ang & 0x4000` was leading to results that were not always completely accurate; for example, calculating sin when ang = 0x2000 (equivalent to 45 degrees) gives a result of 0.70710677 which is accurate to single precision, but ang = 0x6000 (equivalent to 135 degrees) gives a result of 0.707039 which is very slightly off. This tiny error wasn't making any discernible difference in most games, but for some reason it was messing up Daytona; at very specific angles the player car would move sideways during a frame instead of forwards, and the camera would rotate to follow the car moving sideways:
Changing the calculation to `index = std::min(0x4000 - (int)index, 0x3fff)` makes it so the results are always accurate, and the above bug no longer occurs. Clamping …
=> model1/model 2: TGP sin/cos lookup tables

src/devices/machine/mos6551.cpp, src/devices/machine/mos6551.h
**Context:**
This pull request aims to fix a discrepancy between MAME emulation of the 6551 and real life. I have written in the last monthes an Apple II audio/video streamer, which works over two 6551 serial ports at 115200 bps, getting data from a serial proxy. In this project, there are not enough cycles available to handle the Status register read before reading the Data register on both ports, so I chose to check Status before reading Data on the video stream, and blindly read Data on the audio stream. The rationale being that it is not a problem to misread an audio sample, whereas it would be a problem to misread a video byte.
The audio bytes are used to update a JMP target and branch to the next duty cycle. Each duty cycle does PWM for sound check if a video byte if present, …
=> MOS6551: correctly transfer data from RSR to RDR

src/mame/konami/contra.cpp
Confirmed on hardware that both reads and writes will ping the watchdog.  Additionally reading the watchdog address always returns 0xff.
=> contra: add missing watchdog

src/mame/konami/tmnt2.cpp
Trigon schematics show a pull-up resistor at the NMI pin. However, the driver connects that signal.
This PR removes the connection in the driver. The sound is not affected after the change.
I created a separate branch in my fork for this, so feel free to push other changes to it.
=> lgtnfght: removed NMI connection as it does not exist on schematics.

scripts/src/osd/sdl.lua
The vast majority of the OSes use `BASE_TARGETOS=unix` and `SDLOS_TARGETOS=unix`, which are set as default values; the few exceptions (Windows and macOS) already have their own selections.
Hence drop all the empty if statements for other OSes than Windows and macOS, as actually redundant.
=> osd: remove redundant checks when setting BASE_TARGETOS/SDLOS_TARGETOS

src/mame/dataeast/dec8.cpp, src/mame/dataeast/dec8.h, src/mame/dataeast/dec8_v.cpp
NMI on the 6309 comes from the 74LS00 @ 13C (dual input NAND gate) where input 1 is vblank and input 2 comes from a latch (74LS273 @ 3A). The latch gets updated with writes to 0x3840, which is what you write to to enable/disable NMI.  So there is no hardware logic to ACK NMIs.
=> ghostb: there is no ACK for NMIs

src/mame/act/victor9k.cpp
A line of code was inadvertently dropped during conflict resolution prior to merging https://github.com/mamedev/mame/pull/13583.  This resulted in the hard disk disappearing.
Thanks to @pauldevine for catching this.
=> victor9k: Restore line of code inadvertently removed, causing hard disk to disappear

src/osd/modules/file/posixptty.cpp
There is no defined size for the slave name returned by `openpty()`; OSes that have a `PATH_MAX` constant usually use that as limit. Create a custom `OPENPTY_PATH_MAX` constant specifically for `openpty()`, even in case `PATH_MAX` is not available: in that situation, use 8192 as buffer size, which hopefully should be "good enough".
=> osd/modules/file: define buffer size for openpty()

hash/ekara_cart.xml
new software list additions
-----------
ekara_cart.xml
e-kara Web cartridge 28M (used, with 26 songs) (Japan) [David Haywood, TeamEurope]
e-kara Web cartridge 12M (used, with 12 songs, set 2) (Japan) [David Haywood, TeamEurope]
e-kara Web cartridge 12M (used, with 12 songs, set 3) (Japan) [David Haywood, TeamEurope]
e-kara Web cartridge 12M (used, with 12 songs, set 4) (Japan) [David Haywood, TeamEurope]
e-kara Web cartridge 12M (used, with 12 songs, set 5) (Japan) [David Haywood, TeamEurope]
e-kara Web cartridge 12M (used, with 12 songs, set 6) (Japan) [David Haywood, TeamEurope]
e-kara Web cartridge 12M (used, with 12 songs, set 7) (Japan) [David Haywood, TeamEurope]
e-kara Web cartridge 12M (used, with 12 songs, set 8) (Japan) [David Haywood, TeamEurope]
e-kara Web cartridge 12M (used, …
=> added 12 (used) e-karaweb user carts, and KD-4

src/mame/layout/wackygtr.lay
Actual hardware:
Current internal layout in MAME:
Improved layout included in this pull request:
=> [Wacky Gator] Internal layout improvements

src/mame/sega/model2.cpp, src/mame/sega/model2.h
Most revisions of Model 2 feature an NEC D71051C (Intel 8251 compatible) serial controller which is used to communicate with the Model 1 sound board and/or the SCSP; this is accessed over the 16-bit secondary bus at address 0x1C80000.
But the Model 2B-CRX does not feature a standalone D71051C. Instead it has an 8251-compatible serial controller built into the 315-5797 buffer controller (Model 2B manual chapter 6), which is accessed over the 32-bit primary bus at address 0x9C0000.
All Model 2 games have been tested and have sound working.
=> sega/model2.cpp: sound comms

src/devices/sound/dac76.cpp, src/devices/sound/dac76.h, src/devices/sound/va_eg.cpp, src/devices/sound/va_eg.h, src/devices/sound/va_vca.cpp, src/devices/sound/va_vca.h, src/mame/casio/cps2000.cpp, src/mame/linn/linndrum.cpp, src/mame/moog/source.cpp, src/mame/oberheim/dmx.cpp, src/mame/paia/fatman.cpp, src/mame/roland/roland_tr707.cpp
Implemented the suggestion in #13860, for `va_eg` (first commit in this PR).
I also noticed there is a `get_sound_requested_inputs()`, which `sound/dac` uses to automatically switch to streaming ranges. So I did something similar for `va_vca` and `dac76`, and got rid of the `configure_streaming_*` functions. @galibert, I am assuming this is preferable, given the suggestion in  #13860, but let me know if I should just stick to the `va_eg` changes.
This change also required adapting `cps2000` to the new sound engine. Other than that, this PR is a behavioral no-op.
=> sound/[va_eg, va_vca, dac76]: Automatically adapt to the  input and output connections.

src/mame/taito/arkanoid.cpp
Added the year for hexa and clone hexaa according to the entry in the GRB archived scans: https://web.archive.org/web/20160508161306/http://www.grb.or.kr/download/GameImage/1999/%EC%A0%9C769%ED%98%B8.jpg
=> arkanoid.cpp: corrected Hexa release year

hash/pv1000.xml
Inufuto has released two additional homebrew games since last addition. The new games are:
pv1000: Mieyen, Mazy2 [inufuto]
This PR adds both games to Inufuto's 16 homebrew games already in the list. Both Mieyen and Mazy2 tested in a fresh MAME 0277 install + updated pv1000.xml file.
=> Add Mieyen and Mazy2 homebrew games to PV-1000 software list

src/mame/sega/model2.cpp, src/mame/sega/model2.h, src/mame/sega/model2_v.cpp, src/mame/sega/model2rd.ipp
With the implementation of lighting, stadium ads in Virtua Striker now have the correct colors.
Model 2 games set a "gamma curve" by using the color translate RAM. It is most likely that each cabinet has its monitor factory-calibrated to produce a desirable picture for the specific game it was designed to play. Virtua Fighter 2, Fighting Vipers and Sonic the Fighters feature adjustable bias and gain settings, presumably to allow software calibration when installing the game board into an Astro City or similar multi-purpose cabinet.
For now I have settled on the translation `raw_value = std::max(((double)i - 64.0) * 255.0 / 191.0, 0.0)` since this produces decent results for most games without requiring any game-specific adjustments. For the above titles which allow software calibration, …
=> sega/model2: implement proper lighting; improve "gamma" table

src/mame/gaelco/gaelco2.cpp
wrally2d is playing incorrect sounds in places, eg. for the title screen announcement.  I think it should be using different (older?) sound ROMs that aren't dumped.
=> Update gaelco2.cpp - mark wrally2d sound ROMs as incorrect

src/mame/mame.lst, src/mame/nintendo/nes_vt369_vtunknown.cpp
This is interesting as it's a VT369 (or possibly VT389) system that supports loading games from an SD card. Marked as NOT WORKING because the SD card support isn't emulated - the regular 150 built in games seem okay, although they're nothing special.
=> nes_vt369_vtunknown: Add GB-50

hash/duelmast_cart.xml, src/devices/video/ppu2c0x_sh6578.cpp, src/mame/mame.lst, src/mame/nintendo/nes_sh6578.cpp, src/mame/nintendo/nes_vt32.cpp, src/mame/nintendo/vt1682.cpp, src/mame/sega/mdconsole.cpp, src/mame/sega/mdconsole.h, src/mame/sega/megadriv_rad.cpp, src/mame/tvgames/elan_eu3a05.cpp, src/mame/tvgames/elan_eu3a05commonsys.cpp, src/mame/tvgames/spg2xx.cpp, src/mame/tvgames/spg2xx.h, src/mame/tvgames/spg2xx_jakks_gkr.cpp, src/mame/tvgames/trkfldch.cpp, src/mame/tvgames/xavix.cpp, src/mame/tvgames/xavix.h, src/mame/tvgames/xavix2.cpp, src/mame/tvgames/xavix_2000.cpp, src/mame/tvgames/xavix_2002.cpp, src/mame/tvgames/xavix_2002.h
this is a tidier / squashed version of https://github.com/mamedev/mame/pull/13875
----------
Hyakujuu Sentai Gaoranger: DX Soul Bird (Japan) [David Haywood, TeamEurope]
Mission: Paintball Trainer [David Haywood, TeamEurope]
Mission: Paintball [David Haywood, TeamEurope]
----------
Terebi de Asobou! Mickey & Minnie Mouse Kids (Japan) [David Haywood, TeamEurope]
Let's! TV Play Kage Hatsudou Taikan! Blue Dragon - Kiwamero! Fire Crisis! (Japan) [David Haywood, TeamEurope]
Beyblade Arcade Challenge 5-in-1 (US) [David Haywood, Sean Riddle, TeamEurope]
TV de Asobou! Manabou! Pooh-san to Issho: ABC AIUEO Zukan (Japan) [David Haywood, TeamEurope]
Let's TV Play Dragon Ball Z Battle Experience Kamehameha (Japan) [David Haywood, TeamEurope]
Family Tetris …
=> Current Plug + Play PR - added 18 sets, 3 working + 1 software list entry

src/osd/modules/debugger/debugwin.cpp, src/osd/modules/debugger/win/debugwininfo.cpp, src/osd/modules/debugger/win/debugwininfo.h
On Windows, the debugger has a special Windows-specific feature that drops the user into the debugger if the key sequence is pressed.  This seems to be present so that the key sequence triggers dropping into the debugger not just from the main window, but also from debugger windows.
This has also created an oddity where pressing the debugger key sequence from a MAME window will cause a "User-initiated break" but pressing it from a debugger window will cause "Internal breakpoint" to be displayed.
However, while this logic has a check to not apply when to a MAME window, it seems to also activate even if MAME itself is not in focus.  This change ensures that a stray debugger sequence in a completely unrelated application won't cause the user to be dropped in the debugger.
=> Windows:  Do not drop into debugger when no MAME window has focus

src/devices/cpu/mb86233/mb86233.cpp, src/devices/cpu/mb86233/mb86233.h, src/mame/sega/model2.cpp
The TGP code for Sega Rally and Manx TT have multiple instructions where both the ALU op and the transfer write to the same register D. Here is one of those instructions, from a subroutine that approximates square roots:
`01B3: 1D9DB24E fsmd : mov $0x4e, d`
Since commit 5363907, we emulate it so that the final value assigned to D is the result of the transfer rather than the ALU operation, but this results in the speed of the enemy cars being too slow compared to real hardware (both ElSemi's Model 2 Emulator and the PS2 release of this game bundled with Sega Rally 2006 have the same issue). If we change the register update priority for the above instruction only, the speed of the enemy cars in Sega Rally matches real hardware, without the bug where cars clip into the track and fly into …
=> cpu/mb86233: sort out register update priority

src/mame/apple/macpwrbk030.cpp
Comments in the file show:
// ADC 1 - battery level
// ADC 5 - battery temperature
// ADC 7 - "TABLE SEL" on the schematic
but the code has:
m_pmu->ad_in<1>
m_pmu->ad_in<5>
m_pmu->ad_in<8>
This causes array out-of-bounds exceptions in some builds
Ref https://github.com/mamedev/mame/issues/13352
=> Typo on MacBook battery ADC

src/lib/formats/all.cpp
IPF is included unconditionally by scripts/formats.lua, so the HAS_FORMATS condition was always false.
86F is also included unconditionally but simply wasn't added to formats/all.cpp when it was introduced.
I added 86F to the "Container FM/MFM" category for consistency with the grouping in devices/imagedev/floppy.cpp and moved IPF to the "PC" category for the same reason.
cf. 3b13ae6d7121b3e1de8e5aa48918f9f9b6567f7a, add6b4515206d5973ec7e3e30012a469fecc49bb
=> formats/all.cpp: Include IPF, 86F disk formats in floptool

scripts/src/3rdparty.lua
Since ba6f5853e9382a959af8ff81980c0f06a6ffe80e wayland is dynamically loaded at run-time.
=> No longer require wayland-egl-backend at compile-time

src/mame/philips/mcd212.cpp
This fixes #13968
Originally this flag made the cursor 2x as wide (4 pixels). However the Validation Disc (EU) test GC_Ptn has a clarifying comment that in double-resolution mode, the cursor should be half the width of the normal cursor.
This fixes this oversight.
Here's the comment
And with the fix
To validate, you can simply play `The Challenge (UK)` and notice the cursor looks properly sized, instead of 4x too wide.
=> CD-i: Fix Double Width Cursor

scripts/src/3rdparty.lua
was broken in 79bef1e23049fdac25f1fefd132e0b6c7d2cc3a1 by leaving a typo in 3rdparty.lua that had been fixed in LZMA source
not in this PR, but LZMA 25.00 is out btw
=> fix LZMA PPMD support

src/mame/casio/cz1.cpp
The second sound chip wasn't hooked up to the output correctly after the sound system rewrite. This restores the intended behavior, i.e.
- upd933 A goes to both speakers or only the left speaker
- upd933 B goes to both speakers or only the right speaker
=> cz1: fix audio routing

src/devices/cpu/z80/z80.lst, src/mame/sinclair/atm.cpp, src/mame/sinclair/byte.cpp, src/mame/sinclair/pentagon.cpp, src/mame/sinclair/scorpion.cpp, src/mame/sinclair/spec128.cpp, src/mame/sinclair/spec128.h, src/mame/sinclair/specpls3.cpp, src/mame/sinclair/spectrum.cpp, src/mame/sinclair/spectrum.h, src/mame/sinclair/spectrum_v.cpp
~~There is an issue with precise timings. Will try to sort that out next time.~~
=> sinclair/spectrum_v.cpp: Added ULA snow effect support [holub, spectramine]

scripts/src/sound.lua, src/devices/bus/nscsi/hd.cpp, src/devices/machine/mb87030.cpp, src/devices/sound/fz_pcm.cpp, src/devices/sound/fz_pcm.h, src/mame/casio/fz1.cpp
FZ samplers now make mostly correct sound, sans sampling support.
Some small SCSI-related changes were also made for fz20m:
* `nscsi_harddisk_device`: trying to write past the end of a drive now immediately signals an error (the system relies on this when detecting the size of a drive being formatted)
* `mb87030_device`: implement some small bits of missing behavior per datasheet
=> fz1 and clones: preliminary sound emulation, fz20m: fix SCSI hookup

src/devices/bus/spectrum/dma/slot.cpp, src/devices/machine/z80dma.cpp, src/mame/sinclair/sprinter.cpp
Existing problem with wait states in Sprinter is big performance pressure for the Accelerator related tasks.
This commit delivers trade-off for both preciseness and performance:
* Non batched (one step) operations are processed in CPU's running window using icount adjustment.
* Batched keep using own timer and put CPU in "real" WAIT state, but merging all iteration in single window.
=> sinclair/sprinter.cpp: Optimized wait state handling for performance. / Confirmed MACHINE_SUPPORTS_SAVE.

src/mame/philips/cdicdic.cpp, src/mame/philips/cdicdic.h
Fixes: https://github.com/mamedev/mame/issues/13991
This change simplifies several XA audio related functions by de-duplicating functionality. Finally, it fixes an error in the header offset. This fixes the garbled menu sounds in Golf Tips and it becomes the clear sound of a golfball.
=> CD-i: Fixes XA audio header offset

src/devices/sound/flt_biquad.cpp, src/devices/sound/flt_biquad.h, src/mame/linn/linndrum.cpp, src/mame/roland/roland_tr707.cpp
Consolidated RC BPF parameter calculation from  `linndrum.cpp` and `roland_tr707.cpp` into `flt_biquad.cpp`.
=> sound/flt_biquad: Added calculator functions for RC-based band-pass filters.

src/devices/sound/k053260.cpp, src/devices/sound/k053260.h, src/mame/konami/tmnt2.cpp
The sound interrupt for the Z80 is wrong on glfgreat. It should be the TIM2 output of the K053260. This output produces a pulse with a 2ms period, hence the pin name. Furrtek's schematics for this chip show the function.
The M68000 does not produce an interrupt on the Z80 on this board.
I have modified the files to implement this, but given my poor understanding of the MAME framework, something might be wrong. Particularly, the K053260 should set the interrupt request and it should not be cleared until the Z80 starts the interrupt execution. I do not know if my changes implement that correctly.
There is a note about wrong audio before but I have not really listened to the audio from the old driver as it must be wrong if a 500Hz interrupt becomes a random interrupt from the M68000. 
This …
=> glfgreat: uses k053260's TIM2 output as interrupt source.

hash/gbcolor.xml
New working software list additions (gbcolor.xml)
-------------------------------------------------
Super Mario Bros. Mini (v2.0.8) [chungy]
Super Mario Bros. Mini (v2.0.7) [chungy]
Super Mario Bros. Mini (v2.0.6) [chungy]
Super Mario Bros. Mini (v2.0.5) [chungy]
Super Mario Bros. Mini (v2.0.4) [chungy]
Super Mario Bros. Mini (v2.0.3) [chungy]
Super Mario Bros. Mini (v2.0.2) [chungy]
Super Mario Bros. Mini (v2.0.1) [chungy]
Super Mario Bros. Mini (v2.0.0) [chungy]
Super Mario Bros. Mini (v1.0.3) [chungy]
Super Mario Bros. Mini (v1.0.2) [chungy]
Super Mario Bros. Mini (v1.0.1) [chungy]
Super Mario Bros. Mini (v1.0.0) [chungy]
=> gbcolor.xml: Added Super Mario Bros. Mini (homebrew SMB port)

src/mame/ta/alphatpx.cpp
Performance issue: the entire screen was being updated when only a single scanline needed to be updated, causing 100% host CPU usage and non-realtime emulation.
=> alphatpx.cpp: Honor 'cliprect' in screen_update()

hash/juicebox.xml
Added to the list of known cartridges:
H6257 Yu-Gi-oh! Episode 229
H6236 Juice Box Music Video (Liz Phair, Stacie Orrico, Sarah Hudson, Steriogram)
=> added two cartridge names to juicebox.xml

hash/gaelco_ds5002fp_rom.xml, src/mame/gaelco/ds5002fp_programmer.cpp, src/mame/mame.lst
------
Gaelco DS5002FP Programmer [Javier Valero, Josep Quingles, Recreativas.org]
--------
gaelco_ds5002fp_rom.xml:
Alligator Hunt [Javier Valero, Josep Quingles, Recreativas.org]
Maniac Square [Javier Valero, Josep Quingles, Recreativas.org]
Target Hits [Javier Valero, Josep Quingles, Recreativas.org]
Glass [Javier Valero, Josep Quingles, Recreativas.org]
TH Strikes Back [Javier Valero, Josep Quingles, Recreativas.org]
Touch and Go [Javier Valero, Josep Quingles, Recreativas.org]
World Rally 2 [Javier Valero, Josep Quingles, Recreativas.org]
World Rally 2 (older) [Javier Valero, Josep Quingles, Recreativas.org]
=> new NOT WORKING machines - Gaelco DS5002FP Programmer

src/mame/toaplan/raizing_batrider.cpp
Added note about undumped bbakraid set: (Hong Kong) (Tue May 25 1999),  based on the non-unlimited version of the game
[https://www.youtube.com/watch?v=1Fm6kpPTZkM](https://www.youtube.com/watch?v=1Fm6kpPTZkM)
=> raizing_batrider.cpp: added note about undumped bbakraid set

src/mame/mame.lst, src/mame/misc/amaticmg.cpp
Multi Game III  (V.Int 3.63) [FakeShemp]
---
I changed this to be `am_mg3` and renamed the German versions to be `am_mg3g*`. As far as I understand, English versions should be "parents" if available.
=> misc/amaticmg: Add V.Int version of Multi Game III

src/mame/namco/namcos23.cpp
Hopefully this will fix the occasional no-polygons issue that some MAME developers have reported.
=> Namco System 23: Clear all machine-class members on reset

hash/psx.xml
Actua Pool (Europe) [Redump]
Adiboo & Paziral's Secret (Europe) [Redump]
Adibou et l'Ombre Verte (France) [Redump]
Alone in the Dark: Jack is Back (Europe) [Redump]
Alone in the Dark 2 (Japan) [Redump]
Amerzone: Das Testament des Forschungsreisenden (Germany) [Redump]
Amerzone: El Legado del Explorador (Spain) [Redump]
Amerzone: Il Testamento dell'Esploratore (Italy) [Redump]
Amerzone: O Testamento do Explorador (Portugal) [Redump]
Amerzone: The Explorer's Legacy (Europe) [Redump]
L'Amerzone (France) [Redump]
Pool Shark (Europe) [Redump]
TechnoMage: De Terugkeer der Eeuwigheid (Netherlands) [Redump]
TechnoMage: Die Rüeckkehr der Ewigkeit (Germany) [Redump]
Technomage: El Retorno de la Eternidad (Spain) …
=> psx.xml: Added 18 working items + 2 redumped items

src/emu/diserial.cpp
Avoid updating the data frame and resetting the receive register. The original change adding the reset of the receive register - https://github.com/mamedev/mame/commit/9070579622081991a899ba5d4fb1b6bb61084f6e cause a regression in the Heathkit H89 emulation, and the CPU and terminal boards (connected by 8250s) were not properly syncing. This caused garbled text.
Instead of the correct monitor prompt.
=> diserial.cpp: Avoid updating data frame if nothing changed

src/devices/imagedev/floppy.cpp
Since a feature like this seems to be commonly requested, and some of the new software in #14091 demands it, I'm showing how simple it is to implement. The intended usage is:
> `<feature name="write_protected" value="true" />`
to protect one disk image, or
> `<sharedfeat name="write_protected" value="true" />`
to protect all disk images. If other devs want to use a different name or value for this, please comment.
=> imagedev/floppy.cpp: Allow images to be write protected from software list

hash/megacd.xml
New working software list items:
Loadstar - The Legend of Tully Bodine (USA, prototype) [redump.org]
Snatcher (USA, prototype 19941007) [redump.org]
Star Wars - Rebel Assault (USA, re-release) [redump.org]
The Secret of Monkey Island (USA, re-release) [redump.org]
WireHead (Europe, prototype 19950912) [redump.org]
New non-working software list items:
Heavy Nova (Japan, prototype 19911102) [redump.org]
=> megacd.xml: Six software items added

scripts/src/bus.lua, src/devices/bus/heathzenith/h8/cards.cpp, src/devices/bus/heathzenith/h8/cpu8080.cpp, src/devices/bus/heathzenith/h8/front_panel.cpp, src/devices/bus/heathzenith/h8/h8bus.cpp, src/devices/bus/heathzenith/h8/h8bus.h, src/devices/bus/heathzenith/h8/h_8_1.cpp, src/devices/bus/heathzenith/h8/h_8_1.h, src/devices/bus/heathzenith/h8/h_8_5.cpp, src/devices/bus/heathzenith/h8/ha_8_6.cpp, src/devices/bus/heathzenith/h8/ha_8_6.h, src/devices/bus/heathzenith/h8/ha_8_8.cpp, src/devices/bus/heathzenith/h8/ha_8_8.h, src/devices/bus/heathzenith/h8/wh_8_16.cpp, src/devices/bus/heathzenith/h8/wh_8_16.h, src/devices/bus/heathzenith/h8/wh_8_64.cpp, src/devices/bus/heathzenith/h8/wh_8_64.h, src/mame/heathzenith/h8.cpp
Added cards:
- HA-8-6 - Z80 CPU replacement board
- HA-8-8 - Extended configuration board
- WH-8-16  - 16k Static RAM board
Other changes
- Use `address_space_installer` for the h8 memory mapping
- add support for ROM disable line (to support ORG-0 and CP/M)
- Remove PAM37 ROM as an option for 8080 board (only supported on HA-8-6 Z80 board).
- Update handing of `RUN LED` to match real system.
- Fix value returned for unmapped addresses (memory and IO).
=> heathzenith/h8.cpp: Add more cards, change to use address_space_installer

src/mame/layout/roland_tr707.lay, src/mame/roland/mb63h114.cpp, src/mame/roland/mb63h114.h, src/mame/roland/roland_tr707.cpp
Accuracy improvements (likely imperceptible):
* EG attack times and max voltage.
* EG attack slowdown, when multiple voices are triggered at once.
* DC-blocking capacitors before the left and right summing op-amps.
* Conflict handling in key matrix scanning.
* Sample playback timing.
* Layout shows cartridge when it is connected.
Bug fix:
* First voice trigger after a reset was being ignored.
Tidying up:
* Improved comments and component designations.
* Updated copyright holders (missed in previous PRs).
=> roland_tr707.cpp: Minor accuracy improvements, fixes and tidying up.

src/mame/konami/tmnt2.cpp
- use BIT macros for single bit values
- Fix side effects for popmessage in ssriders_protection_r
- Replace VIDEO_START_MEMBER to video_start()
- Fix namings
- Simplify prmrsocr sound bankswitching
=> konami/tmnt2.cpp: Split driver states per configurations, Fix save states and cleanups

src/mame/apple/apple2gs.cpp
This PR fixes `$C019` to work correctly on the IIgs: the sense is inverted compared to the //e.
This is documented incorrectly in the [Apple IIgs Hardware Reference](http://archive.org/details/Apple_IIgs_Hardware_Reference_HiRes/page/270/mode/2up), but later corrected in
[Apple IIgs Technical Note #40](http://apple2.gs/technotes/tn/iigs/TN.IIGS.040.txt), and was well-known in [published literature](http://link.springer.com/content/pdf/10.3758/BF03202812.pdf) of that era.
Examples of VBL syncing errors fixed by this PR:
* ACS's ACS_DEMO1.2mg, # 5 GIGA SCROLLING! (tearing top scroller and missing bottom)
* FTA's XMASDEMO.2mg (flickering fill-mode zoom of X-MAS logo) _(but still hangs on WAI after that)_
* Brutal Deluxe's Beauvais1992.2mg (too-fast text scroller at bottom)
I have updated my …
=> apple2gs: fix VBL sync

src/mame/sinclair/sprinter.cpp
=> sinclair/sprinter.cpp: Fixed DCP mapping --TolikTrek

src/devices/cpu/i960/i960.cpp, src/devices/cpu/i960/i960.h, src/mame/namco/namcofl.cpp, src/mame/sega/model2.cpp
If a particular IRQ line is already high, trying to assert another IRQ on the same line no longer has any effect; the IRQ line must be cleared/lowered first before another IRQ can be asserted. 
IRQ acknowledgement logic has been implemented for Namco System FL, since it is now required with the i960 update.
=> cpu/i960: store IRQ line states, immediately return if unchanged

src/devices/bus/isa/fdc.cpp, src/devices/bus/isa/hdc.cpp, src/devices/bus/isa/hdc.h
Disable option ROM on fixed disk controller (onboard BIOS has built-in support).
=> ec1841: support quad density floppies as an option.

src/mame/alesis/midiverb.cpp, src/mame/layout/alesis_midifex.lay, src/mame/mame.lst
Alesis MIDIFEX [*]
[*] I stumbled upon this [here](https://synth-diy.org/pipermail/synth-diy/2025-July/175631.html). Up to the MAME team on how you'd like to handle credits.
=> alesis/midiverb.cpp: Adding the MIDIFEX and its layout.

src/devices/bus/qbus/dvk_kgd.cpp, src/devices/bus/qbus/dvk_kgd.h, src/devices/bus/qbus/dvk_mx.cpp, src/devices/bus/qbus/dvk_mx.h, src/devices/bus/qbus/pc11.cpp, src/devices/bus/qbus/pc11.h, src/devices/bus/qbus/qbus.cpp, src/devices/bus/qbus/qbus.h
Support systems with entire memory space covered by a view (uknc) -- views are not initialized at device_start() time.
Correct initial state of PC11 device.
=> qbus: add bus error and BEVENT (periodic timer) callbacks.

hash/mac_flop_clcracked.xml, hash/mac_flop_orig.xml
New working software list items (mac_flop_orig.xml)
Crossword Magic (version 4.0) [4am, A-Noid]
Deluxe Music Construction Set (version 2.0) [4am, A-Noid]
Fokker Triplane Flight Simulator (version 1985-10-31) [4am, A-Noid]
Harrier Strike Mission (version 1985-09-05) [4am, A-Noid]
Indiana Jones and the Last Crusade (version 1.7) [4am, A-Noid]
James Bond 007 in: Goldfinger [4am, A-Noid]
Jazz (version 1A) [4am, A-Noid]
KidTalk (version 1.0) [4am, A-Noid]
MacMatch [4am, A-Noid]
MathTalk (version 1.0) [4am, A-Noid]
MusicWorks (version 1.0) [4am, A-Noid]
PageMaker (version 1.2) [4am, A-Noid]
pfs: file (version A.01) [4am, A-Noid]
pfs: report (version A.00) [4am, A-Noid]
Sargon III [4am, A-Noid]
Uninvited (version 1986-08-06) [4am, A-Noid]
New working software list …
=> mac_flop_orig.xml and mac_flop_clcracked.xml: Added 35 dumps

src/devices/cpu/i960/i960.cpp, src/devices/cpu/i960/i960.h
On the Intel 80960KB, pending interrupts are only checked at the following times ([source](http://bitsavers.informatik.uni-stuttgart.de/components/intel/i960/80960KB_Programmers_Reference_Manual_Mar88.pdf)):
- After returning from an interrupt
- While executing `modpc` if it causes the current priority to be lowered
- After receiving a test pending interrupts IAC message
If pending interrupts are checked during a memory test while it is writing to the same area as the interrupt table, it can result in a spurious IRQ with an invalid vector, ultimately causing MAME to crash when the i960 reads an invalid opcode. This is the cause of [MT08347](https://mametesters.org/view.php?id=8347).
To fix this, `check_irqs()` has been split into two functions: `check_immediate_irqs()` and …
=> cpu/i960: Split check_irqs() into two separate functions; fixes MT08347

src/mame/konami/dbz.cpp
- Use BIT macro for single bit values
- Fix spacing
- Fix namings
=> konami/dbz.cpp: Reduce duplicates, Minor cleanups

src/mame/konami/gradius3.cpp
- PCB has no stereo sound output config nor connector, and only left channel is connected for YM2151. It fixes sound balance of salamander stage BGMs. (left channel is always enabled in all channels, right channel is disabled in some channels)
- Use BIT macro for single bit values
- Use logmacro.h for logging feature
- Fix namings
=> konami/gradius3.cpp: Fix sound routing, Minor cleanups

src/devices/cpu/mb86235/mb86235.cpp, src/devices/cpu/mb86235/mb86235.h, src/devices/cpu/mb86235/mb86235ops.cpp, src/mame/sega/model2.cpp
For each Model 2C game the copro TGPx4 initialization procedure writes a list of function addresses to data A and afterwards writes 0 to external address 0x2C, which in the current code is mapped to data A so it ends up corrupting the address of copro function 0x2C. This commit separates data A and external memory so this no longer occurs.
Fixes enemy car collision detection in stcc, probably other bugs in Model 2C games we hadn't discovered
=> cpu/mb86235: Use separate memory spaces for data A and external

src/devices/video/ef9345.cpp
This PR implements the CLF and CLG commands of the EF9345 and TS9347 video chips. While none of the currently supported Minitel ROMs seems to rely on them, they are used in similar Minitel models that we might want to support in the future.
From the EF9435 datasheet, Table 4:
Official documentation about this commands seems quite lacking. A good explanation can be found here: https://stardot.org.uk/forums/viewtopic.php?t=22941&start=31
They have been validated with tests `test_clear_page16` and `test_clear_page24` from https://github.com/fabio-d/minitel-ef9345-testsuite/blob/main/tests/test_memory.py.
**Implementation notes:**
Unlike all the other commands, CLF and CLG never complete.
More precisely, in the real chip, they keep filling the video RAM in a loop, restarting from line 8 after …
=> ef9345: implement commands CLF and CLG
