mamedev/mame

src/mame/drivers/hp9k_3xx.cpp
We have a buserror handler that catches all unmapped
addresses in hp9k3xx_common(), so no need for additional
handlers. Removing the superfluous ram() handlers also
fixes booting on the /320.
=> hp9k_3xx: remove obsolete bus error handler

src/devices/sound/pokey.cpp
Don't count POT counters as long as SK_RESET is applied, i.e. bit #0
and bit #1 of SKCTL are both clear.
=> pokey: return most recent m_ALLPOT during SK_RESET

src/mame/drivers/pacland.cpp
incorrect:"30K 80K 130K 300K 500K 1M"
correct  :"30K 80K 150K 300K 500K 1M"
=> Fix: Value of dipswitch "Bonus Life" is incorrect.

src/devices/cpu/m6502/dxavix2000.lst, src/devices/cpu/m6502/oxavix2000.lst, src/devices/cpu/m6502/xavix2000.cpp, src/devices/cpu/m6502/xavix2000.h
(it borrows quite a few mapping / ideas from the 65816 but does things differently, so stubby handlers for now)
=> restore Super XaviX opcode table with correctly swapped opcodes

src/lib/util/coretmpl.h
Not 100% confident about the variable type, and there may still be some debate over the function name (trying to avoid confusion with the length of the container, or with the number of empty slots), so appreciate review/comments.
=> util::fifo.queue_length() (nw)

src/devices/machine/mb87030.cpp
This makes Bootrom Rev C1 machines (/340, /370) boot via SCSI
=> mb87030: fix temp register sampling

src/mame/drivers/rainbow.cpp
Write fault must not be set to 1 permanently (only in case of fatal write errors).
=> [Rainbow-100]: write fault must not be set to 1

src/devices/bus/hp_dio/human_interface.cpp, src/devices/bus/hp_dio/human_interface.h
This makes the HP-UX 9 installer properly work with GPIB. Without
this patch it will hang ages during detection of GPIB devices.
=> hp9k3xx/human_interface: add parallel poll logic (nw)

src/devices/cpu/m68000/m68kmmu.h
Makes the HP-UX 9 installer boot.
Also tested that the following OS's still work:
- Mac OS 7 on macii
- HP-UX 7 on hp9k360
=> m68kmmu: support short indirect descriptors & set MMU status flags in pmmu_atc_lookup()

src/devices/cpu/m68000/m68k_in.cpp, src/devices/cpu/m68000/m68kmmu.h
Makes it easier to maintain. Should not introduce any functional change.
=> m68kmmu: split m68881_ops() into subfunctions

src/devices/cpu/m68000/m68kdasm.cpp, src/devices/cpu/m68000/m68kdasm.h
this adds some more decoding to someof the MMU instructions. The
following encodings are now properly decoded:
$ ./unidasm test.bin -arch m68040
00: f010 8216  ptestr #6, (A0), 0
04: f010 8209  ptestr D1, (A0), 0
08: f010 8200  ptestr %sfc, (A0), 0
0c: f010 8201  ptestr %dfc, (A0), 0
10: f010 8310  ptestr #0, (A0), 0, @A1
14: f010 8000  ptestw %sfc, (A0), 0
18: f548       ptestw (A0)
1a: f568       ptestr (A0)
1c: f500       pflushn (A0)
1e: f501       pflushn (A1)
20: f509       pflush (A1)
22: f510       pflushan
24: f518       pflusha
=> m68kdasm: decode ptest & pflush

src/mame/drivers/rainbow.cpp
Default to Microsoft Mouse (sane for DEC Windows 1.03). 
Note that the older DEC Windows 1.0 uses another hard wired mouse model, possibly the DEC hockeypuck mouse (VSAxxx), which is unemulated yet.
=> [Rainbow-100]: default to Microsoft Mouse

hash/pc98.xml
- Added new entries from the Neo Kobe Collection:
Ballade3
Bible Master - Crash of the Blleot Rutz
Bible Master - Crash of the Blleot Rutz (Alt)
Bind - Kinbaku Jinmon Densetsu
Black Bird - Tori-tachi no Tooboe
Blackthorne - Jigoku no Fukushuu (16-color version)
Blackthorne - Jigoku no Fukushuu (256-color version)
Blandia 98
Blind Games
Blue Ruins - Harukanaru Bibanon no Hihou
Bounty Hunter Ludy
Branmarker 2
Bretonne Lays Scenario Shuu 1
Briganty - The Roots of Darkness
Bunny Hunter Zero
- Added my own dump of Brandish Renewal
- Renamed the current Brandish Renewal entries to indicate they are
cracked, since the original disks are protected
- Relabeled disks with their actual names
- Added usage notes for software that needs DOS
- Removed user …
=> pc98.xml: softlist updates, part 3 (B)

src/mame/drivers/8080bw.cpp, src/mame/layout/yosakdon.lay
I use this YouTube video: https://youtu.be/3jVR50cqXCM found by MetalGod (https://mametesters.org/view.php?id=7126)
and several screenshots of yosakdon from MAME 0.36b16 to get the color position in the picture.
Example: http://www.mameworld.info/mameinfo/download/yosakdon-MAME_036b16.png
=> Added color overlay to Yosaku To Donbei

src/mame/drivers/xavix.cpp, src/mame/includes/xavix.h
this also fixes load / saves in general with the Taito / Namco Nostalgia games, which for whatever reason aren't happy with page support being enabled (even if the chip type should in theory support it)
excite fishing still moans, but always did.
(this and previous already merged PR are part of release quality control check I'm doing)
=> XaviX - allow driver to work with i2cmem in a suitable way nostalgia games (page support causes hangs in Gaplus etc.)

src/mame/drivers/pbaction.cpp, src/mame/includes/pbaction.h, src/mame/mame.lst
The "pbaction2" set was a Tecfri licensed game.
The Tecfri variant included an additional subboard (previously dumped, but documented as "function unknown") for controlling an external vertical scores board with 7-sements diplays (like on a real Pinball).
I've renamed "pbaction2" to ""pbactiont", an accordingly:
"pbaction3" -> "pbaction2"
"pbaction4" -> "pbaction3"
More info about the extra Tecfri subboard (Spanish):
https://petacos.forumcommunity.net/?t=60710482
http://www.recreativas.org/pinball-action-1025-tecfri
=> Document the Tecfri license Pinball Action set

src/mame/drivers/balsente.cpp
Maibesa officially licensed Trivial Pursuit from Bally for translation to Spanish (and also added questions related to Spanish culture) and distribution on Spain. Maibesa also manufactured a dedicated cabinet for Trivial Pursuit.
For reference, see http://www.recreativas.org/trivial-pursuit-898-maibesa
=> Mark Trivial Pursuit (Spanish) as licensed by Maibesa (nw)

src/frontend/mame/luaengine.cpp
While testing, found out that read_range ignores offset/index, and that it returns char data only. Is any of that a bug?
Don't see an option to request a review, but these questions are mostly directed to @cracyc.
=> luaengine: add description comments for emu.item()

src/mame/drivers/supbtime.cpp, src/mame/includes/supbtime.h, src/mame/video/deco16ic.cpp, src/mame/video/supbtime.cpp
they were lost when the driver was merged with supbtime (verified with hardware videos)
=> restore tilemap offset to tumblep and chinatwn

scripts/src/cpu.lua, src/devices/cpu/nec/v53.cpp, src/devices/cpu/nec/v53.h, src/devices/cpu/nec/v5x.cpp, src/devices/cpu/nec/v5x.h, src/devices/machine/am9517a.cpp, src/devices/machine/am9517a.h, src/devices/machine/i8251.cpp, src/devices/machine/i8251.h, src/mame/audio/hng64.cpp, src/mame/drivers/mpc3000.cpp, src/mame/includes/hng64.h, src/mame/includes/mips.h
An attempt to add the NEC V50 to the existing V53/V53A devices. Also overhauled for devcb3, and made some required changes to the peripherals. Because this is a pretty wide-ranging change, I'm soliciting feedback before merging.
* v53: refactor and add v50, devcb3, exploit templates and other general cleanup
* am9517a: add 16 bit transfer support to v5x_dmau variant
* i8251: minor tidy on v5x_scu variant
* hng64: update to match v53 changes
* mpc3000: update to match v53 changes
=> v53: overhaul

src/devices/machine/mb87030.cpp
This makes Pascal 3.25 boot/run from SCSI on hp9k_3xx. Pascal
is now a fully running OS like BASIC on these machines. While
at it also clean up a few style issues.
=> mb87030: support padding mode

src/lib/formats/dsk_dsk.cpp
Fix MameTesters #07134.
Thanks to Klez for testing.
=> dsk_dsk.cpp: Avoid to use uninitialized booleans

src/mame/drivers/m52.cpp, src/mame/includes/m52.h, src/mame/video/m52.cpp
It's meant to be a conversion, or at least was given to us that way, but it disagreed with certain things about the way the existing mpatorl driver worked.  I think some of these things were optimizations in the mpatrol driver to save memory back in the day.
it's a Kyle Hodgetts abomination, so without reference material it's very difficult to work out how things should be, eg. the power orbs you collect are part of the text tilemap, which must scroll, but with the scroll offsets and sprite positioning we have they only collide with the very back of your huge ship,  I think this is correct however.
It seems to expect double height background images, which strongly suggests that moon patrol should have this too, and is simply not populating the lower half, hence the 'solid colour' pull-up. …
=> m52: improvements to alpha1v (promoted to working)

src/devices/cpu/m68000/m68kdasm.cpp
There's a slight error in the number of bits in the MC6830 Manual.
=> m68kdasm: fix ptest instruction (nw)

src/devices/machine/mb87030.cpp
Previous order of code triggered a state change after
the disconnect, which confused the NETBSD installer. With this
fixed, writing a disklabel to a netbsd chd works.
=> mb87030: fix SCSI disconnect interrupt (nw)

src/mame/drivers/williams.cpp
Also marked the PROM as BAD_DUMP, since it was taken from other set
=> Rename according to ROM and socket labels (useful when redumping) (nw)

src/devices/cpu/m68000/m68kcpu.cpp, src/mame/drivers/hp9k_3xx.cpp, src/mame/drivers/hp_ipc.cpp, src/mame/drivers/wicat.cpp, src/mame/drivers/x68k.cpp
RW bit actually means 1 = read, 0 = write. It was also not
shifted in m68000_base_device::set_buserror_details(), thus overwriting the LSB of FC.
=> m68000: fix rw bit in address error frame (nw)

src/devices/bus/cbus/pc9801_86.cpp
This change adds stereo sound routing for the FM/rhythm channels of the YM2608 on the PC-9801-86 and Speak Board cards (the PSG part is always mono).
=> pc9801_86.cpp: add stereo sound

src/devices/cpu/m68000/m68kmmu.h
in the check fc wasn't actually checked, so as soon as an OS (like
the MAC II CI) set the SUPERVISOR_ONLY but the MMU caused a bus
error exception.
=> m68kmmu: fix compare of SUPERVISOR_ONLY bit in 8 byte descriptors (nw)

src/mame/drivers/asuka.cpp, src/mame/includes/asuka.h
the bad code is a single bit wrong and causes the last stage in the game to make invalid ROM writes due to using A2 as a pointer instead of A0, and thus breaking the rowscroll on that stage.  (noticed the bug while watching MAME roulette video)
the prototype clone has correct code here, and works fine, so it seems very likely a case of bitrot on the parent set.  (the ROM check done by the game is useless)
=> earthjkr (Earth Joker) appears to be a bad dump, mark it as such

src/mame/drivers/namcos2.cpp
This PR is fixes metlhawk intermission.
=> namcos2.cpp : Fix c123 video RAM mirroring issue

src/devices/bus/hp_dio/human_interface.cpp
pre-init the latch clock variable to 1, so the first write to the latch
doesn't cause invalid data latched which would trigger an invalid write to
the RTC, causing an invalid time.
=> hp9k_3xx: fix RTC corruption

src/mame/drivers/hp9825.cpp, src/mame/layout/hp9825.lay
Hi,
this PR adds the internal expansion ROMs to hp9825b emulation. I'll send the ROM images to code@... as usual.
I've also fixed the author in hp9825.lay (it was probably copy-pasted from hp9k_3xx.lay).
Thanks.
--F.Ulivi
=> HP9825: added internal expansion ROMs

src/mame/drivers/deco32.cpp, src/mame/includes/deco32.h, src/mame/video/deco32.cpp
Fix spacing, Move tilegen configurations into video_start, Remove VIDEO_START_MEMBER, Fix namings, Cleanup duplicates in gfxdecode, Reduce unnecessary address_space arguments, Reduce unnecessary arrays, Fix tattass* metadata related to date in ROM/RAM check screen
=> deco32.cpp : Cleanups

src/devices/cpu/m68000/m68kcpu.h, src/emu/debug/debugcmd.cpp, src/emu/debug/debugcmd.h, src/emu/debug/debugcpu.cpp, src/emu/debug/debugcpu.h, src/emu/diexec.h
gp 'go privilege' starts execution until the privilege mode
changes. This can be used to break on task switches. I.e on m68k,
one could do:
gp { ~sr & 0x2000 && crp_aptr == 0x1234567 }
which would execute until the privilege mode changes to user mode and
the CPU root pointer is 0x1234567.
for cpu code, all that is needed to make this work is calling
debugger_privilege_hook() when the execution level changes.
=> debugger: add 'gp' command

src/mame/drivers/nes_vt.cpp, src/mame/mame.lst
Dance Dance Revolution Disney Mix [zino, ClawGrip, The Dumping Union, Recreativas.org]
Notes: 
* The console has stereo output (via two RCA cables), but the driver outputs mono.
* I've marked the game as MACHINE_IMPERFECT_GRAPHICS as every other game on the driver, 
but I see no graphical differences with the real game.
I recorded a video of it: https://www.youtube.com/watch?v=PTmwcrRqufI
* The original console shows a "Konami" banner on startup, but it seems to be missing on the emulation.
* MAME crashes when the game is resetted (F3) on a MAME debug build.
=> New WORKING machine

src/mame/drivers/brkthru.cpp
The PCB owner redumped the ROMs, getting variable results on ROMs 6, 7 and 8, and constant reads on all other ROMs.
He also recorded a video of the game running: https://www.youtube.com/watch?v=eBbToDz0YQw
=> brkthru.cpp: Marked brkthrut ROMs 6, 7 and 8 as BAD_DUMP (nw)

src/devices/cpu/nec/necinstr.hxx
Avoids runtime error 200 in Turbo Pascal 7 runtime.   Not tested on the real thing (yet).
=> cpu/nec: force bits 12..15 of flag word to 1 in POPF, to match Intel 8086

src/mame/drivers/backfire.cpp
Cleanup duplicates, Remove unused, Convert arrays into std::unique_ptr, Add notes, Fix metadata related to regional warning screen (Both dumped sets are Japan release)
=> backfire.cpp : Minor cleanups

src/mame/drivers/atvtrack.cpp
About a known but undumped Smashing Drive Spain/Portugal set with different checksum.
=> atvtrack.cpp: Add notes (nt)

src/devices/bus/cbus/pc9801_86.cpp
This change fixes a regression introduced with the MCFG removal (commit cc59e2123eaa5e6c5c71317d28b55f425bb6a333) that caused the PSG part of the YM2608 to sound extremely loud compared to the rest of the channels.
=> pc9801_86.cpp: fix PSG regression

src/devices/video/imagetek_i4100.cpp, src/devices/video/imagetek_i4100.h, src/mame/drivers/hyprduel.cpp, src/mame/drivers/metro.cpp, src/mame/includes/metro.h, src/mame/video/metro.cpp
Add support for buffered sprites, Cleanup sprite drawing routine, Internalize gfxdecode(All driver shared same gfxdecodes)
hyprduel.cpp : Cleanup ACCESSING_BITS
metro.cpp : Fix namings, Cleanup ACCESSING_BITS, Duplicates, Unnecessary address_space arguments, Fix sprite lags for blzntrnd/gstrik2, Fix metadata(Japanese title) for karatourj, Add notes
=> imagetek_i4100.cpp : Updates, Minor cleanups, Remove MCFGs

src/emu/debug/debugcmd.cpp
This is useful for catching putchar() like functions and printing
the written value to error.log.
On hp9k_3xx, i'm using this with the HP 300 test software, to log
test error messages that get printed on screen to error.log, so i
have the message directly after the debug messages from my driver.
Example:
wpset 0xfffe36be,80,w,1,{ logerror "%c", wpdata; g }
=> debugger: add %c to logerror

scripts/src/bus.lua, scripts/src/video.lua, src/devices/bus/hp_dio/hp98550.cpp, src/devices/bus/hp_dio/hp98550.h, src/devices/bus/hp_dio/hp_dio.cpp, src/devices/video/catseye.cpp, src/devices/video/catseye.h, src/emu/xtal.cpp, src/mame/drivers/hp9k_3xx.cpp, src/mame/layout/hp9k_3xx.lay
Used in the high end HP9000/300 machines. Provides a resolution
of 1280x1024 @ 8bpp. It also provides two overlay planes and one
phantom plane. Each plane contains two window movers that are used
for copying characters and tiles on the screen. It also has a RUG
for line/vector drawing. The current state implements everything
that is required to have a working HP Visual user environment in
MAME.
Working:
- window mover
- pixel replacement rules
- window replacement rules
- f0 tripple replacement rule (copy src or keep destination depending on pattern register)
- VRAM bit access mode
- solid line drawing
Not implemented yet:
- drawing circles
- linetype vector/circles
- rectangles
- filling areas
- tripple replacement rules other than f0
=> add HP98550 high-res color graphic card

scripts/target/mame/arcade.lua, src/mame/drivers/blmbycar.cpp, src/mame/drivers/wrally.cpp, src/mame/includes/blmbycar.h, src/mame/includes/wrally.h, src/mame/machine/wrally.cpp, src/mame/video/blmbycar.cpp, src/mame/video/gaelco_wrally_sprites.cpp, src/mame/video/gaelco_wrally_sprites.h, src/mame/video/wrally.cpp
Blomby Car is a bootleg of World Rally, many things are similar, but not quite the same, including the sprites.
Previous emulation of Blomby Car was missing the shadow and highlight effect entirely.  This was implemented on World Rally.
Bringing the video implementations closer together has allowed me to add this missing effect to Blomby Car.
Also looking at some reference material it seems the emulation of the shadow / highlight effect on World Rally was 'too good' in some cases, for example, looking at original hardware videos it looks very much like you're meant to see a car shaped shadow as your headlights pass through the starting arch.  This wasn't present on previous emulation which used 2 pass drawing, but is present with the single pass drawing and mixing.
=> World Rally / Blomby Car improvements (shadow / headlight in Blomby Car)

src/mame/drivers/hp9k_3xx.cpp
use the HP98550A card on HP9000/360 and 370 models so we have
a more realistic machine for using HP-UX.
=> hp9k_3xx: use 98550A on newer models

hash/ekara.xml, src/mame/audio/xavix.cpp, src/mame/drivers/xavix.cpp, src/mame/includes/xavix.h, src/mame/machine/xavix.cpp
hopefully this makes it easier for me to trace why the i2cmem hookup fails, and if it's due to code execution problems causing the unwanted writes, if the device should be less sensitive to them, or if there's an error in the driver hookup.
still not entirely sure the game is happy with what it gets this way, but it's something to work with.
=> XaviX - cheap hack to get epo_efdx to show a title screen + dumps of the remaining US e-kara carts

src/devices/machine/nscsi_bus.h, src/devices/machine/nscsi_cd.cpp
We reported Medium error, which makes at least the HP9000/382 complain
about bad hardware during system search, and netbsd didn't like it either
and reported it during boot up. Change it to report 'Not ready, medium not
present.' This is what my Toshiba XM-5401B reports.
=> nscsi: fix sense data if no cdrom in drive (nw)

scripts/target/mame/mess.lua, src/emu/xtal.cpp, src/mame/drivers/hp3478a.cpp, src/mame/includes/hp3478a.h, src/mame/layout/hp3478a.lay, src/mame/mame.lst
This adds a driver for the HP 3478A DMM. Those units are reasonably well documented with full service manual and schematics. Additionally, I have published my annotated disassembly of a common firmware dump in another repo.
Emulation is subjectively ~ 80% complete and mostly accurate. It's going to be simpler listing what isn't implemented, or broken:
- Analog-side CPU (8048), never dumped (to my knowledge). Its presence can be faked to some extent by patching a handful of bytes in the stock ROM.
- i8291 HP-IB (IEEE488) interface
- LCD "annunciators" not rendered
- LCD charset has 3 unverified characters (flagged in the source code).
I don't plan on adding major features to this driver, but I hope I've commented and written the code in such a way that the "door is open" should someone be …
=> New driver : HP 3478A Digital Multimeter

src/devices/machine/stvcd.cpp, src/devices/machine/stvcd.h, src/devices/sound/scsp.cpp, src/devices/sound/scsp.h, src/devices/sound/scspdsp.cpp, src/mame/drivers/coolridr.cpp, src/mame/drivers/model2.cpp, src/mame/drivers/model3.cpp, src/mame/drivers/saturn.cpp, src/mame/drivers/stv.cpp
Implement EXTS Mixing, DAC18B, Remove MCFGs, Reduce machine().device
coolridr.cpp : Make screen update routine related to cliprect, Minor reduce duplicate
coolridr.cpp, model2, model3 : Correct SCSP / Sound CPU clock/Sound output balance, Add notes
saturn.cpp, stv.cpp : Correct SCSP clock, Add notes
stvcd.cpp : Add device_mixer_interface related to SCSP EXTS
=> scsp.cpp : Updates

src/devices/cpu/m68000/m68kmmu.h
ps == 8 should be ps - 8, which cause a compiler error. However, the code
doesn't work. It wasn't noticed due to the typo, so remove it for now.
=> m68kmmu: fix build

src/devices/cpu/m68000/m68kfpu.hxx
required by netbsd ps command, which utilizes the FPU.
=> m68kfpu: add (d16,An) addr mode to WRITE_EA_FPE()

src/devices/sound/scsp.cpp
Changes decrement operation from "=-"  to "-="
Error:
../../../../../src/devices/sound/scsp.cpp:1549:6: error: use of unary operator that may be intended as compound assignment (-=) [-Werror]
p =- 128;
^~
../../../../../src/devices/sound/scsp.cpp:1585:9: error: use of unary operator that may be intended as compound assignment (-=) [-Werror]
limit =- ASCALE[s];
=> sound/scsp.cpp - Fix compilation on OSX Clang

scripts/src/bus.lua, scripts/target/mame/mess.lua, src/devices/bus/hp9845_io/98032.cpp, src/devices/bus/hp9845_io/98032.h, src/devices/bus/hp9845_io/hp9845_io.cpp, src/devices/bus/hp9845_io/hp9845_io.h, src/mame/drivers/hp9825.cpp, src/mame/drivers/hp9845.cpp, src/mame/includes/hp9845.h, src/mame/machine/hp9845_printer.h, src/mame/machine/hp98x5_io_sys.cpp, src/mame/machine/hp98x5_io_sys.h
Hi,
this PR is for a set of changes to HP9825 & HP9845 emulation. In summary:
- I refactored the HP9845 I/O sub-system to an external device (hp98x5_io_sys_device) to share its code with HP9825,
- I added the I/O slots to HP9825
- I implemented the HP98032 GPIO module.
Next step, when time allows, will be the implementation of HLE of HP9885 8" floppy drive. In the real hw it connects to the system through the 98032 module.
Thanks.
--F.Ulivi
=> HP98x5: refactored I/O sub-system & added HP98032 GPIO module.

src/mame/drivers/rainbow.cpp
Monitor autodetection avoids false colors [would require rewiring on a real machine].
Corrected palette problems (non-working flag). Also, video levels from DEC's documentation turned out too dark. Converted printf to logerror.
=> [Rainbow-100]: correct palette problems and silence log output

src/osd/modules/sound/sdl_sound.cpp
Fix #4381 
I made the circular buffer a separate class to isolate the handling of the buffer from the handling of the sound stuff.
There is no more spinlock, therefore no risk of deadlock. The buffer overflow / underflow conditions are handled only once and acted upon immediately instead of risking a race condition.
One thing to notice is that now the attenuation is performed in the `sdl_callback` function instead of doing it at the time of insertion into the buffer. It is also made as a separate pass onto the data chunk. But I doubt this could have any significant impact on the performance.
=> sdl_sound.cpp: Rework the circular buffer

scripts/src/3rdparty.lua, src/lib/util/png.cpp
When compiling with the option `-Og` (or with the make option `OPTIMIZE=g`), g++ emit an error about some variables that may be used uninitializes. It appear that with `-Og`, GCC's static analyzer falls into that spot where it is smart enough to detect that the variable is conditionally initialized, but not smart enough to realize it is only used when initialized.
=> Fix compilation errors with -Og

src/mame/drivers/pgm2.cpp, src/mame/includes/pgm2.h, src/mame/machine/pgm2_memcard.cpp, src/mame/machine/pgm2_memcard.h, src/mame/video/pgm2.cpp
pgm2.cpp : Do single-pass sprite drawing (uses screen.priority), Remove unused routine/values, Add notes, Shorter type values, Move most of things into private:, Make decrypt rom size related to ROM board integreated RAM size when RAM exists in ROM board, Add input name, Remove machine().save().register_postload, Reduce runtime tag lookups, Remove MCFGs, Remove unnecessary arguments, Simplified gfxdecode, Fix RAM test fail (ddpdojt, kov98umh, kov3)
pgm2_memcard.cpp : Shorter type values, Fix naming, Remove unnecessary arguments
=> pgm2.cpp, pgm2_memcard.cpp : Cleanups, Updates

src/mame/drivers/rainbow.cpp
Venix 86-R (plus Boston Softworks Extensions) working (tested yesterday), just follow https://github.com/bsdimp/venix/blob/master/doc/MESS-RB-INSTALL.md
UCSD Forth and Pascal expect 4 identical QD drives, so definitions for (non standard) PC-style drives in slot 3 and 4 finally commented out.
Also noted a regression in the PC subsystem (3.5 " DS DD images and 5.25 SSDD at slot 3 +4 ) on or after April 2018. Unfortunately can't find or fix disk errors myself.
Bug description: file content broken _while directory listing is OK;_ _seek errors_ and _write fault error reading from I:_  (I: is source disk) when copying.
=> [Rainbow-100]: document driver state (and remove bloat)

src/mame/drivers/subsino.cpp
=> Mark empty PLD dumps from protected devices as NO_DUMP (nw)

src/mame/drivers/pc.cpp
It's two bytes short the full 8K.
=> pc.cpp: Marked the Compaq Portable video ROM as BAD_DUMP.

src/mame/drivers/mitchell.cpp, src/mame/mame.lst
Pang (bootleg, set 6) [ClawGrip, Recreativas.org, The Dumping Union]
There was a battery-backed RAM with portions of the program ROM, but the battery was dead, so it's undumped. All the PLDs were protected.
=> New NOT_WORKING clone

src/devices/machine/nscsi_hd.cpp
This fixes perceived disk corruption when actually the nscsi_harddisk_device block cache is just returning data from the wrong block.
=> nscsi_harddisk_device: track the current block LBA on writes

hash/clickstart_cart.xml, scripts/target/mame/mess.lua, src/devices/machine/spg2xx.cpp, src/mame/drivers/clickstart.cpp, src/mame/mame.lst
seems to be something missing, jumps to outside of code area, maybe secondary small internal ROM of CPU.  I did think the dumps were half size for various reasons, but there is a checksum in the footer of each one that matches the data (even if another checksum in the header for some of them we can't match)  Possible BIOS is wrong tho as that checksum in the footer doesn't match by quite a significant amount.
most games show something just by putting a 'RET' opcode in the upper areas it attempts to jump to.
Ryan credited in driver since it's more or less just a stripped down copy of vsmile.cpp
=> new NOT WORKING ClickStart [Sean Riddle, Clawgrip, TeamEurope] + a Software List for it

src/mame/drivers/srmp6.cpp
Use buffered_spriteram16 for sprite ram, Use shorter type values, Fix namings, Add notes, Fix color fading, Minor corrections, Add save states, Reduce runtime tag lookups, Minor code style fixes, Simplified gfxdecode
=> srmp6.cpp : Updates

src/mame/includes/thomson.h, src/mame/machine/thomson.cpp, src/mame/video/thomson.cpp
This PR adds a new undocumented video mode for the Thomson TO8 8-bit computer (ant the other Thomson computers using the same video chipset). 
The mode has been tested on a real TO8.
=> [thomson] added undocumented video mode

3rdparty/lzma/C/AesOpt.c, 3rdparty/portaudio/src/hostapi/dsound/pa_win_ds.c, 3rdparty/portaudio/src/hostapi/wdmks/pa_win_wdmks.c, 3rdparty/portaudio/src/hostapi/wmme/pa_win_wmme.c, src/devices/cpu/alto2/a2ether.cpp, src/devices/machine/diablo_hd.cpp, src/devices/video/ef9345.cpp, src/frontend/mame/ui/videoopt.cpp, src/lib/formats/apridisk.cpp, src/mame/drivers/by17.cpp, src/mame/drivers/by35.cpp, src/mame/drivers/nokia_3310.cpp, src/mame/drivers/truco.cpp, src/mame/machine/cuda.cpp, src/mame/video/3dom2_te.cpp
- conditionally uninitialised variables in PortAudio;
- floats passed to attotime;
- unsigned->signed enums (this one is technically still wrong)
=> fix MSVC (llvm toolset) compile (nw)

hash/jakks_gamekey_nk.xml, src/devices/machine/spg2xx.cpp, src/mame/drivers/rad_eu3a14.cpp, src/mame/drivers/vii.cpp, src/mame/drivers/xavix.cpp, src/mame/includes/xavix.h, src/mame/machine/xavix.cpp, src/mame/mame.lst
Mattel Classic Sports [Sean Riddle]
Dora the Explorer (JAKKS Pacific TV Game) [Sean Riddle]
kludge handling of invalid size writes to DMA so that Dora the Explorer doesn't trash all of RAM + registers
new SOFTWARE LIST
JAKKS Pacific 'NK' Game Keys
(Dora has corrupt gfx, probably the bad DMAs should do something, Mattel Classic Sports gives a black screen)
xavix.cpp:
e-kara Pro Headset (US, includes 3 songs) [Sean Riddle]
Super Dash Ball (Japan) [Sean Riddle,  Peter Wilhelmsen]
Gururin World (Japan) [Sean Riddle, Peter Wilhelmsen]
disable active raster interrupts if raster interrupt enable is turned off, and add preliminary shifter register emulation, needed for 3D stages in Gururin World [David Haywood]
(Pro Headset works as well as other e-Kara stuff, …
=> TV Game work (xavix, vii, elan)

scripts/src/bus.lua, src/devices/bus/hp9845_io/98032.cpp, src/devices/bus/hp9845_io/hp9885.cpp, src/devices/bus/hp9845_io/hp9885.h, src/lib/formats/hpi_dsk.cpp, src/lib/formats/hpi_dsk.h, src/mame/drivers/hp9825.cpp
Hi,
this PR is for the HLE of HP9885 8" floppy drive. This unit was mainly used on HP9825 systems.
I also extended the HPI format to cover single-sided disks.
I'm going to send to "code" e-mail the updated hp9825b ROM images.
Thanks.
--F.Ulivi
=> hp9825: added HLE of HP9885 floppy drive

src/mame/drivers/psikyo.cpp
s1945bl has 5 of 0x10000 bytes OKI bank areas, Correct this
=> psikyo.cpp : Fix OKI bank count

hash/jakks_gamekey_dy.xml, src/mame/drivers/vii.cpp, src/mame/mame.lst
---
Disney Friends (JAKKS Pacific TV Game, Game-Key Ready) [Sean Riddle]
new NOT WORKING Software List entries
---
jakks_gamekey_dy:stenfcha Sports Tennis & Face Chase & Riches of Agrabah
This confirms that the '3 game' versions of the JAKKS Game Keys (usually sold as part of bundles) are different code to the '2 game' versions, not some soft unlock.
=> new NOT WORKING ---  Disney Friends (JAKKS Pacific TV Game, Game-Key Ready) [Sean Riddle] + new Game-Key

src/mame/drivers/homedata.cpp, src/mame/includes/homedata.h, src/mame/video/homedata.cpp
Reduce unnecessary MCFGs, Add generic_latch_8_device for CPU-CPU interface, Reduce some unnecessary arguments, Add address_map_bank_device for mrokumei banked area, Reduce unnecessary values
Fix reikaids sound clocks (battlcry runs at similar hardware as reikaids, and sound clock is same?), Add notes, Move driver_init handler differs into address_map, Fix some naming, Reduce runtime tag lookups
reikaids sound clock reference : https://youtu.be/eRZ7h96m0pc
=> homedata.cpp : Update / Cleanups

src/mame/drivers/homerun.cpp, src/mame/includes/homerun.h, src/mame/video/homerun.cpp
Use update_partial/tilemap mark_all_dirty when only GFX bank is changed, Fix namings, Use palette decoder for color Move video related save_item into video_start, Reduce unnecessary lines, Fix reset behavior, Reduce runtime tag lookups, Simplified gfxdecodes, Bankswitched areas, Fix spacings
=> homerun.cpp : Cleanups / Updates

src/mame/drivers/storio.cpp, src/mame/mame.lst
V.Reader (US, English, 2011-10-17) [ClawGrip]
V.Reader (CA, English, 2011-10-17) [ClawGrip]
V.Reader (CA, French, 2011-10-17) [ClawGrip]
Storio (GB, English, 2011-10-17) [ClawGrip]
Storio (DE, German, 2011-10-17) [ClawGrip]
Storio (ES, Spanish, 2011-10-17) [ClawGrip]
Storio (FR, French, 2011-10-17) [ClawGrip]
Storio (NL, Dutch, 2011-10-17) [ClawGrip]
* Changed the CPU to ARM9 (ARM926EJ-S CPU core), at 240MHz (from the Nuvoton W55FA9363SDN technical manual, documented as it's normal working frequency)
* Add notes.
=>  New NOT_WORKING machine 

src/mame/drivers/storio.cpp
Use "VTech" instead of "V.Tech" like on the other drivers.
=> Fix typos (nw)

hash/apple2.xml, hash/apple2_flop_orig.xml
- Adjusted (crack) to (cracked) in A2 main softlist. (They're not cracks, they're cracked software.)
- Caught a few cleanly cracked entries that weren't tagged such and added (cleanly cracked) to those.
- Adjusted Originals list to match existing A2 list where both lists have the same software.
- Adjusted names to remove woz/wz reference.
This should be the last adjustment for this month's release outside of any additional 4AM WOZ dumps that show up. After 0.206 I'll look into splitting the softlist up into clean cracks and other content.
=> First pass at prepping A2 softlist for splitting (nw)

src/mame/drivers/megasys1.cpp, src/mame/includes/megasys1.h, src/mame/video/megasys1.cpp
Add notes, Use shorter type values, Allow tilemap scroll register readable, Cleanup duplicates, Reduce runtime tag lookup, Hardecoded tags, Unnecessary device, Handler, Fix spacing, Separate address map / config for smeared OKI access instead driver init, Correct palette size related to RAM size, Minor fix of code styles
=> megasys1.cpp : Cleanups / Updates

hash/jakks_gamekey_sw.xml, src/mame/drivers/rad_eu3a14.cpp, src/mame/drivers/vii.cpp, src/mame/mame.lst
---
Star Wars - Revenge of the Sith (JAKKS Pacific TV Game, Game-Key Ready) [Sean Riddle, Peter Wilhelmsen]
---
jakks_gamekey_sw:tdyoda Turret Defense & Yoda's Escape  [Sean Riddle, Peter Wilhelmsen]
joystick inputs don't appear to work, only buttons.
=> new NOT WORKING machines --- Star Wars - Revenge of the Sith (JAKKS Pacific TV Game, Game-Key Ready) [Sean Riddle, Peter Wilhelmsen]

hash/apple2_flop_orig.xml
Final update in time for 0.206 and initial release of the new original disk softlist.
=> Update A2 Originals to 1/25/2019 4AM dumps (nw)

src/mame/drivers/didact.cpp, src/mame/layout/modulab.lay, src/mame/mame.lst
Nicer hardware compared to the other didact designs, it uses the C923 keyboard controller and also a INS8154 instead of the the MC6820 PIAs. I put some effort into the layout file and even managed to draw some diagonal lines using repeat, doesn't seem to affect performance and mostly for fun.
=> didact.cpp: New working machine modulab, a MC6802 based educational system

src/devices/sound/rf5c68.cpp, src/devices/sound/rf5c68.h, src/mame/drivers/megadriv.cpp, src/mame/machine/megacd.cpp, src/mame/machine/megacd.h
megacd.cpp : Remove unnecessary arguments in some handlers, MCFGs, deprecated warning, nw
=> rf5c68.cpp : Remove unnecessary arguments in handlers

src/devices/machine/nscsi_bus.cpp, src/devices/machine/nscsi_bus.h, src/devices/machine/nscsi_cd.cpp, src/devices/machine/nscsi_cd.h, src/mame/drivers/indy_indigo2.cpp, src/mame/machine/hpc1.cpp
Some versions of IRIX will always send an SGI vendor specific SCSI command to the CDROM, so we need some specialization to acknowledge this command.
=> nscsi_cd: Add new nscsi_cdrom_device derived type for SGI systems

hash/jakks_gamekey_dy.xml, hash/jakks_gamekey_nm.xml, hash/jakks_gamekey_sw.xml, scripts/src/bus.lua, scripts/target/mame/mess.lua, src/devices/bus/jakks_gamekey/rom.cpp, src/devices/bus/jakks_gamekey/rom.h, src/devices/bus/jakks_gamekey/slot.cpp, src/devices/bus/jakks_gamekey/slot.h, src/devices/machine/spg2xx.cpp, src/devices/machine/spg2xx.h, src/mame/drivers/vii.cpp, src/mame/mame.lst
---
Ms. Pac-Man 5-in-1 (Ms. Pac-Man, Pole Position, Galaga, Xevious, Mappy) (JAKKS Pacific TV Game, Game-Key Ready) [Sean Riddle, Peter Wilhelmsen, 20 external donators]
Disney Princess (JAKKS Pacific TV Game, Game-Key Ready) [Sean Riddle, 20 external donators]
Wheel of Fortune (JAKKS Pacific TV Game, Game-Key Ready) [Sean Riddle, 20 external donators]
new WORKING Software List entries
---
jakks_gamekey_nm:nrxdig New Rally X & Dig Dug  [Sean Riddle, Peter Wilhelmsen, 20 external donators]
Namco stuff is playable aside from sound issues (weirdly once certain games save the score, eg. Galaga, a sound channel gets lost)
Wheel of Fortune analog wheel isn't emulated, but it's an optional thing, you can just press B to spin.
also make the game keys actually save to the …
=>  new WORKING machines  (JAKKS stuff)

hash/apple2_flop_clcracked.xml, src/mame/machine/sgi.cpp
* Added some clean cracks.
* Fixed casing and names in a number of places.
* Added placeholder compatibility.
Additionally, should have finally fixed (once and for all, hopefully) the tab-spaces conversion that MULTIPLE of my text editors were hiding from me.
=> Apple II clcracked updates (nw)

src/mame/machine/hpc1.cpp
Fixes panic when indigo4k tries to read cdrom.
=> sgi hpc1, fix dma byte count mask, (nw)

src/emu/xtal.cpp, src/mame/drivers/trs80.cpp, src/mame/includes/trs80.h, src/mame/mame.lst
(nw) Note that "NTSC" and "PAL" would be misnomers for systems with monochrome video output and idiosyncratic line rates.
The 50 Hz timings have also been applied to the HT-1080Z (available documentation for which seems not particularly reliable).
I am submitting this as a PR to solicit input on the set name.
=> sys80: Add 50 Hz version with different timings

src/mame/drivers/gaelco2.cpp
Also, maybe we should remove the sound hardware mapping and add the MACHINE_NO_SOUND_HW flag, since the PCB has no sound hardware.
=> gaelco2.cpp: Fix some "saltcrdi" ROM sizes (nw)

src/emu/video.cpp
There might be a good reason for the code being the way it is. If so, feel free to discard this PR.
Currently, the video throttling code compensate for oversleep by multiplying the wanted sleep time by some averaged oversleep value. Which seems a bit weird to me.
Here is a plot of how much the SDL OSD oversleep with respect to the sleep duration requested. Each dot is a call to `osd_sleep`, the x coordinate is the argument to `osd_sleep`, the y coordinate is the measured duration. The overlseep duration clearly seems to be independant from the requested sleep duration.
Here is a plot of how long `osd_sleep` lasts with the multiplicative correction (`actual_ticks`) vs. how long we want it to last (`current_ticks - target_ticks`).
It almost always undersleep (then loop and sleep again), but …
=> Video throttling: Additive oversleeping

src/osd/eivcx86.h, src/osd/eminline.h
Can we have these? I didn't attempt to add implementations for anything other than MSVC, but I believe gcc and clang for 64-bit targets have equivalents.
=> osd: 64x64 multiply helpers (nw)

hash/apple2_flop_orig.xml
Apple Panic, Archon II: Adept, Bruce Lee, Conan, Gremlins, A Mind Forever Voyaging R77, Monty Plays Scrabble 4.0, Mr. Do, Photar, Space Raiders V2, Track and Field
=> Update WOZ to Feb 16, 2019 (nw)

hash/pc98.xml, hash/pc98_cd.xml
- Added new software items from the Neo Kobe Collection:
Cal III - Kanketsuhen
Cal Gaiden - Tiny Steps Behind the Cal
Capcom Tokoton Efude
Ce'st la vie
Centurion - Defender of Rome
Centurion - Defender of Rome (Alt)
Chiemi
Chou Shinri Samâdhi ((Alt)
Cherry Jam - Kanojo ga Hadaka ni Kigaetara
Cherry Jam - Kanojo ga Hadaka ni Kigaetara (Alt)
Chikyuu Bouei Shoujo Iko-chan - UFO Daisakusen
Clipper - Takepon no Ochimono Puzzle
Cocktail Soft - Zoukan-gou 2
Computer Technica FMC-98 Sound Card Driver Utility
Concert
Contec Super EMS
Cranston Manor
Cranston Manor (2HD conversion)
CRW - Metal Jacket
Cybernetic Hi-School / Dennou Gakuen
Shin'ou Densetsu Crystania
- Relabeled disks with their actual names
- Added usage notes for software that needs DOS
- …
=> pc98.xml: softlist updates, part 4 (C)

hash/vsmile_cd.xml
vsmile_cd.xml: Nickelodeon SpongeBob Squarepants - Idea Sponge (USA Rev. 1), Nickelodeon SpongeBob Squarepants - Idea Sponge (USA Rev. 2), Nick SpongeBob Schwammkopf - Ein Schwamm voller Ideen (Ger), The Amazing Spider-Man - Countdown to Doom (USA, Rev. 2), Disney/Pixar Cars - In The Fast Lane (USA Rev. 1), Disney/Pixar Cars - In The Fast Lane (USA Rev. 3), Wacky Race on Jumpin' Bean Island (USA Rev. 2), Wacky Race on Jumpin' Bean Island (UK), Shrek The Third - The Search for Arthur (UK) [redump.org, ClawGrip]
Also replaced the CloneCD dump from "Disney/Pixar Cars - In the Fast Lane (USA)" with a verified image from redump.org (CloneCD is not fully supported by CHD)
=> New NOT_WORKING software list additions

src/osd/modules/input/input_x11.cpp
SDL/X11 number mouse/lighgun buttons 1,2,3, while windows and other parts of
MAME like offscreen_reload expect 0,2,1. Transpose buttons 2 and 3, and then
-1 the button number to align the numbering schemes.
This fixes lightgun support on Linux - tested with an Ultimarc AimTrak and
the following config:
lightgun                  1
lightgun_device           lightgun
lightgunprovider          x11
lightgun_index1           "Ultimarc Ultimarc"
offscreen_reload          1
Note: MAME must be compiled with XInput support:
make -j10 NO_USE_XINPUT=0
Fixes bug #4695
With these changes, Lightguns on linux are perfectly accurate (well, as accurate as the gun itself allows... I miss real lightguns ;))
=> Linux X11 Input: Fix lightgun support

hash/vsmile_cd.xml
For the following games: "Disney Princess - The Crystal Ball Adventure (USA)", "Disney/Pixar The Incredibles - Mission Incredible (USA)", "The Amazing Spider-Man - Countdown to Doom (USA, Rev. 1)", "Scooby-Doo! Ancient Adventure (USA, Rev. 1)", "Wacky Race on Jumpin' Bean Island (USA, Rev. 3)", "Shrek the Third - The Search for Arthur (USA)" and "Bratz - Fashion Pixiez - The Secret Necklace (USA)".
The only remaining game created from a CCD image is "Nickelodeon SpongeBob Squarepants - Idea Sponge (USA)".
=> vsmile_cd.xml: Replace CHDs created from CloneCD images with new ones created from standard redump.org images [redump.org, ClawGrip]

src/devices/video/mc6845.cpp
Fix MT 06997, 06854 and 06423.
Also others games like "Profanation 2" works now.
=> mc6845.cpp: Do not reset line counter when screen parameters changed

src/devices/sound/pokey.cpp
* step_pot is called from step_one_clock only and just in case pokey is not in
reset state -> No need to check reset state again
* in case there were no bits in 'upd' latched to one, there is no need to call
synchronize(SYNC_POT, 0) because m_ALLPOT won't change.
Performance results with missile / starwars (no pots):
Before:
./mame64 -bench 50 missile -> Average speed: 1171.67% (49 seconds)
./mame64 -bench 50 starwars -> Average speed: 551.66% (49 seconds)
After:
./mame64 -bench 50 missile -> Average speed: 1321.16% (49 seconds)
./mame64 -bench 50 starwars -> Average speed: 551.10% (49 seconds)
=> pokey_device::step_pot: remove operations with no effect

src/devices/sound/pokey.cpp
* This fixes a regression introduced by [1]
* Could not detect and performance change introduced by this
[1] https://github.com/mamedev/mame/pull/4702/commits/308c3c2d04ce8f3af09f620f524579145cbbcaf0
=> pokey: force recalculation of raw sound output after reset

src/devices/video/mc6845.cpp
Regression caused by commit c4f0852c.
Thanks to Tafoid for catch it.
=> mc6845.cpp: Fix mk88 machine

src/devices/sound/pokey.cpp, src/devices/sound/pokey.h
In case
* no counters are running at high speed without prescalers - and
* no prescalers have triggered - and
* there is no borrow counter expected to finish
there is no need to continue on step_one_clock.
Performance measuements:
Before:
./mame64 -bench 50 missile -> Average speed: 1322.75% (49 seconds)
./mame64 -bench 50 starwars -> Average speed: 548.97% (49 seconds)
./mame64 -bench 50 jedi -> Average speed: 375.08% (49 seconds)
After:
./mame64 -bench 50 missile -> Average speed: 1503.10% (49 seconds)
./mame64 -bench 50 starwars -> Average speed: 648.10% (49 seconds)
./mame64 -bench 50 jedi -> Average speed: 444.25% (49 seconds)
=> pokey: yet another performance enhancement

src/devices/sound/pokey.cpp, src/devices/sound/pokey.h
This patch causes regression on sound for many machines. Fixing it shows
that it does not cause a performance win but the opposite - sigh.
Thanks to Scott Stone for tests and reporting.
This reverts most parts of commit 107fff092eb5c0f87adb09c0bdf42280ee94a95d.
=> Revert "pokey: yet another performance enhancement (#4735)"

src/devices/sound/bsmt2000.cpp, src/mame/drivers/deco32.cpp
The BSMT2000 audio board has support for 12 sound channels; 11 of them are for playing back signed 8-bit PCM, and the remaining one is for a custom 4-bit ADPCM format. Previously, ADPCM samples would not play back at all, or clip out the entire audio stream. 
Originally, tms_rom_w loaded a single byte from the sample ROM and sign-extended it to 16 bits. From looking at the DSP code, the problem for ADPCM is that the sample is required to be in the high byte; the DSP uses the midpoint of the 32-bit accumulator register to slice the sample into two nibbles. Regular PCM playback still worked (at 1/256th the expected amplitude!), but was extra quiet and a bit distorted at low volumes.
This patch changes tms_rom_w to shift-extend each sample, and removes the gain boost on the audio output. …
=> bsmt2000: fix 4-bit ADPCM sample playback

src/devices/cpu/m6809/6x09dasm.cpp, src/devices/cpu/m6809/6x09dasm.h
fixed bug in 6809 disassembler where the pc was not being incremented correctly for one particular indexed addressing case (it so happens the first instruction executed when running "mame cocoe -d" exhibited this bug).  looks like just an oversight since it is correctly implemented elsewhere nearby for similar cases.
also, the indexed addressing member function was misnamed "indirect" (guessing it's just a typo since the flag is IND for this mode).  i went ahead and changed the name of indirect() to indexed() in the 6809 disassembly header/source (this done in a separate commit from the above fix).
added a change to use the absolute address in the operand for pc relative indexed addressing (where the assembler computes the offset).  i found that several 6809 assemblers *required* this …
=> Fix for 6809 disassembly

hash/specpls3_flop.xml
These changes add most of the DSKs featured in the latest TOSEC DAT files which, according to Lady Eklipse, include all files that were in TOSEC and all files from www.worldofspectrum.org which were never in TOSEC before. Which file and update they come from is commented for each entry, so that they can be consulted.
Files removed:
- Files marked as "bad dumps" which have a "good" parent set.
- Trained games, except for a "cheat version" of Neighbours which may have come from the original developers.
- 80-track (3.5'') disk images.
- Files generated with the ZXZVM interpreter.
- Games from the Crap Games Competition.
All the DSK files which have a corresponding IPF have been labeled as "alt" clones until they're confirmed to come from the exact same release and can be safely removed …
=> specpls3_flop.xml: DSKs from latest TOSEC DATs

src/devices/machine/upd765.cpp
Result from Read ID must be the sector ID information during execution phase. So result must be:
- Zeroes if not ready (execution phase is not reached).
- Command codes if ready but scan failed (execution phase is reached but ID is not found). This patch fixes this.
- If scan is correct then result is the ID information from sector found.
Fix MT 06611
=> upd765.cpp: Correct result from Read ID when scan failed

hash/apple2_flop_orig.xml
Add:
The Super Factory, Lancaster, Captain Goodnight and the Islands of Fear, Eggs-It, Choplifter, Lunar Leepers, Golden Mountain, Akalabeth, Championship Lode Runner, Gamma Goblins, Serpentine, Gruds in Space, Muppetville, Dazzle Draw (version 1.1), Ultima III: Exodus, A.E., Ernie's Quiz, Mix and Match, Spotlight, Beer Run, Phaser Fire, Bug Attack, Alien Lander, High Orbit, The Asteroid Field, Where in the World is Carmen Sandiego, Labyrinth, Ribbit
=> Update WOZ to Mar 18, 2019 (nw)

src/tools/imgtool/filtbas.cpp
if a basic line didn't terminate a string with a closing double-quote (which is apparently ok - it is just automatically terminated by the basic interpreter), then basic_readfile() would fail to parse the first token on the following line (behaving as if it were still parsing a string from the previous line).
this change just forces each line to begin "outside" of a string (ie. the first encountered double quote on a line will always start a new string).
=> fix for (imgtool) filtbas when strings left unterminated in basic lines

src/osd/modules/render/drawogl.cpp
This one was triggered by batman.
Test case:
mame64 -nothrottle batman
Before: Average speed: 312.11% (20 seconds)
After: Average speed: 327.43% (19 seconds)
=> OSD/OpenGl: Improve performance by moving calculations out of loop

src/mame/drivers/esd16.cpp, src/mame/includes/esd16.h, src/mame/video/esd16.cpp
Reduce unnecessary lines, duplicates, ACCESSING_BITs, Simplify handlers, gfxdecodes, Mark 8x8 tilemap dirty when VRAM data is changed, Fix naming
=> esd16.cpp : Updates

src/mame/drivers/gaelco2.cpp, src/mame/includes/gaelco2.h, src/mame/machine/gaelco2.cpp, src/mame/video/gaelco2.cpp
Reduce duplicates, unnecessary lines, defines, Fix namings, spacings, code styles, Simplify handlers, Use shorter/correct type values
Mark tilemap dirty when RAM base is changed]
Allow save for snowboar exclusive protection related value
=> gaelco2.cpp : Updates

hash/fmtowns_cd.xml
This is a quick fix for a couple of mistakes that I made with PR #4808. It corrects the name and size of the lotr2 user disk.
=> fmtowns_cd.xml: fix some mistakes

src/mame/drivers/expro02.cpp, src/mame/drivers/jchan.cpp, src/mame/drivers/kaneko16.cpp, src/mame/drivers/sandscrp.cpp, src/mame/video/kaneko16.cpp, src/mame/video/kaneko_tmap.cpp, src/mame/video/kaneko_tmap.h
Add address_map for VRAM handling, Move expro02.cpp exclusive tilemap bankswitching function into expro02.cpp (now callback'd), Fix namings, Reduce duplicates, Simplify handlers
expro02.cpp : Minor simplify handlers, Reduce runtime tag lookup, Minor fix naming
jchan.cpp : Fix notes
kaneko16.cpp : Reduce unnecessary lines, Fix notes
=> kaneko_tmap.cpp : Updates / Cleanups

hash/nes.xml, src/devices/bus/nes/namcot.cpp, src/devices/bus/nes/nes_ines.hxx, src/devices/bus/nes/nes_pcb.hxx, src/devices/bus/nes/nes_slot.h
devices/bus/nes/namcot.cpp : Add note
reference : https://wiki.nesdev.com/w/index.php/INES_Mapper_019
=> Implement Namcot 163 expansion sound volume difference related to NES 2.0 submapper format

src/mame/video/zx8301.cpp
The previous behavior looks like it was a temporary implementation, where it was just flashing black. This patch makes the flash bit latch the current color until another set flash bit appears. I've compared it with the real hardware, and it looks the same (except for the speed of the flash).
=> Flash latches the color as on real QL

src/devices/bus/isa/3c505.cpp, src/devices/bus/isa/3c505.h, src/devices/bus/isa/isa_cards.cpp, src/mame/machine/apollo.cpp
For review/comment especially by @rb6502 and Hans Ostermeyer because it's:
* a rewrite/replacement of prior work, and proposes taking over the copyright as well; and
* untested on Apollo at the moment because the driver is crashing while trying to install Domain/OS (unrelated to this device).
Testing with the 3c505.exe diagnostic program on MS-DOS passes the Group 1 & 2 tests successfully when using 16-bit DMA channel. It intermittently fails the Group 2 transmit test when using an 8-bit channel.
=> 3c505: replace hle (nw)

hash/apple2_flop_misc.xml, hash/apple2_flop_orig.xml
Misc sets:
Anti-M 1.0, Anti-M 1.1, Anti-M 1.2
WOZ original sets:
Apple-oids and Chipout, Spider Raid, Lazer Silk, Maze Craze Construction Set, Escape From Rungistan, Zaxxon, Star Blazer, Rocky's Boots (version 4.0), The Flockland Island Crisis, The Print Shop Color, Star Warrior, Warp Destroyer, Super Bunny, Type Attack, Kabul Spy, Arkanoid, Fantavision, Peeping Tom, Blade of Blackpoole, Wizardry III (version 4), Arcade Album #1, BurgerTime, Robots of Dawn, Dig Dug, Zork I (revision 5)
=> Misc and Woz updates to Apr 11th 2019 (nw)

scripts/src/machine.lua, scripts/target/mame/mess.lua, src/devices/cpu/unsp/unsp.cpp, src/devices/cpu/unsp/unsp.h, src/devices/cpu/unsp/unspdasm.cpp, src/devices/cpu/unsp/unspdasm.h, src/devices/cpu/unsp/unspdrc.cpp, src/devices/machine/sunplus_gcm394.cpp, src/devices/machine/sunplus_gcm394.h, src/mame/drivers/gaelco2.cpp, src/mame/drivers/sunplus_gcm394.cpp, src/mame/drivers/vii.cpp, src/mame/mame.lst, src/mame/mess.flt
pull SunPlus GCM394 titles out of vii.cpp
- it's a newer SoC (with a lot more capabilities, eg rotate, zoom, twice the sound channels)
- it uses an updated unSP core (with some extra opcodes)
also made the modifications needed to allow for extension of the unSP + disassembler once we've worked out what the extra opcodes are.
=> pull SunPlus GCM394 titles out of vii.cpp

src/lib/formats/tzx_cas.cpp
=> tzx_cas.cpp: Apply 1ms pause only on data blocks

docs/source/advanced/index.rst, docs/source/advanced/linux-lightguns.rst
WORK IN PROGRESS
Add a new doc page within the 'Advanced Configuration' section which
describes how to enable Lighuns on Linux using the XInput lightgun
provider.
Related PRs: https://github.com/mamedev/mame/pull/4913 https://github.com/mamedev/mame/pull/4698 https://github.com/mamedev/mame/pull/4862 https://github.com/mamedev/mame/pull/4118
=> WIP: Document Linux Lightguns with Xinput

hash/vsmile_cart.xml
Disney Aladdin - Il magico mondo di Aladdin (Italy)
Disney's The Little Mermaid - Ariel's Majestic Journey (UK)
The Batman - Gotham City Rescue (UK)
Disney/Pixar Cars - Rev It Up in Radiator Springs (UK)
Disney's Cinderella - Cinderella's Magic Wishes (UK)
Disney Topolino - Le Magiche Avventure di Topolino (Italy)
Noddy - Detective for a Day (UK)
Winnie the Pooh e la caccia al miele (Italy)
DreamWorks Shrek - Het Verhaal Van Draakje (Netherlands)
Spider-Man & Friends - Missioni Segrete (Italy)
Thomas & Friends - Engines Working Together (UK)
Disney/Pixar Toy Story 2 - Operation-Rescue Woody! (UK)
vsmile_cart.xml: new NOT_WORKING software list additions [Walter Agazzi]
Bob The Builder - Bob's Busy Day (UK) …
=> vsmile_cart.xml: new WORKING software list additions [Walter Agazzi]

hash/specpls3_flop.xml
Added more disk images, some of which were previously missing from the internet due to them being considered "Distribution Denied".
Thanks go to: Antonio M, Fede Jerez, Gorski, Jaime González Soriano, José Manuel, Marino Arribas, Metalbrain, robcfg, Simon Owen, Syx, Zup and TZX Vault.
Also fixed a few things here and there (extra line breaks, full company names, capital letters...).
NOTE: Due to the addition of a UK version of Navy Seals, the Spanish version has been renamed from "navyseal" to "navysealsp" and is now a clone of the new "navyseal".
=> specpls3_flop.xml: New additions

src/mame/drivers/daryde.cpp
(nw) It may be useful to have a working NVRAM dump when working on the driver
=> daryde.cpp: Add NVRAM dump to "cricket" [@LosTrastosDeXaX, ClawGrip]

src/mame/video/pc080sn.cpp, src/mame/video/pc080sn.h, src/mame/video/taito_helper.cpp, src/mame/video/taito_helper.h, src/mame/video/tc0080vco.cpp, src/mame/video/tc0080vco.h, src/mame/video/tc0150rod.cpp, src/mame/video/tc0150rod.h, src/mame/video/tc0480scp.cpp, src/mame/video/tc0480scp.h
Allow masked priority behavior, Use correct/shorter type values
pc080sn.cpp, tc0080vco.cpp, tc0150rod.cpp, tc0480scp.cpp : Fix spacing, Use shorter / correct type values, Allow masked priority behavior
=> taito_helper.cpp : Updates

src/devices/cpu/unsp/unsp.cpp, src/devices/cpu/unsp/unsp_extended.cpp, src/devices/cpu/unsp/unsp_fxxx.cpp, src/devices/cpu/unsp/unspdasm.h, src/devices/cpu/unsp/unspdasm_extended.cpp, src/devices/cpu/unsp/unspdasm_fxxx.cpp, src/mame/drivers/sunplus_gcm394.cpp
smartfp clearly uses unsp isa20 push/pop instructions in the interrupt even if nowhere else in the code (nw)
=> smartfp clearly uses unsp isa20 push/pop instructions in the interrupt

src/frontend/mame/luaengine.cpp
- This is not directly related to outputting lua help (https://github.com/mamedev/mame/issues/3000), but if those comments are accurate, it'd be a a step towards that goal. Therefore, _I'd like this to be reviewed_.
- Only touching comments, not code
- Tested everything I could get to work (watchpoint and thread libraries completely refused to work and kept crashing or giving errors)
- Fix syntax mismatch
- Add missing functionality (don't know where to add `address_map_entry` comments not to break actual code; also don't know how to use `input:seq_poll*`)
- Reorder and group methods and fields together
- Call out libraries by object type
- Include full commands to access library objects (short commands relied on other commands which were scattered around the file, requiring constantly …
=> Improve luaengine comments (fixes and updates)

src/mame/drivers/at.cpp, src/mame/mame.lst
=> at.cpp: Siemens-Nixdorf notebooks (non-working) and 486 mainboards,

plugins/autofire/autofire_menu.lua, plugins/autofire/autofire_save.lua, plugins/autofire/init.lua, plugins/autofire/plugin.json
This is a plugin I wrote to provide autofire/turbo functionality in MAME. MAME already has a built-in autofire feature accessed through the cheats menu, but this implementation contains extra features/flexibility, including:
- Saving and loading autofire settings (saves a config file per rom so autofire settings will be remembered the next time you load the rom)
- Separate buttons for autofire and non-autofire
- Individual autofire rates per button (e.g. one button for 30 Hz autofire and another for 15 Hz). The number of frames to hold the button and the number of frames to release the button are individually customizable.
Note: One potential point of confusion is that the autofire keybindings are managed in the menu provided by the plugin, separate from the regular input menu. It's …
=> Add plugin for autofire

src/mame/drivers/seibucats.cpp, src/mame/drivers/seibuspi.cpp, src/mame/includes/seibuspi.h, src/mame/machine/seibuspi.cpp, src/mame/machine/seibuspi.h, src/mame/video/seibuspi.cpp
Simplify handlers, Simplify gfxdecodes, Fix / cleanup some DMA / drawing routines, Reduce unnecessary lines, Fix spacings, Namings, Use shorter / correct type values
seibucats.cpp : Add seperate video config related to no tilemap present, sprite bpp differs, Add notes, Fix sound output
=> seibucats.cpp, seibuspi.cpp : Updates

hash/apple2_flop_clcracked.xml, hash/apple2_flop_orig.xml
This is an interim update to get my own work caught up with the official branch. There will be at least one more PR this month.
Add originals:
Microsoft Adventure, Micro Invaders, Blister Ball and Mad Bomber, Typing Tutor, Space Warrior, The Crimson Crown, Zykron Hearts, Gold Rush, The Print Shop Companion (Version 1.2), Adventureland (Version 2.0/416), Pirate Adventure (Version 2.1/408), Mission Impossible (Version 2.1/306), Voodoo Castle (Version 2.1/119), The Count, Strange Odyssey, Neptune, Where in Europe is Carmen Sandiego, Wishbringer (R68), Dueling Digits, Elite, Fore, Gorgon, Hacker, Impossible Mission, Juggler, Sorcerer of Siva, Top Fuel Eliminator, Zork II (R7), Tass Times in Tonetown, Robotwar
Cleanly cracked:
Seven Cities of Gold, Stickybear Printer (Revision 2)
Fixes: 
Disk …
=> A2 WOZ and clean cracked updates for May 14th 2019 (nw)

src/mame/drivers/pgm.cpp, src/mame/includes/pgm.h, src/mame/machine/pgmprot_igs025_igs012.cpp, src/mame/machine/pgmprot_igs025_igs012.h, src/mame/machine/pgmprot_igs025_igs022.cpp, src/mame/machine/pgmprot_igs025_igs022.h, src/mame/machine/pgmprot_igs025_igs028.cpp, src/mame/machine/pgmprot_igs025_igs028.h, src/mame/machine/pgmprot_igs027a_type1.cpp, src/mame/machine/pgmprot_igs027a_type1.h, src/mame/machine/pgmprot_igs027a_type2.cpp, src/mame/machine/pgmprot_igs027a_type2.h, src/mame/machine/pgmprot_igs027a_type3.cpp, src/mame/machine/pgmprot_igs027a_type3.h, src/mame/machine/pgmprot_orlegend.cpp, src/mame/machine/pgmprot_orlegend.h, src/mame/video/pgm.cpp
Simplify handlers, Simplify gfxdecodes, Move non-public things into protected: and/or private:, Make sprite drawing routine related to cliprect, Fix tilemap region size for fit 5bpp tile correctly, Reduce unuseds, Unnecessary lines, MCFG_MACHINE_START, MCFG_MACHINE_RESET, MCFG_VIDEO_START overrides, Runtime tag lookups, Fix debugger issues, Fix namings, Spacings, Use shorter / correct type values, Fix notes
Move palette init function into machine_config
=> pgm.cpp, pgmprot_*.cpp : Updates

src/mame/drivers/cave.cpp, src/mame/includes/cave.h, src/mame/video/cave.cpp
Simplify handlers, Use common interface for palette, Use seperated gfxdecode, palette, screen finder, bitmap for ppsatan each screen, Move sprite granularity into video_start, Allow save state for sailormn 3th tilemap, Reduce runtime tag lookups, Unnecessary lines, Fix debugger issue, Fix spacings, Use shorter / correct type values, Add notes
=> cave.cpp : Updates

src/mame/arcade.flt, src/mame/drivers/mazerbla.cpp
In MAME 0.206 the MCFG macros were removed and Great Guns crashed in the attract mode.
Typo in palette init:
PALETTE(config, "palette", FUNC(mazerbla_state::mazerbla_palette), 246+1);
246+1
instead of
256+1
=> Fixed Great Guns palette init typo

src/devices/video/315_5124.cpp, src/devices/video/315_5124.h, src/devices/video/315_5313.cpp, src/devices/video/315_5313.h, src/mame/drivers/megadriv.cpp, src/mame/drivers/vgmplay.cpp, src/mame/includes/megadriv.h, src/mame/machine/mega32x.cpp, src/mame/machine/mega32x.h, src/mame/machine/megadriv.cpp
315_5124.cpp : Use color lookup and correct color levels for 315_5313, Add notes
315_5313.cpp : Use color lookup, Convert bitmap drawing function into bitmap_rgb32, Reduce unused, Fix save pointers, Fix external palette handlers, Implement 3 bit color mode
mega32x.cpp : Use color lookup, Reduce unuseds, Add device_palette_interface
=> Sega 315-5313 color related function updates

plugins/autofire/autofire_menu.lua, plugins/autofire/autofire_save.lua, plugins/autofire/init.lua, plugins/autofire/plugin.json
This fixes a bug with saving/loading autofire settings, where soft-resetting the game would cause the settings to be lost due to their being reloaded from the settings file.
This also fixes a crash that could happen by hard-resetting a game in the middle of editing/adding an autofire button. The menu state would not be cleaned up, and accessing the old ioport_field references would cause MAME to crash.
I also replaced the get_settings_path implementation that reads the plugins path option and concatenates "/autofire/cfg/" with one that implements "set_folder" to get the plugin's directory, because I just learned that that exists.
=> Autofire plugin: Save/load fixes

src/mame/drivers/jaguar.cpp, src/mame/video/jaguar.cpp
Correct gpu timer rate related to gpu clock, Fix notes, Fix crash cause in 68ec020 cpu games (all 68ec020 based games are HDD based, no bankswitched ROMs)
=> jaguar.cpp : Updates

scripts/src/bus.lua, src/devices/bus/hp9845_io/98046.cpp, src/devices/bus/hp9845_io/98046.h, src/devices/bus/hp9845_io/hp9845_io.cpp, src/devices/bus/hp9845_io/hp9845_io.h, src/devices/bus/hp_optroms/hp_optrom.cpp, src/devices/bus/hp_optroms/hp_optrom.h, src/devices/machine/z80sio.cpp, src/devices/machine/z80sio.h, src/mame/drivers/hp9845.cpp, src/mame/includes/hp9845.h
Hi everyone,
this PR is for the addition of HP98046 serial I/O emulation. In order to satisfy the insanely in-depth HP test software I add to rewrite a lot of Z80 SIO emulation. I'm now convinced that the SIO is now a lot closer to the real hw than before. By the way, the Univac UTS20 self-test passes, too. I'm mentioning it because "uts20" is written all over the place in z80sio.cpp...
Thanks.
--F.Ulivi
=> Hp9845: added 98046 module emulation

src/mame/drivers/hh_sm510.cpp
Fix order of miss segments (should be right to left)
=> hh_sm510: segment id fix (nw)

plugins/autofire/autofire_save.lua, plugins/autofire/init.lua, plugins/autofire/plugin.json
According to feedback on #5093 and [documentation that I missed](https://docs.mamedev.org/commandline/commandline-all.html#core-search-path-options), plugins are expected to save data to homepath rather than pluginspath.
=> Change autofire config directory to homepath

src/mame/drivers/nes_vt.cpp, src/mame/mame.lst
---------------------------------------------------------
VRT VT SDK 'Pink Jelly' (VT03 Demo) [ClawGrip]
VRT VT SDK 'VT03 Sound Test' (Sound Generator FMDemo) [ClawGrip]
---------------------------------------------------------
VRT VT SDK 'Pinball' (C-Compiler Demo Program 2) [ClawGrip]
VRT VT SDK 'Boxing' (Demo for VT03 Pic32) [ClawGrip]
(nw) All those programs came from the official VT SDK from V.R. Technology. I'm not sure about the flags, as being demo programs I'm not sure what they should really do or look like. At least "Pink Jelly" looks better on the emulator bundled with the VRT VT SDK than on MAME.
=>  New WORKING machines 

src/devices/machine/z80sio.cpp
Hi,
this commit fixes a few regressions caused by my last changes to Z80SIO driver.
In detail:
+ **altos5**, **isbc28612**, **isbc2861**, **c8002** now have the same exact image on screen as before at the end of 10 seconds of emulation,
+ **c5000** has one more word ("tape") displayed, probably because some initial self-test is now a bit faster,
+ **att4425** doesn't change after this fix, but I'm convinced that the current image is more correct (the one showing "keyboard test failed", as the generic rs232 keyboard that is connected has no loopback function).
This list of systems was provided by Tafoid as a comment to my last PR (#5115), it's probably not complete. I'll look into new regressions as they are reported.
Thanks.
--F.Ulivi
=> Z80SIO: fixed a few regressions after PR #5115

src/mame/drivers/exedexes.cpp, src/mame/includes/exedexes.h, src/mame/video/exedexes.cpp
Use prio_* for sprite draw routine, Simplify handlers, gfxdecodes, Reduce runtime tag lookups, Unnecessary lines, Fix namings, Spacings
=> exedexes.cpp : Updates

scripts/genie.lua, scripts/src/osd/modules.lua
- `dxsdk` was missing from includes
- `winmm` was missing from libs
- narrowing warning was silenced for VS, but not from vsllvm, where it leads to an error in `menu_video_options::handle()`
=> fix vsllvm configuration

src/devices/video/stvvdp2.cpp, src/emu/drawgfx.cpp, src/emu/drawgfx.h, src/emu/drawgfxm.h, src/mame/drivers/realbrk.cpp, src/mame/includes/realbrk.h, src/mame/video/hng64.cpp, src/mame/video/realbrk.cpp
Move additive blending function into drawgfx.h, Add priority related copybitmap and draw_scanline functions, Fix spacings
Priority related copybitmap and draw_scanline  functions are sprite like priority handling(prio_) and tilemap like priority handling (primask_), These are helpful for priority related bitmap / scanline drawing routines.
drawgfxm.cpp: Add variations of priority related pixel draw functions, Fix spacings
realbrk.cpp: Updates, Example usage for prio_copybitmap
Simplify handlers, Use priority bitmap for sprite priority, Fix spacings, Use shorter / correct type values
=> drawgfx.cpp : Updates

src/mame/drivers/fuukifg2.cpp, src/mame/drivers/fuukifg3.cpp, src/mame/includes/fuukifg2.h, src/mame/includes/fuukifg3.h, src/mame/video/fuukifg.cpp, src/mame/video/fuukifg.h, src/mame/video/fuukifg2.cpp, src/mame/video/fuukifg3.cpp
Use callback for colour, priority, tilebank behaviors, Internalize gfxdecodes, Use external spriteram, Reduce unnecessary lines, Fix spacings, Use shorter / correct type values
fuukifg2.cpp, fuukifg3.cpp : Updates
Correct spriteram, vreg types, Use tilemap buffer behavior into RAM bank (number of actually visible tilemap layer is 3), SImplify handlers, Reduce unnecessary lines, Fix notes, Spacings, Use shorter / correct type values
=> fuukifg.cpp : Updates

src/mame/drivers/aquarium.cpp, src/mame/drivers/gcpinbal.cpp, src/mame/includes/aquarium.h, src/mame/includes/gcpinbal.h, src/mame/video/aquarium.cpp, src/mame/video/excellent_spr.cpp, src/mame/video/excellent_spr.h, src/mame/video/gcpinbal.cpp
Internalize gfxdecode, Use callback for priority behavior, Reduce unnecessary lines, Simplify handlers, Fix spacings
aquarium.cpp, gcpinbal.cpp : Updates
Simplify handlers, gfxdecodes, Reduce unnecessary lines, Runtime tag lookups, Fix namings, Use shorter / correct type values, Move virtuals under protected:, Rearrange devices under values in .h files
gcpinbal.cpp : Make tilemap dirty when tilebank is changed
=> excellent_spr.cpp : Updates

src/devices/sound/mas3507d.cpp, src/devices/sound/mas3507d.h, src/mame/machine/k573dio.cpp, src/mame/machine/k573dio.h, src/mame/machine/k573fpga.cpp, src/mame/machine/k573fpga.h
**Please don't merge until there has been a sufficient review done.**
This fixes most of the regressions from https://github.com/mamedev/mame/commit/c910c1cf0ab357df250aff10002547e52e896f76.
I will be leaving comments to explain why I made certain changes just to make sure we're on the same page and make it easier to give advice for a better way to write something. It might be easier to review on a per-commit basis since the commits are pretty self-contained.
~~The MP3 decoder still has heavy glitching problems but that's probably going to take the longest time to fix out of the regressions.~~
Update: All bugs that I had previously found, except one where you can briefly hear the previously played audio for less than a second between MP3 transitions, have been fixed now with the latest …
=> Fix regressions in k573dio/k573fpga/mas3507d

src/emu/xtal.h
This is probably due to the fact that IBM 128bit long double format is not constant folded.
I slighlty rewrote ""_kHz_XTAL(long double clock) and ""_MHz_XTAL(long double clock)
the way ""_kHz_XTAL(unsigned long long clock) and ""_MHz_XTAL(unsigned long long clock) are written.
which makes the compiler happy.
I initially sent this patch in Debian : 
https://salsa.debian.org/games-team/mame/merge_requests/15/diffs
which fixes the bug in Debian from my tests.
Thanks,
F.
=> Fix ppc64el issue #3157

src/mame/drivers/undrfire.cpp, src/mame/video/tc0100scn.h
Simplify gfxdecodes, Correct 6bpp gfx decode behavior into mix ROM data, Fix naming
tc0100scn.cpp : Add sync granularity function with bg gfx
=> undrfire.cpp : Updates

src/mame/drivers/2mindril.cpp, src/mame/drivers/taito_f3.cpp, src/mame/includes/taito_f3.h, src/mame/video/taito_f3.cpp
Convert VRAMs into shared_ptr, Fix namings, Spacings, Simplify gfxdecodes, Handlers, Split hi 2bpp of gfx data to each rom, Correct 6bpp gfx decode behavior into mix ROM data, Reduce duplicates, Runtime tag lookups, Unnecessary lines, Move structs into taito_f3.h, Fix postload
taito_f3.h : Move taito_f3.cpp exclusive things under private:
=> taito_f3.cpp, 2mindril.cpp : Updates

hash/apple2_flop_clcracked.xml, hash/apple2_flop_misc.xml, hash/apple2_flop_orig.xml
Adds several new WOZ originals, three versions of AppleWorks in the misc disks section, and some small metadata corrections.
=> Original Apple II WOZ images to June 7th, 2019, AppleWorks in Misc (nw)

src/mame/drivers/toaplan2.cpp, src/mame/includes/toaplan2.h, src/mame/video/gp9001.cpp, src/mame/video/gp9001.h, src/mame/video/toaplan2.cpp
Simplify handlers, gfxdecodes, Correct tilemap behavior (each tiles are grouped 4 8x8 tile), Use callback for gfx bankswitching behavior, Use shorter / correct type values
toaplan2.cpp : Fix spacing, Reduce unnecessary lines
=> gp9001.cpp : Updates

src/mame/drivers/groundfx.cpp, src/mame/video/groundfx.cpp
Simplify gfxdecodes, Fix spacing, Correct 6bpp gfx decode behavior into mix ROM data, Reduce unnecessary lines
=> groundfx.cpp : Updates

src/devices/bus/vectrex/rom.cpp
rom.cpp: change 64KiB cart bank reset value from 0 to 1.
The real hardware starts up in bank 1, so this is more accurate behavior. The real fix is to emulate the pull-up resistor on PB6 when it's set to input mode, but it doesn't look like MAME supports that right now.
This fixes 64KiB carts "Where Have All the Pixels Gone?" and "EigenVectrex," quite possibly others.
No regressions found.
=> Vectrex reset into bank 1 for 64KiB carts

src/devices/cpu/i386/cache.h
Basically, there was some testing code here that assumed unsigned char was always 8 bits, and that unsigned int was always 32 bits, which fails on some systems.
=> Fix up some commented out testing code (nw)

src/mame/drivers/gticlub.cpp, src/mame/drivers/hornet.cpp
I missed a small detail from that I/O board. There are actually two variations of this board. The one used in Operation: Thunder Hurricane uses a K056230 while the one in Teraburst uses a K056800. I guess this is how the assumption of this board used for networking and sound came into place. Thunder Hurricane's main pcb gets it's gun/analog values by networking with its I/O board while Teraburst has it's I/O board directly connected to its main pcb directly to the main cpu. The usage of an additional K056800 for Teraburst will remain unknown for now.
I will admit this was difficult to notice at first.
=> Better to document the GN680 I/O board

src/mame/drivers/toaplan2.cpp, src/mame/includes/toaplan2.h, src/mame/video/toaplan2.cpp
Simplify handlers, Fix namings, Spacings, Reduce duplicates, Unnecessary lines, Runtime tag lookups, Correct output rate, Use optional_memory_bank for bgaregga/batrider OKI bankswitching because these aren't present NMK112, Use shorter / correct type values
=> toaplan2.cpp : Updates

src/mame/drivers/megatech.cpp
Correct ROM type in games description (23C4000 -> 834200A)
Correct a typo (Gold -> Golf)
Correct ROM labels (mpxx -> mpr-xx)
Correct ROM size (0x100000 -> 0x080000) and related crc and sha1. Added comment.
=> Correct ROM names, size + some info

src/devices/cpu/m6502/oxavix.lst, src/devices/cpu/m6502/xavix.cpp, src/devices/cpu/m6502/xavix.h
xavix - store the extra codebank byte in a private stack when making long calls etc. (fixes crash on calibration screen in rad_hnt2)
this seems feasible as it's an extension to the CPU, so keeping it in a private stack would maintain better compatibility with 6502 code
=> xavix - store the extra codebank byte in a private stack when making long calls etc.

hash/pc98.xml, hash/pc98_cd.xml
- Added new software items from the Neo Kobe Collection:
D.O. Doki Doki Disk Vol. 08
Daijuutai
Dam Busters
Dangerous Toys
Dark Seraphim
Datenshi Kyouko Part I
Dead Force
Delicious Lunch Pack
Dennou Garou
Desert Dragoon - Sabaku no Ryuukihei
Desire - Haitoku no Rasen
Diadrum
Director Monogatari
Dires - Giger Loop
DiskX II
Bishoujo Daizukan
Diver's
Doki Doki Pretty League Dai-1-wa - Pink Angels Kiki Ippatsu no Maki
Doki Doki Pretty League Dai-2-wa - Mou Hitotsu no Rival
Doki Doki Pretty League Dai-3-wa - Minami no Umi no Kai no Maki
Doki Doki Pretty League Dai-4-wa - Nanase no Himitsu no Maki
Doki Doki Pretty League Dai-5-wa - Saraba Pink Angels-tachi
Doom II
Doop
Dora Dora Emotion - Seihaiden
DR² Night Janki
Dragon Master Silk - Ryuu Shoukan Musume - Episode II
Dragon Master Silk - Ryuu …
=> pc98.xml: softlist updates, part 5 (D)

src/mame/drivers/toypop.cpp
=> toypop.cpp: liblrabl: The sprite of the flower withered by an enemy like scissors was not correct.

src/lib/formats/tzx_cas.cpp
@AmatCoder it appears the changes you made cause the various Speedlock loaders to fail (this is the vast majority of the full-price commercial library for the system after a certain point, so this is a major regression.
as an example / test case, the following sets from the software list NO LONGER function in 0.202 due to the changes made.   (used with 'spectrum' machine)
batmana - fast loader - yellow/blue
batmanb - fast loader with timer, black/blue
batmanf - fast loader - yellow/blue
The following didn't change (mostly budget rereleases or alt tzx encodings that use different block types to represent the same things)
unknown loader/encoding (never worked due to flawed 0x19 - Generalized Data Block?)
batmanc
batmang
flashy border loaders (works before and after)
batman
batmand
batmanh …
=> revert tzx_cas changes from 0.202, they break things

src/devices/bus/isa/myb3k_fdc.cpp, src/devices/bus/isa/myb3k_fdc.h, src/mame/drivers/myb3k.cpp
Adds support for FDC4712 8-inch floppy disk controller card for MyBrain 3000 (and clones).
As part of this work I've moved common functionality between the FDC471x cards into a base class `isa8_myb3k_fdc471x_device_base` (as suggested in the file header). There's a few things I'm not completely happy with in regards to the implementation:
- FDC4710 only supports connecting up to 2 disk drives. I've implemented this restriction with an `optional_device_array<floppy_connector, 4>` on the base class, with `isa8_myb3k_fdc4710_device::device_add_mconfig` only adding two floppy connectors, but I'm not sure if this is the right approach.
- Motor control support is toggled via `has_motor_control`, which is set in each device subclass.
There are probably other things as well - any direction as to …
=> myb3k: Add support for FDC4712

src/devices/bus/isa/myb3k_fdc.cpp, src/devices/bus/isa/myb3k_fdc.h
As pointed out in #5256, the FDC4711 card uses an FD1791 chip as opposed to the MB8876A used on the FDC4710 and FDC4712.
=> myb3k_fdc.cpp: Use FD1791 for FDC4711

src/devices/bus/a2bus/mouse.cpp, src/devices/bus/spectrum/opus.cpp, src/devices/bus/ss50/mpc.cpp, src/devices/machine/6821pia.cpp, src/devices/machine/6821pia.h, src/mame/drivers/coinmstr.cpp, src/mame/drivers/mpu3.cpp, src/mame/drivers/zwackery.cpp, src/mame/includes/coco.h, src/mame/includes/coco3.h, src/mame/machine/coco.cpp, src/mame/machine/coco3.cpp, src/mame/machine/dgn_beta.cpp, src/mame/machine/thomson.cpp
This is mostly about cleaning up how port A's register is read when in output mode. Previously, pins in output would always read their input value, but this is only true in a rare situation where a device was driving the pins.
This is a followup to PR 5175, which got rolled back. It's been tested with all the boards that were broken in https://github.com/mamedev/mame/pull/5175#issuecomment-500396359 .
=> Pia6821 improvements

scripts/target/mame/mess.lua, src/mame/drivers/gaelco2.cpp, src/mame/drivers/prestige.cpp, src/mame/drivers/redclash.cpp, src/mame/drivers/tomy_princ.cpp, src/mame/mame.lst, src/mame/mess.flt
- move princ out of prestige.cpp (it should have never been put there) and into a new driver
- fix graphic alignment on the salter gym machines, also promote htem both to working (the hang I saw before on cycle doesn't seem to happen now)
- re-parented the Red Clash sets based on evidence suggesting it is a Kaneko game
note, princ uses a F2MC-16L based CPU, I don't believe we have a core, but there are plenty of docs available should somebody want to write a disassembler at least.
=> misc changes (move princ to new driver - needs F2MC-16L CPU core, promote salter/gaelco stuff, manufacturer note in redclash.cpp)

src/mame/drivers/nwk-tr.cpp, src/mame/drivers/plygonet.cpp
Was going to add them in an earlier branch but it didn't come to mind. Also, some more nwk-tr stuff:
- Racing Jam Chapter 2 and Thrill Drive were released as a conversion kit that contained additional replacement roms and another network board which added a PIC EEPROM at 2G. The purpose of that PIC EEPROM may have been both formatting the old timekeeper data as well as prevent game/region swapping. thrilldea has it's rtc check shows as "JAD" so it fails because it reads the incorrect region.
- Speak of thrilldea, the version itself isn't correct as the program roms use the "B" version. I'm marking the rtc dump as bad because the first fourteen bytes have incorrect data. This also requires changing the region on the network board
=> Missed two drivers (nw)

src/frontend/mame/luaengine.cpp, src/frontend/mame/ui/auditmenu.cpp, src/frontend/mame/ui/custui.cpp, src/frontend/mame/ui/datmenu.cpp, src/frontend/mame/ui/dirmenu.cpp, src/frontend/mame/ui/filesel.cpp, src/frontend/mame/ui/info.cpp, src/frontend/mame/ui/info.h, src/frontend/mame/ui/inputmap.cpp, src/frontend/mame/ui/menu.cpp, src/frontend/mame/ui/menu.h, src/frontend/mame/ui/miscmenu.cpp, src/frontend/mame/ui/moptions.cpp, src/frontend/mame/ui/moptions.h, src/frontend/mame/ui/optsmenu.cpp, src/frontend/mame/ui/selector.cpp, src/frontend/mame/ui/selmenu.cpp, src/frontend/mame/ui/simpleselgame.cpp, src/frontend/mame/ui/sliders.cpp, src/frontend/mame/ui/slotopt.cpp, src/frontend/mame/ui/sndmenu.cpp, src/frontend/mame/ui/submenu.cpp, src/frontend/mame/ui/ui.cpp, src/frontend/mame/ui/ui.h, src/frontend/mame/ui/utils.cpp, src/frontend/mame/ui/viewgfx.cpp
The various UI_*COLOR macros were implemented as calls to
decode_ui_color, which cached the values for the various options in a
static array, which was obviously a gross hack.
This refactoring is strategic because I am trying to confine awareness
of mame_ui_manager to code in src/frontend/mame/ui, and the
implementation of decode_ui_color() relied on the ability to access
mame_ui_manager as a singleton from outside this code.
=> Changed the various usages of UI_*COLOR to be calls to src/frontend/mame/ui/moptions.h

hash/fmtowns_cd.xml
- Added new items from the redump.org database:
Cat's Part-1
DOR Best Selection Gekan
Gokko Vol. 1 - Doctor
Professional Mahjong Goku
Scavenger 4 (1993-11-11)
Taiken Shiyou! Marty Channel
- Replaced the following items with images that match the redump.org database. In many cases the existing images had no offset correction (which leads to small chunks of audio data at the start/end of the disc being missing) and no proper pregaps, so these should be better.
The 4th Unit 5 - D-Again
The 4th Unit 7 - Wyatt
Genocide Square
Gunship - The Helicopter Simulation
The Legend of Kyrandia (promoted to working due to this change)
Kyrandia II - The Hand of Fate
Last Armageddon CD Special
Mahjong de Pon!
Misty - Meitantei Toujou
Puyo Puyo
Schwarzschild IV - The Cradle End
Silent Möbius
Splatterhouse …
=> fmtowns_cd.xml: additions, replacements and cleanups

src/devices/cpu/i386/i386.cpp, src/devices/cpu/i386/i386.h, src/devices/cpu/i386/i386op16.hxx, src/devices/cpu/i386/i386op32.hxx, src/devices/cpu/i386/i386ops.hxx, src/devices/cpu/i386/i386segs.hxx
As of right now, both instruction AND data breakpoints work perfectly with the CUP386 debugger, which i ran on ctmouse.exe like: `cup386 c:\ctmouse.exe /3 /d`
Some rudimentary testing was also done with Soft-Ice (breaking into the debugger from the DOS prompt doesn't work, likely due to other bugs in the at386 driver), and also a rather obscure real-mode 386 debugger that you can get from here, which has working data breakpoints in this emulation: http://sites.e-advies.nl/download/i386-debug/monitor4.exe
This PR makes MAME the second i386 emulator to ever implement the instruction breakpoints (the first being pcx86 in pcjs), and the first ever i386 emulator to implement the data breakpoints, that i know of.
I don't expect this PR to get merged before MAME 0.200's release, as @cuavas has …
=> Add hardware breakpoint functionality to the i386 core.

src/devices/bus/nes_ctrl/zapper.cpp, src/devices/bus/sms_ctrl/lphaser.cpp, src/devices/video/ppu2c0x.cpp, src/devices/video/ppu2c0x.h, src/mame/drivers/nes.cpp, src/mame/includes/nes.h, src/mame/machine/playch10.cpp, src/mame/machine/vsnes.cpp, src/mame/video/nes.cpp, src/mame/video/playch10.cpp
Split of pull request #4910, contains only the necessary changes to fix the light gun regression first mentioned in MT report https://mametesters.org/view.php?id=7331
Note: the NES and derivative drivers required some additional changes when compared to SMS and derivative drivers because the code for the NES stuff wasn't prepared for more than one screen update per frame (only for full frame updates) and the line drawing routine for the NES PPU device is programmed to draw the last line that was surpassed by the beam, contrary to the routine of the SMS VDP (despite similar scheduling) that draws the next line that will be surpassed by the beam.
=> nes, sms: Fix light gun regression

src/mame/drivers/nmk16.cpp, src/mame/includes/nmk16.h, src/mame/video/nmk16.cpp
Reduce duplicates, Move afega related stuffs into afega_state, Cleanup twinactn OKI bankswitching routine
tdragon2, raphero has address-swapped main RAM; related to protection?
Simplify handlers, Reduce unnecessary lines, Runtime tag lookups, Fix spacings, Namings, Use shorter / correct type values
correct sound output (afega games aren't having a stereo output)
Fix metadata, Add/Fix notes (Vince is seems like a bootlegger name (bootleg set title is still 'Red Hawk'), Add 'horizontal' in horizontal screen version of red hawk games)
Fix tilemap RAM bankswitching behavior - mark tilemap dirty when RAM bank is changed
=> nmk16.cpp : Updates

src/devices/bus/gamegear/ggext.cpp, src/devices/bus/gamegear/ggext.h, src/devices/bus/gamegear/smsctrladp.cpp, src/devices/bus/nes_ctrl/ctrl.cpp, src/devices/bus/nes_ctrl/ctrl.h, src/devices/bus/nes_ctrl/hori.cpp, src/devices/bus/nes_ctrl/hori.h, src/devices/bus/nes_ctrl/joypad.cpp, src/devices/bus/nes_ctrl/zapper.cpp, src/devices/bus/nes_ctrl/zapper.h, src/devices/bus/sms_ctrl/lphaser.cpp, src/devices/bus/sms_ctrl/lphaser.h, src/devices/bus/sms_ctrl/multitap.cpp, src/devices/bus/sms_ctrl/rfu.cpp, src/devices/bus/sms_ctrl/smsctrl.cpp, src/devices/bus/sms_ctrl/smsctrl.h, src/mame/drivers/nes.cpp, src/mame/drivers/nes_vt.cpp, src/mame/drivers/sms.cpp
Currently the light gun device is making an assumption about the screen used by the host system. This patch moves to the host system the responsibility to define the screen used by the light gun.
=> nes,sms: Change the way screen is set for the light gun device

src/mame/drivers/playch10.cpp, src/mame/video/playch10.cpp
Data of the PPU (that manages the game/bottom screen) is incorrectly being used by the screen_update code of the "top" (selection) screen, and the screen_update code of the "bottom" screen is using the data of the selection screen. The problem was not noticed for games using the standard controller because the screen order is inverted in the machine config. This patch fix the screen_update codes and the screen order, what is necessary to fix the light gun problem of MT 7331: https://mametesters.org/view.php?id=7331
=> playch10: Fix order and screen_update code for both screens

src/emu/video.cpp, src/emu/video.h, src/frontend/mame/luaengine.cpp
`pixels()` and `size()` correspond to internal game resolution covering all screens and internal pixel colors. The same values are used for bitmap dumping. Similar things available for `screen_device` lua library take into account final UI resolution and colors, so they can't be used when accurate framebuffer is needed.
`refresh_attoseconds()` allows to calculate precise numerator and denominator for framerate.
=> luaengine: video:size(), video:pixels(), screen:refresh_attoseconds()

src/devices/sound/mas3507d.cpp, src/devices/sound/mas3507d.h
- k573dio now correctly reports the actual number of samples already
played (instead of rounding up by one discrete mpeg frame in advance and
disregarding samples that have been copied to the stream but not yet
actually played).
=> k573dio: timing fixes

src/lib/formats/tzx_cas.cpp
Current TZX specification says: "Header blocks have 8063 and data blocks have 3223 pilot pulses"
It also says: "The pilot tone consists in 8063 pulses if the first data byte (flag byte) is < 128, 3223 otherwise"
(unlike tap format that if flag byte is 0 indicates header block and data block otherwise).
=> tzx_cas.cpp: Fix pulses on Standard Data blocks

src/mame/drivers/fmtowns.cpp
Currently all FM Towns software that uses CDDA starts and stops playing audio at the wrong position, 2 seconds ahead to be exact. This is more noticeable in some cases than others (e.g. the cutscenes in Vain Dream, Last Armageddon or the Emit series are completely out of sync), and is caused by the Towns CD-ROM controller using absolute addressing (starting from the beginning of the TOC area, or sector -150) while the CDDA device in MAME uses LBA addressing (starting from sector 0).
The current code already takes care of this, but just for track 1. This change applies the same principle to all CD read operations by substracting 150 sectors from the start/end positions on the MSF-to-LBA calculation.
Note that CD images improperly dumped without audio track pregaps might still start at the …
=> fmtowns.cpp: fix CDDA start/end position

src/frontend/mame/ui/ui.cpp
The UI startup screens are meant to be shown in the main window, but it doesn't exist in this case. For platforms with mandatory images it won't run without them anyway, so one just has to provide one. Game info screen can also be disabled in the options. But for machine warnings, there's no easy way to get past them, mostly because there's no window to accept user inputs. Maybe it can be done with lua, but it's not trivial. So I just disabled the blocking UI screens.
PS: This video mode is headless to some extent, and mame can be controlled via lua console just fine. There's even a command to shut down the emulator (`manager:machine():exit()`). So the warning saying `-video none doesn't make much sense without -seconds_to_run` is only partially true. This mode is quite usable overall.
=> Disable UI startup screens for "-video none"

src/emu/emuopts.h, src/emu/image.cpp
Fixing MameTesters 07377, 06880, 06677 and 06655.
(This does not fix the underlying problem which is discussed in #2555).
=> Fix segfault when trying to access some image option that does not exists

hash/fmtowns_cd.xml
- Added 4 new entries that match the redump.org database (all working):
G5
Leading Company
Sekigahara
Shinjuku Labyrinth
- Promoted emit1, emit2 and vastness to working due to the CDDA playback fix in PR #5346 and removed the notes about CDDA desyncs in vaindrem and vaindrm2.
- A couple of title fixes that I missed on the previous cleanup
=> fmtowns_cd.xml: additions, metadata fixes

src/emu/emuopts.cpp, src/emu/emuopts.h, src/frontend/mame/ui/ui.cpp
This is needed for worker_ui, where BletchMAME implements its own file management capabilities
=> Created a -skip_mandatory_fileman option

src/mame/drivers/nycaptor.cpp
they contain significantly less data than the bootlegs, and will definitely need to be checked if/when an original PCB shows up to dump the MCU
=> mark some Cycle Shooting roms as BAD_DUMP (nw)

plugins/boot.lua, src/frontend/mame/clifront.cpp, src/frontend/mame/luaengine.cpp, src/frontend/mame/mame.cpp, src/frontend/mame/pluginopts.cpp, src/frontend/mame/pluginopts.h, src/frontend/mame/ui/miscmenu.cpp
This makes MAME's plugin less "bubble gum and duct tape".  Specifically:
* plugin_options no longer derives from core_options, and has its own object model
* we still use core_options internally for INI parsing and generation
* this is also more extensible; it is now easier to thread information into plugins
* boot.lua is now dramatically simplified; it no longer has to replicate the logic for searching the plugins directory for plugin.json
* a side effect is that the old boot.lua is no longer compatible
* old code that accessed manager:plugins() is also likely not compatible, but this doesn't seem to be a problem
* -plugin and -noplugin will now error when they are invoked for a nonexistent plugin
Hypothetically, plugin_options and pluginopts.cpp should be renamed to plugin_manager and …
=> Refactored MAME's plugin system

src/devices/machine/mc6846.cpp
The bit definitions for the timer modes were backwards. The datasheet might have mislead here, it tables these bits low to high, left to right, which is not the usual convention.
=> mc6846 - fix the timer modes.

src/emu/tilemap.cpp
There was no bug noticed there, but the calculation looks wrong, it looks like it intended to calculate the difference between the limits not to add them.
=> tilemap - fix calculation of visible area height and width.

src/mame/video/fmtowns.cpp
This fixes a regression introduced with commit bb32d72c7e68d4b34a94e1250f1440394d473f7d that causes semi-random emulator crashes (at least in non-debug builds) in 38-man Kilo no Kokuu and Yami no Ketsuzoku Special. Apparently they are trying to set colors for palette indexes higher than 15 in 16-color mode, and the m_entry_color array goes out of bounds.
I'm not sure if the hardware discards everything but the 4 least significant bits of the palette index, or if it ignores the color change completely, but it doesn't seem to make any difference in practice, so I'm assuming the former.
=> fmtowns.cpp: fix crash regression in System Sacom games

src/emu/tilemap.cpp
This reverts https://github.com/mamedev/mame/pull/5393 The original looks good, sorry. A comment has been added to the source to clarify the meaning of the 'width' and 'height' variables, which might be better understood to the `2 * left + width + 1` and `2 * top + height + 1`. These were only used as inputs to the `effective_*scroll()` functions and their use can be followed there.
=> tilemap: revert changes to the tile scroll computations.

src/devices/bus/sega8/sega8_slot.cpp, src/devices/video/315_5124.cpp, src/devices/video/315_5124.h, src/mame/machine/sms.cpp
When Charles MacDonald documented the horizontal display timing of the 315-5124 chip (SMS VDP) in his msvdp-20021112.txt document, he calculated the HCount values based on the active display start value, that he assumed to be 0x00. For example, the horizontal sync starts 279 pixels after the active screen start position, then its HCount value was documented as 0x8B. There's some documentation in MAME's 315_5124.cpp file that follows the same assumption. More recently, when he did some tests on a Japanese SMS (http://www.smspower.org/forums/viewtopic.php?p=92925), he discovered that horizontal sync starts at HCount 0xE9 instead 0x8B. This pull request changes the 315_5124.cpp documentation of the horizontal timings to new HCount values based on the discovered horizontal sync start value …
=> 315_5124: Adjust horizontal screen positions

hash/vsmilem_cart.xml
It may take a while to dump them, it's better to mark them to avoid duplications when looking for undumped games
=> vsmilem_cart.xml: Mark soon-to-be-dumped carts (nw)

src/devices/bus/spectrum/exp.cpp, src/devices/bus/spectrum/exp.h, src/devices/bus/spectrum/intf1.cpp, src/devices/bus/spectrum/intf1.h, src/mame/drivers/spec128.cpp, src/mame/drivers/spectrum.cpp
this mimics behaviour found in other emulators, stops nonsense commands from triggering nonsense save operations with interface1 installed which was caused by the rom banking out too early.
=> add a 'post opcode fetch' to spectrum expansion bus so that interface 1 enable / disable works correctly

src/mame/drivers/m72.cpp
The last dump we did didn't work on the real hardware, so we've dumped it again with different equipment and this new dump works fine on the real PCB
=> m72.cpp: Re-redumped the GAL of "lohtb" [parramon]

src/frontend/mame/info.cpp, src/frontend/mame/info.h, src/frontend/mame/ui/miscmenu.cpp
- The two variations of output() no longer duplicate logic
- No longer relying on driver_enumerator::config() to create machine_config objects.  Because driver_enumerator would cache all objects created, we would needlessly hog memory
=> Refactored info_xml_creator::output()

src/frontend/mame/info.cpp, src/frontend/mame/info.h, src/frontend/mame/ui/miscmenu.cpp
Specifically, this simplifies that change by collapsing the newly introduced enum info_xml_creator::devices_disposition into a bool, more resembling what was there before.
It occurred to me that having a tristate was unnecessary, because the need for filtering could be expressed by a null std::function for the filter
=> Follow up to previous listxml_refactor PR (nw)

src/emu/emuopts.cpp, src/emu/emuopts.h, src/frontend/mame/luaengine.cpp, src/frontend/mame/luaengine.h, src/frontend/mame/mame.cpp, src/frontend/mame/mame.h, src/frontend/mame/ui/info.cpp, src/frontend/mame/ui/info.h, src/frontend/mame/ui/ui.cpp
- Removed the -skip_mandatory_fileman command line option
- Created an emu.register_mandatory_file_manager_override() LUA functionto allow LUA plugins to substitute the mandatory file manager
=> Changed mechanisms for overriding the mandatory file manager

src/lib/formats/m20_dsk.cpp, src/tools/floptool.cpp
This enables writing to M20 *.img files. 'floptool' enhanced to support M20 images as well.
=> add write support for Olivetti M20 floppy images

src/frontend/mame/ui/ui.cpp
This is a bug fix to an earlier PR
=> Surpressing mandatory file manager when -str (seconds to run) is on (nw)

src/mame/drivers/thedeep.cpp
The Deep uses a Rockwell R65C02 CPU for sound. See PCB (top right cpu)
http://adb.arcadeitalia.net/media/mame.current/pcbs/thedeep.png
=> Correct audio CPU for The Deep

scripts/src/osd/modules.lua, scripts/src/osd/sdl.lua, src/devices/cpu/arm7/arm7.cpp, src/emu/debug/debugcpu.cpp, src/emu/debug/debugcpu.h, src/emu/distate.h, src/osd/modules/debugger/debuggdbstub.cpp, src/osd/modules/lib/osdobj_common.cpp, src/osd/modules/lib/osdobj_common.h
This debugger can be used to connect to an external debugger that
communicates using the GDB Remote Serial Protocol, such as GDB itself
or many other GDB frontends.
Currently i386 (ct486), arm7 (gba), and ppc (pmac6100) are supported.
=> gdbstub: added new GDB stub debugger

src/devices/machine/wd_fdc.cpp, src/devices/machine/wd_fdc.h
Some machines do not connect the SSO output to control the floppy side. When this new callback option is used the wd_fdc no longer controls the floppy, rather calls the SSO callback. E.g. a SWTPC DC4 or DC5 FDC uses SSO to control the density, by inverting the SSO output and connecting that to the DDEN input, and this support is needed there.
=> wd_fdc: add a SSO callback.

scripts/src/formats.lua, src/lib/formats/uniflex_dsk.cpp, src/lib/formats/uniflex_dsk.h, src/tools/floptool.cpp
The UniFLEX disk format is not compatible with the Flex format. Significantly it does not use a mix of single density for booting on some double density disks which makes it simpler - hardware required a new boot ROM to run UniFLEX. Further, the UniFLEX sector size is 512 bytes versus 256 for Flex, and the UniFLEX 'SIR' info sector record is completely different to the info on Flex disk, and the file system format is also not at all compatible.
Thus the UniFlex format can rely largely on the WD17xx format, with an overload to handle the sector numbering on the second side continuing from the first side (one feature in common with the Flex format). This gives a quick 'save' capability and shares code.
Support for 8" disks is included as this was the initial distribution format and the only …
=> Add a UniFLEX specific floppy format.

src/lib/formats/flex_dsk.cpp, src/lib/formats/flex_dsk.h, src/lib/formats/wd177x_dsk.h
This now works with both single density and double density floppy disks, and dynamically identifies boot sector IDs required for 6800 booting, and supports writing back to the 'dsk' image files. UniFLEX support has been split out into a separate format.
=> flex floppy dsk: rewrite to be based on the wd177x dsk format

makefile
This fixes the 'cleansrc' operation on Unix/Linux.
With current version I'm getting this when running "`make cleansrc`":
```
$ make cleansrc
GCC 8 detected
Cleaning up tabs/spaces/end of lines....
Cleaned up src/devices/video/virge_pci.h:
7 line(s) with trailing whitespace trimmed
3 tab(s) expanded to spaces
Cleaned up src/devices/bus/isa/s3virge.h:
4 line(s) with trailing whitespace trimmed
Cleaned up src/devices/imagedev/wafadrive.h:
1 tab(s) expanded to spaces
Cleaned up src/mame/machine/pce_cd.h:
2 line(s) with trailing whitespace trimmed
2 tab(s) created from spaces
11 space(s) combined into tabs
Cleaned up src/mame/includes/pc9801.h:
1 line(s) with trailing whitespace trimmed
Cleaned up src/osd/windows/window.h:
10 tab(s) expanded to spaces
Cleaned up …
```
=> toplevel makefile: fix 'cleansrc' target for Unix/Linux

src/devices/video/315_5313.cpp, src/devices/video/315_5313.h, src/mame/drivers/calcune.cpp, src/mame/drivers/megadriv.cpp, src/mame/drivers/segac2.cpp, src/mame/includes/segas18.h, src/mame/machine/mega32x.cpp, src/mame/machine/mega32x.h, src/mame/machine/megacd.cpp, src/mame/machine/megacd.h, src/mame/machine/megadriv.cpp
Correct timer rate related to screen refresh rate for 315_5313.cpp, megacd.cpp, mega32x.cpp
315_5313.cpp : Reduce duplicates, Simplify DMA behavior, Add notes, Simplify handlers, Fix spacing, Reduce unnecessary lines, Use shorter / correct type values, Fix debugger issue
megadriv.cpp, segac2.cpp, calcune.cpp : Correct screen refresh rate, Add notes (source : https://segaretro.org/Sega_Mega_Drive/Technical_specifications)
megadriv.cpp : Allow Z80 VDP reading, Correct VDP sound output
calcune.cpp : Fix naming, Add notes
=> 315_5313.cpp DMA / Timer Updates, Correct refresh rate and timer rate related to systems when using mega drive VDP

scripts/genie.lua, scripts/src/devices.lua, scripts/src/emu.lua, scripts/src/mame/frontend.lua, scripts/target/mame/arcade.lua, scripts/target/mame/dummy.lua, scripts/target/mame/mess.lua, scripts/target/mame/nl.lua, scripts/target/mame/tiny.lua, scripts/target/mame/virtual.lua, src/devices/cpu/bcp/bcpdasm.cpp, src/devices/cpu/cr16b/cr16bdasm.cpp, src/devices/cpu/f2mc16/f2mc16dasm.cpp, src/devices/cpu/hpc/hpcdasm.cpp, src/devices/cpu/rii/riidasm.cpp
Precompiled headers are enabled only in the following library projects:
emu
frontend
precompile
dasm
optional
=> Enable precompiled header usage in the Visual Studio compiler

src/frontend/mame/info.cpp, src/frontend/mame/info.h
This is primarily to make the output be deterministic.
=> Ensuring that devices emitted by -listxml are sorted

src/tools/imgtool/filtbas.cpp, src/tools/imgtool/main.cpp, src/tools/imgtool/modules/thomson.cpp
Based on the code in `filtbas.cpp` and @Pulkomandy's `bastok.cpp` for some info about the format.
Note that while I can write and read a BASIC file, I've not fully checked whether each token is correctly selected (I think there's a problem with `GO` vs. `GOSUB`).
=> Add BASIC Thomson tokenizer

scripts/src/bus.lua, src/devices/bus/ss50/interface.cpp, src/devices/bus/ss50/mps2.cpp, src/devices/bus/ss50/mps2.h
For the SWTPC09. A step in moving the serial port support out of the SWTPC-09 machine. Worked fine in FLEX and UniFLEX. Still need the MPS for the SWTPC 6800 - they are designed for different I/O address ranges, 4 bytes versus 16 bytes.
=> SS-30 MP-S2: Dual Serial Interface

scripts/src/bus.lua, src/devices/bus/ss50/interface.cpp, src/devices/bus/ss50/piaide.cpp, src/devices/bus/ss50/piaide.h
Split out the PIA IDE hard disk interface from the swtpc09 machine. This support appears to have been incomplete or to have bit rotten, and has been updated and tested lightly with FLEX9.
=> SS-30 PIA IDE hard disk interface

scripts/src/bus.lua, src/devices/bus/ss50/dc5.cpp, src/devices/bus/ss50/dc5.h, src/devices/bus/ss50/interface.cpp
Split out the floppy disk controller from the swtpc09 machine, adding it to the ss50 interface. The DC5 is compatible with both the SWTPC 6800 and 6809 systems, supporting the 4 and 16 byte I/O interfaces respectively, via a jumper setting, so can be used on the MAME swtpc and swtpc09 machines. The DC5, like the DC4, supports double sided and density disks, and claimed backward compatibility with the DC1, DC2 and DC3.
Test on the swtpc 6800 and swtpc09 machines running FLEX and FLEX9.
=> SS-30 DC5 floppy disk interface

src/frontend/mame/info.cpp, src/frontend/mame/info.h
This is to keep things isolated to a single translation unit as much as possible
=> Moved most of the implementation of info_xml_creator to anonymous namespaces

src/emu/sound.cpp, src/emu/sound.h, src/frontend/mame/luaengine.cpp, src/frontend/mame/ui/ui.cpp
```lua
manager:machine():sound():samples()
manager:machine().samplerate
```
Obtaining samples enables me to output it along with video buffer and even record a video externally. These videos show that I'm correctly grabbing the audio buffer:
https://www.youtube.com/watch?v=WQTMy-zdXqM
https://www.youtube.com/watch?v=IiNi8HvgIGA
I had to make `samples_this_update` a class member so that it persists until the next frame and can be exposed to other classes. There doesn't seem to be a way to know this information until mixing is done for a given frame. In my case luaengine needs it in order to know the size of the buffer it should allocate.
Couple instances of tiny cleanup is also included.
=> Expose sound buffer and samplerate to luaengine

makefile, src/devices/cpu/g65816/g65816ds.h, src/devices/cpu/lh5801/5801dasm.h, src/devices/cpu/m37710/m7700ds.h, src/devices/cpu/m68000/m68kcpu.h, src/emu/http.cpp, src/emu/save.h, src/mame/machine/sec.h, src/osd/modules/file/posixptty.cpp, src/osd/modules/font/font_sdl.cpp, src/osd/modules/output/network.cpp
This is a patch that excludes third-party fixes, which I will attempt to get merged upstream, see #5508, #3205.
=> Fix Solaris 2.11 (non-Oracle)

src/emu/machine.cpp, src/emu/main.h, src/frontend/mame/luaengine.cpp, src/frontend/mame/luaengine.h, src/frontend/mame/mame.cpp, src/frontend/mame/mame.h
- Created emu.register_before_load_settings(), to allow LUA scripts to
override default input port values before settings are loaded
- New ioport_field methods/props ([set_]default_input_seq(), port)
=> Miscellaneous LUA functionality

src/mame/drivers/swtpc09.cpp, src/mame/includes/swtpc09.h, src/mame/machine/swtpc09.cpp
Add support for the SS-30 bus. The DC5 FDC, MPS2, PIA-IDE and MPT have been
added to the SS-30 bus and are split out.
A separate floppy format has been added for UniFLEX, and the FLEX format has
been improved. These formats should be usable now, and have been lightly
tested.
The banked memory was not implemented correctly and has been updated.
The DMAF2 and DMAF3 FDCs are still implemented in the swtpc09 device, but have
been updated. These belong on the SS-50 bus, but there is no SS-50 bus yet -
still on the TODO list.
The PIA IDE has been implemented on the SS-30 bus, and updated to get it
working, and the swtpc09i machine is promoted to working. Have been able to
boot this from a FLEX hard disk image, and it also boots FLEX using the DC5
FDC.
Tested swtpc09 running FLEX with DMAF2 …
=> swtpc09: update, use the SS-30 bus, get these working.

src/mame/drivers/chinagat.cpp
Current document says it's unknown where are the background images
stored. But it should be in the TRJ-100 custom package, that needs a
custom adapter to dump it.
Also add a side note that the TRJ-100 chip generates 5MHz clock for
some unknown reasons, and used by some ICs as a clock. This may help
to solve the speed problems in the future.
=> Update PCB information in chinagat.cpp

src/emu/rendfont.cpp
In C++98/03, basic_string::c_str() was allowed to be a reallocation to insert the null terminator. MAME is ensuring this actually happens with a do-nothing call to c_str().
In C++11 and later, this is prohibited, and the string is mandated to be always null terminated. As a result Visual C++ marks c_str() with [[nodiscard]], triggering a warning here for discarding the result.
(I don't know of any C++03 implementation that actually reallocates here, but just in case this code actually targeted such an implementation I've just suppressed the warning for now. If MAME only targets C++11 or later, we should fix it by deleting the line.)
=> Resolve [[nodiscard]] warning from c_str() call.

.travis.yml
Due to ppas used the travis-ci only works with trusty. With xenial being the default as of August 2019 the builds fail most of the time. Request trusty explicitly until the CI configuration can be migrated to a more recent Ubuntu release.
=> Explicitly use Ubuntu Trusty

src/lib/formats/flex_dsk.cpp
It had been printing the disk name again.
=> flex_dsk: fix the logging of the disk name extension

src/devices/cpu/tms34010/34010ops.hxx
Correctly handle S=1, D=1 case which allows any alignment of
source and destination. Fixes endless loop in atronic / atricmon.
=> tms34020: Fix BLMOVE S=1, D=1 opcode handling

scripts/genie.lua, scripts/src/osd/sdl.lua
The current Emscripten release is not happy with the use of "-s ERROR_ON_MISSING_LIBRARIES=0" as a link option, it gives an error stating that all libraries must now be present, so remove that use.
This leaves a missing 'util' library. This did not appear to be needed on the few builds I have tried, and this patch avoids adding this library for asmjs.
I still get an error `emcc: cannot find library "SDL2_ttf`. Simply removing that library at the linking stage allows it to proceed, and I don't see any related missing symbols. Not sure about this one, emscripten does build this one and cache it.
Has anyone else seen these problems and know more?
=> asmjs: can not ignore errors on missing libraries

src/mame/drivers/hh_sm510.cpp
This fixes changes the tone length for the game over tune and adds a stop bit so the end of level tune isn't played after a miss.
=> hh_sm510: Melody ROM fixes for gnw_mbaway melody

src/mame/drivers/supbtime.cpp
The 68000 core, DATA EAST chip 59, should run at 10.738636MHz.
This is confirmed by DE-0343-4, Tumblepop. Pin 57 is for the clock.
=> Fix the main cpu clock for the DE-0343 board

src/devices/video/mc6845.cpp
It appears that the cursor is not displayed when the start raster address is equal to the maximum raster address in the 'interlace and video' mode. At least this addresses a claimed regression in the 'apricot' machine. To be explored further on hardware.
The maximum raster address was also off by one in these calculations.
Addressing regressions noted in https://github.com/mamedev/mame/pull/5562 and thank you again for the reports and patience.
=> mc6845: address cursor display edge case in interlaced mode.

src/devices/video/mc6845.cpp, src/devices/video/mc6845.h
For the HD6845 the cursor does not wrap around as it does for the MC6845.
Thank you for exploring this. This might not deal with all edge cases, but appears to address the reported regressions, and attempts to take into account results of hardware testing.
=> HD6845: specialize the cursor emulation

src/mame/drivers/supbtime.cpp
The HuC6280 core seems to run at 8.055MHz rather than 16.110MHz.
Confirmed by DE-0343-4, Tumblepop.
=> Fix the audio cpu clock for the DE-0343 board

src/emu/natkeyboard.cpp, src/frontend/mame/ui/ui.cpp, src/osd/modules/lib/osdlib.h, src/osd/modules/lib/osdlib_macosx.cpp, src/osd/modules/lib/osdlib_unix.cpp, src/osd/modules/lib/osdlib_uwp.cpp, src/osd/modules/lib/osdlib_win32.cpp, src/osd/osdcore.h
This change has only been tested on Windows.  The Un*x/Mac versions were
made blindly; they might not even build.  This needs to be checked prior
to merging.
=> Changed osd_get_clipboard_text() to return std::string

src/devices/cpu/g65816/g65816.cpp, src/devices/cpu/g65816/g65816.h, src/devices/cpu/g65816/g65816cm.h, src/devices/cpu/spc700/spc700.cpp
Resolve MT06901 and MT07419
Also it fixes other games like Cliffhanger, Taekwon-Do and Super Tekkyuu Fight
=> [snes] Fix 5a22/spc700 clock cycles

src/emu/video.cpp
This tweak allows the user to decide if throttling should be forced while paused. Of course if we're just talking about the paused state, this makes no sense, but when we're frame-stepping, we might want throttling to go away.
I used an obscure option that's only checked in a single place and intended for debug use. Its nature seems to fit my purpose quite well, and it's also used along with `machine().paused()` in that one place that had it, exactly like I do here.
In my case, I control MAME remotely via luaengine and I have a periodic callback that advances a frame (among other things). When throttling is forced during pause, I can only get 50% speed with this method, even if I send `-video none -nothrottle`. Using frame advance on periodic callbacks seems to be required not to mess …
=> Don't force throttling while paused

scripts/target/mame/mess.lua, src/mame/drivers/mekd4.cpp, src/mame/drivers/mekd5.cpp, src/mame/layout/mekd4.lay, src/mame/layout/mekd5.lay, src/mame/mame.lst, src/mame/mess.flt
Motorola MC6809 evaluation board. This emulation implements the keypad and LED 7 segment display, and the RS-232 terminal interface, and the MEK68R2 MC6845 CRT and parallel keyboard interface. The RAM and ROM banking is not yet implemented but most of the D4BUG monitor commands are supported.
Some questions if anyone cares to help me get up to speed with MAME:
* If the machine emits sound for only a cassette interface then should it be flagged as `MACHINE_NO_SOUND`? Is that for a sound card rather than emulation of the machines noises?
* This board includes an address bus comparator which can trigger an interrupt. It is used for tracing and debugging. This has been implement by general address read and write functions and a bank device to add another address map. Is there a cleaner way to …
=> MEKD4 and D5: new machines

.appveyor.yml
As tea-ci has been broken for quite a while now, there has been no MINGW CI available. MINGW builds can be done in appveyor too. Tools build had to be disabled as it takes longer than the allowed 60 minutes. Wa,-mbig-obj was added to avoid "file too big" errors.
=> Add gcc build to appveyor

src/mame/drivers/icebox.cpp
(for example: Command '220 LOAD' now works with disk GORF8102.IMD)
=> [icebox] Add INTRQ handler so that disk routines can work properly

src/mame/drivers/at.cpp, src/mame/drivers/genpc.cpp, src/mame/drivers/ibmpc.cpp, src/mame/mame.lst
Landmark/Supersoft Diagnostics ROMs for PC, XT and AT (IBM versions) and Ruud Baltissen's Diagnostics ROM for generic PCs.
=> at.cpp: 386 BIOS versions and motherboards, PC drivers: diagnostics

src/mame/drivers/mekd3.cpp
These are empty and giving a validation warning. Needs more development.
=> mekd3: remove the ROM bank attempt

src/mame/drivers/hh_sm510.cpp, src/mame/mame.lst
-------------
Game & Watch: Balloon Fight (crystal screen) [algestam, hap]
This PR adds the Crystal Screen version of G&W Balloon Fight. Since the Crystal Screen was released before the New Wide Screen version, the names has been changed so that the Crystal Screen version is called gnw_bfight and the New Wide screen version is named gnw_bfightn.
=> New Working clone added

src/mame/machine/segabill.cpp
Similar data is provided for other Sega boards. I tried to be as descriptive as I could. If more or less information is needed please advise.
=> Adding visual and descriptive board layout for Versus City Billboard

src/lib/netlist/plib/putil.h
Oddly, this problem does not seem to manifest under clang on gcc.godbolt.org.  I suspect that this might be related to the fact that sizeof(std::size_t) != sizeof(long) on Windows.
=> Fixed a compilation bug under clang-cl

hash/midi_flop.xml, src/mame/drivers/atpci.cpp, src/mame/drivers/ct486.cpp, src/mame/drivers/ps2.cpp, src/mame/machine/at.cpp
A weird list this one. This is a "software" list for standard MIDI floppy disks. Content is dumped by me from my own disk.
This should be possible to enable for any MIDI-compatible synthesizer with 3.5" drive. Please tell me of any such drivers and I'll attempt to hook it up for them. I could only think of the SQ-80, but the floppy drive doesn't seem to be working yet for it.
=> Add MIDI floppy softlist

src/emu/main.h, src/emu/sound.cpp, src/frontend/mame/luaengine.cpp, src/frontend/mame/luaengine.h, src/frontend/mame/mame.cpp
New samples are generated independently from the video system, vblank, frames, etc. Sound update uses its own timer and fires [50 times per second](https://github.com/mamedev/mame/blob/master/src/emu/sound.cpp#L884). So if we want to grab the sound buffer, we need to do it 50 times per second as well.
This PR adds a callback that fires whenever audio has been updated and new samples have been generated. I tested it with this script and got the same output as from `-wavwrite`:
```lua
local function log(s, name)
logfile = io.open(name, "ab") -- binary mode is required, otherwise junk gets appended along the way
logfile:write(s)
logfile:close()
end
emu.register_sound_update(function()
local samples = manager:machine():sound():samples()
log(samples, "check.wav")
end)
```
=> Lua callback after sound update has generated new samples

makefile
Without this tweak it would only create the file if it doesn't exist, and wouldn't update an existing one.
=> Allow updating version.cpp when IGNORE_GIT=1 is passed

hash/fmtowns_cd.xml
The 4th Unit 6 - Merry-Go-Round
Air Warrior V1.1
Dragon Shock
Final Blow
Ms. Detective File #1 - Iwami Ginzan Satsujin Jiken
Rance III - Leazas Kanraku
Sherlock Holmes - Consulting Detective
Turbo Out Run
The Visitor
Shanghai
- Added new NOT working dumps from the redump.org database (most of these are missing floppy disks):
Air Warrior V1.2
Fujitsu Habitat V2.1L10
Hyper Media NHK Zoku Kiso Eigo: Dai-3-kan
Nobunaga no Yabou: Sengoku Gun'yuuden
Taito Chase H.Q. (Demo)
- Added a parent-clone relationship between the Windows 3.1 revisions
- Updated the missing list with some recently confirmed software
=> fmtowns_cd.xml: additions, better dumps, updated missing list

scripts/target/mame/arcade.lua, src/mame/drivers/nmk16.cpp, src/mame/drivers/powerins.cpp, src/mame/includes/nmk16.h, src/mame/includes/powerins.h, src/mame/video/nmk16.cpp, src/mame/video/nmk16spr.cpp, src/mame/video/nmk16spr.h, src/mame/video/powerins.cpp
Original source by nmk16.cpp, with Fix flipped case, Allow pdrawgfx drawing
nmk16.cpp, powerins.cpp : Convert sprite draw routine into nmk16spr.cpp
nmk16.cpp : Fix manybloc flipped screen, Remove unused
powerins.cpp : Verify clock related to on-board XTALs, Add screen raw params
=> nmk16spr.cpp : Device-fied NMK 16 bit sprite hardware

src/emu/machine.cpp, src/emu/video.cpp
MAME was setting up AVI before devices have properly launched, so default 60fps was used, which resulted in skipped frames in the video if machine's framerate is above 60 (btoads), and presumably duplicate frames for machines below 60fps (haven't tested).
Now every frame that is generated is also present in the video.
Test script (dump avi with framecount display):
```lua
local function getscreen()
for k,v in pairs(manager:machine().screens) do return v end
end
local screen = getscreen()
local function framecount()
str = "frame: " .. screen:frame_number()
print(str)
screen:draw_text(0, 0, str, 0xffffffff, 0xff000000)
end
emu.register_frame_done(framecount)
```
=> Fix AVI framerate

hash/apple2_flop_clcracked.xml, hash/apple2_flop_orig.xml
apple2_flop_clcracked: The Haunted Palace (cleanly cracked), The World's 
Greatest Baseball Game (Enhanced Version) (cleanly cracked) [4am, 
Firehawke]
apple2_flop_orig: Carriers at War, Europe Ablaze, Halls of Montezuma, 
Panzer Battles, Reach For The Stars (Version 1.0), Reach For The Stars 
(Version 2.0), Reach For The Stars (Version 3.0), Russia, Decisive 
Battles of the Civil War: Volume One, Battlefront, Oil Rig, American 
Government (Micro Learningware), Muppet Learning Keys: The Muppet 
Discovery Disk, Leisure Suit Larry in The Land of The Lounge Lizards, I, 
Damiano, Crime Stopper, Questprobe featuring Spider-Man, Beach Landing, 
Vaults of Zurich, Decisive Battles of the American Civil War: Volume 
Two, Decisive Battles of the American Civil …
=> Update Apple 2 softlists to October 2nd, 2019

src/mame/drivers/megasys1.cpp
=> src/mame/drivers/megasys1.cpp: fix compilation error

src/mame/drivers/hh_sm510.cpp
Have now confirmed that the gnw_mmouse rom exactly matches the rom of the Soviet clone.
=> hh_sm510: confirm gnw_mmouse rom (nw)

src/mame/drivers/gamate.cpp
According to reports in the cc65 project, it appears that the RAM contains
0xFFs at power up. See https://github.com/cc65/cc65/issues/941.
Adapt the driver to account for this.
Caveat: I don't have real hardware to double check.
=> gamate: fix power up RAM contents

src/mame/drivers/fmtowns.cpp, src/mame/includes/fmtowns.h
This PR tries to better approximate what actual FM Towns machines are like, in terms of devices/configurations. The details are in the commit text, but the most important changes are the removal of the integrated SCSI controller on the first-gen models and the Marty (they don't have one in real life), and RAM options that reflect the actual onboard/SIMM combinations for each model. It also includes a couple of bugfixes and sanity checks to prevent emulator crashes I've found along the way.
This is the first time I mess around with devices and machine configurations, so feel free to criticize or suggest improvements.
Sources used:
http://www.mahoroba.ne.jp/~kazstary_/usage/simmfaq.txt
http://labo.main.jp/newage/towns/fmt_model.html …
=> fmtowns: bring machine configurations a bit closer to real hardware

scripts/target/mame/mess.lua, src/devices/bus/isa/ega.cpp, src/devices/bus/isa/isa_cards.cpp, src/devices/bus/isa/mda.cpp, src/devices/bus/isa/mda.h, src/devices/cpu/m6800/m6801.cpp, src/devices/machine/i8251.cpp, src/devices/machine/pit8253.cpp, src/devices/video/mc6845.cpp, src/devices/video/mc6845.h, src/emu/xtal.cpp, src/mame/drivers/eispc.cpp, src/mame/drivers/pc.cpp, src/mame/machine/eispc_kb.cpp, src/mame/machine/eispc_kb.h, src/mame/mame.lst, src/mame/mess.flt
This replaces PR #5312 The EPC can now boot from floppy and a new LLE serial keyboard is functional. Credits for the dump of the keyboard 6801 MCU goes to the people at Dalby Datormuseum whom I collaborated with in a dumper project:  
https://sites.google.com/site/dalbydatormuseum/home
https://github.com/MattisLind/6801reader
=> Rebase and completion of split out of epc driver and addition of graphics card

src/osd/modules/render/bgfx/shaders/makefile
Replacing make with $(MAKE) has uncovered the fact that current shaders build set-up is not compatible with parrallel builds.
Also, -s needs to be removed for VERBOSE=1 to have the desired effect.
=> Make shaders fixes

scripts/src/3rdparty.lua
This should fix the msvc build failures @MooglyGuy reported on irc.
=> -x c++ should not be applied to targets like msvc

src/mame/drivers/fmtowns.cpp, src/mame/mame.lst
This change adds the ROM dumps from a first-generation FM Towns computer (a Model 2, but the Model 1 is essentially a different configuration of the same machine), replacing the old "fmtowns" parent set, which turned out to actually be an FM Towns II MX.
For now this is a software dump, made from DOS with the "rombeger" tool included with the Unz emulator. I hope to get physical dumps of at least the two socketed chips in the near future, when I have the necessary tools, but judging from the MX example, the software dumps should match the real ones.
I also looked into the "fmtownsa" set, and found the ROM version and build date inside the system ROM, so I renamed it and changed the descriptions a bit to be more accurate, and also added a list with every known model to the source comments.
=> fmtowns: add the Model 2 ROMs

src/mame/drivers/hh_sm510.cpp
This fixes a problem with the alarm clock segments for manhole (gold). Thanks to TheOldGamerGuy for finding and reporting the issue.
=> hh_sm510: fix gnw_manholeg alarm clock segment

src/devices/bus/ss50/mps2.cpp
At least some of these are required for operation with terminals. For example the SWTPC 8212 terminal uses DTR to CTS for hardware flow control, and that is needed even at 9600 baud.
=> SWTPC MP-S2: connect up the RS232 control lines

src/mame/drivers/nes_vt.cpp, src/mame/mame.lst
new machines NOT WORKING
-----
Ping Pong / Table Tennis / Super Ping Pong (PP1100, ABL TV Game) [David Haywood,  Morten Kirkegaard, Peter Wilhelmsen]
boots and runs, but no sound, seems to need an additional device at 410f emulating which may or may not be sound related, waits for a long time for it to finish sending streams of data there.  if you wait long enough controls do actually work as it appears the 'motion' control here just simulates a button press.  As pointed out, this seems to be an updated version of Gameinis' Ping Pong with improved gfx etc.
=> new machines NOT WORKING (plug & play)

scripts/genie.lua
Fixes cross-compiling for Windows from a Debian testing machine.
=> Fix build for nonstandard compiler versions like '8.3-win32'

src/devices/bus/rs232/ie15.cpp, src/devices/bus/rs232/ie15.h, src/devices/machine/ie15.cpp, src/devices/machine/ie15.h, src/mame/drivers/ie15.cpp
The RS232 port has been moved out of the ie15 device. It is only needed in stand alone operation, and not when connected to the rs232 bus, it was odd leaving it in there, odd to still have an rs232 port slot option when running stand alone.
The IE15 UART implementation has been removed from the rs232 bus code and back into the ie15 device code. This leaves the rs232 bus code dealing with only serial data, and not the parallel data, and that should make it easier in future to have a common interface to RS232 terminals.
This is to illustrate some points raised in PR https://github.com/mamedev/mame/pull/5729 the SWTPC 8212 terminal proposal. This IE15 terminal proposal uses the same interface function names, and interfaces to the ie15 device using only serial data as is done for the …
=> IE15 terminal: rework the RS232 interfaces

.appveyor.yml, .travis.yml, 3rdparty/genie/src/actions/vstudio/vstudio_vcxproj.lua, scripts/src/tools.lua
As the only remaining build failures only affect debug build of tools, tweak the configuration so that the build can actually complete:
* disable tools build
* switch to release build while disabling optimization
* no longer allow msvc build to fail
=> Continuous integration improvements

src/devices/bus/rs232/rs232.cpp, src/devices/bus/rs232/rs232.h
Calling the line handlers, such as m_cts_handler() from the device_start() function is problematic as some of these handlers may wish to read ioports and that is not safe at this stage, so move these to a new device_reset() function.
When adding a write line function for a serial line, to route the line based on config options, it fails to initialize claiming that reading the ioport is not safe. It appears to have been due to the calls from the res232 device_start() function, and moving them to a device_reset() function worked around that.
=> RS232: move some initialization to a device_reset() function

3rdparty/sol2/sol/traits.hpp, src/frontend/mame/luaengine.cpp
Previous semantics were encouraged by sol2, and ThePhD admitted it was a bad idea for usertypes with lots of members. sol3 allows to assign members outside a constructor for regular usertypes, but mame can't move to sol3 because it requires C++17. Turns out sol2 also has a way to add members separately, and that is what I used. This helps immensely.
This approach required a fix to warning C5046 copied from here https://github.com/ThePhD/sol2/commit/57990845726e17fba11a39cfcb1fc0127a7ea638
Tested current mame plugins, everything seems to work.
Due to come black magic, if I use `simple_usertype::set()` with "manager" as well, "machine" member dies (others are fine!), so I had to leave it intact.
github isn't too good at displaying inline changes :/
=> luaengine: reduce memory usage during compilation

src/devices/bus/rs232/null_modem.cpp, src/devices/bus/rs232/null_modem.h
Some terminals use the DTR output for hardware flow control, so add that as another option.
E.g. This allows the SWTPC 8212 terminal, which has only DTR hardware flow control, to work with the null modem bit banger. It might also be a useful option for terminals that can optionally use DTR flow control such as the QVT102 and others.
=> rs232 null_modem: add DTR flow control

scripts/src/3rdparty.lua
Building asmjs fails after the BGFX update.
This PR isn't completely fixing the asmjs issue yet so consider it a work in progress. What has been done so far is a fix that suppresses a warning in BIMG which allows the MAME build to complete but there still linking related issues which needs to be resolved.
The linking issues are looking like this:
warning: undefined symbol: _ZN4bgfx2gl9GlContext11makeCurrentEPNS0_11SwapChainGLE
warning: undefined symbol: _ZN4bgfx2gl9GlContext15createSwapChainEPv
warning: undefined symbol: _ZN4bgfx2gl9GlContext16destroySwapChainEPNS0_11SwapChainGLE
warning: undefined symbol: _ZN4bgfx2gl9GlContext4swapEPNS0_11SwapChainGLE
warning: undefined symbol: _ZN4bgfx2gl9GlContext6createEjj
warning: undefined symbol: _ZN4bgfx2gl9GlContext6resizeEjjj
warning: undefined …
=> Fix asmjs build

src/mame/drivers/megaplay.cpp
Streets of Rage was previously listed at http://www.system16.com/hardware.php?id=707 but was removed between April 2016 and June 2017 judging by The Internet Archive's Wayback Machine:
https://web.archive.org/web/20160421233731/http://www.system16.com/hardware.php?id=707
https://web.archive.org/web/20170612023248/http://system16.com/hardware.php?id=707
The site now suggests, more sensibly, that the original Streets of Rage was only on the Mega-Tech system, not Megaplay.
=> Revise comment

scripts/src/machine.lua
The recent move of the IDE devices to the ata bus broke the build linking for the swtpc09. This PR fixed that here. If this is not the appropriate fix then could someone please have a look at what is going wrong.
=> IDE devices are now on bus/ata, build fix.

src/mame/drivers/tv990.cpp
The addresses of the rows in the vram do not increase monotonically
with the screen scan lines and the cursor address appears to follow
these addresses so the cursor row can not be computed from the
address. Rather compute the cursor column from the difference of the
cursor address offset and the address off of the start of the row, and
implicitly match the rows when comparing the columns. This might not be
perfect, but it is a big improvement and no issues have been spotted.
=> tv990: cursor fix

hash/fmtowns_cd.xml
Indiana Jones and the Last Crusade
Towns System Software v2.1 L51
CG Syndicate Vol. 1 - Lisa Northpoint
CubicSketch V1.1 L10
New Horizon CD Learning System II - English Course 1
Space Museum
TownsSOUND V1.1 L20
Z's Triphony DigitalCraft Towns
- Added new NOT working dumps:
Debian GNU/Linux 1.3.1 with Debian-JP Packages [akira_2020 / Tokugawa Corporate Forums]
Debian GNU/Linux 2.0r2 with Hamm-JP [akira_2020 / Tokugawa Corporate Forums]
TownsFullcolor V2.1 L10 [redump.org]
Video Koubou V1.4 L10 [redump.org]
=> fmtowns_cd.xml: additions, better dumps

hash/amigaocs_flop.xml, hash/c64_cass.xml, hash/ibm5170_cdrom.xml
This has two commits: one simply tidies up the name of Ocean's label The Hit Squad; the other one tentatively adds in some more tape dumps.
These dumps are [verified good](https://archive.org/download/c64tapes/the_list.htm) by the Tapclean software.  Where there are duplicates between The Ultimate Tape Archive and the C64 Tape Archive, the payload's "magic CRC32" matches, but the overall files' CRC32s and SHA1s don't, which I believe is to be expected, given the nature of the medium.  (At the end of the day, this isn't a 1:1 mapping of binary data like in a ROM chip; it's counting clock cycles between a pulse wave flipping on a Compact Cassette tape, stylised to compensate for wow and flutter, wrapped up in a custom format with its own headers.)  So I'm ignoring duplicates, even though …
=> Start work on C64 tapes

3rdparty/bgfx/src/renderer_vk.cpp
Currently waitvsync is broken in the bgfx vulkan backend.
The option is just ignored and a mode waiting for vsync is selected.
This also breaks throttle. -nothrottle doesn't work.
These changes fix this. If available a non-syncing mode is used if
-nowaitvsync is used.
=> Fix waitvsync for bgfx vulkan backend. [Couriersud]

src/osd/modules/render/bgfx/chain.cpp
This PR resolves an issue that happens when changing BGFX screen effects too many times. In my environment, MAME either crashes (Vulcan) or gives a black screen (OpenGL) after:
* Starting MAME
* Bringing up the in-game menu
* Selecting Slider Controls and hover on "Window 0, Screen 0 Effect"
* Traverse all effects back and forth a number of times by holding right or left key
The following commands was used to start the system:
Vulkan: `./mame64 -window -video bgfx -bgfx_backend vulkan -bgfx_screen_chains none [game]`
OpenGL: `./mame64 -window -video bgfx -bgfx_backend opengl -bgfx_screen_chains none [game]`
The games outrun and ridgerac are among the games tested and where the proposed fix resolves the issue
=> bgfx: fix issue with changing screen effects

src/devices/video/hp1ll3.cpp, src/mame/drivers/hp_ipc.cpp
Hi,
this commit fixes a bug in 1LL3 GPU emulation that caused cursor&sprite to disappear at top/left hand side of screen (i.e. when one of the coordinates is negative).
I also removed the "imperfect graphic" flag for HP IPC because, from my point of view, video emulation is as close as possible to the real hw.
Thanks.
--F.Ulivi
=> hp_ipc: fixed a bug in 1LL3 GPU

src/devices/cpu/m6502/deco16.cpp, src/devices/cpu/m6502/m4510.cpp, src/devices/cpu/m6502/m4510.h, src/devices/cpu/m6502/m6502.cpp, src/devices/cpu/m6502/m6502.h, src/devices/cpu/m6502/m6504.cpp, src/devices/cpu/m6502/m6504.h, src/devices/cpu/m6502/m6507.cpp, src/devices/cpu/m6502/m6507.h, src/devices/cpu/m6502/m6509.cpp, src/devices/cpu/m6502/m6509.h, src/devices/cpu/m6502/m6510.cpp, src/devices/cpu/m6502/m6510.h, src/devices/cpu/m6502/m65ce02.cpp, src/devices/cpu/m6502/xavix.cpp, src/devices/cpu/m6502/xavix.h, src/mame/drivers/a2600.cpp, src/mame/drivers/c128.cpp, src/mame/drivers/c64.cpp, src/mame/drivers/cbm2.cpp, src/mame/drivers/pet.cpp, src/mame/drivers/plus4.cpp, src/mame/drivers/tvboy.cpp, src/mame/drivers/vic10.cpp, src/mame/drivers/vic20.cpp, src/mame/drivers/xavix.cpp, src/mame/machine/deco222.h, src/mame/machine/decocpu6.h, src/mame/machine/decocpu7.h, src/mame/machine/m6502_vtscr.h
Now that `direct_read_data` has been replaced with `memory_access_cache`, which is better equipped to deal with dynamic banking, there should be all the more reason to put an end to this pernicious antipattern.
=> m6502: Eliminate the disable_cache hack (nw)

src/lib/util/aviio.cpp
This fixes a case where:
* m_soundbuf_samples == processedsamples
* processedsamples > 0
* processedsamples * stream->channels() == m_soundbuf.size()
In this scenario, the std::memmove() would do nothing (moving zero bytes), but the operator[] on the second parameter to std::memmove() overflows the array.  This can be benign in optimized builds (because the third parameter to std::memmove() is 0), but on debugging builds this can cause an assert.
=> Fix invalid std::vector<> lookup in aviio.cpp

hash/gamegear.xml, hash/sms.xml
segacd.xml related prototypes will come later, once I write an automation tool.
gamegear.xml:
WORKING:
Sonic the Hedgehog Chaos (Euro, Prototype 19930517) [Hidden Palace]
sms.xml:
NOT_WORKING:
Sonic the Hedgehog Chaos (Euro, "Ver 0.20", Prototype 19930630) [Hidden Palace]
WORKING:
Sonic the Hedgehog Chaos (Euro, Prototype 19930713) [Hidden Palace]
These prototypes are believed to have been solely burned for Sega Europe/UK, and thus are all labeled "Euro".
=> prototypes from third session of Sonic Month 2019

hash/gameking.xml
new SOFTWARE LIST entry
-----
gameking.xml : mc_4v19 - 4 in 1 - Warrior + Cleverhawk + Valiant + MetalDeform ('APR 23 05', 512KB cartridge) [Team Europe]
the previous mc_4v19 has been made a clone mc_4v19a and description changed to "4 in 1 - Warrior + Cleverhawk + Valiant + MetalDeform ('JUN 16 05', 1MB cartridge)"
the new dump is playable, but from a different revision of the cartridge with only 512KB ROM instead of 1MB meaning the dump of this one is complete.  Presumably the 1MB versions exist either as bugfixes, or as a crude copy protecton against people with 512KB flash carts.
=> new SOFTWARE LIST entry [Team Europe] (GameKing)

scripts/target/mame/mess.lua, src/mame/drivers/rcm32p.cpp, src/mame/drivers/rmt32.cpp, src/mame/mame.lst, src/mame/mess.flt
The CM-32P is a 6 channel, 31 voice PCM ROMpler.
The machine works well enough to pass some basic checks and boot the Test Mode.
There is no emulation of the sound chip and DSP yet.
=> add Roland CM-32P driver

src/mame/drivers/cps1.cpp, src/mame/drivers/fcrash.cpp, src/mame/includes/cps1.h, src/mame/mame.lst, src/mame/video/cps1.cpp
added new Street Fighter II Alpha Magic-F bootleg set (sf2amf3), working
added new Saturday Night Slam Masters bootleg set (slampic2), working, no sound (protected PIC)
existing slampic set: fixed most graphics issues, a few very minor issues remain, so will leave MIG flag for now 
existing slampic set: fixed player 4 input
existing sf2amf2 set: add some dipsw settings
=> Cps1 bootleg, new sets + fixes

hash/apple2_flop_misc.xml, hash/apple2_flop_orig.xml
This also includes metadata for the Anti-M releases, which I consider important to save since we have no way to know what will happen if GitHub or 4am should disappear at some point.
=> Update Apple softlists to 11/9/2019

hash/apple2_flop_orig.xml
Missed that during my fast eyeball of the data. Think I have an idea on how to better avoid this for the future, though.
=> Fix publisher data for Pharaoh's Revenge (nw)

src/mame/drivers/pc2000.cpp, src/mame/mame.lst
PreComputer 2000 (Spain) [ClawGrip]
(nw) Please note that PreComputer 2000 uses a SED1278F-0B instead of an HD44780. The SED1278F-0B is pin-compatible with the Hitachi, but the charset is different (and hence the CHROM, that can also be recreated from the datasheet).
=> New clones marked as NOT_WORKING

makefile
Quick workaround to have cross compilation back after genie update.  Move the MPARAM logic up to execute before PTR64 tests.
Not the best fix, but I'm not willing to rewrite a good part of mame makefile to have a better cross compile setup (I think we should differentiate host arch from target arch).
See details in https://github.com/mamedev/mame/pull/5631#issuecomment-552403142.
Thanks!
=> workaround to fix cross compilation to x86 from a x64 host

src/devices/video/ppu2c0x_vt.cpp, src/devices/video/ppu2c0x_vt.h, src/mame/drivers/elan_eu3a14.cpp, src/mame/drivers/nes_vt.cpp, src/mame/machine/elan_eu3a05commonsys.cpp, src/mame/machine/elan_eu3a05commonsys.h
----
Pinball (P8002, ABL TV Game) [David Haywood,  Morten Kirkegaard, Peter Wilhelmsen]
- divided up large nes_vt.cpp class, and did some general tidy up, commented some known addresses etc. to stop code rot.
- temporarily disabled timer on elan when running rad_bb3 until timer enable can be identified, made a few notes.
=> new WORKING machines (ABL Pinball) + temp disable timer IRQ in rad_bb3 + significant nes_vt cleanups / state chop

src/emu/emuopts.cpp, src/emu/emuopts.h, src/emu/video.cpp, src/emu/video.h, src/osd/mac/osdmac.h, src/osd/mac/video.cpp, src/osd/mac/window.cpp, src/osd/osdepend.h, src/osd/sdl/osdsdl.h, src/osd/sdl/video.cpp, src/osd/sdl/window.cpp, src/osd/uwp/video.cpp, src/osd/windows/video.cpp, src/osd/windows/winmain.h
**Remove up to one frame of input latency. Makes MAME virtually lagless on VRR monitors.**
MAME has currently two sources of input latency:
1.- Main loop arrangement: inputs are not polled at the optimal moment.
2.- Frame buffering associated to v-sync.
Fixing (1) is very straight-forward and is the purpose of this patch.
Fixing (2) is a complex task, that requires direct raster polling (GroovyMAME) or backend specific features (waitable object swapchain).
Modern VRR screens don't require v-sync, so fixing (1) is all we need to get latency as low as it gets.
The existing design polls input too early, before throttling:
- Emulate frame 1
- Render + poll input
- Throttle
- Emulate frame 2
- ...
When it's time is to emulate frame 2, input information is nearly one frame too old. In order to …
=> Remove up to one frame of input latency. 

src/devices/machine/ins8250.cpp, src/devices/machine/ins8250.h, src/mame/drivers/eispc.cpp
Sadly there were lots if regression side effects of my simple attempt to add this feature that I don't have time to sort out at the moment, so I revert it.
=> ins8250: reverted BAUDOUT pin support and documented findings in eispc.cpp

src/devices/machine/mb8421.cpp, src/devices/machine/mb8421.h, src/mame/drivers/esqmr.cpp, src/mame/drivers/firebeat.cpp, src/mame/drivers/twinkle.cpp
twinkle.cpp, firebeat.cpp : Device-fied CY7C131 Dual port SRAM, Add notes
esqmr.cpp : Add IDT7130 Dual port SRAM placeholder, Add notes
=> mb8421.cpp : Support variable size and data width, Use template for base device, Add notes

src/mame/drivers/hh_sm510.cpp
This PR was done to correct the tone length of two tones in the gnw_dkcirc startup melody. The issue has been here: https://youtu.be/zxhNV1lM37E
=> hh_sm510: gnw_dkcirc start melody fix (nw)

src/mame/video/terracre.cpp
- [07494](https://mametesters.org/view.php?id=7494): horekid, horekidb, boobhack: Coffee break doesn't show
=> teracre.cpp: Add hide text layer support (used in horekid)

hash/spectrum_mgt_flop.xml, src/devices/bus/spectrum/mgt.cpp
Added rare v1.0 +D rom, pal, system disk and few notes.
(thanks to Jose Manuel of trastero.speccy.org)
=> ZX Spectrum +D disk interface: added v1.0 rom

src/mame/drivers/skyfox.cpp, src/mame/includes/skyfox.h, src/mame/video/skyfox.cpp
The previous background implementation was completely wrong.
I found stars position stored in memory.
I used this to rewrite the background drawing code.
Reference PCB video:
- https://www.youtube.com/watch?v=oyE1CfcVrDc
- https://www.youtube.com/watch?v=5QhTNrNH-CU
- https://www.nicovideo.jp/watch/sm13578374
- https://www.nicovideo.jp/watch/sm13692186
=> skyfox.cpp : Improve background based on PCB

src/mame/video/speedatk.cpp
By this bonus rate are displayed correctly.
=> speedatk.cpp : Fixed tilemap wrong bit assignment

scripts/src/main.lua
Fix that resolves a problem that some bgfx effects displays when selected since required resources aren't available.
The errors looks like this:
Unable to load PNG 'artwork' from path 'bgfx/chains/hq4x.png'
Unable to load chain bgfx/chains//hqx/hq4x.json, falling back to no post processing
The affected effects are hq2x, hq3x hq4x, crt-geom and crt-geom-deluxe.
Applying this change makes these effects load without explicit errors but the overall BGFX issue reported in #5833 still remains for almost all effects.
=> Add bgfx artwork path for Emscripten build (nw)

src/mame/drivers/geniusjr.cpp
(nw) I've added it only on the machines I'm sure it's present, but it's probably on every machine on this driver.
=> geniusjr.cpp: Add placeholders for TI TSP50C10 speech ROM (nw)

src/mame/includes/galivan.h, src/mame/machine/nb1414m4.cpp, src/mame/machine/nb1414m4.h, src/mame/video/galivan.cpp
ninjemak and clones
- "INSERT COIN" is displayed on the continue screen
- Dusts appear in the lower left
- Appear dusts with "ONE PLAYER ONLY" and "ONE OR TWO PLAYERS" (ninjemak and youma2 only)
- Credits number does not display correctly when more 10 credits
- 1P and 2P scores are not displayed in attract demo
- Score 0 displayed as "00" ("0" is correct)
kozure
- "GAME OVER" is blinking
- “1-UP” stops blinking when game over
- "INSERT COIN" is displayed when game over
- 1P and 2P scores are not displayed in attract demo
- Score 0 displayed as "00" ("0" is correct)
terraf and clones
- "INSERT COIN" is displayed on the continue screen
galivan.cpp
- TILE_GET_INFO_MEMBER(ninjemak_get_tx_tile_info) : Fixed dusts in lower left (This is for hide custom chip communication).
galivan.h
- Fixed …
=> nb1414m4.cpp, galivan.cpp : Fix displayed different from PCB

hash/c64_flop_clcracked.xml, hash/c64_flop_misc.xml, hash/c64_flop_orig.xml, src/mame/drivers/c64.cpp
This PR serves to make a case to split the C64 disk softlist the same way we currently have the Apple II softlists: into clean cracks, originals, and misc (homebrew and defaced cracks).
My rationale for this change is that if we continue to dig into the C64 library, we most certainly will run into all three types for the same software. Being able to clearly denote which is which and use the same .zip filenames where appropriate will serve to make the documentation easier to read for developers and users both.
While I have committed a sin by having two empty softlists for the moment, there has been some interest from a MW poster to work on these lists and if I can grease the wheels a bit by doing the initial prepwork for them, I'm absolutely in favor of doing just that.
=> Split C64 disk softlist similarly to Apple II.

src/mame/drivers/model2.cpp
The current Model 2 driver does not have a DIP switch on the mainboard of most games. In fact, only Zero Gunner has it. All Model 2A, B and C boards do have DIP switches, however, and we have found code in Virtua Fighter 2, Sonic the Fighters and Fighting Vipers that use the DIP switches to enable debug features. Please see this article for more details on that: http://sudden-desu.net/entry/debug-tools-in-virtua-fighter-2-fighting-vipers-and-sonic-the-fighters-part-2
=> Added DIP switches to all Model 2 board per research

src/emu/device.h, src/emu/save.h
This is to see whether the CI server’s Visual Studio 2019 MSVC can compile the code with this workaround applied.  There’s no point merging it if it doesn’t go green (see issue #6044).
=> Possible workaround for MSVC issue in #6044

src/devices/bus/hp_dio/hp98265a.cpp
This pull request fixes two issues:
1. A confusingly named default cdrom device.
2. Configuring select codes other than the default 14.
=> HP98265A SCSI interface fixes

src/mame/machine/nb1414m4.cpp, src/mame/machine/nb1414m4.h
This request was separated from #5996.
Fixed issue :
ninjemak and clones
- The continue screen is corrupt (https://mametesters.org/view.php?id=4344)
=> nb1414m4.cpp : Fixed corrupted ninjemak continue screen

src/mame/drivers/dreamwld.cpp
also since this, unlike the earlier Semicom games, was the bare minimum code (no game title, author, or date in the MCU) I've moved the fake protdata regions into MCU code files using the code from dreamwld, and marked them as BAD DUMP, meaning we always emulate the MCU here.
=> plausible hookup for dreamwld MCU

src/mame/drivers/galaxian.cpp
(nw) From "Electrogame" to "Electrogame S.A.", like on the other Electrogame bootlegs. Also fixed some spacing and ROM types.
=> galaxian.cpp: Fix company name on "mandingaeg" (nw)

src/mame/drivers/atetris.cpp
(nw) This is a raw dump from a visual decap, but the ROM layout and the note format are not understood, so it cannot be properly hooked up. Any help on this will be appreciated. Full info: http://www.seanriddle.com/um348x/
=> atetris.cpp: UM3482 raw dump for "atetb3482" [Sean Riddle]

src/devices/sound/c6280.cpp, src/devices/sound/c6280.h
Use shared index between wavefrom writing and sound playback
Fix spacings/Namings, Use correct / shorter type values, Add notes, Reduce unnecessary lines
reference : https://archive.org/stream/PCEDev/HuC6280%20-%20CMOS%20Programmable%20Sound%20Generator%20Manual
=> c6280.cpp : Fix noise, Volume calculation, Interface behavior related to manual, Modernize save states

src/osd/modules/render/drawd3d.cpp
This is to make -attach_window work with non-root windows
=> Changed Direct3D renderer to call GetAncestor() in device_create() to get the root window

src/devices/bus/intv/voice.cpp
Voice reads and writes were clipped to 8 bits when they needed to be 16 bit.  This fixes Mame Testers issue #7336.
=> Fix intvoice not working since 207

src/mame/drivers/tk2000.cpp, src/mame/mame.lst
MPF-II is one of the earliest Apple II clone but not totally compatible
with.
It does not have a text mode, The address of the second graphic buffer
is different as well as the address of the keyboard input.
It have only one extension slot whit somme little pinning differences,
no joystick interface, a printer and a keyboard connector.
tk2000 drivers seems to be far more close to MPF-II, with the same
memory mapping, ram/rom banking in upper 16K, compatible keyboard
interface, same apple2 like video interface.
This drivers partially tested and seems fine with MPF-II rom.
Tested : Video, keyboard, sound.
=> Add Multitech MPF-II as clone of tk2000

src/mame/drivers/gaelco2.cpp
Adds config.set_perfect_quantum("gaelco_ds5002fp:mcu") (missing? removed?) to drivers using the ds5002fp to correct timing issues.
=> Fixes timing issues with ds5002fp

src/devices/sound/2612intf.cpp, src/devices/sound/2612intf.h, src/mame/drivers/fmtowns.cpp
=> Revert "sound/2612intf.cpp : Add YMF276 device, Clamp output related to internal 9-bit DAC, Add notes"

hash/gameking.xml
- mc_4v01,mc_4v04,mc_4v07,mc_4v09,mc_4v14,mc_4v15,mc_4v16,mc_4v17,mc_4v18,mc_4v19a  all redumped
- no more bad dumps remain
new SOFTWARE LIST clones
gameking.xml:
new: mc_4v05a - 4 in 1 - SeaGuard + Whirlybird + Spectask + Captain (set 2)
new: mc_4v06a - 4 in 1 - Three Battles + Light Sword + Risker + Metal Deform (1MB cartridge)
new: mc_4v10a - 4 in 1 Vol. 10 - Soldier + Seatercel + General + Seafight (1MB cartridge)
=> GameKing redumps [TeamEurope, SSJ]

src/mame/drivers/system1.cpp, src/mame/includes/system1.h, src/mame/video/system1.cpp
system1.cpp : Fix color, Use indirect entries for palette lookup, Reduce runtime tag lookup, Fix namings, Fix palette RAM handling, Fix bitmap clear behavior, Reduce unnecessary lines, Use correct / shorter type values
=> Fix Sega System 1 Color handling, Minor cleanups

src/mame/video/stfight_dev.cpp
The following bugs are fixed.
- MAME Testers [06897](https://mametesters.org/view.php?id=6897): empcity: Red Screen During Transitions
=> sfight.cpp : Fixed filling the screen red when text or BG layers are hidden

src/mame/drivers/ddragon.cpp, src/mame/drivers/gunsmoke.cpp
I have used Double Dragon 1 priority PROM for DD2 on FPGA and it displays correctly through the whole game. I think it should be included in the ROM set.
I have also verified the ADPCM frequency assumptions using a bootleg PCB.
=> Remarks based on PCB exploration and FPGA conversion

src/devices/sound/2612intf.cpp, src/devices/sound/2612intf.h, src/devices/sound/fm.h, src/devices/sound/fm2612.cpp, src/mame/drivers/fmtowns.cpp, src/mame/drivers/megadriv.cpp, src/mame/includes/megadriv.h, src/mame/machine/megadriv.cpp, src/mame/mame.lst
2612intf.cpp : Fix output bits, Device-fied YMF276, Add notes
fm2612.cpp : Add output bit variation, Fix DAC calculation
fmtowns.cpp : Add YMF276 placeholder for later model use this
megadriv.cpp : Add config for when YM3438 is integreated in ASIC, Add handheld variations, Fix PAL sound clock
=> YM2612 output updates, Add some Mega drive variations

hash/c64_cass.xml
Side A is from c64tapes.org as I couldn't get a good dump myself. 
http://web.archive.org/web/20170228231957/http://c64tapes.org/title.php?id=1821
Side B is my own dump.
=> c64_cass.xml - Add Hole In One

src/mame/drivers/cubo.cpp, src/mame/mame.lst
Laser Quiz Greece [English Amiga Board]
Odeon Twister (v1.4) [English Amiga Board]
Eldorado (4.2) [English Amiga Board]
(nw) I did not hook up the inputs. I marked the ISOs as BAD_DUMP because we can not verify how the CDs were dumped. I also renamed "lsrquiz2" to "lsrquiz2i".
=> New machines marked as NOT_WORKING

hash/ibm5150.xml
UCSD p-System was one of the three original OS for the IBM PC. This software list addition is based on two sources:
- https://www.bitsavers.org/bits/IBM/PC/p-system/p-system_rel_1.zip (base system plus FORTRAN)
- http://www.z80.eu/downloads/IBMPC-UCSD.zip (alternate SYSTEM2 disk and PASCAL)
I've verified this works fine in MAME.
=> ibm5150.xml: add UCSD p-System

src/mame/drivers/expro02.cpp, src/mame/drivers/galpanic_ms.cpp, src/mame/drivers/kaneko16.cpp, src/mame/video/galpani2.cpp, src/mame/video/kaneko16.cpp, src/mame/video/kaneko_spr.cpp, src/mame/video/kaneko_spr.h
Fix priority in enabled 'keep sprite' function, Split 'Copy temporary bitmap into screen bitmap' function and Getting sprite function
kaneko16.cpp : Fix sprite delay, Add notes, Correct explbrkr OKI bankswitching (tied into m_ym2149[0] port B), Remove outdated note
=> kaneko_spr.cpp : Fix drawing behavior

hash/fmtowns_cd.xml
- Added the missing floppy disk dump for Fujitsu Habitat V2.1L10 [StuBlad]
After Burner (v1.01)
After Burner III
Last Survivor
- Added new working dumps:
Emit Vol. 3 - Watashi ni Sayonara o [redump.org]
Shooting Towns [rockleevk]
The New Zealand Story (HMA-213) [redump.org]
=> fmtowns_cd.xml: additions and replacements

src/lib/formats/ap2_dsk.cpp
The APPLE2_TRACK_COUNT macro was not being expanded here, at least on gcc8.
This resulted in the string "APPLE2_TRACK_COUNT" being within the specification
and that in turn broke option_resolution::lookup_in_specification leading to
an assertion fail with the debug checks enabled. So bake in the numeric
constant to at least get things working again.
Not a pretty fix - has anyone got a better idea?
=> apply2 floppy format: bake in the track count

src/devices/sound/huc6230.cpp, src/devices/sound/huc6230.h, src/devices/video/huc6272.cpp, src/devices/video/huc6272.h, src/mame/drivers/pcfx.cpp
But it's still noisy and imperfect; Add imperfect_features for this.
huc6230.cpp : Fix ADPCM frequency, Make ADPCM less louder, Fix naming related to patents, Fix stream sample rate related to PSG output rate, Add notes, Add patent for reference
huc6272.cpp : Fix ADPCM frequency, Add patent for reference
=> Fix PC-FX ADPCM frequency behavior

src/mame/drivers/superga2.cpp
This patch fixes input port bit masks for players one and two and marks the remaining two bits unused. I spent a couple of hours debugging the kuzmich ROM and could find no place where these two bits are explicitly checked.
=> superga2.cpp: fixed player two

src/mame/drivers/armedf.cpp, src/mame/includes/armedf.h, src/mame/video/armedf.cpp
Fix namings, Make text VRAM into shared_ptr, Reduce duplicates, Move install_handler into address map, Fix naming, Fix terraf_io without NB1414M4, Simplify handlers, Simplify gfxdecode, Use shorter/correct type values, Add notes
=> armedf.cpp : Use pdrawgfx for sprite drawing, Minor cleanups

hash/fmtowns_cd.xml
3x3 Eyes - Sanjiyan Henjou
Branmarker
Free Software Collection 4
Free Software Collection 5
Fushigi no Umi no Nadia - The Secret of Blue Water
Libido7
Life & Death
Loom
Microcosm (HMD-215)
Ms. Detective File #2 - Sugata-naki Irainin
Megaspectre
Nova - Miirareta Shitai
Super Real Mahjong PII & PIII
Super Real Mahjong PIV
Super Street Fighter II - The New Challengers
Youjuu Senki - A.D. 2048
Cyber Sculpt V1.0 (HMC-140A)
Mahjong Bishoujoden Ripple
Microcosm (HMD-215A)
- Added new NOT working dumps from the redump.org database:
Doki Doki Vacation - Kirameku Kisetsu no Naka de
Secre Volume I - Naoko Iijima
- Demoted nadia to …
=> fmtowns_cd.xml: additions, replacements and notes

src/devices/sound/ymf271.cpp
Correct this to PCBs and OSTs.
reference : https://www.youtube.com/watch?v=PQsefFtqAwA
=> ymf271.cpp : Correct envelope release time

src/lib/formats/flex_dsk.cpp, src/lib/formats/flex_dsk.h, src/lib/formats/os9_dsk.cpp, src/lib/formats/os9_dsk.h, src/lib/formats/wd177x_dsk.cpp, src/lib/formats/wd177x_dsk.h, src/tools/floptool.cpp
Add a get_track_format() method that can be overridden to supply format
variations for any track and head. The code is generalised to account for such
variations. The default method returns the passed format, so this change is
neutral for existing formats.
Simplify the FLEX DSK format code. There are now simply format variation
descriptions for the second track that have the sector ID continuing in
sequence from the first track, rather than specialized code.
Extend the FLEX format to support variations in the sectors ID of the first
two sectors. The FLEX 6800 boot sectors have IDs based at zero rather than
one. Extend the FLEX format to support variations for which the first track,
on both sides, is single density on an otherwise double density disk which was
historically a common format. …
=> wd177x_dsk: generalize to allow custom track format variations

src/mame/drivers/gimix.cpp
The FDC clock changes with the programmed connector selection.
The 5.25 versus 8 inch boot floppy jumper is an input and does
not need and input changed handler.
The FDC supports four floppy drives, up from two.
The IRQ line was not implement. Add an input merge device and
connect up more of the IRQs to this. The timer hack is no longer
necessary and has been removed - it was just missing an IRQ.
Add a DASM override for OS9 system calls, copied largely from the
COCO, enabled only when the OS9 ROMs are switched on.
Add a BIOS option for OS9 Level 1 version 1.2.
Renamed the version 1.1 ROMs for consistency.
The Gimix machine appears to be working well enough to promote it
from a 'skeleton' to working.
Found the OS9 L1 V1.2 ROMs and a boot disk at …
=> Gimix: improve IRQs, OS9 improvements, four floppies,

src/lib/formats/flex_dsk.cpp, src/lib/formats/flex_dsk.h
It is necessary to return a higher score on success, higher than
returned by the default method, in order for a general 'identify' to
succeed over competitive matches.
=> flex_dsk: include an identify() method.

src/mame/drivers/swtpc09.cpp, src/mame/includes/swtpc09.h, src/mame/machine/swtpc09.cpp, src/mame/mame.lst
The ROM for this one is available at http://www.evenson-consulting.com/swtpc/Downloads.htm in the 'Complete Setup current version' bundle and within that see the file `ROMImages/6809/OS9Rom.stx` which needs to be decoded into a flat EPROM binary. There are also OS9 boot disks there etc. The decoded ROM in a zip file for MAME is temporarily at https://68bit.org/swtpc09o.zip
The OS9 ROM has been set up as a system BIOS as these are specific to each version of OS9, the ROM contains part of OS9, so other variants are expected. This ROM boots straight into OS9. Here is just one example:
```mame64d swtpc09o -io1:dc5:fdc:0 qd -flop1 /tmp/OS9BTBK3.DSK```
=> swtpc09: OS9 support, misc fixes.

src/mame/machine/swtpc09.cpp
Fixes swtpc09i issue noted in https://github.com/mamedev/mame/pull/6282 thanks.
=> swtpc09: the OS9 DC5 variant needs a unique id.

src/mame/video/boogwing.cpp
This PR fixes blending behavior of museum stage windows.
Window frames are must be solid pixel, NOT blended.
=> boogwing.cpp : Fix museum stage windows

hash/fmtowns_cd.xml
4D Boxing
Taito Chase H.Q.
Marble Madness
Raiden Densetsu / Raiden Trad
Rance IV - Kyoudan no Isan
The New Zealand Story (HMA-213A)
Vain Dream
Vain Dream II
Yumimi Mix
- Added new NOT working dumps from the redump.org database:
Para Para Paradise
- Re-tested and promoted to working status:
The Case of the Cautious Condor
King's Quest V - Absence Makes the Heart Go Yonder
Mixed-Up Mother Goose
Panzer Division - Kikou Shidan
Secre Volume I - Naoko Iijima
Secre Volume 2 - Mai Oikawa
- Re-tested and promoted to partially working status:
Taito Chase H.Q. (Demo)
Kyuukyoku Tiger
=> fmtowns_cd.xml: one new dump, replacements and re-tests

src/devices/cpu/mcs51/mcs51.cpp, src/mame/drivers/midqslvr.cpp
U4 component on the Diego board was initially incorrect as "109B" instead of "1098" (A/D converter that obviously controls steering and throttle). Arctic Thunder's I/O cpu turned out to be a 87C552 MCU which uses the same architecture as the predicted 87C51/2; both Intel MCS-51 based. If anyone wants this decapped, I will (most likely) be happy to donate my substitute I/O board though I would hate to waste a fully working pcb.
Just to be sure: http://www.keil.com/dd/docs/datashts/philips/8xc5x2_ov.pdf
=> Finish midqslvr.cpp's documentation (nw)

hash/apple2_flop_clcracked.xml, hash/apple2_flop_orig.xml
Okay, so there's going to be questions about why there's so much addition and removal from the clcracked and orig softlists.
It basically boils down to the fact I forgot that the scripts on this ancient Linux laptop were much older versions that didn't have the "automatically reorder the entries in the correct release order" update. As such, they were in reverse order for each commit, and I want them to remain in release order.
This has been fixed and it won't be happening again.
=> Apple II update to Feb 23rd - additional note included

src/emu/save.cpp, src/emu/save.h, src/frontend/mame/luaengine.cpp
Dumping all save items in one go is a major pain since they are separated by device and their manipulation is based on name and index, which is unconvenient and slow if I want them all. RAM states use internally kept buffer, so transferring them via lua is also not convenient: it'd take twice the space and twice the time to save them internally and then to copy over to/from lua.
So I made luaengine return savestate buffer as a binary string, with the same contents the file based savestate has, just without compression (like in ram states). I also made it load the savestate from such a string: it's not void pointer, and all the usual checks are there, so it should be safe to manage savestates like that.
This is another step forward for https://github.com/mamedev/mame/issues/2398 (see …
=> luaengine: save state to/from binary string buffer

hash/apple2_flop_orig.xml
This includes:
Bringing all use of each machine type's name to be the same to make things much more text-searchable. (e.g. no more mixing and matching of Apple ][+ and II+)
Makes all comments fit within 80 columns.
Cleans up spelling errors that were copy-pasted from original source.
Makes all compatibility notices of a type the same, so that they're text-searchable.
Removes a few erroneously included comment lines from build sessions in the past.
=> One new softlist entry and a ton of cleanups

scripts/src/bus.lua, src/devices/bus/hp80_io/82939.cpp, src/devices/bus/hp80_io/82939.h, src/devices/bus/hp80_io/hp80_io.cpp, src/devices/machine/1mb5.cpp, src/devices/machine/1mb5.h, src/devices/machine/ins8250.cpp, src/mame/drivers/hp80.cpp
Hi,
I've just added the emulation of HP82939 serial I/O module for HP80 systems.
I needed to fix a small bug in INS8250 emulation because the module self-test was failing. Hopefully I didn't break anything in other systems with 8250.
ROM image for the module microcontroller will be emailed shortly to "code" address.
Thank you.
--F.Ulivi
=> hp80: HP82939 serial I/O module added

src/mame/drivers/gal3.cpp, src/mame/drivers/namcos21.cpp, src/mame/drivers/namcos21_c67.cpp, src/mame/drivers/namcos21_de.cpp, src/mame/video/namco_c355spr.cpp, src/mame/video/namco_c355spr.h
Fix overwritten shadowed pixel(ex : namcofl.cpp), Support bitmap_rgb32
namcos21.cpp, gal3.cpp : Fix palette entries related to RAM size
=> namco_c355spr.cpp : Convert sprite drawing behavior related to template bitmap

scripts/src/bus.lua, src/devices/bus/hp80_io/82900.cpp, src/devices/bus/hp80_io/82900.h, src/devices/bus/hp80_io/hp80_io.cpp, src/devices/bus/hp80_io/hp80_io.h
Hi,
this commit adds the hp82900 CP/M module. It was used to enable HP86/87 machines to run CP/M software. The relevant ROM image will be sent to code email shortly.
Thanks.
--F.Ulivi
=> HP82900 CP/M module

hash/fmtowns_cd.xml
4D Driving
Blandia
Daisenryaku III '90
Death Brade
Derby Stallion
Drakkhen
Freeware Collection 1
Hana yori Dango 2
The Incredible Machine
Operation Wolf
Shangrlia 2
Super Odyssey & Dennou Planetarium
Shadow of the Beast - Mashou no Okite
Zoku Dungeon Master - Chaos no Gyakushuu
Big Honour
FM Towns World
Gokko Vol. 02 - School Gal's
High C Compiler Multimedia Kit v1.7 L12
Kanade V1.1L10
Katakana no Ehon
Kanji no Ehon
Kyouiku & FM Towns Vol. 3
NHK Eigo de Asobo Vol. 1
NHK Eigo de Asobo Vol. 2
Pegasus (Rev A)
SimCity (1990-03-05)
- Added new NOT working dumps from the redump.org database:
Towns VNet V1.1 L20
- Renamed:
Blandia …
=> fmtowns_cd.xml: 12 additions, 14 replacements, renames

src/mame/drivers/taito_l.cpp
Brute forced the two PAL16L8's, created logic-equivalent GAL16V8's and tested on hardware.  Also compared logic equations to dumps from jammaarcade.net, and they are logic-equivalent.  Ended up using the images from jammaarcade.net, and the same driver format as the other GAL's in the driver.  Note: I added them to all production versions of the game, as the PCBs are all the same and PALs are labelled the same.  I did not add it the prototype version. I have no way of knowing if that hardware revision and/or PALs are the same.
=> taito_l: Add PLD Images to Kuri Kinton Drivers

hash/mz2200_cass.xml, src/mame/drivers/mz2000.cpp
Dumps by Gaming Alexandria.
I'm guessing the softlist can't be added to only the MZ-2200 since it's a clone of the MZ-2000?
=> Add softlist for mz2200

hash/ibm5150.xml
Made from Kryoflux dumps by Flyers80.
There seems to be some kind of copy protection on the disks but I'm not 100% sure.
=> ibm5150.xml: Add Power Drift

src/mame/drivers/midzeus.cpp
Zeus 2 pcbs use dedicated firewire/IEEE 1394 hardware to link other pcbs (verified on hardware).
Link layer controller: https://www.digchip.com/datasheets/download_datasheet.php?id=1001640&part-number=TSB12LV01A
Physical layer interface (PHY): https://datasheet.datasheetarchive.com/originals/library/Datasheets-IS15/DSA00292238.pdf
=> Confirm Zeus 2's cab linking is firewire/IEEE 1394

src/mame/drivers/esripsys.cpp
Added Star Wars flight yoke controller to Turbo Sub. This fixed the inverted input since MAME 0.192.
See http://www.turbosub.com/turbosubmain.html
"Most of the cabinets that have surfaced have been converted from Star Wars cabinets, this makes sense considering the game utilizes the same flight yoke".
See also MAMETesters bug #06913
=> Added Star Wars controller to Turbo Su

hash/specpls3_flop.xml
-Documented Rescate Atlántida being a dual Spectrum+Amstrad release.
-Documented Comando Tracer being a dual Spectrum+Amstrad release (though it's still not clear which version did the current dump come from).
-Changed Comando Tracer's year of release to 1988.
-Split the two Navy Moves Spanish editions correctly (standalone and dual Spectrum+Amstrad).
-Removed one Navy Moves duplicate which only had an altered header.
-Added new parent/clone relationship between Wanderer 3D UK and Spanish versions.
-Cosmetic changes:
--Moved the relevant comments into their respective entries/floppies.
--Reworded a few things.
=> specpls3_flop.xml: Dual release documentation, etc

scripts/src/sound.lua, scripts/target/mame/mess.lua, src/devices/cpu/mcs96/mcs96ops.lst, src/devices/sound/rolandpcm.cpp, src/devices/sound/rolandpcm.h, src/mame/drivers/roland_cm32p.cpp
Emulation of the sound chip is complete enough so that it sounds good.
There are a few bugs with samples that use ping-pong loops.
The CM-32P firmware currently freezes when playing the 32th note, because voice allocation doesn't work yet.
The I8096 fix is required to make the Orch.Hit patch load. The fix makes the CPU core behave as the specified by the manual.
=> add CM-32P PCM emulation

hash/fmtowns_cd.xml
- Added requirements for software items that need more hardware than what an unexpanded Model 1 would provide (386 CPU, 1 MB RAM, no HDD).
Alone in the Dark
Azure
Bible Master - Crash of the BlleotRutz
Bomberman - Panic Bomber
ElFish
if 2 - Invitations from Fantastic Stories
Might and Magic III - Isles of Terra
Mobile Suit Gundam - Hyper Classic Operation
Tatsujin Ou
Titan
Towns System Software v1.1 L10
Yami no Ketsuzoku Special - The Predestined Homicides
After Burner (v1.02)
After Burner (v1.02, alt)
Can Can Bunny Premiere
Debut Shimasu... - Nakagawa Yuuko
Free Software Collection Marty 1
Hyper Channel - Towns TV
TownsPAINT …
=> fmtowns_cd.xml: requirements, 12 replacements and 10 additions

scripts/src/tools.lua
The issue has been fixed as of Visual Studio 2019 16.5
I have tested it locally but merging should wait until appveyor is updated too, otherwise CI will break.
=> Roll back no longer needed /ZI workaround

hash/st_flop.xml
From Greaseweazle dump by mikerochip.
Speaking with Jeff of HxC it seems stx isn't the best of formats, so replace those with mfm dumps.
=> st_flop.xml: Add Fantasy World Dizzy

src/mame/drivers/apple2gs.cpp
This is making my F/E stalled although it should happily display the content of all apple2gs related software lists.
=> Fixed software list declaration for apple2gs with the actual content of the related software lists

hash/telestory_cart.xml, src/mame/drivers/nes_vt.cpp
This refactors some of nes_vt.cpp in ways which will make it easier to split the SoC emulation into it's own file.  For now this ends up with a lot of ugly / redundant looking stuff, but that will be cleaned up by the splitting.
Primary goal here is moving bits out of the current 'in driver' SoC code out of it when they are actually external to the SoC, and ensuring it can be split without the parts having to know too much about each other.
This also allows senwld to have RAM correctly mapped in what was previously 'ROM only' space.
no whatsnew needed at this point, will credit when work is complete, this is just a checkpoint, so (nw)
=> Plug and Play work

src/mame/drivers/fantland.cpp
Better description of components on "whellrun", identified 2x sound chips SN76489AN and measured clocks for all chips.
=> Better description

hash/ibm5170.xml
Did a small update to reflect the origin of the affected dumps. They are all winimage made. The whole gem* set is wininmage made, will update them later, to reflect their baddump status
=> updated to ibm5170 softlist

hash/c64_cass.xml
Hi!
So I'm [dumping](https://archive.org/details/c64tapes) a bunch of C64 tapes, and also [collating](http://c64tapes.com) some C64 tapes dumped by myself as well as others, as two separate projects.  I'm also working on a handy export feature that generates c64_cass.xml based on these.  There's a few things to note:
- Some of these dumps are only one side, if only one side dumped successfully.  I'll add to, or replace, those if and when I can get the other side to dump successfully.
- I'm sticking to the 8.3 filename convention for both the software name and ROM name.  I'm also trying to keep re-releases of titles separate, assuming you'll want _all_ known releases and re-releases of any given title.  So e.g. `bdash4h`, for Hi Tec Software's re-release of Boulder Dash 4, isn't going to …
=> Adding and tidying some C64 tapes

src/mame/drivers/backfire.cpp, src/mame/drivers/boogwing.cpp, src/mame/drivers/cbuster.cpp, src/mame/drivers/cninja.cpp, src/mame/drivers/darkseal.cpp, src/mame/drivers/dassault.cpp, src/mame/drivers/dblewing.cpp, src/mame/drivers/deco156.cpp, src/mame/drivers/deco32.cpp, src/mame/drivers/dietgo.cpp, src/mame/drivers/dreambal.cpp, src/mame/drivers/funkyjet.cpp, src/mame/drivers/mirage.cpp, src/mame/drivers/pktgaldx.cpp, src/mame/drivers/rohga.cpp, src/mame/drivers/simpl156.cpp, src/mame/drivers/sshangha.cpp, src/mame/drivers/supbtime.cpp, src/mame/drivers/vaportra.cpp, src/mame/includes/cninja.h, src/mame/includes/deco32.h, src/mame/includes/sshangha.h, src/mame/video/cninja.cpp, src/mame/video/deco16ic.cpp, src/mame/video/deco16ic.h, src/mame/video/deco32.cpp, src/mame/video/sshangha.cpp
deco16ic.cpp: Fix transparency/transmask handling in custom draw case
Use callback for tile info and 8bpp mixing, Fix sshangha regression, Reduce unnecessary values
cninja.cpp: Correct 8bpp tilemap drawing behavior in robocop2 (in 8bpp tilemap, Same data in both tilemap RAM for tilegen[1], only tile bank is different), Correct sound routes for PCBs without stereo sound output
darkseal.cpp, sshangha.cpp: Cleanup gfxdecode layout
sshangha.cpp: Correct palette entries, Both chip and PCB hasn't any stereo sound output, Correct sound output routes
mirage.cpp: Use pri_callback for sprite priority
=> deco16ic.cpp Drawing behavior updates

src/emu/diexec.cpp
This fixes problems where devices are input line changes are missed
because a device was reset. One case is at startup, where one device's
output is wire to another's input. During start the first device adds,
eg, a RESET assertion to the second. When that device starts, it resets
itself and clears the pending RESET assertion.
I've testing this a bit on the few games I have, and I haven't seen any issues.
=> Don't clear the input queue on reset.

hash/c64_cass.xml
- Make both the software name and ROM names conform to lowercase 8.3 filename structure
- Give credit to who dumped each software title
- Optimise the image with tapclean, which changes the file's hashes (but not the payload's magic CRC32, as the target data itself is unaltered).  This makes the tape image fully pass inspection.
Many more to follow over the next few months, if this gets approved.
=> Tidy up The Ultimate Tape Archive's dumps

src/mame/drivers/at.cpp, src/mame/drivers/compc.cpp, src/mame/drivers/europc.cpp, src/mame/drivers/ps2.cpp, src/mame/drivers/tandy1t.cpp
Added comments to several drivers about the XTA (8-bit IDE) harddisks used in those machines. The term XT-IDE is now firmly established for the open source hardware project, this is possibly confusing.
=> Euro XT: BIOS revision, several: XTA harddisk info

src/mame/drivers/rpunch.cpp, src/mame/includes/rpunch.h, src/mame/video/rpunch.cpp
Use pdrawgfx for sprite priority, Use bitmap_ind16 for drawing framebuffer behavior, Fix notes and variable names
Add notes, Use set_rom_bank for upd bankswitching, Reduce unnecessary includes, Fix spacing, Fix address map related to framebuffer exists, Use shorter/correct type values, Simplify handlers, Cleanup gfx layouts
=> rpunch.cpp: Update drawing behaviors, misc updates

src/mame/drivers/nmk16.cpp, src/mame/drivers/powerins.cpp, src/mame/includes/nmk16.h, src/mame/includes/powerins.h, src/mame/video/nmk16.cpp, src/mame/video/powerins.cpp
Add notes, Simplify handlers, Use screen raw params for bootlegs
nmk16.cpp: Use timer for sprite DMA behavior, Reduce duplicates, Fix sabotenb sprite delay, Add notes
=> powerins.cpp: Reduce duplicates related to nmk16.cpp, Move subclass into nmk16.h (Similar hardware design)

hash/fmtowns_flop.xml
- New dumps (all working, dumped by me):
Ai Shimai - Futari no Kajitsu
Doukyuusei 2 Special Disk
Super Ultra Mucchin Puripuri Cyborg Maririn DX
Music Pro-Towns (1990-05-23)
Shangrlia 2 Special Disk
S. A. 2
- Promoted Music Pro-Towns to working and added usage instructions.
- Replaced MS-DOS 6.20 L10 with the images from the Master CD, which should match the original disks. The previous images were the "installed" floppies that can be created from the original ones.
=> fmtowns_flop.xml: 6 new dumps, replaced DOS 6.2 images

src/mame/drivers/cps1bl_pic.cpp, src/mame/drivers/fcrash.cpp, src/mame/includes/fcrash.h
Improved new wofpic set, playable now, still some minor gfx issues (not using values from main ram this time!)
Redump bad wofpic,wofabl gfx rom
Load wofpic,wofabl gfx roms properly instead of rearranging in init
Make some of the bootlegs not use the brightness values as some don't have the h/w for it on the real pcbs (the 74ls07's and resistor arrays/dacs are unpopulated)
=> Improve wofpic and other misc bootleg stuff

hash/leapfrog_didj_cart.xml, scripts/target/mame/mess.lua, src/mame/drivers/magiceyes_pollux_vr3520f.cpp, src/mame/mame.lst, src/mame/mess.flt
----
leapfrog_didj_cart.xml: Nicktoon Android Invasion (US, 500-13290-B) [Team Europe]
there's a skeleton driver too, but it's really nothing but a holder for the Software List as the BIOS isn't yet dumped.
=> new NOT WORKING software list entries

hash/timex_cass.xml, src/mame/drivers/timex.cpp
Timex computer emulation is currently using the Spectrum softlist for cassettes, but many of those entries are actually incompatible unless the "Spectrum Emulator" cartridge (which seems to be missing from the timex_dock softlist) is being used.
So I've created their own compatible (depending on the model) softlist, with every actual Timex dump I could find in both World of Spectrum and Spectrum Computing.
Most of these should work with the Timex "equivalents" of the Spectrum 48K and their clones:
-TS2068
-TC2068				(not currently emulated)
-TC2048
-TC2048 (NTSC)		(not currently emulated)
-UK2086
I've noticed that many of the TZX dumps were fake ones made from TAP files (so the real pauses between blocks were all replaced with 1000ms) so I just added the TAPs in those cases, while those …
=> Created softlist for Timex cassettes (timex_cass)

docs/source/conf.py
While smartquotes are somewhat configurable, it's better if we don't use them at all. Makes sure there are no hidden pit traps for the users.
=> Fix smartquotes by disabling them

hash/hp86_rom.xml, src/mame/drivers/hp80.cpp, src/mame/mame.lst
Hi,
this PR introduces two variants of HP86B that support various non-English European languages. Drivers are named "hp86b_001" & "hp86b_004" (see head of hp80.cpp file for a description of these variants).
I also updated the software list to include two service plug-in ROMs.
I'm going to mail the relevant ROM images soon.
Thanks.
--F.Ulivi
=> Hp86: new variants with non-English keyboards

scripts/src/emu.lua, src/emu/machine.cpp, src/emu/recording.cpp, src/emu/recording.h, src/emu/video.cpp, src/emu/video.h, src/frontend/mame/luaengine.cpp, src/frontend/mame/ui/ui.cpp
This PR is a refactoring of the AVI/MNG code, to isolate the code specific to AVI vs MNG and consolidate what was previously seemed to be copy and paste code.  Specifically:
1. Code that was previously in src/emu/video.cpp pertaining to file recording is now in a new separate module (src/emu/recording.cpp)
2. Cut down on the duplicated logic pertaining to -snapview native handling
3. Toggling recording off will now turn off all recordings; previously if one had both an AVI and MNG recording, pressing Ctrl+Shift+F12 would turn off the AVI and leave the MNG running, and a subsequent Ctrl+Shift+F12 would do nothing
These changes could go further; I preserved the logic that concatenated screen indexes when creating movies when '-snapview native' is in effect.  This logic is not aware of file …
=> Refactoring of AVI/MNG recording code

hash/fmtowns_cd.xml
- Added known serial numbers for all entries.
- Re-classified some of my old dumps as being from Redump, since I submitted them anyway.
- Added floppy dump for Angel and promoted to working.
Ed Bogas' Music Machine
HomeStudio V1.2L10
Kid Pix Jr.
New Horizon CD Learning System II - English Course 1 (FM Towns Marty version)
Sargon V - World Class Chess
Ms. Detective File #1 - Iwami Ginzan Satsujin Jiken (FM Towns Marty version)
A Ressha de Ikou III
Appare CD Vol. 1 - Hiryuu no Maki
ElFish Lite
Muscle Bomber - The Body Explosion
Metal Eye 2
Nihon no Rekishi - Kodai-hen
The Secret of Monkey Island
- Reordered some entries
=> fmtowns_cd.xml: serials, 6 new dumps, 7 replacements

src/mame/drivers/seattle.cpp, src/mame/drivers/vegas.cpp
All unnecessary inputs are removed from all respective games without problems. I decided to remove "IMPERFECT_SOUND" from the NBA Showtime games because those games used a standard Vegas SIO board.
=> seattle.cpp and vegas.cpp: Clean House (nw)

src/devices/machine/tms9914.cpp, src/devices/machine/tms9914.h
Hi,
I've just added two missing FSMs in TMS9914 emulation (serial request & parallel poll). I've also fixed a typo reported by shattered (two bits swapped in a register).
Thanks.
--F.Ulivi
=> tms9914: added SR & PP FSMs, typo fixed

src/emu/xtal.cpp, src/mame/drivers/gaiden.cpp, src/mame/drivers/suprnova.cpp, src/mame/drivers/tecmo16.cpp, src/mame/includes/gaiden.h, src/mame/includes/suprnova.h, src/mame/includes/tecmo16.h, src/mame/video/gaiden.cpp, src/mame/video/suprnova.cpp, src/mame/video/tecmo16.cpp
gaiden.cpp, tecmo16.cpp, suprnova.cpp: Move delayed sprite drawing function into screen_vblank
suprnova.cpp: Use generic gfx layout, Fix CPU clock related to XTAL, Use device for screen
=> Move sprite delaying behavior into screen_vblank for some drivers

hash/sgi_mips.xml, src/mame/drivers/4dpi.cpp, src/mame/drivers/indy_indigo2.cpp
Add an initial software list for SGI MIPS-based systems and hook it up to the Indy and 4D drivers.
=> sgi_mips: add software list

src/mame/drivers/hp80.cpp
I've just fixed a bug in HP86 emulation that prevented correct key auto-repeat with non-English keyboard layouts.
Thanks.
--F.Ulivi
=> hp86: fixed a bug in key auto-repeat function

src/devices/bus/nscsi/cd.cpp
On `indy_4610` running IRIX 5.3, the `eject` command (or selecting the same operation in the UI, e.g. in the cdrom icon context menu) causes an immediate abort due to
```
[:scsibus:6:cdrom] Unhandled command ? (1): c4
```
Adding a stub handler for the command allows the system to work properly. Moreover, it is now possible to switch CD media on a running system without having to resort to messy workarounds: just switch the media MAME's file manager and run `eject` to make IRIX reload it.
=> nscsi/cd: handle eject command for SGI drives

src/devices/cpu/i960/i960dis.cpp, src/devices/cpu/i960/i960dis.h
Based on issue https://github.com/mamedev/mame/issues/6559
- Added 10 opcodes that are currently emulated but missing from the disassembler.
- Operand order was changed to match the _i960® Processor Assembler User's Guide_ as well as _IDA pro_ and _onlinedisassembler.com_
Some things I noticed but did not touch:
- certain opcodes should have 2 operands instead of 3: `not`, `cvtir`, `cvtirl`
the current opcode table does not allow that, though.
- load and store operations with a 1-byte alignment are output differently.
oda.com gives `r10,(g11)[g12]` while MAME gives `st      r10,(g11)[g12*1]`
- branch-on-bit opcodes may be faulty in certain edge cases.
for opcode `30290120` oda.com gives `bbc     r5,r4,...` while MAME gives `bbc     5,r4,...` - the difference being register r5 instead of …
=> i960dasm fixes and additions

src/devices/bus/coco/cococart.cpp
The previous code would get into an infinite loop if the user tried to load a ROM cartridge smaller than or equal to 16k. That's because m_cart->get_cart_size() is 16384:
len = min(16384, 16384-16384)
len = 0
=> Fix CoCo cartridge loading for less than 16k carts.

src/mame/drivers/indy_indigo2.cpp
Move `softlist.h` include before `logmacro.h` per @cuavas comment on https://github.com/mamedev/mame/pull/6601
=> indy_indigo2: fix include ordering

hash/sgi_mips.xml
* Merged CDs that came on the same bundle and add features with metadata on all entries (nw)
* Replaced some images with cleaner ones (Plextor, without C2 errors) (nw)
=> Add missing discs to IRIX 6.5 [ClawGrip, Rampa]

src/devices/cpu/avr8/avr8.cpp, src/devices/cpu/avr8/avr8.h
* Add support for ATMega328 to boot the Arduino UNO.
* Fixed the specification of the page size of the bootloader.
* Fixes m_pc to be correctly initialized in boot sequence.
Test driver demo:
https://github.com/h1romas4/mame/tree/arduino
Best regards.
=> Added a preliminary support for Arduino UNO booting by avr8

src/mame/video/vtvideo.cpp
This fills in 1px gaps in 80column wide mode, details which are lost
unless the line-mode is double-wide. This reintroduces functionality
lost in commit d0fa593c1ea1ad.
=> vtvideo.cpp: Implement pixel stretching of characters.

src/mame/drivers/coco12.cpp, src/mame/drivers/coco3.cpp, src/mame/includes/coco.h
CoCo: Modified coco3dw1 to have becker port turned on by default.
=> CoCo: Changed driver coco3dw1 to have a default on becker port.

src/emu/diimage.cpp
I don't believe MAME compiles on any platform where the colon is a path seperator.
So removing this solves a problem when viewing file names in the UI File Manager.
=> Remove colon as a path seperator in the core

src/devices/cpu/i960/i960dis.cpp, src/devices/cpu/i960/i960dis.h
Based on documents:
- 270567-001  80960KB Programmer's Reference Manual (March 1988)
- 270710-003  i960 CA/CF Microprocessor User's Manual (March 1994)
- 271081-001  80960MC Programmer's Reference Manual (July 1988)
- 272483-001  i960 Jx Microprocessor User's Manual (September 1994)
- 272484-002  i960 Hx Microprocessor Developer's Manual (September 1998)
- 272736-002  i960 Rx I/O Microprocessor Developer's Manual (April 1997)
- 273353-001  Intel 80303 I/O Processor Developer's Manual (May 2000)
Why oh why are there so many different variant of the i960? :)
The older variants (Mx, Kx, Jx) have several bits defined as zeros, which are used for various things in the newer variants (Cx, Hx, Rx).
I implemented some checks for all bits that are (still) defined as zeros in newer variants to …
=> i960dasm: rewrote disassembler

src/devices/cpu/m6809/hd6309.ops
nw: I removed the wrong BRA in the last patch. This one puts the correct BRA back on and removes the BRA that is illegal.
=> 6309: removed wrong BRA

src/devices/cpu/i960/i960.cpp
Currently, one IAC message is supported (0x93) by the i960KB cpu emu, but the manual defines several more. Any unsupported messages call fatalerror and kill MAME. It seems that this hasn't been an issue for most games, but it does cause VF2, Fighting Vipers and Sonic the Fighters to crash when using the debug menu, as outlined here: http://sudden-desu.net/entry/debug-tools-in-virtua-fighter-2-fighting-vipers-and-sonic-the-fighters
This patch adds cases for each of the IAC messages outlined in the 80960KB Programmer's Reference Manual (chapter 13). While there isn't much actual code implementation, this will at least prevent MAME from fatal'ing.
=> Add partial support for all IAC messages

src/mame/drivers/raiden2.cpp
[jj4b02__ami18cv8-15.u0342.zip](https://github.com/mamedev/mame/files/4584061/jj4b02__ami18cv8-15.u0342.zip)
https://twitter.com/neSneSgB/status/1232115385303879680 Discussion starting here, I successfully dumped the missing U0342 from a location test US Raiden 2, and confirmed that the dump worked on a final Raiden 2 PCB. I converted it to a binary using jedutil to generate the CRC and SHA1.
=> raiden2.cpp: add U0342 PAL to ROM definitions

src/lib/formats/hxchfe_dsk.cpp
this fixes https://mametesters.org/view.php?id=7526
`src/lib/formats/hxchfe_dsk.cpp` reproducibly creates a SEGV when writing HFE files. This is caused by an endless loop in `hfe_format::generate_hfe_bitstream_from_track`, writing beyond end-of-array at https://github.com/mamedev/mame/blob/140ba5147df230751a87a62374eba8880f5d3dbe/src/lib/formats/hxchfe_dsk.cpp#L683
The endless loop is caused by re-setting `cur_pos` at two occasions and re-setting the loop variable.
This fix drops the reset of `cur_pos` resulting in a successful write of a mixed-density (track0 sd, others dd) HFE image.
=> fix HFE disk write

hash/famicom_flop.xml, hash/msx1_cart.xml, hash/nes.xml
moejudo alt_title typo is fixed and also made to match box orthography, otherwise changes are self explanatory.
=> nes.xml, famicom_flop.xml, msx1_cart.xml: minor metadata fixes

src/mame/drivers/nemesis.cpp, src/mame/includes/nemesis.h
this is proof of the problem.. better would be to know why the dump was stripped in the first place...
=> add init to convert twinbeeb bubble dump into something the driver can actually use (nw)

hash/sgi_mips.xml
Also add a missing CD for 6.5.13 and merge two freeware entries with their corresponding IRIX releases.
=> sgi_mips: new software list additions

src/mame/drivers/gal3.cpp, src/mame/drivers/namcos21.cpp, src/mame/drivers/namcos21_c67.cpp, src/mame/drivers/namcos21_de.cpp
8MHz XTAL isn't exists in these hardwares, so 21.39KHz is wrong.
=> gal3.cpp, namcos21*.cpp: Fix c140 input clock source related to on-chip XTALs

hash/sgi_mips.xml
Fix a few issues reported by @Tafoid 
- drop `apps_6_5_aug_01` as it's already included in `irix_6_5_13`
- use the correct hashes for `hotmix_11` and `hotmix_12`
- drop `irix_5_3_d` as the media is a straight duplicate of `irix_5_3_a`, and a proper version hasn't surfaced yet
=> sgi_mips: fix a few issues

src/mame/drivers/dec8.cpp, src/mame/includes/dec8.h
(note, this causes loss of coinage sound, it doesn't generate the same interrupt on the MCU as the other games at least as there's no code for that)
=> identified 3 bad bits in csilver MCU dump, corrected them, hooked up MCU, removed simulation [dink]

src/mame/video/gime.cpp
This gets cartridges working again. (nw)
=> CoCo: fix 0xFEXX memory when in ROM mode.

src/devices/machine/6850acia.cpp
Fixes a lockup running UniFlex on the SWTPC09.
Tested on hardware, the TDRE flag reads as zero in the reset state and
reads as set when taken out of reset, and even if data has been written
to the data register while in the reset state.
=> mc6850: TDRE should read clear in reset, and set coming out of reset

src/devices/cpu/tms32031/32031ops.hxx, src/devices/cpu/tms32031/dis32031.cpp, src/devices/cpu/tms32031/dis32031.h, src/devices/cpu/tms32031/tms32031.cpp, src/devices/cpu/tms32031/tms32031.h
Fix chip name (no NMOS variant exists) and some descriptions
Fix Microcomputer mode when 320C30 internal ROM is empty
reference: TMS320C3x User's Guide
=> cpu/tms32031/*: Add/Correct notes for Internal peripherals and Chip family differences

src/devices/machine/generalplus_gpl16250soc.cpp, src/devices/machine/generalplus_gpl16250soc.h, src/devices/machine/generalplus_gpl16250soc_video.cpp, src/devices/machine/generalplus_gpl16250soc_video.h, src/mame/drivers/generalplus_gpl16250.cpp, src/mame/drivers/generalplus_gpl16250_rom.cpp, src/mame/drivers/generalplus_gpl16250_romram.cpp, src/mame/includes/generalplus_gpl16250.h, src/mame/includes/generalplus_gpl16250_romram.h
tkmag220 will fairly quickly show a rom test screen where the check fails (not surprising, ROM is banked etc. and might need some swapping applied) (nw)
lazertag, after a long time unthrottled, will show a single screen of sprites, there are palettes uploaded for something else before that, but like many of these it never seems to populate tile ram (nw)
=> some small GPL16250 tweaks / hacks so that tkmag220 and lazertag show more (nw)

src/mame/includes/gaplus.h, src/mame/video/gaplus.cpp
- Fixed scrolling speed and direction ([Testers-00434](https://mametesters.org/view.php?id=434))
- Added top and bottom clipping ([Testers-07663](https://mametesters.org/view.php?id=7663))
- Modified to use sprite color instead of text color with refer to the PCB
- Added blinking when the movement of the star changes
Reference Video:
https://www.youtube.com/watch?v=vrmZAUJYXnI
https://www.youtube.com/watch?v=_1x5Oid3uPg
=> gaplus : Fixed displaying of starfield

src/mame/video/cps1.cpp
sf2level, sf2m3, sf2m8, sf2ceds6, sf2cems6a, sf2cems6b, sf2cems6c, sf2re, sf2rules
scroll1 was off by 4px
=> fix scroll offset, various sf2 bootleg sets

src/emu/debug/debugcon.cpp, src/emu/debug/debugcon.h, src/emu/emuopts.cpp, src/emu/emuopts.h, src/emu/machine.cpp, src/emu/machine.h
When this option is specified, all console output is echoed to a log
file.
Some caveats/limitations:
- The file-open process was copied from -log, so it has the same limits
- Filename is hard-coded (debug.log)
- File is overwritten if it exists
- File is opened during emulation initialization
- Thus, the file is cleared if you invoke the "Hard Reset"
debugger command
- Probably some other details I don't know about
- Logging works as such: When a string is appended to the scrollback
buffer, it is also written to the log file.
Some commands forcibly wrap their output (e.g. `help` to 80 columns.)
Because this wrapping is done inside the scrollback buffer, the text
written to the file is not wrapped.
This can be seen with `help execution`.
=> Debugger - add `-debuglog` option to log debug console output to file

src/mame/drivers/armedf.cpp
Fix of [MAME Testers 07640](https://mametesters.org/view.php?id=7640)
Fixed that "Armed Formation" resolution was 16 pixels narrower than PCB. (320x224 -> 320x240)
=> armedf : Fixed the resolution difference from PCB. (Testers-07640)

src/mame/video/tubep.cpp
Text and sprite layers draw a drop shadow with 1 dot width to the left.
See the gameplay video on the PCB. https://www.youtube.com/watch?v=xxONzbUOOsw
=> tubep : Added text and sprite drop shadow

src/mame/drivers/consola_emt.cpp
* N80C188XL25 is known to work at 25MHz (nw)
* This specific ROMset is from 24/Mar/2003 (nw)
=> consola_emt.cpp: Small fixes (nw)

src/mame/drivers/taitowlf.cpp
Some of these components were already mentioned later in the driver. "TODO" wasn't really correct because main board (and rom board connected to main board) all communicate with the PC motherboard via PCI. Figuring out PCI comms between both boards as well as reading the two program roms, u1 and u2, may prove tricky.
=> taitowlf: update documentation (nw)

scripts/src/bus.lua, src/devices/bus/coleco/cartridge/exp.cpp, src/devices/bus/coleco/cartridge/exp.h, src/devices/bus/coleco/cartridge/megacart.cpp, src/devices/bus/coleco/cartridge/megacart.h
Assume that a rom file that is more than 32K in size is a megacart
and that it should be bankswitched using Megacart protocol.
=> Support Colecovision Megacart.

src/mame/drivers/twinkle.cpp, src/mame/layout/bmiidx.lay
All games running on the Twinkle hardware shipped with anamorphic 16:9 widescreen monitors. In 4:3, most graphics appear squashed horizontally. (beatmania IIDX continued to use anamorphic widescreen after switching to PC hardware with 9th style.)
This also updates the Lamps layout to display the screen in 16:9 and changes the color of the 16-segment display to "LED red" to match the 16-segment displays that were used on the machines.
=> Change aspect ratio for Konami Twinkle to 16:9

src/mame/drivers/tiki100.cpp, src/mame/includes/tiki100.h
Graphics emulation for Tiki-100 redone to be accurate down to the start of each scanline, and making palette-changes work correctly. Also fixed a small inacuracy in the keyboard, where the column-select would reset after the wrong number of reads.
=> Tiki-100 improvement

src/emu/debug/debugcon.cpp, src/emu/debug/debugcon.h, src/emu/debug/textbuf.cpp, src/emu/debug/textbuf.h
This is another debugger enhancement -- it allows you to export the
current contents of the debug console window to a file.
The filename parsing is based on the `trace` command, and as such,
supports both the "{game}" placeholder, and the ">>" prefix for
appending instead of overwriting.
=> Debugger: add `condump` command to export console buffer to a log file

hash/famicom_flop.xml, hash/gameboy.xml, hash/nes.xml
gameboy.xml's pocket mahjong was listed as a clone of pokemon yellow which explains an earlier mistake where a jp version of pokemon yellow was not listed as a clone. pocketmj is clearly a different game.
=> gameboy.xml, famicom_flop.xml, nes.xml: more metadata corrections

hash/pc98.xml
- Added new software items from the Neo Kobe Collection (working):
Eimmy to Yobanaide (Demo)
Ekispert
Ekudorado - Kagami no Naka no Oukoku
Elm Knight - A Living Body Armor (Demo)
Elthlead Senshi
EO System 3.0 (v1.10 installer)
EPSON Jiko Shindan Program
EPSON MS-DOS 2.11 (Rev. E22)
EPSON MS-DOS 2.11 (Rev. R15)
EPSON Nihongo Disk BASIC v2.0
Estate
eXOn
eXOn (Demo)
Expert-98
- Added new software items from the Neo Kobe Collection (not working):
Eisei Meijin II
Elysion (2DD version)
EPSON Software Installation Program (v2.17)
EPSON Software Installation Program (v2.23)
EPSON Software Installation Program (v2.27)
EPSON Software Installation Program (v3.02)
- Relabeled disks with their actual names
- Added usage notes for software that needs DOS
- …
=> pc98.xml: softlist updates, part 6 (E)

src/frontend/mame/luaengine.cpp
Allows to see possible values and their descriptions for DIP switches, since those can't be deduced from raw numbers.
**Setting value** is _table key_, **setting name** is _table value_, which may look like they're reversed, but it's not a mistake: we're sending digital values, they're the primary subject here, and setting names are just hints for humans.
=> Expose ioport_setting to luaengine

src/devices/sound/ics2115.h
Interpolation issue is most noticeable in cave PGM hardware game musics
=> ics2115.h: Add imperfect_features related to incorrect/unverified interrupt, interpolation, ramping

src/mame/drivers/cps1.cpp
fixed gfx rom loading and decode (sf2rk_init), fixes corrupt sprite issues (text, zangief etc.)
added note and rom patch regarding the dark screen issue, confirmed present on real pcb.
patch disabled by default as correct behaviour is to have no palette fade effects and turn up contrast as with real pcb/monitor, launching with -contrast 2.5 looks about right to me.
=> fix sf2rk gfx rom load and decode

hash/ibm5170.xml
humans_525: changed the floppy interface to "floppy_5_25"
inca2: renamed from "Inca 2: Wiracocha (Europe)" to "Inca 2: Wiracocha (Euro)"
goblins: renamed from "Gobliiins (US - VGA release)" to "Gobliiins (USA, VGA version)"
=> ibm5170 - changes

src/mame/drivers/chicago.cpp, src/mame/drivers/exidyttl.cpp
Various prom image issues were fixed
dmodrbcc:
All 512 byte roms were set to length 256 (incorrect length)
Some upper bits in nibble-wide roms were not set to default zero
destdrby ("new" driver):
Added newly dumped roms from exidy PCB, images now match fixed images from dmodrbcc (expected)
Added new skeleton driver in exidyttl.cpp.
(Redundant with dmodrbcc in chicago.cpp, but it is a different PCB layout and different company)
deathrac:
Images 36 and 35 were corrupt, fixed with correct images from bootleg rhunting
Added note about format of image 36
rhunting:
Images now match death race 100%
Driver now uses deathrac rom images
=> (nw) (destdrby) Rom Image Corrections/Fixups:

src/devices/cpu/cp1610/cp1610.cpp
Use a 16 bit temp variable so the high 8 bits from the second read
are discarded and can't affect the COV calculation.
=> Ensure SDBD operations set correct condition flags.

hash/fmtowns_cd.xml
Akiko - Premium Version
Cal III - Kanketsu-hen
Chiemi & Naomi
Curse
Eikan wa Kimi ni 2 - Koukou Yakyuu Zenkoku Taikai
FM Towns Application Catalog CD-ROM - Original Soft-hen
G5 (HMA-206)
Gambler - Queen's Cup
Gokuraku Mandala
Hyper Fetishism
Illust Hyakka - Yamashita Hideki no Ikiiki Cut-shuu
Iris-tei Serenade
Jouhou Club - Card Processor Ver. 1.1
Mahjong Musashi
Manami no Doko made Iku no? 2 - Return of the Kuro Pack
Marionette Mind
Mirage 2 - Torry, Neat & Roan Fairladies in MagicLand
Noushuku Angel 120%
Shamhat - The Holy Circlet (FM Towns Marty version)
Tenshin Ranma
The Manhole (1990-08-01)
Two Shot Diary
Viper-V12 RS
Pro Student G (ALS-0010)
Towns-Telop
True Heart
- Replaced entries with dumps from …
=> fmtowns_cd.xml: 26 new dumps, 24 replacements

.travis.yml
The fact that asmjit does not build on anything except x86 got missed recently. This commit adds arm64 and s390x to travis CI so that issues like this get noticed sooner.
=> Add arm64 and s390x to travis CI

hash/sgi_mips.xml, hash/sgi_mips_hdd.xml, src/mame/drivers/indy_indigo2.cpp
Add a new software list to collect preinstalled hard disk images for SGI workstations.
=> sgi_mips_hdd: add software list

src/mame/video/bosco.cpp
Sprites have a lower priority than BG.
MAME 0.222
Fixed
PCB
=> bosco.cpp: Sprites have a lower priority than BG.

src/mame/drivers/midyunit.cpp, src/mame/includes/midyunit.h, src/mame/machine/midyunit.cpp
Mortal Kombat bootleg mkyawdim2
fixed sound
added some pal dumps
created a [schematic of sound section](https://drive.google.com/file/d/1KeOUkzJNXqwgpDgrdjke42A3cKhwSrv6)
sound emulation now accurate with real bootleg pcb, still poor compared to genuine Midway pcb (just has a single m6295 after all)
=> mkyawdim2 fix sound, add pal dumps

hash/sgi_mips.xml
This PR adds the following CD images (dumped from original media) for the SGI MIPS driver(s):
* European Language Module 1.1 (in a separate commit)
* European Language Module 1.3.1
* Desktop Special Edition 1.0
Later commits add the following (see comments below for some pictures)
* IndiZone 1.0
* ONC3/NFS for IRIX 6.2
* ONC3/NFS for IRIX 6.2 with Indigo² IMPACT 10000
* IRIX 5.1.1.2 patch
* IRIX 5.2 for Indy R4600PC and Challenge SX
~~Since I do not have FTP access, I uploaded the corresponding CHD files [here](http://files.darkstar.me/sgi_mips_chds.zip). The ELM 1.1 (for the second commit) is [here](http://files.darkstar.me/european_language_module_1_1.zip).~~
All CHDs (also those for the other commits) are combined [here](http://files.darkstar.me/sgi_chds.zip)
Since these are the first …
=> sgi_mips.xml: Many new additions

src/lib/formats/wd177x_dsk.cpp
A single missing sector was causing it to give up on an images, as incompatible. Being a little more permissive here helps working
with some old recovered disk images with some lost sectors.
It had once looked at only the first track to assess compatibility, but that was changed to look at all tracks to deal with variations on the first track and variations on different sides, but that was probably a little to restrictive.
=> wd177x dsk: be permissive of some missing sectors in later tracks

src/lib/formats/os9_dsk.cpp
These formats were by OS9 L1 on the Motorola EXORciser.
=> os9 dsk: add 8 inch, 16 sector, single density formats

src/devices/bus/rs232/printer.cpp
High is the restful state for RS232. The low level could cause
continual breaks to be received by an attached device and this could
cause problems for some drives.
=> rs232 serial printer: initialize the data output high.

scripts/target/mame/mess.lua, src/mame/drivers/monkey_king_3b.cpp, src/mame/mame.lst, src/mame/mess.flt
The Monkey King 3B is an emulation-oriented ARM-based SoC by Digital Media Cartridge, a company closely associated with AtGames. The Monkey King family is a successor to their Titan ARM-based SoCs.
The RS-70 is one of the systems using it, with 648 NES and Genesis games on NOR flash in a PS1-esque casing and HDMI output.
This is just the beginnings of the core, all it does so far is print the following debug messages before hanging, but at least that means the memory mapping is vaguely right:
```
Modes:0x00000000
PUT: Setting joystick to mode 0x0, timer to 250us
******************************************************
MK FIRMWARE INFORMATION
Mode:       0xB4
Build Time: May  8 2019 14:09:21
CPU Clock:  240MHz
TFS Start:  0x8070000
Video Buf:  0x6000000
Stack Top:  0x3001EE8
IWRAM Size: 32kB …
```
=> Add Monkey King 3B SoC skeleton and RS-70 system

src/lib/formats/mdos_dsk.cpp, src/lib/formats/mdos_dsk.h
Some more scrutiny made it clear that the cells size was wrong, and the gaps then needed some correction too. It was working, the PLL adjusted the bit clock, but it was off. Updated the comments to make it clear that this is the Motorola MDOS format, as requested. FYI EXORterm 155 and EXORciser emulators are being developed and reading, writing and formatting this disc format is working - trying to finish them off and clean them up.
=> mdos dsk: fix the cells size and gaps, make clear its Motorola MDOS

hash/ibm5150.xml
Just a quick fix for my own copy-paste mistake (the files don't change). Thanks to ArcadeShadow for pointing it out in #6876.
=> ibm5150.xml: fix dataarea sizes (nw)

hash/sgi_mips.xml
This PR adds the following new software list entries:
- Hot Mix 5
- Hot Mix 7
- SupportFolio 10/96
- SupportFolio 2/97
- SupportFolio 4/97
- SupportAdvantage 10/94
- SupportAdvantage 6/95
~~It also renames some Hot Mix CDs to increase consistency.~~
Photos of the CDs will be added in the comments.
All CHDs are available [here](http://files.darkstar.me/sgi_chds_2.zip)
=> sgi_mips.xml: New additions

hash/sgi_mips.xml
Sorry, I goofed up on this CD (or rather ISObuster goofed up and I didn't notice)
[Here](http://files.darkstar.me/indizone.zip) is the fixed CHD. It replaces the one from PR #6868
=> sgi_mips.xml: fix bad dump (nw)

hash/pc98_cd.xml
Chiemi & Naomi
F15 Strike Eagle III
if 2 - Invitations from Fantastic Stories
Manami no Doko made Iku no? 2 - Return of the Kuro Pack
Phobos
Pro Student G (ALS-0010)
YES! HG - Erotic Voice Version
Yuurou - Transient Sands
DOR Special Edition '93
DOR Special Edition '93 (alt)
Kanji Land 3-nen
Kyrandia II - The Hand of Fate
Lemon Cocktail Collection
Lip 3 - Lipstick Adventure 3
Mirage 2 - Torry, Neat & Roan Fairladies in MagicLand
Branmarker 2
Eimmy to Yobanaide
Lesser Mern - Special Director's Edition
Mahjong de Pon!
Saint Diary - Kiyoka-chan no Nikki
Takamizawa Kyousuke - Nekketsu!! Kyouiku Kenshuu
The Legend of Kyrandia
Tuned Heart
Vastness - Kuukyo no …
=> pc98_cd.xml: 15 new dumps, 11 replacements

src/devices/machine/mc6852.cpp, src/devices/machine/mc6852.h
This adds functionality needed to support a Motorola m68sfdc floppy disk controller emulator. It adds byte sized functions for sending and receiving data as these are a practical size for the FDC emulation. It should not regress any existing functionality and does not touch the serial interface which appears to be only a skeleton. Various issues TODO are noted. It has been tested on a m68sfdc emulator running EXORciser firmware.
=> mc6852 - implement more functionality, add byte interface.

scripts/src/bus.lua, scripts/src/machine.lua, scripts/target/mame/mess.lua, src/devices/bus/rs232/exorterm.cpp, src/devices/bus/rs232/exorterm.h, src/devices/machine/exorterm.cpp, src/devices/machine/exorterm.h, src/emu/layout/exorterm155.lay, src/mame/drivers/exorterm.cpp, src/mame/mame.lst, src/mame/mess.flt
This was an early Motorola terminal that was used with Motorola MDOS on the EXORciser. I doubt it is of general utility except for MDOS so it has not been added to the default RS232 device. It has been implement as a device so that it can be integrated with an EXORciser emulator, but a stand alone front end is also included. It has been tested on an EXORciser emulator.
The firmware was from http://bitsavers.trailing-edge.com/components/motorola/6800/EXORterm_155/ and there is a useful manual there too. There appears to be no dump of the character ROM, so an apparently similar published Motorola character set has been substituted for now. The collection of files is at https://68bit.org/exorterm155_device.zip
=> EXORterm 155: Motorola terminal

src/devices/bus/isa/gblaster.cpp, src/devices/bus/isa/sblaster.cpp, src/devices/sound/saa1099.cpp, src/devices/sound/saa1099.h, src/mame/drivers/vgmplay.cpp
Fix noise frequency closer to real hardware, Reduce unnecessary, unused values, Reduce duplicates, macros
gblaster.cpp, sblaster.cpp: Fix output, clock inputs, verified from real hardware
vgmplay.cpp: Support SAA1099 stereo output, reference: pinout, datasheet
=> saa1099.cpp: Fix output, frequency behavior, Add notes

hash/ibm5150.xml
Source: https://archive.org/download/msxenix/apps/sco-xenixdev-2.1.3.zip
The manual is also available at https://archive.org/details/xenix-release-notes-2
=> ibm5150: add XENIX Development System

src/emu/layout/exorterm155.lay
This change adjusts the aspect ratio to bring it close to that in the
photo of the screen in the manual. The monitor has a 4:3 aspect
ratio. The character area resolution is 720x288 pixels and the prior
1:1 dot ratio was far from realistic.
=> exorterm: more realistic layout screen aspect ratio.

src/emu/devcb.h
"Fix"
```
In file included from ../../../../../src/emu/emu.h:103:
/Users/buildbot/buildbot/osx/libretro-mame/build/projects/retro/mame/gmake-osx-clang/../../../../../src/emu/devcb.h:1102:12: error: 'consume' is a protected member of 'devcb_write<unsigned char, '\xFF'>::builder_base'
{ m_sink.consume(); }
^
```
full build log: http://paste.libretro.com/215612
Feedback welcome about best way to implement the compiler check.
=> Use gcc broken friend workaround also with clang8

plugins/autofire/autofire_save.lua
Changed to determine if dictionary is empty
=> plugins/autofire: don't save 2bytes cfg file (nw)

src/devices/video/imagetek_i4100.cpp, src/devices/video/imagetek_i4100.h, src/mame/drivers/hyprduel.cpp, src/mame/drivers/metro.cpp
Sprite position when zoomed, Tilemap offsets, glitches in hyprduel
hyprduel.cpp: Fix sprite delay
metro.cpp: Fix flipped tilemap offset for vmetal
=> imagetek_i4100.cpp: Partially fix flip screen

.travis.yml
macOS builds have recently begun failing due to hitting 50 minute time limit. This change appears to shave a couple minutes off, enough to make the cutoff:
https://travis-ci.com/github/belegdol/mame/builds/176776347
=> Overhaul travis.yml in an attempt to speed up macos builds

.appveyor.yml
GCC build on windows appears to be broken on optimisation levels below -O3. O3 build has finished within approximately 50 minutes which means that it at least has a chance of succeeding. Once gcc or mame is fixed to build with -O1, this change can be reverted. While not ideal, it would unbreak the CI until a proper fix is in place.
=> Switch appveyor GCC build to -O3 (issue #6804)

src/devices/video/vector.cpp, src/devices/video/vector.h, src/emu/emuopts.cpp, src/emu/emuopts.h, src/frontend/mame/ui/ui.cpp, src/frontend/mame/ui/ui.h
Add new option beam_dot_size that controls the rendered size of 'dots' in vector games. [Aaron Giles]
=> Add new option beam_dot_size

scripts/src/bus.lua, scripts/target/mame/mess.lua, src/devices/bus/hp_ipc_io/82919.cpp, src/devices/bus/hp_ipc_io/82919.h, src/devices/bus/hp_ipc_io/hp_ipc_io.cpp, src/devices/bus/hp_ipc_io/hp_ipc_io.h, src/devices/machine/mc68681.cpp, src/devices/machine/mc68681.h, src/mame/drivers/hp_ipc.cpp
Hi,
in this PR I'm adding the support for I/O slots to HP integral PC. At the moment there's just the 82919 serial I/O card emulated.
The test of serial card on HP diagnostic disk passes thanks to a couple of fixes to MC68681 driver. Hopefully, these changes are not affecting other systems with this chip.
Thanks.
--F.Ulivi
=> HP IPC: support for I/O slots and 82919 serial card added

src/devices/machine/netlist.cpp, src/emu/emuopts.cpp, src/emu/emuopts.h, src/emu/speaker.cpp, src/emu/speaker.h
Added a new option -speaker_report <n> which enables an end-of-session report from each speaker on the maximum sample value seen and whether there was any clipping. n=0 (default) means no report. n=1 prints a summary only if there was clipping, and n=2 prints the summary regardless. n=3 prints a list of clipped maxima over time, and n=4 prints the entire list of maxima across the whole session.
=> Add new option -speaker_report <n> to help devs tune volume

src/lib/formats/mdos_dsk.cpp, src/lib/formats/mdos_dsk.h
Add legacy floppy image support which is currently required for the
mc6843 FDC emulator and used by the EXORset which run XDOS a variant
of MDOS.
Add support for 5.25 inch XDOS floppy drive formats as used by the
EXORset.
Make some of the identity tests more permissive to work with observer
disks. The date day and month are reversed on some disks, and the boot
rib cluster is lower.
=> mdos dsk: support legacy floppy images, add XDOS support

src/devices/machine/mc6843.cpp, src/devices/machine/mc6843.h
Code using programmed I/O may read the last byte of a sector and then
expect to have some time to store that to memory before receiving an
interrupt on the completion of the command. The interrupt was
occurring on the last read and the last byte was being lost by some
drivers. This change adds a delay after reading the last byte, roughly
the time needed to read the 16 bit CRC, before the end of a read
command is processed.
Avoid side effects when these are disabled.
Tested on an EXORset emulator.
=> mc6843: add a delay reading the CRC

.appveyor.yml
Appveyor VS2017 image only ships with pacman 5.1.3 as of now. In that version pacman-key --verify only takes one argument, the signature.
=> Fix redundancy in pacman-key --verify call

src/mame/layout/spyhunt.lay
This adds several optional layouts for Spy Hunter for use of modern widescreen displays.
Included are the following:
- Shifter off the game screen on the left or right
- Shifter and lamps off the game screen on the left or right. This is not 100% accurate to the original display but allows for a larger game screen.
- Vertically oriented layouts with the shifter below the lamps on the left or right side. This is designed for a widescreen monitor rotated 90 degrees to the left or right.
=> Widescreen layouts

.appveyor.yml, .travis.yml, scripts/src/cpu.lua, scripts/target/mame/ci.lua, src/devices/cpu/drcuml.cpp, src/mame/ci.lst
As mentioned in #7037 and #7039, non-x86 build is broken which went unnoticed because the tiny build used for CI currently does not use DRC capable CPU cores.
The approach suggested here does build but I do not know whether it is correct. Thank you for reviewing.
=> Fix non-x86 build and try to make sure it does not break silently again

scripts/src/3rdparty.lua
IMGUI_DISABLE_OBSOLETE_FUNCTIONS was defined in osd/modules.lua but not
in 3rdparty.lua. As a result, two different variants of struct ImGuiIO
were being defined, causing a C++ One Definition Rule violation
=> Define IMGUI_DISABLE_OBSOLETE_FUNCTIONS consistently

hash/pc98.xml
- Added new software items from the Neo Kobe Collection (working):
F-15 Strike Eagle
F29 Retaliator (1992-10-10)
Farland Story - Kamigami no Isan
Farland Story - Juuou no Akashi
Farland Story - Juuou no Akashi (cracked)
Fermion - Mirai kara no Houmonsha
Figure - Ubawareta Houkago
Figure - Ubawareta Houkago (Alt)
Finish Hold
Finish Hold Hissatsuwaza Zukan
Finish Hold 2 - Tag
Fantasy Knight Fukkokuban
First Queen
First Queen (Alt)
First Queen III
FlixMix
Floppy Bunko 09 - Bishoujo Graphic Data Shuu Vol. 04
FontWave
Four Flush
Frontier
Frontier (cracked)
Foresight Dolly
Fuurin Kazan
Fuzoroi no Lemon
- Added new software items from the Neo Kobe Collection (not working):
Fairie's Residence
Farce - Yuuwaku Hakusho
Finish Hold (cracked)
Finish Hold 2 - Tag (cracked)
- Replaced these software …
=> pc98.xml: softlist updates, part 7 (F)

src/mame/drivers/tnzs.cpp
Replaced "datails" by "details".
=> Fix a typo in TNZS driver

hash/hp9k3xx_cdrom.xml, hash/hp9k3xx_hdd.xml, src/mame/drivers/hp9k_3xx.cpp
Add two software lists for hp9k3xx, one for CD-ROM software and one for hard disk images.
=> hp9k3xx: add hp9k3xx_cdrom and hp9k3xx_hdd software lists

hash/ibm5150.xml
Added: Prince of Persia (3.5", v1.1), Wolfpack (USA)
Renamed [ppersia35a]: Prince of Persia (3.5", v1.1) --> Prince of Persia (3.5", v1.1, Hit Squad release)
Renamed [ppersia35fr]: Prince of Persia (3.5", v1.0, French) --> Prince of Persia (3.5", v1.0, France)
=> ibm5150 - New working software list additions

src/mame/drivers/vsmile.cpp, src/mame/includes/vsmile.h, src/mame/layout/vsmile.lay
This PR adds support for visualizing the LEDs in the V.Smile controllers using an opt-in custom layout.
The exact design of the layout could of course be discussed and improved on.
=> vsmile: Simple controller LED visualization support

makefile
PowerPC architecture is special in a way that it has some inline assembly
code but no DRC support. As a result, NOASM=1 was never configured.
In contrast to the old DRC, asmjit only compiles on the architectures it
supports. FORCE_C_DRC_BACKEND=1 needs to be passed to the makefile or
the compilation will fail.
CI target does compile on travis but fails to validate. Full compilation is likely going to fail due to #3157 but with this PR there is one issue fewer.
=> Pass FORCE_C_DRC_BACKEND=1 on ppc architectures

makefile
Fix android builds after mame-0.224 because of https://github.com/mamedev/mame/commit/c8218dabdb7b62a747723bbf774d0f3ccc9118a2.
=> android: auto-discover clang version

src/lib/formats/vg5k_cas.cpp, src/mame/drivers/vg5k.cpp
Add wavfile support for reading/writing tapes, for more accuracy. The currently supported K7 file type misses timing data.
VG5000µ adds a wait cycle after the second T state of the M1 cycle of the Z80. Because it was not emulated, the timings were off, especially in the sensible cassette read/write routines.
With wavfile support added and timings fixed, the emulation can now read/write cassette at 1200 and 2400 bauds.
Still keeping the MACHINE_NOT_WORKING flag, as real hardware tests need to be complete.
=> Add support for WAV tape files to VG5000µ and fix timings.

src/osd/sdl/taputil.sh
I found this while doing the Uthernet work.  The taputil.sh script mentions a "MASK" command line arg and treats it as mandatory but then doesn't actually make any use of it.  So, I dropped it from my copy and the team may be interested in picking that up.
If there's interest in me adding some scripting to perform the iptables commands for performing IP masquerading, I'm happy to do that, too.  Alternatively, it's something that could be added to documentation.
=> Drop MASK from taputil.sh

hash/apple2_flop_clcracked.xml, hash/apple2_flop_orig.xml
Jaws [4am, Firehawke]
Dawn Patrol [4am, Firehawke]
Theseus and the Minotaur [4am, Firehawke]
Dungeon! [4am, Firehawke]
The Coveted Mirror (1983 Penguin Software release) [4am, Firehawke]
Write It Right! Capitalization and Punctuation [4am, Firehawke]
Valentine's Day Grump [4am, Firehawke]
NBA (Version 1.0) [4am, Firehawke]
Panzer Strike! (Version 1.0) [4am, Firehawke]
Police Quest [4am, Firehawke]
Techno Cop [4am, Firehawke]
Nibbler [4am, Firehawke]
Midnight Malady [4am, Firehawke]
Alf (Version 3.2) [4am, Firehawke]
New working software list additions (apple2_flop_clcracked.xml)
Bop-A-Bet (cleanly cracked) [4am, san, Firehawke]
Playing with Science: Temperature …
=> Update Apple II Software lists to September 3rd, 2020

hash/fmtowns_cd.xml
Bible Master 2 - The Chaos of Aglia
Dungeon Master (1989-12-08)
Hyper Planet (1990-09-20)
Kyouiku & FM Towns Vol. 2
Illusion CG Collection Vol. 1 - Yawahada Bishoujo
Record of Lodoss War II - Goshiki no Maryuu
Alone in the Dark 2
Castles
Centurion - Defender of Rome
De-Ja II
Excellent 10
Ikazuchi no Senshi Raidy
Madou Gakuin R
Soko-ban Perfect
Super Real Mahjong PII & PIII +
Super Shooting Towns
Wizardry - Crusaders of the Dark Savant
Xak II - Rising of the Redmoon
Xenon - Mugen no Shitai
- Promoted wizardr7 to working, as the previous dump didn't work due to
a bad conversion to CUE/BIN.
=> fmtowns_cd.xml: 6 new dumps, 13 replacements

src/mame/drivers/vg5k.cpp
- Add support for the "Delta" key
The "Delta" key on the VG5000µ keyboard is wired to directly assert the NMI line of the Z80. The handler for the NMI in the BASIC ROM checks if the CTRL key is also depressed and then causes a soft reset.
This routine can be hooked to produce other effects than soft reset.
=> VG5000µ update: support for the "Delta" key

src/devices/cpu/unsp/unsp_extended.cpp, src/devices/cpu/unsp/unsp_other.cpp, src/devices/cpu/unsp/unspdasm_extended.cpp, src/mame/drivers/generalplus_gpl_unknown.cpp
- fixed extended push/pop for unsp2.0 devices
- identified alt use of dma mode by pcp8718/8728
- allow some illegal opcodes in unsp to be treated as NOP because buggy code in pcp8718/8728 explicitly attempts to execute them
=> pcp8718 / pcp8728 work, including unsp2.0 fixes [David Haywood]

hash/ibm5150.xml, hash/ibm5170.xml, hash/ibm5170_hdd.xml, src/mame/drivers/atpci.cpp, src/mame/drivers/ct486.cpp, src/mame/drivers/ps2.cpp, src/mame/machine/at.cpp
Also add a few missing labels, and tag `win30` as a bad dump due to the WinImage header.
=> ibm5170_hdd: new software list

hash/fmtowns_cd.xml, src/mame/video/fmtowns.cpp
This update slightly changes the behavior of layer and sprite drawing in 15-bit mode:
- Sprite color values are masked to their 15 least significant bits before they are rendered to VRAM.
- Pixels on the bottom layer (or in single-layer mode) are always drawn, even if the transparency bit is set to 1.
This is presumably the actual behavior of the hardware, since the menus and UI elements in Niko² (which are sprites on the top layer) all have bit 15 set to 1 and they would be transparent otherwise, and the Wolfteam logo screen (which is a bitmap drawn on a single layer) has some parts with bit 15 set that are very clearly meant to be visible.
This fixes the missing colors, menus and UI elements in Niko², so the game is playable now. Also fixes a regression in Hatchake Ayayo 1-2-3 with …
=> fmtowns: changes to 15-bit layer/sprite drawing, fixes niko2

src/mame/drivers/atetris.cpp, src/mame/includes/atetris.h
This commit adds support for the ROM bank switching mechanism used in the prototype bartop version of Atari Tetris (`atetrisbp`), based on my own examination of the existing ROM dump.
Since the prototype doesn't use the slapstic, it instead handles bank selection at `$4000-7fff` using a couple of previously unused bits at the same address as the coin counters.
I also removed the "not working" flag from the `atetrisbp` set, since this patch makes it playable and passes the ROM checksum test when entering the service menu.
=> atetris.cpp: add support for bartop proto bank switching

hash/ibm5170.xml
Added: Fables & Fiends - Book One: The Legend of Kyrandia (v1.0, 5.25"), NASCAR Racing, NASCAR: Track Pack, SSN-21 SeaWolf
Renamed [kyrandia] Fables & Fiends - Book One: The Legend of Kyrandia -> Fables & Fiends - Book One: The Legend of Kyrandia(v1.3, 3.5")
Renamed [kyrandiafr] Fables & Fiends - Book One: The Legend of Kyrandia (France) -> Fables & Fiends - Book One: The Legend of Kyrandia (v1.7, 3.5", France)
Corrected [mkg] Mortal Kombat (Germany) to clone of [mk] Mortal Kombat
=> ibm5170 - New working software list additions

src/mame/drivers/seta2.cpp, src/mame/video/seta2.cpp
Add notes for background color
=> seta2.cpp: Fix invisible pixel issue in horizontal zoom algorithm

hash/fmtowns_cd.xml
F-BASIC386 Compiler v2.1 L10
FM Towns Demonstration CD-ROM '90. Fuyu - The Galaxy of FM Towns
Ginga Eiyuu Densetsu II DX+ Towns Special
Indiana Jones and the Last Crusade (Pre-Release Version)
NHK Special - Ginga Uchuu Odyssey Vol. 2 - Choushinsei Bakuhatsu
Presence
Psychic Detective Series Vol. 2 - Memories (Demo)
Sherlock Holmes - Consulting Detective (Demo)
Steepia Lite
Trigger 2
Zan II - Towns Special (1992-04-23)
Hyper Address Ver. 2.0
Megamorph (Demo)
Abel - Shin Mokushiroku Taisen
Cyberia
Dead of the Brain - Shiryou no Sakebi
Dragon Half
Dragon Knight III
Elm Knight - A Living Body Armor
Ningyou Tsukai
Power DoLLS
Power DoLLS 2
Rinkan Gakkou
Shinseiki …
=> fmtowns_cd.xml: 13 new dumps, 16 replacements

plugins/cheat/init.lua
This should be mostly the same as before but cheat.set_* is used instead of :, is_oneshot is a value not a function and the script table just indicates if the script exists not a reference to it.  @npwoods, comments?
=> plugins/cheat: copy the cheat table to not expose internal state

src/mame/drivers/megaplay.cpp
I'm not really sure why the DIP switch definitions for Columns III (`mp_col3`) are dummied out in the driver source, since they seem to work just fine in the actual game, so this patch just enables them in the driver.
=> megaplay.cpp: make the existing Columns 3 dip switch definitions actually used

hash/apple2_flop_orig.xml
BattleTech: The Crescent Hawk's Inception [4am, Firehawke]
Voodoo Island [4am, Firehawke]
Forbidden Castle [4am, Firehawke]
The American Challenge: A Sailing Simulation [4am, Firehawke]
The Mist [4am, Firehawke]
Bop 'N Wrestle [4am, Firehawke]
Bank Street Storybook (Version 1.2) [4am, Firehawke]
Crossword Magic (Version 4.0) [4am, Firehawke]
Riddle Magic [4am, Firehawke]
Apventure to Atlantis [4am, Firehawke]
Mummy's Curse [4am, Firehawke]
Mission on Thunderhead [4am, Firehawke]
Space Rogue [4am, Firehawke]
=> More Apple II stuff for September 2020..

src/mame/drivers/p2000t.cpp, src/mame/includes/p2000t.h, src/mame/machine/p2000t_mdcr.cpp
The P2000M shipped with an MDCR as well. We now turn the mdcr into
a required device and initialize it for the M model as well.
This fixes a nullptr exception upon access of ports 0x10, 0x20.
Includes a fix to reset the phase decoder when the end of tape signal is
raised.
=> Add MDCR support to P2000m

scripts/genie.lua, scripts/src/main.lua
* Most OpenGL link issues fixed. Two remain from drawogl.cpp.
This isn't working anyhow.
* "-video accel" now uses WebGL. This allows GL based scaling and
provides an performance improvement.
* Fixed pong and other games by adding another function to the
exception whitelist
* Target now is mame.html. This allows emrun to be used for testing.
mame.js is created as well and thus the current behaviour
unchanged.
=> emscripten: netlist and OpenGL improvements.

src/devices/video/ppu2c0x.cpp, src/devices/video/ppu2c0x.h, src/devices/video/ppu2c0x_sh6578.cpp, src/devices/video/ppu2c0x_sh6578.h, src/devices/video/ppu2c0x_vt.cpp, src/devices/video/ppu2c0x_vt.h, src/mame/drivers/nes_vt.cpp, src/mame/machine/nes_vt_soc.cpp, src/mame/machine/nes_vt_soc.h
--------
Golden Nugget Casino [David Haywood, Sean Riddle]
Sudoku Plug & Play TV Game '6 Intelligent Games' [David Haywood, Sean Riddle]
Frogger (MSI Plug & Play, white joystick) [David Haywood, Sean Riddle]
35 in 1 Super Twins [David Haywood, Sean Riddle]
Vs. Maxx 17-in-1 [David Haywood, Sean Riddle]
- made use of the code that was already partially present in the NES PPU code to handle emphasis modes, used to highlight tally bars etc. in 'nes rampart', apply a red tint to 'fds bublbobl' and dim the screen in a number of other games.
- fixed a number of issues with VT palette modes that was causing black screens in many games, allowing them to be promoted
- added a timing kludge for interrupts in the NES Frogger titles, until timings are better overall,makes …
=> machines promoted to WORKING (Plug and Play)

src/devices/bus/bw2/ramcard.cpp, src/mame/drivers/bw2.cpp
- The write protection bit was inverted, with that change you can write into IMD files without error.
- The ramcard was broken, it should only respond to addresses below 0x8000, now the option -exp ramcard works and boots up correctly
=> Fix Bondwell 2 machine

makefile
A parallel build appears to sometimes fail with:
```
Converting src/mame/machine/mulcd.ppm...
Unable to open output file 'build/generated/mame/machine/mulcd.hxx'
make: *** [makefile:1728: build/generated/mame/machine/mulcd.hxx] Error 255
```
This commit adds the same dependency that other files in GENDIR have.
=> Makefile: add GEN_FOLDERS dependency to mucld.hxx

hash/ibm5150.xml
Add the game "Fire & Forget 2" which was dumped from an original disk using a KryoFlux.
The disk image, a scan of the disk and the KF dump can be downloaded [here](https://s3.au.de:8082/md1-stuff/fireforget2.zip)
=> ibm5150.xml: Add Fire & Forget 2

hash/fmtowns_cd.xml
- New dumps (working):
NHK Eigo de Asobo Vol. 3 - Bernard no Amusement Park [redump.org]
Oshiete Noobow [sampson]
Z's Triphony DigitalCraft Towns (HMB-212) [redump.org]
Burai Kanketsu-hen
Jealousy
Kindan no Ketsuzoku
Lunatic Dawn II
Necronomicon
- Added floppy disk dump to Railroad Tycoon and promoted to working [anonymous]
- Added a recreated floppy image for Lipstick Adventure 3 (marked as a bad dump), and promoted to working.
=> fmtowns_cd.xml: 3 new dumps, 5 replacements, railtycn/lipsadv3 floppies

makefile, scripts/src/3rdparty.lua, src/osd/modules/file/posixptty.cpp
Those 3 commits (+2 in 3rdparty, see https://github.com/evadot/mame/commits/fbsd) makes mame compilable on FreeBSD.
I'll work with upstream so they include the fixes and get back here when it's done.
When everything compile out of the box I'll add a CI target as travis supports FreeBSD.
=> FreeBSD fixes

src/devices/bus/a2bus/computereyes2.cpp, src/devices/bus/a2gameio/computereyes.cpp, src/devices/imagedev/picture.h
null references are not valid in C++ so compilers like to eliminate the null pointer check. This can result in a segfault,
eg, `mame apple2e -gameio compeyes` will segfault if no image (`-pic`) is provided.
switched to use a pointer instead.
=> picture_image_device::get_bitmap can return a null reference

hash/sgi_mips.xml
This commit adds some more "Hot Mix" CDs to the SGI softlist. They were all sourced from the Internet and are not dumped by me, that's why they are all standard MODE1 dumps (not RAW)
I also corrected the year on the Hot Mix 11 and Hot Mix 12 CDs:
* For Hot Mix 11, the year in the ISO9660 PVD is 1995, and all files are also dated 1995, and the copyright in the file "HTML/APPSDIR/APPS.HTM" also says 1995
* For Hot Mix 12, all files are dated 1995, and since it's unlikely to have come before Hot Mix 11, 1995 is certainly the correct year
For the naming ("Hot Mix Volume X" vs. just "Hot Mix X") I looked at various sources
* For Volume 1, the string "Hot Mix, Volume One" appears in the README on disc
* For Volume 9, the cover says "Volume 9" (as can be seen on later Hot Mix CDs, as the covers …
=> sgi_mips.xml: more Hot Mix CDs for SGI

scripts/target/mame/mess.lua, src/mame/drivers/generalplus_gpl162xx_lcdtype.cpp, src/mame/drivers/generalplus_gpl_unknown.cpp, src/mame/mame.lst, src/mame/mess.flt
- split off the handhelds that seem to be based around gpl162xx technology into their own file from generalplus_gpl_unknown.cpp to generalplus_gpl162xx_lcdtype.cpp
- identify unkunsp based on new information
(I'll rename sets + add extra in a separate PR for clarity)
=> - split off the handhelds that seem to be based around gpl162xx technology into their own file from generalplus_gpl_unknown.cpp

src/mame/drivers/darius.cpp
darius: fix: MSM5205 output ports are inverted
The stereo output channels of ADPCM chip (OKI MSM5205) are inverted.
I've confirmed it on the output of an actual arcade machine instance and the official soundtrack.
Confirmation method :
Start any variant of Darius and press F2, F3.
When the monitor test screen comes up, press 1 Player Start to enter the test mode.
Press P1 Up 46 times to set the SOUND CODE to 2E.
Press 1 Player Start to play the track 'Inorganic Beat'.
Compare the ADPCM part with official soundtrack
( e.g. https://www.youtube.com/watch?v=4toor1KlugA ) .
=> darius: fix: MSM5205 output ports are inverted

hash/ibm5170.xml
Redumped: 1830 - Railroads & Robber Barons (software promoted to working)
Marked: "doombbs" marked as bad dump (modified OEM ID and modified root)
=> ibm5170: Redumped - 1830

hash/ibm5150.xml
Added: Silent Service 2 (v457.03, 5.25"), Silent Service 2 (v457.01, 5.25"), Silent Service 2 (v457.01, 3.5"), Sex Vixens from Space
Marked: "fireforget2" marked as bad dump (modified root)
=> ibm5150: New working software list additions

hash/sgi_mips.xml
This PR adds the developer toolbox CDs from [nixzone.nl](http://nixzone.nl/hotmix/).
I could not find any SGI P/N for them online, so for now they were added without. The year was inferred from the README and COPYRIGHT files on the CD. The only information I could find is [this archived page](http://archive.irixnet.org/sgistuff/software/irixintro/index.html) on irixnet (which was archived from nekochan.net before it went dark), which has some pictures of the Developer Toolbox 4.2 CD
Yes, the Developer Toolbox 6.1 really starts numbering with CD 0 (not CD 1), confirmed by the README on the first CD.
The CHDs are available to download [here](https://s3.au.de:8082/md1-stuff/developer_toolbox_chds.zip)
=> sgi_mips.xml: Add Developer Toolbox CDs

src/mame/drivers/ninjaw.cpp, src/mame/drivers/warriorb.cpp
darius2 darius2d warriorb: fix: stereo output channels are inverted
Stereo output channels on Darius II / Warrior Blade are inverted .
It can be observed on titles that use same hardware.
As for darius2, both dual screen and triple screen variants have same issue.
I've compared it with actual arcade machines and official soundtracks.
Step to reproduce/comparison:
Start any variant of Darius II(darius2/darius2d/sagaia ...) and press F2, F3.
When the monitor test screen comes up, press [1 Player Start] to enter the test mode.
Press [P1 Up] 10 times to set the SOUND value to 0A.
Press [1 Player Start] to play the track 'Olga Breeze'.
Compare the playback with a proper source
( e.g. https://mora.jp/package/43000033/ZTTL9023/  track#3) .
Start warriorb and press F2, F3.
When the monitor test …
=> darius2 darius2d warriorb: fix: stereo output channels are inverted

src/lib/netlist/generated/static_solvers.cpp, src/mame/audio/nl_brdrline.cpp, src/mame/audio/vicdual.cpp
according to #7328 and #7091 i would change the triggers for the inputs a little bit to fit the sounds more to what i remember to.
its only suggestions.
=> my suggestions to brdrline trigger assignments

scripts/src/bus.lua, scripts/target/mame/mess.lua, src/devices/bus/fmt_scsi/fmt121.cpp, src/devices/bus/fmt_scsi/fmt121.h, src/devices/bus/fmt_scsi/fmt_scsi.cpp, src/devices/bus/fmt_scsi/fmt_scsi.h, src/mame/drivers/fmtowns.cpp, src/mame/includes/fmtowns.h
This update adds a slot device to the first-generation FM Towns models that represents the dedicated 30-pin slot for the FMT-121 SCSI Card, and another device for the card itself. This is a one-off slot that only exists in the Model 1 and 2, and only supports that one card (as far as I know).
This allows users to use hard disks with the original "fmtowns" machine in a realistic way, as an optional slot card (instead of the "fake" integrated controller it had in older versions of MAME, that was removed with commit 2576f614e6c9b7da6f9ddd936356b3262a1dd0c4), with the -scsislot option:
mame64 fmtowns -scsislot fmt121 -hard1 harddisk.chd
This is the first time I deal with slot devices, so I used the Pasopia PAC2 and X68000 slots as reference. It's a very simple card, but I hope everything …
=> fmtowns: add devices for the SCSI card slot and the FMT-121 card

src/mame/drivers/pacman.cpp, src/mame/includes/pacman.h
These two commits add/improve a few things for `clubpacm` and `clubpacma`:
* Multiplexed P1/P2 joystick inputs for Double Command mode in `clubpacm`
* Corrections to other inputs (including dip switches)
* Simple protection(?) latch needed by at least `clubpacma`
Both of these sets should now be in good shape, aside from some bugs in the games themselves (which I tried to document in comments where possible, e.g. the broken free play setting).
The only thing I'm not really sure about is whether `clubpacm` is supposed to support third and fourth joysticks for the other side of a cocktail table, or if it's even intended to be playable in cocktail mode in the first place...
=> pacman.cpp: upgrade clubpacm and clubpacma to working

scripts/src/sound.lua, scripts/target/mame/ci.lua, src/devices/sound/flt_biquad.cpp, src/devices/sound/flt_biquad.h, src/devices/sound/hc55516.cpp, src/devices/sound/hc55516.h, src/mame/audio/exidy.cpp, src/mame/audio/exidy.h, src/mame/audio/s11c_bg.cpp, src/mame/audio/s11c_bg.h, src/mame/audio/williams.cpp, src/mame/audio/williams.h, src/mame/drivers/s11.cpp, src/mame/drivers/s11a.cpp, src/mame/drivers/s11b.cpp, src/mame/drivers/s11c.cpp, src/mame/drivers/williams.cpp, src/mame/includes/s11.h, src/mame/includes/williams.h, src/mame/machine/williams.cpp
* Split hc55516 core into separate cores/subclasses for hc55516 and hc55532 (new 'digital' implementation based on decap/die tracing) as well as mc3417 and mc3418 (old existing 'analog' implementation left alone) and hooked the hc55516 and mc3417 implementations to the appropriate hardware drivers. This should vastly improve CVSD sound quality in drivers that use the hc55516.[Lord Nightmare, Sean Riddle]
* Made Exidy's mouse trap use a timer to clock the mc3417 and update the state readable by the z80 rather than relying on the mc3417 to accept a clock parameter and update the z80 state via a callback. The timer implementation ensures proper synchronization and prevents missed clock transitions from the z80 side causing noise in the CVSD audio. [Lord Nightmare]
* Added a biquad-based 2nd …
=> Major update for HC55516 CVSD audio device and related filtering, as well as hooking it to drivers.

src/mame/drivers/nwk-tr.cpp, src/mame/mame.lst
This is an update for documentation as well as add some code from hornet.cpp's driver to correct the the whole "dual screen" situation. If anyone around here does have an nwk-tr system, it would be nice to know what the slave CG board displays on actual hardware.
My other changes:
- Added the second K001604. Since nwk-tr does use two CG boards, there should be a second K001604 as well. Also had to add additional read/write parameters to support using two K001604s for now.
- Updated network board documentation to better explain the chip at 2G, XICOR X76F041, and functions. Added NO_DUMP placeholders to the games that use this specific network board with the added eeprom.
- Renamed 'Thrill Drive (EAA) (thrilldae)' to 'Thrill Drive (EAB) (thrilldbe)' because the program rom used for this set …
=> Some nwk-tr changes

src/devices/machine/rescap.h
The exact authorship of a few of these definitions isn't quite clear, though @aaronsgiles had nothing to do with them as far as I can tell. I'm not sure how much credit other developers are willing to take for these, though, so I'll invite comments before merging.
=> rescap.h: Credit the actual authors (nw)

hash/fmtowns_flop.xml
- Documented the images that are known to be dumped from original disks, and if they are protected or not, so the non-protected ones can't be mistaken for cracked/hacked images.
- Added 4 new dumps (I re-formatted the commit message following Vas' recommendations, I hope it makes things easier):
Premium [r09]
Quiz Banchou [r09]
Shangrlia [r09]
Yajiuma Pennant Race 2 [r09]
=> fmtowns_flop.xml: 4 new dumps

scripts/target/mame/mess.lua, src/mame/drivers/betacam.cpp, src/mame/drivers/dfs500.cpp, src/mame/drivers/umatic.cpp, src/mame/layout/dfs500.lay, src/mame/mame.lst, src/mame/mess.flt
This is a followup to PR #7346 
This PR includes:
* New non-working driver: SONY DFS-500 DME Video Mixer (1994)
* New skeleton drivers for SONY VCRs: U-Matic vo5850PM and BETACAM-SP models UVW-1200, UVW-1600, UVW-1800
I've completely removed any use of the legacy `output().set_value` API calls and adopted `output_finders`, as suggested by @cuavas at https://github.com/mamedev/mame/pull/7346#issuecomment-710344184
Internal Artwork Layout:
External Artwork Layout: (hosted at https://github.com/felipesanches/dfs500_MAME_artwork):
=> SONY video equipment (DFS-500 Video Mixer and VCRs)

src/devices/video/315_5124.cpp, src/devices/video/315_5124.h
- Fix behavior of register 04 in mode 4
- Emulate behavior of register 03 in mode 4
- Disable sprite processing in mode 1 (text mode)
- Process legacy sprites in mode 3
- Split hcount and vcount calculations to separate functions to allow reuse for logging
- Rename some variables/functions to better represent their purpose
=> 315-5124: Registers 03 and 04 behavior in mode 4 [Enik Land]

src/devices/video/ppu2c0x.cpp, src/devices/video/ppu2c0x.h, src/mame/drivers/vsnes.cpp, src/mame/includes/vsnes.h, src/mame/machine/vsnes.cpp, src/mame/mame.lst
Based on kevtris' [schematics](http://blog.kevtris.org/blogfiles/vssmbbootleg.PDF) and [video](https://www.youtube.com/watch?v=g8gZT1F9UkE), these commits:
* get the two SN76489s connected and working (w/ the expected Z80 interrupt behavior when the 6502 writes sound registers)
* run the 6502, Z80, and both SN76489s at the correct clock speeds
* add a new PPU subclass `ppu2c04_clone_device` which implements the bootlegs' register behavior, palettes, video timing, and other differences
* mark the Z80 ROM in the `suprmriobl3` set as a bad dump due to corrupted return instructions in both interrupt handlers
I removed `MACHINE_NOT_WORKING` from sets 1 and 2 but left it on set 3 due to the bad Z80 ROM.
What I'm not sure about at the moment:
* Audio levels: I have both SN76489s at 50% right …
=> vsnes: working sound + "improved" graphics in Vs. SMB bootleg sets

src/devices/sound/msm5232.cpp
msm5232, a tone generator chip which is used by some early TAITO and Alpha Denshi arcade PCBs, has 'arm' flag that alters behaviour of envelope generation.
Basically, the 'arm' flag turns Attack-Decay-Release envelope generation to simpler ON/OFF states.
If the 'arm' flag set, the transition from Attack to Decay doesn't occur unless explicitly indicated.
On current implement, when this 'arm' flag is set on a channel which is on a Decay state, the Decay state continues.
It seems that, the state should be turned into a Attack state in this situation.
=> msm5232: fix: behaviour when the 'arm' flag set while envelope generator is on a decay state

src/devices/video/315_5313.cpp, src/mame/drivers/megaplay.cpp
A bit of a strange one this time, hopefully I can explain it well enough...
This fixes the "odd interlace frame" bit in the VDP status register so that it is only set if interlace is actually enabled. Believe it or not, this was actually the cause of the 68k/Z80 communications issues in Mega Play games that were causing the two CPUs to get confused about the current game state.
This appears to fix all of the sets in megaplay.cpp, but I'll use some 68k code from Sonic 2 as an example.
Every frame, the game checks the "odd frame" bit here, and sets/clears a flag in RAM accordingly:
```
ROM:000003AE                 move.w  ($C00004).l,d0
ROM:000003B4                 btst    #4,d0
ROM:000003B8                 beq.s   loc_3D0
ROM:000003BA                 move.b  #$40,($FFFFAE).l ; interlace …
```
=> fix a Genesis VDP status bit which was breaking Mega Play 68k->Z80 comms

src/mame/video/k001005.cpp
Added a missing command only used in jetwave's "How to Control" screen.  This screen would show some model of the jetski in turning the handlebars and leaning on the jetski for controls. This fixes an issue where not only the model(s) wouldn't be present but the game would slow down complaining about an unknown polygon command.
=> k001005.cpp: Add missing command

src/devices/video/snes_ppu.cpp, src/devices/video/snes_ppu.h
Fix CGRAM size, Direct color behavior
Reduce unnecessary values
=> snes_ppu.cpp: Use device_palette_interface for Palette handling

scripts/target/mame/mess.lua, src/mame/drivers/leapfrog_iquest.cpp, src/mame/drivers/leapfrog_leappad.cpp, src/mame/drivers/megadriv.cpp, src/mame/drivers/megadriv_acbl.cpp, src/mame/drivers/megadriv_rad.cpp, src/mame/drivers/megadriv_sunplus_hybrid.cpp, src/mame/drivers/megadriv_vt_hybrid.cpp, src/mame/drivers/megaplay.cpp, src/mame/drivers/megatech.cpp, src/mame/drivers/nes_clone.cpp, src/mame/drivers/nes_sh6578.cpp, src/mame/drivers/nes_vt02_vt03.cpp, src/mame/drivers/puckpkmn.cpp, src/mame/drivers/segapico.cpp, src/mame/drivers/spg2xx_zone.cpp, src/mame/includes/megadriv.h, src/mame/includes/megadriv_acbl.h, src/mame/includes/megadriv_rad.h, src/mame/machine/megadriv.cpp, src/mame/mame.lst, src/mame/mess.flt
-----
The New York Times Sudoku [David Haywood, Sean Riddle, Kamaal Brown]
Vs Maxx 25-in-1 (VT03 hardware) [David Haywood, Sean Riddle, Kamaal Brown]
6-in-1 Sudoku Plug & Play [David Haywood, Sean Riddle]
Plug 'N' Play 50-in-1 (DGUN-853) [David Haywood, Sean Riddle, Kamaal Brown]
-----
Mega Drive Collection Volume 2 (Radica, Arcade Legends) (UK) [David Haywood, Sean Riddle]
Super Sonic Gold (Radica Plug & Play) (UK) [David Haywood, Sean Riddle]
-----
Plug 'N' Play 25-in-1 (DGUN-806) [David Haywood, Sean Riddle, Kamaal Brown]
IQuest (US) [David Haywood, Sean Riddle, Kamaal Brown]
- Added MegaDrive side ROM to sarc110 sets, moved to skeleton 'hybrid' driver based on megadriv_rad.cpp and demoted to not working for now as …
=> Plug and Play work (lots of new sets from Sean etc.)

scripts/target/mame/mess.lua, src/devices/cpu/avr8/avr8.cpp, src/devices/cpu/avr8/avr8.h, src/mame/drivers/pensebem.cpp, src/mame/mame.lst
Equivalent to VTech Smart Start from the 80s (which was based on a Z8 MCU that I was not yet able to dump).
The TecToy Pense Bem (2017 release) emulated here is based on an Atmel ATMEGA168PB.
This driver is working almost perfectly, except for the sound. The sound portion of this device is very simple, actually: just a piezo buzzer controlled by a single bit being toggled by one of the AVR8 timers. The issue is that the specific timer mode in use was not yet implemented in MAME. I implemented it in the naive straightforward way but the performance is very very bad and I hear lots of noise. So I'd like to get some help on how to handle that.
=> new driver: TecToy Pense Bem (2017)

hash/fmtowns_flop.xml
Just a quick change to add Might and Magic: World of Xeen to the FM Towns floppy softlist. For some reason I completely forgot about this disk until now, even though it's been in the last release of the Neo Kobe Collection for about 4 years.
=> fmtowns_flop.xml: add the World of Xeen disk

src/mame/drivers/klax.cpp, src/mame/includes/klax.h
This PR gets the Klax bootleg sets working, including sound.
A few notes:
* I'm not sure if the audio frequency is correct. I used the standard 384kHz oscillators for both MSM5205s with the f/64 prescaler, but it's about two semitones lower than the non-bootleg sets.
* "6.ic22" from klax5bl2 might be a bad dump? It's the same as the version from klax5bl but with random bytes missing (mostly in the middle of ADPCM data, but also at the Z80 reset address)
* klax5bl3 is still "not working" since the audio CPU uses encrypted opcodes, but it's otherwise identical to klax5bl2.
=> klax.cpp: get bootleg sets working

src/mame/drivers/hp3478a.cpp, src/mame/layout/hp3478a.lay
-LCD has 12 text annunciators (1 segment each) which now work
-some buttons have an extra label printed above, for shift-functions
-generally improved the layout : parametrized some of the elements
actual unit : https://4.bp.blogspot.com/-o1K3h8qAfiM/WjWkJsYsCvI/AAAAAAAAGyc/3obboNUwozMB-paG8SheovOdWA5afCI3wCLcBGAs/s1600/cropped%2B3478A.jpg
=> hp3478a: layout: LCD annunciators, button labels

src/mame/drivers/model2.cpp, src/mame/drivers/model3.cpp
[Carried over from MT5701](https://mametesters.org/view.php?id=5701).
Need to document more which Model 2/3 games have changeable regions, might need to document Model 3 secret region change method in games that have it? ([Documented here](https://pastebin.com/ByiHRKKb), [archived from here which requires login](http://www.supermodel3.com/Forum/viewtopic.php?f=3&t=50))
=> model2.cpp, model3.cpp: Daytona USA/Scud Race description update per MT5701

src/mame/drivers/centiped.cpp, src/mame/includes/centiped.h, src/mame/video/centiped.cpp
This implements the address mirroring and configurable memory ranges used by the Multipede kit for switching games.
I also shortened the watchdog timeout in `centiped_base` to be similar to some of the other Atari drivers, since the kit relies on it to reset the system within a short period after switching games and raises an error if it doesn't.
=> centiped.cpp: support switching games in multipede

src/mame/drivers/centiped.cpp
This commit fixes an issue noticed in the replies to #7431 where some bootleg sets were missing watchdog writes because the watchdog wasn't actually included in the memory map. I also added `nopr()` and `noprw()` to a few address ranges to get rid of several error log messages (due to 6502 dummy reads, and vestigial code from the original ROMs trying to write to a nonexistent POKEY)
=> centiped.cpp: add watchdog reset address to bootlegs

src/osd/modules/debugger/debuggdbstub.cpp
A small addition in order to add support for the Motorola 6809 processor in the gdbstub.
Thanks
Gus
=> Add m6809 support for gdb remote debugger.

src/devices/cpu/tms7000/7000dasm.cpp
BTJO and BTJZ instructions, which use PC releative addressing would be off by one. Fix incorrect JPI mnemonic to be the correct JPZ.
=> cpu/tms7000: Fixed JPZ mnemonic and offsets for BTJO and BTJZ (inherent) in disassembly

hash/ibm5150.xml
blockout: Marked as bad dump (modified OEM ID and modified root)
=> ibm5150 - Blockout bad dump

src/mame/drivers/coco12.cpp, src/mame/drivers/coco3.cpp, src/mame/drivers/dragon.cpp, src/mame/includes/coco.h, src/mame/includes/coco3.h, src/mame/includes/dgnalpha.h, src/mame/includes/dragon.h, src/mame/machine/coco.cpp, src/mame/machine/coco3.cpp, src/mame/machine/dgnalpha.cpp, src/mame/machine/dragon.cpp
When adding a proper ACIA to the Dragon 64 driver it was requested to use an input merger to handle all the interrupt sources. This required changes all the way down to the base driver. 
Also fix small typo when handling the parallel port on the Dragon 32.
=> [coco] Remove IRQ trampolines from coco driver family

src/emu/drawgfxt.ipp
I think I catched a little typo/mistake in drawgfxt.ipp drawscanline_core.
=> Fix drawscanline_core leftover loop, should be outside unrolled loop

src/devices/cpu/m68000/m68kfpu.cpp
SysV Unix kernel on hcpu30 uses these modes:
Fatal error: M68kFPU: FSAVE unhandled mode 6 reg 7 at f854
=> m68k: accept addressing mode 6 for FSAVE/FRESTORE

src/mame/drivers/sauro.cpp
The newly dumped set has the "Test mode" bug which causes a crash when "Difficult" is selected via dip switches fixed, so it's (probably) newer.
=> sauro.cpp: Switch 'Set 1' and 'Set 2' to make the newly dumped set the parent one

src/mame/drivers/segas16a.cpp
Needed for moving platforms in stage 15, see https://mametesters.org/view.php?id=7792
again I think this is a case of 'has never worked in MAME' because the old protection sims didn't do this either
=> allow 8751 MCU to access tile ram as well as text RAM on the pre-system16 boards (Quartet / Quartet 2)

src/mame/drivers/starshp1.cpp, src/mame/video/starshp1.cpp
Fixed a bug where there was garbage on the screen from extra unitialized ram being drawn on the screen.  The ram region here is only 256 bytes - and it is drawn at the top of the screen only, by the hardware.  I was surprised that drawing a smaller tilemap defaults to drawing to the entire screen, so I made a special cliprect.  Please let me know if I am missing something fundamental about cliprects and tilemaps.
=> starshp1: Fix tilemap size, get rid of uninitialized chars on screen

src/devices/bus/coco/coco_ssc.cpp, src/devices/bus/coco/coco_ssc.h
This game requires very specific status values after a reset. The speech chip was incorrectly being reset too soon in the process. The logging system was modernized. The device busy delay timer was unneeded, so removed. Tested with BASIC commands from manual, Pitfall 2, and PandPR.
=> coco_ssc.ccp: fix speech in Pegsaus and the Phantom Riders

src/devices/bus/coco/coco_multi.cpp, src/devices/bus/coco/cococart.cpp, src/devices/bus/coco/cococart.h, src/mame/drivers/coco12.cpp
1. Consolidated CoCo cartridge slot device configuration, to remove duplicate code that was specific to slots on the Multi-Pak interface.
2. Marked "pak" and "banked_16k" as internal, as they are not standalone
=> Cleanups and corrections for CoCo cartridge slot configuration

src/mame/drivers/cosmic.cpp
Some cleanup to sample playback for cosmica - remove some redundant calls, and turn the questionable `[[fallthrough]]` into a `break`
=> cosmic.cpp: Fixed bug in sound output handler and cleaned up sample playback code

hash/fmtowns_cd.xml
Collector D - Bangai-hen - Gokurakudai Nishichiku Sales Daisakusen
[redump.org]
Eikan wa Kimi ni 2 - Koukou Yakyuu Zenkoku Taikai (HMC-144) [redump.org]
Gokichi-kun Series - Igo Nyuumon Doujou [redump.org]
Hiragana no Ehon [redump.org]
Hirou [redump.org]
Hyper Planet Shiki Vol. 1 [redump.org]
Igo II (HMA-219) [redump.org]
Joshikousei Shoujo Densetsu - Cosplay Special [redump.org]
Mahjong Gensoukyoku II - Mahjong Fantasia [redump.org]
Mahjong Gensoukyoku III - Mahjong Fantasia the 3rd Stage [redump.org]
NHK Jissen Eikaiwa (HMC-120A) [redump.org]
Soft de Hard na Monogatari [redump.org, wiggy2k]
Soft de Hard na Monogatari 2 [redump.org, wiggy2k]
Vampire High School [redump.org] …
=> fmtowns_cd.xml: 20 new dumps, 35 replacements, add msdet2 floppy

src/osd/modules/file/posixfile.cpp
Tracked by ticket:
https://github.com/mamedev/mame/issues/7536
=> Mame: Fix compilation error on older MacOS/Xcode releases, for file 'src/osd/modules/file/posixfile.cpp'

src/mame/drivers/neptunp2.cpp
It was previously dumped half its size
=> neptunp2.cpp: Redumped 'unk960606' sound ROM

src/devices/machine/t10mmc.cpp
An incorrect value is returned as the relative CD address when the MSF bit is set since it subtracts the LBA track start position from the MSF position here.
This fixes note scrolling in Keyboardmania, Keyboardmania 2nd Mix, and Keyboardmania 3rd Mix and anything else that relies on the relative MSF position.
=> t10mmc: Fix calculating relative value in T10MMC_CMD_READ_SUB_CHANNEL

hash/fmtowns_flop.xml
Also added more information about all the Futoppara coverdisks, and some notes about images known to be dumped from originals.
Dinosaur [r09]
Dragon Knight 4 Special Disk [r09]
Futoppara FD Heisei 1-gou [r09]
F-BASIC86HG Interpreter/Compiler V1.2 L31A [anonymous]
F-BASIC86HG Interpreter V1.2 L31A [anonymous]
Oh! Pai [akira_2020]
Jissen Igo Taikyoku - Gokichi-kun - Chuukyuu (Jou) [wiggy2k]
=> fmtowns_flop.xml: 7 new dumps

src/mame/drivers/firebeat.cpp
Originally the CPU was implemented as 66 MHz but was changed from 66 MHz to 64 MHz in a commit 8 years ago. At 64 MHz, the music notes gradually get more and more off time as the song progress. Setting it back to 66 MHz fixes the timing issues.
For reference, the datasheets for the PowerPC 403GCX that I could find list the CPU frequencies as 50 MHz, 66 MHz, and 80 MHz.
http://www.icbase.com/pdf/IBM/IBM01670106.pdf
[note] I am not familiar with this driver/hardware so I am not comfortable making the change myself, but the only other usage of the PowerPC 403GCX that I could find also uses a suspicious clock speed.
ref: https://github.com/mamedev/mame/blob/master/src/mame/drivers/konendev.cpp#L410
=> firebeat: Change clock speed from 64 MHz to 66 MHz

src/devices/bus/coco/coco_fdc.cpp, src/devices/bus/coco/coco_multi.cpp, src/devices/bus/coco/cococart.cpp, src/devices/bus/coco/cococart.h, src/devices/machine/wd_fdc.cpp, src/mame/drivers/coco3.cpp
The PIA mirroring uses fewer addresses than the CoCo 1 & 2. This agrees with Tepolt (Table 7-1) and a oscilloscope testing.
I also added some more granular logging in the cartridge interrupt system to help track this issue down.
=> Adjust CoCo 3 PIA mirrors

hash/next_hdd.xml, src/mame/drivers/next.cpp
Add a software list with preinstalled disk images for NeXT. I've tested these with the `next` machine and tagged the non-working ones as such. The images come from https://archive.org/details/NeXTOSIMAGES
=> next_hdd: initial hdd software list for next

src/mame/drivers/next.cpp, src/mame/includes/next.h
Refactor the driver to only include the MO drive for NeXTcube systems. NeXTstation systems didn't ship with the MO, and I don't see any way they could have used it either. I've also added a couple of helper functions to try and minimize duplication.
=> next: only NeXTcube systems used the MO drive

src/mame/drivers/next.cpp
Add ROM definitions from http://www.nextcomputers.org/NeXTfiles/Software/ROM_Files/ for:
rev_0.8_v31.bin
rev_1.0_v40.bin
rev_1.1_v42.bin
rev_2.0_v58.bin
rev_3.1_v71.bin
and add a missing labels for the existing matching ROMs:
rev_3.0_v70.bin
rev_3.2_v72.bin
rev_3.3_v74.bin
=> next: add some more roms

src/mame/drivers/next.cpp
As this is debugging output, I think it should go the log instead of being printed unconditionally. The only entry that actually matters here is the `ramdac_w` one, but I've updated the others too for consistency, even if they're just comments for now.
=> next: use logerror instead of printf

src/mame/drivers/firebeat.cpp, src/mame/drivers/gunpey.cpp, src/mame/drivers/konamim2.cpp, src/mame/drivers/realbrk.cpp, src/mame/drivers/tecmosys.cpp, src/mame/drivers/vgmplay.cpp, src/mame/drivers/zn.cpp, src/mame/includes/zn.h
these seem to be the only place it's used in a multi-chip setup.
calcune.cpp does have the genesis PSG sound on the VDP, but makes no use of it
suprnova.cpp was highlighted to me but the only MSM is the RTC?
in most cases volume levels of other chips have been reduced, although for vgmplay.cpp I just bumped the YMZ up, as there seems to be no other practical way to handle that
zn.cpp is the only one that required a header file changing (to add m_spu) and only hvnsgate + cbaj use the ymz, so spu levels were dipped for just the atlus config.
=> rebalance sound after ymz280b change

src/tools/imgtool/filtbas.cpp
They were copied from Color Disk BASIC. This corrects the tokens to use actual values.
=> imgtool/dragondos: fix disk BASIC tokens

hash/gamegear.xml, hash/sg1000.xml, hash/sms.xml
gamegear:
- Redumped Sports Illustrated Championship Football & Baseball (Euro, USA) [smspower]
gamegear:
Andre Agassi Tennis (prototype),
Bubble Bobble (prototype),
CJ Elephant Fugitive (prototype),
Dinobasher Starring Bignose the Caveman (prototype),
Dragon - The Bruce Lee Story (prototype),
Empire Syndicate (Chicago Syndicate) (prototype, 19950320),
Kawasaki Superbike Challenge (USA),
Micro Machines (prototype)  [smspower]
sg1000:
San-nin Mahjong (Jpn, alt)  [smspower]
sms:
3D Gunner (prototype),
Alex Kidd - High Tech World (prototype),
Battle Wings (Bomber Raid, prototype),
Cyborg Hunter (prototype),
Game de Check! Koutsuu Anzen (Jpn, prototype)
Hang-On (prototype),
Missile Defense 3-D (prototype),
Out Run 3-D …
=> gamegear, sg1000, sms software list additions

src/devices/cpu/tlcs900/dasm900.cpp
This fixes PC-relative addressing in the TLCS900 disassembler to calculate the absolute address correctly. Since `pos` is already derived from `pc`, adding them both to the offset in the instruction results in a displayed address that's slightly over double what it actually should be.
=> tlcs900: fix disassembly of PC-relative addressing

scripts/target/mame/mess.lua, src/devices/machine/1ma6.cpp, src/devices/machine/hp_dc100_tape.cpp, src/devices/machine/hp_dc100_tape.h, src/devices/machine/hp_taco.cpp, src/devices/machine/hp_taco.h, src/lib/formats/hti_tape.cpp, src/lib/formats/hti_tape.h, src/mame/drivers/hp2640.cpp, src/mame/drivers/hp9845.cpp, src/mame/machine/hp2640_tape.cpp, src/mame/machine/hp2640_tape.h, src/mame/machine/hp9825_tape.cpp, src/tools/imgtool/modules/hp85_tape.cpp, src/tools/imgtool/modules/hp9845_tape.cpp
Hi & happy new year!
With this PR I'm adding the emulation of DC100 tape drives to HP264x terminals.
I extended the HTI format to handle the Manchester-encoded data of these terminals (previously HTI format only supported delta-distance modulation of HP9845,9825 & 85 systems).
Thanks.
--F.Ulivi
=> HP2640: added tape emulation

src/devices/machine/jvsdev.cpp, src/devices/machine/jvsdev.h, src/mame/drivers/ksys573.cpp, src/mame/machine/k573mcr.cpp, src/mame/machine/k573mcr.h
This is a software implementation of the JVS memory card reader device used by System 573. This allows for saving and loading scores in DDR games, loading custom edit chart data in DDR and Guitar Freaks games, and PS1 guitar controller inputs in Guitar Freaks games.
I've included packet captures for every implemented commands and the corresponding responses in the code for documentation purposes. If it's too much or not required then I can remove them.
The following games are affected:
```
ddr2mc2
ddr2ml
ddr2mla
ddr3mka
ddr3ma
ddr3mk
ddr3mj
ddr3mp
ddr4m
ddr4mj
ddr4ms
ddr4msj
ddr4mp
ddr4mps
ddr5m
ddrmax
ddrmax2
ddrextrm
gtrfrk3m
gtfrk3ma
gtrfrk4m
```
All of the above have been tested to make sure that the memory card and controller functionality is working. I've also tried to test as much …
=> k573mcr: Implementation of JVS memory card reader device for System 573

3rdparty/minimp3/minimp3.h, 3rdparty/minimp3/minimp3_ex.h, src/devices/sound/mas3507d.cpp, src/devices/sound/mas3507d.h, src/emu/devfind.h, src/mame/machine/k573dio.cpp, src/mame/machine/k573dio.h, src/mame/machine/k573fpga.cpp, src/mame/machine/k573fpga.h
This PR is an attempt to improve accuracy of the System 573's digital I/O audio emulation. 
I noticed only 2 other devices in all of MAME even use STREAM_SYNCHRONOUS and I realize there's performance hit involved with its usage so I will offer a justification for its usage here. If there are other options besides STREAM_SYNCHRONOUS that would allow for accurately tracking playback at the sample level without the performance hit then I'd love suggestions.
The biggest issue currently with the k573dio/fpga emulation is audio buffering. The current sample counter implementation relies on the buffered sample counts: `u32 get_frame_count() const { return total_frame_count - buffered_frame_count; }`.
With this implementation, the sample counter increments in fixed intervals whenever the buffer …
=> Improve accuracy of System 573's digital I/O audio emulation

hash/fmtowns_cd.xml
In addition to everything below:
- Added a floppy disk included with Crystal Rinal [cherokee]
- Replaced the Bible Master floppy disk with a cleaner copy [wiggy2k]
Air Warrior V1.2L11 [redump.org, wiggy2k]
Emit Vol. 1 - Toki no Maigo (Demo) [redump.org]
Engage Errands - Miwaku no Shito-tachi [redump.org]
Engage Errands II - Hikari o Ninau Mono [redump.org, wiggy2k]
Hyper Planet Shiki Vol. 2 [Maddog]
Kikai Jikake no Marian [rockleevk]
Last Armageddon CD Special (Selon reprint) [redump.org]
Lua [redump.org]
Naru Mahjong [redump.org]
Nijiiro Denshoku Musume [redump.org]
Princess Danger [rockleevk]
Tactical Tank Corps DX [redump.org]
Tensen Nyannyan [redump.org]
Winning Post [redump.org]
WonPara Wars [redump.org]
New not …
=> fmtowns_cd.xml: 16 new dumps, 13 replacements, 6 missing floppies added

src/mame/video/k057714.cpp, src/mame/video/k057714.h
Screenshots included for easy comparison since the games shown here have the worst issues but aren't bootable in upstream yet.
I've also checked against the following games for regressions:
```
kbm
kbm2nd
kbm3rd
ppp1mp
```
The konendev device also uses this chip but has not been tested.
Not shown but fixed: full screen framebuffer alpha blending. This is used to transition the entire screen and can be seen, for example, when choosing a song (fades to black and then fades into the song loading screen). Also used in the boot sequence screens (for example in pop'n music 8) to transition between boot screen.
---
Clipped pixels around edges as well as general viewport dimension issues. The before shows too much width which displays the next framebuffer on the right side, and the bottom pixels …
=> k057714: Implement display resolution register and various fixes to drawing

src/mame/drivers/jpmimpct.cpp, src/mame/drivers/jpmimpctsw.cpp, src/mame/includes/jpmimpct.h, src/mame/mame.lst
jpmimpact.cpp / jpmimpactsw.cpp progress on non-video fruit machines [David Haywood]
- Hopper tweaks to allow many more sets to boot
- Return 0xffff from some unknown memory addresses to allow later games to boot (security / anti-tamper?)
- Better per-game defaults to allow more sets to boot
- Alt reel configs for a handful of ACE games to allow them to boot
- Remove a few bad dumps
- Correct ROM loading on several sets
- Fix up manufacturer information for several sets
- Use timed coin optos for coins so that they insert reliably without triggering scam detection
- Started adding per-game input configurations
- Various notes / observations based on behavior to identify where improved hookups are still needed
- Added myself as copyright holder as I've made significant changes to the …
=> jpmimpact.cpp / jpmimpactsw.cpp progress on non-video fruit machines [David Haywood]

src/devices/machine/intelfsh.cpp
This is a hack. The Fujitsu 29F016A datasheet specifically states "data polling must be performed at an address within any of the sectors being erased" whereas Konami is polling outside of the sectors.
All of the following information is based off pop'n music 6 in the Firebeat driver.
When initializing the flash memory, the following sequence of commands are issued in the following order:
1. Chip clear command issued, polling sector 0 until it's finished
2. Sector 0 clear command issued, polling sector 0 until it's finished
3. Sector 1 clear command issued, polling sector 0 until it's finished
4. Sector x clear command issued (looped until entire chip is erased again), polling sector 0 until it's finished
The polling code reads the first two bytes of the sector and XORs them together. The …
=> intelfsh: Force fujitsu_29f016a to return status bits during clearing regardless of sector

src/devices/sound/rf5c400.cpp, src/devices/sound/rf5c400.h
This is the fix mentioned in https://github.com/mamedev/mame/pull/7693 that is required for pop'n music and beatmania III to work properly.
pop'n music Mickey Tunes (Firebeat)
beatmania III THE FINAL (Firebeat)
beatmania IIDX 7th Style (Twinkle)
- Will set loop offset to somewhere in the range between start and end when it wants to actually loop somewhere
- Will set the loop offset to 7 when it does not want to loop (= just loop tail end of sample until the channel is stopped?)
- (Firebeat only) Will set the loop offset higher than the buffer length when it wants to loop back to the beginning of the buffer. This mode seems to be used in conjunction with rf5c400_r 0x09 using the rf5c400's playback offset to determine the appropriate timing for DMA updates.
--- 
Gradius 4 (Hornet)
Teraburst …
=> rf5c400: Fix looping, implement new register

makefile
This fixes arm build breakage introduced by 6e1bbe8be89349038995df2aaa4f11019439e39e.
=> Unbreak aarch64 and arm builds

docs/source/commandline/commandline-all.rst, docs/source/initialsetup/compilingmame.rst, docs/source/techspecs/layout_script.rst, docs/source/usingmame/usingmame.rst
Need a specific review on compilingmame.rst line 205, though.
=> Change "mame64" to "mame" in docs

src/devices/bus/ata/atapicdr.cpp, src/devices/bus/ata/atapicdr.h, src/mame/drivers/firebeat.cpp, src/mame/video/k057714.cpp
There are two SPU configurations implemented here:
- pop'n music which uses DVDs
- beatmania III which uses HDDs
This PR allows for all pop'n music games to be booted but some things will not work properly without further changes to rf5c400 which will come in a future PR. beatmania III HDD issues are also partially fixed by this PR.
Other changes:
firebeat: Documented some unknown ports including dipswitches (verified positions using PPP and beatmania III)
firebeat: Swapped sound channels (tested in various Firebeat games, I think it was PPP that even showed you "left", "center", "right")
k057714: Set an initial display width and height. This fixes some visual glitching for games that don't set the display size manually (beatmania III).
k057714: 44130d5dd9aca78ac2fba84c2cc05f8653be6f35 …
=> firebeat: Implement SPU DMAs and fix SPU device configurations

src/mame/drivers/viper.cpp, src/mame/mame.lst
Previously this game would error out immediately with a security check error due to the placeholder `ds2430.u3`. I've generated working dongles that will allow the games to boot as retail (non-rental type cabinet) JAA (Japan region) and AAA (Asia region) region codes. These are generated (not real dumps) so they are both still marked as `BAD_DUMP` to be sure. `ppp2nda` uses the same data as `ppp2nd` except the dongle tells it to boot AAA region instead of JAA. JAA will be in Japanese, AAA will be in English. Since it is the only way to play in English I included it as a separate game entry.
Sensor mappings worked the same as Firebeat so I just copied those over and added the read handler. I gave it a quick test in-game and all buttons including the sensors respond as expected in the I/O …
=> viper: Add new dongles for ppp2nd (JAA), add new game ppp2nda (AAA) as MACHINE_NOT_WORKING, and add ppp2nd/a IO

src/devices/bus/cpc/cpc_rs232.cpp
The COMMSTAR ROM software won't run due to the ring indicator bit 4 of the DART RR0 being high when it's expected to be 0. 
If line 55 is uncommented bit 4 is low as expected and the software runs.
I've tried a few different pieces of mid 80's comms software and all is good.
Reading between the lines of forum posts back in 2014. It seems that the z80 dart emulation has been improved since then and I think now's the time to reinstate that line. 
The routine in cpc_ser/COMMSTAR1.ROM that reads the z80 dart RR0 are:
```
LD      BC,&FADD                ;;F102:   ...     01 DD FA
LD      A,&18                   ;;F105:   >.      3E 18
OUT     (C),A                   ;;F107:   .y      ED 79
LD      A,&10                   ;;F109:   >.      3E 10
OUT     (C),A                   ;;F10B:   .y …
```
=> Reinstated RI Handler

src/devices/machine/applefdintf.h
**apple2gs** has just switched to the new IWM implementation.  This patch adds floppy drive sounds to it.
=> apple2gs: added floppy drive sounds (for new IWM implementation)

src/osd/modules/debugger/debuggdbstub.cpp
Simple edit to [debuggdbstub.cpp](https://github.com/mamedev/mame/compare/master...nabetse00:feat-m68000-gdbstub?expand=1#diff-f41329a6fe0bf2bb7c7cf98de36374f1f1e825a637f765277c3495c420fc2c5a) adding m68000 cpu support.
Tested with prebuilt Windows Toolchain for m68k-elf from [here](https://gnutoolchains.com/m68k-elf/).
It Works with minor issues:
-  mame window cannot be moved util gdb connects and starts the emulation.
-  m68-elf-gdb complains about fpcontrol register not present (megadrive/genesis 68000 has no floating point capabilities)
-  Sometimes gdbstub stops to respond (maybe a problem from my test rom) nevertheless wathchdog option solves this.
Command line used (mame compiled from source with standard build mame build tools for windows):
```
.\mame.exe megadriv -cart …
```
=> add m68000 to debuger gdbstub

src/mame/drivers/gfamily.cpp
We've used different tools to create the CHD from the Norton Ghost image, as the previous conversion had corruption issues.
=> gfamily.cpp: Redumped HDD [ICEknight]

src/mame/drivers/raiden_ms.cpp
This couple of commits fixes up main-to-sound-CPU communication and a few details of YM and ADPCM writes from the sound CPU so that music and sound effect playback get triggered correctly.
The FM audio still doesn't sound _great_, but it's at least functional.
=> raiden_ms.cpp: sound improvements

src/mame/drivers/firebeat.cpp, src/mame/mame.lst, src/mame/video/k057714.cpp, src/mame/video/k057714.h
This is a large refactor of the Firebeat driver as discussed in #7693 so please forgive me for the huge PR with a meaningless diff. I've tried to make note of anything below that I've changed during the refactoring that wasn't just structural refactoring.
All games on the Firebeat platform except those with missing HDD data (`bm36th` and `bm3core`) have been tested to make sure they are still booting into gameplay and inputs responding as expected.
All of the required new ROMs for this PR have been sent to `code ( at ) mamedev`.
NOTE: Even with this PR, pop'n music *will not* boot as-is currently due to lack of support for the DVD CHDs. The CHDs are made as HDD CHDs which can't be loaded by the CD-ROM emulation code. The pop'n music games will work if you extract the raw data from the …
=> firebeat: Large refactor + initial beatmania III support

src/mame/drivers/ksys573.cpp
Previously unimplemented and barely used. Doesn't seem to have any real noticeable differences.
=> ksys573: Add ATA CS1 to memory map

hash/gamegear.xml
Rename: [suprjedi] Super Return of the Jedi (Euro, USA) -> Super Star Wars: Return of the Jedi (Euro, USA)
(information source: https://segaretro.org/Super_Star_Wars:_Return_of_the_Jedi)
=> gamegear - Updated description

hash/fmtowns_flop.xml
A bit more of an explanation for this update:
- The "cracked" entries were created recently by cyo.the.vile himself. The protected versions work in MAME, but these can be useful for people that want to write the images back to real disks, or use them in other emulators.
- The "toshintoa" clone of Toushin Toshi has been removed, since dumping one more copy of the game has revealed that the "alternate" version of disk B just had an additional file created long after the release of the game that wasn't present in the original unmodified disk. Also, disks A and E have been replaced with clean unmodified copies.
Cameltry (cracked) [cyo.the.vile]
Columns (cracked) [cyo.the.vile]
Lord Monarch [cyo.the.vile]
Nonomura Byouin …
=> fmtowns_flop.xml: 4 new dumps, 1 replacement

hash/fmtowns_flop.xml
Just a quick fix for a copy-paste mistake I made with the last update. Thanks to @Tafoid for spotting this.
=> fmtowns_flop.xml: fix lordmon sha1

src/devices/sound/cdda.cpp
Older System 573 Dance Dance Revolution and Guitar Freaks/Drummania games used CDDA audio and relied on the CDDA position for timing and animations. Buffering additional sectors forces the LBA position to also increase an equal amount causing the CDDA position to not be what the game expects. In DDR's case, animations become really choppy. In GFDM's case, the game will just stop playing the song and end the stage early.
Fixes: https://mametesters.org/view.php?id=7856
Not mentioned on mametesters: `drmn`, `drmn2m` and probably other early Guitar Freaks games were also bugged. Instead of playing the song, it would start off playing the song, slow down immediately, and then after a second or two the song would end. This change also fixes those issues.
=> cdda: Return LBA position as currently playing LBA

src/mame/drivers/firebeat.cpp
Tracked down a bug when using debug dongles in pop'n music to the IN1 register. There's no spots for an extra set of dipswitches on the main CPU from what I can tell. The functionality is only when debug dongles are in use so I think there may be something extra on the I/O port but I don't really know. 
I couldn't find any usages outside of pop'n music for IN1. I documented the known usages as PORT_BITS in the popn section.
Additionally, I added some information about main PCB dipswitches that has been newly discovered.
=> firebeat: Fix IN1 value, add new documentation about dipswitches

docs/source/debugger/watchpoint.rst, docs/source/techspecs/luareference.rst, src/emu/debug/debugcpu.cpp, src/emu/debug/debugcpu.h, src/emu/debug/points.cpp
This patch adds a variable to the watchpoint engine that exposes the size (in bytes) of the read or write. Among other things, this makes it possible to use a watchpoint script to dump a log of every I/O operation.
=> Add 'wpsize' variable to access the data size from a watchpoint

src/mame/drivers/twinkle.cpp, src/mame/mame.lst
Updates twinkle.cpp with data from my personal collection:
- Dongle dumps for 2nd style through 8th style. 4th and 5th were not marked "BAD_DUMP" but had serial "123456" which was clearly handcrafted, so I replaced those with actual dumps as well. These have all been tested.
- All missing HDD and CD images added. These have all been tested.
- CD images marked "BAD_DUMP" updated with fresh dumps. These have all been tested.
- With the inclusion of the rest of the data, all of Substream through 8th style can be promoted to "WORKING". I've removed the "MACHINE_NOT_WORKING" designation on mixes that had them. I've tested all mixes to verify they boot to attract sequence.
- Three new working variants (Substream Export/Asia version, 3rd Style B revision, 7th Style B revision) added and tested. …
=> twinkle.cpp: All Missing CD/HDD Data, 3 new working variants

src/mame/drivers/twinkle.cpp
IRQ1 is used for timing certain SPU events such as fading in and out menu music, with the way this was set up before it never got asserted because I guess you can't have multiple periodic IRQ's?
This fixes the menu music and some sound effects not fading out properly.
=> twinkle.cpp: Removed periodic source for IRQ2

src/mame/drivers/galaxian.cpp, src/mame/drivers/quasar.cpp, src/mame/drivers/tecmo16.cpp, src/mame/includes/tecmo16.h, src/mame/video/1943.cpp
tecmo16.cpp - improve IRQ ack mechanism (fixes riot from corrupting at the end of stage 1 and locking up on stage 2 while not breaking fstarfrc either)
1943.cpp - fix drawing past spriteram (was randomly causing bad sprite bottom left of screen)
galaxian.cpp - fix typo on manufacturer of anteateruk in galaxian.cpp
quasar.cpp - flip 'freeplay' settings, 'off' was not reducing credits after a game, while 'on' was
=> tecmo16.cpp - improve IRQ ack mechanism + 1943.cpp - fix drawing past spriteram + galaxian.cpp - typo fix

src/mame/drivers/apple2gs.cpp
=> apple2gs: don't segfault when floppy drive disabled

src/mame/drivers/coco12.cpp
This fixes Mame Testers bug #07701.
=> coco: Set proper tri-state value for keyboard PIA port B

hash/megadriv.xml, src/devices/bus/megadrive/eeprom.cpp, src/devices/bus/megadrive/eeprom.h, src/devices/bus/megadrive/md_carts.cpp, src/devices/machine/i2cmem.cpp, src/devices/machine/i2cmem.h
Note, not for inclusion in merge: It would be appreciated if someone could take the time to verify that Dodge Danpei, Evander Holyfield's Boxing, Greatest Heavyweights of the Ring, and Sports Talk Baseball are fixed, and update the table in eeprom.cpp accordingly. I cannot stand sports games, and the gameplay is opaque enough that it's not immediately obvious at what point a given game can be saved.
=> -i2cmem: Added Xicor X24C01 support. [Ryan Holtz]

src/mame/drivers/apple2gs.cpp
The z8530 baud rate generator works a whole lot better when the speed is configured.
[IIgs tech note #30](http://www.1000bit.it/support/manuali/apple/technotes/iigs/tn.iigs.030.html)
> The SCC's Receive/Transmit Clock (/RTxC) inputs for both ports are driven by a single crystal oscillator circuit. This is accomplished by connecting a 3.6864 MHz crystal between the /RTxC and Synchronization (/SYNC) input of port A. Port B's /RTxC pin is connected to port A's /SYNC pin to drive port B's clocks from port A's oscillator circuit. Because of this single circuit, Write Register 11 (WR11) bit 7 must be set to 1 for SCC port A and must be set to 0 for SCC port B. The SCC itself is clocked at 3.58 MHz by the Apple IIgs' Color-Reference clock (CREF) at the SCC's PCLK clock input. The maximum …
=> apple2gs: configure scc channel speeds

src/devices/bus/coco/coco_fdc.cpp
Add a call to super in bus/coco/fdc: coco_fdc_device_base::device_start()
=> bus/coco/fdc: call super device start in subclass

src/mame/drivers/coco3.cpp, src/mame/drivers/dragon.cpp
This finally fixes https://mametesters.org/view.php?id=7701
=> coco3, dragon: Add tristate value of 0xff to the first PIA

src/devices/bus/coco/cococart.cpp
Change name of Games Master Cartridge on a CoCo driver to match what it is called in the Dragon drivers: gmc.
=> coco: normalize name of GMC cartridge

src/lib/util/cdrom.cpp, src/lib/util/cdrom.h, src/mame/drivers/fmtowns.cpp, src/mame/machine/megacdcd.cpp, src/mame/machine/pce_cd.cpp, src/mame/machine/psxcd.cpp
Stumbled on a related bug with the way pregap is added to the TOC while trying to fix CDDA audio issues in Firebeat and System 573.
MAME vs Duckstation (both using the same CHD):
Results on real PS1:
Results with this patch applied:
I came up with a simple test program that uses `CdGetToc` and `CdPosToInt` to display the reported MSF and LBA values. Although this change will affect everything that uses cdrom.cpp, I chose the PS1 emulator for testing because I am able to reproduce the bug I'm hunting down using the PS1's CD player functionality in the BIOS.
Testing method for MAME and Duckstation:
1) Load test program cdtester.chd
2) Change disc using file menu from cdtester.chd to a different CHD, in this case a custom CHD named 845jba02.chd
3) Press button which calls `CdGetToc` and …
=> cdrom: Return index 1/start of track data instead of index 0/start of pregap data

src/mame/drivers/seibuspi.cpp
in SXX2D, JP121 is for mono/stereo sound output select, there's no jumper for cartridge change/flashing.
reference: Japanese SPI motherboard manual from http://ikotsu.blogspot.com/2010/01/raiden-fighter-jet-seibu-spi-jet.html
=> seibuspi.cpp: Fix document based from hardware manual

.github/workflows/ci-windows.yml
As an example, here's the improvement for ``liboptional.a``
Standard ar:
```
Tue, 30 Mar 2021 15:52:58 GMT Archiving liboptional.a...
Tue, 30 Mar 2021 15:54:22 GMT Compiling src/mame/mame.cpp...
```
With llvm-ar:
```
Tue, 30 Mar 2021 15:54:15 GMT Archiving liboptional.a...
Tue, 30 Mar 2021 15:54:19 GMT Compiling src/mame/mame.cpp...
```
=> Use llvm-ar for CI

src/osd/modules/lib/osdobj_common.cpp, src/osd/modules/sound/direct_sound.cpp, src/osd/modules/sound/xaudio2_sound.cpp
Currently with MAME 0.230, if `audio_latency` of 0 is specified then you will get the error `Out-of-range integer value for audio_latency: "0" (must be between 1 and 5, inclusive); reverting to 2` after https://github.com/mamedev/mame/commit/d578fa07444ef8744e9c2c569b49ab1ca0ed11a3 which re-enabled validations.
pasound uses `audio_latency` = 0 to mean "very-low-latency" mode: https://github.com/mamedev/mame/blob/30371b5717b3aa88da7f3d19235821f7eca0d429/src/osd/modules/sound/pa_sound.cpp#L264-L273
CoreAudio and SDL already clamp to 1-5. DirectSound and XAudio2 don't do anything but their calculations would probably break if set to 0 so I've added code to clamp those to 1 as well.
=> Change audio_latency valid range from 1-5 to 0-5

src/mame/drivers/fmtowns.cpp
The changes in commit 2caa566f22606682ee432c410d40376335e12b02 have exposed an existing miscalculation that is currently causing a few Data West games (psydet3/4, shamhat, maybe others) to hang at the initial logo.
Basically what's happening is: the "play CDDA" CD controller command uses the start point and end point as parameters, but MAME's CDDA device needs the total amount of sectors to play, so the "end LBA - start LBA" calculation makes it stop one sector before it should. This change fixes it by adding 1 to the total.
=> fmtowns: fix off-by-1 calculation in CDDA length

scripts/genie.lua
A `vs2019_clang` build is quite a bit faster than `vs2019`, so it has value too. From my observations, the speed of `vs2019_clang` is the same as of a GCC build, while its size is _more than twice_ smaller.
=> Fix vs2019_clang build

hash/fmtowns_cd.xml
- Added the missing floppy images to Igo Doujou, Air Warrior V1.2L10 and Suikoden - Tenmei no Chikai [cyo.the.vile]
- Added the missing floppy image to Viper GTS [wiggy2k]
- Replaced the Alice no Yakata II, Europa Sensen and Hiouden II images with cleaner unmodified copies [wiggy2k]
- Removed outdated comments and changed some serials and disk labels to reflect their actual names
Dalk (alt floppy disk) [redump.org, wiggy2k]
Kazadama Vol. 2 - Masuo per Masuo - Ikeda Masuo Hanga-shuu [redump.org]
Kouryuuki [redump.org, wiggy2k]
Kusuriyubi no Kyoukasho [redump.org]
Psychic Detective Series Vol. 4 - Orgel (DCCS remake) [redump.org, cyo.the.vile]
Remember Beatles No. 2 - Michelle [redump.org]
Remember Beatles No. 4 - Let …
=> fmtowns_cd.xml: 14 new dumps, 16 replacements, 4 missing floppies added

src/devices/bus/megadrive/svp.cpp
Related to https://github.com/mamedev/mame/issues/7910
This PR adds a bit of technical detail on the internal ROM that I found in the SVP chip on what parts of it are actually used during the boot-up process of Virtua Racing. Also I fixed the addresses where this ROM should be in the internal memory map. (Note: I don't have the means to test this thoroughly right now, but I think that moving the start address for the ROM loading should do the trick).
I'm not sure if there's any process that it's distinguishing between internal and external views from the DSP to the ROM space (i.e.: when accessing ROM space from external registers you should see the actual game ROM data, not the internal ROM - caveat: I haven't tested this yet but I can try to do a quick test in real hardware at some point …
=> Adding technical details on the SVP chip internal ROM and fixing start address

src/mame/drivers/twinkle.cpp
Add dumps taken from actual hardware for 1stStyle and Substream variants that use the X76F041 for the dongle. This is not strictly necessary to play the games as it turns out that the game binaries have a bug where they call strcmp on the data returned from the dongle but don't check the return code. Therefore, the only thing actually "protecting" these versions from piracy is a dongle which returns "password okay" and any 8 bytes of data from a dongle. This is why Substream variants which have no dongle dump still returned "OK" in the security portion of the startup.
Still, I've dumped all dongle variants that I have access to and updated the romsets accordingly. They are marked "BAD_DUMP" because its not possible to recover the write or config password, nor the config registers without …
=> twinkle.cpp: Add partial dumps for Twinkle 1stStyle and Substream variants

src/mame/drivers/qx10.cpp
The second floppy drive was always reporting not ready due to its motor not being enabled on the write to io address 0x30
=> qx10: Enable drive B motor when doing a write motor on register

src/mame/drivers/apple2.cpp, src/mame/mame.lst
Hello,
The Franklin ACE 1000 was a popular clone of the Apple ][+.  The differences were:
* a more complicated color video generator,
* built-in lowercase support (so different character generator ROM and a few other ROM changes),
* slightly modified ROMs
I own two ACE 1000s.  I've dumped the ROMs (attached) and added an "ace1000" target to the apple2 driver.
Would it be possible to merge these changes into the main repository?
Thanks,
-- Chris
=> Add Franklin ACE 1000 as a clone of the Apple ][+

hash/a800.xml, hash/a800_flop.xml
Adds six new software list items and verifies galahad. CRCs checked against those at a8preservation.com, which seems to be the current standard bearer for Atari 8-bit dumping.  items have at least two known matching dumps according to their database.
=> a800_flop.xml: add several verified .atr dumps from a8sp

hash/megadriv.xml
Super Kick Off : 1992 -> 1993 [https://segaretro.org/Super_Kick_Off]
Fantastic Dizzy : 1991 -> 1993 [https://segaretro.org/Fantastic_Dizzy]
Sensible Soccer - International Edition : 1993 -> 1994 [https://segaretro.org/Sensible_Soccer:_International_Edition]
Double Clutch : 1992 -> 1993 [https://segaretro.org/Double_Clutch]
Hook : 1992 -> 1993 [https://segaretro.org/Hook]
Prince of Persia : 1993 -> 1994 [https://segaretro.org/Prince_Of_Persia]
NBA All-Star Challenge : 1992 -> 1993 [https://segaretro.org/NBA_All-Star_Challenge]
Stimpy's Invention : 1993 -> 1994 [https://segaretro.org/The_Ren_%26_Stimpy_Show_Presents_Stimpy%27s_Invention]
The Lost Vikings : 1993 -> 1994 [https://segaretro.org/The_Lost_Vikings]
The Chaos Engine (Euro) : 1992 -> 1994 [https://segaretro.org/The_Chaos_Engine] …
=> megadriv - Update info on 11 entries

hash/u110_card.xml, src/mame/drivers/roland_cm32p.cpp
This PR adds support for PCM ROM cards to the CM-32P driver.
With the SN-U110-04 card inserted, the CM-32P driver finally passes the PCM ROM test. (number 3)
A softlist for all currently dumped cards is included.
The CM-32P uses the PCM cards initially made for the U-110. Thus I named the softlist `u110_card`.
Known issues:
- Inserting a PCM card currently restarts the (emulated) CM-32P machine.
On the actual device, you can just insert and eject the cards without a reboot. It works more like floppies.
However I couldn't get MAME to treat the PCM card slot similar to a floppy drive.
- Selecting the PCM cards from the softlist doesn't seem to work properly.
MAME detects that the files are there, restarts, and then exits with e.g.  
`Fatal error: Device Generic Cartridge Slot load …
=> CM-32P: support PCM cards, add U-110 card softlist

src/devices/video/upd7220.cpp, src/devices/video/upd7220.h, src/mame/drivers/qx10.cpp
This update contains the following two patches:
1. Fix display issues with mixed mode (graphics/text)
2. Add support for DMAW and DMAR commands
The first patch will fix the display bugs in the second bitmap graphics test on the QX10 diagnostics disk. It also for the same reason fixes the VALDOCS menu system on the QX10.  
The second patch adds DMA support to the upd7220. I tested this again using the QX10 diagnostics disk and both the DMA write and DMA read test now behave as expected.
=> upd7220 fixes

src/mame/drivers/qx10.cpp
Fixes the inevitable segfault that will occur if you configure the machine to use a color video board.
=> qx10: allocate enough vram for color mode

src/mame/drivers/apple2gs.cpp
=> apple2gs: tweak the keypad = key

src/mame/drivers/travrusa.cpp
travrusa.cpp - hold vblank interrupt for the whole of the vblank period allowing it to retrigger in some cases - improves shtrider countdown sync at start of race.  mustache, another Seibu game requires the same logic in mustache.cpp, so it seems reasonable.  I've tested travrusa with these changes and didn't notice any new issues.
=> travrusa.cpp - hold vblank interrupt for the whole of the vblank period

src/mame/audio/laserbat.cpp, src/mame/drivers/laserbat.cpp, src/mame/includes/laserbat.h, src/mame/video/laserbat.cpp
According to [this page](http://zzzaccaria.com/zzz/CatnMouseRestoration.htm) and [this photo](http://zzzaccaria.com/zzz/images/Projects/CatnMouseRestoration/DSCN6831.JPG) in particular, there’s a wire mod on at least some Cat'n'Mouse boards to pull up pins 8, 9, 10 and 11 on IC13I.  This would have the effect of quantising area effect 2/shell to 4-pixel intervals.
How plausible does it seem that the boards would have all left the factory with this mod?  They *were* using a wire mod for sprite banking.
(The rest of the change is just tidying up the driver a little.)
=> laserbat.cpp: Quantise area effect 2/shell to 4-pixel intervals for catnmous.

hash/a800_flop.xml
Add nine more titles from a8preservation.com's verified dumps (.atr format).
Phobos works (error was in my botched testing), so remove unsupported flag.
=> a800_flop.xml: more floppy soft additions

src/mame/drivers/stfight.cpp, src/mame/includes/stfight.h, src/mame/machine/stfight.cpp
[testers-03911](https://mametesters.org/view.php?id=3911):   stfight,  empcity: Music pitch is too low
Empire City: 1931 implements a hack that 3x YM2203 clock frequency in order to solve the all sounds too low pitch. But FM (BGM) be correct, but SSG (timer countdown, clear bonus count) is still low pitch.
Frequency hack can't seem to get the correct pitch.
This PR removes frequency hack and sets YM2203 clock prescaler at machine_start in order to get right pitch.
This PR may be a hack-like approach, but I proposed the fix in this because this can remove hack that result in wrong pitch.
=> stfight.cpp: Remove YM2203 frequency hack, and set prescaler at machine_start

src/mame/audio/nl_segas16b.cpp
While comparing the segas16b netlist implementation with the schematics I noticed two capacitor labels that are incorrect.
Reference: https://www.jammarcade.net/files/Schematics/Arcade/system16b_schematics.pdf (page 6)
PCB pictures: http://reassembler.blogspot.com/2016/01/shinobi-system-16b-fix-log.html
Close-up: http://3.bp.blogspot.com/-iC5WA88RInM/Vpv1ZczijQI/AAAAAAAABq0/y289juQ5Vro/s1600/shinobi14.jpg
=> nl_segas16b: fix two capacitor labels

plugins/cheat/cheat_xml.lua
When turning on they gave message like: "index a nil value (global 'maincpuo')"
I could't build master with my 4G ram and I don't know how to make the compilation lighter, so only tested with 0.230. But pretty straightforward.
=> Fix XML cheats which use multiple spaces.

src/mame/drivers/funkyjet.cpp, src/mame/includes/funkyjet.h, src/mame/video/funkyjet.cpp
tweaks to the funkyjet addition, also apply single pixel video offset to match hardware videos and correct bg / sprite alignment.
I've also tagged the sample ROM in the other sets as BAD_DUMP pending verification, it definitely looks suspicious compared to the one in the new set.
I've marked the addition as a 'prototype?' rather than alternate demo, because there are many, many more changes than just the demo.
=> tweaks to the funkyjet addition, also apply single pixel video offset to match hardware

src/frontend/mame/luaengine.cpp
Also changes exit(0) when the script of the thread returns non-string
to an error message instead. exit stops the whole process not just the
thread.
=> Add a couple error messages to emu.thread.

src/osd/modules/input/input_sdl.cpp
As of SDL2 2.0.14, SDL on OS X synthesizes the caps lock key event by [posting a keydown event, then immediately posting a key up event](https://github.com/libsdl-org/SDL/blob/ed24c3452a99e6515faf99f155c77872f35eacd6/src/video/cocoa/SDL_cocoawindow.m#L927-L930).  As there is no time for an intervening frame update between the two events, caps lock will never be seen by the emulator.
Perhaps there's a better solution but one could use a frame callback to give the caps lock key enough time to be seen. (It can't be the next frame because the sdl input callback will happen before the ioport frame callback)
=> osx/sdl - caps lock

docs/source/initialsetup/compilingmame.rst
Add `libpulse-dev` as a build requirement for Ubuntu.
=> docs: Update build requirements for Ubuntu

src/mame/drivers/raiden2.cpp, src/mame/mame.lst
The only difference for PRG1 compared to raiden2e is the region byte being US (01) instead of Korea (04). The rest of the ROMs on the PCB match other sets.
[raiden2eub.zip](https://github.com/mamedev/mame/files/6362322/raiden2eub.zip)
=> Added working Raiden II clone

src/devices/cpu/m68000/m68kfpu.cpp
Since the two bits seem to have symmetry (top bit controls post/pre, bottom bit controls static/dynamic), it's odd this wasn't there before.
I'm not sure if copy and pasting the other case was fine, but it does seem to work. :shrug: 
Should fix issues with Domain/OS and NeXTSTEP emulation. (The crash w/o this can be reproduced by trying to start VUE on a DN3500 running Domain/OS 10.4.)
=> m68kfpu.cpp: Implement FMOVEM mode 0b11

hash/fmtowns_flop_cracked.xml, hash/fmtowns_flop_misc.xml, hash/fmtowns_flop_orig.xml
- Moved asuka120 from fmtowns_flop_misc.xml to fmtowns_flop_cracked.xml, since the original disks have been confirmed to be protected
- Moved kawaichi and ushinawa from fmtowns_flop_misc.xml to fmtowns_flop_orig.xml, since they have been verified to match the originals
- Removed the reiraa clone, since it only differs from the parent in the save data
- Additions/corrections to the missing list
Golf Links 386 Pro Champion Course Vol. 1 - Mauna Kea Beach Golf Course [al32gabby]
Golf Links 386 Pro Champion Course Vol. 2 - Firestone Country Club South Course [al32gabby]
Golf Links 386 Pro Champion Course Vol. 3 - Banff Springs [al32gabby]
Golf Links 386 Pro Champion Course …
=> fmtowns_flop_*.xml: 11 new dumps, verifications

src/mame/drivers/vgmplay.cpp
The old FM cores did not really require this spacing and didn't implement the busy flag, so many VGM captures have multiple writes stacked in the same cycle. This won't work with the new cores, so this kludge helps ensure we don't end up with ugly playback on existing files.
=> vgmplay: Ensure all writes to Yamaha FM chips are spaced by 1 cycle. 

src/mame/drivers/namcos1.cpp
PRG6 and PRG7 EPROMs on this US Galaga '88 are marked as "G82", while the rest of the ROMs have "G81" as expected. Checksums are no different.
=> Corrected filename for Galaga '88's PRG6 and PRG7

hash/pce_tourvision.xml
Be Ball and Gomola Speed do in fact match the only verified dumps in pce.xml. Old alternates in pce.xml appear to be a one-byte hack (2 lives -> 5 lives) and a bad dump, respectively.
=> pce_tourvision.xml: cleanup to match changes to pce.xml

src/mame/drivers/cyclemb.cpp
I think Cycle Maaboh sounds was corrected on pull request for #7979.
And, Sky Destroyer does not seem to have any sound imperfections compared to PCB.
So I want to remove MACHINE_IMPERFECT_SOUND flags from the driver.
(If you think I should not remove the flag, please review it)
=> cyclemb.cpp: Remove MACHINE_IMPERFECT_SOUND flags

src/mame/drivers/cyclemb.cpp
Cocktail mode for Cycle Maabou and Sky Destroyer was fixed in pull request #7979, but I forgot to remove MACHINE_NO_COCKTAIL flags.
Sorry, I forgot this in my previous pull request #8055 too.
=> cyclemb.cpp: Remove MACHINE_NO_COCKTAIL flags

src/mame/drivers/fmtowns.cpp
The volume of the PCM sound in the FM Towns driver has always been a bit too loud, but after the rewrite of the YM3438 core it has become even more evident, with the PCM sounds completely overpowering the FM instruments in music that uses both at the same time. The output of the RF5C68 was set to 3.00 gain, which is clearly too much, so this change sets it to 1.00, which sounds a lot closer to real hardware.
To demonstrate, here are recordings of the same track (from the game Deep) in:
- current MAME (after the FM rewrite): https://www.r-09.net/mame/deep_old.flac
- current MAME after this change: https://www.r-09.net/mame/deep_new.flac
- real hardware (original FM Towns Model 2): https://www.r-09.net/mame/deep_real.flac
The real thing seems to have some kind of lowpass filter that makes …
=> fmtowns: adjust PCM volume

src/mame/drivers/asuka.cpp, src/mame/mame.lst
Added new clone earthjkrb to asuka.cpp
Dump credits to: JammaFever, Nebula, Recreativos Piscis, Spain
* Found in Taito PCB: K1100726A / J1100169B
* It only differs from parent set in 2 program roms: `4.ic23` and `3.ic8`. They are very close to the earthjkra set ones and only differs in 42 bytes in each rom.
* Eprom labels are numbered in the same way as earthjkrp set, but 3 and 4 ones are swapped (Maybe a typo in earthjkrp ?)
* Same ROMSTAR license and no region disclaimer when dipswitch is changed, like earthjkr and earthjkra sets.
* It seems a newer version than earthjkra set, including additional changes to those added in earthjkra in comparison to earthjkr set, as earthjkra and earthjkrb share the same changes from earthjkr.
* Actual PCB picture: https://i.imgur.com/DYgniZc.jpg
* …
=> asuka.cpp: Added new clone earthjkrb: "U.N. Defense Force: Earth Joker (US / Japan, set 3)"

src/mame/drivers/namcos1.cpp
- Added Beraboh Man allow continue setting (DIPSW4).
- Fixed unofficially abbreviated titles
- Beraboh Man (ベラボーマン) -> Cho-Zetsurin-Jin Beraboh Man ([超絶倫人ベラボーマン](https://ja.wikipedia.org/wiki/%E8%B6%85%E7%B5%B6%E5%80%AB%E4%BA%BA%E3%83%99%E3%83%A9%E3%83%9C%E3%83%BC%E3%83%9E%E3%83%B3))
- Cho (超) = Super
- Zetsurin (絶倫) = Matchless
- Jin (人) = Human
- World Stadium (ワールドスタジアム) -> Pro Yakyuu World Stadium ([プロ野球 ワールドスタジアム](https://ja.wikipedia.org/wiki/%E3%83%97%E3%83%AD%E9%87%8E%E7%90%83%E3%83%AF%E3%83%BC%E3%83%AB%E3%83%89%E3%82%B9%E3%82%BF%E3%82%B8%E3%82%A2%E3%83%A0))
- Yakyuu (野球) = Baseball
- World Court (ワールドコート) -> Pro Tennis World Court ([プロテニス ワールドコート](https://ja.wikipedia.org/wiki/%E3%83%97%E3%83%AD%E3%83%86%E3%83%8B%E3%82%B9_%E3%83%AF%E3%83%BC%E3%83%AB%E3%83%89%E3%82%B3%E3%83%BC%E3%8 …
=> namcos1.cpp: Fixed abbreviated title, and added allow continue DIPSW of Beraboh Man

src/mame/includes/coco3.h, src/mame/machine/coco3.cpp
It is documented that the GIME monitors $FF22 to determine the proper legacy video mode. But it also monitors $FF23 to be sure $FF22 is the data register and not the data direction register. This fixes MAME testers: https://mametesters.org/view.php?id=7512
=> coco3: fix video glitch in Skiing

src/lib/formats/fsmgr.h
This addresses an issue found during compilation on GCC 7.5 and GCC 8 on Linux:
../../../../../src/lib/formats/fsmgr.h:179:7: error: ‘function’ in namespace ‘std’ does not name a template type
std::function<void (const fs_meta &)> m_validator;
^~~~~~~~
../../../../../src/lib/formats/fsmgr.h:179:2: note: ‘std::function’ is defined in header ‘<functional>’; did you forget to ‘#include <functional>’?
=> Compile fix for Linux

src/mame/drivers/m72.cpp
FM output volume is louder than DAC output volume in previous behavior, that's incorrect compared to real hardware.
=> m72.cpp: Fix sound output balance

hash/fmtowns_cd.xml
- Added the missing floppy disk to Taikou Risshiden [cyo.the.vile]
Air Warrior V1.1 (1992-03-16) [redump.org, wiggy2k]
Hajimete no Ryokou Eikaiwa (FM Towns Marty version) [redump.org]
Healthy Life II [redump.org]
NHK Jissen Eikaiwa (FM Towns Marty version) [redump.org]
Sim Sports Diving - Soreyuke! Diving [redump.org]
Towns System Software V2.1 L31 [redump.org]
Kero Kero Keroppi to Origami no Tabibito [redump.org]
Towns VNet V1.1 L10 [redump.org]
38-man Kilo no Kokuu [redump.org]
Daikoukai Jidai [redump.org]
Dengeki Nurse [redump.org]
Dungeon Master II - Skullkeep [redump.org]
FM …
=> fmtowns_cd.xml: 8 new dumps, 21 replacements, 1 missing floppy added

src/devices/sound/c6280.cpp
This fixes the envelopes having a weird tremolo like effect not present on the hardware.
You can see what this PR fixes by looking at this examples:
https://deflemask.com/c6280_comparison.png
https://deflemask.com/c6280_before.wav
https://deflemask.com/c6280_after.wav
I used this .vgm to render the examples, feel free to double check:
https://deflemask.com/c6280_example.vgm
=> Fix c6280 volume envelope shape

src/mame/drivers/ksys573.cpp
Changed name in driver from "Dance Dance Revolution Karaoke Mix" to "Dance Dance Revolution Karaoke Mix (GQ921 VER. JBB)" to match gamelist file.
=> ksys573: Change name of DDR Karaoke Mix to be more detailed

src/mame/includes/coco3.h, src/mame/machine/coco3.cpp, src/mame/video/gime.cpp, src/mame/video/gime.h
Move the PIA monitor logic into video/gime.cpp to better match the real hardware.
=> coco3: rework PR#8078

hash/nes.xml
------------------------------------
After Burner II (Jpn, Alt PCB)
Baseball (Jpn, STROM pcb)
Bible Adventures (USA, v5.0)
The Chessmaster (USA, Rev. A)
Dr. Mario (Apr 27, 1990 prototype)
Pac-Man (Jpn, Rev. B)
Mahjong (Jpn)
Rockman 4 - Aratanaru Yabou!! (Jpn) (Rev. A)
Tecmo NBA Basketball (USA) (NES-N7)
Tiger-Heli (Euro) (Rev. A)
Tokyo Pachi Slot Adventure (Jpn)
- new verified dumps from bootgod's nescartdb: aburnerj1, baseballj1, bibleadv, chessmstu, drmariop1, pacmanj
- new good yet "baddumps" split from nointro: mahjongb, rockman4, tecmonba, tigerhel, tokyopsa1
- fixed by splitting verified nointro dumps (still need pcb info): badmintn, f1senstnj, tetrisjb
- verified many previously listed split dumps against bootgod's db, updated chip/pcb labels, …
=> nes.xml: add dumps, fix dumps, verify dumps

src/mame/drivers/phoenix.cpp
* Fix G.G.I. name, it's "G.G.I. Corporation", not "G.G.I Corp".
* Only the set that shows Irecsa on the title screen is from (Irecsa / G.G.I. Corporation), every other G.G.I. Corporation Phoenix set is a generic bootleg set (we've found them on Irecsa PCBs, but also on PCBs from ASSA/Automave, Recreativos Franco and generic ones), so renamed the company from "Phoenix (Irecsa / G.G.I. Corporation)" to "Phoenix (G.G.I. Corporation)".
* Fix a note about "avefenix". "Electrogame" and "Video Game" are the same company (they changed its name circa 1981).
* Fix identation
=> phoenix.cpp: Fix "G.G.I. Corporation" Phoenix set names

hash/a800.xml, hash/pmd85_cass.xml
There's a U+009D following "2000" in each line. Is this somehow related to Czech character  ť  i.e. U+0165? ť is 9D in certain character sets and the Turbo 2000 originates there. This looks like a copy/paste error. U+009D is an invisible control char OSC, Operating System Command.
=> a800.xml: remove spurious Unicode code point

src/devices/sound/es5503.cpp
(This is in preparation for the Ensoniq Mirage driver I will be committing soon)
In the documentation I found on the ES 5503, these bits are always returned hi. This needs to be corrected to make the ISR in the Mirage work correctly.
I don't know if this negatively affects the Apple ][gs. I'll be happy to do some testing, but I would need help getting setup.
=> es5503: Register E0 bits 0 and 6 are always high

hash/nes.xml
Adventure Island 3 (Euro, prototype) [Hidden Palace]
Final Fantasy (USA, prototype) [Hidden Palace, Stephan Reese]
Nobunaga no Yabou - Bushou Fuuunroku (Jpn, Rev. A) [No-Intro]
Pachio-kun 3 (Jpn, Rev. A) [No-Intro]
UWC (USA, prototype) [Hidden Palace, Stephan Reese]
nes.xml:
* UWC info confirmed against PCB photos
* other four additions need info from PCB and/or confirmation of split ROM dumps
* also verified racketat, rcproam against bootgod's DB + minor corrections
=> nes.xml: more dumps added, more dumps confirmed

src/mame/drivers/ksys573.cpp
This change fixes "CD-ROM DRIVE ERROR (-8)" errors in Drummania 2nd Mix (and variants).
Only tested with Bemani games.
=> ksys573: Change ATAPI_CYCLES_PER_SECTOR from 5000 to 30000

src/devices/machine/rtc65271.cpp, src/devices/machine/rtc65271.h, src/mame/drivers/firebeat.cpp
Firebeat beatmania III and pop'n music require a password to unlock the RTC chip on a fresh installation. The only way to unlock it is to input a password you were supposed to get from Konami via a phone line, and more recently using a website/program I made (https://github.com/987123879113/firebeatrtc). Inputting the password is really inconvenient and the website isn't exactly advertised anywhere so it's hard for people not in the know to actually use Firebeat games. I've included RTC files that have been initialized as far as inputting the password with otherwise default settings.
=> rtc65271, firebeat: Add way to use default data for nvram initialization

src/mame/machine/6883sam.cpp
Remove space before end parentheses in log statements.
=> 6883sam: fix white space

src/devices/bus/coco/coco_fdc.cpp
1. Add 5.25 double density and 3.5 in double density drives. This allows the user to choose the type of geometry in which MFM disk images can be created.
2. Rename drives to match all other drivers.
=> coco: add additional disk drives

hash/mac_hdflop.xml, src/mame/drivers/mac.cpp, src/mame/drivers/mac128.cpp, src/mame/drivers/macprtb.cpp, src/mame/drivers/macpwrbk030.cpp, src/mame/drivers/macquadra700.cpp
This change attaches the orphan mac_hdflop.xml software list to (hopefully) all the Macintosh machines with HD floppy drives, and adds about 70 new software items to it.
The Mac is a bit out of my comfort zone, but rockleevk sent me some previously undumped KanjiTalk images a few months ago, and now that the Mac drivers fully support HD disks and all the obvious bugs have been ironed out, I thought this was a good time to add them along with some other things I got from WinWorld. I actually have about 60 more more waiting to be added, but as this is an almost-new list I wanted to submit my work so far and see if everything checks out.
A couple of notes about the naming...
- I have tried to reproduce disk labels as part_ids as closely as possible. In some cases this involves languages that …
=> mac_hdflop.xml: attach the list and start adding stuff

src/lib/formats/wd177x_dsk.cpp
Error gracefully if the image format has too many tracks for floppy drive.
I changed the default drive in the CoCo from 80 tracks to 40. If you try to load an 80 track disk with a 40 track drive, MAME would segfault because there was no room for the extra tracks.
=> wd177x: test track count is under drive limit

src/lib/formats/wd177x_dsk.cpp
1. Remove test for head count. @cuavas was right about loading a double sided disk in a single sided drive. It doesn't segfault.
2. Add track test in check_compatibility(). generate_bitstream_from_track() will segfault if disk drive doesn't have enough tracks.
=> wd177x: fix segfault based on track count

scripts/src/osd/mac_cfg.lua, scripts/src/osd/sdl_cfg.lua, scripts/src/osd/windows_cfg.lua
I was not able to build an executable with (pcap) networking enabled on macOS (11.2) until I made this change to mac_cfg.lua. I made the same change to the other scripts in that directory where the same condition is used.
I know nothing about Lua, though, and it's entirely possible some other part of my hours-long pounding on it was what actually made the difference. But I was able to repeat the results in a new branch (which I know doesn't clear out all the build stuff) with just this change, so I guess this was maybe it.
=> fix pcap builds
