mamedev/mame

- src/devices/cpu/m6502/oxavix2000.lst
- src/devices/cpu/m6502/xavix.cpp
- src/devices/cpu/m6502/xavix.h
- src/mame/drivers/xavix.cpp
- src/mame/includes/xavix.h
- src/mame/machine/xavix.cpp
- src/mame/video/xavix.cpp
also improve handling of some Super XaviX opcodes.
> XaviX - revert some previous changes that didn't have desired effect and caused an issue

- src/mame/drivers/nmk16.cpp
- src/mame/mame.lst
A working clone for a Hacha Mecha Fighter location test prototype has been added. DIPs have been tested to work as well.
> Hacha Mecha Fighter prototype; nmk16 clone addition

- src/mame/drivers/atvtrack.cpp
(useful when searching for clones)
> Add version notes to "smashdrv" (nw)

- src/mame/drivers/pbaction.cpp
- src/mame/includes/pbaction.h
- src/mame/layout/pbactiont.lay
display is hooked up and functions, although there seems to be some communication back to the maincpu from the sub that is incorrect (attempting to hook it up prevents flippers from working)
also killed off an anonymous timer.
> pbaction: hooked up Tecfri external pinball display on Pinball Action (working but missing some comms)

- src/mame/drivers/snk.cpp
Sourced from https://twitter.com/frankcifaldi/status/1058138736561598464
> SNK 40th Collection info on 'ikarijpb' bootleg source (nw)

- src/mame/drivers/hotblock.cpp
PALETTE_FORMAT for palette, Add notes, Cleanup video update routine, Convert VRAM array into std::unique_ptr, confirmed XTAL (PCB is only has 24 MHz XTAL)
> hotblock.cpp : Minor cleanups

- scripts/target/mame/mess.lua
- src/mame/drivers/xavix.cpp
- src/mame/includes/xavix.h
- src/mame/machine/xavix.cpp
- src/mame/machine/xavix_madfb_ball.cpp
- src/mame/machine/xavix_madfb_ball.h
- src/mame/video/xavix.cpp
(studying what each game is doing for IO before working out better solutions)
> XaviX - fix opcode access in upper banks (needed for rad_fb) + basic input mapping to push things along

- src/mame/audio/gottlieb.cpp
- src/mame/audio/gottlieb.h
- src/mame/drivers/gottlieb.cpp
- src/mame/drivers/gts80.cpp
- src/mame/drivers/gts80a.cpp
- src/mame/drivers/gts80b.cpp
- src/mame/includes/gottlieb.h
- src/mame/video/gottlieb.cpp
Fix namings, Spacings, Cleanup gfxdecodes
audio/gottlieb.cpp : Reduce unnecessary arguments of handlers
> gottlieb.cpp : Minor cleanups, Reduce unnecessary arguments

- src/mame/drivers/xerox820.cpp
The 820-II driver is not working at the moment. The 5.00 ROM shows "ROM error". Both additions have the extra ROMs for the low profile keyboard.
> Added ROM version 4.02 from an 820-II and 5.00 from an 820-II 16/8

- src/devices/machine/serflash.cpp
- src/devices/machine/serflash.h
Support address for when overall size is more/less than 0x8400000 bytes, or Flash page size is more/less than 2048+64
Fix block erase command, Add notes, Fix overflow
> serflash.cpp : Updates

- src/devices/cpu/m68000/m68000.h
- src/devices/cpu/m68000/m68kmmu.h
- src/mame/drivers/hp9k_3xx.cpp
With these workarounds/fixes HPUX-9 runs stable with VUE (Visual User Environment - HP's X desktop)
> Hpux final fixes

- src/mame/drivers/xerox820.cpp
ROM error like the v50 set in x168
> x820ii: Added new v50 v018 ROMset from Bitsavers.

- src/mame/drivers/tecmo.cpp
- src/mame/includes/tecmo.h
- src/mame/video/tecmo.cpp
Cleanup duplicates, Reduce some runtime tag map lookups, Convert scroll array into shared_ptr, Remove unnecessary handler installs, Fix spacing, Naming
> tecmo.cpp : Cleanups

- src/mame/drivers/stadhero.cpp
- src/mame/includes/stadhero.h
- src/mame/video/decbac06.h
- src/mame/video/decmxc06.h
- src/mame/video/stadhero.cpp
Removal some MCFGs, Fix some namings, Cleanup gfxdecode, Reduce unnecessary handlers
> stadhero.cpp : Minor cleanups, Add notes

- src/mame/drivers/gaelco.cpp
- src/mame/includes/gaelco.h
- src/mame/video/gaelco.cpp
gaelco.cpp : Reduce duplicate, Cleanup naming, Reduce runtime tag lookup, Cleanup gfxdecode
> gaelco.cpp : Minor cleanups

- hash/ekara.xml
- src/mame/includes/xavix.h
- src/mame/machine/xavix.cpp
*EC0003-  J-Pop Mix Volume 3
*EC0006-  ENK Volume 1
*EC0010-  Kid's Mix Volume 1
*EC0012-  J-Pop Mix Volume 7
*EC0013-  J-Pop Mix Volume 8
*EC0015-  Artist Selection Volume 2 - unknown artist
*EC0022-  J-Pop Mix Volume 10
*EC0026-  J-Pop Mix Volume 14
*EC0027-  J-Pop Mix Volume 15
*EC0029-  Artist Selection Volume 3 - Dreams Come True
*EC0031-  Artist Selection Volume 4 - unknown artist
*EC0034-  Kid's Mix Volume 3
*EC0036-  Artist Selection Volume 6 - KinKi Kids
*EC0042-  J-Pop Mix Volume 19
*EC0044-  Artist Selection Volume 9 - Every Little Thing
*EC0045-  Artist Selection Volume 10 - Mr. Children
*EC0048-  ENK Volume 6
*EC0049-  Artist Selection Volume 11 - Judy and Mary
*EC0054-  J-Pop Mix Volume 23
*GC0002-  BHT Volume 1
e-kara UK / Europe Volume 7 (UK-E007)
e-kara Germany 5-Songs …
> new ekara Software List entries [Team Europe + contributors]

- src/mame/drivers/nes_vt.cpp
> Change company name (nw)

- src/mame/drivers/blmbycar.cpp
- src/mame/includes/blmbycar.h
- src/mame/video/blmbycar.cpp
Cleanup duplicates, ACCESSING_BITS, runtime tag lookups
Fix memory map, Sound output(Both chip and PCB can't support stereo output)
Fix metadata related to check screen
blmbycar.h : Use private:
> blmbycar.cpp : Cleanups/Updates

- src/mame/drivers/lordgun.cpp
- src/mame/includes/lordgun.h
- src/mame/video/lordgun.cpp
Fix aliencha save state, YMF278B clock ( reference: https://www.youtube.com/watch?v=_RaCpHwyS78 )
> lordgun.cpp : Cleanup duplicates, Naming, Unnecessary handlers

- src/mame/drivers/dec0.cpp
- src/mame/includes/dec0.h
- src/mame/machine/dec0.cpp
- src/mame/video/dec0.cpp
Minor spacing fixes, Cleanup some naming
> dec0.cpp : buffered_spriteram16_device for sprite RAM

- src/mame/drivers/karnov.cpp
- src/mame/includes/karnov.h
- src/mame/video/karnov.cpp
Convert background tilemap into generic MAME tilemap system, Cleanup handlers, Reduce unnecessary values, address_space arguments, Duplicates, ROM region sizes
> karnov.cpp : Cleanups

- src/devices/video/nereid.cpp
- src/devices/video/nereid.h
Required for the upcoming HP 98550A support.
> nereid: add overlay support

- src/mame/drivers/taito_o.cpp
parentj uses FM channel of YM2203 for jingle/musics
> taito_o.cpp : Fix volume

- src/mame/drivers/f1gp.cpp
- src/mame/includes/f1gp.h
- src/mame/video/f1gp.cpp
Cleanup duplicate/naming, Split f1gp2 specific functions into driver state, Move GFX swap into ROM load, Add shared_ptr for GFX RAM, Banking
> f1gp.cpp : Various cleanups

- src/mame/video/gp9001.cpp
- src/mame/video/gp9001.h
Make tilemap drawing routine related to screen cliprect, buffered_spriteram16 for sprite RAM, Minor fix spacing
> gp9001.cpp : Updates

- src/mame/includes/ssv.h
- src/mame/video/ssv.cpp
can be seen on dynagear title screen, ultrax title screen, eaglshot sammy logo, keithlcy parallax background when you insert a coin, probably more.
> SSV - emulate rowscroll effect

- src/devices/sound/scsp.cpp
- src/devices/sound/scsp.h
- src/devices/sound/scspdsp.cpp
- src/devices/sound/scspdsp.h
Add imperfect_features related to Some DSP issues, etc..
> scsp.cpp : Add save states, Correct bool

- src/devices/sound/scsp.cpp
- src/devices/sound/scsp.h
- src/devices/sound/scspdsp.cpp
Code style fixes, Correct SSCTL, Initial RBL, Add notes, Cleanup unused / duplicates
> scsp.cpp : Minor updates

- src/mame/drivers/gaelco2.cpp
- src/mame/includes/gaelco2.h
- src/mame/mame.lst
(this is a starting point, it shows the boot screen, probably want s a signal / input from something to continue)
> new NOT WORKING --  Pro Tele Cardioline (Salter Fitness Bike V.1.0, Checksum 02AB)  [ClawGrip, Roberto Fresca, Arcade Vintage, Recreativas.org]

- src/mame/drivers/prehisle.cpp
- src/mame/includes/prehisle.h
- src/mame/video/prehisle.cpp
Cleanup handlers, Fix some namings, Fix scroll, Cleanup gfxdecode
Move non-video related save state into machine_start
> prehisle.cpp : Cleanups

- src/mame/drivers/coolridr.cpp
Cleanup duplicates, Add region_ptr for gfx ROM instead pointer, Convert arrays into std::unique_ptr, Fix some namings, Reduce unnecessary value
> coolridr.cpp : Cleanups

- src/mame/drivers/seta2.cpp
- src/mame/includes/seta2.h
- src/mame/video/seta2.cpp
Reduce unnecessary handlers, protected:'d more handlers, Fix namings, Reduce ACCESSING_BITs, Convert array into std::unique_ptr
> seta2.cpp : Cleanups

- hash/gbcolor.xml
I'll add some more info on a second PR.
> gbcolor.xml: Improve hardware info and notes (nw)

- src/mame/drivers/psikyo4.cpp
- src/mame/includes/psikyo4.h
- src/mame/video/psikyo4.cpp
Fix sound output, Namings, Some spacings, Cleanup duplicates, ACCESSING_BITs, Runtime tag lookups, Add notes
> psikyo4.cpp : Updates/Cleanups

- src/mame/drivers/powerbal.cpp
- src/mame/includes/playmark.h
- src/mame/video/playmark.cpp
playmark stuff could really do with untangling and making of devices tho, especially as 'playmark style' bootlegs are very common, with slight differences in each case.
> improve atombjt sprites (nw)

- hash/monon_color.xml
- scripts/target/mame/mess.lua
- src/mame/drivers/monon_color.cpp
- src/mame/mame.lst
first pass
note, software list names need romanizing so that shortnames can be properly assigned, would appreciate some help with that.
> basic Monon Color skeleton + Software List [zhongtiao1]

- src/mame/video/deco32.cpp
> deco32.cpp : Make ACE related mixing routine now related to cliprect

- src/mame/drivers/pc9801.cpp
I don't think RS/UX should be parents of VM but I'm not sure I can reorganize all of that without breaking something.
> pc9801.cpp: make pc9801vm boot (nw)

- src/mame/drivers/cps3.cpp
reference(sfiii3) : https://youtu.be/QYayVahSh84
> cps3.cpp : Correct color fading behavior closer to real hardware

- src/devices/machine/nscsi_bus.cpp
- src/devices/machine/wd33c9x.cpp
- src/devices/machine/wd33c9x.h
Add a new NSCSI device model for the WD33C9x family of SCSI Controllers.
> New NSCSI device for WD33C9x SCSI Controllers

- docs/source/advanced/bgfx.rst
- docs/source/advanced/devicemap.rst
- docs/source/advanced/glsl.rst
- docs/source/advanced/hlsl.rst
- docs/source/advanced/multiconfig.rst
- docs/source/advanced/paths.rst
- docs/source/advanced/shiftertoggle.rst
- docs/source/commandline/commandline-all.rst
- docs/source/commandline/sdlconfig.rst
- docs/source/commandline/windowsconfig.rst
- docs/source/initialsetup/installingmame.rst
The world is not 100% Windows, so case sensitvity is needed.
> Case sensitivity training for INI (nw)

- hash/gba.xml
- hash/gbcolor.xml
> gbcolor.xml: Add alternate game serials (nw) 

- hash/leapster.xml
500-12202-A - La Conquista de los Números (Spa)
500-12206-A - Don Lápiz - Aprender a Dibujar y Escribir (Spa)
500-12210-A - Spider-Man - El Caso de Las Letras Revueltas (Spa)
500-12227-A - Buscando a Nemo - Leer Bajo el Mar (Spa)
500-12259-A - El Laberinto de las Letras (Spa)
> leapster.xml: New NOT_WORKING software list additions [TeamEurope, ClawGrip]

- scripts/src/sound.lua
- src/devices/sound/nes_apu.cpp
- src/devices/sound/nes_apu.h
- src/devices/sound/nes_vt_apu.cpp
- src/devices/sound/nes_vt_apu.h
- src/mame/drivers/nes_vt.cpp
- Add support for the VT03+ second APU channel (with all functionality except DWS/PCM)
- Add support for the VT03+ PCM mode
- Add support for the VT3x dual-channel PCM mode
> nes_vt: APU improvements

- hash/neogeo.xml
- src/mame/drivers/neogeo.cpp
- src/mame/drivers/neopcb.cpp
Correct year, publisher/developer, Add notes, Related to title screen, staff roll, etc.
AES release of razion is exists
> Minor metadata updates of neogeo games

- src/mame/drivers/galastrm.cpp
- src/mame/includes/galastrm.h
- src/mame/video/galastrm.cpp
galastrm.cpp : Device'fied TC0110PCR, Reduce duplicate, ACCESSING_BITs, Unnesessary Runtime tag lookups, handlers, pointers
> galastrm.cpp : Minor cleanups

- src/devices/bus/neogeo/cmc.cpp
- src/devices/bus/neogeo/cmc.h
- src/devices/bus/neogeo/rom.cpp
- src/devices/bus/neogeo/rom.h
Both jockeygp, vliner has battery-backed RAM, Correct this
Convert some arrays into std::unique_ptr
> devices/bus/neogeo/cmc.cpp, rom.cpp : Implement NVRAM

- src/devices/bus/isa/sblaster.cpp
SB16: per SB HW programming guide, transfer length is in samples.  Shift by 1 for stereo is not necessary. 
SB Pro: has high-speed DMA more.
Both fixes improve playback in Inertia Player.
> sblaster: DMA fixes for SB Pro and SB16

- src/mame/drivers/xavix.cpp
- src/mame/includes/xavix.h
- src/mame/machine/xavix.cpp
Machines promoted to working
-----
Super Dash Ball (Japan) [Sean Riddle, Peter Wilhelmsen, ShouTime, David Haywood]
>  Machines promoted to working  ----- Super Dash Ball (Japan) [Sean Riddle, Peter Wilhelmsen, ShouTime, David Haywood]

- LICENSE.md
- README.md
- docs/source/license.rst
- docs/source/techspecs/luaengine.rst
- docs/source/whatis.rst
- src/lib/netlist/prg/nltool.cpp
- src/lib/netlist/prg/nlwav.cpp
- src/osd/modules/render/bgfx/shaders/shader.mk
- uismall.bdf
> 2018 -> 2019 changes (nw)

- src/devices/bus/neogeo/slot.h
- src/devices/bus/neogeo_ctrl/ctrl.h
- src/mame/drivers/midas.cpp
- src/mame/drivers/neogeo.cpp
- src/mame/drivers/neogeocd.cpp
- src/mame/drivers/neopcb.cpp
- src/mame/video/neogeo_spr.cpp
- src/mame/video/neogeo_spr.h
midas.cpp : Fix namings, Reduce some runtime tag lookup, Add notes (MCUs in machine config, etc...), Sound output correction
neogeo_spr.cpp : Remove unnecessary device pointer, Convert pointer into region_ptr, Add device_video_interface for screen
bus/neogeo/slot.cpp, bus/neogeo_ctrl/ctrl.cpp : Remove MCFGs
> midas.cpp, neogeo.cpp, neopcb.cpp, neogeocd.cpp : Remove MCFGs

- docs/source/commandline/commandline-all.rst
- docs/source/initialsetup/compilingmame.rst
There's always more to do, though.
> Correct compilation packages (for #4507) and finish cleanup on previous docs updates. (nw)

- hash/jakks_gamekey_dy.xml
- src/mame/drivers/rad_eu3a14.cpp
- src/mame/drivers/vii.cpp
- src/mame/drivers/xavix.cpp
- src/mame/mame.lst
---
Play TV Buckmasters Huntin' 2 (NTSC) [Sean Riddle, Peter Wilhelmsen]
new not working SOFTWARE LIST entries
---
jakks_gamekey_dy.xml: Sports Bowling & Goofy's Underwater Adventure [Sean Riddle]
jakks_gamekey_dy.xml: Sports Tennis & Face Chase [Sean Riddle]
> new NOT WORKING  --- Play TV Buckmasters Huntin' 2 (NTSC) [Sean Riddle, Peter Wilhelmsen] + extra Jakks gamekeys

- hash/clickstart_cart.xml
-------------
Nick Jr. The Backyardingans [TeamEurope, Sean Riddle]
The World of Cars [TeamEurope, Sean Riddle]
Disney Princess [TeamEurope, Sean Riddle]
Nickelodeon Go Diego Go! - Learning Expeditions [TeamEurope, Sean Riddle]
Learning Carnival [TeamEurope, Sean Riddle]
Nickelodeon Ni Hao, Kai-Lan (UK) [TeamEurope, Sean Riddle]
Scout's Puppy Pals (UK)
> clickstart_cart.xml: New NOT_WORKING software list additions

- src/mame/drivers/rad_eu3a14.cpp
- src/mame/drivers/trkfldch.cpp
- src/mame/mame.lst
---
Play TV Real Swing Golf [Sean Riddle, Peter Wilhelmsen]
also byteswapped the Golden Tee Home ROM to be more inline with current findings / dumping technique (nw)
> new NOT WORKING --- Play TV Real Swing Golf [Sean Riddle, Peter Wilhelmsen]

- src/devices/machine/spg110.cpp
- src/devices/machine/spg110.h
- src/mame/drivers/rad_eu3a14.cpp
- src/mame/drivers/spg110.cpp
- src/mame/drivers/vii.cpp
- src/mame/drivers/xavix.cpp
- src/mame/mame.lst
- src/mame/video/xavix.cpp
---
XaviX Baseball (XaviXPORT) [Sean Riddle, Peter Wilhelmsen]
Excite Ping Pong (Japan) [Sean Riddle, Peter Wilhelmsen]
Scooby-Doo! and the Mystery of the Castle (JAKKS Pacific TV Game) [Sean Riddle, Team Europe]
XaviX baseball uses the bitmap layer in ways I don't support yet (this will be useful)  Excite Ping Pong needs controls mapping.
Scooby-Doo is a Sunplus and seems to expose logic / rendering bugs.  
- Race To Fontecastello : corrupt van, corrupt backgrounds at times
- The River of Frights : shaggy can walk on water in places, probably meant to be more logs there based on real hw videos
- The Mysterious Doors : sometimes you'll just fail the level over and over without it really starting (start on top of an enemy?) sometimes hangs between levels (random?)
- The …
> new NOT WORKING (TV games)

- hash/apple2_flop_orig.xml
Fixed casing on CRC and SHA1 for the first entries I'd prototyped the list with so they all match. Moved two entries to be better alphabetically sorted. Also fixed WOZ file naming on Rampage.
> Small fixes per gregf request (nw)

- hash/apple2_flop_orig.xml
Cleaned up spacing on a few entries, added Wishbringer r23, Planetfall r10, Ultima 4, and Ultima 5.
> Minor cleanups, add new 4AM dumps (nw)

- src/mame/drivers/galaxian.cpp
- src/mame/mame.lst
Super Cobra (bootleg, set 3) [David Torres, ClawGrip, Recreativas.org]
It's a bootleg from the Spanish company Cocamatic. The PCB is from "GGI Corp.".
>  New WORKING clone 

- hash/vsmile_cd.xml
El Asombroso Spider-Man - Persecución en la Ciudad (Spa) [ClawGrip, The Dumping Union]
Los Increíbles - Misión Increíble (Spa) [ClawGrip, The Dumping Union]
* Also unified the CHD names as the game´s serial
> vsmile_cd.xml: New NOT_WORKING software list additions

- hash/vsmileb_cart.xml
Sorry, I added the double hyphen after checking the XML.
I'll double check the next time.
> vsmileb_cart.xml: Fix comment (nw)

- hash/pce_tourvision.xml
Blodia (Tourvision PCE bootleg) [system11, Recreativas.org, ClawGrip]
Ganbare! Golf Boys (Tourvision PCE bootleg) [system11, Recreativas.org, ClawGrip]
Hanii on the Road (Tourvision PCE bootleg) [system11, Ricky2001, Recreativas.org, ClawGrip]
Time Cruise II (Tourvision PCE bootleg) [system11, Ricky2001, Recreativas.org, ClawGrip]
> pce_tourvision.xml: New NOT_WORKING software list additions

- hash/vtech_storio_cart.xml
Rapunzel - Neu verföhnt (Germany) [TeamEurope]
Spongebob Schwammkopf - Ein Schwamm will nach oben (Germany) [TeamEurope]
Micky Maus Wunderhaus (Germany) [TeamEurope]
Dora und die drei Schweinchen (Germany) [TeamEurope]
> vtech_storio_cart.xml: New NOT_WORKING software list additions

- scripts/target/mame/mess.lua
- src/devices/cpu/m6502/oxavix2000.lst
- src/devices/cpu/m6502/xavix2000.cpp
- src/devices/cpu/m6502/xavix2000.h
- src/mame/drivers/xavix.cpp
- src/mame/includes/xavix.h
- src/mame/machine/rad_eu3a05gpio.h
- src/mame/machine/xavix.cpp
- src/mame/machine/xavix2002_io.cpp
- src/mame/machine/xavix2002_io.h
- src/mame/machine/xavix_io.cpp
- src/mame/machine/xavix_io.h
- src/mame/mame.lst
new NOT WORKING 
---
Doraemon Computer Megaphone (Japan) [Sean Riddle, Peter Wilhelmsen]
Domyos Fitness Exercises (Domyos Interactive System) [Sean Riddle, Peter Wilhelmsen]
Domyos Fitness Challenge (Domyos Interactive System) [Sean Riddle, Peter Wilhelmsen]
Domyos Fitness Adventure (Domyos Interactive System) [Sean Riddle, Peter Wilhelmsen]
XaviX Bowling (XaviXPORT) [Sean Riddle, Peter Wilhelmsen]
XaviX Bass Fishing (XaviXPORT) [Sean Riddle, Peter Wilhelmsen]
XaviX Boxing (XaviXPORT) [Sean Riddle, Peter Wilhelmsen]
Domyos Fitness Adventure looks like it might be an entirely different architecture, we'll see once Sean cleans the CPU die and takes a look.  Possibly a 32-bit CPU, haven't managed to identify it as anything I recognize tho.  Dump should be valid tho.
> new NOT WORKING (TV Game Work)

- src/mame/drivers/segas16a.cpp
- src/mame/mame.lst
new WORKING clone
---
Fantasy Zone (FD1089B 317-0016) [??]
> new WORKING clone --- Fantasy Zone (FD1089B 317-0016) [??]

- src/mame/drivers/btoads.cpp
- src/mame/drivers/tapatune.cpp
- src/mame/includes/btoads.h
btoads.h : Use private: for most things
> Remove remaining BSMT2000 related MCFGs (nw)

- docs/source/images/MAMElogo.svg
- docs/source/index.rst
Behold the power of SVG!
Added the logo to the docs as a prototype based on @cuavas's work-in-progress.
Also cleaned up trailing whitespace in the index file.
> Initial implementation of new logo for docs (nw)

- hash/monon_color.xml
- src/devices/machine/spg110.cpp
- src/devices/machine/spg110.h
- src/mame/drivers/rad_eu3a14.cpp
- src/mame/drivers/subsino2.cpp
- src/mame/drivers/xavix.cpp
- src/mame/includes/xavix.h
- src/mame/mame.lst
---
Play TV SSX Snowboarder (NTSC) [Sean Riddle, Peter Wilhelmsen, David Haywood]
---
Play TV Snowboarder (Blue) (NTSC) [Sean Riddle, Peter Wilhelmsen, David Haywood]
----
Queen Bee (Ver. 114) [Cristiano-MDQ]
Queen Bee (Israel, Ver. 100) [Cristiano-MDQ]
Queen Bee (SA-101-HARD) [Cristiano-MDQ]
new NOT WORKING SOFTWARE LIST entries
---
monon_color.xml: mechcycla  Jī jiǎ xuànfēng-gédòu dàshī (set 2) [zhongtiao1]
also refactored the spg110 stuff to be closer to spg2xx, which regresses things a bit for now due to differences, but only thing using it is the in-progress jak_capb emulation I'm working on.  sharing the code doesn't seem practical due to all the subtle differences, so needs working out like this for now at …
> new WORKING machines --- Play TV SSX Snowboarder  (and other misc / TV game work)

- src/devices/sound/ics2115.cpp
- src/devices/sound/ics2115.h
- src/mame/drivers/igs011.cpp
Remove unnecessary arguments in handler, Move igs011.cpp exclusive 16bit handlers into ics2115.cpp, Minor code style fixes, Use shorter type values, Correct device name
> ics2115.cpp : Updates

- src/devices/sound/es5506.cpp
- src/devices/sound/es5506.h
- src/devices/sound/esqpump.cpp
- src/devices/sound/esqpump.h
- src/mame/audio/taito_en.cpp
- src/mame/audio/taito_en.h
- src/mame/drivers/esq5505.cpp
- src/mame/drivers/esqasr.cpp
- src/mame/drivers/esqkt.cpp
esqpump.cpp : Use required_device for m_esp, Add device_clock_changed, Add notes, Change timer frequency related to sample rate(clock)
> es5506.cpp, Sync sample rate with esqpump.cpp

- src/devices/sound/qs1000.h
- src/mame/drivers/ghosteo.cpp
- src/mame/drivers/limenko.cpp
- src/mame/drivers/vegaeo.cpp
limenko.cpp : Removed deprecated warning, nw
ghosteo.cpp, vegaeo.cpp : Use getter for qs1000 internal CPU
> qs1000.cpp : Add getter for internal CPU

- hash/c2color_cart.xml
- hash/ekara_japan_m.xml
- hash/ekara_japan_p.xml
- hash/ekara_japan_s.xml
- hash/leapfrog_leappad_cart.xml
- hash/leapfrog_mfleappad_cart.xml
- hash/vsmile_cart.xml
- hash/vsmilem_cart.xml
- scripts/target/mame/mess.lua
- src/mame/drivers/c2color.cpp
- src/mame/drivers/leapfrog_leappad.cpp
- src/mame/drivers/nes_vt.cpp
- src/mame/mame.lst
- src/mame/mess.flt
---
LeapPad [Sean Riddle]
My First LeapPad [Sean Riddle]
+ software lists for them.  (Currently BIOS is not dumped for LeapPad, but some carts are, BIOS is dumped for My First LeapPad, but not carts)
---
C2 Color [zhongtiao1]
+ software list (Again the internal ROM isn't dumped, but we need the placeholder driver for the software list hookup, 2 carts are dumped)
> skeleton stuff (mostly to give Clawgrip a starting place)

- src/devices/bus/electron/plus1.cpp
- src/devices/bus/electron/plus1.h
- src/devices/machine/adc0844.cpp
- src/devices/machine/adc0844.h
- src/mame/drivers/mcr3.cpp
- src/mame/drivers/mcr68.cpp
- src/mame/drivers/midvunit.cpp
- src/mame/machine/midyunit.cpp
bus/electron/plus1.cpp : Remove unnecessary arguments in some handlers, nw
> adc0844.cpp : Remove unnecessary arguments in handlers

- src/devices/sound/c140.cpp
- src/devices/sound/c140.h
- src/mame/drivers/namcona1.cpp
- src/mame/includes/namcona1.h
namcona1.cpp : Remove unnecessary handler, Add note
> c140.cpp : Remove unnecessary arguments in handlers

- language/Portuguese_Brazil/strings.po
* Nomenclature fix.
* Year update.
* Better description of what MAME is really doing.
> Nomenclature fix

- src/mame/drivers/xavix.cpp
- src/mame/machine/xavix.cpp
- src/mame/mame.lst
---
Play TV Baseball (NTSC) [Sean Riddle, Peter Wilhelmsen]
dumped XaviX Bass Fishing SEEPROMS containing code for the IO MCUs [Sean Riddle]
> new NOT WORKING machines --- Play TV Baseball (NTSC) [Sean Riddle, Peter Wilhelmsen]

- src/mame/layout/md6802.lay
Introduced a lot more visual features like screws, IC:s and separation of boards in a configuration that this computer was sold.
> md6802.lay: Improved layout

- plugins/cheatfind/init.lua
1. Changes visual indications to make it nicer & quicker to use.
2. Adds selectable automatic pause capability to the cheat finder menu.
3. Allows the Test/Write poke to be changed
4. Adds another cheat format capability for cheat.simple (write support only)
> Cheat Finder Usability Improvements

- hash/leapfrog_mfleappad_cart.xml
Thomas & Friends - Thomas and the School Trip (UK) [TeamEurope]
Leap's Big Day (UK) [TeamEurope]
I Know My abc's (UK) (Dec 18 2002) [TeamEurope]
I Know My abc's (UK) (Feb 12 2002) [TeamEurope]
Joy Joy - The Jet Plane - High-Flying Adventures (UK) [TeamEurope]
The Foot Book - Based on the Book by Dr. Seuss (UK) [TeamEurope]
Vroom! Vroom! - On the Go (UK) [TeamEurope]
> leapfrog_mfleappad_cart.xml: New NOT_WORKING software list additions

- hash/leapfrog_leappad_cart.xml
Tad's Good Night (UK) [TeamEurope]
Disney Hüpf, Tigger, hüpf! (Germany) [TeamEurope]
Shrek (Germany) [TeamEurope]
Little Amadeus (Germany) [TeamEurope]
Disney Prinzessin - Prinzessinnen-Geschichten (Germany) [TeamEurope]
Also removed "I Know My abc's", since it's a "My First LeapPad" game, and not "LeapPad".
>  leapfrog_leappad_cart.xml: New NOT_WORKING software list additions 

- hash/ekara_japan.xml
- hash/ekara_japan_a.xml
- hash/ekara_japan_d.xml
- hash/ekara_japan_g.xml
- hash/ekara_japan_m.xml
- hash/ekara_japan_s.xml
- hash/gamate.xml
- scripts/target/mame/mess.lua
- src/devices/bus/ekara/rom.cpp
- src/devices/bus/ekara/rom.h
- src/devices/bus/ekara/slot.cpp
- src/devices/bus/ekara/slot.h
- src/devices/machine/spg2xx.cpp
- src/mame/drivers/gaelco2.cpp
- src/mame/drivers/vii.cpp
- src/mame/drivers/xavix.cpp
- src/mame/drivers/xavix2.cpp
- src/mame/includes/xavix.h
- src/mame/mame.lst
- src/mame/mess.flt
new WORKING Software List entries
---
gamate:fortress Fortress of Fierceness [Peter Wilhelmsen]
---
Dragon Ball Z (JAKKS Pacific TV Game, Game-Key Ready) [Sean Riddle, 19 external donators]
new NOT WORKING Software List entries
---
ekara_japan_a:a7 A-7 Pichi Pichi Pitch Pure Chapter 3 (Japan) [Peter Wilhelmsen, Sean Riddle]
ekara_japan_a:a5 A-5 Pichi Pichi Pitch Karaoke Party (Japan) [Peter Wilhelmsen, Sean Riddle]
ekara_japan_a:a4 A-4 Pichi Pichi Pitch Pure Chapter 1 (Japan) [Peter Wilhelmsen, Sean Riddle]
ekara_japan_a:a1 A-1 Pichi Pichi Pitch vol.1 (Japan) [Peter Wilhelmsen, Sean Riddle]
---
Play 2000 (Super Slot & Gran Tesoro) (v7.0i) (Italy)  [Peter Wilhelmsen, Morten Shearman Kirkegaard]
> new WORKING Gamate game + Working DBZ JAKKS + misc bits

- hash/leapfrog_leappad_cart.xml
A Day at Moss Lake (Germany) [TeamEurope]
Das Angel-Abenteuer (Germany) [TeamEurope]
Bob der Baumeister - Bob und Heppo: Alles im Griff! (Germany) [TeamEurope]
Englisch Kurs - Let's go 1 (Germany) [TeamEurope]
Englisch Kurs - Let's go 2 (Germany) [TeamEurope]
> leapfrog_leappad_cart.xml: New NOT_WORKING software list additions

- hash/ibm5150.xml
ibm5150: Budokan - The Martial Spirit (Big Games release), Lagaf': Les Adventures De Moktar - Vol 1: La Zoubida, Monty Python's Flying Circus (3.5"), Xenon (3.5") [ArcadeShadow]
> New working software list additions

- src/mame/drivers/nova2001.cpp
- src/mame/includes/nova2001.h
- src/mame/video/nova2001.cpp
Reduce duplicates, Unnecessary lines, MCFGs, Fix some namings, Spacings, Use shorter type values
> nova2001.cpp : Cleanups

- src/devices/machine/ins8154.cpp
I have tested it with acrnsys1 and vega drivers, both seem to have survived
> ins8154.cpp: Fixed bit register accesses

- src/mame/drivers/jazz.cpp
@pmackinlay Would you kindly verify my patch because it touches your file. Thanks!
> Fix compilation error when compiled with Clang 10.0.0 (Xcode 10.1)

- src/devices/video/315_5124.cpp
- src/devices/video/315_5124.h
- src/devices/video/315_5313.cpp
- src/devices/video/315_5313.h
- src/mame/drivers/megaplay.cpp
- src/mame/drivers/megatech.cpp
- src/mame/drivers/segae.cpp
- src/mame/drivers/sms.cpp
- src/mame/drivers/sms_bootleg.cpp
- src/mame/includes/sms.h
- src/mame/machine/sms.cpp
Implement internal PSG, Use shorter type values, Remove register_postload, Remove unnecessary arguments in handlers
megaplay.cpp : Add notes
megatech.cpp : Remove unnecessary handler, Add notes, nw
segae.cpp : Minor MCFG removals, Add notes
sms.cpp : Minor MCFG removals
> 315_5124.cpp : Updates

- src/osd/sdl/sdlmain.cpp
> Show video-mode option 'accel' in help and GUI

- keymaps/km_br_LINUX.map
All key maps tested and working.
> Update for Brazilian ABNT2 keyboard map

- src/emu/didisasm.h
- src/mame/drivers/coco12.cpp
- src/mame/drivers/coco3.cpp
- src/mame/drivers/dgn_beta.cpp
- src/mame/drivers/palm.cpp
coco12.cpp, coco3.cpp Minor MCFG removals
dgn_beta.cpp, palm.cpp : Remove MCFGs
> Remove MCFG_DEVICE_DISASSEMBLE_OVERRIDE usage

- hash/vsmilem_cart.xml
Disney/Pixar Cars 2 (Ger) [Sean Riddle, TeamEurope]
> New NOT_WORKING software list addition

- hash/leapfrog_leappad_cart.xml
---------------------------------------------
leapfrog_leappad_cart.xml: Was ist das? - Von Richard Scarry (Germany), LeapPad Lernsystem (Germany), Einkaufen mit Tad (Germany), Disney Jede Menge Honigtöpfe (Germany) [TeamEurope]
> New NOT_WORKING software list additions

- scripts/src/tools.lua
- src/tools/imgtool/main.cpp
- src/tools/imgtool/modules.cpp
- src/tools/imgtool/modules/rt11.cpp
Using native RT-11 5.3 as a benchmark, I have found no major difference in directory listing output (5.3 does not suport Y2K dates so those files are reported as "-BAD-").
> imgtool: new read-only filesystem: DEC RT-11 (take 2)

- src/devices/machine/timekpr.cpp
- src/devices/machine/timekpr.h
- src/mame/drivers/atlantis.cpp
- src/mame/drivers/cps1.cpp
- src/mame/drivers/itech32.cpp
- src/mame/drivers/konamim2.cpp
- src/mame/drivers/midzeus.cpp
- src/mame/drivers/multfish.cpp
- src/mame/drivers/vegas.cpp
- src/mame/machine/harddriv.cpp
Use shorter / correct type values, Fix code styles
> timekpr.cpp : Remove unnecessary arguments in handlers

- src/mame/drivers/gaelco2.cpp
- src/mame/includes/gaelco2.h
- src/mame/mame.lst
- src/mame/video/gaelco2.cpp
machines promoted to working
---
Play 2000 (Super Slot & Gran Tesoro) (v7.0i) (Italy) [Peter Wilhelmsen, Morten Shearman Kirkegaard, Caius, David Haywood]
Play 2000 (Super Slot & Gran Tesoro) (v4.0i) (Italy) [Peter Wilhelmsen, Morten Shearman Kirkegaard, Caius, David Haywood]
note, marking MCU as bad dump we had 2 boards, but one died on us, so unable to double verify the data (and the process often introduces the odd bad bit)
> machines promoted to working (Play 2000)

- hash/sms.xml
- scripts/src/bus.lua
- src/devices/bus/sg1000_exp/kblink.cpp
- src/devices/bus/sg1000_exp/kblink.h
- src/devices/bus/sg1000_exp/sk1100.cpp
- src/devices/bus/sg1000_exp/sk1100.h
- src/devices/bus/sg1000_exp/sk1100prn.cpp
- src/devices/bus/sg1000_exp/sk1100prn.h
Instructions added for the entry of the f16falcjc software in the hash/sms.xml file.
> sg1000m3: Add keyboard cable link for F-16 Fighting Falcon's 2p mode

- src/devices/sound/pokey.cpp
> pokey: performance optimization by not using modulus

- src/mame/drivers/odyssey2.cpp
It is broken since commit 48f24cb5
> odyssey2.cpp: Fix videopac machine

- src/mame/drivers/meadows.cpp
Label and location taken from real PCB
> Correct label and location

- hash/vsmile_cd.xml
Make the later revision the parent
> vsmile_cd.xml: Fix parent-clone relationships (nw)

- src/mame/drivers/leapfrog_leappad.cpp
- src/mame/mame.lst
-----------------------------------------------------
My First LeapPad (World, V1.3) [Sean Riddle, ClawGrip]
LeapPad (Canada) [Sean Riddle, ClawGrip]
Also renamed the existing set to "mfleappadus", as it's the US version, an made the new set the parent, even being older, as it's the World version.
> New NOT_WORKING clones

- src/devices/sound/pokey.cpp
- src/devices/sound/pokey.h
Yet another 2% - first one was much easier...
> Atari pokey performance II

- src/devices/video/mc6845.cpp
- src/devices/video/mc6845.h
> mc6845.cpp: Check if vsync should be enabled when frame is reset

- src/devices/video/tms34061.cpp
- src/devices/video/tms34061.h
- src/mame/drivers/guab.cpp
- src/mame/drivers/jpmsys5.cpp
- src/mame/includes/itech8.h
- src/mame/video/capbowl.cpp
- src/mame/video/itech8.cpp
itech8.cpp : Reduce unnecessary arguments in some routine
> tms34061.cpp : Simplify handlers, Use shorter type values

- src/mame/drivers/model1.cpp
- src/mame/includes/model1.h
hooked up drive board ouputs (again), choose anything but 'standard' cabinet type in vr.
> model1: hooked up drive board outputs

- hash/jpopira_jp.xml
- src/mame/drivers/vii.cpp
- src/mame/drivers/xavix.cpp
- src/mame/includes/xavix.h
- src/mame/machine/xavix.cpp
- src/mame/mame.lst
---
Jumping Popira [Sean Riddle, Peter Wilhelmsen, ShouTime, David Haywood]
---
Fun 2 Learn Smart Fit Park [Sean Riddle, Clawgrip]
(Smart Fit Park is unsp based, but seems like a newer Soc and slightly revised core with extra opcodes)
> new WORKING machines (Jumping Popira)

- src/mame/drivers/expro02.cpp
> small update to readme

- hash/snes.xml
Striker (Euro, NTSC Prototype)
> snes.xml - Add new dump

- hash/cd32.xml
Had these laying around on a HDD so I decided to test them and add the one not in the list yet.
> cd32.xml - Add one dump

- src/devices/bus/nes/konami.cpp
- src/devices/bus/nes/konami.h
- src/devices/sound/ym2413.cpp
- src/devices/sound/ym2413.h
bus/nes/konami.cpp : Fix sound clock, volume for VRC7
> ym2413.cpp : Implement instrument table for VRC7, Add notes

- src/mame/drivers/silvmil.cpp
Reduce unnecessary lines, Move handler behaviors under silvmil_state, Fix namings, Move alternative GFX layout into gfxdecode, Use shorter type values, Simplify handlers
> silvmil.cpp : Updates

- src/devices/machine/74157.cpp
- src/devices/machine/74157.h
- src/devices/sound/es8712.cpp
- src/mame/drivers/asuka.cpp
- src/mame/drivers/firetrap.cpp
- src/mame/drivers/inder.cpp
- src/mame/drivers/namcos1.cpp
- src/mame/drivers/rastan.cpp
- src/mame/drivers/seta.cpp
- src/mame/drivers/spinb.cpp
- src/mame/includes/dec0.h
> devices/machine/74157.cpp : Simplify handlers, Fix naming

- scripts/target/mame/mess.lua
- src/mame/drivers/titan_soc.cpp
- src/mame/mame.lst
- src/mame/mess.flt
---
Mega Drive 4 / Guitar Idol (set 1) [Alexandre Souza]
(it's an ARM based SoC, there is a debug terminal etc. if anybody fancies trying to mske it do anyhting, see
http://tabajara-labs.blogspot.com/2017/10/hackeando-o-mega-drive-4-parte-1.html )
People have extracted the ROMs from it, but obviously MAME would emulate this as a proper ARM based console instead of hacking out the ROMs it emulates.
> new NOT WORKING machines

- src/mame/drivers/namcos1.cpp
- src/mame/includes/namcos1.h
- src/mame/machine/namcos1.cpp
- src/mame/video/namcos1.cpp
Reduce duplicates, Runtime tag lookups, Simplify handlers, Use shorter/correct type values
> namcos1.cpp : Updates

- src/mame/drivers/spectrum.cpp
> spectrum.cpp: Fix return bits depending on hardware version

- src/mame/drivers/toaplan1.cpp
- src/mame/includes/toaplan1.h
- src/mame/machine/toaplan1.cpp
- src/mame/video/toaplan1.cpp
Cleanup duplicates, Reduce unnecessary runtime tag lookups, lines, functions, Simplify handlers, Fix namings, code styles
Split demonwld, samesame specific machine state related to exclusive value, device
Remove register_postload, Use shorter type values
> toaplan1.cpp : Updates

- src/mame/drivers/oneshot.cpp
- src/mame/drivers/vii.cpp
- src/mame/includes/oneshot.h
- src/mame/mame.lst
- src/mame/video/oneshot.cpp
--
Komo Como (Topmar, bootleg?) [f205v]
I think this is a hack / bootleg of the original Promat version of the game (which we still don't have)
> new clones  -- Komo Como  (Maddonna)

- hash/32x.xml
Also move _cf2_ out of the "old interleaved/unconfirmed dump" block.
> 32x.xml - Add new Pinocchio prototype dump

- src/mame/drivers/oneshot.cpp
- src/mame/includes/oneshot.h
- src/mame/video/oneshot.cpp
Simplify handlers, GFX layouts Fix some namings, Spacings, Reduce runtime tag lookups, Unnecessary lines
> oneshot.cpp : Updates

- hash/fmtowns_cd.xml
- hash/fmtowns_flop.xml
**fmtowns_cd.xml**
- J. R. R. Tolkien's The Lord of the Rings, Vol. II - The Two Towers [Tokugawa Corporate Forums / DamienD]
- Enkaiou [redump.org / r09]
- Joker Towns [redump.org / r09]
- Joshikou Seifuku Monogatari [redump.org / r09]
- Yuka Watanabe & Tomo Kawai - Pleasure [redump.org / r09]
**fmtowns_flop.xml**
- Viewpoint Demonstration No. 1 [David Swanson]
- Dragon Slayer: The Legend of Heroes II [r09]
- Towns Karaoke V1.1L10 [r09]
> FM Towns softlists: add new dumps

- src/mame/drivers/crospang.cpp
- src/mame/includes/crospang.h
- src/mame/video/crospang.cpp
Simplify handlers, Fix namings, Move alternative GFX layout into gfxdecode
crospang.h : Move most private things under private:
> crospang.cpp : Updates

- src/mame/drivers/tumbleb.cpp
The PIC still needs to be properly hooked up
> tumbleb.cpp: Add PIC dump for "funkyjetb" [Caps0ff, ClawGrip, The Dumping Union]

- src/devices/bus/nes/konami.cpp
- src/devices/sound/vrc6.cpp
- src/devices/sound/vrc6.h
Implement master frequency register, Fix frequency / square duty behaviors, Use shorter type values, Reduce unnecessary lines
device/bus/nes/konami.cpp : Fix vrc6 sound volume, Remove outdated comment
> vrc6.cpp : Updates

- src/devices/bus/nes/mmc5.cpp
- src/devices/bus/nes/mmc5.h
Additional sound channel instead mirroring; will be separated device
Add note
> devices/bus/nes/mmc5.cpp : Correct sound behavior

- src/mame/drivers/itech32.cpp
- src/mame/includes/itech32.h
- src/mame/video/itech32.cpp
Simplify handlers, Reduce unnecessary ACCESSING_BITs, Duplicates, Runtime tag lookups, Fix some namings, Use shorter type values
> itech32.cpp : Updates

- src/devices/sound/gaelco.cpp
- src/devices/sound/gaelco.h
- src/mame/drivers/gaelco2.cpp
Add device_rom_interface for sound data, Correct sound pitch (related to clock), Minor code style fixes
gaelco2.cpp : Minor XTAL correction, Add notes
Reference of sound pitch : (snowboar* - https://youtu.be/9ISkG2ggfEc , wrally2* - https://youtu.be/PqnnsH2aPi8)
> devices/sound/gaelco.cpp : Updates

- src/mame/drivers/simpl156.cpp
- src/mame/includes/simpl156.h
- src/mame/video/simpl156.cpp
Simplify handlers, Simplify gfxdecode, Reduce duplicates, Fix namings, spacing, OKI clock confirmed by PCB OSCs - PCBs are hasn't 32.22MHz XTAL
> simpl156.cpp : Updates

- src/devices/machine/watchdog.cpp
- src/devices/machine/watchdog.h
- src/mame/drivers/airbustr.cpp
- src/mame/drivers/capbowl.cpp
- src/mame/drivers/destroyr.cpp
- src/mame/drivers/dkong.cpp
- src/mame/drivers/flkatck.cpp
- src/mame/drivers/funkybee.cpp
- src/mame/drivers/galaxian.cpp
- src/mame/drivers/mcatadv.cpp
- src/mame/drivers/midvunit.cpp
- src/mame/drivers/mw8080bw.cpp
- src/mame/drivers/namcos86.cpp
- src/mame/drivers/poolshrk.cpp
- src/mame/drivers/segaorun.cpp
- src/mame/drivers/segas16a.cpp
- src/mame/drivers/supdrapo.cpp
- src/mame/drivers/warpwarp.cpp
- src/mame/drivers/xtheball.cpp
- src/mame/machine/ajax.cpp
- src/mame/machine/williams.cpp
- src/mame/video/skydiver.cpp
Reduce watchdog handler trampolines
> devices/machine/watchdog.cpp : Simplify handlers

- src/mame/drivers/galastrm.cpp
- src/mame/drivers/groundfx.cpp
- src/mame/drivers/gunbustr.cpp
- src/mame/drivers/slapshot.cpp
- src/mame/drivers/superchs.cpp
- src/mame/drivers/taito_f2.cpp
- src/mame/drivers/taito_z.cpp
- src/mame/drivers/undrfire.cpp
- src/mame/video/groundfx.cpp
- src/mame/video/tc0480scp.cpp
- src/mame/video/tc0480scp.h
- src/mame/video/undrfire.cpp
Fix naming, Remove unnecessary handlers, Simplify handlers, Use shorter type values
undrfire.cpp : Add notes
> tc0480scp.cpp : Updates

- src/mame/drivers/wc90b.cpp
- src/mame/includes/wc90b.h
- src/mame/mame.lst
- src/mame/video/wc90b.cpp
- tidy driver, improve gfx decodes etc.
---
Euro League (Gaelco bootleg, Modular System) [Clawgrip, ArcadeHacker, Recreativas.org]
(gfx decodes etc. done, there are only some slight changes to the program so I imagine it will be easy enough to figure the rest out)
> wc90b.cpp - tidy driver a bit + new not working clone

- hash/ibm5170.xml
> ibm5170.xml - New non-working software

- src/devices/bus/nes/mmc5.cpp
- src/devices/cpu/m6502/n2a03.cpp
- src/devices/cpu/m6502/n2a03.h
- src/mame/audio/dkong.cpp
- src/mame/drivers/cham24.cpp
- src/mame/drivers/famibox.cpp
- src/mame/drivers/multigam.cpp
- src/mame/drivers/nes.cpp
- src/mame/drivers/playch10.cpp
- src/mame/drivers/punchout.cpp
- src/mame/drivers/vgmplay.cpp
- src/mame/drivers/vsnes.cpp
- src/mame/includes/playch10.h
- src/mame/includes/punchout.h
nes.cpp, mmc5.cpp : Fix sound volume
> n2a03.cpp : Add device_mixer_interface instead hardcoded tags

- src/mame/drivers/balsente.cpp
- src/mame/mame.lst
Trivial Pursuit (Volumen V, Spanish, Maibesa hardware) [Retro Sevilla, Diego Bartolomé, Recreativas.org, ClawGrip]
>  New NOT_WORKING clone 

- src/mame/audio/leland.cpp
- src/mame/audio/leland.h
- src/mame/drivers/leland.cpp
- src/mame/includes/leland.h
- src/mame/machine/leland.cpp
- src/mame/video/leland.cpp
Simplify handlers, Fix some namings, Reduce some runtime tag lookups, Use shorter / correct type values
audio/leland.cpp : Remove hardcoded tag for ROMs and host CPU
> leland.cpp, audio/leland.cpp : Updates

- src/mame/drivers/r2dx_v33.cpp
- src/mame/drivers/raiden2.cpp
- src/mame/includes/raiden2.h
- src/mame/video/raiden2.cpp
Simplify handlers, Use shorter values, Fix code styles, Reduce some unnecessary line
> raiden2.cpp, r2dx_v33.cpp : Updates

- hash/icanpian.xml
new WORKING software list additions
---
icanpian:wizardoz The Wizard of Oz - We're Off to Play the Piano [Sean Riddle, Peter Wilhelmsen]
icanpian:barbie Barbie Princess Enchanted Sounds (J7526) [Sean Riddle, David Haywood]
icanpian:dora Dora the Explorer Musical Adventure (J7523) [Sean Riddle, David Haywood]
icanpian:aitts American Idol Take the Stage [Sean Riddle, David Haywood]
icanpian:pophits Pop Hits (K0653) [Sean Riddle, David Haywood]
icanpian:holidaywl Holiday Wonderland (J7528) [Sean Riddle, David Haywood]
(that should be all the icanpian cartridges)
> new WORKING software list additions (icanpian cartridges)

- src/emu/emupal.cpp
- src/emu/emupal.h
- src/mame/drivers/deniam.cpp
- src/mame/drivers/taito_l.cpp
- src/mame/includes/deniam.h
- src/mame/video/deniam.cpp
deniam.cpp : Add note
taito_l.cpp, deniam.cpp : Correct palette format
> emupal.cpp : Add xBGRBBBBGGGGRRRR case of palette format

- src/osd/modules/input/input_x11.cpp
On X11 Linux, every lightgun event was passed onto every lightgun
device within MAME. This obviously works for 1 gun, but with 2, it
causes both crosshairs to move in the same direction at the same
time.
This was discovered after my second gun arrived! It didn't trigger
when configuring a single gun as P1, then moving it to P2 etc..
Hence fixing it here, rather than in #4698
> Linux X11 Input: Fix multiple lightgun support

- src/mame/audio/m72.cpp
- src/mame/audio/m72.h
- src/mame/drivers/m72.cpp
- src/mame/drivers/m90.cpp
- src/mame/drivers/shisen.cpp
- src/mame/drivers/vigilant.cpp
Remove hardcoded tags, Unused functions and values, Add device_rom_interface for sample roms
m72.cpp : Correct DAC volume
m90.cpp : Fix notes
> audio/m72.cpp : Updates

- hash/3do_m2.xml
> 3do_m2.xml - Add new dump

- src/mame/drivers/deniam.cpp
- src/mame/includes/deniam.h
- src/mame/video/deniam.cpp
Simplify handlers, Fix freezing screen behavior, Reduce runtime tag lookups, Use shorter type values, Reduce unnecessary lines
> deniam.cpp : Updates

- src/mame/drivers/asuka.cpp
- src/mame/drivers/galastrm.cpp
- src/mame/drivers/groundfx.cpp
- src/mame/drivers/ninjaw.cpp
- src/mame/drivers/othunder.cpp
- src/mame/drivers/taito_f2.cpp
- src/mame/drivers/taito_z.cpp
- src/mame/drivers/undrfire.cpp
- src/mame/drivers/warriorb.cpp
- src/mame/drivers/wgp.cpp
- src/mame/includes/taito_f2.h
- src/mame/video/groundfx.cpp
- src/mame/video/taito_f2.cpp
- src/mame/video/tc0100scn.cpp
- src/mame/video/tc0100scn.h
Move taito_f2.cpp exclusive bankswitch function into taito_f2.cpp, Simplify handlers, Fix namings, Use shorter type values, Allow masked priority behavior
> tc0100scn.cpp : Updates

- src/mame/drivers/pcw.cpp
- src/mame/includes/pcw.h
- src/mame/mame.lst
- src/mame/video/pcw.cpp
I have sorted out differences between the different pcw models. 
Will take a look at why the second floppy doesn't work and go through the softlist later, will come in separate PR:s later
> Amstrad PCW driver step I

- src/mame/drivers/pengo.cpp
opening this so that experiments can be seen for now.
> schick stuff (stuck, so feel free to merge now)

- hash/ekara_pal.xml
- hash/icanpian.xml
- src/mame/drivers/vii.cpp
---
ekara_pal:spainvol1 e-kara Spain 10-Songs Volume 1 [ClawGrip, Team Europe]
ekara_pal:spainvol2 e-kara Spain 10-Songs Volume 2 [ClawGrip, Team Europe]
information about Spanish (South American?) I Can Play Piano cartridges [ClawGrip]
information about release codes for I Can Play Piano cartridges [Sean Riddle]
some details about SunPlus dies and what uses them [Sean Riddle]
> new e-kara dumps + notes

- hash/sms.xml
Changes in the World Grand Prix entries, based on a new dump made from an European cartridge.
> sms.xml: Fix metadata [TeamEurope, ICEknight, ClawGrip]

- src/devices/sound/k053260.cpp
- src/devices/sound/k053260.h
- src/mame/drivers/tmnt.cpp
Simplify handlers, Use std::s, Shorter type values, Fix spacings
> k053260.cpp : Updates

- hash/vsmile_cart.xml
Disney/Pixar Up (Spa, Rev. 022) [Team Europe, Diego Bartolomé, ClawGrip]
Gimnasio Interactivo V.Smile (Spa) [Team Europe, Diego Bartolomé, ClawGrip]
Don't know why, but controls aren't working on those games. "Up" shows a "Please, connect the controller" message on screen.
> vsmile_cart.xml: New NOT_WORKING software list additions

- src/mame/drivers/ginganin.cpp
- src/mame/includes/ginganin.h
- src/mame/video/ginganin.cpp
Simplify GFX layouts, Simplify handlers, Reduce runtime tag lookups, unnecessary batch, unnecessary lines, Fix namings, Use shorter/correct type values
> ginganin.cpp : Updates

- src/mame/drivers/gaiden.cpp
- src/mame/drivers/galspnbl.cpp
- src/mame/drivers/spbactn.cpp
- src/mame/drivers/tecmo16.cpp
- src/mame/video/gaiden.cpp
- src/mame/video/galspnbl.cpp
- src/mame/video/spbactn.cpp
- src/mame/video/tbowl.cpp
- src/mame/video/tecmo.cpp
- src/mame/video/tecmo16.cpp
- src/mame/video/tecmo_spr.cpp
- src/mame/video/tecmo_spr.h
- src/mame/video/wc90.cpp
Remove unnecessary value
Replace gfx_element instead gfxdecode_device, Reduce unused / unnecessary lines
Correct some value type
> tecmo_spr.cpp : Updates

- scripts/target/mame/mess.lua
- src/mame/drivers/superga2.cpp
- src/mame/mame.lst
... and single game (Mario Bros. translation hack)
> superga2: new machine (Apple ][-based arcade board) 

- src/devices/sound/qs1000.cpp
- src/devices/sound/qs1000.h
- src/mame/drivers/eolith.cpp
- src/mame/drivers/limenko.cpp
- src/mame/drivers/vamphalf.cpp
- src/mame/drivers/vegaeo.cpp
Add imperfect_features related to emulation incorrection
> qs1000.cpp : Updates

- src/mame/drivers/boogwing.cpp
- src/mame/drivers/cninja.cpp
- src/mame/drivers/dblewing.cpp
- src/mame/drivers/deco32.cpp
- src/mame/drivers/deco_mlc.cpp
- src/mame/drivers/dietgo.cpp
- src/mame/drivers/dreambal.cpp
- src/mame/drivers/funkyjet.cpp
- src/mame/drivers/lemmings.cpp
- src/mame/drivers/pktgaldx.cpp
- src/mame/drivers/rohga.cpp
- src/mame/drivers/sshangha.cpp
- src/mame/machine/deco104.cpp
- src/mame/machine/deco104.h
- src/mame/machine/deco146.cpp
- src/mame/machine/deco146.h
Reduce unnecessary arguments, Duplicates, Unnecessary lines, Fix spacings, Debugger issues, Use shorter type values
deco104.cpp : Reduce unnecessary line, Use shorter type values
> deco146.cpp : Updates

- src/mame/drivers/hh_sm510.cpp
Spitball Sparky hasn't been added yet afaik
> hh_sm510: g&w gamelist fix (nw)

- hash/pce_tourvision.xml
F1 Triple Battle (TourVision PCE bootleg)
(nw) Also removed redundant 0 offset labels
> pce_tourvision.xml: New NOT_WORKING software list addtion

- hash/apple2_flop_clcracked.xml
- hash/apple2_flop_misc.xml
- hash/apple2_flop_orig.xml
Don't merge this until Vas has had time to look things over; this close to release, I want to make sure this doesn't include any major screw-ups.
* Misc sets:
Anti-M 1.0, Anti-M 1.1, Anti-M 1.2, Anti-M 1.3
* WOZ original sets:
Apple-oids and Chipout, Spider Raid, Lazer Silk, Maze Craze Construction Set, Escape From Rungistan, Zaxxon, Star Blazer, Rocky's Boots (version 4.0), The Flockland Island Crisis, The Print Shop Color, Star Warrior, Warp Destroyer, Super Bunny, Type Attack, Kabul Spy, Arkanoid, Fantavision, Peeping Tom, Blade of Blackpoole, Wizardry III (version 4), Arcade Album #1,BurgerTime, Robots of Dawn, Dig Dug, Zork I (revision 5) 
Add the following cleanly cracked:
All About America, All About Purim, Alligator Alley, Alligator Mix, Aligator Mix 1982.0, Alligators and …
> Apple II WOZ updates and Clean Cracks updates for 04/2019 (nw)

- src/mame/drivers/daryde.cpp
- src/mame/mame.lst
Cricket [@LosTrastosDeXaX, ClawGrip]
> New NOT_WORKING machine

- src/mame/drivers/atarig1.cpp
- src/mame/drivers/atarig42.cpp
- src/mame/drivers/atarigt.cpp
- src/mame/drivers/atarigx2.cpp
- src/mame/video/atarirle.cpp
- src/mame/video/atarirle.h
Simplify handlers, Use shorter type values, Fix spacing
> atarirle.cpp : Updates

- src/mame/video/tc0280grd.cpp
- src/mame/video/tc0280grd.h
Simplify handlers, Use shorter type values, Reduce unnecessary lines, Fix spacings
> tc0280grd.cpp : Updates

- src/mame/drivers/harddriv.cpp
- src/mame/machine/asic65.cpp
- src/mame/machine/asic65.h
Simplify handlers, Use shorter type values, Reduce unnecessary lines, Fix debugger issues, Fix spacing
> asic65.cpp : Updates

- src/devices/cpu/tms57002/57002dsm.cpp
- src/devices/cpu/tms57002/57002dsm.h
- src/devices/cpu/tms57002/tms57002.cpp
- src/devices/cpu/tms57002/tms57002.h
- src/devices/cpu/tms57002/tms57kdec.cpp
- src/devices/cpu/tms57002/tmsops.cpp
- src/mame/drivers/konamigq.cpp
- src/mame/drivers/konamigx.cpp
- src/mame/includes/konamigx.h
Simplify handlers, Fix code styles, Use shorter type values, Fix notes
konamigq.cpp, konamigx.cpp : Reduce unnecessary handlers
> tms57002/*.* : Updates

- src/devices/machine/k033906.cpp
- src/devices/machine/k033906.h
- src/mame/machine/konppc.cpp
Simplify handlers, Fix some spacings, Convert arrays into std::unique_ptr
> k033906.cpp : Updates

- src/mame/drivers/igs017.cpp
- src/mame/drivers/igs_m027.cpp
- src/mame/video/igs017_igs031.cpp
- src/mame/video/igs017_igs031.h
Internalize palette, Remove hardcoded tags, Reduce unnecessary lines, Defines, Fix namings, spacings, Simplify handlers, Use shorter/correct type values, Add save states
igs017.cpp, igs_m027.cpp : Reduce duplicates, Use shorter type values
> igs017_igs031.cpp : Updates

- src/mame/drivers/88games.cpp
- src/mame/drivers/aliens.cpp
- src/mame/drivers/blockhl.cpp
- src/mame/drivers/bottom9.cpp
- src/mame/drivers/crimfght.cpp
- src/mame/drivers/gradius3.cpp
- src/mame/drivers/konmedal.cpp
- src/mame/drivers/mainevt.cpp
- src/mame/drivers/spy.cpp
- src/mame/drivers/thunderx.cpp
- src/mame/drivers/tmnt.cpp
- src/mame/drivers/vendetta.cpp
- src/mame/drivers/xmen.cpp
- src/mame/video/gradius3.cpp
- src/mame/video/k052109.cpp
- src/mame/video/k052109.h
- src/mame/video/simpsons.cpp
- src/mame/video/xmen.cpp
Simplify handlers, Remove unnecessary handlers, Fix notes
> k052109.cpp : Updates

- src/mame/drivers/asterix.cpp
- src/mame/drivers/quickpick5.cpp
- src/mame/drivers/tmnt.cpp
- src/mame/video/k053244_k053245.cpp
- src/mame/video/k053244_k053245.h
Simplify handlers, Reduce unnecessary handlers
> k053244_k053245.cpp : Updates

- src/mame/drivers/asterix.cpp
- src/mame/drivers/dbz.cpp
- src/mame/drivers/gijoe.cpp
- src/mame/drivers/moo.cpp
- src/mame/drivers/overdriv.cpp
- src/mame/drivers/tmnt.cpp
- src/mame/drivers/xexex.cpp
- src/mame/drivers/xmen.cpp
- src/mame/video/k053251.cpp
- src/mame/video/k053251.h
Simplify handlers, Reduce unnecessary handlers
> k053251.cpp : Updates

- src/mame/drivers/moo.cpp
- src/mame/drivers/mystwarr.cpp
- src/mame/drivers/tmnt.cpp
- src/mame/video/k054000.cpp
- src/mame/video/k054000.h
Simplify handlers, Reduce unnecessary handlers
> k054000.cpp : Updates

- src/mame/audio/atarijsa.cpp
- src/mame/drivers/atarisy2.cpp
- src/mame/drivers/badlands.cpp
- src/mame/drivers/gauntlet.cpp
- src/mame/drivers/klax.cpp
- src/mame/machine/atarigen.cpp
- src/mame/machine/atarigen.h
- src/mame/video/atarisy1.cpp
- src/mame/video/blstroid.cpp
Simplify handlers, Reduce unnecessary lines, Fix debugger issues, Fix notes, Use shorter type values, Fix spacings
badlands.cpp, gauntlet.cpp : Fix irq acknowlodge behavior
> atarigen.cpp : Updates

- hash/leapfrog_leappad_cart.xml
-------------------------------------------
Sed de Saber - Libro 1 - Spanish as a second Language Edition (UK) [TeamEurope]
Sed de Saber - Libro 2 - Spanish as a second Language Edition (UK) [TeamEurope]
Sed de Saber - Libro 3 - Spanish as a second Language Edition (UK) [TeamEurope]
Sed de Saber - Libro 4 - Spanish as a second Language Edition (UK) [TeamEurope]
Sed de Saber - Libro 5 - Spanish as a second Language Edition (UK) [TeamEurope]
Sed de Saber - Libro 6 - Spanish as a second Language Edition (UK) [TeamEurope]
Removed redundant offsets tags (nw)
Renamed the "Sed de Saber" Spanish entries (nw)
> leapfrog_leappad_cart.xml: New software list additions

- src/mame/drivers/wswan.cpp
- src/mame/video/wswan.cpp
- src/mame/video/wswan.h
Remove hardcoded tags, Add device_video_interface for screen
> wswan.cpp : Updates

- src/mame/drivers/dgpix.cpp
Simplify handlers, Reduce unnecessary runtime tag lookups, Unnecessary lines, Use shorter/correct type values, Fix spacings, Namings
> dgpix.cpp : Updates

- src/mame/drivers/cedar_magnet.cpp
- src/mame/machine/cedar_magnet_board.cpp
- src/mame/machine/cedar_magnet_board.h
- src/mame/machine/cedar_magnet_flop.cpp
- src/mame/machine/cedar_magnet_flop.h
- src/mame/machine/cedar_magnet_plane.cpp
- src/mame/machine/cedar_magnet_plane.h
- src/mame/machine/cedar_magnet_sprite.cpp
- src/mame/machine/cedar_magnet_sprite.h
Simplify handlers, Reduce unnecessary lines, Duplicates, Runtime tag lookups, Convert arrays into std::unique_ptr, Fix namings, Spacings, Use shorter type values
> cedar_magnet*.cpp : Updates

- src/tools/castool.cpp
castool was calling itself castool.exe even on *NIX systems.
> castool: Fix usage message

- src/mame/drivers/1945kiii.cpp
Correct flicker behavior, Simplify handlers, Use shorter type values, Add notes, Fix spacing
>  1945kiii.cpp : Updates

- src/mame/drivers/igs017.cpp
Simplify handlers, Reduce duplicates, Unnecessary runtime tag lookups, Unnecessary lines, Fix spacings
> igs017.cpp : Updates

- src/devices/cpu/cubeqcpu/cubeqcpu.cpp
- src/devices/cpu/cubeqcpu/cubeqcpu.h
- src/mame/drivers/cubeqst.cpp
Simplify handlers, Use correct/shorter type values, Fix spacings
> cubeqcpu.cpp : Updates

- src/devices/cpu/mips/mips3drc.cpp
There were two issues with the current DRC tlb miss handling.
1) If the tlbmiss was an instruction in a delay slot at the top of a 4k page then the wrong page index would be calculated for the tlb lookup.
2) The tlbmiss causes multiple sequential interrupts.  The current implementation loses track due to the multiple interrupts that the instuction is in a delay slot.
This causes the preceding branch jump to never be taken even if the branch condition is met.
Test case: vegas machine, mwskinsa driver
Set dipswitch Boot Mode to "Boot Disk Based Self Test".  This causes the machine to boot into a Linux 2.2.10 kernel.
mame64 mwskinsa -debug
bp 43bffc
bp 43c000
Code (after tlbmiss is resolved):
0043BFF8: AFBC001C sw        $gp,$1c($sp)
0043BFFC: 1040001F beq       $v0,$0,$0043c07c
0043C000: …
> MISP3 DRC: Fix tlbmiss in delay slot

- hash/pencil2.xml
Collaboration between the team at silicium.org and the IZE80 hardware mod+code from plgDavid
> First game dump !

- src/mame/drivers/hh_sm510.cpp
- src/mame/mame.lst
-------------
Game & Watch: Climber (crystal screen) [algestam]
> New Working clone added

- src/mame/drivers/limenko.cpp
Simplify handlers, Cleanup sprite gfx drawing routines, Reduce unnecessary lines, Fix some drawing routines, Fix spacings, Use shorter / Correct type values
> limenko.cpp : Updates

- hash/specpls3_flop.xml
New:
-Full Samdisk dump of Mercs, including both sides.
-Spanish version of 4 Soccer Simulators.
Thanks go to Gorski and ZXdenied.
> specpls3_flop.xml: New additions

- src/mame/drivers/taito_z.cpp
- src/mame/includes/taito_z.h
- src/mame/video/taito_z.cpp
Simplify handlers, Simplify gfxdecodes, Reduce duplicates, Register_postload, Runtime tag lookups, Unnecessary lines, Fix spacings, Use shorter / correct type values
> taito_z.cpp : Updates

- src/mame/drivers/slapshot.cpp
- src/mame/includes/slapshot.h
- src/mame/video/slapshot.cpp
Simplify handlers, Simplify gfxdecodes, Reduce runtime tag lookups, Unnecessary lines, Fix namings, Use shorter / Correct type values
> slapshot.cpp : Updates

- src/mame/drivers/taito_f2.cpp
- src/mame/includes/taito_f2.h
- src/mame/video/taito_f2.cpp
Simplify handlers, Simplify gfxdecodes, Reduce register_postload, duplicates, Runtime tag lookups, Unnecessary lines, Fix bankswitching behaviors, Fix spacings, Namings, Use shorter / Correct type values, Add notes
> taito_f2.cpp : Updates

- src/mame/drivers/namcona1.cpp
- src/mame/includes/namcona1.h
- src/mame/video/namcona1.cpp
Simplify handlers, Simplify gfxdecodes, Reduce unnecessary lines, Register_postload, Fix / Cleanup some drawing routines, Fix tilemap mark dirty behavior, Move tilemap palette change behavior into vreg handler, Fix spacings, Fix bit modification values, Use shorter / correct type values
> namcona1.cpp : Updates

- src/mame/drivers/actfancr.cpp
- src/mame/drivers/dec0.cpp
- src/mame/drivers/dec8.cpp
- src/mame/drivers/madmotor.cpp
- src/mame/drivers/stadhero.cpp
- src/mame/drivers/thedeep.cpp
- src/mame/drivers/vaportra.cpp
- src/mame/includes/actfancr.h
- src/mame/includes/dec0.h
- src/mame/includes/dec8.h
- src/mame/includes/vaportra.h
- src/mame/video/actfancr.cpp
- src/mame/video/dec0.cpp
- src/mame/video/dec8.cpp
- src/mame/video/decbac06.cpp
- src/mame/video/decmxc06.cpp
- src/mame/video/decmxc06.h
- src/mame/video/stadhero.cpp
- src/mame/video/thedeep.cpp
- src/mame/video/vaportra.cpp
Use callback for colour masking and priority behavior, Move configuration into handlers, Reduce unnecessary lines, Unnecessary configuration values
decbac06.cpp : Implement priority
dec0.cpp : Add notes
> decmxc06.cpp : Updates

- src/mame/drivers/expro02.cpp
- src/mame/drivers/jchan.cpp
- src/mame/drivers/kaneko16.cpp
- src/mame/drivers/sandscrp.cpp
- src/mame/includes/kaneko16.h
- src/mame/video/kaneko_tmap.cpp
- src/mame/video/kaneko_tmap.h
Internalize gfxdecode, Initialize values, Reduce unnecessary lines, Fix spacings
> kaneko_tmap.cpp : Updates

- src/mame/drivers/taito_h.cpp
- src/mame/drivers/taito_o.cpp
- src/mame/drivers/taitoair.cpp
- src/mame/includes/taito_h.h
- src/mame/includes/taito_o.h
- src/mame/includes/taitoair.h
- src/mame/video/taito_h.cpp
- src/mame/video/taito_o.cpp
- src/mame/video/taitoair.cpp
- src/mame/video/tc0080vco.cpp
- src/mame/video/tc0080vco.h
Internalize gfxdecodes, Sprite drawing routines, Simplify handlers, Reduce unnecessary lines, Unnecessary configuration values, Fix spacings, Add notes
> tc0080vco.cpp : Updates

- hash/gameboy.xml
Game Boy Test Cartridge (Euro, USA)
> gameboy.xml: New NOT_WORKING software list addition

- src/mame/drivers/expro02.cpp
- src/mame/drivers/galpani2.cpp
- src/mame/drivers/kaneko16.cpp
- src/mame/includes/kaneko16.h
- src/mame/video/kaneko_spr.cpp
- src/mame/video/kaneko_spr.h
Internalize gfxdecodes(VU002 has 4bpp, KC002 has 8bpp), Reduce unnecessary lines, Fix spacings,Use shorter / correct type values
> kaneko_spr.cpp : Updates

- src/mame/drivers/galastrm.cpp
- src/mame/includes/galastrm.h
- src/mame/video/galastrm.cpp
Simplify handlers, Simplify gfxdecodes, Reduce unnecessary lines, Fix spacings, Use shorter / correct type values, Add notes
> galastrm.cpp : Updates

- hash/cd32.xml
* Amiga CD32 - Volume 1
* Amiga CD32 - Volume 2
* Amiga CD32 Gamer - Volume 1
* Amiga CD32 Gamer - Volume 2
* Amiga CD32 Gamer - Volume 3
* Amiga CD32 Gamer - Volume 4
* Amiga CD32 Gamer - Volume 5
* Amiga CD32 Gamer - Volume 6
* Amiga CD32 Gamer - Volume 7
* Amiga CD32 Gamer - Volume 8
* Amiga CD32 Gamer - Volume 9
* Amiga CD32 Gamer - Volume 10
* Amiga CD32 Gamer - Volume 11
* Amiga CD32 Gamer - Volume 12
* Amiga CD32 Gamer - Volume 13
* Amiga CD32 Gamer - Volume 14
* Amiga CD32 Gamer - Volume 15
* Amiga CD32 Gamer - Volume 16
* Amiga CD32 Gamer - Volume 17
* Amiga CD32 Gamer - Volume 18
* Amiga CD32 Gamer - Volume 19
* Amiga CD32 Gamer - Volume 20
* Amiga CD32 Gamer - Volume 21
* Amiga CD32 Gamer - Volume 22
* Arcade Pool
* Arcade Pool (Alt)
* ATR: All Terrain Racing
> cd32.xml - Add some CD32 demos

- src/mame/drivers/kaneko16.cpp
- src/mame/includes/kaneko16.h
- src/mame/video/kaneko16.cpp
Correct spriteram buffer behavior, Simplify handlers, Add notes
> kaneko16.cpp : Updates

- src/mame/drivers/segahang.cpp
- src/mame/drivers/segaorun.cpp
- src/mame/drivers/segaxbd.cpp
- src/mame/includes/segaorun.h
- src/mame/video/segahang.cpp
- src/mame/video/segaic16_road.cpp
- src/mame/video/segaic16_road.h
- src/mame/video/segaorun.cpp
- src/mame/video/segaxbd.cpp
Simplify handlers, Remove hardcoded tags, Unnecessary pointer, Reduce unnecessary lines, Fix debugger issues, Fix spacings, Use shorter / correct type values
> segaic16_road.cpp : Updates

- src/mame/drivers/segahang.cpp
- src/mame/drivers/segaorun.cpp
- src/mame/drivers/segas16a.cpp
- src/mame/drivers/segas16b.cpp
- src/mame/drivers/segas18.cpp
- src/mame/drivers/segaxbd.cpp
- src/mame/drivers/segaybd.cpp
- src/mame/machine/segaic16.cpp
- src/mame/machine/segaic16.h
- src/mame/video/segahang.cpp
- src/mame/video/segaorun.cpp
- src/mame/video/segas16a.cpp
- src/mame/video/segas16b.cpp
- src/mame/video/segas18.cpp
- src/mame/video/segaxbd.cpp
- src/mame/video/segaybd.cpp
- src/mame/video/system16.cpp
Move palette shadow / hilight toggle bit function into palette handler (excpect hangon; it has external shadow / hilight toggle bit), Simplify some handlers, Fix debugger issues, Fix spacing, Use shorter / correct type values
> machine/segaic16.cpp : Updates

- src/devices/video/stvvdp2.cpp
- src/mame/includes/saturn.h
Fix blending when tilemap transparency pen is disabled, Fix some transparency behavior
> stvvdp2.cpp : Updates

- src/mame/drivers/jchan.cpp
Correct sprite delay, Simplify handlers, Reduce unnecessary lines, Runtime tag lookups, Fix spacings, Use shorter / correct type values
> jchan.cpp : Updates

- src/mame/video/argus.cpp
- src/mame/video/jalblend.cpp
- src/mame/video/jalblend.h
- src/mame/video/psychic5.cpp
Move alpha table into palette, Fix spacing, Reduce unnecessary line, Fix some behavior, Use shorter / correct type values
> jalblend.cpp : Updates

- src/mame/drivers/dreamwld.cpp
Simplify handlers, Correct vram data type, Convert lineram into shared_ptr, Reduce unnecessary lines, Fix spacings, Namings, Use shorter / correct type values
Fix debugger issues
> dreamwld.cpp : Updates

- hash/ekara_japan_ac.xml
- hash/icanguit.xml
- src/mame/drivers/xavix.cpp
new Software List entries
---
ekara_japan_ac:ac0009 KR-1 Kirarin Cartridge Vol.1 (Japan) (AC0009-KIR) [Sean Riddle, David Haywood]
icanguit:barbie Barbie Guitar Party (K9901) [Sean Riddle, David Haywood]
icanguit:rock101 Rock 101 (K9906) [Sean Riddle, David Haywood]
> new Software List entries (icanguit / ekara)

- src/devices/video/stvvdp1.cpp
Fix transparency and endcode behavior, Fix gouraud shading behavior, Fix sprite count, Add note
> stvvdp1.cpp : Updates

- src/mame/drivers/asteroid.cpp
- src/mame/drivers/bwidow.cpp
- src/mame/drivers/bzone.cpp
- src/mame/drivers/mhavoc.cpp
- src/mame/drivers/omegrace.cpp
- src/mame/drivers/quantum.cpp
- src/mame/drivers/starwars.cpp
- src/mame/drivers/tempest.cpp
- src/mame/drivers/tomcat.cpp
- src/mame/machine/asteroid.cpp
- src/mame/video/avgdvg.cpp
- src/mame/video/avgdvg.h
Remove hardcoded tags, Runtime tag lookups, Simplify handlers, Reduce unnecessary lines, Fix spacings, Some code styles, Namings, Use shorter / correct type values
> avgdvg.cpp : Updates

- hash/apple2_flop_clcracked.xml
- hash/apple2_flop_orig.xml
Final PR for this month unless a major issue is found.
> WOZ and Cleanly Cracked updates for May 2019 (nw)

- src/mame/drivers/fcombat.cpp
- src/mame/includes/fcombat.h
- src/mame/video/fcombat.cpp
Simplify handlers, Reduce runtime tag lookups, Unnecessary lines, Fix namings, Spacings, Use shorter / correct type values
> fcombat.cpp : Updates

- src/mame/drivers/igs017.cpp
- src/mame/drivers/pgm.cpp
- src/mame/machine/igs022.cpp
- src/mame/machine/igs022.h
- src/mame/machine/pgmprot_igs025_igs022.cpp
- src/mame/machine/pgmprot_igs025_igs022.h
Reduce hardcoded tags, Runtime tag lookups, Unnecessary pointers, Unnecessary lines, Use shorter / correct type values
> igs022.cpp : Updates

- src/mame/drivers/momoko.cpp
- src/mame/includes/momoko.h
- src/mame/video/momoko.cpp
Simplify handlers, Reduce runtime tag lookups, Unnecessary lines, Fix namings, Spacings, Use shorter / correct type values
> momoko.cpp : Updates

- src/emu/screen.cpp
This is necessary to fix the MT report https://mametesters.org/view.php?id=7331 along with a new commit I will add to pull request #4910.
> fix screen_device::update_now() when drawing partial lines

- docs/source/advanced/linux-lightguns.rst
This cleans up spelling and other issues in the original text.
This work is still prototype and will probably require fine-tuning between Vas and myself.
> Overhaul to advanced gun instructions (nw)

- src/lib/util/chd.cpp
- src/tools/imgtool/imghd.cpp
- src/tools/imgtool/modules/pc_hard.cpp
Solves "Unexpected error" in mess_hd (it's CHDERR_INVALID_PARAMETER) and pc_chd (CHDERR_ALREADY_OPEN).
> imgtool: MT 6693 wip, solves mess_hd issue (nw)

- src/devices/cpu/jaguar/jagdasm.cpp
- src/devices/cpu/jaguar/jagdasm.h
- src/devices/cpu/jaguar/jaguar.cpp
- src/devices/cpu/jaguar/jaguar.h
- src/emu/xtal.cpp
- src/mame/audio/jaguar.cpp
- src/mame/drivers/jaguar.cpp
- src/mame/includes/jaguar.h
Add notes, Reduce defines, Simplify handlers, Use shorter / correct type values, Reduce unnecessary lines, Remove register_postload
jaguar.cpp : Fix metadata, Correct XTAL frequency
> cpu/jaguar/*.cpp : Updates

- src/mame/video/decmxc06.cpp
This PR is fixes https://github.com/mamedev/mame/commit/83723a8d4c8f0622c4ddf994ab3f767fba5b57cb 's regression.
> decmxc06.cpp : Fix regression

- src/mame/drivers/1943.cpp
- src/mame/includes/1943.h
- src/mame/video/1943.cpp
Correct sprite priority handling routine, Reduce runtime tag lookups, Fix namings, Simplify handlers, Gfxdecodes, Use shorter / correct type values
> 1943.cpp : Updates

- src/mame/audio/jedi.cpp
- src/mame/drivers/jedi.cpp
- src/mame/includes/jedi.h
- src/mame/video/jedi.cpp
Simplify handlers, Add gfxdecode for debug, Add palette_device for palette handling, Reduce runtime tag lookups, Fix some drawing routines, Reduce unnecessary lines, Fix namings, Spacings, Use shorter / correct type values, Add notes
> jedi.cpp : Updates

- src/mame/drivers/8080bw.cpp
- src/mame/mame.lst
Super Invasion (Electromar, Spanish) [ARPA, Recreativas.org]
(nw) I've marked it as MACHINE_IMPERFECT_CONTROLS because coinage is wrong, and probably the other dips also are. I'd appreciante if someone could have a look at it.
>  New WORKING clone

- src/mame/drivers/bionicc.cpp
- src/mame/drivers/supduck.cpp
- src/mame/drivers/tigeroad.cpp
- src/mame/includes/tigeroad.h
- src/mame/video/bionicc.cpp
- src/mame/video/tigeroad.cpp
- src/mame/video/tigeroad_spr.cpp
- src/mame/video/tigeroad_spr.h
Internalize gfxdecode, Fix spacings, Notes, Reduce unnecessary lines, Use shorter / correct type values
bionicc.cpp, tigeroad.cpp, supduck.cpp : Simplify gfxdecode, Reduce unnecessary lines, Fix spacing, Namings
> tigeroad_spr.cpp : Updates

- hash/apple2_flop_clcracked.xml
- hash/apple2_flop_misc.xml
- hash/apple2_flop_orig.xml
Almost too much to list, and there's going to be a lot more this month.
> First set of Apple II softlist updates for June 2019 (nw)

- hash/apple2_flop_clcracked.xml
Now MAME can be the MECCa of MECC disks with this load of classic educational content.
Also, made the last disk a special one, because everyone remembers and loves Oregon Trail.
Add cleanly cracked:
Mathematics Activities Courseware Level 4, Mathematics Activities Courseware Level 6, Mathematics Problem Solving Software Level 1, Mathematics Problem Solving Software Level 2, Mathematics Problem Solving Software Level 3, Mathematics Skills Software Level 2, Mathematics Today, Mathematics Word Problems Grade 3, Maths Invaders - Special Products and Algebraic Factors, Max Command, Max Dublin's Treasure, Maxwell Manor, MECC-A114 Writing an Opinion Paper (Version 1.1), MECC-A116 Puzzles and Posters (Version 1.2), MECC-A126 Study Guide (Version 1.4), MECC-A132 MECC Writer (Version 1.1a), …
> There's #500 of the cleanly cracked Apple II disks for July 2019 (nw

- src/devices/video/epic12.cpp
- src/devices/video/epic12.h
- src/devices/video/epic12in.hxx
- src/devices/video/epic12pixel.hxx
- src/mame/drivers/cv1k.cpp
Implement debug VRAM viewer, Reduce unnecessary lines, Simplify handlers, Fix spacings, Remove hardcoded tags, Unnecessary pointers, Use shorter / correct type values
> epic12.cpp : Updates

- scripts/target/mame/arcade.lua
- src/mame/arcade.flt
- src/mame/drivers/galpanic_ms.cpp
- src/mame/mame.lst
---
Gals Panic (Modular System bootleg) [Juan Romero, Recreativas.org, ClawGrip, David Haywood]
these things are *ugly* from a hardware perspective (massive 6 board stack just for Gals Panic with many, many code hacks to work around hardware changes) so I felt it best to create a new driver with the background bits copy+pasted; the sprites + sound system specific to these bootlegs will need adding.
>  new NOT WORKING clones (Gals Panic - Modular System)

- src/devices/video/epic12.cpp
- src/devices/video/epic12.h
- src/devices/video/epic12in.hxx
- src/devices/video/epic12pixel.hxx
- src/mame/drivers/cv1k.cpp
Fix naming, Make clr_t endian-safe
> Revert Revert "epic12.cpp : Updates"

- src/mame/drivers/asuka.cpp
- src/mame/includes/asuka.h
- src/mame/video/asuka.cpp
Simplify handlers, gfxdecodes, Reduce unuseds, Fix namings, Spacings, Use shorter / correct type values
> asuka.cpp : Updates

- src/mame/drivers/ashnojoe.cpp
- src/mame/includes/ashnojoe.h
- src/mame/video/ashnojoe.cpp
Simplify handlers, gfxdecodes, Correct tilemap usage (actually visible tilemap is 6), Reduce duplicates, ROM region usage, Runtime tag lookups, Fix naming, Spacings, Use shorter / correct type values
> ashnojoe.cpp : Updates

- src/mame/drivers/ninjaw.cpp
- src/mame/includes/ninjaw.h
- src/mame/video/ninjaw.cpp
Remove register_postload, Simplify handlers, Cleanup sprite priority behavior, Reduce unnecessary lines, Simplify gfxdecodes, Split gfx layout related per each TC0100SCNs, Add notes, Fix namings, Spacings, Use shorter / correct type values
> ninjaw.cpp : Updates

- src/mame/drivers/warriorb.cpp
- src/mame/includes/warriorb.h
- src/mame/video/warriorb.cpp
Correct clock (related to XTAL on actual PCB), Simplify handlers, gfxdecodes, Correct ROM loading, Add notes, Reduce unnecessary lines, Fix namings
> warriorb.cpp : Updates

- src/mame/drivers/othunder.cpp
- src/mame/includes/othunder.h
- src/mame/video/othunder.cpp
Simplify gfxdecodes, Reduce runtime tag lookups, Unnecessary lines, Use shorter / correct type values
> othunder.cpp : Updates

- src/mame/drivers/taito_f2.cpp
- src/mame/includes/taito_f2.h
- src/mame/video/taito_f2.cpp
- src/mame/video/tc0280grd.cpp
- src/mame/video/tc0280grd.h
taito_f2.cpp : Updates
Simplify handler, gfxdecodes, Allow masked priority for ROZ layer, Fix namings, Correct finalb 6bpp gfx decode behavior into mix ROM data
> tc0280grd.cpp : Internalize gfxdecode, Allow masked priority

- src/mame/drivers/2mindril.cpp
Only dumped set of 2mindril is USA release.
> 2mindril.cpp : Fix metadata, Add notes

- src/mame/drivers/seta.cpp
- src/mame/includes/seta.h
- src/mame/video/seta.cpp
Simplify handlers, gfxdecodes, Reduce unnecessary lines, Fix spacings, Allow protection reading with side effect disabled, Use shorter / correct type values
> seta.cpp : Updates

- scripts/target/mame/arcade.lua
- src/mame/arcade.flt
- src/mame/drivers/bigkarnk_ms.cpp
- src/mame/drivers/wc90b.cpp
- src/mame/mame.lst
--
Big Karnak (Modular System) [Recreativas.org, ArcadeHacker, ClawGrip, David Haywood]
as with other Modular System things, it's not really very close to original hw at all (and uses different boards in a different configuration to other modular system setups) so new driver
> new NOT WORKING clones

- src/mame/drivers/topspeed.cpp
- src/mame/includes/topspeed.h
- src/mame/video/topspeed.cpp
Simplify handlers, gfxdecodes, Reduce runtime tag lookups, Unnecessary lines, Fix namings, Spacings, Use shorter / correct type values
> topspeed.cpp : Updates

- src/mame/drivers/darius.cpp
- src/mame/includes/darius.h
- src/mame/video/darius.cpp
Move volume initialize function into machine_start, Simplify handlers, gfxdecodes, Cleanup sprite priority behavior, Fix namings, Spacings, Reduce duplicates, Unnecessary lines, Runtime tag lookups, Use shorter / correct type values
> darius.cpp : Updates

- src/mame/drivers/2mindril.cpp
- src/mame/drivers/taito_f3.cpp
- src/mame/includes/taito_f3.h
- src/mame/video/taito_f3.cpp
Add gfx layouts for hi 2bpp datas of 6bpp gfxs
> taito_f3.cpp, 2mindril.cpp : Updates

- src/mame/drivers/aquarium.cpp
- src/mame/includes/aquarium.h
- src/mame/video/aquarium.cpp
Correct 5bpp gfx decode behavior into ROM data mixing, Fix naming, Simplify gfxdecodes, Reduce unnecessary lines
> aquarium.cpp : Updates

- src/devices/machine/6821pia.cpp
> pia6821: roll back port A read change.

- hash/apple2_flop_clcracked.xml
- hash/apple2_flop_misc.xml
- hash/apple2_flop_orig.xml
Misc Adds:
Anti-M (Version 1.5)
WOZ Adds:
Pentapus
Starcross (Revision 17 / 821021)
The Caverns of Freitag
AIRSIM 1
Pensate
Pipe Dream
Laf Pak
> Apple II updates to June 12th, 2019 (nw)

- src/mame/drivers/cbuster.cpp
- src/mame/includes/cbuster.h
- src/mame/video/cbuster.cpp
Simplify handlers, gfxdecodes, Reduce unnecessary handlers, Unnecessary lines, Use palette_format for color update, Use shorter / correct type values
> cbuster.cpp : Updates

- hash/megatech.xml
Correct ROM labels (mpxx -> mpr-xx)
Correct ROM size (0x100000 -> 0x080000) and related crc and sha1.
> Correct ROM names, size

- hash/pce_tourvision.xml
- src/mame/drivers/segaxbd.cpp
>  segaxbd.cpp and pce_tourvision.xml: Typo 

- src/mame/drivers/igspoker.cpp
- src/mame/drivers/subsino2.cpp
- src/mame/mame.lst
---
Champion Poker (v101) [Canil Babypet]
Champion Poker (v201F) [Canil Babypet]
Champion Poker (v210KS) [Canil Babypet]
Champion Poker (v300US) [Canil Babypet]
new machines marked NOT WORKING
---
Treasure Bonus (American Alpha, Ver. 1.6) [Canil Babypet]
> misc NOT WORKING additions [Canil Babypet]

- hash/jb3000_flop.xml
- hash/stepone_flop.xml
- src/mame/drivers/myb3k.cpp
> jb3000: Added softlist

- hash/apple2_flop_clcracked.xml
- hash/apple2_flop_orig.xml
- hash/coco_flop.xml
Per request of Vas, not adding more to the softlists for the 0.211 cycle.
This will get the beginnings of the June-July A2 and CoCo cycle started.
> A2/CC Softlist updates - do not merge until next (0.212) cycle starts, please (nw)

- src/mame/drivers/dooyong.cpp
- src/mame/video/dooyong.cpp
- src/mame/video/dooyong.h
Simplify handlers, Use callback for ROM based tilemap attributes, Implement tilemap ROM limitation, Add notes, Allow tilemap drawing with masked priority, Reduce unnecessary lines, Fix namings, Spacings, Use shorter / correct type values
Fix metadata (NTC licensed sets are released and published in Japan, gulfstrmm is actually a Japanese release too.)
> dooyong.cpp : Updates

- scripts/src/bus.lua
- scripts/src/formats.lua
- scripts/target/mame/mess.lua
- src/devices/bus/a2bus/a2diskii.cpp
- src/devices/bus/a2bus/a2diskii.h
- src/devices/bus/a2bus/agat840k_hle.cpp
- src/devices/bus/a2bus/agat_fdc.cpp
- src/devices/bus/a2bus/agat_fdc.h
- src/lib/formats/aim_dsk.cpp
- src/lib/formats/aim_dsk.h
- src/lib/formats/ds9_dsk.cpp
- src/lib/formats/ds9_dsk.h
- src/lib/formats/dvk_mx_dsk.cpp
- src/lib/formats/dvk_mx_dsk.h
- src/lib/formats/flopimg.cpp
- src/lib/formats/flopimg.h
- src/mame/drivers/agat.cpp
- src/mame/video/agat7.cpp
- src/mame/video/agat9.cpp
- src/mame/video/agat9.h
- src/tools/floptool.cpp
also included: MX floppy format (nw)
> agat: basic emulation of agat9 (video, apple compat mode, LLE floppy)

- src/lib/formats/tzx_cas.cpp
> tzx_cas.cpp: Fix memory leak (nw)

- src/lib/formats/dsk_dsk.cpp
> dsk_dsk.cpp: Surpass some copy-protected tracks

- src/mame/drivers/mpu5.hxx
- src/mame/mame.lst
Gold Strike (Barcrest) (MPU5) (V1.00, Spanish, Bilso S.A.) [jordigahan, ClawGrip, Recreativas.org]
>  New NOT_WORKING clone

- src/mame/drivers/deco32.cpp
- src/mame/includes/deco32.h
- src/mame/video/deco32.cpp
Simplify handlers, Reduce unnecessary handlers, Runtime tag lookups, Region spaces, Unnecessary lines, Fix spacings, Use shorter / correct type values
> deco32.cpp : Updates

- hash/apple2_flop_clcracked.xml
- hash/apple2_flop_orig.xml
Yeah, I'm still working on this stuff!
> Update Apple II disks to July 13th 2019 (nw)

- src/osd/modules/sound/pa_sound.cpp
- Needed to keep audio in sync when playing rhythm game machines such
as konami system 573. This is because the lowest audio_latency currently
supported (audio_latency 1) introduces at least 10 ms of variable latency.
I am unsure how to go about this without breaking backward compatibility
so I set it to work only when audio_latency is 0 (which was previously ignored
by mame itself and was treated equivalent to audio_latency 1). I am aware
that setting audio_latency to 0 is not supported by many mame frontends,
but this change seems natural. Otherwise, would it be better to add
a new mame.ini option, or to automatically enable this low-latency mode
when pa_latency is set lower than, say, 0.01 (10ms), which would
break people's configurations if they already rely on the old behavior?
> Suggestion for very-low-latency mode on portaudio

- src/emu/natkeyboard.cpp
- src/emu/natkeyboard.h
- src/frontend/mame/luaengine.cpp
- src/frontend/mame/ui/ui.cpp
- src/frontend/mame/ui/ui.h
> Moving paste() from mame_ui_manager class to natural_keyboard class

- src/emu/natkeyboard.cpp
- src/emu/natkeyboard.h
- src/frontend/mame/luaengine.cpp
I removed emu:paste() that I submitted earlier, because this seems to be a better place to it.  I did not remove existing functionality to post input, for backwards compatibility reasons.
> Exposed natual_keyboard object to LUA

- src/frontend/mame/luaengine.cpp
Specificially, create(), display() and must_be_loaded
> Exposed various methods/properties on device_image_interface to LUA

- src/emu/uiinput.cpp
- src/emu/uiinput.h
- src/frontend/mame/luaengine.cpp
This is needed to disable UI keyboard input for the worker_ui LUA plugin
> Added ui_input_manager::[set_]presses_enabled() and exposed to LUA

- hash/vsmile_cart.xml
50-092244-204 - Cinderella - Lernen im Märchenland (GER) [TeamEurope]
50-092424 - Findet Nemo - Nemos Unterwasserabenteuer (GER) [TeamEurope]
> vsmile_cart.xml: New WORKING software list additions

- src/mame/drivers/vamphalf.cpp
Make don't change screen size / fps when flipscreen state is changed, Make sprite drawing routine related to cliprect, Reduce duplicates, Unnecessary lines, Simplify handlers, Fix spacings, Add notes, Use shorter / correct type values
> vamphalf.cpp : Updates

- hash/vsmilem_cart.xml
Sportskanone (GER) [TeamEurope]
Micky Maus Wunderhaus (GER) [TeamEurope]
Fussball Meisterschaft (GER) [TeamEurope]
(nw) Also normalized region names and removed redundant zer-offset labels
> vsmilem_cart.xml: New NOT_WORKING software list additions

- hash/vsmile_cart.xml
Changed the comments section width to the default GitHub editor, for easy viewing (nw)
> vsmile_cart.xml: Add note about missing cart (nw)

- hash/apple2_flop_clcracked.xml
- hash/apple2_flop_orig.xml
On the IA stuff, at least.
This can wait until next cycle if desired, since I know we're in freeze.
> Officially caught up with 4AM as of July 28th, 2019 (nw)

- hash/vsmile_cart.xml
Assepoester - De wonderwereld van Assepoester (NL) [TeamEurope]
Aladdin - De wonderwereld van Aladdin (NL) [TeamEurope]
Scooby-Doo! - Griezelen in het Pretpark (NL) [TeamEurope]
Alfabet Pretpark (NL) [TeamEurope]
Ratatouille-Remy's Nieuwe Recepten (NL) [TeamEurope]
Winnie de Poeh - De wonderwereld van Poeh (NL) [TeamEurope]
>  vsmile_cart.xml: New WORKING software list additions 

- hash/vsmilem_cart.xml
Sport Games (NL) [TeamEurope]
Dora's Reparatie Avontuur! (NL) [TeamEurope]
Mijn Puppy! (NL) [TeamEurope]
> vsmilem_cart.xml: New NOT_WORKING sofware list additions

- src/mame/drivers/vp101.cpp
As we'll soon dump another PCB with the same CF version but an older boot ROM
> Add boot version on game description (nw)

- hash/psx.xml
This isn't an exhaustive addition. These are just the games that I've dumped myself.
> psx.xml - Add some dumps

- hash/apple2_flop_clcracked.xml
- hash/apple2_flop_orig.xml
> 4AM releases to August 2nd, 2019 (nw)

- src/mame/drivers/nmk16.cpp
blkheart test mode exists, but buggy text
> nmk16.cpp : Add docs for tharrier, blkheart test mode, Add notes

- src/frontend/mame/clifront.cpp
- src/frontend/mame/info.cpp
- src/frontend/mame/info.h
- src/frontend/mame/ui/miscmenu.cpp
Also, we are now passing the stream to every function, rather than sloppily keeping it in a member variable
> Changed info_xml_creator to use std::ostream

- src/mame/drivers/at.cpp
> at.cpp: add BIOS dates

- src/frontend/mame/info.cpp
- src/frontend/mame/info.h
On my machine, this seems to speed up -listxml by ~150%
I had to create a local copy of util::xml::normalize_string(), because the normal implementation is not thread safe.
> Speeding up -listxml by performing the heavy lifting asynchronously

- hash/st_flop.xml
Added the unreleased port of Highway Encounter by Vortex Software.
> st_flop.xml: New addition

- src/mame/drivers/subsino.cpp
Victor 21 is now the parent set and G.E.A. is only a hack and now the clone.
See http://robbie.mameworld.info/
> Typo in subsino.cpp

- src/devices/machine/wd33c9x.cpp
Hardware reset triggers a SCSI_STATUS_RESET interrupt when the MR signal is asserted, but this is also true when the device first powers on.
Move the interrupt generation to device_reset so all hardware resets trigger the interrupt.
> wd33c9x - clarify hardware reset

- src/osd/modules/debugger/debuggdbstub.cpp
z80 was tested with pacman and m6502 was tested with apple2e.
Side-effects must be disabled before reading memory, otherwise apple2e
starts failing after the first read to 0xc080.
Since GDB doesn't support those processors, I made up the features name
with "mame.<cpuname>". I also had to choose the registers to export in
the target.xml file, and since I don't have any experience with these
processors I don't know if I made the best choice.
> gdbstub: add z80 and m6502

- scripts/src/bus.lua
- src/devices/bus/ss50/interface.cpp
- src/devices/bus/ss50/mpt.cpp
- src/devices/bus/ss50/mpt.h
E.g. this can be used SWTPC FLEX for a timer tick.
> SS-30: add support for the MP-T timer / counter card.

- src/mame/drivers/vii.cpp
MACHINES PROMOTED TO WORKING
---
Dream Life (Version 1.0, Feb 07 2005) [Sean Riddle, David Haywood]
>  add eeprom support to dreamlif, promote to working

- src/mame/drivers/atronic.cpp
- src/mame/drivers/vii.cpp
- src/mame/mame.lst
Atronic changes (identify video CPU, fix rom loading etc.) based on information provided [Priit Laes]
---
Wild Thing (Atronic) [Priit Laes]
I C Money (Atronic) [Priit Laes]
Bonus Poker (Atronic) [Priit Laes]
(also an unrelated vii.cpp research change that I missed from the last PR) (nw)
>  Atronic changes (new sets, CPU ident etc.) [Priit Laes]

- src/frontend/mame/luaengine.cpp
This seems to work around a problem that (at least for me) caused the 'sol::object seq' parameter to not properly handle a specified sol::user<input_seq>.
This problem could be reproduced with the following command at the LUA console:
manager:machine():input():seq_poll_start("absolute",
manager:machine():input():seq_from_tokens("KEYCODE_Q"))
I would feel more comfortable if I understood why the existing code failed; it isn't clear to me if this is a bug in our sol handling for input_item_class, a bug in sol itself, or a compiler bug, but this change works for me and should definitely not introduce any problems; the worst case scenario is that we're failing to exploit some courtesy of templates syntactic sugar.
> Changes LUA seq_poll_start to take the input_item_class as a string

- src/tools/imgtool/modules/thomson.cpp
> [Imgtool] Add special characters support to Thomson BASIC

- src/devices/bus/ss50/dc5.cpp
Bit 7 of the control register inhibits all drive select lines when high and
this is now implemented. This was a long standing feature in this line of
floppy disk controller boards. The drives are also inhibited when the motor
timer has timed out. It is not just their motors that are off.
Add a conf option to interpret bit 7 of the control register as an 'erroneous'
side select, and log such usage. Some drivers use bit 7 for side selection and
this option help work around them and adapt them.
Add support to set the clock rate using the DC5 extended control register, and
update the associated code. The clock rate config option is now only an
'expected' rate and may be null.
Clarify that the motor timer is only triggered by access to the FDC registers
and not by access to the control …
> SS-30 DC5: drive select inhibit; dynamic clock rates; motor timer updates

- hash/apple2_flop_clcracked.xml
Per Vas request, here's the remaining material I have for this month.
> Finish up August 2019 softlist cycle (nw)

- hash/ibm5170.xml
* Add _Strike Commander_, _Strike Commander: Tactical Operations_ and _Strike Commander: Speech Pack_
* Add some source documentation to _TMS320C5x DSK - Applications Guide - Application Software_
* Add usage to _The Incredible Machine_
> ibm5170.xml - Add new dumps and info

- src/mame/drivers/chinagat.cpp
This patch update chinagat.cpp to have more concrete information
on TRJ-100. Now pin assignments are almost investigated as we can
try dumping it.
Also, this comment clarify which SRAM chip constructs bgvideoram.
> Add PCB layout for the second board, and information on TRJ-100

- src/mame/drivers/segac2.cpp
(tfrceac)
reference : https://youtu.be/AOmeWp9qe5E
reference 2 : https://youtu.be/Tq8VkJYmij8
reference 3: https://youtu.be/VId_HWdNuyA
> segac2.cpp : Add notes for sound output balance

- hash/vsmile_cart.xml
- hash/vsmilem_cart.xml
(nw) I need these lists to be updated with this info to search for new carts.
> Add vsmile and vsmilem "soon to be dumped carts" info (nw)

- hash/amiga_apps.xml
- hash/amiga_hardware.xml
- hash/ibm5150.xml
- hash/ibm5170.xml
- hash/mac_flop.xml
- hash/mac_hdflop.xml
- hash/st_flop.xml
* Add a bunch of new dumps
* Redumped and/or reconverted dumps that had various issues
* Tested a bunch of dumps to add _supported_ status and/or _baddump_
* Add more info about various dumps
> Floppy software additions (Amiga, ST, IBM PC, Mac)

- src/mame/drivers/commando.cpp
- src/mame/drivers/gng.cpp
Fixed main CPU frequency for Commando as per schematics.
Removed watchdog from GnG as per schematics/PCB.
> Accuracy improvement to GnG and Commando

- scripts/target/mame/mess.lua
- src/mame/drivers/h01x.cpp
- src/mame/includes/h01x.h
- src/mame/mame.lst
- src/mame/mess.flt
- src/mame/video/h01x.cpp
new computer nf500a h01jce
Chinese Computer Manufactured in 1985 
cpu		Z-80A 4MHz
video	MC6845P
sysrom	16KB EPROM
hzrom	32KB EPROM
ram		32KB SRAM
vram		16Kx4bit DRAM
> add mess nf500a h01jce

- src/mame/drivers/apple2.cpp
- src/mame/mame.lst
HKC 8800A
Apple2+ clone
Made in Hong Kong, China
> new clone computer HKC 8800A

- src/mame/machine/snes.cpp
> snes.cpp: Do not update HDMA if enabled channels are the same

- src/mame/drivers/hh_sm510.cpp
- src/mame/mame.lst
----------
Game & Watch: Fire (silver) [algestam, Mr. Do, Sean Riddle]
> * New working machine added

- src/mame/drivers/psikyosh.cpp
- src/mame/video/psikyosh.cpp
Reduce duplicates, Fix spacing, Use shorter / correct type values
> psikyosh.cpp : Updates

- src/devices/sound/ay8910.cpp
- src/devices/sound/ay8910.h
Implement ay8930 expanded mode, Add notes, Add feature value for chip specific features, Add runtime pin26 handler, Use struct for tone, envelope, Reduce defines, Fix spacings, Reduce unnecessary lines
> ay8910.cpp : Updates

- src/mame/drivers/deco_mlc.cpp
- src/mame/includes/deco_mlc.h
- src/mame/video/deco_mlc.cpp
reference : https://youtu.be/eCwAVt0GbhQ
> deco_mlc.cpp : Update blending behavior and misc updates

- src/mame/drivers/deco_mlc.cpp
- src/mame/video/deco_mlc.cpp
reference : https://www.youtube.com/watch?v=eCwAVt0GbhQ
> deco_mlc.cpp : Re-enable background color blending, Misc updates

- src/devices/video/315_5124.cpp
- src/devices/video/315_5124.h
- src/devices/video/315_5313.cpp
- src/devices/video/315_5313.h
- src/mame/drivers/calcune.cpp
- src/mame/drivers/megadriv.cpp
- src/mame/drivers/segac2.cpp
- src/mame/drivers/segas18.cpp
- src/mame/machine/megacd.cpp
Fix 3bit color mode masking, Convert drawing routine using device_gfx_interface, Simpler VRAM write / replace function
calcune.cpp : Reduce duplicates, Convert drawing routine into using vdp internal palette, Add save state
315_5124.cpp : Fix naming
> devices/video/315_5313.cpp : Fix 3bit color mode masking, Convert drawing routine using device_gfx_interface

- src/emu/video/generic.cpp
- src/emu/video/generic.h
- src/mame/drivers/airbustr.cpp
- src/mame/drivers/argus.cpp
- src/mame/drivers/cischeat.cpp
- src/mame/drivers/djboy.cpp
- src/mame/drivers/gaiden.cpp
- src/mame/drivers/galpanic.cpp
- src/mame/drivers/hvyunit.cpp
- src/mame/drivers/jalmah.cpp
- src/mame/drivers/limenko.cpp
- src/mame/drivers/mcatadv.cpp
- src/mame/drivers/megasys1.cpp
- src/mame/drivers/ninjakd2.cpp
- src/mame/drivers/nmk16.cpp
- src/mame/drivers/powerins.cpp
- src/mame/drivers/quizpani.cpp
- src/mame/drivers/sandscrp.cpp
- src/mame/drivers/snowbros.cpp
- src/mame/drivers/tecmo.cpp
- src/mame/drivers/tecmo16.cpp
- src/mame/drivers/tecmosys.cpp
these are made of 4 8x8 tiles, currently 4bpp packed layout is exists.
More usage of generic gfx layouts, Fix spacing
> emu/video/generic.cpp : Add 2x2 grouped case of 16x16 gfx layouts

- src/devices/video/imagetek_i4100.cpp
- src/devices/video/imagetek_i4100.h
- src/mame/drivers/hyprduel.cpp
Add notes, Reduce duplicates, Use struct for sprite drawing routines, Fix spacings, Use shorter / correct type values
hyprduel.cpp : Add MACHINE_NO_COCKTAIL flag related to wrong flipped screen displaying
> imagetek_i4100.cpp : Updates

- src/devices/cpu/m6502/m6502.cpp
- src/devices/cpu/m6502/om6502.lst
> Fix some style issues with my previous PR (nw)

- hash/ibm5150.xml
Dumped this myself from original disk.
> ibm5150.xml - Add Colossus Bridge 4

- hash/ibm5170.xml
> ibm5170.xml - Add QuickLink II Fax

- hash/ibm5150.xml
> ibm5150.xml - Add Star Pack

- hash/ibm5150.xml
> ibm5150.xml - Add UMS II: Nations at War - Planet Editor

- hash/ibm5170.xml
My own dump from my own disk.
The disk is damaged, hence "baddump".
> ibm5170.xml - Vinguiden 1.0

- src/devices/video/snes_ppu.cpp
- src/mame/machine/snes.cpp
Also run HDMA when vpos=0
Fix Vortex & Judge Dreed graphics
> [snes] Run HTOTAL double only if needed

- src/mame/drivers/vsnes.cpp
- src/mame/mame.lst
Vs. Super Mario Bros. (bootleg with Z80, set 3) [jordigahan, ClawGrip]
> New clones marked as NOT_WORKING

- src/devices/bus/nes/sunsoft.cpp
- src/devices/sound/ay8910.cpp
- src/devices/sound/ay8910.h
- It has Yamaha SSG volume/envelope parameters, single sound output and internal divider.
- Manufactured by Yamaha
> ay8910.cpp : Device-fied sunsoft 5B sound hardware

- src/devices/cpu/tms34010/34010ops.hxx
This pull request implements `SETCDP` opcode for tms34020.
Standalone testcase here: https://gist.github.com/plaes/dec4b76ffc4b720726f21031d8d399ac
Changes in v3:
* Dropped log2 usage in favor of `32 - count_leading_zeros()`
* Dropped useless includes
* Fixed formatting for braces
* Use logical or instead of sum
Changes in v2:
* Use functions from eminline.h (population_count_32 instead of __builtin_popcount and count_leading_zeros instead of __builtin_ffs)
* Use `log2` from `<cmath>`
* Fix pointless `log2` calls in the double power of two case.
> tms34020: Implement SETCDP opcode

- src/devices/sound/mos6581.cpp
- src/devices/sound/mos6581.h
- src/devices/sound/sid.cpp
- src/devices/sound/sid.h
- src/devices/sound/sidenvel.cpp
- src/devices/sound/sidvoice.cpp
- src/devices/sound/sidvoice.h
sid.cpp : Reduce duplicates, Add postload function
sidvoice.cpp : Fix type value when DIRECT_FIXPOINT defined
sidenvel.cpp, sidvoice.cpp, sid.cpp : Fix spacings
> mos6581.cpp : Add save states, Misc SID chip updates

- src/osd/modules/input/input_x11.cpp
https://mametesters.org/view.php?id=7372
> Check that m_display is not null to prevent crash

- src/devices/sound/ymf262.cpp
- src/devices/sound/ymf278b.cpp
> ymf278b.cpp : Allow scaling for FM DO2 output

- src/mame/drivers/at.cpp
- src/mame/mame.lst
> at.cpp: motherboards and BIOS versions, RAM and cache information, small ROM name

- hash/ekara_japan_a.xml
- hash/ekara_japan_ac.xml
- hash/evio.xml
- src/devices/cpu/unsp/unsp.cpp
- src/devices/cpu/unsp/unsp_fxxx.cpp
- src/devices/cpu/unsp/unspdrc.cpp
- src/devices/cpu/unsp/unspfe.cpp
- src/mame/drivers/vii.cpp
- src/mame/drivers/xavix.cpp
- src/mame/includes/xavix.h
- src/mame/mame.lst
-------
Disney Princesses (JAKKS Pacific TV Game, Game-Key Ready) [Sean Riddle, David Haywood, anonymous]
Capcom 3-in-1 (1942, Commando, Ghosts'n Goblins) (JAKKS Pacific TV Game, Game-Key Ready) (29 MAR 2005 B) [Sean Riddle, David Haywood, anonymous]
-----
Care Bears TV Games (JAKKS Pacific TV Game, Game-Key Ready) [Sean Riddle, David Haywood, anonymous]
-----
ekara_japan_a.xml:
a3 : A-3 Pichi Pichi Pitch vol.3 (Japan) [David Haywood, Sean Riddle]
evio.xml:
em2: eM2 - evio Selection 02 [David Haywood, Peter Wilhelmsen, ShouTime, Sean Riddle]
em3: eM3 - Anime Mix 1 [David Haywood, Peter Wilhelmsen, ShouTime, Sean Riddle]
em4: eM4 - I Love Classic 1 [David Haywood, Peter Wilhelmsen, ShouTime, Sean Riddle] …
> Plug and Play additions

- src/mame/drivers/naomi.cpp
> Names consistency in notes - improved Cart 171-7978B documentation

- src/mame/drivers/cps1.cpp
- src/mame/video/cps1.cpp
Mercs and Street Fighter II 910228 World/USA CPS-B-18 variants
> some cps1 c-board pal dumps

- src/devices/video/315_5124.cpp
- src/devices/video/315_5124.h
- src/devices/video/315_5313.cpp
- src/devices/video/315_5313.h
- src/mame/drivers/megaplay.cpp
megaplay.cpp : Use LCM of support horizontal resolution in both VDPs
315_5124.cpp : Allow dividing hcounter related to using LCM
> 315_5313.cpp : Allow LCM scaling of horizontal resolution

- src/devices/machine/spg2xx_io.cpp
- src/devices/machine/spg2xx_io.h
- src/mame/drivers/vii.cpp
- src/mame/layout/pvmil.lay
machine promoted to WORKING
----
Who Wants to Be a Millionaire? (Play Vision, Plug and Play, UK) [David Haywood, Morten Kirkegaard, Peter Wilhelmsen]
> promoted to WORKING (pvmil - SunPlus)

- src/devices/sound/es5506.cpp
- src/devices/sound/es5506.h
Reduce duplicates, Unnecessary lines, #define macros, Implement reset behavior(RESB in ES5506), Add notes, Use shorter / correct type values, Fix filter behaviors, Sync to official documents
references : http://zine.r-massive.com/ensoniq-technical-documents-and-schematics/
> es5506.cpp : Add/Implement ES5505 difference, Fix spacing, Various updates

- src/mame/drivers/elan_eu3a05.cpp
- src/mame/mame.lst
---
Air-Blaster Joystick (AB1500, PAL) [David Haywood,  Morten Kirkegaard, Peter Wilhelmsen]
boots, 2d games can be played, although speed probably not correct.  3d sections don't work properly at all.  dump is pending 2nd verification, but I think the issues are emulation issues (missing timers etc.)
> new NOT WORKING machines (Air-Blaster Joystick)

- src/mame/drivers/elan_eu3a05.cpp
- src/mame/video/elan_eu3a05vid.cpp
- src/mame/video/elan_eu3a05vid.h
fixes some scroll modes (to the extent we have evidence for)
improves code
> Plug & Play improvements (Elan / Air Blaster Joystick)

- src/mame/drivers/midqslvr.cpp
It would honestly be better to know what components these I/O boards have. Hydro and Offroad Thunder share a lot in common. Both have the same video card security and I/O MCU.
I also added a machine config for Arctic Thunder so at least the cpu runs at its correct speed. The two MCUs are said to house internal roms so I added placeholder dumps of these roms in the meantime.
> midqslvr.cpp: I/O board readme (nw)

- src/devices/bus/spectrum/melodik.cpp
> ZX Spectrum, Melodik soundcard fix

- src/devices/video/ppu2c0x_vt.cpp
- src/devices/video/ppu2c0x_vt.h
- src/mame/drivers/nes_vt.cpp
- src/mame/includes/nes.h
- src/mame/mame.lst
-----
Pinball (P8002, ABL TV Game) [David Haywood,  Morten Kirkegaard, Peter Wilhelmsen]
> new NOT WORKING machines (ABL Pinball plug & play)

- src/mame/drivers/vii.cpp
- src/mame/layout/sentx6p.lay
Senario Texas Poker preliminary LCD controller / UART hookup work [David Haywood]
this handles the output format to the LCD screens (there's probably an MCU in each in reality, but for now we can simulate the display using the artwork system)  Input reading not yet handled.
> Senario Texas Poker preliminary LCD controller / UART hookup work [David Haywood]

- src/devices/bus/spectrum/mface.cpp
- src/devices/bus/spectrum/mface.h
Corrected nmi clearing
Added on board kempston port
Added disable switch and joystick disable jumper
Lots of notes
I'm not too familiar with the other models so made changes to original "One" model only for now.
> ZX Spectrum Multiface One improvements

- src/mame/drivers/qvt102.cpp
Splitting out some of the general improvements to the qvt102, based on feedback, thanks. Could we at least land these improvements given that people have had a look over it and provided constructive feedback. If there are more suggestions for the general code then might they be considered here.
Looking at the schematic, the latch is not cleared in hardware on reset, so would it be most appropriate to not reset it, or is the MAME reset method interpreted as resetting latches?
> qvt102: key lines, boost interleave

- src/devices/bus/spectrum/exp.h
- src/mame/drivers/spectrum.cpp
- src/mame/includes/spectrum.h
Added a floating bus behaviour, fixes a few games that rely on it.
> ZX Spectrum floating bus support

- src/mame/arcade.flt
- src/mame/drivers/cps1.cpp
- src/mame/drivers/cps1bl_5205.cpp
- src/mame/drivers/cps1bl_pic.cpp
- src/mame/drivers/fcrash.cpp
- src/mame/includes/cps1.h
- src/mame/mame.lst
- src/mame/video/cps1.cpp
Some new sets in Fcrash:
Added captcommb2 - Captain Commando single board bootleg (w/ 2x oki MSM5205)
Added knightsb3 - Knights of the Round single board bootleg (w/ 2x oki MSM5205)
Added dinopic3 - Cadillacs and Dinosaurs single board bootleg (w/ PIC) no sound (pic secured)
> Cps1 bootlegs, some more new sets

- src/devices/machine/spg2xx_io.cpp
- src/mame/drivers/vii.cpp
- src/mame/layout/sentx6p.lay
also for spg2xx_io, add machine().describe_context() to more of the logging calls to make it more informative for debugging.
added all player inputs on Senario Poker, relies on a few hacks for now, but functional.
> Plug & Play work (Tv GoGo, Poker inputs etc.)

- src/devices/machine/ins8250.cpp
- src/devices/machine/ins8250.h
- src/mame/drivers/eispc.cpp
Would such a crude solution be ok, I want to avoid rewriting the diserial hookup for ins8250, please review approach
> ins8250 support for BAUDOUT pin

- hash/apple2_flop_clcracked.xml
- hash/apple2_flop_orig.xml
Also includes some metadata cleanup.
> Apple Softlists to Nov 16th, 2019

- src/devices/machine/ins8250.cpp
There could also be edge cases that needs to be taken care of as the current implementation in diserial has two timers, one for the rx shifter and one for the tx shifter but 8250 only has one clock but diserial doesn't like to have the other clock running when it isn't in use.
> ins8250.cpp: fixed regression caused by local BRG used for baudout pin

- src/mame/drivers/cps1.cpp
> some sf2ce m-street6 pal dumps

- hash/ibm5170.xml
ibm5170: Kick Off 3: European Challenge
> New working software list addition

- src/devices/bus/isa/mda.cpp
- src/devices/bus/isa/mda.h
- src/mame/drivers/eispc.cpp
I think it is good enough now for floppy boot and usage, some configurations were sold without hard disk so promotion is legit as most main board features are supported now. Hard disk support and other features will be added later and are all based on ISA cards.
> eispc.cpp, mda.cpp: epc LPT device properly installed and is promoted to working

- src/mame/drivers/vt1682.cpp
added some timers (currently fixed frequency, need to use register) and hook up the DACs, which produce slightly crackly sound at the moment in the 'right' channel, need to check why.
> vt1682.cpp - (plug & play) preliminary sound support

- src/mame/drivers/cave.cpp
- src/mame/video/cave.cpp
- src/mame/video/tmap038.cpp
- src/mame/video/tmap038.h
> tmap038.cpp : Add tile size check related to vram is found, Move mirroring map into driver

- src/mame/drivers/galivan.cpp
- src/mame/includes/galivan.h
- src/mame/video/galivan.cpp
- [06946](https://mametesters.org/view.php?id=6946): dangar, dangara, dangarb, dangarbt, dangarj: missing black screen between areas (black hole warp)
- [07493](https://mametesters.org/view.php?id=7493): dangar, dangara, dangarb, dangarj, galivan, galivan2, galivan3: Some text displays red, but actial is white
- Fixed corrupt title logo of dangar.
> galivan.cpp : Add hide text layer support, and fix text color attlibute

- src/mame/drivers/vt1682.cpp
also, please credit BeckyRGB in the whatsnew for the promotions
> vt1682 - swap bg pen fallthrough for boxing, adjust render/latching timing slight, correct spellings

- src/mame/drivers/segas16a.cpp
- src/mame/drivers/segas16b.cpp
- src/mame/includes/segas16a.h
- src/mame/includes/segas16b.h
Move dfjail related handlers/variables into dfjail_state, related to sound hardware differs
> segas16a.cpp, segas16b.cpp : Add save state, Partially fix reset behavior

- src/devices/bus/spectrum/mface.cpp
zx spectrum multiface 1 slot device: new rom from a Brazilian clone unit.
> mface.cpp: new dump

- src/mame/drivers/vii.cpp
- src/mame/drivers/vt1682.cpp
- src/mame/mame.lst
-------
Zone 40 [David Haywood, BeckyRGB]
Zeus IG900 20-in-1 (US?) [David Haywood, Sean Riddle]
surprisingly zone40 games are ports of the vt1682 games to SunPlus hardware, not a 6502 based platform
Zeus IG900 20-in-1 state hasn't changed, but none of the bugs are critical, so I've promoted that.
> machines promoted to WORKING  (Plug & Play / SunPlus - Zone 40)

- src/mame/drivers/at.cpp
- src/mame/drivers/bw12.cpp
- src/mame/drivers/pc.cpp
- src/mame/mame.lst
added German Bondwell BW-14 and AEG Olympia Olyport 40-21 (Zenith SuperSport 286)
> new CP/M and DOS computer BIOS versions

- scripts/target/mame/mess.lua
- src/mame/drivers/lexibook_jg7425.cpp
- src/mame/mame.lst
- src/mame/mess.flt
---
Lexibook JG7425 221-in-1 [TeamEurope]
> new NOT WORKING machines (Lexibook)

- hash/fmtowns_flop.xml
- Added alt_titles for most entries
- Added three new entries to the softlist, all dumped by me from the original disks and working:
DOR
DOR Part 3
Elle
> fmtowns_flop.xml: additions, alt_titles

- src/mame/drivers/armedf.cpp
- src/mame/drivers/galivan.cpp
(It is split off from #5996)
youma, ninjemak
- https://www.nicovideo.jp/watch/sm4519702
- https://www.nicovideo.jp/watch/sm4520007
kozure
- https://www.nicovideo.jp/watch/sm4186904
armedf
- https://www.nicovideo.jp/watch/sm4175795
legion
- https://www.nicovideo.jp/watch/sm7128742
ccrimbr2
- https://www.nicovideo.jp/watch/sm4174557
danger
- https://www.nicovideo.jp/watch/sm7129509
galivan
> galivan.cpp, armedf.cpp : Adjusted Some games DAC gain compared with PCB movies.

- src/mame/drivers/esd16.cpp
- src/mame/includes/esd16.h
- src/mame/mame.lst
new machines NOT WORKING
-----
Fantasy Story [David Haywood, caius, The Dumping Union]
technically it's fully playable, but since there's no sound I've left it as NOT WORKING for now, as first impressions will be bad, sound is driven by a PIC.
> new machines NOT WORKING  (Fantasy Story)

- hash/gcslottv.xml
- scripts/target/mame/mess.lua
- src/mame/drivers/generalplus_gpl32612.cpp
- src/mame/drivers/nes_vt.cpp
- src/mame/drivers/spg110.cpp
- src/mame/drivers/sunplus_gcm394.cpp
- src/mame/drivers/vii.cpp
- src/mame/drivers/vt1682.cpp
- src/mame/drivers/xavix.cpp
- src/mame/includes/xavix.h
- src/mame/mame.lst
----
Gachinko Contest! Slot machine TV (Japan) [Sean Riddle, Peter Wilhemsen, ShouTime, David Haywood] (actually, no BIOS is dumped yet, but this means the carts don't have to be orphaned)
Shredmaster Jr (NTSC) [Sean Riddle, David Haywood]
Golden Tee Golf (JAKKS Pacific TV Game) [Sean Riddle, David Haywood]
Cars 2 (JAKKS Pacific TV Game) [Sean Riddle, David Haywood]
Toy Story Mania (JAKKS Pacific TV Game) [Sean Riddle, David Haywood]
V.Baby [Sean Riddle, Clawgrip]
Playskool Heroes Transformers Rescue Bots Beam Box (Spain) [Sean Riddle, Clawgrip]
Virtual Ping Pong (Conny / SDW Games) [Sean Riddle, David Haywood]
Konami Collector's Series Arcade Advanced [Sean Riddle, David Haywood]
Teenage Mutanat Ninja Turtles Hero Portal [Sean Riddle]
Star Wars Blaster Strike [Sean …
> new sets from Sean Riddle, mostly NOT WORKING for now

- hash/gameking.xml
- hash/gameking3.xml
new SOFTWARE LIST entries
-----
gameking.xml : 4 in 1 - Chaser + Blaster + StarWars + Nagual (set 2) [sCZther, TeamEurope]
gameking3.xml : Falcon Corps [sCZther, TeamEurope]
gameking3.xml : Search Action [sCZther, TeamEurope]
gameking3.xml : Vagrant [sCZther, TeamEurope]
- added some metadata about cartrridge types to GameKing lists [TeamEurope]
> new SOFTWARE LIST entries (GameKing / GameKing3)

- hash/pico.xml
These were dumped by Demon in 2016 and released on Assembler.
> pico.xml - Add Muppets on the Go protos found in 2016

- hash/tvgogo.xml
- src/devices/cpu/unsp/unsp.cpp
- src/devices/cpu/unsp/unsp.h
- src/devices/cpu/unsp/unsp_extended.cpp
- src/devices/cpu/unsp/unsp_exxx.cpp
- src/devices/cpu/unsp/unsp_fxxx.cpp
- src/devices/cpu/unsp/unspdasm.cpp
- src/devices/cpu/unsp/unspdasm_extended.cpp
- src/devices/cpu/unsp/unspdasm_other.cpp
- src/mame/drivers/generalplus_gpl32612.cpp
- src/mame/drivers/nes_vt.cpp
- src/mame/drivers/sunplus_gcm394.cpp
- src/mame/drivers/vii.cpp
- src/mame/mame.lst
new WORKING clone
----
200 in 1 Retro Arcade [eanbowman]
+ general preparation for further unsp20 based stuff since the NAND games actually use the extra registers etc.
> Plug and Play work + New Working clone

- hash/pico.xml
- hash/sawatte.xml
> pico.xml/sawatte.xml - Add more scans of book pages

- hash/pico.xml
These are from TeamEurope, just like the ROM dump.
> pico.xml - Add book pages to anpanwpk

- hash/clickstart_cart.xml
- hash/iqunlim_cart.xml
- scripts/target/mame/mess.lua
- src/mame/drivers/iqunlim.cpp
- src/mame/drivers/nes_vt.cpp
- src/mame/drivers/vt1682.cpp
- src/mame/machine/vt1682_uio.cpp
- src/mame/machine/vt1682_uio.h
- src/mame/mame.lst
----
InterAct Complete Video Game - 111 Games & 42 Songs (G5410) [TeamEurope]
Let's Play! Game Machine 240 in 1 [TeamEurope]
----
MiWi2 7-in-1 Sports [David Shah]
new NOT WORKING Software List
----
iqunlim_cart.xml: Englisch für Anfänger [TeamEurope]
note: the VT1682 based InterAct Complete Video Game is basically playable, apart from the 'Shooting games' because I haven't mapped the guns, and some issues with player 2 / alt control schemes in some titles.   want to address these (and maybe look for a better solution to some stability issues) before promoting it.
> Plug and Play sync for TeamEurope (VT1682, nes_vt, iqunlim)

- hash/megadriv.xml
Dumped by drx.
https://hiddenpalace.org/Sonic_the_Hedgehog_2_(Aug_21,_1992_prototype)
https://hiddenpalace.org/Sonic_the_Hedgehog_2_(Sep_14,_1992_prototype)
> megadriv.xml - Add two new Sonic 2 protos

- hash/snes.xml
Dump by drx.
https://hiddenpalace.org/Mr._Tuff_(Dec_5,_1994_prototype)
> snes.xml - Replace Mr Tuff with proper redump

- hash/snes.xml
Dumped by Radar.
https://hiddenpalace.org/Earthworm_Jim_(Aug_4,_1994_GameMaster_prototype)
https://hiddenpalace.org/Earthworm_Jim_(Aug_19,_1994_prototype)
>  snes.xml - Add new Earthworm Jim prototype dump and document another

- hash/n64.xml
Dumped by Paulweeze71.
https://hiddenpalace.org/007:_The_World_is_Not_Enough_(Prototype)
> n64.xml - Add 007: The World is Not Enough proto

- hash/snes.xml
Dumped by Baker64.
https://hiddenpalace.org/Arcade%27s_Greatest_Hits:_The_Atari_Collection_1_(Feb_10,_1997_prototype)
> snes.xml - Add Missile Command

- hash/snes.xml
Dumped by Togemet2.
https://hiddenpalace.org/Super_Nova_(prototype)
> snes.xml - Add Super Nova proto

- hash/snes.xml
Dumped by Togemet2.
https://hiddenpalace.org/Arcana_(prototype)
> snes.xml - Add Arcana (prototype)

- hash/c64_cass.xml
> c64_cass.xml - Add some new dumps

- src/mame/drivers/ms32.cpp
P-47 Aces ROM comments verified
> Correct comments in ms32 driver

- src/devices/cpu/unsp/unsp_exxx.cpp
- src/devices/machine/sunplus_gcm394.cpp
- src/devices/machine/sunplus_gcm394.h
- src/devices/machine/sunplus_gcm394_video.cpp
- src/devices/machine/sunplus_gcm394_video.h
- src/mame/drivers/sunplus_gcm394.cpp
includes being able to render the 'bitmap test' in service mode (which is software generated in RAM)  appears to point at me needing to fix a few more things tho.
> a few bits for jak_car2

- hash/c64_cass.xml
Actually, this contains a Visiload T3 loader and a Visiload T1 loader on the other side.
> c64_cass.xml - Update bmxracersa3

- src/devices/video/psx.cpp
fixes sync issues regarding beatmania IIDX games
> NTSC mode to set refresh rate to 59.82 for 240 and 59.94 for 480

- plugins/hiscore/init.lua
will handle multiple spaces correctly
> made read_config in hiscore lua plugin more robust

- src/devices/sound/2612intf.cpp
- src/devices/sound/2612intf.h
- src/mame/drivers/fmtowns.cpp
fmtowns.cpp : Add notes for sound chip
> sound/2612intf.cpp : Add YMF276 device, Clamp output related to internal 9-bit DAC, Add notes

- src/devices/machine/microtch.cpp
(nw) It would be nice to at least load the already dumped BIOS ROMs (v5.5 and v5.6 AFAIK), just for preservation.
> microtch.cpp: Add notes and ISA board layout (nw)

- hash/c64_cass.xml
> c64_cass.xml - Add Sweep

- src/devices/machine/vrender0.cpp
- src/devices/machine/vrender0.h
- src/devices/sound/vrender0.cpp
- src/devices/sound/vrender0.h
This reverts commit b90eb659e8c96f50a036344020b9d1314beb55b0.
> Revert "VRender0 Sound Engine Fixes, Improves (#6112)"

- src/lib/formats/img_dsk.cpp
- src/lib/formats/img_dsk.h
Hi,
this PR adds the "save" capability to the IMG floppy format which I left out in the previous PR (see #6119).
I've also added a proper interleaving to sectors to speed r/w up considerably.
Thanks.
--F.Ulivi
> imds2: implemented save in IMG disk format

- src/mame/drivers/docastle.cpp
These sets have been broken for over 6 years now - see https://mametesters.org/view.php?id=5419
> docastle.cpp: flagged asoccer and idsoccera as NOT WORKING (nw)

- hash/a800_cass.xml
- src/mame/drivers/atari400.cpp
> Add Atari 400/800 cassette list

- hash/apple2_flop_clcracked.xml
- hash/apple2_flop_orig.xml
Also includes a very minor cleanup on a couple of softlist entries.
> Apple II update to January 10th, 2020.

- hash/leapfrog_ltleappad_cart.xml
- src/devices/machine/sunplus_gcm394.cpp
- src/devices/machine/sunplus_gcm394_video.cpp
- src/devices/machine/sunplus_gcm394_video.h
- src/mame/drivers/leapfrog_leappad.cpp
- src/mame/drivers/sunplus_gcm394.cpp
- src/mame/drivers/vt1682.cpp
- src/mame/mame.lst
----
Zone 7-in-1 Sports (US) [Sean Riddle, David Haywood]
Excite Sports Wireless Interactive TV Game - 48-in-1 (US) [Sean Riddle, David Haywood]
----
Little Touch LeapPad [Sean Riddle, Clawgrip]
> Plug and Play work

- hash/a800_cass.xml
Add Zaxxon dumps from AtariMania.
http://www.atarimania.com/game-atari-400-800-xl-xe-zaxxon_5914.html
http://www.atarimania.com/game-atari-400-800-xl-xe-zaxxon_6093.html
> a800_cass.xml - Add Zaxxon

- src/mame/drivers/teamjocs.cpp
- src/mame/mame.lst
(nw) Team Jocs is the hardware type, the game is "Diana Elite", see http://www.recreativas.org/diana-elite-5664-recreativos-presas for details.
> teamjocs.cpp: Rename "Team Jocs" to "Diana Elite" (nw)

- hash/apple2_flop_clcracked.xml
corrected some clearly wrong years and confirmed them from the titlescreens
> spectrum_cass, apple2_flop_clcracked: year corrections (nw)

- src/frontend/mame/luaengine.cpp
_Removed outdated description._
> luaengine: addr_space:read_range()

- src/devices/cpu/gigatron/gigatron.cpp
- src/mame/drivers/gigatron.cpp
> gigatron: hook up screen, change machine type

- hash/apple2_flop_clcracked.xml
- hash/apple2_flop_orig.xml
Hopefully we can get this in before freeze.
> Late January Apple II update.

- hash/c64_cass.xml
> c64_cass.xml - Add two new dumps

- hash/gameboy.xml
- hash/nes.xml
- hash/snes.xml
fix miscellaneous clones, non-clones, typos, and a software name error
> gameboy.xml, nes.xml, snes.xml

- hash/buzztime_cart.xml
- src/devices/bus/nes_ctrl/ctrl.cpp
- src/devices/bus/nes_ctrl/ctrl.h
- src/devices/bus/nes_ctrl/joypad.cpp
- src/devices/bus/nes_ctrl/joypad.h
- src/mame/drivers/mastboyo.cpp
- src/mame/drivers/nes_vt.cpp
- src/mame/drivers/spg2xx_lexibook.cpp
- src/mame/drivers/xavix.cpp
- src/mame/includes/nes.h
- src/mame/mame.lst
-----
Disney Game It! Classic Pals [Sean Riddle, David Haywood]
Champiyon Pinball (Japan) [Sean Riddle, Peter Wilhelmsen, ShouTime, David Haywood]
new WORKING clone
-----
Master Boy (1987, Z80 hardware, Ichi-Funtel) [Juan Romero, ClawGrip]
new NOT WORKING software list entry
-----
buzztime_cart.xml: Series 1 - Everything [Sean Riddle, David Haywood]
- start refactoring some nes_vt stuff (don't force non-nes controllers through the nes controller bus, and thus untangle nes_vt from nes.cpp, the controllers don't comform to the standard anyway)
> misc Plug and Play work etc.

- hash/ique.xml
- hash/n64.xml
* Add a bunch of new dumps that has popped up over the years.
* Replace a few old bad dumps with redumps.
* Add a lot more PCB documentation.
* Add the beginning of an iQue softlist.
> n64.xml: Rework the N64 softlist

- src/mame/drivers/gb.cpp
- src/mame/mame.lst
Also, please note that the credit for this game (David's previous commit) is [Sean Riddle, ClawGrip] and not just [Sean Riddle]. Thx!!
> Fix Mega Duck description (nw)

- scripts/target/mame/mess.lua
- src/mame/drivers/nes_sh6578.cpp
- src/mame/drivers/nes_vt.cpp
- src/mame/drivers/spg2xx.cpp
- src/mame/includes/spg2xx.h
- src/mame/mame.lst
----
Guitar Fever (2007.07.03 Ver 2.7) [TeamEurope, Peter Wilhelmsen, David Haywood]
has timer issues making the music way too slow
Atari Flashback Mini 7800 [Sean Riddle, GameHistory.org]
City Patrolman [unknown]
> Plug & Play work

- src/devices/bus/msx_cart/moonsound.cpp
- src/devices/sound/ymf262.cpp
- src/devices/sound/ymf262.h
- src/devices/sound/ymf278b.cpp
- src/devices/sound/ymf278b.h
- src/mame/drivers/fuukifg3.cpp
- src/mame/drivers/psikyo4.cpp
- src/mame/drivers/vgmplay.cpp
ymf262.cpp : Support clock divider difference
vgmplay.cpp : Fix YMF278B volume
> ymf278b.cpp : Fix output rate and clock divider of FM part, Fix mixing behavior

- src/devices/bus/ss50/dc5.cpp
Add the OS9, MFI and UniFlex floppy formats. Update the debug config
options to suit OS9. Single density track zero on OS9 is typically
only on the first side, unlike FLEX which used single density track
zero on both sides. Clarify some of the FLEX specific debug
options. Fix some bugs in the logic related to these options.
> SS50 DC5 FDC: OS9 support, misc corrections.

- hash/c64_cass.xml
> c64_cass.xml: Add new dumps.

- src/devices/bus/isa/gus.cpp
- src/devices/bus/isa/sblaster.cpp
- src/mame/drivers/hp95lx.cpp
gus: active channels are numbered from 0 (nw)
hp95lx: add DAC (nw)
> sblaster: support more playback commands (nw)

- src/devices/sound/ics2115.cpp
- src/devices/sound/ics2115.h
- src/mame/drivers/igs011.cpp
- src/mame/drivers/igs_fear.cpp
- src/mame/drivers/pgm.cpp
ics2115.cpp : Calculated sample rate related to clock, Activated voice numbers, Add notes
> Calculated actual ICS2115 sample rate

- hash/c64_cass.xml
- hash/c64_flop_orig.xml
https://www.pagetable.com/docs/input64/
> c64_cass.xml/c64_flop_orig.xml: Add all coverdisks/tapes from Input64

- hash/hp86_rom.xml
- src/devices/cpu/capricorn/capricorn.cpp
- src/devices/cpu/capricorn/capricorn.h
- src/mame/drivers/hp80.cpp
- src/mame/layout/hp86b.lay
- src/mame/mame.lst
Hi,
this commit adds the emulation of HP-86B system.
I'm going to mail the relevant ROM images to code e-mail soon.
Thanks.
--F.Ulivi
> HP86B added

- hash/ibm5170.xml
> ibm5170.xml: Add new dump

- hash/telestory_cart.xml
- src/mame/drivers/generalplus_gpl32612.cpp
- src/mame/drivers/raiden2.cpp
- src/mame/drivers/spg2xx.cpp
- src/mame/drivers/spg2xx_dreamlife.cpp
- src/mame/drivers/sunplus_unsp20soc_mobigo.cpp
- src/mame/includes/spg2xx.h
- src/mame/mame.lst
new WORKING clone
---
Raiden II (easier, US, prototype? 11-16) [neSneSgB]
-- see https://shmups.system11.org/viewtopic.php?f=6&t=66065
---
Designer's World (Version 1.0, Dec 20 2005) [Sean Riddle, David Haywood]
new NOT WORKING machine
---
Dream Life Superstar (Version 0.3, Mar 16 2007) [Sean Riddle, David Haywood]
DreamWorks Dragons Hero Portal [Sean Riddle, David Haywood]
MobiGo [Sean Riddle, Clawgrip]
-----
telestory_cart.xml [Sean Riddle, TeamEurope]
SponegeBob SquarePants - Ice-Cream Dreams / Stop the Presses! (USA)
Dora the Explorer - At the Carnival / Dora Goes to School (USA)
The Lion King - The Lion King / The Lion King II - Simba's Pride (USA)
Cinderella - Cinderella / Beauties in Bloom (USA)
Winnie the Pooh - Bounce …
> Plug and Play work etc.

- src/mame/video/boogwing.cpp
This commit fixes transporter pilot priority incorrection.
> boogwing.cpp : Further priority acknowledge

- src/mame/drivers/boogwing.cpp
- src/mame/includes/boogwing.h
- src/mame/video/boogwing.cpp
- src/mame/video/deco_ace.cpp
deco_ace.cpp : Add notes, Use fixed point values for palette fading behavior
> boogwing.cpp : Fix tilemap in some final stage effects, Fix palette effect boundary

- hash/vsmile_cart.xml
> Added some missing french carts

- hash/apple2_flop_clcracked.xml
- hash/apple2_flop_orig.xml
Everything that's new from last MAME release until yesterday.
> Apple update for Feb 18th, 2020

- hash/ibm5150.xml
> ibm5150.xml: Add new dump

- scripts/src/cpu.lua
- src/devices/cpu/z80/lz8420m.cpp
- src/devices/cpu/z80/lz8420m.h
- src/mame/drivers/psikyo.cpp
It has Z80 with additional IO, Embedded RAM
Used in psikyo.cpp
> Add skeleton LZ8420M device

- hash/pi_storyreader_cart.xml
-----
pi_storyreader_cart.xml [TeamEurope]
Cars (Germany)
Das Dschungel-Buch (Germany)
Der Konig der Lowen (Germany)
Findet Nemo (Germany)
Peter Pan (Germany)
Winnie Puuh - Ein sturmischer Tag (Germany)
Winnie Puuh hat keinen Hunger (Germany)
> new NOT WORKING software list entries

- src/mame/drivers/spg2xx_lexibook.cpp
- src/mame/mame.lst
---
VG Pocket Caplet Fast Acting 50-in-1 [Sean Riddle, David Haywood, Ryan Holtz]
> new WORKING machine (Plug and Play)

- src/mame/drivers/m10.cpp
Support new ROM dump.  Not yet playable, but attract mode runs and can be coined up
> m10: Add support for missing greenber ROM gb7

- src/mame/drivers/boogwing.cpp
- src/mame/drivers/deco32.cpp
- src/mame/includes/boogwing.h
- src/mame/video/boogwing.cpp
- src/mame/video/deco16ic.cpp
- src/mame/video/deco32.cpp
- src/mame/video/deco_ace.cpp
- src/mame/video/deco_ace.h
boogwing.cpp : Fix priority with alternative palette fading, Fix palette effects
deco32.cpp : Add notes, nslasher : Fix palette effects, Background color, Fix sprite drawing behavior
deco16ic.cpp : Fix drawing behavior with 16bit indexed bitmap
deco_ace.cpp : Split palette area
> Improve mixing behavior related to DECO ACE chip

- hash/ibm5150.xml
Made from Kryoflux dump by Flyers80.
> ibm_5150.xml: Add 3.5'' Menace

- src/mame/drivers/deco32.cpp
- src/mame/includes/deco32.h
- src/mame/video/deco16ic.cpp
- src/mame/video/deco16ic.h
- src/mame/video/deco32.cpp
- src/mame/video/deco_ace.cpp
Add notes, Implement runtime color bank changes, Reduce duplicates
deco_ace.cpp : Add notes for alpha value usage
deco16ic.cpp : Implement runtime color bank changes, Fix 8bpp color base
> deco32.cpp : Improve blending behavior for Tattoo Assassins

- src/devices/sound/x1_010.cpp
- src/devices/sound/x1_010.h
Fix spacing, Reduce unused, unnecessary lines, Add / Fix notes, Use shorter / correct type values
> x1_010.cpp : Accurate frequency calculation, Minor cleanups

- src/mame/video/deco32.cpp
Sprite1 pri 2 vs Sprite2 pri 1 priority is changeable related to m_pri value
> deco32.cpp : Fix wheel vs hospital wall priority

- hash/st_flop.xml
> st_flop.xml: Add Leviathan

- hash/st_flop.xml
> st_flop.xml: Add Striker

- hash/st_flop.xml
> st_flop.xml: Add 1943

- hash/st_flop.xml
> st_flop.xml: Add Track Suit Manager

- hash/ibm5150.xml
Made from Kryoflux dump by flyers80.
> ibm5150.xml: Add Moonwalker

- hash/ibm5150.xml
Made from Kryoflux dump by flyers80.
> ibm5150.xml: Add Conflict

- src/mame/drivers/1945kiii.cpp
Acknowledge VRAM access toggle behavior, Implement sprite limitation per frame, Add notes, Convert screen parameters into raw format
> 1945kiii.cpp : Hardware notes, Implement some behavior

- hash/st_flop.xml
> st_flop.xml: Add Smash 16 version of Spidertronic

- hash/apple2_cass.xml
> apple2_cass.xml: Add Puck Man

- hash/apple2_cass.xml
> apple2_cass.xml: Add 四人麻雀

- hash/amigaocs_flop.xml
> amigaocs_flop.xml: Add 16 Bit Komix

- hash/pasopia_cass.xml
- src/mame/drivers/pasopia.cpp
Software is dumped by Gaming Alexandria.
Any help with the Japanese is appreciated.
> Add softlist for pasopia

- hash/ibm5150.xml
Made from Kryoflux dump by Flyers80.
> ibm5150.xml: Add Fiendish Freddy's Big Top o' Fun

- hash/ibm5150.xml
Made from Kryoflux dump by Flyers80.
> ibm5150.xml: Add Baal

- hash/ibm5150.xml
Made from Kryoflux dumps by Flyers80.
> ibm5150.xml: Add D/Generation

- hash/ibm5150.xml
Made from Kryoflux dump by Flyers80.
> ibm5150.xml: Add Go Simulator

- hash/ibm5150.xml
Dyna Blaster, Test Drive III - The Passion, Martian Memorandum, The Secret of Monkey Island (5.25", EGA version), The Secret of Monkey Island (3.5", EGA version)
> ibm5150 - New working software list additions

- hash/ibm5170.xml
Another World, The Lost Vikings, The Humans (3.5" DD), The Humans (5.25" HD)
> ibm5170 - New working software list additions

- hash/ibm5170.xml
> ibm5170 - New working software list addition

- hash/compis.xml
TD0 dumps by David Karlström.
MFM dumps made by me.
> compis.xml: Add new dumps and update

- hash/apple2_flop_clcracked.xml
- hash/apple2_flop_orig.xml
The rest of the cleanly cracked disks probably won't be ready by freeze, so those can wait until next month.
> The rest of the WOZ files for North Dakota

- src/mame/drivers/cave.cpp
- src/mame/includes/cave.h
- src/mame/video/cave.cpp
- src/mame/video/tmap038.cpp
- src/mame/video/tmap038.h
Fix sprite position handling related to videoregs
Fix tilemap offsets in ppsatan
Fix logging
> cave.cpp : Log unimplement videoregs, Add notes

- hash/ibm5150.xml
From Kryoflux dumps by flyers80.
> ibm5150.xml: New dumps

- hash/n64.xml
> Added Viewpoint 64 prototype

- src/mame/drivers/psikyo.cpp
- src/mame/includes/psikyo.h
- src/mame/video/psikyo.cpp
Move dynamic tilemap size behavior into TILEMAP_MAPPER_MEMBER
Correct notes, VRAM/Sprite LUT data type, convert drawing behavior into bitmap_rgb32
> psikyo.cpp : Update and Minor cleanup drawing behavior

- hash/fmtowns_cd.xml
Advantage Tennis
Alice no Yakata CD
Asuka 120% Burning Fest. Excellent
Awesome
Classic Road
Fractal Engine Demo
Hyper Address (HMB-106)
Infestation - Chinmoku no Wakusei
Loom (audio drama CD)
Oshare Cooking II
Sangokushi III
Software Contest Nyuusen Sakuhinshuu 2
Sotsugyou '93 - Graduation
Super Shanghai - Dragon's Eye
Takamizawa Kyousuke - Nekketsu!! Kyouiku Kenshuu
TDF - Terrestrial Defense Force
Towns Magazine Vol. 2
The 4th Unit 5 - D-Again (Demo)
Air Warrior V2.1L10
Ehon Writer - Denshi Ehon - Aesop World Dai-1-shuu
GEdit Towns
Hyper Address (HMB-106A)
Kotoba Asobi - CDView HiP Catch
Kanji Land 3-nen
Lord of the Rings, …
> fmtowns_cd.xml: 17 replacements, 16 additions, 2 new floppy dumps

- src/mame/drivers/nmk16.cpp
- src/mame/includes/nmk16.h
- src/mame/video/nmk16.cpp
reference : https://www.youtube.com/watch?v=lljCeUfCMDQ (Live stream)
> nmk16.cpp : Implement sabotenb vertical scrolling, noticeable when explosion occurs

- hash/ibm5150.xml
- hash/ibm5170.xml
Harpoon Battleset 2 - North Atlantic Convoys, The Software Toolworks Game Pack 3 & Jurassic Park made from Kryoflux dumps by Flyers80
Leisure Suit Larry 2 & Pepper's Adventures in Time from Kryoflux dumps by Gypsy Dave.
> ibm5150/5170.xml: Add new dumps

- src/mame/drivers/dec0.cpp
- src/mame/drivers/dec8.cpp
- src/mame/drivers/madmotor.cpp
- src/mame/includes/dec0.h
- src/mame/includes/dec8.h
- src/mame/video/actfancr.cpp
- src/mame/video/dec0.cpp
- src/mame/video/dec8.cpp
- src/mame/video/decbac06.cpp
- src/mame/video/decbac06.h
- src/mame/video/pcktgal.cpp
- src/mame/video/stadhero.cpp
- src/mame/video/thedeep.cpp
Convert pen masking feature into set_transmask behavior, Add notes, Reduce duplicates, unneeded values
dec0.cpp: Reduce duplicates, Move shared video_start under protected: section
madmotor.cpp: Cleanup gfx layouts
> decbac06.cpp Update drawing behavior, Use tile callback

- src/mame/drivers/ddealer.cpp
- src/mame/drivers/nmk16.cpp
- src/mame/drivers/patapata.cpp
- src/mame/drivers/quizpani.cpp
- src/mame/includes/nmk16.h
- src/mame/video/nmk16.cpp
- src/mame/video/powerins.cpp
- src/mame/video/quizpani.cpp
nmk16.cpp : Reduce unused
quizpani.cpp : Fix visible area (same as nmk16.cpp?)
patapata.cpp, ddealer.cpp : Use generic gfx layout
> Use scrolldx for tilemap shifting in some NMK hardwares

- hash/fmtowns_cd.xml
- Replaced entries with dumps from the redump.org database:
Free Software Collection 6
Free Software Collection 7
Free Software Collection 8
Free Software Collection 9
Free Software Collection 10
Free Software Collection 11
Freeware Collection 2
Freeware Collection 3
Golf Links 386 Pro
Psychic Detective Series Vol. 5 - Nightmare
Towns System Software V1.1L30
Viewpoint
Gadget - Invention, Travel, & Adventure
Virtuacall 2
- Started to re-convert some pre-0.175 CHDs with current CHDMAN (see GitHub issue #2517). I'm starting with the Redump ones (and Neo Kobe ones that match Redump), the rest will come later:
Air Combat II Special
Dangel
DOR Best Selection Joukan
DOR Special Edition '93
F-BASIC386 v1.1 L20
Galaxy Force II
Hyper Ocean …
> fmtowns_cd.xml: 2 additions, 12 replacements, first wave of CHD re-conversion

- src/mame/drivers/fcrash.cpp
- src/mame/includes/fcrash.h
wofabl: return to old (bad) gfx rom 12 (see #6556 comments)
both games:
remove eeprom device (real pcbs have 3x8pos dipsw, no eeprom)
add some dip switch settings
fix player 3 inputs
minor priority tweak
> some wofabl, sgyxz fixes

- hash/ibm5150.xml
> ibm5150 - New working software list addition

- src/mame/drivers/cps1bl_pic.cpp
- src/mame/drivers/fcrash.cpp
- src/mame/includes/fcrash.h
- src/mame/mame.lst
- src/mame/video/cps1.cpp
add wofr1bl, very similar to wofpic but with usual z80/ym/oki sound h/w instead of pic
tweak wofpic bit more, more priority issues fixed
fcrash, cps1bl_pic source tidy-up
> add another wof bootleg set

- src/mame/drivers/spg2xx.cpp
- src/mame/mame.lst
----
Teenage Mutant Ninja Turtles: Battle for the City [Sean Riddle, Kamaal Brown]
> Plug and Play work (new WORKING machine)

- src/mame/drivers/galaga.cpp
- src/mame/machine/namco06.cpp
> Namco custom fix

- hash/compis.xml
> compis.xml: Five new dumps

- src/devices/machine/tms9914.cpp
This PR is for a minor change to tms9914 driver. I simplified a bug fix by @usernameak.
--F.Ulivi
> tms9914: simplify handling of CIDS state

- hash/cgenie_cass.xml
@pullmoll sorry but I am a stalker :grin:
> cgenie_cass.xml: Some nits

- src/mame/drivers/gs6502.cpp
- src/mame/drivers/gs6809.cpp
- src/mame/drivers/gscpm.cpp
- src/mame/drivers/gsz80.cpp
- src/mame/mame.lst
See http://searle.wales/ for details.  Drivers are gsz80, gscpm, gs6502, and gs6809.
> Drivers (4) for Grant Searle's Simple machines (Z80, CP/M, 6502, and 6809)

- src/devices/sound/c140.cpp
- src/devices/sound/c140.h
- src/mame/drivers/gal3.cpp
- src/mame/drivers/namcona1.cpp
- src/mame/drivers/namcos2.cpp
- src/mame/drivers/namcos21.cpp
- src/mame/drivers/namcos21_c67.cpp
- src/mame/drivers/namcos21_de.cpp
- src/mame/drivers/vgmplay.cpp
- src/mame/includes/namcona1.h
- src/mame/includes/namcos2.h
- src/mame/machine/namcos2.cpp
> Revert "c140.cpp: Update data bus behavior and support 12 bit PCM, Verified from assault(namcos2) schematics"

- hash/sgi_mips.xml
> sgi_mips.xml: Typo (nw)

- scripts/src/bus.lua
- src/devices/bus/coco/coco_multi.cpp
- src/devices/bus/coco/coco_ram.cpp
- src/devices/bus/coco/coco_ram.h
- src/mame/drivers/coco12.cpp
- src/mame/drivers/dragon.cpp
Added the cart to the slot system of the CoCo and Dragon.
> CoCo: Added Disto RAM cartridge

- src/devices/machine/mos6551.cpp
- src/mame/drivers/dragon.cpp
- src/mame/includes/dragon.h
This allows the ACIA to talk to the outside world.
> Dragon64: connected ACIA to RS232 system

- src/devices/sound/c352.cpp
- src/devices/sound/c352.h
Add notes, Use shorter/correct type/argument values
> c352.cpp: Allow byte accessing, Modernize save states

- src/mame/drivers/gticlub.cpp
This is to access thunderh's 68k program easier for disassembly. There are no comms however between the main cpu and I/O cpu as that requires proper k056230 emulation. Could this 68k program help a bit in k056230 emulation?
> Add thunderh's I/O M68k stub

- hash/ibm5170.xml
Speed Racer in the Challenge of Racer X, Subwar 2050 - The Underwater Combat Simulation
> ibm5170 New working software list additions

- src/devices/machine/k056230.cpp
- src/mame/drivers/konamigx.cpp
- src/mame/drivers/plygonet.cpp
- src/mame/includes/konamigx.h
Not much else to say besides adding an address map specific to racinfrc.
> 056230 doc updates

- hash/st_flop.xml
Made from Greaseweazle dumps by Mikerochip.
> st_flop.xml: Add Street Fighter II: The World Warrior

- hash/sgi_mips.xml
Also update publisher for some entries.
> sgi_mips: new software list additions

- hash/compis.xml
> compis.xml: add seven more dumps

- hash/ibm5150.xml
> ibm5150: New working software list addition

- hash/ibm5170.xml
ibm5170: New working software list additions
Roberta Williams' Laura Bow in "The Dagger of Amon Ra", Leisure Suit Larry 1: In the Land of the Lounge Lizards (VGA release), Leisure Suit Larry 1: In the Land of the Lounge Lizards (EGA release)
> ibm5170: New working software list additions

- hash/ibm5170.xml
> ibm5170: New working software list addition

- hash/x68k_flop.xml
Mostly stuff from a spreadsheet I had from a while. A few things here and there got improved in the meantime.
>  QA a selection of Sharp X68000 SWs (nw) 

- src/mame/drivers/seta2.cpp
- src/mame/includes/seta2.h
- src/mame/video/seta2.cpp
Fix clock for P0-113A PCBs
Fix source file name (.cpp instead .c)
> seta2.cpp: Add notes for hardware configs, emulation issues in some game

- src/mame/drivers/cps1.cpp
> varthb2: mark gfx roms bad_dump

- scripts/src/bus.lua
- scripts/target/mame/mess.lua
- src/devices/bus/qbus/pc11.cpp
- src/devices/bus/qbus/pc11.h
- src/devices/bus/qbus/qbus.cpp
- src/devices/bus/qbus/qbus.h
- src/mame/drivers/pdp11.cpp
- src/mame/includes/pdp11.h
> pdp11: qbus skeleton, pc11

- src/mame/drivers/mc10.cpp
- src/mame/mame.lst
mcx128 MC-10 with MCX-128 expanion [tim lindner]
alice128 Alice with MCX-28 expansion [tim lindner]
> New clones marked as WORKING

- src/mame/drivers/hornet.cpp
- src/mame/video/k037122.cpp
- src/mame/video/k037122.h
hornet.cpp: Add screen raw parameters (verified in both voodoo and K037122 display timing parameters), Add notes
> k037122.cpp: Update hardware information

- src/devices/sound/rf5c68.cpp
- src/devices/sound/rf5c68.h
- src/mame/drivers/segas18.cpp
- src/mame/drivers/segas32.cpp
- src/mame/drivers/system16.cpp
> rf5c68.cpp: Verify default register map, Add notes

- src/devices/bus/ieee488/remote488.cpp
- src/mame/drivers/hp9845.cpp
Hi,
the commits in this PR fixes a couple of bugs:
+ An addressing error in the graphic memory of hp9845c (funny I didn't see it earlier)
+ A signal corruption bug in IEEE488 remotizer
Thanks.
--F.Ulivi
> Bug fixes for hp9845c & remote488

- hash/msx1_cart.xml
> msx1_cart: New working software list addition

- hash/fmtowns_cd.xml
Dracula Hakushaku - Bishoujo-tachi no Chi no Shitatari
Hyper Planet
Lemon Cocktail Collection
Märchen Toshokan - Grimm Douwa - Bremen no Ongakutai
Nihon no Rekishi - Ishin-hen - Kurofune Raikou
Phobos
Towns Chiri - Jigsaw World
Lip 3 - Lipstick Adventure 3
Ballade for Maria
Mobile Suit Gundam - Hyper Desert Operation
Populous & The Promised Lands
SimEarth - The Living Planet
Tunnels & Trolls - Crusaders of Khazan
> fmtowns_cd.xml: 8 new dumps, 5 replacements

- src/mame/drivers/pgm.cpp
Ketsui Arrange adds an option formation change button on button 4, this wasn't available with the ddp3 input setting.
> pgm.cpp: Switch Ketsui Arrange to 4 button input layout

- hash/ibm5150.xml
Both working, and dumped from my original disks. Also tagged the existing ones as cracked.
> ibm5150.xml: add original dumps for Centipede and Ms. Pac-Man

- .travis.yml
Switch Ubuntu build from gcc-9 to gcc-10
Switch macOS build from Xcode 11.0 (macOS 10.14.6) to Xcode 11.5 (macOS 10.15.4)
> Update Travis CI build environments

- src/devices/sound/rf5c68.cpp
- src/devices/sound/rf5c68.h
- src/mame/drivers/segas18.cpp
- src/mame/drivers/segas32.cpp
- src/mame/machine/megacd.cpp
- src/mame/machine/megacd.h
Reference: RF5C68 Datasheet, Mega CD hardware manual PCM sound source
segas18.cpp, segas32.cpp: Add notes for sound chip
megacd.cpp: Correct sound chip variation
> rf5c68.cpp: Implement some chip variant differences, Verify,Implement RF5C164 default register map

- src/devices/sound/okiadpcm.cpp
- src/devices/sound/okiadpcm.h
- src/devices/sound/qs1000.cpp
Fix initial values, Fix descriptions
qs1000.cpp: Add save state related to loop support (disabled currently)
> okiadpcm.cpp: Add looped sample support, Allow reading current output without decoding

- hash/megadriv.xml
Just a couple of observations in the Earthworm Jim (USA) and Streets of Rage 3 (USA) entries, based on no-intro's site and my own cartridges.
Also added a couple of prototypes mentioned in a recent interview with Juan Santos from TecVia.
> megadriv.xml: Added info on some games which require proper dumping

- docs/source/commandline/commandline-all.rst
- docs/source/usingmame/commonissues.rst
**PLEASE READ:**
Here's a first pass at commandline parameter examples.
I'm not expecting this to be to everyone's satisfaction, so it's probably best to let this sit until everyone has had a chance to go through it. I'll fix what issues you find at that point.
In particular, the GLSL stuff is expected to need more work.
This also includes a first pass at VRR information in the FAQ. I plan to revisit this after the main commandline stuff is worked out as I've found some useful information on Blur Busters in regards to VRR's quirks.
> First completed pass of commandline parameters. (nw)

- src/emu/ioport.cpp
- src/emu/ioport.h
I have no idea if this is the best way to fix this. I just wanted to start a discussion.
> Setting analog inputs don't work in LUA

- hash/ibm5170.xml
All working and dumped by me from the original disks.
Gravis UltraSound (GUS) Installation - V2.05
Chuck Yeager's Air Combat (Gravis Ultrasound version)
Dune (3.5")
Frontier - Elite II
> ibm5170.xml: add 4 new dumps

- src/lib/formats/imd_dsk.cpp
- src/lib/formats/imd_dsk.h
Allow to save IMD floppy image disk. Tested on Zorba and Kaypro II
> Add ImageDisk IMD save support

- src/devices/sound/ics2115.cpp
- src/devices/sound/ics2115.h
device_memory_interface for later DMA and DRAM interface support
Allow u-law interpolation (some instrument sound samples in IGS PGM Motherboard sound ROM are u-law)
Add notes, Reduce duplications
> ics2115.cpp: Use device_memory_interface for fetch external samples

- scripts/target/mame/arcade.lua
- src/devices/machine/spg_renderer.cpp
- src/mame/drivers/pengo.cpp
- src/mame/drivers/schick.cpp
- src/mame/drivers/spg2xx.cpp
- src/mame/mame.lst
moved schick out of pengo driver (nw)
-----
Speed Racer (Senario) [Sean Riddle, Kamaal Brown]
Ford Racing [Sean Riddle, David Haywood]
> move schick out of pengo driver + misc promotions

- hash/apple2_flop_clcracked.xml
- hash/apple2_flop_orig.xml
> June 2020 Apple Softlist updates

- src/devices/cpu/gigatron/gigatron.cpp
- src/devices/cpu/gigatron/gigatron.h
- src/mame/drivers/gigatron.cpp
I hooked up the keypad to the CPU, and fixed a plumbing issue with the outx callback.
> Gigatron: a little more meat on the bones

- src/emu/debug/debugcmd.cpp
- src/emu/debug/debugcmd.h
> add saver to operate memory region

- src/devices/sound/k051649.cpp
- src/devices/sound/k051649.h
Modernized save state, Correct type values
> k051649.cpp: Fix frequency behavior

- scripts/src/3rdparty.lua
- scripts/src/main.lua
> Only build asmjit on x86 and x86_64

- hash/vsmile_cart.xml
Disney/Pixar Wall-E (China) [tenyuhuang]
New working software list additions (vsmile_cart.xml)
Les Bisounours - Le monde merveilleux des Bisounours (France) [DisizDream]
Nickelodeon Bob L'éponge - Une journée dans la vie d'une éponge (France) [DisizDream]
> New NOT_WORKING software list additions (vsmile_cart.xml)

- hash/pi_storyreader_cart.xml
Disney Blanca Nieves y los siete enanos (Spain) [TeamEurope, ClawGrip]
Disney El Rey León (Spain) [TeamEurope, ClawGrip]
Walt Disney Peter Pan (Spain) [TeamEurope, ClawGrip]
> New NOT_WORKING software list additions (pi_storyreader_cart.xml)

- hash/leapfrog_mfleappad_cart.xml
Disney/Pixar Cars (Spain) [TeamEurope, ClawGrip]
> New NOT_WORKING software list additions (leapfrog_mfleappad_cart.xml)

- hash/sgi_mips_hdd.xml
Add IRIX 6.2 and rework the comments to be more generic.
> sgi_mips_hdd: new software list additions

- hash/vsmileb_cart.xml
Teletubbies (France) [DisizDream]
>  New NOT_WORKING software list additions (vsmileb_cart.xml)

- hash/vsmilem_cart.xml
Sporti'Folies (France)
Nickelodeon Dora L'Exploratrice - Les adventures de Dora Apprentie Mécano (France) [DisizDream]
DreamWorks Kung Fu Panda - La mission de Po (France) [DisizDream]
Martin Le Dauphin (France) [DisizDream]
Football Challenge (France) [DisizDream]
Toy Story 3 (France) [DisizDream]
Disney/Pixar Cars 2 (France) [DisizDream]
(nw) Also fixed two wrong game serials
> New NOT_WORKING software list additions (vsmilem_cart.xml)

- hash/vsmile_cart.xml
Bianfuxia - Zhengjiu Chengshi (China) [tenyuhuang]
> New working software list additions (vsmile_cart.xml)

- hash/vsmilem_cart.xml
> vsmilem_cart.xml: Fix 'cars2mf' hash (nw)

- scripts/src/formats.lua
- src/lib/formats/mdos_dsk.cpp
- src/lib/formats/mdos_dsk.h
- src/tools/floptool.cpp
Motorola DOS, used on the EXORciser etc. The single sided format has been tested.
> MDOS disk format support

- src/devices/machine/6821pia.cpp
Was not sure if all the log messages should be inhibited when the debugger reads the device, so did not touch some of those.
> 6821pia: guard against side effects when these should be disabled

- hash/mobigo_cart.xml
Dreamworks Shrek - Forever After (US) [TeamEurope]
Disney Princess (USA, alt) [TeamEurope]
Sesame Street - Elmo and Abby - Nature Explorers (USA) [TeamEurope]
Disney/Pixar Brave (USA) [TeamEurope]
Disney Jake and the Neverland Pirates (USA, alt) [TeamEurope]
* Also Fixed 'tbell' hash and sorted the list (nw)
> New NOT_WORKING software list additions (mobigo_cart.xml)

- src/devices/machine/cop452.cpp
Hi, this PR fixes a small problem with timer reloading in cop452.
Thanks.
--F.Ulivi
> hp_ipc: small fix in cop452 driver

- hash/tvgogo.xml
- src/mame/drivers/generalplus_gpl16250_nand.cpp
- src/mame/drivers/nes_vt.cpp
- src/mame/drivers/spg29x_lexibook_jg7425.cpp
- src/mame/drivers/spg2xx.cpp
- src/mame/drivers/spg2xx_pdc.cpp
- src/mame/drivers/spg2xx_wiwi.cpp
- src/mame/includes/spg2xx.h
- src/mame/mame.lst
------
Totally Spies! (France) [TeamEurope, David Haywood]
PDC150 Tactile - Pocket Dream Console (VideoJet, France) [TeamEurope, David Haywood]
PDC200 - Pocket Dream Console (VideoJet, France) [TeamEurope, David Haywood]
Guitar Buster [Sean Riddle, David Haywood]
------
Marvel Avengers TV Game Console (32-bit) (Lexibook) [TeamEurope, David Haywood]
Wireless Duet Play Ping-Pong [Sean Riddle, David Haywood, Dave 'Foxhack' Silva]
tvgogo.xml:
Basketball (US) [Sean Riddle, David Haywood]
> new WORKING machines (plug and play)

- hash/gba.xml
- src/mame/drivers/spg2xx.cpp
- src/mame/includes/spg2xx.h
- src/mame/mame.lst
-----
Wireless Fitness / Dance Fit (Senario) [Sean Riddle, David Haywood, anonymous, Kev (FBN)]
new software list entries 
-----
gba.xml:
Rayman IV (Rayman - Sunshine of Trip) (unlicensed) (protection hacked) [RibShark]
Rayman IV (Rayman - Puteshestviye Solnechnogo Sveta) (unlicensed) (Russian) (protection hacked) [taizou]
Leiman IV - Guangming Zhi Lv (unlicensed) (Chinese) (protection hacked) [侵蚀你的私处]
Super Mario DX (unlicensed) (protection hacked) [taizou]
Chaoji Maliou DX (unlicensed) (Chinese) (protection hacked) [yy小龙虾]
Crash Advance IV  (unlicensed) (protection hacked) [taizou]
Digimon - Ruby and Sapphire (unlicensed) (protection hacked) [taizou]
Pokemon - Sapphire Version (unlicensed) (protection hacked) [taizou]
Sonic 3 - Fighter Sonic (unlicensed) (protection …
> Plug and Play (Wireless Fitness) + some GBA pirate stuff

- src/mame/drivers/cave.cpp
- src/mame/includes/cave.h
- src/mame/video/cave.cpp
Use generic gfx layout for 4bpp tilemap, Reduce duplicates, Unnecessary values
> cave.cpp: Use gfxdecode for sprite decoding

- src/mame/drivers/megaplay.cpp
(nw) Kevin bruteforced the three remaining PLDs, but we cannot make one of them to work on the real PCB, so I've added only the other two (tested working on the real PCB).
> megaplay.cpp: Added two more motherboard PLDs [Kevin Eshbach]

- src/devices/cpu/gigatron/gigatron.cpp
- src/devices/cpu/gigatron/gigatron.h
- src/mame/drivers/gigatron.cpp
Some video generation work was done, along with some stuff for the CPU
> gigatron: some more work

- src/devices/sound/ymz280b.cpp
- src/devices/sound/ymz280b.h
Allow side effects, Reduce unnecessary defines, Use shorter/correct type names, Fix spacings, Add notes
> ymz280b.cpp: Modernize save state, Fix frequency calculation

- src/devices/sound/rf5c400.cpp
- src/devices/sound/rf5c400.h
Add imperfect_features related to unemulated effects and unverified envelope issues
> rf5c400.cpp: Modernized save states, Allow clock changed behavior

- hash/vsmilem_cart.xml
Action Mania (USA, Rev. 4?), Action Mania (USA, Rev. 6?), Action Mania (USA), Sport Games (Netherlands), Sportskanone (Germany), Sporti'Folies (France), Action Mania (Spain), Disney/Pixar Cars - Vollgas in Radiator Springs (Germany), Disney/Pixar Cars - Quatre Roues (France), Disney/Pixar Cars - Acelera el Motor en Radiador Springs (Spain), Disney/Pixar Cars 2 (Germany), Disney/Pixar Cars 2 (France), Disneys Princess Cinderella - Lernen im Marchenland (Germany, Rev. 2?), Disneys Princess Cinderella - Lernen im Marchenland (Germany), Walt Disney Cendrillon - Le reve enchante de Cendrillon (France), Nickelodeon Dora the Explorer - Dora's Fix It Adventure (USA, Rev. 3?), Nick Jr Dora - Dora's Reparatie Avontuur (Netherlands), Nick Dora - Doras …
> Software list items promoted to working (vsmilem_cart.xml)

- scripts/target/mame/arcade.lua
- src/mame/arcade.flt
- src/mame/drivers/bigkarnk_ms.cpp
- src/mame/drivers/mpu4vid.cpp
- src/mame/drivers/nes_clone.cpp
- src/mame/drivers/nes_sh6578.cpp
- src/mame/drivers/nes_vt.cpp
- src/mame/drivers/splash_ms.cpp
- src/mame/mame.lst
--------
Vs Maxx 6-in-1 Casino / Senario Card & Casino Games [Sean Riddle, David Haywood]
--------
Splash (Modular System) [jordigahan, ClawGrip, David Haywood]
--------
Plug and Play Sudoku Game (NES based) [Sean Riddle, David Haywood, GameHistory.org]
- significant work on Modular System version of Big Karnak [David Haywood]
> New Working Machine (Vs Maxx 6-in-1) + Splash Modular System + Plug & Play Sudoku 

- scripts/src/sound.lua
- scripts/target/mame/arcade.lua
- scripts/target/mame/mess.lua
- src/devices/bus/nes/disksys.cpp
- src/devices/bus/nes/disksys.h
- src/devices/sound/rp2c33_snd.cpp
- src/devices/sound/rp2c33_snd.h
bus/nes/disksys.cpp: Implement sound function
test video:https://youtu.be/6Cv_Ytt3pgM
> Implement FDS sound emulation

- hash/ibm5150.xml
Source: https://winworldpc.com/product/pc-ix/10
> ibm5150: add PC/IX

- src/devices/machine/v3021.cpp
- src/devices/machine/v3021.h
Support serial interface, Implement RAM and address commands, use device_rtc_interface for RTC handling, Add notes
> v3021.cpp: Improvement RTC behavior

- src/mame/drivers/mpu4vid.cpp
- src/mame/mame.lst
------
The Crystal Maze (v1.3) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood]
The New Crystal Maze Featuring Ocean Zone (v2.2) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood]
The Crystal Maze Team Challenge (v0.9) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood]
The Mating Game (v0.4) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood]
Adders and Ladders (v2.1) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood]
Strike it Lucky (v0.5) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood]
Barquest (v2.6) (MPU4 Video) [Ryan Holtz, James Wallace, David Haywood]
Tetris Payout (BWB TET1 Version 2.2, set 1) (MPU4 Video)  [Ryan Holtz, James Wallace, David Haywood, Angelo Salese]
Blox (SJM BLOX, 50p/20p Play, Version 2.0) (MPU4 Video) …
> MPU4 Video promotions after some testing / input fixups / set fixups

- src/devices/sound/ics2115.cpp
- src/devices/sound/ics2115.h
based on Jan Klaasen's final burn neo github code
Add notes
> ics2115.cpp: Update envelope behavior, Minor adjusts

- src/mame/drivers/gigatron.cpp
also clean up, and do a bit of work on port OUTX
> gigatron: add DAC

- .appveyor.yml
The build still fails due to issue #6991 but this at least fixes issues caused by changes in msys2 maintainers team.
> Appveyor msys2 workaround

- src/devices/sound/k054539.cpp
- src/devices/sound/k054539.h
related to unverified/unemulated effector and some registers.
> k054539.cpp: Allow side effects, Add imperfect_features

- 3rdparty/sol2/sol/container_usertype_metatable.hpp
- 3rdparty/sol2/sol/function_types.hpp
- 3rdparty/sol2/sol/object.hpp
- 3rdparty/sol2/sol/simple_usertype_metatable.hpp
- 3rdparty/sol2/sol/stack_core.hpp
- 3rdparty/sol2/sol/stack_push.hpp
- 3rdparty/sol2/sol/usertype_metatable.hpp
This PR is a test to see whether or not this commit is enough to fix issue #6991 on AppVeyor's GCC build.
> Fix SOL2 build on GCC 10.2 by working around overload resolution problem

- src/mame/drivers/generalplus_gpl16250_rom.cpp
- src/mame/drivers/nes_sh6578.cpp
- src/mame/drivers/nes_vt.cpp
- src/mame/drivers/spg2xx.cpp
- src/mame/drivers/spg2xx_zone_32bit.cpp
- src/mame/drivers/vt1682.cpp
- src/mame/includes/spg2xx.h
- src/mame/mame.lst
-----
Vs Maxx 10-in-1 Casino / Senario Card & Casino Games [Sean Riddle, David Haywood]
-----
Ordenador-TV (Spain) [ClawGrip, Sean Riddle, David Haywood]
Centro TV de Diseno Artistico [ClawGrip, Sean Riddle, David Haywood]
I'm Game! GP120 (Family Sport 120-in-1) [Sean Riddle, David Haywood]
My Wico Guitar [ClawGrip, Sean Riddle, David Haywood]
unknown VT1682 based 101-in-1 handheld (PAL) [Takashi Omoto / https://twitter.com/takashioomoto , TeamEurope, David Haywood]
Lexibook Compact Cyber Arcade - Paw Patrol [TeamEurope]
> new WORKING machines (Plug Play)

- src/mame/drivers/nes_vt.cpp
- src/mame/drivers/vt1682.cpp
- src/mame/mame.lst
-----
Lexibook Compact Cyber Arcade - Cars [TeamEurope, David Haywood]
NJ Pocket 60-in-1 handheld 'X zero' (NTSC) [Takashi Omoto / https://twitter.com/takashioomoto , TeamEurope, David Haywood]
> new NOT WORKING machines (Plug Play)

- scripts/src/bus.lua
- src/devices/bus/hp9845_io/98036.cpp
- src/devices/bus/hp9845_io/98036.h
- src/devices/bus/hp9845_io/hp9845_io.cpp
Hi,
this PR is for the addition of the 98036 serial I/O module which is an optional I/O module for HP9825 and 9845 systems.
Thanks.
--F.Ulivi
> HP98036 serial I/O module added

- src/mame/drivers/tecmo.cpp
fix missing background tiles on last level.
> silkworm bootleg

- src/devices/video/epic12.cpp
Add notes for commands, Fix spacing
> epic12.cpp: #if instead #ifdef

- scripts/target/mame/ci.lua
Copy-paste of 4b754f0724c208f44dab5c2ba0b33df5d9a88629
> Fix ci build

- src/mame/drivers/seta.cpp
Reference: Japanese Mad Shark flyer
non-english title is for china release?
> seta.cpp: Add notes for madshark title

- src/mame/drivers/seta.cpp
> Revert "seta.cpp: Add notes for madshark title"

- hash/gamate.xml
new WORKING Software List Entry
gamate.xml: Incantational Couple [Peter Wilhelmsen, David Haywood, Morten Kirkegaard]
> new WORKING Software List Entry

- hash/n64.xml
> n64.xml: Fix validation errors

- src/mame/drivers/mrdo.cpp
- src/mame/includes/mrdo.h
- src/mame/mame.lst
Mr. Do! (bootleg) [Juan Romero, ClawGrip]
> New working clones 

- src/mame/drivers/nmk16.cpp
> nmk16.cpp: Fix DMA timing related regression

- src/lib/netlist/plib/palloc.h
See discussion in https://github.com/android/ndk/issues/1339.
> palloc: use posix_memalign with android

- hash/apple2_flop_clcracked.xml
Further cleanup of metadata per Vas's comments on #7112.
> More metadata cleanups on Apple II disks.
