mamedev/mame

src/mame/drivers/photoply.cpp
src/mame/mame.lst

Photo Play 1998 (Spanish) [Victor Fernandez (City Game), ClawGrip]

New machines marked as NOT_WORKING 

---

src/mame/drivers/megadriv_acbl.cpp
src/mame/includes/megadriv_acbl.h
src/mame/mame.lst

-----
Super Bubble Bobble (Sun Mixing, Megadrive clone hardware) [Jorge Silva, David Haywood]

new WORKING machine (Super Bubble Bobble Sun Mixing Megadrive HW)

---

src/mame/drivers/cps1bl_pic.cpp

slampic: dumped pals
dinopic2: dumped missing pal, redumped bad gfx rom, removed MNW flag

Some more cps1 bootleg pals

---

src/mame/drivers/nes_vt.cpp
src/mame/mame.lst

----
Ms. Pac-Man (MSI Plug & Play) [Sean Riddle]
Space Invaders (MSI Plug & Play) [Sean Riddle]

new WORKING machines (Plug & Play)

---

hash/hp9k3xx_cdrom.xml

Also renamed a couple of sets for consistency.

hp9k3xx_cdrom: new software list additions

---

scripts/target/mame/mess.lua
src/mame/drivers/spg2xx_wiwi.cpp
src/mame/drivers/vt_unknown.cpp
src/mame/mame.lst
src/mame/mess.flt

-----
Double Dance Mania: Supreme / Dance Supreme [Sean Riddle, David Haywood, Kamaal Brown]
Double Dance Mania: Mega 12 [Sean Riddle, David Haywood]
-----
My Arcade Wireless Video Game Station 200-in-1 (DGUN-2572) [Sean Riddle, David Haywood]
dgun2572 hardware needs properly identifying, it runs NES games, but seems to run at least some of them at higher resolution, but I'm not finding boot code etc.

new WORKING machines (Plug & Play Double Dance Mania x2)

---

src/mame/drivers/generalplus_gpl_unknown.cpp

these do now appear to be trying to display the 'hardware checksum' text.

some experimental code for pcp8728 / pcp8718 [David Haywood]

---

src/devices/machine/wd33c9x.cpp

hcpu30 operates SCSI chip in DMA mode, but does not have a DMA chip, so the CPU polls DRQ line instead.   delay(1) avoids moving state machine too fast.   firmware also expects SCSI_STATUS_DISCONNECT return code.
cps3 (redearth) seems to work fine with this change, I haven't tested others.

wd33c93: handle 'polled DMA' in vme_hcpu30 (nw)

---

src/mame/drivers/cps1bl_5205.cpp
src/mame/drivers/cps1bl_pic.cpp
src/mame/drivers/midyunit.cpp

dumped various captcommb2, knightsb3, mkyawdim2 pals

few more bootleg pal dumps

---

src/mame/drivers/cps1bl_pic.cpp

add jurassic99 pals

---

hash/ibm5170.xml
hash/ibm5170_hdd.xml

Added a few more labels as well

ibm5170_hdd: new software list additions

---

src/mame/drivers/unk6502_st2xxx.cpp

verification pass needed, no attempt to hook it up properly made

 unk6502_st2xxx.cpp : load preliminary dump of internal ROM for several sets [David Haywood, Sean Riddle]

---

src/devices/machine/generalplus_gpl16250soc.cpp
src/mame/drivers/generalplus_gpl16250.cpp
src/mame/drivers/generalplus_gpl16250_romram.cpp
src/mame/drivers/generalplus_gpl_unknown.cpp
src/mame/drivers/nes_vt.cpp
src/mame/drivers/unk6502_st2xxx.cpp
src/mame/includes/generalplus_gpl16250_romram.h
src/mame/mame.lst

----
Retro Handheld Console 152-in-1 [Sean Riddle, David Haywood]
----
WWE Wrestlemania Steel Cage Challenge (Plug & Play) (set 2) [Sean Riddle]
- set all GPL16250 games to 96Mhz as this seems to be accurate (will look for speedups where possible later) [David Haywood]

Plug & Play work (new NOT WORKING machines)

---

src/mame/drivers/ddealer.cpp

Fix MCU input with side effects
Reduce runtime tag lookup
Reduce duplicates
Use shorter type values
Add/Fix notes
Fix naming

ddealer.cpp: Use tilemap_t for splittable foreground tilemap

---

src/mame/drivers/pgm2.cpp

reference: https://www.youtube.com/watch?v=XOuJtOzx-Fw

pgm2.cpp: Verified kof98umh refresh rate

---

docs/source/usingmame/defaultkeys.rst
src/emu/inpttype.ipp

I'm expecting some need for refinement, so I'll leave this open for the time being.

Docs: Overhaul the default keys list

---

src/devices/machine/generalplus_gpl16250soc.cpp
src/mame/drivers/generalplus_gpl16250_nand.cpp
src/mame/mame.lst

----
Camp Rock Guitar Video Game (JAKKS Pacific TV Game) [Sean Riddle, Team Europe, David Haywood]

new NOT WORKING (plug play)

---

src/mame/drivers/generalplus_gpl_unknown.cpp
src/mame/drivers/nes_vt.cpp
src/mame/mame.lst

----
Handheld Game Console BC-19 - 218 in 1 [Sean Riddle, David Haywood]
Vs. Maxx 17-in-1 [Sean Riddle, David Haywood]
- reworked pcp8718 / pcp8728 / bkid218 to not HLE certain syscalls and to instead use the proper ROM code, removed excessive HLE logging and no longer relevant notes etc..

new NOT WORKING machines (Plug & Play) + replace a bunch of no longer used / needed HLE

---

src/lib/util/bitmap.cpp

This gives better code for modern x86 CPUs:
* It uses SSE to speed up the fill.
* It avoids load dependencies by not using `memcpy`.
* It avoids an extra multiply in `raw_pixptr`.
The only reason I’m doing this as a PR rather than pushing it directly is I’m not sure what it will do for a 32-bit target that doesn’t have some kind of extended vector registers, or how much we care about that situation.

util/bitmap.cpp: Use std::fill_n to get better code for modern CPUs.

---

scripts/src/machine.lua
scripts/target/mame/mess.lua
src/devices/machine/bl_handhelds_menucontrol.cpp
src/devices/machine/bl_handhelds_menucontrol.h
src/mame/drivers/generalplus_gpl_unknown.cpp

- currently functionality isn't 100% understood, but it needs sharing with the lower resolution handhelds, so needs to be a device
- some code cleanups

pcp8718 / pcp8728 / bkid218 - make menu controller a shared device

---

hash/fmtowns_flop.xml

Both working:
386|ASM Tool Kit V1.1
Super Daisenryaku
These are not my own dumps. They were dumped by someone who wants to remain anonymous.

fmtowns_flop.xml: add 2 new dumps

---

src/mame/drivers/nes_vt.cpp
src/mame/machine/nes_vt_soc.cpp
src/mame/machine/nes_vt_soc.h

----
VG Pocket Tablet (VG-4000) [David Haywood]
- nes_vt - fixed logic for external memory / internal mapper selection
- nes_vt - tweak vt control handling

machines promoted to WORKING (Plug and Play, vgtablet)

---

hash/ibm5170.xml

Converted to IMD with `disk-analyze` from the SCP dumps at https://archive.org/details/Doom1BBS (as I don't think MAME supports SCP directly). IMD files are at https://drive.google.com/drive/folders/1thWkdG0ZEtyW19GI7XLpm_w98J5kXtGY?usp=sharing

ibm5170: new software list addition

---

src/mame/drivers/nes_vt.cpp
src/mame/machine/nes_vt_soc.cpp

-----
Konami Collector's Series Arcade Advanced [David Haywood]

machines promoted to WORKING (plug play)

---

src/mame/drivers/segasp.cpp

I used to test it and the sound works similar to NAOMI. Additionally, MACHINE_IMPERFECT_GRAPHICS.

segasp.cpp: Change from MNS to MIS

---

hash/fmtowns_flop.xml

Working:
Metal Blade [CoolFox]
Traffic Confusion [wiggy2k]
Wedding Errantry - Gyakutama Ou [wiggy2k]
Not working:
Bun-kun Series - Youji Kiso Nouryoku Training Soft Set [wiggy2k]

fmtowns_flop.xml: 4 new dumps

---

src/devices/machine/generalplus_gpl16250soc.cpp
src/devices/machine/generalplus_gpl16250soc.h
src/devices/machine/generalplus_gpl16250soc_video.cpp
src/devices/video/ppu2c0x.cpp
src/devices/video/ppu2c0x_sh6578.cpp
src/devices/video/ppu2c0x_vt.cpp
src/mame/drivers/generalplus_gpl16250_rom.cpp
src/mame/drivers/generalplus_gpl32612.cpp
src/mame/drivers/generalplus_gpl_unknown.cpp
src/mame/drivers/nes_sh6578.cpp
src/mame/drivers/nes_vt.cpp
src/mame/drivers/spg2xx_lexibook.cpp
src/mame/mame.lst

------
101 Games in 1 (Senario) [David Haywood, Sean Riddle, Kev (FBN), Kamaal Brown]
Vs Maxx TX-2 50-in-1 [David Haywood, Sean Riddle, Kev (FBN), Kamaal Brown]
Vs Maxx Wireless 77-in-1 [David Haywood, Sean Riddle, Kev (FBN), Kamaal Brown]
Vs Maxx Video Extreme 50-in-1 (with Speed Racer and Snood) [David Haywood, Sean Riddle, Kev (FBN), Kamaal Brown]
VG Pocket Caplet Fast Acting 35-in-1 [David Haywood, Sean Riddle, Kev (FBN), Kamaal Brown]
------
Beijue 16 Bit Handheld Games (Game Boy style case) [David Haywood, Sean Riddle, Kev (FBN), Kamaal Brown]
Space Invaders (Tiny Arcade) [Rik]
Vs Maxx 25-in-1 [David Haywood, Sean Riddle, Kev (FBN), Kamaal Brown]
Vs Maxx 15-in-1 [David Haywood, Sean Riddle, Kev (FBN), Kamaal Brown]
Zippity (US) [David …

Plug and Play work (new sets)

---

src/mame/drivers/nes_vt.cpp
src/mame/mame.lst

-----
Venturer '25 Games' 25-in-1 [David Haywood, Sean Riddle, Kev (FBN), Kamaal Brown]
Turbo GT 50-in-1 [David Haywood, Sean Riddle, Kev (FBN), Kamaal Brown]
RCA NS-500 30-in-1 [David Haywood, Sean Riddle, Kev (FBN), Kamaal Brown]

new WORKING machines (3x VT Plug and Play)

---

scripts/target/mame/mess.lua
src/mame/drivers/betacam.cpp
src/mame/drivers/dfs500.cpp
src/mame/drivers/umatic.cpp
src/mame/layout/dfs500.lay
src/mame/mame.lst
src/mame/mess.flt

And a few new skeleton drivers for some other SONY video equipment:
* U-Matic vo5850PM
* BETACAM-SP UVW-1200
* BETACAM-SP UVW-1600
* BETACAM-SP UVW-1800
Note: This is something I've been working on my free time throughout the last month. I've put a lot of effort on the DFS-500 driver during the past weekends and I believe I reached a milestone in its development that makes it worthy to submit this PR. I will definitely work more on this one, but for now I'd like to submit this and rest a bit before putting more effort into it.

New non-working driver: SONY DFS-500 DME Video Mixer (1994)

---

.github/workflows/hash.yml
hash/c64_flop_clcracked.xml
src/mame/drivers/c128.cpp
src/mame/drivers/c64.cpp

This GitHub Action will run on any commit or pull request that changes a file in the "hash" directory. It will do a simple xmllint run for the HSI files and will check the softwarelist XML files against their DTD.

Create GitHub Action to validate hash XML files

---

src/devices/sound/dac.cpp
src/devices/sound/dac.h
src/devices/sound/volt_reg.cpp
src/emu/sound.cpp
src/mame/audio/leland.h
src/mame/drivers/williams.cpp

* modify dac to accept streams of any input rate to avoid resampling
* modify dac to assume input voltage streams are constant by only
grabbing the first input sample
* modify volt_reg to output at the minimum sample rate

dac/volt_reg: improve performance

---

hash/fmtowns_cd.xml

CRISS Ver. 1.00 [redump.org]
Demon City [redump.org]
Dengeki Nurse 2 - More Sexy [redump.org, wiggy2k]
Free Software Collection 5 (HMD-117A) [redump.org]
Free Software Collection 5 (HMD-117B) [redump.org]
Free Software Collection 6 (HME-141A) [redump.org]
Free Software Collection 7 (HME-225A) [redump.org]
Hacchake Ayayo-san IV - Sexy Olympic / Ayayo's Live Affection
[redump.org]
if 3 - Invitations from Fantastic Stories [redump.org]
Kyouko no Ijiwaru!! Hachamecha Daishingeki [redump.org]
New 3D Golf Simulation - Eight Lakes G.C. [redump.org]
Only You - Seikimatsu no Juliet-tachi [redump.org]
Moeru Asoko no Paipai Yuugi - Fukkatsu! Mahjong Oukoku [redump.org]
Pi's Solitaire Royale + Tom Snyder's Puppy Love [redump.org] …

fmtowns_cd.xml: 21 new dumps, 21 replacements

---

hash/apple2_flop_orig.xml

Mini-Pix #2 (Version 1986-11-01) [4am, Firehawke]
Mini-Pix #3 (Version 1986-11-17) [4am, Firehawke]
I.O. Silver [4am, Firehawke]

New working software list additions (apple2_flop_orig.xml)

---

src/devices/cpu/avr8/avr8.cpp

(followup to commit c9d3d973dd955bc985346f3ef3cad77246ed753c)

fix crash on pensebem / avr8 timer1

---

src/mame/drivers/nes_sh6578.cpp
src/mame/machine/nes_vt369_vtunknown_soc.cpp
src/mame/machine/nes_vt369_vtunknown_soc.h
src/mame/machine/nes_vt_soc.cpp
src/mame/machine/vt1682_alu.cpp

Plug and Play work - improve vt1682 ALU behavior, small steps towards vt369 including adding of soundcpu for denv150 [David Haywood]

Plug and Play work - improve vt1682 ALU behavior, small steps towards vt369 including adding of soundcpu for denv150

---

hash/ekara_pal.xml
src/mame/drivers/megadriv_rad.cpp
src/mame/drivers/segac2.cpp
src/mame/drivers/tsamurai.cpp
src/mame/drivers/tubep.cpp
src/mame/drivers/wecleman.cpp
src/mame/includes/megadriv.h
src/mame/includes/tsamurai.h
src/mame/includes/tubep.h
src/mame/includes/wecleman.h
src/mame/machine/megadriv.cpp
src/mame/mame.lst
src/mame/video/tsamurai.cpp
src/mame/video/tubep.cpp
src/mame/video/wecleman.cpp

- weclemans.cpp cleaned up MACHINE_START_OVERRIDE / MACHINE_RESET_OVERRIDE / VIDEO_START [David Haywood]
- tsamurai.cpp cleaned up MACHINE_START_OVERRIDE / MACHINE_RESET_OVERRIDE / VIDEO_START  [David Haywood]
- tubep.cpp cleaned up MACHINE_START_OVERRIDE / MACHINE_RESET_OVERRIDE / VIDEO_START  [David Haywood]
- segac2.cpp cleaned up MACHINE_START_OVERRIDE / MACHINE_RESET_OVERRIDE / VIDEO_START  [David Haywood]
------
Street Fighter II: Special Champion Edition (MSI Plug & Play) (Europe) [Team Europe]
new WORKING software list entries
-----
ekara_pal.xml:
uk_vol4 e-kara UK / Europe Volume 4 (UK-E004) [David Haywood. Team Europe]
uk_vol5 e-kara UK / Europe Volume 5 (UK-E005) [David Haywood. Team Europe]

cleanups to machine_start / machine_reset overides + some p&p bits [David Haywood]

---

src/mame/drivers/generalplus_gpl32612.cpp
src/mame/drivers/spg2xx_shredmjr.cpp
src/mame/machine/vt1682_alu.cpp
src/mame/mame.lst

- fixed out of bounds access in vt1682_alu.cpp [David Haywood]
-----
Plug 'N' Play Rockstar Guitar / Guitar Rock (PAL) [Peter Wilhelmsen, David Haywood, Team Europe]
-----
Zippity (UK) [David Haywood, Team Europe]

Fixed vt1682_alu.cpp out of bounds accesses + 2 Plug Play additions

---

hash/gameking.xml
hash/vtech_innotv_innotabmax_cart.xml
scripts/target/mame/mess.lua
src/mame/drivers/innotv_innotabmax.cpp
src/mame/mame.lst
src/mame/mess.flt

------
InnoTV [Team Europe]
------
vtech_innotv_innotabmax_cart.xml:
pawpatrl: Paw Patrol - Pups Save a UFO! (80-274103 UK) [Team Europe]
dcgcr: DC Comics - Gotham City Robots (80-274803 UK) [Team Europe]
finddory: Finding Dory (80-274903 UK) [Team Europe]
liongrd: The Lion Guard (80-275203 UK) [Team Europe]
new WORKING software list entries
-----
gameking.xml:
mc_4v07a: 4 in 1 - TrojanLegend (Trojan) + HappyBall + Supermotor (Motor) + Lanneret (Hawk) (512KB cartridge) [Team Europe]
mc_4v16a: 4 in 1 - Manhunt + Bobby + Tantivy + Racing Car (512KB cartridge) [Team Europe]

new NOT WORKING machines (InnoTV)

---

src/mame/drivers/nes_vt369_vtunknown.cpp
src/mame/machine/m6502_swap_op_d5_d6.cpp
src/mame/machine/m6502_swap_op_d5_d6.h
src/mame/machine/nes_vt32_soc.cpp
src/mame/machine/nes_vt369_vtunknown_soc.cpp
src/mame/machine/nes_vt369_vtunknown_soc.h
src/mame/mame.lst

-----
HKB-502 268-in-1 (set 1) [jacaba]
My Arcade Caveman Ninja [Tim Schuerewegen]
Retro FC 400-in-1 [Tim Schuerewegen]
Mini Arcade Machine 240-in-1 (Red5) [ne7!]
Mini Game Player 48-in-1 [Team Europe]
------
E-Game! 150-in-1 [gelotus]
HKB-502 268-in-1 (set 2) [Tim Schuerewegen]
Gaming Tech CT-885 [kludge]
Cyber Arcade 200-in-1 [pascal_frigoriste]
My Arcade Retro Machine 200-in-1 (DGUN-2577) [ne7!]
240-in-1 Mini Arcade Machine (Thumbs Up) [emuboy85]

new Plug and Play (VT) sets

---

src/mame/drivers/goldstar.cpp

on u70 is a Logic IC HD74LS157P check the below photo --> https://i.ibb.co/qmRVN8z/Viber-2020-11-10-08-17-11.jpg  , The correct location is u79.

goldstar.cpp: Corrected U79 PROM location

---

src/mame/drivers/undrfire.cpp
src/mame/includes/undrfire.h
src/mame/video/tc0360pri.cpp
src/mame/video/undrfire.cpp

tc0360pri.cpp: Remove unnecessary define

undrfire.cpp: Fix priority in cbombers, Add notes

---

src/mame/drivers/unk6502_st2xxx.cpp
src/mame/mame.lst

-----
Mini Arcade Console (Arcade 10-in-1) [Team Europe]
Arcade Classics Mini Handheld Arcade (Supreme 150) [Team Europe]

new NOT WORKING machines  (Plug and Play)

---

src/devices/cpu/m6502/st2205u.cpp

This is the DMA part of the changes required by https://github.com/mamedev/mame/pull/7430 which I've split out in attempt to make the process smoother.

DMA required by PR #7430

---

src/mame/drivers/lindbergh.cpp

Added known Lindbergh game Psy-Phi to the Lindbergh driver game list.

Add Psy-Phi to Lindbergh driver game list

---

src/mame/drivers/naomi.cpp

naomi.cpp: Explain mainboard jumper JP1 (Aica clock source)

---

scripts/src/bus.lua
src/devices/bus/coco/coco_multi.cpp
src/devices/bus/coco/coco_sym12.cpp
src/devices/bus/coco/coco_sym12.h
src/mame/drivers/coco12.cpp
src/mame/drivers/dragon.cpp

A 12 voice (4 psg) music device from the 80s.

coco: add symphony 12 bus device

---

src/mame/drivers/vg5k.cpp

To emit the character, it is first latched on port ($10) then a rising edge is produced on port ($11).

VG5000µ printer more accurate support.

---

src/mame/drivers/vicdual.cpp
src/mame/includes/vicdual.h

(don't think these sets were ever properly playable)

simulate protection for carnivalh / carnivalha sets [David Haywood]

---

src/mame/drivers/hp2640.cpp
src/mame/mame.lst

Hi,
I've just integrated hp2641a APL terminal from Gavin Scott into hp2640.cpp.
I'm going to submit the ROM images to the code e-mail soon.
Thanks.
--F.Ulivi

HP2641A APL terminal from G.Scott

---

src/mame/drivers/kpython.cpp
src/mame/mame.lst

Added dogstation Deluxe hard drive dump to the konami python driver.

kpython.cpp: Add dogstation Deluxe hdd dump

---

hash/leapfrog_turboextreme_cart.xml

new NOT WORKING Software List entries
------
leapfrog_turboextreme_cart.xml:
grade2 - Grade 2 [Sean Riddle, David Haywood]

new NOT WORKING Software List entries (Turbo Extreme Grade 2)

---

src/mame/drivers/deco32.cpp
src/mame/video/deco32.cpp
src/mame/video/deco_zoomspr.cpp
src/mame/video/deco_zoomspr.h

"alpha" flag is actually flicker flag
deco32.cpp: Add notes, device placeholder for dragngun

deco_zoomspr.cpp: Fix drawing behavior

---

src/mame/audio/seibu.cpp
src/mame/audio/seibu.h
src/mame/drivers/cabal.cpp
src/mame/drivers/deadang.cpp
src/mame/drivers/shanghai.cpp
src/mame/includes/cabal.h

audio/seibu.h: Fix hardware notes
cabal.cpp, deadang.cpp, shanghai.cpp: Fix ADPCM clock
shanghai.cpp: Fix CPU clock (CXQ70116 can't support 16MHz), add notes

audio/seibu.cpp: Replace MSM5205 interface with device_sound_interface in seibu_adpcm

---

hash/easy_karaoke_cart.xml
scripts/target/mame/mess.lua
src/devices/machine/generalplus_gpl16250soc.cpp
src/devices/machine/generalplus_gpl16250soc.h
src/mame/drivers/easy_karaoke.cpp
src/mame/drivers/generalplus_gpl16250_spi_direct.cpp
src/mame/drivers/nes_clone.cpp
src/mame/drivers/st22xx_bbl338.cpp
src/mame/drivers/vt1682.cpp
src/mame/mame.lst
src/mame/mess.flt

-----
Portable Game Player BBL-338 (Baobaolong, 48-in-1) [Team Europe, taizou]
HengSheng 36-in-1 (Red pad) [Team Europe, taizou]
HengSheng 36-in-1 (Black pad) [Team Europe, taizou]
Fix It Felix Jr. (Mini Arcade) [Sean Riddle, Kamaal Brown]
Where in the World is Carmen Sandiego? (Handheld) [foone]
TV Dance Mat 4 Games in 1 (Mix Party 3 / Dance Mix 3) [Team Europe, David Haywood]
Ultimate Pocket Console GM-235 [Team Europe, taizou]
-----
easy_karaoke_cart.xml:
Golden Greats Vol.3 [Team Europe, David Haywood]
Golden Greats Vol.4 [Team Europe, David Haywood]
(an Easy Karaoke driver was added to hold the software list / details, but the system ROM is not yet dumped)

new NOT WORKING machines (Plug and Play)

---

src/mame/drivers/easy_karaoke.cpp

- added dump of system ROM to Easy Karaoke [Team Europe]
------
Easy Karaoke Groove Station [Team Europe, David Haywood]

added dump of system ROM to Easy Karaoke [Team Europe]

---

src/mame/drivers/nes_clone.cpp
src/mame/drivers/nes_sh6578.cpp
src/mame/drivers/nes_vt32.cpp
src/mame/mame.lst

- move dancmix3 to nes_sh6578.cpp [David Haywood]
------
My Arcade Data East Classics - Pixel Classic (308-in-1) (DGUNL-3201) [Team Europe]

move dancmix3 to nes_sh6578.cpp + added dgunl3201 set

---

hash/fmtowns_cd.xml

Bell's Avenue Vol. 3 [redump.org]
F-BASIC386 v1.1 L21 [redump.org]
FM Towns Free Soft Nyuumon Kit [redump.org]
Hajimete no Ryokou Eikaiwa [redump.org]
Heike Monogatari (Joukan) [redump.org]
Idol Project (1995-06-16 15:06:42) [redump.org, wiggy2k]
Igo Doujou Shodan - Kaigan! Kyuu kara Dan e no Chousen [redump.org]
Maruanki Eitango - Chuugaku 2-nensei [redump.org]
Maruanki Eitango - Chuugaku 3-nensei [redump.org]
Nihon no Yachou (FM Towns Marty version) [redump.org]
Special & Delicious! Original CD-ROM [redump.org]
The Manhole (HMB-181A) [redump.org]
Terra Towns (HMA-110) [redump.org]
Alice no Yakata CD II [redump.org]
Alice no Yakata 3 [redump.org]
Ayumi-chan …

fmtowns_cd.xml: 13 new dumps, 22 replacements, 2 missing floppies added

---

src/mame/drivers/twinbskt.cpp

My bad, I submitted the dump with the wrong manufacturer name.

twinbskt.cpp: Fix manufacturer name

---

src/emu/render.h
src/frontend/mame/ui/videoopt.cpp
src/osd/mac/video.cpp
src/osd/modules/input/input_sdlcommon.cpp
src/osd/sdl/video.cpp

Add "Non-Integer Scaling" and "Keep Aspect" settings to UI video options menu and remove SDL hotkeys for same

Add "Non-Integer Scaling" and "Keep Aspect" settings to UI video options

---

hash/leapfrog_turbotwistbrainquest_cart.xml
src/mame/drivers/leapfrog_iquest.cpp
src/mame/mame.lst

------
Turbo Twist Math (US) [Sean Riddle, David Haywood]
Turbo Twist Brain Quest (US) [Sean Riddle, David Haywood]
------
leapfrog_turbotwistbrainquest_cart.xml:
grades5_6 - Grades 5 & 6 (500-00745) [Sean Riddle, David Haywood]

new NOT WORKING machines (Leapfrog Turbo Twist units)

---

hash/next_cdrom.xml
src/mame/drivers/next.cpp

Add a software list for CD-ROM NeXT software

next_cdrom: initial cdrom software list for next

---

scripts/src/bus.lua
src/devices/bus/coco/coco_midi.cpp
src/devices/bus/coco/coco_midi.h
src/devices/bus/coco/cococart.cpp
src/mame/drivers/dragon.cpp

Implement a midi device as a coco/dragon cartridge.

coco/dragon: add midi cartridge

---

src/devices/video/ef9345.cpp

Fix the underline latched attribute when emitting a delimiter character.
Fix the delimiter emitted character address.
Change word from "hided" to the datasheet coherent "conceal"

VG5000µ fix latched attributes on delimiter.

---

hash/fmtowns_flop.xml

Darwin's Dilemma - The Solution Is Evolution [wiggy2k]

fmtowns_flop.xml: 1 new dump

---

src/devices/video/imagetek_i4100.cpp
src/devices/video/imagetek_i4100.h
src/mame/drivers/metro.cpp

imagetek_i4100.cpp: Add state of CRTC related value for debug
also fixed MT #07845

metro.cpp: Fix tilemap offset regression

---

src/devices/bus/a2bus/a2diskiing.cpp
src/devices/imagedev/floppy.cpp

Apple 2 floppy drive (diskiing, diskiing13): added sounds

---

src/mame/drivers/getaway.cpp

------
Get A Way [hap, Angelo Salese]

getaway.cpp: various updates, promoted to working

---

hash/rx78_cart.xml

A minor update to add the missing product code to Donjara and place it in its correct order.

Minor RX-78 gamelist update [Dave 'Foxhack' Silva]

---

src/mame/drivers/system1.cpp

Correct ROM labels and location for ufosensib, verified against PCB

Correct ROM labels and location for ufosensib

---

src/devices/bus/rs232/printer.cpp
src/devices/bus/rs232/printer.h
src/devices/bus/rs232/rs232.cpp
src/mame/drivers/coco12.cpp
src/mame/drivers/coco3.cpp

Radio Shack serial printer's use the receive line as a status line. If it is not set low, printing software will hang indefinitely.

bus/rs232/printer: Add generic Radio Shack printer option

---

src/mame/drivers/bogeyman.cpp
src/mame/drivers/shootout.cpp
src/mame/drivers/snk.cpp

shootout.cpp: correct monitor orientation to ROT180 [Corrado Tomaselli]

bogeyman.cpp: correct monitor orientation to ROT180 [Corrado Tomaselli]

---

COPYING
README.md
android-project/LICENSE
benchmarks/LICENSE
docs/source/conf.py
docs/source/license.rst
docs/source/whatis.rst
regtests/LICENSE
scripts/toolchain.lua
src/devices/video/fixfreq.cpp
src/lib/netlist/prg/nltool.cpp
src/lib/netlist/prg/nlwav.cpp
src/mame/drivers/socrates.cpp
src/osd/modules/render/bgfx/shaders/shader.mk
src/tools/testkeys.cpp
tests/LICENSE
uismall.bdf
web/LICENSE

Update "2020" text to "2021"

---

docs/source/initialsetup/compilingmame.rst

Suggested changes to MacOS to build reqs, the old info is very out of date with the current requirements.

Suggested changes to MacOS to build reqs

---

src/mame/drivers/hh_sm510.cpp

The G&W Egg display has been digitized from an actual unit and is an improvement to the existing one.

hh_sm510.cpp: Improve gnw_egg display

---

src/devices/cpu/es5510/es5510.cpp
src/devices/cpu/es5510/es5510.h

Implement (partially) RAM clear function
Fix host control register; host access OK flag is inverted (0 is active)
Reference docs from: http://zine.r-massive.com/ensoniq-technical-documents-and-schematics/

es5510.cpp: Add notes, Add serial control register for debugging, Fix/Add some hardware features

---

src/mame/drivers/apple2gs.cpp

documented in the Apple IIgs toolbox reference Volume 1, Chapter 3

AppleIIgs : add some missing ADB commands.

---

src/mame/drivers/spg2xx_jakks_sharp.cpp
src/mame/mame.lst

------
Go Diego Go! - Aztec ABC Adventure (Sharp Cookie) (PAL, UK) [Sean Riddle, David Haywood]
Dora the Explorer - Dora Saves the Mermaids (Sharp Cookie) (PAL, UK) [Sean Riddle, David Haywood]

new WORKING machine (Go Diego Go + Dora Sharp Cookie)

---

hash/hp_ipc_rom.xml
scripts/target/mame/mess.lua
src/mame/drivers/hp_ipc.cpp
src/mame/machine/hp_ipc_optrom.cpp
src/mame/machine/hp_ipc_optrom.h

Hi,
I've just added the support for external ROMs to HP integral PC. At the moment I'm only aware of the existence of a "Software Engineering ROM".
I'm going to e-mail this ROM's image shortly.
Thanks.
--F.Ulivi

HP Integral: support for expansion ROMs added

---

src/mame/drivers/spg2xx_jakks_sharp.cpp
src/mame/mame.lst

------
Scooby-Doo! and The Pirate's Puzzles (Sharp Cookie) (PAL, UK) [Sean Riddle, David Haywood]

new WORKING machine (Scooby-Doo! Sharp Cookie)

---

hash/ekara_japan_a.xml

------
ekara_japan_a.xml:
A-6 Pichi Pichi Pitch Pure Chapter 2 (Japan) [WingedPikPik, TeamEurope]
A-8 Pichi Pichi Pitch Karaoke Party 2 (Japan) [WingedPikPik, TeamEurope]

new software list entries (ekara)

---

src/mame/drivers/thoop2.cpp
src/mame/includes/thoop2.h
src/mame/video/thoop2.cpp

Move virtual functions under protected: section

thoop2.cpp: Fix sprite vs sprite priority

---

hash/fmtowns_cd.xml

- Removed the floppy disks for 38-man Kilo no Kokuu and Powermonger, since they are user-created disks and the games only need blank disks to save
- Replaced Lunatic Dawn II floppy with a cleaner unmodified copy [akira_2020]
- Replaced Nobunaga no Yabou - Bushou Fuuunroku floppy with a cleaner unmodified copy [wiggy2k]
- Replaced the "fake" Lipstick Adventure 3 floppy with an image dumped from the original disk [r09]
- Added a missing floppy image to Nobunaga no Yabou - Tenshouki (it wasn't marked as unsupported but it didn't actually work correctly before) [wiggy2k]
Ehon Writer School v1.1 L21 [redump.org]
Gakuen Bakuretsu Tenkousei! [redump.org]
Hana no Kioku - Dainishou [redump.org]
if 1-2-3 CD Collection …

fmtowns_cd.xml: 11 new dumps, 19 replacements, 3 missing floppies added

---

hash/sms.xml

Updated Date Info: [fireice] 1993 -> 1995
source:
https://segaretro.org/Fire_%26_Ice

sms - Updated Info

---

src/mame/drivers/actions_atj2279b.cpp

I added some information that I found on the internet (unconfirmed).
There are also a continuation of Generations, but they are not dumped and can be on different hardware also with ARM.

actions_atj2279b.cpp: add notes

---

src/mame/drivers/neogeo.cpp
src/mame/drivers/neogeocd.cpp

neogeocd.cpp: Move value into driver class, Add notes for hardware region

neogeo.cpp: Add notes for AES clock, regional difference

---

hash/apple1.xml

apple1.xml: Hamurabi (Computerland of Nashua) [Brutal Deluxe]
apple1.xml: Nightmare 6 (Computerland of Nashua) [Brutal Deluxe]

apple1: New working software list additions

---

hash/ekara_japan_gk.xml
hash/ekara_japan_sp.xml
src/mame/drivers/spg2xx.cpp
src/mame/mame.lst

------
Dora the Explorer - Dora TV Adventure Globe [Sean Riddle, David Haywood]
- set some of the previous ekara additions to unsupported as they actually use the alt seeprom hookup that isn't currently functional, and lock up in places as a result. [David Haywood]

new WORKING machine (Dora TV Adventure Globe)

---

src/devices/machine/tc009xlvc.cpp
src/devices/machine/tc009xlvc.h
src/mame/drivers/dfruit.cpp
src/mame/drivers/heromem.cpp
src/mame/drivers/lastbank.cpp
src/mame/drivers/sbmjb.cpp
src/mame/drivers/taito_l.cpp
src/mame/includes/taito_l.h
src/mame/video/taito_l.cpp

Fix background drawing behavior (it fixes gemcrush ranking, select stage screen), Convert bankswitched VRAM handler into internal memory space
Fix variable name, Add notes

tc009xlvc.cpp: Include Z80 core (interrupt handler not yet ported)

---

src/devices/machine/fdc37c665gt.cpp
src/devices/machine/fdc37c665gt.h
src/devices/machine/upd765.cpp

The old FDC37C665GT implementation was a bare bones implementation to get Twinkle games past the DVD init check at boot. This wasn't sufficient for Firebeat beatmania III's floppy drives so I decided to reimplement the device from scratch using FDC37C93x with the ISA-related code removed as a base since it was similar enough in regards to how the configuration register needs to be implemented.
This is not a full implementation. I left out the things that I can't test myself such as DMAs, IDE, and a bunch of configuration register flags. Neither Firebeat or Twinkle use the parallel port so it's untested but it's a freebie from FDC37C93x. The FDC37C666GT-specific differences also haven't been implemented but it may work for that too.
Data sheet for reference: …

fdc37c665gt: Reimplementation with floppy and parallel support

---

src/mame/drivers/elan_ep3a19a.cpp
src/mame/mame.lst

------
TV Board Games 3-in-1: Boggle, Connect 4, Roll Over [Sean Riddle, David Haywood]
TV Board Games 3-in-1: Silly 6 Pins, Hungry Hungry Hippos, Match 'em [Sean Riddle, David Haywood]
TV Board Games 3-in-1: Simon, Battleship, Checkers [Sean Riddle, David Haywood]

new WORKING machines (TV Board Games Boggle, Connect 4)

---

src/mame/drivers/generalplus_gpl16250_spi_direct.cpp
src/mame/mame.lst

------
Pac-Man (mini arcade) [Sean Riddle]
Ms. Pac-Man (mini arcade) [Sean Riddle]

new NOT WORKING machines (Plug & Play)

---

src/mame/drivers/spg2xx.cpp
src/mame/includes/spg2xx.h
src/mame/mame.lst

------
Teléfono interactivo de TV (Spain) [ClawGrip, Sean Riddle, David Haywood]

new WORKING machines (Teléfono interactivo de TV)

---

src/mame/drivers/joystand.cpp

Add hardware notes, Reduce duplicates
Demote to MACHINE_NODEVICE_PRINTER because printer emulation is missing

joystand.cpp: Convert cartridge accessing function into address_map_bank_device

---

src/mame/drivers/apple2gs.cpp

The ADB GLU uC should recognize command-control-escape and command-control-delete and generate the appropriate ADB status byte and ADB data IRQ. ADB response bytes were also failing to generate the ADB data IRQ (which is generally not important since the toolbox disables IRQs and polls directly when data is expected).

apple2gs: control panel support

---

src/mame/drivers/leapfrog_iquest.cpp
src/mame/mame.lst

------
Turbo Twist Fact Blaster (US) [Sean Riddle, David Haywood]

new NOT WORKING machines (Turbo Twist)

---

src/mame/includes/momoko.h
src/mame/video/momoko.cpp

- fixed glitches on momoko high score table after memory system updates (was reading past end of region)
- refactored a little, added TODO notes

fixed glitches on momoko high score table after memory system updates (was reading past end of region)

---

hash/fmtowns_cd.xml

- Added the missing floppy image to OASYS/Win 2.0 (still not working due to lack of DD floppy support) [cyo.the.vile]
- Replaced the psydet5 and psydetf1 floppy images with cleaner unmodified copies [cherokee]
Alice no Yakata 3 (1995-05-16) [redump.org]
Battle [redump.org]
Ehon Writer V1.1 L10 [redump.org]
Half Moon ni Kawaru made - Ramiya Ryou no Nijiiro Tamatebako
[redump.org, wiggy2k]
Never Land [redump.org]
Oto to E no Deru Eigo Jisho No. 2 - English in Dream [redump.org]
Populous II - Trials of the Olympian Gods - Expert [redump.org]
Running Girls - Hashiri Onna II + Rance 4.1 / 4.2 Hint Disk [redump.org]
Soreike! Anpanman - Tanoshii Eigo Asobi [redump.org]
Toshiyuki Yoshino - Lullaby of BirdLand [redump.org] …

fmtowns_cd.xml: 13 new dumps, 12 replacements, 5 missing floppies added

---

hash/apple2_flop_clcracked.xml

Major screw-up on my part. Sorry about that.

Apple softlist correction

---

language/Dutch/strings.po

Added all missing strings for the Dutch language.
Also made spelling and meanings more consistent after testing the menu's with previous translations.

Update Dutch strings.po

---

hash/megadriv.xml
src/devices/bus/megadrive/md_carts.cpp
src/devices/bus/megadrive/md_slot.cpp
src/devices/bus/megadrive/md_slot.h
src/devices/bus/megadrive/rom.cpp
src/devices/bus/megadrive/rom.h

new WORKING software list entries
------
megadriv.xml
fbarg96 - Futbol Argentino 96 (Argentina) (hack of J. League Pro Striker 2) [Sebastian Beltran, David Haywood]
tc2000a - TC 2000 (Argentina, protected) [Sebastian Beltran, David Haywood]
------
megadriv.xml:
truco96a - Truco '96 (Argentina, protected) [Sebastian Beltran, David Haywood]

new WORKING software list entries

---

hash/pc98_cd.xml

- Added the missing floppy image to Lipstick Adventure 3 [r09]
- Added/replaced all hybrid CDs known so far with the CHDs from the FM Towns softlist, and added some new entries from Redump (details below)
Alice no Yakata 3 (1995-05-16) [redump.org]
Bell's Avenue Vol. 1 [redump.org]
Bell's Avenue Vol. 2 [redump.org]
Bell's Avenue Vol. 3 [redump.org]
Gakuen Bakuretsu Tenkousei! [redump.org]
Hana no Kioku - Dainishou [redump.org]
if 1-2-3 CD Collection [redump.org]
Ikazuchi no Senshi Raidy 2 (1996-08-01) [redump.org]
Kousoku Choujin [redump.org]
Mahjong Gensoukyoku II - Mahjong Fantasia [redump.org]
Mahjong Gensoukyoku III - Mahjong Fantasia the 3rd Stage [redump.org]
Misato-chan no Yume Nikki [redump.org]
Never Land …

pc98_cd.xml: sync with the FM Towns softlist

---

src/mame/drivers/qx10.cpp

This patch adds the currently missing sound support for QX10 systems.

qx10: Implement Sound/Speaker

---

src/devices/video/upd7220.cpp

Fixes copy paste bug in upd7220 DMA handling, also fixed up coding style to be consistent with the rest of the upd7220.cpp file.

upd7220: fix copy paste bug in DMA handling

---

hash/ibm5150.xml

ibm5150.xml: 1 working software list addition

---

hash/fmtowns_cd.xml

Special thanks to everyone who participated in the fundraiser to acquire and dump most of these (cyo.the.vile, F1ReB4LL, rockleevk, Wiggy2k).
- Added the missing floppy image to Taiken Shiyou! Marty Channel [wiggy2k]
- Added the missing floppy image to Air Warrior V1.1 [al32gabby]
- Replaced the Inindou and Star Cruiser II floppy images with cleaner unmodified copies [cyo.the.vile]
- Added the bonus audio CD that was included with Bible Master [redump.org]
California X Party - Joshi Daisei Himitsu Club [redump.org, al32gabby]
Castles II - Bretagne Touitsu Senki / Castles II - Siege & Conquest [redump.org]
CD-ROM Bishoujo Senshi Collection - Yuu Disc Special [redump.org]
Collector D [redump.org]
Diamond Players …

fmtowns_cd.xml: 29 new dumps, 13 replacements, 1 missing floppy added

---

src/devices/video/upd7220.cpp
src/mame/drivers/qx10.cpp

This adds zoom support for the QX10 system.  Zooming on the upd7220 works by having the gpu rpeat each scanline the number of times equal to the programmed zoom factor. This will zoom in the vertical direction, the horizontal diretion requires external hardware on the machine in question to slow the fresh rate down which will create streched pixels allowing for soomin in the horizontal direction. On the QX10 the zoom rate for this external circuitry is set via the io port 0x3a.
This patch modifies the upd7220 so that it will multiple each Y count by the zoom factor and then updates the QX10 code to correctly multiply the X direction based on the value sent to the 0x3a io port.

upd7220, qx10: Implement display zoom support

---

plugins/console/init.lua

Changed a loadstring to load, since lua 5.3 loadstring is not
available.
Made sure the linenoise thread returns a string.
After Ctrl+D stop reading lines.

Save line history for the console and other minor fixes

---

src/mame/drivers/amstr_pc.cpp
src/mame/drivers/pc.cpp
src/mame/mame.lst

Alloy EarthStation I, Frael King, Victor VPC II, MY-COM MPU-9088-VF, Triumph-Adler TA 1700-PC

pc.cpp: added systems NOT_WORKING

---

plugins/autofire/autofire_save.lua
plugins/boot.lua
plugins/cheat/init.lua
plugins/console/init.lua
plugins/data/data_hiscore.lua
plugins/data/database.lua
plugins/hiscore/init.lua
plugins/portname/init.lua
plugins/timer/init.lua
plugins/util.lua

26defea154413796e7e38891a78c4834a8813358 tries to read homepath as an ui option. The first commit changes that, second commit adds an util.lua file and functions to create multiple parent directories. I also changed the other lua files to use that.

Create console history file in homepath

---

src/mame/drivers/joctronic.cpp
src/mame/mame.lst

New NOT_WORKING machines

---

hash/a800_flop.xml

Atari Translator (USA) [a8sp]
Forbidden Forest [a8sp]
Saracen [a8sp]
Crosscheck [a8sp]
Spitfire 40 [a8sp]

a800_flop.xml: more floppy soft additions

---

hash/rx78_cart.xml

Added serial number and official romanization to a few applications. [Dave 'Foxhack' Silva]

RX-78 software information update

---

src/mame/drivers/ladybug.cpp
src/mame/includes/ladybug.h
src/mame/mame.lst
src/mame/video/ladybug.cpp

I also added a lot of hardware notes for the Universal 8203 boardset.  
I expect to add one more revision to document the rest of it.

mrsdyna: New driver for Mrs. Dynamite

---

hash/sms.xml

Bara Buru [Kagesan]
Bruce Lee [Kagesan]
Flight of Pigarus (v1.11) [Kagesan]
Flight of Pigarus (v1.10) [Kagesan]
Flight of Pigarus (v1.00) [Kagesan]
Heroes Against Demons [Ichigo]
Voyage - A Sorceress' Vacation [Snags]

sms.xml: added recently published carts

---

hash/gamegear.xml

Argos no Juujiken (Tw, SMS mode) [smspower]
Black Belt (Tw, SMS mode) [smspower]
The Cyber Shinobi (Tw, SMS mode) [smspower]
Doki Doki Penguin Land - Uchuu Daibouken (Tw, SMS mode) [smspower]
Double Dragon (Tw, SMS mode) [smspower]
Final Bubble Bobble (Tw, SMS mode) [smspower]
Forgotten Worlds (Tw, SMS mode) [smspower]
Great Basketball (Tw, SMS mode) [smspower]
Hokuto no Ken (Tw, SMS mode) [smspower]
Kung Fu Kid (Tw, SMS mode) [smspower]
Lord of Sword (Tw, SMS mode) [smspower]
Paperboy (Tw, SMS mode) [smspower]
Prince of Persia (Tw, SMS mode) [smspower]
Quartet (Tw, SMS mode) [smspower]
R-Type (Tw, SMS mode) [smspower]
Scramble Spirits (Tw, SMS mode) [smspower]
Secret Command (Tw, SMS mode) [smspower]
Seishun Scandal …

gamegear.xml: new software list additions + fix MT 7965

---

hash/ibm5150.xml

Astérix: El Golpe del Menhir (Astérix y Operacion Menhir) (Spain, System 4 release) [archive.org]
Astérix: Operation Getafix (UK) [The Good Old Days]
Battle Chess (3.5", EGA version, Spain, Dro Soft release) [archive.org]
Ishar: Legend of the Fortress [The Good Old Days]

ibm5150.xml: New working software list additions

---

hash/ibm5170.xml

Alone in the Dark (Spain, Top Games/Altaya release) [archive.org]
Heart of China (Spain, MCM release) [archive.org]
Indiana Jones and the Fate of Atlantis (3.5", Spain, Erbe release) [archive.org]
Indiana Jones and the Last Crusade - The Graphic Adventure (3.5", EGA version, Spain, Maxi Juegos/Erbe release) [archive.org]
Ishar 2: Messengers of Doom (Spain, Proein release) [The Good Old Days]
Wolfenstein 3-D (shareware, CWI Information Services release) [archive.org]

ibm5170.xml: New working software list additions

---

scripts/target/mame/mess.lua
src/mame/drivers/philipsbo.cpp
src/mame/mame.lst
src/mame/mess.flt

New machines marked as NOT_WORKING
Philips BO (Videosynthesizer Prototype) [Ryan Holtz, MrMii6, CD-i Fan]

Added skeleton for Philips BO (Videosynthesizer Prototype)

---

src/mame/drivers/gunpey.cpp

Reduce duplicates, Unnecessary variables and lines
Fix naming, Spacing
Use alpha_blend_r16 for blending functions
Use shorter/correct type values
Add notes

gunpey.cpp: Add save states, Fix init, Add version info from startup screen, Minor cleanups

---

src/devices/bus/coco/coco_ssc.cpp
src/mame/drivers/coco12.cpp

1. Fix noise on reset.
2. Improve reset handling
3. reduce logging on floating bus writes

CoCo Speech/Sound Pak: fix noise on reset

---

src/mame/includes/coco.h
src/mame/machine/coco.cpp

Disabling the left or right joystick would disable all joystick buttons.

coco: fix disabling of joysticks (MT #7475)

---

src/mame/drivers/alg.cpp
src/mame/mame.lst

As shown on the games, cab and manuals.

alg.cpp: Fix company name, it's "Picmatic", not "Web Picmatic"

---

src/mame/drivers/spinb.cpp
src/mame/mame.lst

Bushido (set 3) [Victor Fernandez (City Game)]

New NOT_WORKING clone 

---

plugins/data/data_history.lua

This fixes #8114 on Linux but someone should test it on other OSes just to be safe.

Strip CRs from history.xml

---

hash/apple2_flop_orig.xml
hash/neogeo.xml

* apple2_flop_orig.xml: a couple of obvious typos
* neogeo.xml: consistent spacing + jp title

fix softlist typos

---

hash/gamegear.xml
hash/sms.xml

gamegear:
Dynamite Headdy (prototype) [smspower]
Mortal Kombat (prototype) [smspower]
sms:
Advanced Dungeons & Dragons - Heroes of the Lance (prototype) [smspower]

gamegear.xml, sms.xml: added more prototypes

---

hash/megadriv.xml

Akira (prototype) [Hidden Palace]
Ecco the Dolphin (prototype) [Hidden Palace]
The Flintstones (prototype) [Hidden Palace]
Sonic Spinball (Euro, prototype 19930917) [Hidden Palace]
Street Fighter II' - Champion Edition (Euro, USA, prototype 19930325) [Hidden Palace]
Street Fighter II' - Champion Edition (Euro, USA, prototype 19930730) [Hidden Palace]
World of Illusion Starring Mickey Mouse and Donald Duck (prototype) [Hidden Palace]
* also replace Star Wars proto dump with proper EPROM dumps

megadriv.xml: add protos for more blast processing

---

src/devices/bus/coco/coco_max.cpp
src/mame/machine/6883sam.cpp

1. address white space comments from @cuavas.
2. add keyboard inc and dec to mouse movements
3. fix mask in ff90_read()

CoCo MAX fixes

---

src/devices/machine/spg2xx_io.cpp
src/devices/machine/spg2xx_io.h

-spg2xx_io: Cleaned up IRQ checking and improved ADC behavior. [Ryan Holtz]

Made SPG2xx I/O IRQ checking a bit more lean; improved ADC behavior.

---

src/mame/audio/acan.cpp
src/mame/audio/acan.h
src/mame/drivers/supracan.cpp

-acan: Added DMA-driven sample support and fixed sample length calculation. [Ryan Holtz, Ian Karlsson]

Super A'Can audio improvements

---

hash/nes.xml
src/devices/bus/nes/act53.cpp
src/devices/bus/nes/act53.h

Streemerz - Action 53 Function 16 Volume 1 (R.C.#2) [Damian Yerrick, NESDev]
Double Action 53 Volume 2 (R.C.#2) [Damian Yerrick, NESDev]
Action 53 Vol. 3 - Revenge of the Twins [Damian Yerrick, NESDev]
action53.cpp:
* on start up point prg to correct final bank based on cart size
* allow full 9-bit bank select per the spec
* switch to shorter type names, u8 etc

nes.xml: add Action 53 based games

---

src/mame/drivers/indigo.cpp

This dump is the byte swapped version of the one attached in https://github.com/mamedev/mame/issues/5992#issuecomment-591119768 by @hbent. I've put it at --removed link to copyrighted rom--

indigo: add new ROM revision for indigo4k

---

hash/juicebox.xml
src/devices/machine/smartmed.cpp

new WORKING software list entries
------
juicebox.xml:
Teenage Mustant Ninja Turtles Volume 1 (H2692) [Sean Riddle, David Haywood]
Teenage Mustant Ninja Turtles Episode 36 (H6260) [Sean Riddle, David Haywood]
Juicebox Music Video - Avril Lavigne, The Calling, Avril Lavigne, Clay Aiken, Ruben Studdard (H6228) [Sean Riddle, David Haywood]
Juicebox Music Video - Liz Phair, Stacie Orrico, Skye Sweetnam (H2709) [Sean Riddle, David Haywood]
Juicebox Music Video - ZOEgirl, Jump5, Jump5, Baha Men, Atomic Kitten (H6232) [Sean Riddle, David Haywood]
Juicebox Music Video - Baha Men, Jump 5, Jump 5, Beu Sisters, ZOEgirl (H6230A) [Sean Riddle, David Haywood]
Juicebox Music Video - Ashlee Simpson, The Cure, Vanessa Carlton, fan_3, Ashlee Simpson (H6226) [Sean Riddle, David Haywood]
Winx Club Volume 1 …

juicebox additions [David Haywood, Sean Riddle]

---

src/lib/formats/flopimg.cpp

Object/resource pool usage was almost gone from flopimg. This PR removes the remainder. Specifically:
* The track data and tag data are now held by std::unique_ptr
* The floppy_image_legacy struct is now allocated/freed with new/delete, and no longer memset
With this PR, and the previous one to remove usage from imgtool, we should be able to remove the very legacy src\lib\util\pool.* code altogether.

flopimg: Remove pool usage

---

hash/ibm5150.xml

Advanced Dungeons & Dragons - Death Knights of Krynn (3.5", v1.00) [The Good Old Days]
Advanced Dungeons & Dragons - Death Knights of Krynn (3.5", v1.10) [The Good Old Days]
Advanced Dungeons & Dragons - Death Knights of Krynn (5.25", v1.00) [The Good Old Days]
Advanced Dungeons & Dragons - War of the Lance [The Good Old Days]
DeathTrack [Old-Games]
Starflight 2: Trade Routes of the Cloud Nebula (3.5", alt) [The Good Old Days]
Starflight [The Good Old Days]

ibm5150.xml: 6 new dumps, 1 replacement

---

hash/ibm5170.xml

Midwinter II - Flames of Freedom (USA) [The Good Old Days]
SimCity 2000 (Ver 1.00) [The Good Old Days]
SimCity 2000 (Germany, Ver 1.00) [The Good Old Days]
SimCity 2000 (Spain, Ver 1.00) [archive.org]
The Secret of Monkey Island (Germany) [The Good Old Days]
The Secret of Monkey Island (Spain) [archive.org]

ibm5170.xml: 6 new dumps

---

hash/snes.xml

Atmosfear (USA, prototype 19940712) [Hidden Palace]
EarthBound (USA, prototype 19950327) [Hidden Palace]
College Slam (USA, final prototype) [togemet2]
CutThroat Island (Euro, final prototype) [togemet2]
Fatal Fury 2 (USA, prototype) [togemet2]
Foreman For Real (USA, final prototype) [togemet2]
Kyle Petty's No Fear Racing (USA, final prototype) [togemet2]
Samurai Shodown (USA, prototype) [togemet2]
Speed Racer in My Most Dangerous Adventures (USA, prototype) [togemet2]
Venom &amp; Spider-Man - Separation Anxiety (USA, final prototype) [togemet2]
WWF WrestleMania - The Arcade Game (USA, prototype) [togemet2]

snes.xml: add 11 prototypes

---

hash/fmtowns_cd.xml

- Added the missing floppy disks to pharmony and wyattd [tenyuhuang]
- Added the missing floppy disk to landlore [cyo.the.vile]
- Added the missing floppy disk to genchohi [Neo Kobe Collection]
- Normalized the titles of the New Horizon discs
- Moved gnutowns to the applications section, since it is a collection of GNU tools and not an OS
- Demoted asu120ex to not working (this doesn't seem to be a regression, it was just marked incorrectly)
- Promoted beast, beast2 and gunship from partial to fully working after the latest fixes to 15-bit sprite drawing [crazyc]
Ehon Writer V1.1 L10 (FMB-3011) [redump.org]
CD Learning System II - New Horizon English Course 2 [redump.org]
FM Towns FlexData Collection Vol. 1 - E to Oto …

fmtowns_cd.xml: 12 new dumps, 9 replacements, 4 missing floppies added

---

hash/pce.xml
hash/pce_tourvision.xml

* make newer revision of R-Type part 2 the parent
* remove motorod2a which appears to be a 1-byte hack: it changes the 5-player input loop counter to not read input from players 3 to 5

pce.xml: minor updates + remove a hack

---

hash/x68k_flop.xml

Also renamed the existing entries to reflect the fact that they are cracked versions.
Detana!! TwinBee [r09]
Video Game Anthology vol. 11 - Pac-Land [cyo.the.vile]

x68k_flop.xml: 2 new dumps from original disks

---

hash/gamegear.xml

Ecco the Dolphin (prototype, 19930614) [drx]
Ecco the Dolphin (EPROM 20 prototype) [drx]

gamegear.xml: a pair of Ecco prototypes

---

src/devices/bus/nes/2a03pur.cpp
src/devices/bus/nes/act53.cpp
src/devices/bus/nes/bootleg.cpp
src/devices/bus/nes/cony.cpp
src/devices/bus/nes/event.cpp
src/devices/bus/nes/kaiser.cpp
src/devices/bus/nes/mmc3_clones.cpp
src/devices/bus/nes/nes_carts.cpp
src/devices/bus/nes/nes_ines.hxx
src/devices/bus/nes/nes_pcb.hxx
src/devices/bus/nes/nes_unif.hxx
src/devices/bus/nes/pirate.cpp

- updates to mapper # comments to ease cross referencing
- change MESS to MAME where appropriate

bus/nes: start updating mapper # comments

---

language/Portuguese_Brazil/strings.po

Updated translation to brazilian portuguese.

Updated translation

---

hash/nes.hsi
hash/nes.xml

Batman 4 (Batman - Return of the Joker pirate)
FIFA International 2' 96 (Goal!! pirate)
Pizza Pop Mario (Pizza Pop pirate)

nes.xml: hook pirate VRC4 carts up properly

---

src/mame/drivers/lwriter.cpp

Also change the mode to "Serial Batch Mode 9600 Baud"
from "AppleTalk".
The numbers correspond to documented values in
"Inside PostScript" (12-1)

lwriter.cpp: Implement switch setting.

---

src/devices/cpu/nanoprocessor/nanoprocessor.cpp
src/devices/cpu/nanoprocessor/nanoprocessor.h

Hi,
I've improved Nanoprocessor emulation to be closer to the real hw behavior. I recently completed a complete reverse engineering of the chip.
Thanks.
--F.Ulivi

nanoprocessor: various improvements

---

hash/nes.xml

- correctly split angrybr3 into 32K PRG and 64K CHR
- fix Plants vs Zombies garbled title screen
Angry Birds 3 (Chi)

nes.xml: fix a couple more Chinese pirate carts

---

src/mame/drivers/chanbara.cpp

https://mametesters.org/view.php?id=8024  confirms the sprite priority behaviour even if it looks ugly in places
I haven't fixed the sound tempo, it seems the only way you can do this is to adjust the YM clocks, but according to the driver notes the clocks are measured.  Could be another case like Street Fight, same chip, 2203.

chanbara.cpp - render low priority sprites

---

hash/samcoupe_flop.xml

Castle [World of SAM]
Lemmings [World of SAM]
Prince of Persia [World of SAM]
Sophistry [World of SAM]

samcoupe_flop.xml: New software list additions

---

hash/saturn.xml

All the changes are based on the information provided by _https://segaretro.org_

saturn.xml: Updated metadata (name; year)

---

hash/pc98.xml

OS/2 J2.11 [huoqianyu, flyingharuka]

pc98.xml: add OS/2 J2.11 dump

---

hash/fmtowns_cd.xml

- Renamed the Windows sets to reflect the actual names more properly, and changed the publisher field, since they were published by Fujitsu under license from Microsoft.
- Added the missing floppy disk to lettuce2 [cyo.the.vile]
- Replaced the rance4 floppy disk with a cleaner unmodified copy [cyo.the.vile]
Computer Zukan - Shokubutsu-hen [redump.org]
FM Towns II Demonstration CD-ROM '93 Winter [redump.org]
FM Towns Super Technology Demo 1993 (HME-219A) [redump.org]
GNU for Towns [redump.org]
Hyperland II - Mimi no Daibouken [redump.org]
Multimedia Communication Virtual Town - TC-Station - Computer Gakushuu Program [redump.org, cyo.the.vile]
Multimedia Communication Virtual Town - TC-Station - Computer Graphics & …

fmtowns_cd.xml: 25 new dumps, 12 replacements, add/replace floppies

---

hash/snes.xml

Addams Family Values (prototype) [snescentral, VGHF]
Armored Police Metal Jack (USA, early prototype) [snescentral, VGHF]
Congo's Caper (prototype) [snescentral, VGHF]
Might and Magic II - Gates to Another World (USA, prototype) [snescentral, VGHF]
Might and Magic II - Gates to Another World (USA, earlier prototype) [snescentral, VGHF]
Operation Thunderbolt (prototype) [snescentral, VGHF]
Rock n' Roll Racing (USA, prototype) [snescentral, VGHF]
Street Racer (prototype) [snescentral, VGHF]
Tom &amp; Jerry (USA, prototype, alt) [snescentral, VGHF]
World Cup USA 94 (USA, prototype) [snescentral, VGHF]
Mortal Kombat 3 (USA, final prototype) [togemet2] …

snes.xml: some recent prototype goodies

---

hash/nes.xml
src/devices/bus/nes/nes_carts.cpp
src/devices/bus/nes/nes_ines.hxx

4 in 1 (Alt 2)
4 in 1 (Alt 3)
Reset Based 4 in 1

nes.xml: Hooked up some multicarts to existing emulation.

---

hash/ibm5150.xml

Crime Wave (5.25", v1.1) [The Good Old Days]
Crime Wave (5.25", v2.0) [The Good Old Days]

ibm5150: New working software list additions

---

hash/ibm5170_hdd.xml

Caldera OpenDOS 7.01 [Davide Cavalca]
Caldera OpenDOS Lite 7.01 [Davide Cavalca]
DR DOS 7.03 [Davide Cavalca]
DR DOS Lite 7.03 [Davide Cavalca]
OS/2 Warp Connect with Win-OS/2 [Davide Cavalca]
OS/2 Warp with Win-OS/2 [Davide Cavalca]

ibm5170_hdd: new software lists additions

---

hash/next_hdd.xml

next_hdd: promote nextstep_3_1 and nextstep_3_2 to working

---

src/devices/machine/hp_taco.cpp

Hi,
I've just added the commands to read HP9825 tapes on HP9845 systems.
Thanks.
--F.Ulivi

hp_taco: commands to read HP9825 tapes added

---

hash/nes.xml
src/devices/bus/nes/bootleg.cpp
src/devices/bus/nes/bootleg.h
src/mame/machine/nes.cpp

bus/nes: Fixed a non-working SMB2 FDS conversion.

---

hash/nes.xml
src/devices/bus/nes/multigame.cpp
src/devices/bus/nes/multigame.h

bus/nes: Fixed a multicart game (mapper 229).

---

hash/nes.xml
src/devices/bus/nes/multigame.cpp
src/devices/bus/nes/multigame.h

- Fixed games: Volleyball, Paddle, Dynamite Bowling

bus/nes: Fixed the 3 non-working games in 11 in 1 Ball Series multicart.

---

src/mame/drivers/naomi.cpp

removed duplicate entry for "Driving Simulator"

remove duplicate entry

---

hash/amiga_hdd.xml
src/mame/drivers/amiga.cpp

Workbench 2.05 [Davide Cavalca]
Workbench 2.1 [Davide Cavalca]
Workbench 3.0 [Davide Cavalca]
Workbench 3.1 [Davide Cavalca]

amiga_hdd: add new software list

---

hash/ibm5150_hdd.xml

AT&T Personal Computer 6300 DOS Release 2.0 (MS-DOS 2.11) [Davide Cavalca]
MS-DOS (Version 3.30A) [Davide Cavalca]
MS-DOS (Version 4.00) [Davide Cavalca]
MS-DOS (Version 5.00) [Davide Cavalca]
Multitasking MS-DOS (Version 4.00) [Davide Cavalca]
IBM Personal Computer DOS (Version 2.00) [Davide Cavalca]
IBM Personal Computer DOS (Version 2.10) [Davide Cavalca]
IBM Personal Computer DOS (Version 3.00) [Davide Cavalca]
IBM Personal Computer DOS (Version 3.10) [Davide Cavalca]
IBM Personal Computer DOS (Version 3.20) [Davide Cavalca]
IBM Personal Computer DOS (Version 3.30) [Davide Cavalca]
Microsoft Windows Version 1.0 [Davide Cavalca]

ibm5150_hdd: new software list additions

---

hash/fm7_cass.xml

New WORKING software list additions:
Biotek [Cytlan, Gaming Alexandria]
Elevator Game [Cytlan, Gaming Alexandria]
Hitsuji Yaai [Cytlan, Gaming Alexandria]
Killer Station [Cytlan, Gaming Alexandria]
Kinasai [Cytlan, Gaming Alexandria]
Oozumou [Cytlan, Gaming Alexandria]
Shinjuwan Kougeki [Cytlan, Gaming Alexandria]
Yume no Pro Yakyuu [Cytlan, Gaming Alexandria]
New NOT_WORKING software list additions:
Crash Ball [Cytlan, Gaming Alexandria]
FM Racer [Cytlan, Gaming Alexandria]
New WORKING software list clones:
I wa Sanjutsu Nari (alt) [Cytlan, Gaming Alexandria]
Sokoban (alt) [Cytlan, Gaming Alexandria]
Space Warp (alt) [Cytlan, Gaming Alexandria]

fm7_cass: New software list additions

---

src/mame/drivers/naomi.cpp

naomi.cpp :
- correct PIN number for mask ROMs on 171-8132B carts
- small alignment
- game order by year/number

naomi.cpp : update notes 

---

hash/nes.xml
src/devices/bus/nes/mmc3_clones.cpp
src/devices/bus/nes/mmc3_clones.h
src/devices/bus/nes/nes_ines.hxx

19 in 1 (K-3088) [anonymous]
4 in 1 (411120-C)

bus/nes: Fixed 411120-C board emulation and added a compatible game.

---

hash/nes.xml
src/devices/bus/nes/multigame.cpp
src/devices/bus/nes/multigame.h

- Corrects certain games not loading or loading with corrupt graphics in different multicarts.

bus/nes: Fixed bugs in Game Star type "A" boards.

---

hash/fmtowns_cd.xml

- Redumped the vircall2 floppy disk [wiggy2k]
- Added the missing floppy disk to cm1denwa and nhkzkei2 [wiggy2k]
Anne no Yume no Kuni - Anne's Country of Dreams [redump.org]
ARS Art RentaLease - Kaiga Fukugou Kensaku System [redump.org]
C-Trace [redump.org]
Cover Girls Vol. 1 [redump.org]
Ed Bogas' Music Machine (HME-144A) [redump.org]
Enkaiou Ver. 3 - Chikyuu Saidai no Kessen [redump.org]
Exciting CD (Car Marty) [redump.org]
Fouge Vol. 2 - Masuo per Masuo - Ikeda Masuo Hanga-shuu (1994-07-08) [redump.org]
Hyper Eigo Gakushuu System - New Crown Series 2 [redump.org]
Hyper Eigo Gakushuu System - New Total English 2 [redump.org]
Image Power [redump.org]
Kanji no Ehon 2 [redump.org]
Kanji Land 3-nen (OSL-010) …

fmtowns_cd.xml: 30 new dumps, 17 replacements, add missing floppies

---

src/mame/drivers/miniguay.cpp

Found the manual, so updated some info about it

miniguay.cpp: Fix game name, add notes

---

src/mame/drivers/seibuspi.cpp

Referenced from Germany Raiden Fighters Jet manual.

seibuspi.cpp: Add/Fix notes for Jumper JP1

---

src/devices/sound/ics2115.cpp

Improved sound using next-state logic from column 126 of patent 5809466.
Some comparaison with real hardware needed.

ics2115: Improved sound using next-state logic

---

hash/nes.xml
src/devices/bus/nes/mmc3_clones.cpp
src/devices/bus/nes/mmc3_clones.h

- Reorganized sglionk (Super Game bootleg games) around lookup tables for its register/address scrambling.
- Implemented Boogerman it terms of sglionk, since it is functionally identical with different scrambling permutations.
The Lion King (pirate, alt 2) [Consolethinks]
Boogerman (Rus)

bus/nes: Fixed a Boogerman bootleg.

---

hash/pc98_cd.xml

Chuushaki - Hirasawa Nurse School [redump.org]
if - Invitations from Fantastic Stories [redump.org]
if 3 - Invitations from Fantastic Stories [redump.org]
Kanako [redump.org, wiggy2k]
Kousoku - Yorokobi no Aegi [redump.org]
Moonlight Energy 2 [redump.org]
Record of Lodoss War II - Goshiki no Maryuu [redump.org, wiggy2k]
Tania [redump.org]
The Silent Service - Chinmoku no Kantai [redump.org, wiggy2k]
Virtuacall [redump.org, wiggy2k]
Waku Waku Mahjong Panic! 2 - Kokushi Musou [redump.org]
OS/2 Warp V3 - Nihongo-ban [sampson]
Moonlight-chan Rinshan [redump.org]
Psychic Detective Series Vol. 4 - Orgel [redump.org]
Syndicate [redump.org] …

pc98_cd.xml: 16 new dumps, 21 replacements, sync with FM Towns softlist

---

hash/apple2_flop_clcracked.xml
hash/apple2_flop_orig.xml
hash/apple2gs_flop_orig.xml

Will leave this open for 24 hours before merging in case anyone wants any changes.

Apple softlist updates for August 2021

---

src/devices/cpu/e132xs/e132xsdrc_ops.hxx
src/devices/cpu/e132xs/e132xsop.hxx
src/mame/drivers/f-32.cpp

-royalpk2: Added lamps, inputs, and protection handling. MNW due to settings-saving issues. [Ryan Holtz]

royalpk2 fixes and updates

---

hash/nes.xml
src/devices/bus/nes/ave.cpp
src/devices/bus/nes/ave.h

Maxi 15 (Aus)
Maxi 15 (USA)
Maxi 15 (USA, v2.0)

bus/nes: Fixed several games not loading in Maxi 15 multicarts.

---

hash/nes.xml
src/devices/bus/nes/multigame.cpp
src/devices/bus/nes/multigame.h

Fixes corrupt graphics in multiple games on all seven multicarts (including the new addition). Fixes flickering menu for several carts, making them usable.
5000000 in 1 (JPx72) [anonymous]

bus/nes: Corrections for N625092 related multicarts.

---

hash/ibm5170.xml

DOOM (Japan, v1.1) [r09]
Doukyuusei [wiggy2k]
Doukyuusei 2 [wiggy2k]
Kairaku no Okite - Aoi Taiken [wiggy2k]

ibm5170.xml: 4 new dumps

---

hash/nes.xml
scripts/src/bus.lua
src/devices/bus/nes/batlab.cpp
src/devices/bus/nes/batlab.h
src/devices/bus/nes/nes_carts.cpp
src/devices/bus/nes/nes_ines.hxx
src/devices/bus/nes/nes_pcb.hxx
src/devices/bus/nes/nes_slot.cpp
src/devices/bus/nes/nes_slot.h
src/mame/machine/nes.cpp

Super Russian Roulette [re4mat]

bus/nes: Added support for Super Russian Roulette.

---

hash/samcoupe_flop.xml

Batz 'n Balls [worldofsam.org]
Domino Box [worldofsam.org]
Double Top [worldofsam.org]
Exodus [worldofsam.org]
Five on a Treasure Island [worldofsam.org]
Quizball [worldofsam.org]
Spell Master [worldofsam.org]
Splat! [worldofsam.org]

samcoupe_flop.xml: New working software list additions

---

hash/nes.xml
src/devices/bus/nes/batlab.cpp
src/devices/bus/nes/batlab.h
src/devices/bus/nes/nes_carts.cpp
src/devices/bus/nes/nes_ines.hxx
src/devices/bus/nes/nes_pcb.hxx
src/devices/bus/nes/nes_slot.h

bus/nes: Added support for Star Versus.

---

src/mame/drivers/hh_sm510.cpp

This change adds cheats to gnw_flagman, gnw_judge and gnw_lion. Thanks to Milan G. for finding them!

hh_sm510: Add cheats for gnw_flagman, gnw_judge and gnw_lion

---

hash/snes.xml

Raiden Densetsu (Jpn, prototype) [Gaming Alexandria]
Raiden Trad (USA, prototype) [Revenant]

snes.xml: Added Raiden prototypes.

---

hash/gameboy.xml

New working software list addition:
Sarakon (prototype) [Gaming Alexandria]

gameboy.xml: New working software list addition

---

hash/vsmilem_cart.xml

About "Toy Story 3" and "Super Why to the Rescue! - The Beach Day Mystery"

vsmilem_cart.xml: Add note about pocket carts being the same ROM as the motion ones

---

hash/nes.xml
src/devices/bus/nes/mmc3_clones.cpp
src/devices/bus/nes/mmc3_clones.h
src/devices/bus/nes/nes_carts.cpp
src/devices/bus/nes/nes_ines.hxx
src/devices/bus/nes/nes_pcb.hxx

bus/nes: Uncommented some existing code for Toy Story pirate cart.

---

hash/nes.xml

nes.xml: Added alternate PCB version of Gauntlet.

---

hash/nes.xml
src/devices/bus/nes/multigame.cpp

7 Grand Dad (The Flintstones - The Rescue of Dino &amp; Hoppy pirate) [anonymous]
Black Dragon (Korea) [NewRisingSun]
Flying Superboy (Korea) [NewRisingSun]
Miss Peach World 1 - Super L.A. Cop (Japan) [famiac]
Olympic I.Q. (Korea) [Gaming Alexandria]
1100000 in 1 [Consolethinks]
64 in 1 (CF-015) [Consolethinks]
9999999 in 1 - 1998 Series No. 10 [Consolethinks]
Super 98 - 43 in 1 (VT321) [Consolethinks]
4 in 1 (KG-443) [MrNorbert1994, Consolethinks]

nes.xml: Added a colorful potpourri of games.

---

src/devices/bus/snes/sa1.cpp
src/devices/bus/snes/sa1.h

Fix side effects issue, Split bitmap flag to bool variable
SA1 Frequency is derived from motherboard XTAL
also seen: https://github.com/VitorVilela7/SnesSpeedTest

sa1.cpp: Fix CPU speed, memory access cycle, Add notes

---

src/mame/machine/amstrad.cpp

amstrad: fix spelling/grammar in the comments

---

src/devices/sound/tt5665.cpp
src/devices/sound/tt5665.h

CSL pin controls voices in left channel, CSR pin controls voices for right channel
reference: TT5665 datasheet
constantize some variables

tt5665.cpp: Add support for separated voice command per output channel

---

hash/nes.xml
src/devices/bus/nes/pirate.cpp
src/devices/bus/nes/pirate.h

1996 Yīngyǔ CAI 3 in 1 (China) [taizou]
Xiǎoxuéshēng Shùxué CAI (China) [MLX]

bus/nes: Fixed loading and bank locking for EH8813A boards.

---

hash/snes.xml

Change the words "Prototype" and "Alt" to lowercase in the description

snes.xml: Change "Prototype" and "Alt" to lowercase

---

src/mame/includes/rmnimbus.h
src/mame/machine/rmnimbus.cpp
src/mame/video/rmnimbus.cpp

Updated RM Nimbus mouse code so mouse now mostly works, can use Windows 1.x/2.x/3.0
Updated RM Nimbus SASI/SCSI code so that formatting disks with HDFORM works
for ST125N and ST225N.
Added documentation of the video code drawn from the Nimbus Service manual.

Updated RM Nimbus mouse handling so it now mostly works.

---

hash/nes.xml
src/devices/bus/nes/mmc3_clones.cpp
src/devices/bus/nes/mmc3_clones.h

1994 New Series Red Pig 7 in 1 (EW-002) [anonymous]
1994 Super HiK 7 in 1 (M-026) [anonymous]
1994 Super HiK 7 in 1 (M-027) [anonymous]
7 in 1 (M-022)

bus/nes: Improved 830118C multicarts, all menu items now load.

---

hash/nes.xml

Gotta Protectors - Amazon's Running Diet [kmg]
Minna de Mamotte Knight - Amazon no Diet Daisakusen [kmg]

nes.xml: Added a pair of promotional releases.

---

hash/nes.xml
src/devices/bus/nes/rexsoft.cpp
src/devices/bus/nes/rexsoft.h

- Fixed CHR banking and mirroring issues. Clears up all graphics glitches in Rex Soft's Samurai Spirits.

bus/nes: Corrections for SL-1632 board.

---

hash/nes.xml

Airball (RetroZone) [anonymous]
Larry and the Long Look for a Luscious Lover [anonymous]
The Legends of Owlia [anonymous]
The Mad Wizard - A Candelabra Chronicle [Sly Dog Studios]
Mystic Pillars [anonymous]
Nomolos - Storming the Catsle [anonymous]
The Rise of Amondus [Sly Dog Studios]
Ultimate Frogger Championship [KHAN Games]

nes.xml: Added some homebrew games released on cartridge.

---

hash/nes.xml

Mega Man 2 - 30th Anniversary Classic Cartridge [kdawg]

nes.xml: Added a Mega Man 2 re-release.

---

hash/samcoupe_cass.xml

Corrected software list description

samcoupe_cass: Corrected software list description

---

hash/amiga_hdd.xml

Corrected the software list's description (added the manufacturer's name)

amiga_hdd: Corrected software list description

---

hash/fmtowns_cd.xml

- Added missing floppy disks to hypraddr2, hypland and iris [cyo.the.vile]
- Replaced the pharmony floppy disk with a cleaner unmodified image [cyo.the.vile]
- Replaced the royalbld bad floppy dump with a better one [cyo.the.vile]
Hyper Note (1992-03-03) [redump.org, cyo.the.vile]
Hyper Planet (1992-02-14) [redump.org, cyo.the.vile]
Man'youshuu [redump.org]
Märchen Toshokan - Grimm Douwa - Ibarahime (Nemurihime) [redump.org]
Märchen Toshokan - Grimm Douwa - Ookami to Shichihiki no Koyagi [redump.org]
Music Pro-Towns v1.3 (Naizou Ongenban) [redump.org]
TEATA - Vision - Recording & Playback System V1.0 [redump.org, cyo.the.vile]
TEATA - Vision - Recording & Playback System V1.1 [redump.org, cyo.the.vile]
TEATA - Vision …

fmtowns_cd.xml: 15 new dumps, 2 replacements, added floppies

---

hash/nes.xml
src/devices/bus/nes_ctrl/powerpad.cpp
src/devices/bus/nes_ctrl/powerpad.h

- Changed KEYPAD inputs to BUTTON with numbering following the pattern used in Family Trainer.
- Removed device_reset().
- Added strobe proper strobe bit behavior and reading 1s on excess reads.
- Made Running Stadium and Stadium Events games clones of World Class Track Meet, the last released variant of the same game.
Super Team Games (USA)

bus/nes_ctrl: Updated Power Pad code. Promoted all games to working.

---

hash/gamegear.xml
hash/sms.xml

New working software list additions (sms.xml)
Dead Angle (prototype) [smspower]
Thunder Blade (prototype) [HoverEel, smspower]
New working software list additions (gamegear.xml)
Streets of Rage II ~ Bare Knuckle II - Shitou e no Chingonka (prototype) [smspower, VGHF]

sms.xml, gamegear.xml: Added 2 Master System, 1 Game Gear prototypes.

---

hash/c64_cass.xml

Galactic Games (Activision) [C64 Ultimate Tape Archive V2.0]
Game Over II (Dinamic) [C64 Ultimate Tape Archive V2.0]
Garfield (The Edge) [C64 Ultimate Tape Archive V2.0]
Garfield: Winter's Tail (The Edge) [C64 Ultimate Tape Archive V2.0]
Gauntlet (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Gauntlet / Xevious (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Ghost Chaser (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Ghostbusters II (Activision) [C64 Ultimate Tape Archive V2.0]
Ghosts'n Goblins (Elite Systems) [C64 Ultimate Tape Archive V2.0]
Ghouls'n Ghosts (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Giants (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Glider Rider (Quicksilva) [C64 Ultimate Tape Archive V2.0]
Go Crazy …

c64_cass.xml: Added 34 entries

---

scripts/target/mame/arcade.lua
src/mame/arcade.flt
src/mame/drivers/rbowlorama.cpp
src/mame/mame.lst

Rockin' Bowl-O-Rama [Museo del Recreativo, ClawGrip]

New NOT_WORKING machine 

---

hash/gbcolor.xml

Lowercase on some description's words (like: Prototype, Alt, ...)

gbcolor.xml : Lowercase on some description's words

---

hash/nes.xml
scripts/src/bus.lua
src/devices/bus/nes_ctrl/ctrl.cpp
src/devices/bus/nes_ctrl/konamibag.cpp
src/devices/bus/nes_ctrl/konamibag.h

bus/nes_ctrl: Added support for Exciting Boxing air bag controller.

---

hash/ngpc.xml

----------
ngpc.xml:
Metal Slug - 1st Mission (prototype) [Brian Hargrove, Elliot Rosenberger]
this is a different code revision, not just different save data, it seems to freeze during attract demos, but that's probably just part of it being a proto

new software list entries

---

hash/fm77av.xml

Also marked the existing one as cracked.
Deep Forest [Katsura82, rockleevk, r09]

fm77av.xml: add protected Deep Forest image

---

hash/nes.xml
src/devices/bus/nes/mmc3_clones.cpp
src/devices/bus/nes/mmc3_clones.h
src/devices/bus/nes/nes_carts.cpp
src/devices/bus/nes/nes_ines.hxx
src/devices/bus/nes/nes_pcb.hxx
src/devices/bus/nes/nes_slot.cpp
src/devices/bus/nes/nes_slot.h
src/mame/drivers/nes_vt369_vtunknown.cpp
src/mame/mame.lst

Data East All-Star Collection [anonymous]
Mega Man 8 in 1 (PL-0006) [anonymous]
Super Games 143 in 1 (The Best Games of NES) [anonymous]
CoolBoy 198 in 1
CoolBoy 400 in 1
CoolBoy 400 in 1 (alt, 403 games)
Game 450 in 1
Game 500 in 1
Pocket Games 150 in 1
Super Game 218 in 1 (JF2181)
Super Game 360 in 1
Super Game 402 in 1

bus/nes: Added support for boards using the SMD133 ASIC.

---

src/mame/drivers/zr107.cpp

I fixes ZR107 Tilemap Position reference PCB Video, also fixes tilemap gabage in titlescreen

ZR107 Tilemap Position Fixes [sjy96525]

---

hash/nes.xml
src/devices/bus/nes/mmc3_clones.cpp

- Also corrected VRAM amount for mc_101, fixing graphics issues.
125 in 1 (JY-125) [MLX]
130 in 1 (JY-130) [MLX]
Mario Family 7 in 1 [MLX]
Super 13 in 1 [famiac, NewRisingSun]

nes.xml: Added 4 multicart dumps.

---

hash/nes.xml

Booky Man (Brazil) [fcgamer]
Captain Planet and the Planeteers (pirate) [Consolethinks, Nikolka]
Destroyer (Asia) [MLX]
FIFA International Soccer '96 (J.League Winning Goal pirate) [NewRisingSun]
Go! Benny! (Asia) [joanna88, krzysiobal]
Over Horizon (pirate) [Consolethinks]
Pokemon 2000 (Felix the Cat pirate) [SupahRetroooo]
Super Contra DS (Super Contra pirate) [famiac, NewRisingSun]
Super Mario 15 (Kaiketsu Yanchamaru 3 - Taiketsu! Zouringen pirate) [mt777]
Xiǎo Bǎikē 2 in 1 - Dūdū Wāwā Dà Màoxiǎn & Zhìlì Pīntú (China) [tenyuhuang]
Xiǎo Zhuàngyuán Shùxué (China) [MLX]
Xītiān Qǔjīng - Journey To The West (Asia) [taizou]

nes.xml: Added 12 bootleg and unlicensed cartridge dumps.

---

hash/gba.xml

Mechanic Mechanica (Japan, prototype) [forestillusion]

gba.xml: Added an unreleased game.

---

hash/32x.xml

Lowercase on some description's words (like: Prototype, Set, ....)

32x.xml : Lowercase on some description's words

---

README.md

Delete travis-ci.org badge from README.md.

Delete travis-ci.org badge from README.md.

---

hash/apple2_flop_clcracked.xml

Chariots, Cougars, and Kings (Version 03.12.86) (cleanly cracked) [4am, Firehawke]
Punctuation Skills: Commas (cleanly cracked) [4am, Firehawke]
Logic Workout (cleanly cracked) [4am, Firehawke]
Apple Project Manager (cleanly cracked) [4am, san, Firehawke]
A-mazing Words (cleanly cracked) [4am, Firehawke]
Mighty Math (cleanly cracked) [4am, Firehawke]
Take Me North (cleanly cracked) [4am, Firehawke]
Space Port (cleanly cracked) [4am, Firehawke]
Word-Player (cleanly cracked) [4am, Firehawke]
Dividing Decimals (Version 1.1) (cleanly cracked) [4am, Firehawke]
Percentage Panic (cleanly cracked) [4am, Firehawke]
Moonlight and Madness Level II (Version 04.19.88) (cleanly cracked) [4am, Firehawke]

New working software list additions (apple2_flop_clcracked.xml)

---

src/devices/bus/nscsi/hd.cpp

ncsi/hd.cpp: Copy "MODE SELECT 6" from cd.cpp

---

hash/nes.xml
src/devices/bus/nes_ctrl/arkpaddle.cpp
src/devices/bus/nes_ctrl/arkpaddle.h

- Added daisy chain expansion port to Famicom paddle for Arkanoid II's versus mode.
- Also expanded range of paddle value reads to ensure full range of motion within all games' play fields.

bus/nes_ctrl: Updated Arkanoid paddles.

---

hash/gba.xml

Perplexus Diodomin (prototype) [James Boulton, GTW]

gba.xml: Added another unreleased game.

---

hash/gamegear.xml

BreakThru! (prototype) [smspower, VGHF]

gamegear.xml: Added a non-working prototype.

---

hash/ibm5170.xml

Laser Squad (3.5", USA) [The Good Old Days]
Laser Squad (5.25", Euro) [The Good Old Days]
Night Shift [old-games.ru]
Push-Over [The Good Old Days]
Quest for Glory: Shadows of Darkness [The Good Old Days]
Quest for Glory I: So You Want to Be a Hero [The Good Old Days]
Quest for Glory III: Wages of War [The Good Old Days]
Quicky: The Computer Game (Euro) [old-games.ru]
Tony & Friends in Kellogg's Land (Germany) [old-games.ru]
Creepers [The Good Old Days]
_(the replaced set had a modified OEM ID)_

ibm5170.xml: New software list additions

---

src/mame/audio/flower.cpp
src/mame/audio/flower.h
src/mame/drivers/flower.cpp

Use tilemap_t for text layer
Add hardware notes
Add notes for unknown sound register writes
Add sound io register value for debug purpose
Fix initializing behavior
Use shorter/correct type values, Fix spacings
Reference:
https://youtu.be/ycbJMG09UZ0
https://youtu.be/NolazjlEiAY
https://youtu.be/8JOPTCWu67g

flower.cpp: Replace hardcoded tags to region pointers, Fix some sound/cocktail mode behaviors

---

hash/nes.xml
src/devices/bus/nes_ctrl/partytap.cpp
src/devices/bus/nes_ctrl/partytap.h

- Project Q now detects the controller and inputs work.

bus/nes_ctrl: Updated Partytap controller.

---

hash/nes.xml
src/mame/drivers/nes.cpp
src/mame/includes/nes.h
src/mame/machine/nes.cpp

Minna no Taabou no Nakayoshi Daisakusen (Japan) [kmg]

machine/nes.cpp: Accomodate games that don't initialize RAM.

---

hash/ibm5170_cdrom.xml

New software list additions
SkyNET [Dave 'Foxhack' Silva]
Terminator 2: Judgment Day - Chess Wars / Grandmaster Chess [Dave 'Foxhack' Silva]
The Terminator: 2029 - Deluxe CD Edition [Dave 'Foxhack' Silva]
The Terminator: Future Shock [Dave 'Foxhack' Silva]
The Terminator: Rampage [Dave 'Foxhack' Silva]

ibm5170_cdrom.xml

---

hash/n64.xml

Controller Checker Ver.1.01 [BehindTheCode, Forest of Illusion]
Unknown RGB Test Cartridge [BehindTheCode, Forest of Illusion]

n64.xml: Added a couple test/demo cartridges.

---

hash/nes.xml

Hero Quest (Germany, prototype) [anonymous]

nes.xml: Added an unreleased prototype.

---

hash/nes.xml

8Bit Music Power [anonymous]
8Bit Music Power Final [anonymous]
Kira Kira Star Night DX [anonymous]
Neo Heiankyo Alien [anonymous]

nes.xml: Added some more recent chiptune related fare.

---

hash/nes.xml
src/devices/bus/nes_ctrl/ctrl.cpp
src/devices/bus/nes_ctrl/mjpanel.cpp
src/devices/bus/nes_ctrl/mjpanel.h
src/emu/inpttype.ipp

- Fixed reversed Start and Select buttons.
- Added more labels to the multi-use buttons.

bus/nes_ctrl: Updated mahjong controller based on hardware info.

---

src/mame/drivers/hp9825.cpp

Hi,
this PR upgrades hp9825 emulation to prepare it for the keyboard & display layout I'm going to release soon.
Thanks.
--F.Ulivi

hp9825: changes to keyboard & other minor fixes

---

hash/ibm5150.xml

The Dream Team: 3 on 3 Challenge [old-games.ru]
Hero's Quest: So You Want to be a Hero [The Good Old Days]
Last Ninja 2: Back with a Vengeance [The Good Old Days]
Police Quest II - The Vengeance (3.5", v1.001.000) [The Good Old Days]
Rick Dangerous (Kixx release) [The Good Old Days]
Rocket Ranger (UK) [The Good Old Days]
SimEarth: The Living Planet (Europe, 5.25", v1.0) [The Good Old Days]
Blades of Steel [The Good Old Days]
Police Quest II - The Vengeance (5.25", v1.002.011, Sierra's Value Pack) [The Good Old Days]
Police Quest II - The Vengeance (3.5", v1.002.011, Sierra's Value Pack) [The Good Old Days]

ibm5150.xml: 7 New working softwares + 3 redumps

---

hash/n64.xml

X'treme Roller (prototype) [Baker64]

n64.xml: Added a prototype of an unreleased game.

---

hash/nes.xml

Holy Diver Collector's Edition [anonymous]

nes.xml: Added Holy Diver rerelease.

---

src/mame/drivers/cdi.cpp
src/mame/includes/cdi.h
src/mame/machine/cdicdic.cpp
src/mame/machine/cdicdic.h
src/mame/machine/cdislavehle.cpp
src/mame/machine/cdislavehle.h

-cdi: Significantly improved compatibility and re-promoted to working [Ryan Holtz, CD-i Fan]

Complete re-write of Philips CD-i CDIC handling; re-promoted to working

---

src/mame/drivers/rohga.cpp

- drop sound levels in rohga.cpp

sound level adustments to avoid clipping / compressor

---

src/mame/machine/cdicdic.cpp

-cdicdic: Fixed audio crackling, and fixed various hangs. [Ryan Holtz, CD-i Fan]

CD-i updates.

---

src/mame/audio/dcs.cpp
src/mame/audio/dcs.h
src/mame/drivers/pinball2k.cpp

added a working pinball 2k driver including DCS2.
Please read the notes in the driver

pinball2k driver

---

hash/fmtowns_cd.xml

- Replaced the emit1 floppy disk with a clean unmodified image [fuzzball]
Emit Vol. 1 - Toki no Maigo (Version 1.30 Release 2.00) [redump.org, fuzzball]
F-BASIC386 v1.1 L10 [redump.org]
F-BASIC386 v1.1 L10B [redump.org]
Shadow of the Beast - Mashou no Okite (1991-10-11) [redump.org]
Technostress Yobouhou Series - Chinsei [redump.org]
Technostress Yobouhou Series - Stress [redump.org]
Towns System Software V1.1 L10B [redump.org]
TownsSOUND V1.1 L10 [redump.org]
Psychic Detective Series Vol. 3 - Aya (DCCS remake) [redump.org]
Psychic Detective Series Vol. 5 - Nightmare (DCCS remake) [redump.org]

fmtowns_cd.xml: 10 new dumps

---

src/mame/audio/dcs.cpp
src/mame/audio/dcs.h
src/mame/drivers/pinball2k.cpp

Revert "pinball2k driver"

---

hash/sms.xml

Astro Warrior & Pit Pot (Euro, alt) [smspower]
Dynamite Dux (prototype) [smspower]
Rampage (prototype) [smspower]
Summer Games (Euro, early prototype) [smspower]

sms.xml: Added 4 dumps.

---

scripts/src/tools.lua
src/tools/floptool.cpp

Before merging, this needs to be cleared with an expert on the GEnie build scripts

Added a '-version' parameter to floptool

---

src/tools/floptool.cpp

- Getting the name of the tool from argv[0] (stop hardcoding floptool.exe)
- Adding missing hddir/hdread/hdwrite declarations

Fixing floptool usage message:

---

hash/cdi.xml

Added the manufacturer's name in the Software List's description

cdi.xml - Added the manufacturer's name

---

src/mame/drivers/hh_sm510.cpp

This PR updates the SVG display file for nupogodi with an improved version done by Milan Galcik.

hh_sm510: display improvements for nupogodi

---

hash/nes.xml
src/devices/bus/nes/mmc3_clones.cpp
src/devices/bus/nes/mmc3_clones.h
src/devices/bus/nes/nes_slot.cpp
src/devices/bus/nes/nes_slot.h

The King of Fighters 96 (Asia) [kmg]

bus/nes: Simplified KOF96 board. Removed deprecated poke().

---

hash/c64_cass.xml

Mikie (Imagine) [C64 Ultimate Tape Archive V2.0]
Missile Command (Interceptor Software, alt) [C64 Ultimate Tape Archive V2.0]
Mission Elevator (Micropool) [C64 Ultimate Tape Archive V2.0]
Monte Carlo Casino (Codemasters) [C64 Ultimate Tape Archive V2.0]
Monty on the Run (Gremlin Graphics) [C64 Ultimate Tape Archive V2.0]
Motor Massacre (Gremlin Graphics) [C64 Ultimate Tape Archive V2.0]
Mutants (Ocean) [C64 Ultimate Tape Archive V2.0]
My Life (Psytronik Software) [C64 Ultimate Tape Archive V2.0]
Mystery of the Nile (Firebird) [C64 Ultimate Tape Archive V2.0]
Myth: History in the Making (System 3) [C64 Ultimate Tape Archive V2.0]
N.O.M.A.D (Ocean) [C64 Ultimate Tape Archive V2.0]

c64_cass.xml: Added eleven working items

---

hash/nes.xml
src/devices/bus/nes/mmc3_clones.cpp
src/devices/bus/nes/mmc3_clones.h

bus/nes: Simplified Kay A9711 board and fixed multicart support.

---

hash/nes.xml

Battle Kid - Fortress of Peril (v1.100) [anonymous]
Battle Kid - Fortress of Peril (v1.000) [anonymous]
Battle Kid - Kiken no Wana (Japan, v2.000) [anonymous]
Battle Kid 2 - Mountain of Torment (v1.000) [anonymous]

nes.xml: Added 4 new dumps.

---

src/devices/machine/upd765.cpp

- Check for write protect during the Write Data & Format Track commands, fail and return the NW bit if disk is write protected
- Make Format Track return ST1 and ST2
Fixes the IBM PC BIOS not detecting write protected disks

upd765: Check write protect during write & format commands

---

src/devices/cpu/mb88xx/mb88xx.cpp
src/mame/audio/namco52.cpp
src/mame/audio/namco52.h
src/mame/audio/namco54.cpp
src/mame/audio/namco54.h
src/mame/drivers/galaga.cpp
src/mame/machine/namco06.cpp
src/mame/machine/namco06.h
src/mame/machine/namco50.cpp
src/mame/machine/namco50.h
src/mame/machine/namco51.cpp
src/mame/machine/namco51.h

Various accuracy fixes for the Namco custom chips.
This fixes https://mametesters.org/view.php?id=7892

Namco custom chip improvements

---

hash/lynx.xml

Klax (prototype) [peekb]
Pit-Fighter - The Ultimate Competition (prototype 19921013) [Hidden Palace, Steve Lin]

lynx.xml: Added two prototypes.

---

hash/32x.xml

Spot Goes to Hollywood (prototype) [Hidden Palace, VGHF]
Time Warner 32X CMD Download Cartridge [Hidden Palace, Steve Lin]

32x.xml: Added two new dumps.

---

hash/tg16.xml

PC Denjin - Pankic Cyborgs (Air Zonk prototype) [Hidden Palace, VGHF]
TV Sports Baseball (prototype) [Hidden Palace, VGHF]

tg16.xml: Added two prototypes.

---

hash/nes.xml

Bio Force Ape (USA, prototype) [Hidden Palace]
QuarterBack Scramble (USA, prototype) [VGHF]

nes.xml: Added two prototypes.

---

hash/snes.xml

Mer Wars (prototype) [Hidden Palace, Steve Lin]
Reactor (prototype) [Hidden Palace, Steve Lin]
Mr. Tuff (Euro, prototype 19940621) [Hidden Palace]
Nightmare Busters (Japan, prototype 19940409) [Hidden Palace]
Super Full Metal Planet (prototype B) [Hidden Palace]
Super Full Metal Planet (prototype C) [Hidden Palace]
Super Full Metal Planet (prototype D) [Hidden Palace]

snes.xml: Added seven prototypes.

---

hash/gba.xml

Robocop (prototype) [Hidden Palace, Marcal Mora]

gba.xml: Added a prototype.

---

hash/gbcolor.xml

San Francisco Rush - Extreme Racing (prototype) [Hidden Palace, Steve Lin]

gbcolor.xml: Added a prototype.

---

hash/gameboy.xml

Blade Warrior (prototype) [Hidden Palace]
Dungeon Warrior (prototype) [Hidden Palace]
Jet Pak Jak (prototype) [Hidden Palace]
Jet Pak Man (prototype) [Hidden Palace]
John Madden Football (prototype) [Hidden Palace, VGHF]
Nintendo Game Boy Aging Cartridge (Ver 1.1) [Hidden Palace]
Learn and Play Blackjack & Solitaire (prototype) [Hidden Palace, VGHF]

gameboy.xml: Added seven prototypes.

---

hash/megadriv.xml
hash/nes.xml

Beethoven's 2nd - The Quest for Pups (prototype) [Hidden Palace, drx]
Lobo (April prototype) [Hidden Palace, VGHF]
Out of the Vortex (prototype) [Hidden Palace] [Hidden Palace]
Payne Stewart Pro Golf (prototype A) [Hidden Palace]
Payne Stewart Pro Golf (USA, prototype B) [Hidden Palace, Steve Lin]
R.B.I. Baseball '95 (prototype) [Hidden Palace, Steve Lin]
Road Riot 4WD (prototype) [Hidden Palace]
Space Hero (prototype) [Hidden Palace]

megadriv.xml: Added eight prototypes.

---

src/devices/bus/nes/sunsoft.cpp

- Removed hard-coded NTSC timing. Improves raster-split effects for the two PAL games, Mr. Gimmick and Batman Return of the Joker.
- Clear IRQs for any write to IRQ control register, as confirmed by hardware tests.

nes/bus: Small fixes for Sunsoft FME-7 IRQ.

---

hash/nes.xml
src/devices/bus/nes/mmc3_clones.cpp
src/devices/bus/nes/mmc3_clones.h

Ultimate Mortal Kombat 3 (Asia, 14 characters) [kmg]

bus/nes: Simplified H2288 board a bit.

---

hash/apple2_flop_clcracked.xml
hash/apple2_flop_orig.xml

Includes "Glutton", which is an interesting historic artifact that was almost lost permanently.

Apple II updates for January 2022

---

src/mame/drivers/naomi.cpp

Just an update for the 18wheelr set on the NAOMI driver that I have added the subtitle to the game name.

naomi.cpp -  Some game name consistencies, added subtitle to 18wheelr and clones.

---

hash/megadriv.xml

Ex-Mutants (prototype) [Hidden Palace, VGHF]
Fantastic Dizzy (prototype) [David Rogers]
Flashback (prototype 19920918) [Hidden Palace]
Junker's High (later prototype) [Hidden Palace]
Kick Off 3 (prototype) [Hidden Palace, VGHF]
Lakers versus Celtics and the NBA Playoffs (prototype) [Hidden Palace, Steve Lin]
Micro Machines 2 - Turbo Tournament (prototype) [Hidden Palace]
Muhammad Ali Heavyweight Boxing (USA, later prototype) [Hidden Palace, VGHF]
NFL 98 (prototype) [Hidden Palace]
Race Drivin' (prototype) [Hidden Palace]
Slap Fight MD (prototype) [Hidden Palace]
Sylvester & Tweety in Cagey Capers (prototype) [Hidden Palace, VGHF]
Twisted Flipper (later prototype) [Hidden Palace]
Wayne Gretzky and the NHLPA All-Stars …

megadriv.xml: Added 15 prototypes.

---

hash/fmtowns_cd.xml

- Added missing floppy images to akikogld and tenranma [wiggy2k]
Kyouiku & FM Towns [redump.org]
Nihon no Chou [redump.org]
Doda Mega-Mix!!! [redump.org]
High C Compiler Multimedia Kaihatsu Kit v1.7 L13 [redump.org]
Prince of Persia [redump.org]
That's Toukou Part 2 [redump.org]
Wrestle Angels 3 - Mezasu wa Saikyou Dantai! [redump.org]
Akiko Gold [wiggy2k]

fmtowns_cd.xml: 2 new dumps, 5 replacements

---

hash/fmtowns_flop_orig.xml

- Replaced kawaichi disk A with a clean unmodified image [wiggy2k]
Setsujuu - Yuganda Kioku [cherokee]
Youjuu Club Custom [cherokee]

fmtowns_flop_orig.xml: 2 new dumps, 1 replacement

---

hash/c64_cass.xml

Neoclyps (Personal Software Services) [C64 Ultimate Tape Archive V2.0]
The Neverending Story (Ocean) [C64 Ultimate Tape Archive V2.0]
Ninja Massacre (Code Masters) [C64 Ultimate Tape Archive V2.0]
Ninja Remix (System 3) [C64 Ultimate Tape Archive V2.0]
North & South (Infogrames) [C64 Ultimate Tape Archive V2.0]
Nemesis the Warlock (Martech) [C64 Ultimate Tape Archive V2.0]

c64_cass.xml: Added six items (five working, one not working)

---

hash/a800_flop.xml

New working software list addition
Atari LiteDOS-SE [Mr.Atari]

a800_flop.xml: New working software list addition

---

hash/c64_cass.xml

Ocean's All Star Hits (Ariolasoft) [C64 Ultimate Tape Archive V2.0]
Ocean's Greatest Hits (Ocean) [C64 Ultimate Tape Archive V2.0]
Oink! (CRL) [C64 Ultimate Tape Archive V2.0]
On the Tiles (Firebird) [C64 Ultimate Tape Archive V2.0]
Operation Wolf (Ocean) [C64 Ultimate Tape Archive V2.0]
Out Run (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Outback (Paramount Software) [C64 Ultimate Tape Archive V2.0]
Overlander (Elite Systems) [C64 Ultimate Tape Archive V2.0]

c64_cass.xml: Added eight working items

---

hash/nes.xml
src/devices/bus/nes/2a03pur.cpp
src/devices/bus/nes/2a03pur.h

bus/nes: Fixed 2A03PURITANS board not booting when <1024k.

---

hash/snes.xml

Prince of Persia (prototype) [Hidden Palace]
Putty Squad (prototype) [Hidden Palace]
Race Drivin' (prototype) [Hidden Palace, Steve Lin]
Shadowrun (prototype) [Hidden Palace, Stephan Reese]
Super Ghouls'n Ghosts (prototype) [Hidden Palace]
The Ignition Factor (prototype) [Hidden Palace]
The Peace Keepers (prototype) [Hidden Palace]
Troddlers (prototype 19921023) [Hidden Palace, Steve Lin]
Troddlers (prototype 19930203) [Hidden Palace]
Utopia - The Creation of a Nation (prototype) [Hidden Palace]

snes.xml: Added 10 prototypes.

---

src/mame/drivers/playch10.cpp
src/mame/machine/playch10.cpp

- Mark Excite Bike and Ninja Gaiden 2 as imperfect graphics.

playch10.cpp: Correct NT mirroring for various games (MT 02646).

---

src/mame/drivers/cv1k.cpp

pinkswtssc has it's own homepage (http://suicideclub.gameordie.com/), it confirms hacker name.

cv1k.cpp: Fix hardware notes, Add pinkswtssc notes

---

hash/lynx.xml

Lowercase in the description "prototype" word

lynx.xml: Lowercase in the description "prototype" word

---

hash/cdi.xml

Added the cloneof="aliengat" tag, to the [aliengatu] and [aliengatu1] sets

cdi.xml: metadata cleanup (parent/cloneof)

---

hash/snes.xml

Asterix (prototype 19930311) [Hidden Palace]
Magic Boy (prototype) [snescentral]
Marvel Super Heroes - War of the Gems (Japan, prototype) [Hidden Palace, Steve Lin]
MechWarrior (prototype) [Hidden Palace, Stephan Reese]
NBA All-Star Challenge (prototype) [Hidden Palace]
NBA Live 97 (prototype 19960920) [Hidden Palace]
Prehistorik Man (prototype) [Hidden Palace]
Illusion of Gaia (prototype B) [Hidden Palace, Stephan Reese]

snes.xml: Added 8 prototypes.

---

hash/coco_cart.xml

Changed working software list
<hr>
changed hash of Canyon Climber.

coco_cart.xml: fix hash of Canyon Climber

---

hash/ibm5170.xml

Armour-Geddon [The Good Old Days]
Eye of the Beholder 3: Assault on Myth Drannor [The Good Old Days]
Eye of the Beholder 3: Assault on Myth Drannor (Eye of Beholder Trilogy release) [The Good Old Days]
Eye of the Beholder 3: Assault on Myth Drannor (Kixx release) [The Good Old Days]
Eye of the Beholder 3: A l'assaut de Myth Drannor (France) [The Good Old Days]
Eye of the Beholder 3: Sturm auf Myth Drannor (Germany) [The Good Old Days]
Formula One Grand Prix (Euro, v1.05, alt) [ibmpc5150, archive.org]
Might and Magic III: Isles of Terra (3.5"DD) [The Good Old Days]
Might and Magic III: Isles of Terra (5.25"HD) [The Good Old Days]
Operation Body Count [ibmpc5150, archive.org]
Railroad Tycoon Deluxe [The Good Old Days]
Star Wars: TIE Fighter (Spain) …

ibm5170.xml: 16 entries added + 1 redumped

---

hash/jaguar.xml

Speedster II [Gaming Alexandria]

jaguar.xml: Added an unreleased prototype.

---

src/devices/bus/isa/mach32.cpp
src/devices/bus/isa/s3virge.cpp
src/devices/bus/isa/svga_cirrus.cpp
src/devices/bus/isa/svga_s3.cpp
src/devices/bus/isa/svga_trident.cpp
src/devices/bus/isa/svga_tseng.cpp
src/devices/bus/isa/trident.cpp
src/devices/bus/isa/vga.cpp
src/devices/bus/isa/vga_ati.cpp
src/devices/video/clgd542x.cpp
src/devices/video/pc_vga.cpp
src/devices/video/pc_vga.h
src/devices/video/virge_pci.cpp
src/mame/drivers/bebox.cpp
src/mame/drivers/gambl186.cpp
src/mame/drivers/gamtor.cpp
src/mame/drivers/konmedal020.cpp
src/mame/drivers/magtouch.cpp
src/mame/drivers/pcat_dyn.cpp
src/mame/drivers/photoply.cpp
src/mame/drivers/vis.cpp
src/mame/machine/pcshare.cpp

As discussed in https://github.com/mamedev/mame/commit/2b2e918981ac2ae03388475bae0ad1ee95d323d8

vga: made video RAM size configurable at machine configuration

---

hash/nes.xml

Family BASIC (Japan, V1.0) [No-Intro]
Playbox BASIC (Japan, V1.0) [PALCOLOR]
Playbox BASIC (Japan, V0.0)

nes.xml: Added original Family BASIC cartridge.

---

hash/fm77av.xml
hash/fm7_cass.xml
hash/fm7_disk.xml
hash/pc8801_flop.xml

New working software list additions (fm77av.xml)
------------------------------------------------
The 4th Unit 2 [r09]
New working software list additions (fm7_disk.xml)
--------------------------------------------------
FM Logo 2.0 [sampson]
Chikyuu Senshi Rayieza [r09]

fm7_disk.xml/fm77av.xml: add 3 new dumps

---

src/mame/drivers/decocass.cpp
src/mame/mame.lst

-----
The Tower (DECO Cassette) (Europe?) [Darksoft, Senil Data Systems]

new WORKING machine (The Tower)

---

hash/c64_cass.xml

Quartet (Activision) [C64 Ultimate Tape Archive V2.0]
QUATTRO Coin-Ops (Codemasters) [C64 Ultimate Tape Archive V2.0]
Quedex (Thalamus) [C64 Ultimate Tape Archive V2.0]

c64_cass.xml: Added three working items

---

src/mame/drivers/naomi.cpp

Todd McFarlane without the space between the Mc and Farlane.  Just a typo fix.

naomi.cpp: spawn - Correction on illustrator surname.

---

src/mame/drivers/nmk16.cpp

reference: https://mametesters.org/file_download.php?file_id=4878&type=bug

nmk16.cpp: Add notes of Thunder Dragon 3 Bootleg hardware

---

hash/midi_flop.xml

midi_flop: Hikari Navigation (FL-90) (Japan) [Devin Acker]

New working software list item

---

src/devices/bus/a2bus/a2mockingboard.cpp

The ECHO+ uses a single VIA to address two PSGs. The BC2 lines of the PSGs are connected to PB3 and PB4 respectively. Both PSGs are reset through PB2.
The changes were tested with the ECHO+ demo disk. Now the chords in the music demo play correctly.

Fixed the second PSG addressing on the ECHO+

---

src/mame/drivers/galaxian.cpp

galaxian.cpp: Dumped PROM and bad gfx ROM from Mandinka [Victor Fernandez (City Game), ClawGrip]

---

src/mame/drivers/midzeus.cpp

The PIC still need to be properly hooked up
Also reformatted single-line comments on the ROM definitions

midzeus.cpp: Add Cruis'n Exotica (and clones) PIC dump [Caps0ff, Darksoft, Mitsurugi_w]

---

src/devices/sound/k007232.cpp

reference: https://github.com/furrtek/VGChips/tree/master/Konami/007232 (based on reverse engineering)

k007232.cpp: Fix frequency bits, Add notes

---

hash/megacd.xml
hash/megacdj.xml
hash/segacd.xml

segacd.xml - megacd.xml - megacdj.xml: Lowercase on some description's words

segacd.xml - megacd.xml - megacdj.xml: Description lowercase

---

src/mame/drivers/famibox.cpp

- Joypads now swap depending on which one hit start on game select menu.
- Controller inputs ignored during attract mode before inserting coin.
- Minor cleanups of cart switching.

famibox.cpp: Added some input control bits.

---

src/osd/mac/window.cpp
src/osd/modules/render/bgfx/chainentryreader.cpp
src/osd/modules/render/bgfx/chainmanager.cpp
src/osd/modules/render/bgfx/effect.h
src/osd/modules/render/bgfx/effectmanager.cpp
src/osd/modules/render/bgfx/effectmanager.h
src/osd/modules/render/bgfx/effectreader.cpp
src/osd/modules/render/bgfx/effectreader.h
src/osd/modules/render/bgfx/shadermanager.cpp
src/osd/modules/render/bgfx/shadermanager.h
src/osd/modules/render/bgfx/texturemanager.cpp
src/osd/modules/render/bgfx/view.cpp
src/osd/modules/render/drawbgfx.cpp
src/osd/modules/render/drawbgfx.h
src/osd/sdl/window.cpp
src/osd/windows/window.cpp

- bgfx: Improved stability when encountering missing files, and improved multi-window stability. [Ryan Holtz]

More BGFX stability improvements (missing files + multi-window)

---

hash/nes.xml

Advanced Dungeons & Dragons - Hillsfar (USA, prototype) [Hidden Palace]
Caesars Palace (USA, prototype, alt) [Hidden Palace, VGHF]
Dr. Mario (prototype, alt 2) [Hidden Palace, Stephan Reese]
Dragon Warrior II (USA, prototype) [Hidden Palace, Stephan Reese]
Moero!! Junior Basket - Two on Two (Japan, prototype) [Hidden Palace]
NES Open Tournament Golf (USA, prototype) [Hidden Palace, Stephan Reese]
NES Play Action Football (USA, prototype) [Hidden Palace, Stephan Reese]
Ninja Hattori-kun (Japan, prototype) [togemet2]
Star Soldier (Japan, prototype) [togemet2]
Tonjan!? (Japan, prototype) [togemet2]
Hitler no Fukkatsu - Top Secret (Japan, prototype) [togemet2]

nes.xml: Added eleven prototypes.

---

src/mame/drivers/vsnes.cpp
src/mame/includes/vsnes.h
src/mame/machine/vsnes.cpp

- Added address maps for PPUs, eliminating some variables and associated setup.
- Separated banking from base light gun input handler.

vsnes.cpp: Simplified graphics memory handling a bit.

---

hash/nes.xml

8Bit Rhythm Land [anonymous]
DuckTales (USA, 19890205 prototype) [TCRF]
Freedom Force (USA, 19871229 prototype) [Hubz]
Hot Dance with Samba (Asia) [krzysiobal]
Metal Storm Collector's Edition [anonymous]
Rainbow Brite - Journey to Rainbow Land [anonymous]

nes.xml: Added six miscellaneous dumps.

---

src/mame/drivers/coco3.cpp
src/mame/mame.lst

This is a Mexican Color Computer 3, with a revised BASIC ROM.
Thanks to @abcbarryn for the ROM.

new working clone: Micro-Sep Model 3

---

hash/megadriv.xml

16Bit Rhythm Land [anonymous]
Castlevania - Bloodlines (USA, 19931003 prototype) [Simon_Belmont, Pulse_Project]
Castlevania - Bloodlines (USA, 19930804 prototype) [Billscat-socks]
Dune - The Battle for Arrakis (prototype, Ver 0.03) [GamingLegend64, Hard4Games, Forest of Illusion]
Mortal Kombat 3 (prototype) [sadikyo]

megadriv.xml: Added 5 new dumps.

---

hash/ibm5150.xml

Dragon's Lair (5.25") [ibmpc5150, archive.org]
Ghostbusters II [ibmpc5150, archive.org]
Hillsfar (v1.0, 5.25") [The Good Old Days]
Hillsfar (v1.0, 3.5") [The Good Old Days]
Hillsfar (v1.1, 3.5") [The Good Old Days]
Hillsfar (v1.2, 3.5") [The Good Old Days]
Night Shift (5.25") [ibmpc5150, archive.org]
Night Shift (3.5") [ibmpc5150, archive.org]
Night Shift (3.5", alt) [moved from ibm5170 software list]
Paperboy (5.25") [ibmpc5150, archive.org]
Paperboy 2 (5.25") [ibmpc5150, archive.org]
Police Quest II - The Vengeance (5.25", v1.001.000) [ibmpc5150, archive.org]
Space Quest III - The Pirates of Pestulon (5.25") [The Good Old Days]
Space Quest III - The Pirates of Pestulon (3.5") [The Good Old Days]
Waterloo [ibmpc5150, …

ibm5150.xml: 17 added + 3 redumped + 4 renamed

---

src/mame/drivers/gsz80.cpp

[RFC2795 LTD](https://find-and-update.company-information.service.gov.uk/company/10159326/) - Company number 10159326
Spencer Owen owns the RC2014 trademark, and trades as RFC2795 LTD.

rc2014 - Added the correct company name for the RC2014 Kits.

---

hash/nes.xml
src/devices/bus/nes/bootleg.cpp
src/devices/bus/nes/henggedianzi.cpp
src/devices/bus/nes/henggedianzi.h
src/devices/bus/nes/nes_ines.hxx
src/devices/bus/nes/nes_slot.cpp
src/devices/bus/nes/nes_slot.h
src/devices/bus/nes/vrc_clones.cpp
src/devices/bus/nes/vrc_clones.h
src/devices/bus/nes/waixing.cpp
src/devices/bus/nes/waixing.h

Qīlóngzhū (China)
Sàiyǎrén Mièjué Jìhuà (China)
Sānguózhì III (China)
Sānguózhì (Asia, decrypted SmyNES)
Shénhuà Jiàn Yún III (China)

bus/nes: Improved support for some Waixing pirate Chinese translations.

---

hash/fmtowns_cd.xml

- Added missing floppy images to psydet3r and psydet5r [cyo.the.vile]
- Replaced the lotr2 floppy image with a proper one dumped from the original disk [cyo.the.vile]
AIV - A Ressha de Ikou 4 (1993-12-15 04:00:00) [redump.org, cyo.the.vile]
Emit Vol. 1 - Toki no Maigo (Version 1.30 Release 2.00, 1995-01-20) [redump.org, cyo.the.vile]
Master CD - Fresh Series-you (Ichitarou Model) [redump.org]
Microsoft Windows Version 3.1 L10 [redump.org, cyo.the.vile]
Software Contest Nyuusen Sakuhinshuu 1 (HMC-139A) [redump.org]
Taiken Shiyou! Marty Channel II [redump.org]
Terra Towns II [redump.org]
Towns Magazine Vol. 3 [redump.org]
Nihongo Linux + JE …

fmtowns_cd.xml: 10 new dumps, 2 replacements

---

hash/apple2_flop_clcracked.xml
hash/apple2_flop_orig.xml
hash/apple2gs_flop_orig.xml

Leaving this one open for review as there's a high probability I missed something in my current state. Sorry it took so long to get this done..

Apple softlist update for March 2022

---

src/mame/drivers/vsnes.cpp
src/mame/includes/vsnes.h
src/mame/machine/vsnes.cpp

- Unify some functions that are the same on both Main and Sub sides of board.
- Removed machine reset macro.

vsnes.cpp: A few more improvements.

---

src/mame/drivers/kaypro.cpp

Recent research by a user on [https://forum.vcfed.org/index.php?threads/kaypro-5.1236580/](url) led to the verification of the existence of the Kaypro 5. Info added.

kaypro.cpp: added information about the Kaypro 5

---

hash/famibox.xml
src/mame/drivers/nes.cpp

I forgot to add a credits list of those who provided dumps and/or info: [Fiskbit, ICEknigh7, j4m13c0, joey4, kmg, Marionova64, Patnukem, RetroGE, togemet2]

famibox.xml: Initial software list.

---

hash/neogeo.xml

NGM: Alternate title was not added.
NGH: Year should be 1998 not 1990.

neogeo.xml - lastblad: Correct year and add alt title

---

hash/nes.xml

Super Games 143 in 1 (HKMK-143) [Consolethinks]
Game 500 in 1 (alt) [Consolethinks]

nes.xml: Added a couple large dumps.

---

hash/ibm5150.xml

Added a working set of untouched MS-DOS (Version 3.2) disks.

Added MS-DOS (Version 3.2) (Alt.) [winworldpc]

---

src/devices/machine/laserdsc.cpp
src/devices/machine/laserdsc.h
src/mame/drivers/timetrv.cpp

-timetrv: Replaced IPT_COIN2 with IPT_BILL1, as it is the bill-validator input. [Ryan Holtz]

Fixed bill validator hookup in Time Traveler

---

hash/roland_tnsc1.xml
scripts/target/mame/mess.lua
src/mame/drivers/roland_tnsc1.cpp
src/mame/mame.lst
src/mame/mess.flt

roland_tnsc1.xml:
70's and 80's (TN-SC1-03) [Sean Riddle, ClawGrip]
We'll soon dump three more cards.

New NOT_WORKING software list additions 

---

src/mame/layout/timetrv.lay

-timetrv: Fixed layout to not warp screen to non-4:3 aspect. [Ryan Holtz]

Fixed timetrv artwork aspect ratio

---

src/devices/machine/ldv4200hle.cpp

-ldv4200hle: Fixed overshoot issue with Multi-Speed Forward/Reverse. [Ryan Holtz]

LDV-4200 HLE fixes for issues in Time Traveler

---

hash/sms.xml

Basket Ball Nightmare (early prototype) [smspower]
Golden Axe CES Demo [smspower]
Psycho Fox (prototype) [smspower]
Super Futebol II (Brazil) [smspower]
Wimbledon (Brazil) [smspower]
Game Mo-eumjip 188 Hap (Korea) [smspower]

sms.xml: Added six dumps.

---

hash/gamegear.xml

Poker Face Paul's Cribbage (prototype) [smspower]

gamegear.xml: Added an unreleased prototype.

---

hash/neogeo.xml
src/mame/drivers/neogeo.cpp
src/mame/mame.lst

Update of https://github.com/mamedev/mame/pull/9485.

matrim: Correct year as 2003

---

hash/nes.xml

- Removed underdumped Soap Panic set.

nes.xml: Replaced underdumped graphics ROM for Hanafuda Yuukyouden.

---

src/lib/formats/fsmeta.cpp
src/lib/formats/fsmeta.h
src/tools/floptool.cpp

No need to pass in the meta_type when using std::visit() on the std::variant

Changed fs::meta_value::to_string() to not be static and not require meta_type

---

hash/nes.xml
src/devices/bus/nes/multigame.cpp
src/devices/bus/nes/multigame.h

bus/nes: Minor cleanup of BMC_12IN1 board.

---

hash/nes.xml

King Gizzard & the Lizard Wizard - Polygondwanaland - 2nd Edition [anonymous]

nes.xml: Added a recent chiptune dump.

---

src/mame/drivers/slapfght.cpp

Revert "Fix MT08279 [sjy96525]"

---

hash/a800.xml

Popeye (prototype, 19830829) [Dutchman2000]
Popeye (prototype, WIP8) [Tempest]

a800.xml: Added two Popeye prototypes.

---

hash/nes.xml

1993 Super HiK 4 in 1 (F-034) [Consolethinks]
Assimilate [Nessylum]
L'Abbaye des Morts [Parisoft]
Little Lancelot (USA) [anonymous]
Metal Max (Japan, prototype) [Zoda-Y13, Forest of Illusion]
Pyramids of Ra (USA) [anonymous]
Toobin' (Korea) [MLX]

nes.xml: Added seven miscellaneous dumps.

---

src/lib/formats/fsmeta.cpp
src/lib/formats/fsmeta.h

Let's try to hide the nastiness of std::visit() as much as humanly possible

Added a 'type()' accessor to fs::meta_value

---

hash/nes.xml

Mike Tyson's Intergalactic Power Punch (USA, prototype) [HiddenPalace]

nes.xml: Added a new dump; fixed tysonpoh bad dump.

---

hash/nes.xml
src/devices/bus/nes/multigame.cpp
src/devices/bus/nes/multigame.h

76 in 1 Y2K [superretrogamer2741]
Super HiK 42 in 1 (K-42001) [Consolethinks]

bus/nes: Improved support for BMC-64IN1NR boards.

---

hash/famicom_flop.xml

Changed descriptive text in descriptions to lowercase.

famicom_flop.xml: Metadata corrections

---

hash/vboy.xml

Changed descriptive text in descriptions to lowercase.

vboy.xml: Metadata corrections

---

hash/pcecd.xml

Changed descriptive text in descriptions to lowercase

pcecd.xml: Metadata correction

---

src/devices/bus/nes/irem.cpp
src/devices/bus/nes/irem.h

- Fixed various minutiae with banking modes, bus conflicts, masks based on pin counts.
- Made H3001 a subclass of G101. It's mostly functionally the same with an added IRQ.

bus/nes: Updated Irem boards.

---

hash/nes.xml

AO [anonymous]
Beat'Em & Eat'Em [anonymous]
Dúshlán [anonymous]
NES Virus Cleaner [anonymous]
Solaris [anonymous]
Tic-Tac XO [anonymous]

nes.xml: Added six homebrew cartridges.

---

src/lib/formats/fs_coco_rsdos.cpp
src/lib/formats/fs_coco_rsdos.h

- Moved internal logic out of header file and into anonymous classes
- Commenting

Cleanups for the CoCo RS-DOS fs module

---

src/mame/drivers/ksys573.cpp

Remove unneeded undumped asterisk for Kick & Kick.

ksys573.cpp - Let’s kick some typo.

---

src/lib/formats/fs_coco_os9.cpp
src/lib/formats/fs_coco_os9.h

- Moved internal logic out of header file and into anonymous classes

Cleanups for the CoCo OS-9 fs module

---

hash/nes.xml

Chǒngwù Bǎobǎo (China) [famiac, NewRisingSun]
Dì Shì Tiān (China) [Consolethinks]
Jiànxiá Qíngyuán (China, Final Fantasy pirate) [famiac, NewRisingSun]
Qítiān Dàshèng (China) [famiac, NewRisingSun]
Wúmíng Chuánshuō (China) [Consolethinks]

nes.xml: Added some Chinese RPGs and a virtual pet game.

---

src/mame/drivers/spec128.cpp
src/mame/drivers/spectrum.cpp

restore border size

---

src/mame/drivers/gaelco.cpp

gaelco.cpp: Verify clocks

---

hash/apple2_flop_clcracked.xml
hash/apple2_flop_orig.xml

Drugs: Their Effects on You [Matthew Eric D'Asaro, Firehawke]
New working software list additions (apple2_flop_clcracked.xml)
Drugs: Their Effects on You (cleanly cracked) [4am, Matthew Eric D'Asaro, Firehawke]

The last April 2022 Apple II push

---

src/devices/cpu/mips/mips3drc.cpp

-mips3drc: Moved unchanging conditionals outside for loop in generate_checksum_block. [Ryan Holtz]

Refinement to MIPS3 EXTRA_INSTR_CHECK change; reduces perf loss on unaffected machines

---

src/mame/drivers/4enlinea.cpp
src/mame/mame.lst

4enlinea.cpp: Fix game name for 'unkdarts'

---

hash/gbcolor.xml

Tyrannosaurus Tex (USA) [NoIntro]

gbcolor.xml: Added one dump.

---

hash/gba.xml

gba.xml: Added one dump.

---

hash/nes.xml

Baby Boomer (Korea) [MLX]
Exploding Fist (USA) [anonymous]
Get'em Gary [anonymous]
More Glider [anonymous]
Multidude [RetroSouls]
Nomolos - Storming the Catsle (v1.00) [anonymous]
Quest Forge - By Order of Kings [anonymous]
Super Painter [RetroSouls]
Tújí (Taiwan) [kazblox]
Uninvited (USA, prototype) [Forest of Illusion, Clarkzer0]
Wùkōng Dòujù (China) [anonymous]

nes.xml: Added eleven dumps. Removed some baddump flags.

---

hash/megadriv.xml

Awesome Possum Kicks Dr. Machino's Butt! (USA, prototype, 19930712) [DrBizz]

megadriv.xml: Added an Awesome Possum prototype.

---

src/lib/netlist/FAQ.md
src/lib/netlist/devices/nld_9321.cpp
src/lib/netlist/plib/pfunction.cpp
src/lib/netlist/plib/ptokenizer.cpp
src/lib/netlist/solver/nld_matrix_solver.h
src/lib/netlist/solver/nld_ms_w.h
src/lib/netlist/solver/nld_solver.cpp

- Added a first version of a FAQ
- Use better error messages in pfunction.
- Add static where appropriate in nld_solver.

Netlist lint, first version of a FAQ and small code changes

---

src/mame/drivers/homedata.cpp

Just a note of adding the subtitle to Reikai Doushi.

homedata.cpp - Add subtitle to reikaids

---

hash/pc98_cd.xml

Brandish 2 Renewal [redump.org]
Canaan - Yakusoku no Chi [redump.org]
Doom II for Windows 95 [redump.org]
Ningen Konchuu - Nozoki [redump.org]
Shin'ou Densetsu Crystania DX [redump.org]
Uki Uki Island [redump.org]
X Girl [redump.org, cyo.the.vile]
Ayumi-chan Monogatari [redump.org]
Collector D [redump.org, cyo.the.vile]
Etemible - Tenjou Mukyuu [redump.org, Coolmod]
Ginga Eiyuu Densetsu IV [redump.org]
Master of Magic [redump.org]
NEC Demonstration CD-ROM - Evolution and Dinosaurs [redump.org]
Prince of Persia 2 - The Shadow & The Flame [redump.org]
Sorcer Kingdom [redump.org]
Strike Commander [redump.org]
Teitoku no Ketsudan III …

pc98_cd.xml: 19 new dumps, 18 replacements

---

src/mame/machine/midwayic.cpp

Update midwayic to logmacro for logerror messages.

midwayic.cpp: Use logmacro for debug

---

hash/c64_cass.xml

Salamander (Imagine) [C64 Ultimate Tape Archive V2.0]
Sanxion (Thalamus) [C64 Ultimate Tape Archive V2.0]
Savage (Firebird) [C64 Ultimate Tape Archive V2.0]
Scorpion (Prism Leisure) [C64 Ultimate Tape Archive V2.0]
The Secret Diary of Adrian Mole (Mosaic Publishing) [C64 Ultimate Tape Archive V2.0]
Sentinel (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
The Sentinel (Firebird) [C64 Ultimate Tape Archive V2.0]
Shadow Skimmer (The Edge) [C64 Ultimate Tape Archive V2.0]
Scooby-Doo (Elite Systems) [C64 Ultimate Tape Archive V2.0]
Shadows of Mordor (Melbourne House) [C64 Ultimate Tape Archive V2.0]

c64_cass.xml: Added 10 items (8 working, 2 not working)

---

src/mame/drivers/8080bw.cpp
src/mame/includes/8080bw.h
src/mame/video/8080bw.cpp

I was sent this code. The colors seem strange to me, but the blurry, low resolution pics seem to confirm them. Opening a PR since I'm not confident enough to commit directly without comments / verification.

8080bw.cpp: added colors emulation to vortex [Mike Coates]

---

hash/gameboy.xml

Dangan GB [snorpung, nordloef]
Death Planet [Mackerel Interactive]
Into the Blue [Jonas Fischbach]
Retroid [Jonas Fischbach]

gameboy.xml: Added four homebrew entries.

---

src/lib/netlist/build/makefile
src/lib/netlist/core/base_objects.h
src/lib/netlist/plib/gmres.h
src/lib/netlist/plib/pconfig.h
src/lib/netlist/plib/pmath.h
src/lib/netlist/plib/pmatrix_cr.h
src/lib/netlist/plib/prandom.h
src/lib/netlist/plib/psource.h
src/lib/netlist/plib/pstream.h
src/lib/netlist/plib/pstring.cpp
src/lib/netlist/prg/nlwav.cpp
src/lib/netlist/solver/nld_matrix_solver_ext.h
src/lib/netlist/solver/nld_ms_gmres.h

nvcc 11.3 (latest cuda tools) has an issue with some auto x(some
variable) declariations. This commit fixes the compile errors.

netlist: Fix standalone nltool building with nvcc.

---

src/mame/drivers/vigilant.cpp

Deletes in-line credits, to keep with MAME general style. Advised by hap

---

src/devices/imagedev/bitbngr.cpp
src/devices/imagedev/bitbngr.h
src/osd/modules/file/posixfile.cpp
src/osd/modules/file/posixfile.h
src/osd/modules/file/posixsocket.cpp
src/osd/modules/file/winfile.cpp
src/osd/modules/file/winfile.h
src/osd/modules/file/winsocket.cpp
src/osd/osdfile.h

Example bitbanger usage: -bitb udp.234.99.99.99:15122

Add udp multicast support

---

src/devices/imagedev/bitbngr.cpp
src/devices/imagedev/bitbngr.h
src/osd/modules/file/posixfile.cpp
src/osd/modules/file/posixfile.h
src/osd/modules/file/posixsocket.cpp
src/osd/modules/file/winfile.cpp
src/osd/modules/file/winfile.h
src/osd/modules/file/winsocket.cpp
src/osd/osdfile.h

Revert "Add udp multicast support"

---

hash/dc.xml

Renaming Prototype, Alt, Rev, Demo words to lowercase

dc.xml: Metadata cleaning

---

hash/cdi.xml

The Photo CD Book Companion CD-ROM [Dave 'Foxhack' Silva]

cdi.xml: Added one new entry

---

3rdparty/portmidi/pm_win/pmwinmm.c

portmidi: fix windows midi callback signatures

---

src/mame/drivers/spdheat.cpp

Driver says about sound filters and multiple speakers, both of which aren't emulated.

spdheat.cpp: Demote to MACHINE_IMPERFECT_SOUND

---

hash/gamegear.xml

gamegear.xml: Made brkthru playable.

---

hash/fmtowns_cd.xml

'94-nen Nice Gal - Natsu no Soukessan [redump.org]
Ii Tabi Ii Aji Goannai - Furusato Kodzutsumi & Kanpo no Yado - Heisei Gannendo-ban [redump.org]
Pocky 1-2 + Ponyon [redump.org]
Psychic Detective Series Vol. 4 - Orgel (Demo) [redump.org]
Psychic Detective Series Final - Solitude Gekan (Demo) [redump.org]
The Playroom [redump.org]
Zak McKracken and The Alien Mindbenders (HMB-218) [redump.org]

fmtowns_cd.xml: 7 new dumps

---

hash/megadriv.xml

Canon - The Legend of the New Gods [NoIntro]
Clan of Heroes - Generals of the Yang Family [NoIntro]
Custodian [NoIntro]
Duke Nukem 3D (Piko reissue) [NoIntro]
Mega Noah's Ark 3D [NoIntro]
Switchblade [NoIntro]
Water Margin - A Tale of Clouds and Wind [NoIntro]
Wisdom Tree Collection [NoIntro]

megadriv.xml: Added eight dumps.

---

hash/snes.xml

Kidou Soukou Dion (Japan, prototype) [Zoda-Y13, Forest of Illusion]
Pocky & Rocky (USA, prototype) [Squiddy, Forest of Illusion]
Puggsy (prototype) [TCRF]
Radical Rex (USA, prototype 19940318) [Squiddy, Forest of Illusion]
Seifuku Densetsu Pretty Fighter (Japan, prototype) [Squiddy, Forest of Illusion]
Snoopy Concert (Japan, prototype) [Squiddy, Forest of Illusion]

snes.xml: Added six prototypes.

---

hash/pce_tourvision.xml

pce_tourvision.xml: Add known undumped game to list notes

---

src/osd/modules/render/bgfx/chainmanager.cpp
src/osd/modules/render/drawbgfx.cpp

See discussion on #9632 – this is mainly visible as slot machine reels not working properly.

bgfx: Honour texture wrap flag

---

hash/specpls3_flop.xml

Added one compilation and one game:
-Made in Spain 5 Estrellas [Fede Jerez]
-Simulador Profesional de Tenis [Fede Jerez]

[specpls3_flop.xml] 2 new working entries

---

src/mame/drivers/segae.cpp
src/mame/mame.lst

-------
Megumi Rescue [Jeff Willard Jr]

new WORKING machines (Megumi Rescue)

---

hash/cdi.xml

chdman changed since the chd hashes were taken. This is an update for about 200 disk hashes.
See issue #2517

Updated cdi.xml hashes for TOSEC disks

---

hash/jaguar.xml

Lower case on description's word like: Prototype, Alt, Re-release, Hacked

jaguar.xml: Metadata cleaning

---

hash/a2600.xml

Lower case on description's word like: Unknown, Alt, Prototype, Older

a2600.xml: Metadata cleaning

---

hash/saturn.xml

Renaming Prototype, Alt, Rev, Demo words to lowercase

saturn.xml: Metadata cleaning

---

hash/lynx.xml

Robotron: 2084 (prototype) [swlovinist]

lynx.xml: Added a prototype.

---

src/mame/drivers/y2.cpp

That's seems like copy-paste error.

y2.cpp: Fix dependency

---

src/mame/drivers/namcos12.cpp

namcos12.cpp: Add note

---

hash/pc8801_cass.xml

3156 Coro Coro [Gaming Alexandria]

pc8801_cass.xml: New software list addition

---

src/mame/arcade.flt

Added missing segafruit.cpp to Arcade build filter.

Fixed Arcade build

---

hash/psx.xml

Lowercase on description's words like: Prototype, Demo, Tech Demo, etc...

psx.xml: Metadata cleaning

---

hash/megadriv.xml

Lowercase on some description's word, like: Alt, Cracked, Incomplete Dump, Hacked, Pirate, Prototype, Unprotected, etc...

megadriv.xml: Metadata cleaning

---

src/mame/drivers/jp.cpp

Dumped and added a new set of 'Halley Comet'. Also added some comments about the differences between the two 'Aqualand' sets.
Halley Comet (set 3) [Sergio y Vicente de www.electronicavys.es]

jp.cpp: Dumped and added a new set of 'Halley Comet'

---

src/mame/drivers/pluto5.cpp

Also added some links to the official Heber Pluto 5 webpages, with some more info for developers

pluto5.cpp: Add notes about the Pluto 5 hardware

---

hash/gameboy.xml

Alfred Chicken (prototype) [VGHF, Hidden Palace]
Jimmy Connors Tennis (prototype) [VGHF, Hidden Palace]
Klustar (prototype) [VGHF, Hidden Palace]
Lethal Weapon (prototype) [VGHF, Hidden Palace]
Loopz (prototype) [VGHF, Hidden Palace]
Metal Masters (prototype) [VGHF, Hidden Palace]
Mickey's Ultimate Challenge (prototype, 19931112) [VGHF, Hidden Palace]
Mighty Morphin Power Rangers (prototype) [VGHF, Hidden Palace]
Mind-Bender (Brain-Bender prototype, 19910304) [VGHF, Hidden Palace]
Monster Max (prototype, 19930401) [VGHF, Hidden Palace]
Ninja Taro (USA, prototype, earlier?) [VGHF, Hidden Palace]
Otto's Ottifanten - Baby Bruno's Nightmare (prototype) [VGHF, Hidden Palace]
Pinball - Revenge of the 'Gator (prototype) …

gameboy.xml: Added 25 prototypes.

---

hash/ibm5170.xml

Battle Chess (Windows 3.x release) [minimojoman, archive.org]
King's Quest VI: Heir Today, Gone Tomorrow (3.5") [The Good Old Days]
King's Quest VI: Heir Today, Gone Tomorrow (3.5", Germany) [The Good Old Days]
King's Quest VI: Heir Today, Gone Tomorrow (5.25") [The Good Old Days]
Litil Divil [The Good Old Days]
Roberta Williams' Laura Bow in "The Dagger of Amon Ra (Germany) [The Good Old Days]

ibm5170.xml: 6 new software additions

---

src/mame/drivers/spec128.cpp
src/mame/drivers/spectrum.cpp
src/mame/includes/spectrum.h
src/mame/video/spectrum.cpp

Workaround for partial update issue at the end of frame.
https://mametesters.org/view.php?id=8264
https://mametesters.org/view.php?id=8265
https://github.com/mamedev/mame/pull/9670#issuecomment-1118576555
https://github.com/mamedev/mame/pull/9750

spectrum: fix partial updates at the end of frame

---

hash/apple2_flop_clcracked.xml
hash/apple2_flop_orig.xml

This includes some metadata/title changes as well as some new materials. I'll do the merge on Friday, giving me a bit more time for any last minute changes/additions.

Apple softlist update for June 2022.

---

hash/a2600_cass.xml

Lowercase on description's words like: Alt, Preview, Prototype

a2600_cass.xml: Metadata cleaning

---

src/osd/sdl/sdlmain.cpp

This should fix issue #9852, pending @substring's confirmation.

Throw a fatal error if combination of bgfx video and wayland videodriver has been detected

---

src/mame/drivers/m79amb.cpp

The generated LUTs for the guns are unchanged. This just does it a bit better by not scanning `lut_cross` repeatedly.

m79amb.cpp: Improved input lookup table generation; added DIP locations.

---

src/mame/audio/nl_jpmsru.cpp
src/mame/drivers/jpmsru.cpp
src/mame/layout/j_cnudgr.lay
src/mame/layout/j_ewsbl.lay
src/mame/mame.lst

- Added 3 new sets
- Fixed audio by setting a precise value for the tone pot, also removed unnecessary amplifier section resistor
- Added impulses to coin inputs to stop j_ewnd giving credits every frame
- Turned the audio level down a bit

jpmsru.cpp: Added new sets, fixed audio

---

src/devices/machine/k056230.cpp
src/devices/machine/k056230.h
src/mame/drivers/gticlub.cpp
src/mame/drivers/plygonet.cpp
src/mame/drivers/zr107.cpp

-plygonet: More PSAC2 fixes, some K056230 fixes [Ryan Holtz, Phil Bennett, Hydreigon]

plygonet: Polygonet Warriors goes in-game, plus some screen-size fixes

---

src/mame/drivers/plygonet.cpp

Apologies for the PR spam, having to PR against the release branch is super awkward.

More plygonet fixes

---

src/mame/drivers/elwro800.cpp
src/mame/drivers/spec128.cpp

Includes:
https://github.com/mamedev/mame/pull/9998
https://github.com/mamedev/mame/pull/9997

spectrum-clones: bugfix 0245 regressions

---

src/devices/video/fixfreq.cpp
src/mame/atari/atarittl.cpp
src/mame/atari/nl_gtrak10.cpp

Please ensure that gtrak10.cfg is deleted - may override defaults.

Fixed gtrak10 video.

---

src/mame/subsino/subsino2.cpp

Note that I have been unable to verify the inputs on the queenbee clones as only the program ROMs are available presently.

subsino2.cpp: Identified several inputs for queenbee (MT08365)

---

src/mame/mame.lst
src/mame/seta/seta.cpp

Thunder & Lightning (set 2) [Sergio Galiano, Recreativos Piscis]

seta/seta.cpp: Added alternate version of Thunder & Lightning

---

hash/neogeo.xml

Fixed mismatch between serial given in description and info. 024 is lresort serial.

neogeo.xml: Fix eightman serial

---

hash/nes.xml

Déjà Vu (USA, prototype, 19900428) [Forest of Illusion]
Déjà Vu (USA, prototype, 19900508) [Forest of Illusion]
Déjà Vu (USA, prototype, 19900515) [Forest of Illusion]
Déjà Vu (USA, prototype, 19900703) [Forest of Illusion]
Heavy Shreddin' (USA, prototype) [johnsodu]
Shadowgate (Japan, prototype) [Forest of Illusion]
Uninvited (USA, prototype, 19900704) [Forest of Illusion]
Uninvited (USA, prototype, 19900823) [Forest of Illusion]
Uninvited (USA, prototype, 19900910) [Forest of Illusion]

nes.xml: Added nine prototypes.

---

hash/gameboy.xml

Aladdin (Europe, sample) [thevideogameproject]
Dennis (Europe, prototype) [ashthedragon]
Disney's Darkwing Duck (prototype) [FNeogeo, Forest of Illusion]
Dr. Franken (Europe, prototype) [Aetius For Real]
Eddie's Puzzle Time (prototype) [Jason McGann]
Felix the Cat (prototype) [DillyDylan, drx]
Hook (USA, prototype) [FNeogeo, Forest of Illusion]
Joe & Mac - Caveman Ninja (Europe, prototype) [ashthedragon]
Lemmings (prototype) [speedyink]
Mega Man III (USA, sample) [Skaarg, Rockman Corner]
Mortal Kombat (prototype) [ashthedragon]
R-Type II (prototype) [The Retro Future]
Tintin in Tibet (Europe, En / Es / It / Sv, prototype) [Aetius For Real] …

gameboy.xml: Added 14 prototypes.

---

src/mame/sinclair/spectrum_v.cpp

https://mametesters.org/view.php?id=8370

spectrum-v.cpp: avoid screen update before video initialized - MT8370

---

hash/megadriv.xml

Road Riot 4WD (prototype, 19930719) [DrBizz]
Steel Talons (USA, prototype, 199206xx) [DrBizz]

megadriv.xml: Added two prototypes.

---

hash/a7800.xml
hash/a800_flop.xml
hash/einstein.xml
hash/gameboy.xml
hash/gba.xml
hash/gbcolor.xml
hash/intv.hsi
hash/lisa.xml
hash/msx1_cart.xml
hash/msx1_flop.xml
hash/nes.hsi
hash/nes.xml
hash/pc8001_flop.xml
hash/pc8801_flop.xml
hash/pc88va.xml
hash/pc98.xml
hash/pce.xml
hash/pcecd.xml
hash/psx.xml
hash/saturn.xml
hash/snes.xml
hash/wswan.xml
hash/x1_flop.xml
hash/x68k_flop.xml

- Removed mention of MESS.
- Corrected case (and more) in various Japanese titles.

Miscellaneous software list cleanups.

---

hash/intv.xml

Map Mazes (unreleased) [Chuck Gill]
Shapes in Space (unreleased) [Chuck Gill]

intv.xml: Added two Tutor Vision dumps.

---

hash/ekara_japan.xml
hash/ekara_japan_d.xml
hash/ekara_japan_en.xml
hash/ekara_japan_g.xml
hash/ekara_japan_m.xml
hash/ekara_japan_p.xml
hash/ekara_japan_s.xml
src/mame/tvgames/xavix_a.cpp

new Software List entries
ekara_japan_m:mc0005  Kids Song Mini Volume 1 (Japan) (MC0005-KSM) [Team Europe]
ekara_japan_m:mc0007  Artist Mini Volume 5 (SMAP, KinKi Kids) (Japan) (MC0007-ATM) [Team Europe]
ekara_japan_s:sc0015  Detective Conan Volume 2 (Japan) (SC0015-DCS) [Team Europe]
ekara_japan_s:sc0007  Detective Conan Volume 1 (Japan) (SC0007-DCS) [Team Europe]
ekara_japan_g:gc0018  TV Pop Volume 7 (Japan) (GC0018-TPJ) [Team Europe]
ekara_japan_g:gc0011  TV Pop Volume 4 (Japan) (GC0011-TPJ) [Team Europe]

new Software List entries (6x eKara / Popira / Popira 2 carts) [Team Europe]

---

src/mame/mame.lst
src/mame/midway/midzeus.cpp

The Grid (version 1.01) [Museo del Recreativo]

midzeus.cpp: Dumped and added The Grid V1.01

---

hash/uzebox.xml

Lower case on "Alt" word in the set description

uzebox.xml: Metadata Cleaning

---

hash/a7800.xml

Food Fight (NTSC, prototype) [gambler172, Eckhard Stolberg]
Xevious (NTSC, prototype) [gambler172, Eckhard Stolberg]
7800 Pro System Diagnostic Test (prototype) [gambler172, Eckhard Stolberg]
Pole Position II (prototype) [gambler172, Eckhard Stolberg]

a7800.xml: Added four prototypes.

---

hash/apple2gs_flop_orig.xml

* New working software list additions (apple2gs_flop_orig.xml)
--------------------------------------------------------------
Dragon's Lair [Antoine Vignau, A-Noid]
Dragon's Lair: Escape from Singe's Castle [Antoine Vignau, A-Noid]
Dragon's Lair II: Time Warp [Antoine Vignau, A-Noid]

apple2gs_flop_orig.xml: Added 3 Games

---

hash/gameboy.xml
hash/megadriv.xml
hash/pc98.xml
hash/snes.xml

- Replaced incorrect dakuten/double prime quote pairing with proper CJK double quotes.
- Replaced full-width combining dakuten/handakuten with non-combining equivalents.

Cleaned up some software list kana issues.

---

src/mame/capcom/lwings.cpp

Added info about the undumped Avengers protection chip.

Added info on the Avengers protection chip

---

hash/famibox.xml

Punch-Out!! [Lina, Forest of Illusion]

famibox.xml: Added a missing dump; replaced 1943's bad dump.

---

hash/c64_cass.xml

They Sold a Million (The Hit Squad) [C64 Ultimate Tape Archive V2.0]
They Sold a Million 3 (The Hit Squad) [C64 Ultimate Tape Archive V2.0]
Thing Bounces Back (Gremlin Graphics) [C64 Ultimate Tape Archive V2.0]
Thing on a Spring (Gremlin Graphics) [C64 Ultimate Tape Archive V2.0]
Thrill Time Gold 1 (Elite Systems) [C64 Ultimate Tape Archive V2.0]
Thunder Blade (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Thundercats (Elite Systems) [C64 Ultimate Tape Archive V2.0]
Tiger Mission (Status Software) [C64 Ultimate Tape Archive V2.0]
Tilt (Codemasters) [C64 Ultimate Tape Archive V2.0]
They Stole a Million (39 Steps) [C64 Ultimate Tape …

c64_cass.xml: Added 10 items (9 working, 1 not working)

---

src/mame/gaelco/gaelco3d.cpp
src/mame/mame.lst

Football Power (Version 1.1) [Victor Fernandez (City Game), Arcade Planet]

gaelco3d.cpp: Dumped and added Football Power v1.1

---

src/devices/machine/6840ptm.cpp
src/devices/machine/6840ptm.h

-6840ptm: Fixed counter duration and fixed output behavior in single-shot and dual-8-bit modes. [Ryan Holtz]

6840PTM: Fix regressions, counter duration, and single-shot/dual-8-bit behavior

---

hash/ibm5170.xml

Alone in the Dark 2 - Secret Doors (USA) [dosnostalgic, archive.org]
Genesia (v1.41) [The Good Old Days]
Genesia (v1.4) [MarkHnsn, archive.org]

ibm5170.xml: 3 new software additions

---

hash/a2600.xml

- Corrected some bad parent/clone relationships.

a2600.xml: Set default controllers for games that don't use joysticks.

---

hash/a2600.xml
src/devices/bus/vcs/compumat.cpp
src/devices/bus/vcs/compumat.h
src/devices/bus/vcs/dpc.cpp
src/devices/bus/vcs/dpc.h
src/devices/bus/vcs/harmony_melody.cpp
src/devices/bus/vcs/harmony_melody.h
src/devices/bus/vcs/rom.cpp
src/devices/bus/vcs/rom.h
src/devices/bus/vcs/scharger.cpp
src/devices/bus/vcs/scharger.h
src/devices/bus/vcs/vcs_slot.cpp
src/devices/bus/vcs/vcs_slot.h
src/mame/atari/a2600.cpp
src/mame/atari/a2600.h
src/mame/atari/tvboy.cpp

a2600.xml: Fix description for challenge and add usage note.

atari/a2600.cpp: Remove device lookups.

---

hash/mo5_cart.xml

Lower case on "Alt" word in the set description.

mo5_cart: Metadata cleaning

---

hash/a2600.xml

Astro Chase (prototype) [Tempest]
Centipede (prototype) [Dutchman2000]
Defender (prototype 198111xx) [Rom Hunter]
Elf Adventure (prototype 19830502) [Tempest]
Elf Adventure (prototype 19830422) [Tempest]
Frankenstein's Monster (prototype) [swlovinist]
Gorf (prototype) [Rom Hunter]
Joust (prototype 19830705) [Rom Hunter]
Kangaroo (prototype 19830119) [Tempest]
Missile Command (prototype) [Rom Hunter]
Monkey Music (prototype 19820818) [Tempest]
Mr. Do!'s Castle (later prototype) [Tempest]
Mr. Do!'s Castle (prototype 19840312) [Tempest]
Popeye (prototype) [Tempest]
Raiders of the Lost Ark (prototype 19820614) [Rom Hunter]
Solar Fox (prototype) [Dutchman2000]
Solaris (prototype) [Tempest]
Venture (prototype) [Rom Hunter] …

a2600.xml: Added 20 prototypes.

---

hash/lynx.xml

Yastuna Vol.1 - The Alchemy of Cubes [kmg]
Yastuna Vol.2 - The Space Incident [kmg]

lynx.xml: Trimmed 64-byte header from Yastuna homebrews.

---

hash/casloopy.xml
hash/coco_cart.xml
hash/x1_flop.xml

x1_flop.xml: Fixed a kanji reading.

casloopy.xml: Fixed a ROM size and kanji reading.

---

hash/snes.xml

Boxing Legends of the Ring (USA, prototype) [Forest of Illusion]
Hammer Lock Wrestling (USA, prototype) [Forest of Illusion]
Porky Pig's Haunted Holiday (USA, prototype 19950807) [iniche, Forest of Illusion]
Super Punch-Out!! (Euro, prototype) [Zoda-Y13, Forest of Illusion]
We're Back! - A Dinosaur's Story (USA, prototype) [Forest of Illusion]

snes.xml: Added five prototypes.

---

hash/gbcolor.xml

Chāorén Tègōngduì (Taiwan) [taizou]
Fēngkuáng Āgěi Ⅲ - Chāojí Zhàdànrén (Taiwan) [taizou]
Wángzú Tiāntáng (Taiwan) [taizou]
Xiándàn Chāorén - Ultraman (Taiwan) [taizou]

gbcolor.xml: Added four Taiwanese dumps.

---

hash/nes.xml

Fighting Simulator - World Champ (USA, prototype) [rjtiger]

nes.xml: Added a prototype.

---

hash/to7_cass.xml

- Lower case on "Alt", "Split", "Tape", "Password Required", "Source Code", "Unknown", "No Loader Screen" words in the set description.
- Replaced the "Ger" abbreviation by the "Germany" country name.

to7_cass.xml: Metadata Cleaning

---

hash/to7_cart.xml

- Lower case on "Alt" word in the set description.
- Replaced the "Ger" abbreviation by the "Germany" country name.

to7_cart.xml: Metadata Cleaning

---

hash/to7_qd.xml

Lower case on "Alt" and "Bad" words in the set description.

to7_qd.xml: Metadata Cleaning

---

hash/vboy.xml

- Added alt_title and developer info tags.
- Data sizes changed to hexadecimal.
- Various cleanups.
Hyper Fighting (pirate) [Planet Virtual Boy]

vboy.xml: Added a homebrew pirate release.

---

hash/cdi.xml

Lower case on "Alt" and "Demo" words in the set description.
Replaced the countries' abbreviation by the full name

cdi.xml: Metadata cleaning

---

hash/megadriv.xml

Primal Rage (prototype) [Rezrospect, Forest of Illusion]

megadriv.xml: Added a prototype.

---

hash/snes.xml

- Lower case on "Cracked", "Bad Dump", "Sample" words in the set description.
- Replaced the countries' abbreviations by their full name

snes.xml: Metadata Cleaning

---

docs/source/initialsetup/compilingmame.rst

Update emscripten compile instructions to reflect recent source rearrangement

docs: Fix emscripten compile instructions

---

hash/tsconf_betadisc_flop.xml
src/mame/sinclair/tsconf.cpp
src/mame/sinclair/tsconf.h
src/mame/sinclair/tsconf_m.cpp

tsconf.cpp: start software list

---

hash/fmtowns_cd.xml

- Added the bundled Sample Data Disk to kidpixjr [cyo.the.vile]
- Replaced the habitat1110 floppy image with a good dump [cyo.the.vile]
- Some minor metadata corrections
DAPS for Windows [redump.org]
DynEd Demo Disc [redump.org]
FM Towns II Demonstration CD-ROM '94 Spring [redump.org]
FM Towns II Demonstration CD-ROM '94 Summer [redump.org]
Gakuen Bomber [redump.org]
Hyper Planet (demo) [redump.org]
LiveAnimation V1.1 L10 [redump.org]
Manami - Ai to Koukan no Hibi [redump.org, cyo.the.vile]
Maruanki Eitango - Chuugaku 1-nensei [redump.org]
Mirumiru Sagasu Konchuu Series Vol. 1 - Chiisana Ensouka [redump.org]
Mirumiru Sagasu Konchuu Series Vol. 2 - Mori no Ninkimono - Jueki ni Atsumaru Mushi-tachi [redump.org]
Muscle …

fmtowns_cd.xml: 24 new dumps, 3 replacements

---

src/mame/nintendo/vsnes.cpp

- Added watchdog timer (currently only active on DualSystem games).
- Set perfect quantum for vsmahjng, just like all the other DualSystem games.
- Switched vssoccera from bnglngby's init, which installs a fake IRQ hack, to standard init.
- Switched suprmriobl to empty_init and gave it more consistent function naming.

nintendo/vsnes.cpp: A few minor changes.

---

src/mame/sinclair/pentagon.cpp

pentagon.cpp: cleanup driver detection

---

plugins/hiscore/hiscore.dat
src/mame/mame.lst
src/mame/pacman/pacman.cpp
src/mame/pacman/pacman.h

This adds support for the Miss Packman Plus roms that have the alternate mazes.

pacman.cpp: Added Miss Packman Plus.

---

hash/a800_flop.xml
hash/snes.xml
src/devices/bus/snes/rom.cpp
src/mame/nintendo/snes.cpp

Hercules (pirate) [Revenant]
Hercules (pirate, hacked) [Revenant]
The King of Fighters '98 (pirate, hacked) [Revenant]
Marvel Super Heroes Vs. Street Fighter (pirate, hacked) [Revenant]
Squirrel [Revenant]
Squirrel (pirate, hacked) [Revenant]
The King of Fighters '98 (pirate) [ALMCLE]
Marvel Super Heroes Vs. Street Fighter (pirate) [ALMCLE]

snes.xml: Added eight dumps (four pirate dumps, four cracked versions).

---

src/mame/sinclair/atm.cpp
src/mame/sinclair/glukrs.cpp
src/mame/sinclair/glukrs.h
src/mame/sinclair/tsconf.cpp
src/mame/sinclair/tsconf.h
src/mame/sinclair/tsconf_m.cpp

* atm.cpp: add CMOS
* glukrs.cpp: refactoring

atm.cpp: add CMOS

---

hash/ibm5170.xml

Classics Arcade [ibmpc5150, archive.org]
GrandMaster Chess [The Good Old Days]
GrandMaster Chess Deluxe [The Good Old Days]
Nomad [MarkHnsn, archive.org]
PC Format (Issue 24 - September 1993) [MarkHnsn, archive.org]
PC Format (Issue 26 - November 1993) [MarkHnsn, archive.org]
PC Format (Issue 35 - August 1994) [StefanNL, archive.org]
PC Format (Issue 48 - September 1995) [MarkHnsn, archive.org]
PC Gamer (UK) (Vol. 01 Nº 01 - December 1993) [MarkHnsn, archive.org]
PC Gamer (UK) (Vol. 01 Nº 03 - February 1994) [MarkHnsn, archive.org]
PC Gamer (UK) (Vol. 01 Nº 04 - March 1994) [MarkHnsn, archive.org]
PC Gamer (UK) (Vol. 01 Nº 05 - April 1994) [MarkHnsn, archive.org]
PC Gamer (UK) (Vol. 01 Nº 07 - June 1994) [MarkHnsn, …

ibm5170.xml: 22 new software additions

---

hash/apple2gs_flop_orig.xml

New working software list additions (apple2gs_flop_orig.xml)
------------------------------------------------------------
Space Ace (Brutal Deluxe) [Antoine Vignau, A-Noid]

New working software list additions (apple2gs_flop_orig.xml)

---

src/mame/sinclair/atm.cpp

sinclair/atm.cpp: Fixed I/O addressing, and disabled RAM writes when ROM is active

---

hash/a7800.xml

- Lowercase on descriptive text like "Prototype", "alternate", "Hack", "Older", "Demo"
- Uppercase on descriptive text "Pokey"

a7800.xml: Metadata cleaning

---

hash/intv.xml

Lowercase on descriptive text on words like "Prototype", "Alt", "Unreleased", "Unfinished", "Fixed", "Download Version", "Hacked"

intv.xml: Metadata cleaning

---

hash/nes.xml

NARC (USA, CES sample, prototype) [Hard4Games, Dustin Echoes, Forest of Illusion]
Controller Test Program (Japan) [Forest of Illusion]

nes.xml: Added two dumps.

---

src/mame/layout/spbactnp.lay
src/mame/tecmo/spbactn.cpp

Super Pinball Action (US, prototype, dual screen) [David Haywood]

Super Pinball Action protoype - add emulation of 2nd screen

---

hash/snes.xml

Kid Klown in Crazy Chase (Euro, prototype)</description> [Zoda-Y13, Forest of Illusion]
WeaponLord (USA, prototype) [DrBizz]

snes.xml: Added two recent prototype dumps.

---

src/lib/formats/fs_oric_jasmin.cpp
src/tools/floptool.cpp

Declare as unused some return variables

Fixed some compiler errors

---

hash/lynx.xml

Lowercase on the descriptive "Demo" word

lynx.xml: Metadata cleaning

---

hash/ibm5170.xml

PC Magazine (All Star - December 1992) [arranarchipelago, archive.org]
PC Plus (Issue 69 - June 1992) [arranarchipelago, archive.org]
PC Today (Vol. 06 № 08 - December 1992) [arranarchipelago, archive.org]
Personal Computer World (1994-04 - April 1994) [SmartCoda, archive.org]
Space Quest IV: Roger Wilco and the Time Rippers (Germany) [The Good Old Days]
Tetris Trio [The Good Old Days]
The Lost Files of Sherlock Holmes [The Good Old Days]
Redump
Disney's Aladdin [Abandon Socios]

ibm5170.xml: 7 new software additions + 1 Redump

---

hash/intellect02.xml

Lowercase on the software list description (Cartridges)

intellect02.xml: Rename software list description

---

hash/apple2_flop_clcracked.xml
hash/apple2_flop_orig.xml
hash/apple2gs_flop_orig.xml

Microzine 1 [4am, Firehawke]
Microzine 2 [4am, Firehawke]
Microzine 3 [4am, Firehawke]
Microzine 4 [4am, Firehawke]
Microzine 5 [4am, Firehawke]
Microzine 6 [4am, Firehawke]
Microzine 7 [4am, Firehawke]
Microzine 8 [4am, Firehawke]
Microzine 9 [4am, Firehawke]
Microzine 10 [4am, Firehawke]
Microzine 11 [4am, Firehawke]
Microzine 12 [4am, Firehawke]
Microzine 13 [4am, Firehawke]
Microzine 14 [4am, Firehawke]
Microzine 15 [4am, Firehawke]
Microzine 16 [4am, Firehawke]
Microzine 17 [4am, Firehawke]
Microzine 18 [4am, Firehawke]
Microzine 19 [4am, Firehawke]
Microzine 20 [4am, Firehawke]
Microzine 21 [4am, Firehawke]
Microzine 22 [4am, Firehawke]
Microzine 23 [4am, Firehawke] …

New Apple II disks for August 2022

---

hash/adam_cass.xml

Lowercase on some descriptive words like "Alt", "Prototype", "Demo"

adam_cass.xml: Metadata cleaning

---

hash/adam_cart.xml

Lowercase on some descriptive words like "Alt" and "Prototype"

adam_cart.xml: Metadata cleaning

---

hash/adam_flop.xml

Lowercase on some descriptive words like "Alt", "Prototype", "Demo", "Hacked", "Patched", "Disk", "Unknown"

adam_flop.xml: Metadata cleaning

---

src/mame/swtpc/swtpc09.cpp

Retested all of these and they are still working. Did not have a UniFLEX DMAF2
disk to test that one combination, but it should be close to working.
Added comments to help people make a start with these.

swtpc09: restore to working status, and add comments to help

---

src/mame/mame.lst
src/mame/misc/highvdeo.cpp

------------
Zoomania (Version 10.04, set 1) [Cristiano MDQ]
Zoomania (Version 10.04, set 2) [Cristiano MDQ]
Sala Due (Version 3.04) [Cristiano MDQ]
Paradise (Industrias Brasilerias, Version 1.04) [Cristiano MDQ]
technically these might be working, but I haven't spent time verifying the inputs etc. are correct.
I've also cleaned up the driver a little, it was using static variables in functions before
Also made some of the other sets in here that didn't boot, boot, and set some to the correct machine type so the video renders as it should, some still need work on inputs etc.

new NOT WORKING machines (Brazilian gambling games)

---

hash/nes.xml

Wily &amp; Light no RockBoard - That's Paradise (Japan, sample) [Zoda-Y13, Forest of Illusion]

nes.xml: Added a sample cartridge dump.

---

scripts/src/bus.lua
src/devices/bus/nes_ctrl/ctrl.cpp
src/devices/bus/nes_ctrl/sharpcass.cpp
src/devices/bus/nes_ctrl/sharpcass.h
src/mame/nintendo/nes.cpp

Sharp My Computer Terebi C1 [kmg]

bus/nes_ctrl: Added Sharp Cassette Interface AN-300SL device.

---

hash/nes.xml

Indora no Hikari [Zoda-Y13, Forest of Illusion]

nes.xml: Added another prototype cartridge.

---

hash/megadriv.xml

Super Spin (prototype) [GamingLegend64, Forest of Illusion]

megadriv.xml: Added an unreleased prototype.

---

hash/ngp.xml
hash/ngpc.xml

- Replaced the country's name abbreviations by the full name
- Lowercase on some descriptive words like "Prototype", "Demo"

ngp.xml, ngpc.xml: Metadata cleaning

---

hash/digiblast_cart.xml
src/devices/bus/centronics/digiblst.cpp
src/mame/mame.lst
src/mame/skeleton/digiblast.cpp

new NOT WORKING machine
-------------
digiBLAST [Team Europe]
digiblast_cart.xml:
sonicx1: Sonic X 1 (Italy / Spain) [Most-Student-5165]
sbsp1: Sponge Bob Square Pants 1 (Italy / Spain) [Most-Student-5165]
totsp1: Totally Spies! 1 (Italy) [Most-Student-5165]
yugi: Yu-Gi-Oh! (Italy / Spain) [Most-Student-5165]
winx1: Winx Club 1 (Italy / Spain) [Most-Student-5165]
wxatari: Winx Club + 5 Atari Games (Italy / Spain) [Most-Student-5165]

Added skeleton driver for Nikko Entertainment/Grey Innovation digiBLAST

---

hash/fmtowns_flop_misc.xml

Use lowercase for descriptive text in descriptions ("Alt", "Disk")

fmtowns_flop_misc.xml: Metadata cleaning

---

hash/nes.xml
src/mame/nintendo/nes_m8.cpp

nintendo/nes_m8.cpp: Made parent set 1 and oldest clone set 3.

nes.xml: Corrected indorap ROM label.

---

hash/coleco.xml

- Replaced Canada country abbreviation by the full name
- Use lowercase for descriptive text in descriptions ("Alt", "Prototype", "Earlier", Demo, "Bad")

coleco.xml: Metadata cleaning

---

hash/famicom_cass.xml

Abunai Penpen! [ozidual, Gaming Alexandria]
Fruit Panic [ozidual, Gaming Alexandria]
Itazura Karasu [ozidual, Gaming Alexandria]
Kani-san no Hatahokobi [ozidual, Gaming Alexandria]
Star Dust [ozidual, Gaming Alexandria]
War Game [ozidual, Gaming Alexandria]

famicom_cass.xml: Added six Micom BASIC Magazine games.

---

hash/ibm5170_cdrom.xml

Blackhawk (Europe) [Jackal, redump.org]
Network Q RAC Rally (USA) [MrX_Cuci, redump.org]
Supaplex (Europe) [Jackal, redump.org]

ibm5170_cdrom.xml: New working software list additions

---

hash/ekara_japan_s.xml

ekara_japan_s.xml:
sc0014            Saiten Cartridge Challenge Idol vol.4 (Japan) (SC0014-SAI) [Team Europe]
sc0020            Saiten Cartridge Challenge Idol vol.5 (Japan) (SC0020-SAI) [Team Europe]

New Software List Entries (2x e-kara)

---

hash/famicom_cass.xml

Star Ship Go!! [ozidual, Gaming Alexandria]

famicom_cass.xml: Added one more Micom BASIC magazine game.

---

hash/ibm5150.xml

Chess Simulator [The Good Old Days]
Chicago 90 [The Good Old Days]
California Pro Golf [The Good Old Days]
Command H.Q. (3.5") [The Good Old Days]
Command H.Q. (5.25") [The Good Old Days]
Expert Will (v1.4) [ibmpc5150, archive.org]
Metadata correction: Change floppy interface to 3_5 on "Wizardry" games

ibm5150.xml: 6 new working software list additions

---

hash/apple2_flop_clcracked.xml
hash/apple2_flop_orig.xml
hash/apple2gs_flop_orig.xml

Autoduel [4am, Firehawke]
Bismarck: The North Sea Chase [4am, Firehawke]
Championship Wrestling [4am, Firehawke]
GBA Championship Basketball [4am, Firehawke]
Moebius [4am, Firehawke]
The Games: Winter Edition [4am, Firehawke]
Six-Gun Shootout [4am, Firehawke]
The Road to Gettysburg [4am, Firehawke]
Gettysburg: The Turning Point (Version 1.2) [4am, Firehawke] Microzine 31 [4am, Firehawke]
Microzine 33 [4am, Firehawke]
Microzine 34 [4am, Firehawke]
Microzine 35 [4am, Firehawke]
Microzine 36 [4am, Firehawke]
Microzine 37 [4am, Firehawke]
Microzine 38 [4am, Firehawke]
Microzine 39 [4am, Firehawke]
The Balance of Nature (800K 3.5") [4am, Firehawke] The Insect World (800K 3.5") …

Apple software for September

---

src/mame/nmk/nmk16.cpp

They are the same as the ones in bjtwin set

sabotenb: added dumps for proms

---

hash/ekara_japan_en.xml
hash/ekara_japan_g.xml
hash/ekara_japan_m.xml
hash/ekara_japan_s.xml
hash/ekara_japan_web.xml

new SOFTWARE LIST entries
-----------
ekara_japan_m.xml:
mc0003  Artist Mini Volume 3 (Japan) (MC0003-ATM) [Team Europe] 
mc0010  Artist Mini Volume 6 (Utada Hikaru) (Japan) (MC0010-ATM) [Team Europe] 
mc0015  TV Pop Mini Vol.1 (Japan) (MC0015-TPM) [Team Europe]
ekara_japan_s.xml:
sc0002  Saiten Cartridge: Challenge Idol vol.1 (Japan) (SC0002-SAI) [Team Europe] 
sc0008  Saiten Cartridge: Challenge Idol vol.2 (Japan) (SC0008-SAI) [Team Europe]
ekara_japan_web.xml
ekaraweb12b  e-kara Web cartridge 12M (used, with 12 songs) (Japan) [Team Europe]
ekara_japan_en.xml:
en4  Enka-shÅ« Dai Yon-hen (Japan) (EN-4) [Team Europe]
ekara_japan_g.xml:
gc0005  TV Pop Junior Volume 1 (Japan) (GC0005-TPJ) [Team Europe]

new SOFTWARE LIST entries (8x ekara)

---

hash/evio.xml

new SOFTWARE LIST entries
evio.xml:
em1    evio Selection 01 [Team Europe]
em5    Healing Air 1 [Team Europe]
em6    Drama Mix 1 [Team Europe]
em10   Anime Special - Pocket Monsters [Team Europe]
em15   evio Selection 04 [Team Europe]
em17   Minna no evio [Team Europe]

new SOFTWARE LIST entries (6x evio cartridges)

---

hash/nes.xml

Creepy Brawlers [No-Intro]
Haunted: Halloween '85 [No-Intro]
Haunted: Halloween '86 - The Curse of Possum Hollow [No-Intro]
Haunted: Halloween '86 - The Curse of Possum Hollow (alt) [No-Intro]

nes.xml: Added four spooky homebrews.

---

src/mame/mame.lst
src/mame/toaplan/twincobr.cpp

Kyukyoku Tiger (Japan, set 1) [Mikado Game Center Europe, Victor Fernandez (City Game)]

toaplan/twincobr.cpp: Dumped an added a newer ktiger set

---

scripts/src/formats.lua
src/devices/bus/multibus/isbc202.cpp
src/lib/formats/all.cpp
src/lib/formats/fs_isis.cpp
src/lib/formats/fs_isis.h
src/lib/formats/img_dsk.cpp
src/lib/formats/img_dsk.h
src/mame/intel/imds2ioc.cpp

Hi, this is actually old PR #10281 adapted to changes in 5499683a239.
Thank you.
--F.Ulivi

Added support for Intel ISIS-II filesystem

---

hash/cdtv.xml

Replaced the countries' abbreviations by the countries' full name

cdtv.xml: Metadata cleaning

---

hash/sms.xml

Replaced the countries' abbreviations by the full names

sms.xml: Metadata cleaning

---

src/mame/taito/taito_f3_v.cpp

I've done some bits of work on this over the years, including, but not limited to, fixing up the billboards in the football games.

Add myself to the taito_f3_v.cpp header

---

hash/coleco.xml

Dr. Seuss's Fix-Up the Mix-Up Puzzle (Rev R prototype) [phattyboombatty]
Dr. Seuss's Fix-Up the Mix-Up Puzzle Graphics Demo [phattyboombatty]

coleco.xml: Added a couple prototypes.

---

.github/workflows/ci-windows.yml

Same idea as the Linux CI build extended to Windows

Add clang/Windows CI build

---

hash/gameboy.xml

Jeep Jamboree (USA, prototype) [square_wave, Forest of Illusion]

gameboy.xml: Added a prototype.

---

hash/gamegear.xml

Replaced the countries' abbreviation by the countries' full name.

gamegear.xml: Metadata cleaning

---

hash/gba.xml

Replaced the countries' abbreviation by the countries' full name.

gba.xml: Metadata cleaning

---

hash/gameboy.xml

Super Scrabble (USA, prototype) [Zach Lambert, Forest of Illusion]

gameboy.xml: Added one more prototype.

---

hash/a7800.xml

Astro Blaster (NTSC) [Trebor]
Astro Fighter (NTSC) [Trebor]
FailSafe (NTSC) [Trebor]
FailSafe (PAL) [Trebor]
Meteor Shower (NTSC) [Trebor]
Meteor Shower (PAL) [Trebor]
Moon Cresta (NTSC) [Trebor]
Moon Cresta (PAL) [Trebor]
Super Pac-Man (NTSC) [Trebor]
Super Pac-Man (PAL) [Trebor]

a7800.xml: Added 10 homebrew cartridges.

---

hash/a5200.xml

Battlezone (prototype, alt) [swlovinist]
Behind Jaggi Lines (prototype) [swlovinist]
Pole Position (prototype 133-05) [swlovinist]
Astro Grover (prototype) [CPUWIZ]

a5200.xml: Added four prototypes.

---

hash/ibm5170.xml

I Dream of Jeannie [MAZterXP, archive.org]
Operation Crusader [The Good Old Days]
Operation Harrier [The Good Old Days]
Personal Computer World (1994-06 - June 1994) [arranarchipelago, archive.org]
Personal Computer World (1994-11 - November 1994) [SmartCoda, archive.org]
Personal Computer World (1997-05 - May 1997) [SmartCoda, archive.org]

ibm5170.xml: 6 new working software list additions

---

hash/snes.xml

Bing Bing! Bingo (Japan, prototype) [keiichi-desu]
Densetsu no Ogre Battle - The March of the Black Queen (Japan, prototype) [keiichi-desu]
Dual Orb - Seireiju Densetsu (Japan, prototype) [keiichi-desu]
Elfaria - The Isle of the Blest (Japan, prototype) [keiichi-desu]
Kessen! Dokapon Oukoku IV - Densetsu no Yuusha-tachi (Japan, prototype, Ver 07.315) [keiichi-desu]
Kessen! Dokapon Oukoku IV - Densetsu no Yuusha-tachi (Japan, prototype, Ver 07.431) [keiichi-desu]
Kunio no Oden (Japan, prototype) [keiichi-desu]
The Last Battle (Japan, prototype) [keiichi-desu]
Michael Andretti's IndyCar Challenge (USA, prototype) [keiichi-desu]
Nosferatu (Japan, prototype) [keiichi-desu]
Super Nazo Puyo - Rulue no Roux (Japan, …

snes.xml: Added 14 prototypes (13 working, 1 not working).

---

src/devices/sound/pokey.cpp

- fixes a1200xl booting to self-test no matter J1 setting, as observed by https://github.com/mamedev/mame/pull/10442#discussion_r1002482276

pokey.cpp: remove m_SKCTL assignment hack in device_start and issue a potgo at device_reset instead

---

hash/gamecom.xml

Castlevania - Symphony of the Night (prototype) [Anonymous, diskman.com, Hidden Palace]

gamecom.xml: Added a prototype.

---

hash/apple2_flop_orig.xml

- Added the question mark on the Carmen Sandiego's descriptions.
- Changed the publisher's name "Broderbund" to "Brøderbund".

apple2_flop_orig.xml: Metadata cleanups

---

hash/32x.xml

32x.xml: Metadata cleanings

---

src/mame/cirsa/neptunp2.cpp
src/mame/mame.lst

New NOT_WORKING games
La Perla del Caribe (V1.0, Catalonia) [jordigahan, Recreativas.org]
Multi Points [jordigahan]
unknown 960606-5 based machine (set 2) [jordigahan]

Dumped and added three more games on Unidesa/Cirsa "960606-5" hardware

---

src/mame/msx/msx.h
src/mame/msx/msx1.cpp
src/mame/msx/msx2.cpp

msx1.cpp: Fixed incorrect configuration of hb55d.
msx2.cpp: Fixed regression of hbf900a.

msx: Fixed problems with hb55d and hbf900a

---

src/devices/machine/wd_fdc.cpp

Adjust write protect delay to better match real hardware.

Refine write protect delay value

---

hash/n64.xml

SimCopter 64 (prototype 19970616) [VGHF]

n64.xml: Added an unreleased prototype.

---

hash/nes.xml

- The Cheetahmen: The Creation (USA) [Magic Jewelry Nerd]

nes.xml: Added new working entry

---

hash/pico.xml

- Lowercase on descriptive words ("Alt", "Prototype")

pico.xml: Metadata cleaning

---

hash/a2600.xml

Turbo (NTSC, prototype) [Rom Hunter]

a2600.xml: Added an unreleased prototype.

---

hash/megacd.xml
hash/megacdj.xml

megacd.xml, megacdj.xml: Metadata cleanings

---

hash/scv.xml

- Lowercase applied on "Alt" descriptive word
- Add tag info with `alt_title` on y2mnstld set (and removed the comment)

scv.xml: Metadata cleanings

---

src/mame/mame.lst
src/mame/misc/falgas_m89.cpp

Fantastic Car (M89 hardware) [Eduardo Anay]
New NOT_WORKING  clone
Fantastic Car (Micro-87 hardware) [Eduardo Anay]

Dumped and added two different versions of Falgas "Fantastic Car" kiddie ride

---

src/mame/mame.lst
src/mame/misc/diamondking.cpp

Dumped and added "Golden Chip" slot machine from SegaSA / Sonic

---

hash/msx1_cart.xml
hash/msx1_cass.xml

msx1_cart.xml: Marked testcart as bad dump.
msx1_cass.xml: Added 47 titles, 1 redump.
Aprende astronomía con El Sol (Spain) [msxcassettes]
Aprende astronomía con la Luna (Spain) [msxcassettes]
Aprende astronomía con la Tierra en el espacio (Spain) [msxcassettes]
Aprende astronomía con los planetas (Spain) [msxcassettes]
Cocos (Spain) [msxcassettes]
Contabilidad Personal (Spain) [msxcassettes]
Data MSX - Issue 01 (Spain) [msxcassettes]
Data MSX - Issue 04 (Spain) [msxcassettes]
Data MSX - Issue 09 (Spain) [msxcassettes]
Dog Fighter (Spain) [msxcassettes]
Floppy el Pregunton (Spain) [msxcassettes]
Frankie (Spain) [msxcassettes]
Freddy Hardest (UK, Italy) [msxcassettes]
Generador de Sprites (Spain) [msxcassettes]
Golf …

msx1_cass.xml: Added 47 titles, 1 redump.

---

src/mame/gaelco/mastboy.cpp
src/mame/mame.lst

gaelco/mastboy.cpp: Fix description for 'mastboyib' and rename it to 'mastboyiv2'

---

hash/neogeo.xml
hash/ngp.xml
hash/ngpc.xml

- Lowercase on descriptive words

neogeo.xml, ngp.xml and ngpc.xml: Metadata cleanings

---

hash/neocd.xml

- Lowercase on descriptive "Alt" abbreviation

neocd.xml: Metadata cleanings

---

hash/sg1000.xml

- Lowercase on descriptive words ("Alt", "Older", "Prototype", "Hacked")

sg1000.xml: Metadata cleanings

---

hash/a5200.xml

Lower case on some descriptive words

a5200.xml: Metadata cleaning

---

src/mame/nintendo/vsnes.cpp

I played around with this some more and learned some more about mahjong. The dora rule variants seem to usually be referred to as 現物 and ネクスト, so that's what I've called them here. If there's some other common MAME nomenclature let me know.

nintendo/vsnes.cpp: Fill in missing Dora DIP settings.

---

hash/nes.xml

nes.xml: Add the Yuletide homebrew in prep for MAMEmas!

---

hash/rz1_cass.xml

Lowercase on descriptive "samples" word

rz1_cass.xml: Lowercase on descriptive word

---

hash/apple2_flop_orig.xml

Uppercase on "Brøderbund Software" publisher's initials

apple2_flop_orig.xml: Uppercase on publisher's initials

---

src/devices/video/v9938.cpp

v9938.cpp: Add support for V9958 registers 26 and 27 to modes graphic23 and graphic4 mode. Fixes MT#08466

---

hash/snes.xml

16 Bit Xmas 2011 - Christmas Craze (USA) [retroUSB]
16 Bit Xmas 2012 - Snowball Fight (USA) [retroUSB]

snes.xml: Put a couple holiday homebrews in your SNES stocking.

---

hash/sega_beena_cart.xml

Lowercase on "cartridges" word in software list name

sega_beena_cart.xml: software list rename

---

hash/pcecd.xml

Replaced "Jpn" country abbreviation by "Japan"

pcecd.xml: Metadata cleanups

---

hash/megadriv.xml

megadriv.xml: Rockman Mega World (Japan, EEPROM) [eientei]

megadriv.xml: add offset="0x000000" back for multi-rom entries; fix rockman1 entry

---

src/mame/dataeast/decocass.cpp
src/mame/dataeast/decocass.h
src/mame/dataeast/decocass_m.cpp
src/mame/mame.lst

New WORKING Machines
------
Nebula (DECO Cassette) (UK) [Rene Balke, Darksoft, Arcadeautomaten/Senil Data Systems, David Haywood]

New WORKING Machines (Nebula, DECO Cassette)

---

hash/pc98.xml

Lowercase on descriptive words (like: "Alt", Disk", "Format", "Fix", etc...)

pc98.xml: Metadata cleanups

---

hash/msx2_cart.xml
hash/msx2_cass.xml
hash/msx2_flop.xml
hash/msx2p_flop.xml

- Lowercase on descriptive words ("Alt", "Cracked", "Demo", "Remake", ...)

msx2_cart.xml, msx2_cass.xml, msx2_flop.xml, msx2p_flop.xml: Metadata cleanings

---

src/mame/mame.lst
src/mame/yamaha/ympsr16.cpp

dumped pss-780 ic4
(ic3 is same as pss-680)

new machine (not working/skeleton): Yamaha keyboard/musicstation pss-780

---

hash/sms.xml

King's Quest - Quest for the Crown (USA, prototype, 19890203) [Ed Semrad, smspower, VGHF]
Monopoly (USA, prototype, alt) [Ed Semrad, smspower, VGHF]
Super Monaco GP (USA, prototype) [Ed Semrad, smspower, VGHF]

sms.xml: Added 3 prototypes.

---

src/mame/capcom/cps1.cpp
src/mame/capcom/cps1_v.cpp

created proper sfzch mapper (decoded the recently found/dumped SFZ63B pal)

created proper sfzch mapper

---

hash/nes.xml

2 in 1 - GEMiNIM & Siamond [NESBrew12]
Crazy Land (USA, prototype) [Ed Semrad, Hidden Palace, VGHF]
Galaxy 5000 - Racing in the 51st Century (USA, prototype) [Ed Semrad, Hidden Palace, VGHF]
Hoops (USA, prototype) [Ed Semrad, Hidden Palace, VGHF]
Iron Tank - The Invasion of Normandy (USA, prototype) [Ed Semrad, Hidden Palace, VGHF]
Nighttime Bastards [anonymous]
R.B.I. Baseball 2 (USA, prototype, 19900307) [Ed Semrad, Hidden Palace, VGHF]
Rally Bike (USA, prototype, 19900226) [Ed Semrad, Hidden Palace, VGHF]
RoadBlasters (USA, prototype) [Ed Semrad, Hidden Palace, VGHF]
Shadow of the Ninja (USA, sample) [Ed Semrad, Hidden Palace, VGHF]
Silkworm (USA, prototype) [Ed Semrad, Hidden Palace, VGHF]
Sudoku 2007 [NESBrew12]

nes.xml: Added 12 dumps.

---

src/mame/sega/turbo.cpp
src/mame/sega/turbo.h

- turbo: Added pedal. Made shifter start in low gear by default.
- buckrog: Added pedal, which is selected by accelerator type DIP switch. Corrected cabinet type DIP switch, which now also controls presence of 2P start button.

sega/turbo.cpp: Added missing pedal inputs.

---

src/mame/capcom/gunsmoke.cpp
src/mame/mame.lst

Gun.Smoke (USA and Canada, 1986/01/20) [Victor Fernandez (City Game), Jordi Beltrán]
* Also fixed metadata on the other sets

capcom/gunsmoke.cpp: Dumped and added a new Gun.Smoke set

---

hash/ibm5150.xml

Arcade Hits [The Good Old Days]
Bombuzal [The Good Old Days]
Mega Man (3.5") [The Good Old Days]
Pole Position [The Good Old Days]
Street Fighting Man (alt) [The Good Old Days]
Teenage Mutant Hero Turtles (5.25") [old-games.ru]
Teenage Mutant Hero Turtles (Spain, 3.5") [Abandon Socios]
Teenage Mutant Hero Turtles (Spain, 5.25") [Abandon Socios]
Zeliard (3.5") [The Good Old Days]
Zeliard (3.5", v2.0) [old-games.ru]
Zeliard (5.25") [The Good Old Days]

ibm5150.xml: 11 New working software list additions

---

src/mame/sega/turbo_v.cpp

@happppp Here's another minor cleanup to go along with all the others. When I tried (and failed) to fix the priority issue I somehow found these lines very annoying.

sega/turbo_v.cpp: another minor code simplification
