mamedev/mame

- src/mame/drivers/galaxian.cpp
- src/mame/includes/galaxian.h
- src/mame/video/galaxian.cpp
This is a starting-point for splitting up the “everything-bucket” state class in the “new” Galaxian driver.  It’s mostly the help @DavidHaywood with the impasse mentioned in #8164.
This is really just a starting point, and there’s a lot of work to do:
* There’s obviously still a huge amount of game-specific stuff in the state class
* I’m not sure whether `bagmanmc_state` and `pisces_state` are the right points to split things at – I wouldn’t be offended if that stuff got pushed back down into `galaxian_state`
* There’s a bunch of stuff in driver init functions that should go in machine configuration and machine start functions
* Eventually the tile extension callbacks and draw callbacks should be turned into device delegates and set from machine configuration
> galaxian.cpp: Started splitting up the state class

- hash/mac_hdflop.xml
This is the second (and last, for now) batch of additions from WinWorld. There's probably a lot more out there, but that's going to take some time.
---
- Renamed "ClarisWorks 2.0 (Swedish)" to "ClarisWorks 3.0Sv1 (Swedish)", the version number was incorrect
Apple Network Administration Toolkit 1.0 [WinWorld]
Apple Network Administration Toolkit 1.0 Updates [WinWorld]
Apple Network Administration Toolkit 2.0 Updates [WinWorld]
Claris Organizer 2.0v1 [WinWorld]
ClarisWorks 2.0CDv1 (UK English) [WinWorld]
ClarisWorks 3.0CDv1 (UK English) [WinWorld]
ClarisWorks 4.0v4 (US English) [WinWorld]
ClarisWorks 4.0Sv1 (Swedish) [WinWorld]
FoxBASE+/Mac 2.00 [WinWorld]
FrameMaker 4.0.2 [WinWorld]
FrameMaker 5.0 [WinWorld]
Microsoft …
> mac_hdflop.xml: second batch of additions, rename clarisw20sv

- hash/megadriv.xml
Bio Hazard Battle (prototype) [Modern Vintage Gamer]
Ship (visitor prototype) [Modern Vintage Gamer]
Disney's Aladdin (prototype 19930627) [Hidden Palace]
Australian Rugby League (prototype) [Hidden Palace]
Captain Lang (prototype) [Hidden Palace]
Champions World Class Soccer (prototype) [Hidden Palace]
College Football USA 96 (prototype 19950621) [Hidden Palace]
Danny Sullivan's Indy Heat (prototype) (pirate) [Hidden Palace]
Dr. Robotnik's Mean Bean Machine (USA, prototype b) [Hidden Palace]
Dune - The Battle for Arrakis (Euro, prototype 19940111) [Hidden Palace]
The Flintstones (Ocean prototype) [Hidden Palace]
Granada (Jpn, USA, v1.1 prototype) [Hidden Palace]
NBA Jam (Apr 1993 prototype) [Hidden Palace]
NHLPA …
> megadriv.xml: more protos, even more blast processing

- src/devices/video/hd61830.cpp
- src/mame/drivers/pofo.cpp
When Cursor=Off and Blink=On, the controller is in "Character Blink"
mode, according to the data sheet.
This means that the character cell at the the position of the cursor is
turned fully ON at a 50% blink duty cycle. Verified on a device with a
real HD61830 (Atari Portfolio).
> HD61830: Fix character blink mode

- src/mame/drivers/psikyosh.cpp
because flip screen isn't support now
Add docs for ROM location/usage, Export name for daraku
Fix fill value for empty ROM area
Fix naming
> psikyosh.cpp: Add/Fix docs based on PCB marking,Demote games with MACHINE_NO_COCKTAIL

- src/mame/drivers/pasha2.cpp
Remove palette RAM trampolines
Use bitmap_ind16 and copybitmap for bitmap functions, Fix namings
Add XTAL for clock generations
Add hardware notes, Use shorter/correct type values
> pasha2.cpp: Minor cleanups

- src/mame/drivers/psikyo.cpp
Sengoku Ace (and overseas version Samurai Aces?) is distributed by Banpresto, reference from some japanese flyer.
> psikyo.cpp: Fix metadata

- src/devices/bus/pofo/hpc104.cpp
- src/mame/drivers/pofo.cpp
A combination of various fixes:
---
pofo: Fix RAM expander read access
This was writing the uninitialized `data` value into RAM on read
accesses, causing the external RAM checks to fail. Probably a typo, fix.
---
pofo: Magic port 0x61 emulation
This is used by various utility programs (such as `ram_test.com` and
`lcd_test.com`) to identify if the program is running on a Pofo.
Apparently 0x61 is the Pofo developers favorite magic value, since the
Pofo-specific services' interrupt number is also 0x61.
---
pofo: Fix external drive B: detection
(see added comment in code)
---
pofo: Better control register 0x8051 emulation
(see added comment in code)
> Atari Portfolio: Emulation fixes and improvements

- makefile
Currently the FreeBSD section is outside of BIGENDIAN block.
> End the big-endian block in the right place

- hash/apple2_flop_clcracked.xml
- hash/apple2gs_flop_orig.xml
New working software list additions (apple2_flop_clcracked.xml)
Bumble Games (Version 1.3) (cleanly cracked) [4am, san, Firehawke]
Reader Rabbit (Version 1.0) (cleanly cracked) [4am, san, Firehawke]
Projectile and Circular Motion (cleanly cracked) [4am, Firehawke]
Bumble Plot (Version 1.1) (cleanly cracked) [4am, san, Firehawke]
Gertrude's Puzzles (1982 Version) (cleanly cracked) [4am, san, Firehawke]
Gertrude's Secrets 1982 (cleanly cracked) [4am, san, Firehawke]
Tales of Discovery (cleanly cracked) [4am, san, Firehawke]
Advanced Electricity (cleanly cracked) [4am, Firehawke]
Complex Circuits (cleanly cracked) [4am, Firehawke]
PAI Forth (Version 3.0, 12-21-1985) (cleanly cracked) [4am, Firehawke]
Rocky's Boots (Unknown 1982 …
> Apple updates for June 2021

- src/frontend/mame/ui/state.cpp
- src/frontend/mame/ui/state.h
This post on r/MAME asked about it: https://www.reddit.com/r/MAME/comments/o53l6z/does_anyone_knows_how_to_delete_a_save_state_from/
There currently isn’t a way to do it, but this implements it with relatively low impact.  You’re prompted to confirm you really want to delete.  If you do, it removes the file directly (it doesn’t get get put in the Recycle Bin or similar), so no backsies.
Any objections to this?
> Allow saved states to be deleted from the internal UI.

- hash/sgi_mips_hdd.xml
-sgi_mips_hdd: Added _hdd suffix to entries to prevent conflicts with CD-ROM entries when both are present. [Ryan Holtz]
> Fixed conflicting softlist entries in SGI softlists.

- hash/c64_cass.xml
Reviewed c64_cass.xml and noticed a number of release years were inconsistent, missing or incorrect, and a few of the publisher details were also incorrect.
During the 80's and 90' there were a number of budget labels that had been created by some publishers to release games at a discounted price.  Sometimes these games were re-releases of games previously published by the same company at full price.
Notable budget labels are as follows:
Firebird Silver (Firebird) - A mix of original and re-releases.
Silverbird (previously Firebird Silver) - A mix of original releases and re-releases.
Ricochet (Mastertronic) - All re-releases.
The Hit Squad (Ocean & U.S. Gold) - All re-releases and compilations.
Encore (Elite Systems) - Mostly re-releases.
Kixx (U.S. Gold) - All re-releases.
Summit …
> c64_cass.xml - updated year and publisher details

- src/mame/drivers/snes.cpp
- src/mame/machine/cx4fn.hxx
- src/mame/machine/cx4oam.hxx
- src/mame/machine/cx4ops.hxx
- src/mame/machine/snescx4.cpp
- src/mame/machine/snescx4.h
It was already passing the machine around everywhere, for no reason other than to fetch the maincpu. Instead just pass the address_space, which is really all it needs in the end anyway.
> Eliminate reacharound calls to fetch the maincpu in the SNES CX4

- scripts/target/mame/arcade.lua
- src/mame/arcade.flt
- src/mame/drivers/segas18_astormbl.cpp
- src/mame/drivers/system16.cpp
- src/mame/includes/system16.h
- src/mame/mame.lst
this at least renders the backgrounds using the very strange 'tile strip' logic the bootleg hardware appears to implement as a replacement for the system16/18 'pages' making them a lot more playable.
> rework system18 Alien Storm bootlegs, put in their own driver to study

- hash/megadriv.xml
Ballz 3D (USA, prototype 199406xx) [HyperGHZ]
Ballz 3D (prototype 199409xx) [ExplodedHamster]
Disney's The Jungle Book (prototype) [Hidden Palace]
Mega Turrican (prototype 19930518) [armadylo]
Michael Jackson's Moonwalker (prototype 19900424) [Landon White]
Taz-Mania (prototype) [stonic]
Wayne Gretzky and the NHLPA All-Stars (prototype 19950217) [Sonik]
also:
* fix PCB refdes errors on crydragn
* move ggroundp and legobatm out of fully documented section
> megadriv.xml: add protos + some fixes

- src/tools/imgtool/imgtool.cpp
- src/tools/imgtool/imgtool.h
- src/tools/imgtool/library.cpp
- src/tools/imgtool/library.h
- src/tools/imgtool/main.cpp
- src/tools/imgtool/modules.cpp
- src/tools/imgtool/modules/os9.cpp
Object/resource pool usage was almost gone from imgtool. This PR removes the remainder. Specifically:
* The image class doesn't allocate extra_data for the module; rather, the module allocates it on its own
* Several strings are now represented as std::string in the module structure (which can no longer be cleared by memset)
* The image::malloc() function has been removed; it was only used in one place, for the OS9 bitmap allocation. Since the maximum bitmap size is only 64k, to avoid deeper changes I just changed it to a fixed size 64k array so that the malloc is no longer needed.
With this PR, and the next one to remove usage from flopimg, we should be able to remove the very legacy src\lib\util\pool.* code altogether.
> imgtool: Remove object pool usage

- hash/nes.xml
Sample Cassete Cadillac (Jpn) [Skrybe]
F-1 Race (Jpn, prototype) [Skrybe]
Meikyuu Kumikyoku - Milon no Daibouken (Jpn, prototype) [Skrybe]
Double Dragon III - The Rosetta Stone (USA, prototype) [Hidden Palace]
Robin Hood - Prince of Thieves (USA, 19910516 prototype) [Hidden Palace]
Dino Hockey (USA, 19901218 prototype) [Frank Cifaldi]
Garfield - A Week of Garfield (Jpn, prototype v0.9) [togemet2]
Getsufuu Maden (Jpn, sample) [Ballz, Kevtris]
Magical Doropie (Jpn, prototype) [SegaSamiCD, VGHF]
Millipede (Jpn, prototype) [Dutchman2000, bunnyboy]
The Tale - Elrond no Eiyuu (Jpn, prototype) [TC, anonymous]
U-four-ia - The Saga (USA, prototype) [armadylo]
> nes.xml: add a dozen more protos

- hash/ibm5170_hdd.xml
This also includes a handful of formatting fixes for consistency.
New working software list additions:
FreeDOS 1.0
FreeDOS 1.3 Release Candidate 4
MS-DOS (Version 3.31)
MS-DOS (Version 6.20)
IBM DOS (Version 5.00)
IBM DOS (Version 5.02)
IBM DOS (Version 6.1)
Microsoft Windows/386 Version 2.1
Microsoft Windows/386 Version 2.11
Windows Version 3.11
Windows for Workgroups Version 3.1
Windows for Workgroups Version 3.11
Windows NT 3.1 Workstation (3.10.511.1)
Windows NT 3.51 Workstation (3.51.1057.1)
Windows 95
> ibm5170_hdd: new software list additions

- hash/fmtowns_flop_cracked.xml
- hash/fmtowns_flop_misc.xml
- hash/fmtowns_flop_orig.xml
- Demoted shogisei to not working, as I haven't found any way to make it work
- Added usage and compatibility notes to most floppy software
- Removed reira from fmtowns_flop_misc.xml, since it has been redumped from the original disks (the previous images were built from loose files)
- Added some missing release years
Gear-Video [cyo.the.vile]
Logo Writer 2 [cyo.the.vile]
Reira [wiggy2k]
Software list items promoted to working (fmtowns_flop_orig.xml)
Asuka 120% Burning Fest. [crazyc]
Software list items promoted to working (fmtowns_flop_cracked.xml) …
> fmtowns_flop_*.xml: 3 new dumps, usage notes, retests

- src/mame/video/gime.cpp
- src/mame/video/gime.h
1. Calculate based on clock divisors.
2. Fix PAL timings.
3. Stopping passing a floating point value to a function that expects an integer.
> coco3: improve timer value

- src/devices/bus/centronics/ctronics.cpp
- src/devices/bus/centronics/ctronics.h
- src/devices/bus/centronics/epson_ex800.h
- src/devices/bus/centronics/epson_lx800.h
- src/devices/bus/centronics/epson_lx810l.h
- src/devices/bus/centronics/printer.h
- src/mame/drivers/qx10.cpp
Add centronics printer port to qx10 emulation.
The new sense_handler() on the centronics bus is a 5 volt signal generated on pin 35 of the centronics connector and is used to sense if there is a powered up device attached to the port.
> qx10: Add centronics printer port

- hash/ibm5170.xml
Also update the labels for the pcdos61 sets to be more accurate
> ibm5170: add some missing labels

- src/mame/drivers/lwriter.cpp
Without this the ROM will set up a buffer of bytes to send to SCC A but
thinks it's getting ready to transmit interrupts on SCC B.
With this change we now succesfully get the following error message
after we timeout trying to intialize the print controller.
%%[ PrinterError: controller not responding ]%%
> lwriter.cpp: Swap SCC a/b addresses.

- src/mame/drivers/lwriter.cpp
This is enough to avoid the timeouts when initializing the print controller and
the ROM now crashes when trying to print the test page.
> lwriter.cpp: Stub out a minimal print controller

- src/mame/drivers/lwriter.cpp
This is enough to get the ROM to boot into the PostScript
executive.
> lwriter.cpp: Stub out a bit of the eeprom

- src/mame/drivers/cave.cpp
Pac-Carnival has a routine at $0001630E that tries to detect what addresses various things are mapped to, and generates a 4-character string representing the following:
```
first digit:  location of IRQ and video regs
second digit: location of layer 0
third digit:  location of palette
fourth digit: location of inputs
```
The current configuration is detected as "4675", while the game itself expects "7654" and will halt if it detects anything else. This just rearranges things to match the expected configuration.
> cave.cpp: fix address map for paccarn, promote to working

- hash/32x.xml
> 32x.xml: add Euro parent set for zaxxon2k

- scripts/src/bus.lua
- src/devices/bus/a2bus/lancegs.cpp
- src/devices/bus/a2bus/lancegs.h
- src/devices/machine/smc91c9x.cpp
- src/devices/machine/smc91c9x.h
- src/mame/drivers/apple2e.cpp
- src/mame/drivers/apple2gs.cpp
LANceGS ethernet card for The Apple IIe and IIgs.  smc91c9x changes were broken up into smaller parts for review but I will squash after review.
smc91c9x code doesn't seem to be big endian clean but I left that alone.
Is there a good way to handle the EEPROM?  It includes an identification string (which may be checked in software) as well as card specific information including the MAC address and serial number.
> apple2 - lancegs support

- hash/nes.xml
- src/devices/bus/nes/multigame.cpp
- src/devices/bus/nes/multigame.h
- fixes the menu in mc_s42 so you can actually tell what you are selecting
- fixes the menu in mc_76 so it refreshes when returning from submenu pages to main menu
- fixes graphics glitches too numerous to list (anything with scrolling was heavily glitched to unplayable)
- simplifies the code a bit
> bus/nes: fix broken graphics for mapper 226 (two multicart pirate carts)

- hash/nes.xml
- src/devices/bus/nes/discrete.cpp
- src/devices/bus/nes/kaiser.cpp
- metroidk: corrects fixed bank address that caused game to crash after title screen
- metroidk: corrects the nametable page mis-ordering that then becomes apparent when game is running
----------------------------------------
Crime Busters
Metroid - Jin Ji Zhi Ling (Asia, FDS conversion)
> bus/nes: fix Kaiser Metroid, promote games to working

- src/mame/drivers/batman.cpp
- src/mame/includes/batman.h
- src/mame/video/atarimo.cpp
- src/mame/video/atarimo.h
- src/mame/video/atarivad.cpp
- src/mame/video/atarivad.h
my point of reference is https://youtu.be/IyDdq5B8R9g which is a video of a PCB being repaired.
this clearly shows the tilemaps were previously misaligned by 2 pixels vs. the hardware output (check the extreme right of the car dashboard at 8:50, see which pixels are visible, also note MAME was rendering 2 unwanted flashing columns on the left during the same scene which are gone with the shift)
sprite alignment against the background can be seen at 4:42 when batman is pressing against the crate, there's a single pixel gap between his foot and the crate
text layer alignment can be compared to other layers in various place
furthest back layer is not 100% verified against the video.
I don't know if the number of layers enabled or similar has an effect on the offsets, but these cases where …
> batman.cpp - layers need some offsets to align with real PCB videos

- src/devices/cpu/spc700/spc700.cpp
The old MAKE_INT_8 macro failed (added 0x100 displacement in the BRANCH method) on gcc-arm-none-eabi-10-2020-q4-major since by default __CHAR_UNSIGNED__ is defined on that platform. Now there might be a better solution to this. Figured this is 2021 and int8_t should be available everywhere. Fixes works on MSVC2017, (gcc-arm) and XCode12 (llvm). Now MAME may use -fsigned-char when compiling and this change makes no sense. I am using this file outside and took me a while to find this issue.
> MAKE_INT_8 fails on GCC/ARM

- hash/c64_cass.xml
A View to a Kill (Domark) [C64 Ultimate Tape Archive V2.0]
ACE: The Air Combat Emulator (Cascade Games) [C64 Ultimate Tape Archive V2.0]
AcroJet (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Action Pack (Prism Leisure Corporation, alt) [C64 Ultimate Tape Archive V2.0]
Addicted to Fun: Rainbow Collection (Ocean) [C64 Ultimate Tape Archive V2.0]
Advanced Pinball Simulator (Codemasters) [C64 Ultimate Tape Archive V2.0]
Adventures of Bond... Basildon Bond (Probe Software) [C64 Ultimate Tape Archive V2.0]
Alleykat (Hewson Consultants, alt) [C64 Ultimate Tape Archive V2.0]
Altered Beast (Activision) [C64 Ultimate Tape Archive V2.0]
Alternative World Games (Gremlin Graphics) [C64 Ultimate Tape Archive V2.0]
America's Cup …
> c64_cass.xml: 30 new dumps

- src/mame/video/namco_c355spr.cpp
-c355spr: Fixed handling of sprite attribute table index, fixes missing sprites in finalapr. [Ryan Holtz]
> Fixed incorrect handling of sprite format table masking in Namco C355

- src/mame/drivers/namcos2.cpp
since this isn't the standard Namco System 2 video board (different sprites) and the C355 sprite device has been shown to need buffering in other cases, I speculate there is buffering here.
it might be under CPU control as there are some interesting writes around the sprite area, but for the moment we're using the mechanism that is in place and used by other games.
> use namco_c355spr_device built in sprite buffering to pevent flickering gfx in suzuk8h2 [David Haywood]

- src/mame/drivers/namconb1.cpp
- src/mame/drivers/namcos2.cpp
- src/mame/includes/namconb1.h
- src/mame/includes/namcos2.h
- src/mame/video/namco_c355spr.cpp
- some Namco posirq kludges [David Haywood]
This fixes some graphics in Burning Force, Suzuka 8 Hours 2, and Nebulusray
In reality this probably needs correct emulation of when each layer latches values / renders scanlines (with some layers being linebuffered, and others not etc.) but I think identifying the problematic cases, and the fact that they are IRQ related helps for now, and Burning Force's regression keeps being reported.
- fix remaining finalapr sprite positions [Ryan Holtz]
This seems to cause a slight issue with Solvalou's top display, but Namco S21 positions are somewhat kludged anyway, and that's an unusual case with a mirror effect over the screen cropping off the top, so needs it's own research.
> some Namco posirq kludges [David Haywood] + Final Lap R sprite position fix [Ryan Holtz]

- hash/nes.xml
- src/devices/bus/nes/kaiser.cpp
- src/devices/bus/nes/nes_ines.hxx
- src/devices/bus/nes/nes_unif.hxx
This fixes the loader from silently loading mapper numbers modulo 256. It hooks up a skeleton list of mappers > 255 for loading loose .nes files and correctly aborts for those not hooked up.
> bus/nes: Support full 12-bit mapper numbers in NES 2.0 loader.

- 3rdparty/softfloat/fpatan.c
- 3rdparty/softfloat/softfloat.h
- scripts/src/3rdparty.lua
- src/devices/cpu/m68000/m68kfpu.cpp
Backports some Bochs SoftFPU code. That implements x87 FPATAN, but I believe that can do fractional atan, so one plus the single argument from FATAN should map the semantics. I'm not sure which argument order is correct though.
I wrote this because xeyes on Domain/OS needs it, but it seems like a lot of Mac media software wants it too.
Related to #8157
> Implement 68k FPU FATAN instruction

- src/mame/drivers/cave.cpp
- src/mame/includes/cave.h
Per the comments on b0808b247bec25494128e49ecd057475ffff0c2e, this adds an additional "Bet 12" button connected to both the "Bet 4" and "Bet 8" inputs, to match how the real machine seemingly does it.
> cave.cpp: add Bet 12 button to paccarn

- hash/snes.xml
- mk2u is identical to mk2ua when it should be a revision, not simply a split ROM. Replace with correct dump.
- mk3p1 is identical to mk3up, and there's no evidence of two protos from the same day on different hardware. Keep documented board, remove duplicate.
> snes.xml: replace a bad dump, remove a duplicate

- hash/fmtowns_flop_orig.xml
- Replaced rance, rance2 and toshinto with cleaner images (fewer save files modified) [cyo.the.vile]
- Verified drstop, rance and rance2 as correct dumps from original disks and moved them to fmtowns_flop_orig.xml [cyo.the.vile]
- Renamed dpssg2 and dpssg3 in fmtowns_flop_misc.xml as alternate versions with slight differences
Ayumi-chan Monogatari Hint Disk [cyo.the.vile]
D.P.S SG 2 - Dream Program System SG Set 2 [cyo.the.vile]
D.P.S SG 3 - Dream Program System SG Set 3 [cyo.the.vile]
Dr. Stop! [cyo.the.vile]
Kakeibo + Fukubukuro - Wagaya no Benrichou Vol. 1 [cyo.the.vile]
Rance - Hikari o Motomete [cyo.the.vile]
Rance 2 - Hangyaku no Shoujo-tachi [cyo.the.vile]
Rance 2 …
> fmtowns_flop_*.xml: 13 new dumps, AliceSoft replacements and cleanups

- hash/gameboy.xml
- hash/gbcolor.xml
The most recent revisions were (mostly) made the parent sets but were not given the shorter canonical set name. This is prone to error—for instance redarrem was a clone of gargoyle but neither was a clone of the most recent revision gargoylea.
> gameboy.xml, gbcolor.xml: fix some parent/clone relationships/naming

- src/devices/video/upd7220.cpp
When rendering the pattern in pram[8]-pram[15] the gchrd command should always start with pram[15]. Currently it will start at pram[8+n], where n is the height of your fill area. This works fine when the height is a multiple of 8, but otherwise the wrong bytes of the pattern buffer are accessed.
This fixes some display bugs on the QX-10 system when using mfbasic.com
> upd7220: During a GCHRD command always start with pram[15]

- src/mame/drivers/qx10.cpp
This fixes the qx-10 emulation so it will display the proper colors when configured for color video
> qx10: Fix color video mode to display proper colors

- src/mame/drivers/lwriter.cpp
This appears to be the desired effect of the code using this range.
It fixes the rasterization of the '5' glyph in the test page and avoids
the "Fatal system error @ 0x2a8416" buffer overflow in glyph the cache
when writting out the last byte of the bitmap because it ends up or'ing
with zero instead of overwritting with zero.
Fixes #8309
> lwriter.cpp: Reimplement the 0x600000-0x7fffff range to bitwise-OR on write.

- src/mame/drivers/mcr.cpp
Recently had a board sent to me with dates not found in MAME for tapper. After reading in the EPROMS, the data matched the tapperb set.  Updated the code with the dates found on the EPROMs.
Let me know if you'd like to have the EPROMs renamed to match the others. If so, I believe they should be:
tapper_c.p.u._pg_0_1c_1-12-84.1c
tapper_c.p.u._pg_1_2c_1-12-84.2c
tapper_c.p.u._pg_2_3c_1-12-84.3c
tapper_c.p.u._pg_3_4c_1-12-84.4c
> tapperb eprom update

- hash/nes.xml
- src/devices/bus/nes/bootleg.cpp
- src/devices/bus/nes/bootleg.h
- Corrected IRQ behavior. Fixes almost all flickering on status bar divider line.
- Corrected various minor details that don't affect emulation but are accurate to PCB.
- PRG ROM is on two DIPs. Split image to reflect that.
> bus/nes: Improved emulation of a SMB3 bootleg.

- hash/apple2_flop_orig.xml
Stickybear Math 2 (1988 Re-release) (800K 3.5") [4am, Firehawke]
Stickybear Opposites (1989 Re-release) (800K 3.5") [4am, Firehawke]
Stickybear Town Builder (1988 Re-release) (800K 3.5") [4am, Firehawke]
Stickybear Typing (1988 Re-release) (800K 3.5") [4am, Firehawke]
Spelling Rules (1989 Re-release) (800K 3.5") [4am, Firehawke]
Sentence Fun (1989 Re-release) (800K 3.5") [4am, Firehawke]
Alge-Blaster Plus! (Version 1.0) (800K 3.5") [4am, Firehawke]
Mickey's Crossword Puzzle Maker (800K 3.5") [4am, Firehawke]
> Final batch of Apple disks for July 2021

- hash/ibm5170.xml
Caldera OpenDOS 7.01 (3.5" 1.44MB) [archive.org]
Caldera OpenDOS 7.01 (3.5" 720KB) [archive.org]
Caldera OpenDOS 7.01 (5.25" 1.2MB) [archive.org]
Caldera OpenDOS Lite 7.01 (3.5" 1.44MB) [archive.org]
Caldera OpenDOS Lite 7.01 (3.5" 720KB) [archive.org]
Caldera OpenDOS Lite 7.01 (5.25" 1.2MB) [archive.org]
DR DOS 6.0 [archive.org]
DR DOS 7.03 [archive.org]
DR DOS Lite 7.03 [archive.org]
OS/2 Black Jack [archive.org]
OS/2 Poker [archive.org]
OS/2 Warp [archive.org]
OS/2 Warp 3 FixPak XR_W040 [archive.org]
OS/2 Warp Connect with Win-OS/2 [archive.org]
OS/2 Warp with Win-OS/2 [archive.org]
Windows NT 3.1 Workstation (3.10.511.1) [WinWorld]
Windows NT 3.1 Workstation (3.10.511.1) [3.5" floppy] [WinWorld]
Windows NT 3.51 …
> ibm5170: new software lists additions

- hash/ibm5170_cdrom.xml
Caldera OpenDOS Machine Readable Source Kit (M.R.S) 7.01 [archive.org, Davide Cavalca]
IBM AttachPak for OS/2 Warp Connect [archive.org]
IBM DEMOpkg for OS2 - First Edition 99Q3 [archive.org]
Lotus Notes Express v3.30 for OS2, Special Promotion Copy NFR [archive.org]
Lotus SmartSuite for OS/2 Warp 4 [archive.org]
OS/2 Warp [archive.org]
OS/2 Warp Connect with Win-OS/2 [archive.org]
OS/2 Warp Special CD - november 1995 [archive.org, Davide Cavalca]
OS/2 Warp with Win-OS/2 [archive.org]
PC DOS 7 [archive.org]
Windows NT 3.1 Workstation (3.10.511.1) [WinWorld]
Windows NT 3.51 Workstation (3.51.1057.1) [WinWorld]
> ibm5170_cdrom: new software list additions

- hash/nes.xml
- Added new parent smb2fds from verified LF36 cart.
- Old mistaken LF36 corrected to its known PCB label YS-612 (smb2lf renamed smb2fdsd).
- Old parent set renamed smb2fdsf (and maybe is a candidate for future removal).
- Replaced known bad dump of smb2fdsc (TONY-I).
- Removed mrmary2 multicart extract in favor of its source 4-in-1 multicart.
- Promoted vballfds since it doesn't use the IRQ causing trouble in the related smb2fdse.
Exciting Soccer - Konami Cup (Asia, FDS conversion) [famiac]
Super Mario Bros. 2 (LF36) [krzysiobal, NewRisingSun]
Super Mario Bros. 2 (TONY-I) [krzysiobal, NewRisingSun]
Volleyball (Asia, FDS conversion)
New …
> nes.xml: SMB2 FDS bootleg (and related PCB) additions/clean-up.

- hash/nes.xml
- src/devices/bus/nes/multigame.cpp
- src/devices/bus/nes/multigame.h
- src/devices/bus/nes/nes_carts.cpp
- src/devices/bus/nes/nes_ines.hxx
- src/devices/bus/nes/nes_pcb.hxx
- src/devices/bus/nes/nes_slot.h
- src/devices/bus/nes/nes_unif.hxx
- Renamed Elfland 200-in-1's device with bmc- prefixes to be consistent with related multicarts. Promoted to working since everything is in working order.
- Throw in Elfland singleton cart since it's been separately dumped.
72 in 1 Cartridge Story [MLX]
80 in 1 Cartridge Story (II) [Yahweasel]
90 in 1 Cartridge Story (III) [MLX]
Elfland [NewRisingSun]
200 in 1 - Elfland
> bus/nes: Added support for Cartridge Story multicarts.

- hash/c64_cass.xml
This pull request fixes some invalid software list filenames for some of the new clones added in my earlier c64_cass.xml pull requests.
> c64_cass.xml: Correct some invalid software list filename entries

- src/mame/video/gime.cpp
Force constant RAM at $FEXX does not override ROM settings. This fixes the splash screen in Demon Attack.
> coco3: adjust $FEXX constant RAM setting 

- src/mame/video/gime.cpp
Pop*Star pilot exposed a problem with the timer delay calculations.
> coco3: timer calculation wrong by a factor of 2

- src/mame/machine/n64.cpp
- src/mame/video/n64.cpp
- src/mame/video/n64.h
- src/mame/video/rdptpipe.cpp
-n64: Various RDP and VI changes. [Ryan Holtz, krom]
* Fixed handling of 8bpp framebuffer mode.
* Adjusted how VI scan-out functions.
* Swapped 'magic matrix' dither pattern axes to match hardware tests.
> N64 video adjustments: 8bpp mode, VI scan-out improvement

- src/mame/drivers/qx10.cpp
Update: Dropped second patch as I now have a better and more complete implementation of the the upd7220 draw_char routine. 
Reduces the QX10 video memoy allocation to 128k instead of 256k and setups mirroring in the memory map.
With these patches the following mfbasic program now works properly.
```
10 print "Hello World!"
20 goto 10
```
Also running the diag disk in color mode now sucessfully works on the final scrolling text test.
> QX10 fix graphics scrolling

- src/lib/formats/imd_dsk.cpp
Incorrect cell size for FM track results in empty bitstream that ultimately causes data.empty() to seg fault.
> imd_dsk.cpp: Fix segmentation fault saving FM track

- src/tools/chdman.cpp
Add some more entries to the hard disk templates list. This is split out of https://github.com/mamedev/mame/pull/7155
> chdman: add a few more hard disk templates

- src/mame/drivers/lwriter.cpp
This dramatically improves serial output speed, which I believe
was limping along off the timer interrupt. It also fixes serial output
on channel B as well as with the ROM for the original LaserWriter.
Further, it better matches the 0x60 that VIA_PCR is set to which has
CA1 latch/interrupt control set to "Negative active edge".
> lwriter.cpp: Invert the state of the SCC interrupt

- src/devices/machine/smc91c9x.cpp
- src/devices/machine/smc91c9x.h
1. m_loopback_result needs to be a signed int so negative results remain negative.
2. FDSE bit was masked out
3. when Full Duplex Switched Ethernet is active, deferral and collision logic is not in effect
4. implement AUTO_RELEASE mode
The receive collision detection seems problematic to me.  If it were a real hardware on a real half-duplex network, the sender would detect the collision and resend, AIUI. Currently, the 91c9x discards the packet and it will never be resent.
> smc91c96 updates ( apple2e, a2osx w/ lancegs)

- hash/nes.xml
- CRC match of the game can be found in at least one multicart, mc_52gam. Extracted game crashes when reset since it tries to return to the multicart menu.
> nes.xml: Removed fancybro multicart extract.

- hash/nes.xml
- Replaced smb10 and smario14 with cart redumps. Previous dumps were rom hacks to allow the games to work on ancient emulators. [NewRisingSun]
- Likewise removed rom hack smb11a. smb11 is the proper pirate MMC3-variant dump, so it is retained.
- Hooked up heromali to correct slot device. Works now.
- Hooked smb4 up to correct slot. Works now as well.
- Bonus: hooked magicblks up to a proper slot device. Fixes graphics.
The Ancient Modern Heros [NewRisingSun]
Super Mari - Mali Lugi - Mari no Daisakusen 2 [NewRisingSun]
Super Mario Bros. IV (Armadillo pirate)
> nes.xml: Two redumps, two new dumps, one dump removed.

- src/devices/bus/compis/hrg.cpp
- src/devices/bus/isa/num9rev.cpp
- src/devices/video/upd7220.cpp
- src/devices/video/upd7220.h
- src/mame/drivers/a5105.cpp
- src/mame/drivers/dmv.cpp
- src/mame/drivers/hhtiger.cpp
- src/mame/drivers/if800.cpp
- src/mame/drivers/mz6500.cpp
- src/mame/drivers/qx10.cpp
- src/mame/drivers/rainbow.cpp
- src/mame/drivers/vt240.cpp
- src/mame/video/mikromik.cpp
- src/mame/video/pc9801.cpp
These patches fix some issue in the implementation of the upd7220 GPU.
1. The first patch fixes the adress space to use a -1 address shift so that is actually word adressable. Without this the total amount of memory addressable was only 256k but the actually device should be able to address 512k of memory. In addition this cleans up memory accesses since we no longer need to multiple every address by 2 to get the correct word access.
2. This patch does a proper implementation of the GCHRD command using the ead/dad/mask as specified via the datasheet. This is ncessary since the previous implementation did not use the mask properly which was preventing the screen clearing routines on the QX-10 from working properly.
Tests ran:
QX-10: diag disk in color mode. (Works)
compis: bildspel.cmd …
> Upd7220 area fill rework

- src/mame/drivers/lwriter.cpp
- src/mame/mame.lst
To make this ROM work we need to initialize VIA CA1 to
1 so that we don't miss the first serial interrupt.
> lwriter.cpp: Add support for LaserWriter Plus ROM

- src/mame/audio/wiping.cpp
- src/mame/drivers/clshroad.cpp
- src/mame/drivers/wiping.cpp
- src/mame/includes/clshroad.h
- src/mame/video/clshroad.cpp
clshroad.cpp: Add tilemap color bank, fix lightning flashing and color cycling for Fire Battle;
clshroad.cpp: Hand-tuned all clock frequencies for clshroad and halved vblank irq rate, syncing video and sound timings in logical sense;
clshroad.cpp, wiping.cpp: Convert to Xtal and add tentative screen raw params;
audio/wiping.cpp: Make custom audio to actually not divide internally by 2;
> clshroad.cpp: various fixes

- hash/c64_cass.xml
Bad Cat (Go!) [C64 Ultimate Tape Archive V2.0]
Bad Dudes Vs. Dragon Ninja (Imagine) [C64 Ultimate Tape Archive V2.0]
Bad Dudes Vs. Dragon Ninja (Erbe) [C64 Ultimate Tape Archive V2.0]
Bangkok Knights (Activision) [C64 Ultimate Tape Archive V2.0]
Basket Master (Imagine) [C64 Ultimate Tape Archive V2.0]
As discussed on my earlier PR #8331, this follow up PR contains a small number of new software list entries with the intent of raising standards going forward.
My proposal to improve standards considers the following:
1. software name / rom name keeping to the 8.3 / 16.3 filename formats for consistency
2. software name / rom name all lowercase letters and no use of spaces
3. description, publisher, release year, …
> c64_cass.xml: Proposal for raising standard of software list files

- hash/amiga_workbench.xml
AmigaOS 3.1.4 [Davide Cavalca]
AmigaOS 3.1.4.1 (Update) [Davide Cavalca]
AmigaOS 3.2 [Davide Cavalca]
AmigaOS 3.2 (3.5" floppies) [Davide Cavalca]
AmigaOS 3.9 [archive.org]
AmigaOS 4.0 Classic [fsck.technology]
AmigaOS 4.1 Final Edition for Classic [Davide Cavalca]
> amiga_workbench: new software list additions

- src/devices/bus/centronics/epson_lx810l.cpp
- src/devices/bus/centronics/epson_lx810l.h
- src/devices/machine/e05a30.cpp
- src/devices/machine/e05a30.h
ap2000 is reset when the maincpu is reset, and then gets an NMI signal a short while later (0.9 seconds minimum).
This adds printer reset from the keyboard and hooks up centronics init signal
> Adding reset to ap2000, hooking up centronics init signal

- hash/nes.xml
- Hooked clones up to an appropriate cart device. Fixes in-game graphics.
- Removed magicarps2 which was an identical dump to magicarps1.
> nes.xml: Fixes for Magic Carpet clones.

- hash/nes.xml
- src/devices/bus/nes/pirate.cpp
- src/devices/bus/nes/pirate.h
- Graphics issues were in sets mihunche, mihunchea, and scche.
- Separately, demoted several non-working games to not supported.
> bus/nes: Fixed graphics issues in BB Car clones.

- src/mame/drivers/missbamby.cpp
Found the Cirsa Lucky Player technical manual. The game (Cirsa 810702 PCB) indeed uses a 8155.
> missbamby.cpp: Remove uneeded comment

- hash/nes.xml
Sonic & Knuckles 5 (Asia)
Street Fighter II - The World Warrior (Asia)
Street Fighter II - The World Warrior (Asia, Alt)
Street Fighter II - The World Warrior (Asia, Alt 2)
Ultimate Mortal Kombat 4 (Asia)
> nes.xml: Set correct board type for several pirate games.

- src/devices/video/upd7220.cpp
- src/devices/video/upd7220.h
This patchset fixes the FIGD drawing to use m_ead/m_mask instead of an x/y cordinate system. This patchset, mutch like my previous one for teh GCHRD command, makes the FIGD command behave as it would on a real upd7220. It also fixes up the inital values for FIGS which did not match what was specified in the datasheet.
Tested on the following systems with no noticable regressions: qx10, compis, dmv, pc-98, vt240, rainbow
> video/upd7220: Update FIGD to use ead and mask to calculate drawing location

- src/devices/cpu/g65816/g65816ds.cpp
- src/mame/machine/apple2common.cpp
- JSL support for gs/os & prodos 16 calls
- JSL/JML/STA named address support
- inline debug name support (Apple IIgs Tech Note 103)
- use lowercase mnemonics and registers in the disassembly to be consistent with 6502 family and override mnemonics
Before:
After:
> apple2gs disassembler tweaks

- src/mame/machine/6883sam.cpp
- src/mame/video/gime.cpp
This reverts PR #8364 (commit 6ee768c205ba9a70d4790a6667c6bda2eed0aec5). It turns out it was correct the first time.
I also am adding some logging I used to verify this.
> coco3: Revert constant RAM fix.

- src/lib/util/zippath.cpp
Choosing the root path in the ui (on the SDL platforms) would cause an "Error accessing '/'" problem. This fixes this it.
I have also done full testing in Windows to be sure this doesn't break that operating system.
> sdl ui: fix choosing the root path

- hash/megadriv.xml
- This multicart doesn't fully work because it's a bad dump--the second 2MB is missing and is a repeat of the first half. New checksums are for the first 2MB.
> megadriv.xml: Replaced dump for s19in1.

- hash/nes.xml
- src/devices/bus/nes/nes_ines.hxx
- src/devices/bus/nes/rcm.cpp
- src/devices/bus/nes/rcm.h
- Got boards gs2004 and gs2013 working and merged them into related classes (they differ solely by a fixed bank number).
- Simplified tf9in1 board and fixed its graphics issues (sets mc_20a, mc_tf9).
Tetris Family 5 in 1 [NewRisingSun]
Tetris Family 6 in 1 (GS-2004)
Tetris Family 12 in 1 (GS-2013)
> bus/nes: Improved support for various RCM multicarts.

- src/devices/bus/nes/bootleg.cpp
- src/devices/bus/nes/bootleg.h
Replaced IRQ hold line semantics with proper set/clear and otherwise cleaned up code based on most recent info on these bootlegs.
> bus/nes: Updates for three SMB2FDS bootleg board types.

- src/devices/bus/nes/sunsoft.cpp
- src/devices/bus/nes/sunsoft.h
IRQs now cleared in the correct place, simplified the code a bit, and added exact bank-size masks based on pin counts.
> bus/nes: Slightly more accurate Sunsoft 3 boards.

- src/mame/drivers/vsmileb.cpp
-vsmileb: Added default input mappings for the slider window on the controller. Demoted to MNW due to audio issues with narration, and the critical nature of working audio for a toddler-oriented system. [Ryan Holtz]
> Updates to V.Smile Baby driver (inputs + demotion)

- src/osd/modules/debugger/debuggdbstub.cpp
The `m_readbuf_state` variable's default value in `gdbstub` is uninitialized. Depending on the compiler, this can result to debugger not working.
> fix m_readbuf_state being in undefined state

- src/lib/formats/wd177x_dsk.cpp
Prevents further evaluation of incompatible formats.
> wd177x_dsk.cpp: Add head count check

- src/mame/drivers/agat.cpp
- src/mame/drivers/apple2.cpp
- src/mame/drivers/apple2e.cpp
- src/mame/drivers/apple2gs.cpp
This fix reproduces some usually undesirable behavior with the game I/O port. The way an Apple II analog input (joystick or paddle) works is the potentiometer in the controller becomes part of a 555-style monostable timer circuit on the motherboard (the actual chip is a 558 quad timer). A timer start running when the game port is strobed. The more resistance supplied by a potentiometer, the longer a timer runs. When a timer expires, its output is asserted. By continuously polling an output in software, the elapsed time is measured, yielding a controller position.
There are a couple of subtleties to this circuit. First, when a timer is started, it cannot be restarted until it expires. Second, all of the timers use a common strobe signal. If you want to read a two-axis joystick this can get …
> fixed one-shot paddle timers in Apple II and clones

- src/osd/modules/render/bgfx/target.cpp
D24 maps to VK_FORMAT_D24_UNORM_S8_UINT which is not supported on AMD hardware:
https://bugs.freedesktop.org/show_bug.cgi?id=106528#c6
https://github.com/KhronosGroup/MoltenVK/issues/888#issuecomment-635014600
> Use D32F texture format instead of D24

- src/mame/drivers/toaplan1.cpp
- src/mame/drivers/twincobr.cpp
- src/mame/drivers/wardner.cpp
- src/mame/includes/toaplan1.h
- src/mame/includes/twincobr.h
- src/mame/video/toaplan1.cpp
- src/mame/video/toaplan_scu.cpp
- src/mame/video/toaplan_scu.h
- src/mame/video/twincobr.cpp
Use device specific delegate for priority mask
Use device_video_interface for screen interface
Add/Fix notes
Remove unnecessary functions and values
toaplan1.cpp, twincobr.cpp: Add notes
> toaplan_scu.cpp: Use single pass pdrawgfx for sprite vs tilemap priority

- src/devices/machine/fdc37c665gt.cpp
There are 2 possible address slots per serial port which are configurable through the configuration register. The addresses in the `com_addresses` array are also configurable, so for the serial ports only I stored the selected address index in the device addresses array instead of the actual address value. I forgot about that when I reimplemented this code a few months back so the read/write functions have been working based on the selected address index instead of the actual selected address.
> fdc37c665gt: Fix serial 1/2 address usages

- src/mame/drivers/atarisy1.cpp
This change reduces audio volume in atarisy1.cpp to avoid clipping in indytemp that occurs when speech is playing.
> atarisy1.cpp: Fix overdriven sound

- src/mame/drivers/namcos2.cpp
- src/mame/drivers/spg2xx.cpp
- src/mame/drivers/spg2xx_jakks.cpp
- src/mame/includes/namcos2.h
- src/mame/mame.lst
------
SpongeBob SquarePants Jellyfish Dodge (JAKKS Pacific TV Game) (Apr 5 2007) [Sean Riddle, David Haywood]
------
Dora the Explorer - Doras Abenteuer-Globus (Germany) [Sean Riddle, TeamEurope]
-namcos2.cpp : made Japanese Marvel Land the parent, the US prototype is an earlier incomplete build, it ends abruptly, lacks any end credits, and is missing many of the levels (plus various other incomplete elements, see https://tcrf.net/Marvel_Land_(Arcade) ) 'US' could also be 'World' but I haven't changed that.
> new WORKING machines (Plug + Play) also reparented marvland as current parent is a very early incomplete build.

- hash/saturn.xml
corrected the description of the "zico" set to "Isto é Zico - Zico no Kangaeru Soccer (Jpn)"
Source: https://segaretro.org/Isto_%C3%A9_Zico:_Zico_no_Kangaeru_Soccer
> saturn.xml: update "zico" set description

- src/mame/audio/segam1audio.cpp
This change adjusts the audio level in Sega Model1 and Model2 games to avoid overdriven audio.
> segam1audio.cpp: Fix overdriven sound

- hash/nes.xml
- Removed a "fixed" version of quanhr2, now that parent is working.
Quánhuáng R-2 - Dàshé Sìtiānwáng
Yǒngzhě Chuánshuō
Wángzhě Wúshuāng
> nes.xml: Set correct board type for several games.

- hash/nes.xml
- src/devices/bus/nes/multigame.cpp
- src/devices/bus/nes/multigame.h
- Fixed games not loading in mc_6et40 and mc_11a42 and graphics issues with several games across the nine cartridges represented here.
11 in 1 (A-042) [anonymous]
1994 Super HiK 6 in 1 (A-017) [anonymous]
> bus/nes: Improved emulation for T-262 board and related multicarts.

- hash/nes.xml
- Beyond metadata this gives aressha WRAM, making it playable now.
- Separately, demoted Enix games dquest and doordoor due to game crashing bugs.
> nes.xml: Updated PCB details for A Ressha de Ikou.

- src/mame/drivers/psikyo.cpp
This change adjusts the audio level in gunbird to avoid overdriven sound output.
> psikyo.cpp: Fix overdriven sound in gunbird

- hash/nes.xml
- src/devices/bus/nes/multigame.cpp
- src/devices/bus/nes/multigame.h
- src/devices/bus/nes/nes_carts.cpp
- src/devices/bus/nes/nes_ines.hxx
- src/devices/bus/nes/nes_pcb.hxx
- src/devices/bus/nes/nes_unif.hxx
- Fixed graphics glitches in the following boards: BMC-20IN1 (Kaiser 20 in 1), BMC-SUPER700IN1 (700 in 1, 190 in 1), BMC-VT5201 (six multicarts).
- Simplified BMC-21IN1 board (21 in 1, 8 in 1).
Super 190 in 1 [anonymous]
> bus/nes: More fixes for various multicart types.

- scripts/target/mame/tiny.lua
- src/emu/devdelegate.h
- src/emu/device.h
- src/emu/emumem.h
- src/emu/gamedrv.h
- src/emu/save.h
- src/lib/util/delegate.cpp
- src/lib/util/delegate.h
If a delegate is set to a functoid (e.g. a lambda) with a signature that is an exact match for the delegate's signature, it will be bound directly.  If arguments or the return value need conversion, a static adaptor will be generated.  This removes unnecessary indirection through the out-of-line `std::function::operator()`.
There’s no flexibility lost, you can still be a bit sloppy with lambda signatures, but it means if you’re strict with your lambda signatures, one small performance penalty is removed.  You still have an extra level of indirection through the captured `this` pointer when accessing members, but that’s not as bad as the flow control indirection.
> -util/delegate.cpp: One less level of indirection for functoid delegates.

- src/mame/video/gime.cpp
If a master interrupt switch is turned off, the interrupt will un-assert.
> coco3: fix GIME master interrupt switches

- makefile
It is not supported by gcc on this architecture.
This worked prior to 6e1bbe8
> Do not build with -m64 on riscv64

- src/lib/util/delegate.cpp
- src/lib/util/delegate.h
* Fixed `this` pointer displacement being reapplied after delegates are copied – caused issues with classes with multiple inheritance.  Each time you assigned or copied a delegate containing a member function pointer with a non-zero `this` pointer displacement, the `this` pointer would walk into the weeds a bit more.  This did not affect “compatible” delegates, only the optimised versions.
* Made null member function pointer test conformant with Itanium C++ ABI specification.  The specification only requires that the pointer be a null function pointer for the “standard” variant, or that the pointer be a null function pointer and the least significant bit of the `this` pointer displacement be clear.  Previously, the pointer and entire `this` pointer displacement were being compared to …
> util/delegate.cpp: Fixed multiple issues

- src/mame/drivers/segahang.cpp
- src/mame/includes/segahang.h
- The MCU for the sharrier1 set is handcrafted and marked BAD_DUMP
- There is a slight issue with the initial synchronisation, so there is a hack to ignore the problematic write
> sharrier: Hook up MCU, remove simulation

- hash/fmtowns_flop_misc.xml
- hash/fmtowns_flop_orig.xml
- Renamed the Houma Hunter Lime entries to be more accurate to the disk labels
- fmtowns_flop_misc.xml: marked dpssg2, dpssg3, hhunt01, hhunt02, hhunt03 and superdps as alternate versions of the ones in the original list
- fmtowns_flop_misc.xml: removed duplicate entries that have been moved to the original list (drstop, rance, rance2) and were left here by mistake in the last update
Houma Hunter Lime Dai-1-wa [cyo.the.vile]
Houma Hunter Lime Dai-2-wa [cyo.the.vile]
Houma Hunter Lime Dai-3-wa [cyo.the.vile]
Kitty World 2 [cyo.the.vile]
Metal Eye Special Disk [r09]
Sadistic Gamers Part-3 - Telephone Play [cyo.the.vile]
Sadistic Gamers Part-5 - Burusera Play [cyo.the.vile]
> fmtowns_flop_*.xml: 7 new dumps, misc list cleanups

- hash/fmtowns_cd.xml
- Added the missing floppy disk to amarant3 [akira_2020]
- Added the missing floppy disk to hypnote [cyo.the.vile]
- Added the Planet's Edge bonus audio CD [redump.org]
- Removed the floppy part_id from uwaki, as it's not part of the floppy label
CRI Postman [redump.org]
Dynamic English 3 - Upper Basic [redump.org, cyo.the.vile]
FM Towns Shougaku Ongaku (5-6-nensei-you) [redump.org, cyo.the.vile]
Hyper Aquarium - Kaisui-hen [redump.org]
Hyper Aquarium - Tansui-hen [redump.org]
Hyper Eigo Gakushuu System - New Crown Series 1 [redump.org]
Igo Doujou Yaburi - Menkyo Kaiden!! Mezase 7-kyuu [redump.org]
J.League 1994 Professional Soccer [redump.org]
Master CD - Fresh Series-you [redump.org]
Meikyoku Master (FM Towns Marty …
> fmtowns_cd.xml: 16 new dumps, 7 replacements, add missing floppies

- src/lib/formats/sc3000_bit.cpp
Much of the SC-3000 tape software library cannot be encoded with the .bit format, while it can be easily encoded using tzx. Problem discussed here.
https://www.smspower.org/forums/15470-SC3000TapeSoftwareRestorationProject
> added tzx to the sc-3000 formats

- hash/saturn.xml
- src/devices/machine/smpc.cpp
- src/devices/machine/stvcd.cpp
- src/mame/drivers/saturn.cpp
- src/mame/mame.lst
- stvcd.cpp: guard against deleting partial sectors in cmd_delete_sector_data, fixes pstarcol Phantasy Star 2 crash after first attract cycle;
- smpc.cpp: NMI is unconditionally requested for screen clock change commands, fixes booting in bigichig, capgen1, capgen4, capgen5;
- stvcd.cpp: add fixed status for NetLink, allow dragndrm to actually boot (with -nodrc);
> saturn.cpp: Add Korean BIOS placeholder

- hash/nes.xml
- src/devices/bus/nes/mmc3.cpp
- Fixes most graphics glitches in Rad Racer II and unlicensed Jurassic Boy 2, Rocman X carts.
> bus/nes: Fixed hardwired 4-screen mirroring for MMC3 games.

- src/mame/video/kikikai.cpp
Bubble Bobble runs on bublbobl.cpp driver, not here.
> kikikai.cpp: Fix notes

- hash/nes.xml
- src/devices/bus/nes/mmc1.cpp
- src/devices/bus/nes/mmc1.h
- src/devices/bus/nes/nes_carts.cpp
- src/devices/bus/nes/nes_ines.hxx
- src/devices/bus/nes/nes_pcb.hxx
- src/devices/bus/nes/nes_slot.cpp
- src/devices/bus/nes/nes_slot.h
- Removed pseudo board types SXROM_A and SOROM_A that are simply SXROM and SOROM boards fitted with MMC1A chips.
- Provide the equivalent behavior directly in SXROM and SOROM by letting each board know which MMC1 type it has from the existing feature in the softlist.
> bus/nes: Simplified handling of SxROM + MMC1A boards a bit.

- hash/nes.xml
- src/devices/bus/nes/event.h
- src/devices/bus/nes/mmc3_clones.cpp
- src/devices/bus/nes/mmc3_clones.h
- src/devices/bus/nes/multigame.cpp
- src/devices/bus/nes/multigame.h
- src/devices/bus/nes/nes_ines.hxx
- src/devices/bus/nes/pirate.cpp
- Reimplemented these related boards as class/subclass.
- Corrected missing iNES loader support.
35 in 1 (HM5511) [anonymous]
68 in 1 (HM5511) [anonymous]
15 in 1
3 in 1
70 in 1
76 in 1 (alt games)
800 in 1
> bus/nes: Updates for BMC-70IN1 and BMC-800IN1 boards.

- hash/famicom_flop.xml
- hash/nes.hsi
- hash/nes.xml
- src/devices/bus/nes/multigame.cpp
- Updated support status of various NES/FDS titles.
- Fixed loading of mc_76a outside of software lists.
1000 in 1 (alt games) [NewRisingSun]
> nes.xml: Added a missing game from recent N625092 board improvements.

- hash/c64_cass.xml
Batman (Ocean) [C64 Ultimate Tape Archive V2.0]
Battle Through Time (Anirog) [C64 Ultimate Tape Archive V2.0]
Beach-Head II (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Beach-Head II (Erbe) [C64 Ultimate Tape Archive V2.0]
Best of Elite: Vol. 1 (Elite Systems) [C64 Ultimate Tape Archive V2.0]
Best of Elite: Vol. 2 (Elite Systems) [C64 Ultimate Tape Archive V2.0]
Beyond the Forbidden Forest (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Beyond the Ice Palace (Elite Systems) [C64 Ultimate Tape Archive V2.0]
Biff (Beyond Belief Software) [C64 Ultimate Tape Archive V2.0]
Big Names Bonanza (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Bazooka …
> c64_cass.xml: 11 new dumps

- src/mame/machine/amstrad.cpp
This reverts commit 2bc0a7ab939b4ac49a7fb533e96354773fa232e2.
> Revert "amstrad: fix spelling/grammar in the comments (#8647)"

- src/devices/bus/nes/nes_carts.cpp
- src/devices/bus/nes/nes_ines.hxx
- src/devices/bus/nes/nes_pcb.hxx
- src/devices/bus/nes/nes_slot.h
- src/devices/bus/nes/sealie.cpp
- src/devices/bus/nes/sealie.h
- Enabled support for NES 2.0 PRG chunks >= 64MB and CHR chunks >= 32MB.
> bus/nes: Added emulation for A Winner is You homebrew cart.

- src/mame/drivers/tmspoker.cpp
- src/mame/mame.lst
Las Vegas (Jeutel, set 1) [Benjamin Roux, ClawGrip]
Las Vegas (Jeutel, set 2) [Benjamin Roux, ClawGrip]
Note: I've not added the common ROMs (on the main PCB) as a ROM_SYSTEM_BIOS because I don't know if it can be considered as a BIOS. We found three PCBs and two different game carts, two of them with the same ROM as the one already on MAME ('tmspoker'), and the third one with the ROM damaged and unreadable.
> tmspoker.cpp: Add two Jeutel "Las Vegas" sets

- src/mame/machine/6883sam.cpp
add all debug options to template. fix shift count to properly display M bits.
> coco: fix 6883 SAM debugging

- hash/c64_cass.xml
Bigfoot (Codemasters) [C64 Ultimate Tape Archive V2.0]
Bigtop Barney (Interceptor Software) [C64 Ultimate Tape Archive V2.0]
Black Lamp (Firebird) [C64 Ultimate Tape Archive V2.0]
Black Tiger (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Blood Brothers (Prism Leisure) [C64 Ultimate Tape Archive V2.0]
Blue Max (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Blue Max 2001 (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
The Blues Brothers (Titus) [C64 Ultimate Tape Archive V2.0]
BMX Simulator 2 (Codemasters) [C64 Ultimate Tape Archive V2.0]
Bobby Bearing (The Edge) [C64 Ultimate Tape Archive V2.0]
The Boggit: Bored Too (CRL) [C64 Ultimate Tape Archive V2.0]
Bomb Jack (Elite Systems) [C64 Ultimate Tape Archive V2.0]
Bomb …
> c64_cass.xml: 13 new dumps

- src/devices/machine/spg_renderer.cpp
This PR copies the blend level fix that had already been done for sprites in https://github.com/mamedev/mame/commit/d919a1e095674c02679247d751e1c229b2b3e305 to the tile layer implementation. It has also been tested and verified on real hardware (V.Smile with [Disco-Cart](https://github.com/DiscoStarslayer/disco-cart)).
> machine/spg_renderer.cpp: Fix blend level handling for tile layers

- src/devices/bus/centronics/epson_lx810l.cpp
When hitting mame's soft reset (f3), the lx810l/ap2000 will walk the carriage's left most point to the location where the printhead is currently located.  This happens because the home sensor is looking at the stepper's position from get_absolute_position.  Upon reset, it resets itself to zero.  The printhead's position is stored in m_real_cr_pos and it tracks deltas of the absolute position.
Changing the home position sensor to look at m_real_cr_pos fixes this.  Previously, every soft reset walks the carriage leftmost home position to the right.
Also changed Espon -> Epson.
> lx810l: fixes rightward walking carriage on mame soft reset and minor typo

- src/devices/bus/nes/konami.cpp
- src/devices/bus/nes/konami.h
- This eliminates the constant shaking in TMNT2J and Akumajo Special's status bars and full screen shaking in some vertical stages (Clock Tower at least) in Akumajo Densetsu.
> bus/nes: Corrected VRC4/6/7 IRQ pseudo-scanline counter.

- src/devices/bus/nes/konami.cpp
- Fixes several graphics glitches in Wai Wai World.
> bus/nes: VRC2 only supports two mirroring modes.

- hash/nes.xml
- src/devices/bus/nes/mmc3_clones.cpp
- src/devices/bus/nes/mmc3_clones.h
- src/devices/bus/nes/nes_ines.hxx
- Also rename set mc_4scb and make it a clone of one of the new additions.
Super Cool Boy 3 in 1 (ABAB CB-403x) [NewRisingSun]
Super Cool Boy 4 in 1 (CB-4011) [Consolethinks, NewRisingSun]
Super Cool Boy 4 in 1 (CB-4034) [Consolethinks, NewRisingSun]
Super Cool Boy 4 in 1 (CB-4035) [CaH4e3, NewRisingSun]
4 in 1 (JH-274) [anonymous]
1998 HIGH 4 in 1 (YH-463) [anonymous]
4 in 1 (YH-4103) [anonymous]
> bus/nes: Improved support for Super Cool Boy and related multicarts.

- hash/amigaecs_flop.xml
- hash/amigaocs_flop.xml
- src/devices/machine/8364_paula.cpp
- src/devices/machine/8364_paula.h
- src/devices/machine/amigafdc.cpp
- src/devices/machine/mos6526.cpp
- src/mame/drivers/alg.cpp
- src/mame/drivers/amiga.cpp
- src/mame/includes/amiga.h
- src/mame/machine/amiga.cpp
- amiga.cpp: connect missing DSKINDEX signal from FDC to CIA-B ICR bit 4 
- amigafdc.cpp: workaround live_counter > 8 to reset, makes abreed to boot to gameplay;
- amigafdc.cpp: fix DMAON readback, giving logica2 diag BIOS the chance to print extensive floppy test info;
- mos6526.cpp: guard against resetting IRQs when none is chained, makes timer B polling reads to actually work in barb2paln4 which fixes booting;
- 8364_paula.cpp: fix output channel of irq delegation, and throw one when a DMA reaches the end of a stream. Fixes asparmgp/gpmaster BGMs;
- 8364_paula.cpp: avoid reading audio DMA buffers outside the allocated ranges, fixes sound buzzing/aliasing bug (xenon2);
- 8364_paula.cpp: fix DMA reload behaviour (fixes BGMs in Ocean games) add live logging;
- amiga.cpp: ignore bit 0 with …
> First pass in improving Amiga SW compatibility 

- hash/c64_cass.xml
Cosmic Causeway: Trailblazer II (Gremlin Graphics) [C64 Ultimate Tape Archive V2.0]
Crazy Cars (Titus) [C64 Ultimate Tape Archive V2.0]
Crazy Comet (Martech) [C64 Ultimate Tape Archive V2.0]
Crazy Kong (Interceptor Software, alt) [C64 Ultimate Tape Archive V2.0]
Creatures 2: Torture Trouble (Thalamus) [C64 Ultimate Tape Archive V2.0]
Critical Mass (Durell) [C64 Ultimate Tape Archive V2.0]
Crystal Castles (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Crack Down (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Creatures (Thalamus) [C64 Ultimate Tape Archive V2.0]
> c64_cass.xml: Added nine entries

- hash/fmtowns_flop_misc.xml
- hash/fmtowns_flop_orig.xml
- Verified the Futoppara FD Heisei disks as dumped from original disks and moved them to fmtowns_flop_orig.xml [cyo.the.vile]
- Removed the old handcrafted Columns image
Gorby no Pipeline Daisakusen [Katsura82, rockleevk, r09]
Tama CG-shuu - Mai [cyo.the.vile]
New not working software list additions (fmtowns_flop_orig.xml)
Columns [Katsura82, rockleevk, r09]
Musirou - Ongaku Kyoushitsu Ver. 2.0 [cyo.the.vile]
> fmtowns_flop_*.xml: 4 new dumps, verified originals

- hash/sgi_mips.xml
First part of the sgi_mips softlist update with new stuff from jrra.zone.
This (so far) includes the "demos" and "compilers" sections.
corresponding CHD files are [here](https://s3.au.de:8082/md1-stuff/sgi_mips_part1.zip)
I will add more within the next few days, but feel free to merge this PR now
> sgi_mips: new software list additions from jrra.zone

- hash/nes.xml
- src/devices/bus/nes_ctrl/ftrainer.cpp
- Column input reads now shifted to correct bit, fixing reads for top two rows.
- Button presses are correctly 0 bits.
- Multiple rows can be scanned per read.
- Flipped key bindings on mat side A. Now left/right on keyboard actually corresponds to left/right on mat.
> bus/nes_ctrl: Fixed Family Trainer button reads.

- src/devices/machine/gt913_snd.cpp
This just adds slightly more specific logging for two instrument-related commands to make it more clear what the relevant parts of the data registers are. Also adjusts sample addresses to match the actual size of the address space.
> gt913: log two more unknown sound commands

- 3rdparty/genie/build/gmake.linux/genie.make
- 3rdparty/genie/scripts/genie.lua
Compiles GENie with `off_t` defined as a 64-bit integer to assist with building MAME on a 32-bit operating system like Raspberry Pi OS and a storage volume larger than 2 GB.
Without this, the build can fail with a misleading error:
```
[string "premake.fields = {}..."]:82: Can't find matching files for pattern :.../mame/scripts/resources/uwp/assets/*.png
stack traceback:
[C]: in function 'error'
[string "premake.fields = {}..."]:82: in function 'makeabsolute'
[string "premake.fields = {}..."]:76: in function 'makeabsolute'
[string "premake.fields = {}..."]:92: in function <[string "premake.fields = {}..."]:71>
(...tail calls...)
.../mame/scripts/src/main.lua:79: in function 'mainProject'
.../mame/scripts/genie.lua:1566: in main chunk
[C]: in upvalue 'builtin_dofile'
[string "premake = { …
```
> genie: Set _FILE_OFFSET_BITS=64

- hash/c64_cass.xml
Ferrari Formula One (Activision) [C64 Ultimate Tape Archive V2.0]
Fight Night (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Fire Ant (Mogul) [C64 Ultimate Tape Archive V2.0]
Firelord (Hewson Consultants) [C64 Ultimate Tape Archive V2.0]
First Strike (Elite Systems) [C64 Ultimate Tape Archive V2.0]
Fists 'n' Throttles (Elite Systems) [C64 Ultimate Tape Archive V2.0]
Flight Path 737 (Anirog) [C64 Ultimate Tape Archive V2.0]
Flying Feathers (Bubble Bus Software, alt) [C64 Ultimate Tape Archive V2.0]
Flying Shark (Firebird) [C64 Ultimate Tape Archive V2.0]
Football Manager 2 (Addictive Games) [C64 Ultimate Tape Archive V2.0]
Forgotten Worlds (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Fort Apocalypse (U.S. Gold) [C64 …
> c64_cass.xml: Added twenty entries

- hash/sgi_mips.xml
This is part 2 of the new softlist entries from jrra.zone and archive.org. The following was added:
- ImageVision Library 2.5
- Impressario Developer's Kit 1.1 and 1.2
- 3.10 Compiler Maintenance Update for IRIX 4.0.5
- MegaDev 3.0
- RapidApp 1.1
- SCSL Scientific Library Library 1.3
- WorkShop Pro MPF 2.5 w/ Ada Add-On
- MIPSPro 7.2.1 compiler Patches June 1998
- MIPSPro 7.3 and 7.4 Compiler Execution Environment
- ProDev WorkShop 2.5.1, 2.9.1 and 2.9.2
And from archive.org:
- Hot Mix 2 and Hot Mix 3
- IRIX 4.0.5f
- Trusted IRIX /B 4.0.4
The new CHD files are [here](https://s3.au.de:8082/md1-stuff/sgi_mips_part2.zip)
> sgi_mips: Add new softlist entries from jrra.zone and archive.org

- hash/ibm5150.xml
- hash/ibmpcjr_flop.xml
Fixes #8838. [Back cover](https://www.mobygames.com/images/covers/l/31083-touchdown-football-pc-booter-back-cover.jpg) says it requires a PCjr, and apparently won't boot using the ibm5150 driver
> Move Touchdown Football to ibmpcjr_flop

- src/mame/video/powervr2.cpp
The background offset register is calculated not only against the base of texture RAM, but also against the `param_base` register. MAME was only calculating against the base of texture RAM. This appeared to work because the Naomi BIOS and most games use double-buffering with one of the two buffers based at 0x0 in the texture RAM (`param_base` set to 0) and they write the background polygon as their first draw command. However, for code not using the official SEGA libraries the current code can calculate the background offset wrong resulting in an incorrectly drawn background. This is tested against a homebrew program that was run in MAME, Demul and on actual hardware (Rev. H-based multibios, net dimm) with identical results in all three.
I also added a TODO into the section as the …
> [naomi.cpp] Fix the BG Offset 

- src/devices/cpu/tms32031/32031ops.hxx
- src/devices/cpu/tms32031/tms32031.cpp
- src/devices/cpu/tms32031/tms32031.h
- src/mame/audio/cage.cpp
Implement instruction fetch cycle differences between TMS320C3x family DSPs, Add support for low power operation mode
Add infos for RAM block configuration, Not implemented operations
Fix spacing, Reduce duplicates
reference: TMS320VC33 datasheet, User's Guide from Texas Instruments
> tms32031.cpp: Add TMS320VC33 emulation support, Add notes

- src/mame/drivers/hh_sm510.cpp
Removing additional IDs listed for Elektronika Fowling. Images found of the instruction booklet states `IM-16` and haven't found any images of the other IDs on the product or manual.
> hh_sm510: Remove uncertain Fowling IDs

- src/devices/machine/hp_taco.cpp
- src/devices/machine/hp_taco.h
Hi,
this commit adds the capability to write hp9825-format tapes to HP TACO driver (it could already read this format).
Thanks.
--F.Ulivi
> hp_taco: added support for writing hp9825-format tapes

- src/devices/sound/gaelco.cpp
- src/mame/drivers/gaelco.cpp
- src/mame/drivers/gaelco2.cpp
- src/mame/includes/gaelco.h
- src/mame/includes/gaelco2.h
- src/mame/video/gaelco.cpp
- src/mame/video/gaelco2.cpp
CG-1V/GAE1 video/audio fixes
- support y scroll in rowscroll mode
- prevent shadow sprites from corrupting previously drawn shadow sprites
- fix cases of samples not being played where the 2nd chunk addresses are written first
- remove old hack to work around ancient MAME number of colour limits
Other changes to related drivers
- fixed thoop, squash priorities
- added IRQ acks
- set Manaic Square prototype to 1992, and decloned it, I'm told this was an earlier project that was redone from scratch for the released game
- demoted Thunder Hoop to NOT WORKING due to the stage 4 crash.
> CG-1V/GAE1 video/audio fixes

- src/mame/drivers/namcops2.cpp
Ridge Racer V Arcade Battle titlescreen says 2000 and released in November 2000 confirmed from Arcade TV Game List Kokunai - Kaigai Hen (1971 - 2005) at page 54.
https://i.imgur.com/Yoy91h0.jpg
https://i.imgur.com/S6xReZh.png
> Correct Ridge Racer V Arcade Battle year [sjy96525]

- hash/c64_cass.xml
H.E.R.O. (Activision) [C64 Ultimate Tape Archive V2.0]
Hacker (Proein Soft Line) [C64 Ultimate Tape Archive V2.0]
HardBall! (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
HardBall (Compulogical S.A.) [C64 Ultimate Tape Archive V2.0]
Harvey Smith Showjumper (Software Projects) [C64 Ultimate Tape Archive V2.0]
Head Over Heels (Ocean) [C64 Ultimate Tape Archive V2.0]
Heartland (Odin Computer Graphics) [C64 Ultimate Tape Archive V2.0]
Hero Quest (Gremlin Graphics) [C64 Ultimate Tape Archive V2.0]
Herobotix (Prism Leisure) [C64 Ultimate Tape Archive V2.0]
High Frontier (Activision) [C64 Ultimate Tape Archive V2.0]
Hits! Vol 1 (Micropool) [C64 Ultimate Tape Archive V2.0]
The Hobbit (Melbourne House) [C64 Ultimate Tape …
> c64_cass.xml: Added 27 entries

- hash/c64_cass.xml
APB (Domark, alt) [C64 Ultimate Tape Archive V2.0]
The Flintstones (Grandslam) [C64 Ultimate Tape Archive V2.0]
Ghostbusters (Activision) [C64 Ultimate Tape Archive V2.0]
Green Beret (Imagine) [C64 Ultimate Tape Archive V2.0]
In response to MT#08138, I have tested and promoted gberet to working status and added a usage field that explains that the c1541 slot device needs to removed prior to loading.
I have also tested all other entries marked as not working and found both flintstn and ghostbsta also work if the c1541 slot device is removed prior to loading.  These entries have been updated in the same manner as gberet.
I also found apba works regardless of whether the c1541 slot device is removed or not so …
> c64_cass.xml: Promote gberet and other entries to working status (MT#08138)

- src/mame/video/powervr2.cpp
This is a super simple "fix" that adds support for render mode 5 (ARGB0888). I tied the functionality to render mode 6 (ARGB8888) in order to get it to work instead of printing the error message per-pixel. Technically this is incorrect: ARGB0888 fills in the alpha value based on a preset value in a configuration register 0xA05F8048 (which is not implemented in MAME), while ARGB8888 takes the alpha value from the written pixel itself. However, the implementation in MAME for all render modes does not set the alpha value in the resulting framebuffer meaning that ARGB0888 and ARGB8888 are functionally identical according to the current implementation. This doesn't matter in practice because of two reasons: 1) The alpha value is only useful when rendering if you compare against the chroma …
> [naomi.cpp] Add support for render mode 5.

- src/devices/imagedev/midiin.cpp
- src/devices/imagedev/midiin.h
It doesn't really make sense to do this for multitimbral devices.
> midiin_device: don't strip channel number from MIDI file events

- src/mame/drivers/hh_sm510.cpp
- src/mame/mame.lst
This PR renames the Elektronika drivers in `hh_sm510.cpp` to use local Soviet names instead of English export titles (see discussion in #8886).
Marking this PR as a draft until name changes has been agreed upon before renaming ROM files.
> hh_sm510: Rename Elektronika drivers to use local Soviet names

- docs/source/_templates/versions.html
- docs/source/conf.py
- docs/themes/sphinx_rtd_theme/theme.conf
- docs/themes/sphinx_rtd_theme/versions.html
- docs/update.sh
This refactor will prevent updates to the theme from blowing away our changes by using the _template.
The bottom left download links panel will appear when "make html" is run with the environment variable "MAMEDEV" set to anything, and it will not build it into the HTML otherwise.
> Refactor docs build process to use new template and env variable

- src/mame/drivers/dec0.cpp
It's a Fujitsu MB8421 Dual port SRAM.
Since it's a supported device (src/devices/machine/mb8421.cpp), maybe it should be correctly hooked up on the driver.
> dec0.cpp: Correct note about DEM-01 [Caps0ff]

- src/devices/bus/nes_ctrl/ctrl.cpp
- src/devices/bus/nes_ctrl/ctrl.h
- src/devices/bus/nes_ctrl/joypad.cpp
- src/devices/bus/nes_ctrl/joypad.h
- src/mame/machine/nes.cpp
- Removed read_exp call from fcpad2. The FC expansion port is not tied to the relevant line at all.
- Replaced with read_bit2 in the control port interface for the same purpose.
- Separated JOYPAD inputs from MIC. The microphone shouldn't be mixed with button inputs' shift register.
machine/nes.cpp: Also removed read_exp calls on FC control ports. Other than the microphone on fcpad2 nothing used these (nor should they as the only line in common is $4017 bit 0, which in general is never used by the expansion port).
> bus/nes_ctrl: Disentangled Famicom joypad 2 from expansion port code.

- hash/nes.xml
- src/devices/bus/nes_ctrl/ctrl.cpp
- src/devices/bus/nes_ctrl/ctrl.h
- src/devices/bus/nes_ctrl/hori.cpp
- src/devices/bus/nes_ctrl/hori.h
- src/devices/bus/nes_ctrl/joypad.cpp
- src/devices/bus/nes_ctrl/joypad.h
- src/devices/bus/nes_ctrl/pachinko.cpp
- src/devices/bus/nes_ctrl/pachinko.h
- src/devices/bus/nes_ctrl/powerpad.cpp
- src/devices/bus/nes_ctrl/powerpad.h
- src/mame/machine/nes.cpp
- Enforced proper strobe behavior on joypads. Added helper function to controller interface for common pattern.
- Added proper expansion port version of joypad.
- Streamlined pachinko controller by making it an expansion joypad subclass. Moreover, ball launch lever now works correctly!
- Added missing battery-backed WRAM to Pachio-kun 5, game runs now.
- Simplified arcade stick a bit, now also a subclass of the expansion joypad.
- Rewrote Hori Twin and 4 Players adapters. The latter's 4P mode protocol now works. In theory this supports six players simultaneously, though all known games using it have duplicate controls for P1 and P2.
machine/nes.cpp: Removed hack that shifted bit 0 reads to support controller port joypads on expansion port. There shouldn't be any expansion port devices …
> bus/nes_ctrl: Work on Famicom joypads + more separation of EXP port.

- hash/c64_cass.xml
Jack the Nipper (Gremlin Graphics) [C64 Ultimate Tape Archive V2.0]
Jack the Nipper II: In Coconut Capers (Gremlin Graphics) [C64 Ultimate Tape Archive V2.0]
James Bond 007 in The Living Daylights - The Computer Game (Domark) [C64 Ultimate Tape Archive V2.0]
Jinks (Go!) [C64 Ultimate Tape Archive V2.0]
Jon Ritman's Match Day II (Ocean) [C64 Ultimate Tape Archive V2.0]
Juice! (System 3) [C64 Ultimate Tape Archive V2.0]
Jump Jet (Anirog) [C64 Ultimate Tape Archive V2.0]
Jungle Quest (Solar Software) [C64 Ultimate Tape Archive V2.0]
Jungle Quest (Solar Software, alt) [C64 Ultimate Tape Archive V2.0]
Judge Dredd (Melbourne House) [C64 …
> c64_cass.xml: Added 10 entries

- scripts/target/mame/arcade.lua
- src/devices/cpu/mcs51/mcs51.cpp
- src/devices/cpu/mcs51/mcs51.h
- src/devices/sound/gaelco.cpp
- src/devices/sound/gaelco.h
- src/mame/drivers/gaelco.cpp
- src/mame/drivers/gaelco2.cpp
- src/mame/drivers/wrally.cpp
- src/mame/includes/gaelco.h
- src/mame/includes/gaelcrpt.h
- src/mame/includes/wrally.h
- src/mame/machine/gaelcrpt.cpp
- src/mame/machine/gaelcrpt.h
- src/mame/video/gaelco.cpp
Research into thoop and squash 'refresh rate' protection [Victor Fernandez (City Game), Peter Ferrie, David Haywood]
- prevents freeze when dying in stage 4 of Thunder Hoop, and bad text on continue in Squash
Made gaelcrpt a device rather than static (cleaner code for thoop, wrally, squash) [David Haywood]
Save gaelco sound registers properly (prevents bad loops etc. on state load in touchgo) [David Haywood]
Better handling of ds5002fp RNR for touchgo (previously no random numbers were returned) [David Haywood]
> Research into thoop and squash 'refresh rate' protection [Victor Fernandez (City Game), Peter Ferrie, David Haywood]

- src/mame/drivers/ms32.cpp
[Footage of the game](https://www.youtube.com/watch?v=OuR6TjPbg3A) - [attract](https://www.youtube.com/watch?v=OL30cIwp28M)
[Hardware info per Hydregion's comments here.](https://mametesters.org/view.php?id=3523)
> ms32.cpp: Documenting Shutokou Red Zone as undumped

- src/devices/cpu/h8/gt913.cpp
- src/devices/cpu/h8/gt913.h
- src/devices/cpu/h8/gt913.lst
- src/devices/machine/gt913_io.cpp
- src/devices/machine/gt913_snd.cpp
- src/devices/machine/gt913_snd.h
- src/mame/drivers/ctk551.cpp
Reverts mamedev/mame#8960.  Doesn't build at all on Clang.
> Revert "ctk551: implement sound, promote to working"

- src/mame/drivers/pcipc.cpp
440HX and 440TX don't exist. 430HX and 430TX are the actual chipsets being emulated here.
> pcipc.cpp: Fix names of chipsets

- 3rdparty/ymfm/src/ymfm_fm.h
- 3rdparty/ymfm/src/ymfm_fm.ipp
This is an experimental fix to see how it impacts the Konami games, whose music runs too slow. May impact MT08146, MT07078, MT03737.
I'm holding off putting it into mainline ymfm until I get confirmation that this produces the right result in MAME. The music is certainly a bit faster in contra at least, so it is having an effect.
> ymfm: Correct for free-running timer B multipler

- src/osd/osdsync.cpp
- src/osd/osdsync.h
- Defaults chdman to all threads on the system (previously used a maximum of 4 threads)
- Fixes a race condition that made chdman's rapid task allocation not properly wake up all threads (a thread wouldn't mark itself as active until it started running, so if two tasks were scheduled in quick succession, the first would notify a thread, and the second would see that that thread wasn't active yet (since it was notified but not yet running) and notify the *same* thread instead of a new one).
Side note: `osd_event` feels very easy to misuse.  In particular, the way it prevents inclusion of other checks under its lock makes me worry about anything that attempts to combine it with other flags to conditionally call `set()`.  In addition to the old wake code, `osd_work_queue::doneevent` does …
> Fix chdman threading on cpus with many cores

- hash/c64_cass.xml
Labyrinth: The Computer Game (Activision) [C64 Ultimate Tape Archive V2.0]
Last Mission (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
The Last Ninja (Activision) [C64 Ultimate Tape Archive V2.0]
Last Ninja 2: Back with a Vengeance (System 3) [C64 Ultimate Tape Archive V2.0]
Last Ninja 3 (System 3) [C64 Ultimate Tape Archive V2.0]
Law of the West (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Leader Board (Erbe) [C64 Ultimate Tape Archive V2.0]
Leader Board: Executive Edition (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Legend of Kage (Imagine) [C64 Ultimate Tape Archive V2.0]
Licence To Kill (Domark) [C64 Ultimate Tape Archive V2.0]
Little Computer People (Activision) [C64 Ultimate Tape Archive V2.0]
Live Ammo …
> c64_cass.xml: Added 14 entries

- src/devices/imagedev/midiin.cpp
- src/devices/imagedev/midiin.h
feed1e143cbf088065df49d55454f1b21ef090ca unintentionally introduced a problem where trying to load a MIDI file from the command line would attempt to read the config port before the machine was running. This reworks it a bit to wait and modify the MIDI status bytes during playback instead of when initially loading/parsing the file.
I also fixed a parsing issue where the opening byte of sysex events was getting lost.
> midiin_device: handle channel remapping at playback time instead of load time

- hash/apple2_flop_clcracked.xml
- hash/apple2_flop_orig.xml
This set was delayed briefly when it was discovered a number of 3.5" 800K sets had incorrect compatibility information in the header. The incorrect information does not affect MAME's ability to work with the images, but could potentially give inaccurate information to users about whether these disks work with the Apple IIe+.
As such, this PR corrects the disks that need correcting and adds the rest of this month's set.
> Apple softlist update for December 2021

- hash/fmtowns_flop_orig.xml
- Changed the romanization of 日コン連企画 to "Nichikonren Kikaku" as seen in the official website (http://www.nichikon.co.jp/)
- Replaced the Futoppara FD Heisei disks 7 and 10 with unmodified images
FMR/Towns Kihon DOS Tools [cyo.the.vile]
Hometown, U.S.A. [cyo.the.vile]
Hon'yaku Helper Zurukamashi [cyo.the.vile]
Hon'yaku Helper Zurukamashi - Jisho Disk Junior [cyo.the.vile]
Sadistic Gamers Syndrome - Episode I [cyo.the.vile]
Towns Drill - Shougaku Sansuu Series - Sansuu 1-nen (TownsGEAR V2.1 version) [cyo.the.vile]
Yoku Wakaru Sansuu - Shougaku 2-nen [cyo.the.vile]
Futoppara FD Heisei 7-gou [fuzzball]
Futoppara FD …
> fmtowns_flop_orig.xml: 7 new dumps, 2 replacements

- src/emu/video.cpp
One thing I just noticed:
the %t time format code from video_manager::open_next
it needs to be "char t_str[16];"  to accommodate the format string since it's 4+2+2+1+2+2+2+1 (terminating zero) for 16 chars.
If it doesn't have enough room for the zero it will drop the last specifier:
char t_str[15]; and a -snapname "%g/%t" will give filenames like: 
20211225_0406.png
char t_str[16]; and a -snapname "%g/%t" will give filenames like: 
20211225_042939.png
```
if (pos_time != -1)
{
char t_str[16];
const std::time_t cur_time = std::time(nullptr);
strftime(t_str, sizeof(t_str), "%Y%m%d_%H%M%S", std::localtime(&cur_time));
strreplace(snapstr, "%t", t_str);
}
```
> expand buffer size from 15 to 16 for %t time in video_manager::open_next

- src/devices/cpu/h8/h8_sci.cpp
This seems to fix an issue with ctk551 where transmitting and receiving MIDI at the same time could cause TX interrupts to not occur properly, which could cause the firmware's outgoing MIDI buffer to become full, at which point it locks up waiting for the buffer to be processed by an interrupt that never occurs.
The new behavior was verified against the H8/3397 manual from Renesas.
> h8_sci_device: don't set TDRE when receiving

- src/devices/cpu/h8/gt913.cpp
- src/devices/cpu/h8/gt913.h
- src/mame/drivers/ctk551.cpp
Just a couple of corrections made after looking at service manuals again. Powering off also now mutes the speakers like it's supposed to.
Hopefully this is the last time I touch this stuff for a while (at least until I manage to procure some new dumps...)
> ctk551: minor I/O corrections

- hash/r8_card.xml
- hash/u110_card.xml
- src/mame/drivers/roland_cm32p.cpp
- src/mame/drivers/roland_r8.cpp
This PR adds:
- `hash/r8_card.xml`: list of currently dumped and undumped PCM addon cards
- `src/mame/drivers/roland_r8.cpp`: adds PCM card slots (1 for R8 and R8 mkII, 3 for R8M)
> add Roland R-8 PCM cards

- src/emu/render.cpp
- src/osd/windows/window.cpp
- src/osd/windows/window.h
Solves issues related to: https://github.com/mamedev/mame/pull/8209
Fixes: https://github.com/mamedev/mame/issues/8387
Fixes: https://mametesters.org/view.php?id=8110
This is a general case algorithm for all scale modes. Now, the SCALE_FRACTIONAL case wouldn't need a separate implementation anymore, however I'd rather keep it by now since it's much simpler than the general case.
I would have preferred a "single run" algorithm like the previous ones, but the way these features are expected to work seems to require a "find-best-fit" type of implementation, that correctly accounts for the effects of rounding scale values to integers over respective axes.
> New scaling algorithm. Fixes aspect related issues, undesired overscan, etc.

- hash/cdi.xml
- src/mame/machine/cdicdic.cpp
-cdicdic: Always byteswap CDDA data if necessary. Fixes Alien Gate (Euro). [Ryan Holtz]
> Philips CD-i, CDIC changes regarding CD-DA

- src/mame/machine/k573dio.cpp
- src/mame/machine/k573dio.h
- Network communication registers have been documented. I don't know the proper way to implement RS485 to connect multiple instances of MAME together so the registers are stubbed for now. See https://github.com/mamedev/mame/issues/9090 and https://github.com/mamedev/mame/issues/9101 for discussion.
- MP3 start/end addresses are read in some cases so I've added the appropriate readers.
> k573dio: Document new registers and update PCB schematic

- src/devices/bus/isa/fdc.cpp
Turns on floppy sounds for all the PC FDC variants
> bus/isa/fdc: Enable PC floppy sounds

- hash/c64_cass.xml
Magic Marbles (Ariolasoft) [C64 Ultimate Tape Archive V2.0]
Magicland Dizzy (Codemasters) [C64 Ultimate Tape Archive V2.0]
Magnetron (Firebird) [C64 Ultimate Tape Archive V2.0]
Marble Madness (Ariolasoft) [C64 Ultimate Tape Archive V2.0]
Mario Bros (Ocean) [C64 Ultimate Tape Archive V2.0]
MASK II (Gremlin Graphics) [C64 Ultimate Tape Archive V2.0]
Maths Tutor (Channel 8 Software) [C64 Ultimate Tape Archive V2.0]
Matrix (Llamasoft) [C64 Ultimate Tape Archive V2.0]
Mega-Apocalypse (Martech) [C64 Ultimate Tape Archive V2.0]
Megaplay Volume 1 (Mastertronic) [C64 Ultimate Tape Archive V2.0]
Metro Blitz (Personal Software Services) [C64 Ultimate Tape Archive V2.0]
Metro Cross (U.S. Gold) [C64 Ultimate Tape Archive V2.0] …
> c64_cass.xml: Added seventeen working items

- src/devices/cpu/upd7810/upd7810_table.cpp
I think this is correct.  LDAX instructions from  29-2f   and STAX instructions from 39-3f are listed as 2 byte instructions but they're only 1 byte.
Since they're one byte too large, it causes a skipped instruction to skip 1 more byte than it should.
There's another table for the 7807 with the exact same entries but I don't have a datasheet so I'll leave that to someone who knows more than me.
> upd7810_table.cpp: fix LDAX and STAX tables to match proper instruction size for skipping

- src/mame/video/n64.cpp
- src/mame/video/n64.h
- src/mame/video/rdptpipe.cpp
- YUV texture fetch and color space conversion
- textured rectangle command parsing
- set primitive depth command parsing
The following test ROMs illustrate these issues:
https://github.com/PeterLemon/N64/blob/master/RDP/16BPP/Rectangle/FillZBufferRectangle320x240/Cycle1FillZBufferRectangle16BPP320X240.N64
https://github.com/PeterLemon/N64/blob/master/RDP/16BPP/Rectangle/TextureRectangle/Cycle1TextureRectangleYUV16B320x240/Cycle1TextureRectangle16BPPYUV16B320X240.N64
> n64: fix several RDP regressions

- hash/nes.xml
- src/devices/bus/nes/event.cpp
- src/devices/bus/nes/event.h
- src/devices/bus/nes/mmc1.cpp
- IRQ timer now counts up and no longer latches DIP setting when initialized, i.e. DIP switches are always live.
- Removed deprecated hold_irq_line().
> bus/nes: Simplified NES-EVENT board.

- src/mame/drivers/cdi.cpp
- src/mame/includes/cdi.h
- src/mame/video/mcd212.cpp
- src/mame/video/mcd212.h
-mcd212: Various accuracy and timing improvements. [Ryan Holtz]
* Added wait states on ROM and VRAM accesses.
* Simplified pixel-duplication in 360/384-width modes.
* Fixed DCA to process after VSR.
* Switched to use raw parameters for screens.
* Fixed some transparency-fill issues with disabled ICM/VSR.
> CD-i / MCD-212 accuracy and timing improvements

- src/devices/machine/genpc.cpp
- src/devices/machine/genpc.h
- src/mame/drivers/ibmpc.cpp
- Added separate DIP switches for PC with the extra RAM switches configurable as on the real machine, unlike the previous code    
which returned a value based on the set RAM size (and did so incorrectly)
- Added DIP locations for PC and XT
- Added some more RAM options for PC
> IBM PC configurable RAM switches

- src/mame/drivers/model3.cpp
model3.cpp - mark Magical Truck Adventure program ROMs as bad [Bart Trzynadlowski]
- see https://twitter.com/BartronPolygon/status/1476386263498330114
> model3.cpp - mark Magical Truck Adventure program ROMs as bad [Bart Trzynadlowski]

- src/devices/machine/i8255.cpp
This behaviour is expected by ibm6580 self-tests.   Datasheet (page 1058 of components/intel/_dataBooks/1982_Intel_Component_Data_Catalog.pdf) seems to confirm this:
> ~STB (Strobe Input).  A "low" on this input loads data into the input latch.
> i8255: always latch input data when strobe is asserted

- hash/ibm5150.xml
Castles (5.25") [The Good Old Days]
Castles (3.5") [The Good Old Days]
Castles: The Northern Campaign [The Good Old Days]
Hoyle: Official Book of Games - Volume 3 (EGA release) [The Good Old Days]
John Madden Football (alt) [The Good Old Days]
John Madden Football II [The Good Old Days]
Loom (3.5", v1.0) [ibmpc5150, archive.org]
Loom (3.5", v1.1) [ibmpc5150, archive.org]
Star Control (5.25") [The Good Old Days]
Star Control (3.5") [The Good Old Days]
The Black Cauldron (5.25", v2.10) [The Good Old Days]
Turbo Out Run (5.25") [ibmpc5150, archive.org]
Turbo Out Run (3.5") [ibmpc5150, archive.org]
Xenon (16 Blitz Plus release) (5.25") [ibmpc5150, archive.org]
John Madden Football [The Good Old Days] (previous set has a modified OEM ID)
Lemmings (duplicate entry, the game is already in the …
> ibm5150.xml: 14 entries added + 1 redumped - 1 removed

- src/devices/sound/nes_apu.cpp
- src/devices/sound/nes_apu.h
- src/devices/sound/nes_defs.h
Fixes pitch being flat for DPCM sounds for nespal (and m82p). This is most apparent in Mr. Gimmick, though it affects all software that use the DPCM channel.
> nes_apu.cpp: Added missing DPCM period table for PAL. (MT8183)

- src/mame/drivers/ampro.cpp
Added a second call to the "ampro_floppies" function to add support DSQD drives as an option for a given floppy device.
> ampro.cpp: Added quad density 5.25" floppy drive option

- src/mame/drivers/yuvomz80.cpp
- src/mame/mame.lst
From YouTube video references and ROM analyzing, ymz ICs of conventional goldhexa set have sounds of Hexa President and doesn't have songs of Golden Hexa.
goldhexa set should be renamed as "Hexa President (YMZ280B set)".
Release month of Hexa President is described as early June of 1995 in Game Machine no.499 (https://onitama.tv/gamemachine/pdf/19950715p.pdf) P.19.
(Golden Hexa is posted its advertise in Game Machine no.457 (https://onitama.tv/gamemachine/pdf/19930915p.pdf) p.11, published in 1993.)
> yuvomz80.cpp: Correct machine name

- src/devices/cpu/adsp2100/2100ops.hxx
- src/devices/cpu/adsp2100/adsp2100.cpp
- src/devices/cpu/adsp2100/adsp2100.h
Allow PMOVLAY, DMOVLAY register reading on opcodes and debugger states
Add device_post_load for restore external space overlay state
Add/Fix hardware notes
Fix spacing
References:
https://www.analog.com/en/products/landing-pages/001/adsp-manuals.html (ADSP-21xx Manuals)
https://www.analog.com/media/en/dsp-documentation/processor-manuals/5876423468xinset.pdf (ADSP-218x DSP Instruction Set Reference (Rev. 2.0))
ADSP-218x DSP Hardware Reference
> cpu/adsp2100/*.*: Add partially support for PMOVLAY register

- hash/ibm5150.xml
Added some dumps from WinWorld:
- Asynchronous Communications Support (Version 1.00)
- Diagnostics (Version 1.00)
- EasyWriter (Version 1.00)
- Macro Assembler (Version 1.00)
- Pascal Compiler (Version 1.00)
- Typing Tutor (Version 1.00)
- VisiCalc (VC-156Y0-IBM)
> ibm5150.xml: Add new softlist entries from WinWorld

- src/mame/drivers/segag80v.cpp
I recently ran mame and saw I could no longer run zektor due to this commit:
Fix a typo in a ROM filename (1607->1670) commit d26b99931c00c2ec5d097bfc82d443dad4d44469
The 1607 was not a typo; I was there 25 years ago when the ROMS for Zektor were
originally read from the speech PCB.
In addition, I noticed that startrek had, all this time, also been using the incorrect
ROM labeling.  A quick online search of "star trek speech pcb" will bring up a visual of the original
PCB with the EPROM clearly labeled "1607". 
Besides, EPROM number 1670 is reserved for Tac/Scan; Sega/Gremlin didn't reuse EPROM numbers, though they
did reuse the eproms themselves across games (for example, Space Fury and Astro Blaster also share speech EPROM 808).
Unfortunately, this will effect people playing zektor and …
> segag80v.cpp: Corrected speech ROM labels for zektor and startrek

- hash/vis.xml
- src/devices/bus/isa/mcd.cpp
- src/mame/drivers/vis.cpp
This adds a new software list for the Tandy/Memorex VIS with 70 entries, which should be almost the entire library of the system. I have tested them but not too extensively, so I may have missed some bugs.
To allow the discs to auto-mount from the command line, this also adds a set_interface line to the Mitsumi ISA CD adapter used by the VIS.
> New software list for the Tandy/Memorex VIS

- src/lib/netlist/plib/pstream.h
Fedora rawhide has updated gcc to version 12. Minimal changes are required to get mame to build.
> Fix building with gcc-12

- hash/vis.xml
Just a quick update for the VIS software list to get it up to date with the latest improvements. Many thanks to @cracyc for allowing modern audiences to enjoy all this high quality software. :)
A Survey of Western Art - The Electronic Library of Art [crazyc]
America's National Parks [crazyc]
Americans in Space [crazyc]
Learn to Play Guitar Volume 1 [crazyc]
Mercer Mayer's Just Grandma and Me [crazyc]
Mutanoid Word Challenge [crazyc]
Peter and the Wolf - A Multimedia Storybook [crazyc]
Rick Ribbit - Adventures in Early Learning [crazyc]
Sail with Columbus [crazyc]
Time Magazine Compact Almanac 1992 [crazyc]
> vis.xml: re-test software and promote to working

- hash/nes.hsi
- hash/nes.xml
- src/devices/bus/nes/kaiser.cpp
- src/devices/bus/nes/konami.cpp
- src/devices/bus/nes/konami.h
- src/devices/bus/nes/nes_ines.hxx
- src/devices/bus/nes/nes_pcb.hxx
- Added missing WRAM enable bit (VRC4/6/7).
- Simplified handling of pins that connect to variable address lines (VRC2/4/6/7). VRC7's pin 19 now is configured dynamically like the others.
- For each VRC chip, masked bank numbers to reflect actual ROM size supported by pinout.
- Removed unreachable logging statements, other assorted cleanups and simplifications.
> bus/nes: Updated all Konami VRC boards.

- src/mame/drivers/vegas.cpp
Fixes the use of uart_1 instead of uart_2 on the serial port ttys02
> Vegas - Fix Uart definition

- src/mame/includes/playch10.h
- src/mame/machine/playch10.cpp
- Removed WRAM from PinBot, there's none on its PCB.
> machine/playch10.cpp: Properly clear IRQs for MMC3 boards.

- src/mame/drivers/cv1k.cpp
Fix year metadata - both copyright string at bottom of title and version string is changed year to 2017
Fix manufacturer string - Four horsemen is authors of pinkswtssc hack, Bootlegger is still unknown
Fix spacing
> cv1k.cpp: add further notes for pinkswtssc

- src/devices/sound/nes_apu.cpp
- src/devices/sound/nes_defs.h
- Fixed a value in the parallel NTSC table for the largest period (lowest freq).
- Fixed a value in the counter length table (for all channels but DMC).
> nes_apu.cpp: Added noise channel period table for PAL systems.

- src/mame/drivers/vsnes.cpp
- src/mame/includes/vsnes.h
- src/mame/machine/vsnes.cpp
- Fixed size and mirroring of RAM. Correctly share shared RAM only. Shared RAM is also now properly NVRAM (Wrecking Crew saves high scores, etc).
- Removed spurious "extra RAM" installed in a couple spots.
- Added coin read/write address mirroring.
- Renamed "mapper 68" to Sunsoft-3, the chip on Platoon's board. Fixed its write masking.
- Implemented proper strobe behavior for joystick read/writes.
- Removed now unnecessary lightgun-specific read function and unused variables.
> vsnes.cpp: Various fixes and cleanups.

- src/devices/bus/nes/mmc3_clones.cpp
- src/devices/bus/nes/nes_slot.cpp
- src/devices/bus/nes/nes_slot.h
- Removed PPU_MIRROR_NONE as an option for nametable mirroring.
- Shrunk over-allocated 4-screen NT RAM to correct 4K size.
- Sundry minor clean ups.
> nes_slot.cpp: Unified CHR banking into a common function.

- hash/nes.xml
- src/devices/bus/nes_ctrl/ctrl.cpp
- src/devices/bus/nes_ctrl/joypad.cpp
- src/devices/bus/nes_ctrl/joypad.h
- src/devices/bus/nes_ctrl/pachinko.cpp
- src/devices/bus/nes_ctrl/pachinko.h
- Generalized the read/write pattern for joypads a bit more and placed it in the base NES joypad class.
- Using that, added Virtual Boy controller and simplified Pachinko controller some more.
Candelabra - Estoscerro [SlyDogStudios]
> bus/nes_ctrl: Added NES support for Virtual Boy controllers.

- scripts/src/bus.lua
- scripts/target/mame/mess.lua
- src/devices/bus/epson_qx/option.cpp
- src/devices/bus/epson_qx/option.h
- src/mame/drivers/qx10.cpp
This adds support for the QX-10 expansion bus.
Supports both IO/MEM access as well as support for DMA lines and interrupts are included. Also removed the multifont ROM from the main QX10 driver as this will be included in a series of followup patches, one of which adds emulation support for the multifont card.
> qx10: Add expansion bus

- scripts/src/bus.lua
- src/devices/bus/a2bus/a2superdrive.cpp
- src/devices/bus/a2bus/a2superdrive.h
- src/devices/bus/a2bus/cards.cpp
- src/devices/machine/swim1.cpp
- src/mame/drivers/apple2gs.cpp
Apple II 3.5" Disk Controller Card.
n.b. - mame's 65c02 implementation has incorrect false reads when crossing page boundaries.  This needs to be fixed for the  uc code to work correctly.
The firmware modifies the apple iigs rombank statereg bit to check if it's a IIgs or a IIe.
Writing to an 1.44MB MFM disk image frequently errors out due to transition too wide errors.
> bus/a2bus: Added Apple II 3.5" Disk Controller Card

- src/mame/drivers/ctk551.cpp
Changed the year to 2000 based on [the product page on CasioPart](https://www.casiopart.com/model-number/ctk551/) (which seems to have only gone online sometime within the last few months). The original 1999 date was taken from the (nearly identical) CTK-541 service manual.
> ctk551: correct release year, add mask ROM label

- src/devices/machine/swim1.cpp
- src/devices/machine/swim2.cpp
I encountered some odd crashes testing the a2superdrive slot options (eg, `mame apple2ee -sl7 superdrive -sl7:superdrive:fdc:0 35sd` ). Poking further, swim1 had an invalid `m_floppy` since it is never initialized.  swim2 would also have the same issue.  There's also a timer in swim1 that isn't initialized.
> swim1/swim2 - initialize m_floppy and m_timer

- src/devices/cpu/m68000/m68k_in.lst
- src/devices/cpu/m68000/m68kcpu.cpp
- src/devices/cpu/m68000/m68kops.cpp
I have been working on the AT&T UNIX PC driver (68010) and ran into an issue with page fault handling. I tracked this back to the RTE instruction for 68010 wherein the SP can potentially be changed mid-unwind of the bus error exception stack frame (format = 8), when transitioning from supervisor mode back to user mode (A7 being set to USP).
I also added 68010 format 8 stack frame setup in the bus error handling code.  This code is presently inaccessible to 68010, due to the `pmmu_enabled` conditional. But that is a separate topic being discussed in issue #9170
> create 68010 bus error stack frame / fix for 68010 RTE stack frame unwinding

- src/mame/machine/snes.cpp
this commit fixes some regression after [this commit](https://github.com/mamedev/mame/commit/db40a44d0093bdb2ffa508a9452a81e05750f56e).
> snes.cpp: partial revert DMA cycle function

- hash/nes.xml
- src/devices/bus/nes_ctrl/zapper.cpp
- src/mame/machine/playch10.cpp
- src/mame/machine/vsnes.cpp
- Removes the pixel-perfect sensor by averaging pixel brightness over circular area around gun position.
- Treat RGB values equally and don't use lib/util/palette.h's weighted brightness function.
> nes, playch10.cpp, vsnes.cpp: Made zapper sensor fuzzier.

- src/devices/bus/coco/coco_fdc.cpp
- src/lib/formats/jvc_dsk.cpp
- src/lib/formats/os9_dsk.cpp
formats/jvc_disk: Change osd_printf_info() to LOG_FORMATS(). Changed code to verify image geometry against floppy drive geometry.
formats/os9_dsk: Improved logging
bus/coco/coco_fdc: Improved logging. Turned on disable_motor_control and force_read in wd1773. This fixed some new games that use the AGI Engine
> coco3: fix crash in some AGI games

- src/mame/drivers/pentagon.cpp
- src/mame/includes/spectrum.h
POC for modernization of screen_device usage.
This implementation is done on self-contained Pentagon driver with intention to be moved to parent spectrum.
Improvements:
* gfx rendered directly on screen_device without intermediate bitmaps (m_border_bitmap, m_screen_bitmap)
* INT raised on beginning of vblank instead of manually adjusted position
* position of the gfx can be moved to arbitrary position (see: PENTAGON_SCREEN), not customly hardcoded at (0,0). That respects vblank/hblank positions "before" real screen, not wrongly "after" previously.
> spectrum: move gfx to screen_device

- hash/c64_cass.xml
Pack of Aces (Prism Leisure) [C64 Ultimate Tape Archive V2.0]
Pac-Land (Quicksilva) [C64 Ultimate Tape Archive V2.0]
Pandora (Firebird) [C64 Ultimate Tape Archive V2.0]
Panic (Datamaxx) [C64 Ultimate Tape Archive V2.0]
Paperboy (Elite Systems) [C64 Ultimate Tape Archive V2.0]
Pastfinder (Activision) [C64 Ultimate Tape Archive V2.0]
Peter Beardsley's International Football (Grandslam) [C64 Ultimate Tape Archive V2.0]
Ping Pong (Imagine) [C64 Ultimate Tape Archive V2.0]
Pitfall II: Lost Caverns (Activision) [C64 Ultimate Tape Archive V2.0]
Pitstop II (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Pitstop II (Rushware) [C64 Ultimate Tape Archive V2.0]
Plumb Crazy! (Terminal Software) [C64 Ultimate Tape Archive V2.0] …
> c64_cass.xml: Added 22 items (21 working, one not working)

- src/devices/video/ppu2c0x.cpp
- src/devices/video/ppu2c0x.h
- Added function to unify grayscale and palette emphasis flags application. Flags now applied to background pixels (including separate cases: 0 tile pixel, disabled background lines, and blanked 8-pixel left column).
- Fixed special case where background is disabled and scanline color is set by PPU address latch pointing to palette RAM (used in Micro Machines).
- Plus a few minor simplifications and cleanups.
> ppu2c0x.cpp: A few background palette fixes.

- src/mame/drivers/blockade.cpp
Change title to "CoMotion" as per flyers (nw)
Said flyers:
* [flyer 1](https://flyers.arcade-museum.com/flyers_video/sega/107001504.jpg)
* [flyer 2](https://flyers.arcade-museum.com/flyers_video/sega/107441701.jpg)
and the [patent that was transcribed](https://patents.google.com/patent/US4089524A/en)
> blockade: Add version of CoMotion from patent [eientei]

- src/mame/drivers/raiden.cpp
- src/mame/includes/raiden.h
- src/mame/video/raiden.cpp
Reduce unnecessary memory region size, Simplify gfxdecode layouts, Fix namings, Use shorter/correct type values
> raiden.cpp: Use prio_* for single pass sprite draw routine, Minor cleanups, Add notes for country/game mode byte

- src/devices/sound/nes_apu.cpp
- src/devices/sound/nes_defs.h
- Don't set output level to zero, it is always determined by sequencer, which cannot be reset. This eliminates most of the popping, hopefully.
- Raised artificial frequency cutoff to about 18KHz instead of 11KHz.
- Added linear counter reload flag.
> nes_apu.cpp: Improvements for triangle channel.

- hash/c64_cass.xml
Rallycross Simulator (Codemasters) [C64 Ultimate Tape Archive V2.0]
Rambo III (Ocean) [C64 Ultimate Tape Archive V2.0]
Rambo: First Blood Part II (Ocean) [C64 Ultimate Tape Archive V2.0]
Rampage (Activision) [C64 Ultimate Tape Archive V2.0]
Ramparts (Go!) [C64 Ultimate Tape Archive V2.0]
Rana Rama (Hewson Consultants) [C64 Ultimate Tape Archive V2.0]
Rasputin (Firebird) [C64 Ultimate Tape Archive V2.0]
Rastan (Imagine) [C64 Ultimate Tape Archive V2.0]
The Real Ghostbusters (Activision) [C64 Ultimate Tape Archive V2.0]
Re-Bounder (Prism Leisure) [C64 Ultimate Tape Archive V2.0]
Red Heat (Ocean) [C64 Ultimate Tape Archive V2.0]
Red L.E.D. (Dro Soft) [C64 Ultimate Tape Archive V2.0]
Red Max (Codemasters) [C64 …
> c64_cass.xml: Added 13 working items

- src/devices/sound/nes_apu.cpp
- src/devices/sound/nes_apu.h
- src/devices/sound/nes_defs.h
- Removed old, unused, or redundant code, variables, and comments.
- Removed array used for reading back registers. APU registers cannot be read.
- Updated length counter table to match hardware counts.
- Consolidated some functions.
> nes_apu.cpp: A few cleanups.

- hash/c64_cass.xml
Renegade III: The Final Chapter (Imagine) [C64 Ultimate Tape Archive V2.0]
Rescue on Fractalus! (Activision) [C64 Ultimate Tape Archive V2.0]
Retrograde (Thalamus) [C64 Ultimate Tape Archive V2.0]
Return to Oz (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Revenge of the Mutant Camels (Llamasoft) [C64 Ultimate Tape Archive V2.0]
Richard Petty's Talladega (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Roadwars (Melbourne House) [C64 Ultimate Tape Archive V2.0]
RoboCop (Ocean) [C64 Ultimate Tape Archive V2.0]
Rodland (Storm) [C64 Ultimate Tape Archive V2.0]
Rolling Thunder (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Room Ten (CRL) [C64 Ultimate Tape Archive V2.0]
Run the Gauntlet (Ocean) [C64 Ultimate Tape Archive …
> c64_cass.xml: Added 12 working items

- docs/source/techspecs/luareference.rst
- src/emu/ioport.cpp
- src/emu/ioport.h
- src/frontend/mame/luaengine_input.cpp
Made setting analog values user friendly.
Exposed adjusted min/max values. Together with defvalue, they can be used to check in-game range of available analog values to send.
Previously you had to send raw value between -65535 and 65535 which would then be normalized depending on machine specifics. You could read the normalized value from the analog port, but you couldn't send normalized values in, only raw. Since raw values don't directly mean anything specific in-game, you had to use trial and error to figure out the range of values that do anything at all. In order to work around those gaps in effectiveness, you'd have to normalize the values yourself on the lua side, and not all relevant factors were exposed (and normalization is a mess anyway).
This commit results in a slight change …
> luaengine: make setting analog values user friendly

- src/devices/cpu/mips/r4000.cpp
- src/devices/cpu/mips/r4000.h
Per the MIPS R4000/R4400 User's Manual, the G bit should be written into both EntryLo0 and EntryLo1 when a TLBR instruction is executed. Sony NEWS-OS 4.2.1aRD expects this bit to be set if it writes it into the TLB when it reads information back out. This is something mips3 has.
EntryLo0/1 definition:
TLBR description:
> r4000.cpp: Set TLB global bit in EntryLo0/1 on TLBR instruction

- src/mame/drivers/playch10.cpp
- src/mame/includes/playch10.h
- src/mame/machine/playch10.cpp
- Modernized PRG ROM banking.
- Cleaned up cart daughter board initialization code.
- Fixed daughter board RAM sizes for Baseball Star, Pinbot, and Punch-Out. Punch-Out's is NVRAM and it now saves properly.
> playch10.cpp: Various cleanups.

- src/emu/input.cpp
In practice this was probably benign, because a trailing NUL was there.  But this should still be fixed.
> Fix out of bounds access to std::string_view

- src/tools/floptool.cpp
"Error: Aaving" should be "Error: Saving"
> Fix typo in floptool

- src/mame/drivers/terracre.cpp
According to [music sheet](https://jogrm.blogspot.com/2022/02/blog-post_19.html) officially offered from Nichibutsu (found from "Bokura no Game Music", Appendix of Beep 1986-06), sounds in the intro of main theme in old/older set seems not a glitch.
> terracre.cpp: correct description

- src/mame/drivers/playch10.cpp
- src/mame/includes/playch10.h
- src/mame/machine/playch10.cpp
- src/mame/video/playch10.cpp
- Nametable RAM is now 2K, except for the two games (Rad Racer II, Gauntlet) that have extra RAM on daughter boards.
- Removed unnecessary overridden machine/video start code for PinBot.
- Added an address map for the PPU.
- Further simplified initialization code for games that have VRAM or special RP5H01 usage.
- Lots of conversion to C++-style comments with a few corrections along the way.
> playch10.cpp: A few more cleanups.

- src/devices/cpu/i960/i960.cpp
Primarily added dmovt opcode to prevent occasional crashes in VF2 (and likely other Model 2 games) when in debug mode, as outlined here:
https://mametesters.org/view.php?id=7800
Also added daddc/dsubc to round out the decimal opcodes. Code for these is based on the existing addc/subc code. There is a little confusion on these, as the newer [i960 manual](file:///mnt/aine/Library/Development/CPU/Intel%20i960%20Processor%20Assembler%20Users%20Guide.pdf)  seems to imply these should work with ASCII coded decimals, like dmovt does. However, the older [80960 manual](http://www.bitsavers.org/components/intel/i960/80960KB_Programmers_Reference_Manual_Mar88.pdf) indicates they should work with BCD values. I have implemented the BCD 4 bit versions from the older manual as it is more explicit on …
> Added dmovt opcode to i960 cpu

- src/mame/drivers/alpha68k_n.cpp
According to [video by PCB](https://youtu.be/dA2lsgwdrU0?t=6222), audio clocks need to be corrected.
Also, former 2nd and 3rd YM2203 are actually AY-3-8910s.
> alpha68k_n: correct audio clock for sstingry

- src/mame/drivers/4enlinea.cpp
https://img.recreativas.org/2022/02/g/sport-dart-tv-g14289.jpg
> 4enlinea.cpp: Fix 'sprtdart' game name as in title screen

- src/mame/drivers/ksys573.cpp
This implements the I/O for the newly added game Kick & Kick. With the I/O board implemented, the game is playable from start to finish without any noticeable issues so I removed the `MACHINE_NOT_WORKING` flag. Having said that, while the game works, the controls are unintuitive when played as key binds in MAME. The order and the speed that you trigger the sensors is important. I've found the order that works best is front sensor -> horizontal sensor -> vertical sensor.
> ksys573: Implement I/O for Kick & Kick [windyfairy, Shiz]

- hash/fmtowns_flop_misc.xml
- hash/fmtowns_flop_orig.xml
Also removed the old Shougi Seiten images from fmtowns_flop_misc.xml, since they have been confirmed to be bad dumps.
2069 AD [cyo.the.vile]
Nihongo MS-DOS V3.1 L36 (Kihon Kinou) [cyo.the.vile]
Shougi Seiten [cyo.the.vile]
Fortress [cyo.the.vile]
Para Para Paradise Update Disk [cyo.the.vile]
> fmtowns_flop_orig.xml: 5 new dumps

- src/mame/drivers/djmain.cpp
Fix for PR #9398: `bmcompmxb` was supposed to be a child of `bmcompmx` but I forgot to add the appropriate parent parameter.
> djmain: Fix parenting for bmcompmxb

- src/mame/drivers/seta.cpp
This name is found if you change the country setting to Japan via the dip switch settings.
(Image from The Arcade Flyer Archive)
> seta.cpp - add alternative title to kamenrid

- hash/fmtowns_flop_orig.xml
This replaces the system disk for A Ressha de Ikou IV Map Construction + Power-Up Kit. Turns out this disk was protected (the other two are not), but it went unnoticed because the previous dump was made with a simple "dd" command that somehow didn't report any errors. This image comes from a flux-level dump and passes the protection check.
I also found out that you can run these disks directly instead of installing them to HDD, so I have updated the usage notes.
> fmtowns_flop_orig.xml: add redumped aressh4m [cyo.the.vile]

- hash/nes.xml
Galaxy 5000 - Racing in the 51st Century (USA, prototype) [GamersGulch, Forest of Illusion]
Hatris (USA, prototype) [mmsc]
Rampart (Japan, sample) [Skrybe]
Renegade (USA, prototype) [rfancella]
Saiyuuki World (Japan, prototype) [Aetius For Real]
Square Deal (Japan, Great Deal prototype) [Skrybe]
Toki (USA, prototype) [CloudGamerX]
> nes.xml: Added seven prototypes.

- src/mame/drivers/photoply.cpp
Four dongles has been dumped, finding different mixes of MCU programs and EEPROM ROMs, making not much sense with the "rev" sticker present on each one.
> photoply.cpp: Add security dongle MCU dumps for 'photoply99sp' [Caps0ff, jordigahan, ClawGrip]

- src/frontend/mame/luaengine.cpp
- src/frontend/mame/luaengine.h
- src/frontend/mame/luaengine.ipp
This does two things: enables all of Sol’s safety checks in debug builds, and replaces the `sol::buffer` class with another helper for using Lua string buffers.
The first change is simpler.  It means that for debug builds, you get somewhat helpful error messages when you do something like using `.` instead of `:` when calling instance member function rather than MAME just crashing twenty levels inside Sol (@galibert might appreciate this).  Of course, this does cost performance in debug builds.  However, this can’t be done without doing something about `sol::buffer` (see [MT08242](https://mametesters.org/view.php?id=8242)), which brings us to the second change.
The point of `sol::buffer` was to allow returning a Lua string from C++ without needing the copy you’d get if you return a …
> Lua engine: Enable checks for debug builds, kill sol::buffer

- src/mame/drivers/asuka.cpp
bonzeadv has no ADPCM-A samples, but has ADPCM-B's.
> asuka.cpp: bonzeadv has no ADPCM-A samples

- hash/ibm5170_cdrom.xml
- hash/pc98_cd.xml
New software list additions
Microsoft Windows 98 Second Edition (jp 4.10.2222) (Retail Full)
Corrected release years for other Windows releases and added serials for Microsoft Windows 98 Second Edition (PC-98 / IBM 5170)
> ibm5170_cdrom.xml / pc98_cdrom.xml: Data fixes

- src/mame/drivers/vsnes.cpp
- src/mame/includes/vsnes.h
- src/mame/machine/vsnes.cpp
- Modernized PRG ROM banking. Gets rid of banking via memcpy.
- Cleaned up some of the daughter board code, including protection routines.
- Lots of C-style comment to C++-style conversion.
> vsnes.cpp: Various cleanups.

- src/mame/drivers/namcona1.cpp
In according with namconian blog130 wibsite, so the correct Bin Bin Bingo year is 1996.
http://namconian.blog130.fc2.com/blog-entry-355.html
> Correct Bin Bin Bingo year

- src/mame/drivers/vicdual.cpp
Note that I have also updated the DIP switch names on alphahob to reflect the game names used on this bootleg (Missile & Circuit)
> vicdual.cpp: add bonus life DIP switch to wantsega, alphaho & alphahob (MT08256 & MT08257)

- src/mame/drivers/minitel_2_rpic.cpp
This PR makes it possible to use the emulated minitel as if it was connected using its modem or serial line.
Since the original purpose of this device is to serve as a modem terminal, it is now possible to have an interaction with a real server.
> Minitel 2 : Modem and serial port support

- hash/ibm5170.xml
Alone in the Dark 2 (Germany) [The Good Old Days]
Eternam [ibmpc5150, archive.org]
Fables & Fiends - Book One: The Legend of Kyrandia (v1.8, 3.5", Germany) [The Good Old Days]
Dragon's Lair [ibmpc5150, archive.org]
Maniac Mansion: Day of the Tentacle (Germany) [The Good Old Days]
Prophecy of the Shadow (3.5") [The Good Old Days]
Prophecy of the Shadow (5.25") [The Good Old Days]
Serf City: Life is Feudal (USA) [ibmpc5150, archive.org]
SimCity 2000 (Interactive demo disk) [lazygamereviews, archive.org]
Redump
------
Inca 2: Wiracocha (Euro) [ibmpc5150, archive.org] (disk 3 and disk 10 have a modified OEM ID)
Rename
------
tentaclef -> tentaclefr
> ibm5170.xml: 9 added + 1 redumped + 1 renamed

- src/mame/drivers/cham24.cpp
- src/mame/drivers/famibox.cpp
- src/mame/drivers/multigam.cpp
- src/mame/drivers/playch10.cpp
- src/mame/includes/playch10.h
- src/mame/machine/playch10.cpp
famibox.cpp: Use memory banks for nametable RAM.
cham24.cpp: Use memory banks for nametable RAM.
multigam.cpp: Add PPU address map and use memory banks for nametable RAM.
> playch10.cpp: Use memory banks for nametable RAM.

- scripts/src/bus.lua
- src/devices/bus/epson_qx/multifont.cpp
- src/devices/bus/epson_qx/multifont.h
- src/devices/bus/epson_qx/option.cpp
This adds supports for emulation of the QX-10 multifont card. It is still missing the font ROMs, but the actual emulation of the card works fine. The emulation is based of reading the schematics and documenation that is available online. If the missing font roms are ever dumped the emulation should just work. I tested this using mfont from the cpm221m1.td0 boot disk and a fake font rom file I created using an existing bitmap bdf font. When running mfont it is correctly reading and displaying the bdf font from the fake rom file.
[Test font data](https://github.com/mamedev/mame/files/8028418/hn43128.2a.zip)
> qx10: add multifont option card

- src/mame/drivers/qx10.cpp
Connect the Epson QX-10's software timers to the proper IRQ lines.
> qx10: Install software timer interrupts

- hash/fmtowns_flop_orig.xml
Fixed Scenario Disk 3 for Dragon Slayer: The Legend of Heroes II, which had an incorrectly converted protection sector.
Think Lead Gakushuu System - FM Towns CMI Program [cyo.the.vile]
Think Lead Gakushuu System - FM Towns Theme-betsu Gakushuu Series - Jikkou Program Ver. 2 [cyo.the.vile]
Think Lead Gakushuu System - Shougaku Rika 5-nen - Tane no Hatsuga (1) [cyo.the.vile]
Think Lead Gakushuu System - Shougaku Rika 6-nen - Karada no Tsukuri (1) [cyo.the.vile]
> fmtowns_flop_orig.xml: 4 new dumps + fix

- hash/apple2_flop_orig.xml
An apparent duplicate woz-a-day entry slipped through the cracks on 4AM's part and wasn't caught by -valid and xmllint.
> Temporarily remove duplicate Apple-oids and Chipout disk pending detailed analysis

- hash/nes.xml
- src/devices/bus/nes/ggenie.cpp
- src/devices/bus/nes/ggenie.h
- src/devices/bus/nes/nes_slot.cpp
- src/devices/bus/nes/nes_slot.h
- Trimmed overdumped PRG ROM to 4K.
- Removed nonexistent CHR ROM, replaced with emulation of on-board logic.
- Removed hack from NES slot code that directly set the CPU program counter.
- Corrected reset behavior.
> bus/nes: Game Genie cleanup time.

- hash/fmtowns_flop_cracked.xml
- hash/fmtowns_flop_orig.xml
- hash/pc98.xml
- hash/pc98_cd.xml
After another round of re-checking I've found a few more cases of protected disks incorrectly converted to the HxC MFM format. It seems the HxC tools don't handle well the conversion when a sector crosses the index pulse, so those sometimes require a bit of manual editing. I didn't catch them originally because most of them seem to be a bit sneaky:
- Dinosaur only fails the protection check when you reload a saved game from the game itself and try to move to a different area.
- In Lord Monarch only the ending disk was affected, so the game works but it probably couldn't be finished.
- As for Maririn DX and My Fair Teacher, I have no idea since they always seemed to work, but maybe they have more protection checks further into the game?
Brandish PC-98 simply didn't work, and it does now. …
> fmtowns_flop_orig.xml/pc98.xml: fix incorrect mfm files

- hash/nes.xml
- src/devices/bus/nes/act53.cpp
- src/devices/bus/nes/aladdin.cpp
- src/devices/bus/nes/ave.cpp
- src/devices/bus/nes/bandai.cpp
- src/devices/bus/nes/benshieng.cpp
- src/devices/bus/nes/benshieng.h
- src/devices/bus/nes/bootleg.cpp
- src/devices/bus/nes/hes.cpp
- src/devices/bus/nes/hes.h
- src/devices/bus/nes/jaleco.cpp
- src/devices/bus/nes/mmc3_clones.cpp
- src/devices/bus/nes/multigame.cpp
- src/devices/bus/nes/multigame.h
- src/devices/bus/nes/namcot.cpp
- src/devices/bus/nes/nes_slot.cpp
- src/devices/bus/nes/pirate.cpp
- src/devices/bus/nes/sachen.cpp
- src/devices/bus/nes/subor.cpp
- src/devices/bus/nes/waixing.cpp
- src/devices/bus/nes_ctrl/hori.cpp
bus/nes/benshieng.cpp: Streamline banking; no need to store variables in this device.
bus/nes/hes.cpp: Only support multicarts. Related singleton carts reassigned to relevant board types. (Fixes various graphics issues in the multicarts.)
bus/nes_ctrl/hori.cpp: Amend some minutiae involving strobing and excessive controller reading.
hash/nes.xml: Removed a few more baddump flags.
> nes: Various minor fixes, more cleanups with bit functions.

- src/devices/imagedev/floppy.cpp
This is not an actual user facing bug right now, because in the MAME UI the call to `init_fs()` is followed up by a call to `setup_write()`, which forces the image to commit without regard to the dirty bit.  There is an argument that this is itself code smell; `setup_write()` perhaps should be `set_output_format()` and not arbitrarily perform a commit.
> Changed floppy_image_device::init_fs() to set the dirty bit on the floppy image

- language/Ukrainian/strings.po
Applied the changes from the file attached to #9095 to make it easier to review.
Areas that have been problematic for translators in the past include:
* Parent/clone terminology
* Names for gambling inputs and/or mahjong inputs
* UI Select vs controller Select button
* Timer plugin terminology (“Current Time” meaning “elapsed time in current session”, the English expression “Wall Clock Time”, etc.)
> Added Ukrainian UI translation. [Stanley Kid]

- src/lib/formats/fs_coco_os9.cpp
- src/lib/formats/fs_coco_os9.h
A caveat of this support is that there is no way for a FS implementation to get the actual floppy geometry.  Therefore, we are currently hard coding the track count, head count and sector size (attn @galibert)
> Adding support for formatting CoCo OS-9 file systems

- src/osd/strconv.cpp
I've only tested CP932 but I suspect other codepages that have multibyte characters are also affected. To reproduce this bug you must be using Windows and set your system locale to a locale that uses multibyte characters (Japanese for example). Create an ini file such as folders/category.ini that uses ASCII or UTF-8 **without** BOM (any encoding with a BOM is unaffected). The file will not be loaded when MAME is launched, and a debugger can be used to check that `osd_uchar_from_osdchar` is returning an error.
On CP932 specifically, `MaxCharSize` will become 2. The input count passed into `osd_uchar_from_osdchar` is anything up to 16.
https://github.com/mamedev/mame/blob/ba77706c5cea808d5e532550b7bafd78e8bf6d09/src/lib/util/corefile.cpp#L315-L326
Using the category INIs for example where …
> osd: Add multibyte check to osd_uchar_from_osdchar

- src/devices/imagedev/floppy.cpp
- src/devices/imagedev/floppy.h
- src/frontend/mame/ui/filecreate.cpp
- src/frontend/mame/ui/filecreate.h
- src/frontend/mame/ui/floppycntrl.cpp
- src/frontend/mame/ui/floppycntrl.h
We had two separate memebers in floppy_image_device (m_create_fs and m_io_fs) that contained the same data.  Whether the file systems can be formatted or read can be identified by querying fs::manager_t.
For this reason, it seems bad to have these separate members, the seemingly only reason to make the UI code slightly less complicated.  For this reason I consolidated these two members and moved the burden of selecting which ones are creatable to the UI code.
> Consolidated floppy_image_device::m_create_fs and floppy_image_device::m_io_fs vectors

- src/lib/formats/fs_coco_os9.cpp
- src/lib/formats/fs_coco_rsdos.cpp
- src/lib/formats/fs_oric_jasmin.cpp
- src/lib/formats/fs_prodos.cpp
- src/lib/formats/fs_vtech.cpp
- src/lib/formats/fsmeta.h
With the recent change to use std::variant more closely, I noticed a problem where meta_descriptions of type meta_type::String got defaults of type 't'.  This was because the templated ctor for meta_description would convert 'const char *' to 'bool'.  This change adds another overload to catch 'const char *', along with asserts to catch problems.
In the process I corrected a few meta_description ctors
It is possible that this change does not go far enough.  Perhaps the meta_type argument should be removed, and we should instead create distinct ctor types (rather than relying on templates) and specify the precise meta_type in the overload.  Or even go further and remove m_type from meta_description, and instead create an overload that calculates meta_type based on calling std::visit on the …
> Fixed some issues involving fs::meta_description construction

- src/devices/sound/mas3507d.cpp
- src/devices/sound/mas3507d.h
- src/mame/machine/k573dio.cpp
- src/mame/machine/k573dio.h
- src/mame/machine/k573fpga.cpp
- src/mame/machine/k573fpga.h
MAS3507D previously used a callback to receive data when it needed to fill the buffers which worked for the previous implementation but wasn't accurate to what the MAS3507D actually does, which is trigger the demand pin and wait for the other end to send data via the input clock and input data pins. I rewrote that code to more accurately reflect the real MAS3507D which allowed me to implement the FPGA side more accurately to what the real code was doing based on my research with the state flags and timers/counters.
Datasheet ref: http://www.mas-player.de/mp3/download/mas3507d.pdf
This PR also closes https://github.com/mamedev/mame/issues/8619. Further research showed that DDR Solo Bass Mix times songs entirely differently than any other digital I/O game. I had previously identified that …
> k573dio/k573fpga: Improve counters and status flags

- hash/nes.xml
- src/devices/bus/nes/nes_ines.hxx
- src/devices/bus/nes/taito.cpp
- src/devices/bus/nes/taito.h
- Replaced bad program ROMs with dumps with proper page order.
- Updated banking to work with proper dumps.
- Fixed CHR banking from possibly ignoring first writes.
- Added special latching bytes to internal X1-017 RAM.
- Added IRQ support (no games exist that use it).
> bus/nes: Updated Taito X1-017 boards.

- src/devices/machine/gt64xxx.cpp
- src/devices/machine/gt64xxx.h
- src/mame/drivers/seattle.cpp
- src/mame/drivers/vegas.cpp
gt64xxx: Change interrupt handler to not send new interrupts if an interrupt has already been asserted and improve dma timing.
seattle: Add some harddrive dma delay to make harddrive performance more realistic.
> Fix MT07568: hyprdriv (seattle) randomly freezes.

- src/mame/drivers/cinemat.cpp
Title has no space in the middle in the marquee, art, flyers, or operator's manual.
> cinemat.cpp: Starhawk typo fix

- src/devices/video/imagetek_i4100.cpp
- src/devices/video/imagetek_i4100.h
- src/mame/drivers/metro.cpp
- src/mame/includes/metro.h
Proposed fix for [MT08203](https://mametesters.org/view.php?id=8203)
imagetek_i4100.cpp: add external pin callbacks, disallow internal irq acks for 5 to 7 lines;
metro.cpp: tie irq line 5 to a vblank source with external pin 0 as irq enable, fixes MT08203;
> MT08203 fix

- src/lib/formats/fsmeta.h
In absence of a constructor that explicitly took 'const char *', passing a const char * would be interpretted as a bool
> Fixed string constructor for fs::meta_value

- src/devices/bus/nes/bootleg.cpp
- src/devices/bus/nes/mmc3.cpp
- src/devices/bus/nes/mmc3.h
- src/devices/bus/nes/mmc3_clones.cpp
- src/devices/bus/nes/mmc3_clones.h
- src/devices/bus/nes/pirate.cpp
- Fixed TXSROM's repeated setting of nametable pages.
- NES-QJ, PAL-ZZ boards can only change outer banking bits when RAM enabled.
> bus/nes: Minor cleanups for some MMC3 boards.

- hash/nes.xml
- src/devices/bus/nes/waixing.cpp
- src/devices/bus/nes/waixing.h
Shènghuǒ Huīzhāng - Suǒfēiyà Fùsū (China)
Shènghuǒ Huīzhāng - Suǒfēiyà Fùsū (China, alt)
Shènghuǒ Huīzhāng - Suǒfēiyà Fùsū (China, fixed?)
Shènghuǒ Huīzhāng Wàizhuàn (China)
Shènghuǒ Huīzhāng II Dài (China)
Shènghuǒ Huīzhāng II Dài (China, alt)
Zhēntián Shí Yǒngshì (China)
> bus/nes: Fixed emulation for Chinese Fire Emblem translations.

- hash/fm7_cass.xml
- hash/fm8_cass.xml
- src/mame/drivers/fm7.cpp
This change adds a software list to the Fujitsu FM-8, split off from the FM-7 list. I have included software that was released before the FM-7 itself, and post-1982 software that was explicitly advertised to be FM-8 compatible, using the lists at fm-7.com as reference. Sadly there seems to be a lot of undumped FM-8 (and FM-7) software out there, but this should work as a starting point.
Everything is tested and works on the FM-8 machine in MAME, but there are a couple of cases that still bug me: Sokoban 1 and Portopia are supposed to have FM-8 support, but they fail to load with syntax errors, which usually indicates they are trying to use BASIC 3.0 features that aren't present on the FM-8. They could be later rereleases that removed FM-8 support, but unless someone redumps them from the …
> fm7_cass.xml: split into FM-7 and FM-8 lists

- src/mame/drivers/krz2000.cpp
(Apologies if the format or content of this PR deviates from MAME standards - this is my first pull request to the project and I tried to keep things roughly similar to what I've seen in existing MAME code.)
This PR gets the MAME driver for the Kurzweil K2000 to complete its boot sequence and land on the main UI:
I/O is still not working (no MIDI input), audio output is still not working, etc. Many comments have been left in the code to describe some of the reverse-engineering work undertaken to get things working so far. But it boots!
(cc @d235j, @Lord-Nightmare)
> Get Kurzweil K2000 skeleton driver to boot.

- src/devices/machine/z80scc.cpp
- src/devices/machine/z80scc.h
> If this bit is set to "1," an External/Status interrupt is generated whenever the counter in the baud rate generator reaches "0." This bit is set to "0" by a channel or hardware reset.
Fixes MT 8239, Apple IIgs: Diversi-Tune 1.1 crashes/hangs emulation on song start of playback
https://mametesters.org/view.php?id=8239
It overlaps somewhat with the unused and incomplete Z80SCC_USE_LOCAL_BRG code so I tried to leave that unchanged.
> z80scc: add support for WR15_ZEROCOUNT interrupts.

- src/mame/drivers/pgm2.cpp
This makes a couple of minor updates to the comments on the main PGM2 driver source file.
The comment about the two Japanese games indicates they were only released as a single-board PCB, but the one photo I've found of Ochaken no Puzzle shows a cart in a standard PGM2: https://www.dentsubo.net/~nosuke/diary/diary.html?y=2015&m=1&d=17&n=0&x=5&a=2&mode=comment
I've also added the Japanese spelling for Jigsaw World Arena, based on this AM-NET blog post from when it was location tested: https://blog.am-net.jp/?p=376
> pgm2: update comments

- language/Chinese_Simplified/strings.po
#: plugins/autofire/autofire_menu.lua:93；msgstr "%s [%d Hz]" is changed to msgstr "%s [%g Hz]"
> Update simplified Chinese translation for autofire button name format

- src/mame/audio/cage.cpp
- src/mame/audio/cage.h
- src/mame/drivers/atarigt.cpp
- src/mame/drivers/metalmx.cpp
- src/mame/drivers/seattle.cpp
- src/mame/includes/atarigt.h
Add device_mixer_interface for sound output routines, Add PCB layouts, Add notes
atarigt.cpp,seattle.cpp: Add/Fix sound channel configurations based on operator's manuals, Schematics, Add notes
metalmx.cpp: Move sound channel configurations from cage.cpp, Add notes
> cage.cpp: Add partially support of variable sound output channels

- hash/nes.xml
- src/devices/bus/nes/disksys.cpp
- src/devices/bus/nes/mmc3_clones.cpp
- src/devices/bus/nes/taito.cpp
- src/devices/bus/nes/taito.h
- Fixed address masks for TC0190FMC and X1-005, reflecting hardware pin connections.
- Fixed off-by-one in TC0190FMC+PAL IRQ due to using two's complement instead of one's complement.
> nes/bus: Minor cleanups for Taito boards.

- hash/nes.xml
Tiějiǎ Tújí (China) [ZDog]
Xīnghé Zhànduì (China) [ZDog]
Zhànshén Shìjiè (China) [kmg]
Jiànxiá Qíngyuán (China) [kmg]
Shénmó Dàlù (China) [kmg]
Kǒudài Guàishòu - Fěicuì Bǎn (China) [kmg]
Yǒngzhě Hēi'àn Shìjiè - Hùndùn De Shìjiè (China) [kmg]
> nes.xml: Set correct board type for several more Chinese RPGs.

- hash/apple2_flop_clcracked.xml
- hash/apple2_flop_orig.xml
- hash/apple2gs_flop_orig.xml
Fixed dump of Choplifter, a large number of disk copiers.
> First part of April's Apple II software list updates.

- src/osd/modules/input/input_common.h
- src/osd/modules/input/input_dinput.cpp
- src/osd/modules/input/input_dinput.h
- src/osd/modules/input/input_rawinput.cpp
- src/osd/modules/input/input_sdl.cpp
- src/osd/modules/input/input_sdlcommon.cpp
- src/osd/modules/input/input_sdlcommon.h
- src/osd/modules/input/input_win32.cpp
- src/osd/modules/input/input_x11.cpp
- src/osd/modules/input/input_xinput.cpp
This is the most obvious approach to detecting game controllers being reconnected with SDL.  The trouble is, it behaves badly on Windows SDL builds.
The GUIDs are not unique on Windows – they just contain the bus type, vendor ID and product ID padded out with zeroes.  This means that on Windows, it can’t distinguish between similar controllers being added.  For example if you have more than one of the same kind of controller attached to a hub, and you disconnect and reconnect the hub, the joysticks may come back with different assignments.  This is possibly worse than just not detecting reconnected controllers.  SDL 2.0.14 includes a `SDL_JoystickGetSerial` function, but I don’t want to bump the required SDL version up that high right now.
It does seem to work acceptably on Linux with …
> osd/modules/input: Detect joystick reconnection with SDL

- src/mame/drivers/osborne1.cpp
Partially reverts an old commit from @Robbbert (https://github.com/mamedev/mame/commit/247939853301565efd348cad12b04fc957707bc2) where the floppy device was (mistakenly?) set to FLOPPY_525_QD (quad density) from FLOPPY_525_SSDD (single-sided double-density). 
As far as I am aware, the Osborne1 only supported SSSD and SSDD disks. Revert appears to resolve known Osborne1 issues [5792](https://mametesters.org/view.php?id=5792) (thanks to @Osso13 for pointing this out) and [8100](https://mametesters.org/view.php?id=8100) @cuavas.
> osborne1.cpp: revert floppy device back to SSDD

- src/devices/cpu/mips/mips3drc.cpp
- src/devices/machine/z80scc.cpp
- src/devices/machine/z80scc.h
-z80scc: Removed unused Z80SCC_USE_LOCAL_BRG and simplified WR15_ZEROCOUNT usage to reduce the likelihood of needless timer activation. [Ryan Holtz]
-mips3drc: Additional micro-optimizations to generate_checksum_block. [Ryan Holtz]
> Addressed performance loss from recent z80scc changes

- src/devices/machine/acorn_bmu.cpp
- src/devices/machine/acorn_bmu.h
- src/devices/machine/i2cmem.cpp
- src/devices/machine/pcf8573.cpp
- src/devices/machine/pcf8573.h
- src/devices/machine/pcf8583.cpp
- src/devices/machine/pcf8583.h
- src/mame/drivers/aa310.cpp
i2cmem devices incorrectly ACK all device-ids, not just their own.
Devices based on i2cmem.cpp also do the same.
If they're not selected they also leave the data line low whereas it should be high.
Please note that this fix will probably break any driver which has multiple I2C slave devices on the same bus and combines their data lines by OR'ing them together. They should be AND'ed.
> Only ACK correct I2C device-id

- src/devices/cpu/z80/z80.cpp
- src/devices/cpu/z80/z80.h
- src/mame/drivers/spec128.cpp
- src/mame/drivers/spectrum.cpp
- src/mame/includes/spectrum.h
- src/mame/video/spectrum.cpp
Fixed "floating" int. Now border in demos stays steady and not shaking.
> spectrum48: fix floating int

- src/mame/drivers/xavix2.cpp
Any further fixes to the title screen will require better CRTC emulation.
This fix was found by realizing that the background, which was the only part that required scaling to match hardware, was the only sprite in the list with w and h in the command set to 0x20 instead of 0x10. Guessing that this was some sort of scaling factor turned out to be fruitful.
After the change:
> xavix2: Fix scaling of background in ltv_naru

- src/devices/cpu/z80/z80.cpp
- src/devices/cpu/z80/z80.h
- src/mame/drivers/spectrum.cpp
- src/mame/includes/spectrum.h
- src/mame/video/spectrum.cpp
Removes undesired state variable (m_irq_at) in z80 implementation per @happppp and @angelosa request in #9637
> z80: remove undesired state var in cpu implementation

- src/devices/machine/pcf8593.cpp
- src/devices/machine/x76f041.cpp
- src/devices/machine/x76f100.cpp
- src/devices/sound/mas3507d.cpp
- src/mame/machine/zs01.cpp
I2C slaves should only ACK their own device-id and NAK all others.
SDA output should only change state while clock is low.
Idle state of SDA must be high.
> Added FIXME comments to badly behaved I2C target devices

- hash/nes.xml
- Explicitly set mirroring for hardwired boards (mostly NROM, CNROM, UNROM). Graphics glitches fixed in sets: conquer, dancekar, goldktvp, machridrp, mc_8lm, phantom, rockmanr, seadream.
- Trimmed smaruo's overdumped graphics ROM.
> nes.xml: Various cleanups.

- hash/nes.xml
- ntf2tc1 and modaosyma were overdumps with doubled PRG ROM of their parent sets.
- dreamfgtasd was a multicart extract with extra CHR data from three other games.
- Half of musicboxa's CHR was an overdump that matched half its PRG dump.
> nes.xml: Removed four bad dumps.

- src/mame/drivers/spec128.cpp
- src/mame/drivers/specpls3.cpp
- src/mame/includes/specpls3.h
Makes ula128 test work for spectrum 128, +2 models
+2A, +3 uses same pattern as models above but possibly this test not expected to work on there models - nice to have confirmation from owners of physical devices. 
compare to master:
> spec128.cpp, specpls3.cpp: Added initial bus contention emulation for Spectrum 128+ models

- src/mame/drivers/ksys573.cpp
Delete 'Dance Dance Revolution Kids' and the undumped status, as it is dumped and in the Konami GSAN1 hardware driver.
> Delete DDR Kids from ksys573.cpp

- src/mame/drivers/4enlinea.cpp
- src/mame/drivers/spg2xx_jakks_gkr.cpp
- src/mame/drivers/xavix.cpp
- src/mame/drivers/xavix_2000.cpp
- src/mame/drivers/xavix_2002.cpp
- src/mame/includes/xavix.h
Fix games broken by I2C changes.
Add comment to driver requiring additional I2C device.
> Fix fallout from i2C changes

- src/mame/drivers/spec128.cpp
- src/mame/drivers/specpls3.cpp
- src/mame/drivers/spectrum.cpp
- src/mame/includes/specpls3.h
- src/mame/includes/spectrum.h
- src/mame/machine/tsconf.cpp
- src/mame/video/spectrum.cpp
ZX Spectrum Memory/IO contention finalized for 128/+2 models
refactored memory access gives ~60% performance improvement
> spec128: contention final

- src/devices/machine/6850acia.cpp
Leaving this uninitialized, caused WIP driver to randomly respond to serial terminal when driver is started.
> acia6850: initialize receive section

- hash/ibm5150.xml
The ibm5150.xml list divides games into a "Booter Games" section and a "DOS-based games" section.
The following games are in the "Booter Games" section but are not PC Booter games (they give a "non-system disk" error if you try to run them that way. They can be run through DOS). This PR moves them to the "DOS-based games" and removes the PC Booter usage line from those that have it.
**Hacker
Sex Vixens from Space
World Championship Soccer (both 5.25" and 3.5")
Ancient Land of Ys**
The following games are PC Booter games but are missing the PC Booter usage line, so this PR adds it for them.
**Adventures in Math
Amnesia
Boulder Dash (booter version)
BurgerTime
Earthly Delights
Executive Suite
Inca**
> ibm5150.xml: PC Booter corrections

- hash/dc.xml
- hash/ibm5170_cdrom.xml
- hash/pc8801_flop.xml
- hash/pcecd.xml
- hash/pico.xml
- hash/psx.xml
- hash/smc777.xml
- hash/sms.xml
- hash/x1_flop.xml
- Replaced halfwidth characters (including middle dot) with fullwidth ones.
- Fixed a few alt titles.
> Various software list kana metadata cleanups.

- src/lib/netlist/core/exec.h
- src/lib/netlist/nl_base.cpp
- src/lib/netlist/nl_config.h
- src/lib/netlist/nltypes.h
- src/lib/netlist/solver/nld_solver.cpp
- src/lib/netlist/solver/nld_solver.h
- Reduce the use of macros by converting defines into c++ constants.
- more minor code clean up.
> netlist: more c++, less macros

- src/mame/drivers/ksys573.cpp
-The bottom of the driver says '"Dance Dance Revolution Karaoke Mix (GQ921 VER. JBB)"'
which is hard to deduce as being 'DAM-DDR Dance Dance Revolution for DAM' at the top of the driver.
As such, I've changed it to: "Dance Dance Revolution Karaoke MIX (DAM-DDR)" and "Dance Dance Revolution Karaoke MIX 2nd (DAM-DDR)" based on what I've found on the internet. This name appears to be accurate, at least for the system. The game disc itself doesn't contain the name DAM.
A few sources:
https://remywiki.com/AC_DDR_Karaoke
https://bcaweb.bai.ne.jp/miyooo/ddrd.html
-: In the list, there is a 'P' next to these names, denoting 'plain System573', but according to my first source:
DDR KAraoke "...uses a modified System 573, equipped with four video input/output and a DAM karaoke device."
As such I've …
> Notes/typos + note changes for DDR Karaoke

- hash/a2600.xml
This has its own driver in a2600.cpp
> a2600.xml: Remove "Atari VCS Point-of-Purchase ROM" (nw)

- src/mame/drivers/vigilant.cpp
Following on the closed [PR](https://github.com/mamedev/mame/pull/9695). This has been compiled and works correctly. The timings match the original PCB now.
> Vigilante correct video timings

- src/devices/machine/intelfsh.cpp
This fix running a tool to update flash as on original hardware in my WIP driver.
Before this was failing since it was entering part of code where address is masked but mask was zero
> Fix address mask for SST 39SF040

- src/mame/video/powervr2.cpp
This fixes a few miscellaneous rendering bugs with Naomi1/2 that I noticed while trying to debug my doom port in MAME. 
1. Hooks up non-textured sprite rendering. Not sure why this was excluded (aside from UV stuff not applicable?) since all code worked just fine on hooking up. Without this fix, the boxes behind the next/previous instructions at the bottom of this test code do not appear. With this fix, they appear matching hardware. Also, with fix 2 below they properly render translucently (I don't have any photos of this but I did test on actual HW, demul and MAME and saw them all working identically).
3. Fixes the "enable alpha" bit to enable alpha on base/offset color, with the alpha set to full when unset, and hooked up "disable texture alpha" to disabling texture alpha instead of …
> [powervr2.cpp] Naomi Rendering Fixes

- src/mame/drivers/atari400.cpp
- src/mame/mame.lst
New working clones:
Atari 5200 (2-port) (1983, Atari)
> atari400.cpp: Add 2-port version of a5200; fix ANTIC memory size

- src/mame/drivers/pentagon.cpp
- src/mame/drivers/spec128.cpp
- src/mame/drivers/specpls3.cpp
- src/mame/drivers/spectrum.cpp
- src/mame/includes/spectrum.h
- src/mame/machine/tsconf.cpp
- src/mame/video/agat7.cpp
- src/mame/video/agat9.cpp
- src/mame/video/spectrum.cpp
- src/mame/video/timex.cpp
zx spectrum drivers - restore irq length 32
more precise timings for screen and border updates
simplify current frame shift calculation which improves performance
minor: some states init/save
> zx spectrum drivers - restore irq length == 32 / border timings

- hash/specpls3_flop.xml
- hash/timex_cass.xml
**specpls3**
Spectrum disk version of Comando Tracer has been verified to be the standalone release, so its entry was changed.
Added list of known undumped games and other observations.
**spectrum_cass**
Added two demos and a good dump.
-Shock Megademo (Known dump on the internet was in TAP, so I created this TZX from the "SHOCKSAVER" program in the covertape for Sinclair User 85)
-The Lyra II (Full version, as opposed to the one split across several covertapes)
-Diseñador de Juegos (Microbyte): Replaced bad dump with verified one
**timex_cass**
Added a list of the known covertapes of "Byte Power, 1st Class Magazine" as well as the only known dump.
-Byte Power (February 1988)
**timex_cass and spectrum_cass**
Detected some games published by TMX Portugal but which were actually made for …
> Additions and changes to Spectrum-related softlists

- src/devices/cpu/mips/r4000.cpp
- src/devices/cpu/mips/r4000.h
This change implements boot-mode setting bit 19, TimIntDis/TimerIntDis, which configures if the R4x00 will use IPEX5 as an external interrupt, or as an internal timer using the compare register as the threshold (which is the default). The Sony NEWS NWS-5000X has multiple external timers, including a free-running clock and a hardware clock that drives IPEX2. So, Sony disabled the internal timer using TimerIntDis and repurposed IPEX5 for other things.
Boot-Mode Setting Description:
Block diagram:
Test booting `jazz.cpp` to the WinNT installer, showing that the internal timer is still functional in the default config:
This is another change pulled in from #8854 since that PR is way too big. Apologies for taking so much time to restart the process of breaking it up into smaller, easier to …
> r4000.cpp: Add TimerIntDis mux to IPEX5

- hash/a2600.xml
"Mystique" was a product line, actual publisher was "American Multiple Industries"
> a2600.xml: Fix publishers; mark generalr/westward clones of custer (nw)

- src/mame/drivers/8080bw.cpp
This resolves one of the issues @cuavas brought up in #9149
> 8080bw.cpp: Re-remove cocktail inputs from spaceat2/sinvzen (nw)

- src/mame/drivers/slapfght.cpp
- src/mame/includes/slapfght.h
- src/mame/machine/taito68705interface.cpp
- src/mame/machine/taito68705interface.h
This makes the flip screen DIP switch and cocktail mode work for alcon and slapfigh.  It already worked for slapfigha which uses the same latch output as the other games for this purpose.  Screen flipping still doesn’t work in the bootlegs, but that could well be a real limitation as they lack the MCU (the bootleggers may have been too lazy to hook screen flipping up a different way).
The graphics still have offsets, but at least the offsets look the same between normal and flipped mode now.
> slapfght.cpp: Hooked up flip screen output to MCU for alcon and slapfigh

- src/lib/netlist/.gitignore
- src/lib/netlist/build/makefile
- src/lib/netlist/buildVS/netlistlib.vcxproj
- src/lib/netlist/buildVS/nltool.vcxproj
- src/lib/netlist/buildVS/nltool.vcxproj.filters
- src/lib/netlist/buildVS/nlwav.vcxproj
- src/lib/netlist/core/core_device.h
- src/lib/netlist/core/queue.h
- src/lib/netlist/nl_base.cpp
- src/lib/netlist/nl_interface.h
- src/lib/netlist/nl_setup.cpp
- src/lib/netlist/nltypes.h
- src/lib/netlist/plib/pfmtlog.h
- src/lib/netlist/plib/pmatrix2d.h
- src/lib/netlist/plib/ppmf.h
- src/lib/netlist/plib/ptests.h
- src/lib/netlist/plib/ptypes.h
- src/lib/netlist/prg/nlwav.cpp
- src/lib/netlist/tests/test_pmfp.cpp
- src/lib/netlist/tests/test_pmfp_multibase.cpp
- Fixes compile with apple clang 10
- fix standalone vs 2019 build
- PMF now working properly in VS due to addition of static stub.
- Align syntax in ppmf to MAME delegate.h
There is one use case in netlist using the protected object function.
Once this has been removed, netlist can optionally be compiled with
MAME delegate code.
- Add tests/test_ppmf*.cpp testing examples given in #8590
> netlist: Resolve #8590 and fix #r73625467 (#9751), add tests

- src/mame/drivers/bfcobra.cpp
Interface to slave upd7759 was using start and reset inputs when should've been using mode and reset.
This used to work but recent PR #9614 meant it stopped working.
Change to mode and reset inputs confirmed on schematics.
> Fix interface to upd7759 sounds in brkball

- src/emu/emuopts.cpp
`value()` is using `m_specified` flag internally. Without fix setting bios trough the UI caused selected slot name to be lost.
> Properly set BIOS under slot

- src/mame/drivers/gsz80.cpp
The rc2014mini ROM block got left behind during @mmicko creation of a much more comprehensive RC2014 driver with rc2014.cpp and associated devices.
> Remove vestigial rc2014mini ROM definition from gsz80.cpp

- hash/gbcolor.xml
Added all three prototypes from Kak's attempt to officially remake Green Beret (unrelated to Naps Team's):
- Green Beret (prototype 1) [Kak, retroLEL]
- Green Beret (prototype 2) [Kak, retroLEL]
- Green Beret (prototype 3) [Kak, retroLEL]
> [gbcolor.xml] Added Green Beret prototypes for Game Boy Color

- docs/source/usingmame/defaultkeys.rst
- src/frontend/mame/ui/ui.cpp
- src/frontend/mame/ui/viewgfx.cpp
- src/frontend/mame/ui/viewgfx.h
When viewing decoded graphics tiles, hold Shift while pressing 0/-/= (or whatever you remap them to) to restrict scaling to integer factors.
Also encapsulated things a bit more and made the UI manager hold onto the storage rather than keeping it in file statics.
> ui/viewgfx.cpp: Added ability to restrict tiles to integer scale factors

- src/devices/bus/ieee488/hp9122c.cpp
This adds the default MFM floppy formats to the HP 9122c floppy drive. It allows the HP 9000/3xx machines to actually use the floppy images in the software list, which were failing to load before (loudly or silently, depending on the method used to load them).
HP BASIC and HP Pascal are now bootable from floppy, for example, though HP-UX 5.1 still doesn't work (for unrelated reasons, probably).
> bus/iee488/hp9122c.cpp: Added floppy image formats

- src/mame/drivers/clcd.cpp
Use 1 MHz for the system clock of the Commodore LCD based on hardware and firmware evidence from [Bil Herd's prototype](http://c128.com/commodore-lcd-teardown).  The emulator uses the ROM code dumped from this same prototype.
A [photo](https://flickr.com/photos/mnaberez/31314601462) of Bil Herd's prototype shows a 4.0 MHz crystal above the G65SC102.  It is likely that the crystal is connected to pins 35 (XTLI) and 37 (XTLO).  The [GTE 65SC102 datasheet](http://archive.6502.org/datasheets/cmd_g65scxxx_mpu_family.pdf) says, "the 65SC10X Series is supplied with an internal clock generator operating at four times the Φ2 frequency."  The [Rockwell R65C102 datasheet](http://archive.6502.org/datasheets/rockwell_r65c00_microprocessors.pdf) agrees, saying, "The R65C102 internal clocks may be …
> clcd.cpp: Use 1 MHz for system clock.

- src/mame/drivers/bwidow.cpp
- src/mame/includes/bwidow.h
- src/mame/video/avgdvg.cpp
This change introduces a cabinet type setting which allows Space Duel to be placed into cocktail mode.  When run in a cocktail cabinet, the game:
- Strobes the invert x & invert y outputs to rotate the video 180 degrees.  This is necessary because the monitor in the SD cocktail is mounted upside-down relative to the upright.
- Draws the player 2 score in an orientation where they can be read by the second player, who stands on the opposite side of the cabinet as player one.
In addition to the driver support, I had to implement video flipping in avg_device, as it didn’t support it.
> Add support for Space Duel’s cocktail mode.

- hash/c64_cass.xml
Spindizzy (Electric Dreams) [C64 Ultimate Tape Archive V2.0]
Spitfire Ace (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Split Personalities (Domark) [C64 Ultimate Tape Archive V2.0]
Sprite Man (Interceptor Software) [C64 Ultimate Tape Archive V2.0]
Spy Hunter (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Star Eggs (Mirrorsoft) [C64 Ultimate Tape Archive V2.0]
Star Raiders II: The Great Galactic Adventure Continues (Electric Dreams) [C64 Ultimate Tape Archive V2.0]
Starion (Melbourne House) [C64 Ultimate Tape Archive V2.0]
Stir Crazy Featuring Bobo (Infogrames) [C64 Ultimate Tape Archive V2.0]
Steel (Prism Leisure) [C64 Ultimate Tape …
> c64_cass.xml: Added 10 items (9 working, 1 not working)

- hash/c64_cass.xml
Sky Twice (American Action) [C64 Ultimate Tape Archive V2.0]
Slap Fight (Imagine) [C64 Ultimate Tape Archive V2.0]
Slayer (Prism Leisure) [C64 Ultimate Tape Archive V2.0]
Solo Flight (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Son of Blagger (Alligata) [C64 Ultimate Tape Archive V2.0]
Space Doubt (CRL) [C64 Ultimate Tape Archive V2.0]
Space Harrier (Zafiro Software Division) [C64 Ultimate Tape Archive V2.0]
Space Invasion (Elite Systems) [C64 Ultimate Tape Archive V2.0]
Skyline Attack (Century Software) [C64 Ultimate Tape Archive V2.0]
Snare (Thalamus) [C64 Ultimate Tape Archive V2.0]
> c64_cass.xml: Added 10 items (8 working, 2 not working)

- hash/cdi.xml
I would like to state for the record that I am a absolute moron who didn't know the difference between "SHA1" and "Data SHA1":
$ chdman info -i Link\ -\ The\ Faces\ of\ Evil\ \(USA\).chd
chdman - MAME Compressed Hunks of Data (CHD) manager 0.243 (unknown)
Input file:   Link - The Faces of Evil (USA).chd
File Version: 5
Logical size: 626,501,952 bytes
Hunk Size:    19,584 bytes
Total Hunks:  31,991
Unit Size:    2,448 bytes
Total Units:  255,924
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     116,979,986 bytes
Ratio:        18.7%
SHA1:         63c8ae61d7e98668cb8864b909c7f7377ff5fdb4
Data SHA1:    e9deb9df291474b9a4db2e5ce444bb98c149faa6
Metadata:     Tag='CHT2'  Index=0  Length=93 bytes
TRACK:1 TYPE:MODE2_RAW SUBTYPE:NONE FRAMES:255924 PREGAP:0 P
> cdi.xml: Fixed Link: the Faces of Evil

- src/mame/drivers/jpmsru.cpp
- src/mame/layout/j_ews.lay
- src/mame/layout/j_ewsdlx.lay
- src/mame/layout/j_la.lay
- src/mame/layout/j_lt.lay
- src/mame/layout/j_plus2.lay
- src/mame/layout/j_ssh.lay
- src/mame/layout/j_sup2p.lay
- src/mame/layout/j_super2.lay
- src/mame/mame.lst
- Support for remaining games from the previous SRU skeleton driver
- New games & clones
- Some cleanups (per-game mconfigs replaced with a macro, is that OK?)
> jpmsru: Sort out remaining games, add new ones

- src/mame/drivers/clcd.cpp
Add IEC bus connections to the Commodore LCD based on firmware evidence from [Bil Herd's LCD prototype](http://c128.com/commodore-lcd-teardown) and the [schematics](http://mikenaberezny.com/2008/10/04/commodore-lcd-firmware/) released by Bil.
I disassembled the IEC code in the [KERNAL ROM](https://github.com/mamedev/mame/blob/mame0243/src/mame/drivers/clcd.cpp#L742) to find the connections.  With these additions and the [clock fix](https://github.com/mamedev/mame/commit/33d14d54fe385867790a4c97f42259bdb742599e), IEC almost works but most of the time it locks up.  Since we don't know if the IEC support in the LCD prototype ever actually worked, the problem could be the KERNAL or an emulation bug.
Out of dozens of attempts, I got a disk directory from `c1541` twice.  Since it got that far, …
> clcd.cpp: Added IEC bus connections.

- src/mame/arcade.flt
Removed "Shuttle MS11 PC" computer from Arcade build/Listxml.
> Fixed Arcade build

- hash/n64.xml
Carnivalé - Cenzo’s Adventure (prototype 20000721) [Baker64, Forest of Illusion]
Doubutsu Banchou (Japan, prototype) [Marshall, Olivieryuyu, Baker64]
> n64.xml: Added two unreleased titles.

- hash/c64_cass.xml
Shanghai (Activision) [C64 Ultimate Tape Archive V2.0]
Shirley Muldowney's Top Fuel Challenge (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Side Arms (Go!) [C64 Ultimate Tape Archive V2.0]
Sidewize (Firebird) [C64 Ultimate Tape Archive V2.0]
Sigma 7 (Durell) [C64 Ultimate Tape Archive V2.0]
Silent Service (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Silkworm (Virgin) [C64 Ultimate Tape Archive V2.0]
Siren City (Interceptor Software) [C64 Ultimate Tape Archive V2.0]
Siren City (Datamaxx) [C64 Ultimate Tape Archive V2.0]
Six Shooter (Dixons) [C64 Ultimate Tape Archive V2.0]
Skate Crazy (Gremlin Graphics) [C64 Ultimate Tape Archive V2.0]
Skate or Die (Electronic Arts) [C64 Ultimate Tape Archive V2.0]
New NOT_WORKING …
> c64_cass.xml: Added 13 items (12 working, 1 not working)

- scripts/target/mame/arcade.lua
- src/mame/arcade.flt
- src/mame/drivers/tomsadvs.cpp
- src/mame/mame.lst
Tom's Adventures [Museo del Recreativo]
Ice Cold Beer (ICE) [Museo del Recreativo]
> New NOT_WORKING machines

- hash/c64_cass.xml
Super Cycle (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Super Dogfight (Terminal Software) [C64 Ultimate Tape Archive V2.0]
Super Hero (Codemasters) [C64 Ultimate Tape Archive V2.0]
Super Huey II (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Super Huey UH-1X (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Super Oswald (Silverrock Productions) [C64 Ultimate Tape Archive V2.0]
Super Skramble (Terminal Software) [C64 Ultimate Tape Archive V2.0]
Super Spring (Electric Dreams) [C64 Ultimate Tape Archive V2.0]
Super Stunt Man (Codemasters) [C64 Ultimate Tape Archive V2.0]
Super Trux (Elite Systems) [C64 Ultimate Tape Archive V2.0]
Super Wonder Boy (Activision) [C64 Ultimate Tape Archive V2.0]
Super Zaxxon (U.S. Gold) [C64 …
> c64_cass.xml: Added 14 working items

- hash/ibm5150.xml
The Wizardry IV, Wizardry V and non-alternate Summer Games II entries in this list are for cracked images but not marked as so.
Wizardry IV
Wizardry V
Summer Games II
I followed the convention used for other cracked games in this file, as in
`<info name="cracked" value="demonlord" />`
although I feel "Cracked by" would look better than "cracked" in the MAME UI, and I think "Demonlord" (capitalized) would be correct.
Also Summer Games II has an alternate entry, and that one is not clearly cracked (it does not advertise itself as so, at least), so it seems like it should perhaps be the parent, not the cracked one.
> ibm5150.xml: Mark some cracked images

- src/mame/drivers/su2000.cpp
(this is just info for when someone does start a driver)
-First attempt at listing that there are SU2000 (Stand Up) and SD2000 (Sit Down) models
-Attempt at listing the 2000 platform's software (same base hardware, so each system theoretically runs the same software)
-Added a link to SU2000 Technical Manual
-Listed the main base hardware (shared by SD2000 and SU2000)
> add notes: SD2000 and SU2000 hardware, list of games

- src/devices/bus/rc2014/edge.cpp
- src/devices/bus/rc2014/edge.h
@mmicko there are a couple of typos introduced by da0cf02007ac3e70b4d470fd7f188c5b1274f83d
> bus/rc2014/edge.cpp: Fix typos in comments

- src/devices/machine/dp83932c.cpp
- src/devices/machine/dp83932c.h
This PR has two additions to the SONIC driver:
1. Add support for big endian bus accesses by adjusting the width of the bus access appropriately (In 32-bit mode, descriptors and the RBA must all be aligned to longword boundaries, even when the values are only 16 bit, thus the previous method had issues on BE buses. See pages 7 and 15 in the datasheet)
2. Stop driver from starting a second transaction task if one is already in progress. The datasheet recommends that software which wants to append packets during a transmission send another transmission command to avoid a race condition, and it should do nothing if this command is received while the transfer is still ongoing. NEWS-OS 4.2.1aRD is an example of software that does this. It would hang on boot without this change because the …
> dp83932c.cpp: Support BE mode and transmission packet appending

- src/mame/drivers/supstarf.cpp
- src/mame/mame.lst
supstarf.cpp: Dumped and added a new set of 'Super Star', make it the parent since it's a complete dump.
Super Star (Recreativos Franco, set 1) [jordigahan]
> Dumped and added a new set of 'Super Star'

- src/devices/cpu/mips/r4000.cpp
- src/devices/cpu/mips/r4000.h
Partially implements the secondary cache piece of the CACHE instruction. Only tag manipulation is supported (so this is just a half-step towards a full secondary cache subsystem for this driver), but the benefit is that software that uses the tag to determine how much secondary cache is present will be able to do so (even though the driver will still treat every memory access as a secondary cache hit).
This is useful for emulating devices like the Sony NWS-5000X. The NEWS-OS 4.2.1aRD kernel (which only supports the NWS-5000 series and thus doesn't have to deal with computers that don't have a secondary cache) uses the scache size early in kernel initialization (seems to use it when figuring out the VM page size or something like that). So, this partial implementation is enough to satisfy …
> r4000.cpp: Partially implement secondary cache tag manipulation

- src/mame/drivers/geniusiq.cpp
- src/mame/mame.lst
Dumped ROMs for North American version of PreComputer Unlimited and added it to the driver.  Also fixed parent/clone relationships and re-formatted comments.
PreComputer Unlimited (USA/Canada) [Val Polyakh]
> geniusiq.cpp: Added PreComputer Unlimited (USA/Canada)

- src/emu/sound.cpp
- src/emu/sound.h
The PR address #9917. A save state may occur between time slices.
Sound devices through sound.cpp are updated during a timer call every
20ms. When the state is saved, these devices are not updated to the
current machine time. Consequently after a state load the devices
have a "time lag" since in postload buffer end time is forced to
machine time.
This change will save the last buffer end time so that all outstanding
samples are processed.
This is a core change. I tested it on some drivers. This needs a very
thorough review and I post the PR primarily to document a possible
solution.
> sound.cpp: Fix missed samples due to state save (#9917)

- src/frontend/mame/clifront.cpp
- src/frontend/mame/luaengine.cpp
- src/frontend/mame/mame.cpp
- src/osd/modules/file/posixdir.cpp
- src/osd/modules/file/posixfile.cpp
- src/osd/modules/file/winfile.cpp
- src/osd/modules/file/winrtfile.cpp
- src/osd/modules/render/bgfx/chainmanager.cpp
- src/osd/modules/render/bgfx/effectmanager.cpp
- src/osd/modules/render/bgfx/shadermanager.cpp
- src/osd/osdcore.h
- src/osd/windows/winutil.cpp
It looks like #9859 is not going to be merged anytime soon, so with this PR we do part of the process - updating `osd_subst_env()` for the C++17 era
> Changinging osd_subst_env() to take an std::string_view and return an std::string

- src/devices/sound/315-5641.cpp
- src/devices/sound/315-5641.h
- src/mame/drivers/segapico.cpp
- fix uPD775x type
- enforce "slave" mode (required for manual data stream)
- hook up "PCM FIFO empty" interrupt
> fix Sega Pico PCM playback (MT#08332)

- hash/gameboy.xml
Astérix (earlier prototype) [VGHF, Hidden Palace]
Astérix (early prototype) [VGHF, Hidden Palace]
Asteroids (prototype) [VGHF, Hidden Palace]
Barbie - Game Girl (prototype) [VGHF, Hidden Palace]
Battle Ships (Spain, prototype) [VGHF, Hidden Palace]
Blaster Master Boy (USA, prototype) [VGHF, Hidden Palace]
Bomb Jack (earlier prototype) [VGHF, Hidden Palace]
Bomb Jack (later prototype) [VGHF, Hidden Palace]
Bonk's Adventure (USA, prototype) [VGHF, Hidden Palace]
Bubble Ghost (prototype) [VGHF, Hidden Palace]
Catrap (prototype) [Forest of Illusion, Swanhubstream]
Cosmo Tank (USA, prototype) [VGHF, Hidden Palace]
Dropzone (prototype, alt) [VGHF, Hidden Palace]
Gauntlet II (prototype) [Forest of Illusion, Rezrospect] …
> gameboy.xml: Added 21 more prototypes.

- src/frontend/mame/ui/selgame.cpp
At times std::vector<menu_item> m_items found in src/frontend/mame/ui/menu.h is empty, even after displaying a full list, triggering this assertion:
/usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/include/g++-v11/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = ui::menu_item; _Alloc = std::allocator<ui::menu_item>; std::vector<_Tp, _Alloc>::reference = ui::menu_item&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
> ui/selgame.cpp: Avoid assert in std::vector when no items in menu

- src/mame/drivers/mpu4bwb.cpp
this identifies the settings various sets in mpu4bwb.cpp expect, and configures them better by default.
these don't boot fully without the changes from JW (and one other change) but I've tried to be careful not to stop on any toes while documenting these (I've only touched mpu4bwb.cpp, which he hasn't touched)
> mpu4bwb.cpp - set identification / defaults for booting

- hash/gameboy.xml
The Chessmaster (Japan, prototype) [DillyDylan, Gaming Alexandria]
Out of Gas (prototype) [Forest of Illusion]
Pang (prototype) [Forest of Illusion]
Populous (prototype) [Forest of Illusion]
Prince of Persia (Euro, prototype) [DillyDylan, Hidden Palace]
Riddick Bowe Boxing (USA, prototype) [Rezrospect, Forest of Illusion]
Taz-Mania (Europe, prototype) [Forest of Illusion]
Wordtris (V6 prototype) [Forest of Illusion]
Zoop (prototype) [Rezrospect, Forest of Illusion]
> gameboy.xml: Added nine more prototypes.

- src/mame/drivers/ksys573.cpp
https://callusnext.com/archives/605
`mamboagg` uses the 700B01 BIOS (known as "dsem2" in MAME) on real hardware. The CRC mentioned, `6CF852AF`, also matches the `dsem2` BIOS currently in MAME. The change has no noticeable differences in gameplay.
> ksys573: Use dsem2 BIOS like real hardware for mamboagg

- src/mame/matic/barata.cpp
Appears to have been caused by the cleanup in e6f78d5ed281850d9e8b391c049b8bf696e140bf
> barata.cpp: Restore proper company name

- scripts/genie.lua
Fixes #10011 following a suggestion by @cuavas.
> genie: Explicitly set LinkSupportCircularDependencies for NetBSD

- src/lib/netlist/nl_base.cpp
Code was parsing src/lib/netlist/macros instead of using compiled
version.
> netlist: Fix regression

- src/devices/machine/z80scc.cpp
- src/devices/machine/z80scc.h
This change adds support for using /W//REQ as the RX DMA pin, as well as the /DTR//REQ pin as the TX DMA pin. This allows software that uses both directions simultaneously to function (like Sony NEWS-OS 4.2.1aRD's `esccf` driver on the NWS-5000 series, which uses these pins in conjunction with one of its CXD8442Q WSC-FIFO chips for async serial communication) . 
Note - the ESCC user manual mentions that the /W//REQ and /DTR//REQ pins don't depend on the transmitter enable status, but that is not how the driver was originally coded, so I didn't touch that part, but with this code, /DTR//REQ will not consider the transmitter enable flag to match the spec:
> machine/z80scc.cpp: Implement /W//REQ on receive and /DTR//REQ on transmit

- src/devices/machine/pci.cpp
- src/devices/machine/pci.h
This makes sure that PCI map_extra in device initialization is executed after complete reset of device is performed
> Fix PCI device initialization

- 3rdparty/ymfm/src/ymfm.h
- 3rdparty/ymfm/src/ymfm_adpcm.cpp
- 3rdparty/ymfm/src/ymfm_adpcm.h
- 3rdparty/ymfm/src/ymfm_fm.h
- 3rdparty/ymfm/src/ymfm_fm.ipp
- 3rdparty/ymfm/src/ymfm_opl.cpp
- 3rdparty/ymfm/src/ymfm_opm.cpp
- 3rdparty/ymfm/src/ymfm_opm.h
- 3rdparty/ymfm/src/ymfm_opn.cpp
- 3rdparty/ymfm/src/ymfm_opn.h
- 3rdparty/ymfm/src/ymfm_pcm.cpp
- 3rdparty/ymfm/src/ymfm_pcm.h
- 3rdparty/ymfm/src/ymfm_ssg.cpp
- 3rdparty/ymfm/src/ymfm_ssg.h
Update ymfm library to latest version (a78b567): [Aaron Giles, hyano]
- Fix incorrect operator volumes in some cases for OPL (MT8108)
- Fix PCM playback to cut off previous notes when new waveforms are selected (see dragnblz)
- Fix reversed OPM noise frequency
- Fix bug preventing CSM key ons from being noticed
- Fix bug where SSG EG envelope could be left in inverted state
- Fix SSG envelope handling when tone and noise are off
- Increase strength of DAC discontinuity in YM2612
- Improve latching logic for fnums in OPN
- Increase envelope suppression threshold so some effects don't get prematurely muted
- Improve ADPCM-B behavior at stop/limit addresses (more thorough rewrite here coming later)
> Update ymfm library to latest version (a78b567)

- hash/n64.xml
- Marked Dragon Sword prototypes as bad dumps and noted incorrect sizes.
> n64.xml: Converted ROM sizes to hexadecimal.

- src/mame/atari/nl_stuntcyc.cpp
There's some gross hacks that can be done to make the cycle make it down to the jump and to change the number of buses:
#ifdef STUNT_CYCLE_BUS_COUNT_HACK
CLOCK(BUSES_COUNT_UP, 0.20)  // FIXME: HACK to increase the number of buses on 5 sec period clock
NET_C(BUSES_COUNT_UP.VCC, VCC)
NET_C(BUSES_COUNT_UP.GND, GND)
TTL_74192(B8, GROUND, GROUND, GROUND, P, GROUND, START_Q, BUSES_COUNT_UP, P)  // FIXME: HACK to test buses
#else
TTL_74192(B8, GROUND, GROUND, GROUND, P, GROUND, START_Q, A8_2.Q, P)
#endif
#ifdef STUNT_CYCLE_HORIZ_COUNT_HACK
TTL_7486_XOR(B2_2, DIRECTION_Q, C2_2.Q)  // FIXME HACK: this should be a 7400 NAND, horizontal counting isn't quite working properly.  Leftward movement isn't working.
// without this hack, the bike never will make it down to the ramp level
// with this hack, …
> stuntcyc: fixed up rom addressing so that cycle displays properly

- hash/snes.xml
Doraemon 2 - Nobita no Toys Land Daibouken (Japan, prototype) [atomic]
Gourmet Warriors [NoIntro]
Jelly Boy (prototype) [Hard4Games, snescentral]
Jelly Boy (earlier prototype) [Mark Flitman, snescentral, VGHF]
Jimmy Connors Pro Tennis Tour (Germany, prototype) [snescentral]
Pinkie [NoIntro]
Superman Unfinished Version (demo) [Nostalgia Alley, snescentral, VGHF]
Tinhead [NoIntro]
Total Carnage (USA, prototype 19930610) [snescentral]
> snes.xml: Added nine dumps.

- hash/gameboy.xml
- Corrected deathtrk mistakenly being marked as not supported.
Casper (prototype) [Clarkzer0, Forest of Illusion]
Outburst (Japan, prototype) [Martin Refseth, Forest of Illusion]
Primal Rage (prototype) [JakeS909, drx]
Splitz (prototype) [DillyDylan, drx]
Super Off Road (prototype) [DillyDylan, drx]
> gameboy.xml: Added five prototypes.

- hash/snes.xml
Dragon Ball Z - Final Bout (pirate, hacked) [d4s]
Dragon Ball Z - Final Bout (pirate) [VGHF]
> snes.xml: Added bootleg Dragon Ball Z Final Bout dumps.

- src/devices/machine/6840ptm.cpp
- src/mame/matsushita/duet16.cpp
-duet16: Added external PTM clock. [Ryan Holtz]
-6840ptm: Fixed one-shot behavior and timer enabling when switching to internal clock. [Ryan Holtz]
> Fixed breakage from recent 6840PTM changes.

- src/lib/formats/fs_cbmdos.cpp
This problem was identified because the file system didn't properly show up when the 'c64' driver was run, and this seems to be the correct fix.  The part of this that confuses me is that if this defect was preventing the CBMDOS fs from showing up under c64, why don't the CoCo file systems have the same problem?  Both fs_coco_rsdos.cpp and fs_coco_os9.cpp specify (seemingly incorrectly) SSDD.
> Fixing fs::cbmdos_image::enumerate_f() to properly look for single density (instead of double)

- src/mame/trs/coco.cpp
Adjust CoCo Max 3 hi res adaptor coefficients to better match values from actual hardware. See http://tlindner.macmess.org/?p=885
> coco3: fine tune ccm3 hires adaptor

- hash/ibm5150.xml
Advanced Dungeons & Dragons - DragonStrike (v1.0) [ibmpc5150, archive.org]
Advanced Dungeons & Dragons - DragonStrike (v1.1) [ibmpc5150, archive.org]
Advanced Dungeons & Dragons - DragonStrike (v1.2) [ibmpc5150, archive.org]
Home Alone 2: Lost in New York [ibmpc5150, archive.org]
Pac-Man (Thunder Mountain release) [ibmpc5150, archive.org]
Secret Agent (shareware, $5 Computer Store - Wiz Technology release) [SmartCoda, archive.org]
Temple of Death [ibmpc5150, archive.org]
King's Quest (DOS release) [Gypsy Dave, archive.org]
Redump software list
Home Alone - A Family Game Without the Family [ibmpc5150, …
> ibm5150.xml: 10 new software additions

- src/mame/miltonbradley/vectrex_m.cpp
- src/mame/miltonbradley/vectrex_v.cpp
In commits ca79d71af4b and then 1efbdbf8055, `mame/machine/vectrex.cpp` and `mame/video/vectrex.cpp` changed how the value from via PORTA reaches the mux output with the requisite 8.5us delay.
An unwanted result is that the value _currently_ on PORTA at the time the delay expires is what ends up in the destination, rather than the value that had been in place when the delay started. The effect is that in some circumstances the Y integrator operates with the current X value, to produce output in the game Thrust like [this,](https://drive.google.com/file/d/1jNNX95YxQ2b_LjT31GElsjEAC7HlVa9X/view?usp=sharing) whereas it should look like [this](https://drive.google.com/file/d/1iyoltPLEq-q8JLcpEuIoam3EiTKnEZsS/view?usp=sharing).
> vectrex: Pass the new value with the timer param, so it ends up in the y integrator.

- src/mame/fairlight/cmi.cpp
- Switched to shorter type names.
- Tightened up spacing in function declarations and definitions.
- Removed some now-unnecessary trampoline functions.
- Hooked up Rx and Tx clocks for MIDI port 1; MIDI in/out now works.
> CMI2X: Standards change + MIDI port 1 hookup

- hash/c64_cass.xml
Trantor: The Last Storm Trooper (Go!) [C64 Ultimate Tape Archive V2.0]
Trap (Alligata) [C64 Ultimate Tape Archive V2.0]
TRAZ: Transformable Arcade Zone (Cascade Games) [C64 Ultimate Tape Archive V2.0]
Trio (Elite Systems) [C64 Ultimate Tape Archive V2.0]
Turbo Out Run (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Turrican (Rainbow Arts) [C64 Ultimate Tape Archive V2.0]
Turrican II: The Final Fight (Rainbow Arts) [C64 Ultimate Tape Archive V2.0]
Typhoon (Imagine) [C64 Ultimate Tape Archive V2.0]
Uchi Mata (Martech) [C64 Ultimate Tape Archive V2.0]
The Untouchables (Ocean) [C64 Ultimate Tape Archive V2.0]
> c64_cass.xml: Added 10 working items

- hash/gameboy.xml
- Noted probable underdump of Lunar Chase prototype.
There's one comment line added and three extraneous offsets removed, but otherwise this is all mechanical search and replace. Everything but the commented ROM falls into a handful of power-of-two buckets.
> gameboy.xml: Converted data sizes to hexadecimal.

- hash/gamecom.xml
These are identical to the existing dumps but with initial 256K padding. Sourced from NoIntro.
> gamecom.xml: Replaced three underdumped ROMs.

- hash/mo5_cass.xml
Lower case on "Alt", "Single Tape", "Cracked", "Format" words in the set description.
Removed empty lines.
> mo5_cass: Metadata cleaning

- hash/mo5_flop.xml
Lower case on "Alt", "Hacked", "Format" words in the set description.
Removed empty lines.
> mo5_flop: Metadata cleaning

- src/devices/bus/multibus/isbc202.cpp
- src/devices/bus/multibus/isbc202.h
- src/devices/bus/multibus/multibus.cpp
- src/devices/bus/multibus/multibus.h
- src/devices/machine/i3001.cpp
- src/devices/machine/i3001.h
- src/devices/machine/i3002.cpp
- src/devices/machine/i3002.h
- src/mame/intel/imds2.cpp
- src/mame/intel/imds2ioc.cpp
- src/mame/intel/imds2ioc.h
Hi,
this PR is for a couple of changes to imds2 driver.
- The correct dump for PIO controller has been added
- A regression introduced by 4287970 has been fixed. The iSBC202 floppy controller broke because of this regression.
Thanks.
--F.Ulivi
> Intel MDS-II: correct dump for PIO & regression fixes

- src/mame/sony_news/cxd8442q.cpp
- src/mame/sony_news/cxd8442q.h
- src/mame/sony_news/dmac3.cpp
- src/mame/sony_news/dmac3.h
More split-out commits from the NWS-5000X driver to make it easier to review. This commit implements the SCSI (CXD8403Q DMAC3) and low-speed I/O (CXD8442Q WSC-FIFOQ) DMA controllers used by the NWS-5000 series.
See https://github.com/briceonk/news-os/blob/master/nws5000x-board-pictures.md for pictures.
There is no public documentation about these chips (that I could find, anyways), so the functionality is based on what the monitor ROM and NEWS-OS 4.2.1aRD/FCS#2 do with them.
The DMAC3 is a fairly standard DMA controller with two channels, one per SPIFI SCSI controller. It has the ability to use physical addresses as well as APbus virtual addresses. APbus virtual addresses use the central APbus TLB/map RAM on the platform to map virtual addresses loaded into the `address` register to their …
> dmac3.cpp, cxd8442q.cpp: Implement DMAC3 and WSC-FIFOQ DMA controllers

- src/mame/gaelco/mastboy.cpp
- src/mame/mame.lst
Added comments and reformatted existing single-line ones.
Added placeholders for PLDs.
The Italian sets are not hacks. Gaelco licensed the game to Playmark for the Italian market, so changed the manufacturer accordingly on the Italian sets.
Finally, the Rev A on the piggyback PCB refers to the game revision, not the PCB revision, so, changed the games names removing the "PCB" reference (although all sets are Rev A, even if the game expects a different MCU program version).
------------------------------------
Master Boy (Italian, rev A, set 3) [Recreativas.org]
> mastboy.cpp: Dumped and added a newer Italian set

- src/osd/modules/debugger/debuggdbstub.cpp
The logic was changed to find the first CPU, without any particular expectation about naming.  This should address issue #10141
> Changed gdbstub to no longer expect a CPU named ':maincpu'

- src/mame/galaxian/galaxold.h
- src/mame/galaxian/galaxold_v.cpp
Makes the bullets 2x2 instead of a single pixel so you can see your shots as well as incoming shots.  This makes the games much easier to play.
Don't know if it's accurate, but it seems to work (able to get up to level 4).
some additional discussion at:
https://forums.bannister.org/ubbthreads.php?ubb=showflat&Number=121174#Post121174
> rescue, minefld: make bullets 2x2 pixels instead of a single pixel

- scripts/src/machine.lua
- src/devices/machine/spifi3.cpp
- src/devices/machine/spifi3.h
Another split from #8854 with the HP SPIFI3 emulator. Like most of the custom Sony silicon that the NWS-5000X uses, the SPIFI3 doesn't have much in the way of public documentation. So, this only implements what NEWS-OS uses (although it could be updated to support NetBSD as well, it partially works with NetBSD already but has some LUN issues that NEWS-OS doesn't). Major thanks to Olivier Galibert and Patrick; having the bones of the SCSI state machine from the NCR and CXD SCSI controllers to reference made this way easier than it would have been otherwise :) Can't say I'd be itching to RE another SCSI controller without a datasheet, though...
> spifi3.cpp: Implement HP 1TV3-0302 SPIFI3 SCSI controller

- src/mame/mame.lst
- src/mame/misc/falgas_m89.cpp
The game is a modified version of Konami Hyper Rally for MSX.
Extends the Falgas M89 hardware for kiddie rides with an external video board.
Rally Montecarlo [Museo del Recreativo]
> falgas_m89.cpp: Dumped and added "Rally Montecarlo" for Falgas M89 hw

- hash/c64_cass.xml
Vigilante (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
The Vindicator! (Imagine) [C64 Ultimate Tape Archive V2.0]
Wanderer 3D (Elite Systems) [C64 Ultimate Tape Archive V2.0]
Water Polo (Gremlin Graphics) [C64 Ultimate Tape Archive V2.0]
The Way of the Exploding Fist (Micropool) [C64 Ultimate Tape Archive V2.0]
West Bank (Gremlin Graphics) [C64 Ultimate Tape Archive V2.0]
Western Games (Magic Bytes) [C64 Ultimate Tape Archive V2.0]
Wheelin' Wallie (Interceptor Software) [C64 Ultimate Tape Archive V2.0]
Germany 1985: When Superpowers Collide (Transatlantic Simulations) [C64 Ultimate Tape Archive V2.0]
V (Ocean) [C64 Ultimate Tape …
> c64_cass.xml: Added 13 items (9 working, 4 not working)

- hash/gamate.xml
Lowercase on the "Alt" abbreviation (on sets descriptions)
> gamate.xml: Metadata cleaning

- hash/megaduck.xml
Lowercase on the "Alt" abbreviation (on set description)
> megaduck.xml: Metadata cleaning

- src/mame/atari/a2600.cpp
- src/mame/mame.lst
- Removed some nonexistent inputs from all the TV Boy clones.
TV Boy (PAL) [Thomas Jentzsch, kmg]
> atari/a2600.cpp: Added TV Boy dump.

- hash/vectrex.xml
Lowercase on the "Alt", "Final", "Sample" abbreviations (on sets descriptions)
> vectrex.xml: Metadata cleaning

- src/mame/nintendo/playch10.cpp
- Removed MACHINE_IMPERFECT_GRAPHICS flag from pc_gntlt. [kmg]
- Added MACHINE_IMPERFECT_GRAPHICS flag for pc_cshwk. [Dullaron]
Dumps are identical to the NES version. The PC-10 Gauntlet board is seen with mask roms with identical labels, so this should be correct—Nintendo is fastidious about labeling revisions. The old dump has garbled graphics/text at the bottom of the title screen and possibly other issues. It turns out this was not an emulation bug.
> nintendo/playch10.cpp: Replaced pc_gntlt PRG and CHR dumps.

- hash/snes.xml
DSP1 Tech Demo (USA, prototype)
An identical binary has been dumped from a different prototype board, so this isn't corrupt.
> snes.xml: Promoted dsp1demo to working.

- hash/a2600.xml
- hash/a800.xml
- hash/amigaocs_flop.xml
- hash/apple2_flop_clcracked.xml
- hash/coleco.xml
- hash/ekara_japan_a.xml
- hash/gameboy.xml
- hash/gba.xml
- hash/gbcolor.xml
- hash/megadriv.xml
- hash/msx1_cart.xml
- hash/msx2_flop.xml
- hash/n64.xml
- hash/neogeo.xml
- hash/nes.xml
- hash/pc8801_flop.xml
- hash/pc98.xml
- hash/pce.xml
- hash/psx.xml
- hash/segacd.xml
- hash/snes.xml
- hash/snes_bspack.xml
- hash/specpls3_flop.xml
- hash/tutor.xml
- hash/x1_cass.xml
- hash/x1_flop.xml
Note there's a weird Unicode code point after the word "Turbo" in the second changed line in a800.xml. It has been removed but doesn't show up on GitHub's diff. Same issue in this file popped up in #8112.
> Various software lists: Cleaned up more extraneous spaces.

- hash/nes.xml
- src/mame/mame.lst
- src/mame/nintendo/nes.cpp
- src/mame/nintendo/nes.h
My Computer Terebi C1 [kmg]
The 2C0x palette is the standard one found in PlayChoice-10 and VS. The builtin ROM was in the software list, but the PRG was an overdump (repeated data). I verified the size at least is correct by looking at the PCB.
> nintendo/nes.cpp: Added an RGB Famicom clone.

- src/mame/psikyo/psikyo.cpp
Added on both "Tengai" sets by now, although it was dumped from a World PCB.
> psikyo.cpp: Dumped and added (not hooked up yet) the security PIC for "Tengai" [Caps0ff, Museo Arcade Vintage, ClawGrip]

- scripts/src/formats.lua
- src/devices/bus/ss50/dc5.cpp
- src/lib/formats/all.cpp
- src/lib/formats/cp68_dsk.cpp
- src/lib/formats/cp68_dsk.h
CP/68 is an operating system for the SWTPC 6800 computer which was
published in a book as well as available commercially from the author.
Because the operating system source code was published in the book the
code was OCRed thus reviving the operating system.  This code change
adds the CP/68 disk format which was adjusted by Mike Douglas of
deramp.com to work on real hardware.  The same disk images he published
work with this code change unaltered.
> Adding CP/68 Disk format for SWTPC 6800

- src/devices/imagedev/midiin.cpp
Just so stopping a MIDI file input mid-playback doesn't leave notes hanging on the receiving device. Not sure if this should be tied to another config option or something just so it doesn't risk doing anything weird to non-GM devices, though.
> imagedev/midiin.cpp: send All Notes Off CC when unloading a MIDI file

- src/mame/sony_news/cxd8452aq.cpp
- src/mame/sony_news/cxd8452aq.h
This is the last device needed for #8854 :) The driver implements the WSC-SONIC3, the DMA controller used with a National Semi SONIC ethernet controller for networking on the Sony NEWS NWS-5000 series. It uses the same APbus address translation mechanism as DMAC3.
> cxd8452aq.cpp: Add WSC-SONIC3 DMA controller support

- src/lib/util/cdrom.cpp
- src/lib/util/cdrom.h
This fixes the data roundtrip problem mentioned in https://github.com/mamedev/mame/issues/10230. This does not address the TOC returning `CD_ROM` instead of `CD_ROM_XA` that is mentioned in the same issue.
As a test I used a toc/bin I had on hand and went from bin/toc -> chd -> bin/toc and verified the SHA-1 of the two BINs matched. Additionally, I tried some redump PS1 bin/cue files I had on hand and verified that the SHA-1 resulting of the BIN after doing bin/cue -> chd -> bin/cue matches the file I had on hand and also what was listed on the redump website. (see: https://github.com/mamedev/mame/issues/10230#issuecomment-1215996922)
Additionally, the `phys` parameter of `read_partial_sector` has a default value of `false` which made this bug go unnoticed for a long time. All usages of …
> cdrom: Pass phys flag to read_partial_sector in read_subcode

- src/lib/formats/flex_dsk.cpp
- src/lib/formats/flex_dsk.h
The FLEX 1.0 (MiniFLEX) Operating System for the SWTPC MF-68 Disk System
was released in 1978 and replaced the prior FDOS Operating System.  The
MiniFLEX Disk Format is notably different from later versions of FLEX.
MiniFLEX uses 18 sectors of 128-bytes per track. Later versions of FLEX
used 256-byte sectors.  Disk images from both deramp.com and
https://github.com/rsanchovilla/SimH_cpanel work with this change.
> formats/flex_dsk.cpp: Add FLEX 1.0 (MiniFLEX) Disk Format

- src/tools/chdman.cpp
Fixes issue mentioned in https://github.com/mamedev/mame/issues/10230 where `CD_ROM_XA` is expected but `CD_ROM` is written. Additionally, I implemented the `CD_DA` session type based on the information found in cdrdao.
The logic used follows cdrdao's cue2toc code (https://github.com/cdrdao/cdrdao/blob/3787686d6f49687ce1b553236482078761e511de/trackdb/Cue2Toc.cc#L605-L642) and matches what's written in the man file (https://github.com/cdrdao/cdrdao/blob/3787686d6f49687ce1b553236482078761e511de/dao/cdrdao.man#L458-L466).
Test TOCs can be found on the cdrdao repo: https://github.com/cdrdao/cdrdao/tree/master/testtocs
I tested the following:
- `CD_ROM` is written when there is mode1 tracks but no mode2
- `CD_ROM_XA` is written when there is a mode2 track (converted a PS1 bin/cue -> chd -> …
> chdman: Fix TOC session type detection for extractcd

- src/emu/xtal.cpp
- src/mame/layout/astoneag.lay
- src/mame/layout/dinodino.lay
- src/mame/layout/magibomb.lay
- src/mame/layout/magibombb.lay
- src/mame/layout/showhanc.lay
- src/mame/layout/showhand.lay
- src/mame/layout/skilldrp.lay
- src/mame/layout/winbingo.lay
- src/mame/layout/zoo.lay
- src/mame/mame.lst
- src/mame/misc/astrcorp.cpp
astrcorp.cpp protection and layouts update: [Luca Elia]
* Emulated the "CPU Code" protection in newer games (astoneag, dinodino, hacher, magibombd, winbingo, winbingoa, zoo).
* Expanded ROM patches to work around imperfect data in the first 0x400 bytes (ROM overlay?), getting all games to boot.
* Implemented 16x32 sprites in astoneag.
* Created layouts and factory defaults EEPROMs for all sets.
* showhand: Fixed regression that caused the new opponent face to be invisible while entering the screen.
Machines promoted to working
Magic Bomb (Ver. L3.5S) [Luca Elia, Ivan Vangelista, Angelo Salese, Phil Bennett, Cristiano MDQ]
Dino Dino (Ver. A1.1, 01/13/2005) [Olivier Galibert, Luca Elia, Ivan Vangelista, Guru]
Stone Age (Astro, Ver. EN.03.A, 2005/02/21) [Olivier …
> astrcorp.cpp protection and layouts update

- hash/channelf.xml
- Lowercase on descriptive text on words like "Prototype", "Alt", "Final", "Older"
- Replaced countries abbreviations by their full name
> channelf.xml: Metadata cleaning

- src/devices/machine/8530scc.cpp
- src/devices/machine/8530scc.h
- Also fix baud counter registers
Reference: http://www.zilog.com/docs/serial/ps0117.pdf
The X68000 uses the Clock Mode feature of the SCC, which multiplies the baud period by 16. Combined with a bug that read the baud counter from the wrong registers, this meant the emulator had two baud rate expiry callbacks running at some MHz.
The x68k driver doesn't implement RS232 and doesn't yet use the SCC IRQs for mouse updates, so this doesn't yet affect the driver directly, but it does improve performance.
> machine/8530scc.cpp: Implement SCC baud rate calculation

- src/mame/sega/model3.cpp
The US Title (Sega Super GT) is known to exist on most (but not all) sets via service mode when you change region settings.
> sega/model3.cpp: Add US Title to most Scud Race sets.

- src/devices/machine/ds1207.cpp
rtc_clock_updated() wrongly declared and initialised a local variable m_startup_time when it should've been initialising the global m_startup_time.
Thanks to smf for spotting this.
> DS1207: Fix initialisation of start time

- hash/nes.xml
- src/mame/nintendo/nes.cpp
- src/mame/nintendo/playch10.cpp
- src/mame/nintendo/vsnes.cpp
nintendo/nes.cpp: Mark famitvc1 as not working.
nes.xml: Mark shinsend as not supported.
> nintendo/playch10.cpp: Minor bug fix and MMC1 cleanup.

- hash/monon_color.xml
A QoL fix rather than anything else
4+ years ago, when I originally translated them, 赛尔号 didn't have an English name. That has changed since then. I overlooked Roco Kingdom as well, so that has been fixed.
The capitalization issues were also bugging me, so I fixed those.
I didn't touch the software names as I was unsure if changes would be needed or not.
> Correct the English translations of Monon Color games

- hash/kpython2.xml
- src/mame/arcade.flt
- src/mame/konami/kpython.cpp
- src/mame/konami/kpython2.cpp
- src/mame/mame.lst
kpython and kpython2 share nothing in common besides the fact that they're PS2-based so I split kpython2 into its own driver. 
The HDD images were made by installing the game data onto a fresh HDD. All HDDs have been tested to make sure they boot properly and the ROM check in the operator menu returns OK (small exception: Thrill Drive 3 doesn't have a ROM check function but does have a data check during boot). However, because these are not HDD dumps straight from a real machine, I have marked them as `BAD_DUMP` so they can be replaced in the future if someone has the means to make proper dumps from a real machine. Likewise, the dongle files are generated using custom tools so they're marked as `BAD_DUMP` in case someone can replace them with real dongles dumps, but the dongle payload is …
> kpython2: Add new skeleton driver

- src/mame/mame.lst
- src/mame/misc/magicard.cpp
TeamEurope pointed out that some of the Magic Card game names were incorrect, these have now been fixed.
Now the names are correct some of the romset names are obviously wrong.
Could someone give me guidance on what the romset names should be please as I'm really not sure.
For the Magic Card games there is the following (grouped together for easier reading)
magicard	"Magic Card (v2.01)"
magicarda	"Magic Card (v1.5 17.12.93, set 1)"
magicardb	"Magic Card (v1.5 17.12.93, set 2)"
magicarde	"Magic Card Export 94 (v2.11a, set 1)"
magicardea	"Magic Card Export 94 (v2.11a, set 2)"
magicardf	"Magic Card Export 94 (V2.11a, set 3)"
magicardeb	"Magic Card Export 94 (v2.09a)"
magicardec	"Magic Card III Jackpot (V4.01 6/98)"
magicardj	"Magic Card III Jackpot (V4.01 7/98)"
unkte06	"Magic Card (v1.10 …
> Corrected Magic Card game names

- src/devices/sound/pokey.cpp
- src/devices/sound/pokey.h
The implementation changes come from the [A7800 project](https://github.com/7800-devtools/a7800).
Here's a sample from the homebrew Atari 7800 game ["E.X.O."](https://forums.atariage.com/topic/309450-exo-done/), whose soundtrack relies on accurate Pokey behavior. Listen especially from 14 seconds onwards.
[MAME 246](https://drive.google.com/file/d/1jXkBVrWstuLKMB8uP18x7I3kuSMJ5m87/view?usp=sharing).
[MAME with changes](https://drive.google.com/file/d/1jZ2V-Ey5fESXG-k-jpwmijSGv8t0B1cA/view?usp=sharing).
@schnitzeltony
@msaarna
> Improve accuracy of pokey emulation.

- src/mame/seibu/raiden.cpp
Also documented the values of 0x1fffd and 0x1fffe in the sets which didn't have them. I'm unsure whether to actually document them, as the value after decryption changes for some sets.
> raiden.cpp: Document the configuration bytes, convert comments to cpp-style

- hash/c64_cass.xml
Willow Pattern (Firebird) [C64 Ultimate Tape Archive V2.0]
Winter Camp (Thalamus) [C64 Ultimate Tape Archive V2.0]
Winter Games (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
Winter Olympiad 88 (Tynesoft) [C64 Ultimate Tape Archive V2.0]
Wiz (Melbourne House) [C64 Ultimate Tape Archive V2.0]
Wizardry (The Edge) [C64 Ultimate Tape Archive V2.0]
Wizball (Ocean) [C64 Ultimate Tape Archive V2.0]
Wonder Boy (Activision) [C64 Ultimate Tape Archive V2.0]
World Championship Soccer (Elite Systems) [C64 Ultimate Tape Archive V2.0]
World Class Leader Board: The Ultimate Golf Challenge (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
World Cup Carnival (U.S. Gold) [C64 Ultimate Tape Archive V2.0]
World Games (U.S. Gold) [C64 …
> c64_cass.xml: Added 16 items (15 working, 1 not working)

- src/mame/technos/renegade.cpp
This is a stopgap solution until #10163 is resolved.
> technos/renegade.cpp: More sprite RAM to fix flickering regression.

- hash/fmtowns_flop_misc.xml
- hash/fmtowns_flop_orig.xml
- Redumped Irium from the original disks, and removed the current entry in fmtowns_flop_misc.xml which was created from loose files [cyo.the.vile]
- Redumped disk A of Youjuu Club Custom from an unmodified disk with no saves [cyo.the.vile]
:LOOP - Izanai no Kaikiten [cyo.the.vile]
Disk Megastore Volume 1 [cyo.the.vile]
Power DoLLS S-Premium Disk [cyo.the.vile]
You-Jong Part I [cyo.the.vile]
> fmtowns_flop_orig.xml: 4 new dumps, 2 replacements

- src/mame/konami/ksys573.cpp
This isn't exactly a new clone but just a new dump for an existing game so I wasn't sure how to write the commit message for the readme. Please credit this dump to Taro.
This PR is for the proper audio CD for the Japanese-only release of Drummania + also cleared up some confusion about the b02 disc. The b02 disc is the all-region version. The JAD disc is a real upgrade disc and not a bootleg.
From a brief comparison, it appears that the big difference between the audio CD for a02 and b02 is there is an extra track at the end of b02 that has the practice track in English. The track ordering seem to be otherwise the same.
> ksys573: Add 811jaa02 audio CD for drmna

- src/mame/konami/kpython2.cpp
- src/mame/mame.lst
This completes the Python 2 library as far as having at least one version of every game on the platform. The only thing left is any unknown/undumped regional variants (English version of Thrill Drive 3?) and undumped datecodes/updates (GFDM V initial release, and any other online updates).
New machine marked NOT_WORKING
DANCE 86.4 FUNKY RADIO STATION (E01:J:A:A:2005040400) [Taro]
> kpython2: Add Dance 86.4 Funky Radio Station

- src/mame/samsung/dvd-n5xx.cpp
-noted more Nuon models: Samsung DVD-N705, Oritron DVD900, Motorola Blackbird, RCA (Thomson multimedia) DRC480N
> Added notes of Nuon console models

- hash/gbcolor.xml
Antz (Europe, prototype) [VGHF, Hidden Palace]
Beach'n Ball (Europe, prototype, 20001121) [VGHF, Hidden Palace]
Bob et Bobette - Les Dompteurs du Temps ~ Suske en Wiske - De Tijdtemmers (Europe, late prototype) [VGHF, Hidden Palace]
Die Maus (Europe, prototype) [VGHF, Hidden Palace]
Die Maus - Verrückte Olympiade (Germany, prototype) [VGHF, Hidden Palace]
Driver (Europe, prototype) [VGHF, Hidden Palace]
Klustar (Europe, prototype, 19981001) [VGHF, Hidden Palace]
Klustar (Japan, prototype, 19981001) [VGHF, Hidden Palace]
Looney Tunes Collector - Martian Alert! (Europe, prototype) [VGHF, Hidden Palace]
Lucky Luke - Desperado Train (Europe, prototype) [VGHF, Hidden Palace]
Moomin no Daibouken (Japan, prototype) [VGHF, …
> gbcolor.xml: Added 18 prototypes (15 working, 3 not working).

- scripts/src/formats.lua
- src/devices/bus/ss50/dc5.cpp
- src/lib/formats/all.cpp
- src/lib/formats/fdos_dsk.cpp
- src/lib/formats/fdos_dsk.h
The FDOS Operating System was released by SWTPC in 1977 along with the
MF-68 Mini Disk System and was superceeded by FLEX a few months later.
This change adds support to boot FDOS on the SWTPC 6800 machine in MAME
using a specific disk image (FDOSMPS.DSK) from deramp.com (Mike Douglas)
and can also read/write the other available disk images.
> Add FDOS disk format for the SWTPC 6800

- src/devices/cpu/m6502/n2a03.cpp
- src/devices/cpu/m6502/n2a03.h
- src/devices/sound/nes_apu.cpp
- src/devices/sound/nes_apu.h
- src/devices/sound/nes_defs.h
- src/mame/mame.lst
- src/mame/nintendo/cham24.cpp
- src/mame/nintendo/famibox.cpp
- src/mame/nintendo/multigam.cpp
- src/mame/nintendo/nes.cpp
- src/mame/nintendo/nes.h
- src/mame/nintendo/nes_arcade_bl.cpp
- src/mame/nintendo/nes_clone.cpp
- src/mame/nintendo/playch10.cpp
- src/mame/virtual/vgmplay.cpp
This fixes several audio bugs with the noise channel in VS. System games. The most noticeable ones I've found are:
- high pitch sound in vsgshoe percussion track
- jet sounds in bnglngby
- number of tanks killed count screen in btlecity
- nvs_platoon's bullet and enemies dying sounds are subtly changed
> nes_apu.cpp: Added earliest hardware variant of 2A03 APU.

- src/emu/video.cpp
Fixes the contiguous text when unthrottled and %FPS > 999. I can't be the only one annoyed by this?
> emu/video.cpp: Added a space before %FPS in speed text.

- src/mame/bfm/bfm_sc2.cpp
- fix upd7759 sample triggering in bfm_sc2.cpp (MT 8325) [Paul-Arnold]
- made the volume ramp a little less aggressive
> fix upd7759 sample triggering in bfm_sc2.cpp (MT 8325) [Paul-Arnold]

- src/mame/bfm/bfm_sc2.cpp
Although #10319 fixed the problem of sample triggering in the bfm_sc2 driver it wasn't the correct solution :(
This correctly fixes the triggering.
The number of samples was also restricted to 64 but should be 128.
The upd7759 reset signal is controlled by a single bit rather than a byte.
> fix bfm_sc2 upd7759 sample triggering and reset control

- src/devices/bus/nes_ctrl/fckeybrd.cpp
- src/devices/bus/nes_ctrl/fckeybrd.h
- Allows Lode Runner to successfully detect keyboard, enabling save/load menu options.
- Also fixes Castle Excellent save/load menu.
> bus/nes_ctrl: Minor fixes for Famicom Keyboard and Data Recorder.

- hash/cdi.xml
Removed the "[DVC enhanced]" in descriptions, since the info `compatibility` tag already tells that.
> cdi.xml: Metadata cleaning

- src/mame/midway/vegas.cpp
sf2049se boot ROM dump is not bad, POST checksum failing is correct as verified by dumping several original U27 chips
> Remove BAD_DUMP marker on sf2049se U27

- src/mame/nintendo/n64_v.cpp
RDP primitives can span 4096 rows, not 2048.
> n64: fix stack buffer overflow

- hash/nes.xml
- src/mame/mame.lst
- src/mame/nintendo/nes.cpp
- src/mame/nintendo/nes_m8.cpp
- src/mame/nintendo/nes_m82.cpp
Nintendo M8 Game Selectable Working Product Display (US, set 3) [kmg, Voodooween, Forest of Illusion, Fiskbit]
Nintendo M8 Game Selectable Working Product Display (US, set 2) [kmg]
Nintendo M8 Game Selectable Working Product Display (US, set 1) [kmg]
nintendo/nes_m82.cpp: Moved m82 to separate source file and added partial implementation. Added missing graphics ROM. Got rid of m82p for now.
nintendo/nes.cpp: Corrected name of "Twin Famicom". Switched famitvc1 to use older RP2A03.
> New working machines

- hash/c64_cart.xml
- Use lowercase for descriptive text in descriptions ("Alt", "Prototype").
- Replaced the country abbreviations by the full names.
> c64_cart.xml: Metadata cleaning

- hash/a2600.xml
Climber 5 (NTSC) [AtariAge]
Climber 5 (PAL) [AtariAge]
Gunfight (NTSC) [AtariAge]
Gunfight (PAL) [AtariAge]
Jammed [AtariAge]
Marble Craze (NTSC) [AtariAge]
Marble Craze (PAL) [AtariAge]
Oystron [AtariAge]
Qb (NTSC) [AtariAge]
Qb (PAL) [AtariAge]
Seawolf (NTSC) [AtariAge]
Seawolf (PAL) [AtariAge]
Space Instigators [AtariAge]
Star Fire (NTSC) [AtariAge]
Star Fire (PAL) [AtariAge]
Synthcart [AtariAge]
Testcart [AtariAge]
Thrust+ - D.C. Edition [AtariAge]
Thrust+ - Platinum Edition [AtariAge]
> a2600.xml: Added 19 homebrew cartridges.

- src/osd/modules/diagnostics/diagnostics_win32.cpp
Restore necessary const qualifier removed by 0055a33e81b60284c6390e9c73db9fcb19b8ce8b
> diagnostics: fix clang Windows build

- src/devices/machine/wd1000.cpp
Currently the code for the WD1000 controller is using resolve() for its interrupt callback. This changes it to use resolve_safe() to prevent crashes for devices that do not set an interrupt callback.
> wd1000: use resolve_safe for m_intrq_cb

- scripts/src/bus.lua
- src/devices/bus/epson_qx/option.cpp
- src/devices/bus/epson_qx/sound_card.cpp
- src/devices/bus/epson_qx/sound_card.h
This patch adds a YM2149 based sound card to the Epson QX-10.
> qx10: Add YM2149 based sound card to the Epson QX-10

- src/mame/namco/namcos23.cpp
- Properly mapped H8 ADC ports to namcos23.cpp
- Added complete input configs for rapidrvr, finfurl, downhill, timecrs2 and 500gp. All these games can coin up and have working analog ports (be sure to calibrate them in service mode).
- Added placeholder I/O ports for the default 's23' input port config. It's roughly translated from previous input port configs. Games using this should coin up the day they properly reach attract mode.
- Added a hacked H8 I/O firmware that replaces the JVS ID with that used in an FCA pcb for 500gp and aking (though 500gp doesn't need it). aking can properly go past its second I/O check only to shortly freeze afterward (anyone against this? please let me know.).
- Changed machine configs to reflect current changes.
- Updated TODO.
> namcos23.cpp: Start on completing I/O configs for some games.

- src/mame/sega/sega16sp.cpp
This simplifies the code to make it more readable
- There is no +1 or -1 in the data[7] assignment
- The flip/no flip cases are combined
- The meaning of "flip" is clearly stated
- The long line with multiple statements is broken into several lines
- It's shorter, even after expanding that long line
- Corrects the wrong "four pixels" comment (should be eight)
Tested with _Out Run_ and _After Burner_.
> Out Run: simpler sprite logic 

- hash/ekara_japan_s.xml
the observed crash happens even with the original cartridge this was dumped from, and seems a bit too obvious to have not been caught, so most likely bitrot.
> ekara_japan_s.xml: Mark sc0008 as a bad dump as it needs double checking against a second cartridge

- src/emu/emuopts.cpp
- src/emu/softlist_dev.cpp
- src/emu/softlist_dev.h
- src/frontend/mame/clifront.cpp
- src/frontend/mame/infoxml.cpp
- src/lib/util/corestr.cpp
- src/lib/util/corestr.h
- Changed parameters from `const char *` to `std::string_view`
- Removed 16-character limit in `core_strwildcmp()`
I do not like how in practice, the implementation of `core_strwildcmp()` is a copy-and-paste from `core_stricmp()`, but it seems better to do that then it is to do what the old code did, and copy the arguments to temporary buffers
> Modernize core_strwildcmp() and core_iswildstr()

- hash/gbcolor.xml
Alone in the Dark - The New Nightmare (Europe, prototype) [VGHF, Hidden Palace]
Dragon Ball Z - Densetsu no Chou Senshi-tachi (Japan, prototype, cheats enabled) [VGHF, Hidden Palace]
Dragon Ball Z - Densetsu no Chou Senshi-tachi (Japan, prototype) [VGHF, Hidden Palace]
Dragon Ball Z - Guerreros de Leyenda (Spain, prototype) [VGHF, Hidden Palace]
Dragon Ball Z - Guerreros de Leyenda (Spain, prototype, all features unlocked) [VGHF, Hidden Palace]
Dragon Ball Z - I Leggendari Super Guerrieri (Italy, prototype) [VGHF, Hidden Palace]
Dragon Ball Z - Legendäre Superkämpfer (Germany, prototype) [VGHF, Hidden Palace]
Dragon Ball Z - Legendäre …
> gbcolor.xml: Added 12 prototypes (11 not working).

- hash/lynx.xml
Cabal (prototype) [MacRorie, The Brewing Academy, Atari Gamer]
Daemonsgate (USA, prototype, alt) [MacRorie, The Brewing Academy, Atari Gamer]
Eye of the Beholder (USA, prototype) [MacRorie, The Brewing Academy, Atari Gamer]
Friendly (prototype) [MacRorie, The Brewing Academy, Atari Gamer]
Full Court Press (prototype) [MacRorie, The Brewing Academy, Atari Gamer]
Geoduel (prototype) [MacRorie, The Brewing Academy, Atari Gamer]
Guardians Storm Over Doria (prototype) [MacRorie, The Brewing Academy, Atari Gamer]
Guardians Storm Over Doria (prototype, alt) [MacRorie, The Brewing Academy, Atari Gamer]
Loopz (USA, prototype, 19920916) [MacRorie, The Brewing Academy, Atari Gamer]
Marlboro Go! (Germany, prototype) [MacRorie, …
> lynx.xml: Added 19 prototypes.

- src/mame/sinclair/pentevo.cpp
newer non FE ROM better candidate for default
> sinclair/pentevo.cpp: Changed default BIOS to non-FE ROM 0.59.04

- .github/workflows/ci-linux.yml
- .github/workflows/ci-macos.yml
- .github/workflows/ci-windows.yml
- src/mame/tiny.lst
* Changed Linux GCC build to use the tiny subtarget.
* Added chdman and unidasm executables to artefacts.
This should still have reasonable coverage, with a bit less resource usage on Linux runners:
* We get a full GCC/libstdc++ build from the Windows GCC build.
* We get a full clang/libstdc++ build from the Linux clang build.
* We get a full clang/libc++ build from the macOS clang build.
We’re already building all the tools in every build, but none of them are currently included in artefacts.  This adds unidasm and chdman to artefacts.  I figure unidasm is the most likely to be changed, given disassemblers are worked on rather frequently, and chdman has a life outside MAME.
> Adjusted GitHub CI workflows:

- src/frontend/mame/ui/selgame.cpp
In #8674,  added UI for selecting localised system names.
But still missing in Favorites.
> ui: Add support for shows localised system name in Favorites.

- src/devices/machine/wd_fdc.cpp
- src/devices/machine/wd_fdc.h
In a couple cases the WD FDC looks at the data_reg after hitting an FM sync.  But the data_reg isn't necessarily valid.  Adding extra_data_reg() fixes this.
Also, the READ TRACK was not looking at all possible FM marks for sync.
> FDC FM sync fix

- hash/lynx.xml
Replaced the "Euro" abbreviation by "Europe"
> lynx.xml: Metadata cleaning

- hash/nes.xml
Replaced the "Euro" and "Kor" abbreviations by the full names.
> nes.xml: Metadata cleaning

- src/mame/igs/pgm.cpp
- src/mame/igs/pgmprot_igs027a_type3.cpp
- src/mame/mame.lst
The board features a v100-stickered M68k ROM and a v104-stickered U26 ARM ROM. I dumped this from a China-region cart.
> pgm: add theglad104

- src/frontend/mame/luaengine_input.cpp
Noticed that the items table was getting shorted by 1 item:
before: (missing BUTTON8)
[MAME]> lastitem = manager.machine.input.device_classes["joystick"].devices[2].items
[MAME]> for a,b in pairs(lastitem) do print(a,b,b.name,b.current,b.token) end
129	sol.input_device_item*: 0x561402611f08	Button 1	0	BUTTON1
130	sol.input_device_item*: 0x5614026058a8	Button 2	0	BUTTON2
131	sol.input_device_item*: 0x5614026058e8	Button 3	0	BUTTON3
132	sol.input_device_item*: 0x561402649d38	Button 4	0	BUTTON4
133	sol.input_device_item*: 0x561402649d78	Button 5	0	BUTTON5
134	sol.input_device_item*: 0x561402636f28	Button 6	0	BUTTON6
135	sol.input_device_item*: 0x561402636f68	Button 7	0	BUTTON7
121	sol.input_device_item*: 0x561402617438	A1	0	XAXIS
122	sol.input_device_item*: 0x561402617478	A2	0	YAXIS
123 …
> luaengine_input.cpp: fix input_device_type items upper bound

- src/mame/namco/galaga.cpp
I was going to dump this version a few months ago because I got a PCB with it, but I forgot about it until now. Anyways, I can verify that the PROMs are the same as on the other revisions. The only thing of note is that BOS1-3 and BOS1-4 on my PCB have swapped labels, but the data was correct for the board location. Considering that my BOS1-6 also has an upside label, I am going to assume that it was just a label mistake.
> Mark new bosco parent set PROMs as good

- src/emu/sound.cpp
The user can still lower it if needed (probably rare these days?), but in case it was needed to be higher, there was no way to increase it.
When using lua instead of OSD to obtain samples, we don't need sound output, but we need decent samplerate.
> Don't force lower samplerate for `-sound none`

- src/mame/midway/seattle.cpp
1997, not 1987 on the description.
> midway/seattle.cpp: blitz typo fix.

- src/mame/msx/msx2.cpp
msx2.cpp: Fix sha1 copy/paste mistake for nms8245. Removed duplicate rom entries on y503iiir and y503iiire.
> msx2.cpp: Fix rom definitions for nms8245, y503iiir and y503iiire.

- src/mame/taito/tc0100scn.cpp
- src/mame/taito/tc0100scn.h
Caused by https://github.com/mamedev/mame/pull/5207/files#diff-d1157515ada7840f50c950748ba77671119be687fda8d13dfc3c99291f470170L269
- taito/tc0100scn.cpp: removed `set_color_base` setter since it's unused.
> taito/tc0100scn.cpp: fix longstanding color regression with wgp

- hash/gameboy.xml
Altered Space - A 3-D Alien Adventure (USA, prototype, 19910215) [SteelGeneral, Forest of Illusion]
I've marked this as partial because all of its clones are marked partial. I'm not sure if/when there are issues with MAME's emulation for this game. There's this [page](https://mgba.io/2017/05/29/holy-grail-bugs/) which describes issues related to the edge-triggered STAT IRQ. MAME doesn't have the glitches in the screenshot shown there, so maybe things are all good? Or maybe there are yet more subtle issues for this title? I'll leave it to somebody more knowledgeable about the GB drivers to say whether the "partial" flags can be removed here.
> gameboy.xml: Added a prototype.

- src/devices/bus/gio64/newport.cpp
- src/devices/bus/gio64/newport.h
In REX3, iterator setup should be a dedicated operation that is only execuated if
a). A Draw command is execuated with DoSetup at DRAWMODE0 set or
b). A host write is issued to SETUP register
At setup stage REX3 will calcuate quadrant for a block or span drawcall or octant together with some Bresenham parameters for a line drawcall.
Linux newport_con driver is rely on this behavior to use quadrant calculated by previous draw call to render characters.
Fixes: #9667
Now Debian installation disk seems display properly:
> newport: Split out iterator setup stage

- src/mame/olympia/portrait.cpp
- src/mame/olympia/portrait.h
- src/mame/olympia/portrait_v.cpp
- Make color palette to be b&w for the time being, being more visible to the eye than the previous washed out attempt;
- mask sprite area against defined playfield clip rectangle;
- fix global sprite Y positions, they mostly follow up current scroll value except for some edge cases;
- attempt to fix sprite priorities;
- make tilemap bank more logical (?) bitwise;
> olympia/portrait.cpp: apply some WIP cleanups, make it playable

- src/devices/cpu/e132xs/e132xsfe.cpp
-e132xsfe.cpp: Fixed missing bit mask causing UBSAN warnings. (Github #10502) [Ryan Holtz, Oliver Stöneberg]
> Fixed missing bit mask in e132xsfe.cpp causing UBSAN warnings

- src/devices/machine/jvshost.cpp
The size of the encoded packet returned by the `encode` function was off by the number of bytes that were escaped. This issue is only seen when a raw packet includes bytes that need to be escaped (0xd0 or 0xe0).
The `add` variable is added to the output `size` variable after the loop but since the `add` variable is directly decremented every time a byte is escaped in the loop, the final `size += add` turns into `size += 0`.
> jvshost: Fix size of encoded packet with escaped bytes

- src/mame/konami/hornet.cpp
- src/mame/konami/k573mcal.cpp
The JVS code in hornet seems to predate `jvs_host` so I ripped out the old code and replaced it with an equivalent using `jvs_host` to allow for hooking up a `jvs_device`-based JVS device as well as get rid of some duplicated logic.
Gradius 4 with the [Master Calendar JVS device](https://github.com/mamedev/mame/blob/master/src/mame/konami/k573mcal.cpp) as well as a stubbed Windy 2 JVS I/O device (identifies as `KONAMI CO.,LTD.;Windy2;Ver1.0;Windy2 I/O Ver1.0`) were used for testing.
I also tested gradius4, nbapbp, terabrst, thrilldbu, sscope, sscope2 to make sure they were still booting without a JVS device hooked up.
> hornet: Replace JVS impl with jvs_host device

- hash/msx1_cart.xml
I wanted to make it easier to run the various flavors of msxlogo.  The current softlist only contains the NL version.
There are a few that aren't included but I wasn't able to locate them (DE, IT, JP etc).
Full list at https://www.generation-msx.nl/company/lcsi/1224/software/
> msx1_cart.xml: added msxlogo uk, es, ar, br, pl and renamed nl

- src/osd/osdsync.cpp
For platforms which do not support threads (i.e. emuscripten), queue->thread might not have any work_thread_info's added to it. This is bad as osd_work_item_queue_multiple will access queue->thread[0] when queue->threads == 0, and subsequently crash as the queue has no items in it.
> Ensure queue->thread will have at least 1 work_thread_info in it

- hash/ibm5150.xml
- hash/ibm5170.xml
Best of the Best: Championship Karate (Spain, PC Games release) [AbandonSocios]
Fleet Defender [The Good Old Days]
RoboSport (3.5" DD) [The Good Old Days]
RoboSport (5.25" HD) [The Good Old Days]
The Humans: Insult to Injury (France) [The Good Old Days]
The Humans: Insult to Injury (Spain, PC Games release) [AbandonSocios]
Moved from ibm5150 Software List
Both "Nova 9" games requires hard disk installation and EGA or VGA graphic card ([box cover info](https://www.mobygames.com/game/dos/nova-9-the-return-of-gir-draxon/cover-art/gameCoverId,223398/)) 
Nova 9: The Return of Gir Draxon (v1.1, 3.5" DD)
Nova 9: The Return of Gir Draxon (v1.0, 3.5" DD)
Requires IBM AT ([box cover …
> ibm5170.xml: 9 new software additions

- hash/a2600.xml
Shootin' Gallery (PAL, prototype) [Buckaroo]
> a2600.xml: Marked light gun games unsupported. Added a prototype.

- src/devices/machine/jvsdev.cpp
Previously only the first device in the chain would receive the reset command, causing any slave devices to retain their assigned address after the reset. The desired behavior is for all slaves in the chain to reset.
> devices/machine/jvsdev.cpp: Fix chaining resets

- src/mame/capcom/sonson.cpp
Source of measurements --> https://github.com/MikeS11/Arcade-Sonson_MiSTer/issues/1#issuecomment-1312089702
The value originally set must have been a typo, according to @kold669 (aka Corrado Tomaselli who is credited in the original change made back in 0.156). The original PCB alternates between 55.37Hz and 55.43Hz and it is Corrado's suggestion to run it at 55.40Hz. Measurement pictures backed up here as well:
Vsync
Hsync
Csync
> capcom/sonson: Change vsync to 55.40Hz

- src/emu/xtal.cpp
- src/mame/layout/dx9.lay
- src/mame/mame.lst
- src/mame/mess.flt
- src/mame/yamaha/ymdx9.cpp
This is a skeleton driver for the Yamaha DX9 synthesizer. The layout has a functional UI, with the LCD, LEDs, and front-panel buttons. I intend to improve the layout file when time permits.
This is the first driver I've implemented. If there are any issues with how I've structured the code, or any extra documentation required, please let me know, and I'll be happy to correct the issues.
If I understand it correctly, I need to email the required ROM image to the MAME developers. If someone could instruct me where to send that, I'm happy to do so.
> Yamaha DX9 Skeleton Driver

- 3rdparty/ymfm/.gitignore
- 3rdparty/ymfm/README.md
- 3rdparty/ymfm/examples/vgmrender/vgmrender.cpp
- 3rdparty/ymfm/src/ymfm.h
- 3rdparty/ymfm/src/ymfm_fm.h
- 3rdparty/ymfm/src/ymfm_fm.ipp
- 3rdparty/ymfm/src/ymfm_opl.cpp
- 3rdparty/ymfm/src/ymfm_opn.cpp
- 3rdparty/ymfm/src/ymfm_pcm.h
Update ymfm library to latest. [Aaron Giles]
* Uninitialized member was causing slight jitter in timing when timer B is used.
* OPNA now has correct attenuation when LFO is disabled.
* PCM address incrementing was incorrect, resulting in some wraparound bugs.
> Update ymfm to latest.

- src/devices/cpu/powerpc/ppc.h
- src/devices/cpu/powerpc/ppccom.cpp
- src/mame/konami/hornet.cpp
As per the PPC403 CPU manual, SerClk is supposed to be an external clock and can only be up to half of SysClk, and SysClk should be the actual system clock speed.
The hardcoded 33333333 (system clock) and 3686400 (serial clock) constants have existed for longer than I can see in the Git history (pre-0.121) so I don't have more context for those specific values.
https://github.com/mamedev/mame/blame/7b77f1218624ea26dbb2efd85a19f795f5d4e02e/src/emu/cpu/powerpc/ppc403.c#L625-L629
I tested with a few random Konami Hornet, Konami Cobra, and Konami Firebeat games and everything seems to be working as well as before, and a fatal error with Hornet games when frequently polling for inputs on the JVS I/O has been fixed (commented in code). The fatal error does not affect any games currently but …
> devices/cpu/powerpc/ppccom.cpp: (PPC4xx) Add configurable external serial clock and use actual system clock value for serial timer

- src/devices/machine/upd71071.cpp
For some time I've noticed that the hard drives were occasionally (randomly) not working on startup in the FM Towns machines, which usually points to something using uninitialized variables. After tracing it with Valgrind it seems the issue is in the uPD71071 DMA controller.
I have tested the driver with these changes and in about 30 tries it hasn't failed at all (it didn't take more than 3 or 4 before), so I'm pretty confident that it's working correctly now.
> machine/upd71071.cpp: initialize variables, prevents random HDD failures in fmtowns

- src/mame/mame.lst
- src/mame/philips/cdi.cpp
- src/mame/philips/cdi.h
- src/mame/philips/cdislavehle.cpp
- src/mame/philips/cdislavehle.h
New working machines
Quizard (v1.8, Italian, i8751 IT 11 I2) [Ryan Holtz, f205v, Team Europe]
Quizard (v1.7, Italian, i8751 IT 11 I2) [Ryan Holtz, f205v, Team Europe]
Quizard (v1.2, Italian, i8751 IT 11 I2) [Ryan Holtz, f205v, Team Europe]
Quizard (v1.0, Italian, i8751 IT 11 I2) [Ryan Holtz, f205v, Team Europe]
Machines promoted to working
Quizard 3 (v3.4, German, i8751 DE 132 D3) [Ryan Holtz]
Quizard 3 (v3.4, German, i8751 DE 132 A1) [Ryan Holtz]
Quizard 3 (v3.2, German, i8751 DE 132 D3) [Ryan Holtz]
Quizard 4 Rainbow (v4.2, German, i8751 DE 142 D3) [Ryan Holtz]
Quizard 4 Rainbow (v4.2, Czech, i8751 TS142 CZ1) [Ryan Holtz]
Quizard 4 Rainbow (v4.1, German, i8751 DE 142 D3) [Ryan Holtz]
Quizard 4 Rainbow (v4.0, German, i8751 DE 142 D3) …
> -cdi: Added support for Italian version of Quizard 1. [Ryan Holtz, f205v, Team Europe]

- src/mame/konami/hornet.cpp
- src/mame/konami/k573mcal.h
- src/mame/konami/k573mcr.h
- src/mame/konami/windy2.cpp
- src/mame/konami/windy2.h
Windy 2 JVS I/O device has been tested in NBA Play By Play on Konami Hornet and Fighting Wu-Shu 2nd! on Konami Cobra hardware.
The panel configuration is normally determined by the DIPSW8 on the I/O PCB but I found the games can be picky about the minimum number of buttons available for it to accept the panel configuration, so I removed the user configurable dipswitch in favor of having the driver programmer decide the best panel type for a game to reduce any false reports from bad panel configuration settings.
This is the panel layout and dipswitch setting reference from the manual:
> konami/hornet.cpp: Fix 4 player cabinet type in NBA Play By Play

- src/devices/machine/upd765.cpp
- fixes most CHRN marked fails in pc8801_flop.xml and (eventually) pc88va FDC PIO mode stall at POST.
> upd765.cpp: return a command_end with data_completion = false for failed commands

- hash/a800.xml
- Replaced countries' abbreviations by their full name
- Lowercase on some descriptive words like "Rev", "Alt", "Prototype", "Pirate", ...
> a800.xml: Metadata cleanups

- src/mame/konami/konmedal.cpp
The clock divider that was previously defined caused the music for the games that used shuriboy's machine configuration to be pitched higher than hardware recordings. This should match, if not at least be close, to the actual clock from hardware recordings.
Shuriken Boy: hardware(https://youtu.be/EeRqRCpqzkE?t=23) vs. MAME (https://youtu.be/YkUlJdstDrA?t=33)
Fuusen Pentai: hardware(https://youtu.be/JL45gafk2_Y?t=8) vs. MAME(https://youtu.be/M6qyGSBPD5o?t=6)
Tsururin Kun: hardware(https://youtu.be/loGvV6tgkhY?t=8) vs. MAME(even though it's unplayable, it was affected by this.)
Tsurikko Penta: hardware(https://youtu.be/ggqx9tX3jEw?t=13) vs. MAME(https://youtu.be/J4vxjq8NPwg?t=5)
Mario Roulette: hardware(https://youtu.be/8QMDrwWOvG0?t=4) vs. MAME(https://youtu.be/SmzuAp-lfzA?t=162)
I should …
> konmedal.cpp: Corrected the K051649 clock for a few titles.

- src/mame/konami/hornet.cpp
- The Silent Scope's scope I/O board's ADC is hooked up where it should be so the game can boot without the machine init skip dipswitch enabled now.
~~- I added a hack for Silent Scope's scope screen to fix the screen update issue. I documented why the scope screen was broken and why the hack will fix it but I have no idea how to fix it properly so I'm hoping the hack + comment gives someone some leads to fix it properly in the future. The function of interest called by IRQ1 in `sscope` is 0x80008828 if someone wants to take a look at it.~~
- I hooked up controls to `gun_r` which allows Teraburst to work without the machine init skip dipswitch enabled and generally makes the game more playable (previously only had keyboard controls). It's an HLE style emulation instead of trying to …
> konami/hornet.cpp: Improvements to Silent Scope and Teraburst

- src/mame/konami/hornet.cpp
Hornet games default to having the "skip post" dipswitch set to on because most games have issues during boot still, so I didn't notice when I broke the gun I/O's boot test in https://github.com/mamedev/mame/pull/10627. The two problems being that I completely forgot to fix returning m_gn680_ret0 and m_gn680_ret1 after I changed the functions from 32 bit to 16 bit, and also didn't take into account that gun I/O polling wants 0x7408000e to be set to 0.
Teraburst has a bunch of `[:voodoo0] internal_lfb_r: Buffer offset out of bounds x=486 y=1023 offset=000FFDE6 bufoffs=FFFB01E6` errors and eventually is reset by the watchdog so it's impossible to test if guns work skip post disabled.
Tested that the gun I/O check was passing again with skip post disabled, and also checked that the guns are …
> konami/hornet: Fix regression in Teraburst's gun I/O not passing boot test

- src/devices/cpu/m6502/rp2a03.cpp
- src/devices/cpu/m6502/rp2a03.h
- src/devices/sound/nes_apu.cpp
- src/devices/sound/nes_apu.h
- src/mame/nintendo/dkong.cpp
- src/mame/nintendo/nes_sh6578.cpp
- src/mame/nintendo/nes_vt369_vtunknown_soc.cpp
- src/mame/nintendo/nes_vt_soc.cpp
- src/mame/nintendo/nes_vt_soc.h
nintendo/nes_vt*: Aligned PnP APU code with core changes.
nintendo/dkong.cpp: Fixed dkong3b crash regression.
> sound/nes_apu.cpp: Can no longer read from anything but status register.

- src/devices/machine/mc68328.cpp
- src/devices/machine/mc68328.h
- src/mame/layout/pilot1k.lay
- src/mame/palm/palm.cpp
- src/mame/palm/palm_dbg.ipp
-mc68328: Improved LCDC and SPI handling. [Ryan Holtz]
-palm: Added LCD blanking bits, improved port handling, removed unneeded prefixes. [Ryan Holtz]
> MC68328 and PalmPilot: More cleanups and better LCDC emulation

- src/mame/mame.lst
- src/mame/tecmo/tehkanwc.cpp
- src/mame/tecmo/tehkanwc.h
new clones
---------
Tee'd Off (World) [system11]
note, since the new set has the same 'protection' code that we thought might be due to a bad dump, I've unflagged the other ROMs.
this is the new parent set.  I've also demoted the game to NOT WORKING for now because there's something strange going on, and it isn't clear that the behavior is 100% correct with the patch.
system11 also provided the following PCB images http://mamedev.emulab.it/haze/amisc/teedoff_pcb_images.zip note @angelosa there doesn't seem to be anything out of the ordinary anywhere on the PCB.  Maybe this code shouldn't be being executed at all and the failure is earlier? maybe it's an open bus read?
> new clones (teedoff)

- src/mame/hp/hp80.cpp
Hi,
I'm opening this PR because I fixed the long-standing keyboard problem on `hp86b_001` and `hp86b_004`.
The bug was apparently due to the keyboard controller being enabled too early during the boot process.
Thanks.
--F.Ulivi
> hp80: Fixed keyboard issue on hp86b_001 & hp86b_004

- src/devices/bus/coco/cococart.cpp
- src/devices/bus/coco/cococart.h
Move device initialization to constructor. Added resolve_safe() to remove some checks.
> bus/coco: minor cleanup of interfaces

- hash/a7800.xml
- src/devices/bus/a7800/rom.cpp
The current ROMs don't work when put back on an original cartridge due to pairs of 8K blocks being swapped. This corrects that and other minor details.
> bus/a7800/rom.cpp: Use proper bank order for Activision 128K cartridges.

- scripts/src/video.lua
- src/devices/machine/mc68328.cpp
- src/devices/machine/mc68328.h
- src/devices/video/sed1375.cpp
- src/devices/video/sed1375.h
- src/mame/palm/palm.cpp
- src/mame/palm/palm_dbg.ipp
- Split MC68328 device into a base class with shared functionality, and derived MC68328 and MC68EZ328 models.
- Added roughly-functional implementation of the Epson SED1375 LCD controller.
Machines promoted to working
Palm IIIc [Ryan Holtz]
> -mc68328: Added EZ variant support.

- src/osd/windows/window.cpp
-osd/windows/window.cpp: Check for a non-null renderer before issuing a draw request to the renderer. [Ryan Holtz]
> Fixed a crash when toggling fullscreen w/ NES Gyromite on Windows

- src/mame/nintendo/playch10.cpp
- src/mame/nintendo/vsnes.cpp
- Also fixes incorrect Zapper-like trigger behavior. The PC10 trigger is just a button that fires upon being pushed. The NES trigger is a more complex mechanism where a full trigger motion pushes and then releases a micro switch (still not handled well in MAME as it generally means games fire when you _release_ a button).
For some reason (laziness?) P1's first button (B) was being repurposed for the light gun's trigger. Playchoice-10 has separate dedicated pins for both P1/P2 standard controls AND the light gun. All three happily coexist on hardware (unlike a light gun on a VS cabinet).
> nintendo/playch10.cpp: Added separate gun trigger input.

- hash/ibm5170_cdrom.xml
5 Plus One: Pack 10 - The Blues Brothers (compilation) [redump.org]
5 Plus One: Pack 25 - TV Sports Football (compilation) [redump.org]
Delphine Classic Collection - Adventure (compilation) [redump.org]
Hocus Pocus (Europe) [redump.org]
Hocus Pocus (Germany) [redump.org]
Hocus Pocus (Germany, shareware) [redump.org]
Hocus Pocus (Spain) [redump.org]
Hocus Pocus (USA) [redump.org]
Hocus Pocus (USA, rerelease) [redump.org]
Hocus Pocus (USA, rerelease, alt) [redump.org]
Hocus Pocus (USA, mail order release) [redump.org]
id Anthology (rev 1, compilation) [redump.org]
id Anthology (compilation) [redump.org]
The Bitmap Brothers Compilation (compilation) [redump.org]
Zool: Ninja of the "Nth" Dimension [redump.org]
Zool 2 …
> ibm5170_cdrom.xml: 16 new software list additions

- src/devices/bus/snes/snes_slot.cpp
Was always reporting speed as fastrom
> bugfix in snes header logerror reporting

- src/mame/yamaha/ymdx9.cpp
This PR resolves an issue with handling incoming MIDI on the Yamaha DX9 driver.
I made a mistake in my original analysis of the schematics. There's a divider on the 500 kHz crystal attached to the MIDI clock. I also forgot to finalise the reading of MIDI.
This PR should resolve those issues.
> Yamaha DX9: Resolve issue with incoming MIDI clock

- src/mame/mame.lst
- src/mame/mess.flt
- src/mame/skeleton/vector3.cpp
It appears Vector Graphic Monitor 4 was confused with Vector 4. The majority of the functioning parts are for the Vector 3, as that is the source of the ROMs.
I've fixed some of the easier Vector 4-isms that were copied from the user guide, but it will need more thorough work. That should be a lot easier with the better understanding of which machine was running and the detailed documentation.
------
I'm familiar with the Vector 4, but not so much with the Vector 3. I have a follow-up to add Vector 4. It doesn't conflict except for mame.lst.
> skeleton: Rename Vector 4 to Vector 3

- hash/ibm5170_cdrom.xml
Corrected "Peristroka" to "Perestroika" on "5plus1_25" notes
> ibm5170_cdrom.xml: Typo correction

- hash/nes.xml
- src/devices/sound/nes_apu.cpp
- src/devices/sound/nes_apu.h
- src/devices/sound/nes_defs.h
Akagawa Jirou no Yuurei Ressha (Japan) [kmg]
Castelian (Europe) [kmg]
Door Door (Japan) [kmg]
Door Door (FMG pirate) [kmg]
Dragon Quest (Japan) [kmg]
Dragon Quest II - Akuryou no Kamigami (Japan) [kmg]
GeGeGe no Kitarou - Youkai Daimakyou (Japan) [kmg]
GeGeGe no Kitarou - Youkai Daimakyou (Japan, prototype) [kmg]
GeGeGe no Kitarou - Youkai Daimakyou (FMG pirate) [kmg]
The Guardian Legend (Europe) [kmg]
The Guardian Legend (USA) [kmg]
Guardic Gaiden (Japan) [kmg]
Jesus - Kyoufu no Bio Monster (Japan) [kmg]
Mahjong Taikai (Japan) [kmg]
Ninja Jajamaru - Ginga Daisakusen (Japan) [kmg]
Ninja Jajamaru - Ginga Daisakusen (Japan, prototype) [kmg]
Ninja Kid (USA) [kmg]
Mendel Palace (USA) [kmg]
The Mutant …
> nes_apu.cpp: Implemented frame counter IRQ (MT06186, MT07625, MT07658).

- scripts/src/video.lua
- src/devices/machine/mc68328.cpp
- src/devices/machine/mc68328.h
- src/devices/video/mc68328lcd.cpp
- src/devices/video/mc68328lcd.h
- src/mame/palm/palm.cpp
- src/mame/vtech/iqunlim.cpp
-mc68328: Improved LCD controller emulation. [Ryan Holtz]  
-mc68328lcd: Added a generic device to handle MC68328-style LCD output signals. [Ryan Holtz]
-iqunlim: Hooked up MC68EZ328 device. [Ryan Holtz]
> More MC68EZ328 work for palmm100 and iqunlim

- src/mame/sharp/x68k.h
- src/mame/sharp/x68k_v.cpp
Reverts mamedev/mame#10719
Unfortunately it doesn’t work.  Backgrounds are completely broken in Super Hang-On.
> Revert "x68k_v.cpp: Clean up screen_update"

- hash/x68k_flop.xml
I found a boxed SX-Window 3.1 set that had two extra disks not in the already existing dumps. These images were dumped directly from the pictured floppy disks using a Greaseweazle and a Mitsumi 5.25" drive.
Images: https://archive.org/details/sxwindow-31.tar
I've never updated a software list before, so let me know if I made any mistakes :)
> Add SX-Window 3.1 alternate dump

- src/mame/mame.lst
- src/mame/pacman/pengo.cpp
reorganized the Pengo sets a little
- The Export versions are the versions with replaced music / faster maze drawing
- The Japan versions have slow maze drawing and the 'popcorn' music
- The unencrypted sets are the newest releases we have of both versions - for Japan that is ROMs 5120-5127 and for export that is ROMs 5128 - 5135 (suggesting these unencrypted versions were both released at the same time)
- see https://tcrf.net/Pengo_(Arcade) for some research
> pacman/pengo.cpp: Sorted Pengo sets, and changed scheme for short names

- src/mame/apple/apple2.cpp
- src/mame/apple/apple2e.cpp
- src/mame/apple/apple2video.cpp
- src/mame/apple/apple2video.h
a2_video_device::{text_update,plot_text_character} already had a template parameter to distinguish II/II+ from IIe/IIc. Extending it enables {text_update,plot_text_character}{_ultr,_jplus,GS} to be merged in as well.
I preserved all of the logic of the old functions even where I suspect it's wrong. Behavior that seems suspicious to me: not masking by 0x3f on II/II+ (isn't their character ROM only 0.5K?); logic for the range 60..7f on IIe/c not applied on GS; and inconsistent use of m_aux_mask in aux_page accesses.
One exception to the previous paragraph: text_update_{jplus,ultr} didn't calculate startcol and stopcol, which seems to be just a missed optimization opportunity, and they tested row <= stoprow instead of row < stoprow, which is a bug that would make them emit 25 lines instead …
> Merge copies of text_update and plot_text_character in a2_video_device

- src/mame/apple/apple2video.cpp
- src/mame/apple/apple2video.h
m_dhires_artifact_map was just a rotate-four-bits-by-2 lookup table. The code that used it was already doing four-bit rotations by arbitrary amounts, so it is slightly simplified by eliminating the table.
> Remove a2_video_device::m_dhires_artifact_map

- src/devices/machine/upd765.cpp
- src/devices/machine/upd765.h
The observed behavior of other_irq and data_irq appear to be the same where they are cleared by reading or writing the data register.  This implements that, using a pr to get some additional testing.
> upd765: unify data_irq and other_irq

- src/devices/cpu/m6809/hd6309.lst
This is a weird instruction that can copy a bit from a register to a memory location.
Previously it was not reading the value of the memory of the location before modifying it.
> hd6309: Fix STBT instruction

- src/mame/apple/macadb.cpp
...which doesn't entirely matter because they were sent in the wrong order so it all works out but it was confusing none-the-less.
More importantly, bit 7 of the X position is the second mouse button status (or 1 in most cases).
https://developer.apple.com/library/archive/technotes/hw/hw_01.html#Section6
Guide to the Macintosh Family Hardware, Chapter 8, table 8-4, page 301
> macadb: mouse x/y variables are reversed

- src/devices/machine/sun4c_mmu.cpp
- src/devices/machine/sun4c_mmu.h
-sun4c_mmu: Removed non-functional cache emulation. sun4_60 can install and boot SunOS 4.1.4 again. [Ryan Holtz]
> Removed non-functional sun4c_mmu cache emulation

- src/mame/sun/sun4.cpp
> Fixed array-bounds oversight in sun4.cpp, fixes macOS and Linux compiles

- src/mame/apple/apple2gs.cpp
* mouse data register is full until both x/y are read
* X/Y bit set after X is read, cleared after Y is read
* X/Y bit was accidentally dependent on the KGS_ANY_KEY_DOWN bit
> apple2gs.cpp: make kmstatus match observed IIgs behavior;

- src/lib/formats/fs_coco_os9.cpp
Fixed a bug in the OS-9 file system's file name validation function that caused it to incorrectly tolerate characters with the seventh bit set
> Fixed a bug in the OS-9 file system module

- src/mame/apple/apple2video.cpp
Fix an off-by-1 error in the 160-column mode that caused the rightmost 2 pixels to be omitted. In 140-column color and mixed modes, use custom logic to make 140 wide pixels instead of simulating blurry artifact color. In mixed mode, each high bit controls 7 narrow pixels according to the manual.
With these changes, the card seems to pass all of the tests on the official demo disk, except that foreground-background hires remains unimplemented, "Color Mouse Draw" seems to hang/crash, and some demos sometimes set the wrong mode when run after other demos (including themselves). The last could be a bug in the demos.
> Apple II: fix Video-7 RGB card double hi-res modes

- src/mame/apple/apple2video.cpp
- src/mame/apple/apple2video.h
- src/mame/apple/superga2.cpp
- src/mame/apple/tk2000.cpp
The superga2 and tk2000 drivers called hgr_update directly. Instead set the appropriate mode and call screen_update, and make hgr_update private along with the other mode-specific functions.
> Make all clients of a2_video_device use screen_update

- src/mame/taito/taito_f2.cpp
Fixes MT08543 – megablst and clones: Shield powerup aura on option is missing.
Many other games in the driver use `m_screen->screen_vblank().set(FUNC(taitof2_state::screen_vblank_partial_buffer_delayed));` and there's a long explanation about the game software and how they buffers things and why it is needed in those cases.  I don't know why it wasn't set for this game however, so please check for new issues elsewhere.
> taito/taito_f2.cpp: Use screen_vblank_partial_buffer_delayed for Mega Blast (MT08543)

- src/devices/bus/isa/s3virge.cpp
- src/devices/bus/isa/s3virge.h
- src/devices/video/virge_pci.cpp
- bus/isa/s3virge.cpp: implement DPna, DSna, DSno, DSPDxax and DSo ROP opcodes;
- bus/isa/s3virge.cpp: fix source pitch stride;
- bus/isa/s3virge.cpp: clip against de bit;
- bus/isa/s3virge.cpp: initialize pattern variable in mono mode;
> video/virge_pci.cpp: fix remapping, allow pcipc with ibm5170_hdd:win98se to boot without hacks in 256 color mode

- src/devices/bus/vcs_ctrl/paddles.cpp
-vcs_ctrl/paddles: Swap ports and button bits at runtime. Avoids multiple input defs per-device. [Ryan Holtz]
> Revised vcs_ctrl/paddles to use one input definition

- src/mame/bfm/bfm_bd1.cpp
- src/mame/bfm/bfm_bda.cpp
This should fix the regressions noted here (https://github.com/mamedev/mame/commit/6e5d7328cb152e56612bb5bc20ddb0ec3434c617#commitcomment-95293594)
In short, the window code for BDA still uses the clear all method that was missed out before.
There's more that needs to be done, but this restores the behaviour on error currently seen
> BFM_BDA.cpp : Restore window code to fix SC5 graphical glitches

- src/mame/apple/apple2video.cpp
- src/mame/apple/apple2video.h
Make most video modes produce a 560x192 monochrome bitmap that goes through shared artifact color simulation code, and add some dip-switch options to control the algorithm.
This also implements the Video-7 foreground-background hires mode, since it was easy to do with the shared code.
> Apple II: factor out NTSC color simulation and add config options

- hash/sgi_mips.xml
Three new Onyx2 demo CDs popped up on IA recently. This PR adds them to the `sgi_mips.xml` softlist.
They are "working" in a technical sense (standard ISO format, files can be installed/copied to an SGI running IRIX) but many of them don't run properly since they require an Onyx2 which I don't have/cannot test on/isn't emulated yet, so I'll add them as "not working".
````
New NOT_WORKING software list additions:
- sgi_mips: Onyx2 - As Real As it Gets Demo CD - Volumes 1, 2 and 3
````
> sgi_mips: Three new software list additions

- hash/cd32.xml
- hash/cdtv.xml
Replaced "Euro" by "Europe" and lowercase on some descriptive words
> cd32.xml, cdtv.xml: Metadata cleanings

- src/mame/dynax/ddenlovr.cpp
According to videos from PCB, AY8910 clocks need to be corrected to half. 
PCB Video 1: [Waiwai Animal Land(ワイワイアニマルランド)](https://www.youtube.com/watch?v=c74k8IQSe34) (Japanese "Monkey Mole Panic") - Game start countdown sound, Mode confirm sound, etc.
PCB Video 2: [The First Funky Fighter (ザ・ファースト・ファンキーファイター)](https://www.nicovideo.jp/watch/sm6737990) - Game start countdown sound, etc.
Also, Animalandia Jr. PCB Notes shows all clock values already verified.
> dynax/ddenlovr.cpp mmpanic: fix AY8910 clock

- src/mame/pinball/inder.cpp
> pinball/inder.cpp: Fix date in note about "Mundial 90"

- src/mame/sanritsu/jantotsu.cpp
According to video from PCB, SN76489A clocks need to be corrected.
Reference Video: https://twitter.com/kakikukecat/status/1530945420347645952
> sanritsu/jantotsu.cpp : fix SN76489A clock

- src/mame/vsystem/f1gp.cpp
Per this remark on [MT08411](https://mametesters.org/view.php?id=8411):
>It also should be noted that the "ID CHECK ERROR" note on f1gp.cpp is no longer accurate - the game does boot with Game Mode set to Multiple, but the ID CHECK gives random numbers every boot
...and this [TCRF page](https://tcrf.net/F-1_Grand_Prix_(Arcade)) documenting Set 1 vs Set 2 changes.
> f1gp notes (link and banners)

- hash/ibm5170_cdrom.xml
Alien Incident (Europe, v1.01) [redump.org]
Alone in the Dark (Europe) [redump.org]
Alone in the Dark (Europe, rev. 1) [redump.org]
Alone in the Dark (Europe, Pay as You Play version, CD-ROM User) [redump.org]
Alone in the Dark (Europe, Pay as You Play version, PC Power) [redump.org]
Alone in the Dark 2 (Europe) [redump.org]
Alone in the Dark 2 (Europe, English only) [redump.org]
Alone in the Dark 2 (France) [redump.org]
Beneath a Steel Sky (USA, Slash release) [redump.org]
Epic Pinball (Europe, Romware release) [redump.org]
Epic Pinball (USA, Mail Order release) [redump.org]
Formula One Grand Prix (Netherlands) [archive.org]
Gobliiins (Italy, Collezione Cd-Rom) [redump.org]
Gobliiins (USA, Sierra Originals …
> ibm5170_cdrom.xml: 25 New working software list additions

- src/devices/machine/6522via.cpp
These 3 datasheets:
http://archive.6502.org/datasheets/mos_6522_preliminary_nov_1977.pdf http://archive.6502.org/datasheets/synertek_sy6522_via_1978_jan.pdf
http://archive.6502.org/datasheets/rockwell_r6522_via.pdf
state that:
The IFR bit 7 is not a flag. Therefore, this bit is not directly cleared by writing a logic 1 into it. It can only be cleared by clearing all the flags in the register or by disabling all the active interrupts as discussed in the next section.
but this is what current code does. If more updated datasheets are available, please share the links.
> machine/via6522.cpp: Don't clear all interrupts on IFR writes with bit 7 set

- scripts/src/bus.lua
- src/devices/bus/nabupc/hdd.cpp
- src/devices/bus/nabupc/hdd.h
- src/devices/bus/nabupc/option.cpp
This adds support for hard drive emulation to the nabupc system.
> nabupc: Add support for hdd controller

- src/devices/bus/nscsi/cd.cpp
- src/devices/machine/ncr53c90.cpp
- src/devices/machine/ncr53c90.h
Discussion can be found in this commit: https://github.com/mamedev/mame/commit/8518c8421555e9ad7443e4537ea02ed6d4f4c441#r98926600
Basic NCR53CF96 was added in preparation for an upcoming PR to convert the Konami arcade drivers using AM53CF96 to use NSCSI.
The nscsi/cd change is required to fix sun4_60 booting because Solaris 2.6 requests 48 bytes from the SCSI INQUIRY command but only receives the hardcoded 36 bytes, so it would time out waiting for the remaining data.
> ncr53c90: Add NCR53CF96 + bugfixes

- hash/msx1_cart.xml
- hash/msx2_cart.xml
- src/devices/bus/msx/cart/nomapper.cpp
- src/devices/bus/msx/slot/cartridge.h
- Use hexadecimal sizes.
- Add a feature to explicitly indicate where in memory cartridges without mappers should be loaded.
- Updated serial, isbn, gtin, and usage notes.
- Updated versions for Arabic releases and added Arabic alt_titles.
> msx1_cart.xml: Hexadecimal sizes, explicitly configure loading for smaller images, add information and usage notes.

- src/mame/misc/neomania.cpp
The HDD CHD boots fine now. The procedure used to create the CHD from the Norton Ghost images was: 1.- Use Norton Ghost to convert from GHO to VHD.
2.- Use QEmu to convert from VHD to raw.
3.- Use chdman to convert from raw to CHD.
> misc/neomania.cpp: Redumped the HDD image [Recreativas.org]

- src/mame/mame.lst
- src/mame/misc/playcenter.cpp
PlayCenter Champions Tournament (v9.3, 'K6' hardware)  [Recreativas.org]
PlayCenter Champions Tournament (v9.3, 'Celeron' hardware) [Recreativas.org]
The HDD CHDs boot fine now. The procedure used to create the CHDs from the Norton Ghost images was:
1.- Use Norton Ghost to convert from GHO to VHD.
2.- Use QEmu to convert from VHD to raw.
3.- Use chdman to convert from raw to CHD.
> misc/playcenter.cpp: Redumped the current HDD and added two PlayCenter clones

- src/mame/misc/gfamily.cpp
The HDD CHD boots fine. The procedure used to create the CHD from the Norton Ghost image was: 
1.- Use Norton Ghost to convert from GHO to VHD using the 'ntexact' option. 
2.- Use QEmu to convert from VHD to raw.
3.- Use chdman to convert from raw to CHD.
> misc/gfamily.cpp: Re-encoded the CHD from the GHO the right way [Recreativas.org]

- hash/msx2_cass.xml
The Red Lights of Amsterdam was released as a double sided tape. The redlight entry was both sides in a single file as if all the data was on a single side.
> msx2_cass.xml: Update note and serials. Replace redlight with redlighta.

- hash/c64_flop_misc.xml
- hash/c64_flop_orig.xml
Replaced countries' abbreviation by the full name
> c64_flop_misc.xml, c64_flop_orig.xml: Metadata cleaning

- src/osd/sdl/osdsdl.cpp
As of 2810c9d BGFX is no longer default on SDL, OpenGL is
> Do not error out on -video auto -videodriver wayland

- scripts/src/machine.lua
- src/devices/machine/gayle.cpp
- src/devices/machine/gayle.h
- src/devices/machine/linflash.cpp
- src/devices/machine/linflash.h
- src/devices/machine/pccard.cpp
- src/devices/machine/pccard.h
- src/devices/machine/pccard_sram.cpp
- src/devices/machine/pccard_sram.h
- src/mame/amiga/amiga.cpp
- src/mame/amiga/amiga_m.cpp
- src/mame/konami/ksys573.cpp
- Add callbacks for card detect, battery voltage and write protect to the PCCard interface
- Add helpers to read/write data swapped (similar to the existing support in the ATA device)
- Add support for 2 MB and 4 MB SRAM PCMCIA models from Centennial. Those have a builtin eeprom storage for CIS information
- Rewrite the Amiga Gayle emulation, adding support for PCMCIA
- Fix an issue with Amiga interrupts arriving at the wrong time
- Update the linear flash card emulation to use the new card detection support
Screenshots showing support in the Amiga 600 driver:
> PCMCIA: Add support for SRAM cards

- src/mame/taito/taito_f3.h
- src/mame/taito/taito_f3_v.cpp
used by land maker, riding fight, rayforce stage 5 intro, some other effects in stgs
| before | after |
| ------|----- |
|![](https://qcs.shsbs.xyz/api/File/raw/veqtq)|![](https://qcs.shsbs.xyz/api/File/raw/cscug)
|![](https://qcs.shsbs.xyz/api/File/raw/njwtf)|![](https://qcs.shsbs.xyz/api/File/raw/fyxgo)|
pcb refs for samples
https://youtu.be/oQaxP8j9Zbg?t=282
https://youtu.be/4DLBWmaOOO0?t=70
not sure what the previous "can affect opacity" comment is trying to imply, assuming just that palette add happens before blending.
it might be nice for playfields to opt out of effects like this in all-zero cases but that's begging a real rewrite.
> taito/taito_f3_v.cpp: line ram palette add effect

- src/devices/cpu/tlcs870/tlcs870.cpp
- src/mame/snk/hng64.cpp
- src/mame/snk/hng64.h
- src/mame/snk/hng64_3d.ipp
- src/mame/snk/hng64_sprite.ipp
- src/mame/snk/hng64_v.cpp
- use 16-bit framebuffer rather than 32-bit for the 3D, so it can be passed as index values into the mixer
note, looks a bit worse for now in terms of lighting, but I think this is going to be closer to how the hardware works, just our lighting calculations are wrong anyway.
> hng64_3d.ipp : use 16-bit framebuffer rather than 32-bit for the 3D, so it can be passed as index values into the mixer

- src/mame/taito/taito_f3.h
- src/mame/taito/taito_f3_v.cpp
- respect all 4 clip planes (needed by landmakrj, quizhuhu)
- remove some incorrect assumptions about clip plane 3 enable bit being a clip disable
- found a 'invert clip inverse mode' flag. most games set it, caused problems with unset pbobble4, commandw
- don't truncate landmakr/quizhuhu palette offsets: caused green fades in quizhuhu, incorrect win message colors in landmakrj. apparently the truncation fixed symptoms in a number of games, deserves more research.
fixes mt00950: landmakr: Winning message is missing.
fixes mt01014: quizhuhu: The question text is not displayed.
fixes mt02819: pbobble4 and clones: Victory screen not shown at end of match
fixes commandw map display
fixes quizhuhu pre-taito logo intro not visible
fixes landmakr ending slide display
> taito/taito_f3_v.cpp: line clip fixes, landmakr/quizhuhu palette fix

- hash/m20.xml
Added more game roms to the M20 hash file. This should now be a more or less complete list of all the games that are available for the M20.
Also added a comment about a common issue with some of the already existing bootable system roms and how to fix it.
> Added new roms and comments to M20 hash file

- src/mame/heathkit/h19.cpp
Fix an apparent copy-n-paste issue that was introduced with restructure of device timer from https://github.com/mamedev/mame/pull/9788
> Stop endless beep on Heathkit H19

- src/mame/heathkit/h19.cpp
- src/mame/heathkit/h89.cpp
Update company name in h19.cpp and h89.cpp to match the name in h8.cpp and et3400.cpp. "Heath Company" is the name the company used in documentation and catalogs.
> Make company name consistent across all Heathkit machines

- src/devices/machine/6522via.cpp
**** ***THIS IS UNTESTED*** ******
*I have created this pull request to address the below and document a possible fix.*
From http://archive.6502.org/datasheets/mos_6522_preliminary_nov_1977.pdf and http://archive.6502.org/datasheets/synertek_sy6522_via_1978_jan.pdf
MCS6522/SYS6522 OPERATION
[...]
C. PORT A REGISTERS, PORT B REGISTERS
[...] With input latching enabled, IRA will reflect the contents of the Port A prior to setting the CA1 Interrupt Flag (IFRl) by an active transition on CA1 [...] With input latching enabled on Port B, setting CB1 interrupt flag will cause IRB to latch this combination of input data and ORB data **until the interrupt flag is cleared** [...]
Auxiliary Control Register
[...]
.1. PA …
> machine/6522via.cpp: Make input ports read transparently when corresponding interrupt flag is clear

- hash/neogeo.xml
- src/mame/neogeo/neogeo.cpp
- puzzldpr was a new version of the game, a year later, with separate ID number, it shouldn't be considered a clone.
- added a BIOS found on a restored Japanese Irritating Maze cabinet, sadly it appears to be a hack done by the arcade distributor who restored it (probably the original mainboard was missing when the restoration was done?) [Simon Taylor]
> neogeo/neogeo.cpp: Don't treat puzzldpr as a clone, added additional irrmaze BIOS

- src/mame/snk/hng64.cpp
- src/mame/snk/hng64.h
- src/mame/snk/hng64_3d.ipp
- src/mame/snk/hng64_sprite.ipp
- src/mame/snk/hng64_v.cpp
- identified 'blend' flag for 3D objects, and did a minimal implementation (used in many places, eg. shadows in fatfurwa, buriki, final boss in sams64_2)
- emulated 'split' tilemap effect (needed by buriki one character introductions)
- don't draw sprites with '0' zoom values, rather than using an unscaled sprite (needed by sams64 text at start of round)
- make 'sprite erase' code less aggressive (prevent it from wiping out palette values) (needed by sams64 2nd intro)
- support 'texture scrolling' (used by windows on cars in xrally/roadedge, waterfalls in xrally)
> hng64.cpp - further video improvements

- src/mame/apple/apple3_m.cpp
Apple /// Owner's guide page 12:
"If the power is already on, the procedure for booting is to hold down the CONTROL key while you press and release the RESET button behind the keyboard."
Additionally, control-open apple-reset will drop into the (very simple) monitor.
> apple3: Add support for control-reset.

- src/mame/atari/irobot_m.cpp
Originally, irobot_state::init_irobot() starts first and sets up m_irmb_stack with addresses from m_mbops.  Then it called irobot_state::load_oproms() where m_mbops gets redefined on line 321.  This triggers an assertion in std::unique_ptr.h, something like "get() != pointer()".  Moving the load_oproms() call earlier does not cause the assertion to happen.
> atari/irobot_m.cpp: Initialise mathbox stack after loading decoding opcode PROMs

- src/mame/acorn/acrnsys1.cpp
Uploading one as a check I'm doing this correctly before doing more.
I didn't have to change much because the first 8 refs in INPUT_PORTS_START are the keyboard already.
Questions:
1) Does the zero in `m_keyboard(*this, "X%u", 0U)` mean start from the first def in INPUT_PORTS_START, or something else? Is it finding by name using the "X%u"?
2) Nothing appears to reference the port refs `reset` `switch` & `config`. Are these some standard names, or just not connected up?
3) I've noticed that (even before I changed anything) keys such as Esc and Tab don't work like other emulations. Is that expected?
> Upgrade acorn sys1 to use ioport_array

- hlsl/bloom.fx
-bloom.fx: Return an alpha of 1 rather than texel alpha. Fixes #10977 [Ryan Holtz]
> Fixed GH issue #10977, broken bloom in HLSL mode.

- src/mame/snk/hng64.cpp
- src/mame/snk/hng64.h
- src/mame/snk/hng64_3d.ipp
- src/mame/snk/hng64_sprite.ipp
- src/mame/snk/hng64_v.cpp
- added support for raster interrupt, needed to enable fatfurwa floor without ignoring the 'enable' bit with a hack
- various experiments with priority, still needs a proper per pixel mixer, but this gives a ballpark idea of any special cases that will need further attention
- various experiments with the remaining colour mixer effects, still imperfect, but again this helps highlight areas in need of more attention
> hng64.cpp - current progress, including using raster effect to enable fatfurwa floor

- src/emu/validity.cpp
- src/emu/video/rgbgen.h
The SSE and VMX implementations of rgbaint_t have consistent and well defined behavior for out of range shifts: the shift amount is treated as unsigned and shifts equal to or greater than the element width either zero the result (shl, shr) or replicate the sign into every bit (sra).
Shifts of this amount are undefined behavior in C++ and so extra checks have been added to reproduce the same behavior in the generic implementation. The validity checker has also been updated to add cases for out of range shifts.
Some explicit sign extensions have been removed from sra() as the validity checker already requires that signed right shifts must be arithmetic.
This bug was encountered when building the N64 RDP for ARM64 as it caused very obvious rendering artifacts.
> rgbgen: Safely compute out of range shifts

- src/devices/cpu/h8/h8_sci.cpp
- src/devices/cpu/h8/h8_sci.h
- src/devices/cpu/h8/h8_timer8.cpp
- src/devices/cpu/h8/h8s2245.cpp
- src/devices/cpu/tms32010/32010dsm.cpp
- src/devices/cpu/tms32025/32025dsm.cpp
Trying to keep these smaller to help review.
Some more sprintf removal to fix compiler warnings.
The slightly controversial part of this one is promoting the clock_mode enum to an enum class.
Not sure about the name ClockMode; the codebase has a mix of case styles, and generally seem to be all lower case?
> More sprintf warning fixes

- src/mame/ddr/kc.cpp
- src/mame/ddr/kc.h
- src/mame/ddr/kc_m.cpp
This is an overhaul of the sound emulation for the VEB Mikroelektronik KC 85/2..4 (ddr/kc).
The KC 85 series has 3 distinct sound outputs, which are currently not emulated as such:
1. Two 1-bit channels K0 and K1, driven by flip-flops via CTC channels 0 and 1, connected to the left and right channels on the Tape output. This feature is commonly used in music editors from the era. K0 and K1 are always in an undefined state (so they can be toggled but not set to a specific state), except on KC 85/4, where they can be reset to a known state via PIO B.
2. A binary weighted DAC that outputs on the RGB/FBAS port, with volume control via PIO B. Offers 5 bits of volume control on KC 85/2 and 85/3, and 4 bits of volume control on the KC 85/4. The signal sum of K0 and K1 is routed through the DAC. …
> KC 85 rework sound

- src/mame/snk/hng64.cpp
- src/mame/snk/hng64.h
- src/mame/snk/hng64_3d.ipp
- src/mame/snk/hng64_sprite.ipp
- src/mame/snk/hng64_v.cpp
- fixed name entry screen on roadedge
- don't buffer sprites (render them in the same update call as we use them)
- fix extra texture scroll (was double what it should have been), fixes some tv screens/billboards in roadedge
- some additional code safety on texture fetches
- minor refactoring to better facilitate further experiments
> hng64.cpp - small video improvements

- src/mame/ddr/kc.h
- src/mame/ddr/kc_m.cpp
Remove an erroneous shift on the output data on KC 85/2. Since the DAC works the same way on 85/2 and 85/3, there is no need to maintain a separate function for handling PIO B writes on 85/3. Thanks to @ValleyBell for catching this.
I also tested using a `dac_byte_device` instead of a `speaker_sound_device`, which would save some more code. Unfortunately this introduces some additional sound artifacts which don't happen with the latter (and neither on actual hardware), so I have abandoned this idea for now.
> ddr/kc: fix DAC output on KC 85/2

- hash/msx1_cart.xml
- Swap sets to make the newer version the parent: btanuki and btanukia, clapton2 and clapton2a, and yrm101 and yrm101a.
- Removed entries where the copy protections are patched out:
- alcazara, antarct, coastraca, coastracb, gooniesa, gooniesb, guardica, hyprallya, hyprallyb, hyprallyc, hypersp3a, hypersp3b, kingvalb, kingvalc, kingvald, mopirangc, mopirangd, midbrosa, mkidwiza, konbballa, konboxina, konboxinb, konfootba, konfootbb, kongolfb, knightmra, knightmrb, konsoccrb, konsoccrc, pingpongb, pingpongc, pippolsa, pippolsb, pippolsc, pitfallb, qberta, rambob, ramboc, sboy2a, tetris, thexdera, thexderb, twinbeea, twinbeeb, twinbeec, yiear2b.
- Renamed antarcta to antarct, pillboxa to pillbox, rogerruba to rogerrub, tetrisa to tetris.
- Removed seikachoa and starblazb. Bad dumps.
- …
> msx1_cart.xml: Clean alts and versions.

- hlsl/post.fx
- src/osd/modules/render/d3d/d3dhlsl.cpp
-hlsl/post: Fixed double-drawing of screen data with D3D9 HLSL and screen scale/offset. [Ryan Holtz]
-d3dhlsl.cpp: Fixed screen-container search function. Fixes #10872. [Ryan Holtz]
-d3dhlsl.cpp: Fixed downsample pass, fixes blocky vector bloom. [Ryan Holtz]
> More HLSL regression fixes

- hash/c64_cass.xml
This patch largely reverts my previous attempt at "improving" things, with my apologies!
1. I've undone "optimising" some of the Ultimate Tape Archive's dumps, as it turns out they were more fastidious than the tools I was using, not less
2. Now the originals are back in place, I've removed the redundant subsequent "alt" additions of the originals
3. In cases where the Ultimate Tape Archive has dumped the same tapes as me, I've replaced mine with theirs (they're more fastidious than me too, and I gave them my own physical tapes, so you're not missing anything)
4. I also added Micro Rhythm +, while I was there
These are all sourced from the Ultimate Tape Archive V3.0, the current latest version of the archive.
Thanks!
> Fix various C64 tapes

- src/mame/snk/hng64_3d.ipp
- src/mame/snk/hng64_v.cpp
- this bit gets disabled on the fatal fury wild ambition title screen, and roads edge name entry screen, both cases where tilemap wrap definitely looks to need to be disabled.
> hng64.cpp - add 'wraparound enable' bit to the tilemaps, 

- scripts/src/bus.lua
- src/devices/bus/isa/hpblp.cpp
- src/devices/bus/isa/hpblp.h
- src/devices/bus/isa/isa_cards.cpp
- src/emu/devcpu.cpp
- src/emu/devcpu.h
This adds support for the HP82321A BLP cards sold by HP about 35 years ago. Note that this needs a quirk in the new68k to extend a 68k bus cycle until the x86 host served the request. I'm happy for smarter ways to achive this.
> bus/ISA: Added HP82321A BASIC Language coprocessor

- src/mame/dataeast/dec0.cpp
- src/mame/dataeast/dec0.h
- src/mame/dataeast/dec0_m.cpp
- src/mame/dataeast/dec0_v.cpp
Split up class for reduce optional object finders. Remove bankdev.
Fix namings, Add notes
Fix side effect in some protection functions
> dataeast/dec0.*: cleanup

- hash/ibm5170_cdrom.xml
Alien Carnage (Europe) [redump.org]
Ecstatica (Europe) [redump.org]
Ecstatica (Europe, Argentum Collection release) [redump.org]
Ecstatica (Europe, English only) [redump.org]
Ecstatica II (Germany) [redump.org]
Ecstatica II (Germany, Mega 3 Pak Volume 1 release) [redump.org]
Fables & Fiends - Book One: The Legend of Kyrandia (Asia) [redump.org]
Fables & Fiends - Book One: The Legend of Kyrandia (Denmark, Euro Power Pack release) [redump.org]
Fables & Fiends - Book One: The Legend of Kyrandia (Europe) [redump.org]
Fables & Fiends - Book One: The Legend of Kyrandia (Europe, Westwood 10th Anniversary release) [redump.org]
Fables & Fiends - Book One: The Legend of Kyrandia (Europe, The Hit Squad release) …
> ibm5170_cdrom.xml: 28 New Software list additions

- src/mame/konami/nwk-tr.cpp
- it's a sequel that just happens to share some ROMs.
> konami/nwk-tr.cpp: Make racingj2 as a parent, not a clone of racingj

- hash/camplynx_cass.xml
Replaced country's abbreviation "Fra" by the full name "France"
> camplynx_cass: Metadata cleaning

- src/devices/machine/wd_fdc.cpp
- src/devices/machine/wd_fdc.h
Patch from Peter Philips:
• DRQ fix for Marble Maze
• FM sync prefix fix for Marble Maze
• Fix for false FM sync bug (8511)
• live_info::shift_reg_low() which allows for exact bit matches (> 16)
• update all shift register comparisons to use shift_reg_low(16) (or approrpriate)
• live_info:shift_reg_data() which cleans up several LOGSHIFT() statements
> machine/wd_fdc.cpp: Don’t clear DRQ  on LDB/INTR, and fix spurious READ TRACk/ADDR FM mark syncs

- hash/pce.xml
- hash/pcecd.xml
- src/devices/bus/pce_ctrl/pcectrl.cpp
- src/devices/video/huc6270.cpp
- fix: draculax Stage 4' "all blue" Richter;
- fix: faussete Stage 2 excessive slowdown and erratic water line;
- fix: xwiber Stage 2 boss never spawning [MT#07384](https://mametesters.org/view.php?id=7384)
- fix: ppersia misplaced line [MT#07727](https://mametesters.org/view.php?id=7727)
- fix: ddragon2 options menu display;
- fix: tblade hang after third person view [MT#08585](https://mametesters.org/view.php?id=8585)
> huc6270.cpp: fix RCR sync, it happens one line earlier

- src/mame/dataeast/dec0.cpp
I've removed the needless list at the top, and I fixed a few grammar mistakes.
> dataeast/dec0.cpp: Removed superfluous list of games in comment

- hash/leapster.xml
leapster.xml:
Disney Princess (USA, set 2) [TeamEurope]
Nick Jr. Go Diego Go! - Animal Rescuer (USA, set 2) [TeamEurope]
Leapster 2 Gaming Pop (USA) [TeamEurope]
Number Raiders - Arcade-Style Learning! (USA, set 1) [TeamEurope]
Sonic X (USA, set 1) [TeamEurope]
Also change ROM sizes to hexadecimal, fixed some game metadata and added some games to the missing/dumped list on comments.
> leapster.xml: Dumped five USA games

- src/devices/cpu/mips/mips3.cpp
- src/devices/cpu/mips/mips3.h
- src/devices/cpu/mips/mips3com.h
- src/devices/cpu/mips/mips3drc.cpp
The IDT MIPS-series manual is rather explicit about the R4650 lacking TLB entirely. Instead, COP0 registers 0 through 3 are occupied by Instruction Base/Bound and Data Base/Bound pairs, with the CPU throwing an address error if a user-mode memory access exceeds that bound, and adding the Base register to the user-mode access's virtual address if it's in-range.
This fixes an assortment of crashes in at least rapidrvr, rapidrvrp, finfurl, motoxgo, and 500gp due to Namco's own program code accessing null or near-null addresses, as all games run in Kernel mode, meaning there is no address translation nor bounds-checking.
> Fixed memory access handling in the IDT MIPS R4650 core

- hash/fmtowns_cd.xml
4D Driving (FM Towns Marty version) [redump.org]
Doki Doki Disk CD-ban - Club D.O. Vol. 2 [redump.org]
Doki Doki Disk CD-ban - Club D.O. Vol. 3 [redump.org]
FM Towns Marty Tentou Auto Demo '93 Natsu [redump.org]
FM Towns Super Technology Demo 1993 (HME-919) [redump.org]
HomeStudio V1.1L10 [redump.org]
Medicco to Asobou - Kazu-Katachi-Ryou [redump.org]
Monster Planet 2255 [redump.org]
NHK Special - Ginga Uchuu Odyssey Vol. 1 - Tabidachi Waga Taiyoukei [redump.org]
Pack 13000 Free Soft & Shareware [redump.org]
Psychic Detective Series Vol. 2 - Memories (DCCS remake) [redump.org, cyo.the.vile]
The Yachtman [redump.org]
Mad Paradox [redump.org]
Provvidenza - …
> fmtowns_cd.xml: 12 new dumps, 2 replacements

- hash/svi318_cass.xml
- Lowercase on descriptive words (Alt, Conversion, etc.).
- Replaced countries' abbreviations by their full name.
> svi318_cass.xml: Metadata cleaning

- src/mame/mame.lst
- src/mame/namco/namcos10.cpp
Mr. Driller 2 (US, DR23 Ver.A) [TwistedSymphony, Bill, Coolmod, simzy39]
I've used the in-game operator menu to wipe the settings and additionally overwrote the header of the EEPROM section (0x40000-0x40020) with 0x55 so that the game will trigger the first boot sequence when you first boot it up. Same thing as done in: https://github.com/mamedev/mame/pull/11059
> namcos10: Add new clone Mr. Driller 2 (US, DR23 Ver.A)

- src/devices/cpu/m6809/6x09dasm.cpp
- src/devices/cpu/m6809/6x09dasm.h
- src/devices/cpu/m6809/m6809.cpp
- src/devices/cpu/m6809/m6809.h
- src/devices/cpu/m6809/m6809.lst
I used this as a reference: https://github.com/hoglet67/6809Decoder/wiki/Undocumented-6809-Behaviours
Sorry for the third attempt at a PR. All of @cuavas 's comments have been addresses. The disassembler treats consecutive page opcodes as Vas wishes.
> cpu/m6809.cpp: Add undocumented Opcodes

- src/mame/taito/taito_f3_v.cpp
fixes mt08593: landmakr and clones: ending slide has wrong vertical offset
checked against pcb recordings for
landmakr(+) pbobble2(+) dariusg(+) recalh(+) elvactr(+) gekiridn(+)
arabianm(=) lightbr(=) bublbob2(=) trstar(=) ringrage(=) kaiserkn(=) bubblem(=)
this... feels questionable without hw testing, and there are certainly other places tilemap offset problems could come from, but this is a relatively clean solution, not out of the question for this hardware, and seems to make sense when considering that the affected playfields are 2/3 and the way affected games write line zoom for those playfields.
> taito/taito_f3_v.cpp: Ignore first line zoom value (appears to fix MT08593)

- src/mame/mame.lst
- src/mame/namco/namcos10.cpp
ballpom was previously known as unks10md2 but was able to be named with the redump. ballpom boots but needs an MGEXIO board to function so you will only see an error screen. I noted in the driver you can make a cheat to patch memory addr 0x8007af02 to be 0 which will skip the error for testing.
The old mrdrilrg main entry was a bad dump. Doing a deeper inspection of the game data itself (taking the invalid block table into account) revealed that the game data was the same as mrdrilrga which is a good dump, so I removed mrdrilrga and replaced mrdrilrg with the ROM entries that were in mrdrilrga.
I added a blurb to the header aimed at dumpers and anyone trying to verify dumps because there was a lot of confusion recently about what was and wasn't a bad dump. I've also unmarked ptblank3 and …
> namco/namcos10: New dumps (medalnt2, taiko4, taiko5) and redumps (ballpom, g13jnc, gjspace, puzzball, taiko6)

- src/mame/layout/smiconk.lay
- src/mame/snk/miconkit.cpp
Verified with these images and from Dillweed via Discord
> snk/miconkit.cpp: Add orange overlay for Space Micon Kit

- src/mame/namco/namcos10.cpp
(left them to default to Japan for now as the Konotako shows a different license as English, and it is not yet known how the parent Gamshara set will behave)
> namco/namcos10.cpp: Labelled region/licensee DIP switch settings for Mitchell games

- hash/msx1_cart.xml
Warroid (Japan, alt) [file-hunter]
Water Driver (Spain, alt) [file-hunter]
Senjou no Ookami (Japan, alt) [file-hunter]
Word Processor (United Kingdom) [file-hunter]
Yellow Submarine (Japan, Jast) [file-hunter]
Yie Ar Kung-Fu II - The Emperor Yie-Gah (Korea) [file-hunter]
Youkai Tantei Chimachima (Japan, alt) [file-hunter]
Yogoetamjeong (Korea) [file-hunter]
Youkai Yashiki (Japan, alt) [file-hunter]
Young Artist (Arab, v1.18) [file-hunter]
Chou Senshi Zaider - Battle of Peguss (Korea) [file hunter]
Zanac A.I. - 2nd Version (Japan, alt 2) [file-hunter]
Zenji (Japan, alt 1) [file-hunter]
Zexas Limited (Japan, alt 3) [file-hunter]
Westen House (English, v1.3.1) [santiontanon]
Westen House (Spanish, v1.3.1) [santiontanon]
Westen …
> msx1_cart.xml: Software list additions

- src/mame/psikyo/psikyo.cpp
Adds correct timings for Tengai to psikyo.cpp.
Measured using a Saleae Logic Pro 16 logic analyzer, sampling at 500Mhz.
Pictures, logic traces are available at:
http://img.buffis.com/psikyo/tengai/
(Also random note, I think the HSync timing specied for Strikers 1945 in the docs is likely incorrect, but I haven't had time to check on my Strikers 1945 board yet)
> psikyo/psikyo.cpp: Use accurate measurements for Tengai video timings

- src/mame/sanyo/mbc200.cpp
This should recreate the exact behavior of the original floppy drive selector, driving a 74145 with bits 4..6 of port B of the 8255A PPI.
The original machines had only 1 or 2 floppy disk drives, but it was possible, as an option, to add 2 external drives,  a BIOS alteration source code for the 8" format was provided, but the boot disk loaded the same format/skew table for all the 4 devices.
> sanyo/mbc200.cpp: Fix floppy drive selection (was stuck on A:)

- src/mame/psikyo/psikyo.cpp
Fixes a off-by-one error where number of visible lines were 223 instead of 224.
There are indeed 39 HSync PULSES between the visible color data... but the first one of those are signaling the end of the previous visible frame, and the last one of them is signaling the start of first visible row of the next frame, which means that there's 38 "non-visible" lines during blanking.
This means:
262 total lines. 224 visible. 38 blanking.
> psikyo.cpp : Fixes an off-by-one error in m_screen->set_raw

- src/mame/psikyo/psikyo.cpp
The code for Tengai was updated to be correct, but not the docs. This fixes the docs too.
I was looking at sync-pulses surrounding front/back-porch, and sync pulses during vblank previously. This is an incorrect way of looking at things.
See: http://img.buffis.com/psikyo/tengai/vblank.png which has a very easy to grasp visual representation of the VBlank lines.
> psikyo/psikyo.cpp: Fixed docs for sync timings of Tengai and Strikers 1945

- src/devices/bus/nscsi/cd.cpp
- src/devices/bus/nscsi/cd.h
- src/devices/machine/t10mmc.cpp
- src/mame/sega/segas32.cpp
I initially made this NSCSI CDDA implementation to go with another PR but ran into some harder to resolve issues, but this code is being requested for some other machines so I am submitting it on its own. I've left TODOs for things I couldn't test on my targets and couldn't find something that made use of the feature. Implemented enough that CDDA audio worked on Konami GV games during testing. I didn't want to break the old code and don't know of a better default value so I set `mode_data_size` to default to the same as what `sizeof(mode_data)` returned.
Also found an issue with the `set_output_gain` calls in t10mmc.cpp when cross referencing between the documentation and the old CD-ROM code so I threw in a fix for that as well.
> nscsi/cd: Implement basic CDDA support

- hash/msx1_cart.xml
- hash/msx2_flop.xml
- hash/msx2p_flop.xml
- hash/msxr_flop.xml
cpc_flop.xml:
Removed Livingv2 (msx2 software, livingst in msx2_flop.xml)
Removed LASTMIV2w (msx2 software, lastmiss in msx2_flop.xml)
msx1_cart.xml:
Fix duplicate rom name between zeroinfs and zeroinfsa
msx2_flop.xml:
Removed The Witch ‘Iz’ (Japan)   (duplicate from witchiz in  msx2p_flop.xml)
Removed Mobius Debugger 2 - Eternal Striker (Japan, demo) (duplicate from estriker in msxr_flop.xml)
Removed Shoulder Blade (Japan, bad dump?) (duplicate from shdblade in msxr_flop.xml)
msx2p_flop.xml:
Removed Battle Bomber (duplicate from battlebo in msx2_flop.xml)
> Remove some cpc and msx softlist duplicates

- src/emu/recording.cpp
Before, mslugx (59.185606 Hz) would have this AVI framerate
```
framerate:   59.185000000000002
numerator:   59185
denominator: 1000
```
Now, it has
```
framerate:   59.185609563542229
numerator:   1000000000
denominator: 16895999
```
which is directly inherited from the internal refresh rate of the game.
This affects audio/video sync and timings. Here's a comparison of how the same shot at the very start and 200k frames in has audio that appears differently:
After my change, it appears the same in both cases (the sound effect now also appears on the same frame as the shot, but that's just a subjective observation without a recording of the real machine):
Also notice how the same scene happens on entirely different frames. This is because fps value reduction results in duplicate or …
> set accurate avi framerate instead of rough approximation

- src/mame/psikyo/psikyo.cpp
- Remove MACHINE_IMPERFECT_TIMING from psikyo.cpp roms
- Minor documentation fixes (IRQ info, typo for LH5168)
Main motivation for the incorrect timing seems to be that these have four frames of input lag. This is actually consistent with PCBs though, unlike what the comment states.
When doing measurements with a 240fps iphone camera and "Is it snappy" on Tengai, the current behavior is:
- Input is triggered during a frame (and likely sampled during vblank?)
- Three frames of inaction follows
- The fourth frame afterwards, the sprite moves.
With sprites at top of screen, this gives delays of 54.2ms -> 62.5ms for me from input press, to sprite changing.
This is consistent with mame behavior:
- Press pause
- Hold an input and step-pause until movement
- Movement will trigger on fourth frame …
> psikyo.cpp: Remove MACHINE_IMPERFECT_TIMING and fix some docs

- src/mame/sega/sg1000.cpp
The high part of the port is always connected to the cassette interface, and should not be masked by the joystick. See https://segaretro.org/images/e/eb/SC-3000ServiceManual.pdf page 5 (of the PDF)
> sega/sg1000.cpp: fixed tape loading

- 3rdparty/linenoise/linenoise-win32.c
restores d73b585d65936a5b9736e23cf85e543ef5bd2779
> 3rdparty/linenoise: Support keypad Enter on Windows

- src/mame/sanyo/mbc200.cpp
The MBC-200 speaker can be driven by 2 PPI chips, connected to one of the two Z80 CPUs, through 1Kohm resistors. The speaker is driven by a simple bipolar transistor commutation, and the sound is always generated by simple bit-banging loops on one of the two CPUs. The audio level is fixed, no matter whether both the CPUs are sending a high level input together. The keyboard click is..  just a short ON/OFF commutation, no oscillation at all !
> sanyo/mbc200.cpp: Mix PPI sound outputs for system speaker

- src/devices/sound/msm5232.cpp
MSM5232 determines the attack or decay duration of each note from the lower 3 bits of Attack Time Data(addr $8,$9), or the value specified in the lower 4 bits of Decay Time Data(addr $A,$B).
According to the datasheet, when the lower 3 bits of the Attack/Decay Time Data are 0x6 or 0x7, the second bit is ignored and the value for 0x4 or 0x5 is used.
The current msm5232 emulation implementation does not take this into account.
For example, with 0xE specified in the Decay Time Data, the decay duration of a note should be 4 seconds, but the current implementation decays for 16 seconds.
This commit corrects the Attack/Decay time to be in line with the datasheet when 0x6 or 0x7 is specified for the lower 3 bits of Attack/Decay Time Data. …
> MSM5232: Use correct attack/decay time nominal value when certain attack/decay time data is specified

- src/devices/bus/rs232/pty.cpp
- src/devices/bus/rs232/pty.h
Using the rs232 pty backend works very badly as there is no flow control. I have copied flow control support from the null_modem backend, and at least the XON/XOFF version works well with the emulated VT102. (I don't know what to test the other ones with.)
> rs232 pty: flow control copied from null_modem

- src/mame/seta/seta.cpp
- fix [MT#08614](https://mametesters.org/view.php?id=8614)
> seta/seta.cpp: workaround extdwnhl ending crash

- src/devices/cpu/i386/cpuidmsrs.hxx
- src/devices/cpu/i386/i386.cpp
- src/devices/cpu/i386/i386op16.hxx
- src/devices/cpu/i386/i386op32.hxx
- src/devices/cpu/i386/i386segs.hxx
- src/devices/cpu/i386/i486ops.hxx
- src/devices/cpu/i386/pentops.hxx
- src/devices/cpu/i386/x87ops.hxx
At the moment, the cores derived from i386 create megabytes of logerror() debug spew every second when running protected-mode applications. 
For example, under EMM386, most hardware IRQs will cause a GPF. Since all GPFs are printed by logerror() in i386, that means that under normal usage you get thousands and thousands of task gate error GPFs in your error log that don't mean anything.
This sets up a more granular logging system based on LOGMASKED bits to control the output and make it easier to debug systems using i386.
> Changed logerror stuff in i386 to use granular masking

- src/mame/dec/vt100.cpp
Not everyone likes green, and I think at least most of those terminals were available with these colors.
> dec/vt100.cpp: add setting for phosphor color.

- src/mame/sega/megatech.cpp
Replaced the duplicate After Burner entry with the missing Great Soccer, in the initial comments. Also did a bit of cleanup with the titles.
Judging from the comments, perhaps these should be marked as "Bad Dump"?
- Fantasy Zone
- Turbo Outrun
> sega/megatech.cpp: Fixed some titles in the comments

- hash/msx1_cart.xml
- src/devices/bus/msx/module/skw01.cpp
- src/devices/cpu/z80/z80.cpp
- src/devices/cpu/z80/z80.h
- src/mame/sega/system1.cpp
z80.cpp: Fix incorrect cycle counts when custom cycle tables are used.
msx1_cart.xml:
A Life Planet - M36 - Mother Brain has been aliving (Japan)
> z80.cpp: Fix incorrect cycle counts when custom cycle tables are used.

- hash/abc806_flop.xml
Update CRC value (missing first character) on "cpm_turbo.img" file
- fix: #11192
> abc806_flop.xml: Update CRC value

- hash/st_flop.xml
- Replaced regions abbreviation by their full name ("Euro", "Swe")
- Lowercase to descriptive word "Rev."
> st_flop.xml: Metadata cleanups

- src/mame/mame.lst
- src/mame/trs/coco12.cpp
- src/mame/trs/coco12.h
Remove cocoe and coco2 drivers. They existed to have multiple bios options available.
Make available all of the combinations Color BASIC and Extended Color BASIC versions to the coco driver.
> trs/coco12.cpp: add bios options

- src/mame/taito/taito_f3_v.cpp
correct a mistake introduced in 819a5c4
> taito/taito_f3_v.cpp: fix vram wrap width (bubble symphony platforms)

- src/devices/video/epic12.cpp
- src/devices/video/epic12.h
- src/mame/misc/cv1k.cpp
Change clipping for CV1K games to draw 32 pixels surrounding the visible area.
This can be easily seen in Muchi Muchi Pork, which has a VRAM viewer in Special mode (Object Test), which will show 32 px drawn around the visible areas of framebuffers.
See: https://www.arcade-projects.com/threads/research-into-cv1000-blitter-performance-and-behavior.24385/#post-364121
For most gamers, this wont really matter at all... except for in Muchi Muchi Pork, where changing this actually fixes a bug for Rafute (yellow ship).
When Bombing with Rafute (not the other two character), the screen background will go wavy in a sine-like pattern. Currently in mame, the top of screen will show black pixels when this happens.
Like this: http://img.buffis.com/mmppatch/without_patch.png
With this fix for clipping, …
> video/epic12.cpp: Fix clipping of CV1K games

- src/devices/cpu/m6800/m6801.cpp
- src/devices/cpu/m6800/m6801.h
- src/devices/machine/timekpr.cpp
- src/devices/machine/timekpr.h
- src/emu/screen.cpp
- src/mame/mame.lst
- src/mame/roland/roland_jx8p.cpp
- src/mame/skeleton/600cat.cpp
- src/mame/skeleton/digitech_gsp5.cpp
- src/mame/yamaha/ymdx7.cpp
- src/mame/yamaha/ymdx9.cpp
- src/osd/modules/lib/osdobj_common.cpp
- src/osd/sdl/video.cpp
- src/osd/windows/video.cpp
In addition to a simple skeleton driver that at least shows an initial readout on the LCD, this includes the following other changes:
- Fixed the HD6303R CPU to use an internal map derived from the M6803, and removed the now-unneeded address map entries from drivers using it.
- A prescale limit of 8 for systems with particularly small LCDs still produces bad-looking results, so I raised it to 20, as it should be relatively harmless, and any accelerated renderers will clamp to the maximum-supported texture size anyway.
- I noticed that `screen_device` was still referring to old MCFG_ macros in its logerror call to exhort devs to use raw screen parameters, so I replaced both with the relevant member function names.
- The Dallas DS1643 is a near-identical clone of the STMicro M48T58, so I …
> Skeleton driver for 600 Cellular Activation Tester

- src/devices/sound/lc82310.cpp
- src/devices/sound/mas3507d.cpp
- src/devices/sound/mp3_audio.cpp
- src/devices/sound/mp3_audio.h
Follow up to https://github.com/mamedev/mame/pull/11210 based on a comment from cuavas.
Tested save states in squizchs (Namco System 10) and ddrmax (Konami System 573) to make sure the known devices that use the MP3 decoder are working now. For ddrmax I tested both in the game menus where it plays an MP3 for BGM without anything special, and also in-game during a song to make sure everything looked fine with the notes as they scrolled. 
Also missed two save items in LC82310 so I added those in as well.
> sound/mp3_audio: Implement save states for MP3 decoder

- hash/cpc_cass.xml
- Replaced countries' abbreviation by their full name.
- Lowercase on descriptive words (like: "Alt", "Demo", "Side", "Incomplete Dump", etc...)
> cpc_cass.xml: Metadata cleanups

- src/devices/bus/ata/atapicdr.cpp
- src/devices/bus/scsi/scsicd.cpp
- src/devices/bus/scsi/scsicd.h
- src/mame/konami/konamim2.cpp
- src/mame/mame.lst
This fixes the recently broken CDDA audio for CD-ROM drives. nscsi already had set_cdrom called on device_reset so no change required there. Tested on Konami GV, Konami Firebeat (ppp series), and Konami System 573 (early DDR games before 3rd mix).
The reason these broke is the DVD commit (https://github.com/mamedev/mame/commit/28104cdbdfc39b0ced6411381ffb074772dce345) removed `t10mmc::SetDevice` which was called when an image was changed and was responsible for calling `m_cdda->set_cdrom(...)`.
@galibert Please review and fix any remaining issues with CDDA before this month's release.
> ata/atapicdr, scsi/scsicd: Set CDDA image on device reset

- src/lib/formats/fs_coco_rsdos.cpp
There are 8 entries per sector, not 4.
> formats/fs_coco_rsdos.cpp: Fix directory entry count

- src/mame/heathkit/h89.cpp
- src/mame/heathkit/tlb.cpp
Implemented more of the H89. 
- Added the 4 ports which cause an NMI (these were ports that were defined on the H8, the NMI allows the ROM to handle some backward compatibility with the H8).
- Added the 3 serial ports from the H-88-3 serial board.
- Implemented the ORG-0 upgrade, which allowed the H89 to run CP/M, and was still compatible with HDOS.
- Fixed the read value for non-existent memory.
- Added the write-protectable Floppy RAM.
New ROMs
- MTR-88
- MTR-89
More tech details
- description of the different models.
- available commands for MTR-88 and MTR-89.
- description of the memory map.
- list of assigned port addresses.
> heathkit/h89.cpp: Implement more functionality, add new monitor ROMs, add more tech details

- bgfx/chains/hlsl.json
- src/osd/modules/render/d3d/d3dhlsl.cpp
- src/osd/modules/render/drawd3d.cpp
Fix for #11107: Simply removed the erroneously copy/pasted line.
Fix for #11106: Avoiding redundant state-set calls was going awry. We now ensure that the first `set_texture` call of a scene always succeeds by clearing the cached texture pointer at frame start.
Fix for #11104: Calling `post_pass` and `downsample_pass` to generate bloom targets when bloom is disabled was causing issues when applying the post/shadowmask pass. Avoid calling them entirely if bloom is disabled, since the downsampled targets are not used anyway.
> BGFX and D3D9 renderer fixes for issues #11104, #11106, and #11107

- src/devices/cpu/m6809/m6809.lst
Further testing has determined there is an error in the Hoglet67 paper.
> m6809/m6809.lst: Set V flag on XDEC

- hash/gba.xml
AGB Aging Cartridge (World, version 1.0) [SmellyGhost, Forest of Illusion]
AGB Aging Cartridge (World, version 9.0) [Suicune41, Forest of Illusion]
Aero the Acro-Bat - Rascal Rival Revenge (Europe, prototype earlier) [LongwoodGeek, Forest of Illusion]
Chokkan Hitofude Advance (Japan, prototype) [xprism, Forest of Illusion]
Commandos 2 (USA, prototype) [DillyDylan, Forest of Illusion]
Dark Eden (prototype) [Ian Dunlop, Forest of Illusion]
Demon's Crest (prototype) [Ian Dunlop, Forest of Illusion]
Manic Miner (Europe, 20030307) [March42, Forest of Illusion]
Mario Kart XXL (demo, 20040417) [Forest of Illusion]
R3D-Demo V1 (demo) [Forest of Illusion]
Racing Gears Advance (USA, prototype, 20030922) [XBrav, Forest of Illusion]
Sea …
> gba.xml: Added 21 prototypes.

- hash/oric1_cass.xml
Bandit (Express Software) [oric.org]
Caspak [oric.org]
Dinky Kong [oric.org]
Base Mercure [oric.org]
1815 [oric.org]
Lone Raider (France) [oric.org]
Changed the system's name in the softwarelist name (missing the dash)
Lowercase on some French words
> oric1_cass.xml: Software list additions

- src/devices/sound/spu.cpp
- src/devices/sound/spureverb.cpp
- src/mame/namco/namcos10.cpp
- src/mame/namco/ns10crypt.cpp
- src/mame/namco/ns10crypt.h
Redo of https://github.com/mamedev/mame/pull/11236 + fix a small save state-related explosion caused by the SPU if you save state in any PS1-based game at the wrong time (when a "valid" reverb preset isn't in the registers). 
`spu_reverb_cfg` should also probably be set to null when a valid reverb preset isn't found, but that'd have noticeable changes to the audio for potentially all PS1 games and I don't have the energy to test that.
Edit: To give more extra info. The save state issue happens with `mrdrilr2`. Save state on the title screen or similar and load the save state again from command line using something like `mame mrdrilr2 -state 1`. It immediately crashes MAME due to the null pointer without the patch here. The reverb settings in the registers don't match any known presets so …
> namco/namcos10: Add partial decrypter for Point Blank 3 [Peter Wilhelmsen, Samuel Neves]

- scripts/src/bus.lua
- src/devices/bus/epson_qx/cqgmem.cpp
- src/devices/bus/epson_qx/cqgmem.h
- src/devices/bus/epson_qx/option.cpp
This implements the 1 MB memory expansion board that was released by Commodity Quote Graphics for the Epson QX-10.
> qx10: Add Commodity quote graphics memory expansion board

- src/mame/apple/apple2gs.cpp
The ROM 1, the ram size calculation is a little off. For the base case of 256K-1.125MB, the e0/e1 memory needs to be subtracted as well. (Currently, a 256K apple2gsr1 has 384k).  Once you start getting into 2MB and 4MB, etc memory cards, that memory shouldn't be subtracted - if you install a 4MB card, you have 4megs on top of 0/1/e0/e1, for a total of 4.25MB.
> apple2gs: rom1 ram size logic

- hash/msx1_cart.xml
Rally (Japan) [file-hunter]
Rise Out from Dungeons (Korea) [file-hunter]
River Raid (Japan, alt) [file-hunter]
RX Editor YRM-302 (Japan, alt) [file-hunter]
QBIQS (v1.2) [file-hunter]
QBIQS (v1.1) [MSXDev]
QBIQS (v1.0) [MSXDev]
Quartet (v1.2) [MSXDev]
Quartet (v1.1) [file-hunter]
Questprobe 2: Spiderman [file-hunter]
Raftoid (v1.1) [MSXDev]
Raftoid (v1.0) [file-hunter]
Ratbox [file-hunter]
Raven [MSXDev]
Reflexion [MSXDev]
Reflexion (alt) [MSXDev]
Relevo's Snowboarding [MSXDev]
Retaliot [MSXDev]
Risky Rick (demo) [file-hunter]
RMD [n.i]
Robo Rumble [MSXDev]
Robots [MSXDev]
Robotto Demo [file-hunter]
Running Naked in a Field of Flowers [MSXDev]
Running Naked in a Field of Flowers (older) [file-hunter]
Ruptus [inufuto]
New …
> msx1_cart.xml: Add 28 items, 26 working

- src/mame/atari/atarist.cpp
`ste`, etc, use `m_videox` instead of `m_video`, which causes a segfault.
> atari/atarist.cpp: (ste) don't segfault immediately when starting up

- src/devices/video/epic12.cpp
Fix issue where some games do very large over-draws which when utilized in Blitter calculations will cause more delay than whats seen on hardware. The fog in S1 of Mushi Futari 1.5 is a good example of this.
On Mushi Futari 1.5, in the section before the boss, the Blitter delay seen on PCB is aprox 12 milliseconds at peaks. With this fix, it matches that quite well!
It's not 100% clear to me this is exactly how things behave, but this should be closer to the truth, until I can figure out a more reliable and reproducible test-case.
See discussions on this PR for background : https://github.com/mamedev/mame/pull/11227
For reference, Saleae logic analyzer output is available in: http://img.buffis.com/misc/futaris.sal
> video/epic12: Apply clipping to Blitter calculations as well

- src/mame/mame.lst
- src/mame/namco/namcos10.cpp
The CD wasn't properly imaged in the past when the dumper had access to it in the past so all we have is a recreated CD image made using the loose files that were available due to the rarity of this version and lack of other options currently. I've left a comment explaining such in the driver and marked it as `BAD_DUMP`. The game does some small checks on the CD to make sure it's the right CD and it accepts the image without issue. Taiko RT only has 20 songs in total so I tested every song to make sure the CD image was playable with music until the end.
Also, I made sure to clear the EEPROM section in 8e this time. It'll show "first power on" on the first boot and have the default settings.
> namco/namcos10: Add Taiko no Tatsujin RT: Nippon no Kokoro

- src/mame/psikyo/psikyo.cpp
I went ahead and verified that Gunbird uses the exact same timings as Strikers 1945 and Tengai, so it should be safe to use them for everything with this driver.
I left the Bootleg as-is though, since I dont know what that hardware looks like.
Gunbird also uses IPL2 for interrupts (Interrupt level 4), see pic below.
Reference pics:
- Pic of test setup: http://img.buffis.com/gunbird/pcb.jpg
- HSYNC: http://img.buffis.com/gunbird/sync.png
- VBLANK IRQS: http://img.buffis.com/gunbird/ipl2.png
- Visible pixels in a row: http://img.buffis.com/gunbird/visible.png
> psikyo.cpp: Accurate measurements for remaining (non-bootleg) games

- src/mame/taito/taito_f3_v.cpp
fixes MT00899, fixes MT02576, canonizes the fix in MT02499.
> taito_f3_v.cpp: Fix visible tile check for alternate tilemap lines

- src/devices/cpu/z80/z80.cpp
The heath/h89.cpp with a z37 soft-sectored controller uses IM0 and places an EI instruction on the bus when DRQ signal is received from the WD disk controller.
I'm putting this part up early to get comments. Maybe someone with more experience with the z80 code could implement the top TODO in this file
```
- Interrupt mode 0 should be able to execute arbitrary opcodes
```
> z80.cpp - Add EI to IM0 handler

- src/mame/taito/taito_f3_v.cpp
trstar regression discovery: https://github.com/finalburnneo/FBNeo/issues/1483
this reverts commit e04cb5691ad699021bb4a45ae61a558edad275b5 in favor of a solution that is cleaner anyway.
> taito_f3_v.cpp: fix line zoom regression

- src/devices/bus/coco/coco_fdc.cpp
There are two parts to the change.  First is a correction to the coco_fdc hardware emulation. Second is file format ordering adjustments wich make things easier for using FLEX on CoCos.
For the hardware change:  Before the change FLEX was unable to boot on CoCo machines.  The behaviour and troubleshooting showed that while the FLEX kernel started up it was unable to read anything from Track 0.  Standard FLEX disks have SD(FM) on Track 0, and the remainder of the disks (for CoCo FLEX) are normally DD(MFM) or could also be SD(FM).  The bug was in the handling of the WDC FDC's INTRQ line.  Reviewing the available documentation and schematics showed that when the FDC asserts INTRQ two things happen.  NMI is asserted on the CoCo bus and the HALT signal is cleared.  The MAME code added an …
> coco_fdc: Allow FLEX to work on CoCo machines

- hash/r8_card.xml
- hash/roland_tnsc1.xml
- hash/roland_tnsc2.xml
- hash/u110_card.xml
- src/mame/mame.lst
- src/mame/roland/roland_tnsc2.cpp
This PR adds:
- a new TN-SC-2 softlist (`hash/roland_tnsc2.xml`), as well as a dummy system for the softlist, similar to TN-SC1
- the following Roland cards:
- PCM card: SN-R8-09 Power Drums U.S.A.
- PCM card: SN-SPLA-01 Sound Elements Vol. 1
- style card: TN-SC2-04 Dance
> add 3 Roland cards 

- src/mame/heathkit/h19.cpp
- src/mame/heathkit/h89.cpp
- src/mame/heathkit/intr_cntrl.cpp
- src/mame/heathkit/intr_cntrl.h
- src/mame/heathkit/tlb.cpp
- src/mame/heathkit/tlb.h
- src/mame/heathkit/z37_fdc.cpp
- src/mame/heathkit/z37_fdc.h
The H19 allowed the user to press the right-shift and reset key to reset the system. Since the h89 shared the common terminal board in the H19, this reset also was routed to the h89 cpu board and reset the entire computer. The actual reset occurs on the release of the keys. 
In mame, the default key for reset is F10. Using the right-shift and F10 now causes the machine (either H19 or H89) to be reset.
A few other general cleanup of comments, formatting, etc. is also done in this PR.
> heath/h19.cpp Implement Shift-Reset functionality

- src/devices/imagedev/floppy.cpp
- src/devices/imagedev/floppy.h
Define the parameters for the Teac FD55-A and FD55-B drives.
> floppy.cpp: add Teac FD55-A and FD55-B drive types

- src/mame/roland/roland_mt32.cpp
This change adds version 2.0.7 of the MT32 rom.  It's a 128k rom that will require banking to work in the future.
> mt32: Add rom version 2.0.7

- hash/megacdj.xml
- hash/segacd.xml
segacd.xml:
Compton's Interactive Encyclopedia v2.00S (USA) [redump.org] Note! Color Mechanica (USA) [redump.org]
Note! Color Mechanica (USA, alt) [redump.org]
What is X'Eye Multi Entertainment System (USA) [redump.org]
megacdj.xml:
Heavenly Symphony - Formula One World Championship 1993 Hibaihin (Japan) [redump.org]
Keiou Yuugekitai Taikenban Hibaihin (Japan) [redump.org]
Lunar - Eternal Blue Hibaihin Auto Demo (Japan) [redump.org]
Microcosm Demo CD (Japan) [redump.org]
Night Trap Hibaihin (Japan) [redump.org]
Popful Mail Taikenban Hibaihin (Japan) [redump.org]
Silpheed Hibaihin (Japan) (Fixed) [redump.org]
Sonic The Hedgehog CD Hibaihin (Japan) [redump.org]
Thunderhawk Hibaihin (Japan) [redump.org]
Urusei Yatsura - Dear My …
> segacd.xml, megacdj.xml: New software list items added

- hash/dragon_cart.xml
Modified software list formatting with the new standards.
Also added this entry:
- Cyrus Chess [Clawgrip, ICEknight]
PCB has two EPROMs, previous entry had been dumped as one ROM. The new dumps come from reading the EPROMs directly.
And finally, added more info to entry for "Test de conducción", based on PCB pics.
> dragon_cart.xml: Entry replaced with good dump, added additional info from PCB, updated softlist to new standards

- src/mame/atari/pong.cpp
Seen some images where an orange overlay exists for Rebound.
> atari/pong.cpp: Note about an orange overlay in Rebound

- src/mame/exidy/exidy.cpp
Updated the color latching for Exidy Targ and Spectar.
Targ - text should be light blue, not white
Spectar - Player's ship & enemy ship that doesn't fire should be yellow. Text is white in Spectar.
For additional information see:
https://www.outerworldarcade.com/targ/targ_video.html
Targ
MAME Current Settings:
BLUE
$6B 
0110.1011
1 = 0 [0- Background ]
1 = 0 [4- Character RAM ($C0 - $FF) ]
0 = 1 [3- Character RAM ($80 - $BF) ]
1 = 0 [2- Character RAM ($40 - $7F) ]
0 = 1 [1- Character RAM ($00 - $3F) ]
1 = 0 [5- ? ]
1 = 0 [6- Moving Object 2 (Player's Missile) ]
0 = 1 [7- Moving Object 1 (Player's Ship) ]
GREEN
$EE 
1110.1110
0 = 1 [0- Background ]
1 = 0 [4- Character RAM ($C0 - $FF) ]
1 = 0 [3- Character RAM ($80 - $BF) ]
1 = 0 [2- Character RAM ($40 - $7F) ]
0 = 1 [1- Character RAM ($00 …
> Update color latching for Exidy Targ and Spectar in exidy.cpp

- hash/ibm5150.xml
- hash/ibm5170.xml
Basket Playoff (re-release) [Total DOS Collection]
Brutal: Paws of Fury [Total DOS Collection]
Discworld [Total DOS Collection]
Dungeon Master II: The Legend of Skullkeep [Total DOS Collection]
Eye of the Beholder: Trilogy [Total DOS Collection]
Hoyle: Official Book of Games - Volume 3 (VGA, Futura release) [Total DOS Collection]
Risky Woods (Futura release) [Total DOS Collection]
Super Space Invaders (Big Games release) [Total DOS Collection]
The Colonel's Bequest (Futura release) [Total DOS Collection]
Thomas the Tank Engine & Friends - Electronic Paint Box [Total DOS Collection]
Thomas the Tank Engine & Friends - The Collection [Total DOS Collection]
Moved from ibm5150 to ibm5170 software list …
> ibm5170.xml: Software list additions

- src/mame/sunelectronics/markham.cpp
The current balance between the two SN76496 chips is off.
A hardware recording can be seen here: https://www.youtube.com/watch?v=CQIogpkafoU
There is a "fill-in" segment in the music that is very clearly audible in the video at 0:28. However, in MAME it is barely audible at all due one of the chips being too quiet.
---
I fixed the balance by measuring the distance of the jump between the "high" and "low" states of the square waves in the intro segment present in each stage music.
This segment has a low tone played on sn1 and a higher tone played on sn2. I measured the distance in the OST recording of the song and adjusted the balance in MAME accordingly. The balance ended up 1/5 to 1/1.
Note that the overall music volume is decreased a lot (by about -8 db) as result of the rebalancing. …
> fix SN76496 chip balance in banbam/pettanp

- src/devices/cpu/mb88xx/mb88xx.cpp
- src/mame/namco/namco54.cpp
There seems to be a bit flip in the 54xx ROM dump. Byte 0x10 is 0x3E, instruction EN #04, enabling interrupts. This occurs early in the interrupt routine and has no effect as interrupts are already enabled. At byte 0x174 is another EN #04, this time correct as it enables interrupts right before ending the routine. This happens again at 0x1BD, 0x1D9, 0x1F6, and 0x214.
This first EN should be a DIS, disabling interrupts during the interrupt routine. This is opcode 0x3F, so the low bit seemingly got flipped.
> namco54: fix interrupt handling

- src/devices/bus/a2bus/romcard.cpp
remove extra ) in the description.
> bus/a2bus/romcard.cpp - Apple II ROM Card (Integer BASIC))

- src/mame/misc/cave.cpp
Wrong clock for YMZ in Gaia Crusaders. That made the sound pitch a bit higher than original pcb.
Unlike other games also using ymz in cave driver, gaia (and theroes) has 16MHz clock for it, instead of 16.9344MHz one. 
Pictures of actual Gaia Crusaders pcb from two different sources:
[https://i.imgur.com/5uTlfh3.png](https://i.imgur.com/5uTlfh3.png)
[https://i.imgur.com/uCM3PFA.png](https://i.imgur.com/uCM3PFA.png)
Other games, such as ddonpach, esprade and dfeveron have different one:
[https://i.imgur.com/0YRIMwi.png](https://i.imgur.com/0YRIMwi.png)
[https://i.imgur.com/vlNZ1YT.png](https://i.imgur.com/vlNZ1YT.png)
[https://i.imgur.com/KkWfDjZ.png](https://i.imgur.com/KkWfDjZ.png)
> cave.cpp: Fixed ymz clock for gaia and theroes

- src/mame/mame.lst
- src/mame/pc/at.cpp
- src/mame/pc/genpc.cpp
- src/mame/pc/pc.cpp
Added BIOS revisions to pc and pcv20, NCR PC6 [eggimac], AUVA VIP 800 [fdiskitup], Hyundai Super 16T and TE [sequoia], Octec XT-286 [ozzyrules] and Nixdorf 8810-20 [MajorMaxdom]
> at.cpp, pc.cpp, genpc.cpp: adding BIOS versions

- src/devices/machine/wd_fdc.cpp
- src/devices/machine/wd_fdc.h
Simplifies how bus inverting is handled, no longer has an if check, but always perform an xor with the value defined in the class. For chips that do inverting, the value will be set to 0xff. For chips without inverting, it is set to 0x00.
> machine/wd_fdc.cpp: Simplify/optimize how bus inverting is handled

- src/mame/heathkit/tlb.cpp
On the H19, when turning off line 25, it should no longer be seen on the screen. On a real H19, that line is no longer scanned out on the CRT and will fade quickly. In mame, the screen still shows the line. This fixes it by putting black on the screen when the `de` value is set.
> heathkit/tlb.cpp: Clear screen lines when DE is deasserted

- src/devices/machine/mm5740.cpp
- src/devices/machine/mm5740.h
- src/mame/heathkit/h89.cpp
- src/mame/heathkit/tlb.cpp
- src/mame/heathkit/tlb.h
Implements the repeat key functionality for the H19, and updates MM5740 to support the repeat input line.
Updates the interrupt handling to properly control the line based on OR-ing the keyboard and serial 8250 interrupt inputs.
> heathkit/h19.cpp implement repeat key, fix intr handling

- plugins/hiscore/hiscore.dat
- plugins/hiscore/init.lua
I made a fix for the hiscore plugin lua, software list entries were not detected as the start of a new cluster. As a result games defined just before software list games also read the memory regions from the following software. I discovered this because sonic spinball was waiting forever for the tf3 memory region to get its initial values.
The hiscore.dat definition does not include the settings menu data which gets cleared on restart, should that be included here?
> Add hiscore plugin support for Sonic Spinball

- src/mame/heathkit/tlb.cpp
- src/mame/heathkit/tlb.h
Implement the interrupt processing that happens on the H19 terminal board when the break key is pressed.
Note: the actual break functionality will not work until the INS8250 properly handles the "Set Interrupt" bit in it's LCR register.
> heathkit/tlb.cpp Implement interrupt handling for break key

- scripts/src/osd/modules.lua
- src/osd/modules/debugger/qt/breakpointswindow.cpp
- src/osd/modules/debugger/qt/dasmwindow.cpp
- src/osd/modules/debugger/qt/mainwindow.cpp
- src/osd/modules/debugger/qt/memorywindow.cpp
- Look for MOC in QT_HOME/libexec if not found in QT_HOME/bin
- Use the Qt6* libraries if the Qt version is >= 6
> Fix Qt6 detection on Linux

- hash/msx1_cart.xml
Replaced Decathlon (Japan) [file-hunter]
D-Day (Korea, alt) [file-hunter]
Deep Dungeon II - Yuushi no Monshou (Japan, alt) [file-hunter]
Dip Dip (Spain) [file-hunter]
Dip Dip (Spain, alt) [file-hunter]
Penguin Land (Korea) [file-hunter]
Dr. Hello (Korea) [file-hunter]
Droids En el Planeta Ingo (Spain) [file-hunter]
Droids the White Witch (Spain) [file-hunter]
Double Face (Arab, alt) [file-hunter]
Daedalian Opus [MSXDev]
Danger Tower [MSXDev]
DAQ Lord of Idar [MSXDev]
DAQ Lord of Idar (flashrom version) [MSXDev]
Deep Core Raider [file-hunter]
Deep Dungeon Adventure (cartridge) [Trilobyte]
Deep Dungeon Adventure (cartridge, alt) [file-hunter]
Deep Dungeon Adventure [file-hunter]
Deep Dungeon [MSXDev]
Defence (v1.3) [MSXDev] …
> msx1_cart.xml: Added 46 items, 43 working.

- hash/snes.xml
- Renamed description "Val d'Isère Championship" to match the box title.
- Toy Story: Promoted parent set to working (it works as well as the clones).
> snes.xml: Metadata fixed

- src/mame/apple/macscsi.cpp
> apple: Stop logging every byte written via SCSI

- hash/mac_flop_orig.xml
- src/mame/apple/mac128.cpp
- src/mame/apple/macii.cpp
- src/mame/apple/maciici.cpp
- src/mame/apple/maciifx.cpp
- src/mame/apple/macpdm.cpp
- src/mame/apple/macprtb.cpp
- src/mame/apple/macpwrbk030.cpp
- src/mame/apple/macquadra700.cpp
New Macintosh software list for MOOF-a-day flux dumps from 4 AM.   This update contains all existing releases through 7/20/2023.   This update builds upon the original contribution from Firehawke, which was deleted last year.   I have tried to incorporate all the suggestions for updates to the Apple II lists.
A-Noid
> New working software list items (mac - macii) 123 dumps

- src/osd/modules/render/drawsdl.cpp
Hello.
I found that when I specify the `-video soft` option, but OpenGL is loaded.
So I created a pull request with a fix so that the FLAG_SDL_NEEDS_OPENGL bit is not set. 
Please reject if my understanding is incorrect.
Best Regards.
----
Command line:
```bash
$ mame -video soft -videodriver directfb -verbose
```
Error log: `OpenGL not supported on this driver:`
```bash
...snip...
Available videodrivers: x11 wayland directfb KMSDRM dummy 
Current Videodriver: directfb
...snip...
Using SDL multi-window soft driver (SDL 2.0+)
Enter sdlwindow_init
...snip...
Leave sdlwindow_init
Enter sdl_info::create
OpenGL not supported on this driver: OpenGL support is either not configured in SDL or not available in current SDL video driver (directfb) or platform
Enter sdlwindow_exit
Leave …
```
> render/drawsdl.cpp: Don't request OpenGL context

- hash/ibm5150.xml
America's Cup Yacht Racing Simulator [Total DOS Collection]
Ballyhoo [Total DOS Collection]
Beyond Castle Wolfenstein (alt) [Total DOS Collection]
Bruce Lee [Total DOS Collection]
Championship Golf - The Great Courses of the World - Volume One: Pebble Beach [Total DOS Collection]
Commando [Total DOS Collection]
F-15 Strike Eagle (3.5", v402.01) [Total DOS Collection]
F-15 Strike Eagle (5.25") [Total DOS Collection]
Deadline (release 27) [Total DOS Collection]
Destroyer [Total DOS Collection]
Gettysburg: The Turning Point (v2.0) [Total DOS Collection]
Hacker II (alt) [Total DOS Collection]
Karateka (v1.0) [Total DOS Collection]
King's Quest (DOS release, v1.0U) [Total DOS Collection]
King's Quest III: To Heir …
> ibm5150.xml: Software list additions

- src/osd/modules/render/draw13.cpp
I built the hh_sm510 driver from 0.256 using Emscripten, but there was an occasional divide-by-zero exception when running with `-video accel`. Debugging revealed it came from `renderer_sdl2::render_quad` in the SDL2 OSD renderer. For some reason, `texture->m_copyinfo->time` was 0 when trying to calculate `texture->m_copyinfo->perf`. I suspect the timer that backs `osd_ticks` might be too imprecise under Emscripten. Since this is only used for performance diagnostics, I assumed it was safe to use 1 as a denominator when `texture->m_copyinfo->time` is 0. After rebuilding with this change, I have not observed the divide-by-zero exception again.
> Fix divide-by-zero in SDL2 OSD renderer when using Emscripten

- src/mame/dataeast/dec0.h
- src/mame/dataeast/dec8.cpp
- src/mame/dataeast/dec8.h
- src/mame/dataeast/dec8_v.cpp
dataeast/dec0.h: remove unused address map
> dataeast/dec8.cpp: Split classes for reduce optional shared functions, Reduce runtime tag lookups

- hash/apple2_flop_orig.xml
New working software list items (apple2_flop_orig.xml)
Dungeon of Doom [John Brown, DefaultGen, eientei, A-Noid]
Zenith [4AM, A-Noid]
The Space Ark [4AM, A-Noid]
Cavern Creatures [4AM, A-Noid]
Argos [4AM, A-Noid]
Cribbage/Solitaire [4AM, A-Noid]
Cyclotron [4AM, A-Noid]
Wings Out of Shadow [4AM, A-Noid]
> apple2_flop_orig.xml: Added 8 working items.

- hash/n64.xml
Corrected the French word "Trésors" (like it is on the box and cartridge)
> n64.xml: Fixed razmoket description

- src/mame/heathkit/tlb.cpp
- src/mame/heathkit/tlb.h
Fix NMI handling, to only trigger after the proper port is accessed.  Only when the ROM needs to update the CRTC registers does it write to the special port to allow the next VSYNC to trigger a NMI. 
The change fixes the Self-diagnostic test in the UltraROM. It was failing because the scratchpad memory is modified during the NMI interrupt routine, and that was conflicting with the memory test of the scratchpad.
> heathkit/tlb.cpp: fix nmi handling for H19

- hash/ibm5150.xml
Fixed "America's Cup Yacht Racing Simulator" SHA1 hash
Renamed "sfootbls" to "spsunday_c" and added as cloneof "spsunday"
Renamed "wingames" to "wingames_c"
Renamed "wldgames" to "wldgames_c"
Moonmist [Total DOS Collection]
Ninja [Total DOS Collection]
Sorcerer (release 4, booter) [Total DOS Collection]
Sorcerer (release 13) [Total DOS Collection]
Space Battles [Total DOS Collection]
Starcross [Total DOS Collection]
Starglider [Total DOS Collection]
Storm (5.25" double sided) [Total DOS Collection]
Super Sunday [Total DOS Collection]
Trinity [Total DOS Collection]
Wall Street [Total DOS Collection]
Winter Games (3.5") [Total DOS Collection]
Winter Games (3.5", alt) [Total DOS Collection]
World Games (5.25") …
> ibm5150.xml: Added 16 items

- src/mame/heathkit/h8.cpp
- Fix the timing of the 2 mSec clock interrupt (was at 1 mSec).
- Fix the frequency of the speaker to 1 kHz (was 2 kHz).
> heathkit/h8.cpp: Fix 2 mSec interrupt and speaker frequency

- src/mame/misc/astropc.cpp
I'm not entirely sure how the code is stored, only that the executable does a lot of in/out communication and then a final XOR with a hard-coded key before writing the function
> misc/astropc.cpp: Add notes on AstroCard dongle from looking at the game's code

- src/mame/apple/apple3.cpp
- src/mame/apple/apple3.h
- src/mame/apple/apple3_m.cpp
Adding the keyboard auto repeat support. The Apple /// has a faster repeat speed that is invoked with the closed apple key. This is based on the Apple2 code.
> apple/apple3.cpp: Add keyboard 2spd autorepeat

- hash/cpc_cass.xml
Added the actual titles that these covertapes were given and tidied up their descriptions in general.
Added "Future Publishing" as publisher.
Promoted `amsac004` to working status (others I tested still froze at some point, so might not be worth testing further until the core gets some fixes).
> Tidied up the Amstrad Action covertapes, promoted amsac004 to working status
