mamedev/mame

src/emu/luaengine.c
src/emu/luaengine.h
src/emu/video.c

These commits add a way to let LUA scripts register a callback
to be invoked before rendering each frame.
This callback typically makes use of other provided methods to draw
custom graphics on top of each frame.
The idea is to let LUA script provide HUD-like features, mostly used for
trainings and TAS runs development.
Signed-off-by: Luca Bruno lucab@debian.org

luaengine: add HUD-like capabilities

---

src/osd/sdl/sdl.mak

- Library names must be lower-case when cross-compiling from Linux (-limm32 instead of -lImm32)
- ntohl() needs -lws2_32

Fix linking for Windows SDL cross-compilations

---

src/mame/drivers/firetrk.c

m_gear+1 is so output of gears will start at 1 instead of 0, to be consistent with other Atari 4-speed shifter games (drag race & sprint series).  Internally gear still starts at 0 (though perhaps that should be changed).

added output so artwork can display current gear settings

---

src/mame/drivers/mappy.c

According to tilt.it (http://www.tilt.it/deb/sidam-en.html), this one was licensed. Claim holds up given that there's a Super Pac-Man licensed to Bally France that was manufactured by Sidam (http://www.gamoover.net/Forums/index.php?topic=29916.0)

Update phozons manufacturer (nw)

---

src/mame/drivers/hikaru.c

this romboard uses the same encryption as Naomi M1/Actel-type cartridges

hikaru.c: added protection key for sgnascar [MetalliC]

---

src/mame/drivers/naomi.c
src/mame/machine/315-5881_helper.c

note: it seems old security data feeding routines can be removed from model3.c now

add Fighting Vipers 2 key

---

makefile

Useful for distro packager, this adds proper references to zlib and flac in the reduced set of libraries (BASELIBS).

*nix: Fixed linking tools against system libraries

---

src/emu/audit.c
src/emu/ui/selgame.c

There's no reason for the GUI to bail on an incorrect CRC (especially with a misleading error message!), and the auditor should actually return NOTFOUND instead of INCORRECT when a ROM is not found.

Don't error out on an incorrect CRC for the GUI

---

3rdparty/mongoose/mongoose.c

If _XOPEN_SOURCE is defined to 600, NetBSD does not provide strtoll
and other stuff.
Sent upstream as
https://github.com/cesanta/mongoose/pull/466
and committed as
https://github.com/cesanta/mongoose/commit/bef3f85ba88f3b2067f4b00c4cc4d290149957df
Signed-off-by: Thomas Klausner <wiz@NetBSD.org>

3rdparty/mongoose: Fix build on NetBSD and possibly Solaris.

---

src/osd/sdl/sdl.mak

I compiled testkeys from Homebrew failed, this patch will help this.

sdl: Add BASELIBS for MACOSX_USE_LIBSDL

---

src/mame/drivers/segae.c

sound code == sega mark3.
extend emu. YM2413.

SEGA:System-E::fantzn2 extend YM2413.

---

src/mame/drivers/segae.c

Reverts mamedev/mame#137
MAME emulates the original hardware games ran on; we don't add "improvements".

Revert "SEGA:System-E::fantzn2 extend YM2413."

---

makefile
src/build/verinfo.py
src/osd/sdl/sdl.mak

The ultimate purpose of this is to get version information into MAME/MESS/UME on OSX that will show in Finder info windows and the applications' about boxes.  There are three parts to the change.
* First commit adds functionality to verinfo.py for generating Info.plist files for OSX.  By default it still generates a Windows resource script.  This meant adding slightly sophisticated command-line argument parsing to it.  I also changed the hand-rolled string matching to use Python's regular expression module.
* The second commit marks the emulator binary as depending on the version source file and decouples the dependencies from the linker inputs.  Editing src/version.c doesn't cause the emulator to be re-linked if nothing else has changed, this changes that.
* The third change embeds …

Version info for OSX binaries

---

src/mame/drivers/mitchell.c

It introduced naming conflicts in two rom sets where the name
bb9.bin is used for two different roms.
Signed-off-by: Thomas Klausner <wiz@NetBSD.org>

Revert part of 34d0ee6b.

---

src/mame/drivers/seta.c
src/mame/mame.lst

Add Daioh (location test version) [CoolMod, trap15]
Remove Daioh (set 1) and replace with Daioh (set 2).
Set 1 was a hack and probably should not have been accepted.

Add Daioh loctest and remove hacked Daioh set.

---

src/emu/sound/segapcm.c

This affects R360 G-LOC where some drum samples play too loud (volume 0xf7 instead of 0x77).
[Example (good volume)](https://www.youtube.com/watch?v=lyOEO0zi9Kk)
[Example (bad volume)](https://www.youtube.com/watch?v=oWmWzsOsQd4)

Fix SegaPCM volume register overflow

---

docs/luaengine.md
src/emu/luaengine.c
src/emu/ui/ui.c

This PR contains minor bugfixes/enhancements related to luaengine.
In particular it:
* fixes a pre-existing infinite loop condition in ui, triggerable via `draw_text()`
* introduces an (optional) text color parameter to `draw_text()`
* fixes a type confusion (float/int) in all drawing methods
* specify color format and screen origin in docs

luaengine: minor bugfixes and enhancements

---

src/mess/drivers/spc1000.c

Currently motor on/off function has not implemented.
Because motor on/off function and cassette play/record button are coupled for port A of AY8910.
I changed the code to support motor check function properly.

(MESS) spc-1000 cassette motor check fix for recording fuction working properly

---

src/mame/machine/n64.c

Now it doesn't do sudden jumps anymore.

Fixed N64 Mouse wrapping.

---

scripts/src/osd/sdl_cfg.lua

This will help me to build latest MAME with homebrew.
I think OSX can use GLEXT with native OpenGL library.

Drop NO_SDL_GLEXT define on OSX

---

src/mame/arcade.lst
src/mame/drivers/vigilant.c

Original driver had all variants based on bootleg PCB, this commit contains corrections for existing sets as well as corrections to sets I recently submitted and a new revision.  There is probably a revision F left to find.  Of note all versions prior to the current 'main' World E actually use mask ROMs in place of some 27C512s which are oversized with the top halves blank aside from ic2 which covers the ic2 & 3 found on E onwards.
Complete set of ROM zips which can replace all existing ones uploaded to:
http://www.system11.org/temp/ROMs/vigilante_sets.zip

Corrections to all Vigilante sets plus new clone

---

src/emu/cpu/avr8/avr8.c

After commit eaa3a955f706ed0c1b477471948e7ae577e74537 Replicator 1 driver spits a whole bunch of log messages that make it worse than before that commit. This pull request suppresses such log flood (except when a developer decides to enable debugging logs for the timers implementation in the AVR8 core)

Avoid log message flood in Replicator 1 driver.

---

src/emu/emuopts.c
src/emu/gamedrv.h
src/emu/info.c

Hello MAME project team.
MAME and MESS combined are happy events.
But, It have problem in the listxml.
The xml can't indicate machine type are arcade(MAME) or console/system(MESS).
I propose to add type attribute in the xml.
It is easy way to add filtering in the custom front-end.
If no filter needs, the attribute can ignore.
I'm tested binary in the clrmamepro after attribute added.
it is no error occured.
thank you.

machine type attribute added in the xml

---

src/mame/arcade.lst
src/mame/drivers/expro02.c

taken from board with 961210 model number same as the others.
New ROM set:
http://www.system11.org/temp/ROMs/fantsia2n.zip

Added 1998 copyright Fantasia 2 version, single ROM difference

---

src/mame/arcade.lst
src/mame/drivers/paradise.c
src/mame/drivers/sidearms.c

added paradisea - alt version of Paradise
added paradisee - Escape license of Paradise
corrected year for Paradise versions to 1994 based on evidence from one of the PCBs
removed comment about bugged bonus round chance + explanation
corrected comments in sidearms.c from my previous commits
ROMs and photos of PCBs for new clones:
http://www.system11.org/temp/ROMs/S11paradise.zip

S11paradise

---

src/emu/sound/es5503.c

If one oscillator is in swap mode, its partner should be treated as
being in swap mode, even if it is set to one shot. This behavior is
undocumented in literature from Ensoniq, but exploited by software
developers. See: https://groups.google.com/forum/#!original/comp.sys.apple2/TrB4IN10Qiw/j46LHuQvFbYJ
This change allows Ninjaforce's NinjaTracker to correctly play looped
instruments. NinjaTracker, along with it's source code, can be obtained from the following link: http://www.ninjaforce.com/html/products_ninjatracker.html
The included demo song 'conrad' exhibits the looping bug with some instruments that this patch addresses. Output accuracy was also verified with a real ROM 01 Apple IIgs.

Improve Ensoniq 5503DOC Swap Mode

---

hash/n64.xml

http://doc.kodewerx.org/hacking_n64.html#devices_gspro
http://www.gamewinners.com/device/misc/blgameshark.htm
Gameshark and Action Replay for N64 are the exact same device with different names. Action Replay was originally developed by Datel in the UK It was then sold by Interact with the Gameshark label in the U.S. Madcatz now owns that label. They're also called GameBuster in Germany.

Gameshark is a clone of Action Replay

---

makefile
scripts/genie.lua

This commit adds OPT_FLAGS back which is useful when generating Linux packages

Added OPT_FLAGS back

---

makefile
scripts/src/osd/sdl.lua
scripts/src/osd/sdl_cfg.lua

The new flag allows overriding of the default value for the ini_path entry. It's very handy in building the package for Debian/Ubuntu and derivatives, please consider merging.
Thanks!
Cesare

Added new SDL_INI_PATH flag

---

hash/gamegear.xml

Would otherwise leave it unselectable in the gamegear driver.

Fix copy/paste error (nw)

---

src/mame/mess.lst
src/mess/drivers/apple2.c

This is an apple2 clone
elppa.chr is a BAD_DUMP placeholder copied from apple2p
The other ROMs were actually dumped from an original Elppa II+

New apple2 clone: "Elppa II+" by "Victor do Brasil"

---

src/osd/sdl/video.c
src/osd/windows/video.c

-showusage says, and the Windows version looks for,
"\<width>x\<height>[@\<refreshrate>]", but the SDL version was scanning for
"\<width>x\<height>[x\<depth>][@\<refreshrate>]", with the effect of
silently ignoring refreshrate if depth was omitted. And if given, the
depth didn't appear to be used anywhere anyway.
If you want to test this, I suggest doing something like
./mame64 shinobi -switchres -resolution0 800x600@60 -verbose
and looking at the verbose output to see the scores it gave to the modes, instead of asking your monitor what refresh rate it's actually switched to, as there's another bug to do with SDL and mode switching which I'm going to make another PR for shortly.

In SDL version command line, don't look for depth in -resolution

---

src/osd/sdl/window.c

The SDL version is used on so many different systems, and the SDL documentation is vague enough, that any argument for this change can only really be a "works for me". Let me ramble a bit anyway on how this does work for me.
The change is confined to the file src/osd/sdl/window.c. This file contains code for both SDL 1 and SDL 2 ("#if (SDLMAME_SDL2)"). My change relates to the SDL 2 code only.
Using a command line such as "./mame64 shinobi -resolution 800x600@60 -switchres", I've observed the following when single-stepping through the original code with gdb:
([Line 1178](https://github.com/mamedev/mame/blob/e1e0e9edbd0e857997c4725703e562f715c9589b/src/osd/sdl/window.c#L1178)) SDL_CreateWindow() is called with arguments that include the desired width, height and an SDL_WINDOW_FULLSCREEN …

In SDL version, fix refresh rate setting in fullscreen

---

src/mame/arcade.lst
src/mame/drivers/rainbow.c

jumpingi from a red 'Imnoe' PCB which was the source for the recent clock timing fixes.  Board has unsplit code ROMs, based on (or parent of) jumpinga set.
Corrected date to 1988 for jumpinga
http://www.system11.org/temp/ROMs/S11jumping.zip

Added 'jumpingi' / correct date

---

src/mame/drivers/alpha68k.c

This simple line change fixes the missing sound bug in KYROS and SSTINGRY (which was not reported in the bug). There's no more need to doubling audio CPU interrupts per frame after the conversion of the driver to the usage of scanline timers.
Sorry for opened and closed this request multiple times, I'm learning how to GIT works just now. Thanks.

Fix for MAMETESTERS bug #05959

---

scripts/target/mame/mess.lua
src/emu/cpu/avr8/avr8.c
src/mame/mess.lst
src/mess/drivers/rambo.c

Based on the RAMBo board, thus the driver name.
(This also provides an implementation of the AVR8 EIJMP instruction)

New non-working driver: Metamáquina 2 desktop 3d printer

---

src/mame/video/seta.c

Adjusted offsets in seta.c video hardware file. The mentioned bugs in commit title are fixed, probably others too. No time to test all games in normal and flip screen mode, also detect a 1 pixel bug is often really difficult with screen flipped. The vast majority of games have been tested with service mode test grid and are ok. Curiously these changes don't fix #04877 which seems to be another kind of issue: offsets values are right but the whole screen is shifted 8 pixels to the right.

Fix for MAMETESTERS bug #00317, #04405

---

src/mame/video/aerofgt.c

Discussed this commit with Haze directly. If we cannot get rid of the draw_sprites
hack we use, at least we should make it working correctly, not to be the cause of bugs.
Fixed the mentioned bug and priorities in all other games that use same drawing routine.

Fix for MAMETESTERS bug #05981

---

src/mame/drivers/lastduel.c
src/mame/drivers/rainbow.c

Jumping bootleg (non copyright version, larger boardset) confirmed to use 18.432mhz crystal for CPU.  Not sure on Seyutu split ROM version until one is found again.
Verified visible area for lastduel.c against PCB, possible bug comment removed (02430)

Corrected CPU clock for jumping (non copyright) + close last duel bug

---

src/mame/drivers/snk.c

Previously using flyer evidence - often WIP/incorrect images used on those.

Corrected viewable as per 05991

---

makefile

This commit fixes building on arm Linux, ensuring -m32 is not passed to gcc on that architecture.

Do not pass -m32 to gcc on arm

---

3rdparty/bgfx/src/renderer_null.cpp
3rdparty/bx/include/bx/os.h
3rdparty/bx/include/bx/platform.h
3rdparty/portmidi/porttime/ptlinux.c
makefile
scripts/src/3rdparty.lua
scripts/toolchain.lua
src/osd/osdmini/minifile.c

Due to the change in the build system and additional bx/bgfx libraries, mame didn't build on NetBSD any longer.
The patches in this pull request fix this. Please take as much as possible, though I would understand that you want to avoid changing 3rdparty code.
In that case, let me know how to prepare the changes so you can take what you want as easily as possible.
Thanks.

Re-add NetBSD support.

---

src/mame/drivers/taito_x.c
src/mame/includes/seta.h
src/mame/video/seta.c

A quick fix for the only (it seems) game which requires different foreground y offsets.

Fix for MAMETESTER bug #6005

---

src/mame/machine/raiden2cop.c

This caused issues on ARM hosts where result of such
conversion is always 0. Casting the negative float to
signed int resolves the issue. Without this fix some sprites
had wrong rotation and also bullet direction was not
always correct on ARM host. The fix was tested on Intel
and ARM host, both platform work OK.

raiden2cop: fixed negative float to unsigned int implicit conversion

---

src/mame/video/aerofgt.c

This was skipped/forgotten when I pulled my request #251. There are some bootlegs of pspikes that use its drawing sprites method, so they have to be fixed in the same way.

\video\aerofgt.c - fixed priorities in bootlegs

---

src/mess/includes/coco.h
src/mess/includes/coco12.h
src/mess/includes/dragon.h
src/mess/machine/coco.c
src/mess/machine/coco12.c
src/mess/machine/dragon.c

Emulation accuracy improvements and fixes for TRS-80 Color Computer audio/PIA hardware.
This fixes audio artifacts in Sock Master's Donkey Kong and Tandy's Androne games.
I spent quite a bit of time diagnosing and trying to resolve the issue with the 'buzzing' sound in the Tandy/Datasoft Popcorn game, as mentioned in an earlier code comment, until I played it on a real Coco and realized that this sound is supposed to be in the game.  I think it is supposed to be the sound of the conveyer belt moving.
I tested quite a few Coco 2 and Coco 3 cartridge game to test for regressions and didn't find any.

Trs80 coco audio fixes

---

src/emu/drivers/emudummy.c

While all other uses of `GAME_*` have been changed to `MACHINE_*`, there is one left behind. Not sure if it's really used, but seems to prevent building `TOOLS`.

Fix GAME_NO_SOUND in emudummy

---

src/osd/modules/debugger/win/debugviewinfo.c
src/osd/modules/debugger/win/debugwininfo.c
src/osd/modules/debugger/win/editwininfo.c
src/osd/windows/input.c
src/osd/windows/output.c
src/osd/windows/window.c
src/osd/windows/winmain.c
src/osd/windows/winutil.c
src/osd/windows/winutil.h

GetModuleHandle(NULL) is not an universal way to get HInstance of the program.
If you will try to use MAME in dynamic loadable libraries, you will fall with creating windows, and some other troubles.
This commit should fix it.

Fixed GetModuleHandle to be universal.

---

src/mess/drivers/mc1000.c

NE555 timing fixed, cleaner schematics found.

---

src/mess/drivers/asst128.c

- native BASIC
- native chargen (NO_DUMP, for now)
- fold two variants into one (rombios7/8 = extbios + mainbios); there might have never been a cassette-only BIOS

asst128: use better ROM dumps

---

scripts/target/mame/mess.lua
src/mame/mess.lst
src/mess/drivers/mzr8105.c

The board is equipped with a 68000@10Mhz with support for a 16Kb OS9 bootstrap ROM
A terminal interface is hooked up to a UPD7201 that the ROM expects on the VME bus, probably the Mizar 8300 SIO board.

New VME board: Mizar 8105

---

hash/bbcb_cass.xml
hash/bbcb_de_cass.xml
hash/bbcb_us_flop.xml
hash/bbcmc_flop.xml
hash/pro128_cart.xml
src/lib/formats/bbc_dsk.c
src/lib/formats/bbc_dsk.h
src/mame/mess.lst
src/mess/drivers/bbc.c
src/mess/includes/bbc.h
src/mess/machine/bbc.c
src/mess/video/bbc.c

- Added clone bbcb1770, bbcb now 8271 only.
- Added clone pro128s, Olivetti Prodest PC 128S.
- Added clones Acorn Business Computers and Cambridge Workstation.
- Added clone reutapm, Reuters APM board.
- Improved floppy formats, added dsd and double density formats for ADFS.
- Added speech PHROMs, not yet hooked up correctly.
- Added softlists bbcb_de_cass, bbcb_us_flop and bbcmc_flop.
- Added S11 links (dipswitch) to specify Econet ID.
- Address map cleanups.

bbc: clones, floppy formats, softlists, and cleanups.

---

src/mame/drivers/prehisle.c

05939: prehisle, gensitou, prehislek, prehisleu: Wrong speed.
This is a guesswork but in any case it's better than use a standard refresh rate of 60.00 Hz. Values are taken from snk68.c driver which contains games with very similar (if not identical) hardware to prehisle. Notice that the new refresh rate is identical to NeoGeo and this should not be a surprise since we're talking about SNK manufacturer

Attempt to fix MAMETESTERS bug #5939

---

3rdparty/libflac/include/share/Makefile.am
3rdparty/libflac/include/share/endswap.h
3rdparty/libflac/src/libFLAC/bitreader.c
3rdparty/libflac/src/libFLAC/bitwriter.c

This is based on code from https://github.com/xiph/flac/commit/a5d1d4f0c520529c9c49bb3d2e82232144ca2f6d. 
Is there a cleaner way to do what I'm doing at https://github.com/mamedev/mame/pull/331/files#diff-6eb8b7b64ec15bd2fbabf51c22671450R32 ?

Backport libflac endian patch to not use winsock.h etc.

---

makefile
scripts/genie.lua
src/osd/modules/debugger/osx/debugview.m
src/osd/modules/debugger/osx/pointsviewer.m

Xcode 7 changes Clang version numbering to 7.0.0. Apple has also added additional null-checking, and the documentation for those calls has not yet been updated. This allows for clean build on 10.11 with Xcode 7.
I am not certain about the purpose of https://github.com/mamedev/mame/pull/332/files#diff-cd5dbf3629c558b0104ba8f0937d6816L728 , which looks for 3. in the Clang version number. This doesn't work anymore because Clang is now version 7.0.0.

Fix build with Xcode 7

---

src/emu/machine.c
src/emu/schedule.c

No real need for an extra pointer here "device_scheduler * scheduler", only makes the code more cryptic with no real gain in performance.
Removed the assignment steps by initializing the objects with the values intended, at "attotime stoptime" and "attotime target".

Code Enhancements

---

src/mame/includes/n64.h
src/mame/machine/n64.c
src/mame/video/n64.c
src/mame/video/n64.h
src/mame/video/n64types.h

VI now uses the values set in registers to set the screen resolution, instead of using fixed values.

More effort to disentangle the VI and RDP in the source.

---

src/mame/machine/n64.c
src/mame/video/n64.c
src/mess/drivers/n64.c

VI timing should now be accurate (for NTSC)

VI timing period is now set dynamically from the VI registers.

---

src/devices/machine/z80scc.c
src/devices/machine/z80scc.h
src/devices/machine/z80sio.c
src/mess/drivers/hk68v10.c

- Added correct read FIFO depths for the different SCC variants
- Started work on interrupt system, not verified/debugged due to lack of software
- Added conditonal compile for MVC and GCC LOG messages to sort out differences
- Cleaned up LOG messages
I also noticed that the z80dart.c and my own derived z80sio.c implements FIFOs as LIFOs. I will change the z80sio.c to match the datasheet in the same manner I implemented the FIFO for z80scc.c but I leave z80dart.c as is because it basically works as long as the emulator core emulates devices sequentially and pushes signals all the way or at least out of the device. If the core becomes preemptive and/or multi threaded on a per deivie basis the LIFO will deliver characters in swapped order which can be very confusing.

    - Added correct reset values

---

src/mame/includes/n64.h
src/mame/machine/n64.c
src/mame/video/n64.c

Add field for VI interlaced modes.  Display of interlaced video still needs work.

Fix reversion for PI.  PI transfers round length up, not down.

---

src/mame/drivers/1942.c
src/mame/drivers/galaxold.c

1942p:
Clocks thanks to masto75; verified 20mhz OSC, CPU clocks and both AY chips.
spcwarp:
Compared to hunchbkg, important parts in the $16xx RAM region were moved to $17xx. This being flip flags, stars, and NMIs. According to a disassembly, only $1680 wasn't moved.
The game now gets to a credits screen + working starfield.

Verify the clocks in 1942p; fix spcwarp boot procedure.

---

src/devices/sound/digitalk.c

The interrupt command was triggered at the end of the post-sample blank instead of at the start. It's a tight guess but is on par with real hardware footage of Scorpion...

Fix digitalker speed

---

src/devices/machine/z80scc.h

I start to understand the TAB debate now, I didn't see the pin out diagram was trashed in my editor of course but it shows in 'git diff', sorry about that.

untabified the pinout diagram

---

src/mame/drivers/amiga.c

Surprisingly, cd32 driver doesn't have cd32 softwarelist attributed.
I'm just fixing this.

Attributing cd32 softwarelist for the cd32 driver

---

src/mame/drivers/megadriv.c

"Sega CD (USA, NTSC, w/32X)" needs to have compatibility with Sega CD softwarelist too.

"Sega CD w/32X" needs compatibility with segacd softwarelist too.

---

src/devices/cpu/i86/i86.c
src/mame/drivers/cosmic.c

i86 - implement 0xF1 alias for 0xF0 (LOCK)
cosmic.c - correct magspot clock

i86 and cosmic.c fixes

---

hlsl/vector.fx
src/emu/emuopts.c
src/emu/emuopts.h
src/emu/ui/ui.c
src/emu/video/vector.c
src/emu/video/vector.h
src/osd/sdl/video.c

I made some fixed and other more or less "experimental" changes to the vector renderer to improve the visual presentation. I hope these changes will make it into the MAME code base even if I call them "experimental", but I think the results speak for themselves.
Changes:
- fixed vector intensity
- fixed vector flicker
- replace beam width by beam width min. and beam width max. width, this makes it
possible to create a linear dynamic beam width by the amount of
intensity of the beam
- added beam intensity weight, this adds an exponential factor to the
dynamic beam width (values greater than 0 will push larger intensities
more than smaller intensities)
- fixed ratio of "vector points" (zero-length lines)

Vector Rendering Fixes and Improvements

---

src/mame/drivers/segaybd.c

"bank_motor_position" was never output because we were using the whole 16bit value of m_pdrift_bank in the switch statement.

fix power drift outputs ("bank_motor_position" was never output)

---

src/devices/sound/fmopl.cpp
src/devices/sound/ymf262.cpp

3.0 and 1.5 dB/OCT were reversed around according to opl3 on the OPL reverse engineering forum.

fix ksl shift bits in OPL chips

---

src/mame/drivers/rungun.cpp
src/mame/includes/rungun.h
src/mame/video/rungun.cpp

This patch takes into accout current multiplexer frame for drawing and palette updates. 
Makes dual screen 4p support to happen for all games in the driver. 
I'm not directly merging because I would like to know if anybody has a costructive criticism, if any.

rungun.cpp: Implemented bread and butter dual screen drawing setup.

---

src/lib/formats/cassimg.cpp

reference http://stackoverflow.com/questions/22212737/strange-syntax-error-reported-in-a-range-based-for-loop

fix build for VS 2013 and earlier.

---

src/mame/drivers/spc1000.cpp

A motor on/off(toggle) signal in the cassette deck is a pulse instead of digital on/off in spc-1000.
It needs a timing check for emulating cassette deck more precisely.
m_motor binary variable has been removed and m_time variable for pulse timing control.
It can make it more proper emulation by my cassette tape play test.

[spc1000] Using timing difference for cassette deck motor on/off toggle

---

src/mame/drivers/msx.cpp

Daewoo MSX dpc200 has strange configuration for TMS9918.
Most of MSX in Korea has msx_ntsc instead of msx_tms9918.
This difference makes an display error in SCREEN 2 mode,
It can be fixed by changing the value from msx_tms9918 to msx_ntsc

VDP changed from msx_tms9918 to msx_ntsc for Daewoo MSX dpc200

---

src/emu/info.cpp

The listxml dosn't output the game samples.
This fixed commit: tagmap_t to std::unordered_map or std::unordered_set where applicable… 
https://github.com/mamedev/mame/commit/3414b0166e77c5353373d655e3def0251571722d

Fixed listxml sample output.

---

src/devices/cpu/x86log.cpp
src/devices/cpu/x86log.h
src/lib/util/coretmpl.h

* Use variadic template functions instead of `va_list`
* In `x86log_mark_as_data` and `x86log_printf`
* Add `noexcept` where appropriate/safe
* Use `constexpr std::size_t` instead of macros for constants
* Nest `nullptr` check to prevent useless check, add assertion
* In `x86log_printf`
*(Hope variadic templates are OK!)*

Modernize x86log.h and x86log.cpp

---

src/devices/cpu/drcbex64.cpp
src/devices/cpu/drcbex86.cpp
src/devices/cpu/x86log.cpp
src/devices/cpu/x86log.h

* Use variadic template functions instead of `va_list`
* In `x86log_mark_as_data` and `x86log_printf`
* Add `noexcept` where appropriate/safe
* Use `constexpr std::size_t` instead of macros for constants
* Nest `nullptr` check to prevent useless check, add assertion
* In `x86log_printf`
* Move definitions of `log_comment`, `data_range_t`, `x86log_context` to `x86_log.h` from `x86_log.cpp`
* Adapt usages of `x86log_printf` in `drcbex64.cpp` and `drcbex86.cpp`

Modernize x86log.h and x86log.cpp:

---

src/emu/clifront.cpp

-verifyroms doesn't verify sub-(sub-)devices like mpu401 and c2040fdc. This change enables it.

Make -verifyroms verify sub-devices like mpu401 and c2040fdc

---

src/emu/debug/debugcon.h

Increased MAX_COMMAND PARAMS and MAX_COMMAND_LENGTH to quadruple their previous size.  The previous values did not have the capacity to allow trace logging of all registers at the same time in some CPUS.  Setting the maximum to 128 should allow for capturing of systems with large symbolic lists (such as Playstation) if needed. 
For example, the following command would throw an error when trace logging a 68000 CPU because the maximum parameters (16) would be reached when attempting to capture all registers:
trace 68K.log,0,{tracelog "A0=%08X, A1=%08X, A2=%08X, A3=%08X, A4=%08X, A5=%08X, A6=%08X, A7=%08X, D0=%08X, D1=%08X, D2=%08X, D3=%08X, D4=%08X, D5=%08X, D6=%08X, D7=%08X ",a0,a1,a2,a3,a4,a5,a6,a7,d0,d1,d2,d3,d4,d5,d6,d7}

Increase debug console maximum parameters in debugcon.h

---

src/lib/util/corealloc.cpp
src/lib/util/corealloc.h

This is required because some library headers (specifically libc++) expect realloc to be present and break if it isn't.

Add realloc implementation as required by the C standard

---

src/emu/clifront.cpp
src/emu/mame.cpp
src/emu/validity.cpp
src/emu/validity.h
src/lib/util/corealloc.h
src/osd/modules/lib/osdobj_common.cpp
src/osd/modules/lib/osdobj_common.h
src/osd/osdcore.cpp

* Verbose messages can be enabled by option for the -validate command. They are displayed through the same channel as errors and warnings encountered during validation but are not counted as either, and are printed separately for each driver if produced. Verbose output is entirely disabled for pre-run validation to spare users from spurious error pop-ups.
* osd_printf_verbose is no longer enabled or disabled by a global variable; instead, osd_output objects should make the decision whether or not to allow verbose messages, as is now done within both osd_common_t and validity_checker.
* Messages printed by the validity checker no longer have superfluous indentation following the last newline.
* The validity checker now tracks and tags devices slightly differently, omitting the leading …

Allow mame -validate -verbose to capture verbose messages

---

src/mame/drivers/kaneko16.cpp

Sound was clearly incorrect before, now it sounds much closer to PCB
video. Also changed the VSync rate to 59.1854 like Fujiyama Buster and
B.Rap Boys, as it makes the title theme exit at the same point as the
PCB video.

Wing Force sound fixes, and change VSync.

---

src/devices/machine/6821pia.cpp

I guess it wasn't intentional to leave it in VERBOSE?

Stop PIA from spamming debug console by default

---

src/emu/emuopts.cpp
src/emu/emuopts.h
src/emu/luaengine.cpp
src/emu/mame.cpp

Originally removed by @mmicko when mongoose was axed in b6707c3bb53c931e9ec3c5c6630149b7121bbcf5.
Since C++14 I'm assuming using std::thread is ok.

add lua console support back in

---

src/osd/osdcore.h
src/osd/osdmini/minimisc.cpp
src/osd/sdl/sdlfile.cpp
src/osd/windows/winfile.cpp
src/osd/windows/winutil.cpp

Environment substitution in osd_open for Windows so it behaves exactly like non-Windows.

common osd path environment var expansion

---

scripts/src/osd/sdl_cfg.lua

Get SDL_INI_PATH back in the source tree. This makefile variable helps giving an arbitrary default value to the inipath entry in mame.ini. Useful for linux packagers.
Please consider merging, thank you.

Get .ini file default path makefile variable back.

---

src/drivers/spc1500.cpp

Samsung SPC-1500 driver by Miso Kim
2015-12-16 preliminary driver initialized
2015-12-18 cassette tape supported
2015-12-26 80/40 column mode supported
2015-12-28 double access mode supported for I/O 
2016-01-02 Korean character input method and display enabled
2016-01-03 user defined char (PCG, Programmable Character Generator) support	
2016-01-05 detection of color palette initialization 
2016-01-06 80x16 mode graphic mode support
TODO:
- Verify PCG ram read
- Support floppy disk drive with SD-1500A controller card
Hardware Specification
1) SPC-1500
RAM 122KB
- Main Memory: 64KB
- Video RAM: 10KB (text 2KB, character attributes 2KB, custom letter: 6KB)
- Graphics RAM: 48KB (16KB on three sides by assigning each of RGB)
ROM 96KB
- BIOS: 32KB (including IPL and a part of BASIC)
- BASIC …

new MESS driver for spc1500

---

scripts/target/mame/mess.lua
src/mame/drivers/didact.cpp
src/mame/mess.lst

- Added support for Didact mp68a, a 6800 based educactional computer with 7seg display and hex keypad. 7Seg display and keyboard works only from full build.
- Added skeleton for the Didact md6802, the successor, not yet functional
- Added skeleton for Esselte 100, another Didact design with a CRT and real keyboard, no ROM dumped yet
For some reason the driver does not get 7seg support if built alone and I had to start it using the driver name or the 7seg support would also disappear, like this
./mess64d mp68a -window 
Artwork etc can be found here: https://drive.google.com/file/d/0B685nj_1DkduaFQ0M2dhMTFtbVU/view?usp=sharing

Didact driver

---

hash/x1_cass.xml

Fantasian (Xtal Soft, 1985)  - seems to work only with the x1turbo drivers, but the box says it should be compatible with the original X1
Pinball (Hudson Soft, 1982)

x1_cass.xml: Two new dumps

---

src/devices/bus/megadrive/svp.cpp
src/devices/bus/megadrive/svp.h
src/devices/cpu/ssp1601/ssp1601.cpp
src/devices/cpu/ssp1601/ssp1601d.cpp

notes:
9f1788f65c243208e1ea386bc476dfb71f89bcb7 already removed MAME license
notice without bothering with permission
00b76c70c3a437d5bd9d988e43782df5931964ac claims Pierpaolo Prazzoli chose
BSD3 too
3360feb244452ca0a0c2f4f0a4dae59327b49567 claims the same about
Fabio Priuli

relicense SVP/SSP1601 code (nw)

---

src/osd/modules/sound/xaudio2_sound.cpp

When refactoring this code in the last pull request, I created a new method to initialize the buffers I forgot to call.  Additionally, there isn't any need to initialize COM before calling XAudio2Create in XAudio2 2.8

XAudio2 Bug fix - forgot to initialize buffers and no need to init COM

---

src/mame/drivers/didact.cpp
src/mame/layout/md6802.lay
src/mame/layout/mp68a.lay
src/mame/mess.lst

- Created common base class for didact drivers
- Added builtin layouts for mp68a and md6802
These drivers requires layout and other support files found here: https://drive.google.com/open?id=0B685nj_1DkduaFQ0M2dhMTFtbVU
I will eventually hunt down Esselte 100 and Candela roms to add support for these fantastic machines as well. There are also 2-3 variants more of the md6802, and 5-10 laboration add ons which will be added if I find time and how to add an overlay per lab, I'd love'em to be animated or at least interactive!

- Added support for Didact md6802

---

src/mame/drivers/marywu.cpp
src/mame/layout/marywu.lay

Most of the hardware has been mapped by analysing the pcb tracks. This set of commits include:
* a video layout with all 30 LEDs 13 double-digit 7seg modules
* an improved memory map hooking up the couple AY8910-3 chips, 2kb of Static RAM and the keyboard/display controller (an i8279 clone)
* multiplexing signals for the 7seg displays
* LEDs being controlled by the IO ports of the 2 AY8910-3 chips
* 8-bit set of DIP-Switches, a 2x16 keyboard and 4 push buttons mapped to the i8279 scanlines and return lines
The device still does not play music because it apparently fails to detect auxiliar hardware (it tries to do something with port bits P1.0 and P1.6 a few dozen of times and then enters an infinite-loop). In this case, the display is frozen with a number 1 displayed in the top right …

Marywu improvements

---

src/emu/clifront.cpp
src/emu/validity.cpp
src/emu/validity.h

- The -validate command now accepts an optional string, validating only matching drivers.
This has proven useful for debugging. The default is to validate all drivers as usual.
- Devices' names are tracked when validating their auto-finders.

Some more validity checking improvements:

---

src/emu/debug/debugcmd.cpp
src/emu/debug/textbuf.cpp
src/emu/diimage.cpp
src/emu/luaengine.cpp
src/emu/render.cpp
src/emu/sound/wavwrite.cpp
src/emu/ui/miscmenu.cpp
src/emu/ui/selgame.h
src/emu/ui/ui.cpp
src/emu/video.cpp
src/emu/video.h
src/lib/util/corealloc.h

- corealloc.h: added macro definition for global_alloc (nothrow) memory allocation.
- textbuf.cpp / wavwrite.cpp: removed pointless cast.
- debugcmd.cpp / luaengine.cpp / render.cpp: avoid strlen calls in a loop.
- diimage.cpp: simplified "device_image_interface::set_image_filename" function.
- miscmenu.cpp / selgame.h / video.cpp(h): replaced int with bool where applicable.
- ui.cpp: removed unused code.

Small code cleanup

---

src/mame/drivers/arcadecl.cpp
src/mame/drivers/atarisy2.cpp
src/mame/drivers/gauntlet.cpp
src/mame/drivers/rampart.cpp
src/mame/drivers/relief.cpp
src/mame/includes/arcadecl.h
src/mame/includes/atarisy1.h
src/mame/includes/atarisy2.h
src/mame/includes/badlands.h
src/mame/includes/cyberbal.h
src/mame/includes/gauntlet.h
src/mame/includes/rampart.h
src/mame/includes/relief.h
src/mame/machine/atarigen.cpp
src/mame/machine/atarigen.h

This lets atarigen.cpp shed legacy sound routines using the archaic
method of looking up sound devices by types rather than tags (which
until 0.126u2 they weren't required to provide and often didn't have).

Modernize sound volume setting code in various Atari drivers

---

src/devices/video/ef9365.cpp

(note: I don't think is right initialized to 0, but I don't have the skills necessary to determine the proper value.)

This fix VS2015 warning (and building) about uninitialized variable.

---

src/emu/clifront.cpp
src/emu/emuopts.cpp
src/emu/emuopts.h
src/emu/ui/slotopt.cpp

This feature is enabled when executing 'mame driver software'. After the specified software is found in the software list and attached to an appropriate image device, the software part's feature list is examined for any feature whose name is that of a slot device with _default appended. The feature's value field becomes the slot's default option, which overrides any driver-specified default and can be overridden by user-specified options.
No software lists have been updated to use this feature at the moment.

Software list entries can now supply slot option defaults

---

src/emu/emuopts.cpp

This prevents software lists from (e.g.) trying to put a Zapper into ctrl1 on the Famicom.

Ignore invalid default slot options in software lists

---

src/lib/util/aviio.cpp

GCC 5.3.1 on Fedora 22
src/lib/util/aviio.cpp:1378:57: error: ‘offset’ may be used uninitialized in this function [-Werror=maybe-uninitialized]

fix compile (nw)

---

hash/m5_cart.xml
hash/m5_flop.xml
src/mame/drivers/m5.cpp

fixed bug: crash if rom card was only cart
fixed bug: when em-5 selected monitor rom wasn't paged in
brno mod: windowed boot as default rom
brno mod: fixed bug: tape command in menu now works

Sord m5: bug fixes

---

src/emu/clifront.cpp
src/emu/clifront.h
src/emu/cliopts.cpp
src/emu/cliopts.h
src/emu/drivenum.cpp
src/emu/drivenum.h
src/emu/ui/imgcntrl.cpp
src/emu/ui/imgcntrl.h
src/emu/ui/inputmap.h
src/emu/ui/mainmenu.h
src/emu/ui/menu.cpp
src/emu/ui/miscmenu.h
src/emu/ui/selgame.cpp
src/emu/ui/selgame.h
src/emu/ui/simpleselgame.cpp
src/emu/ui/simpleselgame.h
src/emu/ui/slotopt.h
src/emu/ui/ui.cpp
src/emu/validity.cpp
src/osd/sdl/man/mame.6
src/osd/sdl/man/mess.6

Five new specifiers for driver enumeration and all commands depending thereon:
- @source.cpp matches all drivers in source.cpp
- ^driver matches driver and all its clones
- :drivbios matches drivbios and all drivers having it as their BIOS
- ^ matches all drivers excluding clone sets
- : matches all BIOS roots
Note that these new specifiers are not compatible with other wildcards; they only perform normal case-insensitive matches with driver or source file names.
The -listclones command now lists drivers in a completely different, human-readable format. It performs an extra loop to deduce the parent set name if a clone was specified; this causes, for instance, -listclones pacman and -listclones puckman to produce identical output. It includes descriptions with the clone driver names much …

New driver specifiers; modify -listclones, -listsource; add -listtree

---

src/osd/sdl/sdlfile.cpp

Apparently, somebody thought fflush() had two arguments... This caused a compile error on my system.

Fix an SDL compile bug

---

src/devices/cpu/mips/mips3com.cpp

Currently only tested with N64.  As not having the timer intermittently not trigger, this may improve other mips systems too.

Fix for mips3 compare timer.

---

language/Spanish/strings.po

Follow the Spanish capitalization rules, optimize space and use correct grammar, complete missing translations. Much better.

Sensibly improve the Castilian Spanish translation

---

scripts/build/makelist.py
src/osd/modules/input/input_xinput.cpp

* inconsistent indentation (python 3)
* Xinput.h is xinput.h when cross building for windows

fix build errors (nw)

---

src/mame/drivers/taitogn.cpp
src/mame/drivers/zn.cpp
src/mame/machine/cat702.cpp
src/mame/machine/cat702.h

This eliminates two instances of driver_start, including one performing a game-name lookup (nw)

CAT702 transform table must be specified in MCFG

---

language/German/strings.po

This PR only adds a translation for the string "Covers". All the other changes are only changes in the line breaks, thanks to poEdit.
I translated the string "Covers" with "Cover" - it's a well-known term in German and any translation would sound quite silly. I'm open for discussions regarding the plurals form - according to the Duden, "Cover" as well as "Covers" is accepted as a plural form, but I think "Cover" is more known to the public...

Update German strings.po file

---

src/osd/modules/input/input_dinput.cpp

Note: recent ComPtr change requires Mingw64 HEAD (post 5.0-rc1 commits) for wrl support. Should be good to go in 5.0-rc2.

Fix cross compile (nw)

---

src/emu/render.cpp

This also makes sure ui aspect ratio is computed correctly even on rotated targets.

Fix issue with ui aspect due to recent changes in -keepaspect

---

src/mame/drivers/crimfght.cpp
src/mame/drivers/eolith.cpp
src/mame/mame.lst

4P Crime Fighters was made specifically for the US market, World rev should be default - ROMs and driver corrected for this.  No longer loading unused ROMs in one version of Penfan girls since that board physically doesn't have the chips.
New ROM sets:
http://www.system11.org/temp/ROMs/S11pencrim.zip

World rev of Crime Fighters now default, Penfan girls set minor rev

---

src/devices/bus/coleco/exp.cpp
src/devices/bus/coleco/exp.h

Fix the coleco_cart:rom so that it doesn't crash MAME when used in the debugger:-
eg.
print coleco_cart:rom.mb@0

Tiny fix for coleco_cart region so it doesn't crash MAME when used in the debugger

---

src/mame/drivers/toypop.cpp

to fix flip sprites in toypop.

---

scripts/genie.lua

OPTIMIZE= to disable the current default value 3
Also allow ARCHOPTS to be set regardless of OPTIMIZE, useful for
debug flags.

support build without optimize flag (nw)

---

src/emu/ioport.cpp

This simplifies an old piece of MESS code that failed to properly classify paddle, pedal, positional and dial inputs, along with many of the less-common digital inputs. MT #06172 should be fixed by this.
The distinction between INPUT_CLASS_MISC and INPUT_CLASS_INTERNAL makes more sense now, though nothing makes use of it.

Recognize the full range of controller inputs

---

src/emu/diserial.cpp

I had to add this fix to make 1 stop bit work with the serial terminal device. Apparantly diserial sended bytes back to back which is not normal, there is always a small delay between bytes on a serial line.
The real fix may be to add a device_serial_interface callback to allow for an arbitrary delay and also implement the 1.5 stop bits but I am not brave enough to mess with core classes yet.

Added extra bit as delay between bytes to make 1 stop bit work

---

src/mame/drivers/chihiro.cpp

Changed a few games' names for consistency with similar situation,
where the Export version has the simplest name, and the Japan version
has a trailing j.

game name consinstency

---

src/emu/clifront.cpp
src/emu/clifront.h

As the name of the binary is normally installed lowercase, the help
output should also reflect this.

Show MAME's program name lowercase in help output.

---

scripts/src/osd/modules.lua

Some systems like Debian, Ubuntu and other derivatives, expect qtchooser
will be used to select the appropriate Qt version, as Qt5 and Qt4 can
co-exist.
As MAME's build system does calls to moc and qmake directly, and Qt5 is
now the required version for the debugger, pass -qt5 to all moc and qmake
calls to avoid the build fail.

Pass explicit -qt5 to all moc and qmake calls.

---

src/osd/modules/render/d3d/d3dhlsl.cpp

I don't know if the reason to save Windows post-fx screeenshots in 4 chunks is still important to anybody, just in case patch 9904765 changes that. The other patch is a fix for the same feature.

One bugfix and one functional change for the Windows post-fx screeenshot feature.

---

src/devices/cpu/z80/tmpz84c015.cpp
src/devices/cpu/z80/tmpz84c015.h
src/devices/cpu/z80/z80daisy.cpp
src/devices/cpu/z80/z80daisy.h
src/mame/drivers/pve500.cpp
src/mame/drivers/system1.cpp

- Prevent tmpz84c015_device::irq_priority_w from crashing or corrupting the daisy chain
- Eliminate the need for TMPZ84C015_DAISY_INTERNAL by not overwriting elements in the daisy list
- Removed leftover MCFG_SEGAZ80_SET_DECRYPTED_TAG from macros in system1.cpp, which lets all drivers validate without crashing

Critical fixes (nw)

---

src/mame/drivers/segag80v.cpp

I'm working on an actual boardset here, and I realized MAME was running a little faster than the real thing.  You can also verify from the schematics that the oscillator on the CPU board is overridden by a signal from the XY boards, providing a clock on all sega vector games which is derived from the video clock.  The CPU board oscillator is used only on the raster games.

fixed segag80v clocks

---

src/mame/video/decocass.cpp

This stops the headlight in chwy from bouncing all over the screen and makes the shadow stick to cskater's toe.
Reference videos show that color is still 100% wrong.

decocass: Fix positioning of object sprite

---

src/mame/drivers/wmg.cpp

In file included from ../../../../../src/mame/includes/williams.h:10:0,
from ../../../../../src/mame/drivers/wmg.cpp:71:
../../../../../src/devices/cpu/m6809/m6809.h:25:14: error: 'device_type' does not name a type
extern const device_type M6809;
^

fix build (nw)

---

hash/megadriv.xml
src/emu/diimage.cpp
src/emu/softlist.cpp
src/emu/softlist.h
src/frontend/mame/clifront.cpp
src/frontend/mame/ui/selsoft.cpp
src/frontend/mame/ui/swlist.cpp
src/mame/drivers/megadriv.cpp

This new softlist feature is now used by genesis_tmss to exclude several entries from megadriv.xml.
- Use popmessage instead of osd_printf_warning for incompatibility warnings
- Unify some common software loading code, which reduces indentation levels in clifront.cpp

Check software parts for incompatibility as well as compatibility

---

scripts/resources/emscripten/emscripten_post.js
scripts/src/main.lua

This change is specifically for the Emscripten build, it allows the containing website to access the SDL_SendKeyboardKey function directly, which is useful for linking webpage UI elements with the running emulator instance.

Export SDL_SendKeyboardKey function to allow scancode injection in Emscripten build

---

hash/fmtowns_cd.xml

- Added the rest of the CHDs starting with D
- Added more converted CHDs from Breiztiger (powermon, prinpers, prinper2, puyopuyo, puzznic, volfied, wingcmar, wingcmdr, wingcmsm, wingcm2s, xak2, xak3, xenon, zenith, zokudm)
- Fixed dalk sha1

fmtowns_cd.xml: more software + sha1 fix

---

hash/fm7_cass.xml

_Portopia Renzoku Satsujin Jiken_ 『ポートピア連続殺人事件』 has a lot of ports. They are usually called 'portopia' in software lists. This should be consistent. For additional consistency, the ROM names were changed as well. The files should be given more descriptive names if it can be discovered what they are for. (Note I haven't been able to get this to run yet.)

Change portpia to portopia in fm7_cass.xml to match with other versions.

---

src/mame/drivers/goal92.cpp
src/mame/drivers/legionna.cpp
src/mame/drivers/r2dx_v33.cpp
src/mame/drivers/raiden2.cpp
src/mame/includes/legionna.h
src/mame/machine/raiden2cop.cpp
src/mame/machine/raiden2cop.h
src/mame/video/legionna.cpp

- grainbow: Correct score and credits display
- heatbrl: Suppress "divide by zero?" message since code actually checks for it (no, still not working)
- legionna: 2P inputs now designated as such
- zeroteam: Hook up PRNG (definitely used in this game)

Input documentation and COP tweaks based on M68000 and V30 code

---

src/emu/ioport.cpp
src/emu/ioport.h
src/emu/machine.cpp
src/emu/uiinput.cpp
src/emu/uiinput.h
src/emu/validity.cpp
src/frontend/mame/luaengine.cpp
src/frontend/mame/ui/cheatopt.cpp
src/frontend/mame/ui/inputmap.cpp
src/osd/modules/debugger/debugimgui.cpp
src/osd/sdl/window.cpp
src/osd/sdl/window.h

- Completely move mouse hit testing down into the UI input module. This reduces some dependencies.
- Never return a null pointer from ioport_field::name() to prevent potential crashes. All anonymous inputs are classified as INPUT_CLASS_INTERNAL, so several frontend functions now check type_class instead.
- Correct a couple of typos.

Ioport refactoring and cleanups (nw)

---

src/devices/cpu/hphybrid/hphybrid.cpp
src/devices/cpu/hphybrid/hphybrid.h
src/mame/drivers/hp9845.cpp

Hi,
I pushed a set of changes to hp9845b driver to support graphic video. If you want something very basic to try, type in this program:
10 PLOTTER IS "GRAPHICS"
20 GRAPHICS
30 FRAME
40 END
and RUN it: it should show a rectangle on the border of the screen (wasn't BASIC fun??).
Don't forget that you need to load the "graphics" optional ROM, I'm attaching the image. It can be loaded in any of the optrom slots through the software list facility.
Thanks.
-- F.Ulivi
[graphics.zip](https://github.com/mamedev/mame/files/266172/graphics.zip)

Hp9845: added support for graphic video

---

src/mame/drivers/8080bw.cpp

Added the original/dumped 2708 roms (1024 bytes) to clone Ozma Wars (set 2).
They were merged with (set 1) since they were added in MAME 0.53.
Also added Malcor's PCB info from 1998 to (set 2).
The PCB info says that Ozma Wars (set 2) uses Taito's three board colour version of 
Space Invaders PCB, so i added the color maps proms from intruder to it. They matched
the flyer picture at:
http://flyers.arcade-museum.com/?page=flyer&db=videodb&id=5784&image=2
While (set 1) only differs in 6 bytes from (set 2) i added the proms also to (set 1).

Added color proms to Ozma Wars.

---

makefile
scripts/src/osd/sdl.lua
scripts/toolchain.lua

also rename ANDROID_NDK_ROOT -> ANDROID_NDK_LLVM to point directly to
prebuilt host compiler (removes windows only host build restriction).
make[1]: Circular SDL2 <- SDL2 dependency dropped.
make[2]: Circular ../../../../../android-project/app/src/main/libs/armeabi-v7a/libSDL2.so <- ../../../../../android-project/app/src/main/libs/armeabi-v7a/libSDL2.so dependency dropped.

fix android target libSDL2 circular ref (nw)

---

src/devices/imagedev/cassette.cpp
src/devices/imagedev/cassette.h
src/devices/machine/hp_taco.cpp
src/devices/machine/hp_taco.h
src/emu/diimage.h
src/emu/ui/uimain.h
src/frontend/mame/ui/ui.cpp
src/frontend/mame/ui/ui.h

Hi,
I've made a small change to call_display so that UI frontend is better de-coupled from image devices. Basically the UI periodically calls this function to retrieve the string that should be displayed as status of the image device. The function itself doesn't display it anymore.
As of now this way of providing visual feedback is only used by the cassette image device and the HP TACO driver I wrote for HP9845b system. If I kept the previous way of interfacing image devices and UI, whenever the UI fronted was built it also required the taco driver to be compiled as well in order to link successfully. With this approach building the UI is independent from the device building.
Let me know if these changes are ok for you.
Thanks.
--F.Ulivi

A little change to device_image_interface::call_display to better decouple UI fronted and image devices

---

src/mame/drivers/tmnt.cpp

Several MT bugs closed on this, never correctly verified - this resolves the 'bumper viewable in road stage' bug for example and now matches PCB grid test accurately.

Corrected viewable screen area as per real hardware

---

src/devices/sound/ay8910.cpp
src/emu/render.cpp
src/frontend/mame/ui/text.cpp

Use osd_printf_verbose instead of popmessage in ay8910 (too annoying even for debug build)

Prevent NaN errors by initializing variable in ui::text_layout (nw)

---

src/emu/emumem.cpp

This allows hp9845b to boot again.

Use unshifted addrmask (not bytemask) in check_optimize_foo (nw)

---

src/devices/cpu/sparc/mb86901.cpp
src/devices/cpu/sparc/sparc.h
src/devices/cpu/sparc/sparcdefs.h

The SPARC Architecture Manual Version 8 gives detailed descriptions of exactly how opcodes are handled in terms of when traps are tested, what traps are invoked, how flags are calculated, and even the general execution loop. With that in mind, I've re-written the vast majority of mb86901.cpp, and it should presumably be more accurate than before.
This sadly does not fix sun4_60, but it at least has the pleasant side effect of not running off into the weeds when anymore, as when it starts trying to execute garbage at 0xffe82000, the first instruction is "fbo", which is unimplemented, effectively stopping the emulated processor from executing more instructions as it stops advancing the program counter.

Rewrite SPARC emulation based on detailed descriptions from SPARC manual

---

src/devices/cpu/hphybrid/hphybrid.cpp
src/devices/cpu/hphybrid/hphybrid.h

Hi, here's a little change to AEC (memory extension chip) of HP hybrid CPU. It should prevent lock-up in very rare cases.
Thanks.
--F.Ulivi

hphybrid: cleanup of AEC logic

---

src/mame/drivers/bfm_sc4.cpp
src/mame/includes/bfm_sc4.h

Unscramble the output for the 7segment displays in most Scorpion4 machines.

Scorpion4 7segment displays mostly fixed

---

src/frontend/mame/ui/filesel.cpp
src/frontend/mame/ui/filesel.h
src/lib/util/unicode.cpp
src/lib/util/unicode.h

This fixes a bug in filesel.cpp that caused clicking on directories to omit the final path separator in the target directory, and does a bunch of changes related with replacing char buffers with std::string

Filesel cleanup

---

src/frontend/mame/ui/filesel.cpp
src/frontend/mame/ui/imgcntrl.cpp

Previously, the calling code would make the determination and pass that to the file selector.  That was incorrect, because this determination wouldn't be remade if the user enters or exits an archive

Fixes how the file selection dialog determines when to show [create]

---

src/devices/machine/rtc4543.cpp
src/devices/machine/rtc4543.h
src/mame/drivers/feversoc.cpp

RTC writes and reads in feversoc both fully work now.

Correct JRC6355E implementation to agree with NJU6355 datasheet

---

src/mame/drivers/tmaster.cpp

COIN 5+6 are mapped twice in Touchmaster 2000, 3000, 4000, 5000, 7000 and 8000.
You cannot start/coinage since MAME 0.152.

Fixed coinage in Touchmaster 2000-8000

---

hash/bbcbc.xml
scripts/target/mame/mess.lua
src/devices/machine/z80pio.cpp
src/mame/drivers/bbcbc.cpp

- Button mappings completely reworked: grey bidding/suit selection buttons classified as keypad inputs and put in correct order, and other buttons as console-standard Start, Select, Button 1-2
- Inputs now read through PIO instead of RAM addresses, making them less hypersensitive
- Manufacturer/publisher is Unicard, as manuals and system/cartridge labels clearly state
- Added release years for some common cartridges
- (nw) Link bbcbc in its own library rather than the unrelated libacorn ("make clean" strongly recommended)

bbcbc: Input overhaul and machine/software list corrections

---

hash/apple2.xml

The name of the software is "Akalabeth - World of Doom" and not "Aklabeth" as in software-list

Fixing wrong title name

---

scripts/src/mame/frontend.lua
src/frontend/mame/ui/menu.cpp
src/frontend/mame/ui/menu.h
src/frontend/mame/ui/widgets.cpp
src/frontend/mame/ui/widgets.h

Ultimately this code should be structured so that highlighting, arrows etc is completely decoupled from the menu code

Split "widgets" code out of ui::menu::global_state into a separate module

---

src/mame/video/gime.cpp
src/mame/video/gime.h

This patch updates the CoCo 3 composite mode palettes. It replaces the crudely modeled ones with sampled values. It also adds support for a secondary set of composite palettes that kick in when the $FF98 color phase bit is set. This mode is used in SockMaster's "Donkey Kong Remixed." SockMaster was the source of the original modeling code and he supplied the updated palette values and assisted in testing.

coco3: improve palettes and support alternate composite mode

---

src/mame/video/gime.cpp

This patch fixes the CoCo 3 GIME support for legacy graphic modes. It also adds support for the $FF9C lines per row value. This fixes graphics modes used by Nick Marentes in the game Neutroid 2 among others.

coco3: GIME fix for scanlines in legacy graphic modes

---

src/devices/cpu/m6809/6309dasm.cpp
src/devices/cpu/m6809/6809dasm.cpp
src/devices/cpu/m6809/base6x09.ops
src/devices/cpu/m6809/hd6309.cpp
src/devices/cpu/m6809/hd6309.h
src/devices/cpu/m6809/hd6309.ops
src/devices/cpu/m6809/konami.cpp
src/devices/cpu/m6809/konami.ops
src/devices/cpu/m6809/m6809.cpp
src/devices/cpu/m6809/m6809.h
src/devices/cpu/m6809/m6809.ops
src/devices/cpu/m6809/m6809inl.h

Apologies in advance to whomever has to review this PR. Changes are repetitive but were scripted (not manual) then hand-verified and tested. If it makes you feel any better, I've been coding this micro for 30+ years.
The 6809 has 8-bit A and B registers that become a 16-bit D register. The 6309 adds an E and F register that becomes a W. And then D and W combine to form a 32-bit Q.
Although that's the architecture of the chip, the emulation code wandered from it. It made the debugger very difficult to use as register values were duplicated and out of order.
This PR unifies the 6309 emulation to be structured like the original 6809 emulation, with unions of larger registers giving way to smaller ones. As a result some special-casing around the Q register disappears.
Per docs, the V register …

m6809: Improve debugging support for 6809/6309 cpus

---

src/mame/machine/seibucop/seibucop_dma.hxx

- Simulation code in nzeroteam confirms that COP sort DMA function uses a dword key
- Several priorities are still wrong (e.g. bikes invisible on character select screen)

zeroteam: Improve sprite/sprite priorities

---

makefile
scripts/genie.lua

Add detection for Linux architectures alpha and mips64el, to avoid
using gcc -m64, which isn't available on them.

Add arch defines for Linux alpha and mips64el.

---

src/mame/drivers/tim100.cpp

This may or may not work, but it passes validation and prevents unused variable errors.

Fix TIM-100 mconfig (nw)

---

scripts/src/osd/modules.lua
scripts/src/osd/sdl.lua
scripts/src/osd/sdl_cfg.lua

On some systems pkg-config is not available under that name, but for example a prefixed variant. Those systems set the PKG_CONFIG environment variable to define which binary should be called for pkg-config.
While this works for all makefiles etc., the lua osd scripts don't respect that variable.
The attached patch implements that behaviour for the osd build scripts, falling back to "pkg-config" if the variable is nil.

Take pkg-config path from env if defined

---

src/emu/crsshair.cpp
src/emu/crsshair.h
src/frontend/mame/ui/miscmenu.cpp
src/frontend/mame/ui/miscmenu.h
src/mame/machine/sms.cpp
src/mame/video/cave.cpp

- Individual crosshairs are now first-class objects, rather than bits of state scattered across half a dozen arrays. The class is named render_crosshair with a view towards incorporating crosshairs into layouts in the future, rather than managing them separately as crosshair_manager still does now.
- Removed the old crosshair_user_settings interface for adjusting crosshair settings, since the UI can access the new crosshair objects directly.

Crosshair refactoring (nw)

---

src/devices/bus/rs232/null_modem.cpp
src/devices/bus/rs232/null_modem.h
src/devices/machine/i8251.cpp

Hi,
this is an attempt to fix the problem I described here:
[MESS forum post](http://forums.bannister.org/ubbthreads.php?ubb=showflat&Number=106520#Post106520)
I think this is the solution with the least impact on the current code.
Thanks.
--F.Ulivi

i8251: RTS and DTR outputs now use negative logic (0 = active)

---

src/osd/modules/render/drawbgfx.cpp
src/osd/modules/render/drawbgfx.h
src/osd/windows/window.cpp

BGFX renderer requires some effects also when post-processing is disabled. If they are not available, MAME complains about missing effect files, but then goes on and crashes soon after printing the backtrace. This fix just exits gracefully when effect files are incomplete and falls back to a different renderer if the bgfx folder is missing at all, warning the user in advance.

BGFX: fix crash when bgfx effect folder is not present or incomplete

---

src/devices/bus/rs232/sparckbd.cpp
src/devices/machine/z80scc.cpp
src/mame/drivers/sun4.cpp

Added support for changing the baudrate constant with enabled Rx/Tx. There are also related patches for removing the workaround in the Sparc keyboard driver and a commentary the sun4 driver, that can be omitted if they are not wanted/needed.

Sun475 sccbug

---

src/devices/machine/z80scc.cpp
src/devices/machine/z80scc.h
src/mame/drivers/sun4.cpp

Added support for delayed change of Tx baudrate allowing current bit frame to be fully transmitted before change takes effect. The fix includes assurance that the baud rate is calculated correctly at the moment of change which fixed some problems seen with the Sun 4 driver. I tested it on all Sun 4 variants that I had ROM:s for and also added my findings as comments to the sun4.cpp driver

Sccbug sun4 40

---

hash/vz_cass.xml
src/emu/softlist.cpp

- Fix stupid logic errors in software_list_device::internal_validity_check
- Allow info and feature list entries to provide an empty string as the value
- Change a couple of null publisher entries in vz_cass.xml to "<unknown>"

Cure software lists of validity checking errors (nw)

---

scripts/target/mame/arcade.lua

Fixed "undefined reference to 'SUNKBD_PORT'.." in arcade only build.

Fixed arcade only build

---

src/devices/bus/hp_optroms/hp_optrom.cpp
src/devices/bus/ti99x/gromport.cpp
src/devices/bus/ti99x/gromport.h
src/emu/diimage.cpp
src/emu/diimage.h

- Remove the loaded_through_softlist virtual method and add a boolean getter with the same name, replacing a few variables that provided similar but redundant flags.
- Remove call_softlist_load, which the previous change reduces to a simple, unnecessary wrapper.
N.B. This conflicts with pull request #1137.

Cleanups for device_image_interface (nw)

---

3rdparty/bx/include/bx/os.h
3rdparty/bx/include/bx/platform.h
3rdparty/bx/include/bx/process.h
3rdparty/bx/include/bx/thread.h
3rdparty/bx/makefile
3rdparty/genie/makefile
3rdparty/genie/src/host/premake.h
3rdparty/luafilesystem/src/lfs.c

Cherrypick fixes that improve portability on GNU/Hurd and GNU/kFreeBSD for genie, bx and luafilesystem.

Cherrypick portability fixes for 3rdparty modules

---

src/emu/diimage.cpp
src/emu/diimage.h
src/frontend/mame/ui/imgcntrl.cpp

- Removed some c_str() calls when using util::zippath_parent()
- Removed the error code return value from set_image_filename()
- Consolidated error code translation (osd_file::error ==> image_error_t) in image_error_from_file_error()
- Other cosmetic improvements

Miscellaneous cleanups

---

scripts/src/emu.lua
src/emu/device.h
src/emu/romentry.h
src/emu/romload.cpp
src/emu/romload.h
src/emu/softlist.cpp
src/emu/softlist.h

This should really be followed up by further changes to eliminate the usage of the weird accessor macros in favor of conventional C++ accessors

Changes rom_entry from a struct to a class, storing its strings as stdd::string and separated the declaration into a new header

---

src/emu/image.cpp

The issue is that I expected any softlist items passed to devices to be fully qualified (e.g. - apple2e:flop1:agentusa) when in reality, they might not be.  Therefore, I changed the regex that identifies softlist items passed to devices from:
\\w+\\:\\w+\\:\\w+
to:
\\w+(\\:\\w+\\:\\w+)?

Fixed issue that prevented softlist items specified on devices from loading

---

src/emu/diimage.cpp
src/frontend/mame/ui/floppycntrl.cpp
src/frontend/mame/ui/floppycntrl.h
src/frontend/mame/ui/imgcntrl.cpp
src/frontend/mame/ui/imgcntrl.h

I'm still not 100% satisfied with this patch.  While I got rid of the weird path when hook_proc() was called for a software list item, I still don't like the whole m_init_phase infrastructure in devices, which seems to be an arbitrary piece of state.  Baby steps...

This fixes issues where softlist items (that were not for floppies) were loaded from the software list menu

---

plugins/hiscore/init.lua

hiscore.dat and hi folder path were not resolved as expected (their path was relative to mame executable, not to the plugin folder). Explicitly writing them as absolute paths gives the desired behavior.

Fix .hi file load and write

---

scripts/target/mame/arcade.lua
src/mame/drivers/airraid.cpp
src/mame/drivers/darkmist.cpp
src/mame/drivers/stfight.cpp
src/mame/includes/darkmist.h
src/mame/mame.lst
src/mame/video/darkmist.cpp
src/mame/video/stfight.cpp

Air Raid, Street Fight and Dark Mist all basically use very similar video systems (4 layers, 2 of them being ROM based tilemaps, a CLUT prom for each layer which controls colours and transparency handling)
this takes some steps towards allowing a common implementation of it.

various Seibu Refactoring,

---

src/mame/drivers/kurukuru.cpp

- Ticket dispenser now works for real, dispensing on command rather than like crazy
- Correct "Payout Mode" DIP settings
- Correct DSW1 settings in Pyon Pyon Jump
- Rename coin inputs and coin-related DIP switches and reorder them by increasing denomination
- Remove bogus "Unknown" inputs that aren't actually used
- Full character names only for Kuru Kuru Pyon Pyon (except in bookkeeping mode)
- Reset button now mapped as "Memory Reset" (though it also resets the program)
- Random notes based on program code

kurukuru, ppj: Input/output improvements

---

src/frontend/mame/info.cpp

On pull request #1200, MASH identfied a regression caused by recent changes to rom_entry handling.  That said, I disagreed with his proposed fix because the code did a backwards scan for ROMENTRY_ISEND.  I don't think this is correct; ROMENTRY_ISEND should only work for forward scans, and it probably worked by accident simply because rom_entry structures were likely allocated back to back.
As far as I can tell, my proposed change seems to work but I'm somewhat fuzzy on the interactions between BIOS ROMs and devices, and it is possible that I'm neglecting a use case.

This should fix a regression incurred from the rom_entry changes identified by MASH

---

src/devices/imagedev/cassette.cpp
src/emu/diimage.cpp
src/emu/diimage.h

Take note that I eliminated make_readonly(); here is why I think the calls were unnecessary:
1.  All image loads through softlists are done through common_process_file(), and thus going to be readonly anyways
2.  The cassette.cpp call to make_readonly() seems to be a residual hack, if a failure occurs the image will be unloaded anyways

Eliminated device_image_interface::make_readonly()

---

src/mame/drivers/toaplan2.cpp
src/mame/includes/toaplan2.h

- Add NVRAM to Power Kick and Othello Derby; document the reset mechanism for the latter
- Add ticket dispenser to Power Kick (seems to work for the most part)
- Remove numerous bogus DIP switches
- Thoroughly reconfigure coin inputs in Power Kick, adding counters and lockouts for all three (including the "Key In" input that really isn't)
- More meaningful settings for the "Payout" DIP switch in Power Kick (based on program code)

pwrkick, othldrby: Various improvements

---

src/emu/softlist.cpp
src/emu/softlist.h
src/emu/softlist_dev.cpp
src/emu/softlist_dev.h
src/frontend/mame/clifront.cpp

This also fixes a likely undiscovered issue where the filename in softlist XML parse error messages was also blank

Fixed an issue that caused softlist device descriptions to be blank

---

src/osd/modules/sound/xaudio2_sound.cpp

This fixes the audio distortion when using -refreshspeed or -speed in combination with -sound xaudio2.  Currently the xaudio2 module expects an exact number of samples per update, otherwise audio glitches are introduced. When using -refreshspeed or -speed, the sound output is resampled by the core sound manager to meet the new speed factor. This causes a different number of samples to be sent to xaudio2, which causes the mentioned glitches. While the module seems to be designed to allow this circunstance, there are two issues preventing correct behaviour:
1.- New sound buffers are not submitted if there's currently a buffer on the queue.  Maybe there was a good reason for this, but removing this code restores correct audio for the most part.
2.- In case of a speed factor lower than 1.0, …

Fix audio distortion with -refreshspeed and -sound xaudio2 (MT 06199)

---

scripts/src/emu.lua
src/emu/romentry.cpp
src/emu/romentry.h
src/emu/romload.h

turbosub had a ROM_COPY declaration with an expression ('ROM_COPY( "main_code", 0x18000 + 0x2000,...) and this simply did not work with the new model.  This required changing ROM_* declarations to more resemble how they used to be and to perform the conversion on load.

Changed how ROM_COPY and ROM_FILL are represented in tiny_rom_entry to be more how they were in the past

---

hash/x1_flop.xml

ys3 wants to load the intro disk first, but fails after loading the IPL. ys2 wants you to insert disk A (flop2) into the first drive (drive 0) at that screen, then press Enter.

Minor fixes (nw)

---

src/mame/drivers/cps2.cpp
src/mame/drivers/esd16.cpp
src/mame/mame.lst

Deluxe 4 U (ver. 0107, 07/01/2000) [caius]
the flash roms on the board appear to be faulty however, good reads could not be obtained, so left it as not working.

new clones  Deluxe 4 U (ver. 0107, 07/01/2000) [caius]

---

src/mame/drivers/maygay1b.cpp

Fix the lamp mapping for the first half of the matrix
Fix typo and add comment to function that is intended to handle the second half of the matrix

Maygay M1A/B partial fix for lamp mapping

---

hash/pc98_cd.xml

- Added 7 new dumps sourced from P2P
- Added entries from fmtowns_cd.xml that are hybrid CDs and work on PC-98x1

pc98_cd.xml: added more disks + FM Towns hybrids

---

src/mame/drivers/namconb1.cpp

Also we can probably get rid of the MACHINE_IMPERFECT_SOUND flag for the C352 games now, but that will be for another pull request.

namconb1: forgot speaker rearrangement for NB2

---

src/mame/drivers/namconb1.cpp
src/mame/includes/namconb1.h

Did some digging into the sound timing issue in certain NB-1 games.
It seems like the C75 MCU does not like non-60 hz interrupt intervals,
wanting the interrupts to sync with a 120hz internal timer.
By moving the interrupt callbacks to separate 60 hz timers
(instead of the 59.7 scanline timer), this fixes the sound tempo in
nebulray, gslugrsj, gslgr94u and clones, and vshoot.

namconb1: fix sound timing for some games.

---

src/mame/drivers/vii.cpp

Add documentation for 3 bugs in the Vii's recently discovered diagnostic menu (from https://tcrf.net/Vii):
-- The "EEPROM TEST" option in the diagnostic menu (accessible by holding 1+2 or A+B during startup) freezes when selected
-- The "MOTOR" option in the diagnostic menu does nothing when selected
-- The input for the gyroscopic sensor tests in the "KEYBOARD + G-SENSOR" sub-menu goes haywire

Document 3 diagnostic menu bugs in the Vii's BIOS

---

src/devices/cpu/h8/h8_adc.cpp
src/mame/drivers/namcos12.cpp

Techno Drive previously displayed a 'COIN ERROR' at bootup. Fixed this by
patching the sub CPU program (not the best fix maybe but I hope it will
work for now).
The contents of 'th1fl3l.12' and 'th1fl3u.13' appeared to have been
swapped. Swapped the filenames and placed them at the proper memory
location (0x1800000) and the game no longer crashes at the Namco logo.
Played through the game a few times and it seems to be fully working
now.

Make Techno Drive working, fix H8 ADC inputs.

---

src/devices/cpu/h8/h8_sci.cpp
src/mame/drivers/namcos12.cpp

Sub CPU seems to expect certain H8 SCI behavior (especially after starting a transmission by clearing the TDRE flag), otherwise it locks up after a few minutes making controls unresponsive.
Also added notes to namcos12.cpp regarding input calibration and initial setup.

Techno Drive improvements

---

src/mame/drivers/maygay1b.cpp
src/mame/includes/maygay1b.h

m_kbd_ports array order was wrong, strobe needed the same ^4 bit twiddle as the lamps

Maygay - fix input strobe order bug

---

src/devices/video/mc6847.cpp

Fixed a bug from where video data was sampled that could cause too many samples to be loaded in low resolution video modes
On the CoCo, this fixes some low resolution video modes (e.g. - G3R/PMODE2), used by Project Nebula and some other games

Fixed some MC6847 low resolution video modes

---

hash/coco_cart.xml

'cclimber' crashes, whereas 'cclimbra' did not.  After reviewing the difference between the two dumps, I've concluded that the 'cclimbra' so-called "alternate" is in fact the correct dump.
It isn't clear to me who maintains these softlists, or if the softlists are derived from some other data source.  If there is a better way to make this correction, let me know.

Changed coco_cart softlist 'cclimbra' alternate ROM to be the correct rom for 'cclimber'

---

src/lib/formats/cassimg.cpp

This is just better error checking.  You can see this if you create a garbage file named 'foo.csw' and invoke the following command:
mame bbcb -cass1 foo.csw
With this change you get an invalid image error.  Without it, you get this:
Caught unhandled St12length_error exception: vector::_M_default_append

Performs argument checking on the return value of CassetteLegacyWaveFiller.chunk_sample_calc()

---

src/mame/drivers/bfm_sc2.cpp
src/mame/drivers/bfm_sc4.cpp
src/mame/includes/bfm_sc4.h
src/mame/video/bfm_dm01.cpp
src/mame/video/bfm_dm01.h

pretty sure the layout string lookups on sc2prem are killing us tho, might have to treat the DMD as a tiny screen.

put the DM01 matrix board CPU inside the device for BFM Sc2/4.

---

src/emu/debug/debugcmd.cpp

The 'trace' and 'traceover' commands were registered as having three arguments.  This fixes it so there are four arguments
This seems to have been broken a long time.  My guess is that when the ability to disable loop detection was added, the argument count was not changed to continue allowing the existing command argument.

Fixed the ability to have an action on the debugger 'trace' and 'traceover' commands

---

src/mame/machine/6883sam.cpp
src/mame/machine/6883sam.h

This changes the 6883 SAM implementation to assume that memory bank lengths smaller than the available space are no longer mirrored, which is how a legit CoCo 1/2 with less than 32k of RAM would really be.

[COCO 1/2] Fixed configurable RAM sizes (mametester bug #5823)

---

src/devices/cpu/z80/z80.cpp
src/emu/emumem.h
src/mame/drivers/skylncr.cpp

- Use standard input mappings in all games except Sonik Fighter
- Add working hopper outputs and payout buttons
- Promote mbutrfly to WORKING after solving the protection (the code wasn't encrypted) and add the button lamps internally associated with it
- Decrypt bdream97, which is almost working now with obvious graphical glitches and some apparent input problems
Slight error logging elaboration for illegal Z80 instructions (nw)

Improvements to almost all games in skylncr.cpp

---

scripts/genie.lua
src/emu/render.cpp

-Wno-missing-braces is unfortunately now necessary to avoid errors on almost every single use of the std::array initializer in devfind.h. (Apparently C++14 does make double braces optional for std::array initializers, but clang and GCC's -Wmissing-braces never took that into proper account, which is why GCC may still have it disabled by default.)
Several other Clang-specific warnings have been undisabled; some might perhaps need to be locally reenabled if legacy 3rdparty code or sundry OSD includes happen to disagree with them. The only warning to require any code changes was -Wabsolute-value, which seems to have caught a minor render bug (and nothing more).

Change warning flags for Clang build (nw)

---

src/mame/drivers/williams.cpp

Correct rom names in Turkey Shoot Fixed as per PCB picture:
http://softwarethis.com/arcade/boards/turkey/pics/turkey.jpg
http://softwarethis.com/arcade/boards/turkey/info/turkey.txt
All stickers on the Turkey Shoot roms says PROTO, so i changed the description Turkey Shoot (prototype).
Find also the proms for Mystic Marathon in an old Mystic Marathon romset. They are the same as Turkey Shoot.

Added video proms to Turkey Shoot and Mystic Marathon

---

src/emu/emupal.cpp
src/emu/emupal.h
src/emu/memarray.cpp
src/emu/memarray.h
src/frontend/mame/ui/viewgfx.cpp
src/mame/video/seibuspi.cpp

- On the UI graphics viewer's palette screen, moving the mouse over a color rectangle will show the index of the entry and its RGB values in hexadecimal.
- For indirect pens, the index of the corresponding color will also be shown.
- For colors in normal RAM-based palettes, the raw (i.e. undecoded) value stored in memory will also be shown. This does not currently work with most buffered palettes (though the Seibu SPI driver has been updated for this purpose), and is totally incompatible with PROM-based or RAMDAC-based palettes.
(nw) The changes made to the core while implementing this feature may look more substantial than they really are. A whole batch of read methods have been made const, and palette_device now has a generic read_entry function that is used both internally and …

Show color values in palette viewer

---

src/emu/emuopts.cpp
src/emu/emuopts.h
src/emu/render.cpp
src/emu/render.h

New stretching options:
- New option -unevenstretchy (complementary to -unevenstretchx)
- New option -autostretchxy, to automatically apply -unevenstretchx or -unevenstretchy based on source native orientation.
The purpose of -autostretchxy is to achieve evenly spaced scanlines when using filters on LCD monitors, by applying fractional scaling only on direction of the source scanlines.
Note: in options -unevenstretchx/unevenstretchy and -intscalex/intscaley, the x/y axes consistenly correspond to:
- x: long dimension of target monitor
- y: short dimension of target monitor

New stretching options (as suggested by Jeeze)

---

src/emu/digfx.h
src/mame/drivers/barni.cpp
src/mame/drivers/stfight.cpp
src/mame/video/airraid_dev.cpp

- Correct address space number for audiocpu_map in barni.cpp
- Add missing_dependencies check to airraid_dev (fixes segfault in tilemap viewer; yes, I know these tiles are 100% garbage)
- Add assert to device_gfx_interface::palette() to help catch dependency mistakes like the above
- Add MACHINE_IMPERFECT_SOUND to cshootert (music desyncs a lot)

Misc. fixes (nw)

---

src/mame/drivers/gba.cpp

This is untested, but similar in principle to af97bde77ba493435e759f4f987e990ba8de7426.

Attempt at fixing gba savestates (nw)

---

src/devices/sound/ay8910.cpp
src/mame/drivers/big10.cpp

- Use applicable gambling input types and keypad for numbers instead of BUTTON(n)
- Add ticket dispenser for payout (but is there any hopper feedback? no obvious error message)
- Add lamp output(?)
- Try to puzzle out some more DIP switches based on what the code does
Slight improvements to AY8910 error logging, with some messages now disabled by default (nw)

big10: Various modest input/output improvements

---

src/mame/drivers/seattle.cpp
src/mame/layout/calspeed.lay
src/mame/layout/hyprdriv.lay
src/mame/layout/vaportrx.lay

Surprise. it's the same output system as the Midway V Unit. Would expect to find more stuff in there. Couldn't crack what San Francisco Rush was doing with its outputs so couldn't include it. Perhaps some other games with the Widget board uses same system as well, but I'm not sure about the Flagstaff board.
EDIT: Hyperdrive confirmed my suspicions about Widget board. Just needed a small fix.

Added layout for California Speed

---

src/mame/drivers/pacman.cpp
src/mame/mame.lst

---------------------------------------------
Ms. Pac-Man (bootleg, set 2) [Siftware, MASH]
Siftware: multi Pac? (pac.zip)
* Added IC type and sticker letter from the info text to the roms. 
* gfx1 roms pac.5e and pac.5f have identical halves, but the checksum for the first
halves are 93933d1d and 22b0188a and these are the original mspacman gfx1 roms.
* Rom pac.3m and pac.4a have wrong length and are 8bit dumps, but they
are MAME's mspacman roms 82s126.3m and 82s126.4a.
* Sound rom 82s126.1m is missing, but all mspacman versions use the same one.
* Converted rom pac.d with jedutil to 82s153.d.
I have compared all Ms. Pac-Man versions with this dump and the
program is like clone Ms. Pac-Man (bootleg).
The differences are:
269E: 32 03 4E      ld   ($4E03),a  // Note: Like …

New Ms. Pac-Man clone

---

src/mame/drivers/galaga.cpp
src/mame/mame.lst

Battles (set 2) [Siftware, MASH]
Siftware: Battles (bg.zip)
* Converted rom bg.a16 with jedutil to pal10l8_bg.a16.
* Added the BG number from the info text to the roms. Correct name for bg.h9 is bg7.h8.
* Roms dumps bg.c5, bg.c6, bg.c10, bg.f10, bg.f13, bg.f14, bg.h12, bg.h13 and bg.h14
are the proms in MAME, but have wrong length and are dumped in 8bit not 4bit.
* Fixed also the proms length in MAME's clone 'battles', they are the same now as the xevious ones.
battles/battles2 maincpu program differences
============================================
battles                           | battles2
-------------------------------------------------------------------
02AF: 38 26     jr   c,$02D7  | 02AF: 18 26     jr   $02D7
0313: 28 F9     jr …

New Xevious clone

---

src/mame/machine/gb.cpp

I compared the sound register writes made by the Mega Duck and Game Boy versions of Snake Roy and Pile Wonder. From that I found that the nibbles of the Mega Duck envelope and lfsr registers are reversed relative to the Game Boy. Emulating this appears to fix the Mega Duck sound.

Fix Mega Duck envelope and lfsr sound registers

---

src/emu/diimage.cpp
src/emu/diimage.h
src/emu/image.cpp

This addresses MT bug #6372.  The prior issue is that creating serial and/or printer output relied on how image_load() would create images that were not there.  This behavior was not universally desirable (the consensus was that it was wrong for disk images, up in the air for cassettes etc).  This change makes it possible for devices to control this behavior.
Currently I have it associated with image_type(); this might not be the ideal fix.

Allows devices to indicate whether image creation should be supported at the command line

---

src/devices/imagedev/cassette.h
src/emu/diimage.cpp
src/emu/diimage.h

Tafoid reported that 'bbcb exile' failed in the tip, but succeeded in MAME 0.176.  I've identified the issue.
`
In MAME 0.176, cassette.cpp had the following code:
const char *extension;
...
if (software_entry()==nullptr) {
extension = filetype();
} else {
fname = m_mame_file->filename();
int loc = fname.find_last_of('.');
if (loc!=-1) {
extension = fname.substr(loc + 1,fname.length()-loc).c_str();
} else {
extension = "";
}
}
`
The implication of this hack is that filetype() shouldn't be trusted for cassettes loaded by softlists.  The fact that this relied on the return value of c_str() invoked on an rvalue implies that this worked by accident, but that is a separate issue.
This hack was (IMHO correctly) completely unwound in my softlist changes.  The fix to make sure that filetype() …

Now setting m_filetype for images loaded from softlists

---

src/devices/imagedev/diablo.cpp
src/devices/imagedev/diablo.h
src/devices/imagedev/flopdrv.h
src/devices/imagedev/harddriv.cpp
src/devices/imagedev/harddriv.h
src/emu/diimage.cpp
src/emu/diimage.h
src/lib/formats/flopimg.cpp
src/lib/util/opresolv.cpp
src/lib/util/opresolv.h
src/mame/machine/psion_pack.cpp
src/mame/machine/psion_pack.h
src/tools/imgtool/iflopimg.cpp
src/tools/imgtool/imghd.cpp
src/tools/imgtool/imgtool.cpp
src/tools/imgtool/library.cpp
src/tools/imgtool/library.h
src/tools/imgtool/main.cpp
src/tools/imgtool/modules/amiga.cpp
src/tools/imgtool/modules/bml3.cpp
src/tools/imgtool/modules/cybiko.cpp
src/tools/imgtool/modules/hp48.cpp
src/tools/imgtool/modules/pc_hard.cpp
src/tools/imgtool/modules/psion.cpp
src/tools/imgtool/modules/rsdos.cpp
src/tools/imgtool/modules/thomson.cpp
src/tools/imgtool/modules/ti99.cpp
src/tools/imgtool/modules/ti990hd.cpp
src/tools/imgtool/modules/vzdos.cpp

The main point of this change is to C++-ify option_guide.  It was changed from a struct array to a class, namespaced etc, with the ultimate hope of incorporating an in-emulation image creation UI.
Imgtool got hit with a number of changes; I'll probably have to bring that off of the backburner and touch that up too.
Of course, feel free to defer this until after the release.

option_guide C++-ification, touched up imgtool

---

src/mame/drivers/witch.cpp

- Use standard gambling input types where appropriate
- Identify "Attendant Pay" (keyout?) and payout switches
- Remove fake DIP switches
- Names of real DIP switches no longer all-caps
- Expand range of NVRAM
- Add two PPIs for I/O
- Partially implement hopper output

witch: Sort out which inputs and outputs are which

---

src/mame/drivers/pacman.cpp
src/mame/mame.lst

Crush Roller (set 3) [MASH]
This Crush Roller set from Kural and has no NOPs like MAME's Kural sets
Crush Roller (set 3) or (set 4). They look like bootlegs by comparing the DASMs.
I changed the name to Crush Roller (set 3) and the others to (set 4) and (set 5).
Romset: Crush.zip
1.6E 4096 2752 1998-03-11 15:22 50A1A776
2.6F 4096 2617 1998-03-11 15:22 5B03C1F8
3.6H 4096 2997 1998-03-11 15:22 AE5B39FB
4.6J 4096 2206 1998-03-11 15:23 DDF63743
5.5E 4096 1993 1998-03-11 15:23 B1C86CD7
6.5F 4096 1439 1998-03-11 15:23 B5C14376
6331.4A 256 81 1998-07-14 14:43 63EF3927
82S129.1M 256 139 1998-07-19 21:41 A9CC86BF
82S129.3M 256 24 1998-07-19 21:41 77245366
82S129.4A 256 81 1998-07-19 21:42 63EF3927
82S129.7F 32 32 1998-07-19 21:42 FF344446

New Crush Roller clone

---

scripts/src/tools.lua
src/tools/imgtool/main.cpp
src/tools/imgtool/modules.cpp
src/tools/imgtool/modules/hp9845_tape.cpp
src/tools/unidasm.cpp

Hi,
This set of commits adds the support of "hti" image files to imgtool.
The "hti" format is used to simulate tape cartridges in hp9845b driver (actually it's the simulator of HP TACO chip that uses this format).
I've also added support of HP Hybrid CPUs to unidasm: forgot this for a long time.
Thanks.
--F.Ulivi

Imgtool now supports HP9845B tape image

---

hash/psx.xml

The removed discs are identical to their redump.org counterparts,
they've just been dumped with different offsets.

Removed dupes from psx.xml; shortnames consistency fixes

---

src/mame/drivers/snk6502.cpp
src/mame/mame.lst

Nibbler (rev ?) [MASH]
Romset: Nibbler/nibbler.zip (18kb)
IC07        4096  2706  1994-06-14 22:37  7F9D715C
IC08        4096  2579  1994-06-14 22:37  E46EB1C9
IC09        4096  1159  1994-06-14 22:37  A599DF10
IC10        4096  1660  1994-06-14 22:37  E2652C11
IC12        4096  2586  1994-06-14 22:38  E569937B
IC14        4096  1174  1994-06-14 22:38  48EC4AF0
IC15        4096   883  1994-06-14 22:39  7205FB8D
IC16        4096  1705  1994-06-14 22:39  4BB39815
1C17        4096   806  1994-06-14 22:39  ED680F19
IC50        4096   639  1994-06-14 22:41  01D4D0C2
IC51        4096   303  1994-06-14 22:40  FEFF7FAF
IC52        2048   286  1994-06-14 22:40  CABE6C34
README.TXT   643   329  1994-06-14 22:42  B31C0466
First time i start the game, IC10 …

New Nibbler clone

---

src/mame/drivers/phoenix.cpp
src/mame/mame.lst

Phoenix (Amstar, set 2) [MASH]
Romset: Amstar/Phoenix.zip (53kb)
The ZIP file includes 4x Phoenix versions (40files). Three of them are in MAME.
Here i list only the important files:
IC23-CG1.3D  2048  1289  1996-01-28 21:05  3C7E623F
IC24-CG2.4D  2048   555  1996-01-28 21:06  59916D3B
IC39-CG3.3B  2048  1218  1996-01-28 21:07  53413E8F
IC40-CG4.4B  2048   795  1996-01-28 21:07  0BE2BA91
IC45-PGl.1A  2048  1496  1996-01-28 21:08  5B8C55A8
IC46-PG2.2A  2048  1494  1996-01-28 21:09  273A4A82
IC47-PG3.3A  2048  1122  1996-01-28 21:09  CBBB8839
IC48-PG4.4A  2048  1139  1996-01-28 21:10  CB5D9915
IC49-PG5.5A  2048  1660  1996-01-28 21:10  73BCD2E1
IC50-PG6.6A  2048   835  1996-01-28 21:11  AC5E9EC1
IC51-PG7.7A  2048  1482  1996-01-28 21:11 …

New Phoenix clone

---

src/mame/drivers/sauro.cpp
src/mame/mame.lst

Added Sauro (bootleg) [Guru, MASH]
Sauro (bootleg) program roms are *heavy* different compared to all Sauro set.
Game don't use SP0256 speech (see readme.txt).
Romset: Tecfri\sauro_bootleg.zip
readme.txt      456    311   2002-12-03 13:21   50C02FAF
SAURO01.6C    32768  12389   2002-12-02 19:45   4FF12C25
SAURO02.7C    32768  21434   2002-12-02 19:46   72026B9A
SAURO03.16E   32768   7038   2002-12-02 19:59   A30B60FC
-- readme.txt --
Sauro (bootleg)
CPU  : Z80
Sound: Z80, YM3526, YM3014
RAM  : 2016 (x4), 6116 (x5)
Xtal : 20.000MHz, 8.000MHz
DIPs : 8 position (x2)
Other: ULN2003
unpopulated position for SP0256-AL
Only ROMs 01, 02 & 03 are different to existing archive.
Color PROMs match existing archive. One extra PROM was found near ROMs …

New Sauro clone

---

src/mame/drivers/dreamwld.cpp
src/mame/mame.lst

interesting set, it's older but actually shows the proper SemiCom copyright message and logo, also the mode select / high score tables use a different style (and a number of sprite / tile roms are different as a result)

new clones  Rolling Crush (version 1.03.E - 1999/01/29) [system11]

---

src/tools/imgtool/filter.cpp
src/tools/imgtool/filter.h
src/tools/imgtool/modules/hp9845_tape.cpp
src/tools/imgtool/stream.cpp

Hi everyone,
I've just pushed a new filter ("9845data") in imgtool to translate DATA files of HP9845 system to and from text files.
In HP9845 systems DATA files are a kind of files with a generic record-based format. They are used, among other things, to store BASIC programs in text (non-tokenized) form. My filter translates this record-base text into plain text files (and viceversa).
Thanks.
--F.Ulivi

Filter for Hp9845 data files added to imgtool

---

src/mame/drivers/pg685.cpp
src/mame/mame.lst

896K RAM, Bitmapped graphics, Combined CPU/Video/Memory board (with a small daughter card), different HD controller card (WD2010 based vs. 1010 on the OUA11).
The OUA11/OUA12 designation comes from the sticker on the backplate of the machines.

Added the later 286 variant to the Siemens Simatic PG685 skeleton.

---

src/tools/imgtool/iflopimg.cpp
src/tools/imgtool/imgtool.cpp
src/tools/imgtool/imgtool.h
src/tools/imgtool/library.cpp
src/tools/imgtool/library.h
src/tools/imgtool/main.cpp
src/tools/imgtool/modules/amiga.cpp
src/tools/imgtool/modules/pc_hard.cpp
src/tools/imgtool/modules/thomson.cpp

This also eliminated the need for get_sector_size
The asute reviewer will note that a side effect of this change is that in scenarios where we once returned IMGTOOLERR_OUTOFMEMORY, we now throw std::bad_alloc.  This is deliberate.  Having an error code for out of memory conditions no longer makes sense with MAME's embrace of the C++ way of doing things.  It is highly likely that I will follow up this change with one that eliminates IMGTOOLERR_OUTOFMEMORY in favor of throwing std::bad_alloc.
This commit also fixes a recent regression in which we passed nullptr to an std::string ctor

Imgtool:  Changed the read_sector apparatus to use std::vector

---

src/osd/modules/debugger/win/consolewininfo.cpp
src/osd/windows/winutf8.cpp
src/osd/windows/winutf8.h

This eliminated an unnecessary conversion step.
Also, I have no idea what this WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP) stuff is; it is hard to understand how it could possibly be correct because it ignores the 'window' parameter

Changed win_get_window_text_utf8() to return std::string

---

src/mame/drivers/galaxian.cpp
src/mame/mame.lst

UniWar S (Karateco) [MASH]
Uni Wars\uniwars.zip (18kb)
U1           2048  1454  1985-11-20  00:05  D975AF10
U10          2048  1194  1985-11-20  00:14  012941E0
U11          2048  1262  1985-11-20  00:15  DCC2B33B
U12          2048  1218  1985-11-20  00:16  C26132AF
U2           2048  1512  1985-11-20  00:06  B2ED14C3
U3           2048  1627  1985-11-20  00:07  945F4160
U4           2048  1523  1985-11-20  00:08  DDC808C5
U5           2048  1689  1985-11-20  00:10  A0847FE4
U6           2048  1654  1985-11-20  00:10  270A3F4D
U?           2048  1433  1985-11-20  00:11  C9245346
U8           2048  1171  1985-11-20  00:12  5760B65C
U9           2048  1266  1985-11-20  00:13  FC8B58FD
UNIWARS.TXT   246   222  1997-02-17  18:12  975BE46D
Roms U5 and U8 are …

New UniWarS clone

---

src/mame/drivers/model1.cpp

(however, it hangs after you insert coins waiting for the safety bar to lower, also collisions in wingwar still seem broken since the swa work)

make wingwar360 not crash on startup.

---

src/mame/drivers/model1.cpp

there still seems to be something uninitialized or some memory corruption as quite often it will crash instead of launching, but if it does launch you can get a title screen and attract demo with some 3d.  roms pass in rom test now too.
3d is quite broken, lots of polys being stretched in weird ways and no 3d palette.

allow netmerc to boot

---

src/mame/drivers/sg1000.cpp

The Othello Multivision FG-1000 only has one built-in controller. The OMV FG-2000 removed this in favour of external controllers (which will need to be made into slot devices in the future).
OMV FG-1000: http://www.famitsu.com/image/29819/pEllnbNQfCJ58skZ25uB511N6eSFfAu6.jpg
OMV FG-2000: http://segaretro.org/images/6/60/OthelloMultivision_FG-2000_1.jpg
Misc: http://segaretro.org/Othello_Multivision

Remove 2nd joystick from omv1000

---

src/mame/drivers/aristmk5.cpp

Fixed missing ARISTOCRAT_MK5_BIOS defines addition:
https://github.com/mamedev/mame/commit/084e33a159d59b566fad86fbc2032984647be135

Fixed missing ARISTOCRAT_MK5_BIOS defines addition

---

src/osd/modules/debugger/win/consolewininfo.cpp
src/osd/modules/debugger/win/debugviewinfo.cpp
src/osd/modules/debugger/win/editwininfo.cpp
src/osd/modules/debugger/win/uimetrics.cpp
src/osd/modules/file/windir.cpp
src/osd/modules/file/winfile.cpp
src/osd/modules/file/winptty.cpp
src/osd/modules/font/font_dwrite.cpp
src/osd/modules/font/font_windows.cpp
src/osd/modules/input/input_dinput.cpp
src/osd/modules/input/input_dinput.h
src/osd/modules/input/input_rawinput.cpp
src/osd/modules/lib/osdlib_win32.cpp
src/osd/modules/monitor/monitor_dxgi.cpp
src/osd/modules/monitor/monitor_win32.cpp
src/osd/modules/render/d3d/d3dhlsl.cpp
src/osd/strconv.cpp
src/osd/strconv.h
src/osd/windows/main.cpp
src/osd/windows/winmain.cpp
src/osd/windows/winutf8.cpp
src/osd/windows/winutil.cpp

[a|w|t|utf8]_from_[a|w|t|utf8_]string(xyz.c_str()) seems to be common enough to justify overloads.  Also, I'm explicitly assuming that it is legal to override the NUL pointer within a C++ basic_string (e.g. - s[s.size()] = '\0').  As far as I can tell, this seems to be legal - please don't shoot if I am wrong.

Adding new string conversion overloads

---

src/tools/imgtool/imgtool.cpp
src/tools/imgtool/imgtool.h

[Imgtool] Fixed a recently introduced bug that could cause module's close() callback to be invoked if an image fails to be opened or created.
This is really a temporary workaround while Imgtool gets C++-ified; the real issue is the ad hoc nature of the existing semantics of image construction.

[Imgtool] Fixed a recently introduced bug

---

src/devices/machine/rp5c01.cpp
src/devices/machine/rp5c01.h

This also makes the RP5C01's NVRAM actually non-volatile (previously it would be cleared upon reset after being loaded).
The RP5C01 has a power supply line but no reset signal input, so device_reset doesn't seem to make sense here.

Fix clock regression with RP5C01 (nw)

---

src/mame/drivers/nmk16.cpp
src/mame/mame.lst

note, these might actually just be Korean versions rather than prototypes.  This one is encrypted unlike the other, but same 'cheap' looking PCB with typical Korean parts mixed with the original NMK customs.

new clones  Bombjack Twin (prototype? with adult pictures, set 2) [Sugoi Helsinki]

---

src/mame/drivers/decocass.cpp
src/mame/includes/decocass.h
src/mame/machine/decocass.cpp
src/mame/mame.lst

2 sets
Ocean to Ocean (Medal) (DECO Cassette MD) (No 10 / Ver 1 Japan)
Ocean to Ocean (Medal) (DECO Cassette MD) (No 10 / Ver 6 US)
also make the different decocass bios roms actually selectable.

NEW WORKING   Ocean to Ocean (Medal) [Joseph, the Game Preservation Society]

---

hash/hp9845b_rom.xml
scripts/src/bus.lua
scripts/target/mame/mess.lua
src/devices/bus/hp9845_io/98035.cpp
src/devices/bus/hp9845_io/98035.h
src/devices/bus/hp9845_io/hp9845_io.cpp
src/devices/bus/hp9845_io/hp9845_io.h
src/devices/cpu/hphybrid/hphybrid.cpp
src/mame/drivers/hp9845.cpp
src/mame/includes/hp9845.h

Hi,
I just pushed a set of commits that introduces the support of I/O slots on HP9845B system.
So far I've just implemented a single type of I/O cards: the HP98035 real time clock.
Ideally I'd have implemented this card by emulating the HP "nanoprocessor" in it (docs are
available) but I couldn't find a dump of the firmware ROM of this card. So my code
attempts to emulate in C++ the various functions of the original firmware.
In HP9845 systems every I/O card has a configuration value to set the "Select Code".
This is basically the address of the card in the I/O address space. It is a number in the
range 1 to 12, inclusive. Needless to say, every card must have a different SC.
This is not a problem at the moment because there's just a single slot and a single type
of plugin cards.
If you …

Hp9845: added support of I/O cards

---

src/devices/machine/8530scc.cpp

This patch fixes a typo in 8530scc.cpp. This typo was causing the Mac emulator from being able to boot System 7 without locking up during the boot process. With this patch, 7.5.3 Rev. 2 is able to boot normally.

Fix typo in 8530scc.cpp

---

src/devices/machine/pit8253.cpp
src/devices/video/mc6845.cpp
src/devices/video/mc6845.h
src/mame/drivers/amusco.cpp

- Inputs figured out almost completely
- Add blinking cursor for service mode
- Gross hacks used to get coins working due to broken IRQ timings
- Palette remains in dire need of improvement
Peripheral emulation improvements (nw):
- mc6845: Allow cursor blink state to be read
- pit8253: Eliminate device name from logging messages

amusco: Major improvements; promoted to WORKING

---

src/tools/imgtool/iflopimg.cpp
src/tools/imgtool/imghd.cpp
src/tools/imgtool/imgtool.cpp
src/tools/imgtool/library.cpp
src/tools/imgtool/library.h
src/tools/imgtool/modules/amiga.cpp
src/tools/imgtool/modules/bml3.cpp
src/tools/imgtool/modules/concept.cpp
src/tools/imgtool/modules/cybiko.cpp
src/tools/imgtool/modules/cybikoxt.cpp
src/tools/imgtool/modules/hp48.cpp
src/tools/imgtool/modules/hp9845_tape.cpp
src/tools/imgtool/modules/mac.cpp
src/tools/imgtool/modules/os9.cpp
src/tools/imgtool/modules/pc_flop.cpp
src/tools/imgtool/modules/pc_hard.cpp
src/tools/imgtool/modules/prodos.cpp
src/tools/imgtool/modules/psion.cpp
src/tools/imgtool/modules/thomson.cpp
src/tools/imgtool/modules/ti99.cpp
src/tools/imgtool/modules/ti990hd.cpp
src/tools/imgtool/modules/vzdos.cpp

They always took ownership of the stream; this just makes it official.  Because the ownership would only traditionally happen if the open() or create() succeeded, I had to do a clumsy pattern where I call get() at the beginning of the callback to get the stream, but later on release() immediately prior to succeeding.

[Imgtool] Changed the create/open callbacks to take 'imgtool::stream &&'

---

src/emu/devfind.h
src/mame/includes/coco.h
src/mame/machine/coco.cpp

Also, I added a size() accessor to object_array_finder.  If there is a better way to do this, let me know.

[COCO] Changed to use required_ioport_array and optional_ioport

---

hash/segacd.xml

'm' is not a valid character for SHA1, and the string is one byte too long.

Fix typo in setlist sha1.

---

hash/segacd.xml

This should have all the faulty hashes fixed. 
Secret of Monkey Island changed to the redump.org dump as well.

Fix hash errors in Sega CD softlist

---

src/devices/machine/z80scc.cpp
src/devices/machine/z80scc.h

- zbus interface functions zbus_r and zbus_w added supporting shift left/right modes
- improved variant handling including the incomplete read register maps for some
- external CTS and DCD interrupts added
- improved device reset values
- SWI acknowledge command added
- improved/fixed handling of wr9, rr2, rr3
- wr7prime register added

SCC improvements

---

src/devices/machine/z80scc.cpp
src/devices/machine/z80scc.h

reading the modified vector through channel B register 2 didn't work. There was also a theoretical possibility that the unmodified vector had bits set in the vector fields. Both should be fixed now

Fixed vector modification

---

src/mame/drivers/indy_indigo2.cpp

This fixes the SCC hookup for the indy_indigo2.cpp driver enough to boot to the graphical menu. There are more improvements needed for the serial port to work fully but I need to test that a bit more with other drivers before pushing it.

Indy: Fixed SCC hookup

---

scripts/target/mame/mess.lua
src/mame/drivers/kron.cpp
src/mame/mame.lst
src/mame/mess.flt

Sorry guys but I can't figure out why I can't get this to link with the full MAME, just as a single driver build. For the full build I get this error:
`GCC 6.2.0 detected
Building driver list...
33747 driver(s) found
Compiling generated/mame/mame/drivlist.cpp...
Compiling generated/version.cpp...
Emitting mamevers.rc...
Compiling resources scripts/resources/windows/mame/mame.rc...
Linking mame64.exe...
../../../../mingw-gcc/obj/x64/Release/generated/mame/mame/drivlist.o:drivlist.cpp:(.rdata+0x14cf0): undefined reference to `driver_kron180'
collect2.exe: error: ld returned 1 exit status
mame.make:240: recipe for target '../../../../../mame64.exe' failed
make[2]: *** [../../../../../mame64.exe] Error 1
makefile:952: recipe for target 'mame' failed
make[1]: *** [mame] Error 2
makefile:950: …

WIP KRON-180 terminal controller

---

src/devices/cpu/m6809/6x09dasm.cpp

Fixed a recently introduced bug in the 6x09 disassembler that could cause asserts when hitting what would be a legal 6309 instruction when disassembling non-6309 code

Fixed a recently introduced bug in the 6x09 disassembler

---

plugins/cheatfind/init.lua
plugins/data/data_hiscore.lua
plugins/data/data_mameinfo.lua
plugins/data/data_messinfo.lua
plugins/data/init.lua
src/frontend/mame/luaengine.cpp
src/frontend/mame/luaengine.h
src/frontend/mame/mame.cpp
src/frontend/mame/ui/datmenu.cpp
src/frontend/mame/ui/mainmenu.cpp
src/frontend/mame/ui/pluginopt.cpp
src/frontend/mame/ui/selgame.cpp
src/frontend/mame/ui/selmenu.cpp
src/frontend/mame/ui/selsoft.cpp
src/frontend/mame/ui/ui.cpp

Done as a PR for comment and compile testing.

Luaengine sol2

---

src/devices/machine/z80dart.cpp
src/devices/machine/z80dart.h
src/lib/util/coretmpl.h

Don't merge this just yet, I want to switch to the new core template but couldn't get it to work so I implemented a simplified local template. I also feel, as an embedded C programmer by heart, that all the type abstraction in the core template might be quite heavy when using FIFO:s in emulated DMA transfers?
So let me know what you think and I go either way. Maybe we can have a bfifo for base types that can be represented in a one dimensional array, rather than de-referring pointers?
The code is regression tested for the pulsar, ampro and compis drivers at boot rom level. But I don't know how to do save_item on these fifo objects.

DART: Refactored FIFO:s using new template based fifo class

---

scripts/src/cpu.lua
scripts/target/mame/mess.lua
src/devices/bus/hp9845_io/98035.cpp
src/devices/bus/hp9845_io/98035.h
src/devices/cpu/nanoprocessor/nanoprocessor.cpp
src/devices/cpu/nanoprocessor/nanoprocessor.h
src/devices/cpu/nanoprocessor/nanoprocessor_dasm.cpp
src/mame/drivers/hp9845.cpp
src/tools/unidasm.cpp

Hi,
I've just pushed a set of commits where I re-implemented the 98035 RTC module of HP9845
system at a low level. This is now possible because Mr. Kueckes dumped the firmware ROM
for me.
In order to emulate the module at a low level, I also had to implement the driver for its
"nanoprocessor" microcontroller. The nanoprocessor disassembler is already
"Nathan Woods"ized (i.e. it uses ostream's) :)
I'm planning to use the nanoprocessor again for the 98034 driver I'm going to work on in the
near-ish future (have the firmware ROM for this one, too).
I'm repeating here the instructions to read the current time from the module.
If you want to try to read the real time clock from the card, you need to start MESS with
these options:
"-optrom1 iob:lpu_rom -optrom2 iob:ppu_rom -slot0 98035_rtc" …

Hp9845: re-implemented 98035 module with a nanoprocessor driver

---

src/mame/drivers/rainbow.cpp

Small fix for serial RX proposed on page 38 of Requirements-thread at Bannisters. Terminal mode (key "T") still misbehaves afterwards (handshake or keyboard problem...?)  Note that you can change TX and RX baud rates as well as handshake parameters in SETUP mode ("F3", tried FDXA or FDXB mode, 8,N,1, XON/XOFF, 9600 bps with Putty connected on 127.0.0.1). Thanks to all who help to narrow this down!
For reference: http://forums.bannister.org/ubbthreads.php?ubb=showflat&Number=103331&page=38

DEC Rainbow: apply fix for serial RX proposed by Shattered

---

makefile

Fedora have recently enabled ppc64 and ppc64le on their rawhide builders. The change requested here fixes building on ppc64le.

Fixed building on ppc64le

---

src/devices/machine/i8155.cpp
src/mame/drivers/amusco.cpp

i8155: Remove unnecessary tag() parameter from logerror calls (nw)

amusco: Identify and hook up 8155 interface chips for LPT & RTC

---

src/mame/drivers/sms_bootleg.cpp

note, this is actually quite interesting, this is a 512KB MASK rom, hence why it got missed the first time around.
it actually appears to have been pulled straight from a home Sega Master System mulit-game cartridge and used on the arcade PCB.  The rom contains another copy of the games menu in the first bank, except this copy of the menu has no timer/credit support and only references games in this specific rom.  It is completely ignored by the arcade hardware which uses the game data part of the rom only, never banking this copy of the menu in.
as this almost certainly came straight from a bootleg cartridge, this specific rom could also be added to the softlist with a custom mapper for the banking.

add the missing rom to the smssgame set [Astroblaster]

---

src/devices/cpu/cop400/cop410ds.cpp

This one actually had a change in behavior; I had to insert a 'break' somewhere.  Judging from the other cop4x0 disassemblers, this seems to be a bug in the existing disassembler

Changed the cop410 disassembler to use 'std::ostream &' internally

---

src/devices/machine/68230pit.cpp
src/devices/machine/fga002.cpp
src/devices/machine/fga002.h
src/devices/machine/scnxx562.cpp
src/mame/drivers/fccpu30.cpp
src/mame/mame.lst

- fccpu30: WIP New board variants added: cpu30x, cpu30xa, cpu30za, cpu30zbe, cpu30be8, cpu30be16, cpu30lite4, cpu30lite8, cpu30senr, cpu30senr501, cpu33
- fccpu30: support for -ramsize according to each board variant
- fccpu: Prepared to split out base fccpu class to support drivers for cpu2x and cpu4x boards etc
- fccpu30: renamed roms to reflect on content and versions
- Small fixes: PIT68230, FGA022, DUSCC

fccpu30: WIP New board variants added

---

src/mame/drivers/rainbow.cpp

MFM allows up to 17 sectors / track (the limit was set to 16 before).

DEC Rainbow: allow hard disks with up to 17 sectors/track 

---

src/devices/cpu/m68000/m68000.h
src/devices/cpu/m68000/m68k_in.cpp
src/devices/cpu/m68000/m68kcpu.cpp
src/mame/drivers/apollo.cpp
src/mame/drivers/fccpu30.cpp

I needed some way of indicating that the FPU socket is populated or not and found that the Apollo driver fiddles with the internal but public has_fpu parameter. I added methods to set and get it instead and moved it to the private section.

FPU enable/disable methods

---

hash/pc8801_flop.xml

"american truck mkii.d88" and "american truck.d88" got mixed up, kept the filenames as-is for now

Rearrange amtruck/amtrckm2 disks (nw)

---

scripts/src/bus.lua
src/devices/bus/hp9845_io/98034.cpp
src/devices/bus/hp9845_io/98034.h
src/devices/bus/hp9845_io/98035.cpp
src/devices/bus/hp9845_io/hp9845_io.cpp
src/devices/bus/hp9845_io/hp9845_io.h
src/devices/bus/ieee488/ieee488.cpp

Hi,
I'm opening a PR for a set of commits I've just pushed. It implements the HP98034 module for HP9845 system.
This module was used to interface 9845 machines with HPIB/GPIB/488 bus.
At the moment you can't connect anything to the HPIB bus so testing options are limited (can't exchange data with anything).
Anyway, a simple test is this (you need I/O optional ROM):
```
STATUS 7;A,B,C,D
DISP A,B,C,D
```
It should print "332 0 213 64" which is the correct status for the module at boot (provided you don't change the default settings).
I've sent to code@mamedev.org the firmware image of 98034 module (HP part no. 1816-1242).
Thanks.
-- F.Ulivi

HP9845: implemented HP98034 module (HPIB interface)

---

src/devices/video/upd7220.cpp

Calculation of 'addr' in inner for() loop of 'update_graphics": division by zero occurrs if mixed = false and m_lr = 0.

Fix division by zero in update_graphics

---

src/mame/audio/seibu.cpp
src/mame/audio/seibu.h
src/mame/drivers/airraid.cpp
src/mame/drivers/bloodbro.cpp
src/mame/drivers/cabal.cpp
src/mame/drivers/dcon.cpp
src/mame/drivers/deadang.cpp
src/mame/drivers/dynduke.cpp
src/mame/drivers/goodejan.cpp
src/mame/drivers/legionna.cpp
src/mame/drivers/nmk16.cpp
src/mame/drivers/r2dx_v33.cpp
src/mame/drivers/raiden.cpp
src/mame/drivers/raiden2.cpp
src/mame/drivers/seicupbl.cpp
src/mame/drivers/sengokmj.cpp
src/mame/drivers/shanghai.cpp
src/mame/drivers/toki.cpp
src/mame/includes/raiden2.h

- Eliminate SEIBU_SOUND_SYSTEM configuration macros hiding details of device construction
- Start using devcb for generic YM hookups
- Use device finder to connect seibu_sound_device to audiocpu
- kothello has only one YM2203 and one ADPCM, not two of each
Future changes planned
- Separate SEI0100BU and SIE150 types; Cabal and Dead Angle should each be using two of the former
- Separate SEI80BU device to handle Z80 decryption (Mustache Boy uses this for its main CPU)

Seibu sound device cleanup (nw)

---

makefile

Wasn't removed when mmicko did 9eb2734495cda6ff0391f317ca2565b421476738

Remove USE_BGFX option (nw)

---

src/devices/machine/68230pit.cpp
src/devices/machine/68230pit.h

Added some features that is needed for the micro20 selftest but couldn't hook up the missing parts so haven't verified that the self test actually can run through now. Improvements:
- H4 is now cleared in reset and asserted by software down the line
- By calling the update_tin method the device now support external clock for the timer.
- clock can also be polled at port C bit #2 
The test expects something to pulse at port B and then a clock at TIN (port C pin #2 alternate function)

Improved reset, timer and port C behaviour

---

src/mame/drivers/dec8.cpp

(dumps look good, hookups appears to be slightly different to other games due to different main CPU and interrupt schemes, still investigating)
(these can probably be used for the japanese clones if the ID byte is changed to create a fake rom, as was done for the other sets in the driver)

added id8751h dumps to 'csilver' and 'srdarwin', not hooked up yet [Caps0ff]

---

src/emu/uiinput.cpp

If file i/o is slow or you have huge art files in the UI, there is a delay larger than the configured initial delay for autorepeat. In this case, you get a double press effect in the UI menu.  The fix is just to double-check the current key state before allowing the autorepeat to happen.

Double-check key state before UI autorepeat. Fixes #1169

---

src/mame/drivers/dec0.cpp
src/mame/includes/dec0.h

- Reduce YM2203 speed to match music pitch on reference video
- Add second MSM5205 + two 74LS157 and fix communications
- Add sound banking (probably not entirely correct)

automat: Sound improvements

---

src/devices/sound/k054539.cpp
src/devices/sound/k056800.cpp
src/emu/save.cpp
src/mame/drivers/konamigx.cpp
src/mame/machine/konamigx.cpp
src/mame/video/k053246_k053247_k055673.cpp
src/mame/video/k054156_k054157_k056832.cpp
src/mame/video/konamigx.cpp

Previously, loading Konami GX states from a cold boot would hang because several items missed from the save were blocking the vsync and sound update IRQs. This patch fixes this issue; states can be loaded from a cold boot without impacting execution.

konamigx.cpp: fix save states

---

hash/apple1.xml

includes $09DC-$09FF. To use: put disassemble address in $44-$45 (low byte first) then 09F0R <enter>
[dis-assembler.zip](https://github.com/mamedev/mame/files/668839/dis-assembler.zip)

apple1.xml redump dis-assembler

---

src/mame/drivers/rainbow.cpp

All known ClikClok address spaces are supported: $fc000/fe000 (-B), $f4000 (older hardware for 100-B) and $ed000 (revision for 100-A). A table near RTC_ENABLED explains which driver to use...

DEC Rainbow 100: support all ClikClok versions

---

src/mame/drivers/midwunit.cpp
src/mame/includes/midwunit.h
src/mame/machine/midwayic.cpp
src/mame/machine/midwayic.h
src/mame/machine/midwunit.cpp

I've added a new device type and bare bones loading of them so you can see the code running however the communication with the main CPU is not hooked up yet so they still fallback to the simulation code.
also made nbamht a parent, because the nbamht / nbahangt situation really isn't too different to the umk3 / mk3 or sf2ce / sf2 situations, it's a distinct new release.

decapped and read out security pics for umk3 and rmpgwt [Caps0ff]

---

src/devices/cpu/tms32025/tms32025.cpp
src/emu/addrmap.cpp
src/mame/drivers/mc1000.cpp

- tms32025: Correct space of internal data maps
- mc1000: Separate out opcodes map
- addrmap.cpp: Replace a few debug asserts with friendlier error messages (makes validation less dangerous in debug builds)

Address map fixes (nw)

---

src/mame/drivers/joctronic.cpp
src/mame/mame.lst

- Bloody Roller (Playbar)
- Slalom Code 0.3 (Stargame)
punkywil: Added a ridiculously incomplete dump of the CPU ROM.
All of the above were originally dumped by Akiles500 at various dates.
Device hookups and memory maps in joctronic.cpp, following available schematics (nw)

New NOT WORKING pinballs

---

src/devices/cpu/z180/z180.cpp
src/devices/cpu/z180/z180op.hxx
src/devices/cpu/z80/z80.cpp
src/devices/cpu/z80/z80.h
src/devices/cpu/z80/z80daisy.cpp
src/devices/cpu/z80/z80daisy.h
src/mame/machine/cedar_magnet_sound.cpp
src/mame/machine/cedar_magnet_sound.h

- Reconfigure Z80 daisy chain behavior to use the standard vector for an external IRQ, rather than a bogus one from the last device in the chain
- Enable Z80 daisy chain on Cedar Magnet sound board (fake IRQ still necessary, though vectors are correct now)
- Source note regarding IM 2 behavior contrary to Zilog datasheet (nw; was fixed way back in 0.35b11)

Z80 daisy chain stuff

---

src/devices/machine/gen_latch.cpp
src/devices/machine/gen_latch.h
src/mame/drivers/dec0.cpp
src/mame/drivers/discoboy.cpp
src/mame/includes/dec0.h

- Add MCFG_GENERIC_LATCH_DATA_PENDING_CB to raise and lower a line automatically as the latch is written and read. This should make sound IRQs easier to deliver and reduce the incidence of HOLD_LINE in drivers.
- Update a few drivers to use this new callback.

New callback for generic_latch_8/16_device (nw)

---

src/devices/video/tms9927.cpp
src/mame/drivers/attache.cpp
src/mame/drivers/aussiebyte.cpp
src/mame/drivers/expro02.cpp
src/mame/drivers/rm380z.cpp
src/mame/includes/aussiebyte.h
src/mame/includes/rm380z.h
src/mame/machine/rm380z.cpp
src/mame/video/rm380z.cpp

The Research Machines 380Z was delivered in several variants.   The earlier versions had only a 40 columns display and the cassette tape interface.

Support for earlier COS versions on the RM380Z

---

src/mame/includes/taito_f3.h
src/mame/video/taito_f3.cpp

Taito F3 states loaded from a cold boot would execute okay with perfect sound, but large chunks of the graphics would be missing. This patch adds the F3 video RAM to the save state, and adds a device_post_load hook to force the MAME gfx_element for the F3's "pixel layer" to reread the tiles from the pivot RAM.

taito_f3: fix missing graphics on state load

---

src/mame/includes/harddriv.h
src/mame/layout/racedrivpan.lay
src/mame/machine/harddriv.cpp

Hooked up the outputs for harddriv.c
Hard Drivin' uses SEL1 for the shifter-force and SEL3 for the clutch-force
Lamps are somewhat correct - LC1 is connected to the APU board in Hard Drivin' and is used to toggle the seat lock, although I don't understand how exactly this works right now.
LC2 drives the bulb in the Abort-Button.
I also added single screen layouts for Race Drivin' Panorama

harddriv: hook up outputs and add "single screen"-layouts for race drivin' panorama (nw)

---

src/mame/drivers/peyper.cpp
src/mame/mame.lst

- Ator (Videodens)
The dump is credited to Gonzalo. The first program ROM is unfortunately missing, so this is for (partial) preservation only.

New NOT WORKING pinball

---

src/emu/ioport.cpp
src/emu/ioport.h
src/frontend/mame/ui/info.cpp
src/frontend/mame/ui/info.h
src/frontend/mame/ui/ui.cpp

- Changed how input sequences are assigned to service mode DIP switches. The frontend now assigns them the default sequence for the non-toggle service mode/test switch (not necessarily the F2 key, the previously hardcoded default) unless the machine happens to have one of those as well (as is somewhat common with gambling games).
- All DIP and configuration switches are automatically defined as toggle fields to make assigning input codes to them easier.

Service mode DIP switch adjustments

---

src/lib/util/unicode.cpp
src/lib/util/unicode.h
src/tools/imgtool/main.cpp

I really don't like the prevalence of '#ifdef WIN32' in this change, both the _setmode() and bypassing codecvt.  I strongly suspect that the latter is the consequence of some mistake that in practice doesn't cause problems in MSVC.  I welcome all eyes.

[Imgtool] Changed to use wcout/wcerr in order to support Unicode console output

---

src/mame/drivers/hng64.cpp

note, this came from a sample OTP chip that was purchased for testing / analysis, not one of the chips actually taken from a hng64 unit!  The chip had no protection and read out without issue.  It just ended up turning out to be the case that the sample chip had clearly been pulled from such a board at some point in the past.  As a result it isn't clear if this is the driving, shooting or fighting MCU type.
contains the internal string "64Bit I/O Controller Ver 1.0 1997.06.29(C)SNK"
a CPU core is needed (I'll probably do a basic skeleton in the next few days.

added a dump of one of the hng64 tmp87ph40an i/o chips [Caps0ff]

---

hash/a2600.xml
hash/megadriv.xml
hash/n64.xml
hash/snes.xml

Carts for a2600, megadriv, n64 and snes got redumped recently by TeamEurope. Add in newfound information from those dumps to the softlists.
Also remove syvalionp2 as it's simply a bad dump of syvalionp.

Add more softlist documentation based off new dumps

---

src/tools/discrepancy-fixer.py
src/tools/discrepancy-spotter.py

Hi all!
So I noticed that some clone machines have different ROM names to the machines that they're clones of, even for chips that contain completely identical data.  I'm guessing sometimes this should be the case, while sometimes it's due to the original ROM names being updated and the person forgetting about the clones (easily done)?
On the offchance it's at least sometimes the latter, I made a handy Python script that finds identical ROM chips in original-and-clone pairs, that have different filenames.  You can use it like this:
```
$ ./mame64 -listxml > arcade.xml
$ src/tools/discrepancy-spotter.py
```
This lists the source code's filename, clone machine's name, clone ROM's name and identical parent ROM's name, like this:
```
Loading XML file...
Done.
m58.cpp 10yard85: yf-s-3b.3b -> …
```

Clone ROM filename discrepancies

---

src/devices/machine/phi.cpp
src/mame/drivers/dynax.cpp

dynax.cpp: Correction regarding absence of MSM5205 in mjfriday (nw)

phi.cpp: Fix build (nw)

---

src/mame/drivers/rainbow.cpp

Enable Corvus hard drives (Patched CP/M 1.x only, requires DRCDUTIL.TD0 driver disk from Maslin archive).  See section CORVUS HARD DISK for patch instructions. DOS 2.x and CP/M 2.2 were once supported too, but drivers appear to be lost.

DEC Rainbow 100: enable Corvus hard drives

---

scripts/target/mame/mess.lua
src/devices/machine/hd63450.cpp
src/mame/drivers/miniforce.cpp
src/mame/mame.lst

This PR needs some thoughts and review I think. It is a 9 slot VME chassi and will emulate the miniFORCE 2P21 as documented on bitsavers. Right now it can load two slot devices in any of the 9 slots:
`mame miniforce -slot1 fcisio -slot2 fcisio etc...`
This works well for fcisio but the other slot device fcscsi triggers an assert in a device driver because there is no CPU in the chassi I assume:
`Fatal error: assert: ../../../../../src/devices/machine/hd63450.cpp:48: m_cpu != nullptr`
So please advice if I should fix the device(s) so they can be used in a system like this. I also need to make a fccpu20 board driver and a slot device. This seems not to be easy build wise so I am thinking of making two copies and maybe share some header file or similar. Thoughts?

WIP: miniFORCE 2P21 chassi - advice needed

---

src/devices/cpu/pps4/pps4.cpp
src/devices/cpu/pps4/pps4.h
src/devices/machine/ra17xx.cpp
src/devices/machine/ra17xx.h
src/mame/drivers/gts1.cpp

- Split PPS-4 and PPS-4/2 device types; better explain and properly implement the difference
- Use callbacks for discrete input/output ports instead of fake memory addresses
- A17xx reads the address bus directly during I/O accesses
- Misc. chip documentation

PPS-4 refinements and modernization (nw)

---

src/mame/drivers/atlantis.cpp

This preserves mwskinsa as it was before 7c22de056ca511f9bfdf9b52850c9c926ceee4d6.

Remove unused mwskinsa_mod definition in order to fix build (nw)

---

src/mame/drivers/munchmo.cpp
src/mame/includes/munchmo.h
src/mame/video/munchmo.cpp

- Eliminate HOLD_LINE while remaining true to schematics
- Let main CPU properly acknowledge NMI
- Use one VBLANK handler instead of two
- Correct audio CPU clock divider (should be same as PSGs according to schematics)
- Misc. stylistic streamlining

munchmo.cpp: IRQ cleanups (nw)

---

src/emu/diimage.cpp
src/emu/softlist_dev.cpp
src/frontend/mame/mameopts.cpp

(nw) MAME's architecture for software loading remains gruesomely overcomplicated, and this makes it even less efficient than it already was. However, I think more invasive cleanups would best be left until later.

Make "requirement" field in softlists actually work (MT 6464)

---

src/devices/sound/msm5205.cpp
src/devices/sound/msm5205.h
src/mame/drivers/joctronic.cpp
src/mame/machine/pce_cd.cpp

- Implement device_clock_changed instead of using custom handler
- Add proper write handlers for S1 and S2 lines and store their state internally

MSM5205 architectural cleanups (nw)

---

src/devices/imagedev/floppy.cpp
src/devices/imagedev/floppy.h
src/lib/formats/wd177x_dsk.cpp
src/lib/formats/wd177x_dsk.h

dskchg_writable is required for hp_ipc -- it polls dskchg line and resets it once a new floppy is detected.
has_trk00 is wanted by ibm6580 -- mostly by diags, which expect 'recalibrate' command to fail.
wd177x change is for upcoming PPG Waveterm driver -- sector numbering does not start from 1 on reverse side of disk but continues from last sector number on previous side.

minor floppy internals improvements

---

src/emu/main.cpp

I'm doing this in response to a compilation error on MSVC 2015.  As far as I can tell, this is a bug in the compiler.  My basis for asserting this is that placing the following declaration within the 'endpoint.on_open = <<lambda>>' gives the same compilation error:
const std::function<void(void)> mycallback = [](void) {};
Whereas moving that logic outside of the 'endpoint.on_open = <<lambda>>' does not give an error.
Normally I don't like working around buggy compilers, but in this case the callback is supposed to be optional anyways.

Removing unnecessary callback

---

src/emu/debug/debugcmd.cpp
src/emu/debug/debugcmd.h
src/emu/debug/debugcpu.cpp
src/emu/debug/debughlp.cpp
src/emu/debug/express.cpp
src/emu/debug/express.h
src/emu/distate.h

'tracesym' is intended to be a shorthand of 'tracelog', whereby the user doesn't have to specify a format string; the default format string is used

Created a new debugger command 'tracesym'

---

scripts/src/bus.lua
src/devices/bus/vme/vme_fccpu20.cpp
src/devices/bus/vme/vme_fccpu20.h
src/mame/drivers/fccpu20.cpp
src/mame/drivers/miniforce.cpp

I just moved code a round a bit, the previous fccpu20 driver is now a slot device and a new fccpu20 driver emulates just a 1 slot chassi that loads only that slot device. It will allow me to add graphical layout and let the CPU board show up as a single board computer etc, all of the benefits as a board driver. I think it is neat but let me know what you think before I merge it, I think I will do this to all VME CPU boards that has code that supports other VME boards unless there are major draw back of this approach.

Miniforce and fccpu20 slot device

---

src/mame/drivers/rainbow.cpp

Added info about 6 and 20 MB Corvus drives (and how to format / use them) under CP/M 86/80 version 1.
Al Kossow kindly provided driver source for Corvus on Lifeboat CPM 2.2, but this requires - more or less - skillful modification to adapt to DEC's CP/M 86/80 2.x.
Two obstacles: a specific patch address must be determined (RWMLOC & RWMDTA in old source from Maslin), and LDCOPY seems to be hard coded in version 2.x (will not write arbitrary loaders)...
Perhaps one of the few remaining CP/M experts can have a look?
TRS-80 model II uses the same type H drives, by the way...
http://www.retroarchive.org/maslin/disks/dec/
http://www.retroarchive.org/maslin/disks/dec/drcdutil.zip
bitsavers.org/bits/Corvus/Floppies/corvus1.tar

DEC Rainbow: add info how to use 6 and 20 MB Corvus drives

---

hash/neogeo.xml
src/mame/drivers/neodriv.hxx
src/mame/mame.lst

The King of Fighters '99 - Millennium Battle (Korean release) [Brian Hargrove]
(this is an original encrypted release with SMA-KB protection / encryption chip, old kof99k set is now kof99ka and marked as non-encrypted program)

new clones

---

src/devices/bus/ieee488/hp9895.cpp
src/devices/bus/ieee488/hp9895.h
src/devices/machine/fdc_pll.cpp
src/devices/machine/fdc_pll.h
src/devices/machine/phi.cpp

Hi,
this PR is for my emulator of HP9895A dual floppy disk drive. I think that, as far the drive emulator is concerned, it's done. The next step will be the support for a disk image format.
At the moment it only supports the MFI format. I'm attaching an image for a completely empty & unformatted DSDD disk if you want to try it.
The system should be started with the following command line to enable the 9895 emulator.
```
hp9845b -slot0 98034_hpib -slot0:98034_hpib:ieee_dev hp9895 -optrom1 massd -flop1 test9895_virgo.mfi
```
This command line sets this chain up: HP9845B<->98034 module<->HPIB bus<->HP9895 and loads the blank image in the 1st drive.
The defaults are as follows:
98034 select code = 7
98034 HPIB address = 21
98034 is HPIB system controller
9895 HPIB address = 0
Once 9845 has …

HP9895 floppy drive

---

src/devices/machine/6522via.cpp

A couple of fixes to the VIA6522 shift register as we've scrutinized the datasheet. There are still details not emulated perfectly but at least we haev a 50/50 duty cycle now required to interact with a netlist device and we try to do things on the right flank. There is also a fix for spurious timer events that occured when changing shifter mode between internal and external clock. This is abused by the mac128k rom set for instance, see attached regression test logs for details. I am still curious what Tafoid will find if anything :)
[via6255regressions.txt](https://github.com/mamedev/mame/files/743586/via6255regressions.txt)

Via6522 fixes

---

src/mame/drivers/gcpinbal.cpp
src/mame/includes/gcpinbal.h
src/mame/video/gcpinbal.cpp

- Break up the bogus IOC structure and use 8-bit handlers where appropriate. This fixes a music playback glitch due to the old handler's failure to take byte mirroring into account.
- Improve OKI M6295 sounds by using correct bit for banking

gcpinbal: Modernization and sound improvements

---

src/devices/cpu/t11/t11ops.hxx

per T11_UsersMan.pdf, p. 6-62 and B-11

T11: HALT opcode jumps to fixed restart address with PSW=0340 (nw)

---

src/mame/drivers/hp9845.cpp
src/mame/layout/hp9845b.lay

Hi,
this PR implements the correct aspect ratios of text & graphic modes of HP9845B and their relative sizes on the screen.
See my post about this: [MAME forum](http://forums.bannister.org/ubbthreads.php?ubb=showflat&Number=108376)
Thanks.
--F.Ulivi

hp9845: implemented correct aspect of alpha & graphic video modes

---

hash/n64dd.xml
hash/saturn.xml

added ram8 and ram32 cartridges to saturn.xml where needed (infos taken from segaretro.org).
not sure how to handle optional ram extension, maybe with info usage?
also converted the two info usage in n64dd.xml to their respective cartridges.
thanks to AJR for incorporation sharedfeat requirements directly into MAME.

added sharedfeat requirements to n64dd.xml and saturn.xml (nw)

---

src/devices/video/mc6845.cpp

The device should not try to scan-out more lines than has been programmed into the 'visible' register.

Fix scanout of mc6845

---

src/frontend/mame/clifront.cpp

The reason is that the LUA console, HTTP server and other features relied on the command line arguments being "pre-parsed".  Part of the softlist cleanup was to sanitize where command line parsing occurs.  This change moves the setup of the LUA console (and other capabilities such as the HTTP server) to the correct place in the new order.

The recent softlist cleanup broke -console; this fixes it

---

src/emu/main.h
src/frontend/mame/clifront.cpp
src/frontend/mame/clifront.h
src/frontend/mame/mame.cpp
src/frontend/mame/mameopts.cpp
src/frontend/mame/mameopts.h
src/lib/util/options.cpp
src/lib/util/options.h
src/osd/windows/main.cpp
src/osd/windows/winmain.cpp

This change also changes around how command line arguments are passed around; specifically I changed argc/argv to be std::vector<std::string>
Note this is not passed around 'const', the reason being that the command line processing will now "eat" the vector

Fixed an issue where device options (e.g. -cart) were reported as unknown when they actually worked

---

src/emu/machine.cpp
src/emu/main.h
src/frontend/mame/mame.cpp
src/frontend/mame/mame.h

Moved the initial cheat file loading to later in the start up process after the software list cart_rom has been loaded. Otherwise it will not load the cheats as the cart_rom will not exist.
Eg. mame coleco qbert

Fix softwarelist cart memory cheats

---

src/devices/imagedev/flopdrv.cpp

makes certain wip code actually step correctly.

legacy floppy: unbreak floppy_stp_w

---

src/devices/bus/vme/vme_fcisio.cpp

Enabling the serial port revealed a segfault when using more the 2 serial terminals from a slot device something that works just fine with the fccpu30 driver, which is not a slot device yet. 
See reported issue here: https://github.com/mamedev/mame/issues/2109

fcisio: layout added and RS232 configured for all 8 serial ports

---

hash/nes.xml

- nes: added Magic Kid GooGoo, named as mkgoogoo
- nes: assigned UxROM to dancekar
- nes: fixed names of some subor carts
- nes: marked skaraok as unknown for now
The alternate Chinese/Russian names I have put into the commits come from the NESBBS listings and cartridge labels.

Softlist additions and corrections

---

src/devices/bus/hp9845_io/98034.cpp
src/devices/bus/hp9845_io/98034.h
src/devices/bus/hp9845_io/98035.cpp
src/devices/bus/hp9845_io/98035.h
src/devices/bus/hp9845_io/hp9845_io.cpp
src/devices/bus/hp9845_io/hp9845_io.h
src/devices/cpu/nanoprocessor/nanoprocessor.cpp
src/devices/machine/fdc_pll.cpp
src/mame/drivers/hp9845.cpp
src/mame/includes/hp9845.h

Hi,
this hefty set of commits implements the HP-9845C driver.
This system was the color version of the 9845 range of machines.
The driver was written together with Ansgar Kueckes who did a lot of reverse engineering of the video and lightpen sub-systems. 
The best way to try the emulator is running the DEMO tape.
Quick instructions:
* Load the colorgfx optional ROM (-rom1 colorgfx)
* Load the demo1.hti into cassette drive (-magt demo1.hti)
* Optionally, enable lightpen emulation (-lightgun -lightgun_device mouse)
* Map the k8..k15 keys, they are not mapped by default and they are needed for menu navigation (see below).
* Start the demo with: LOAD "AUTOST",1 <EXECUTE>
* Be patient, demo takes a while to load..
* Once the system asks for the type of printer paper, load the demo2.hti image …

HP9845C driver

---

hash/ibm5170.xml

I dumped a lot of floppies recently, and these are the first ones that I create a pull-request for
All floppies were dumped with a KryoFlux and converted to img.
The *.img files as well as the KryoFlux stream dumps, KF logs and scans of the media are available on my archive.org account (archive.org/details/@ dark-star)
If you prefer a different submission method for the *.img files let me know

Some new entries for the IBM5170 softlist

---

src/frontend/mame/mameopts.cpp
src/frontend/mame/mameopts.h

Tafoid brought to my attention a recent regression caused by my softlist changes.  Specifically, this failed:
mame odyssey2 -cart1 voice -cart2 bees
The reason is that the recent refactoring caused some critical softlist logic to be bypassed.  Essentially device_slot_interface::get_default_card_software() provides a technique for devices to inspect softlists and select slot options to be specified.  In the case above, the selection of the "voice" software list item in the first cartridge slot requires get_default_card_software() to be called to specify the o2_voice slot device, which in turn adds the second cartridge slot.  Skipping this caused '-cart2' to stop being recognized.
This is an attempt to fix the problem.  In some ways, this doesn't go far enough - the astute observer will …

Preliminary attempt to fix regression caused by poor understanding of get_default_card_software()

---

hash/ibm5170.xml

Follow-up for my PR #2137 with cleaned/fixed disk images.
@DopefishJustin you should already have the new images

ibm5170 softlist: replace win31g floppy images with cleaned/fixed ones

---

src/devices/sound/ay8910.cpp
src/devices/sound/ay8910.h

Overrided device method to support changing clock frequencies in the ay8910.

Allow clock frequency changes in ay8910.

---

src/mame/video/gime.cpp
src/mame/video/gime.h

The normal way to acknowledge a GIME interrupt is by reading from $FF92/3.  However, the act of disabling interrupts by writing to the same registers will also do the trick, and we were not emulating this technique.
Thanks to Glen Hewlett and Tim Lindner for helping to identify this problem

[CoCo 3]  Fixed an issue clearing interrupts on the GIME implementation

---

src/emu/diimage.h
src/emu/softlist_dev.cpp
src/emu/softlist_dev.h
src/frontend/mame/mameopts.cpp

Pernod found a regression introduced in the 0.183 softlist refactoring whereby multi-part softlist items would not distribute to multiple slots.  The problem was that the old code was relying on the image slots being loaded into the core.  This is not the way the new system works, so I've added a hook into software_list_device::find_mountable_image() that allows the new approach to work.

Fixed regression when loading multipart softlists

---

hash/nes.xml
src/devices/bus/nes/subor.cpp
src/devices/bus/nes/subor.h

_These need to be critically merged before the new MAME version. This includes some important fixes in the nes softlist that repair some of the crap jobs I did on a lack of sleep, doing some big, big whoopsies with me removing WRAM defines by accident that prevented a few educational titles from booting or working correctly._
Misc changes: Fixed copyrights on pirate.cpp code in subor.cpp, and a few more alternate names/serials and publishers were added as well to some educational carts on the NES softlist.
Some BWRAM defines were replaced with WRAM defines due to the said carts in this commit not actually needing battery-backed WRAM to function. They will peform just fine with plain WRAM since none of them have any save functions, nor their iNES dumps describe any battery extensions …

Last minute corrections

---

src/mame/drivers/h19.cpp
src/mame/mame.lst

Adds the AM_MIRROR settings which the Super19 ROM relied on.  The CRTC ports and the videoram memory were the only ones I saw, which was REQUIRED to get it working, but figured I'd update all the memory and ports to properly reflect the real board in case the ROM used it in other code paths I hadn't tested.
Also added preliminary definitions for the SuperSet ROM, not sure if the current AM_MIRROR options allows a way to properly define how it is configured. My initial attempts to define it, caused run-time crashes. The ROM chip is a 32K chip, of which 16K is used. But the valid data is in the 2nd and 4th 8K blocks of the chip, not the 1st and 3rd. So it would either error with 'mirror touching a set bit' or have the memory reflect the invalid parts of the ROM chip.

Fix Super19 version of Heath H19.

---

src/devices/cpu/i386/i386.cpp
src/devices/cpu/i386/i386ops.hxx
src/devices/cpu/i386/pentops.hxx
src/devices/video/pc_vga.cpp
src/devices/video/pc_vga.h

- VGA card now saves vga.dac to the state, as the MAME palette is clobbered periodically with data from here. Changed the type of vga.dac.colour to a flat uint8_t array seeing as save_item isn't struct-friendly. Fixes Liero.
- Saved more VGA flags, including vga.miscellaneous_output, which despite the vague name is needed for reading from the ports.
- Fixed an enum range check miss.
- Saved more i386 flags required for 32-bit save states. Fixes Jump 'n Bump.

i386/pc_vga: save state fixes

---

src/emu/debug/debugcpu.cpp

Reverts mamedev/mame#2184
Breaks side_effects_disabled() everywhere.  Think about the lifetime of the dis object.

Revert "Fixed writes to decrypted opcode memory"

---

src/devices/machine/latch8.cpp
src/devices/machine/latch8.h
src/devices/sound/discrete.h
src/mame/audio/dkong.cpp
src/mame/drivers/dkong.cpp
src/mame/includes/dkong.h
src/mame/video/dkong.cpp

- Eliminate the AM_LATCH8_XXX address map macros. The normal DEVREAD/DEVWRITE ought to be good enough.
- Eliminate the "offset" specifications from latch8_device. This was used mostly to funnel outputs to discrete_device, which now has a templated write_line handler. (Inputs can use MCFG_DEVCB_RSHIFT instead.)
- Organize latch8_device's callbacks as arrays of devcb_readline/devcb_writeline, helping simplifying code greatly.
- Change latch8_device::bit[0-7]_(q_)?r to be proper line read handlers. This requires two extra READ8 handlers in audio/dkong.cpp, but memory-mapping for the MCS-48 T0 and T1 lines is totally artificial anyway.
- Comment out an assert that now tends to fail due to buggy AM_MIRROR behavior.

latch8, discrete: Major device cleanup (nw)

---

src/devices/bus/isa/sblaster.cpp
src/devices/bus/isa/sblaster.h
src/devices/sound/262intf.cpp
src/devices/sound/262intf.h
src/devices/sound/ymf262.cpp
src/devices/sound/ymf262.h

- Sound Blaster now saves DSP registers to the state
- Fixed an issue where Sound Blaster DAC would create loud popping noises before first use (the uninitialized DAC would hold at -1, which during a dropped frame would step to 0?)
- Adlib chip now saves channel/slot info to the state. Part of that involved saving the slot connection routes in a non-raw pointer format so they can be reconstituted at runtime. Also, pointer validity checks!

sblaster/ymf262: save state fixes

---

src/devices/bus/coco/coco_fdc.h
src/devices/bus/coco/coco_multi.cpp
src/devices/bus/coco/coco_multi.h
src/devices/bus/coco/coco_pak.cpp
src/devices/bus/coco/coco_t4426.cpp
src/devices/bus/coco/cococart.cpp
src/devices/bus/coco/cococart.h
src/mame/machine/coco.cpp

This is an attempt to make how the various signals on the CoCo cartridge slot (CART, NMI, HALT) a bit more standardized and less ad hoc, especially with the practice of Program Paks tying the CART line to Q.  This should fix some outstanding bugs in how these signals were passed around when using the CoCo Multi-Pak interface.

[CoCo] Further cleanups in CoCo cartridge slot signal handling

---

scripts/target/mame/arcade.lua
src/mame/audio/vicdual-97271p.cpp
src/mame/audio/vicdual-97271p.h
src/mame/drivers/vicdual.cpp
src/mame/includes/vicdual.h
src/mame/video/vicdual-97269pb.cpp
src/mame/video/vicdual-97269pb.h
src/mame/video/vicdual.cpp

*EDIT*
this is a followup to https://github.com/mamedev/mame/pull/2092 and https://github.com/mamedev/mame/pull/2124
*EDIT*
confirmed PR-33 and PR-34 on the nsub motherboard. type is MMI 6331 (32*8)
added the 97269-P-B daughterboard.
not complete - gradient is still a simulation, but now uses the PROMs
starfield is still completely missing.
reference image: http://images.arianchen.de/2017-01/030320171775.jpg
wiring notes: http://files.arianchen.de/nsub/97269-P-B.txt
the 1024*4 proms are are one nybble-per-byte with the upper 4 bits being zero
PROMs: http://files.arianchen.de/nsub/s97269pb.zip

vicdual: add 97269-P-B and 97271-P daughterboards for nsub

---

hash/ibm5170.xml

- Borland Quattro Pro 3.0 (German)
- Borland Quattro Pro 5.0 (German)
- Borland Turbo Basic 1.0 (German)
- Borland Turbo Pascal 4.0
- Borland Turbo Pascal 6.01 (German)
IMG files have been uplaoded to @DopefishJustin , KryoFlux dumps and floppy scans are available on [my archive.org page](https://archive.org/details/@dark-star)

ibm5170 softlist additions

---

src/lib/util/options.cpp

Examples:  'mame -whatever nes' would previously be reported as "Unrecognized argument: nes"

Fixed issue that could cause bogus arguments to be reported incorrectly

---

src/frontend/mame/ui/swlist.cpp

Fixed a bug that caused "Switch Item Ordering" in the software list menu to dupe entries

---

src/mame/audio/vicdual-97271p.cpp

fix a copy and paste error. (2x warning sound)
this enables the missing long explosion sound.

vicdual: fix missing explosion sound on n-sub (nw)

---

src/emu/device.h
src/emu/diimage.cpp
src/emu/diimage.h
src/emu/dislot.cpp
src/emu/dislot.h
src/emu/emuopts.cpp
src/emu/emuopts.h
src/emu/image.cpp
src/emu/mconfig.cpp
src/emu/romload.cpp
src/frontend/mame/mame.cpp
src/frontend/mame/mameopts.cpp
src/frontend/mame/mameopts.h
src/frontend/mame/ui/imgcntrl.cpp
src/frontend/mame/ui/info.cpp
src/frontend/mame/ui/miscmenu.cpp
src/frontend/mame/ui/slotopt.cpp

Prior to this change, options for images and slots were stored in the emu_options collection.  Anything that might restart the emulation (such as slot changes and images that reset on load) had to manipulate the emu_options structure directly.  The dynamic nature of images and slots meant that some elaborate conventions for setting up this collection had to be understood by clients.
After this change, emu_options has two new members (image_options and slot_options) that expose image and slot selections via an std::map.  Anything that changes images or slots in a fashion that needs to persist across sessions needs to modify these data structures.  Additionally, some of the hairly logic (e.g. - get_default_card_software) now records its data here rather than trying to subvert the …

Refactoring in response to MT#6531

---

src/lib/util/coreutil.cpp
src/lib/util/coreutil.h
src/lib/util/timeconv.cpp
src/lib/util/timeconv.h
src/tools/imgtool/modules/macutil.cpp

Also:
- Converted the NTFS filetime code to use util::arbitrary_clock
- Converted the Mac datetime code to use util::arbitrary_clock
This is in preparation for a bigger change to Imgtool where I eliminate usage of time_t
While I'm (reasonably) confident in the logic, I feel that it is a virtual certainty that I'm violating some norm of std::chrono or some other C++-ism.  Looking forward to Vas reviewing this.

Introduced an 'util::arbitrary_clock' template class, to represent a clock that "knows" when the epoch starts

---

src/emu/validity.cpp

This comes from a regression reported by Tafoid whereby the following command line:
mame coco wildcat
Would report the following error (which was not really fatal because it happened within validation):
Driver t4426 (file coco12.cpp): 1 errors, 0 warnings
Errors:
Fatal error Unknown slot option 'pak' in slot 'ext'
My changes to option processing changed emu_options to put image and slot options in their own arrays, and I expect those image/slot options to be pertinent to the active driver.  However, driver validation was passing the emu_options associated with the main emulation  to validation specific maching_config for other drivers.  This changes validate_one() to always use a fresh emu_options with each individual validation.

Changed the validity checks to have its own emu_options

---

src/emu/emuopts.cpp
src/emu/emuopts.h
src/frontend/mame/mameopts.cpp
src/frontend/mame/mameopts.h
src/lib/util/options.cpp
src/lib/util/options.h

This fix really doesn't go far enough.  I added hooks so that options specified at the command line can also be responded to when parsed from INI files, but in the long run much of the logic that is currently in mame_options should go into emu_options so that when an option is specified, all of the wacko logic around slot/image specification "just works" because it is encapsulated within emu_options.
We have a release 11 days away; I want to be in stabilization mode.

Fixes issues specifying image/slot options fron INI files (reported by Robbbert)

---

src/emu/validity.cpp
src/emu/validity.h

This seems to solve the performance problems introduced by PR#2221 while keeping with that PR's goals of not using the "runtime" emu_options for purposes of validation.

Changed validity_checker to keep a fresh emu_options for validation purposes

---

src/emu/diimage.h
src/emu/emuopts.cpp
src/emu/emuopts.h
src/emu/image.cpp
src/emu/mconfig.cpp
src/frontend/mame/mameopts.cpp
src/lib/util/options.cpp
src/lib/util/options.h

This should address outstanding concerns with PR#2231.  I'm trying to turn emu_options into a self contained structure that encapsulates behaviors related to options, including the gymnastics pertaining to image/slot loading and interactions with get_default_card_software() and "just works".
When the MAME 0.186 development cycle starts up, I hope to take this further.  I want to make core_options::entry an abstract base class so that the entries associated with image options and slot options can derive from it.  This will eliminate the current need for emu_options to directly expose maps for image and slot options.
For now, I'm in stabilization mode, and I hope to get things working for a stable 0.185 release.

More options refactoring

---

src/devices/video/v9938.h
src/emu/dipalette.cpp
src/emu/dipalette.h
src/emu/emupal.cpp
src/emu/emupal.h

* Revert entries(), indirect_entries(), shadows_enabled() and hilights_enabled() to return the configuration parameters instead of accessing the live state. The thought behind the implementation change was that palette devices could potentially determine the number of entries from the sizes of devfind objects. The regressions caused by this have been worked around, but it was probably a bad idea in the first place.
* Zero-entry palettes are no longer valid. The code that tried to support them was basically left over from when every running machine had a single global palette.

dipalette: A return to sanity (nw)

---

src/devices/bus/neogeo/slot.h

The NeoGeo driver exposes a number of different memory regions as vectors.  Accessing the pointers was done through a '&vector[0]' pattern.  This caused problems when the region was size zero; I changed the code to return null pointers in these scenarios.
This was reported by Robbbert in response to recent regressions (the command line was 'mame aes bjourney'), but it seems to be present in MAME 0.184.

Fixed out of bounds issues in NeoGeo memory access

---

src/frontend/mame/ui/info.cpp
src/frontend/mame/ui/ui.cpp

As a consequence of recent changes, we were not properly blocking the emulation from starting when a must_be_loaded() image had an unspecified image.

Fixed a regression in the mandatory image check

---

src/emu/emuopts.cpp

This is a hack; see commentary within the code.  I intend to fix this "for real" when emu_options become more self contained

Workaround for scenarios where both the command line and an INI specify an image option

---

src/devices/cpu/h8/h8.cpp
src/devices/cpu/h8/h8.lst
src/devices/cpu/h8/h83002.cpp
src/devices/cpu/h8/h83002.h
src/devices/cpu/h8/h8_dma.cpp
src/devices/cpu/h8/h8_dma.h

Fixed h8 instruction eepmov.b (used r4h instead of r4l)
Added support for non-autorequest DMA (DREQ edge, DREQ level) in h8
Added support for H8/300H to h8_dma (previously only H8/300S supported)
Added DMA channels to H8/3002
Added RTMCSR register to H8/3002

Fixes and enhancement to H8/300H / H8/3002 

---

src/osd/windows/winmain.cpp

"yiqp" was used for WINOPTION_YIQ_PVALUE and WINOPTION_YIQ_PHASE_COUNT

Disambiguated the WINOPTION_YIQ_PHASE_COUNT option

---

src/devices/machine/6522via.cpp
src/devices/machine/6522via.h

The regression of the Mac adb bus support caused me to refactor the shifter and I feel much better about this implementation as it got rid of ugly sub states and purely handles flanks now as opposed to a mix of flanks and cycles before. In my regression tests I noticed that some systems seems to work a bit better and of course both Mac adb bus and the Prodigy. Let me know any problems asap

via6522 shifter support for external clock

---

src/emu/diimage.cpp
src/emu/diimage.h

This was not guaranteed to cause a problem; the specific issue here was reported by mr_gw in the context of the CoCo, and the proximate issue (hanging) was in CoCo-specific code.   That said, this could cause problems elsewhere.
This was MT#6560

Fixed an issue that could cause problems when loading reset_on_load devices (like cartridges) from softlists at runtime

---

src/tools/imgtool/imgtool.cpp
src/tools/imgtool/imgtool.h

Windows doesn't like mixing std::wc[out|err] and printf()

[Imgtool] Cleanups to validity code, and transitioned to std::wcerr

---

src/mame/video/starshp1.cpp

A very old (> 10 years?) hack seemed to clean up the way the ships explode in Atari Starship 1.  But this is different than the actual game behavior.  See this video of the way the ships behave when they are hit: https://youtu.be/-crXVuoKlL4?t=573  I'm pretty sure this is the way it used to work when I originally coded it from the schematics.  I have removed the hack and modified the comments in the code in video/starshp1.cpp

Remove starshp1 hack to restore correct behavior

---

src/tools/imgtool/imghd.cpp
src/tools/imgtool/imghd.h
src/tools/imgtool/main.cpp
src/tools/imgtool/stream.cpp
src/tools/imgtool/stream.h

Two independent issues reported under MT#6576
- The 'listformats' command was broken
- imghd.cpp (the Imgtool <==> CHD HD bridge) was pretty much completely broken (more work is needed here)

[Imgtool] Fix to MT#6576

---

src/lib/util/chd.cpp

Writing into an std::string is now legal with C++11

Minor improvement to CHD metadata loading

---

src/emu/tilemap.cpp
src/emu/tilemap.h
src/frontend/mame/ui/viewgfx.cpp

This allows you to select different tilemap categories in the
built-in tilemap viewer. The default is to render all categories
(same as before), but you can select to render only a specific
tilemap category with the PAGE_UP and PAGE_DOWN keys.

UI: Add the ability to select different tilemap categories

---

src/emu/dislot.h
src/frontend/mame/ui/slotopt.cpp
src/frontend/mame/ui/slotopt.h

Did the following:
1.  Polished up residual traces of this code's pre-C++ heritage
2.  Moved completely private code to an anonymous namespace
3.  Created device_slot_interface::slot_name() to wrap the pattern of taking the tag and removing the initial colon

Cleanups to src/frontend/mame/ui/slotopt.[cpp|h]

---

src/mame/drivers/xbox.cpp

The MCPX 1.0 ROM had the wrong checksums. The checksums included
were from a known bad copy of the ROM.

Replaced the checksums with correct checksums.

---

src/frontend/mame/clifront.cpp
src/frontend/mame/clifront.h
src/lib/util/options.cpp
src/lib/util/options.h

Made the following changes:
1.  Fixed a bug where resolved slot/image options would choke -romident (reproducible in MAME 0.185 with 'mame64 -romident coco.zip')
2.  'mame64 -romident' no longer crashes (though it doesn't do anything useful)
3.  Changed the aux verb functions to take 'const std::string &'

Bug fix to -romident and aux verb cleanup

---

src/frontend/mame/mameopts.cpp
src/frontend/mame/mameopts.h

eientei95 reported an error where the hashpath specified in INI files was not being honored in softlist evaluation.  This is a change to preprocess INI files for the sole purpose of finding the hashpath prior to evaluating softlists.

Adding hack to fish hashpath option out of INI files prior to softlist evaluation

---

src/mame/drivers/mitchell.cpp
src/mame/includes/mitchell.h

this must have been broken for a while, it was assuming that MAME used the CPU region as RAM for 8-bit CPUs and that hasn't been an valid for a long time. (15+ years?)  As a result data wasn't being saved / restored properly at all.
Corrado Tomaselli noticed this when playing with his Super Pang PCB, after replacing a hacked set with a proper original + Kabuki battery he noticed the game no longer showed '8Mhz Original Board' on bootup.  This is because the battery also backs up at least part of main RAM, and it only displays that string the first time it initializes main ram.
The previous MAME code only tried to save 0x80 bytes of the RAM, with a different location for some games.  I've left that behavior commented in case it turns out the original does only save that area, but it seems …

fix mitchell.cpp nvram saving

---

src/mame/drivers/mitchell.cpp
src/mame/includes/mitchell.h

since after the last submission we're now saving the whole ram and don't have the provisional code to go back we can just use the built in finder rather than set_base

mitchell.cpp : just use the finder method for nvram

---

src/emu/video.cpp

Do not update m_average_oversleep if we overslept too much.
This is still a partial fix, more investigation is needed when the system time jumps backward.

Fix video_manager::throttle_until_ticks (#2309)

---

src/mame/drivers/system1.cpp
src/mame/drivers/taito_f2.cpp
src/mame/mame.lst

new clones
Wonder Boy (set 6, 315-5179) [Mathieu Patard]
he also dumped a Football Champ board only to find the content was the same despite using a different Taito number for the rom that determines the region, so it's likely one of them is incorrect *or* because in this case a Dipswitch determines the title, Taito might have actually shipped the same rom with different numbers (seems less likely tho, because the region byte also affects coinage etc.)  this has been documented and the longname for the set updated to reflect the switchable title.
Also while I was looking there I made euroch92 not a clone as it follows the 'sf2ce' rule, it's a re-released game with small updates, not an identical product, it likely has it's own Taito product code (although we don't currently have the …

clones from Mathieu Patard

---

src/devices/imagedev/floppy.cpp

Hi,
this is the 2nd attempt to fix the bug that sometimes caused segfaults when emulating hp9895 drive. My previous attempt was in PR #2319.
I think this addresses the problem better. It was due to a rounding error in floppy_image_device::find_position function that overflowed the "sacred" 2E+8 limit.
Thanks.
--F.Ulivi

Fix for a segfault when emulating HP9895 drive (take 2)

---

hash/nes.xml
scripts/src/video.lua
scripts/target/mame/mess.lua
src/devices/cpu/m6502/n2a03.cpp
src/devices/cpu/m6502/n2a03.h
src/devices/sound/nes_apu.cpp
src/devices/sound/nes_apu.h
src/devices/sound/nes_defs.h
src/devices/video/ppu2c0x.cpp
src/devices/video/ppu2c0x.h
src/devices/video/ppu2c0x_vt.cpp
src/devices/video/ppu2c0x_vt.h
src/mame/drivers/nes_vt.cpp
src/mame/includes/nes.h
src/mame/machine/nes.cpp
src/mame/mame.lst

VT03 is a clone of the NES hardware but with extended capabilities such as 4bpp tiles, an extended palette and it's own banking schemes.  The VT family of chips are used by the vast majority of recent 'famiclone' systems, often standalone devices with a number of built in games and no cartridge slot.  Later models add 8bpp modes and even more complex banking schemes.
This allows derived classes to extend the PPU functionality to support the basic modes.
mc_dgear has been moved from nes.xml to this driver (as it's not something that could actually run on a NES) and several other dumps from what should be VT based machines have been added, although some use later models.  cybar120 boots but you can see it appears to need an 8bpp mode.  Most of the others don't boot yet.
for mc_dgear …

preliminary steps for basic VT03 (NES clone) support

---

src/devices/bus/a7800/a78_slot.cpp
src/devices/bus/a7800/a78_slot.h
src/devices/bus/nes/nes_slot.cpp
src/devices/bus/nes/nes_slot.h
src/emu/diimage.cpp
src/emu/diimage.h

The following is illegal, even if no elements in the pointer are accessed:
std::vector<my_struct> my_vec(0);	// create an empty std::vector
my_struct *ptr = &my_vec[0];
While this is a degenerate scenario, this should be fixed

Fixed issue when the hash length is zero

---

src/devices/machine/ram.cpp
src/devices/machine/ram.h

There was a longstanding bug where '-ramsize 16kfoo' would be treated as '-ramsize 16k'

[Ram Device] Better detection of bad -ramsize strings, move some private code to anonymous namespace

---

src/mame/drivers/nes_vt.cpp
src/mame/mame.lst

- Rename "Cyber Arcade 120-in-1" to "Defender M2500P 120-in-1". [According to the dumper](http://s4.zetaboards.com/PGC_Forums/single/?p=8143495&t=9029126), this would be the correct name for this machine.
- Add vdogdeme, an earlier version of vdogdemo.

Fix incorrectly labeled machine and add another

---

src/mame/drivers/littlerb.cpp
src/mame/machine/inder_vid.cpp

(Main CPU is more likely 8MHz than 12Mhz)
also use a hack to overclock the TMS to 120% so that the map screen renders properly, points at possible timing errors in the core?

use more likely clocks for littlerb based on PCB XTALS 

---

src/devices/bus/coco/cococart.h
src/lib/formats/jvc_dsk.cpp

And also included an additional #include to let the build system know about the new SDF format.

Fixed JVC disk format to correctly recognize 2 sided disks.

---

src/devices/bus/coco/coco_fdc.h
src/devices/bus/coco/coco_multi.cpp
src/devices/bus/coco/coco_pak.cpp
src/devices/bus/coco/coco_t4426.cpp
src/devices/bus/coco/cococart.cpp
src/devices/bus/coco/cococart.h

This should be considered part of the CoCo cartridge overhaul.  Vas (correctly) suggested that dynamic_casts should be done in interface_config_complete() to avoid calling them at runtime.  This was actually happening inconsistently in the various implementations, and consolidating them is a good cleanup.

[CoCo] Changed device_cococart_interface implementations to do dynamic_casts at config completion

---

src/frontend/mame/ui/selgame.cpp

This bug could be reproduced with the following steps:
1.  Put 'nes' in 'Favorites'
2.  Launch 'nes'
3.  Choose something from the software menu and run the emulation
4.  Escape back  -- CRASH

Fixes a crash when returning to the front end when a system was launched from favorites

---

src/devices/bus/coco/coco_dcmodem.cpp
src/devices/bus/coco/coco_fdc.cpp
src/devices/bus/coco/coco_fdc.h
src/devices/bus/coco/coco_multi.cpp
src/devices/bus/coco/coco_orch90.cpp
src/devices/bus/coco/coco_pak.cpp
src/devices/bus/coco/coco_t4426.cpp
src/devices/bus/coco/cococart.cpp
src/devices/bus/coco/cococart.h
src/devices/bus/coco/dragon_fdc.cpp

- Removed now-extraneous cart_set_line() specific to the FDC code
- Added typedefs for line and line_value within device_cococart_interface()
- Moved private TIMER_* declarations to source file
- Added overload of set_line_value() that takes a 'bool' instead of 'line_value'

[CoCo] Follow up hygiene on CoCo cartridge slot refactoring

---

src/emu/debug/debugcpu.cpp

I've discovered a scenario where reading to the end of file seems to trigger the fail bit, in addition to the eof bit.  Because of this, I've changed the error message to display when we can't read from the stream, but the eof bit is _not_ set

Fixed an issue that could cause the debugger 'source' command to falsely display I/O error

---

src/osd/modules/sound/sdl_sound.cpp

The problem is most noticeable when you are saving state, and the
save takes a relatively long time, short period of audio gets played
repeatedly, which is usually unpleasant.
I found out it's caused by sdl_sound::sdl_callback not fill the audio
buffer with silence when underflow occurs. According to
https://wiki.libsdl.org/SDL_AudioSpec, if there's nothing to play,
the callback should fill the buffer with silence.
I tested this change and the problem is gone.

Fix sound_sdl::sdl_callback, fill buffer with silence when underflow.

---

src/emu/image.cpp

Report from Robert:
Start mame sorcerer, then enter the slots menu, empty the rs232 slot, then choose Reset. It crashes with an access violation.

Fixed sorcerer unmount issue reported by Robert

---

src/mame/drivers/m62.cpp
src/mame/includes/m62.h
src/mame/video/m62.cpp

I've split the massive PROM blocks up into something more modern looking (the single PROM region with all PROMs crammed into it is an old MAME thing from when only one PROM region was allowed)  I've also made use of multipe palettes and gfxdecode structures (required using rgb32 to draw to)
As the boards are quite modular this seems to make sense to me, the palette for the sprites and the sprite decode + sprite palette decode is the same across all games while the rest of the hardware changes a bit.  This should allow us to step closer to converting the various boards into devices and piecing them together more logically.

m62 proposed cleanups.

---

docs/source/initialsetup/compilingmame.rst

DNF is now preferred package manager. alsa-lib-devel is also required (not mentioned in the current docs)

Updated Fedora instructions

---

docs/source/commandline/commandline-all.rst

Include -output and it's available options in documentation.

Include -output option in documentation

---

scripts/src/cpu.lua
scripts/target/mame/mess.lua
src/devices/cpu/capricorn/capricorn.cpp
src/devices/cpu/capricorn/capricorn.h
src/devices/cpu/capricorn/capricorn_dasm.cpp
src/mame/drivers/hp80.cpp
src/mame/mame.lst
src/mame/mess.flt
src/tools/unidasm.cpp

Hi,
this commit is the start of my work on emulating the HP80 series computers.
There are already a couple of stand-alone emulators for this series around, but none in MAME.
This is WIP, so there are a lot of things that are not emulated yet.
What works:
- HP85A machine with 16K of RAM
- Capricorn CPU works
- Keyboard works (with minor issues)
- CRT text / graphics modes work (correct speed is not emulated yet so service ROM complaints)
- BASIC is usable
What is missing (and I'll have hopefully working soon):
- HW timers
- Beeper
- Integral printer
- DC100 cassette drive
- Extension ROMs
- I/O modules (especially the HPIB interface so that we can hook up floppy drives)
- Other models in the family (e.g. HP86)
Just a quick BASIC program to test:
```
10 FOR I=1 TO 10 @ DISP TAB(I);"Hello …
```

Begin of HP80 emulation

---

scripts/target/mame/mess.lua
src/devices/cpu/clipper/clipperd.cpp
src/mame/drivers/interpro.cpp
src/mame/includes/interpro.h
src/mame/machine/interpro_ioga.cpp
src/mame/machine/interpro_ioga.h

Serial DMA is the main change, now the driver gets a "Booting system" message during operating system rebuild (but hangs soon after). Also:
* switch to ncr53c94 (older models use 53c90a, newer use 53c94)
* initial Ethernet preparation
* timer-based DMA (per discussion with @galibert, to be optimised later)
* some C++'ifying fixes to the disassembler

interpro: serial dma is working

---

src/mame/drivers/dec8.cpp
src/mame/includes/dec8.h

use Caps0ff dump for srdarwin
handcraft MCU rom for srdarwinj like was done for other games in the driver so the old sim can be killed off, marked as BAD_DUMP
seems stable, although I had to boost the interleave.
NOTE, this game has never been emulated correctly - there was the following comment
---------
The table below is hopefully correct thanks to Jose Miguel Morales Farreras,
but Boss #6 is uncomfirmed as correct.
if (m_i8751_value == 0x8000) m_i8751_return = 0xf580 +  0; /* Boss #1: Snake + Bees */
if (m_i8751_value == 0x8001) m_i8751_return = 0xf580 + 30; /* Boss #2: 4 Corners */
if (m_i8751_value == 0x8002) m_i8751_return = 0xf580 + 26; /* Boss #3: Clock */
if (m_i8751_value == 0x8003) m_i8751_return = 0xf580 +  2; /* Boss #4: Pyramid */
if (m_i8751_value == 0x8004) m_i8751_return …

use Caps0ff dump for srdarwin

---

scripts/resources/emscripten/emscripten_post.js
scripts/src/main.lua
src/emu/machine.cpp
src/emu/machine.h

Slightly rearranges the ```running_machine::run()``` function so that the Emscripten build can share the same codepath, allowing it to access the scheduler to process any save/load commands that may have been queued.

Fix save/load states in Emscripten build

---

hash/gameboy.xml
src/devices/bus/gameboy/gb_slot.cpp
src/devices/bus/gameboy/mbc.cpp

Miscellaneous Game Boy changes. Please use fast-forward merge to preserve the commit comments.
- Fixes an issue with a previous pull request where I forgot one MBC1 collection game.
- Fixes an issue with MMM01 emulation of ROMB0 switching (broken select ROM bank 0x00 at 0x4000-0x7FFF; not visible due to games behaving themselves)
- add Sachen 4B-003 that was dumped a little while ago to xml

Gameboy v8

---

scripts/resources/emscripten/emscripten_post.js
scripts/src/main.lua
src/emu/machine.cpp
src/emu/machine.h

This patch adds some additional static member functions and exports them to allow control of the running system via a Javascript API in the web builds.  Example:
```js
JSMESS.save('statename');
JSMESS.load('statename');
JSMESS.soft_reset();
JSMESS.hard_reset();
JSMESS.exit();
```

Export additional functions for Emscripten builds

---

src/devices/machine/wd2010.cpp

Better feedback on cylinder positions. Most checks contained in winchester test suite pass now (option 16 at  RX50DIAG.TD0 diskette), except subtest #4 - and few low level tests that require specially crafted manufacturer tracks (write test #1).  
Historical annotation: manufacturer info was hidden in last 4, 8 or 16 cylinders of a DEC RD5x hard disk, diagnostic area in the 4, 8 or 16 cylinders before, depending on the number of heads. At least manufacturer tracks used a format inaccessible to standard disk routines and thus were not writeable.

Improve WD2010 emulation

---

src/devices/cpu/mcs51/mcs51.cpp
src/mame/drivers/gaelco2.cpp
src/mame/drivers/thoop2.cpp
src/mame/includes/gaelco2.h
src/mame/includes/thoop2.h

A number of DS5002FP chips were dumped using the method published by Morten Shearman Kirkegaard and Peter Wilhelmsen as documented at
http://www.afdelingp.dk/files/articles/ds5002fp/ds5002fp.pdf
namely Touch and Go, World Rally 2, and TH Strikes Back
a 2nd verification pass is still needed on them from additional boards, as bad bits existed in World Rally 2 even prior to extraction (steering logic was broken but bad byte was identified and fixed as the code for that command handler was identical to World Rally 1) and TH Strikes Back is crashing at the first boss (could also be a CPU core issue)  Glass was also dumped, but at the time the data wasn't extracted, only the code, and the board has since died, so needs redoing.  Several other boards are currently being sent for dumping / …

A number of DS5002FP chips were dumped....  [Morten Shearman Kirkegaard,Peter Wilhelmsen, David Haywood]

---

scripts/target/mame/mess.lua
src/mame/drivers/tg100.cpp
src/mame/mame.lst
src/mame/mess.flt

TG100 [vampirefrog, superctr, bmos, Valley Bell]
This is a MIDI sound module, but this skeleton driver does not have anything like that included as the CPU (H8/520) is not emulated.
Sound chip is Yamaha YMW258-F. This is almost certainly identical to the MultiPCM chip used in the Sega arcade boards. 12-bit samples are used, which are not supported by the current multipcm.cpp core, but is supported by the OPL4 (ymf278b.cpp) which uses a similar sample format.

New not working machine

---

hash/sms.xml

- fix The Terminator versions by adding their on-cart RAM.
- add notes for games with SK-1100 keyboard support.
- correct Great Baseball (Euro, USA, Bra) release year (title screen as reference).
- correct Teddy Boy Blues (Jpn, Ep-MyCard, Prototype) interface type.
- correct Ghost House (Sega Card, Prototype) interface type.

sms.xml fixes [Enik Land]

---

src/devices/video/mc6847.cpp
src/devices/video/mc6847.h

On these systems, the "Semigraphics 6" mode (contrary to most literature) will display "stripes" for video bytes from $00-$7F.  This is because the INTEXT pin on the MC6847 VDG is set, but AS is not and there is no external ROM.
This was reported by Jim Gerrie:  https://www.youtube.com/watch?v=VmsWqdiwH2o

[MC6847] Fixed the "Semigraphics 6" mode on the CoCo/MC-10

---

src/devices/cpu/clipper/clipper.cpp

Fixes a long-standing bug with some interrupt handlers where the stack pointer is popped into itself.

clipper: popw fix (nw)

---

src/devices/video/sda5708.cpp
src/devices/video/sda5708.h
src/mame/drivers/dbox.cpp
src/mame/layout/sda5708.lay

This works enough to give some output improving the driver. Right now the driver hangs right after putting the BIOS version on the display and I have a film of the real hardware what texts should be put there when it works correctly so it is useful.
Ideally one would like the sda5708 device to offer a sub-layout element to the dbox driver layout to place on the right spot of the dbox-1 front. Maybe there is a way to do that I don't know about.

SDA5708 layout for dbox

---

scripts/src/osd/sdl_cfg.lua

The cflags will contain an include path ending in "SDL2", not just "SDL", and removing just the latter leaves a stray "2" on the end.

Fix include path with USE_LIBSDL on macOS

---

hash/gameboy.xml
src/devices/bus/gameboy/gb_slot.cpp
src/devices/bus/gameboy/gb_slot.h
src/devices/video/gb_lcd.cpp
src/devices/video/gb_lcd.h
src/mame/machine/gb.cpp

I noticed that there was an ugly SGB border hack in the Game Boy system. I looked at it and realized that the SGB VRAM transfer method was broken (even though it works for most games due to Nintendo's SGB SDK).
The SGB VRAM transfer is actually done through the display signals, so the contents have to be shown on screen. It's not really known if window and bg scroll take/attributes take effect or not, so somebody with actual hardware might need to investigate further. If that's the case, a possible redesign would be to make the PPU render to a frame buffer and use that frame for VRAM access and final rendering, but that would entail a big change and it's unclear if it wouldn't be easier to actually emulate the SGB on a SNES with a GB slot.
Anyway, the actual transfers work now as expected …

gameboy: fix SGB VRAM transfers

---

src/mame/drivers/galaxia.cpp

The present S2636 core has been rewritten more than a year ago by Vas to adapt the tone frequency from the refresh rate, and this made me realize that my speed fixes for galaxia.cpp were incorrect.

revert the speed fix in Galaxia/Astro Wars that caused all sets to sound wrong

---

src/mame/drivers/rainbow.cpp

Incorporate change from Z80DART to Z80SIO proposed by Edstrom. Also make UCSD Pascal boot again.

Rainbow-100: use Z80SIO instead of Z80DART; make UCSD Pascal boot again

---

src/mame/drivers/toaplan2.cpp
src/mame/includes/toaplan2.h

This adds  HD647180X MCU dumps to Whoopee and Ghox, allowing for sound emulation in both of them. It also fixes the high score table background in Ghox, which was also MCU related [Team Caps0ff]

add HD647180X MCU dumps to Whoopee and Ghox  [Team Caps0ff]

---

src/mame/drivers/pgm.cpp
src/mame/mame.lst

DoDonPachi III (World, 2002.05.15 Master Ver) [neohyphengeo productions]
note, 'new parent' as technically it's the newest non-Japan set (actually the only non-Japan set) and is actually newer than the original Japanese release (but older than Black Label)  Some may disagree with this designation but it follows 'MAME standard'

new WORKING clones added:  DoDonPachi III (World, 2002.05.15 Master Ver) [neohyphengeo productions]

---

hash/nes.xml

I've been extended the information in the NES game list with some games I own. Although I have kept the dates in the game list, they vary in my games, so they may need to be changed:
- [Super Mario Bros.](http://imgur.com/a/5enCg): The date in [my cart's PCB](http://imgur.com/zKCDZNc) is 1986 instead of 1987.
- [Super Mario Bros. 2](http://imgur.com/a/S919p): The date in [my cart's PCB](http://imgur.com/7la09k2) is 1988 instead of 1989.
- [Trog!](http://imgur.com/a/NFI53): The date in [my cart's PCB](http://imgur.com/6AHcdIj) is 1986 instead of 1991.
I have also uploaded [some images of Pinball](http://imgur.com/a/mmGmg) that verify the information that has been added.
Finally I followed the current rom naming from the game list, as I did in #2537 with SNES, and again, strictly speaking …

Added NES carts information

---

hash/snes.xml

The following information has been added to the SNES game list:
- [Dragon Ball Z - Super Gokuu Den - Kakusei Hen](http://imgur.com/a/RGvnc): Chip names on the [PCB layout](http://imgur.com/tZGIRgV) have been added. Also the rom name has been fixed by renaming it to the proper program name. I kept the date in the game list, which is the date in the cart label (1995), though the date in the [PCB label](http://imgur.com/tZGIRgV) is different (1993).
- [Ranma ½](http://imgur.com/a/Z1ev1): I have added information of an earlier Ranma ½ revision, dated 1992 instead of 1993. It uses two roms as program roms, which could be 2Mb each summing up 4Mb like the 1993 version, or 1Mb U1 and 512Kb U2 like the French version. I have tried to find information about the ROM chips without any success. I have …

Added SNES carts information

---

src/lib/util/server_http.hpp

This seems to be necessary for MSVC to get std::tolower()

Adding #include <cctype>

---

src/emu/dislot.h
src/frontend/mame/ui/slotopt.cpp
src/frontend/mame/ui/slotopt.h

The source of the issue is that the logic for rotating slot options was broken.  It would count selectable options and skip over options that were not selectable, except for the specific scenario where the index was zero.  I ended up largely replacing the logic to be more C++-ish.
I also changed the options list to be std::map instead of std::unordered_map.  Rotating the latter is indeterminent.

Fix to MameTesters bug #6657

---

src/mame/drivers/thoop2.cpp

machines promoted to WORKING - TH Strikes Back [David Haywood, Kevin Eshbach]
dumped using the method developed by Morten Shearman Kirkegaard and Peter Wilhelmsen
note, if you have old nvram file delete it or you won't see any improvement.

machines promoted to WORKING - TH Strikes Back [David Haywood, Kevin Eshbach]

---

scripts/target/mame/arcade.lua
scripts/target/mame/mess.lua
src/mame/drivers/saturn.cpp
src/mame/machine/saturn_cdb.cpp
src/mame/machine/saturn_cdb.h

seems to make more sense than just sitting on the ROMs, which as far as I can tell benefits absolutely nobody...

add basic device for saturn_cdb to load the roms

---

src/emu/addrmap.h
src/mame/drivers/bbcbc.cpp
src/mame/drivers/equites.cpp
src/mame/drivers/gaelco.cpp
src/mame/drivers/gaelco3d.cpp
src/mame/drivers/gridlee.cpp
src/mame/drivers/legionna.cpp
src/mame/drivers/r2dx_v33.cpp
src/mame/drivers/raiden2.cpp
src/mame/drivers/splash.cpp
src/mame/drivers/taito_l.cpp
src/mame/drivers/thoop2.cpp
src/mame/drivers/timeplt.cpp
src/mame/drivers/wrally.cpp
src/mame/includes/equites.h
src/mame/includes/gaelco.h
src/mame/includes/gaelco3d.h
src/mame/includes/gridlee.h
src/mame/includes/legionna.h
src/mame/includes/raiden2.h
src/mame/includes/splash.h
src/mame/includes/taito_l.h
src/mame/includes/thoop2.h
src/mame/includes/timeplt.h
src/mame/includes/wrally.h
src/mame/machine/wrally.cpp

These new macros make it easy to map devices addressed using higher address lines (which helps to reduce line loads on actual HW) without needing to set up custom handlers and associated device finders. The implementation should not impact the efficiency of the core memory system (which Olivier Galibert is trying to improve) since the semantic details are contained within C++11 lambdas.

Add address-shifted versions of AM_DEVREAD/_DEVWRITE/_DEVREADWRITE (nw)

---

src/devices/machine/1ma6.cpp
src/lib/formats/hti_tape.cpp
src/lib/formats/hti_tape.h

Hi,
this PR is for a small fix to DC100 cassette emulation (used in HP 9845 & 85 systems) to prevent false gap detections (which, in turn, prevent reading of tape).
Thanks.
--F.Ulivi

Fixed a bug in gap detection of DC100 tape emulation

---

src/mame/drivers/4enraya.cpp
src/mame/drivers/gaelco2.cpp
src/mame/mame.lst

new WORKING clones  Alligator Hunt (unprotected, set 2) [David Haywood, Peter Wilhelmsen]
this was purchased as part of the quest to find a 2nd working Alligator Hunt still using the DS5002FP rather than the unprotected code, took a gamble on it because it was an unknown set, turns out it's unrprotected but very different to the set in MAME.
also unrelated but marked unkfr as working since I can't find an issue with it

new WORKING clones  Alligator Hunt (unprotected, set 2) [David Haywood, Peter Wilhelmsen]

---

src/devices/sound/gb.cpp

I recently noticed that it takes very long to load a gba state, sometimes
dozens of seconds, and the older the state is, the longer it takes to load.
I found out it's caused by gameboy_sound_device does not save the m_last_updated
variable, and after loading a state, in the update_state method, now could end
up being much larger than m_last_updated, and leads to substantial yet wasted
calculation of the channel state.
Simply adding save_item(NAME(m_last_updated)) should fix the problem, however,
since it will break current existing saved states, and optimize the channel
update methods is in the TODO list, I took the latter choice, now the calculation
to update the channel state is really negligible and the state loading is
almost instantaneous.

gb.cpp: optimize the channel update methods.

---

hash/hp85_rom.xml
scripts/src/bus.lua
scripts/target/mame/mess.lua
src/devices/bus/hp80_optroms/hp80_optrom.cpp
src/devices/bus/hp80_optroms/hp80_optrom.h
src/mame/drivers/hp80.cpp

Hi,
this PR introduces the support of optional ROM modules in HP85 emulation.
A partial software list of these ROMs is included (to be completed).
Each software entry in the list needs a "sc" feature so that the image is loaded in the correct bank. The SC (select code) is the value of a 8-bit port that selects the opt. ROM to be visible in a region of the address space.
Each ROM is hardwired to activate with a particular SC value (that's why I need it in the hash file).
I'm going to mail the ROM images to the usual "code" address.
The images themselves come straight from Kaser's emulator (http://www.kaser.com/hp85.html). The "service_fix" ROM is just the standard service ROM with a fix I made to a bug in tape "U" test.
Thanks.
--F.Ulivi

hp85: support of opt. ROMs

---

src/devices/machine/upd765.cpp
src/devices/machine/upd765.h

Minimal support for i82072: write access to the data rate select register is enough for InterPro 2000 support right now.

upd765: added i82072

---

src/mame/drivers/gaelco2.cpp
src/mame/mame.lst

Alligator Hunt (Spain, protected) [David Haywood, Darksoft, Morten Shearman Kirkegaard, Peter Wilhelmsen]
data was verified using a 2nd board, only 1 byte changed in the code area, data table is also verified by checksum in the code, and by the unprotected set as reference.  This is a good read.

new machines promoted to WORKING : Alligator Hunt (Spain, protected) [David Haywood, Darksoft, Morten Shearman Kirkegaard, Peter Wilhelmsen]

---

src/mame/drivers/hp9k_3xx.cpp

Faking the DMA register set with RAM makes the 'Failed' message
go away, but makes the ROM use DMA functionality even if there's
none. Seen this while working on HPIB support which tries to transfer
data via DMA and fails. When disabling the DMA hack the ROM falls
back to PIO mode.

HP9000/300: disable DMA controller workaround

---

scripts/src/bus.lua
src/devices/bus/hp_dio/hp98603.cpp
src/devices/bus/hp_dio/hp98603.h
src/mame/drivers/hp9k_3xx.cpp

Even if BASIC doesn't boot yet it's handy to have the ROM card in the code
and BASIC in the software list.

hp9k_3xx: add 98603 ROM card

---

src/devices/machine/i82586.cpp
src/devices/machine/i82586.h

* tested 82586 device successfully (with InterPro 2000)
* include heartbeat indicator on all transmits to pass InterPro diagnostic
* corrected a bug affecting long frames (now allows up to 64k, slightly worried about the increase in save state, but don't have a better idea)

i82586: fixed 82586 initialisation

---

src/devices/machine/68340.cpp
src/devices/machine/68340.h
src/devices/machine/68340ser.cpp
src/devices/machine/68340ser.h
src/devices/machine/68340sim.cpp
src/devices/machine/68340tmu.cpp
src/devices/machine/68340tmu.h
src/devices/machine/mc68681.cpp
src/devices/machine/mc68681.h
src/mame/drivers/dbox.cpp

A cleaner PR than [my previous](https://github.com/mamedev/mame/pull/2596). I reached my mile stone as I am able to hook up a terminal to the serial port. In theory it will now be possible to flash the dbox with a shareware called DVB2000 by using a PC utility that connects over serial, it is not tested yet as I need to figure out how to do that, either from a DOSbox or a second MAME instance. Please review in particular the way I created the serial module by inherit the duart driver. I think it works well but there could impurities in the way I did it.

Improved 68340, 68681 and dbox support

---

src/mame/drivers/gaelco2.cpp
src/mame/drivers/glass.cpp
src/mame/mame.lst

Maniac Square (protected, Version 1.0, Checksum DEEE) [Peter Wilhelmsen, Morten Shearman Kirkegaard, Charles MacDonald, David Haywood]
Maniac Square (protected, Version 1.0, Checksum CF2D) [Peter Wilhelmsen, Morten Shearman Kirkegaard, Charles MacDonald, David Haywood]
Glass (Ver 1.1, Break Edition, Checksum 49D5E66B, Version 1994) [Peter Wilhelmsen, Morten Shearman Kirkegaard, David Haywood]
Glass (Ver 1.0, Break Edition, Checksum C5513F3C) [Peter Wilhelmsen, Morten Shearman Kirkegaard, David Haywood]
Glass (Ver 1.0, Break Edition, Checksum D3864FDB) [Peter Wilhelmsen, Morten Shearman Kirkegaard, David Haywood]

new machines promoted to working (Gaelco)

---

src/mame/drivers/panicr.cpp

demote Panic Road (panicr) to MACHINE_NOT_WORKING
playtesting shows that the collisions aren't right, broken collisions = broken game logic = MACHINE_NOT_WORKING flag, we have higher standards.

demote Panic Road (panicr) to MACHINE_NOT_WORKING

---

src/devices/machine/upd765.cpp
src/devices/machine/upd765.h

* changed sense interrupt status drive busy bit handling for seek/recalibrate (only cleared when first result byte is read)
* changed sis to return results in decrementing drive order
* added i82072 motor on/off command
* switched to logmacro.h logging convention
Note: I haven't tested the sense interrupt status change on anything other than the InterPro systems I'm targeting. Hopefully someone else is set up to do so: only the change to the order of sis results is dubious - it's not covered by the documentation I've seen so far, but relied on by the InterPro 2000 diagnostic code.

upd765: sense interrupt status and i82072 changes

---

hash/sms.xml
src/devices/bus/sega8/rom.cpp
src/devices/bus/sms_ctrl/multitap.cpp
src/mame/drivers/sms.cpp
src/mame/machine/sms.cpp

- correct author of the SMS multipad device hardware.
- upper addresses of the SMS2/GG memory map unused by devices need to be mapped to RAM (fixes 'shero' GG game).
- add PCB info for 'termntr' and fix mapper of 'jangpun2', entries of the SMS software list.
- fix a soft reset bug in the mapper code for the '4pak' entry of the SMS software list.
- remove two obsolete comments from the period when MESS didn't supported BIOS selection.
- change two comments to document that player inputs on GG aren't disabled even in SMS mode.

sms/gamegear misc fixes [Enik Land]

---

src/devices/cpu/m68000/m68k_in.cpp

Flamewing has a test that claims to exhaustively test BCD instructions:
https://github.com/flamewing/68k-bcd-verifier
I've verified the test indeed passes on my Megadrive model1 (68000).

m68k: fix abcd/sbcd/nbcd to pass 68k-bcd-verifier

---

src/mame/drivers/europc.cpp
src/mame/mame.lst

size on EuroPC and slot configuration. EMS memory doesn't work on EuroPC II and XT (should be able to be configured from the BIOS, but options don't show up, DOS EMS driver doesn't load).

Added comments and EuroPC II and EuroXT variants, corrected RAM 

---

src/mame/drivers/kdt6.cpp
src/mame/layout/kdt6.lay

A more elaborate layout with a photo bezel and properly positioned drive LEDs is available.

Added basic stub layout with drive LEDs

---

scripts/src/main.lua
scripts/src/osd/sdl.lua
scripts/src/osd/sdl_cfg.lua
scripts/src/osd/windows.lua
scripts/src/osd/windows_cfg.lua
src/osd/osdcore.cpp
src/osd/osdcore.h
src/osd/sdl/sdlmain.cpp
src/osd/windows/main.cpp
src/osd/windows/winmain.cpp
src/tools/imgtool/main.cpp

Specifically, this creates a call osd_get_command_line() that returns UTF-8 command line arguments as std::vector<std::string>.  On non-Windows platforms, this does nothing more than build the vector.  On Windows, this invokes GetCommandLineW() and CommandLineToArgvW().  This also attempts to unwind usage of wmain()/_tmain() on Windows, which is not standard.
Related to this, this fixes a bug in Imgtool; specifically, non-7 bit ASCII was not being handled correctly in Windows.
This is really an admission that the way that Windows handles Unicode and command line arguments sucks, and it is my belief that having a wmain() or _tmain() declaration specific for Windows is a worse solution.  C'est la vie.
I'm very open to the idea that src/osd/osdcore.[cpp|h] is not the best place to do this. …

Attempted to sanitize/rationalize how we access UTF-8 command line arguments

---

src/devices/machine/6840ptm.cpp
src/devices/machine/6850acia.cpp
src/emu/logmacro.h
src/mame/drivers/didact.cpp

tried a long time to use bank devices for this but as it used two levels of indirection, eg 2 banks of 16 banks each where each of the 16 banks can point to any device/ram/rom segment, it got very complex and it was never working and almost impossible to understand. So I rewrote it in plain code and a number of previously not working BASIC commands started working. There are more to do but this is a nice milestone towards booting OS9. 
I also made some C11 strings legacy aware in the PTM and ACIA devices.

Candela PAL driven address map

---

src/devices/cpu/m68000/m68k_in.cpp

Verified on 68000 with an updated bcd-verifier:
https://github.com/flamewing/68k-bcd-verifier/pull/1
Megadrive ROM:
http://notaz.gp2x.de/md/rel/bcd-verifier-u1.zip

m68k: fix another nbcd mistake

---

src/devices/bus/coco/coco_t4426.cpp
src/devices/machine/6821pia.cpp
src/devices/machine/mc14411.cpp
src/mame/drivers/coco12.cpp

Still some odd exits to a disabled BASIC prompt for last two main menu options. It is probably some memory map issue/main board modification not emulated yet. I will verify this on real hardware before hunting the cause of it.
Good news is that it is now possible to write a small CNC program and send it to a printer, or even better, the Terco 4490 CNC which is on my to do list to emulate, so the cart is working to an extent.

Terco 4426 programming station cart banking fixed

---

src/mame/drivers/gaelco2.cpp
src/mame/drivers/himesiki.cpp

verified using 2 more boards in order to weed out the bad bytes, image is now trusted and correct.
also set androidp to 1987, the date is shown during the end credits.

Gaelco touchgo improvement - new SRAM dump

---

src/mame/drivers/dynax.cpp

The game checks for the the string "A WARNING.IF YOU COPY OUR ITEMS,WE REVENGE BY ALL MEANS." at address 0x6E17, and will reset everything if the string does not match when the game starts.
In the current implementation only 0x7000-0x7fff is saved as nvram after exiting the game, which will cause the string to be lost.
I'm not sure what the exact nvram address is, but at least this works.

dynax.cpp: (tenkai) fix credits lost after exiting the game.

---

src/devices/machine/mc68901.cpp

bits 6-4 are used for timer C
bits 2-0 are used for timer D
https://www.nxp.com/docs/en/reference-manual/MC68901UM.pdf page 43
Signed-off-by: Nicolas PLANEL <nplanel@redhat.com>

mc68901 : fix TCDCR register

---

src/emu/emuopts.h
src/frontend/mame/ui/miscmenu.cpp
src/frontend/mame/ui/miscmenu.h
src/osd/modules/lib/osdobj_common.h
src/osd/sdl/sdlmain.cpp
src/osd/windows/winmain.cpp
src/osd/windows/winmain.h

This crash (discovered by Wizz) had the following symptoms:
1.  Start MAME
2.  Choose "Configure Machine"
3.  Choose "Video Options"
CRASH
This was the result of the options editor not having a fully formed list of options where it was expecting one.  The fix is to change the declaration of emu_options to one that have full OSD options (it is possible that SDLMAME needs something slightly different)
Please scrutinize this fix.  I hate it.  I also hate how all of the OSD options are duplicatively declared in submenu.cpp, but with a different data structure.  At the very least we should be having some sort of factory to create "full" options for the pertinent platform; but I'm not sure how precisely we would want it to work.

Fixed an options overhaul regression

---

src/devices/machine/mc146818.cpp

Bit masking error : The flag wasn't cleared properly and others flags are corrupted.

Fix main interrupt flag.

---

src/mame/drivers/namcos23.cpp

In according pcb video, Final Furlong 2 Titlescreen says 1998:
www.nicozon.net/watch/sm11003517
In according pcb video, Crisis Zone Titlescreen says 1999 and released in October 1999:
https://www.youtube.com/watch?v=Pcjdydg_Xdk

Correct Final Furlong 2 and Crisis Zone Years

---

src/devices/machine/eeprom.cpp

I don't know why this check for endianness is here, but I don't believe it's appropriate.

eeprom: don't check endianness (nw)

---

src/mame/drivers/europc.cpp

I never saw an earlier or later BIOS version mentioned for the original EuroPC in a discussion thread.
The 2.04 (and also the 2.05 that is already in MAME) don't work for now because according to one site memory management has been changed afterwards. They just show a dash on the top left of the screen.

EuroPC: Added first and last known BIOS versions

---

src/devices/cpu/cop400/cop400.cpp
src/devices/cpu/cop400/cop400.h
src/emu/debug/debugcon.cpp
src/emu/debug/debugcon.h
src/emu/debug/debugcpu.cpp
src/emu/distate.cpp
src/emu/distate.h

- Create a templated subclass of device_state_entry to provide separate read/write interfaces for registers of varying widths. The efficiency impact of this should be minimal, given that this eliminates the need to make each byte width a subcase for reads and writes.
- Create similarly templated "pseudo-register" versions of device_state_entry that provides custom read/write interfaces through std::function. The intent of this is to eventually replace the dummy register + state_export interface hitherto necessary to provide debugger access to bankswitched or computed state registers.
- State registers can now be made read-only, and this is automatically done now when state_add is called with a std::function read handler but no write handler. This property is honored by MAME debug …

device_state_interface: Polymorphism and std::function for entries (nw)

---

src/mame/drivers/pc.cpp

ROM, manual and disk set are available on the internet (cf. Bannister & FTP)
The Kaypro CGA character ROM still needs to be dumped, and the harddisk controller originally used in the Kaypro 16 (WD1002-HD0, connected from a mainboard port rather than an ISA card) is not emulated yet.
The configuration presented here is essentially the Kaypro 16/2, a version without harddisk and with two 360K floppies.

Added Kaypro 16

---

src/mame/drivers/kaypro.cpp
src/mame/mame.lst

Story and files here https://hackaday.io/project/20151-floppy-fun-backing-up-a-unique-kay-pro-disk
The software runs, but obviously complains about the missing i/o board.

Kaypro: Added the Omni 4 Logic Analyzer

---

src/mame/drivers/pgm.cpp

The (undumped) protection device internal ARM roms provide the region.
As this has no external ROM for the ARM we have no way to trojan it out.

document that the 'oldsplus' set identifies as "Oriental Legend 2" when set to Korea

---

hash/fmtowns_cd.xml
hash/fmtowns_flop.xml

I have completely revamped the missing lists with about 700 new entries. I romanized most of the titles pretty much on my own, but my Japanese isn't quite the best so I may have made some mistakes, especially in titles with wordplay or obscure words. A second look at the list would be appreciated.
The new lists are based on "FMTOWNS用市販ソフトウェアデータベース Ver.0.3" (http://fmtowns.a.la9.jp/db/sdb.html), which is probably the most complete list of commercial software for the FM Towns that exists out there.
Also, I have added several of my own dumps, both CD and floppy. See the commits for details.

FM Towns softlists: new missing lists, several additions

---

src/mame/drivers/tonton.cpp

In according Success website, Waku Waku Doubutsu Land TonTon (とんとん) year is 1987.
https://www.success-corp.co.jp/developments/works

Correct Waku Waku Doubutsu Land TonTon year

---

src/mame/drivers/atarittl.cpp
src/mame/mame.lst

I've credited Ed Fries, Tim Giddens, and Andy Welburn as from the article https://edfries.wordpress.com/2017/10/23/finding-the-first-videogame-rom/

Add older version of Gran-Trak 10

---

src/mame/video/ygv608.cpp
src/mame/video/ygv608.h

This patch fixes rotzoom behavior used in Namco Classic Collection vol.1 & 2.
Verified against actual PCBs.
In NCV1 Xevious Arrangement, scrolling-by-row feature is used to draw and move UFOs in 'AREA 8'.
I think this is the only part where the feature is used (but I'm not sure whether the feature is used in other games on the boards).

ygv608: Namco Classic Collection vol.1 & 2 Graphics improvements

---

src/mame/video/fmtowns.cpp

The kanji characters currently displayed using the fixed ROM font (mainly the boot messages) are wrong. This fixes the offset calculation so the appropriate characters are displayed, e.g.:
ディスクエラーが発生しました (a disk error has occurred) instead of ディスクエラーが遣宛しました (gibberish)
システム読み込み中です (the system is loading) instead of システム局み扶み恰です (gibberish)
And so on.

fmtowns: fix kanji offset calculation

---

src/devices/cpu/arm7/arm7.cpp
src/devices/cpu/arm7/arm7.h
src/devices/cpu/arm7/arm7thmb.cpp
src/mame/drivers/pgm2.cpp

dumped internal IGS036 rom for Oriental Legend 2 [Morten Shearman Kirkegaard and Peter Wilhelmsen]
started adding some devices to the driver to support it [David Haywood]
derived IGS036 type in ARM7/9 core, because it seems like mmu could be different, and there are probably other internal devices [David Haywood]
fixed(?) BLX (LO) thumb opcode in ARM7/9 core, was storing a return address that skipped the following opcode [David Haywood]
I think there might still be ARM9 issues.

dumped internal IGS036 rom for Oriental Legend 2 [Morten Shearman Kirkegaard and Peter Wilhelmsen]

---

src/mame/drivers/kaypro.cpp
src/mame/includes/kaypro.h
src/mame/machine/kaypro.cpp
src/mame/mame.lst
src/mame/video/kaypro.cpp

- renamed kaypro4 to kayproiv (cf. boot message) and kaypro4a to kaypro484
- make Kaypro use standard disk formats, if this is approved, kaypro_dsk.cpp and .h can be removed
- added kaypro1084, kaypro1, kaypro4x, kaypro284 and kaypronew2 as well as II plus 88
- made kaypro484 the parent for the later non-10/non-Robie machines
- made the 4 plus 88 a '84 generation machine in keeping with adverts of the time and photographic evidence - the plus 88 board is a CoPower 88 from SWP and could also be bought indepentently
- distributed ROMs evenly, and marked dumps bad where appropriate
- put handyman ROM into kaypro2x, this ROM can be added to all other Kaypro drivers once it's got its own 16K RAM added and connected
- Kaypro is SS/DD or DS/DD, offer DS/QD as option, it was supported by third …

Added missing Kaypro models, distributed ROM files accordingly

---

src/mame/drivers/model3.cpp

Spikeout: Final Edition titlescreen says 1999, and released date is 1999 confirmed from  Arcade TV Game List Kokunai - Kaigai Hen (1971 - 2005) at Page 38.
https://i.imgur.com/897HPm2.png
https://i.imgur.com/IOUUZgO.png

Correct Spikeout: Final Edition year

---

src/mame/video/fmtowns.cpp

This fixes some scrolling / screen positioning issues with some games in 16-color mode:
Air Management
Brandish
Ginga Eiyuu Densetsu III SP
Schwarzschild IV
Vain Dream
Vain Dream II
And possibly others I haven't tested yet.
Scrolling still isn't quite perfect everywhere but it should be much better than before.

fmtowns: Fix scrolling in 16-color mode

---

src/mame/drivers/vt240.cpp

Bit order in Video Output Map verified via ReGIS palette escape sequences.   Raster width is specified as 800 on page 6-40 of technical manual.

vt240: palette, screen size fix

---

src/mame/drivers/mice.cpp
src/mame/mame.lst

(nw) This anticipates that each CPU type will also require its own special configuration, though none of them are actually emulated yet.
N.B. This is being submitted as a pull request to obtain input on what the best format for set names would be here. The present ones are taken from the old region names, and though they seem logical enough, there might be nicer-looking alternatives.

mice: Split into separate sets for each CPU-specific monitor program

---

scripts/src/machine.lua
scripts/target/mame/mess.lua
src/devices/machine/28fxxx.cpp
src/devices/machine/28fxxx.h

Implementation of 28F010 and family flash memory devices. These are not compatible with the JEDEC-standard flash command protocol implemented in intelfsh.

28fxxx: initial commit for new flash memory device

---

src/mame/drivers/pgm2.cpp

(lightly tested, only seems used by lightning on orleg2 char select at the moment)

pgm2 - support sprite zooming for flipped / reversed cases

---

src/mame/drivers/at.cpp
src/mame/mame.lst

- renamed cmdpc30 to pc30iii as a PC 30 is an XT with a harddisk from the PC 10 line, now it's consistent with the PC10-III from the same vintage
- added BIOS revision v2.0 and notes
- added PC 40-III and notes; VGA ROMs are commented out until some kind soul makes a Paradise VGA (at.cpp has precedent for that)

Renamed Commodore PC 30-III, added BIOS variant and PC 40-III, added info

---

src/mame/drivers/at.cpp
src/mame/mame.lst

- Sanyo MBC-28: Complains about missing Bus mouse
- Compaq Portable III: graphics card emulation wrong (needs AT&T PC 6300/Olivetti M24 compatible), keyboard mcu dump provided but not hooked up
- Siemens PCD-2: keyboard error, keyboard mcu dump provided but not hooked up
- added comments and notes

Add Sanyo MBC-28, Siemens PCD-2, Compaq Portable III and 286 and 486 BIOS versions

---

src/osd/modules/file/winfile.cpp

Provided as a potential fix for physical drive access using chdman in Windows 10.  There may be cleaner/better methods.
This patch allows chdman to access a physical drive in Windows 10 from an elevated command prompt.
This has been tested with extracthd and createhd commands in Windows 10 Professional.
This should be tested on other windows systems as well.

chdman: Patch to allow chdman to access physical drives on Windows 10

---

src/mame/drivers/gal3.cpp

Galaxian 3 - Theater 6 : Project Dragoon was released in December 1992 and Galaxian 3 - Theater 6 J2 : Attack of The Zolgear was released in July 1994 confirmed from Arcade TV Game List Kokunai - Kaigai Hen (1971 - 2005) at Page 53.
https://i.imgur.com/M5aDtWmr.png

Correct Galaxian 3 - Theater 6 : Project Dragoon and Galaxian 3 - Theater 6 J2 : Attack of The Zolgear Years

---

src/devices/cpu/z180/z180.cpp
src/devices/cpu/z180/z180.h
src/devices/cpu/z180/z180ops.h

the definition of Z180_RCR_REFW had a copy/paste error.
added support for the Z180 internal Wait State Generator to the cycle-timing bringing it in line with real hardware.
Still missing: Dynamic RAM Refresh Control timing

z180: fixed Z180_RCR_REFW; support Wait State Generator (DCNTL)

---

src/mame/drivers/segac2.cpp

Soreike! Anpanman Popcorn Factory year found on SEGA and kidstube website.
https://sega.jp/business/news/0807/
http://kidstube.jp/2017/11/14/%e3%80%90%e8%b2%b4%e9%87%8d%e3%81%aa%e5%88%9d%e4%bb%a3%e3%80%91%e3%81%9d%e3%82%8c%e3%81%84%e3%81%91%ef%bc%81%e3%82%a2%e3%83%b3%e3%83%91%e3%83%b3%e3%83%9e%e3%83%b3-%e3%83%9d%e3%83%83%e3%83%97%e3%82%b3/

Soreike! Anpanman Popcorn Factory year Confirmed as 1992.

---

src/mame/drivers/crgolf.cpp

Release year is 1985 confirmed from Arcade TV Game List Kokunai - Kaigai Hen (1971 - 2005) at Page 22.
https://i.imgur.com/UmbcSAi.png

Correct Master's Golf Year

---

src/mame/drivers/nbmj9195.cpp

LD Mahjong #4 Shabon-Dama was released year is 1991 confirmed from Arcade TV Game List Kokunai - Kaigai Hen (1971 - 2005) at Page 56.
https://i.imgur.com/v9p72Ra.jpg

Correct LD Mahjong #4 Shabon-Dama year

---

language/Portuguese_Brazil/strings.po

- All translation updated to follow GNOME Translation Rules for Brazilian Portuguese, this are the same rules followed by other Linux Distributions, Manuals, etc. Now we can avoid translation conflicts.
http://br.gnome.org/GNOMEBR/ErrosFrequentes
http://br.gnome.org/GNOMEBR/GuiaDoTradutor
- Brazilian Portuguese REQUIRE context, it doesn't matter what a word say, we need to see what the program is doing instead of what the word/phrase is saying to construct the phrase correctly.
- That ROM AUDITION functions means nothing in Brazilian Portuguese, so the translation was adapted to "Condição", this reflects better if the ROM is GOOD/BAD, etc.
- OK has different meanings in Brazilian Portuguese, if you ask someone if the food was good and you reply "OK", it means that the food  are between …

Update for Brazilian Portuguese

---

src/mame/video/fmtowns.cpp

This fixes the jerky horizontal movement in games that make use of CRTC registers 18 and 22 to scroll the graphics layers, including but probably not limited to:
Vain Dream
Vain Dream II
Hiouden II
Yami no Ketsuzoku Special
Eye of the Beholder II
Schwarzschild IV
I doesn't seem to break anything else, as far as I have tested.

fmtowns: better horizontal scrolling

---

src/mame/video/fmtowns.cpp

This is an improvement on PR #2873 that takes into account the scaling factor of the graphics layers. It improves scrolling on titles like 38man (intro), azure (title screen), and probably more.
Hi-color mode is just a guess, though. I'm not sure if there is any software that actually uses the scroll registers in this mode so it may not be completely right.

fmtowns: even better horizontal scrolling

---

src/mame/drivers/model3.cpp

Virtua Striker 2 '99 titlescreen says 1998, and released date is 1998 confirmed from  Arcade TV Game List Kokunai - Kaigai Hen (1971 - 2005) at Page 38.
https://i.imgur.com/yf3xSWX.png
https://i.imgur.com/e4lqNDW.png

Correct Virtua Striker 2 '99 year

---

src/mame/video/fmtowns.cpp

Final fix for scrolling / positioning issues (hopefully). Fixes Psychic Detective Vol. 5.

fmtowns: correct scrolling in 16-bit color mode

---

src/mame/video/fmtowns.cpp

After further testing, it seems Vain Dream uses the horizontal adjust registers in 16-bit color mode for a small part of the intro, and PR #2881 made it slightly worse. This should make both it and psydet5 display correctly.

fmtowns: fixed 16-bit color scrolling a bit more

---

scripts/src/video.lua
scripts/target/mame/mess.lua
src/devices/video/dp8510.cpp
src/devices/video/dp8510.h

An implementation of the National Semiconductor DP8510 BITBLT Processing Unit. This is used on the InterPro GT family graphics boards, and this implementation seems to be correct enough to enable me to progress there, hence the PR. While I'd love to have another system to test against, I'm not aware of any other systems that ever used this device other than some NatSemi reference designs, which are not (yet) in MAME.

dp8510: new device (nw)

---

src/mame/drivers/pgm2.cpp
src/mame/mame.lst

dumped Internal rom from an Oversea (English) region "Oriental Legend 2" cartridge confirming only the region byte changes in that case.  [Jeremy Romine, Peter Wilhelmsen, Morten Shearman Kirkegaard]
Other regions, including Japan single PCB need confirming to see if there are further changes in those cases or not.  This is in progress.
As the Oversea version ignores the Card Reader MCU we can mark it as working, so
New Working Machines
Oriental Legend 2 (Oversea)  [David Haywood, MetalliC, Jeremy Romine, Peter Wilhelmsen, Morten Shearman Kirkegaard]

dumped Internal rom from an Oversea (English) region "Oriental Legend 2" cartridge  [Jeremy Romine, Peter Wilhelmsen, Morten Shearman Kirkegaard]

---

src/mame/drivers/fmtowns.cpp

This change fixes a bug that caused the mouse cursor to move downwards on its own in some Data West games (Misty, Psychic Detective series, The 4th Unit series). These games seem to poll the mouse port in a peculiar way that caused the reads to return 0x0f sometimes even if the user wasn't moving the mouse.
It doesn't break anything in other games or in TownsOS / Windows, as far as I have tested.

fmtowns: fixed mouse cursor moving on its own in Data West games

---

hash/ibm5170_cdrom.xml

Added 'Sideline', probably the best sidescrolling shoot 'em up for DOS, and also one of the most obscure.
The game has been declared freeware. More info here > http://sideline.ghegs.com/
I've converted the bin/cue to a chd which can be downloaded here > http://www.mediafire.com/file/pd1utz71px292bs/sideline.chd
Some extra info:
To run the game, you'll need to run INSTALL.BAT on the disc first. Next run SNDSETUP from the installation directory to configure sound cards.
To play, run MAIN.EXE from the disc.

Added 'Sideline'

---

src/mame/drivers/gticlub.cpp

Operation Thunder Hurricane titlescreen says 1997 and released year is 1997 confirmed from Arcade TV Game List Kokunai - Kaigai Hen (1971 - 2005) at Page 28.
https://i.imgur.com/frjxXnA.png
https://i.imgur.com/7FHn0bB.png

Correct Operation Thunder Hurricane year

---

scripts/target/mame/arcade.lua
src/mame/drivers/pgm2.cpp
src/mame/includes/pgm2.h
src/mame/machine/pgm2_memcard.cpp
src/mame/machine/pgm2_memcard.h

promoted China set of Oriental Legend 2 to working
promoted Knights of Valour 2 New Legend to working
as each game/region requires a valid default card in order to save said cards are part of romset.
(there's probably a cleaner way to do the device finder stuff but I forgot and can't find reference)

pgm2: memcard reader now uses image_device stuff, cards can be inserted / removed and get saved [Metallic, David Haywood]

---

src/mame/drivers/toaplan2.cpp

Was doing a repair today that required me to hook up a different clock source to the YM2151, so we tried to use the Z80's clock. Turns out, it's not at all 4MHz, so it was wrong. We put the 32MHz oscillator and the Z80 clock on an oscilloscope and determined the Z80 clock was divided by 6 instead of 8. So instead we divided the 68k's clock by 4 and got 4MHz, so the 68k is indeed 16MHz.

Fix Batrider's audio CPU clock.

---

src/mame/includes/fmtowns.h
src/mame/video/fmtowns.cpp

This change implements attribute bits 10-11 for sprites, which enable half-size rendering. The exact algorithm is unknown (AFAIK), so I'm just rendering alternate pixels / lines.
Documentation on the sprite attribute bits comes from the "FM Towns Technical Databook" by Noriaki Chiba.
It fixes some graphical artifacts in arcade ports that simulate sprite scaling like After Burner, Galaxy Force 2, Turbo Outrun and such. Also fixes the menu text in Azure, and possibly other things.
Note that half-size 16-bit color sprites are untested, as I don't know of any test cases.

fmtowns: implement half-size mode for sprites

---

src/frontend/mame/mame.cpp

In absence of the console plugin, the option entry was not found in m_plugins, making the set_value() crash when deferencing the result of get_entry().
Instead, an error message is logged telling the plugin is not found.

Trigger a fatal error when console was asked but the console plugin not found.

---

src/mame/includes/fmtowns.h
src/mame/video/fmtowns.cpp

This change implements sprite attribute bit 14. This swaps the X and Y coordinates and allows for sprite rotation in 90 degree increments, by combining it with the mirroring bits.
Fixes most (but not all) graphical glitches in After Burner 1 and 3.
As with the half-size attributes, rotation of 16-bit color sprites is untested as I haven't found any test cases yet.

fmtowns: implement sprite rotation

---

src/emu/debug/debugcmd.cpp
src/emu/debug/debugcmd.h
src/emu/debug/debughlp.cpp
src/emu/debug/debughlp.h

Chapter links are sorted.
The current code generated this file:
https://vadosnaprimer.github.io/debughelp.html
Also tweaked static_help_list spacing to always pad commands and never pad explanations.
Not sure about the macro though.
rst file could be generated in a similar way, might try that later.

Command to print all debugger help to html file

---

src/mame/video/fmtowns.cpp

When I implemented half-size sprites I made a slight miscalculation that causes them to be misaligned if the flip bits are also set, creating "gaps" in, e.g. the initial view of the plane in After Burner. This fixes it by keeping the end coordinates fixed and modifying the start ones if the sprite is downscaled + flipped.

fmtowns: fix gaps in flipped sprites

---

scripts/target/mame/mess.lua
src/mame/drivers/hp2640.cpp
src/mame/layout/hp2640.lay
src/mame/mame.lst
src/mame/mess.flt

Hi,
this PR introduces the driver for HP2645A terminal. It's still WIP but the basic system is there.
The most important things missing:
- The UART (so you can play with terminal in local mode only ATM)
- The support for alternate character sets (math symbols, big characters & line drawing)
Hopefully I should have some time over the holidays to work on the driver.
If you want to run the built-in self test, map the "TEST" key to something (I'm using F9) and press it.
I'm going to send the ROM set to the usual "code" e-mail.
Thanks.
--F.Ulivi

Driver for HP2645A terminal

---

src/mame/drivers/namcos12.cpp

Paca Paca Passion titlescreen says 1998 and released year is 1998 confirmed from Arcade TV Game List Kokunai - Kaigai Hen (1971 - 2005) at page 54.
https://i.imgur.com/hQmU2fJ.png
https://i.imgur.com/MkszWya.png

Correct Paca Paca Passion year

---

src/mame/video/fmtowns.cpp

This change improves wrapping when the screen scrolls horizontally past the end of a bitmap layer, by going back to the start of the same line instead of continuing to the next. It's not a perfect solution because it still doesn't work 100% properly for these two cases:
- Combined horizontal + vertical scrolling
- Layer 1, when sprites are present
But for now it fixes 1-line screen "splits" in games like:
- The New Zealand Story (only in some instances, when there isn't vertical scrolling)
- All LucasArts adventure games
- Rayxanber
And probably more.
Also, this PR includes a fix for a regression in 16-bit sprite rendering that was accidentally introduced with PR #2921.

fmtowns: fix horizontal wrap for bitmap layers

---

src/mame/video/fmtowns.cpp

- Doubled line size when in single-layer + high color mode. Software that uses this combination (secre2, debut2, ayayo123 "X68000 version") now looks mostly correct.
- Made the line wrapping code aware of VRAM page selection. Fixes a small number of cases where half of the screen would "shake" without this check.
- The second commit fixes misplaced lines that sometimes appear at the bottom of the screen in some games (e.g. aburner3 intro), due to the drawing code going beyond the last line of the layer.

fmtowns: fix single-layer 16 bit mode and multipage wrapping

---

src/mame/drivers/vg5k.cpp

making the"alternate" (CRC 57983260) the correct one.
- ROM was dumped from a Philips VG-5000µ and compared to
the "alternate" (CRC 57983260) version to find it was the same.
- Analyze of the (CRC a6998ff8) and why it is faulty and useless to keep:
- Address $1000: correct instruction is DI ($F3) at start of boot;
in faulty ROM, the instruction is INC BC ($03), which makes
no sense here.
- Address $2000: this is the start of the table pointing to BASIC
instructions. It is matched with the table at $209e
containing the keywords. The first keyword (END) will
cause the first address to be decoded (at $2519 to $2525)
and executed. Correct address is $2f3a, address found
in the faulty ROM is $2f00, thus preventing END instruction
to work.
- Address $3000: this part is the code for the NEXT …

Removed reference to VG-5000µ default faulty ROM (CRC a6998ff8)

---

src/mame/video/pgm2.cpp

also changes what you see in the shop (improves, hopefully, I can't read Chinese)

kov3: treat this bit as 'sprite disable' - prevents stray horemen heads in kov3 attract

---

src/mame/video/fmtowns.cpp

According to the FM Towns Technical Databook, when reading from port 0xcff86, bit 4 should always be set and bit 2 is the VSYNC flag. With this change, Birdy Soft games (cal, myeyes, beast3...) boot instead of getting stuck in a loop waiting for the flag.

fmtowns: fix vsync flag read from port cff86, Birdy Soft games now boot

---

src/mame/video/ygv608.cpp
src/mame/video/ygv608.h

A few printf shows R#13(m_border_color) is written when entering ND-1 self test.
It's just a guesswork, but this change fixes 'COLOR TEST' screen in test mode.

ygv608.cpp: Fix 'COLOR TEST' in ND-1 self test

---

src/mame/video/fmtowns.cpp

Similar to PR #2999, the later games in the 4th Unit series (zero, dagain, merrygor, wyatt) were getting stuck waiting for the HSYNC flag from 0xcff86 (bit 7). With this change they run past the initial menu.
(this is largely copied from Barry's implementation for port 0xfda0, so credit goes to him)

fmtowns: implemented hsync read from cff86, later 4th Unit games now boot

---

src/mame/includes/fmtowns.h
src/mame/video/fmtowns.cpp

This change fixes two issues that only happen with software that uses the single-layer mode (PMODE bit = 0).
- In 16-bit color mode, if pixels in VRAM have the alpha bit enabled, it's ignored by the video hardware and drawn to the screen anyway. This fixes the character dialogue in the Towns port of Hatchake Ayayo-san Pro-68k.
- 256-color mode can only be enabled as a single layer, so pixels with palette index 0 aren't transparent and need to be drawn. This fixes black "spots" in Yami no Ketsuzoku and wrong colors in the Genocide Square FMVs. 
Along with this, I have simplified the towns_crtc_draw_scan_layer_256 function by removing the layer 1 drawing code (which is never executed).

fmtowns: fix missing pixels in single-layer modes

---

src/mame/drivers/fcrash.cpp

´´´
==173199==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62900084d1fe at pc 0x00000186c8f5 bp 0x7ffcb5643500 sp 0x7ffcb56434f8
READ of size 2 at 0x62900084d1fe thread T0
#0 0x186c8f4 in cps_state::fcrash_render_sprites(screen_device&, bitmap_ind16&, rectangle const&) /mnt/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/mame/drivers/fcrash.cpp:505:7
#1 0x186df0a in fcrash_render_layer /mnt/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/mame/drivers/fcrash.cpp:535:4
#2 0x186df0a in cps_state::screen_update_fcrash(screen_device&, bitmap_ind16&, rectangle const&) /mnt/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/mame/drivers/fcrash.cpp:655
#3 0xe7ac132 in operator() …

fcrash.cpp: fixed m_sprite_base for punipic (nw)

---

src/emu/emuopts.cpp
src/emu/emuopts.h
src/emu/render.cpp

I've added a override_artwork and fallback_artwork to the MAME options. This will allow a user to override (no other artwork is loaded) the artwork or provide a fallback scenario for artwork. In discussion on the forum, the following order was agreed upon:
- If -override_artwork set: load override artwork, and return when successful
- Load explicit file, return when single file is set (UNCHANGED)
- Load driver name (UNCHANGED)
- Load internal default views (UNCHANGED)
- Load parent driver (UNCHANGED)
- Load parent of parent (will find bios artwork, e.g. neogeo for clones of neogeo games)
- If -fallback_artwork set: load fallback artwork
- For single screen: load internal horizont or vertical (UNCHANGED)
- If no layout has been found, load internal defaults based on number of screens (0, …

Override and fallback options for artwork

---

src/mame/drivers/hp2640.cpp

Hi,
this PR adds support for the following features to HP2645A terminal emulation:
- RS232 I/O
- Multiple character sets (line drawing, big characters, math symbols)
- Option switches
- Beeper
The terminal can be used "out of the box" as long as you map the "REMOTE" key to something and press it (or else the terminal will stay in local mode by default).
I'm going to send the updated ROM set to the usual "code" e-mail.
Thanks.
--F.Ulivi

Improvements to HP2645A

---

src/mame/drivers/fmtowns.cpp

This fixes a regression introduced with commit 81f44e1e968b559330a0c9cefebcef0868e1e9f4 that caused some games that were working previously (e.g. Emerald Dragon, several Cocktail Soft games, Indiana Jones and the Last Crusade) to fail to boot. 
Everything that Carl's commit fixed (e.g. Shadow of the Beast 2, Ultima IV/V, Loom, etc.) is also working, so hopefully this should make everyone happy.

fmtowns: fix cdrom regressions

---

src/devices/imagedev/flopdrv.cpp
src/devices/imagedev/flopdrv.h
src/mame/machine/thomflop.cpp

When the legacy floppy code is used for lookups and the tags are not the expected ones it will default to the first drive.
Since atarifdc has the drives below the "fdc" the generic lookup function could not be used. Making a copy of this is definitely ugly, but this is legacy code anyways and it fixes it. There's also some other drivers with legacy floppy support that did it this way.

Some legacy floppy fixes and cleanups

---

docs/source/debugger/annotation.rst
docs/source/debugger/breakpoint.rst
docs/source/debugger/cheats.rst
docs/source/debugger/execution.rst
docs/source/debugger/expressions.rst
docs/source/debugger/general.rst
docs/source/debugger/image.rst
docs/source/debugger/index.rst
docs/source/debugger/memory.rst
docs/source/debugger/registerpoints.rst
docs/source/debugger/watchpoint.rst
docs/source/index.rst

Here's the first pass of debugger help for the documentation LOOSELY based on PR #2948.
Some help text grammar has been corrected and will be backported back to the help command inside the debugger after the documentation version (this) is cleaned up sufficiently.
Known issues:
* There's no help for the history command. I need to work out what to do about that yet, but I didn't want it to delay getting the basics in.
* There's still a little bit of "wall of text" in some descriptions. I'll be cleaning those up.
There SHOULDN'T be any glaring errors in here, but I could have missed something. As always, drop me a note if I need to change anything. This includes formatting-- if you really dislike the formatting, get in touch with me and we'll work something out.

First pass of MAME Debugger help for documentation. (NW)

---

docs/source/debugger/annotation.rst
docs/source/debugger/breakpoint.rst
docs/source/debugger/cheats.rst
docs/source/debugger/execution.rst
docs/source/debugger/expressions.rst
docs/source/debugger/general.rst
docs/source/debugger/image.rst
docs/source/debugger/memory.rst
docs/source/debugger/registerpoints.rst
docs/source/debugger/watchpoint.rst

Per request, adjust case of commands.
Additional small tweaks to the expressions section as well.

Correct command heading case and adjustments to expressions (NW)

---

src/devices/video/ppu2c0x_vt.cpp
src/devices/video/ppu2c0x_vt.h
src/mame/drivers/nes_vt.cpp
src/mame/mame.lst

This adds initial support for the SY-889 handheld I dumped recently, which uses some one of the VTxx enhanced-NES chips. The exact chipset is unknown and doesn't resemble any other VTxx system - as well as software differences, it uses QSPI flash instead of the parallel flash used by all other known VRT chipsets. Credit to NewRisingSun2 who helped with the reverse engineering.
At the moment the ROM will run, the colours are correct (the chipset uses a different palette format to the VT03, storing colours as RGB555), but there are serious graphical glitches on the intro and when the menu scrolls. Most of the games seem to run OK though. I think this is because of the scanline interrupt timing being off.
Reverse engineering thread: http://s4.zetaboards.com/PGC_Forums/topic/30178284/1/

Add initial support for new VTxx handeld, SY-889

---

src/devices/machine/cdp1879.cpp
src/devices/machine/cdp1879.h

- m_regs seems to be too small since R_CNT_HOURS is 4 and it will access m_regs at + 6 - so index 10 would be out of bounds
- device_timer() also checked the alarm latch for the months which is never written and doesn't exist according to the data sheet

cdp1879.cpp: fixed Coverity out-of-bounds warnings (nw)

---

hash/fmtowns_cd.xml

When initially dumping the floppy disk for New 3D Golf Simulation I didn't realize that it had some kind of copy protection on track 2, so it didn't actually work. 
This replaces it with a new dump in HxC MFM format, converted from KryoFlux raw files. It's enough to let the game recognize the system disk as original and start the user disk creation process as expected.

fmtowns_cd.xml: replace 3dgolfha floppy with proper dump

---

docs/source/commandline/commandline-all.rst
docs/source/commandline/commandline-index.rst
docs/source/commandline/index.rst
docs/source/commandline/sdlconfig.rst
docs/source/commandline/windowsconfig.rst

This is a substantial overhaul of the old commandline section.
I found all options that were duplicated across SDL and Windows-specific sections and merged those with careful attention to note what parameters are valid per-OS.
Additionally added a new index page for commandline options that should be useful for providing support.
While I did do my absolute best to make sure no errors crept in, the sheer size of this means it's entirely possible I may have missed something. I didn't see anything obvious at a quick glance, in any case. As always, let me know and I'll do corrections as needed.

Overhaul commandline section of docs, includes index with linkable anchors.

---

src/mame/drivers/gaelco2.cpp
src/mame/includes/gaelco2.h
src/mame/mame.lst

as expected this version lets you set the game options in service mode rather than using dipswitches as the PCB has none.

new WORKING clones - Maniac Square (unprotected, Version 1.0, Checksum 66B1, 960419/1 PCB) [f205v]

---

scripts/target/mame/mess.lua
src/mame/drivers/a2600.cpp
src/mame/drivers/tvboy.cpp
src/mame/includes/a2600.h
src/mame/mame.lst
src/mame/mess.flt

The TV Boy II is a clone of the Atari 2600 with 126 built in games. This PR adds a driver for it, and also refactors the Atari 2600 driver a bit (creating a2600.h) so it can be added as a proper clone of the a2600 rather than a fake cartridge.

Add Systema TV Boy II

---

src/mame/drivers/tvboy.cpp
src/mame/includes/a2600.h
src/mame/mame.lst

previously crashed due to 
MCFG_M6502_DISABLE_DIRECT()
being after the bank definition not the CPU definition
also simplified banking, doesn't need 2 layers of indireciton, just the one.

 fix/tidy tvboy driver

---

src/devices/sound/gaelco.cpp

(fixes clicking sounds in various games, verified this with the sample data in ROM, looks correct, we were playing an extra byte from a different sample each time)

fix sample end position in sound/gaelco.cpp [dink]

---

src/mame/drivers/nwk-tr.cpp

Racing Jam: Chapter 2 titlescreen says 1998, and released in July 1998.
http://s.uvlist.net/l/y2011/05/84500.jpg

Correct Racing Jam: Chapter 2 year

---

src/mame/drivers/model2.cpp

Rail Chase 2 titlescreen says 1994, Cyber Troopers Virtual-On titlescreen says 1995.
https://segaretro.org/images/e/e8/RailChase2_title.png
https://segaretro.org/images/9/9d/Virtual_On_Model_2.png

Correct Rail Chase 2, Cyber Troopers Virtual-On years

---

src/mame/drivers/tetrisp2.cpp
src/mame/includes/tetrisp2.h
src/mame/layout/stepstag.lay
src/mame/layout/vjdash.lay
src/mame/mame.lst
src/mame/video/tetrisp2.cpp

Workable stepstag driver:
-Added fundamental communication between main 68000 and (undumped) Windows PC
-Figured out correct logic of data uploading from main CPU to (maybe an FPGA on some unknown board)
-Discovered proper V-blank frequency of 4 logigal screens(routed to 3 physical screens in real hardware), which effects the communication and synchronization between 2 68000 CPUs, thus affect booting
-Borrowed foreground graphics from vjdash, added proper foreground layer handling, and removed hack code
-Seperated palette and decoding of 3 screens, and added independent 3rd screen decoding/drawing routine, as each screen has their own palette, and may display totally non-related graphics
-Corrected sprite rom loading of step3
-Mapped dancing floor light, spot light, neon light, and key …

Workable Stepping Stage driver, and recently dumped VJDash [Naibo]

---

src/mame/drivers/xavix.cpp
src/mame/mame.lst

this one does a jump to a vector in ram in the interrupt routine, telling me that my irq enable is wrong.  so far every single XaviX dump has provided a little bit extra useful information :-)

new machines marked as NOT WORKING - Play TV Baseball 2 [Sean Riddle, Peter Wilhelmsen]

---

hash/fmtowns_cd.xml
hash/fmtowns_flop.xml

I have re-tested the non- and partially-working softlist items after Carl's latest changes, and promoted everything that works better now.
Also, I have added several new dumps to the softlists. Some are mine and some aren't, so here are the details:
Dumped by "known" people:
- Battle Chess [redump.org / r09]
- Cameltry [r09]
- Dragon Slayer - The Legend of Heroes [r09]
- Emit Vol. 1 - Toki no Maigo [redump.org / r09]
- Emit Vol. 2 - Inochigake no Tabi [redump.org / r09]
- Ku²++ [Tokugawa Corporate Forums / DamienD]
Unknown source (obtained from Japanese anonymous P2P services):
- Doda Mega-Mix!!!
- Oshare Club
- Rinkan Gakkou
- Sakura no Mori
(the last two are the same in the PC-9801 CD list; they are hybrid discs)
The Cameltry and LoH disks are protected, so the dumps were created with a …

 fmtowns softlists: update supported status, new dumps

---

src/devices/cpu/i960/i960.cpp
src/devices/cpu/i960/i960.h
src/mame/drivers/model2.cpp

* This fixes stalls in several Sega Model 2 games, these are Virtua Fighter 2, MotorRaid, Virtua Cop 2, Dynamite Cop, Dynamite Baseball, Dynamite Baseball '97, Fighting Vipers and Indy 500

i960.cpp: support for burst mode stalling save and restore [Angelo Salese]

---

src/devices/video/i8275.cpp
src/devices/video/i8275.h

"Previous commit" is https://github.com/mamedev/mame/commit/f652d21e167265bded620fab397f142d18bd7b45 
Fixes visuals in tim100, hp64k.   No change to dwarfd, mikromik, rc702, zorba, and radio86 clones. 
rt1715, sm1800 and ipds don't actually hook up the 8275 to DMAC (no MCFG_I8275_DRQ_CALLBACK defined) so nothing should change for them either way.
I could not test trs80dt1.

i8275: fix thinko in previous commit; make Preset Counters command useful

---

src/mame/drivers/olyboss.cpp
src/mame/mame.lst

With the BOSS B present, another set of disk images is available for testing.

olyboss.cpp: Add Boss B and C Z80 models

---

src/emu/addrmap.cpp
src/emu/addrmap.h
src/emu/emumem.cpp
src/emu/emumem.h
src/mame/drivers/tatsumi.cpp
src/mame/includes/tatsumi.h

The new cswidth address map constructor method overrides the masking normally performed on narrow-width accesses. This entailed a lot of reconfiguration to make the shifting and masking of subunits independent operations. There is unlikely to have any significant performance impact on drivers that don't frequently reconfigure their memory handlers.

Generalized support for byte-smeared accesses (nw)

---

src/mame/drivers/jclub2.cpp
src/mame/drivers/macs.cpp
src/mame/drivers/simple_st0016.cpp
src/mame/drivers/speglsht.cpp
src/mame/drivers/srmp5.cpp
src/mame/includes/simple_st0016.h
src/mame/machine/st0016.cpp
src/mame/machine/st0016.h

jclub2, srmp5: Accurate tags for what CPUs actually handling, configurated ST0016 ROM Bankswitching(jclub2)
macs, simple_st0016, speglsht : Minor cleanup bankswitching

st0016 : Add object finder m_rom instead memregion(":maincpu")

---

src/devices/sound/ymz280b.cpp
src/devices/sound/ymz280b.h
src/mame/drivers/firebeat.cpp
src/mame/drivers/vgmplay.cpp

firebeat.cpp : Minor cleanups, Split main CPU memory maps related for number of allocated gcu chips in PCB

ymz280b : Add device_rom_interface instead external memory handlers

---

src/mame/drivers/vegas.cpp

Also Original year is 1999 for service menu screen.
https://i.imgur.com/9CtCNpG.png
San Francisco Rush 2049: Tournament Edition year is 2000 in attract Mode.
https://i.imgur.com/sW2iGsz.png

Fix MT#6872

---

language/Portuguese_Brazil/strings.po

* New translations added, fixed
* Minor typo fix
* In Brazilian Portuguese we don't "audit" objects, we "audit" process, accounts, etc. This is why the term "Auditoria" as a function was changed to the verb "Aferir" that means "to assess", "julgar por meio de comparação; avaliar." or to estimate or judge the condition, that is what the software is doing, evaluating a file against a list to "assess" its condition, good or bad. The "Audit results" was set as "Condição" as a result of "Aferir" that reflect better the ROM state, BOA or RUIM.
TODO
* Deal with the "Parent" thing properly, that could be translated to "Principal" or something of that nature. The literal translation "Driver é Pai" doesn't help, this is the same as "Driver is the Father". We understand the meaning but it doesn't …

Update translation for Brazilian Portuguese

---

src/devices/bus/interpro/sr/gt.cpp

Tafoid reported an incorrect rom checksum. This corrects it, hoping it can be slipped in at the last minute for 0.195.

interpro: fix rom checksums (nw)

---

hash/interpro.xml
src/devices/cpu/clipper/clipper.cpp
src/devices/cpu/clipper/clipper.h
src/devices/cpu/clipper/clipperd.cpp
src/devices/cpu/clipper/clipperd.h
src/devices/cpu/clipper/common.h
src/mame/drivers/interpro.cpp
src/mame/includes/interpro.h
src/mame/machine/cammu.cpp
src/mame/machine/cammu.h
src/mame/machine/interpro_ioga.cpp
src/mame/machine/interpro_ioga.h

Many changes, most notable end result is the ability to boot the "blue screen" rebuild floppy, and nearly booting CLIX (hangs trying to mount the filesystems).
Summary of changes:
* added a softlist
* refactored cpu/mmu memory access
* added alignment faults
* implemented most c400 instructions
* fixed wait instruction
* corrections to interpro driver
* removed broken forced interrupt handling
* added support for dma virtual addressing

interpro: various improvements

---

src/devices/sound/c352.cpp
src/devices/sound/c352.h

- Change mulaw algorithm to match Namco's Wii VC emulator. This appears to be the original algorithm used in the hardware. The C352's mulaw algorithm is identical to the C219 (Which is currently not implemented in MAME, I will eventually fix that unless someone beats me to it)
- Fix static noise between fights in Tekken 3.
- Fix the order of the phase inversion flags.

Improve Namco C352 emulation

---

src/devices/sound/qs1000.cpp
src/devices/sound/qs1000.h
src/mame/drivers/eolith.cpp
src/mame/drivers/eolith16.cpp
src/mame/drivers/ghosteo.cpp
src/mame/drivers/limenko.cpp
src/mame/drivers/vamphalf.cpp
src/mame/drivers/vegaeo.cpp
src/mame/includes/eolith.h

Reverts mamedev/mame#3294
This breaks stuff because the MCS51 doesn't have proper emulated serial at the moment - it's still using hacked read8/write8.  Fixing the MCS51 serial is probably going to require changing the CPU core to work at S-cycle level.

Revert "qs1000.cpp : Convert set_irq, serial_in into WRITE_LINE_MEMBER"

---

src/devices/sound/qs1000.cpp
src/devices/sound/qs1000.h
src/mame/drivers/eolith.cpp
src/mame/drivers/eolith16.cpp
src/mame/drivers/ghosteo.cpp
src/mame/drivers/limenko.cpp
src/mame/drivers/vamphalf.cpp
src/mame/drivers/vegaeo.cpp
src/mame/includes/eolith.h
src/mame/video/eolith.cpp

eolith.cpp, eolith16.cpp, vegaeo.cpp : Cleanup vram handler/drawing pixel
eolith.cpp, ghosteo.cpp, limenko.cpp, vamphalf.cpp, vegaeo.cpp : Modernize soundlatches
eolith.cpp, eolith16.cpp, ghosteo.cpp, limenko.cpp, vamphalf.cpp, vegaeo.cpp : Minor cleanup, Add object finders instead runtime tag lookup, Replace user* -> saner ROM areas
limenko.cpp : Minor cleanup of sprite drawing
eolith.cpp : Add machine_config instead driver_init for hidctch3

qs1000.cpp : Convert set_irq into WRITE_LINE_MEMBER

---

src/mame/drivers/xexex.cpp
src/mame/includes/xexex.h

xexex.cpp : Minor cleanup, Add object finder instead runtime tag lookup, Add notes
Demote Xexex/Orius with MACHINE_IMPERFECT_GRAPHICS, because it has alpha blending issue.
Add MACHINE_NO_COCKTAIL flag too, because tilemap scroll is wrong when cocktail mode

xexex.cpp Update

---

src/mame/drivers/model1.cpp
src/mame/machine/m1comm.cpp

- VINT = VBLANK
- added memory and i/o masks
this fixes a possible buffer overflow if the z80 tries to access memory at d000-ffff
- ready-to-send flag is located at 0x0004, not 0x0005
this fixes wingwar getting stuck after link-up.

M1COMM: minor updates (nw)

---

src/mame/drivers/intv.cpp

Was running at 2X speed.  Measured and verified correct.

Corrected 6502 clock rate

---

hash/leapster.xml

Checked names against carts labels, game boxes and manuals (that includes screenshots).
The "Piñata Party" game includes the "ñ" on all locations (see https://images-na.ssl-images-amazon.com/images/I/91pswpnB-9L._SL1500_.jpg for a screenshot).

Regional game names fixes (Spanish special characters)

---

hash/pc98_cd.xml

- Updated the CD software list with everything from the latest update of
the Neo Kobe Collection (too many new entries to list in a commit
description).
- Tested all software list entries, added supported status and emulation
issues for each one. Some games need testing on real hardware to make
sure the issues are emulation-related; I'll do this at a later date.
- Added "usage" tag for games that require serials or manual protection.
- Added disk 2 of the floppy version of Brandish Renewal, since it's
used as a key disk for the CD version.
- Fixed copy-paste error (interface="fmt_cdrom") for hybrid discs copied
from the FM Towns list.
- Replaced the Sweet Days CHD with a properly converted one.
- Some minor consistency / spelling fixes on descriptions.

pc98_cd.xml: additions, testing & fixes

---

src/devices/machine/i8214.cpp

This solves most of screen corruption in ms6102 (8275 sometimes happens to set IRQ while INTE=0 in 8214, so interrupt is ignored and never handled.)

i8214: check pending interrupts when ETLG and INTE lines change (nw)

---

src/mame/drivers/arcadecl.cpp

arcadecl.cpp : Get rid unnecessary gfxdecode for sparkz_state, Fix Sparkz Year on documents

arcadecl.cpp Minor cleanups

---

src/mame/drivers/hp9k_3xx.cpp

The m68k emulation code throws two buserror exception during r-m-w opcodes
like ori #$0x40, (0x1234).b. This confuses the HP bootrom. Work around
that by storing the last read buserror address and compare it with the
write address. if they are the same, ignore the buserror.

hp9k_3xx: workaround double exception during r-m-w operations

---

src/devices/bus/hp_dio/hp98544.cpp
src/devices/bus/hp_dio/hp98544.h

HP Basic (and probably other OS') use the window mover to place letters
on the screen by moving them from non-visible memory to the screen. Add
basic support for that so that we have some output from HP basic. It also
implements cursor control.

Add basic window move support to hp98544 framebuffer

---

src/osd/modules/file/posixsocket.cpp

Without it you have to wait until the socket is moved
out of the TIME_WAIT state, which can take quite a while.
This is pretty anoying when using mame with serial ports
forwarded via TCP.

Set SO_REUSEADDR in posixsocket

---

src/mame/drivers/pasha2.cpp

pasha2.cpp : Cleanup duplicates, Cleanup bitmap write handlers, Add object finder instead runtime tag lookups, Fix tags, Hook up AT89C52, Add notes, Add output finders, Convert m_bitmap* into std::unique_ptr

pasha2.cpp Cleanups

---

hash/pc98_cd.xml

- Re-tested all software entries with video/audio issues, after the latest emulation improvements. Around 70% of them are considered "working" now.
- Demoted Miamisoft's games to non-working since they seem to hang randomly (it probably already happened before, I just didn't realize it).
- Tested some software entries on real hardware (PC-9821Nw150) to make sure the issues are emulation-related.
- Some minor title spelling fixes.

pc98_cd.xml: second round of testing

---

src/mame/drivers/coco12.cpp
src/mame/includes/coco12.h
src/mame/mame.lst

These real alternative systems have the upgraded HD6309E CPU in them.
The code that has been added was tested working in the official 0197 mame sources without problem.

Added real alternative systems cocoh, cocoeh, coco2h, and coco2bh

---

src/devices/sound/c6280.cpp

<<1 is same at patent, not +1 (reference:https://patents.google.com/patent/US4924744A/)

c6280.cpp : Fix LFO

---

src/devices/bus/sega8/sega8_slot.cpp

At least on Fedora Linux 27, the following happened when not using
XML-files:
mame sc3000 -window -cart /usr/share/mame/roms/sc3000/mpr-5998.ic1
Ignoring MAME exception: Unknown slot option 'codemasters' in slot 'slot'
Unknown slot option 'codemasters' in slot 'slot'
I suppose that was because Lode Runner ROM image was not correctly
detected. This patch adds a special case to detect Lode Runner
(Japan, Europe).

Fix Lode Runner SG1000/SC-3000 ROM image detection

---

src/devices/machine/tms9914.cpp
src/devices/machine/tms9914.h

Hi,
this PR is for a small change to tms9914 emulation. This change allows the HPIB test in IPC diagnostic ROM to pass.
HPIB test can be started by running IPC with "diagb" BIOS option. Once the screen has filled with messages from the RAM test, press F1 to interrupt the test sequence, then press F4 to run the HPIB test.
Thanks.
--F.Ulivi

tms9914: improved emulation

---

src/devices/machine/tms9914.cpp
src/devices/machine/tms9914.h

Hi,
this PR adds a way to read CONT & ACCRQ signals from TMS9914. The ability to read the former is needed for HP9000/300 emulation.
Thanks.
--F.Ulivi

tms9914: added methods to read ACCRQ & CONT output lines

---

scripts/src/video.lua
scripts/target/mame/mess.lua
src/devices/video/bt459.cpp
src/devices/video/bt45x.cpp
src/devices/video/bt45x.h

Basic implementation of various Brooktree RAMDAC devices. Two of these (bt457, bt458) are used by InterPro graphics boards currently under development, the others are unused/untested at this point.

bt45x: new devices

---

src/devices/cpu/tms32031/tms32031.cpp
src/devices/cpu/tms32031/tms32031.h

For some reason there was no TMS320C30 device, so it's been added. Stubbed in basic HOLD/HOLDA line/callback support which is used to suspend DSP external bus access, and used by the InterPro EDGE graphics boards under development. This change doesn't actually change the 'C30 behaviour yet, but allows the external device to get an acknowledgement and proceed.

tms32031: add tms320c30 and basic hold/holda support

---

src/devices/cpu/clipper/clipper.cpp

Implemented two compare and delayed branch instructions based on observed use in system software. No documentation has been found for these and other C400 instructions.

clipper: two more instructions (nw)

---

src/mame/layout/irrmaze.lay

- Added color lamps. On the real cabinet, these are behind the marquee.
- Fixed timer lamp order. They now follow the order of the test menu and match recorded footage.
- Changed size of screen, and most lamps to better match the real cabinet.
- Changed CPO button/trackball color to better match the real controls.

irrmaze.lay: added color lamps, accuracy improvements

---

src/mame/video/gime.cpp

This supercede PR#3268. It fixes a problem that was exposed when running "Temple Of ROM" on the coco3 drivers.

Coco3gimefixsam

---

src/mame/drivers/kangaroo.cpp
src/mame/drivers/markham.cpp
src/mame/includes/markham.h
src/mame/video/markham.cpp

Based from observations and Phil's comments on MAMEWorld the SUN 8212 dump should be absolutely good, no doubts from me about it. Actual MCU hookup will come later but in the meantime I've fixed up the fake protection kludge as a placeholder.
Major improvements to banbam and pettanp include the crash on level 11 being fixed (missing GFX command) and correct graphics for both machines; enemy spawn timing appears to be MCU related. Interesting stuff.

Improve simulated protection comms in banbam, mark MCU dump as good.

---

src/devices/machine/ncr5390.cpp
src/devices/machine/ncr5390.h

These changes work with InterPro, but haven't been tested on other machines. Despite this, I'm reasonably confident they are all correct according to the observed behaviour and the documentation.
* don't wait for REQ after initiator complete with NACK
* wait until fifo empty during dma out before command complete
* make sure drq is always cleared on bus/function complete
* reset happens immediately
* always clear TC0 when counter reloaded
* check valid commands separately for 5390 and 5390a
* handle 5390a initiator set attention command
* use logmacro for logging

ncr5390: several small but important changes (nw)

---

src/devices/machine/nscsi_bus.cpp

Only the lower 3 bits of the identify message contain the LUN.

nscsi_bus: minor fix (nw)

---

src/mame/drivers/interpro.cpp

With these rom dumps, the ip6000 now boots. Something is wrong with floppy interrupts, and EDGE isn't good enough to get to the blue screen, but FDM works moderately well.

interpro: add ip6000 roms (nw)

---

src/mame/drivers/megaplay.cpp

Demote Mega Play games with MACHINE_IMPERFECT_GRAPHICS, because Overlay bitmap is wrong ("insert coin(s)" letter, mega play logo, etc...)

megaplay.cpp : Add notes of overlay

---

src/devices/bus/isa/sblaster.cpp

Successfully tested in Scream Tracker 2.2.

sblaster: direct DAC mode

---

makefile
scripts/genie.lua

This patchset allows mame to build on riscv64:
http://fedora-riscv.tranquillity.se/koji/buildinfo?buildID=32386

Enable building on riscv64

---

hash/pc98.xml

- Added new entries from the Neo Kobe Collection:
2601 - Teikoku Kidoubutai no Koubou
3tsu no Negai
714 MIDI Jr.
714 MIDI Special
88 Kantai Monogatari
98 Eiwa Jiten
98 Stadium
98 Stadium 2 - Shouko no Chousen
PC-9801N/NS/NV Teiban Free Software Shuu - 98NOTE no Hissu Aminosan ** this one was already in the list with a translated title, I realized that after submitting the PR. I'm keeping the Japanese one for consistency.
- Corrected title of "Thousand Cranes". It's actually supposed to be a
person's name (Chizuru), not a literal translation of 千鶴.
- Relabeled disks with their actual names
- Added usage notes for software that needs DOS
- Removed user disks from games where they aren't included in the
original box, and the user is expected to …

pc98.xml: softlist updates, part 1 (numbers)

---

src/mame/audio/williams.cpp
src/mame/audio/williams.h
src/mame/drivers/williams.cpp
src/mame/includes/williams.h
src/mame/machine/williams.cpp
src/mame/video/williams.cpp

williams.cpp : Reduce runtime tag lookups, Add input_merger for interrupts, Reduce duplicates, Fix naming, Device'd palette for williams_state/blaster_state games, Split spdball Address map
audio/williams.cpp : Reduce runtime tag lookups, Cleanup duplicates

williams.cpp : Cleanups

---

hash/hp9k3xx_flop.xml
src/mame/drivers/hp9k_3xx.cpp

And remove the BASIC rom cards from the default config. As we can boot
from floppy now.

hp9k_3xx: add software list

---

src/devices/cpu/m68000/m68k_in.cpp

I was debugging why the 'HP9000/300 mainframe tests' where hanging on hp9k_3xx.
Debugger showed the following code:
move.l (a2)+, d0
move.l (a2)+, d1
move d6, ccr
divs.w d0,d1
loop: bcs.s loop
Clearly this tests whether the carry flag is cleared - the Motorola Reference
Manual says it's always cleared. However, in our implementation, it's not
cleared on overflow.
You can reproduce this with latest mame: ./mame64 -flop1 300test -debug

68k: fix carry flag clear in divs instruction

---

src/devices/cpu/m68000/m68k_in.cpp

The following test code from the 'HP9000/300 series mainframe tests'
fails:
lea bytes, a0
pack -(a0),-(a1), #$FEDC
move.b (a1),d0
cmbi.b #$E,d0
loop: bne.s loop
bytes: 0x41 0x42
It looks like most of the pack instructions have the byte order
wrong, but the pack dx,dy variant seems to have been fixed already.

68k: fix pack instructions

---

src/emu/debug/debugcmd.cpp
src/emu/debug/debugcmd.h
src/emu/debug/debughlp.cpp

The underlying implementation was already in place, but there was no command to access it, so this is fairly straightforward. I think the only contentious part might be the exact naming/syntax of the command itself, so feel free to adjust to suit taste. Functionality itself was verified and working nicely with InterPro.

debugger: add command for go_exception (nw)

---

src/mame/drivers/hp9k_3xx.cpp

add one hp9k3xx section that defines all the hardware that
is common between the /300 models.

hp9k_3xx: simplify machine configs

---

src/emu/debug/debugcmd.cpp

This makes these commands useful and consistent with dump in a virtual memory environment. One minor issue is what to do with save for an unmapped memory address: the approach taken here is to write the space.unmap() value, which seems the least harmful. On load, unmapped addresses are not written to, meaning that save/load with a constant address map work as expected.

debugger: make save/load support virtual memory (nw)

---

src/devices/machine/cs4031.cpp
src/devices/machine/cs4031.h
src/devices/machine/mc146818.cpp
src/devices/machine/wd7600.cpp
src/devices/machine/wd7600.h
src/mame/drivers/apollo.cpp
src/mame/drivers/micronic.cpp
src/mame/drivers/octopus.cpp
src/mame/includes/apollo.h
src/mame/machine/apollo.cpp
src/mame/machine/at.cpp
src/mame/machine/interpro_ioga.h

This change makes the MC146818/DS128x devices match the ASSERT_LINE/CLEAR_LINE protocol used by almost all other devices, removing an unexpected surprise. The devices are fairly widely used, so I've tried to review all the references and check if they're affected. A surprising number of systems appear to have the interrupt hooked up, but were not accounting for the inversion, so this change might possibly correct some existing behaviour if the interrupt is actually being triggered.
The following were modified to remove workarounds:
* src/devices/machine/cs4031: removed inversion
* src/devices/machine/wd7600: removed inversion
* src/mame/drivers/apollo: hooked up interrupt
* src/mame/drivers/micronic: removed inversion
* src/mame/drivers/octopus: removed inversion
* …

mc146818: correct interrupt protocol (nw)

---

src/mame/drivers/hp9k_3xx.cpp

The clock frequency is actually 8MHz.

hp9k_3xx: fix HIL clock frequency (nw)

---

hash/x68k_flop.xml

- New software list additions to Login Soft category
*(ldb_x68k conversion) is Converted archive from LOGiN Software Contest X68000 Kessaku Game-sen
ajisai&nbsp;&nbsp;&nbsp;Ajisai (ldb_x68k conversion)
camerot&nbsp;&nbsp;&nbsp;Camerot (ldb_x68k conversion)
choro2&nbsp;&nbsp;&nbsp;Choro Choro (Takeru version)
choro2a&nbsp;&nbsp;&nbsp;Choro Choro (ldb_x68k conversion)
cuartoa&nbsp;&nbsp;&nbsp;Cuarto (ldb_x68k conversion)
dungmana&nbsp;&nbsp;&nbsp;Dungeon Management (ldb_x68k conversion)
galseed2&nbsp;&nbsp;&nbsp;Galseed II (ldb_x68k conversion)
kurupon&nbsp;&nbsp;&nbsp;Kurupon
leshies&nbsp;&nbsp;&nbsp;Leshies (Takeru version)
overdrvr&nbsp;&nbsp;&nbsp;Over Driver (Takeru version)
programa&nbsp;&nbsp;&nbsp;Programan Ace -Source68
sekaissa&nbsp;&nbsp;&nbsp;Sekai-Seifuku Set (ldb_x68k …

x68k_flop: Add/Replace and Organize Login Soft Category

---

src/devices/bus/coco/coco_dcmodem.cpp
src/devices/bus/coco/coco_gmc.cpp
src/devices/bus/coco/coco_multi.cpp
src/devices/bus/coco/coco_orch90.cpp
src/devices/bus/coco/coco_rs232.cpp
src/devices/bus/coco/coco_ssc.cpp
src/devices/bus/coco/coco_t4426.cpp
src/devices/bus/coco/cococart.cpp
src/devices/bus/coco/dragon_fdc.cpp
src/devices/bus/ss50/interface.cpp
src/devices/bus/ss50/mpc.cpp
src/devices/bus/ss50/mps.cpp

According to the C++ standard 14.7 clause 5, "an explicit
instantiation definition shall appear at most once in a program".
Move the instantiation from the individual implementation files
to the interface implementation file.
This fixes issue #3639.
Signed-off-by: Stefan Brüns <stefan.bruens@rwth-aachen.de>

Avoid multiple explicit instantiations definition of templates

---

src/mame/drivers/unico.cpp
src/mame/includes/unico.h
src/mame/video/unico.cpp

Convert video RAMs into shared_ptrs, Reduce runtime tag lookups, Some ACCESSING_BITS Cleanups, PALETTE_DECODER for palette

unico.cpp : Variable cleanups

---

hash/x68k_flop.xml

- disk image was redumped because a disk image was broken.
blade of the great elements (test version) (1990)(amusement).dim (bgelmntt )
gradius ii gofer no yabou (demo) (1992)(konami).dim (gradius2d)
- Fevrie: added year and note.

x68k_flop: fix redump "bgelmntt" and "gradius2d"

---

src/devices/machine/upd765.cpp
src/devices/machine/upd765.h

Mostly tiying up and simplifying the i82072 behaviour; the only change that may potentially impact other upd765 users is marking the st0_filled after every interrupt-generating command ends, rather than only the non-data ones. This appears to be correct behaviour, and will only affect systems which actually do a "sense interrupt status" after a command-completion interrupt (like the InterPro does).
* report valid interrupt sense data after all interrupt-generating commands
* improve i82072 drive busy handling and motor control

upd765: i82072 fixes (nw)

---

src/mame/video/powervr2.cpp
src/mame/video/powervr2.h

PowerVR2 represents color using two components: a base color and an optional
offset color.  The base color is combined with the incoming texture sample (if
any) according to the fixed-function specified by the tsinstruction in the
per-polygon parameters, and then the offset is added to this color (with the
exception of alpha; the offset color has an alpha component but it does not
appear to ever be used).
The base color and offset color can be specified on a per-vertex basis (as
either a group of four 8-bit integers or a group of four single-precision
floating points) or they can be specified on a per-polygon basis (in
floating-point only) and then scaled based on per-vertex scalar values (also
floating point).
Before:
After:
Before:
After:
Before:
After:

PowerVR2: implement color

---

hash/x68k_flop.xml

- New software list additions to Login Soft category
Stein
- Replace disk images to Login Soft category
Galseed (Not included user data)
- Login Soft list is sorted in title order.
- More added release date to Login Soft list
- Added release date to The World of X68000 and II
- Rename alt_title (japanese) to The World of X68000 and II

x68k_flop: Added new/replace Login Soft list. and sorted

---

hash/pc88va.xml

This is my own dump of Tetris for the PC-88VA, taken from an original 5.25" disk. The PC-88VA driver doesn't work, of course, but I'd like to document it anyway in case something happens to the original disk or my computer.
It seems to have some kind of protection on track 1 side 0 (I see some non-standard sector IDs, variable sector sizes, and wrong CRCs) so I thought the HxC MFM format would be the safest choice.

pc88va.xml: add new dump

---

src/devices/bus/a2bus/a2applicard.cpp
src/devices/bus/a2bus/a2softcard.cpp
src/devices/bus/c64/cpm.cpp

Removes `MACHINE_CONFIG_START` macros.

z80: Remove some MCFG_ macros. (nw)

---

src/mame/drivers/1942.cpp

- Remove a few more `MCFG_` macros .
- Use `constexpr` instead of defining macro constants.

1942.cpp: More macro cleanup. (nw)

---

src/devices/video/315_5124.cpp
src/devices/video/315_5124.h
src/devices/video/315_5313.cpp
src/devices/video/315_5313.h
src/mame/drivers/megaplay.cpp
src/mame/drivers/megatech.cpp
src/mame/drivers/segae.cpp
src/mame/drivers/sms.cpp
src/mame/drivers/sms_bootleg.cpp

- Rename GG VDP from sega315_5378 to sega315_5377 to match maintenance manual
- Created a sega315_5313_mode4_device class to emulate some specific 315-5313 behavior in mode 4
- Derivate sega315_5377 (GG) and sega315_5313_mode4 (MD) from sega315_5246 (SMS2) instead sega315_5124 (SMS1)
- Emulate some specific sega315_5377 timings verified on hardware
- Emulate some sega315_5313_mode4 timings and behavior verified with Flubba's VDP Test
- Emulate bits of the status register for the number of the first sprite that overflows
- Emulate sprite zoom limit of sega315_5124 and sega315_5313 VDPs
- Fix inaccurate scrolling reproduced with Charles' scrolling test
- Improve leftmost column color behaviour in mode 4 when fine scroll is applied
- Implement display modes 1 (text) and 3 (multicolor)
- …

315_5124.cpp updates

---

src/devices/machine/nscsi_cd.cpp
src/devices/machine/nscsi_cd.h
src/emu/romload.cpp

Together, these changes enable softlist CD-ROM media changes for InterPro, and presumably other nscsi_cd systems. Haven't looked into how other CD-ROM devices work, but the romload fix should apply equally to them too.
* nscsi_cd: detect and respond to media changes
* romload: fix disk entry processing

nscsi_cd: support media changes (nw)

---

src/mame/drivers/playch10.cpp

Chip'n Dale: Rescue Rangers was released in June 8, 1990 in Japan and USA.

Fix MT06192

---

hash/x68k_flop.xml

"GJ" was original image file is "fortatgj"
(the world of x68000 (disk 1 of 3) - fortress attack &amp; gj.dim)
This image file is multi boot disk. Set drive 1 to boot "GJ".
"gj.dim" is drive 0 boot hack image.
(Same as "aahime")

x68k_flop: Sorry, Return to "GJ"

---

src/devices/video/psx.cpp
src/devices/video/psx.h

(Some real hardware using PSX GPU with SGRAM is connected with triple 8-bit video DAC; so Allow RGB24 display)

psx.cpp : device_palette_interface

---

src/frontend/mame/info.cpp

It currently looks like condition is an orphaned child of sound when it has no relation to it.

info.cpp: Adjust indent of condition.

---

src/mame/video/powervr2.cpp
src/mame/video/powervr2.h

In commit ec325ef I did something stupid from
a performance standpoint, which was to select the shading function on a
per-pixel basis even though it can only change on a per-polygon basis.  This
commit uses c++ templates and inline functions to so that the compiler's
constant folding can eliminate the switch statement that selects shading
functions (thus making the choice a per-polygon one).  I also did the same thing
for the texture and bilinear filtering checks.
This brings back a little less than half of the performance hit on my PC, so
things still aren't as fast as they used to be.
Benchmark (running a full cycle of Crazy Taxi NAOMI's attract) on my PC:
Before ec325ef: 30%
After ec325ef:  23%
With this commit:  26%
Regarding the other 4% of the drop, that is coming from the pixel …

powervr2.cpp: change some per-pixel branches into per-polygon branches

---

src/mame/video/pc9801.cpp

This makes text with the "blink" attribute actually blink instead of inverting the colors every few frames. Verified on real hardware.
Fixes the lingering blinking tile after battles in Akatsuki no Bizantira, the inverted text in several CD-ROM installers, and possibly other things.

pc9801: fix blink attribute

---

src/devices/cpu/tlcs870/tlcs870.cpp
src/devices/cpu/tlcs870/tlcs870.h
src/devices/cpu/tlcs870/tlcs870_ops.cpp

fix silly PSW trashing on interrupts, allow Register Bank to be shown in debugger
code now gets to the 'main loop' (starts at C3E0, jumps back there once it hits C6A3) and continues to execute that loop once it arrives there.

tlcs870 CPU fixes

---

src/devices/sound/x1_010.cpp
src/devices/sound/x1_010.h
src/mame/drivers/seta.cpp
src/mame/includes/seta.h
src/mame/video/seta.cpp

Convert X1-010 Address xor into lrw8
Simpler handlers
Implement calibr50 PCMMUTE, NVRAM
Currently dumped calibr50 is ver 1.01(Shown at regional warning screen), Correct this
Fix twineagl music(timing is related to screen framerate)
x1_010.cpp : Simpler handlers

seta.cpp : Various updates

---

src/mame/drivers/pacman.cpp

The gfx loading in clone Eyes (bootleg set 1) is not correct.
ROM_REGION( 0x2000, "gfx1", 0 )
ROM_LOAD( "9.bin",           0x0000, 0x0800, CRC(342c0653) SHA1(d07e3d4528b72e54a1b5dbed009cce765a5a086f) )
ROM_LOAD( "11.bin",          0x0800, 0x0800, CRC(aaa7a537) SHA1(571d981ed2aad62d7c7f2798e9084228d45523d4) )
ROM_LOAD( "10.bin",          0x1000, 0x0800, CRC(b247b82c) SHA1(8c10a8ef5e79b0b5fefad6eb77bfa68a0ca18035) )
ROM_LOAD( "12.bin",          0x1800, 0x0800, CRC(99af4b30) SHA1(6a0939ff2fa7ae39a960dd4d9f9b7c01f57647c5) )
Roms 9.bin + 11.bin are not rom "d5" and 10.bin + 12.bin are not rom "e5" of Eyes (US set 1)!
Eyes (US set 1):
ROM_REGION( 0x2000, "gfx1", 0 )
ROM_LOAD( "d5",           0x0000, 0x1000, CRC(d6af0030) SHA1(652b779533e3f00e81cc102b78d367d503b06f33) )
ROM_LOAD( "e5", …

Fixed gfx loading in Eyes (bootleg set 1)

---

src/mame/drivers/model2.cpp
src/mame/drivers/stv.cpp
src/mame/includes/model2.h
src/mame/includes/stv.h
src/mame/machine/315-5838_317-0229_comp.cpp
src/mame/machine/315-5838_317-0229_comp.h

the other games are likely going to need a different decipher / decrypt function (encryption is a 16-bit scramble applied over the top of the source data)
still plenty of room for improvement in the code, but getting this in while it works.
not promoted decathlete to working yet because performance on it is worse than Naomi and it has various quite major video emulation issues, eg. blending seems to be enabled on everything, that's unrelated to the encryption/compression tho.

Implement 315-5838 compression / encryption chip used by Decathete [Peter Wilhelmsen, Morten Shearman Kirkegaard, Samuel Neves, David Haywood]

---

src/devices/cpu/tlcs870/tlcs870.cpp
src/mame/drivers/hng64.cpp
src/mame/includes/hng64.h
src/mame/video/hng64_3d.hxx

adds dualport ram device (really just gets treated as RAM, but on a technical level, it should be a device so use the device)
convert fake IO handlers to 8-bit, and ports to 8-bit since the real IOMCU reads 8-bit ports, the DPRAM is also 8-bit, and this should make transition to proper emulation easier later.

 hng64 - add dpram device (nw)

---

src/mame/drivers/hng64.cpp
src/mame/includes/hng64.h

still some addresses need simulation tho
currently not reattached for racing games (which never worked ingame anyway)
need to look at IOCMU->MIPS IRQ I think

hng64: read a bunch of ports through the IO MCU instead of simulation

---

src/devices/machine/z80scc.cpp
src/devices/machine/z80scc.h

* /CTS, /DCD and /SYNC are represented as 1's in rr0 when asserted
* immediately deassert /RTS in some circumstances
* fix rr1 "all sent" status handling
* there is no ring indicator input line
* generate interrupts for /SYNC input

z80scc: serial control signal fixes

---

hash/interpro.xml
src/devices/machine/z80scc.cpp
src/mame/drivers/interpro.cpp
src/mame/includes/interpro.h
src/mame/machine/interpro_ioga.cpp
src/mame/machine/interpro_ioga.h

These fixes enable booting and CLIX installation on headless InterServe systems (InterPro systems without graphics) using a VT100 or VT220 compatible terminal on serial port 2 (0 for ip6000). It's now possible to install and boot CLIX on the ip6000 system, as this works around the issues with the incomplete graphics hardware support in the driver.
* interpro: tidy serial configuration, add missing control lines
* interpro_ioga: fix serial dma
* z80scc: update /WREQ when transmitter is enabled/disabled, use 0 for assert state of active low output
* softlist: added 60x0 CLIX root floppies

interpro: headless configuration working

---

src/devices/sound/zsg2.cpp
src/devices/sound/zsg2.h
src/mame/audio/taito_zm.cpp

zsg2.cpp: implement emphasis filter, this is a noise reduction scheme
that amplifies higher frequncies to reduce quantization noise.
zsg2.cpp: Add sample interpolation and another adjustable lowpass
filter. This seems to be roughly what real hardware does...
zsg2.cpp: Improve panning registers and identify DSP output gain
registers.
Some issues still:
Sound volume appears off for some songs due to the DSP not being hooked up. the ZSG sends two separate audio streams to the DSP, which process the audio that is then mixed with the "bypass" outputs from the ZSG.
ZSG-SPU volume balance seems to vary a lot between games. Maybe cam900 cauld look into that.

Improve Taito Zoom ZSG-2 sound emulation

---

hash/pc98.xml

- Added new entries from the Neo Kobe Collection:
A Ressha de Ikou III HD - Hard Disk Only
A Ressha de Ikou 4 ~ Take the A-Train IV - Map Construction + Power Up Kit
A Ressha de Ikou 4 ~ Take the A-Train IV - Map Construction + Power Up Kit (Cracked)
Alone in the Dark 2
Akiko - Premium Version
Albatross
Albatross - Expert Course
Albatross - Meimon Course I - Oak Hills
Albatross - Visual Course
Albatross - World Course
Alvaleak Boukenki
Amaranth II
Amaranth II (Alt System Disk)
Ambition
Ami - Kaze Tachinu
Ancient Dragon
Angel Army
Animahjong X Perfect File
Animahjong X Perfect File (Alt)
Art of War
Art of War - Kaisenban
Art of War Scenario Shuu
Assist Art - Paint Master
Animation Editor 'da Vinci-98'
Dragons of Flame
- Relabeled disks with …

pc98.xml: softlist updates, part 2 (A)

---

src/devices/video/hp1ll3.cpp
src/devices/video/hp1ll3.h
src/mame/drivers/hp_ipc.cpp

Hi,
this PR has a few more improvements to HP1LL3 GPU. The main features I added are:
+ Configurable VRAM size (as HP-9807 & 9808 have different amounts of VRAM)
+ Auto-configuration of video size & timing
+ Some minor commands used by diagnostic code.
The GPU emulation can now pass both diagnostic tests (in the diagnostic disc & the "diagb" ROM).
As for the regressions in video appearance reported by Tafoid I think that I fully addressed them.
Hopefully this time I was more consistent with the original coding style.. sorry about last PR.
Thanks.
--F.Ulivi

HP1LL3: more improvements

---

src/mame/drivers/hng64.cpp
src/mame/includes/hng64.h

mainly splitting peripheral handlers up a bit rather than having them all in one switch case.

hng64 refactoring

---

src/devices/video/315_5124.cpp
src/devices/video/315_5124.h

- fix off-by-one bug of the sprite zoom limit used by the 315-5124 and 315-5313 VDPs
- fix tile and line numbers used by the 315-5124 VDP to draw the left-most pixels
- change the sprite collision code for the 315-5313 VDP to avoid flag it twice on the same line
- move some lines back to their previous location

315_5124.cpp minor fixes to previous changes

---

src/devices/video/hp1ll3.cpp
src/devices/video/hp1ll3.h

Hi,
this PR adds the implementation of bit offset in RDWIN/WRWIN GPU commands. This addition fixes an annoying "double cursor" defect in rendered video.
I've also added a table of GPU commands for reference.
Thanks.
--F.Ulivi

A small improvement/bug fix in HP1LL3 GPU driver

---

src/devices/machine/dp8390.cpp

Explicitly allow traffic to the AppleTalk broadcast address (`09:00:07:ff:ff:ff`) in `dp8390`'s `recv()`.
Fixes #3871

dp8390: allow AppleTalk broadcast through recv()

---

src/devices/cpu/tms57002/tmsinstr.lst
src/mame/drivers/konamigx.cpp

tms57002: Change flag instructions back to type "2b" [nw]
konamigx: Hook up channels 3,4 of TMS57002. The Lethal Enforces II
schematics are not complete so I couldn't figure out exactly how they
are connected to the sound chips and the DAC, but this sounds OK for
now.

tms57002, konamigx: fix regression

---

src/devices/video/bt459.cpp
src/devices/video/bt459.h

Use a simplistic multiply to simulate contrast control. InterPro systems write to a "virtual contrast DAC" register/latch of some kind, which presumably adjusts the reference voltage produced by the Bt438 before it enters the RAMDAC; this approximation is very crude, however it's simple and produces a satisfactory visual result.

bt459: add contrast control (nw)

---

src/mame/includes/apollo.h

This fixes the following compiler error:
```
1>c:\mame\src\emu\devfind.h(588): error C2680: 'screen_device *': invalid target type for dynamic_cast
1>c:\mame\src\emu\devfind.h(588): note: 'screen_device': class must be defined before using in a dynamic_cast
1>c:\mame\src\emu\devfind.h(580): note: while compiling class template member function 'bool device_finder<screen_device,true>::findit(bool)'
1>c:\mame\src\mame\includes\apollo.h(463): note: see reference to class template instantiation 'device_finder<screen_device,true>' being compiled
```

apollo.h: Fix C2680 compiler error in Visual Studio

---

src/mame/drivers/opwolf.cpp

previously it was calling
opwolf_cchip_init();
which called
m_cchip_timer = timer_alloc(TIMER_CCHIP);
m_cchip_timer->adjust(attotime::from_hz(60), 0, attotime::from_hz(60));
which in turn overrode some of the emulated behavior with the simulation (including coin counter writes)
this is why I personally think it's best to keep clean code, and remove the old simulations, leaving the old MAME versions as reference for them, but I don't feel it's my place to remove it.

actually properly disable opwolf protection simulation, fix coin counters (nw)

---

src/mame/drivers/williams.cpp

Seems to be a "Moogly" typo in MAME 0.201... It was just a joke ;)

Fixed Speed Ball P1 START

---

src/mame/drivers/raiden2.cpp

so that we can more easily see which just differ by region byte, make it clear what features determine game type (normal, easier, harder)
identified new dump that was added as 'harder' based on tanks on the first bridge

group Raiden 2 / DX sets by code revision 

---

src/devices/machine/6840ptm.cpp
src/devices/machine/6840ptm.h

In Dual 8 bit mode the output isn't inverted on
every TC, instead it's low until the count reaches 0xff, and
high afterwards.

Fix output pins in Dual 8 bit mode (nw)

---

src/devices/sound/zsg2.cpp

zsg2.cpp: update documentation
This should fix the popping that sometimes happens at the beginning of raystorm song 12 (Slaughter Hour). Remaining noise in this game (and gdarius) is likely due to bad sample ROM dumps.

zsg2.cpp: properly reset emphasis filter state at key on

---

src/mame/includes/pacland.h
src/mame/video/pacland.cpp

Fixed the difference with real hardware:
- fixed: incomplete priority of sprites on fg
- fixed: sprites could not be displayed at the bottom of the screen

pacland: sprites bugfix

---

src/devices/machine/i82586.cpp
src/devices/machine/i82586.h
src/emu/dinetwork.cpp
src/emu/dinetwork.h
src/osd/modules/netdev/pcap.cpp
src/osd/modules/netdev/taptun.cpp
src/osd/osdnet.cpp
src/osd/osdnet.h

These changes combine to make InterPro networking work on Windows with the TAP-Windows6 driver.
* osdnet: add a receive delay (1 frame) after transmit to avoid a time-travel problem
* taptun: pad short Ethernet frames and append FCS (Windows-only until Linux taptun behaviour is verified)
* clipper: fix bugs in carry flag handling, prefer sign bit for tests
* i82586: fix transmit bug, handle reset

interpro: notworking -> networking

---

src/mame/drivers/taitogn.cpp

Because Taito GNET System uses PSX GPU device, and imperfect graphics flag into PSX GPU device

Removed Usagi imperfect graphics flag

---

src/mame/drivers/funybubl.cpp
src/mame/includes/funybubl.h
src/mame/video/funybubl.cpp

Cleanup naming, Convert tilemap, Add address_map_bank_device for banked vram, Cleanup OKI banking, Fix OKI clock related to On-PCB XTAL, Add palette decoder member for palette, Cleanup/fix naming, Fix palette entry, Reduce runtime tag lookups

funybubl.cpp : Update/Cleanups

---

src/mame/video/fuukifg2.cpp
src/mame/video/fuukifg3.cpp

prevents MAME from crashing trying to access tilemap[0x42] instead of tilemap[0x3]

fix cam900 damage in fuukifg2 / fg3 from May

---

src/mame/video/powervr2.cpp
src/mame/video/powervr2.h

PowerVR 2 treats opaque polygons as a separate class of polygon from transparent polygons.  Pixels rasterized from opaque polygons are always completely opaque regardless of what their alpha values are.
This PR resolves missing graphics in games which render opaque polygons with non-opaque alpha values.
There's also a third class of polygon called punch-through, which supports transparency but not blending (so every pixel is either entirely opaque or entirely transparent).  Those haven't been implemented, and are still being treated as if they were transparent polygons.
Before:
After:
Before:
After:

powervr2.cpp: implement opaque polygons

---

src/mame/drivers/argus.cpp

Text ROM was overdumped (although both halfs were not identical, having two different bytes). The ROM socket on the PCB was labeled as "27128", pointing that the new size is the right one.

Redumped and corrected Text ROM "vt_07.bin" [Tomas Garcia-Meras (ClawGrip), Roberto Fresca, Recreativas.org, The Dumping Union]

---

src/devices/machine/ncr5390.cpp

This gets sun4 slightly further along.

ncr5390: enable dma for command completion (nw)

---

src/mame/includes/pacland.h
src/mame/video/pacland.cpp

Currently, when drawing the topmost-sprites, only draw non-transparent pixels of fg, but originally it is correct to draw the whole screen.
However, it is necessary to keep sprite-sprite priorities intact.
I think that approached the real hardware behavior.
Also, I was able to reduce unnecessary bitmap memory area.

pacland.cpp: Changed to approach real hardware behavior

---

docs/source/commandline/commandline-all.rst

I've noticed this while I was translating the manual.

Add missing short commands

---

src/lib/formats/tzx_cas.cpp

Not only when pause from block is greater than zero .
Otherwise the last pulse is not terminated properly in some cases.

tzx_cass.cpp: 1ms pause is always required

---

src/lib/formats/dsk_dsk.cpp

FDC will read the data if SK bit is not set.
Fixes MameTesters bug #07081

dsk_dsk.cpp: sectors must be read even if it contains deleted mark

---

src/mame/drivers/tehkanwc.cpp

After another two "tehkanwch" boards were found and dumped (where this ROM matched the parent) and a deeper analisys from Roberto Fresca (who thinks that it was a bitrot, since it was a nonsense modification of a sprite), I've changed the ROM #9 (gfx1) to match the parent, as found on the new dumps.

Corrected "tehkanwch" gfx1 ROM (nw)

---

hash/c64_flop.xml

Three new dumps from original floppies.
Kryoflux RAW images are on archive.org
https://archive.org/details/BillBudgePinballConstructionSetCommodore64.7z
https://archive.org/details/JingleDiskHolidayMusicalStoryWithComputerAnimationCommodore64AndAppleIIc.7z
https://archive.org/details/Sargon3Commodore64AndAtari8bit.7z

c64_flop.xml - Add a few new dumps

---

src/mame/drivers/flkatck.cpp
src/mame/includes/flkatck.h
src/mame/video/flkatck.cpp
src/mame/video/k007121.cpp

Was using work RAM as sprite drawing base instead of the actual sprite RAM.

flkatck.cpp: fix sprite-sprite priorities and removed hackish implementation in k007121 [Angelo Salese, Dink]

---

src/mame/drivers/ibmpcjr.cpp

Add null_modem and terminal to serial port options for ibmpcjr driver.

Add null_modem and terminal to serport options.

---

src/mame/drivers/itech8.cpp
src/mame/includes/itech8.h
src/mame/video/itech8.cpp

Convert sound latch into generic_latch_8_device, Reduce runtime tag lookup, ACCESSING_BITs, Remove unnecessary GROM pointer, Make bankswitch reset to 0 is only affected at Main CPU ROM is banked, Split address map related to bankswitch, Function difference, Fix spacing

itech8.cpp : Cleanups

---

src/mame/drivers/pacman.cpp
src/mame/mame.lst

Crock-Man (Marti Colls bootleg of Rene Pierre Crock-Man) [A.R.P.A., Recreativas.org]
Ms. Pac-Man (Marti Colls bootleg) [A.R.P.A., Recreativas.org]
Pac Man (bootleg, Famaresa) [Marcos75, Recreativas.org]
Those are mainly hacks to remove original logos and texts, but have some historical importance:
-Marti Colls is the founder of ITISA, but also worked doing conversions for Falgas (https://www.falgas.com/), a well known Spanish kiddie-ride manufacturer (see the website for reference). He started on the 70s with electromechanical games, following on the 80s manufacturing arcade PCBs and creating conversion kits. 
-FAMARE S.A. was a jukeboxes manufacturer who entered the arcade market by bootlegging arcade hardware and hacking its software. They made lot of …

New WORKING clones

---

src/devices/bus/coco/coco_pak.cpp
src/mame/machine/6883sam.cpp
src/mame/machine/coco_vhd.cpp
src/mame/video/gime.cpp

This fixes Zumwalt bank switching implemented in cartridges when used with all the CoCos.
This fixes the 32k external cartridge ROM mode on the CoCo 3. (Issue #2746)
Software lists are not broken, but they are also not required. If you map in the right hardware with the right ROM it will work.

General CoCo Cartridge Fixes

---

src/mame/includes/m52.h
src/mame/video/m52.cpp

- Sprite priority is incorrect.
- Position of the background (distant mountains, hills, and cityscape) is different from the real hardware.
- Cross-hatch test pattern is incorrect.
- Flip screen is incorrect.
Title
Sprite
Cross-hatch
Flip screen
Real hardware
http://youtu.be/F3_q-AN4AQM

mpatrol: Improved graphics problems

---

src/mame/drivers/norautp.cpp

Drews Revenge (v.2.89, set 2) is a clone of Drews Revenge (v.2.89, set 1).
I compared both DASMs and they have only different JUMP addresses.
Download the DASMs files with instructions on how to compare them
with the awesome WDiff program:
http://www.mameworld.info/mameinfo/download/Drews Revenge (set 1 and 2)-DASM.7z

Drews Revenge set 2 is a clone

---

src/mame/drivers/neogeo.cpp
src/mame/mame.lst

MVS-TEMP 'SubSystem Ver1.4' (Nazca development board) [Brian Hargrove]
we don't really know what this was used for, or what to even call it, these are the pictures of it that he uploaded to his twitter account
http://mamedev.emulab.it/haze/reference/withcase.jpg
http://mamedev.emulab.it/haze/reference/prgboard_side1.jpg
http://mamedev.emulab.it/haze/reference/prgboard_side2.jpg
http://mamedev.emulab.it/haze/reference/m1board_side1.jpg
http://mamedev.emulab.it/haze/reference/m1board_side2.jpg
http://mamedev.emulab.it/haze/reference/m1board_side2_close.jpg
it's likely meant to be used with some PC-side software or something.

new machines marked as NOT WORKING

---

src/mame/drivers/3do.cpp

"1995 American Laser Games" text at $2abeb4c in the extracted orbatak.chd CD-ROM.
Also Youtube video with year and manufacturer: https://www.youtube.com/watch?v=bdBO_ZSIqeE
Additionall infos: http://emuconsoleexploitnews.blogspot.com/2010/06/orbatak-cancelled-3do-arcade-game.html

Orbatak year and manufacturer

---

src/devices/cpu/m68000/m68k_in.cpp

From
https://github.com/kstenerud/Musashi/commit/df0fb402a8042c964a70cb987fe6f27ff96952ef
and
https://github.com/kstenerud/Musashi/commit/a16bd2bb289ea2cdbb1ca11a997490774eb32b5e

m68k: fix andi,ori,eori instruction (nw)

---

src/devices/machine/6840ptm.cpp
src/devices/machine/6840ptm.h

Two problems in dual byte mode:
- the high time flag is the same for all counters
- high time flag is reset on each counter reload, but should
only be reset if the timer is reload by the user.

6840: fix dual byte mode once again (nw)

---

docs/source/techspecs/nscsi.rst

* Those chapter numbers are auto generated by sphinx
* Fix chapter numbers not in sync with the rest of the documentation
* Fix the chapters not been bold like the rest of the documentation
* Change the last two chapters to keep up with the document consistency
* Fix missing bold for `nscsi_full_device`

Fixed broken document structure

---

src/emu/emuopts.cpp

I found a bug in the handling of command line media options.
When adding a second serial port (null_modem) to the CoCo drivers, the user interface (and -listmedia) reported the media options as bitbanger1 and bitbanger2. This is correct.
But the command line would not recognize the option bitbanger1. The switches exposed were bitbanger and bitbanger2. This seemed to be an error.
I found the problem in emuopts.cpp, get_full_option_names(). It was adding the canonical name for the first option only if the image_type() matched the instance_name(). 
In the case of a cartridge port, this would compare "cartridge" with "cartridge". It would then construct the canonical name "cartridge1" and make it available to the command line.
In the case of serial ports the function compared "bitbanger" to …

Fix canonical command line option.

---

src/devices/bus/hp_dio/hp_dio.h
src/mame/drivers/hp9k_3xx.cpp

And while at it, set the cards as non-fixed, as all of our default cards can be removed on real hardware

hp_dio: remove MCFG

---

scripts/src/bus.lua
src/devices/bus/hp_dio/hp_dio.h
src/devices/bus/hp_dio/human_interface.cpp
src/devices/bus/hp_dio/human_interface.h
src/mame/drivers/hp9k_3xx.cpp

On HP9000/300, these modules where always a logical unit connected to
the DIO bus. On some systems this was even a seperate DIO module. Lets
represent this in software. It also cleans up hp9k_3xx.cpp.

hp9k_3xx: move Sound, GPIB, Keyboard and RTC to human interface module

---

src/osd/sdl/window.cpp

Disable setting the SDL_WINDOW_OPENGL extra flag if -video none is set.  This allows a true headless run when the environment variable SDL_VIDEODRIVER=dummy is set prior to mame/mess execution.

Disable setting the SDL_WINDOW_OPENGL extra flag if -video none

---

src/mame/drivers/hp9k_3xx.cpp

/332 was missing DIO slots, /310 had no human interface. While at it,
deduplicate the code a bit.

hp9k_3xx: cleanup dio config

---

src/devices/machine/msm58321.cpp
src/devices/machine/msm58321.h
src/emu/dirtc.cpp

msm53821:
- add standard register support
- use std::array
- fix several counter to behave like a real MSM53821

rtc: add leap year support (nw)

---

src/devices/machine/tms9914.cpp
src/devices/machine/tms9914.h

hp9000/300 sends FEOI directly after the data register write,
before the byte is actually transmitted. This leads to the current
byte being sent out with EOI set, instead of the last one.

tms9914: latch EOI flag until next byte is sent

---

src/devices/machine/am79c90.cpp
src/devices/machine/am79c90.h

Change handling of reserved bits in CSR1 and CSR2 (assumed to be due to differences between original NMOS LANCE and CMOS LANCE), enabling MIPS Rx2030 diagnostics to pass.

am79c90: added am7990 variant (nw)

---

src/mame/drivers/atetris.cpp
src/mame/mame.lst

Tetris (bootleg set 4, with UM3482) [Asayuki Kizuyomina, ClawGrip]
I'm adding this just to save some time just in case anyone wants to work on it. The Z80 isn't hooked up, and the UM3482 is unemulated.

New WORKING clone

---

src/devices/machine/nscsi_bus.cpp
src/devices/machine/nscsi_cd.cpp
src/devices/machine/nscsi_hd.cpp

The default debug settings are filling up error.log pretty quick
when booting SCSI machines like hp9k_3xx. Disable debug in the
default settings, it can still be enabled if some dev/user wants
to debug NSCSI.

NSCSI: disable debug

---

src/emu/save.h

In file included from /usr/include/X11/extensions/XInput.h:53:0,
from ../../../../../src/osd/modules/input/input_x11.cpp:18:
../../../../../src/emu/save.h:95:32: error: expected unqualified-id before numeric constant
static constexpr std::size_t COUNT = 1U;
^
../../../../../src/emu/save.h:102:32: error: expected unqualified-id before numeric constant
static constexpr std::size_t COUNT = N * array_unwrap<T>::COUNT;
^
../../../../../src/emu/save.h:109:32: error: expected unqualified-id before numeric constant
static constexpr std::size_t COUNT = N * array_unwrap<T>::COUNT;
^
../../../../../src/emu/save.h: In member function ‘void save_manager::save_item(device_t*, const char*, const char*, int, ItemType&, const char*)’:
../../../../../src/emu/save.h:154:142: error: expected unqualified-id …

Fix compile error on Linux with NO_USE_XINPUT=0

---

src/emu/rendutil.cpp

Use boolean `TRUE` instead of bool `true` for libjpeg functions. Fixes build failure:
```
../../../../../src/emu/rendutil.cpp:580:2: error: no matching function for call to 'jpeg_read_header'
jpeg_read_header(&cinfo, true);
^~~~~~~~~~~~~~~~
In file included from ../../../../../src/emu/rendutil.cpp:16:
/opt/local/include/jpeglib.h:1039:13: note: candidate function not viable: no known conversion from 'bool' to 'boolean' for 2nd argument
EXTERN(int) jpeg_read_header JPP((j_decompress_ptr cinfo,
^
```

Use boolean not bool for libjpeg functions

---

src/mame/video/warpwarp.cpp

Fixed the player 2 shot (or ball) offset in cocktail mode is wrong.

warpwarp.cpp: Fixed the player 2 shot (or ball) offset in cocktail mode is wrong.
