mamedev/mame

src/mame/drivers/naomi.c
src/mame/mame.lst

Shakatto Tambourine (Rev B) (GDS-0002B) [rtw, ShouTime]
naomi.c: game name corrections & docs [MetalliC]
note: key PIC is missing and WANTED!

new NOT WORKING

---

src/mame/drivers/segajw.c

Internal credits give a copyright date of 1991

Update segajw year (nw)

---

src/mame/drivers/naomi.c
src/mame/mame.lst

removed "Rev C" label from name, vstrik3c set is original release

naomi.c: redumped vstrik3c, both existing and new dumps were BAD, made one good-looking from them [ANY, MetalliC]

---

src/emu/machine/jvshost.c
src/mame/machine/mie.c
src/mame/machine/mie.h

(case of last message byte is special 0xD0 value)

JVS host: real fix for "CRC errors"

---

src/osd/sdl/sdl.mak

Fixes build on NetBSD.
Signed-off-by: Thomas Klausner <wiz@NetBSD.org>

Define network API to use on NetBSD.

---

src/osd/modules/debugger/debugosx.m
src/osd/modules/debugger/osx/debugconsole.h
src/osd/modules/debugger/osx/debugconsole.m
src/osd/modules/debugger/osx/debugview.h
src/osd/modules/debugger/osx/debugview.m
src/osd/modules/debugger/osx/debugwindowhandler.h
src/osd/modules/debugger/osx/debugwindowhandler.m
src/osd/modules/debugger/osx/deviceinfoviewer.h
src/osd/modules/debugger/osx/deviceinfoviewer.m
src/osd/modules/debugger/osx/devicesviewer.m
src/osd/modules/debugger/osx/disassemblyview.h
src/osd/modules/debugger/osx/disassemblyview.m
src/osd/modules/debugger/osx/disassemblyviewer.h
src/osd/modules/debugger/osx/disassemblyviewer.m
src/osd/modules/debugger/osx/memoryview.m
src/osd/modules/debugger/qt/dasmwindow.c
src/osd/sdl/sdl.mak

Yes, it's still more work on the debuggers:
* Qt debugger allows breakpoint control and run-to-cursor from disassembly window for inactive CPUs
* Better mouse handling and window auto-sizing in Cocoa debugger
* Device detail windows in Cocoa debugger (double-click a device in the tree to see details)
* Allow copy/paste to/from OS clipboard in Cocoa debugger views (use context menu)

Another round of debugger improvements

---

hash/pasogo.xml

Transcribed from http://i.imgur.com/s3aT0OQ.jpg

Adding names to undumped game list

---

src/osd/sdl/man/castool.1
src/osd/sdl/man/chdman.1
src/osd/sdl/man/floptool.1
src/osd/sdl/man/imgtool.1
src/osd/sdl/man/jedutil.1
src/osd/sdl/man/ldresample.1
src/osd/sdl/man/ldverify.1
src/osd/sdl/man/mame.6
src/osd/sdl/man/mess.6
src/osd/sdl/man/romcmp.1
src/osd/sdl/man/testkeys.1

Bumps version and fix a couple of options description. Please merge before 0.160, thanks!

Updated *nix manpages to forthcoming 0.160

---

docs/luaengine.md
src/emu/luaengine.c
src/emu/render.c
src/emu/render.h
src/emu/ui/ui.c

This PR contains a couple of bugfixes related to luaengine screen drawing, and initial documentation on how to use the lua API.
(cc @galibert who previously reviewed #129)

luaengine: screen drawing fixes and initial docs

---

src/emu/machine/i8257.c
src/mess/drivers/imds2.c
src/mess/includes/imds2.h
src/mess/mess.lst
src/mess/mess.mak

Hi,
I've just completed a first version of an Intel Intellec MDS series-II system emulator for MESS. It is not complete but it's usable.
Since this is my first contribution to MESS, I'd like to know how to send the relevant ROM images to enable testing, please.
Is it correct to send everything to code@mamedev.org as suggested in "Submitting source code" page of MAME wiki? Should I attach everything instead to a pull request ?
Thanks.
F.Ulivi

A new MESS driver: Intel Intellec MDS series-II

---

src/mame/machine/midikbd.c

fix kbm3rd keyboard error(nw)

---

src/osd/sdl/man/castool.1
src/osd/sdl/man/chdman.1
src/osd/sdl/man/floptool.1
src/osd/sdl/man/imgtool.1
src/osd/sdl/man/jedutil.1
src/osd/sdl/man/ldresample.1
src/osd/sdl/man/ldverify.1
src/osd/sdl/man/mame.6
src/osd/sdl/man/mess.6
src/osd/sdl/man/romcmp.1
src/osd/sdl/man/testkeys.1

Updated man pages to forthcoming 0.161. Please merge, thanks! :-)

*nix man pages: Added new options to select debugger font face and size

---

src/osd/sdl/man/castool.1
src/osd/sdl/man/chdman.1
src/osd/sdl/man/floptool.1
src/osd/sdl/man/imgtool.1
src/osd/sdl/man/jedutil.1
src/osd/sdl/man/ldresample.1
src/osd/sdl/man/ldverify.1
src/osd/sdl/man/mame.6
src/osd/sdl/man/mess.6
src/osd/sdl/man/romcmp.1
src/osd/sdl/man/testkeys.1

Update version to 0.162 in *nix pages. Please merge, thank you.

Bump version on *nix man pages.

---

scripts/src/cpu.lua
scripts/target/mame/mess.lua
src/emu/cpu/hphybrid/hphybrid.c
src/emu/cpu/hphybrid/hphybrid.h
src/emu/cpu/hphybrid/hphybrid_dasm.c
src/emu/video/i8275.c
src/mame/mess.lst
src/mess/drivers/hp64k.c

Hi,
I'm working on a driver for hp 64000 dev. system. This is my first version. It works in diagnostic mode but it cannot load OS because floppy interface is not implemented yet.
Beside the driver proper, I wrote the CPU emulator for this system (HP model 5061-3011, a part of so-called "hybrid" series).
If you approve the merge, let me know where I should send the ROM images for testing, please.
-- F.Ulivi

New driver for hp 64000 development system

---

hash/i7000_card.xml
scripts/target/mame/mess.lua
src/mame/mess.lst
src/mess/drivers/i7000.c

Thanks Alexandre Tabajara for all of the info provided

Itautec I7000 (brazilian computer from 1982)

---

src/emu/cpu/avr8/avr8.c
src/emu/cpu/avr8/avr8.h
src/mess/drivers/uzebox.c

(It works but with terrible performance. Uzebox's DrMario song is recognizable even though the sound is choppy, full of noise).

uzebox: adding sound emulation

---

src/mess/drivers/spc1000.c

Centronics printer support. It works fine.

[MESS] spc1000 added the centronics printer port

---

src/mame/mess.lst
src/mess/drivers/apple2.c

Both english and brazilian portuguese versions of the system ROMs.

Unitron AP II: New Brazilian Apple 2 clone

---

src/mame/mess.lst
src/mess/drivers/coleco.c

Thanks to Cláudio Cassens, Eduardo Luccas and Jogos80.com.br

Microdigital ONYX: new colecovision prototype (unreleased).

---

src/osd/sdl/window.c

Revert "In SDL version, fix refresh rate setting in fullscreen"

---

src/mame/machine/m1comm.c
src/mame/machine/s32comm.c

https://www.youtube.com/watch?v=bSH-4yD3xQ4

S32COMM: fix stadium cross link (nw)

---

src/mame/drivers/thunderx.c

Verified against Thundercross and Super Contra PCBs

Corrected viewable screen area as per bug 05593

---

src/mame/drivers/crimfght.c

Corrected viewable display as per bug 05973

---

makefile
scripts/genie.lua
scripts/src/3rdparty.lua

This commits allows to use system PortAudio

Added ability to use system PortAudio

---

src/osd/sdl/man/castool.1
src/osd/sdl/man/chdman.1
src/osd/sdl/man/floptool.1
src/osd/sdl/man/imgtool.1
src/osd/sdl/man/jedutil.1
src/osd/sdl/man/ldresample.1
src/osd/sdl/man/ldverify.1
src/osd/sdl/man/mame.6
src/osd/sdl/man/romcmp.1
src/osd/sdl/man/testkeys.1

Please merge, thank you!
Cesare

Bump *nix man pages version

---

src/mame/drivers/tourvis.c

Dumps of some of these should be coming soon, new games discovered recently.

Updated known game list

---

src/emu/cpu/m68000/m68kfpu.inc

This pull request is in advance of the ROLM 9751 driver in development.

Add M68kFPU mode 7, reg 0

---

3rdparty/mongoose/mongoose.h

Also filed upstream as https://github.com/cesanta/mongoose/pull/559
Signed-off-by: Thomas Klausner <wiz@NetBSD.org>

Add missing header for va_list.

---

src/mame/drivers/igs_m027.c

(expected to fix a previous bad dump)

new checksum for IGS Amazonia King program rom

---

src/mess/drivers/hp64k.c

Hi,
I've refactored the hp64k code a bit. As someone suggested, I'm now using the COM8116 as a baud rate generator for the rs232 line.
-- F.Ulivi

hp64k: small code refactoring

---

src/mame/drivers/igs_m027.c

(gfx1 and gfx2 ROMs were swapped)

Fixing the gfxdecode for amazonia king character generator

---

.travis.yml

This adds support for Travis build with OS X. Doing a pull request so others can review.

Travis Mac OS X build

---

src/mess/audio/gb.c

mess/audio/gb.c - correct NR52 register writing with proper values

---

scripts/target/mame/arcade.lua
src/mame/arcade.lst
src/mame/drivers/galaxia.c
src/mame/drivers/galaxian.c
src/mame/drivers/spcwarp.c

add manual/schematics for Astro Wars in galaxia.c

seperate Space Warp into a skeleton driver for further notice

---

scripts/target/mame/mess.lua
src/mame/mess.lst
src/mess/drivers/zapcomputer.c
src/mess/includes/zapcomputer.h
src/mess/layout/zapcomputer.lay

based on the book "Build Your Own Z80 Microcomputer" published by BYTE / McGRAW-HILL

new driver: ZAP - Z80 Applications Processor (by Steve Ciarcia - 1981)

---

scripts/target/mame/arcade.lua
src/mame/arcade.lst
src/mame/drivers/wacky_gator.c

whack-a-mole style game with alligators.

Skeleton driver for Wacky Gator (Data East - 1990)

---

src/mame/drivers/vii.c

Fixing small typo

---

src/mame/arcade.lst
src/mame/drivers/galaxian.c

-add notes about Fantasy, Star Crest, and original Zig Zag sets
-made current Zig Zag galaxian sets bootlegs; changed Zig Zag names
-fix typo

galaxian.c - minor changes

---

src/devices/machine/z80scc.c
src/devices/machine/z80scc.h
src/devices/machine/z80sio.c
src/devices/machine/z80sio.h

General improvements and fixing a strange intermittent bug that caused the H-BUG monitor on the  H68V10 board to fail getting the terminal due to clocks not working/starting properly 2 times out of 3.
I separated the SCC channel code from the SIO channel code but intend to create a common base class later. 
It is also a first step toward splitting out the SIO device on the Mizar 8105 board to a separate VME board and implement the VME bus.

Z80scc m166 3

---

src/mame/drivers/nmg5.c

Has bikini shots instead of nudity in Rocktris and Cross Point.

Mark nmg5a as censored (nw)

---

src/mame/drivers/galaxian.c
src/mame/drivers/galaxold.c
src/mame/machine/electron.c

electron.c:
Fixed the beeper algorithm by doubling the divider. Marked it as GUESS.
galaxold.c:
After reverse-engineering, spcwarp clearly a Cosmos conversion. The wikipedia article I took with a big amount of salt by mistake. Organized some notes about the game.
galaxian.c
Sneaking in some minor fixes to some typos and misplacements

some minor changes to a few drivers

---

src/mame/drivers/pc.c
src/mame/mess.lst

First try of a commit ... PCXT keyboard works.

Added Siemens Sicomp PC16-05 BIOS ROM (Multitech MPF-PC/700 mainboard) [rfka01]

---

src/devices/imagedev/floppy.c
src/mame/drivers/imds2.c
src/mame/includes/imds2.h

Ok, I rebased this patch on current master. It compiles on my machine.
--F.Ulivi

Fix for imds2 driver after i8271 modernization (2nd attempt)

---

src/mame/drivers/megadriv.c

Mega-CD with 32X (Japan, NTSC) [Shideravan]
Mega-CD with 32X (Europe, PAL) [Shideravan]
(I'll edit mess.lst for these drivers too - I not aware how to create a pull request with multiple files yet)

New machines marked as NOT_WORKING

---

src/mame/mess.lst

In addition to Pull Request #425

Including 32x_mcd and 32x_mcdj drivers

---

src/devices/cpu/i86/i86.c

i86: "custom hardware" -> "real CPU". too off and picky.

nothing important to see here; just merge and move along

---

src/mame/drivers/konamim2.c

Also, compatibility with 3do_m2 softwarelist

Adding preliminary support for cd-rom in 3do_m2

---

src/mame/drivers/macpci.c

Preliminary support for cd-rom images in Pippin

---

src/mame/drivers/ec184x.c

first hunk fixes the crash, the rest are just eye candy

ec1841: fix crash and make debug messages a bit more intuitive

---

hash/a2600.xml

Remove wrong characters from sha1 fields in hash/a2600.xml.

---

src/devices/bus/vcs/dpcplus.c

most info taken from:
https://atariage.com/forums/uploads/monthly_03_2015/blogentry-3056-0-26480200-1425338924.png

dpcplus - correct ARM speed, fix RAM, add ROM to map

---

src/devices/bus/vcs/dpcplus.c
src/devices/bus/vcs/dpcplus.h

-add missing copyright holders
-improve notes
-confirm ARM7 type

dpcplus: minor non-code related changes

---

src/devices/machine/i8251.c
src/devices/machine/i8251.h

Hi,
I've just pushed a couple of changes to i8251 driver to improve handling of tx ready/empty flags.
Before these changes the HP64000 self-test on serial line failed.
Thanks.
--F.Ulivi

Fix for i8251 device driver

---

src/mame/drivers/imds2.c
src/mame/includes/imds2.h

Hi,
I've just pushed a set of changes to support serial lines on imds2 driver.
--F.Ulivi

Serial ports added to imds2

---

hash/psx.xml

Adding the Interactive CD Sampler collection

---

3rdparty/bx/include/bx/os.h
3rdparty/bx/include/bx/platform.h
3rdparty/genie/build/gmake.bsd/genie.make
3rdparty/genie/build/gmake.solaris/genie.make
src/osd/sdl/sdlptty_unix.cpp

This collects a number of patches to fix the build on NetBSD.
I've also found an obvious problem in the Solaris build, so there's a drive-by fix for that included as well (untested).

Fix build on NetBSD.

---

src/osd/modules/render/d3d/d3dhlsl.cpp
src/osd/modules/render/drawd3d.cpp

I thought I had already fixed this bug, but another change seems to have brought it back.
- fixed missing shadow mask texture when switching between window mode
and full screen

Fixed missing shadow mask (nw)

---

src/devices/sound/fmopl.cpp
src/devices/sound/ymf262.cpp

I..... obviously don't know how to read someone's post when it comes to documentation.

revert ksl order fixes completely

---

scripts/src/video.lua
scripts/target/mame/arcade.lua
scripts/target/mame/mess.lua
src/devices/video/ef9365.cpp
src/devices/video/ef9365.h
src/mame/drivers/squale.cpp

Sound support added.
Bank switching for monitor >2RX added.
ACIA instance added.
PIAs instances added.

Monitor V1.2 EPROM support added.

---

src/devices/video/ef9365.cpp
src/devices/video/ef9365.h
src/mame/drivers/squale.cpp

Squale keyboard added : The user can now have some interactions with the machine.
WD1770 FDC added.
EF9365 emulation improved : 5x8 and 4x4 Blocks drawing support added.
Squale machine turned as working.

Squale keyboard added, Squale FDC added (WIP), EF9365 emulation improved.

---

scripts/src/cpu.lua
scripts/target/mame/mess.lua
src/devices/cpu/patinhofeio/patinho_feio.cpp
src/devices/cpu/patinhofeio/patinho_feio.h
src/devices/cpu/patinhofeio/patinho_feio_dasm.cpp
src/mame/drivers/patinho_feio.cpp
src/mame/mess.lst

More info here:
http://mamedev.emulab.it/fsanches/2015/11/18/a-pleasant-visit-to-the-university/
And here:
https://archive.org/details/Montador_do_Patinho_Feio__Julho1977

New CPU & driver: Patinho Feio (first computer developed in Brazil, in 1971)

---

src/mame/drivers/psikyo.cpp

More stereo -> mono corrections.

These games are all mono

---

src/mame/drivers/coinmstr.cpp

Joker Poker (Coinmaster set 1) [MASH]
Fixed also gfx1 roms lenght to 0x2000

new WORKING game

---

src/devices/cpu/hphybrid/hphybrid.cpp
src/devices/cpu/hphybrid/hphybrid.h
src/devices/cpu/hphybrid/hphybrid_dasm.cpp
src/mame/drivers/hp9845.cpp

Hi,
I've just pushed the first version of the hp9845b driver I'm working on. It's still WIP but it's usable.
Let me know where I should send the zip file with rom images, please.
Thanks.
-- F.Ulivi

First version of HP9845B driver

---

src/devices/cpu/hphybrid/hphybrid.h
src/mame/drivers/hp9845.cpp

Here are the missing overrides: hope they are ok (my gcc 4.9 doesn't complaint at all).
-- F.Ulivi

hp9845b & hphybrid: added missing "override"s

---

src/mame/drivers/squale.cpp

Cartridge slot emulation added.
Joystick inputs added.

Cartridge slot emulation added,Joystick inputs added.

---

src/lib/util/coretmpl.h

* Add `noexcept`
* Use public `=delete` instead of private ctor/assignment
* Remove unused `virtual` from dtor and mark class as `final`

Modernize `simple_list` code

---

src/devices/video/ef9365.cpp
src/devices/video/ef9365.h
src/mame/drivers/squale.cpp

Squale Floppy drives working, EF9365 emulation improvement.

Squale Floppy drives working, EF9365 emulation improvement.

---

src/mame/drivers/cave.cpp
src/mame/drivers/tourvis.cpp

Updated known Tourvision game list
http://mametesters.org/view.php?id=6109
I own or have owned all the ones corrected.

Corrected all known mono titles in cave.cpp

---

src/devices/cpu/i386/i386.cpp
src/devices/machine/at28c16.cpp
src/devices/machine/fdc37c665gt.cpp
src/devices/machine/wd_fdc.cpp
src/devices/machine/x76f041.cpp
src/devices/machine/x76f100.cpp
src/mame/machine/igs022.cpp
src/mame/machine/igs025.cpp
src/mame/machine/igs028.cpp
src/mame/machine/s32comm.cpp
src/mame/video/igs017_igs031.cpp

Revert "Update device names"

---

src/emu/clifront.cpp
src/emu/validity.cpp
src/emu/validity.h

Revert "Allow mame -validate -verbose to display more messages (and make erro…"

---

src/mame/mess.lst

mess.lst update for spc1500 support

---

scripts/target/mame/mess.lua

mess.lua update for supporting spc1500

add spc1500 to mess.lua

---

src/mame/drivers/spc1500.cpp

- Palet table added for simple screen update (from a comment of the Naver cafe manager 'Loderunner') 
- Video start addr of MC6845 regs affected on screen update (galaxy).
- PCG character takes proper palet color (galaxy).
- Joystick port active has been fixed to low from high.

spc1500: screen update modified for game (galaxy)

---

src/mame/drivers/spc1500.cpp

- spc1500 double size character support
- spc1500 PCG addressing improved
- spc1500 cassette tape motor fixed
http://cafe.naver.com/8bitpc/8211 (detail description of the official demo application in Korean)

[spc1500] some feature fixed for the official demo application

---

src/mame/drivers/spc1000.cpp

- spc1000 ROM file update for CP/M disk working at booting time
- spc1000 cassette tape motor fixed for better working

[spc1000] cassette tape motor fixed for working properly

---

src/mame/drivers/armedf.cpp
src/mame/drivers/segas16b.cpp
src/mame/video/sega16sp.cpp
src/mame/video/sega16sp.h

- terrafb: remove unused NB1414M4
- segas16b.cpp: sanity check forgotten in last confix
- sega16sp.cpp: fix region width, make required (as last confix allows)

More configuration fixes

---

src/emu/ui/ui.cpp
src/emu/ui/ui.h
src/emu/uiinput.cpp
src/emu/uiinput.h

Also fixes some bugs without which this feature ends up not very useful.

Allow load/save state slots to be bound to joystick buttons

---

hash/m5_cart.xml
hash/m5_flop.xml
src/devices/bus/m5/rom.cpp
src/devices/bus/m5/rom.h
src/devices/bus/m5/slot.cpp
src/devices/bus/m5/slot.h
src/mame/drivers/m5.cpp
src/mame/includes/m5.h
src/mame/mess.lst

added support for RAM expansions EM-5,64KBI,64KBF,64KRX
added m5p_brno mod Sord m5+1024kB ramdisk+cp/m
2 cart slots

Sord m5 driver update

---

language/German/strings.po

Update German strings.po

---

src/emu/ui/cheatopt.cpp

Fixed an issue related to autofire: https://github.com/mamedev/mame/pull/618#issuecomment-186846109

Fix reset of cheats when entering autofire menu

---

src/osd/sdl/man/mame.6
src/osd/sdl/man/mess.6

mame/mess man pages edited accordingly to patches https://github.com/mamedev/mame/pull/618 and https://github.com/mamedev/mame/pull/610

Man pages aligned to autofire and cheat recent changes

---

language/Japanese/strings.po

First entry. Needs fixes and updates.

Japanese strings.po

---

hash/m5_cart.xml

Remove BOM from XML file.

---

src/emu/ui/custui.cpp

When i change the HIDE_MENU on the customize UI  by cursor key, LANGUAGE_MENU also would be changed .fixed it.

customize UI fixed.

---

language/French/strings.po

Fixes lot typos, missing spaces, improved translation...

Update french translation

---

src/emu/clifront.cpp
src/emu/clifront.h
src/emu/cliopts.cpp
src/emu/cliopts.h
src/emu/drivenum.cpp
src/emu/drivenum.h
src/emu/ui/imgcntrl.cpp
src/emu/ui/imgcntrl.h
src/emu/ui/inputmap.h
src/emu/ui/mainmenu.h
src/emu/ui/menu.cpp
src/emu/ui/miscmenu.h
src/emu/ui/selgame.cpp
src/emu/ui/selgame.h
src/emu/ui/simpleselgame.cpp
src/emu/ui/simpleselgame.h
src/emu/ui/slotopt.h
src/emu/ui/ui.cpp
src/emu/validity.cpp
src/osd/sdl/man/mame.6
src/osd/sdl/man/mess.6

Revert "New driver specifiers; modify -listclones, -listsource; add -listtree"

---

language/Spanish/strings.po

Spanish translation for UI strings

Spanish UI strings

---

language/Italian/strings.po

Many translations and corrections; now missing a few techniques phrases.

Update Italian string.po

---

src/osd/sdl/man/mame.6
src/osd/sdl/man/mess.6

See https://github.com/mamedev/mame/pull/610

Added -exit_after_playback to man pages

---

language/German/strings.po

I couldn't get my initial Pull Request to merge cleanly, so I pulled that and created a new one.
Sorry if this causes inconveniences.

Update German Translation to latest definitions

---

language/Portuguese_Brazil/strings.po

@cuavas can you please review this? It this what you meant on IRC?
If not, you may simply close the pull request
Thanks,
Felipe

a few tweaks to ptbr translations as suggested by cuavas

---

src/emu/emuopts.cpp
src/emu/mame.cpp
src/osd/modules/render/bgfx/targetmanager.cpp

Prevent clang warning about unused variable in BGFX target_manager (nw)

Allow software selected from UI to install slot defaults

---

makefile

Fix compile win 64 bit with mingw 32 bit

---

src/devices/machine/z80scc.cpp
src/devices/machine/z80scc.h
src/mame/drivers/hk68v10.cpp

- verified with HK68v10 driver

initial Z80SCC Baudrate Generator support

---

src/emu/ui/menu.cpp
src/emu/ui/menu.h
src/emu/ui/optsmenu.cpp
src/emu/ui/submenu.cpp

submenu lang and cosmetic (nw)

---

src/devices/cpu/mips/mips3.cpp

I have not tested if this is endian-safe.

mips3: Fix behavior for 32/64 bit mode floating point register aliasing.

---

src/devices/cpu/hphybrid/hphybrid.cpp
src/devices/machine/hp_taco.cpp
src/devices/machine/hp_taco.h
src/mame/drivers/hp9845.cpp

Hi,
I've just pushed a set of improvements to hp9845b driver. In particular the TACO driver was fixed & improved a lot since my last push (TACO was the tape controller of hp9845 machines).
Thanks.
-- F.Ulivi

Improvements to tape driver of hp9845b

---

language/German/strings.po

This PR updates the German GUI translation.

Update German GUI translation

---

src/mame/drivers/dmv.cpp

http://oldcomputers.dyndns.org/public/pub/rechner/ncr/DMV/My_DMV_Color/2016-04-11/index.html
has an older ROM revision for a color mainboard.

Added older ROM revision of a Color DMV

---

hash/hp9845b_rom.xml
scripts/src/bus.lua
scripts/target/mame/mess.lua
src/devices/bus/hp_optroms/hp_optrom.cpp
src/devices/bus/hp_optroms/hp_optrom.h
src/devices/cpu/hphybrid/hphybrid.cpp
src/devices/cpu/hphybrid/hphybrid.h
src/devices/cpu/hphybrid/hphybrid_dasm.cpp
src/mame/drivers/hp9845.cpp

Hi,
I've just pushed a set of changes to hp9845b driver to implement loading of optional ROMs. I've partially updated the hash file: to be completed.
Thanks.
-- F.Ulivi

Hp9845: added capabilty to load option ROMs

---

hash/fmtowns_cd.xml

Filled up to the letter A. More will come later.

Preliminary software list for FM Towns CDs

---

hash/fmtowns_cd.xml

- Corrected alice3 sha1
- Converted file names to lowercase for consistency
- Added some entries starting with D
- Added CHDs converted by Breiztiger (fshark, imgfight, opwolf, win95, zak)

fmtowns_cd.xml: several corrections & additions

---

src/mame/drivers/tourvis.cpp

Updated game list
Added some extra notes & known game IDs
Corrected SW1 dip 8
Corrected 1P button order

Tourvision misc small updates

---

hash/fmtowns_cd.xml

- Added letter F
- Added more CHDs converted by Breiztiger (ultima4, wiz5, wiz6, wiz7, wwcarmen)
- Fixed elfishlt CHD name

fmtowns_cd.xml: Added F + others

---

src/mame/arcade.flt

Remove AES BIOS from arcade build.

Fixed arcade only build

---

hash/fmtowns_cd.xml

- Added H, I & J
- Added more CHDs converted by Breiztiger (mode7dmo, mbomber, necronom, rayxanbr, simcity)

fmtowns_cd.xml: Added H, I & J

---

hash/fmtowns_cd.xml

- Added letter K
- Added CHDs converted by Breiztiger (dragflam, lemmings, lemmin2e, lemmin2j, marble, panzrdiv, populous, ssf2, ssf2samp, sotb, win31)
- Added Shadow of the Beast 2 dump from redump.org

fmtowns_cd.xml: Added K + others

---

makefile
scripts/toolchain.lua

Added missing blocks in Makefile and toolchain.lua to allow building on OpenBSD.

Allow building on OpenBSD

---

hash/fmtowns_cd.xml

- Added CHDs up to L
- Added more CHDs converted by Breiztiger (mcosm, mirage, mmagic4, mmagic5, mustowns, pegasus, racrally, railtyc, ravnloft, splatter)

fmtowns_cd.xml: Added L

---

scripts/src/cpu.lua
scripts/target/mame/mess.lua
src/devices/cpu/patinhofeio/patinho_feio.cpp
src/devices/cpu/patinhofeio/patinho_feio.h
src/devices/cpu/patinhofeio/patinho_feio_dasm.cpp
src/mame/drivers/patinho_feio.cpp

Revert "Further improvements to the Patinho Feio driver & CPU"

---

hash/n64dd.xml
src/mame/drivers/n64.cpp

Updated checksum for Randnet disk, previous conversion was faulty.

Change N64DD to use harddisk device instead of quikload device.

---

scripts/target/mame/mess.lua
src/mame/drivers/alesis_qs.cpp

This is a skelethon driver. I haven't touched it since February, so I think it's better to contribute as is, just in case someone may be interested in working on it.
A major development needed for this one is actually emulating the CPU it uses (an H8/510).

[alesqs7] New skeleton driver: Alesis QS-7 musical keyboard.

---

src/mame/drivers/toratora.cpp

major credit due to siftware also, for verifying numerous connections & component values on pcb!

toratora: fix timer and interrupts, improve sound. game now fully playable.

---

makefile
scripts/genie.lua
scripts/src/3rdparty.lua
scripts/toolchain.lua

+ preliminary fastbuild support (experimental in genie)

support msbuild from posix shell

---

src/emu/ui/uimain.h
src/frontend/mame/ui/menu.cpp
src/frontend/mame/ui/menu.h
src/frontend/mame/ui/sliders.cpp
src/frontend/mame/ui/sliders.h
src/frontend/mame/ui/ui.cpp
src/frontend/mame/ui/ui.h
src/frontend/mame/ui/viewgfx.cpp
src/frontend/mame/ui/viewgfx.h

This changes the ui_callback mechanism in mame_ui_manager to be implemented via lambdas and std::function

Lambdas for ui handlers

---

src/devices/cpu/hphybrid/hphybrid.cpp
src/mame/drivers/hp9845.cpp

Hi,
I've just pushed a set of commits that should fix the interrupt handling in HP hybrid CPU. I've also added the beeper to HP 9845B driver.
Thanks.
-- F.Ulivi

Hp9845: hopefully fixed interrupt handling in hp hybrid processor & minor enhancements

---

src/devices/bus/pet/2joysnd.cpp
src/devices/bus/pet/2joysnd.h

This has a few cleanups to the device I added and smf merged with mame. Although the cleanups are valid, this is mostly to validate that I can make a pull request.

2joysnd: cleanups

---

makefile
scripts/toolchain.lua

cleanup make targets and configuration rules
fix android_ndk_root env test

android: 64bit strip, platform version support (nw)

---

src/mame/drivers/rainbow.cpp

BIOS patch is gone. Floppy drives A-D seem to be locked by BIOS after Z80 RESPONSE FAILURE / DRIVE A (= ERROR 13), so the winchester disk remains ("W"). There is a new two byte patch, intended to ease testing of the DIAG.DISK. It will be removed as soon as possible.

Do away with KEYBOARD_WORKAROUND

---

src/frontend/mame/ui/sliders.cpp
src/frontend/mame/ui/sliders.h
src/frontend/mame/ui/ui.cpp

This fixes a recently introduced regression in the sliders UI control

Fix sliders issue

---

scripts/src/machine.lua
src/devices/machine/68230pit.cpp
src/devices/machine/68230pit.h
src/devices/machine/scnxx562.cpp
src/devices/machine/scnxx562.h
src/mame/drivers/fccpu30.cpp
src/mame/drivers/force68k.cpp
src/mame/mame.lst

WIP but now got prompt and can run some diagnostics

Drivers for Force Computers CPU-30 and Signetics DUSCC milestone 1

---

src/osd/modules/debugger/debugwin.cpp
src/osd/modules/debugger/win/debugwininfo.cpp
src/osd/modules/input/input_dinput.cpp
src/osd/modules/input/input_dinput.h
src/osd/modules/input/input_rawinput.cpp
src/osd/modules/input/input_sdl.cpp
src/osd/modules/input/input_sdlcommon.cpp
src/osd/modules/input/input_win32.cpp
src/osd/modules/input/input_windows.h
src/osd/modules/input/input_winhybrid.cpp
src/osd/modules/lib/osdobj_common.cpp
src/osd/modules/lib/osdobj_common.h
src/osd/modules/osdwindow.cpp
src/osd/modules/osdwindow.h
src/osd/modules/sound/direct_sound.cpp
src/osd/sdl/video.cpp
src/osd/sdl/window.cpp
src/osd/sdl/window.h
src/osd/windows/video.cpp
src/osd/windows/window.cpp
src/osd/windows/window.h
src/osd/windows/winmain.cpp

DONT merge yet. For testing and review
Idea is to combine more window code into osd_window. This part unifies the global window_list

Unify window_list in Windows and SDL OSD

---

src/mame/drivers/fcscsi.cpp
src/mame/drivers/mvme147.cpp

Added two secondary BIOS rom sets for Motorola MVME147 and Force ISCSI-1 VME boards

Added 147bug v2.43 ROM set

---

scripts/src/mame/frontend.lua
src/frontend/mame/ui/filesel.cpp
src/frontend/mame/ui/filesel.h
src/frontend/mame/ui/menu.cpp
src/frontend/mame/ui/menu.h
src/frontend/mame/ui/text.cpp
src/frontend/mame/ui/text.h
src/frontend/mame/ui/ui.cpp
src/frontend/mame/ui/ui.h

This makes the following changes:
- The text layout code has been factored out of ui.cpp into a new module.  Ideally we'd go further and call a "real" text layout engine but this paves the way.
- In the file selection dialog, you can now click portions of the path to go up parent directories

Make filesel current path clickable

---

src/osd/modules/render/bgfx/shaders/shader.mk

Gets past a shaderc error on linux

Rearrange shaderc arguments (nw)

---

hash/fmtowns_cd.xml

- Added Might & Magic III
- Replaced mp3-source dumps of Kyuukyoku Tiger and Viewpoint with proper ones
- Replaced colons with dashes in subtitles, to match other software lists

fmtowns_cd.xml: new dumps & title fixes

---

src/mame/drivers/halleys.cpp

No behavior is changed, just the use of goto:s which is now removed. I have played the game before and after and could not detect any difference in audio or graphics which plays out at 100% and 0 samples clipped at my 2 year old i7 laptop.

removed goto:s and somewhat simplified the readabaility

---

src/devices/cpu/sparc/mb86901.cpp
src/devices/cpu/sparc/sparc.h
src/devices/cpu/sparc/sparcdefs.h
src/mame/drivers/sun4.cpp

See subject line + diff. Requested by R. Belmont.

Make SPARC use only one memory map

---

src/devices/imagedev/cassette.cpp
src/devices/imagedev/cassette.h
src/emu/diimage.h
src/frontend/mame/ui/ui.cpp

Improved the cassette animation, some C++-ification and elimination of old MESS-isms

Modernized the cassette animation

---

src/frontend/mame/ui/text.cpp
src/frontend/mame/ui/text.h
src/frontend/mame/ui/ui.cpp

Fixed an issue that could cause text boxes that wrap to not fit on the screen

Fix text layout actual width

---

hash/pc98_cd.xml
src/mame/drivers/galaxian.cpp
src/mame/drivers/pc9801.cpp

Mostly built from the redump.org DAT, and from images I've had lying around for many years and I've forgotten where they came from (probably Japanese P2P).

New software list for PC-98x1 CDs

---

src/mame/drivers/homedata.cpp
src/mame/mame.lst

New Mahjong game in homedata.cpp driver.  PCB is same type as Private Teacher but with some wire hacks removed.  Dip sheet came with game but is incorrect.  Graphics problems present, currently unable to test against PCB, raising a bug about this.

S11mjjoship - Mahjong Joshi Pro-wres -Give up 5 byou mae-

---

src/emu/diimage.cpp
src/emu/fileio.cpp
src/emu/fileio.h
src/emu/machine.cpp
src/frontend/mame/clifront.cpp
src/frontend/mame/pluginopts.cpp
src/frontend/mame/ui/custui.cpp
src/frontend/mame/ui/dirmenu.cpp
src/frontend/mame/ui/filesel.cpp
src/frontend/mame/ui/filesel.h
src/frontend/mame/ui/imgcntrl.cpp
src/frontend/mame/ui/inifile.cpp
src/frontend/mame/ui/miscmenu.cpp
src/frontend/mame/ui/selgame.cpp
src/frontend/mame/ui/selsoft.cpp
src/frontend/mame/ui/simpleselgame.cpp
src/frontend/mame/ui/ui.cpp
src/frontend/mame/ui/ui.h
src/lib/util/zippath.cpp
src/lib/util/zippath.h
src/osd/modules/file/winfile.cpp
src/osd/modules/render/bgfx/chainentryreader.cpp
src/osd/modules/render/bgfx/chainmanager.cpp
src/osd/osdcore.h
src/osd/windows/windir.cpp
src/osd/windows/winutil.cpp
src/osd/windows/winutil.h

A number of changes and refactorings in preparation for a new load/save state menu.  Most notably, I am C++-ifying osd_directory (now osd::directory) and changing osd_stat() to return std::unique_ptr<osd::directory::entry>
Take note that this change completely omits POSIX support, simply because I lack a development environment to support it.  This will have to be done by someone else.

Load save state preparations

---

hash/pc98_cd.xml

- Added several game disks (no credits as they all come from Japanese anonymous P2P), more to come
- Added some more Windows 2000 variants

pc98_cd.xml: added more game & OS disks

---

src/mame/drivers/homedata.cpp
src/mame/video/homedata.cpp

Added kludge to correct display size for mjjoship next to all the other kludges.
Verified pixel accurate vs PCB now.

S11mjjoship fix

---

src/lib/util/un7z.cpp
src/lib/util/unzip.cpp

Someone can sanity check to make sure this is right, but it fixes the compile errors I'm getting on OSX.

Fix Clang compile on OSX

---

src/mame/drivers/model2.cpp
src/mame/includes/model2.h
src/mame/machine/m1comm.cpp
src/mame/machine/m2comm.cpp
src/mame/machine/s32comm.cpp

replaces printf with osd_printf_verbose in a number of places.
removed no longer needed code from model2

cleaned up some sega comm related stuff

---

hash/pc98_cd.xml

- Added some more game disks
- Fixed win2kpc and winnt40 images (thanks to Yoshizuki)
- Misc title / publisher fixes

pc98_cd.xml: more additions & misc fixes

---

src/frontend/mame/ui/auditmenu.cpp
src/frontend/mame/ui/barcode.cpp
src/frontend/mame/ui/cheatopt.cpp
src/frontend/mame/ui/custmenu.cpp
src/frontend/mame/ui/custui.cpp
src/frontend/mame/ui/datmenu.cpp
src/frontend/mame/ui/devopt.cpp
src/frontend/mame/ui/dirmenu.cpp
src/frontend/mame/ui/filemngr.cpp
src/frontend/mame/ui/filesel.cpp
src/frontend/mame/ui/info.cpp
src/frontend/mame/ui/info_pty.cpp
src/frontend/mame/ui/inputmap.cpp
src/frontend/mame/ui/mainmenu.cpp
src/frontend/mame/ui/menu.cpp
src/frontend/mame/ui/menu.h
src/frontend/mame/ui/menuitem.h
src/frontend/mame/ui/miscmenu.cpp
src/frontend/mame/ui/optsmenu.cpp
src/frontend/mame/ui/pluginopt.cpp
src/frontend/mame/ui/selector.cpp
src/frontend/mame/ui/selgame.cpp
src/frontend/mame/ui/selsoft.cpp
src/frontend/mame/ui/simpleselgame.cpp
src/frontend/mame/ui/slotopt.cpp
src/frontend/mame/ui/submenu.cpp
src/frontend/mame/ui/swlist.cpp
src/frontend/mame/ui/tapectrl.cpp
src/frontend/mame/ui/videoopt.cpp

Essentially changed some 'char *' strings to std::string in the menu code

C++-ified the strings inside of menu items

---

src/frontend/mame/ui/barcode.cpp
src/frontend/mame/ui/custmenu.cpp
src/frontend/mame/ui/custui.cpp
src/frontend/mame/ui/filesel.cpp
src/frontend/mame/ui/filesel.h
src/frontend/mame/ui/inputmap.cpp
src/frontend/mame/ui/miscmenu.cpp
src/frontend/mame/ui/optsmenu.cpp
src/frontend/mame/ui/pluginopt.cpp
src/frontend/mame/ui/selector.cpp
src/frontend/mame/ui/selgame.cpp
src/frontend/mame/ui/selsoft.cpp
src/frontend/mame/ui/sliders.cpp
src/frontend/mame/ui/slotopt.cpp
src/frontend/mame/ui/sndmenu.cpp
src/frontend/mame/ui/swlist.cpp
src/frontend/mame/ui/tapectrl.cpp
src/frontend/mame/ui/videoopt.cpp

This changes filesel entrylist to be a vector, and a bunch of other unglamorous cleanups

Filesel and other cleanups

---

scripts/target/mame/mess.lua
src/devices/machine/68230pit.cpp
src/devices/machine/68230pit.h
src/devices/machine/scnxx562.cpp
src/devices/machine/scnxx562.h
src/mame/drivers/fcisio.cpp
src/mame/mame.lst

WIP but it passes the self test now. The board is an 8 channel Intelligent Serial I/O VME controller with a 68010, 4 SCN68562 DUSCC and a 68230 PIT timer. Not supported yet are interrupts and DMA, I need schematics or the real board to finish it.  Lastly it is capable of interrupting over the VME bus through a 68153 BIM both needed to be written. Once that is done most Force CPU boards, like the CPU-30 has firmware that will auto detect this board.

New Board: Force Computers ISIO-1/2

---

scripts/toolchain.lua

* 2f3f53e got objdir wrong (type folder duplicate)

android objdir (nw)

---

hash/fmtowns_cd.xml

Mostly weird/bad/creepy "multimedia" stuff found in anonymous P2P services. Try at your own risk.

fmtowns_cd.xml: misc additions

---

src/osd/modules/lib/osdobj_common.cpp
src/osd/modules/lib/osdobj_common.h
src/osd/modules/render/aviwrite.cpp
src/osd/modules/render/aviwrite.h
src/osd/modules/render/d3d/d3dhlsl.cpp
src/osd/modules/render/d3d/d3dhlsl.h
src/osd/modules/render/drawbgfx.cpp
src/osd/modules/render/drawd3d.cpp
src/osd/windows/winmain.cpp
src/osd/windows/winmain.h

Use common infrastructure in aviwrite.c instead of equivalent local code.

Direct3D HLSL: use aviwrite to record avi movies

---

src/emu/diimage.cpp
src/emu/diimage.h
src/frontend/mame/ui/filecreate.cpp
src/frontend/mame/ui/filecreate.h
src/frontend/mame/ui/floppycntrl.cpp
src/frontend/mame/ui/imgcntrl.cpp
src/osd/modules/file/winfile.cpp
src/osd/osdcomm.h
src/osd/osdcore.h

Miscellaneous refactorings related to image creation and formats

File create and format refactorings

---

src/mame/drivers/rainbow.cpp

(MESS) Added 4th drive (DD 720K) for PC data exchange via IMPDRV3.SYS. Improved watchdog logic. More concise floppy code (boots from drives other than A). Baud rate generator and preliminary serial port. Promoted Rainbow-100-B  to working.

Promote Rainbow-100-B to WORKING

---

src/devices/bus/isa/omti8621.cpp
src/devices/imagedev/bitbngr.cpp
src/devices/imagedev/bitbngr.h
src/devices/imagedev/cassette.cpp
src/devices/imagedev/cassette.h
src/devices/imagedev/diablo.cpp
src/devices/imagedev/diablo.h
src/devices/imagedev/flopdrv.cpp
src/devices/imagedev/flopdrv.h
src/devices/imagedev/floppy.cpp
src/devices/imagedev/floppy.h
src/devices/imagedev/harddriv.cpp
src/devices/imagedev/harddriv.h
src/devices/imagedev/printer.cpp
src/devices/imagedev/printer.h
src/emu/diimage.cpp
src/emu/diimage.h
src/lib/formats/ap_dsk35.cpp
src/lib/formats/basicdsk.cpp
src/lib/formats/flopimg.cpp
src/lib/formats/flopimg.h
src/lib/formats/pc_dsk.cpp
src/lib/formats/thom_dsk.cpp
src/lib/util/opresolv.cpp
src/lib/util/opresolv.h

Moved to util:: namespace
Changed option_resolution to be a class
C++ comments
Fixed client sites

C++-ification of src/lib/util/opresolv.[cpp|h]

---

src/emu/machine.cpp
src/emu/machine.h
src/frontend/mame/ui/filecreate.h

Two very unglamorous minor refactorings

More miscellaneous refactorings

---

src/frontend/mame/ui/filecreate.cpp
src/lib/util/corefile.cpp
src/lib/util/corefile.h
src/tools/chdman.cpp
src/tools/src2html.cpp

Small changes pertaining to corefile.cpp static functions

Core file changes

---

hash/gba_ereader.xml

While e-reader isn't fully support, I'll start to document the know .raw files
I'm starting with the across - series 1 (based in no-intro set)

Starting work doing the GBA e-reader software-list

---

docs/man/castool.1
docs/man/chdman.1
docs/man/floptool.1
docs/man/imgtool.1
docs/man/jedutil.1
docs/man/ldresample.1
docs/man/ldverify.1
docs/man/mame.6
docs/man/romcmp.1

I finally managed to update the man pages for *nix to the current tree.
Please consider merging.
Thanks!
Cesare

Updated *nix man pages.

---

src/lib/netlist/plib/pdynlib.cpp

When UNICODE is defined LoadLibrary is redefined to LoadLibraryW which expects a widechar string as library name, while libname is always UTF8. Fixed copying TCHAR conversion code from strconv.cpp since netlist is meant to be also a stand-alone library.

Fix for netlist library when built for WINDOWS with UNICODE defined

---

src/emu/diimage.cpp
src/emu/diimage.h
src/emu/image.cpp
src/emu/softlist.cpp
src/emu/softlist.h

Also consolidated with code that performed a quick pass to identify whether a piece of text is a software name

device_image_interface::software_name_split() ==> softlist.cpp:software_name_parse()

---

src/mame/drivers/cave.cpp
src/mame/drivers/segahang.cpp
src/mame/includes/cave.h
src/mame/mame.lst

new clones
Air Gallet (older) [Artemio Urbina]

new clones

---

src/mame/drivers/hp9845.cpp

Hi,
the commit I've just pushed corrects the character generator in hp9845b driver as I now have the dumps of the original ROMs (thanks to A.Kueckes of www.hp9845.net site).
I've branched out of 0.176 tag because I can't compile the current origin/master commit.
I'm attaching the current set of ROM images for hp9845b. Hope it's not inappropriate to publish it here.
Thanks.
--F.Ulivi
[hp9845b.zip](https://github.com/mamedev/mame/files/415989/hp9845b.zip)

hp9845: correct character generator ROMs added

---

hash/gba_ereader.xml

It's time to add Animal Crossing Series 2

---

scripts/src/video.lua
scripts/target/mame/mess.lua
src/devices/video/gba_lcd.cpp
src/devices/video/gba_lcd.h
src/emu/drivers/xtal.h
src/mame/drivers/gba.cpp
src/mame/includes/gba.h
src/mame/video/gba.cpp

I started checking the code against the latest GBATEK (http://problemkaputt.de/gbatek.htm), and I thought some code reshuffling and simplification was necessary before going on.

Rework and simplify GBA code

---

src/mame/machine/kaneko_calc3.cpp
src/mame/machine/kaneko_toybox.cpp

fix read case in kaneko_calc3.cpp and make kaneko_toybox.cpp safe as well

---

src/devices/sound/c352.cpp
src/devices/sound/c352.h

change spaces to tabs, type formats from old school to MAME standard.

c352 code formatting, change type formats

---

src/devices/video/gba_lcd.cpp
src/devices/video/gba_lcd.h
src/mame/drivers/gba.cpp
src/mame/includes/gba.h

gba: decouple video device from main machine state using callbacks

---

src/devices/bus/isa/hdc.cpp
src/devices/bus/isa/hdc.h

(reworked https://github.com/mamedev/mame/pull/1247)

ec1841 + isa_hdc: don't stall at startup of test disk (take 2)

---

scripts/target/mame/mess.lua
src/mame/drivers/kim1.cpp
src/mame/includes/kim1.h
src/mame/layout/kim1.lay

Hooked up the ST key and updated RS key function.
Updated INPUT_PORTS to add numpad keys and better support hex dump pasting.
Moved type definitions to kim1.h.
Simplified kim1.lay coordinates.

kim1: RS & ST keys, input ports update

---

hash/fmtowns_cd.xml

Air Management - Oozora ni Kakeru
Hiouden II
Windows 3.1 L12

fmtowns_cd.xml: new dumps

---

src/mame/drivers/galaxian.cpp
src/mame/drivers/r2dx_v33.cpp
src/mame/includes/galaxian.h
src/mame/mame.lst

unique / interesting bootleg, CPU code is encrypted, and unfortunately one gfx rom is bad and can't easily be reconstructed (see note)
if anybody out there has the same bootleg then it would be helpful to dump it.

new clones (NOT WORKING)   Jungler (Subelectro, bootleg on Scramble hardware) [Andrew Welburn]

---

src/mame/drivers/8080bw.cpp
src/mame/layout/escmars.lay

Escape from Mars (bootleg of Lunar Rescue) [Siftware, MASH]
Rom: ci1.zip
Found the monitor for the game with the colour overlay strips and created the layout from it:
http://www.kijiji.ca/v-video-games-consoles-other/calgary/b-w-arcade-monitor-escape-from-mars/1057700342?enableSearchNavigationFlag=true

New Lunar Rescue clone

---

src/mame/drivers/champbas.cpp
src/mame/mame.lst

New Clone Added
-----------------------------------------------------
Champion Base Ball (Japan set 3) [Siftware, MASH]
Rom: blue1.zip
Set is missing palette + look-up table proms, use the ones from (Japan set 1).

New Champion Base Ball clone

---

src/mame/drivers/midvunit.cpp
src/mame/includes/midvunit.h

Finished what I started on last pull request. Motion tests now won't fail and can see everything the game expects to send to the real device in stdout.

Added motion controller to Midway V-Unit

---

src/devices/video/gba_lcd.cpp
src/devices/video/gba_lcd.h
src/emu/emucore.h

My first attempt at modernizing the code by taking advantage of C++ features.
I hope this actually makes the code easier to read.

gba: 1st batch of code refactorings

---

src/emu/diimage.cpp
src/emu/diimage.h
src/emu/softlist.cpp
src/emu/softlist.h

These started out as some opportunistic softlist cleanups in pursuit of an issue reported by Tafoid, until I realized that the behavior was correct.  I don't want to lose these cleanups; feel free to wait until after the release to merge this pull request.

Yet more softlist cleanups

---

src/mame/drivers/segas18.cpp

Patch that calculates offsets making the game playable.

Fix for Mametesters BugID #1455

---

src/mame/video/bfm_dm01.cpp

(This second update to the RGB values was after reviewing videos and collaborating with people on the fruit machine forums).

BFM DMD: Adjust to more accurately match the colour of the real machines.

---

src/osd/sdl/window.cpp

Warp mode for relative mouse on OSX SDL 2.0.4

---

src/emu/digfx.cpp
src/emu/digfx.h
src/emu/drawgfx.cpp
src/emu/drawgfx.h
src/emu/emu.h
src/emu/emupal.cpp
src/emu/emupal.h
src/emu/tilemap.cpp
src/emu/tilemap.h
src/frontend/mame/ui/ui.cpp
src/frontend/mame/ui/ui.h
src/frontend/mame/ui/viewgfx.cpp

- Mouse over GFX tiles to reveal pixel values
- Mouse over tilemap to reveal tile codes and colors
- UI tilemap scrolling controls are now orientation-relative
- Make mouse visible everywhere in UI graphics viewer by treating it like a menu
- Add all necessary getters to tilemap_t and a few more (nw)
- Add comment about role of decoder in tilemap creation (nw)

More new features for UI graphics viewer

---

hash/gamegear.xml
hash/sms.xml

these are from SMS power
sms:
Sky Fighter (보라매 전사) for the Samsung Gam*Boy / Master System
Prototype of Action Fighter for the Master System
Prototype of Captain Silver for the Master System
gamegear:
Cave Dude for the Game Gear (runs in SMS mode)

New Software List additions (sms.xml, gamegear.xml)

---

hash/gba_ereader.xml

Finally finishing Animal Crossing e-cards and also adding complete Domo-Kun Card-e collection

gba_ereader.xml - update part 3

---

hash/kim1_cass.xml
src/mame/drivers/kim1.cpp
src/mame/includes/kim1.h

[mchess.7z](https://www.sendspace.com/file/ig5oof) is included on the software list. You can test it by using instructions form the [Microchess Manual](http://archive.computerhistory.org/projects/chess/related_materials/text/4-1.MicroChess_%20Manual_for_6502.Micro-Ware/MicroChessManual.PETER_JENNINGS.062303071.sm.pdf).

added software list

---

src/mame/drivers/snk.cpp
src/mame/mame.lst

Jumping Cross (set 2) [MASH]
MAME 0.178: Identifying "unknown_snk.zip"
SNK9.BIN            NO MATCH
SNK11.BIN           = jcrosss1.h2           jcross     Jumping Cross
SNK12.BIN           = jcrossf0.l2           jcross     Jumping Cross
SNK13.BIN           = jcrossf1.k2           jcross     Jumping Cross
SNK14.BIN           = jcrossf2.j2           jcross     Jumping Cross
SNK2.BIN            = jcrossb1.14a          jcross     Jumping Cross
SNK3.BIN            = jcrossb2.13a          jcross     Jumping Cross
SNK4.BIN            = jcrossb3.12a          jcross     Jumping Cross
SNK5.BIN            = jcrossa4.15b          jcross     Jumping Cross
SNK6.BIN            = jcrossa3.14b          jcross     Jumping Cross
SNK7.BIN            = …

New Jumping Cross clone

---

src/mame/drivers/dwarfd.cpp
src/mame/mame.lst

New NOT WORKING game [Siftware, MASH]
-------------------------------------
Poker (Electro-Sport) 
Siftware: Poker? (electro.zip)
* Game is working. You can hear the sound and you can insert coins.
But graphics need to be fixed. You can see cards if you press 5 (Coin 1), M (Bet) and 1 (Player Start).
* Flickering cursor also in MAME's dwarfd

New NOT WORKING game [Siftware, MASH]

---

src/mame/drivers/corona.cpp
src/mame/mame.lst

Le Grandchamps (Isermatic France S.A. 198?) [MASH]
http://flyers.arcade-museum.com/?page=thumbs&db=videodb&id=6520
Romset: Unknown.zip
t1.bin      2048 1406   2003-01-13  22:05  99A8876B
t10.bin     2048 1411   2003-01-13  22:15  3B8F9293
t2.bin      2048 1417   2003-01-13  22:06  A4658A30
t3.bin      2048 1517   2003-01-13  22:10  8CA8C20E
t4.bin      2048 1105   2003-01-13  22:10  8A558BEF
t5.bin      2048 1090   2003-01-13  22:15  8172F711
t7.bin      2048 1215   2003-01-13  22:15  AAAAA37A
Found the driver for this romset by searching the first bytes of the sound rom (t7.bin)
in all MAME set from 9 to 12kb.

New Winners Circle clone

---

src/mame/drivers/zn.cpp
src/mame/mame.lst

(actually new parent, old set is ver. 1.04)

new clones NBA Jam Extreme (ver. 1.10I) [farzeno]

---

src/tools/imgtool/imgtool.cpp
src/tools/imgtool/imgtool.h
src/tools/imgtool/library.cpp
src/tools/imgtool/library.h
src/tools/imgtool/main.cpp
src/tools/imgtool/modules.cpp
src/tools/imgtool/modules.h

This is just the first step in a long process

Initial imgtool C++-ification

---

src/mame/drivers/didact.cpp

It still has some issues as it is a polled PIA based bitbangning serial support and there are timing issues that I am not sure is there on the real hardware which I unfortunality don't have access to. It partly works though and I am quite confident it is correctly setup, so it can also be bugs/flaws in the original rom

Esselte 100: Serial support 

---

hash/x68k_flop.xml

- New software list additions
aqualesd    Aquales (Demo)
genocid2da  Genocide 2 (Demo, Alt)
gradius2d   Gradius II - Gofer no Yabou (Demo)
lagoond     Lagoon (Demo)
lagoondo    Lagoon (Demo, Older)
lemmingsd   Lemmings (Demo)
phalanxd    Phalanx (Demo)
starwarsd   Star Wars - Attack on the Death Star (Demo)
http://wayder.blog102.fc2.com/blog-entry-2985.html

x68k: Added some clones to the software list

---

scripts/src/bus.lua
src/devices/bus/coco/coco_fdc.cpp
src/devices/bus/coco/coco_fdc.h
src/devices/bus/coco/dragon_fdc.cpp

Split CoCo and Dragon FDC code, added save state support, fixed regression introduced on the Dragon FDC from 0.154 and general cleanup.

CoCo and Dragon FDC code overhaul

---

hash/gba_ereader.xml

Adding all the Mario Party-e card collection (U)

New gba_ereader update

---

src/mame/drivers/didact.cpp
src/mame/layout/md6802.lay
src/mame/layout/mp68a.lay

Didact: simplified internal layouts removing dependencies on external artwork

---

src/frontend/mame/ui/selgame.cpp

Exporting is now also possible for the favorites list, except if it has software in it.

Partial fix for MT06383

---

src/mame/drivers/route16.cpp
src/mame/mame.lst

Stratovox (set 2) [MASH]
Romset: speak-squeak.zip (13kb)
SV-l  2048  1511  2001-05-19 20:03  BF4D5825
SV-2  2048  1412  2001-05-19 20:03  16739DD4
SV-3  2048  1585  2001-05-19 20:02  083C28DE
SV-4  2048  1380  2001-05-19 20:01  B0927E3B
SV-S  2048  1443  2001-05-19 20:00  CCD25C4E
SV-6  2048  1380  2001-05-19 19:57  07A907A7
SV-7  2048  1606  2001-05-19 19:56  4D333985
SV-8  2048  2048  2001-05-19 19:55  9B2377E0
This is another version of Stratovox with a female voice
in rom SV-8. MAME's version has a male voice.
All other roms are identical.

New Speak & Rescue clone

---

src/mame/drivers/segae.cpp
src/mame/mame.lst

for current list of donators see
http://www.mameworld.info/ubbthreads/showthreaded.php?Cat=&Number=358781
pull request can be applied once rom is available, rom will be available once cost is covered, which should be soon.

new WORKING game - Slap Shooter [Shoutime, The Dumping Union, (list of donators)]

---

src/mame/drivers/amusco.cpp

- Change CPU type to 8088
- Hook up a bunch of devices
- Identify a few inputs

amusco: Start fleshing out the driver

---

src/mame/layout/3bagflnz.lay
src/mame/layout/3bagflvt.lay
src/mame/layout/README.md

Also more grammar fixes in layout README

Clickable buttons for 3bagflnz, 3bagflvt (nw)

---

hash/apple1.xml

Added Extended Monitor.
Changed Lunar Lander (ASCII Graphics) to supported="partial" because the sound output is not supported.
Updated Wumpus with [errata](http://www.applefritter.com/?q=content/anyone-have-apple-1-copy-hunt-wumpus.)
[wumpus.zip](https://github.com/mamedev/mame/files/504941/wumpus.zip)
[extmon.zip](https://github.com/mamedev/mame/files/504940/extmon.zip)

update apple1 softwarelist

---

scripts/target/mame/arcade.lua
src/mame/drivers/funtech.cpp
src/mame/layout/fts2in1.lay
src/mame/mame.lst

this is similar to, but not identical to goldstar.cpp / skylncr.cpp.  it might be possible to merge it in, however my gut feeling is that said driver should be split up into different machine types all using some generic but fleixlbe video device that can handle these 8x8 tiles, 8x32 reel cases as most of them are based on the same basic concepts, just with their own tweaks.
reels, sounds, inputs are not hooked up here.
see
http://forums.bannister.org/ubbthreads.php?ubb=showflat&Number=107569&page=1
for PCB information.

new WORKING  Super Two In One [Edstrom, David Haywood]

---

src/tools/imgtool/filtbas.cpp
src/tools/imgtool/filteoln.cpp
src/tools/imgtool/imgtool.cpp
src/tools/imgtool/imgtool.h
src/tools/imgtool/library.h
src/tools/imgtool/main.cpp
src/tools/imgtool/modules/amiga.cpp
src/tools/imgtool/modules/bml3.cpp
src/tools/imgtool/modules/concept.cpp
src/tools/imgtool/modules/cybiko.cpp
src/tools/imgtool/modules/cybikoxt.cpp
src/tools/imgtool/modules/fat.cpp
src/tools/imgtool/modules/hp48.cpp
src/tools/imgtool/modules/hp9845_tape.cpp
src/tools/imgtool/modules/mac.cpp
src/tools/imgtool/modules/macbin.cpp
src/tools/imgtool/modules/os9.cpp
src/tools/imgtool/modules/prodos.cpp
src/tools/imgtool/modules/psion.cpp
src/tools/imgtool/modules/rsdos.cpp
src/tools/imgtool/modules/thomson.cpp
src/tools/imgtool/modules/ti99.cpp
src/tools/imgtool/modules/ti990hd.cpp
src/tools/imgtool/modules/vzdos.cpp

imgtool_partition ==> imgtool::partition
imgtool_directory ==> imgtool::directory

[Imgtool] C++-ified a few more classes

---

src/mame/drivers/rainbow.cpp

DEC 100 B Color Graphics Option: Doodle painter shows correct colors and Pacman is playable. Highres and vector mode still have unfixed bugs.

DEC Rainbow-100: correct medium resolution mode

---

hash/x68k_flop.xml

- New software added
bgelmntt - Blade of The Great Elements (Test Version)
phalanxs - Phalanx (Sample Version)
mjfants2 - Mahjong Gensoukyoku II - Mahjong Fantasia -The 2nd Stage
- Add 2HDE Format Header (Unsupported)
ldb_x68k - Login Disk & Book Series - X68000 Kessaku Game-sen
- New/fix software (The World of X68000) added
formulaxa - The World of X68000 - Formula X
fortatgj - The World of X68000 - Fortress Attack & GJ
lcmyprin - The World of X68000 - Logic Rush & Ah! Ohimesama!
cryokua - The World of X68000 II - C Ryoku Kensa
cynthiaa - The World of X68000 II - Cynthia
rushusfl - The World of X68000 II - Rush! & Useful
t94xa - The World of X68000 II - T-94X
- Delete software list in "coming from real disk"
cryokua -> The World of X68000 II - C Ryoku Kensa
cynthi2 -> The World of X68000 …

x68k: Add/fix to the software list

---

src/mame/drivers/toaplan1.cpp
src/mame/mame.lst

seems to be older than the parent (still has a 1989 date) but newer than the other sets (sound rom matches parent, attract cycle matches parent) so added it as set 2.
old set 2 becomes set 3
old set 3 becomes set 4
old set 4 becomes set 5
I've asked if the other roms can be dumped so we can use the proper rom labels for the gfx.

new clones  Demon's World / Horror Story (set 2) [Sugoi Helsinki]

---

scripts/target/mame/mess.lua
src/mame/drivers/accexx.cpp
src/mame/drivers/aceex.cpp
src/mame/mame.lst
src/mame/mess.flt

Just a start do get the ROM in there

Skeleton driver for 1995 Accexx 28.8 modem started

---

hash/segacd.xml

I fixed all the errors and dumb stuff that was pointed out to me (thanks everyone) and did a few new updates toward a better structure of the list.

Fix errors with new Sega CD softlist

---

src/devices/machine/msm5832.cpp
src/mame/drivers/amusco.cpp

- RTC writes now actually go through, so the game will remain stuck in 1987 until the date is changed
- Add the new machine flag for the unemulated printer
- Remove MSM5832 device name from logging messages

amusco: Minor changes (nw)

---

src/devices/machine/z80scc.cpp

- Added iack by reading rr2
- z80daisy_iack now returns -1 when no vector found or disabled through the WR9 VIS
- Removed z80daisy_reti code to match SCC documentation
- Removed defacto reset values where possible and replaced them with documented SCC reset values

SCC iack and reset improvements

---

src/devices/machine/z80scc.cpp
src/devices/machine/z80scc.h

Added Tx fifo including special case with 1 slot tx fifo for NMOS and CMOS. 
It didn't fix the self test problem on Sun 3-80 but may improve the performance of the indigo driver, which I am unable to test

SCC improved Tx handling

---

src/mame/drivers/zn.cpp

Added subtitle as per the PS1 game

Proper name for bam2 (nw)

---

src/tools/imgtool/filtbas.cpp
src/tools/imgtool/filteoln.cpp
src/tools/imgtool/imgtool.cpp
src/tools/imgtool/main.cpp
src/tools/imgtool/modules/hp9845_tape.cpp
src/tools/imgtool/modules/mac.cpp
src/tools/imgtool/modules/macbin.cpp
src/tools/imgtool/modules/thomson.cpp
src/tools/imgtool/stream.cpp
src/tools/imgtool/stream.h

Updated quite a bit of client code that manually owned these pointers

[Imgtool] Changed imgtool::stream::open*() to return imgtool::stream::ptr

---

src/devices/machine/z80scc.cpp
src/devices/machine/z80scc.h
src/mame/drivers/indy_indigo2.cpp

Allows the indy_indigo2.cpp to have a console

SCC: Added support for RTxC as BRG clock source

---

src/mame/drivers/neodriv.hxx
src/mame/mame.lst

closer to the final version than the other proto, gfx/sound data matches released game just in different rom arrangement, program code is unique.

new clones    Burning Fight (prototype, ver 23.3, 910326) [Collin Foust]

---

src/mame/drivers/didact.cpp
src/mame/mame.lst

- can09 a non working driver for the Candela main computer, a 6809 based design with FDC and a 6850 CRTC
- can09t a somewhat working driver for the Candela terminal, a slimmer version without FDC and with a terminal interface

- WIP The Candela computers

---

src/devices/machine/z80scc.cpp
src/mame/drivers/mac128.cpp

Allows macplus & co to boot now

SCC bugfix in rr15 support

---

src/mame/drivers/rainbow.cpp

Colors in highres mode and video levels

Enhance DEC Rainbow 100 Option Graphics

---

src/devices/cpu/tlcs900/dasm900.cpp

Fixed some paren spacing, converted a char[] buffer to std::string

Further cleanups to the TLCS900 disassembler

---

language/German/strings.po

This PR updates the German translation of the integrated MAME UI.
Additions, corrections and discussions are welcome, as always.

GUI: Update German translation

---

src/devices/machine/z80scc.cpp
src/devices/machine/z80scc.h

Allows mouse pointer to move in macplus driver for Mac OS 6.08

SCC improved intterrupt handling

---

src/devices/machine/z80scc.cpp

one bug down but I suspect there are more, let me know. This improves the success ratio a lot getting the mouse working in both X and Y

SCC Fixed init state of latched rr0 values

---

src/mame/drivers/pg685.cpp

Like for the PG 685 variants, I've added a description on the major ICs used on the PG 675's PCBs.

Added hardware info for the PG 675

---

src/mame/drivers/dcon.cpp
src/mame/drivers/goodejan.cpp

goodejan.cpp: Improve PCB documentation (nw)

sdgndmps: Add DIP SW names and locations (verified from manual)

---

src/devices/machine/pit8253.cpp
src/mame/drivers/amusco.cpp

pit8253: MSB-only counter writes need to lower outputs in mode 0

amusco: Fix PIT IRQs; game speed is much better now

---

src/devices/machine/pic8259.cpp
src/mame/drivers/pg685.cpp

i8259: Use resolve_safe to protect against segfaults (nw)

pg685: Preliminary hookups for numerous devices (nw)

---

src/devices/cpu/arcompact/arcompactdasm.cpp
src/devices/cpu/arcompact/arcompactdasm_dispatch.h
src/devices/cpu/arcompact/arcompactdasm_ops.cpp
src/devices/cpu/arcompact/arcompactdasm_ops.h
src/tools/unidasm.cpp

Also added arcompact to unidasm

Changed the arcompact disassembler to use 'std::ostream &' internally

---

src/osd/modules/debugger/debugwin.cpp
src/osd/modules/debugger/win/debugwininfo.cpp
src/osd/modules/input/input_dinput.h
src/osd/modules/input/input_rawinput.cpp
src/osd/modules/input/input_sdlcommon.cpp
src/osd/modules/input/input_uwp.cpp
src/osd/modules/input/input_win32.cpp
src/osd/modules/monitor/monitor_dxgi.cpp
src/osd/modules/monitor/monitor_sdl.cpp
src/osd/modules/monitor/monitor_win32.cpp
src/osd/modules/osdwindow.h
src/osd/modules/render/draw13.cpp
src/osd/modules/render/drawbgfx.cpp
src/osd/modules/render/drawd3d.cpp
src/osd/modules/render/drawgdi.cpp
src/osd/modules/render/drawnone.cpp
src/osd/modules/render/drawogl.cpp
src/osd/modules/render/drawsdl.cpp
src/osd/modules/sound/direct_sound.cpp
src/osd/sdl/window.cpp
src/osd/sdl/window.h
src/osd/uwp/video.cpp
src/osd/uwp/window.cpp
src/osd/uwp/window.h
src/osd/windows/video.cpp
src/osd/windows/window.cpp
src/osd/windows/window.h
src/osd/windows/winmain.cpp

Sending as a pull request to make sure it builds in CI. Tested locally on Linux, Windows, Mac, and UWP

Change window handle storage to template instead of void* (nw)

---

src/mame/drivers/amusco.cpp

- Coin inputs now read properly through IRQ4
- Promote draw88pkr to WORKING (no more "COIN ERROR" on startup, though POST still fails memory test for some reason)
- Removed spurious coin counter
- Updated notes on printer

amusco.cpp: Coin-related improvements

---

src/mame/drivers/namcos2.cpp

this version does not match Japan or any of the ports, and sounds like incorrect sounds are being played.

Tagged as imperfect sound and needing redump of sound rom - the sound in

---

src/mame/drivers/pg685.cpp

- Fill out memory maps, adding I/O handler stubs based on disassembly and notes

pg685.cpp: Give pg675 its own config (nw)

---

src/mame/drivers/bionicc.cpp

First pull request ever, never used git before.
I added a few information in the comments, most notably the clock frequency of the C8751H-88 protection MCU which was unknown so far.

Clock frequencies in bionicc.cpp

---

src/mame/drivers/rainbow.cpp

Make port 50 readable (undocumented, yet used) and revert WRITE_MASK change from last commit. Test case: freeware game SCRAM shows bitmapped intro. R-M-W 'synchronization' (which involves port $50 of external logic and the mode register) still needs to be investigated. Reference: PDF AA-AE36A-TV (June 1984).

DEC Rainbow 100: make port 50 readable

---

scripts/target/mame/mess.lua
src/devices/machine/z80scc.cpp
src/emu/drivers/xtal.h
src/mame/drivers/lwriter.cpp
src/mame/mame.lst
src/mame/mess.flt

The Laser Writer driver is written to be a reference peer for some SCC work supporting Localtalk and the SCC improvements are needed by pwm for the Intergraph driver

WIP Apple Laser Writer II NT and some SCC improvements

---

src/mame/drivers/rainbow.cpp

Change 7220 divider from 4 to 32 (closer to 1 Mhz from VT240). Clock test from the GDC test disk passes (Short test -> subtest 5) and scroll test actually displays something.
Also: stop flicker when color video is off (hgdc_display_pixels) and change the effect of GDC_MODE_ENABLE_VIDEO. See page 21 of PDF AA-AE36A.

DEC Rainbow 100 color board clock fix

---

.gitignore
3rdparty/genie/.gitignore

Read this backwards, this would be bad (nw)

---

src/mame/drivers/rainbow.cpp

Address reentrance problems (reset procedure). Make scroll fully functional (SCRAM levels & GDC diag test #9). Details and credits: see driver.

DEC Rainbow 100: scroll fully functional / address reentrance problems

---

src/mame/drivers/pg685.cpp

Changed floppy controller to FD1797. Floppy controller not hooked up yet.

Added floppy drives to the PG675 and PG685 variants. 

---

src/mame/drivers/rainbow.cpp

Correct cursor position in REGIS TSR

DEC Rainbow 100: correct cursor position in REGIS

---

src/mame/drivers/rainbow.cpp

Parity test on memory board uses NMI now. Fixes the 1st memory test on rx50diag.td0 as well as the 'long' BIOS self test (key 'S'). Wrong aspect ratios in graphics mode also corrected (requires 'Graphics Only' + suitable cmd. line parameters).

DEC Rainbow 100 : implement NMI for parity test / fix aspect ratio

---

scripts/src/bus.lua
src/devices/bus/coco/coco_t4426.cpp
src/devices/bus/coco/coco_t4426.h
src/mame/drivers/coco12.cpp
src/mame/mame.lst

For review by coco maintainer and others

Added coco2 clone t4426 (nw)

---

hash/neogeo.xml
src/mame/drivers/neodriv.hxx
src/mame/drivers/playmark.cpp
src/mame/drivers/powerbal.cpp
src/mame/includes/playmark.h
src/mame/mame.lst

this gives partial sound, OKI banking setup for the game is incorrect in the driver so music doesn't currently play
also I cleaned up OKI banking in the whole driver by using configured banking to make further work cleaner

added PIC16c57 dump to wbeachvl [Caps0ff]

---

src/devices/machine/74157.cpp
src/devices/machine/74157.h
src/mame/drivers/dec0.cpp
src/mame/drivers/discoboy.cpp
src/mame/drivers/inder.cpp
src/mame/drivers/mitchell.cpp
src/mame/drivers/rastan.cpp
src/mame/drivers/spinb.cpp
src/mame/drivers/yunsung8.cpp

- Add 74HCT157 device type alias
- Hook up 74HCT157 in inder.cpp and spinb.cpp as per schematics
- Change device and macro names

74157 updates, pinball division (nw)

---

src/mame/drivers/rainbow.cpp

Serial port A now functional. Printer port B needs more work.

DEC Rainbow 100: serial port now functional

---

src/mame/drivers/system16.cpp
src/mame/includes/system16.h

- Hook up MSM5205 and 74LS157 on the 2xYM2203 bootlegs, all of which now have some imperfect samples playback
- Correct goldnaxeb2 configuration to use the aforementioned sound system

system16.cpp: Sound improvements for some bootlegs

---

src/devices/cpu/m6805/m6805.cpp
src/devices/cpu/m6805/m6805.h
src/mame/drivers/slapfght.cpp
src/mame/includes/slapfght.h
src/mame/machine/slapfght.cpp

start putting some 68705 functionality in the CPU core rather than copy+pasted in all the drivers.
as this is a lengthy task I've created a derived CPU type with the new functionality to aid in the process without disrupting existing drivers that haven't yet been updated.
started with tiger heli / slap fight.

start putting some 68705 functionality in the CPU core rather than copy+pasted in all the drivers.

---

src/mame/drivers/toaplan2.cpp
src/mame/includes/toaplan2.h
src/mame/mame.lst

input ports could be cleaned up a bit (there's probably some kind of hopper in there?) but it's functional.  no real clue how to play the game tho as it's entirely in Japanese and seems to be some kind of lie detector based on pulse rate??

new WORKING -  Enma Daio (Japan) [ShouTime, The Dumping Union] (other credits??)

---

src/devices/cpu/m6805/m6805.cpp
src/devices/cpu/m6805/m6805.h

- All internal memory handlers are now private members
- DDRs zeroed when device reset (as per datasheet)
- Port writes no longer transmit bits not set in DDR
- DDR updates may cause port bits to be written out (this is important)
- Add external read/write handlers for ports

Improvements to I/O emulation in new MC68705 device (nw)

---

src/mame/drivers/x1.cpp

- Added all kana and kana+shift key combinations
- Changed the kana key into a toggle, like in real hardware
- Added some missing keys that exist on the actual X1 keyboard

x1.cpp: add kana input

---

scripts/target/mame/arcade.lua
src/mame/arcade.flt
src/mame/drivers/hapyfish.cpp
src/mame/mame.lst

we've been sitting on this for a while, progress was shown a few years ago, but is apparently lost.  Smitdogg should be able to clarify the exact part numbers, they're not readable in the pictures.
ARM core is better than it was a few years ago too, so might actually work better if hooked up again now.

new NOT WORKING - Happy Fish (V2 PCB, 302-in-1) [The Dumping Union]

---

src/mame/drivers/elwro800.cpp

- NMI handler in separate opcode space so "direct handler can trivially go away" (as R. Belmont suggested)
- Use address_map_bank_device instead of dynamically splicing RAM and ROM banks into the map

elwro800.cpp: Memory cleanup (nw)

---

src/devices/machine/i8255.cpp
src/lib/formats/imd_dsk.cpp
src/lib/formats/td0_dsk.cpp

i8255 change makes it fail system board test a little later.

misc. fixes exposed by Displaywriter WIP

---

hash/ibm6580.xml
scripts/target/mame/mess.lua
src/devices/imagedev/floppy.cpp
src/devices/imagedev/floppy.h
src/mame/drivers/ibm6580.cpp
src/mame/layout/ibm6580.lay
src/mame/machine/ibm6580_fdc.cpp
src/mame/machine/ibm6580_fdc.h
src/mame/machine/ibm6580_kbd.cpp
src/mame/machine/ibm6580_kbd.h

Softlist contents and "old" ROMs are from bitsavers.

IBM 6580 Displaywriter de-skeletonization [shattered]

---

src/mame/drivers/polepos.cpp
src/mame/includes/polepos.h

- Working Spanish/Italian voices in polepos2bi and polepos2bs
- DAC for passing car sound in topracern, polepos2bi and polepos2bs
- These bootlegs may still be missing explosion sounds

polepos.cpp: Sound improvements for bootlegs

---

hash/x1_cass.xml

Not my own dumps. Source unknown.

x1_cass.xml: misc additions

---

scripts/src/3rdparty.lua
src/osd/modules/sound/pa_sound.cpp

Some fixes for the PortAudio implementation.

PortAudio fixes

---

3rdparty/portaudio/src/hostapi/wasapi/pa_win_wasapi.c

Hopefully fixes buildbot's nightlies.

Fix PortAudio MinGW cross-compilation

---

src/tools/imgtool/formats/coco_dsk.cpp

[CoCo] Fixed a recently introduced bug in DMK image creation

---

src/mame/drivers/skyarmy.cpp

- Fix screen flipping in cocktail mode
- Re-add second AY-3-8910A that generates explosion sounds; the claim as to its absence made in 2003 was probably based on less accurate AY8910 emulation and/or a stripped PCB
- Add coin counter

skyarmy: Various small improvements

---

3rdparty/portaudio/src/hostapi/wasapi/mingw-include/audioclient.h

Fix MinGW cross-compilation, for real this time

---

scripts/src/machine.lua
src/devices/machine/68230pit.cpp
src/devices/machine/68230pit.h
src/devices/machine/68561mpcc.cpp
src/devices/machine/68561mpcc.h
src/mame/drivers/fccpu20.cpp

- 68230 PIT: Added support for the PSR register, H1-H4 sense and direct pin levels
- WIP: fccpu20: added mpcc device and serial interface (nw)

- WIP: Refactored device: MPCC 68561 (nw)

---

src/osd/modules/lib/osdobj_common.cpp
src/osd/modules/sound/pa_sound.cpp

Sorry for the abundance of PRs, this is hopefully the last one for a while.

Some PortAudio-related changes and fixes

---

src/mame/drivers/polyplay.cpp
src/mame/mame.lst

- added new polyplay2 romset; german version with 10 games (6 new ones)
- renamed czech version to polyplay2c and made a clone of polyplay2

polyplay: add a german version of zre-pp base polyplay (with 10 games)

---

README.md
android-project/LICENSE
benchmarks/LICENSE
docs/source/conf.py
docs/source/license.rst
docs/source/whatis.rst
src/lib/netlist/prg/nltool.cpp
src/lib/netlist/prg/nlwav.cpp
src/osd/modules/render/bgfx/shaders/shader.mk
tests/LICENSE
uismall.bdf
web/LICENSE

Updates "2016" strings to "2017 where relevant.

2016-2017 changes

---

src/devices/cpu/clipper/clipper.h

include limits.h that provides INT_MIN and INT_MAX

fix clipper cpu build.

---

src/osd/modules/sound/pa_sound.cpp

Fixes a critical bug that causes segfaults. Only seems to affect the 32-bit builds, but might affect 64-bit builds as well.

Fix issues on 32-bit builds and clamp latency

---

src/devices/bus/vme/vme_fccpu20.cpp
src/devices/bus/vme/vme_fccpu20.h
src/mame/drivers/fccpu20.cpp
src/mame/mame.lst

Added board variant handling and a few variants

Force CPU-20

---

src/devices/bus/ieee488/hp9895.cpp
src/devices/bus/ieee488/hp9895.h
src/devices/machine/fdc_pll.cpp
src/devices/machine/phi.cpp
src/devices/machine/phi.h

Hi,
this PR fixes a couple of problems with HP9895 disk drive emulation.
As far as I can tell the emulation behaves as it should now.
It previously had an issue with IEEE488 interface and one with AM synchronization.
Thanks.
--F.Ulivi

Bug fix for HP9895

---

src/mame/drivers/bzone.cpp

Mame Testers Bug:
http://mametesters.org/view.php?id=6489

Correctly assign service button(s)

---

bgfx/chains/hqx/hq2x.json
bgfx/chains/hqx/hq3x.json
bgfx/chains/hqx/hq4x.json

Very minor pull request, this just updates the FSF address in the license header of a few shaders.

Updates FSF address in a few files.

---

scripts/src/formats.lua
src/lib/formats/ms0515_dsk.cpp
src/lib/formats/ms0515_dsk.h
src/mame/drivers/ms0515.cpp
src/mame/layout/ms0515.lay

Reworked https://github.com/mamedev/mame/pull/2052
Formatting done with clang-format, using config at https://gist.github.com/shattered/5ce9af8ad3bcaabf88aef569ef36ab43

ms0515.cpp -- hook up keyboard and floppy, improve video emulation etc. (take 2)

---

src/mame/drivers/namcos22.cpp

Source: game manuals and sound test messages

namcos22: Add per-game speaker configurations

---

src/devices/bus/nes/nes_carts.cpp
src/devices/bus/nes/zemina.cpp
src/devices/bus/nes/zemina.h
src/mame/drivers/galaxold.cpp
src/mame/drivers/marineb.cpp
src/mame/includes/marineb.h

And one miscellaneous commit to go along with them:
- made rockclim base off mooncrst in galaxold.cpp (Z80 sound code was stolen from that game and MAME code suggests that the video board uses some mooncrst logic, so...)

Cleanups to satisfy cuavas's OCD

---

src/frontend/mame/mameopts.cpp
src/lib/util/options.cpp
src/lib/util/options.h

e.g. - 'next -scsibus:1 "" -listdevices'

Fixed regression pertaining to specification of empty strings as slot names

---

src/emu/dislot.cpp
src/emu/dislot.h
src/frontend/mame/mameopts.cpp
src/frontend/mame/ui/slotopt.cpp

Added device_slot_interface::has_selectable_options() to calculate whether a particular slot has selectable options

Cleanup of slot code

---

src/mame/drivers/bitgraph.cpp
src/mame/layout/bitgrpha.lay
src/mame/layout/bitgrphb.lay

now screenshots look nice ( not resized from 768x1024 to 1024x768 :) )

bitgraph: switch from layouts to rotation flags, unbreak keyboard

---

src/mame/drivers/polyplay.cpp

this is a fix for https://github.com/mamedev/mame/pull/2092

polyplay: fixed SIO for real... (nw)

---

scripts/src/bus.lua
scripts/target/mame/mess.lua
src/devices/bus/a2bus/a2diskii.cpp
src/devices/bus/a2bus/a2diskii.h
src/devices/bus/a2bus/agat7langcard.cpp
src/devices/bus/a2bus/agat7langcard.h
src/devices/bus/a2bus/agat7ram.cpp
src/devices/bus/a2bus/agat7ram.h
src/emu/drivers/xtal.h
src/mame/drivers/agat.cpp
src/mame/drivers/apple2.cpp
src/mame/mame.lst
src/mame/mess.flt
src/mame/video/agat7.cpp
src/mame/video/agat7.h

Reworked version of https://github.com/mamedev/mame/pull/2146

agat: split from apple2, implement basic agat7 hardware (take 2).

---

hash/megadriv.xml

Hello,
A few japanese game confirmation and a new dump.
Some cart weren't open because of label on top of screw and games aren't cheap.
You can find pictures of the cart and pcb (sorry no more scanner) here : 
https://www.megadrive.org/elbarto/megadrive/dump/IMG_0161.JPG
https://www.megadrive.org/elbarto/megadrive/dump/IMG_0162.JPG

Confirm a few japanese dump and add a new one.

---

src/devices/sound/upd1771.cpp

Ref: https://en.wikipedia.org/wiki/Cassette_Vision

Fix "Cassette" spelling

---

src/devices/cpu/mips/mips3drc.cpp

instruction before trying to generate code to add it to the block
checksum.

mips3 drc : Make sure branch delay slot instruction is not virtual

---

src/mame/drivers/hp9845.cpp

Hi,
this PR is for an improvement of the light pen emulation of 9845C system.
The LP now behaves a lot better than before even though there are still some (minor) problems here and there.
Hopefully I'll fix them in the (near) future.
Thanks.
--F.Ulivi

Improvements to 9845C light pen emulation

---

src/devices/machine/6821pia.cpp
src/devices/machine/6821pia.h

1.  Changed some 'int' ==> 'bool' where appropriate
2.  Changed the various control byte macros to static functions

Incremental C++-ification of 6821pia.cpp

---

hash/c64_cass.xml
hash/vic1001_cass.xml

added speakeasy software to support PPP speakeasy hardware
https://www.sendspace.com/file/52xvix

vic1001_cass.xml and c64_cass.xml dumps

---

src/emu/debug/debugcpu.cpp

Fixes problem in the debugger and the cheat engine as currently the writes to opcode memory are not handled correctly, so separated EXPSPACE_RAMWRITE and EXPSPACE_OPCODE case statements to allow opcode writes to access the correct memory.
Example:
In flicky this will now disable cat collisions with the main sprite:
maincpu.ob@3ac6=c3

Fixed writes to decrypted opcode memory

---

src/emu/debug/debugcpu.cpp

Fixes problem in the debugger and the cheat engine as currently the writes to opcode memory are not handled correctly, so separated EXPSPACE_RAMWRITE and EXPSPACE_OPCODE case statements to allow opcode writes to access the correct memory.
Example:
In flicky this will now disable cat collisions with the main sprite:
maincpu.ob@3ac6=c3
This is the simplest way of updating this, EXPSPACE_OPCODE is now a copy of EXPSPACE_RAMWRITE except it uses AS_DECRYPTED_OPCODES instead of AS_PROGRAM. This method means I've got a lot of work updating a lot of cheat file warnings ...but this is the correct way of doing this.

Fixed writes to decrypted opcode memory [v3]

---

src/devices/cpu/sm510/sm510d.cpp
src/tools/imgtool/filtbas.cpp

Some very low hanging fruit from Coverity. Compile tested.

Fix unintentional string concatenation

---

src/emu/debug/debugcmd.cpp

unmapped holes.
Previously, 'dasm' would enter an infinite loop if it hit an
unmapped pc, continuing to grow the output file until the program
was killed.

Make debugger 'dasm' command able to traverse virtual spaces with

---

hash/fmtowns_cd.xml
hash/pc98_cd.xml

FM Towns:
F-BASIC386 Compiler v1.1 L21
Dennou Ehon - Kyouryuu no Sekai
Hyper Oku no Hosomichi
Soko-ban Perfect
Youjuu Senki 2 - Reimei no Senshi
PC-98:
Jorougumo - Jubaku no Dorei-tachi
Ms. Detective File #1 - Iwami Ginzan Satsujin Jiken
Youjuu Senki 2 - Reimei no Senshi

fmtowns_cd.xml & pc98_cd.xml: added several dumps

---

3rdparty/bx/src/string.cpp

VS fix. (nw)

---

src/devices/cpu/i86/i86.cpp

Correct i86.cpp

---

src/mame/drivers/vii.cpp
src/mame/mame.lst

Wireless 60 (Jungle Soft / Kids Station Toys Inc)

New working machine added: Wireless 60

---

src/emu/diimage.cpp

This fixes crashes invoked by the following command lines
mame nes zelda
mame gamate cubeup
These had two independent causes.  The first crash was a consequence of open_image_file() doing something inappropriate required by implementations of get_default_card_software().  The second crash was a failure to access image options moved outside the core_options structure.

Fixed some regressions introduced in my recent refactoring related to software lists

---

src/devices/bus/megadrive/md_slot.cpp
src/devices/bus/megadrive/md_slot.h
src/devices/bus/msx_slot/cartridge.cpp
src/devices/bus/msx_slot/cartridge.h
src/devices/bus/nes/nes_slot.h
src/devices/bus/nes/nes_unif.hxx
src/devices/bus/pce/pce_slot.cpp
src/devices/bus/pce/pce_slot.h
src/devices/bus/scv/slot.cpp
src/devices/bus/scv/slot.h
src/devices/bus/sega8/sega8_slot.cpp
src/devices/bus/sega8/sega8_slot.h
src/devices/bus/snes/snes_slot.cpp
src/devices/bus/snes/snes_slot.h
src/devices/bus/vcs/vcs_slot.cpp
src/devices/bus/vcs/vcs_slot.h
src/devices/bus/wswan/slot.cpp
src/devices/bus/wswan/slot.h

Also changed a few methods to return 'bool' when appropriate

Made a number of methods be const correct and static where appropriate

---

src/mame/drivers/esd16.cpp

Head Panic's nude/bikini pics are displayed after a level when set; more modesty means more clothes and vice versa

esd16: Documentation update (nw)

---

src/devices/bus/hp9845_io/98035.cpp
src/devices/cpu/hphybrid/hphybrid.cpp
src/mame/drivers/hp9845.cpp
src/mame/includes/hp9845.h

Hi,
this set of commits implements the HP9845T driver.
The main feature of this machine from the 9845 line was the hardware-accelerated monochromatic graphic video (HP98780A).
The driver was written together with Ansgar Kueckes.
I'm mailing the ROM images to the usual "code" e-mail.
Thanks.
--F.Ulivi

New driver: HP9845T

---

scripts/target/mame/arcade.lua
src/mame/drivers/supstarf.cpp
src/mame/mame.lst

* Super Star (Recreativos Franco) [AJR, Akiles500]

New NOT WORKING:

---

src/emu/romload.cpp

Workaround for sibling disk image loading issue

---

src/emu/image.cpp

This is a hack; details are in the source code.  I felt that it was too late in the 0.185 release cycle to do anything intrusive.  I intend to fix this "for real" when image/slot option morphing is encapsulated within emu_options.

Workaround for issue where the cannonical instance_name for a device was lost

---

src/devices/machine/z80scc.cpp
src/devices/machine/z80scc.h

z80scc: Reset Tx Interrupt Pending Command implemented

---

src/mame/drivers/hh_tms1k.cpp

hh_tms1k.cpp fix typo

---

src/devices/machine/6522via.cpp

which improved  but not completely reverted the vectrex regression

via6522: fixed the flank timer value 

---

src/devices/machine/hp_taco.cpp
src/mame/drivers/hp9845.cpp

Hi,
this PR introduces the handling of display softkeys in hp9845C & T emulation.
It also improves the accuracy of the displayed image of these systems.
Thanks.
--F.Ulivi

Hp9845: softkeys & video rendering improvements

---

src/emu/machine.cpp
src/emu/machine.h
src/frontend/mame/ui/ui.cpp

- Changed running_machine::schedule_[load|save]() to take 'std::string &&' instead of 'const char *'
- Changed running_machine::saveload_schedule to be 'enum class'

Refactoring/cleanup to state load/save handling

---

src/frontend/mame/clifront.cpp
src/frontend/mame/clifront.h
src/lib/util/options.cpp
src/lib/util/options.h

Earlier I was handling 'mame64 -listsource pacman' but not 'mame64 pacman -listsource'

Bug fix to -romident and aux verb cleanup (take two)

---

src/frontend/mame/clifront.cpp
src/frontend/mame/clifront.h
src/frontend/mame/mameopts.cpp

The issue is that -listmedia/-listslots were not honoring command line options specified on the slot.  This works around the problem.

Fixed a regression in -listmedia/-listslots

---

scripts/src/formats.lua
scripts/target/mame/mess.lua
src/devices/bus/coco/coco_fdc.cpp
src/devices/bus/coco/dragon_fdc.cpp
src/lib/formats/sdf_dsk.cpp
src/lib/formats/sdf_dsk.h
src/mame/drivers/dragon.cpp

The CoCoSDC has been around for a while now, with more than 500 sold. A disk format gaining in popularity.

Added read support for the disk format SDF used in the CoCoSDC

---

src/mame/drivers/hornet.cpp

In according with Test mode and boot up.
http://i.imgur.com/8B9GaFU.png
http://imgur.com/jz6bZCg.png

Correct descriptions for Gradius 4 : Fukkatsu, Silent Scope 2

---

src/mame/drivers/galaxian.cpp
src/mame/includes/galaxian.h
src/mame/mame.lst

doesn't look like the original needs rom 5, the bootleg however you can't shoot anything in, presumably they moved some code around causing it to need an extra rom? unfortunately the chip on the bootleg was dead.
decryption figured out by ArcadeHacker.

New WORKING machine - Victory (Comsoft) [Andrew Welburn, ArcadeHacker, David Haywood]

---

src/devices/video/ef9365.cpp
src/devices/video/ef9365.h

(This fix the ARC Squale Basic instruction and probably many others stuffs)

EF9365 : Fix the hardware vector engine.

---

src/devices/bus/coco/coco_ssc.cpp

Added delay to SSC busy bit. (nw)

Coco ssc busy delay

---

src/mame/includes/coco.h
src/mame/machine/coco.cpp
src/mame/machine/coco12.cpp
src/mame/machine/dgnalpha.cpp
src/mame/machine/dragon.cpp

1.  Changed '#ifndef __COCO__' ==> '#ifndef MAME_INCLUDES_COCO_H'
2.  Moved device declarations to be private, added accessors when necessary

[CoCo]  Miscellaneous cleanups/hygiene (nw)

---

src/mame/includes/coco12.h
src/mame/includes/coco3.h
src/mame/includes/dragon.h
src/mame/machine/6883sam.cpp
src/mame/machine/6883sam.h
src/mame/machine/coco12.cpp
src/mame/machine/coco3.cpp
src/mame/machine/dragon.cpp

1.  Moved [required|optional]_device declarations to be private
2.  Better use of references in 6883sam.cpp
3.  Standardized how constructors are formatted

[CoCo] Miscellaneous code cleanups/hygiene (nw)

---

src/mame/drivers/coco3.cpp
src/mame/includes/coco3.h
src/mame/video/gime.cpp
src/mame/video/gime.h

1.  Moved specific implementations to anonymous namespace
2.  gime_base_device ==> gime_device
3.  Changed a pointer to a reference

[CoCo 3]  Cleanups to the GIME implementation

---

src/mame/drivers/pitnrun.cpp
src/mame/includes/pitnrun.h
src/mame/machine/pitnrun.cpp
src/mame/mame.lst
src/mame/video/pitnrun.cpp

same hardware as pitnrun, with no MCU populated.
no copyright on the title screen, thought to be by Kaneko.

new WORKING game - Jump Kun (prototype) [ShouTime]

---

src/mame/drivers/flstory.cpp
src/mame/includes/flstory.h

use actual M68705P5 dump for Rumba Lumber, replaces inaccurate simulation [ShouTime, brizzo]

---

src/mame/drivers/decocass.cpp
src/mame/includes/decocass.h
src/mame/machine/decocass.cpp
src/mame/mame.lst

this is in various public rom collections, and even on MAMEdev, but was never added?
looks like a 100% legitimate Japanese version, complete with the alt (harder) maze.

 new working clone Lock'n'Chase (DECO Cassette) (Japan) [??]

---

src/mame/drivers/nes_vt.cpp
src/mame/mame.lst

boots to menu, some games are playable

new NOT WORKING  Game Prince RS-16 [BeckieRGB]

---

hash/gameboy.xml
src/devices/bus/gameboy/gb_slot.cpp
src/devices/bus/gameboy/gb_slot.h
src/devices/bus/gameboy/mbc.cpp
src/mame/drivers/gb.cpp

Some miscellaneous game boy documentation updates and a simple constant initialization as reported by coverity. Additionally, I converted the mbc1 collection check to compare the whole game title instead of only checking select bytes (probably came from GoodGBX).

Gameboy v7

---

src/mame/drivers/tehkanwc.cpp

(presumably different locations populated on PCB, test mode indicates as such)
without this demo sound dipswitch etc. isn't mapped properly.
also hook up diplocations etc. for all sets in driver.
I think maybe this driver also needs some kind of PPI devices? not sure which tho.

new tehkanwcd clone has a different dipswitch setup to the other sets, fix driver, add diplocations)

---

src/devices/cpu/upd7810/upd7811.cpp
src/devices/cpu/upd7810/upd7811.h
src/mame/machine/cchip_dev.h

I'd actually already made these fixes in the wrong tree, oops.

tidy cchip_dev (nw)

---

src/mame/drivers/hp80.cpp

Hi,
this PR is for a set of improvements I made to HP85 emulation, namely:
- More correct timing of video memory access. Test "F" of service ROM now passes.
- Added beeper
- Implemented the hardware timers. Test "J" passes.
Thanks.
--F.Ulivi

hp85: improvements

---

scripts/src/video.lua
scripts/target/mame/arcade.lua
scripts/target/mame/mess.lua
src/devices/machine/68340.cpp
src/devices/machine/68340.h
src/devices/machine/68340sim.cpp
src/devices/machine/68340sim.h
src/devices/video/sda5708.cpp
src/devices/video/sda5708.h
src/mame/drivers/dbox.cpp

This is only half done but it is a good branch point where I will implement the LED display both using a small video display and in a separate branch using the layout system to compare performance
Anyway there are work on the 68340 too and the Dbox now can display some ascii art characters using the LOG macro printouts proving the sda5708 hookup is somewhat correct

New device: SDA5708 + 68340 improvements for the Nokia Dbox (nw)

---

src/devices/machine/i82586.cpp
src/devices/machine/i82586.h

Not sure if I'm too late for the next release, but 82586/82596 is functional and working with InterPro.
Some work remains, but nothing major:
* testing for 82586 and 82596 big endian and non-linear modes
* more complete statistics capturing
* 82596 monitor mode
* throttle timers and diagnostic command
* special case handling for different 82596 steppings in big endian mode

i82586: functional, ~90% complete

---

src/mame/drivers/seattle.cpp
src/mame/drivers/vegas.cpp
src/mame/layout/sf2049.lay
src/mame/machine/midwayic.cpp
src/mame/machine/midwayic.h

That leader lamp bit makes me question the purpose of that "valid" bit as they are in every write on the vegas wheelboard, but I wouldn't know how to go about testing that.
Added a layout for sf2049 as well. There is something on lamp4, but I can't identify it.

Improved wheel board on flagstaff and vegas

---

src/mame/machine/6883sam.cpp
src/mame/machine/6883sam.h

This affected the CoCo/Dragon family of drivers
Special thanks to Ciaran Anscomb for identifying this problem

SAM6883: Fixed a bug by which VDG addressing incorrectly honored the page bit

---

src/mame/drivers/midvunit.cpp
src/mame/includes/midvunit.h

Found manual with schematics and it all fits well.
Couldn't find any jeds for the PALs however, so had to work backwards for them.

Better documentation for midvunit wheel board

---

hash/fmtowns_cd.xml
hash/fmtowns_flop.xml

Added several entries to FM Towns softlists

---

src/mame/drivers/segac2.cpp
src/mame/mame.lst

this has been sitting around for about 7 years, so no idea about the credit.

new clones: Print Club (World)

---

src/mame/drivers/aristmk5.cpp
src/mame/layout/venicea5.lay
src/mame/mame.lst

fixes some sets, adds honeypot and venicea5

aristmk5 updates (from Heihachi_73)

---

hash/sms.xml

Fan made release, which runs in original system and was also released and (limited) distributed as a physical copy. More info: https://youtu.be/6ntwR94J6iM https://goo.gl/9efrGv

Adding Alex Kidd in Miracle World 2

---

scripts/target/mame/mess.lua
src/mame/drivers/att4425.cpp
src/mame/mame.lst
src/mame/mess.flt

Updated after review in https://github.com/mamedev/mame/pull/2522

att4425: new skeleton (AT&T 4425 / Teletype 56D text terminal) (take 2)

---

src/tools/imgtool/imgtool.cpp

Hi,
this PR is for my attempt at fixing the bug in imgtool I mentioned here:
http://forums.bannister.org//ubbthreads.php?ubb=showflat&Number=110649
I'm not a super-expert in imgtool sources, so I'd like very much if N.Woods could give a look and "validate" my fix.
Thanks.
--F.Ulivi

imgtool: a fix for the "GET" command bug

---

src/devices/machine/ins8250.cpp

I see a few problems with the 8250 code that i'm trying to debug. While doing so i added a lot of register defines to make the code easier to understand.

add and use INS8250 register defines

---

language/Italian/strings.po

Hi, I've updated the translation of the Italian language for Mame 0.189.

Mame 0.189 Italian Language 100% translated.

---

src/mame/drivers/hp9k_3xx.cpp

Install a buserror handler for the DIO/DIO-II card ranges. The
300 BOOT ROM expects to get a Buserror signal to detect if there's
a card. Also remove the memory of PC's doing invalid Bus accesses
as this breaks this detection.

HP9000/300: fix detection of DIO cards

---

plugins/boot.lua
plugins/cheat/init.lua
src/frontend/mame/luaengine.cpp

Making a pull request for comment about whether this is wanted and if so how to add to workflow.  Seems to work fine with find with xgettext anyhow.

luaengine: translation support [Carl]

---

language/Dutch/strings.po

Hi. These are all the translations needed for MAME 0.189. Hope this will help.

Dutch language strings fully translated

---

src/devices/machine/intelfsh.cpp
src/devices/machine/intelfsh.h
src/mame/drivers/dbox.cpp

This should be a clean merge as no dependencies from other drivers towards this new device exists. I am also pending on this being merged to rebase and PR the rest of my dbox/68340  work

dbox: added 29F800B flash boot device

---

src/mame/drivers/megaplay.cpp

basically I don't feel it's ever worked properly, and it has only got worse over the years, time to demote it.

demote Megaplay to not working, see notes

---

src/mame/drivers/eolith.cpp
src/mame/includes/eolith.h
src/mame/mame.lst

new WORKING clones : Land Breaker (World) / Miss Tang Ja Ru Gi (Korea) (pcb ver 1.0) (AT89c52 protected) [Hammy]

---

src/devices/machine/68340.cpp
src/devices/machine/68340.h
src/devices/machine/68340ser.cpp
src/devices/machine/68340ser.h
src/devices/machine/mc68681.cpp
src/devices/machine/mc68681.h
src/mame/drivers/dbox.cpp

Tried to address all of Vas comments from my previous [commit](https://github.com/mamedev/mame/pull/2628)

68340: Fixed -validate errors and made slight cleanup

---

src/mame/drivers/hp16500.cpp

hp16500: connect HIL MLC

---

src/mame/drivers/targeth.cpp
src/mame/includes/targeth.h
src/mame/mame.lst
src/mame/video/targeth.cpp

Target Hits (ver 1.1, Checksum 5152) [Peter Wilhelmsen, Morten Shearman Kirkegaard, Clawgrip, Brian Troha, David Haywood]
Target Hits (ver 1.0, Checksum FBCB) ) [Peter Wilhelmsen, Morten Shearman Kirkegaard, Clawgrip, Brian Troha, David Haywood]
note, the board ClawGrip sent has undumped program roms, these will be dumped in the coming days

machines promoted to WORKING (Target Hits)

---

src/mame/drivers/targeth.cpp
src/mame/mame.lst

new clones  Target Hits (ver 1.1, Checksum 86E1) [Peter Wilhelmsen, Morten Shearman Kirkegaard, Clawgrip, Brian Troha, David Haywood]

---

scripts/src/tools.lua
src/tools/imgtool/main.cpp
src/tools/imgtool/modules.cpp
src/tools/imgtool/modules/hp85_tape.cpp

Hi,
this PR adds support for HP85 tape images to imgtool.
Thanks.
--F.Ulivi

Support for HP85 tapes added to imgtool

---

src/devices/machine/upd765.cpp
src/devices/machine/upd765.h

Fixes http://mametesters.org/view.php?id=6689.

upd765: special case i82072 drive busy bit handling (nw)

---

src/devices/video/vooddefs.h
src/emu/validity.cpp
src/emu/video/rgbgen.cpp
src/emu/video/rgbgen.h
src/emu/video/rgbsse.h
src/emu/video/rgbutil.h
src/emu/video/rgbvmx.h

Looking for some general overview and comments before this goes to the mainline code.  I tried to verify some of the Model3 games but they all seem to be currently inoperational.

rgbsse: Optimize some sse routines. (nw)

---

src/devices/cpu/sh/sh2comn.cpp

(we always use timers for SH2 DMA, and have done for years, just forgot to remove the #ifdef on this code when cleaning up)

fix CPS3/STV

---

src/devices/cpu/sh/sh_dasm.cpp

a few dasm fixes that were in the sh4 core but not the sh2 core and got lost when merging them (nw)

a few dasm fixes that were in the sh4 core but not the sh2 core and got lost when merging them (nw)

---

hash/fmtowns_cd.xml

Somehow I deleted a softlist entry while adding the new ones. It's now fixed.

fmtowns_cd.xml: fix accidental deletion

---

scripts/target/mame/mess.lua
src/mame/drivers/gamate.cpp
src/mame/video/gamate.cpp
src/mame/video/gamate.h

this fixes many games, we can probably mark them all as supported.

rewrote the Gamate video implementation from scratch using Kevtris' document and Peter Wilhelmsen's notes

---

scripts/src/video.lua
src/devices/video/bt459.cpp
src/devices/video/bt459.h

Used in InterPro graphics boards.

bt459: new device

---

hash/gamate.xml
scripts/src/bus.lua
scripts/target/mame/mess.lua
src/devices/bus/gamate/gamate_protection.cpp
src/devices/bus/gamate/gamate_protection.h
src/devices/bus/gamate/rom.cpp
src/devices/bus/gamate/rom.h
src/devices/bus/gamate/slot.cpp
src/devices/bus/gamate/slot.h
src/mame/drivers/gamate.cpp

gamate: add some mirroring to memory map, fix AY frequency
gamate.xml: mark all software as supported
(next step, make it use a bus / cartridge device instead of protection and banking being hardcoded in driver)

gamate, further improvements, mark software as working as it appears ok.

---

hash/gamate.xml
hash/pc98_cd.xml

Also correct spelling mistake in pc98_cd.xml

gamate: Unknown publisher to <unknown> (nw)

---

src/mame/drivers/pgm2.cpp
src/mame/mame.lst

new dumps are dirctly from the rom on the rom+fpga module that plugs in the usual rom socket, complete with extra layer of scrambling it provides [XingXing]

dump 2 new kov3 clones, redump existing v102 set.  

---

src/mame/drivers/big10.cpp

In according Success website, Big 10 is success gambing Game and release year is 1985.
https://www.success-corp.co.jp/developments/works

Correct Big 10 Company and year

---

src/devices/video/bt459.cpp
src/devices/video/bt459.h

* added device address map, simplified switch
* comments and formatting

bt459: device address map (nw)

---

language/Portuguese/strings.po

PT_PT translation. Top to bottom.

Portuguese (Portugal) translation

---

src/devices/machine/6522via.cpp
src/mame/drivers/prodigy.cpp
src/mame/layout/prodigy.lay

The chess computer can now be used for playing a game of chess using the keypad and the BCD display

Prodigy clickable layout

---

src/devices/bus/interpro/sr/sr.cpp
src/mame/drivers/interpro.cpp

* fix the slot initialisation
* make single screen graphics the default

interpro: minor fixes (nw)

---

language/Portuguese/strings.po

Portuguese (PT-PT) translation fixes

---

hash/fmtowns_cd.xml

Added:
- AnotherTOWNS - Anata~ Free Software Collection
- Dragon Shock
- NHK Jissen Eikaiwa
- Okumanchouja II
- Oshare Cooking II
- Tom Snyder's Puppy Love 2
- Suikoden - Tenmei no Chikai (incomplete dump)
- Toushin Toshi II

fmtowns_cd.xml: several additions, minor fixes

---

android-project/README.md
benchmarks/README.md
bgfx/README.md
bgfx/chains/README.md
bgfx/effects/README.md
bgfx/effects/default/README.md
bgfx/effects/hlsl/README.md
bgfx/effects/unfiltered/README.md
docs/man/README.md
hash/README.md
keymaps/README.md
regtests/README.md
src/devices/bus/vme/vme_fccpu20.cpp
src/devices/bus/vme/vme_hcpu30.cpp
src/devices/machine/68561mpcc.cpp
src/emu/layout/README.md
src/mame/drivers/fccpu30.cpp
src/mame/drivers/galaxian.cpp
src/mame/drivers/hk68v10.cpp
src/mame/drivers/mvme147.cpp
src/mame/drivers/stuntair.cpp
tests/README.md
web/README.md

This is the result of me testing out a WIP source code spell-checker
and your project was the random target this time.
(the 3rdparty folder has been ignored)

fix some typos

---

src/devices/bus/hp80_io/82937.cpp
src/devices/bus/hp80_io/82937.h
src/devices/machine/1mb5.cpp
src/mame/drivers/hp80.cpp

Hi,
this PR adds the emulation of HP85 internal printer.
It also tries to address some of the remarks in PR #2749 by V.Crabb.
Thank you.
--F.Ulivi

HP85: Internal printer added

---

src/mame/drivers/pgm2.cpp
src/mame/mame.lst

(initial cleanup of previous PR)

preliminary PGM2 emulation, most video features emulated, Oriental Legend 2 mostly OK, see notes.

---

src/mame/drivers/neogeocd.cpp

Also change "NeoGeo" in the BIOS descriptions to "Neo-Geo" as per the machine description.

Add Neo-Geo CD Universe BIOS v3.2 (nw)

---

src/devices/video/bt459.cpp
src/devices/video/bt459.h

* support for blinking (pixel planes and cursors)
* fixes for dual-cursor and X Window mode
* corrected screen output alignment

bt459: various improvements

---

src/mame/drivers/pgm2.cpp

(need to work out the correct logic for flipped cases, searching for evidence)

pgm2 - add sprite xgrow/xshrink for basic non-flipped cases

---

src/devices/machine/z80scc.cpp
src/devices/machine/z80scc.h

In preparation for synchronous modes and general shape up of the code, will do some more pushing over the next few days or until @cuavas rampage begins :)

z80scc: general cleanup and backport of z80sio improvements

---

src/devices/machine/z80scc.cpp

z80scc: general cleanup part III

---

src/mame/drivers/cps3.cpp

Street Fighter III: New Generation, Street Fighter III 2nd Impact: Giant Attack, Street Fighter III 3rd Strike: Fight for the Future and Warzard / Red Earth Requires to use for 6 buttons.

Correct CPS3 Multi-game Control [sjy96525]

---

hash/fmtowns_cd.xml

- Ishin no Arashi [Reuental]
- Sangokushi II [Reuental]
- Zan III - Ten'un Ware ni Ari [Reuental]
Also, fixed a couple of small mistakes in the missing list.

fmtowns_cd.xml: 3 new additions

---

language/Dutch/strings.po

Good afternoon from The Netherlands!
Added all the new strings, fixed some grammar and spelling mistakes. Should be all complete again.

Update Dutch translations

---

src/devices/bus/interpro/sr/sr.cpp
src/devices/bus/interpro/sr/sr.h
src/devices/cpu/clipper/clipper.cpp
src/devices/cpu/clipper/clipper.h
src/devices/cpu/clipper/clipperd.h
src/mame/drivers/interpro.cpp
src/mame/includes/interpro.h
src/mame/machine/cammu.cpp
src/mame/machine/cammu.h
src/mame/machine/interpro_ioga.cpp
src/mame/machine/interpro_ioga.h

* implemented most clipper cpu and mmu exceptions
* completed c300 instructions, adjusted for c400
* improved cammu dynamic translation and added faults
* refactored c300 cammu into separate instruction/data instances
* configurable ioga and sr bus memory access

interpro: cpu and mmu improvements

---

language/French/strings.po

Update MAME French translation

Update MAME French translation

---

language/Portuguese_Brazil/strings.po

Minor fixes and typos.
Added @felipesanches requests
Shorted some strings as @felipesanches requests, not all "IU" was changed because it breaks the interface or is too long.
We will have to deal with the "parent" and "clone" thing later, maybe the use of RAMIFICAÇÃO (RAMIFICATION OF) that will better reflect with our Language.

Update for Brazilian Portuguese

---

src/emu/debug/debughlp.cpp

also fix a typo in the stateload description

explain the rewind command in debughlp

---

hash/psx.xml

Fire Pro Wrestling G v1.1 [fireprog]
Gradius Gaiden v1.1 [gradiusg]
Gunners Heaven [gunnersh]
Hokuto no Ken - Seikimatsu Kyuuseishu Densetsu [hokutosk]
Jikkyou Oshaberi Parodius - Forever with Me [jikkparo]
Macross Digital Mission VF-X [macrovfx]
Macross VF-X2 ]macrvfx2]
Super Robot Taisen Alpha [srobota]
Super Robot Taisen Alpha Gaiden - Premium Edition [srobotagp]
Super Robot Taisen Alpha Gaiden - Shokai Genteiban [srobotags]
Super Robot Taisen Complete Box [srobotcb]
Super Robot Taisen F [srobotf]
Super Robot Taisen F Kanketsuhen [srobotfk]
Zanac X Zanac [zanacx]

Added 14 entries to psx softlist

---

hash/neogeo.xml
src/mame/drivers/neogeo.cpp
src/mame/mame.lst

Blue's Journey / Raguy (ALH-001) [Razoola]

new working clones

---

src/mame/drivers/alphatpx.cpp
src/mame/mame.lst

split concatenated ROMs in preparation for proper ROM naming and fix ROM copypaste errors, update comments.

alphatpx: Add sound, add Alphatronic P2U and move its ROMs there, 

---

src/emu/debug/debugcmd.cpp
src/emu/debug/debugcmd.h
src/emu/debug/debughlp.cpp
src/emu/debug/debughlp.h

Revert "Command to print all debugger help to html file"

---

src/devices/video/pc_vga.cpp
src/devices/video/pc_vga.h

pc_vga.cpp: CRTC start address is supposed to be shifted left by 2, from 86Box [Melissa Goad]

---

src/devices/machine/nscsi_bus.cpp
src/devices/machine/nscsi_hd.cpp
src/devices/machine/nscsi_hd.h

Also, logmacro.h logging in nscsi_hd and nscsi_bus.

nscsi_hd: use chd idnt metadata for inquiry (nw)

---

src/mame/drivers/igs_m036.cpp
src/mame/drivers/pgm2.cpp
src/mame/includes/pgm2.h
src/mame/machine/igs036crypt.cpp
src/mame/machine/igs036crypt.h

allow ddpdojh to actually run code from ram rather than treating ram as rom (even if the game doesn't actually care)

allow ddpdojh to actually run code from ram rather than treating ram as rom (even if the game doesn't actually care)

---

hash/cd32.xml

- Arabian Nights [arabian]
- Base Jumpers [basejump]
- Beavers [beavers]
- Benefactor [benefact]
- Black Viper [blkviper]
- Battletoads [btoads]
- Bubba 'N' Stix [bubba]
- Bubble & Squeak [bubblesq]
- Bump 'N Burn [bumpburn]
- Chuck Rock [chuckrck]
- Chuck Rock II - Son of Chuck [chukrck2]
- Darkseed [darkseed]
- Deep Core [deepcore]
- D-Generation [dgen]
- Donk! The Samurai Duck! [donk]
- Dragonstone [dstone]
- Dangerous Streets [dstreets]
- Emerald Mines [emerald]
- Fireforce [fireforc]
- Flink [flink]
- Fly Harder [flyhard]
- Frontier - Elite II [frontier]
- Global Effect [global]
- Gloom [gloom]
- Guardian [guardian]
- International Karate + [ikplus]
- Kid Chaos [kidchaos]
- Marvin's Marvellous Adventure [marvin]
- Myth - History in the Making [myth]
- Naughty Ones [naughty]
- …

Added 34 entries to cd32

---

src/mame/video/fmtowns.cpp

- Refactored the line drawing code to make it less repetitive and more flexible.
- Added support for all 16 horizontal zoom levels supported by the hardware instead of just 5. As far as I know this is only used in some Data West games (Misty, Rayxanber)
- Simplified the line wrap detection code and support all use cases (including vertical scrolling and layer 1 with sprites).

fmtowns: refactor line drawing, support zoom up to x16, better wrapping

---

src/mame/video/ygv608.cpp
src/mame/video/ygv608.h

In Namco Classic Collection vol.1, mosaic effect is used in Galaga Arrangement Ending/Staffroll scene. This patch adds emulation of the effect.

ygv608: Add mosaic effect for Galaga Arrangement Ending/Staffroll

---

src/devices/cpu/arm7/arm7.cpp
src/devices/cpu/arm7/arm7.h
src/mame/drivers/pgm2.cpp
src/mame/includes/pgm2.h

also tag driver as supporting states.

pgm2 / arm9 : ensure savestates work from commandline (eg launching with -state 0)

---

README.md
android-project/LICENSE
benchmarks/LICENSE
docs/source/conf.py
docs/source/license.rst
docs/source/whatis.rst
src/lib/netlist/prg/nltool.cpp
src/lib/netlist/prg/nlwav.cpp
src/osd/modules/render/bgfx/shaders/shader.mk
tests/LICENSE
uismall.bdf
web/LICENSE

Updates "2017" copyright string to "2018" where relevant, based on pull request #2017.

Updates "2017" strings to "2018" where relevant.

---

src/mame/drivers/blackt96.cpp

and yes, I think it is meant to sound this awful, playing the coin sound repeatedly when you'd expect a typewriter sound..

hook up sound in black touch '96 [David Haywood]

---

src/mame/drivers/alphatpx.cpp

This allows the P2 series machines to continue to their MOS monitor and boot disks.

alphatpx: Add HSYNC callback

---

scripts/target/mame/mess.lua
src/mame/drivers/radicasi.cpp
src/mame/mame.lst

(not sure what this is really called, it's a 5-in-1, it has Space Invaders printed on it, the title screen says Arcade Legends, it was made by Radica)

new NOT WORKING  Space Invaders (Radica, Arcade Legends TV Game) [Team Europe, Sean Riddle]

---

makefile
scripts/genie.lua

I didn't test it with "thread" yet, that's why there's still a part of the commented code left.

restored SANITIZE make option

---

src/mame/machine/atarifdc.cpp

This was the ugly copied code I was referring to in the previous pull request.
Sorry about that - when I prepared the branch I messed something up and had to set it up again and obviously forgot a commit.

atarifdc.cpp: fixed drive lookup (nw)

---

src/mame/drivers/snowbros.cpp
src/mame/mame.lst

Cookie & Bibi 2 (set 2) [Hammy]
note, protection data needs verifying for this, I had to hack the parent data because there are absolute jumps to rom addresses in the code provided by the MCU just to make sure it doesn't crash when inserting a coin, it's possible some ram addresses differ too, hence need for verification.

new clones   Cookie & Bibi 2 (set 2) [Hammy]

---

docs/source/debugger/expressions.rst

Per request, added some info on other memory operators. Also cleaned up the text formatting a bit further on expressions.

Add additional memory operators per request (NW)

---

src/mame/drivers/radicasi.cpp

lack of test cases / makes these tricky to figure out properly
hopefully more games using this hardware will surface to supply more evidence.

Radica 6502: some hacks to improve the video, 

---

hash/stepone_flop.xml
src/mame/drivers/myb3k.cpp

fixed softlist validation error and added three floppies to the softlist with small games of various origins

Mybrain 3000: More stepone floppies and corrected Mode 0 graphics

---

src/mame/drivers/radicasi.cpp

the ADPCM format needs to be figured out.
OKI ADPCM sounds better than this (ie it doesn't destroy your ears) but is clearly NOT correct either.

radica6502: preliminary sound

---

hash/neogeo.xml
src/mame/drivers/neogeo.cpp
src/mame/mame.lst

I wonder if this is some kind of hack, although if it is the changes to the code appear rather extensive

new clones : Samurai Shodown V / Samurai Spirits Zero (NGM-2700, set 2) [Sugoi Helsinki]

---

src/mame/includes/kickgoal.h

(the online resolver didn't resolve this in the correct order or prompt me about it)

fix compile 

---

src/mame/drivers/multfish.cpp
src/mame/drivers/multfish_boot.cpp

should stop some false reports of them being 'broken'

added pre-initialized factory defaults to all multfish.cpp sets so they boot by default (nw)

---

src/mame/drivers/drgnmst.cpp
src/mame/includes/drgnmst.h
src/mame/video/drgnmst.cpp

on Dragon Master, Palette has 12-bit RGB with Highest 4-bit for brightness, it seems like CPS1 palette format.
so I implemented this for palette fading fix.

Implemented Dragon Master palette brightness value

---

src/mame/drivers/gaelco2.cpp

I went through all the pictures I have on my site for gaelco2.cpp games and updated documentation accordingly.

update documentation based on real pictures

---

scripts/target/mame/mess.lua
src/mame/drivers/olyboss.cpp
src/mame/mame.lst
src/mame/mess.flt

Z80 model with one floppy drive and one 5 MB harddisk.
In the current state, the screen shows garbage although the correct video chip is hooked up.

olyboss.cpp: new not working: Olympia BOSS D [friol]

---

docs/source/debugger/general.rst

Kind of embarrassing, but fixed.

Missed a couple escape sequences. (nw)

---

src/mame/drivers/xavix.cpp
src/mame/mame.lst

XaviX Tennis (XaviXPORT) [Sean Riddle, Peter Wilhelmsen]

new machines marked as NOT WORKING

---

src/mame/drivers/xavix.cpp
src/mame/mame.lst

The code on this one is much closer to Taito Nostalgia, seemingly only using the callfar / returnfar extended opcodes, this further makes me think that XaviX Tennis is a Super XaviX title instead.

new machines marked as NOT WORKING - Play TV Ping Pong [Sean Riddle]

---

src/mame/drivers/megaphx.cpp
src/mame/machine/inder_vid.cpp
src/mame/machine/inder_vid.h
src/mame/mame.lst

new machines marked as NOT WORKING
Hammer Boy [alt/deepfb, Dan Dare, mad3001, Habi, Adonías, cpcmaniaco, Robcfg, Pablo Ruiz, Recreativas.org, The Dumping Union]
can't coin up / dips seem to have no effect, might be unhappy with the PIC response from the Megaphoenix Pic, might be possible to kludge it if that is the case.

new machines marked as NOT WORKING - Hammer Boy [..]

---

src/devices/bus/coco/coco_multi.cpp

Here is my attempt at adding support for the Color Computer's Multi-Pak Interface's slot switch.

Added support fro the MultiPak slot switch as a dip switch.

---

src/mame/drivers/xavix.cpp

started making a bit more sense of this weird 'packet' format before the gfxdata, the outline of the track is correct now, but many of the hazards are still using incorrect flipping (maybe it can rotate tiles too)

xavix - various cleanups / refactoring and monster truck improvements

---

src/devices/sound/x1_010.cpp
src/devices/sound/x1_010.h
src/mame/drivers/seta.cpp
src/mame/includes/seta.h

seta.cpp : Configurated M6502 Bankswitching

x1_010 : Change m_adr value name to m_xor Because it's actually Address Bit XOR value.

---

src/mame/drivers/gaiden.cpp
src/mame/includes/gaiden.h
src/mame/video/gaiden.cpp

gaiden : Fix raiga hang at soft reset, Cleanup duplicates, Split wildfang/raiga machine config and address map

gaiden : Cleanups, Fixes

---

src/mame/drivers/olyboss.cpp
src/mame/mame.lst

The available single sided Prologue boot disk boots.

olyboss.cpp: added Boss A 8085 model

---

src/devices/bus/coco/coco_dcmodem.cpp
src/devices/bus/coco/coco_rs232.cpp

I'm not happy with the ROMs using the EEPROM interface. I would like suggestions on better ways to handle this.

Attached ports to the two Color Computer serial cards.

---

src/mame/drivers/xavix.cpp
src/mame/mame.lst

Play TV Bass Fishin' [Sean Riddle, Peter Wilhelmsen]
also some debug code to help figure out how video banking / segmentation works in the mode used by boxing in places, and this in places and some PAL machine clones of what we have because they're useful for figuring out register use.

xavix - new machines marked as NOT WORKING

---

scripts/src/cpu.lua
scripts/target/mame/mess.lua
src/devices/cpu/diablo/diablo1300.cpp
src/devices/cpu/diablo/diablo1300.h
src/devices/cpu/diablo/diablo1300dasm.cpp
src/devices/cpu/diablo/diablo1300dasm.h
src/emu/xtal.cpp
src/mame/drivers/diablo1300.cpp
src/mame/mame.lst
src/mame/mess.flt

to keep up with those apocalypses. Driver is just for testing the CPU atm.

WIP: Diablo printer CPU

---

src/mame/drivers/mcatadv.cpp
src/mame/includes/mcatadv.h
src/mame/video/mcatadv.cpp

mcatadv.cpp : Cleanup duplicates, Replace gfx* -> saner rom areas, Allocate sound output verified from real PCB

 mcatadv.cpp : Updates

---

src/devices/sound/qs1000.cpp
src/devices/sound/qs1000.h
src/mame/drivers/eolith.cpp
src/mame/drivers/eolith16.cpp
src/mame/drivers/ghosteo.cpp
src/mame/drivers/limenko.cpp
src/mame/drivers/vamphalf.cpp
src/mame/drivers/vegaeo.cpp
src/mame/includes/eolith.h

eolith.cpp, ghosteo.cpp, limenko.cpp, vamphalf.cpp, vegaeo.cpp : Modernize soundlatches
eolith.cpp, eolith16.cpp, ghosteo.cpp, limenko.cpp, vamphalf.cpp, vegaeo.cpp : Replace user* -> saner ROM areas

qs1000.cpp : Convert set_irq, serial_in into WRITE_LINE_MEMBER

---

src/devices/bus/ieee488/hp9895.cpp
src/devices/bus/ieee488/ieee488.cpp
src/devices/bus/ieee488/ieee488.h
src/devices/machine/phi.cpp
src/devices/machine/phi.h
src/mame/drivers/hp64k.cpp

Hi,
this PR adds the support of HPIB bus to HP64000 emulation. It also substantially improves the PHI device so that the BIST in 64000 passes.
Thanks.
--F.Ulivi

HP64K: added support for HPIB

---

src/mame/drivers/mastboy.cpp
src/mame/drivers/xavix.cpp
src/mame/mame.lst

Play TV Rescue Heroes [Sean Riddle, Peter Wilhelmsen]
eKara base unit [Sean Riddle, Peter Wilhelmsen]
new clones marked as WORKING
Master Boy (Spanish, PCB Rev A) [ARPA, Recreativas.org]

XaviX - new machines marked as NOT WORKING 

---

hash/megadriv.xml

Added LEGO Batman (Rus), a game published by KDS.

megadriv software list - added additional game

---

src/mame/drivers/gunpey.cpp

extracted decompressed sprite data from Gunpey [Peter Wilhelmsen, Morten Shearman Kirkegaard]
- hooked these up for now while we study the compression scheme, fixing graphics [David Haywood]
Gunpey (Japan) [Peter Wilhelmsen, Morten Shearman Kirkegaard, David Haywood]
some other gfx features (zooming for example) still need emulating.

extracted decompressed sprite data from Gunpey [Peter Wilhelmsen, Morten Shearman Kirkegaard]

---

makefile
scripts/extlib.lua
scripts/genie.lua
scripts/src/emu.lua
src/emu/hashfile.cpp

These changes allow building using system pugixml. I am not sure if scripts/genie.lua is the best place for the code I added there, please may you advise? Thanks!

Added possibility of building using system pugixml

---

language/Dutch/strings.po

Added the missing sentence to make the translation 100% again.

Update Dutch strings

---

src/mame/drivers/taito_f2.cpp
src/mame/includes/taito_f2.h

(hook it up, for some definition of hook up, since it basically does nothing at all the game cares about)

use real C-chip ROM for MegaBlast [Team Caps0ff]

---

src/devices/cpu/clipper/clipper.cpp
src/devices/cpu/clipper/clipper.h

* save all state
* improve multiply instructions, add condition codes
* fix register pair load/store
* clean up pc handling
* switch to C++ cast syntax, other minor formatting

clipper: minor improvements (nw)

---

src/mame/drivers/firefox.cpp

firefox.cpp : Cleanups, Add output finders/object finders, Reduce runtime tag lookups

firefox.cpp Cleanups

---

src/emu/debug/debugcmd.cpp
src/emu/debug/debugcmd.h
src/emu/debug/debugcpu.cpp
src/emu/debug/debugcpu.h
src/emu/debug/debughlp.cpp

Useful commands for investigations which require interfering devices to be suspended

Added suspend and resume debugger commands

---

src/mame/drivers/atarisy2.cpp
src/mame/mame.lst

Paperboy (prototype) [Andrew Welburn]
had this sat here unsubmitted for years, looks like a different revision, maybe somebody else can make something more of it, possible the video system is not really system2 as the video boards were missing

new clones marked as NOT WORKING

---

scripts/target/mame/arcade.lua
src/mame/drivers/mastboy.cpp
src/mame/drivers/mastboyo.cpp
src/mame/mame.lst

Master Boy (1987, Z80 hardware) [David Haywood, ARPA, Recreativas.org, The Dumping Union]

new WORKING machines

---

src/devices/sound/aica.cpp
src/devices/sound/aica.h
src/devices/sound/aicadsp.cpp
src/mame/drivers/dccons.cpp
src/mame/drivers/hikaru.cpp
src/mame/drivers/naomi.cpp
src/mame/drivers/segasp.cpp
src/mame/includes/dc.h
src/mame/includes/dccons.h
src/mame/includes/naomi.h
src/mame/includes/segasp.h
src/mame/machine/dc.cpp

Revert " AICA Cleanups & Internalize CPU Core"

---

src/mame/drivers/coolpool.cpp
src/mame/includes/coolpool.h

coolpool.cpp : Add generic_latch_16_device for cpu-dsp communications, Split coolpool DSP io map and nballsht DSP io map, Fix ROM tags

coolpool.cpp Updates

---

src/mame/drivers/atarisy2.cpp
src/mame/includes/atarisy2.h
src/mame/video/atarisy2.cpp

atarisy2.cpp : Minor cleanups for bankswitching, Add address_map_bank_device for vram bankswitch handlers

atarisy2.cpp Cleanups

---

hash/nes.xml
src/mame/drivers/bladestl.cpp

- made super mary a clone of smw in nes.xml

- mark blades of steel sets as joystick / trackball to reduce confusion

---

src/devices/video/tlc34076.cpp
src/devices/video/tlc34076.h

tlc34076.cpp : Convert m_pens, m_local_paletteram into std::unique_ptr, Minor cleanup

tlc34076.cpp Cleanups

---

src/mame/drivers/gundealr.cpp
src/mame/includes/gundealr.h
src/mame/video/gundealr.cpp

gundealr.cpp : Cleanup duplicates, Reduce runtime tag lookups, Fix some tags, etc...

gundealr.cpp : Cleanups

---

src/devices/bus/interpro/sr/sr.h
src/devices/cpu/clipper/clipper.cpp
src/devices/cpu/clipper/clipper.h
src/mame/drivers/interpro.cpp
src/mame/machine/cammu.cpp
src/mame/machine/cammu.h

* debugger address translation
* documentation edits

interpro: minor changes (nw)

---

hash/neogeo.xml
src/mame/drivers/neogeo.cpp
src/mame/mame.lst

Sengoku 3 / Sengoku Densho 2001 (set 2) [Razoola]
World Heroes 2 (ALH-006) [Razoola]
V-Liner (v0.7a) [Razoola]
also added 2 new MVS bios dumps, and provided some extra version infomation hints [Razoola]

new WORKING clones (neogeo) [Razoola]

---

src/mame/drivers/rad_eu3a14.cpp

rad_eu3a14 - improve rendering for rad_foot by making more correct use of sprite registers / bits

---

src/devices/sound/aica.cpp
src/devices/sound/aica.h

aica.cpp : Correct register name from development manual, Add docs of unimplemented registers; Add imperfect_features because Emulation isn't perfect (DSP, etc..)

aica.cpp Document updates

---

hash/apple2_cass.xml

Adding quite a few tapes. Links to files in 3 parts:
[https://www.sendspace.com/file/webmcl](url)
[https://www.sendspace.com/file/4gr0ha](url)
[https://www.sendspace.com/file/k2fzy6](url)

apple2_cass softlist additions

---

language/Korean/strings.po

Spent last week getting this done. Let me know if I messed up something.

Adds KO language string.po

---

src/mame/drivers/gunpey.cpp

gunpey.cpp : Minor cleanups, Fix object finder, Convert VRAM into std::unique_ptr, Fix bit manipulations

gunpey.cpp Cleanups

---

src/mame/drivers/fmtowns.cpp

fmtowns.cpp : Accurate sound outputs from real hardware (real one has seperated left/right audio out (supports stereo))

fmtowns.cpp : Accurate sound outputs

---

src/mame/video/rohga.cpp

rohga.cpp : Fix background color of title screen in wolffang

rohga.cpp Update

---

src/mame/drivers/hp9k_3xx.cpp

hp9k_3xx: add internal TMS9914 GPIB

---

src/devices/machine/tms9914.cpp
src/devices/machine/tms9914.h

Hi,
this PR is for a set of small improvements to TMS9914 emulation.
It now passes POST of HP9000/340 & 332.
Thanks.
--F.Ulivi

tms9914: added RL state machine

---

src/devices/machine/tms9914.cpp
src/devices/machine/tms9914.h

Hi,
this commit fixes the handling of GTS aux command in TMS9914.
Thanks.
--F.Ulivi

tms9914: fixed handling of GTS aux command.

---

src/mame/drivers/argus.cpp
src/mame/includes/argus.h
src/mame/video/argus.cpp

argus.cpp : Fix argus sound writes(second ym2203 has not implemented), Cleanup duplicates, Runtime tag lookups

argus.cpp Updates

---

src/mame/drivers/nmk16.cpp

Add romanization of firehawk* chinese title screen, Simpler gfx layouts, Fix spacing

nmk16.cpp : Add notes

---

src/mame/drivers/funkyjet.cpp

reference:http://www5f.biglobe.ne.jp/~zekzek/utt_interview.html (Japanese), it's says developed by mitchell

funkyjet.cpp : Fix company tag for funkyjet*

---

src/devices/bus/interpro/keyboard/hle.cpp
src/devices/bus/interpro/keyboard/lle.cpp
src/devices/bus/interpro/keyboard/lle.h

Also delete non-functional LED handling in hle; no point output-findering it because it doesn't work and the LLE implementation will likely supercede it soon anyway.

interpro: lle keyboard wip checkpoint (nw)

---

src/mame/drivers/vamphalf.cpp
src/mame/mame.lst

World Adventure [ArcadeHacker, The Dumping Union]
(and first pass dedeprecation / splitting class up)

new WORKING machine

---

src/mame/drivers/nmk16.cpp
src/mame/includes/nmk16.h
src/mame/mame.lst

Tom Tom Magic [Jeffrey Gray, ranger_lennier, Evan Korzon, Dane Biegert, MrGoodwraith, Charles MacDonald, Brian Troha, The Dumping Union]
(it's cloned nmk16.cpp hardware, with some changes)

new machines marked as NOT WORKING (Tom Tom Magic)

---

src/mame/drivers/nmk16.cpp

the Joystick at least is needed for high score name entry.
played a bit, seems fine so...
Tom Tom Magic [AJRhacker, David Haywood]

gave Tom Tom Magic a joystick and 3 buttons, as shown in attract mode

---

src/mame/drivers/vis.cpp

vis.cpp : Fix sample rate divider

---

src/mame/drivers/cybertnk.cpp

cybertnk.cpp : Cleanup duplicates, Reduce runtime tag lookups, Fix sound output(related to OST), Add notes

cybertnk.cpp Updates

---

src/mame/drivers/cedar_magnet.cpp

War Mission (WM 4/6/87)  [Jordi Beltran Casany, Recreativas.org, ArcadeHacker, David Haywood]

machines promoted to WORKING

---

src/mame/includes/dccons.h
src/mame/machine/dccons.cpp

With this commit, Daytona USA 2001 boots.

Dreamcast: GD_LEND should output number of bytes successfully DMA'd

---

src/mame/drivers/m92.cpp
src/mame/includes/m92.h
src/mame/video/m92.cpp

Cleanup duplicates, Reduce runtime tag lookups, Make EEPROM Save/loadable, Fix spacing, Split machine configs/address maps related to main CPU ROM, Add notes

m92.cpp : Updates/Cleanups

---

src/devices/sound/tms5220.cpp
src/devices/sound/tms5220.h

PR as requested, with changes (roughly) split.

TMS5220 changes, bugfixes and updates

---

src/mame/drivers/wmg.cpp

wmg.cpp : Cleanups, Add address_map_bank_device for IO Bankswitching, Add machine_start/reset instead MCFG_MACHINE_START/RESET, Add save state, Fix naming, Fix crash

Make wmg.cpp Working again, nw

---

src/devices/bus/hp_dio/hp98543.cpp
src/devices/bus/hp_dio/hp98543.h
src/devices/bus/hp_dio/hp98544.cpp
src/devices/bus/hp_dio/hp98544.h
src/devices/video/nereid.cpp
src/devices/video/topcat.cpp
src/devices/video/topcat.h

These patches improve the window mover, and fix some cursor handling bugs. With that patches Pascal and other software actually show somethings after boot on hp9k_3xx.

Topcat improvements

---

src/mame/machine/pgmprot_igs027a_type2.cpp

USA distributor is Andamiro USA.

pgmprot_igs027a_type2.cpp : Fix martmast metadata

---

src/mame/drivers/alpha68k.cpp
src/mame/includes/alpha68k.h
src/mame/video/alpha68k.cpp

ROM Region Defragmentation, Reduce runtime tag lookups, Reduce unnecessary values, Fix crash

alpha68k.cpp : Updates/Cleanups

---

src/mame/drivers/shangha3.cpp
src/mame/includes/shangha3.h
src/mame/video/shangha3.cpp

Minor cleanups, ACCESSING_BITS cleanups, Fix spacing, Reduce unused, Cleanup blocken okibank
Demote Shanghai III with MACHINE_IMPERFECT_GRAPHICS related to MT #01002

shangha3.cpp : Cleanups

---

src/mame/drivers/snk.cpp
src/mame/includes/snk.h

snk.cpp : Cleanup unused, Reduce runtime tag lookup, Split countryc machine config & address map

snk.cpp : Cleanups

---

src/mame/drivers/lastduel.cpp
src/mame/includes/lastduel.h
src/mame/video/lastduel.cpp

Cleanup duplicates, PALETTE_DECODER for palette, Reduce runtime tag lookups

lastduel.cpp : Minor cleanups, Fix naming

---

hash/ibm5170.xml

There is a minor typo in the ibm5170 softlist. Nothing fancy but it does bother my front-end :p

fixed a typo in the ibm5170 softlist

---

hash/st_flop.xml

I'm separating out all hardware from [#3324](https://github.com/mamedev/mame/pull/3324) so as to make it easier for it to progress.
Archived Kryoflux images:
https://archive.org/details/STELanguageDiskSwedishAtariST.7z

Add new ST floppy dump

---

src/devices/cpu/clipper/clipper.cpp
src/devices/cpu/clipper/clipperd.cpp

This fix enables Insignia SoftPC to run (yes, an emulation within an emulation).

clipper: minor bugfix (nw)

---

src/devices/sound/iremga20.cpp
src/devices/sound/iremga20.h
src/mame/drivers/m107.cpp
src/mame/drivers/m92.cpp
src/mame/drivers/vgmplay.cpp
src/mame/layout/vgmplay.lay

iremga20.cpp : Minor cleanups, Remove MCFGs

vgmplay.cpp : Add GA20 Support

---

src/mame/drivers/1942.cpp

Some code refactoring based on commit c8e2d9504eeebd7b8489d5555f7896ca41ebc5ea made by @MooglyGuy.

1942: Some macro cleanup. (nw)

---

src/mame/drivers/galpani3.cpp
src/mame/drivers/jchan.cpp
src/mame/video/sknsspr.cpp
src/mame/video/suprnova.cpp

suprnova.cpp : Make bitmap draw related to cliprect, Minor cleanup

sknsspr.cpp : Add bitmap clearing disable bit

---

src/mame/drivers/galpani3.cpp
src/mame/video/kaneko_grap2.cpp
src/mame/video/kaneko_grap2.h

galpani3.cpp : Implement/Fix some effects(Background color fading in intro, Girl display in stage start), Add notes
kaneko_grap2.cpp : Add device_palette_interface for palette, Minor cleanups

galpani3.cpp Updates

---

src/devices/sound/x1_010.cpp
src/devices/sound/x1_010.h
src/mame/drivers/seta.cpp
src/mame/drivers/seta2.cpp
src/mame/drivers/vgmplay.cpp
src/mame/includes/seta.h
src/mame/includes/seta2.h
src/mame/layout/vgmplay.lay
src/mame/video/seta.cpp

seta.cpp, seta2.cpp : memory_banks for X1-010 Bankswitching

vgmplay.cpp : Add X1-010 Support

---

src/devices/sound/aica.cpp
src/devices/sound/aica.h
src/mame/drivers/dccons.cpp
src/mame/drivers/hikaru.cpp
src/mame/drivers/naomi.cpp

dccons.cpp, hikaru.cpp : Fix output
dccons.cpp, naomi.cpp, hikaru.cpp : Add XTAL connected with AICA
hikaru.cpp : Correct number of AICAs(1 at motherboard, 1 at AICA PCB)

aica.cpp : Add input clock related to sample rate, Implement MONO/MVOL

---

src/devices/cpu/tlcs870/tlcs870.cpp
src/devices/cpu/tlcs870/tlcs870.h
src/devices/cpu/tlcs870/tlcs870_ops.cpp
src/devices/cpu/tlcs870/tlcs870_ops_dst.cpp
src/devices/cpu/tlcs870/tlcs870_ops_reg.cpp
src/devices/cpu/tlcs870/tlcs870_ops_src.cpp
src/mame/drivers/hng64.cpp
src/mame/includes/hng64.h

- fix indirect bit opcodes (x).p etc.
- add correct cycle counts for all document opcodes
- improve incorrect comments, improve documentation value of comments, document unlisted cases etc.
- various other minor cleanups
(next pass, flag verification)

tlcs870 updates

---

src/devices/sound/262intf.cpp
src/devices/sound/262intf.h
src/devices/sound/ymf262.cpp
src/devices/sound/ymf262.h
src/devices/sound/ymf278b.cpp
src/devices/sound/ymf278b.h

ymz278b.cpp : Add device_post_load for FM part, Add device_clock_changed

ymf262.cpp : Add device_clock_changed

---

src/mame/drivers/cedar_magnet.cpp
src/mame/mame.lst

The Burning Cavern (31/03/87) [Miguel Bragado, Recreativas.org, ArcadeHacker, David Haywood]
A Day In Space (31/03/87) [Miguel Bragado, Recreativas.org, ArcadeHacker, David Haywood]
new clones marked as WORKING
War Mission (WM 09/04/87)  [Miguel Bragado, Recreativas.org, ArcadeHacker, David Haywood]
there was also a disk for Paris Dakar, but the first tracks are damaged beyond repair, and it doesn't work, so haven't added it.

new machines marked as WORKING

---

src/devices/cpu/tlcs870/tlcs870.cpp
src/devices/cpu/tlcs870/tlcs870.h
src/devices/cpu/tlcs870/tlcs870_ops.cpp
src/devices/cpu/tlcs870/tlcs870_ops_helper.cpp
src/devices/cpu/tlcs870/tlcs870_ops_reg.cpp
src/devices/cpu/tlcs870/tlcs870_ops_src.cpp
src/mame/drivers/hng64.cpp
src/mame/includes/hng64.h

still trying to work out exactly how I want this code to be formed, but this keeps pushing the program execution forward at least

tlcs870 - takes first interrupt (nw)

---

src/devices/cpu/tlcs870/tlcs870.cpp
src/devices/cpu/tlcs870/tlcs870.h
src/mame/drivers/hng64.cpp
src/mame/includes/hng64.h

I'll probably tear out the simulation at some point soon so that we're trying to hook this up live, IMHO it's not far off being able to do something useful, just need to find the various triggers and make things like the timer timing realistic.  Don't think the serial stuff is going to matter for the basic hookup.  None of the games are marked as working yet anyway, so hopefully won't be a problem.

current hng64 / tlcs870 notes, tweaks etc.

---

src/mame/drivers/policetr.cpp
src/mame/includes/policetr.h
src/mame/video/policetr.cpp

Convert bitmap_ind8 for dstbitmap, Cleanup pointer/runtime tag lookups/ACCESSING_BITs/naming, Add save states

policetr.cpp : Cleanups

---

src/devices/video/hp1ll3.cpp
src/devices/video/hp1ll3.h
src/mame/drivers/hp_ipc.cpp

Hi,
this PR is for a set of substantial enhancements to HP 1LL3 GPU (the one in the integral PC). I built upon the excellent work by shattered.
It's not over yet, but it's usable. In my opinion various graphical programs are now rendered much better (see the so-called POS demo or GraphicArt, for example).
More to come, stay tuned.
Thanks.
--F.Ulivi

Improvements to HP-1LL3 GPU

---

src/devices/sound/disc_dev.hxx
src/devices/sound/disc_sys.hxx

Fixed DISC_555_TRIGGER_DISCHARGES_CAP option in DISCRETE_555_MSTABLE.  This fixes the sound in Amazing Maze (maze) so that it plays for more then 30s.
Fixed filenames in DISCRETE_CSVLOGx and DISCRETE_WAVLOGx making them function again.

Discrete fixes

---

docs/source/usingmame/aboutromsets.rst

Wasn't entirely thrilled with how the merged set sentence was structured, so rather than clean up the grammar I figured it better to try rewriting it.

Reword the entire merged set example to avoid long sentence soup

---

src/mame/drivers/deco32.cpp
src/mame/video/deco32.cpp
src/mame/video/deco_zoomspr.cpp

deco32.cpp : Add notes, Fix background color for dragngun

---

src/mame/drivers/dcheese.cpp
src/mame/includes/dcheese.h
src/mame/video/dcheese.cpp

dcheese.cpp : Correct palette size, Reduce some runtime tag lookups, Cleanup naming etc...

dcheese.cpp Cleanups

---

src/mame/drivers/hng64.cpp
src/mame/includes/hng64.h
src/mame/video/hng64.cpp
src/mame/video/hng64_3d.hxx

mostly notes, rearrange a few bits, change how a few hacks work, enable backface culling because roadedge needs it

hng64 : misc progress (nw)

---

src/devices/sound/zsg2.cpp
src/mame/audio/taito_zm.cpp
src/mame/drivers/taitogn.cpp
src/mame/drivers/zn.cpp

zsg2.cpp: Clamp audio output to 16-bits

taito_zm games: Better default Zoom/SPU balance

---

src/devices/sound/zsg2.cpp

Should sound better at lower amplitudes now (less quantization noise).
I also added some short notes about the emphasis filter.
Adjusted the emphasis filter cutoff to sound closer to hardware recordings (forgot to mention in commit message).
I still want to fix the popping noises in raycris song #12 so added a
note about that as well. (couldn't figure out the cause now)

zsg2.cpp: Optimized the filters a little bit

---

src/devices/sound/zsg2.cpp

zsg2.cpp: Remove misleading comment [nw]
zsg2.cpp: saturate the emphasis filter output. Right shifting will
cause unwanted noise [nw]
zsg2.cpp: Discharge the output filter slowly when the cutoff is set
to 0. Fixes popping noises in raycris song 12 [nw]

zsg2.cpp: minor improvements [nw]

---

src/mame/drivers/hng64.cpp
src/mame/includes/hng64.h
src/mame/video/hng64_sprite.hxx

document outputs (lamps, coin counters) and use device finder for analog ports

hng64: refactor (nw)

---

src/devices/bus/interpro/sr/edge.cpp
src/devices/bus/interpro/sr/gt.cpp
src/devices/bus/interpro/sr/gt.h
src/devices/bus/interpro/sr/sr.cpp
src/devices/bus/interpro/sr/sr.h
src/devices/bus/interpro/sr/sr_cards.cpp
src/devices/machine/ncr5390.h
src/mame/drivers/interpro.cpp
src/mame/includes/interpro.h

* interpro: removed remaining MCFG and refactored
* gt: major overhaul, support GT+/GTII boards
* ncr5390: added devcb3 support

interpro: cleanup + graphics (nw)

---

scripts/src/sound.lua
scripts/target/mame/arcade.lua
scripts/target/mame/mess.lua
src/devices/sound/huc6230.cpp
src/devices/sound/huc6230.h
src/devices/video/huc6272.cpp
src/devices/video/huc6272.h
src/mame/drivers/pcfx.cpp

huc6272.cpp : Add ADPCM transfer, Add save states
PC-FXGA for PC-9801 C Bus is released in December 1995 in Japan, Correct metadata

Add huc6230 Emulation

---

src/mame/drivers/taotaido.cpp
src/mame/includes/taotaido.h
src/mame/video/taotaido.cpp

taotaido.cpp : Cleanup video functions, Add save states, Reduce runtime tag lookups, shared_ptr for sprite banks

taotaido.cpp : Various cleanups

---

src/mame/drivers/crospang.cpp

In according with F2 System website, Black & White (Heuk Sun Baek Sa) released year is 1997 .
http://www.f2.co.kr/company/ourstory03.php

Correct Heuk Sun Baek Sa year

---

src/devices/bus/hp_dio/hp98543.cpp
src/devices/bus/hp_dio/hp98543.h
src/devices/bus/hp_dio/hp98544.cpp
src/devices/bus/hp_dio/hp98544.h
src/devices/video/topcat.cpp
src/devices/video/topcat.h

- Implement Interrupts
- Add reading of cursor registers
- Implement Pixel Replacement Rules

Topcat fixes

---

hash/fmtowns_cd.xml
hash/fmtowns_flop.xml

fmtowns_cd.xml:
- Branmarker 2 Extra Disc [DamienD / Tokugawa Corporate Forums]
- Super Real Mahjong PII & PIII + [DamienD / Tokugawa Corporate Forums]
- Teito Taisen [r09 / redump.org]
- Teitoku no Ketsudan II [r09 / redump.org]
- The Visitor [DamienD / Tokugawa Corporate Forums]
- Zoku Youjuu Senki - Suna no Mokushiroku [r09 / redump.org]
fmtowns_flop.xml:
- Daisenryaku III '90 Map Collection Vol. 1 [r09]
All of them are working.

FM Towns softlists: add several dumps

---

src/devices/cpu/mips/mips3.cpp

Proper DMULT(U) implementation from git issue #3718 [bryanperris] 
Need to be vetted especially with regards to signed/unsigned types.

mip3: Proper DMULT(U) implementation from git issue #3718 [bryanperris]

---

src/mame/drivers/konamim2.cpp

corrected a few package information, verified on real PCB.

Update documentation for konamim2.cpp

---

src/mame/drivers/legionna.cpp

Denjin Makai is released on February 1, 1994 (from Wikipedia), And Title screen says 1994 copyright.

legionna.cpp : Fix denjinmk year

---

src/mame/drivers/konamigx.cpp

Versus Net Soccer - verified on real PCB
- added Konami custom number for Xilinx FPGA protection chip
- corrected package type for a number of Konami customs

Update documentation on konamigx.cpp

---

src/mame/drivers/galaxian.cpp
src/mame/mame.lst

Defend the Terra Attack on the Red UFO (bootleg, set 2) [Siftware, MASH]
rom: 5049.zip
Romident:
5049.1h = ruhja                 redufob    Defend the Terra Attack on the Red UFO (bootleg)
5049.1k = rukla                 redufob    Defend the Terra Attack on the Red UFO (bootleg)
5049.5              NO MATCH
5049.6  = ru6a                  redufob    Defend the Terra Attack on the Red UFO (bootleg)
5049.6l = 6l.bpr                redufob    Defend the Terra Attack on the Red UFO (bootleg)
5049.7f             NO MATCH
5049.7h             NO MATCH
5049.7k = ru3a                  redufob    Defend the Terra Attack on the Red UFO (bootleg)
5049.7m             NO MATCH
Out of 9 files, 5 matched, 4 did not match.

New working clone

---

src/mame/drivers/armedf.cpp
src/mame/mame.lst

New clones marked as NOT_WORKING
Chouji Meikyuu Legion (Japan ver 1.05, bootleg set 2)
[Tomas Garcia-Meras (ClawGrip), Roberto Fresca, Recreativas.org, The Dumping Union]

New NOT WORKING clone

---

src/mame/drivers/yunsun16.cpp
src/mame/includes/yunsun16.h
src/mame/video/yunsun16.cpp

Cleanup duplicates, Reduce runtime tag lookups, Reduce unused, Fix notes, Cleanup tilemap scanning

yunsun16.cpp : Cleanups

---

src/mame/drivers/sshangha.cpp
src/mame/includes/sshangha.h
src/mame/video/sshangha.cpp

helps with the issues listed in MT6020 ( https://mametesters.org/view.php?id=6020 )

improve sshangha mixing and palette handling

---

src/mame/drivers/sshangha.cpp

Reference : https://www.youtube.com/watch?v=buCb-exoJWo

sshangha.cpp : Fix OKI clock/pin7

---

src/mame/drivers/galaxian.cpp
src/mame/mame.lst

I'm adding this as NON WORKING just to save some time to whoever wants to work on it.
Frogger (Video Dens, Spanish bootleg on Scramble hardware) [Tomas Garcia-Meras (ClawGrip), Roberto Fresca, Recreativas.org, The Dumping Union]

New NOT_WORKING clone

---

src/mame/drivers/nmg5.cpp

nmg5.cpp : copybitmap_trans for bitmap layer, Cleanup duplicates/ACCESSING_BITs

nmg5.cpp : Various cleanups

---

src/mame/drivers/wecleman.cpp

update info for WEC Le Mans 24 based on PCB pictures

wecleman.cpp update info for WEC Le Mans 24 based on PCB pictures

---

src/mame/drivers/neogeo.cpp
src/mame/drivers/neogeocd.cpp
src/mame/drivers/neopcb.cpp
src/mame/includes/neogeo.h
src/mame/video/neogeo.cpp
src/mame/video/neogeo_spr.cpp

neogeo.cpp : Remove some MCFGs
neogeocd.cpp : Cleanup regions/naming
neogeo_spr.cpp : Fix crash when fix bios is not exists

neogeo.cpp, neopcb.cpp : Eliminate register_postload, Cleanup naming

---

src/mame/drivers/ms32.cpp

The correct name for f1superb is "F-1 Super Battle" according to manual and to game title screen.

correct name for f1superb

---

src/mame/drivers/video21.cpp
src/mame/layout/video21.lay

(game doesn't let you know what to do onscreen, only with the lamps, it's still vague without a 'deal' lamp, but at least somewhat playable now and I suspect this is how the machine was)

added crude lamp layout to "Video 21" so that it is actually worthy of the 'Working' tag

---

src/devices/sound/iremga20.cpp

This pull request rewrites the sound update routine in order to
- clean up the code (for-loop instead of manually inlining update code for each channel)
- use value 0 as sample terminator, because that is apparently what was intended  
The current code plays from (start) to (end - 0x20) and the magic 0x20 just makes no sense.
I checked all currently supported GA20 sample ROMs to make sure that the change doesn't break anything.

Irem GA20: rewrite sound update

---

src/mame/drivers/twinkle.cpp

I went through all of my kits and updated the table at the top of twinkle.cpp with information off of each of them. I unmarked the undumped variants as DU says its all dumped (I have dumps of them all as well if needed, unsure how people might want them). Also updated documentation in todo section for how to get 1st style to pass DVD checks.

Update Twinkle docs to match data gleaned from kits.

---

src/mame/drivers/cps3.cpp
src/mame/drivers/wecleman.cpp
src/mame/includes/cps3.h

(move some variable definitions to where they're used etc., fix last line of cliprect in new rowscroll code, divide fg draw into a function)
This addresses a small issue Tafoid pointed out to me.

cps3 - light cleanups

---

src/mame/drivers/itgamble.cpp

Update itgamble.cpp with:
-consistent hardware info
-evolution of hardware over time
-confirmed producer and year for a few games that were missing it.

Update itgamble.cpp info

---

src/mame/layout/coco3.lay

Work around to change default to show one screen on the coco3 driver.

---

hash/ibm5170.xml

These are some new dumps made from my own disks.

Ibm5170.xml - Add new dumps

---

src/devices/bus/hp_dio/hp98543.cpp
src/devices/bus/hp_dio/hp98543.h
src/devices/bus/hp_dio/hp98544.cpp
src/devices/bus/hp_dio/hp98544.h
src/devices/bus/hp_dio/hp98603a.cpp
src/devices/bus/hp_dio/hp98603a.h
src/devices/bus/hp_dio/hp98603b.cpp
src/devices/bus/hp_dio/hp98603b.h
src/devices/bus/hp_dio/hp98644.cpp
src/devices/bus/hp_dio/hp98644.h
src/devices/bus/hp_dio/hp_dio.cpp
src/devices/bus/hp_dio/hp_dio.h

This is the first commit of a series of hp_dio modernization. I want to open PR's for every single one, so i get some feedback whether my changes make sense. I'll open the next one after this one is merged.

hp_dio: add namespace (nw)

---

src/mame/drivers/segas24.cpp
src/mame/includes/segas24.h
src/mame/video/segas24.cpp

Cleanup duplicates, ACCESSING_BITS, Namings
Reduce some MCFGs
Split machine config/address map related to ROM board

segas24.cpp : Cleanups, Add save states

---

src/mame/drivers/glass.cpp
src/mame/includes/glass.h
src/mame/video/glass.cpp

glass.cpp : Remove unnecessary value, Cleanup duplicates, Gfxdecode, Fix Naming, Reduce runtime tag lookups

glass.cpp Minor cleanups

---

src/devices/sound/vrender0.cpp
src/devices/sound/vrender0.h
src/mame/drivers/crystal.cpp
src/mame/video/vrender0.cpp

Cleanup duplicates, Naming, some ACCESSING_BITS, Add notes, Use private:, Remove MCFGs, Update and Add information for CRTC operation, Configured bankswitched area, Reduce unnecessary ROM regions
sound/vrender0.cpp : Fix naming, Remove MCFGs, Add notes, Remove unused
video/vrender0.cpp : Fix device name

crystal.cpp : Cleanups / Updates

---

scripts/target/mame/mess.lua
src/devices/cpu/m6502/oxavix.lst
src/devices/cpu/m6502/xavix.h
src/mame/audio/xavix.cpp
src/mame/drivers/xavix.cpp
src/mame/includes/xavix.h
src/mame/machine/xavix.cpp
src/mame/video/xavix.cpp

not ready for merging yet, plan on doing a bit more to this first, but want to keep it open so I don't forget about it like I did last time.
this is based on debug strings left in the code etc.

XaviX naming changes

---

src/mame/drivers/toypop.cpp

toypop: Fixed the "Flip Screen" dipswitch is reversed.

---

hash/hp9k3xx_flop.xml

I uploaded the files to http://stackframe.org/pascal325.tar.bz2

hp9k_3xx: add Pascal 3.25 to Software list (nw)

---

src/devices/cpu/m6502/oxavix.lst
src/mame/video/xavix.cpp

now that elsewhere works better, allows namcons2 to boot, rad_ping to get past the first screen without crashing etc.

XaviX - simplify some things with the CPU core changes..

---

scripts/src/bus.lua
src/devices/bus/hp_dio/human_interface.cpp
src/devices/bus/hp_hil/hil_devices.cpp
src/devices/bus/hp_hil/hlebase.cpp
src/devices/bus/hp_hil/hlebase.h
src/devices/bus/hp_hil/hlekbd.cpp
src/devices/bus/hp_hil/hlekbd.h
src/devices/bus/hp_hil/hlemouse.cpp
src/devices/bus/hp_hil/hlemouse.h
src/mame/drivers/hp_ipc.cpp

- move hle_device_base to it's own files
- add hlemouse.{cpp,h}
- add mouse device to hp_ipc and hp9k_3xx

hp_hil: add HP 46060B mouse

---

src/mame/drivers/twins.cpp
src/mame/mame.lst

Twins [David Torres, ClawGrip, Recreativas.org]
It seems that the set from Ecogames is the older and original version, and that Electronic Devices later licensed it.
There are also some other ED licensed games from Ecogames: http://www.tilt.it/deb/edevg-en.html
The games shows 1993, and the PCB is also marked with "191193"

New WORKING clone 

---

hash/x68k_flop.xml

Many added (and fix) to alt(japanese) title.
Many added (and fix) to release date. and same fix to year.
Rename publisher "システムハウスオウ" -> "システムハウスオー"
- flappy2, lagoondo, lodoss2, quenduel, rouge, xevious, zark
rename title
- 177
This game was unofficial transplantation.
Move to doujin category.
Correct release year.
- abuten
This title was "Abunai Bunkasai Zenya (あぶない文化祭前夜)"
rename abuten -> abunabun
"abunai tengoku densetsu (1989)(alice soft).dim" -> "abunai bunkasai zenya (1992)(alice soft).dim"
Move from doujin category.
- animjv3
This set was 4 disks right. ("3 disk" is wrong info.)
- daikaint
This set was limited edition, fix note.
Change release year and title.
- dios
This user disk (diosuserdisk.dim) is created in the game.
(That weren't actually provided with software.)
Should …

x68k_flop: many added info and fix data (except Doujin)

---

src/mame/drivers/hh_sm510.cpp
src/mame/mame.lst

-----------
Donkey Kong (Nintendo Game & Watch) [algestam]

New working machine added

---

src/mame/drivers/targeth.cpp
src/mame/includes/targeth.h
src/mame/video/targeth.cpp

targeth.cpp : Cleanup duplicates, ACCESSING_BITs, naming, Runtime tag lookup

targeth.cpp : Minor cleanups

---

src/mame/machine/xavix.cpp
src/mame/video/xavix.cpp

some xavix visible area register tweaks based on studying video evidence (nw)

---

src/devices/video/ramdac.h
src/mame/drivers/adp.cpp
src/mame/drivers/bfcobra.cpp
src/mame/drivers/blitz68k.cpp
src/mame/drivers/bmcbowl.cpp
src/mame/drivers/bmcpokr.cpp
src/mame/drivers/chsuper.cpp
src/mame/drivers/clpoker.cpp
src/mame/drivers/coinmvga.cpp
src/mame/drivers/dunhuang.cpp
src/mame/drivers/gkigt.cpp
src/mame/drivers/highvdeo.cpp
src/mame/drivers/koftball.cpp
src/mame/drivers/lastfght.cpp
src/mame/drivers/magicard.cpp
src/mame/drivers/mediagx.cpp
src/mame/drivers/nibble.cpp
src/mame/drivers/pinball2k.cpp
src/mame/drivers/rltennis.cpp
src/mame/drivers/segajw.cpp
src/mame/drivers/sfbonus.cpp
src/mame/drivers/skylncr.cpp
src/mame/drivers/sliver.cpp
src/mame/drivers/subsino.cpp
src/mame/drivers/subsino2.cpp
src/mame/drivers/tr175.cpp
src/mame/drivers/twins.cpp
src/mame/drivers/wheelfir.cpp
src/mame/drivers/wildpkr.cpp
src/mame/machine/inder_vid.cpp

blitz68k.cpp : Reduce duplicates, Use private:

ramdac.cpp : Remove MCFGs

---

src/mame/drivers/itgamble.cpp

Added more complete hardware info

Update hardware info

---

src/devices/sound/qsoundhle.cpp

fixes clipping in spf2t (MT 07115), and possibly others.
The DSP16A accumulator has built in saturation.

qsoundhle: saturate voice and output accumulators

---

src/devices/cpu/m68000/m68kmmu.h

and initialize m_mmu_tmp_sr before doing a table search. With this commit,
everything required to run HP-UX 9 in mame is upstream.
Tested the following machines with this mmu change:
maciix with Mac OS 7
hp9k360 with HP-UX 7, HP-UX 9 and the HP-UX 9 installer.

m68kmmu: don't try to read address bits in indirect descriptors as status bits (nw)

---

src/mame/drivers/cps1.cpp
src/mame/drivers/fcrash.cpp
src/mame/includes/cps1.h
src/mame/mame.lst
src/mame/video/cps1.cpp

Move to fcrash.cpp, hook up scroll registers and other misc bits

Promote mtwinsb to working

---

src/mame/drivers/onetwo.cpp

onetwo.cpp : PALETTE_DECODER for color decoding
